(function() {
var _1th_ch_1_Verses = [
  {num:1,words:[["O", "O"], ["i mātou ,", "us"], ["o Paulo,", "Paul"], ["ma Siluano,", "and Siluano"], ["ma Timoteo", "and Timothy"], ["o lā mātou tusi lenei", "our book this"], ["i le ekalesia", "in the church"], ["o tagata o Tesalonia,", "men Tesalonia"], ["o", "o"], ["i le Atua", "in the God"], ["le Tamā,", "the father"], ["ma le Ali'i", "and the Lord"], ["o Iesu Keriso.", "Jesus Christ"], ["Ia ia te outou", "to him you all"], ["le alofa tunoa,", "grace"], ["ma le manuia", "and peace"], ["mai le Atua lo tātou Tamā", "from God our Father"], ["atoa ma le Ali'i", "and the Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
  {num:2,words:[["Mātou te fa'afetai pea", "we thank continually"], ["lava", "very"], ["i le Atua,", "in the God"], ["ona o outou uma lava,", "because of all of you"], ["o loo ta'uta'ua outou", "is was to hang up you all"], ["i", "in"], ["a mātou tatalo,", "our pray"]]},
  {num:3,words:[["e le aunoa", "shall not without"], ["ona mātou mānatua lā outou galuega", "and we remember your work"], ["i le fa'atuatua,", "in the faith"], ["ma le fa'amalosi", "and the be strong"], ["i le alofa,", "in the love"], ["ma le tumau pea", "and the enduring continually"], ["i le fa'amoemoe", "in the hope"], ["i lo tātou Ali'i", "than we Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["i luma", "in before"], ["o le Atua", "of God"], ["o lo tātou Tamā lea;", "our father"]]},
  {num:4,words:[["ina ua mātou", "when we"], ["iloa", "know"], ["le filifilia o outou,", "the chosen of you all"], ["le ʻau uso e,", "brethren"], ["o ē ua alofagia", "who favored"], ["e le Atua.", "God"]]},
  {num:5,words:[["Auā", "do not"], ["e lei oo atu lā mātou tala lelei", "by not arrived our gospel"], ["ia te outou", "unto you all"], ["na", "na"], ["o le 'upu,", "the word"], ["a", "but"], ["o le mana,", "the get"], ["ma le Agaga Paia,", "and the Holy Spirit"], ["atoa ma le mautinoa", "and the surely"], ["lava", "very"], ["ina ua outou", "when you all"], ["iloa lā mātou amio", "know our deeds"], ["ona o outou,", "because of you all"], ["a o mātou", "but we"], ["i ai", "therein"], ["ma outou;", "with you"]]},
  {num:6,words:[["sa outou fa'aa'oa'o mai foi", "you all made teacher from also"], ["ia te i mātou,", "unto us"], ["atoa ma le Ali'i,", "and the Lord"], ["ina ua outou", "when you all"], ["talia", "received"], ["le 'upu", "the word"], ["i le puapuaga tele,", "in the affliction great"], ["ma le olioli", "and the joy"], ["mai le Agaga Paia;", "from the Holy Spirit"]]},
  {num:7,words:[["o lea", "therefore"], ["ua avea ai", "became"], ["outou", "you all"], ["ma fa'aa'oa'o", "and make teacher"], ["i", "in"], ["e ua fa'atuatua uma lava", "faith all very"], ["o", "o"], ["i Maketonia", "in Maketonia"], ["atoa ma Akaia;", "and Achaia"]]},
  {num:8,words:[["auā", "for"], ["ua logo atu nai ia te outou", "heard from unto you all"], ["le afioga", "the word"], ["a le Ali'i,", "if not Lord"], ["e le gata", "shall not a snake"], ["i Maketonia", "in Maketonia"], ["ma Akaia,", "and Achaia"], ["a", "but"], ["ua salalau atu foi", "was scattered also"], ["i mea uma lava", "things all very"], ["le tala", "the side"], ["i lo", "than"], ["outou fa'atuatua", "you all faith"], ["i le Atua", "in the God"], ["o lea", "therefore"], ["e le aoga ai", "shall not useful"], ["sa mātou 'upu", "we word"], ["e fai atu ai.", "said to"]]},
  {num:9,words:[["Auā o", "do not of"], ["i lātou lava", "them very"], ["ua iloa ai", "knew"], ["le tala ia te", "the side unto"], ["i mātou", "us"], ["i le uiga", "in the meaning"], ["o lo mātou oo atu", "our arrived"], ["ia te outou", "unto you all"], ["na,", "na,"], ["ma lo outou liliu", "and all the you turn"], ["mai", "from"], ["i le Atua", "in the God"], ["nai tupua,", "from pillar"], ["ina ia outou", "so that you all"], ["auauna", "servant"], ["i le Atua soifua", "in the God life"], ["ma le", "and the"], ["ua moni,", "true"]]},
  {num:10,words:[["ma ia fa'atali atu", "and he wait"], ["i lona Alo", "concerning his Son"], ["mai le lagi,", "from the heaven"], ["o le", "the"], ["na toe fa'atuina mai", "again built from"], ["e ia", "he"], ["nai", "from"], ["e ua oti,", "the dead"], ["o Iesu lea,", "Jesus"], ["o lē laveai", "not delivered"], ["mai ia", "from he"], ["i tātou ai", "us"], ["le toasa atali.", "the wrath atali"]]},
  {num:11,words:[["O lea", "therefore"], ["ia outou feapoapoai ai,", "he you all exhort one another"], ["ma ia fefaamafanafanai,", "and he comfort one another"], ["fa'apei", "like"], ["ona outou faia", "and you all do"], ["lava.", "very"]]},
  {num:12,words:[["Mātou te aїoї atu foi", "we aїoї also"], ["ia te outou,", "unto you all"], ["le ʻau uso e,", "brethren"], ["ia outou iloa", "he you all know"], ["e o galulue", "by of labour"], ["ia te outou,", "unto you all"], ["ma pule ia te outou", "and rule unto you all"], ["i lā le Ali'i,", "in the Lord"], ["ma lātou apoapoai atu", "and they exhort"], ["ia te outou;", "unto you all"], ["13 ia matuá mánatua", "13 he matuá mánatua"], ["i lātou", "them"], ["ma le alofa,", "and the love"], ["ona", "and"], ["o lā lātou galuega.", "their work"], ["lā outou nonofo fefilemuai.", "your dwelling be at peace with one another"]]},
];
renderVerseSet(_1th_ch_1_Verses, '1th-ch1-verses');

var _1th_ch_2_Verses = [
  {num:1,words:[["Auā o outou", "do not of you all"], ["lava,", "very"], ["le ʻau uso e,", "brethren"], ["ua outou iloa", "you all knew"], ["o lo mātou oo atu", "our arrived"], ["ia te outou,", "unto you all"], ["e lei fa'aleaogaina lea;", "by not made void"]]},
  {num:2,words:[["a", "but"], ["e ui lava", "although very"], ["ina muamua", "so that first"], ["ona tigaina o", "and afflicted of"], ["i mātou,", "us"], ["ma fa'aleagaina", "and destroyed"], ["i Filipi,", "in Filipi"], ["pei ona", "as/just as"], ["outou iloa", "you all know"], ["ua mātou fa'amalosi", "we was strong"], ["ona", "and"], ["o lo tātou Atua e", "our God"], ["tautala atu ia te outou", "speak toward unto you all"], ["i le tala lelei", "in the gospel"], ["a le Atua", "of God"], ["ma le finafinau tele", "and the finafinau great"], ["lava.", "very"]]},
  {num:3,words:[["Auā", "do not"], ["o lo mātou apoapoai atu", "our exhort"], ["ia te outou", "unto you all"], ["e lei faia lea", "by not do"], ["ma le sese,", "and the wrong"], ["po", "night"], ["o le amio leaga,", "the iniquity"], ["po", "night"], ["o le fa'a'ole'ole.", "the treacherous"]]},
  {num:4,words:[["A", "but"], ["e peitai,", "however"], ["fa'apei", "like"], ["ona tatau", "and ought"], ["i le finagalo", "in the will"], ["o le Atua", "of God"], ["na te tuuina mai ia te", "he given from"], ["i mātou", "us"], ["le tala lelei,", "the gospel"], ["e fa'apea foi", "so it is also"], ["ona mātou tautala atu ai;", "and we speak toward"], ["e le", "by the"], ["ina ia fiafia", "so that pleased"], ["mai tagata,", "from man"], ["a", "but"], ["o le Atua,", "of God"], ["o lē tofotofo", "not try"], ["mai", "from"], ["i o mātou", "in of we"], ["loto.", "heart"]]},
  {num:5,words:[["Auā mātou te lei fai", "do not we not do"], ["lava", "very"], ["se 'upu", "a word"], ["e fa'aviivii atu ai,", "make to praise"], ["fa'apei", "like"], ["ona outou iloa,", "and you all know"], ["pe faia", "whether do"], ["se ufiufi", "a covering"], ["o le manumanu;", "the animal"], ["ua silafia", "knew"], ["e le Atua;", "God"]]},
  {num:6,words:[["e ui lava", "although very"], ["ina mafai ia te", "so that able unto"], ["i mātou", "us"], ["ona ia mafatia ai", "and he afflicted"], ["outou,", "you all"], ["auā o aposetolo", "for apostle"], ["i mātou", "us"], ["a Keriso,", "of Christ"], ["a e mātou", "but by us"], ["le saili", "not seek"], ["le viiga mai tagata,", "the praise from man"], ["po o outou", "night of you all"], ["po o isi tagata.", "night of other man"]]},
  {num:7,words:[["A", "but"], ["ua mātou agamalu", "we meek"], ["ina ua mātou", "when we"], ["i ai", "therein"], ["ia te outou", "unto you all"], ["na,", "na,"], ["fa'apei", "like"], ["o se failele", "a nursing"], ["na te tausi", "he nurse"], ["lelei", "good"], ["i ana lava tama;", "in cave very child"]]},
  {num:8,words:[["sa fa'apea lava", "saying very"], ["lo mātou maelega", "our earnest"], ["i le alofa", "in the love"], ["ia te outou,", "unto you all"], ["na mātou manao", "we desired"], ["i le fia avatu", "in the want to do something give away"], ["ia te outou", "unto you all"], ["e le", "by the"], ["na", "na"], ["o le tala lelei", "the gospel"], ["i le Atua,", "in the God"], ["a o mātou", "but we"], ["lava ola foi,", "very life also"], ["auā", "for"], ["na alofaina outou", "beloved you all"], ["e", "by"], ["i mātou.", "us"]]},
  {num:9,words:[["Auā", "do not"], ["le ʻau uso e,", "brethren"], ["ua outou mānatua", "you all remembered"], ["lā mātou galuega mamafa", "our work heavy"], ["ma le tiga;", "and the grieved"], ["auā", "for"], ["sa mātou galulue ai", "we labour"], ["i le po", "at night"], ["atoa ma le ao,", "and the day"], ["ina ne'i mafatia so outou,", "so that now afflicted so you all"], ["na mātou tala'i atu ai", "we preached"], ["ia te outou", "unto you all"], ["le tala lelei", "the gospel"], ["a le Atua.", "of God"]]},
  {num:10,words:[["Ua iloa outou", "knew you all"], ["atoa ma le Atua,", "and God"], ["sa mātou amio", "we deeds"], ["Atua,", "God"], ["ma amiotonu,", "and righteous"], ["ma le", "and the"], ["le mata'uleagaina,", "the mata'uleagaina"], ["ina o mātou", "so that of we"], ["i ai", "therein"], ["ia te outou", "unto you all"], ["o ē fa'atuatua.", "whose faith"]]},
  {num:11,words:[["Pei ona", "as/just as"], ["outou iloa,", "you all know"], ["sa mātou", "we"], ["i ai", "therein"], ["ia te outou", "unto you all"], ["taitasi,", "each"], ["pei o le tamā", "like the father"], ["i lana lava fānau,", "in his very born"], ["na mātou apoapoai atu ia te outou,", "we exhort unto you all"], ["o fa'amafanafana atu foi,", "hearten also"], ["ma ta'utino atu,", "and testify"]]},
  {num:12,words:[["ina ia outou", "so that you all"], ["savavali ia tatau", "walked he ought"], ["i le Atua,", "in the God"], ["o le", "the"], ["na valaauina outou", "called you all"], ["i lona mālō", "in his kingdom"], ["ma lona manuia.", "and his prosper"]]},
  {num:13,words:[["O le mea lea", "therefore"], ["mātou te fa'afetai ai", "we thank"], ["i le Atua,", "in the God"], ["o", "o"], ["i mātou lava", "us very"], ["e le aunoa,", "shall not without"], ["auā", "for"], ["na talia e outou", "received by you all"], ["le afioga", "the word"], ["a le Atua", "of God"], ["na outou fa'alogo mai ai", "you all hearken from"], ["ia", "he"], ["i mātou,", "us"], ["ua", "ua"], ["le talia e outou", "not received by you all"], ["o le 'upu", "the word"], ["a tagata,", "but man"], ["a", "but"], ["e peitai", "however"], ["o le 'upu", "the word"], ["a le Atua,", "of God"], ["(e moni lava lea,)", "verily I say"], ["ua matuā galue foi", "exceedingly till also"], ["i totonu ia te outou", "in inside unto you all"], ["o ē fa'atuatua.", "whose faith"]]},
  {num:14,words:[["Auā", "do not"], ["le ʻau uso e,", "brethren"], ["na outou fa'aa'oa'o", "you all made teacher"], ["i ekalesia", "in church"], ["a le Atua", "of God"], ["o", "o"], ["i Iutaia,", "in Judea"], ["o loo ia", "is he"], ["Keriso Iesu;", "Christ Jesus"], ["auā o outou", "for you all"], ["foi", "also"], ["na tigaina outou", "afflicted you all"], ["i ia lava mea", "in he very thing"], ["i tagata", "in man"], ["o lo outou", "your"], ["lava nuu,", "very nation"], ["fa'apei", "like"], ["ona tigaina o", "and afflicted of"], ["i lātou foi", "them also"], ["ia Iutaia;", "he Judea"]]},
  {num:15,words:[["o ē na fasioti", "who killed"], ["i le Ali'i,", "in the Lord"], ["o Iesu lava,", "Jesus very"], ["atoa ma", "and"], ["a lātou lava perofeta,", "their very prophet"], ["na fa'asaua mai foi", "cruel from also"], ["i lātou ia", "them he"], ["i mātou;", "us"], ["e le fiafia", "shall not pleased"], ["i ai", "therein"], ["le Atua,", "God"], ["ua fai foi", "did also"], ["tagata uma lava", "man all very"], ["mo lātou fili;", "for they enemy"]]},
  {num:16,words:[["ua vavao mai ia", "forbade from he"], ["i mātou,", "us"], ["aua mātou te tautala atu", "for we speak toward"], ["i nuu ese,", "in nation away"], ["ina ia fa'aolaina ai", "so that saved"], ["i lātou;", "them"], ["ua fa'aatoa ai", "made together with"], ["e", "by"], ["i lātou", "them"], ["e le aunoa", "shall not without"], ["a lātou agasala;", "their sin"], ["a", "but"], ["ua oo ia te", "it came to pass unto"], ["i lātou", "them"], ["le toasa", "the wrath"], ["e fa'aumatia ai.", "destroyed"]]},
  {num:17,words:[["O", "O"], ["i mātou foi,", "us also"], ["le ʻau uso e,", "brethren"], ["o loo tete'aeseina", "is tete'aeseina"], ["o", "o"], ["i mātou", "us"], ["ma outou", "with you"], ["i ni", "in some"], ["nai aso itiiti,", "from day small"], ["i le tino", "in the body"], ["a", "but"], ["e le", "by the"], ["o le loto,", "the heart"], ["ua atili ai", "more"], ["ona mātou taumafaia", "and we was plenty"], ["ma le naunau tele", "and the desire great"], ["ona ia tātou", "and he we"], ["feiloai", "meet one another"], ["ma outou.", "with you"]]},
  {num:18,words:[["O lea", "therefore"], ["na mātou fia", "we wanted to do something"], ["o atu ai", "went"], ["ia te outou,", "unto you all"], ["o aʻu lava", "I am very"], ["o Paulo,", "Paul"], ["ua atu tasi", "one"], ["ma atu lua,", "and two"], ["a", "but"], ["ua fa'alavelave mai", "a hindrance from"], ["Satani ia te", "Satan unto"], ["i mātou.", "us"]]},
  {num:19,words:[["Auā", "do not"], ["se a ea so mātou", "what indeed? / why? so we"], ["fa'amoemoe,", "hope"], ["ma se fiafia,", "and a pleased"], ["ma se pale", "and a row"], ["e mitamita ai?", "boast"], ["E le o outou", "by the of you all"], ["i luma", "in before"], ["o lo tātou Ali'i", "our Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["i lona afio mai?", "in his dwell from"]]},
  {num:20,words:[["Auā o outou", "do not of you all"], ["lava", "very"], ["o lo mātou viiga", "our praise"], ["ma lo mātou olioli.", "and the we joy"]]},
];
renderVerseSet(_1th_ch_2_Verses, '1th-ch2-verses');

var _1th_ch_3_Verses = [
  {num:1,words:[["O lea", "therefore"], ["ua lelei ai", "that it was good"], ["ia te i mātou", "unto us"], ["ona ia tuua ai", "and he left"], ["i mātou", "us"], ["i Atenai,", "in Atenai"], ["tau o", "fight of"], ["i mātou,", "us"], ["ina ua mātou", "when we"], ["le toe mafai ona", "the again able to"], ["onosai;", "patience"]]},
  {num:2,words:[["a", "but"], ["ua mātou auina atu", "we sent"], ["Timoteo lo mātou uso,", "Timothy our brother"], ["o le auauna foi", "the servant also"], ["o ia", "it/he/she"], ["a le Atua,", "of God"], ["o lē galue fa'atasi ma", "not till together and"], ["i mātou", "us"], ["i le tala lelei", "in the gospel"], ["ia Keriso,", "he Christ"], ["ina ia fa'atumauina outou", "so that established you all"], ["e ia,", "he"], ["ma ia fa'amafanafana atu", "and he hearten"], ["ia te outou", "unto you all"], ["i lo", "than"], ["outou fa'atuatua;", "you all faith"]]},
  {num:3,words:[["ina ne'i fa'agaeetia", "so that now faagaeetia"], ["se tasi", "a one"], ["i nei puapuaga;", "in these affliction"], ["auā", "for"], ["ua outou iloa", "you all knew"], ["ua tofia lenei", "was chosen this"], ["lava mea.", "very thing"]]},
  {num:4,words:[["Auā foi", "do not also"], ["o", "o"], ["ona po", "and night"], ["sa", "sa"], ["i ai", "therein"], ["i mātou ia te outou,", "us unto you all"], ["na mātou muai", "we first"], ["fai atu ai", "said to"], ["ia te outou,", "unto you all"], ["o le a oo mai le puapuaga,", "what came the affliction"], ["ua fa'apea ona", "saying and"], ["taunuu lava,", "fulfilled very"], ["ua outou iloa foi.", "you all knew also"]]},
  {num:5,words:[["O le mea lea", "therefore"], ["na ou", "I"], ["le toe mafai ai", "the again able"], ["ona onosai,", "and patience"], ["ona auina atu lea", "and sent"], ["e aʻu,", "me"], ["ina ia ou iloa lo outou fa'atuatua,", "so that I know your faith"], ["ne'i fa'aosoosoina outou", "now make sit you all"], ["e lē fa'aosooso,", "by not make sit"], ["ona fa'aleaogaina ai lea", "and made void then"], ["o lā mātou galuega.", "our work"]]},
  {num:6,words:[["A o lenei,", "but now"], ["ua sau Timoteo ia te", "came Timothy unto"], ["i mātou", "us"], ["nai ia te outou,", "from unto you all"], ["ua aʻu mai foi", "brought also"], ["le tala lelei", "the gospel"], ["ia te i mātou", "unto us"], ["i lo", "than"], ["outou fa'atuatua,", "you all faith"], ["ma lo outou alofa,", "and all the you love"], ["ma lo outou manatu lelei", "and all the you thought good"], ["mai", "from"], ["e le aunoa", "shall not without"], ["ia te i mātou,", "unto us"], ["o loo fa'anaunau foi", "is make desire also"], ["outou", "you all"], ["ina ia tātou", "so that we"], ["feiloai", "meet one another"], ["ma outou,", "with you"], ["pei o", "like of"], ["i mātou", "us"], ["ona fia feiloai", "and want to do something meet one another"], ["ma outou;", "with you"]]},
  {num:7,words:[["o le mea lea,", "therefore"], ["le ʻau uso e,", "brethren"], ["na fa'amafanafanaina mai ai", "comforted from"], ["i mātou", "us"], ["ona o outou,", "because of you all"], ["i lo mātou puapuaga uma lava,", "than we affliction all very"], ["atoa ma lo mātou tiga,", "and our grieved"], ["ona", "and"], ["o lo outou fa'atuatua.", "your faith"]]},
  {num:8,words:[["Auā o lenei,", "do not now"], ["ua mātou ola,", "we life"], ["pe afai tou te tumau", "whether if second person plural enduring"], ["i le Ali'i.", "in the Lord"]]},
  {num:9,words:[["Se a foi", "a but also"], ["se fa'afetai mātou", "a thank we"], ["te mafaia", "able"], ["ona tuuina atu", "and given / delivered"], ["i le Atua", "in the God"], ["ona o outou,", "because of you all"], ["auā", "for"], ["o le olioli uma lava mātou", "all the joy very we"], ["te olioli ai", "joy"], ["i luma", "in before"], ["o lo tātou Atua?", "our God"]]},
  {num:10,words:[["o loo mātou", "is we"], ["matuā ole atu ai", "exceedingly entreat"], ["i le po", "at night"], ["atoa ma le ao,", "and the day"], ["ina ia tātou", "so that we"], ["feiloai", "meet one another"], ["ma outou,", "with you"], ["e fa'aatoatoaina ai", "complete"], ["mea", "thing"], ["e lei", "by not"], ["atoa", "together with"], ["i lo", "than"], ["outou fa'atuatua.", "you all faith"]]},
  {num:11,words:[["A ia ta'ita'iina lā mātou malaga", "his led our travelling party"], ["ia te outou", "unto you all"], ["e le Atua", "God"], ["lava,", "very"], ["lo tātou Tamā,", "our Father"], ["atoa ma lo tātou Ali'i", "and our Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
  {num:12,words:[["Ia fa'atele foi", "he make great also"], ["e le Ali'i,", "by the Lord"], ["ma ia fa'asilisili", "and he make very much"], ["ona tele", "and great"], ["o lo outou alofa,", "your love"], ["o le tasi", "the one"], ["i le tasi,", "in the one"], ["atoa ma tagata uma,", "and man all"], ["fa'apei o", "like of"], ["i mātou nei", "us these"], ["lava ia te outou;", "very unto you all"]]},
  {num:13,words:[["ina ia fa'atumauina", "so that established"], ["o outou loto", "you all heart"], ["e le mata'uleagaina", "by the mata'uleagaina"], ["i le amio lelei", "in the deeds good"], ["i luma", "in before"], ["o le Atua lo lātou Tamā,", "of God their father"], ["pe a afio mai lo tātou Ali'i", "even though / although dwell from our Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["fa'atasi ma", "together and"], ["ona aʻu paia uma.", "and saints all"]]},
];
renderVerseSet(_1th_ch_3_Verses, '1th-ch3-verses');

var _1th_ch_4_Verses = [
  {num:1,words:[["O lenei,", "now"], ["le ʻau uso e,", "brethren"], ["o le toe 'upu lenei,", "the again word this"], ["mātou te aioi atu", "we cry out"], ["ma apoapoai atu", "and exhort"], ["ia te outou", "unto you all"], ["ona", "and"], ["o le Ali'i", "the Lord"], ["o Iesu,", "Jesus"], ["fa'apei", "like"], ["ona talai e outou", "and preach by you all"], ["mai ia te", "from"], ["i mātou", "us"], ["le uiga", "the meaning"], ["o le ala", "the way"], ["e tatau ona", "should"], ["outou savavali ai,", "you all walked"], ["ia fiafia mai ai", "he pleased from"], ["le Atua ia te outou,", "God unto you all"], ["ia fa'asilisili pea i ai", "he make very much continually therein"], ["outou.", "you all"]]},
  {num:2,words:[["Auā", "do not"], ["ua outou iloa ia", "you all knew he"], ["poloaiga", "commandment"], ["na mātou tuuina atu ai", "we given / delivered"], ["ia te outou", "unto you all"], ["mai le Ali'i", "from the Lord"], ["o Iesu.", "Jesus"]]},
  {num:3,words:[["O le finagalo foi", "the will also"], ["lenei", "this"], ["o le Atua,", "of God"], ["ia fa'apaiaina outou,", "he consecrated you all"], ["ina ia fa'amamao outou", "so that make far you all"], ["ma le faitaaga;", "and the fornication"]]},
  {num:4,words:[["ia taitasi outou", "he each you all"], ["ma iloa", "and know"], ["ona fai", "and do"], ["o lana lava ipu", "his very cup"], ["ma le fa'apaiaina", "and the consecrated"], ["ma le ta'uleleia,", "and the ta'uleleia"]]},
  {num:5,words:[["aua", "for"], ["ma le tu'inanau", "and the tu'inanau"], ["o le manao,", "the desire"], ["fa'apei o nuu ese", "like of nation away"], ["ua", "ua"], ["le iloa", "not know"], ["le Atua.", "God"]]},
  {num:6,words:[["Aua ne'i sopo tapulaa", "do not now step over tapulaa"], ["se tasi,", "a one"], ["ma agaleaga", "and unkind"], ["i lona uso", "in his brother"], ["i lenei", "in this"], ["mea;", "thing"], ["auā", "for"], ["o le Ali'i", "the Lord"], ["na te taui atu", "he a reward"], ["ma sui", "and replace"], ["i nei mea uma,", "these things all"], ["fa'apei", "like"], ["ona mātou muai fai atu ai,", "and we first said to"], ["ma ta'utino atu", "and testify"], ["ia te outou.", "unto you all"]]},
  {num:7,words:[["Auā", "do not"], ["e lei valaauina", "by not called"], ["i tātou", "us"], ["e le Atua", "God"], ["ia amio leaga,", "he iniquity"], ["a ia fa'apaiaina", "his consecrated"], ["lava.", "very"]]},
  {num:8,words:[["O lenei,", "now"], ["o lē fa'aleaoga", "not make of no value"], ["mai,", "from"], ["ua ia le", "he the"], ["fa'aleaoga", "make of no value"], ["i tagata,", "in man"], ["a", "but"], ["o le Atua", "of God"], ["le", "the"], ["ua foai mai", "gave from"], ["lona Agaga Paia", "his Holy Spirit"], ["ia te i mātou.", "unto us"]]},
  {num:9,words:[["A", "but"], ["e le aoga", "shall not useful"], ["ona ou tusi atu", "and I book"], ["ia te outou", "unto you all"], ["i le mataupu", "in the chapter"], ["o le alofa", "the love"], ["i le aʻu uso;", "in the brethren"], ["auā", "for"], ["ua a'oa'oina outou", "taught you all"], ["lava", "very"], ["e le Atua", "God"], ["ia fealofani.", "he fealofani"]]},
  {num:10,words:[["Auā foi", "do not also"], ["ua fa'apea lava ona", "and it was so and"], ["outou faia", "you all do"], ["i le aʻu uso uma lava", "in all the brethren very"], ["o", "o"], ["i Maketonia", "in Maketonia"], ["atoa uma.", "together with all"], ["A e mātou", "but by us"], ["te apoapoai atu", "exhort"], ["ia te outou", "unto you all"], ["le ʻau uso e,", "brethren"], ["ia fa'asilisili pea i ai;", "he make very much continually therein"]]},
  {num:11,words:[["ma ia outou", "and he you all"], ["taumafai", "try"], ["ina ia outou", "so that you all"], ["nofo fifilemu,", "dwell peace"], ["ia faia", "he do"], ["a outou lava feau,", "your very errand"], ["ma ia galulue", "and he labour"], ["i o outou", "in of you all"], ["lava lima,", "very hand"], ["pei ona", "as/just as"], ["mātou fai atu ai", "we said to"], ["ia te outou;", "unto you all"]]},
  {num:12,words:[["ina ia outou", "so that you all"], ["savavali", "walked"], ["ma le matagofie", "and the beautiful"], ["i", "in"], ["e o", "by of"], ["i tuā,", "in behind"], ["ma ia le matitiva outou", "and he the poor you all"], ["i se mea", "in a thing"], ["e tasi.", "one"]]},
  {num:13,words:[["Ou te loto", "I will heart"], ["ina ia outou", "so that you all"], ["iloa,", "know"], ["le ʻau uso e,", "brethren"], ["i le mataupu", "in the chapter"], ["i", "in"], ["e o momoe,", "by of lie down"], ["ina ne'i outou", "so that now you all"], ["fa'anoanoa,", "mourn"], ["pei o isi", "like of other"], ["e leai so lātou", "there is not so they"], ["fa'amoemoe.", "hope"]]},
  {num:14,words:[["Auā afai tātou te talitonu,", "do not if we will believe"], ["ua māliu Iesu", "died Jesus"], ["ma toe tu mai,", "and resurrection"], ["e fa'apea foi", "so it is also"], ["ona aumaia", "and bring here"], ["e le Atua fa'atasi ma ia", "God with him"], ["e o momoe", "by of lie down"], ["ona o Iesu.", "because of Jesus"]]},
  {num:15,words:[["Mātou te fai atu foi", "we said to also"], ["lenei mea ia te outou", "this thing unto you all"], ["i le afioga", "the word"], ["a le Ali'i,", "if not Lord"], ["o", "o"], ["i tātou", "us"], ["o ē ola", "whose life"], ["ma totoe", "and remaining"], ["pe a afio mai le Ali'i,", "even though / although dwell from the Lord"], ["tātou te", "we will"], ["le muamua", "the first"], ["i", "in"], ["e o momoe.", "by of lie down"]]},
  {num:16,words:[["Auā", "do not"], ["e afio ifo", "dwell down"], ["mai le lagi", "from the heaven"], ["le Ali'i lava,", "the Lord very"], ["ma le alaga,", "and the cry"], ["ma le leo", "and the voice"], ["o le agelu sili,", "the angel most"], ["ma le pu", "and the tail"], ["a le Atua;", "of God"], ["e muamua foi", "first also"], ["ona toe tutū", "and again stood up"], ["mai o", "from of"], ["e ua oti", "the dead"], ["o ia Keriso;", "it Christ"]]},
  {num:17,words:[["ona fa'afuasei lea", "and faafuasei"], ["ona aveina ae", "and taken away up"], ["o", "o"], ["i tātou", "us"], ["o ē ola", "whose life"], ["ma totoe,", "and remaining"], ["fa'atasi ma", "together and"], ["i lātou", "them"], ["i ao,", "in day"], ["ina ia fetaiai", "so that meet one another"], ["ma le Ali'i", "and the Lord"], ["i le va nimonimo;", "in the expanse firmament"], ["ona tātou fa'atasi pea", "and we together continually"], ["lava lea", "very"], ["ma le Ali'i.", "and the Lord"]]},
  {num:18,words:[["O lenei,", "now"], ["ia outou fefaamafanafanai i nei", "he you all comfort one another in these"], ["'upu.", "word"]]},
];
renderVerseSet(_1th_ch_4_Verses, '1th-ch4-verses');

var _1th_ch_5_Verses = [
  {num:1,words:[["A o aso", "but day"], ["ma tausaga,", "and years"], ["e le aoga", "shall not useful"], ["ia te outou,", "unto you all"], ["le ʻau uso e,", "brethren"], ["ona ou tusi atu ai", "and I book"], ["ia te outou.", "unto you all"]]},
  {num:2,words:[["Auā", "do not"], ["ua outou iloa", "you all knew"], ["lelei lava,", "good very"], ["o le aso", "the day"], ["o le Ali'i e pei", "the Lord like"], ["o le gaoi", "the steal"], ["i le po,", "at night"], ["e fa'apea ona", "so it is and"], ["oo mai ai;", "came"], ["auā", "for"], ["pe a lātou", "even though / although they"], ["fai ane.", "said/spoke"]]},
  {num:3,words:[["O loo filemu,", "is peace"], ["ua", "ua"], ["le afaina,", "the name of a tree"], ["ona oo lea", "and oo"], ["ia te i lātou", "unto them"], ["o le fano fa'afuasei,", "the perish faafuasei"], ["fa'apei", "like"], ["o le fa'atiga", "the afflict"], ["o le fafine to", "the women plant"], ["a fānau mai,", "but born of"], ["lātou te", "they will"], ["le sosola ai", "the fled"], ["lava.", "very"]]},
  {num:4,words:[["A o outou,", "but you all"], ["le ʻau uso e,", "brethren"], ["tou te", "second person plural"], ["le o", "the of"], ["i le pouliuli,", "in the darkness"], ["ia maua mai ai", "he received from"], ["outou", "you all"], ["e lena", "by that"], ["aso,", "day"], ["pei o se gaoi.", "like a steal"]]},
  {num:5,words:[["O tagata", "men"], ["o le malamalama outou uma lava,", "the light all of you"], ["ma tagata", "and people"], ["o le ao;", "Day"], ["tātou te", "we will"], ["le o", "the of"], ["i le po", "at night"], ["ma le pouliuli.", "and the darkness"]]},
  {num:6,words:[["O lea,", "therefore"], ["aua ne'i tātou", "for now we"], ["momoe ai", "lie down"], ["fa'apei o isi,", "like of other"], ["a ia tātou", "his we"], ["mataala,", "mataala"], ["ma ia fa'autauta.", "and he was prudent"]]},
  {num:7,words:[["Auā o", "do not of"], ["e momoe,", "lie down"], ["e momoe", "lie down"], ["i lātou", "them"], ["i le po;", "at night"], ["o ē inu", "whose drink"], ["ia onā,", "he drunk"], ["e onā", "drunk"], ["i lātou", "them"], ["i le po;", "at night"]]},
  {num:8,words:[["a o", "but"], ["i tātou nei", "us these"], ["o ē", "whose"], ["o le ao,", "Day"], ["ia fa'autauta i tātou,", "he was prudent us"], ["ia tātou oofu i le", "he we oofu in the"], ["ufifatafata", "coat of mail"], ["o le fa'atuatua", "the faith"], ["ma le alofa,", "and the love"], ["ma le puloutau", "and the puloutau"], ["o le fa'amoemoe", "the hope"], ["i le ola.", "in the life"]]},
  {num:9,words:[["Auā", "do not"], ["e lei tofia", "by not was chosen"], ["i tātou", "us"], ["e le Atua", "God"], ["i le toasa,", "in the wrath"], ["a ia maua", "his received"], ["le ola", "the life"], ["ona", "and"], ["o lo tātou Ali'i", "our Lord"], ["o Iesu Keriso,", "Jesus Christ"]]},
  {num:10,words:[["o le", "the"], ["na māliu", "died"], ["e sui a'i tātou,", "in its place we"], ["ina ia tātou", "so that we"], ["ola fa'atasi ma ia,", "life with him"], ["pe tātou te mataala,", "whether we will mataala"], ["pe tātou te momoe.", "whether we will lie down"]]},
  {num:11,words:[["O lea", "therefore"], ["ia outou feapoapoai ai,", "he you all exhort one another"], ["ma ia fefaamafanafanai,", "and he comfort one another"], ["fa'apei", "like"], ["ona outou faia", "and you all do"], ["lava.", "very"]]},
  {num:12,words:[["Mātou te aioi atu foi", "we cry out also"], ["ia te outou,", "unto you all"], ["le ʻau uso e,", "brethren"], ["ia outou iloa", "he you all know"], ["e o galulue", "by of labour"], ["ia te outou,", "unto you all"], ["ma pule ia te outou", "and rule unto you all"], ["i lā le Ali'i,", "in the Lord"], ["ma lātou apoapoai atu", "and they exhort"], ["ia te outou;", "unto you all"]]},
  {num:13,words:[["ia matuā mānatua i lātou", "he exceedingly remember them"], ["ma le alofa,", "and the love"], ["ona", "and"], ["o lā lātou galuega.", "their work"], ["Ia outou nonofo", "he you all dwelling"], ["fefilemuai.", "be at peace with one another"]]},
  {num:14,words:[["Mātou te aioi atu foi", "we cry out also"], ["ia te outou,", "unto you all"], ["le ʻau uso e,", "brethren"], ["ia outou apoapoai atu i", "he you all exhort in"], ["e amio fa'apiopio,", "deeds faapiopio"], ["ia fa'amafanafana i", "he hearten in"], ["e loto iti,", "is fixed small"], ["ia fesoasoani i", "he help in"], ["e o vaivai,", "by of weak"], ["ia outou onosai i", "he you all patience in"], ["tagata uma lava.", "man all very"]]},
  {num:15,words:[["Ia outou,", "he you all"], ["ne'i taui atu", "now a reward"], ["e se tasi", "by a one"], ["le leaga", "the evil"], ["i le leaga", "in the evil"], ["i se tasi tagata,", "in a one man"], ["a ia outou", "his you all"], ["tausisi", "strive for"], ["e le aunoa", "shall not without"], ["i le mea lelei,", "in the thing good"], ["o le tasi", "the one"], ["i le tasi,", "in the one"], ["atoa ma tagata uma lava.", "and man all very"]]},
  {num:16,words:[["Ia outou saga", "he you all saga"], ["olioli pea lava.", "joy continually very"]]},
  {num:17,words:[["Ia tatalo", "he pray"], ["e le aunoa.", "shall not without"]]},
  {num:18,words:[["Ia outou fa'afetai i mea uma lava,", "he you all thank things all very"], ["auā", "for"], ["o le finagalo lea", "the will"], ["o le Atua", "of God"], ["ia te outou,", "unto you all"], ["ia Keriso Iesu.", "he Christ Jesus"]]},
  {num:19,words:[["Aua tou te tineia", "do not second person plural tineia"], ["le Agaga.", "the spirit"]]},
  {num:20,words:[["Aua", "do not"], ["le ta'ufaatauvaa", "the ta'ufaatauvaa"], ["i perofetaga.", "in prophet"]]},
  {num:21,words:[["Ia tofotofo i mea uma lava,", "he try things all very"], ["ia taofi mau i le mea", "he hold opinion in the thing"], ["lelei.", "good"]]},
  {num:22,words:[["Ia mamao outou", "he far you all"], ["ma mea leaga eseese uma lava.", "and thing evil divided all very"]]},
  {num:23,words:[["Ia atoatoa", "he completely"], ["ona fa'apaiaina o outou", "and consecrated of you all"], ["e le Atua", "God"], ["lava", "very"], ["e", "by"], ["ona", "and"], ["le manuia;", "the prosper"], ["ia tausia lava", "he nursed very"], ["lo outou agaga", "your spirit"], ["atoa uma,", "together with all"], ["i le", "in the"], ["ma le loto,", "and the heart"], ["atoa ma le tino,", "and the body"], ["ia le mata'uleagaina,", "he the mata'uleagaina"], ["i le afio mai", "in the dwell from"], ["o lo tātou Ali'i", "our Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
  {num:24,words:[["E fa'amaoni lava", "faithful very"], ["o le", "the"], ["ua valaauina outou,", "called you all"], ["o le", "the"], ["na te faia lava.", "he did very"]]},
  {num:25,words:[["Le ʻau uso e,", "brethren"], ["ia outou tatalo", "he you all pray"], ["mo", "for"], ["i mātou.", "us"]]},
  {num:26,words:[["Ia alolofa atu i le aʻu uso", "he alolofa in the brethren"], ["uma", "all"], ["i le feasogi paia.", "in the salute by rubbJDg holy"]]},
  {num:27,words:[["Ou te matuā fai atu", "I will exceedingly said to"], ["ia te outou", "unto you all"], ["i le suafa", "in the name"], ["o le Ali'i,", "the Lord"], ["ia faitaulia lenei", "he counted this"], ["tusi", "book"], ["i le aʻu uso paia uma lava.", "in the brethren holy all very"]]},
  {num:28,words:[["Ia ia te outou", "to him you all"], ["le alofa tunoa", "grace"], ["o lo tātou Ali'i", "our Lord"], ["o Iesu Keriso.", "Jesus Christ"], ["Amene.", "amen"]]},
];
renderVerseSet(_1th_ch_5_Verses, '1th-ch5-verses');

})();