(function() {
var 1th_ch_1_Verses = [
  {num:1,words:[["O i matou ,", "Paul,"], ["o Paulo,", "and Silvanus,"], ["ma Siluano,", "and Timotheus,"], ["ma Timoteo o la matou tusi lenei i le ekalesia o tagata o Tesalonia,", "unto the church of the Thessalonians which is in God the Father and in the Lord Jesus Christ: Grace be unto you,"], ["o i le Atua le Tamā,", "and peace,"], ["ma le Alii o Iesu Keriso. Ia ia te outou le alofa tunoa,", "from God our Father,"], ["ma le manuia mai le Atua lo tatou Tamā atoa ma le Alii o Iesu Keriso.", "and the Lord Jesus Christ."]]},
  {num:2,words:[["Matou te faafetai pea lava i le Atua, ona o outou uma lava,", "We give thanks to God always for you all,"], ["o loo ta'uta'ua outou i a matou tatalo,", "making mention of you in our prayers;"]]},
  {num:3,words:[["e le aunoa ona matou mānatua la outou galuega i le faatuatua,", "Remembering without ceasing your work of faith,"], ["ma le faamalosi i le alofa,", "and labour of love,"], ["ma le tumau pea i le faamoemoe i lo tatou Alii o Iesu Keriso,", "and patience of hope in our Lord Jesus Christ,"], ["i luma o le Atua o lo tatou Tamā lea;", "in the sight of God and our Father;"]]},
  {num:4,words:[["ina ua matou iloa le filifilia o outou,", "Knowing,"], ["le au uso e,", "brethren beloved,"], ["o e ua alofagia e le Atua.", "your election of God."]]},
  {num:5,words:[["Auā e lei oo atu la matou tala lelei ia te outou na o le upu,", "For our gospel came not unto you in word only,"], ["a o le mana,", "but also in power,"], ["ma le Agaga Paia,", "and in the Holy Ghost,"], ["atoa ma le mautinoa lava ina ua outou iloa la matou amio ona o outou,", "and in much assurance;"], ["a o matou i ai ma outou;", "as ye know what manner of men we were among you for your sake."]]},
  {num:6,words:[["sa outou faaa'oa'o mai foi ia te i matou,", "And ye became followers of us,"], ["atoa ma le Alii,", "and of the Lord,"], ["ina ua outou talia le upu i le puapuaga tele,", "having received the word in much affliction,"], ["ma le olioli mai le Agaga Paia;", "with joy of the Holy Ghost:"]]},
  {num:7,words:[["o lea ua avea ai outou ma faaa'oa'o i e ua faatuatua uma lava o i Maketonia atoa ma Akaia;", "So that ye were ensamples to all that believe in Macedonia and Achaia."]]},
  {num:8,words:[["auā ua logo atu nai ia te outou le afioga a le Alii,", "For from you sounded out the word of the Lord not only in Macedonia and Achaia,"], ["e le gata i Maketonia ma Akaia,", "but also in every place your faith to God-ward is spread abroad;"], ["a ua salalau atu foi i mea uma lava le tala i lo outou faatuatua i le Atua o lea e le aoga ai sa matou upu e fai atu ai.", "so that we need not to speak any thing."]]},
  {num:9,words:[["Auā o i latou lava ua iloa ai le tala ia te i matou i le uiga o lo matou oo atu ia te outou na, ma lo outou liliu mai i le Atua nai tupua,", "For they themselves shew of us what manner of entering in we had unto you,"], ["ina ia outou auauna i le Atua soifua ma le ua moni,", "and how ye turned to God from idols to serve the living and true God;"]]},
  {num:10,words:[["ma ia faatali atu i lona Alo mai le lagi,", "And to wait for his Son from heaven,"], ["o le na toe faatuina mai e ia nai e ua oti,", "whom he raised from the dead,"], ["o Iesu lea,", "even Jesus,"], ["o lē laveai mai ia i tatou ai le toasa atali.", "which delivered us from the wrath to come."]]},
  {num:11,words:[["O lea ia outou feapoapoai ai,", "therefore to ye all feapoapoai"], ["ma ia fefaamafanafanai,", "and to fefaamafanafanai"], ["faapei", "like"], ["ona outou faia lava.", "and ye all made indeed"]]},
  {num:12,words:[["Matou te aїoї atu foi ia te outou,", "we aїoї also unto ye all"], ["le au uso", "the I a relative of the same generation and gender"], ["e,", "by"], ["ia outou iloa", "to ye all known"], ["e o galulue ia te outou,", "by galulue unto ye all"], ["ma pule ia te outou", "and rule unto ye all"], ["i la le Alii,", "in the Lord"], ["ma latou apoapoai atu ia te outou;", "and them apoapoai unto ye all"], ["13 ia matuá mánatua", "13 to matuá mánatua"], ["i latou", "them"], ["ma le alofa,", "and the love"], ["ona o la latou galuega.", "because of their work"], ["la outou nonofo fefilemuai.", "your dwelling fefilemuai"]]},
];
renderVerseSet(1th_ch_1_Verses, '1th-ch1-verses');

var 1th_ch_2_Verses = [
  {num:1,words:[["Auā o outou lava,", "For yourselves,"], ["le au uso e,", "brethren,"], ["ua outou iloa o lo matou oo atu ia te outou,", "know our entrance in unto you,"], ["e lei faaleaogaina lea;", "that it was not in vain:"]]},
  {num:2,words:[["a e ui lava ina muamua ona tigaina o i matou,", "But even after that we had suffered before, and were shamefully entreated,"], ["ma faaleagaina i Filipi,", "as ye know,"], ["pei ona outou iloa ua matou faamalosi ona o lo tatou Atua e tautala atu ia te outou i le tala lelei a le Atua ma le finafinau tele lava.", "at Philippi, we were bold in our God to speak unto you the gospel of God with much contention."]]},
  {num:3,words:[["Auā o lo matou apoapoai atu ia te outou e lei faia lea ma le sese,", "For our exhortation was not of deceit,"], ["po o le amio leaga,", "nor of uncleanness,"], ["po o le faa'ole'ole.", "nor in guile:"]]},
  {num:4,words:[["A e peitai,", "But as we were allowed of God to be put in trust with the gospel,"], ["faapei ona tatau i le finagalo o le Atua na te tuuina mai ia te i matou le tala lelei,", "even so we speak;"], ["e faapea foi ona matou tautala atu ai; e le ina ia fiafia mai tagata,", "not as pleasing men,"], ["a o le Atua,", "but God,"], ["o lē tofotofo mai i o matou loto.", "which trieth our hearts."]]},
  {num:5,words:[["Auā matou te lei fai lava se upu e faaviivii atu ai,", "For neither at any time used we flattering words,"], ["faapei ona outou iloa,", "as ye know,"], ["pe faia se ufiufi o le manumanu;", "nor a cloke of covetousness;"], ["ua silafia e le Atua;", "God is witness:"]]},
  {num:6,words:[["e ui lava ina mafai ia te i matou ona ia mafatia ai outou,", "Nor of men sought we glory,"], ["auā o aposetolo i matou a Keriso,", "neither of you,"], ["a e matou te le saili le viiga mai tagata,", "nor yet of others, when we might have been burdensome,"], ["po o outou po o isi tagata.", "as the apostles of Christ."]]},
  {num:7,words:[["A ua matou agamalu ina ua matou i ai ia te outou na,", "But we were gentle among you,"], ["faapei o se failele na te tausi lelei i ana lava tama;", "even as a nurse cherisheth her children:"]]},
  {num:8,words:[["sa faapea lava lo matou maelega i le alofa ia te outou,", "So being affectionately desirous of you,"], ["na matou manao i le fia avatu ia te outou e le na o le tala lelei i le Atua,", "we were willing to have imparted unto you,"], ["a o matou lava ola foi,", "not the gospel of God only, but also our own souls,"], ["auā na alofaina outou e i matou.", "because ye were dear unto us."]]},
  {num:9,words:[["Auā le au uso e,", "For ye remember,"], ["ua outou mānatua la matou galuega mamafa ma le tiga;", "brethren,"], ["auā sa matou galulue ai i le po atoa ma le ao,", "our labour and travail: for labouring night and day,"], ["ina ne'i mafatia so outou,", "because we would not be chargeable unto any of you,"], ["na matou tala'i atu ai ia te outou le tala lelei a le Atua.", "we preached unto you the gospel of God."]]},
  {num:10,words:[["Ua iloa outou atoa ma le Atua, sa matou amio Atua,", "Ye are witnesses,"], ["ma amiotonu,", "and God also,"], ["ma le le mata'uleagaina, ina o matou i ai ia te outou o e faatuatua.", "how holily and justly and unblameably we behaved ourselves among you that believe:"]]},
  {num:11,words:[["Pei ona outou iloa, sa matou i ai ia te outou taitasi, pei o le tamā i lana lava fanau,", "As ye know how we exhorted and comforted and charged every one of you,"], ["na matou apoapoai atu ia te outou, o faamafanafana atu foi, ma ta'utino atu,", "as a father doth his children,"]]},
  {num:12,words:[["ina ia outou savavali ia tatau i le Atua,", "That ye would walk worthy of God,"], ["o le na valaauina outou i lona malo ma lona manuia.", "who hath called you unto his kingdom and glory."]]},
  {num:13,words:[["O le mea lea matou te faafetai ai i le Atua,", "For this cause also thank we God without ceasing,"], ["o i matou lava e le aunoa,", "because,"], ["auā na talia e outou le afioga a le Atua na outou faalogo mai ai ia i matou,", "when ye received the word of God which ye heard of us,"], ["ua le talia e outou o le upu a tagata,", "ye received it not as the word of men,"], ["a e peitai o le upu a le Atua,", "but as it is in truth,"], ["(e moni lava lea,", "the word of God,"], [") ua matuā galue foi lea i totonu ia te outou o e faatuatua.", "which effectually worketh also in you that believe."]]},
  {num:14,words:[["Auā le au uso e,", "For ye,"], ["na outou faaa'oa'o i ekalesia a le Atua o i Iutaia,", "brethren,"], ["o loo ia Keriso Iesu;", "became followers of the churches of God which in Judaea are in Christ Jesus:"], ["auā o outou foi na tigaina outou i ia lava mea i tagata o lo outou lava nuu,", "for ye also have suffered like things of your own countrymen,"], ["faapei ona tigaina o i latou foi ia Iutaia;", "even as they have of the Jews:"]]},
  {num:15,words:[["o e na fasioti i le Alii,", "Who both killed the Lord Jesus,"], ["o Iesu lava,", "and their own prophets,"], ["atoa ma a latou lava perofeta, na faasaua mai foi i latou ia i matou;", "and have persecuted us;"], ["e le fiafia i ai le Atua,", "and they please not God,"], ["ua fai foi tagata uma lava mo latou fili;", "and are contrary to all men:"]]},
  {num:16,words:[["ua vavao mai ia i matou, aua matou te tautala atu i nuu ese,", "Forbidding us to speak to the Gentiles that they might be saved,"], ["ina ia faaolaina ai i latou;", "to fill up their sins alway:"], ["ua faaatoa ai e i latou e le aunoa a latou agasala; a ua oo ia te i latou le toasa e faaumatia ai.", "for the wrath is come upon them to the uttermost."]]},
  {num:17,words:[["O i matou foi,", "But we,"], ["le au uso e,", "brethren,"], ["o loo tete'aeseina o i matou ma outou i ni nai aso itiiti,", "being taken from you for a short time in presence,"], ["i le tino a e le o le loto,", "not in heart,"], ["ua atili ai ona matou taumafaia ma le naunau tele ona ia tatou feiloai ma outou.", "endeavoured the more abundantly to see your face with great desire."]]},
  {num:18,words:[["O lea na matou fia o atu ai ia te outou,", "Wherefore we would have come unto you,"], ["o a'u lava o Paulo,", "even I Paul,"], ["ua atu tasi ma atu lua,", "once and again;"], ["a ua faalavelave mai Satani ia te i matou.", "but Satan hindered us."]]},
  {num:19,words:[["Auā se a ea so matou faamoemoe,", "For what is our hope,"], ["ma se fiafia, ma se pale e mitamita ai? E le o outou ea i luma o lo tatou Alii o Iesu Keriso,", "or joy,"], ["i lona afio mai?", "or crown of rejoicing? Are not even ye in the presence of our Lord Jesus Christ at his coming?"]]},
  {num:20,words:[["Auā o outou lava o lo matou viiga ma lo matou olioli.", "For ye are our glory and joy."]]},
];
renderVerseSet(1th_ch_2_Verses, '1th-ch2-verses');

var 1th_ch_3_Verses = [
  {num:1,words:[["O lea ua lelei ai ia te i matou ona ia tuua ai i matou i Atenai, tau o i matou,", "Wherefore when we could no longer forbear,"], ["ina ua matou le toe mafai ona onosai;", "we thought it good to be left at Athens alone;"]]},
  {num:2,words:[["a ua matou auina atu Timoteo lo matou uso,", "And sent Timotheus,"], ["o le auauna foi o ia a le Atua,", "our brother,"], ["o lē galue faatasi ma i matou i le tala lelei ia Keriso,", "and minister of God, and our fellowlabourer in the gospel of Christ,"], ["ina ia faatumauina outou e ia,", "to establish you,"], ["ma ia faamafanafana atu ia te outou i lo outou faatuatua;", "and to comfort you concerning your faith:"]]},
  {num:3,words:[["ina ne'i faagaeetia se tasi i nei puapuaga;", "That no man should be moved by these afflictions:"], ["auā ua outou iloa ua tofia lenei lava mea.", "for yourselves know that we are appointed thereunto."]]},
  {num:4,words:[["Auā foi o ona po sa i ai i matou ia te outou,", "For verily,"], ["na matou muai fai atu ai ia te outou,", "when we were with you,"], ["o le a oo mai le puapuaga,", "we told you before that we should suffer tribulation;"], ["ua faapea ona taunuu lava,", "even as it came to pass,"], ["ua outou iloa foi.", "and ye know."]]},
  {num:5,words:[["O le mea lea na ou le toe mafai ai ona onosai,", "For this cause,"], ["ona auina atu lea e a'u,", "when I could no longer forbear,"], ["ina ia ou iloa lo outou faatuatua,", "I sent to know your faith,"], ["ne'i faaosoosoina outou e lē faaosooso,", "lest by some means the tempter have tempted you,"], ["ona faaleaogaina ai lea o la matou galuega.", "and our labour be in vain."]]},
  {num:6,words:[["A o lenei,", "But now when Timotheus came from you unto us,"], ["ua sau Timoteo ia te i matou nai ia te outou, ua au mai foi le tala lelei ia te i matou i lo outou faatuatua,", "and brought us good tidings of your faith and charity,"], ["ma lo outou alofa,", "and that ye have good remembrance of us always,"], ["ma lo outou manatu lelei mai e le aunoa ia te i matou, o loo faanaunau foi outou ina ia tatou feiloai ma outou,", "desiring greatly to see us,"], ["pei o i matou ona fia feiloai ma outou;", "as we also to see you:"]]},
  {num:7,words:[["o le mea lea, le au uso e,", "Therefore,"], ["na faamafanafanaina mai ai i matou ona o outou, i lo matou puapuaga uma lava,", "brethren,"], ["atoa ma lo matou tiga, ona o lo outou faatuatua.", "we were comforted over you in all our affliction and distress by your faith:"]]},
  {num:8,words:[["Auā o lenei, ua matou ola,", "For now we live,"], ["pe afai tou te tumau i le Alii.", "if ye stand fast in the Lord."]]},
  {num:9,words:[["Se a foi se faafetai matou te mafaia ona tuuina atu i le Atua ona o outou,", "For what thanks can we render to God again for you,"], ["auā o le olioli uma lava matou te olioli ai i luma o lo tatou Atua?", "for all the joy wherewith we joy for your sakes before our God;"]]},
  {num:10,words:[["o loo matou matuā ole atu ai i le po atoa ma le ao, ina ia tatou feiloai ma outou,", "Night and day praying exceedingly that we might see your face,"], ["e faaatoatoaina ai mea e lei atoa i lo outou faatuatua.", "and might perfect that which is lacking in your faith?"]]},
  {num:11,words:[["A ia ta'ita'iina la matou malaga ia te outou e le Atua lava,", "Now God himself and our Father,"], ["lo tatou Tamā,", "and our Lord Jesus Christ,"], ["atoa ma lo tatou Alii o Iesu Keriso.", "direct our way unto you."]]},
  {num:12,words:[["Ia faatele foi e le Alii, ma ia faasilisili ona tele o lo outou alofa,", "And the Lord make you to increase and abound in love one toward another,"], ["o le tasi i le tasi,", "and toward all men,"], ["atoa ma tagata uma, faapei o i matou nei lava ia te outou;", "even as we do toward you:"]]},
  {num:13,words:[["ina ia faatumauina o outou loto e le mata'uleagaina i le amio lelei i luma o le Atua lo latou Tamā,", "To the end he may stablish your hearts unblameable in holiness before God,"], ["pe a afio mai lo tatou Alii o Iesu Keriso,", "even our Father,"], ["faatasi ma ona au paia uma.", "at the coming of our Lord Jesus Christ with all his saints."]]},
];
renderVerseSet(1th_ch_3_Verses, '1th-ch3-verses');

var 1th_ch_4_Verses = [
  {num:1,words:[["O lenei,", "Furthermore then we beseech you,"], ["le au uso e, o le toe upu lenei,", "brethren,"], ["matou te aioi atu ma apoapoai atu ia te outou ona o le Alii o Iesu,", "and exhort you by the Lord Jesus,"], ["faapei ona talai e outou mai ia te i matou le uiga o le ala e tatau ona outou savavali ai, ia fiafia mai ai le Atua ia te outou,", "that as ye have received of us how ye ought to walk and to please God,"], ["ia faasilisili pea i ai outou.", "so ye would abound more and more."]]},
  {num:2,words:[["Auā ua outou iloa ia poloaiga na matou tuuina atu ai ia te outou mai le Alii o Iesu.", "For ye know what commandments we gave you by the Lord Jesus."]]},
  {num:3,words:[["O le finagalo foi lenei o le Atua,", "For this is the will of God,"], ["ia faapaiaina outou,", "even your sanctification,"], ["ina ia faamamao outou ma le faitaaga;", "that ye should abstain from fornication:"]]},
  {num:4,words:[["ia taitasi outou ma iloa ona fai o lana lava ipu ma le faapaiaina ma le ta'uleleia,", "That every one of you should know how to possess his vessel in sanctification and honour;"]]},
  {num:5,words:[["aua ma le tu'inanau o le manao,", "Not in the lust of concupiscence,"], ["faapei o nuu ese ua le iloa le Atua.", "even as the Gentiles which know not God:"]]},
  {num:6,words:[["Aua ne'i sopo tapulaa se tasi, ma agaleaga i lona uso i lenei mea;", "That no man go beyond and defraud his brother in any matter:"], ["auā o le Alii na te taui atu ma sui i nei mea uma,", "because that the Lord is the avenger of all such,"], ["faapei ona matou muai fai atu ai, ma ta'utino atu ia te outou.", "as we also have forewarned you and testified."]]},
  {num:7,words:[["Auā e lei valaauina i tatou e le Atua ia amio leaga,", "For God hath not called us unto uncleanness,"], ["a ia faapaiaina lava.", "but unto holiness."]]},
  {num:8,words:[["O lenei,", "He therefore that despiseth,"], ["o lē faaleaoga mai,", "despiseth not man,"], ["ua ia le faaleaoga i tagata,", "but God,"], ["a o le Atua le ua foai mai lona Agaga Paia ia te i matou.", "who hath also given unto us his holy Spirit."]]},
  {num:9,words:[["A e le aoga ona ou tusi atu ia te outou i le mataupu o le alofa i le au uso;", "But as touching brotherly love ye need not that I write unto you:"], ["auā ua a'oa'oina outou lava e le Atua ia fealofani.", "for ye yourselves are taught of God to love one another."]]},
  {num:10,words:[["Auā foi ua faapea lava ona outou faia i le au uso uma lava o i Maketonia atoa uma. A e matou te apoapoai atu ia te outou le au uso e,", "And indeed ye do it toward all the brethren which are in all Macedonia: but we beseech you,"], ["ia faasilisili pea i ai;", "brethren, that ye increase more and more;"]]},
  {num:11,words:[["ma ia outou taumafai ina ia outou nofo fifilemu,", "And that ye study to be quiet,"], ["ia faia a outou lava feau,", "and to do your own business,"], ["ma ia galulue i o outou lava lima,", "and to work with your own hands,"], ["pei ona matou fai atu ai ia te outou;", "as we commanded you;"]]},
  {num:12,words:[["ina ia outou savavali ma le matagofie i e o i tuā,", "That ye may walk honestly toward them that are without,"], ["ma ia le matitiva outou i se mea e tasi.", "and that ye may have lack of nothing."]]},
  {num:13,words:[["Ou te loto ina ia outou iloa,", "But I would not have you to be ignorant,"], ["le au uso e,", "brethren,"], ["i le mataupu i e o momoe,", "concerning them which are asleep,"], ["ina ne'i outou faanoanoa,", "that ye sorrow not,"], ["pei o isi e leai so latou faamoemoe.", "even as others which have no hope."]]},
  {num:14,words:[["Auā afai tatou te talitonu, ua maliu Iesu ma toe tu mai,", "For if we believe that Jesus died and rose again,"], ["e faapea foi ona aumaia e le Atua faatasi ma ia e o momoe ona o Iesu.", "even so them also which sleep in Jesus will God bring with him."]]},
  {num:15,words:[["Matou te fai atu foi lenei mea ia te outou i le afioga a le Alii, o i tatou o e ola ma totoe pe a afio mai le Alii,", "For this we say unto you by the word of the Lord,"], ["tatou te le muamua i e o momoe.", "that we which are alive and remain unto the coming of the Lord shall not prevent them which are asleep."]]},
  {num:16,words:[["Auā e afio ifo mai le lagi le Alii lava,", "For the Lord himself shall descend from heaven with a shout,"], ["ma le alaga,", "with the voice of the archangel,"], ["ma le leo o le agelu sili, ma le pu a le Atua;", "and with the trump of God:"], ["e muamua foi ona toe tutū mai o e ua oti o ia Keriso;", "and the dead in Christ shall rise first:"]]},
  {num:17,words:[["ona faafuasei lea ona aveina ae o i tatou o e ola ma totoe,", "Then we which are alive and remain shall be caught up together with them in the clouds,"], ["faatasi ma i latou i ao, ina ia fetaiai ma le Alii i le va nimonimo;", "to meet the Lord in the air:"], ["ona tatou faatasi pea lava lea ma le Alii.", "and so shall we ever be with the Lord."]]},
  {num:18,words:[["O lenei, ia outou fefaamafanafanai i nei upu.", "Wherefore comfort one another with these words."]]},
];
renderVerseSet(1th_ch_4_Verses, '1th-ch4-verses');

var 1th_ch_5_Verses = [
  {num:1,words:[["A o aso ma tausaga,", "But of the times and the seasons,"], ["e le aoga ia te outou, le au uso e,", "brethren,"], ["ona ou tusi atu ai ia te outou.", "ye have no need that I write unto you."]]},
  {num:2,words:[["Auā ua outou iloa lelei lava, o le aso o le Alii e pei o le gaoi i le po, e faapea ona oo mai ai; auā pe a latou fai ane.", "For yourselves know perfectly that the day of the Lord so cometh as a thief in the night."]]},
  {num:3,words:[["O loo filemu,", "For when they shall say,"], ["ua le afaina,", "Peace and safety;"], ["ona oo lea ia te i latou o le fano faafuasei,", "then sudden destruction cometh upon them,"], ["faapei o le faatiga o le fafine to a fanau mai,", "as travail upon a woman with child;"], ["latou te le sosola ai lava.", "and they shall not escape."]]},
  {num:4,words:[["A o outou,", "But ye,"], ["le au uso e,", "brethren,"], ["tou te le o i le pouliuli, ia maua mai ai outou e lena aso,", "are not in darkness,"], ["pei o se gaoi.", "that that day should overtake you as a thief."]]},
  {num:5,words:[["O tagata o le malamalama outou uma lava,", "Ye are all the children of light,"], ["ma tagata o le ao;", "and the children of the day: we are not of the night,"], ["tatou te le o i le po ma le pouliuli.", "nor of darkness."]]},
  {num:6,words:[["O lea,", "Therefore let us not sleep,"], ["aua ne'i tatou momoe ai faapei o isi, a ia tatou mataala,", "as do others;"], ["ma ia faautauta.", "but let us watch and be sober."]]},
  {num:7,words:[["Auā o e momoe, e momoe i latou i le po;", "For they that sleep sleep in the night;"], ["o e inu ia onā, e onā i latou i le po;", "and they that be drunken are drunken in the night."]]},
  {num:8,words:[["a o i tatou nei o e o le ao,", "But let us, who are of the day,"], ["ia faautauta i tatou,", "be sober,"], ["ia tatou oofu i le ufifatafata o le faatuatua ma le alofa,", "putting on the breastplate of faith and love;"], ["ma le puloutau o le faamoemoe i le ola.", "and for an helmet, the hope of salvation."]]},
  {num:9,words:[["Auā e lei tofia i tatou e le Atua i le toasa,", "For God hath not appointed us to wrath,"], ["a ia maua le ola ona o lo tatou Alii o Iesu Keriso,", "but to obtain salvation by our Lord Jesus Christ,"]]},
  {num:10,words:[["o le na maliu e sui a'i tatou,", "Who died for us,"], ["ina ia tatou ola faatasi ma ia,", "that,"], ["pe tatou te mataala,", "whether we wake or sleep,"], ["pe tatou te momoe.", "we should live together with him."]]},
  {num:11,words:[["O lea ia outou feapoapoai ai,", "Wherefore comfort yourselves together,"], ["ma ia fefaamafanafanai,", "and edify one another,"], ["faapei ona outou faia lava.", "even as also ye do."]]},
  {num:12,words:[["Matou te aioi atu foi ia te outou,", "And we beseech you,"], ["le au uso e,", "brethren,"], ["ia outou iloa e o galulue ia te outou,", "to know them which labour among you,"], ["ma pule ia te outou i la le Alii,", "and are over you in the Lord,"], ["ma latou apoapoai atu ia te outou;", "and admonish you;"]]},
  {num:13,words:[["ia matuā mānatua i latou ma le alofa, ona o la latou galuega.", "And to esteem them very highly in love for their work's sake."], ["Ia outou nonofo fefilemuai.", "And be at peace among yourselves."]]},
  {num:14,words:[["Matou te aioi atu foi ia te outou,", "Now we exhort you,"], ["le au uso e,", "brethren,"], ["ia outou apoapoai atu i e amio faapiopio,", "warn them that are unruly,"], ["ia faamafanafana i e loto iti,", "comfort the feebleminded,"], ["ia fesoasoani i e o vaivai,", "support the weak,"], ["ia outou onosai i tagata uma lava.", "be patient toward all men."]]},
  {num:15,words:[["Ia outou,", "See that none render evil for evil unto any man;"], ["ne'i taui atu e se tasi le leaga i le leaga i se tasi tagata,", "but ever follow that which is good,"], ["a ia outou tausisi e le aunoa i le mea lelei, o le tasi i le tasi,", "both among yourselves,"], ["atoa ma tagata uma lava.", "and to all men."]]},
  {num:16,words:[["Ia outou saga olioli pea lava.", "Rejoice evermore."]]},
  {num:17,words:[["Ia tatalo e le aunoa.", "Pray without ceasing."]]},
  {num:18,words:[["Ia outou faafetai i mea uma lava, auā o le finagalo lea o le Atua ia te outou,", "In every thing give thanks:"], ["ia Keriso Iesu.", "for this is the will of God in Christ Jesus concerning you."]]},
  {num:19,words:[["Aua tou te tineia le Agaga.", "Quench not the Spirit."]]},
  {num:20,words:[["Aua le ta'ufaatauvaa i perofetaga.", "Despise not prophesyings."]]},
  {num:21,words:[["Ia tofotofo i mea uma lava,", "Prove all things;"], ["ia taofi mau i le mea lelei.", "hold fast that which is good."]]},
  {num:22,words:[["Ia mamao outou ma mea leaga eseese uma lava.", "Abstain from all appearance of evil."]]},
  {num:23,words:[["Ia atoatoa ona faapaiaina o outou e le Atua lava e ona le manuia; ia tausia lava lo outou agaga atoa uma, i le ma le loto,", "And the very God of peace sanctify you wholly;"], ["atoa ma le tino, ia le mata'uleagaina, i le afio mai o lo tatou Alii o Iesu Keriso.", "and I pray God your whole spirit and soul and body be preserved blameless unto the coming of our Lord Jesus Christ."]]},
  {num:24,words:[["E faamaoni lava o le ua valaauina outou,", "Faithful is he that calleth you,"], ["o le na te faia lava.", "who also will do it."]]},
  {num:25,words:[["Le au uso e,", "Brethren,"], ["ia outou tatalo mo i matou.", "pray for us."]]},
  {num:26,words:[["Ia alolofa atu i le au uso uma i le feasogi paia.", "Greet all the brethren with an holy kiss."]]},
  {num:27,words:[["Ou te matuā fai atu ia te outou i le suafa o le Alii, ia faitaulia lenei tusi i le au uso paia uma lava.", "I charge you by the Lord that this epistle be read unto all the holy brethren."]]},
  {num:28,words:[["Ia ia te outou le alofa tunoa o lo tatou Alii o Iesu Keriso. Amene.", "The grace of our Lord Jesus Christ be with you. Amen."]]},
];
renderVerseSet(1th_ch_5_Verses, '1th-ch5-verses');

})();