(function() {
var _1th_ch_1_Verses = [
  {num:1,words:[["O i matou ,", "in we (excl)"], ["o Paulo,", "Paul"], ["ma Siluano,", "and Siluano"], ["ma Timoteo", "and Timothy"], ["o la matou tusi lenei", "our book this"], ["i le ekalesia o tagata", "in the church of men"], ["o Tesalonia,", "Tesalonia"], ["o i le Atua le Tamā,", "in the God the father"], ["ma le Alii o Iesu Keriso.", "and the Lord of Jesus Christ"], ["Ia ia te outou", "to him you (all)"], ["le alofa tunoa,", "grace"], ["ma le manuia", "and peace"], ["mai le Atua lo tatou Tamā", "from God our Father"], ["atoa ma le Alii o Iesu Keriso.", "and the Lord Jesus Christ"]]},
  {num:2,words:[["Matou te faafetai pea lava", "we (excl) thank continually indeed"], ["i le Atua,", "in the God"], ["ona o outou uma lava,", "because of all of you"], ["o loo ta'uta'ua outou", "ta'uta'ua you (all)"], ["i a matou tatalo,", "in but we (excl) pray"]]},
  {num:3,words:[["e le aunoa", "by the without"], ["ona matou mānatua la outou galuega", "and we (excl) mānatua your work"], ["i le faatuatua,", "in the faith"], ["ma le faamalosi", "and the be strong"], ["i le alofa,", "in the love"], ["ma le tumau pea i le faamoemoe", "and the enduring continually in the hope"], ["i lo tatou Alii o Iesu Keriso,", "in the we (incl) Lord of Jesus Christ"], ["i luma o le Atua o lo tatou Tamā lea;", "before God our father"]]},
  {num:4,words:[["ina ua matou iloa", "so that we (excl) knew"], ["le filifilia o outou,", "the chosen of you (all)"], ["le au uso", "the I brother"], ["e,", "by"], ["o e ua alofagia", "who favored"], ["e le Atua.", "God"]]},
  {num:5,words:[["Auā e lei oo atu la matou tala lelei", "for by not arrived our gospel"], ["ia te outou", "unto you"], ["na o le upu,", "the word"], ["a o le mana,", "but the to get"], ["ma le Agaga Paia,", "and the Holy Spirit"], ["atoa ma le mautinoa lava", "and the surely indeed"], ["ina ua outou iloa la matou amio", "so that you (all) knew our conduct"], ["ona o outou,", "because of you (all)"], ["a o matou", "but of we (excl)"], ["i ai", "therein"], ["ma outou;", "with you"]]},
  {num:6,words:[["sa outou faaa'oa'o", "you (all) made excellent"], ["mai foi ia te i matou,", "from also unto in we (excl)"], ["atoa ma le Alii,", "and the Lord"], ["ina ua outou talia", "so that you (all) received"], ["le upu", "the word"], ["i le puapuaga tele,", "in the affliction great"], ["ma le olioli", "and the rejoice"], ["mai le Agaga Paia;", "from the Holy Spirit"]]},
  {num:7,words:[["o lea", "therefore"], ["ua avea ai outou", "became you (all)"], ["ma faaa'oa'o", "and make excellent"], ["i e ua faatuatua uma lava o", "in by faith all indeed of"], ["i Maketonia", "in Maketonia"], ["atoa ma Akaia;", "and Achaia"]]},
  {num:8,words:[["auā ua logo atu", "for to hear"], ["nai ia te outou", "from unto you"], ["le afioga", "the word (divine)"], ["a le Alii,", "but the Lord"], ["e le gata", "by the a snake"], ["i Maketonia", "in Maketonia"], ["ma Akaia,", "and Achaia"], ["a ua salalau atu foi i mea uma lava", "but to be scattered also in all things"], ["le tala", "the side"], ["i lo outou faatuatua", "in the you (all) faith"], ["i le Atua o lea e le aoga ai", "in the God therefore by the useful"], ["sa matou upu", "we (excl) word"], ["e fai atu ai.", "to said to"]]},
  {num:9,words:[["Auā o", "for of"], ["i latou lava", "them indeed"], ["ua iloa ai le tala", "knew the side"], ["ia te i matou", "unto in we (excl)"], ["i le uiga o lo matou oo atu ia te outou", "in the kind our (excl) arrived unto you"], ["na,", "na,"], ["ma lo outou liliu", "and the you (all) turned"], ["mai i le Atua", "from in the God"], ["nai tupua,", "from pillar"], ["ina ia outou auauna", "so that you (all) servant"], ["i le Atua soifua", "in the God live"], ["ma le ua moni,", "and the true"]]},
  {num:10,words:[["ma ia faatali atu i lona Alo", "and to wait concerning his Son"], ["mai le lagi,", "from the heaven"], ["o le", "the"], ["na toe faatuina", "again built"], ["mai e ia", "from by him"], ["nai e ua oti,", "from the dead"], ["o Iesu lea,", "Jesus"], ["o lē laveai", "not deliver"], ["mai ia i tatou", "from to in we (incl)"], ["ai le toasa atali.", "the wrath atali"]]},
  {num:11,words:[["O lea ia outou", "therefore to you (all)"], ["feapoapoai ai,", "exhort one another"], ["ma ia fefaamafanafanai,", "and to comfort one another"], ["faapei ona outou faia lava.", "like then you (all) made indeed"]]},
  {num:12,words:[["Matou te aїoї atu foi ia te outou,", "we (excl) aїoї also unto you"], ["le au uso", "the I brother"], ["e,", "by"], ["ia outou iloa", "to you (all) know"], ["e o galulue ia te outou,", "by of labour unto you"], ["ma pule ia te outou", "and rule unto you"], ["i la le Alii,", "in the Lord"], ["ma latou apoapoai atu ia te outou;", "and they exhort unto you"], ["13 ia matuá mánatua", "13 to matuá mánatua"], ["i latou", "them"], ["ma le alofa,", "and the love"], ["ona o la latou galuega.", "because of their work"], ["la outou nonofo fefilemuai.", "your dwelling be at peace with one another"]]},
];
renderVerseSet(_1th_ch_1_Verses, '1th-ch1-verses');

var _1th_ch_2_Verses = [
  {num:1,words:[["Auā o outou lava,", "for of you (all) indeed"], ["le au uso", "the I brother"], ["e,", "by"], ["ua outou iloa", "you (all) knew"], ["o lo matou oo atu ia te outou,", "our (excl) arrived unto you"], ["e lei faaleaogaina lea;", "by not to make of no value"]]},
  {num:2,words:[["a e ui lava", "but to although indeed"], ["ina muamua", "so that first"], ["ona tigaina o", "and afflicted of"], ["i matou,", "in we (excl)"], ["ma faaleagaina", "and destroyed"], ["i Filipi,", "in Filipi"], ["pei ona", "like then"], ["outou iloa", "you (all) know"], ["ua matou faamalosi", "we (excl) was strong"], ["ona o lo tatou Atua e", "because of our God by"], ["tautala atu ia te outou", "spoke unto you"], ["i le tala lelei", "in the gospel"], ["a le Atua", "of God"], ["ma le finafinau tele lava.", "and the finafinau great indeed"]]},
  {num:3,words:[["Auā o lo matou apoapoai atu ia te outou", "for our (excl) exhort unto you"], ["e lei faia lea", "by not made"], ["ma le sese,", "and the wrong"], ["po o le amio leaga,", "night the iniquity"], ["po o le faa'ole'ole.", "night the deceit"]]},
  {num:4,words:[["A e peitai,", "but"], ["faapei ona tatau", "like then to wring out"], ["i le finagalo", "in the a chiefs will or desire"], ["o le Atua", "of God"], ["na te tuuina", "he given"], ["mai ia te i matou", "from in we (excl)"], ["le tala lelei,", "the gospel"], ["e faapea foi", "saying also"], ["ona matou tautala atu ai;", "and we (excl) spoke"], ["e le", "by the"], ["ina ia fiafia", "so that competition"], ["mai tagata,", "from man"], ["a o le Atua,", "but of God"], ["o lē tofotofo", "not to try"], ["mai i o matou", "from in of we (excl)"], ["loto.", "heart"]]},
  {num:5,words:[["Auā matou te lei fai", "for we (excl) not make"], ["lava se upu", "indeed a word"], ["e faaviivii atu ai,", "by faaviivii"], ["faapei ona outou iloa,", "like then you (all) know"], ["pe faia", "whether made"], ["se ufiufi", "a covering"], ["o le manumanu;", "the manumanu"], ["ua silafia", "known"], ["e le Atua;", "God"]]},
  {num:6,words:[["e ui lava", "to although indeed"], ["ina mafai ia te i matou", "so that able unto in we (excl)"], ["ona ia mafatia ai outou,", "and to the distribution of pro- you (all)"], ["auā o aposetolo", "for of apostle"], ["i matou", "in we (excl)"], ["a Keriso,", "of Christ"], ["a e matou te le saili", "but by we (excl) the seek"], ["le viiga mai tagata,", "the praise from man"], ["po o outou po o isi tagata.", "night of you (all) night of other man"]]},
  {num:7,words:[["A ua matou agamalu", "but we (excl) meek"], ["ina ua matou", "so that we (excl)"], ["i ai ia te outou", "therein unto you"], ["na,", "na,"], ["faapei o se failele", "like a nursing"], ["na te tausi lelei", "he nurse good"], ["i ana lava tama;", "in his indeed child"]]},
  {num:8,words:[["sa faapea lava lo matou maelega", "saying indeed our maelega"], ["i le alofa ia te outou,", "in the love unto you"], ["na matou manao", "we (excl) desired"], ["i le fia avatu ia te outou", "in the want to do something give away unto you"], ["e le", "by the"], ["na o le tala lelei", "the gospel"], ["i le Atua,", "in the God"], ["a o matou lava ola", "but of we (excl) indeed life"], ["foi,", "also"], ["auā na alofaina outou", "for beloved you (all)"], ["e i matou.", "by in we (excl)"]]},
  {num:9,words:[["Auā le au uso", "do not I brother"], ["e,", "by"], ["ua outou mānatua la matou galuega mamafa", "you (all) mānatua our work heavy"], ["ma le tiga;", "and the grieved"], ["auā sa matou galulue ai", "for we (excl) labour"], ["i le po", "in the night"], ["atoa ma le ao,", "and the day"], ["ina ne'i mafatia so outou,", "so that now the distribution of pro- so you (all)"], ["na matou tala'i atu ai ia te outou", "we (excl) preached unto you"], ["le tala lelei", "the gospel"], ["a le Atua.", "of God"]]},
  {num:10,words:[["Ua iloa outou", "knew you (all)"], ["atoa ma le Atua,", "and God"], ["sa matou amio Atua,", "we (excl) conduct God"], ["ma amiotonu,", "and righteous"], ["ma le", "and the"], ["le mata'uleagaina,", "the mata'uleagaina"], ["ina o matou", "so that of we (excl)"], ["i ai ia te outou", "therein unto you"], ["o e faatuatua.", "who faith"]]},
  {num:11,words:[["Pei ona", "like then"], ["outou iloa,", "you (all) know"], ["sa matou", "we (excl)"], ["i ai ia te outou", "therein unto you"], ["taitasi,", "each"], ["pei o le tamā", "like the father"], ["i lana lava fanau,", "in his indeed born"], ["na matou apoapoai atu ia te outou,", "we (excl) exhort unto you"], ["o faamafanafana atu foi,", "to hearten also"], ["ma ta'utino atu,", "and to hang near the body"]]},
  {num:12,words:[["ina ia outou savavali ia", "so that you (all) walked to"], ["tatau i le Atua,", "to wring out in the God"], ["o le", "the"], ["na valaauina outou", "called you (all)"], ["i lona malo", "in his government"], ["ma lona manuia.", "and his peace"]]},
  {num:13,words:[["O le mea lea matou", "therefore we (excl)"], ["te faafetai ai", "thank"], ["i le Atua,", "in the God"], ["o i matou lava", "in we (excl) indeed"], ["e le aunoa,", "by the without"], ["auā na talia e outou", "for received by you (all)"], ["le afioga", "the word (divine)"], ["a le Atua", "of God"], ["na outou faalogo", "you (all) hearken"], ["mai ai ia i matou,", "from to in we (excl)"], ["ua le talia e outou", "not received by you (all)"], ["o le upu", "the word"], ["a tagata,", "but man"], ["a e peitai", "but"], ["o le upu", "the word"], ["a le Atua,", "of God"], ["(e moni lava lea,)", "verily I say"], ["ua matuā galue foi lea", "exceedingly till also"], ["i totonu ia te outou", "in inside unto you"], ["o e faatuatua.", "who faith"]]},
  {num:14,words:[["Auā le au uso", "do not I brother"], ["e,", "by"], ["na outou faaa'oa'o", "you (all) made excellent"], ["i ekalesia", "in church"], ["a le Atua o", "of God"], ["i Iutaia,", "in Judea"], ["o loo ia Keriso Iesu;", "to Christ Jesus"], ["auā o outou foi", "for of you (all) also"], ["na tigaina outou", "afflicted you (all)"], ["i ia lava mea", "in to indeed thing"], ["i tagata", "in man"], ["o lo outou lava nuu,", "your indeed nation"], ["faapei ona tigaina o", "like then afflicted of"], ["i latou foi ia", "them also to"], ["Iutaia;", "Judea"]]},
  {num:15,words:[["o e", "who"], ["na fasioti", "killed"], ["i le Alii,", "in the Lord"], ["o Iesu lava,", "Jesus indeed"], ["atoa ma a latou", "and but they"], ["lava perofeta,", "indeed prophet"], ["na faasaua mai foi i latou ia i matou;", "cruel from also them to in we (excl)"], ["e le fiafia", "by the competition"], ["i ai le Atua,", "therein God"], ["ua fai foi tagata uma lava", "made also man all indeed"], ["mo latou fili;", "for they to choose"]]},
  {num:16,words:[["ua vavao mai ia i matou,", "to forbid from to in we (excl)"], ["aua matou te tautala atu i nuu ese,", "for we (excl) spoke in nation away"], ["ina ia faaolaina ai", "so that saved alive"], ["i latou;", "them"], ["ua faaatoa ai e i latou", "made together with by them"], ["e le aunoa", "by the without"], ["a latou agasala;", "but they sin"], ["a ua oo ia te i latou", "but it came to pass unto them"], ["le toasa", "the wrath"], ["e faaumatia ai.", "to destroyed"]]},
  {num:17,words:[["O i matou foi,", "in we (excl) also"], ["le au uso", "the I brother"], ["e,", "by"], ["o loo tete'aeseina o", "tete'aeseina of"], ["i matou", "in we (excl)"], ["ma outou", "with you"], ["i ni", "in some"], ["nai aso itiiti,", "from day small"], ["i le tino", "in the body"], ["a e le", "but by the"], ["o le loto,", "the heart"], ["ua atili ai", "more"], ["ona matou taumafaia", "and we (excl) taumafaia"], ["ma le naunau tele ona", "and the desire great then"], ["ia tatou feiloai", "to we (incl) meet one another"], ["ma outou.", "with you"]]},
  {num:18,words:[["O lea", "therefore"], ["na matou fia o atu ai ia te outou,", "we (excl) wanted to do something of unto you"], ["o a'u lava o Paulo,", "I am indeed of Paul"], ["ua atu tasi ma atu lua,", "one and two"], ["a ua faalavelave", "but a hindrance"], ["mai Satani ia te i matou.", "from Satan unto in we (excl)"]]},
  {num:19,words:[["Auā se a ea so matou", "for a but to rise (as a diver to the sur- so we (excl)"], ["faamoemoe,", "hope"], ["ma se fiafia,", "and a competition"], ["ma se pale", "and a to row"], ["e mitamita ai? E le", "to to boast by the"], ["o outou ea", "you (all) to rise (as a diver to the sur-"], ["i luma o lo tatou Alii o Iesu Keriso,", "before our Lord Jesus Christ"], ["i lona afio mai?", "in his dwell (respectful) from"]]},
  {num:20,words:[["Auā o outou lava o lo matou viiga", "for of you (all) indeed our (excl) praise"], ["ma lo matou olioli.", "and the we (excl) rejoice"]]},
];
renderVerseSet(_1th_ch_2_Verses, '1th-ch2-verses');

var _1th_ch_3_Verses = [
  {num:1,words:[["O lea", "therefore"], ["ua lelei ai ia te i matou", "that it was good unto in we (excl)"], ["ona ia tuua ai", "and to left"], ["i matou", "in we (excl)"], ["i Atenai,", "in Atenai"], ["tau o", "season of"], ["i matou,", "in we (excl)"], ["ina ua matou", "so that we (excl)"], ["le toe mafai ona", "the again able then"], ["onosai;", "patience"]]},
  {num:2,words:[["a ua matou auina atu Timoteo lo matou uso,", "but we (excl) sent Timothy our brother"], ["o le auauna foi o ia", "the servant also he"], ["a le Atua,", "of God"], ["o lē galue faatasi ma", "not till together and"], ["i matou", "in we (excl)"], ["i le tala lelei ia", "in the gospel to"], ["Keriso,", "Christ"], ["ina ia faatumauina outou", "so that established you (all)"], ["e ia,", "by him"], ["ma ia faamafanafana atu ia te outou", "and to to hearten unto you"], ["i lo outou faatuatua;", "in the you (all) faith"]]},
  {num:3,words:[["ina ne'i faagaeetia", "so that now faagaeetia"], ["se tasi", "a one"], ["i nei puapuaga;", "in this affliction"], ["auā ua outou iloa", "for you (all) knew"], ["ua tofia lenei lava mea.", "chosen this indeed thing"]]},
  {num:4,words:[["Auā foi", "for also"], ["o ona po", "then night"], ["sa i ai", "therein"], ["i matou ia te outou,", "in we (excl) unto you"], ["na matou muai fai atu ai ia te outou,", "we (excl) first said to unto you"], ["o le a oo mai le puapuaga,", "what came the affliction"], ["ua faapea ona", "saying and"], ["taunuu lava,", "fulfilled indeed"], ["ua outou iloa foi.", "you (all) knew also"]]},
  {num:5,words:[["O le mea lea", "therefore"], ["na ou", "I"], ["le toe mafai ai", "the again able"], ["ona onosai,", "and patience"], ["ona auina atu lea e a'u,", "and sent to I"], ["ina ia ou iloa lo outou faatuatua,", "so that I know your faith"], ["ne'i faaosoosoina outou", "now faaosoosoina you (all)"], ["e lē faaosooso,", "by not faaosooso"], ["ona faaleaogaina ai lea o la matou galuega.", "and to make of no value our work"]]},
  {num:6,words:[["A o lenei,", "but now"], ["ua sau Timoteo ia te i matou", "came Timothy unto in we (excl)"], ["nai ia te outou,", "from unto you"], ["ua au mai foi le tala lelei", "brought also the gospel"], ["ia te i matou", "unto in we (excl)"], ["i lo outou faatuatua,", "in the you (all) faith"], ["ma lo outou alofa,", "and the you (all) love"], ["ma lo outou manatu lelei", "and the you (all) thought good"], ["mai e le aunoa ia te i matou,", "from by the without unto in we (excl)"], ["o loo faanaunau foi outou", "make desire also you (all)"], ["ina ia tatou feiloai", "so that we (incl) meet one another"], ["ma outou,", "with you"], ["pei o", "like of"], ["i matou", "in we (excl)"], ["ona fia feiloai", "and want to do something meet one another"], ["ma outou;", "with you"]]},
  {num:7,words:[["o le mea lea,", "therefore"], ["le au uso", "the I brother"], ["e,", "by"], ["na faamafanafanaina mai ai", "comforted from"], ["i matou", "in we (excl)"], ["ona o outou,", "because of you (all)"], ["i lo matou puapuaga uma lava,", "in the we (excl) affliction all indeed"], ["atoa ma lo matou tiga,", "and our grieved"], ["ona o lo outou faatuatua.", "because of your faith"]]},
  {num:8,words:[["Auā o lenei,", "for now"], ["ua matou ola,", "we (excl) life"], ["pe afai tou te tumau", "whether if second person plural enduring"], ["i le Alii.", "in the Lord"]]},
  {num:9,words:[["Se a foi", "a but also"], ["se faafetai matou te mafaia", "a thank we (excl) able"], ["ona tuuina atu i le Atua", "and given in the God"], ["ona o outou,", "because of you (all)"], ["auā o le olioli uma lava matou", "for the rejoice all indeed we (excl)"], ["te olioli ai", "rejoice"], ["i luma o lo tatou Atua?", "before our God"]]},
  {num:10,words:[["o loo matou matuā ole atu ai", "we (excl) exceedingly entreat"], ["i le po", "in the night"], ["atoa ma le ao,", "and the day"], ["ina ia tatou feiloai", "so that we (incl) meet one another"], ["ma outou,", "with you"], ["e faaatoatoaina ai mea e lei", "to to complete thing by not"], ["atoa i lo outou faatuatua.", "together with in the you (all) faith"]]},
  {num:11,words:[["A ia ta'ita'iina la matou malaga", "but to led our travelling party"], ["ia te outou", "unto you"], ["e le Atua lava,", "God indeed"], ["lo tatou Tamā,", "our Father"], ["atoa ma lo tatou Alii o Iesu Keriso.", "and our Lord Jesus Christ"]]},
  {num:12,words:[["Ia faatele foi e le Alii,", "to make great also by the Lord"], ["ma ia faasilisili", "and to make very much"], ["ona tele o lo outou alofa,", "and great your love"], ["o le tasi", "the one"], ["i le tasi,", "in the one"], ["atoa ma tagata uma,", "and man all"], ["faapei o", "like of"], ["i matou nei lava ia te outou;", "in we (excl) this indeed unto you"]]},
  {num:13,words:[["ina ia faatumauina o outou", "so that established of you (all)"], ["loto e le mata'uleagaina", "heart by the mata'uleagaina"], ["i le amio lelei", "in the conduct good"], ["i luma o le Atua lo latou Tamā,", "before God their father"], ["pe a afio mai lo tatou Alii o Iesu Keriso,", "whether but dwell (respectful) from our Lord of Jesus Christ"], ["faatasi ma ona au paia uma.", "together and then saints all"]]},
];
renderVerseSet(_1th_ch_3_Verses, '1th-ch3-verses');

var _1th_ch_4_Verses = [
  {num:1,words:[["O lenei,", "now"], ["le au uso", "the I brother"], ["e,", "by"], ["o le toe upu lenei,", "the again word this"], ["matou te aioi atu", "we (excl) cry out"], ["ma apoapoai atu ia te outou", "and exhort unto you"], ["ona o le Alii o Iesu,", "because of the Lord of Jesus"], ["faapei ona talai e outou", "like then preach by you (all)"], ["mai ia te i matou", "from in we (excl)"], ["le uiga o le ala", "the kind the way"], ["e tatau ona", "should"], ["outou savavali ai,", "you (all) walked"], ["ia fiafia mai ai le Atua", "to competition from God"], ["ia te outou,", "unto you"], ["ia faasilisili pea i ai outou.", "to make very much continually therein you (all)"]]},
  {num:2,words:[["Auā ua outou iloa ia", "for you (all) knew to"], ["poloaiga na matou tuuina atu ai ia te outou", "commandment we (excl) given unto you"], ["mai le Alii o Iesu.", "from the Lord of Jesus"]]},
  {num:3,words:[["O le finagalo foi lenei", "the a chiefs will or desire also this"], ["o le Atua,", "of God"], ["ia faapaiaina outou,", "to consecrated you (all)"], ["ina ia faamamao outou", "so that make far you (all)"], ["ma le faitaaga;", "and the fornication"]]},
  {num:4,words:[["ia taitasi outou", "to each you (all)"], ["ma iloa", "and know"], ["ona fai", "and make"], ["o lana lava ipu", "his indeed cup"], ["ma le faapaiaina", "and the consecrated"], ["ma le ta'uleleia,", "and the ta'uleleia"]]},
  {num:5,words:[["aua ma le tu'inanau", "for and the tu'inanau"], ["o le manao,", "the desire"], ["faapei o nuu ese", "like of nation away"], ["ua le iloa", "not know"], ["le Atua.", "God"]]},
  {num:6,words:[["Aua ne'i sopo tapulaa", "for now to step over tapulaa"], ["se tasi,", "a one"], ["ma agaleaga", "and unkind"], ["i lona uso", "in his brother"], ["i lenei mea;", "in this thing"], ["auā o le Alii", "for the Lord"], ["na te taui atu", "he a reward"], ["ma sui", "and to dilute"], ["i nei mea uma,", "these things all"], ["faapei ona matou muai fai atu ai,", "like then we (excl) first said to"], ["ma ta'utino atu ia te outou.", "and to hang near the body unto you"]]},
  {num:7,words:[["Auā e lei valaauina", "for by not called"], ["i tatou", "in we (incl)"], ["e le Atua ia", "God to"], ["amio leaga,", "iniquity/wickedness"], ["a ia faapaiaina lava.", "but to consecrated indeed"]]},
  {num:8,words:[["O lenei,", "now"], ["o lē faaleaoga", "not to make of no value"], ["mai,", "from"], ["ua ia le faaleaoga", "to the to make of no value"], ["i tagata,", "in man"], ["a o le Atua le ua foai", "but of God the gave"], ["mai lona Agaga Paia ia te i matou.", "from his Holy Spirit unto in we (excl)"]]},
  {num:9,words:[["A e le aoga", "but by the useful"], ["ona ou tusi atu ia te outou", "and I book unto you"], ["i le mataupu", "in the chapter"], ["o le alofa", "the love"], ["i le au uso;", "in the I brother"], ["auā ua a'oa'oina outou", "for taught you (all)"], ["lava e le Atua ia", "indeed God to"], ["fealofani.", "fealofani"]]},
  {num:10,words:[["Auā foi", "for also"], ["ua faapea lava ona", "and it was so and"], ["outou faia", "you (all) made"], ["i le au uso uma lava o", "in the I brother all indeed of"], ["i Maketonia", "in Maketonia"], ["atoa uma.", "together with all"], ["A e matou te apoapoai atu ia te outou", "but by we (excl) exhort unto you"], ["le au uso", "the I brother"], ["e,", "by"], ["ia faasilisili pea i ai;", "to make very much continually therein"]]},
  {num:11,words:[["ma ia outou taumafai", "and to you (all) to strive"], ["ina ia outou nofo fifilemu,", "so that you (all) dwell fifilemu"], ["ia faia", "to made"], ["a outou lava feau,", "but you (all) indeed errand"], ["ma ia galulue", "and to labour"], ["i o outou lava lima,", "in of you (all) indeed five"], ["pei ona", "like then"], ["matou fai atu ai ia te outou;", "we (excl) said to unto you"]]},
  {num:12,words:[["ina ia outou savavali", "so that you (all) walked"], ["ma le matagofie", "and the beautiful"], ["i e o", "in by of"], ["i tuā,", "in tuā"], ["ma ia le matitiva outou", "and to the poor you (all)"], ["i se mea e tasi.", "in a thing by one"]]},
  {num:13,words:[["Ou te loto", "I will heart"], ["ina ia outou iloa,", "so that you (all) know"], ["le au uso", "the I brother"], ["e,", "by"], ["i le mataupu", "in the chapter"], ["i e o momoe,", "in by of lie down"], ["ina ne'i outou faanoanoa,", "so that now you (all) mourn"], ["pei o isi", "like of other"], ["e leai so latou", "there is not so they"], ["faamoemoe.", "hope"]]},
  {num:14,words:[["Auā afai tatou te talitonu,", "for if we will believe"], ["ua maliu Iesu", "died Jesus"], ["ma toe tu mai,", "and resurrection"], ["e faapea foi", "saying also"], ["ona aumaia", "and bring here"], ["e le Atua faatasi ma ia", "God with him"], ["e o momoe", "by of lie down"], ["ona o Iesu.", "because of Jesus"]]},
  {num:15,words:[["Matou te fai atu foi lenei mea", "we (excl) said to also this thing"], ["ia te outou", "unto you"], ["i le afioga", "the word"], ["a le Alii,", "but the Lord"], ["o i tatou", "in we (incl)"], ["o e ola", "who life"], ["ma totoe", "and phiral of foe"], ["pe a afio mai le Alii,", "whether but dwell (respectful) from the Lord"], ["tatou te le muamua", "we will the first"], ["i e o momoe.", "in by of lie down"]]},
  {num:16,words:[["Auā e afio ifo", "for to dwell (respectful) down"], ["mai le lagi", "from the heaven"], ["le Alii lava,", "the Lord indeed"], ["ma le alaga,", "and the cry"], ["ma le leo", "and the voice"], ["o le agelu sili,", "the angel most"], ["ma le pu", "and the the tail"], ["a le Atua;", "of God"], ["e muamua foi", "to first also"], ["ona toe tutū", "and again stood up"], ["mai o e ua oti", "from who died"], ["o ia Keriso;", "he Christ"]]},
  {num:17,words:[["ona faafuasei lea", "and faafuasei"], ["ona aveina", "and taken away"], ["ae o", "but of"], ["i tatou", "in we (incl)"], ["o e ola", "who life"], ["ma totoe,", "and phiral of foe"], ["faatasi ma", "together and"], ["i latou", "them"], ["i ao,", "in day"], ["ina ia fetaiai", "so that meet one another"], ["ma le Alii", "and the Lord"], ["i le va nimonimo;", "in the expanse firmament"], ["ona tatou faatasi pea lava lea", "and we (incl) together continually indeed"], ["ma le Alii.", "and the Lord"]]},
  {num:18,words:[["O lenei,", "now"], ["ia outou fefaamafanafanai", "to you (all) comfort one another"], ["i nei upu.", "in this word"]]},
];
renderVerseSet(_1th_ch_4_Verses, '1th-ch4-verses');

var _1th_ch_5_Verses = [
  {num:1,words:[["A o aso", "but of day"], ["ma tausaga,", "and years"], ["e le aoga ia te outou,", "by the useful unto you"], ["le au uso", "the I brother"], ["e,", "by"], ["ona ou tusi atu ai ia te outou.", "and I book unto you"]]},
  {num:2,words:[["Auā ua outou iloa lelei lava,", "for you (all) knew good indeed"], ["o le aso", "the day"], ["o le Alii e pei o le gaoi", "the Lord like the to steal"], ["i le po,", "in the night"], ["e faapea ona", "saying and"], ["oo mai ai;", "came"], ["auā pe a latou fai ane.", "for whether but they said"]]},
  {num:3,words:[["O loo filemu,", "peace"], ["ua le afaina,", "not the name of a tree"], ["ona oo lea ia te i latou", "and oo unto them"], ["o le fano faafuasei,", "the perish faafuasei"], ["faapei o le faatiga", "like the afflict"], ["o le fafine to", "the woman to plant"], ["a fanau mai,", "but born"], ["latou te le sosola ai lava.", "they will the fled indeed"]]},
  {num:4,words:[["A o outou,", "but of you (all)"], ["le au uso", "the I brother"], ["e,", "by"], ["tou te le o", "second person plural the of"], ["i le pouliuli,", "in the darkness"], ["ia maua mai ai outou", "to received from you (all)"], ["e lena aso,", "by that day"], ["pei o se gaoi.", "like a to steal"]]},
  {num:5,words:[["O tagata", "of men"], ["o le malamalama outou uma lava,", "the light all of you"], ["ma tagata", "and people"], ["o le ao;", "Day"], ["tatou te le o", "we will the of"], ["i le po", "in the night"], ["ma le pouliuli.", "and the darkness"]]},
  {num:6,words:[["O lea,", "therefore"], ["aua ne'i tatou momoe ai faapei", "for now we (incl) lie down like"], ["o isi,", "other"], ["a ia tatou mataala,", "but to we (incl) mataala"], ["ma ia faautauta.", "and to careful"]]},
  {num:7,words:[["Auā o e momoe,", "for who lie down"], ["e momoe", "to lie down"], ["i latou", "them"], ["i le po;", "in the night"], ["o e inu ia", "who drink to"], ["onā,", "drunk"], ["e onā", "to drunk"], ["i latou", "them"], ["i le po;", "in the night"]]},
  {num:8,words:[["a o", "but of"], ["i tatou nei o e", "in we (incl) this who"], ["o le ao,", "Day"], ["ia faautauta", "to careful"], ["i tatou,", "in we (incl)"], ["ia tatou oofu", "to we (incl) oofu"], ["i le ufifatafata", "in the breastplate"], ["o le faatuatua", "the faith"], ["ma le alofa,", "and the love"], ["ma le puloutau", "and the puloutau"], ["o le faamoemoe", "the hope"], ["i le ola.", "in the life"]]},
  {num:9,words:[["Auā e lei tofia", "for by not chosen"], ["i tatou", "in we (incl)"], ["e le Atua i le toasa,", "God in the wrath"], ["a ia maua", "but to received"], ["le ola", "the life"], ["ona o lo tatou Alii o Iesu Keriso,", "because of our Lord Jesus Christ"]]},
  {num:10,words:[["o le", "the"], ["na maliu", "died"], ["e sui a'i tatou,", "to to dilute we (incl)"], ["ina ia tatou ola faatasi ma ia,", "so that we (incl) life with him"], ["pe tatou te mataala,", "whether we will mataala"], ["pe tatou te momoe.", "whether we will lie down"]]},
  {num:11,words:[["O lea ia outou", "therefore to you (all)"], ["feapoapoai ai,", "exhort one another"], ["ma ia fefaamafanafanai,", "and to comfort one another"], ["faapei ona outou faia lava.", "like then you (all) made indeed"]]},
  {num:12,words:[["Matou te aioi atu foi ia te outou,", "we (excl) cry out also unto you"], ["le au uso", "the I brother"], ["e,", "by"], ["ia outou iloa", "to you (all) know"], ["e o galulue ia te outou,", "by of labour unto you"], ["ma pule ia te outou", "and rule unto you"], ["i la le Alii,", "in the Lord"], ["ma latou apoapoai atu ia te outou;", "and they exhort unto you"]]},
  {num:13,words:[["ia matuā mānatua", "to exceedingly mānatua"], ["i latou", "them"], ["ma le alofa,", "and the love"], ["ona o la latou galuega.", "because of their work"], ["Ia outou nonofo fefilemuai.", "to you (all) dwelling be at peace with one another"]]},
  {num:14,words:[["Matou te aioi atu foi ia te outou,", "we (excl) cry out also unto you"], ["le au uso", "the I brother"], ["e,", "by"], ["ia outou apoapoai atu i", "to you (all) exhort in"], ["e amio faapiopio,", "to conduct faapiopio"], ["ia faamafanafana", "to to hearten"], ["i e loto iti,", "in to heart small"], ["ia fesoasoani", "to to help"], ["i e o vaivai,", "in by of weak"], ["ia outou onosai", "to you (all) patience"], ["i tagata uma lava.", "in man all indeed"]]},
  {num:15,words:[["Ia outou,", "to you (all)"], ["ne'i taui atu e se tasi", "now a reward by a one"], ["le leaga", "the evil"], ["i le leaga", "in the evil"], ["i se tasi tagata,", "in a one man"], ["a ia outou tausisi", "but to you (all) tausisi"], ["e le aunoa", "by the without"], ["i le mea lelei,", "in the thing good"], ["o le tasi", "the one"], ["i le tasi,", "in the one"], ["atoa ma tagata uma lava.", "and man all indeed"]]},
  {num:16,words:[["Ia outou saga olioli pea", "to you (all) saga rejoice continually"], ["lava.", "indeed"]]},
  {num:17,words:[["Ia tatalo", "to pray"], ["e le aunoa.", "by the without"]]},
  {num:18,words:[["Ia outou faafetai", "to you (all) thank"], ["i mea uma lava,", "in all things"], ["auā o le finagalo lea o le Atua", "for the a chiefs will or desire of God"], ["ia te outou,", "unto you"], ["ia Keriso Iesu.", "to Christ Jesus"]]},
  {num:19,words:[["Aua tou te tineia", "for second person plural tineia"], ["le Agaga.", "the spirit"]]},
  {num:20,words:[["Aua le ta'ufaatauvaa", "for the ta'ufaatauvaa"], ["i perofetaga.", "in perofetaga"]]},
  {num:21,words:[["Ia tofotofo", "to to try"], ["i mea uma lava,", "in all things"], ["ia taofi mau", "to hold opinion"], ["i le mea lelei.", "in the thing good"]]},
  {num:22,words:[["Ia mamao outou", "to far you (all)"], ["ma mea leaga eseese uma lava.", "and thing evil divided all indeed"]]},
  {num:23,words:[["Ia atoatoa", "to completely"], ["ona faapaiaina o outou", "and consecrated of you (all)"], ["e le Atua lava", "God indeed"], ["e ona", "by then"], ["le manuia;", "the peace"], ["ia tausia lava lo outou agaga", "to nursed indeed your spirit"], ["atoa uma,", "together with all"], ["i le", "in the"], ["ma le loto,", "and the heart"], ["atoa ma le tino,", "and the body"], ["ia le mata'uleagaina,", "to the mata'uleagaina"], ["i le afio mai o lo tatou Alii o Iesu Keriso.", "in the dwell (respectful) from our Lord of Jesus Christ"]]},
  {num:24,words:[["E faamaoni lava o le ua valaauina outou,", "to faithful indeed the called you (all)"], ["o le", "the"], ["na te faia lava.", "he made indeed"]]},
  {num:25,words:[["Le au uso", "the I brother"], ["e,", "by"], ["ia outou tatalo", "to you (all) pray"], ["mo i matou.", "for in we (excl)"]]},
  {num:26,words:[["Ia alolofa atu i le au", "to alolofa in the I"], ["uso uma", "brother all"], ["i le feasogi paia.", "in the to salute by rubbJDg holy"]]},
  {num:27,words:[["Ou te matuā fai atu ia te outou", "I will exceedingly said to unto you"], ["i le suafa", "in the name"], ["o le Alii,", "the Lord"], ["ia faitaulia lenei tusi", "to counted this book"], ["i le au uso paia uma lava.", "in the I brother holy all indeed"]]},
  {num:28,words:[["Ia ia te outou", "to him you (all)"], ["le alofa tunoa", "grace"], ["o lo tatou Alii o Iesu Keriso.", "our Lord of Jesus Christ"], ["Amene.", "amen"]]},
];
renderVerseSet(_1th_ch_5_Verses, '1th-ch5-verses');

})();