(function() {
var _2jn_ch_1_Verses = [
  {num:1,words:[["O a'u", "I am"], ["o le toeaina,", "the elder"], ["o la'u tusi lenei", "this letter"], ["i le tamaitai", "in the woman"], ["ua filifilia,", "chosen"], ["ma ana tama,", "and his child"], ["ou te alofa faamaoni", "I love faithful"], ["i ai;", "therein"], ["e le", "by the"], ["na o a'u foi,", "I am also"], ["a o", "but of"], ["i latou uma o", "them all of"], ["e ua iloa", "by knew"], ["le upu moni;", "the word true"]]},
  {num:2,words:[["ona o le upu moni", "because of the word true"], ["o loo tumau ia te", "endure unto"], ["i tatou,", "in we (incl)"], ["e ia te", "by him"], ["i tatou foi", "in we (incl) also"], ["e faavavau.", "forever/everlasting"]]},
  {num:3,words:[["Ia ia te outou", "to him you (all)"], ["le alofa tunoa,", "grace"], ["ma le alofa", "and the love"], ["ma le manuia", "and peace"], ["mai le Atua", "from God"], ["le Tamā,", "the father"], ["atoa ma le Alii o Iesu Keriso,", "and the Lord Jesus Christ"], ["o le Alo", "the Son"], ["o le Tamā,", "the father"], ["i le faamaoni", "in the faithful"], ["atoa ma le alofa.", "and the love"]]},
  {num:4,words:[["E tele lava lo'u fiafia", "to great indeed my competition"], ["ina ua ou iloa ni au", "let I known some I"], ["fanau o", "born of"], ["e savavali", "to walked"], ["i le upu moni,", "in the word true"], ["faapei o le poloaiga", "like the commandment"], ["ua tatou maua", "we (incl) received"], ["mai le Tamā.", "from the father"]]},
  {num:5,words:[["O lenei,", "this"], ["le tamaitai e,", "the woman by"], ["ou te aioi atu ia te oe,", "I cry out unto you"], ["(ou te", "I"], ["le tusi atu ia te oe", "the book unto you"], ["e peiseai", "to as if"], ["o se poloaiga fou,", "a commandment new"], ["a o lea lava", "but therefore indeed"], ["ua ia te", "unto"], ["i tatou talu", "in we (incl) since"], ["le amataga.)", "the beginning"], ["ia tatou fealofani.", "to we (incl) fealofani"]]},
  {num:6,words:[["O lenei lava", "this indeed"], ["le alofa,", "the love"], ["ia tatou savavali", "to we (incl) walked"], ["e tatau", "it is fitting/ought"], ["ma ana poloaiga;", "and his commandment"], ["o lenei lava", "this indeed"], ["le poloaiga,", "the commandment"], ["faapei ona outou faalogo", "like then you (all) hearken"], ["i ai talu", "therein since"], ["le amataga,", "the beginning"], ["ina ia outou savavali ai.", "so that you (all) walked"]]},
  {num:7,words:[["Auā e toatele o", "for many of"], ["e faasese", "to to cause to go astray"], ["ua o atu", "of"], ["i le lalolagi,", "on the earth"], ["o e le ta'u tino", "who the tell body"], ["ua maliu mai Iesu Keriso", "die from Jesus Christ"], ["i le tino;", "in the body"], ["o le faasese lava lea", "the to cause to go astray indeed"], ["ma le anetikeriso.", "and the anetikeriso"]]},
  {num:8,words:[["Ia outou ia te outou,", "to you (all) unto you"], ["ne'i maumau", "now maumau"], ["a matou galuega", "but we (excl) work"], ["na matou faia,", "we (excl) made"], ["a ia maua", "but to received"], ["le taui", "the a reward"], ["atoa.", "together with"]]},
  {num:9,words:[["O i latou uma lava", "them all indeed"], ["o e tuumavaega,", "who covenant breakii"], ["a e le tumau", "but by the endure"], ["i le mataupu ia", "in the chapter to"], ["Keriso,", "Christ"], ["e le o ia te", "by the he"], ["i latou", "them"], ["le Atua;", "God"], ["o lē tumau", "not endure"], ["i le mataupu ia", "in the chapter to"], ["Keriso,", "Christ"], ["e ia te ia", "by him to"], ["lava le Tamā", "indeed the father"], ["atoa ma le Alo.", "and the Son"]]},
  {num:10,words:[["Pe a alu atu ia te outou", "whether but go away unto you"], ["se tasi", "a one"], ["a e le molia lenei", "but by the accused this"], ["lava mataupu,", "indeed chapter"], ["aua tou te talia o ia", "for second person plural received he"], ["i o outou fale,", "in of you (all) house"], ["aua foi tou te ofo alofa", "for also second person plural n love"], ["ia te ia;", "to him"]]},
  {num:11,words:[["auā o sē ofo alofa atu", "for of sē n love"], ["ia te ia,", "to him"], ["e faatasi ai o ia", "to once he"], ["ma ana galuega leaga.", "and his work evil"]]},
  {num:12,words:[["O ia te au", "he I"], ["mea e tele", "great things"], ["e tusi atu ai ia te outou,", "to book unto you"], ["a ou te", "but I"], ["le fia tusi atu", "the want to do something book"], ["i le laupepa", "in the laupepa"], ["ma le vaitusi;", "and the ink"], ["a ou te faamoemoe ou te alu atu", "but I to expect I go away"], ["ia te outou,", "unto you"], ["ia tatou fetautalatalai,", "to we (incl) fetautalatalai"], ["ina ia atoatoa ai lo tatou fiafia.", "so that completely our competition"]]},
  {num:13,words:[["O loo alolofa atu ia te oe", "alolofa unto you"], ["tama a lou uso", "child but your brother"], ["ua filifilia.", "chosen"], ["Amene.", "amen"]]},
];
renderVerseSet(_2jn_ch_1_Verses, '2jn-ch1-verses');

})();