(function() {
var _2jn_ch_1_Verses = [
  {num:1,words:[["O a'u", "I am"], ["o le toeaina,", "the elder"], ["o la'u tusi lenei", "this letter"], ["i le tamaitai", "in the woman"], ["ua filifilia,", "chosen"], ["ma ana tama,", "and his child"], ["ou te alofa faamaoni", "I will love faithful"], ["i ai;", "therein"], ["e le", "by the"], ["na", "na"], ["o a'u foi,", "I am also"], ["a o", "but of"], ["i latou uma", "them all"], ["o", "o"], ["e ua iloa", "by knew"], ["le upu moni;", "the word true"]]},
  {num:2,words:[["ona", "and"], ["o le upu moni", "the word true"], ["o loo tumau", "enduring"], ["ia te", "unto"], ["i tatou,", "in we (incl)"], ["e ia te", "by him"], ["i tatou foi", "in we (incl) also"], ["e faavavau.", "forever/everlasting"]]},
  {num:3,words:[["Ia ia te outou", "to him you (all)"], ["le alofa tunoa,", "grace"], ["ma le alofa", "and the love"], ["ma le manuia", "and peace"], ["mai le Atua", "from God"], ["le Tamā,", "the father"], ["atoa ma le Alii", "and the Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["o le Alo", "the Son"], ["o le Tamā,", "the father"], ["i le faamaoni", "in the faithful"], ["atoa ma le alofa.", "and the love"]]},
  {num:4,words:[["E tele lava", "to great indeed"], ["lo'u fiafia", "my competition"], ["ina", "so that"], ["ua ou iloa", "I knew"], ["ni au fanau", "some I born"], ["o", "o"], ["e savavali", "to walked"], ["i le upu moni,", "in the word true"], ["faapei", "like"], ["o le poloaiga", "the commandment"], ["ua tatou maua", "we (incl) received"], ["mai le Tamā.", "from the father"]]},
  {num:5,words:[["O lenei,", "now"], ["le tamaitai e,", "the woman by"], ["ou te aioi atu", "I will cry out"], ["ia te oe,", "unto you"], ["(ou te", "I will"], ["le tusi atu", "the book"], ["ia te oe", "unto you"], ["e peiseai", "to as if"], ["o se poloaiga fou,", "a commandment new"], ["a o lea", "but therefore"], ["lava", "indeed"], ["ua ia te", "unto"], ["i tatou talu", "in we (incl) since"], ["le amataga.)", "the beginning"], ["ia tatou fealofani.", "to we (incl) fealofani"]]},
  {num:6,words:[["O lenei", "now"], ["lava", "indeed"], ["le alofa,", "the love"], ["ia tatou savavali", "to we (incl) walked"], ["e tatau", "it is fitting/ought"], ["ma ana poloaiga;", "and his commandment"], ["o lenei", "now"], ["lava", "indeed"], ["le poloaiga,", "the commandment"], ["faapei", "like"], ["ona outou faalogo", "and you (all) hearken"], ["i ai", "therein"], ["talu", "since"], ["le amataga,", "the beginning"], ["ina ia outou", "so that you (all)"], ["savavali ai.", "walked"]]},
  {num:7,words:[["Auā", "for"], ["e toatele o", "many"], ["e faasese", "to to cause to go astray"], ["ua o atu", "of"], ["i le lalolagi,", "on the earth"], ["o", "o"], ["e le ta'u tino", "by the tell body"], ["ua maliu mai", "died from"], ["Iesu Keriso", "Jesus Christ"], ["i le tino;", "in the body"], ["o le faasese", "the to cause to go astray"], ["lava lea", "indeed"], ["ma le anetikeriso.", "and the anetikeriso"]]},
  {num:8,words:[["Ia outou ia te outou,", "to you (all) unto you"], ["ne'i maumau", "now maumau"], ["a matou galuega", "but we (excl) work"], ["na matou faia,", "we (excl) made"], ["a ia maua", "but to received"], ["le taui", "the a reward"], ["atoa.", "together with"]]},
  {num:9,words:[["O", "O"], ["i latou uma lava", "them all indeed"], ["o", "o"], ["e tuumavaega,", "to covenant breakii"], ["a", "but"], ["e le tumau", "by the enduring"], ["i le mataupu", "in the chapter"], ["ia Keriso,", "to Christ"], ["e le o ia te", "by the he"], ["i latou", "them"], ["le Atua;", "God"], ["o lē tumau", "not enduring"], ["i le mataupu", "in the chapter"], ["ia Keriso,", "to Christ"], ["e ia te ia", "by him to"], ["lava", "indeed"], ["le Tamā", "the father"], ["atoa ma le Alo.", "and the Son"]]},
  {num:10,words:[["Pe a alu atu", "even though / although go away"], ["ia te outou", "unto you"], ["se tasi", "a one"], ["a", "but"], ["e le molia lenei", "by the accused this"], ["lava mataupu,", "indeed chapter"], ["aua tou te talia", "for second person plural received"], ["o ia", "he"], ["i o outou", "in of you (all)"], ["fale,", "house"], ["aua foi", "for also"], ["tou te ofo alofa", "second person plural n love"], ["ia te ia;", "to him"]]},
  {num:11,words:[["auā o sē ofo alofa atu", "for of sē n love"], ["ia te ia,", "to him"], ["e faatasi ai", "to together"], ["o ia", "he"], ["ma ana galuega leaga.", "and his work evil"]]},
  {num:12,words:[["O ia te au", "he I"], ["mea e tele", "great things"], ["e tusi atu ai", "to book"], ["ia te outou,", "unto you"], ["a ou te", "but I will"], ["le fia tusi atu", "the want to do something book"], ["i le laupepa", "in the laupepa"], ["ma le vaitusi;", "and the ink"], ["a ou te faamoemoe ou te alu atu", "but I will hope I will go away"], ["ia te outou,", "unto you"], ["ia tatou fetautalatalai,", "to we (incl) converse with one another"], ["ina ia atoatoa ai", "so that completely"], ["lo tatou fiafia.", "our competition"]]},
  {num:13,words:[["O loo alolofa atu", "alolofa"], ["ia te oe", "unto you"], ["tama", "child"], ["a lou uso", "but your brother"], ["ua filifilia.", "chosen"], ["Amene.", "amen"]]},
];
renderVerseSet(_2jn_ch_1_Verses, '2jn-ch1-verses');

})();