(function() {
var _2th_ch_1_Verses = [
  {num:1,words:[["O", "O"], ["i matou ,", "in we (excl)"], ["o Paulo,", "Paul"], ["ma Siluano,", "and Siluano"], ["ma Timoteo,", "and Timothy"], ["o la matou tusi lenei", "our book this"], ["i le ekalesia", "in the church"], ["o tagata Tesalonia,", "of men Tesalonia"], ["o", "o"], ["i le Atua lo tatou Tamā,", "in the God our Father"], ["ma le Alii", "and the Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
  {num:2,words:[["Ia ia te outou", "to him you (all)"], ["le alofa tunoa", "grace"], ["ma le manuia", "and peace"], ["mai le Atua lo tatou Tamā,", "from God our Father"], ["ma le Alii", "and the Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
  {num:3,words:[["E tatau ona", "should"], ["matou faafetai", "we (excl) thank"], ["e le aunoa", "shall not without"], ["i le Atua", "in the God"], ["ona o outou,", "because of you (all)"], ["le au uso e,", "the me brother by"], ["e faapei", "to like"], ["ona tusa,", "and according to"], ["auā", "for"], ["ua tupu tele lava", "king great indeed"], ["lo outou faatuatua,", "your faith"], ["ua faateleina foi", "multiplied also"], ["lo outou fealofani", "your fealofani"], ["o outou uma lava taitoatasi.", "all of you each one"]]},
  {num:4,words:[["O lea", "therefore"], ["matou te mitamita ai", "we (excl) to boast"], ["ia te outou", "unto you"], ["o", "o"], ["i matou nei", "in we (excl) this"], ["lava,", "indeed"], ["i ekalesia", "in church"], ["a le Atua,", "of God"], ["ona", "and"], ["o lo outou onosai", "your patience"], ["ma lo outou faatuatua,", "and the you (all) faith"], ["i ona po", "in then night"], ["o sauaga uma", "sauaga all"], ["ma puapuaga", "and affliction"], ["ua outou faatoatoa ai;", "you (all) faatoatoa"]]},
  {num:5,words:[["o le faailoga lea", "the sign"], ["o le faamasinoga tonu", "the judgment right"], ["a le Atua,", "of God"], ["ina ia ta'uaogaina outou", "so that ta'uaogaina you (all)"], ["i le malo", "in the government"], ["o le Atua,", "of God"], ["o le mea lea", "therefore"], ["e tigaina ai", "to afflicted"], ["outou.", "you (all)"]]},
  {num:6,words:[["Auā", "for"], ["ua tonu", "right"], ["i le Atua e", "in the God by"], ["taui atu", "a reward"], ["le puapuaga", "the affliction"], ["i", "in"], ["e ua faapuapuagaina ai", "by made affliction"], ["outou;", "you (all)"]]},
  {num:7,words:[["e ia te outou", "by him you (all)"], ["foi o", "also of"], ["e puapuagaina,", "to affliction"], ["o le mapusaga faatasi ma", "the a resting place together and"], ["i matou,", "in we (excl)"], ["pe a faaalia", "even though / although revealed"], ["le Alii o Iesu", "the Lord of Jesus"], ["mai le lagi,", "from the heaven"], ["faatasi ma agelu", "together and angel"], ["o lona malosi,", "his strong"], ["i le afi mumū,", "in the fire mumū"]]},
  {num:8,words:[["na te taui", "he a reward"], ["ma sui", "and to dilute"], ["i", "in"], ["e ua", "by"], ["le iloa", "the know"], ["le Atua,", "God"], ["ma", "and"], ["ua", "ua"], ["le anaana", "the his own"], ["i le tala lelei", "in the gospel"], ["a lo tatou Alii", "but our Lord"], ["o Iesu Keriso;", "Jesus Christ"]]},
  {num:9,words:[["e faasalaina", "to punished"], ["i latou lava", "them indeed"], ["i le fanoga", "in the fanoga"], ["e faavavau lava,", "forever and ever"], ["ia te'a", "to depart"], ["ma le Alii", "and the Lord"], ["ma le mamalu", "and the glory"], ["o lona malosi;", "his strong"]]},
  {num:10,words:[["pe a afio mai", "even though / although dwell (respectful) from"], ["o ia", "he"], ["ina ia viia", "so that praised"], ["i ona lava tagata paia,", "in then indeed saints"], ["ma ia ofo", "and to n"], ["ia te ia", "to him"], ["i lena", "in that"], ["aso ia te", "day unto"], ["i latou uma", "them all"], ["o", "o"], ["e faatuatua,", "to faith"], ["auā", "for"], ["na outou talitonu mai lava", "you (all) believed from indeed"], ["i la matou mau.", "in our opinion"]]},
  {num:11,words:[["O le mea foi", "the thing also"], ["lea matou te faatoga atu ai", "we (excl) order"], ["e le aunoa", "shall not without"], ["mo outou,", "for you"], ["ina ia ta'uaogaina outou", "so that ta'uaogaina you (all)"], ["e lo tatou Atua", "by our God"], ["ia valaauina,", "to called"], ["ma ia faaatoatoaina", "and to to complete"], ["e ia", "by him"], ["ma le malosi", "and the strong"], ["le loto fiafia uma", "the heart competition all"], ["o le agalelei,", "the treated well"], ["ma le galuega", "and the work"], ["a le faatuatua;", "but the faith"]]},
  {num:12,words:[["ina ia viia", "so that praised"], ["ona o outou", "because of you (all)"], ["le suafa", "the name"], ["o lo tatou Alii", "our Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["ma outou foi", "with you also"], ["ona o ia,", "because of to"], ["e tusa ma le alofa tunoa", "according to grace"], ["o lo tatou Atua,", "our God"], ["ma le Alii", "and the Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
];
renderVerseSet(_2th_ch_1_Verses, '2th-ch1-verses');

var _2th_ch_2_Verses = [
  {num:1,words:[["O lenei,", "now"], ["matou te aioi atu", "we (excl) cry out"], ["ia te outou,", "unto you"], ["le au uso e,", "the me brother by"], ["i le mataupu", "in the chapter"], ["i le afio mai", "in the dwell (respectful) from"], ["o lo tatou Alii", "our Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["ma lo tatou faapotopotoina", "and the we (incl) gathered together"], ["ia te ia;", "to him"]]},
  {num:2,words:[["ina ne'i vave luluina", "so that now quick shaken"], ["o outou loto,", "you (all) heart"], ["pe faaatuatuvaleina", "whether make to be greatly dis-"], ["i se agaga,", "in a spirit"], ["po", "night"], ["o se upu,", "a word"], ["po", "night"], ["o se tusi,", "a book"], ["peiseai", "as if"], ["nai ia", "from to"], ["i matou,", "in we (excl)"], ["peiseai", "as if"], ["ua oo mai le aso", "it came to pass from the day"], ["o Keriso.", "Christ"]]},
  {num:3,words:[["Aua ne'i faasese", "for now to cause to go astray"], ["se tasi ia te outou", "a one unto you"], ["i se togafiti", "in a heal"], ["e tasi;", "by one"], ["auā", "for"], ["e le oo mai lena", "by the came that"], ["aso ,", "day"], ["seia muai", "until first"], ["ona taunuu", "and fulfilled"], ["o le tete'a ese,", "the light colored : as away"], ["ma ia faaalia", "and to revealed"], ["mai", "from"], ["o le tagata", "man"], ["o le agasala,", "the sin"], ["o le tagata lea", "man"], ["o le malaia,", "the disaster"]]},
  {num:4,words:[["o lē tetee atu,", "not to refuse"], ["ma faamaualugaina e", "and exalted by"], ["ia ia te ia", "to him to"], ["e sili", "to most"], ["i mea uma lava", "in all things"], ["ua ta'uatuaina,", "ta'uatuaina"], ["ma mea uma", "and all things"], ["ua ifo", "down"], ["i ai", "therein"], ["tagata ,", "man"], ["o lea", "therefore"], ["ua tietie ai", "rode"], ["o ia", "he"], ["i le malumalu", "in the temple"], ["o le Atua,", "of God"], ["peiseai", "as if"], ["o le Atua", "of God"], ["o ia,", "he"], ["o loo faaali mai", "is/are (progressive) revealed"], ["o ia,", "he"], ["o le Atua", "of God"], ["lava o ia.", "indeed he"]]},
  {num:5,words:[["Tou te", "second person plural"], ["le manatu ea,", "the thought indeed?/really?"], ["na ou fai atu ia", "I said to to"], ["mea ia te outou,", "thing unto you"], ["a o tatou", "but of we (incl)"], ["i ai", "therein"], ["ma outou?", "with you"]]},
  {num:6,words:[["O lenei", "now"], ["foi,", "also"], ["ua outou iloa", "you (all) knew"], ["le mea o loo faalavelave,", "the thing is (progressive) a hindrance"], ["ina ia faaalia", "so that revealed"], ["mai o ia", "from he"], ["i ona lava aso.", "in then indeed day"]]},
  {num:7,words:[["Auā o loo galue nei", "for is (progressive) till this"], ["lava", "indeed"], ["le mea lilo", "the thing secret"], ["a le amio leaga,", "but the iniquity"], ["na", "na"], ["ona seia aveeseina", "and until carried away"], ["le o faalavelave.", "the of a hindrance"]]},
  {num:8,words:[["Ona faaalia mai ai lea", "and revealed from then then"], ["o le", "the"], ["ua amio leaga,", "iniquity"], ["e fano o ia", "to perish he"], ["i le Alii,", "in the Lord"], ["i le mānava", "in the mānava"], ["mai", "from"], ["o lona fofoga,", "his face"], ["ma faaumatia", "and destroyed"], ["i le faaali mai", "in the revealed"], ["o lana afio;", "his dwell (respectful)"]]},
  {num:9,words:[["o lona sau foi", "his come also"], ["e pei o le galuega", "like the work"], ["a Satani,", "of Satan"], ["i le mana uma,", "in the to get all"], ["ma faailoga,", "and sign"], ["ma vavega pepelo,", "and a wonder false"]]},
  {num:10,words:[["ma mea faasese uma", "and thing to cause to go astray all"], ["o le amio leaga", "the iniquity"], ["i", "in"], ["e", "by"], ["a fano;", "but perish"], ["auā", "for"], ["ua latou", "they"], ["le talia", "the received"], ["le upu moni", "the word true"], ["ma le fiafia", "and the competition"], ["i ai,", "therein"], ["ina ia faaolaina ai", "so that saved alive"], ["i latou.", "them"]]},
  {num:11,words:[["O le mea foi", "the thing also"], ["lea", "lea"], ["e auina atu ai", "to sent"], ["e le Atua", "God"], ["ia te i latou", "unto them"], ["le galuega", "the work"], ["e faasese ai,", "to to cause to go astray"], ["ina ia latou", "so that they"], ["talia", "received"], ["le mea pepelo;", "the thing false"]]},
  {num:12,words:[["ina ia faasalaina", "so that punished"], ["o", "o"], ["i latou uma lava", "them all indeed"], ["o", "o"], ["e le talia", "shall not received"], ["le upu moni,", "the word true"], ["a", "but"], ["e fiafia", "to competition"], ["i le amioleaga.", "in the wickedness"]]},
  {num:13,words:[["A o", "but of"], ["i matou", "in we (excl)"], ["e tatau ona", "should"], ["matou faafetai", "we (excl) thank"], ["i le Atua e le aunoa", "in the God by the without"], ["ona o outou,", "because of you (all)"], ["le au uso e,", "the me brother by"], ["e ua alofagia", "by favored"], ["e le Alii,", "shall not Lord"], ["auā", "for"], ["na filifili", "chose"], ["le Atua ia te outou", "God unto you"], ["mai le amataga", "from the beginning"], ["ia faaolaina i le", "to keep alive in the"], ["faapaiaina", "consecrated"], ["e le Agaga,", "shall not spirit"]]},
  {num:14,words:[["ma le talitonu", "and the believe"], ["i le upu moni,", "in the word true"], ["na valaauina ai", "called"], ["outou e ia", "you (all) by him"], ["i la matou tala lelei,", "in our gospel"], ["ina ia maua", "so that received"], ["le manuia", "the peace"], ["o lo tatou Alii", "our Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
  {num:15,words:[["O le mea lea", "therefore"], ["le au uso e,", "the me brother by"], ["ia outou tumau ai,", "to you (all) enduring"], ["ma ia taofi mau", "and to hold opinion"], ["i upu tuu", "in word put"], ["na a'oa'oina ai", "taught"], ["outou", "you (all)"], ["i la matou upu", "in our word"], ["ma la matou tusi.", "and our book"]]},
  {num:16,words:[["O lo tatou Alii", "our Lord"], ["lava o Iesu Keriso,", "indeed of Jesus Christ"], ["atoa ma le Atua lo tatou Tamā,", "and God our Father"], ["o le", "the"], ["ua alofa mai ia te", "loved from"], ["i tatou,", "in we (incl)"], ["ma", "and"], ["na foai mai le", "gave from the"], ["faamatala loto", "faamatala heart"], ["e faavavau,", "forever/everlasting"], ["ma le faamoemoe lelei", "and the hope good"], ["i le alofa tunoa,", "in the grace"], ["ia faamafanafana atu", "to to hearten"], ["e ia", "by him"], ["i o outou", "in of you (all)"], ["loto,", "heart"]]},
  {num:17,words:[["ma ia faatumauina outou", "and to established you (all)"], ["i upu lelei uma", "in word good all"], ["ma galuega lelei uma .", "and work good all"]]},
];
renderVerseSet(_2th_ch_2_Verses, '2th-ch2-verses');

var _2th_ch_3_Verses = [
  {num:1,words:[["O le toe upu lenei,", "the again word this"], ["le au uso e,", "the me brother by"], ["ia outou tatalo", "to you (all) pray"], ["mo", "for"], ["i matou,", "in we (excl)"], ["ia tele vave", "to great quick"], ["ma ia mamalu", "and to glory"], ["le afioga", "the word (divine)"], ["a le Alii,", "but the Lord"], ["e faapei", "to like"], ["ona fai ia te outou;", "and make unto you"]]},
  {num:2,words:[["ia laveaiina foi", "to delivered also"], ["i matou ai", "in we (excl)"], ["tagata amio leaga", "man iniquity"], ["ma", "and"], ["e agasala;", "to sin"], ["auā", "for"], ["e le o", "by the of"], ["i tagata uma", "in man all"], ["le faatuatua.", "the faith"]]},
  {num:3,words:[["A o loo faamaoni", "but is (progressive) faithful"], ["le Alii,", "the Lord"], ["na te faatumauina", "he established"], ["outou", "you (all)"], ["ma leoleoina", "and guarded"], ["ina ne'i leaga.", "so that now evil"]]},
  {num:4,words:[["Matou te faatuatua foi", "we (excl) faith also"], ["i le Alii", "in the Lord"], ["ia te outou,", "unto you"], ["o loo faia", "is (progressive) made"], ["e outou", "by you (all)"], ["o mea", "thing"], ["na matou fai atu ai", "we (excl) said to"], ["ia te outou,", "unto you"], ["i le tou te faia pea", "in the second person plural made continually"], ["lava;", "indeed"]]},
  {num:5,words:[["ia ta'ita'i tonu foi", "to lead right also"], ["e le Alii", "shall not Lord"], ["o outou loto", "you (all) heart"], ["i le alofa", "in the love"], ["o le Atua", "of God"], ["ma le onosai", "and the patience"], ["o Keriso.", "Christ"]]},
  {num:6,words:[["Matou te fai atu", "we (excl) said to"], ["ia te outou,", "unto you"], ["le au uso e,", "the me brother by"], ["i le suafa", "in the name"], ["o lo tatou Alii", "our Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["tou te vavae ese", "second person plural to divide away"], ["i uso uma", "in brother all"], ["o", "o"], ["e amio faapiopio,", "to conduct faapiopio"], ["ma le", "and the"], ["le tusa ma le uputuu", "the according to and the uputuu"], ["na latou maua ia te", "they received unto"], ["i matou.", "in we (excl)"]]},
  {num:7,words:[["Auā", "for"], ["ua outou iloa lava,", "you (all) knew indeed"], ["e tatau ona", "should"], ["outou faa'oa'o mai ia te", "you (all) faa'oa'o from"], ["i matou;", "in we (excl)"], ["auā", "for"], ["sa matou", "we (excl)"], ["le amio faapiopio", "the conduct faapiopio"], ["ina o ia te outou.", "so that he you (all)"]]},
  {num:8,words:[["Matou te lei aai fua foi", "we (excl) not city fruit also"], ["se mea", "a thing"], ["e 'ai", "to eat"], ["a se tasi,", "but a one"], ["a", "but"], ["ua matou galulue", "we (excl) labour"], ["i le galuega mamafa", "in the work heavy"], ["ma le tiga", "and the grieved"], ["i le po", "in the night"], ["ma le ao,", "and the day"], ["ina ne'i mafatia so outou.", "so that now the distribution of pro- so you (all)"]]},
  {num:9,words:[["E le", "by the"], ["ina", "so that"], ["ua leai", "there was not"], ["sa matou pule,", "we (excl) ruled"], ["a", "but"], ["e peitai ia", "to however to"], ["avea", "become"], ["i matou", "in we (excl)"], ["ma faaa'oa'o ia te outou,", "and make excellent unto you"], ["ina ia outou", "so that you (all)"], ["faaa'oa'o mai ia te", "make excellent from"], ["i matou.", "in we (excl)"]]},
  {num:10,words:[["Auā", "for"], ["sa tatou", "we (incl)"], ["i ai", "therein"], ["ma outou,", "with you"], ["ua matou fai atu", "we (excl) said to"], ["lenei mea ia te outou,", "this thing unto you"], ["pe afai", "whether if"], ["e le fia galue", "shall not want to do something till"], ["se tasi,", "a one"], ["aua ne'i 'ai foi", "for now eat also"], ["o ia.", "he"]]},
  {num:11,words:[["Auā", "for"], ["ua matou faalogo", "we (excl) hearken"], ["o ia te outou", "he you (all)"], ["nisi", "some"], ["ua amio faapiopio,", "conduct faapiopio"], ["e le o galulue", "by the of labour"], ["lava,", "indeed"], ["a", "but"], ["e matamata fua", "to observe fruit"], ["i galuega", "in work"], ["a nisi.", "but some"]]},
  {num:12,words:[["Matou te fai atu", "we (excl) said to"], ["i", "in"], ["e o faapea,", "by of thus"], ["ma aioi atu", "and cry out"], ["i ai,", "therein"], ["ona", "and"], ["o lo tatou Alii", "our Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["ia latou galulue", "to they labour"], ["ma le nofo fifilemu,", "and the dwell fifilemu"], ["ma ia latou", "and to they"], ["aai", "city"], ["i", "in"], ["a latou lava mea", "but they indeed thing"], ["e 'ai.", "to eat"]]},
  {num:13,words:[["A o outou", "but of you (all)"], ["le au uso e,", "the me brother by"], ["aua ne'i outou", "for now you (all)"], ["faavaivai", "weakened"], ["i le amio lelei.", "in the conduct good"]]},
  {num:14,words:[["Pe afai", "whether if"], ["e le gauai", "by the gauai"], ["se tasi", "a one"], ["i la matou upu", "in our word"], ["i lenei", "in this"], ["tusi,", "book"], ["ia faailogaina lea", "to sign"], ["tagata;", "man"], ["aua foi", "for also"], ["tou te feoai", "second person plural walk about"], ["ma ia,", "and to"], ["ina ia masiasi ai", "so that to be ashamied"], ["o ia.", "he"]]},
  {num:15,words:[["Aua foi", "for also"], ["tou te manatu", "second person plural thought"], ["o ia", "he"], ["o le fili,", "the to choose"], ["a ia outou", "but to you (all)"], ["apoapoai atu ia te ia", "exhort to him"], ["pei o le uso.", "like the brother"]]},
  {num:16,words:[["O lenei,", "now"], ["o le Alii", "the Lord"], ["lava", "indeed"], ["e", "by"], ["ona", "and"], ["le manuia,", "the peace"], ["ia foaiina atu", "to given"], ["e ia le manuia", "by him the peace"], ["ia te outou", "unto you"], ["e le aunoa", "shall not without"], ["i mea uma lava.", "in all things"], ["Ia ia te outou uma lava", "to him all of you"], ["le Alii.", "the Lord"]]},
  {num:17,words:[["O le alofa", "the love"], ["o a'u", "I am"], ["o Paulo", "Paul"], ["ua tusia", "written"], ["i lo'u lava lima,", "in my indeed five"], ["o le faailoga lea", "the sign"], ["i a'u tusi uma lava;", "in me book all indeed"], ["ou te tusi faapea lava.", "I will book thus indeed"]]},
  {num:18,words:[["Ia ia te outou uma lava", "to him all of you"], ["le alofa tunoa", "grace"], ["o lo tatou Alii", "our Lord"], ["o Iesu Keriso.", "Jesus Christ"], ["Amene.", "amen"]]},
];
renderVerseSet(_2th_ch_3_Verses, '2th-ch3-verses');

})();