(function() {
var 2th_ch_1_Verses = [
  {num:1,words:[["O i matou , o Paulo,", "Paul,"], ["ma Siluano, ma Timoteo,", "and Silvanus,"], ["o la matou tusi lenei i le ekalesia o tagata Tesalonia,", "and Timotheus,"], ["o i le Atua lo tatou Tamā, ma le Alii o Iesu Keriso.", "unto the church of the Thessalonians in God our Father and the Lord Jesus Christ:"]]},
  {num:2,words:[["Ia ia te outou le alofa tunoa ma le manuia mai le Atua lo tatou Tamā,", "Grace unto you, and peace,"], ["ma le Alii o Iesu Keriso.", "from God our Father and the Lord Jesus Christ."]]},
  {num:3,words:[["E tatau ona matou faafetai e le aunoa i le Atua ona o outou,", "We are bound to thank God always for you,"], ["le au uso e,", "brethren,"], ["e faapei ona tusa,", "as it is meet,"], ["auā ua tupu tele lava lo outou faatuatua,", "because that your faith groweth exceedingly,"], ["ua faateleina foi lo outou fealofani o outou uma lava taitoatasi.", "and the charity of every one of you all toward each other aboundeth;"]]},
  {num:4,words:[["O lea matou te mitamita ai ia te outou o i matou nei lava, i ekalesia a le Atua, ona o lo outou onosai ma lo outou faatuatua, i ona po o sauaga uma ma puapuaga ua outou faatoatoa ai;", "So that we ourselves glory in you in the churches of God for your patience and faith in all your persecutions and tribulations that ye endure:"]]},
  {num:5,words:[["o le faailoga lea o le faamasinoga tonu a le Atua,", "Which is a manifest token of the righteous judgment of God,"], ["ina ia ta'uaogaina outou i le malo o le Atua,", "that ye may be counted worthy of the kingdom of God,"], ["o le mea lea e tigaina ai outou.", "for which ye also suffer:"]]},
  {num:6,words:[["Auā ua tonu i le Atua e taui atu le puapuaga i e ua faapuapuagaina ai outou;", "Seeing it is a righteous thing with God to recompense tribulation to them that trouble you;"]]},
  {num:7,words:[["e ia te outou foi o e puapuagaina, o le mapusaga faatasi ma i matou,", "And to you who are troubled rest with us,"], ["pe a faaalia le Alii o Iesu mai le lagi, faatasi ma agelu o lona malosi, i le afi mumū,", "when the Lord Jesus shall be revealed from heaven with his mighty angels,"]]},
  {num:8,words:[["na te taui ma sui i e ua le iloa le Atua,", "In flaming fire taking vengeance on them that know not God,"], ["ma ua le anaana i le tala lelei a lo tatou Alii o Iesu Keriso;", "and that obey not the gospel of our Lord Jesus Christ:"]]},
  {num:9,words:[["e faasalaina i latou lava i le fanoga e faavavau lava,", "Who shall be punished with everlasting destruction from the presence of the Lord,"], ["ia te'a ma le Alii ma le mamalu o lona malosi;", "and from the glory of his power;"]]},
  {num:10,words:[["pe a afio mai o ia ina ia viia i ona lava tagata paia, ma ia ofo ia te ia i lena aso ia te i latou uma o e faatuatua,", "When he shall come to be glorified in his saints,"], ["auā na outou talitonu mai lava i la matou mau.", "and to be admired in all them that believe (because our testimony among you was believed) in that day."]]},
  {num:11,words:[["O le mea foi lea matou te faatoga atu ai e le aunoa mo outou,", "Wherefore also we pray always for you,"], ["ina ia ta'uaogaina outou e lo tatou Atua ia valaauina,", "that our God would count you worthy of this calling,"], ["ma ia faaatoatoaina e ia ma le malosi le loto fiafia uma o le agalelei,", "and fulfil all the good pleasure of his goodness,"], ["ma le galuega a le faatuatua;", "and the work of faith with power:"]]},
  {num:12,words:[["ina ia viia ona o outou le suafa o lo tatou Alii o Iesu Keriso,", "That the name of our Lord Jesus Christ may be glorified in you,"], ["ma outou foi ona o ia, e tusa ma le alofa tunoa o lo tatou Atua,", "and ye in him,"], ["ma le Alii o Iesu Keriso.", "according to the grace of our God and the Lord Jesus Christ."]]},
];
renderVerseSet(2th_ch_1_Verses, '2th-ch1-verses');

var 2th_ch_2_Verses = [
  {num:1,words:[["O lenei,", "Now we beseech you,"], ["matou te aioi atu ia te outou,", "brethren,"], ["le au uso e, i le mataupu i le afio mai o lo tatou Alii o Iesu Keriso,", "by the coming of our Lord Jesus Christ,"], ["ma lo tatou faapotopotoina ia te ia;", "and by our gathering together unto him,"]]},
  {num:2,words:[["ina ne'i vave luluina o outou loto,", "That ye be not soon shaken in mind,"], ["pe faaatuatuvaleina i se agaga,", "or be troubled,"], ["po o se upu,", "neither by spirit,"], ["po o se tusi,", "nor by word,"], ["peiseai nai ia i matou,", "nor by letter as from us,"], ["peiseai ua oo mai le aso o Keriso.", "as that the day of Christ is at hand."]]},
  {num:3,words:[["Aua ne'i faasese se tasi ia te outou i se togafiti e tasi;", "Let no man deceive you by any means:"], ["auā e le oo mai lena aso ,", "for that day shall not come,"], ["seia muai ona taunuu o le tete'a ese,", "except there come a falling away first,"], ["ma ia faaalia mai o le tagata o le agasala,", "and that man of sin be revealed,"], ["o le tagata lea o le malaia,", "the son of perdition;"]]},
  {num:4,words:[["o lē tetee atu, ma faamaualugaina e ia ia te ia e sili i mea uma lava ua ta'uatuaina,", "Who opposeth and exalteth himself above all that is called God,"], ["ma mea uma ua ifo i ai tagata , o lea ua tietie ai o ia i le malumalu o le Atua,", "or that is worshipped;"], ["peiseai o le Atua o ia,", "so that he as God sitteth in the temple of God,"], ["o loo faaali mai o ia, o le Atua lava o ia.", "shewing himself that he is God."]]},
  {num:5,words:[["Tou te le manatu ea,", "Remember ye not,"], ["na ou fai atu ia mea ia te outou,", "that, when I was yet with you,"], ["a o tatou i ai ma outou?", "I told you these things?"]]},
  {num:6,words:[["O lenei foi, ua outou iloa le mea o loo faalavelave, ina ia faaalia mai o ia i ona lava aso.", "And now ye know what withholdeth that he might be revealed in his time."]]},
  {num:7,words:[["Auā o loo galue nei lava le mea lilo a le amio leaga,", "For the mystery of iniquity doth already work: only he who now letteth will let,"], ["na ona seia aveeseina le o faalavelave.", "until he be taken out of the way."]]},
  {num:8,words:[["Ona faaalia mai ai lea o le ua amio leaga,", "And then shall that Wicked be revealed,"], ["e fano o ia i le Alii, i le mānava mai o lona fofoga,", "whom the Lord shall consume with the spirit of his mouth,"], ["ma faaumatia i le faaali mai o lana afio;", "and shall destroy with the brightness of his coming:"]]},
  {num:9,words:[["o lona sau foi e pei o le galuega a Satani, i le mana uma,", "Even him,"], ["ma faailoga, ma vavega pepelo,", "whose coming is after the working of Satan with all power and signs and lying wonders,"]]},
  {num:10,words:[["ma mea faasese uma o le amio leaga i e a fano;", "And with all deceivableness of unrighteousness in them that perish;"], ["auā ua latou le talia le upu moni ma le fiafia i ai,", "because they received not the love of the truth,"], ["ina ia faaolaina ai i latou.", "that they might be saved."]]},
  {num:11,words:[["O le mea foi lea e auina atu ai e le Atua ia te i latou le galuega e faasese ai,", "And for this cause God shall send them strong delusion,"], ["ina ia latou talia le mea pepelo;", "that they should believe a lie:"]]},
  {num:12,words:[["ina ia faasalaina o i latou uma lava o e le talia le upu moni,", "That they all might be damned who believed not the truth,"], ["a e fiafia i le amioleaga.", "but had pleasure in unrighteousness."]]},
  {num:13,words:[["A o i matou e tatau ona matou faafetai i le Atua e le aunoa ona o outou,", "But we are bound to give thanks alway to God for you,"], ["le au uso e, e ua alofagia e le Alii,", "brethren beloved of the Lord,"], ["auā na filifili le Atua ia te outou mai le amataga ia faaolaina i le faapaiaina e le Agaga,", "because God hath from the beginning chosen you to salvation through sanctification of the Spirit and belief of the truth:"]]},
  {num:14,words:[["ma le talitonu i le upu moni, na valaauina ai outou e ia i la matou tala lelei,", "Whereunto he called you by our gospel,"], ["ina ia maua le manuia o lo tatou Alii o Iesu Keriso.", "to the obtaining of the glory of our Lord Jesus Christ."]]},
  {num:15,words:[["O le mea lea le au uso e,", "Therefore, brethren,"], ["ia outou tumau ai,", "stand fast, and hold the traditions which ye have been taught,"], ["ma ia taofi mau i upu tuu na a'oa'oina ai outou i la matou upu ma la matou tusi.", "whether by word, or our epistle."]]},
  {num:16,words:[["O lo tatou Alii lava o Iesu Keriso,", "Now our Lord Jesus Christ himself,"], ["atoa ma le Atua lo tatou Tamā,", "and God,"], ["o le ua alofa mai ia te i tatou, ma na foai mai le faamatala loto e faavavau,", "even our Father,"], ["ma le faamoemoe lelei i le alofa tunoa,", "which hath loved us,"], ["ia faamafanafana atu e ia i o outou loto,", "and hath given us everlasting consolation and good hope through grace,"]]},
  {num:17,words:[["ma ia faatumauina outou i upu lelei uma ma galuega lelei uma .", "Comfort your hearts, and stablish you in every good word and work."]]},
];
renderVerseSet(2th_ch_2_Verses, '2th-ch2-verses');

var 2th_ch_3_Verses = [
  {num:1,words:[["O le toe upu lenei,", "Finally,"], ["le au uso e,", "brethren,"], ["ia outou tatalo mo i matou,", "pray for us, that the word of the Lord may have free course,"], ["ia tele vave ma ia mamalu le afioga a le Alii,", "and be glorified,"], ["e faapei ona fai ia te outou;", "even as it is with you:"]]},
  {num:2,words:[["ia laveaiina foi i matou ai tagata amio leaga ma e agasala;", "And that we may be delivered from unreasonable and wicked men:"], ["auā e le o i tagata uma le faatuatua.", "for all men have not faith."]]},
  {num:3,words:[["A o loo faamaoni le Alii,", "But the Lord is faithful, who shall stablish you,"], ["na te faatumauina outou ma leoleoina ina ne'i leaga.", "and keep you from evil."]]},
  {num:4,words:[["Matou te faatuatua foi i le Alii ia te outou, o loo faia e outou o mea na matou fai atu ai ia te outou,", "And we have confidence in the Lord touching you,"], ["i le tou te faia pea lava;", "that ye both do and will do the things which we command you."]]},
  {num:5,words:[["ia ta'ita'i tonu foi e le Alii o outou loto i le alofa o le Atua ma le onosai o Keriso.", "And the Lord direct your hearts into the love of God, and into the patient waiting for Christ."]]},
  {num:6,words:[["Matou te fai atu ia te outou,", "Now we command you,"], ["le au uso e,", "brethren,"], ["i le suafa o lo tatou Alii o Iesu Keriso,", "in the name of our Lord Jesus Christ,"], ["tou te vavae ese i uso uma o e amio faapiopio,", "that ye withdraw yourselves from every brother that walketh disorderly,"], ["ma le le tusa ma le uputuu na latou maua ia te i matou.", "and not after the tradition which he received of us."]]},
  {num:7,words:[["Auā ua outou iloa lava, e tatau ona outou faa'oa'o mai ia te i matou;", "For yourselves know how ye ought to follow us:"], ["auā sa matou le amio faapiopio ina o ia te outou.", "for we behaved not ourselves disorderly among you;"]]},
  {num:8,words:[["Matou te lei aai fua foi se mea e 'ai a se tasi,", "Neither did we eat any man's bread for nought;"], ["a ua matou galulue i le galuega mamafa ma le tiga i le po ma le ao,", "but wrought with labour and travail night and day,"], ["ina ne'i mafatia so outou.", "that we might not be chargeable to any of you:"]]},
  {num:9,words:[["E le ina ua leai sa matou pule, a e peitai ia avea i matou ma faaa'oa'o ia te outou,", "Not because we have not power,"], ["ina ia outou faaa'oa'o mai ia te i matou.", "but to make ourselves an ensample unto you to follow us."]]},
  {num:10,words:[["Auā sa tatou i ai ma outou,", "For even when we were with you,"], ["ua matou fai atu lenei mea ia te outou,", "this we commanded you,"], ["pe afai e le fia galue se tasi,", "that if any would not work,"], ["aua ne'i 'ai foi o ia.", "neither should he eat."]]},
  {num:11,words:[["Auā ua matou faalogo o ia te outou nisi ua amio faapiopio,", "For we hear that there are some which walk among you disorderly,"], ["e le o galulue lava,", "working not at all,"], ["a e matamata fua i galuega a nisi.", "but are busybodies."]]},
  {num:12,words:[["Matou te fai atu i e o faapea, ma aioi atu i ai,", "Now them that are such we command and exhort by our Lord Jesus Christ,"], ["ona o lo tatou Alii o Iesu Keriso,", "that with quietness they work,"], ["ia latou galulue ma le nofo fifilemu, ma ia latou aai i a latou lava mea e 'ai.", "and eat their own bread."]]},
  {num:13,words:[["A o outou le au uso e,", "But ye, brethren,"], ["aua ne'i outou faavaivai i le amio lelei.", "be not weary in well doing."]]},
  {num:14,words:[["Pe afai e le gauai se tasi i la matou upu i lenei tusi,", "And if any man obey not our word by this epistle,"], ["ia faailogaina lea tagata;", "note that man,"], ["aua foi tou te feoai ma ia,", "and have no company with him,"], ["ina ia masiasi ai o ia.", "that he may be ashamed."]]},
  {num:15,words:[["Aua foi tou te manatu o ia o le fili,", "Yet count him not as an enemy,"], ["a ia outou apoapoai atu ia te ia pei o le uso.", "but admonish him as a brother."]]},
  {num:16,words:[["O lenei, o le Alii lava e ona le manuia, ia foaiina atu e ia le manuia ia te outou e le aunoa i mea uma lava.", "Now the Lord of peace himself give you peace always by all means."], ["Ia ia te outou uma lava le Alii.", "The Lord be with you all."]]},
  {num:17,words:[["O le alofa o a'u o Paulo ua tusia i lo'u lava lima,", "The salutation of Paul with mine own hand,"], ["o le faailoga lea i a'u tusi uma lava;", "which is the token in every epistle:"], ["ou te tusi faapea lava.", "so I write."]]},
  {num:18,words:[["Ia ia te outou uma lava le alofa tunoa o lo tatou Alii o Iesu Keriso. Amene.", "The grace of our Lord Jesus Christ be with you all. Amen."]]},
];
renderVerseSet(2th_ch_3_Verses, '2th-ch3-verses');

})();