(function() {
var _2th_ch_1_Verses = [
  {num:1,words:[["O i matou ,", "in we (excl)"], ["o Paulo,", "Paul"], ["ma Siluano,", "and Siluano"], ["ma Timoteo,", "and Timothy"], ["o la matou tusi lenei", "our book this"], ["i le ekalesia o tagata Tesalonia,", "in the church of men Tesalonia"], ["o i le Atua lo tatou Tamā,", "in the God our Father"], ["ma le Alii o Iesu Keriso.", "and the Lord of Jesus Christ"]]},
  {num:2,words:[["Ia ia te outou", "to him you (all)"], ["le alofa tunoa ma le manuia", "grace and peace"], ["mai le Atua lo tatou Tamā,", "from God our Father"], ["ma le Alii o Iesu Keriso.", "and the Lord of Jesus Christ"]]},
  {num:3,words:[["E tatau ona", "should"], ["matou faafetai", "we (excl) thank"], ["e le aunoa", "by the without"], ["i le Atua", "in the God"], ["ona o outou,", "because of you (all)"], ["le au uso", "the I brother"], ["e,", "by"], ["e faapei", "to like"], ["ona tusa,", "and according to"], ["auā ua tupu tele lava lo outou faatuatua,", "for king great indeed your faith"], ["ua faateleina foi lo outou fealofani", "multiplied also your fealofani"], ["o outou uma lava taitoatasi.", "all of you each one"]]},
  {num:4,words:[["O lea matou te mitamita ai ia te outou", "therefore we (excl) to boast unto you"], ["o i matou nei lava,", "in we (excl) this indeed"], ["i ekalesia", "in church"], ["a le Atua,", "of God"], ["ona o lo outou onosai", "because of your patience"], ["ma lo outou faatuatua,", "and the you (all) faith"], ["i ona po o sauaga uma", "in then night of sauaga all"], ["ma puapuaga", "and affliction"], ["ua outou faatoatoa ai;", "you (all) faatoatoa"]]},
  {num:5,words:[["o le faailoga lea o le faamasinoga tonu", "the sign the judgment right"], ["a le Atua,", "of God"], ["ina ia ta'uaogaina outou", "so that ta'uaogaina you (all)"], ["i le malo o le Atua,", "in the government of God"], ["o le mea lea e tigaina ai outou.", "therefore to afflicted you (all)"]]},
  {num:6,words:[["Auā ua tonu", "for right"], ["i le Atua e", "in the God by"], ["taui atu le puapuaga", "a reward the affliction"], ["i e ua faapuapuagaina ai outou;", "in by made affliction you (all)"]]},
  {num:7,words:[["e ia te outou", "by him you (all)"], ["foi o e puapuagaina,", "also who affliction"], ["o le mapusaga faatasi ma", "the a resting place together and"], ["i matou,", "in we (excl)"], ["pe a faaalia", "whether but revealed"], ["le Alii o Iesu", "the Lord of Jesus"], ["mai le lagi,", "from the heaven"], ["faatasi ma agelu", "together and angel"], ["o lona malosi,", "his strong"], ["i le afi mumū,", "in the fire mumū"]]},
  {num:8,words:[["na te taui", "he a reward"], ["ma sui", "and to dilute"], ["i e ua", "in by"], ["le iloa", "the know"], ["le Atua,", "God"], ["ma ua", "and"], ["le anaana", "the his own"], ["i le tala lelei", "in the gospel"], ["a lo tatou Alii o Iesu Keriso;", "but our Lord of Jesus Christ"]]},
  {num:9,words:[["e faasalaina", "to punished"], ["i latou lava", "them indeed"], ["i le fanoga", "in the fanoga"], ["e faavavau lava,", "forever and ever"], ["ia te'a", "to depart"], ["ma le Alii", "and the Lord"], ["ma le mamalu", "and the glory"], ["o lona malosi;", "his strong"]]},
  {num:10,words:[["pe a afio mai o ia", "whether but dwell (respectful) from he"], ["ina ia viia", "so that praised"], ["i ona lava tagata paia,", "in then indeed saints"], ["ma ia ofo ia te ia i lena aso", "and to n to him in that day"], ["ia te i latou", "unto them"], ["uma o e faatuatua,", "all who faith"], ["auā na outou talitonu", "for you (all) believed"], ["mai lava", "from indeed"], ["i la matou mau.", "in our opinion"]]},
  {num:11,words:[["O le mea foi lea matou", "the thing also we (excl)"], ["te faatoga atu ai e le aunoa", "order by the without"], ["mo outou,", "for you"], ["ina ia ta'uaogaina outou", "so that ta'uaogaina you (all)"], ["e lo tatou Atua ia", "by our God to"], ["valaauina,", "called"], ["ma ia faaatoatoaina e ia ma le malosi", "and to to complete by him and the strong"], ["le loto fiafia uma", "the heart competition all"], ["o le agalelei,", "the treated well"], ["ma le galuega", "and the work"], ["a le faatuatua;", "but the faith"]]},
  {num:12,words:[["ina ia viia", "so that praised"], ["ona o outou", "because of you (all)"], ["le suafa", "the name"], ["o lo tatou Alii o Iesu Keriso,", "our Lord of Jesus Christ"], ["ma outou foi", "with you also"], ["ona o ia,", "because of to"], ["e tusa ma le alofa tunoa", "according to grace"], ["o lo tatou Atua,", "our God"], ["ma le Alii o Iesu Keriso.", "and the Lord of Jesus Christ"]]},
];
renderVerseSet(_2th_ch_1_Verses, '2th-ch1-verses');

var _2th_ch_2_Verses = [
  {num:1,words:[["O lenei,", "now"], ["matou te aioi atu ia te outou,", "we (excl) cry out unto you"], ["le au uso", "the I brother"], ["e,", "by"], ["i le mataupu", "in the chapter"], ["i le afio mai o lo tatou Alii o Iesu Keriso,", "in the dwell (respectful) from our Lord of Jesus Christ"], ["ma lo tatou faapotopotoina ia te ia;", "and the we (incl) gathered together to him"]]},
  {num:2,words:[["ina ne'i vave luluina o outou", "so that now quick shaken of you (all)"], ["loto,", "heart"], ["pe faaatuatuvaleina", "whether make to be greatly dis-"], ["i se agaga,", "in a spirit"], ["po o se upu,", "night a word"], ["po o se tusi,", "night a book"], ["peiseai nai ia i matou,", "as if from to in we (excl)"], ["peiseai ua oo mai le aso", "as if it came to pass from the day"], ["o Keriso.", "Christ"]]},
  {num:3,words:[["Aua ne'i faasese", "for now to cause to go astray"], ["se tasi ia te outou", "a one unto you"], ["i se togafiti", "in a heal"], ["e tasi;", "by one"], ["auā e le oo mai lena aso ,", "for by the came that day"], ["seia muai", "until first"], ["ona taunuu", "and fulfilled"], ["o le tete'a ese,", "the light colored : as away"], ["ma ia faaalia", "and to revealed"], ["mai o le tagata", "from man"], ["o le agasala,", "the sin"], ["o le tagata lea o le malaia,", "man the disaster"]]},
  {num:4,words:[["o lē tetee atu,", "not to refuse"], ["ma faamaualugaina e ia ia te ia", "and exalted by him to him"], ["e sili", "to most"], ["i mea uma lava", "in all things"], ["ua ta'uatuaina,", "ta'uatuaina"], ["ma mea uma", "and all things"], ["ua ifo", "down"], ["i ai tagata ,", "therein man"], ["o lea", "therefore"], ["ua tietie ai o ia i le malumalu", "rode he in the temple"], ["o le Atua,", "of God"], ["peiseai o le Atua o ia,", "as if of God he"], ["o loo faaali mai o ia,", "revealed he"], ["o le Atua lava o ia.", "of God indeed he"]]},
  {num:5,words:[["Tou te le manatu ea,", "second person plural the thought to rise (as a diver to the sur-"], ["na ou fai atu ia mea", "I said to to thing"], ["ia te outou,", "unto you"], ["a o tatou", "but of we (incl)"], ["i ai", "therein"], ["ma outou?", "with you"]]},
  {num:6,words:[["O lenei foi,", "now also"], ["ua outou iloa", "you (all) knew"], ["le mea o loo faalavelave,", "the thing of a hindrance"], ["ina ia faaalia", "so that revealed"], ["mai o ia i ona", "from he in then"], ["lava aso.", "indeed day"]]},
  {num:7,words:[["Auā o loo galue nei", "for of till this"], ["lava le mea lilo", "indeed the thing secret"], ["a le amio leaga,", "but the iniquity"], ["na ona seia aveeseina", "then until carried away"], ["le o faalavelave.", "the of a hindrance"]]},
  {num:8,words:[["Ona faaalia mai ai lea o le ua amio leaga,", "and revealed from the iniquity"], ["e fano o ia i le Alii,", "to perish he in the Lord"], ["i le mānava", "in the mānava"], ["mai o lona fofoga,", "from his face"], ["ma faaumatia", "and destroyed"], ["i le faaali mai o lana afio;", "in the revealed of his dwell (respectful)"]]},
  {num:9,words:[["o lona sau foi e pei o le galuega", "his come also like the work"], ["a Satani,", "of Satan"], ["i le mana uma,", "in the to get all"], ["ma faailoga,", "and sign"], ["ma vavega pepelo,", "and a wonder false"]]},
  {num:10,words:[["ma mea faasese uma", "and thing to cause to go astray all"], ["o le amio leaga", "the iniquity"], ["i e", "in by"], ["a fano;", "but perish"], ["auā ua latou", "for they"], ["le talia", "the received"], ["le upu moni", "the word true"], ["ma le fiafia", "and the competition"], ["i ai,", "therein"], ["ina ia faaolaina ai", "so that saved alive"], ["i latou.", "them"]]},
  {num:11,words:[["O le mea foi lea e auina atu ai e le Atua", "the thing also to sent God"], ["ia te i latou", "unto them"], ["le galuega", "the work"], ["e faasese ai,", "to to cause to go astray"], ["ina ia latou talia", "so that they received"], ["le mea pepelo;", "the thing false"]]},
  {num:12,words:[["ina ia faasalaina o", "so that punished of"], ["i latou uma lava o e le talia", "them all indeed who the received"], ["le upu moni,", "the word true"], ["a e fiafia", "but to competition"], ["i le amioleaga.", "in the wickedness"]]},
  {num:13,words:[["A o", "but of"], ["i matou", "in we (excl)"], ["e tatau ona", "should"], ["matou faafetai", "we (excl) thank"], ["i le Atua e le aunoa", "in the God by the without"], ["ona o outou,", "because of you (all)"], ["le au uso", "the I brother"], ["e,", "by"], ["e ua alofagia", "by favored"], ["e le Alii,", "by the Lord"], ["auā na filifili", "for chose"], ["le Atua ia te outou", "God unto you"], ["mai le amataga ia faaolaina", "from the beginning to keep alive"], ["i le faapaiaina", "in the consecrated"], ["e le Agaga,", "by the spirit"]]},
  {num:14,words:[["ma le talitonu", "and the believe"], ["i le upu moni,", "in the word true"], ["na valaauina ai outou", "called you (all)"], ["e ia i la matou tala lelei,", "by him in our gospel"], ["ina ia maua", "so that received"], ["le manuia", "the peace"], ["o lo tatou Alii o Iesu Keriso.", "our Lord of Jesus Christ"]]},
  {num:15,words:[["O le mea lea", "therefore"], ["le au uso", "the I brother"], ["e,", "by"], ["ia outou tumau ai,", "to you (all) enduring"], ["ma ia taofi mau", "and to hold opinion"], ["i upu tuu", "in word put"], ["na a'oa'oina ai outou", "taught you (all)"], ["i la matou upu", "in our word"], ["ma la matou tusi.", "and our book"]]},
  {num:16,words:[["O lo tatou Alii lava o Iesu Keriso,", "our Lord indeed of Jesus Christ"], ["atoa ma le Atua lo tatou Tamā,", "and God our Father"], ["o le ua alofa", "the loved"], ["mai ia te i tatou,", "from in we (incl)"], ["ma na foai", "and gave"], ["mai le faamatala loto", "from the faamatala heart"], ["e faavavau,", "forever/everlasting"], ["ma le faamoemoe lelei", "and the hope good"], ["i le alofa tunoa,", "in the grace"], ["ia faamafanafana atu e ia i o outou", "to to hearten by him in of you (all)"], ["loto,", "heart"]]},
  {num:17,words:[["ma ia faatumauina outou", "and to established you (all)"], ["i upu lelei uma", "in word good all"], ["ma galuega lelei uma .", "and work good all"]]},
];
renderVerseSet(_2th_ch_2_Verses, '2th-ch2-verses');

var _2th_ch_3_Verses = [
  {num:1,words:[["O le toe upu lenei,", "the again word this"], ["le au uso", "the I brother"], ["e,", "by"], ["ia outou tatalo", "to you (all) pray"], ["mo i matou,", "for in we (excl)"], ["ia tele vave", "to great quick"], ["ma ia mamalu", "and to glory"], ["le afioga", "the word (divine)"], ["a le Alii,", "but the Lord"], ["e faapei", "to like"], ["ona fai ia te outou;", "and make unto you"]]},
  {num:2,words:[["ia laveaiina foi i matou", "to delivered also in we (excl)"], ["ai tagata amio leaga", "man iniquity"], ["ma e agasala;", "and to sin"], ["auā e le o", "for by the of"], ["i tagata uma", "in man all"], ["le faatuatua.", "the faith"]]},
  {num:3,words:[["A o loo faamaoni", "but of faithful"], ["le Alii,", "the Lord"], ["na te faatumauina outou", "he established you (all)"], ["ma leoleoina", "and guarded"], ["ina ne'i leaga.", "so that now evil"]]},
  {num:4,words:[["Matou te faatuatua foi i le Alii", "we (excl) faith also in the Lord"], ["ia te outou,", "unto you"], ["o loo faia e outou", "made by you (all)"], ["o mea", "thing"], ["na matou fai atu ai ia te outou,", "we (excl) said to unto you"], ["i le tou te faia pea", "in the second person plural made continually"], ["lava;", "indeed"]]},
  {num:5,words:[["ia ta'ita'i tonu foi e le Alii o outou", "to lead right also by the Lord of you (all)"], ["loto i le alofa", "heart in the love"], ["o le Atua", "of God"], ["ma le onosai o Keriso.", "and the patience of Christ"]]},
  {num:6,words:[["Matou te fai atu ia te outou,", "we (excl) said to unto you"], ["le au uso", "the I brother"], ["e,", "by"], ["i le suafa", "in the name"], ["o lo tatou Alii o Iesu Keriso,", "our Lord of Jesus Christ"], ["tou te vavae ese", "second person plural to divide away"], ["i uso uma o e amio faapiopio,", "in brother all who conduct faapiopio"], ["ma le", "and the"], ["le tusa ma le uputuu", "the according to and the uputuu"], ["na latou maua ia te i matou.", "they received unto in we (excl)"]]},
  {num:7,words:[["Auā ua outou iloa lava,", "for you (all) knew indeed"], ["e tatau ona", "should"], ["outou faa'oa'o mai ia te i matou;", "you (all) faa'oa'o from in we (excl)"], ["auā sa matou", "for we (excl)"], ["le amio faapiopio", "the conduct faapiopio"], ["ina o ia te outou.", "so that he you (all)"]]},
  {num:8,words:[["Matou te lei aai fua", "we (excl) not city fruit"], ["foi se mea e 'ai", "also a thing to eat"], ["a se tasi,", "but a one"], ["a ua matou galulue", "but we (excl) labour"], ["i le galuega mamafa", "in the work heavy"], ["ma le tiga", "and the grieved"], ["i le po", "in the night"], ["ma le ao,", "and the day"], ["ina ne'i mafatia so outou.", "so that now the distribution of pro- so you (all)"]]},
  {num:9,words:[["E le", "by the"], ["ina ua leai", "so that there was not"], ["sa matou pule,", "we (excl) ruled"], ["a e peitai ia", "but to"], ["avea i matou", "become in we (excl)"], ["ma faaa'oa'o ia te outou,", "and make excellent unto you"], ["ina ia outou faaa'oa'o", "so that you (all) make excellent"], ["mai ia te i matou.", "from in we (excl)"]]},
  {num:10,words:[["Auā sa tatou", "for we (incl)"], ["i ai", "therein"], ["ma outou,", "with you"], ["ua matou fai atu lenei mea", "we (excl) said to this thing"], ["ia te outou,", "unto you"], ["pe afai", "whether if"], ["e le fia galue", "by the want to do something till"], ["se tasi,", "a one"], ["aua ne'i 'ai foi o ia.", "for now eat also he"]]},
  {num:11,words:[["Auā ua matou faalogo o ia te outou", "for we (excl) hearken he you (all)"], ["nisi ua amio faapiopio,", "some conduct faapiopio"], ["e le o galulue lava,", "by the of labour indeed"], ["a e matamata fua", "but to observe fruit"], ["i galuega", "in work"], ["a nisi.", "but some"]]},
  {num:12,words:[["Matou te fai atu i", "we (excl) said to in"], ["e o faapea,", "by of thus"], ["ma aioi atu i ai,", "and cry out therein"], ["ona o lo tatou Alii o Iesu Keriso,", "because of our Lord Jesus Christ"], ["ia latou galulue", "to they labour"], ["ma le nofo fifilemu,", "and the dwell fifilemu"], ["ma ia latou aai", "and to they city"], ["i a latou lava mea e 'ai.", "in but they indeed thing to eat"]]},
  {num:13,words:[["A o outou", "but of you (all)"], ["le au uso", "the I brother"], ["e,", "by"], ["aua ne'i outou faavaivai", "for now you (all) weakened"], ["i le amio lelei.", "in the conduct good"]]},
  {num:14,words:[["Pe afai", "whether if"], ["e le gauai", "by the gauai"], ["se tasi", "a one"], ["i la matou upu", "in our word"], ["i lenei tusi,", "in this book"], ["ia faailogaina lea tagata;", "to sign man"], ["aua foi tou te feoai", "for also second person plural walk about"], ["ma ia,", "and to"], ["ina ia masiasi ai o ia.", "so that to be ashamied he"]]},
  {num:15,words:[["Aua foi tou te manatu", "for also second person plural thought"], ["o ia o le fili,", "he the to choose"], ["a ia outou apoapoai atu ia te ia", "but to you (all) exhort to him"], ["pei o le uso.", "like the brother"]]},
  {num:16,words:[["O lenei,", "now"], ["o le Alii lava", "the Lord indeed"], ["e ona", "by then"], ["le manuia,", "the peace"], ["ia foaiina atu e ia", "to given by him"], ["le manuia ia te outou", "the peace unto you"], ["e le aunoa", "by the without"], ["i mea uma lava.", "in all things"], ["Ia ia te outou uma lava", "to him all of you"], ["le Alii.", "the Lord"]]},
  {num:17,words:[["O le alofa", "the love"], ["o a'u", "I am"], ["o Paulo", "Paul"], ["ua tusia", "written"], ["i lo'u lava lima,", "in my indeed five"], ["o le faailoga lea", "the sign"], ["i a'u tusi uma lava;", "in I book all indeed"], ["ou te tusi faapea lava.", "I book thus indeed"]]},
  {num:18,words:[["Ia ia te outou uma lava", "to him all of you"], ["le alofa tunoa", "grace"], ["o lo tatou Alii o Iesu Keriso.", "our Lord of Jesus Christ"], ["Amene.", "amen"]]},
];
renderVerseSet(_2th_ch_3_Verses, '2th-ch3-verses');

})();