(function() {
var 3jn_ch_1_Verses = [
  {num:1,words:[["O a'u", "I am"], ["le toeaina,", "the elder"], ["o la'u tusi lenei ia Kaio,", "this letter to kaio"], ["o le pele,", "the dear"], ["o le ou te alofa faamaoni", "the I love faithful"], ["i ai.", "therein"]]},
  {num:2,words:[["Le pele e,", "the dear by"], ["ia e manuia", "to to peace"], ["i mea uma,", "in all things"], ["ma ia", "and to"], ["e malolo,", "to rest"], ["faapei ona manuia o lou agaga.", "like then peace your spirit"]]},
  {num:3,words:[["Auā ua tele lava lo'u fiafia", "for great indeed my competition"], ["ina ua o", "let"], ["mai le au uso,", "from the I a relative of the same generation and gender"], ["ma faailoa mai lou faamaoni,", "and declared from your faithful"], ["ina ua", "let"], ["e savali", "to walk"], ["i le upu moni.", "in the word true"]]},
  {num:4,words:[["E leai so'u fiafia", "there is not so'u competition"], ["e sili", "to most"], ["i lenei,", "in this"], ["pe a ou faalogo", "whether but I hearken"], ["ua savavali la'u fanau", "walked my born"], ["i le upu moni.", "in the word true"]]},
  {num:5,words:[["Le pele e,", "the dear by"], ["ua e faamaoni lava", "to faithful indeed"], ["i mea uma o faia", "in all things made"], ["e oe", "to you"], ["i le au uso", "in the I a relative of the same generation and gender"], ["atoa ma tagata ese,", "and man away"]]},
  {num:6,words:[["o e", "who"], ["ua faailoa mai lou alofa", "declared from your love"], ["i luma", "in before"], ["o le ekalesia;", "the church"], ["afai e te fesoasoani", "if by to help"], ["i lo latou moliga", "in the them the sending"], ["e tusa", "to according to"], ["i le Atua,", "in the God"], ["e lelei lau mea", "to good your thing"], ["e fai.", "to make"]]},
  {num:7,words:[["Auā na latou o atu", "for them"], ["ona o lona suafa,", "because of his name"], ["e lei talia sina mea", "to whale's teeth received white thing"], ["mai nuu ese.", "from nation away"]]},
  {num:8,words:[["O lea", "therefore"], ["e tatau ai", "it is fitting"], ["ona tatou talia tagata faapea,", "and us received man thus"], ["ina ia tatou fai", "so that us make"], ["ma fesoasoani", "and to help"], ["i le upu moni.", "in the word true"]]},
  {num:9,words:[["Na ou tusi atu", "I book"], ["i le ekalesia,", "in the church"], ["a o Tioterifi,", "but tioterifi"], ["o lē fia sili ia te", "not want to do something most unto"], ["i latou,", "them"], ["e le talia", "by the received"], ["i matou", "in we"], ["e ia.", "by him"]]},
  {num:10,words:[["O le mea lea,", "therefore/wherefore"], ["pe a a'u alu atu,", "whether but I go away"], ["ou te faamanatu ai lana amio", "I to remind his conduct"], ["o loo faia", "made"], ["e ia,", "by him"], ["o loo tuaupua", "tuaupua"], ["mai ia", "from to"], ["i matou", "in we"], ["i upu leaga;", "in word evil"], ["e le gata foi", "by the a snake also"], ["i ia mea,", "in to thing"], ["a e le talia lava", "but by the received indeed"], ["e ia le au uso,", "by him the I a relative of the same generation and gender"], ["e vavao atu foi", "to to forbid also"], ["i e loto", "in to heart"], ["i ai,", "therein"], ["na te faateaina foi", "faateaina also"], ["i latou", "them"], ["i le ekalesia.", "in the church"]]},
  {num:11,words:[["Le pele e,", "the dear by"], ["aua e te faaa'oa'o", "for by faaa'oa'o"], ["i le leaga,", "in the evil"], ["na o le lelei.", "the good"], ["O lē amio lelei,", "not conduct good"], ["mai le Atua lava lea;", "from God indeed"], ["peitai o lē amio leaga,", "however not iniquity"], ["e lei iloa atu lava", "to whale's teeth known indeed"], ["e ia le Atua.", "by him God"]]},
  {num:12,words:[["Ua logoleleia Temetiu", "logoleleia temetiu"], ["e tagata uma lava,", "to man all indeed"], ["atoa ma le upu moni", "and the word true"], ["lava;", "indeed"], ["o i matou foi matou te molimau", "in we also we a witness"], ["i ai,", "therein"], ["ua outou iloa foi", "ye all known also"], ["e moni la matou mau.", "verily our opinion"]]},
  {num:13,words:[["Ua ia te au mea", "unto me thing"], ["e tele", "to great"], ["e tusi atu ai,", "to book"], ["a ou te", "but I"], ["le fia tusi atu ia te oe", "the want to do something book unto thee"], ["i le vaitusi", "in the ink"], ["ma le fulu tusi.", "and the fulu book"]]},
  {num:14,words:[["Auā ou te faamoemoe o", "for I to expect"], ["le a vave feiloai", "the but quick feiloai"], ["i taua,", "in war"], ["ina ia ta fetautalatalai.", "so that a stroke fetautalatalai"], ["Ia ia te oe", "to unto thee"], ["le manuia.", "the peace"], ["O loo alolofa atu", "alolofa"], ["le aumea mamae ia te oe;", "the aumea mamae unto thee"], ["ua ou alofa", "I love"], ["i le aumea mamae uma", "in the aumea mamae all"], ["lava.", "indeed"]]},
];
renderVerseSet(3jn_ch_1_Verses, '3jn-ch1-verses');

})();