(function() {
var _3jn_ch_1_Verses = [
  {num:1,words:[["O a'u", "I am"], ["le toeaina,", "the elder"], ["o la'u tusi lenei ia", "this letter to"], ["Kaio,", "Kaio"], ["o le pele,", "the dear"], ["o le ou te alofa faamaoni", "the I will love faithful"], ["i ai.", "therein"]]},
  {num:2,words:[["Le pele e,", "the dear by"], ["ia e manuia", "to to peace"], ["i mea uma,", "in all things"], ["ma ia", "and to"], ["e malolo,", "to rest"], ["faapei ona manuia", "like then peace"], ["o lou agaga.", "your spirit"]]},
  {num:3,words:[["Auā ua tele lava lo'u fiafia", "for great indeed my competition"], ["ina ua o mai le au", "so that of from the I"], ["uso,", "brother"], ["ma faailoa mai lou faamaoni,", "and revealed from your faithful"], ["ina ua", "so that"], ["e savali", "to walk"], ["i le upu moni.", "in the word true"]]},
  {num:4,words:[["E leai so'u fiafia", "there is not so'u competition"], ["e sili", "to most"], ["i lenei,", "in this"], ["pe a ou faalogo", "whether but I hearken"], ["ua savavali la'u fanau", "walked my born"], ["i le upu moni.", "in the word true"]]},
  {num:5,words:[["Le pele e,", "the dear by"], ["ua e faamaoni lava", "to faithful indeed"], ["i mea uma o faia e oe", "in all things of made to you"], ["i le au uso", "in the I brother"], ["atoa ma tagata ese,", "and man away"]]},
  {num:6,words:[["o e ua faailoa", "who revealed"], ["mai lou alofa", "from your love"], ["i luma o le ekalesia;", "before the church"], ["afai e te fesoasoani", "if by to help"], ["i lo latou moliga", "in the they the sending"], ["e tusa", "to according to"], ["i le Atua,", "in the God"], ["e lelei lau mea e fai.", "to good your thing to make"]]},
  {num:7,words:[["Auā na latou", "for they"], ["o atu", "o atu"], ["ona o lona suafa,", "because of his name"], ["e lei talia sina mea", "by not received white thing"], ["mai nuu ese.", "from nation away"]]},
  {num:8,words:[["O lea e tatau ai", "therefore it is fitting"], ["ona tatou talia tagata faapea,", "and we (incl) received man thus"], ["ina ia tatou fai ma fesoasoani", "so that we (incl) to be to help"], ["i le upu moni.", "in the word true"]]},
  {num:9,words:[["Na ou tusi atu i le ekalesia,", "I book in the church"], ["a o Tioterifi,", "but of Tioterifi"], ["o lē fia sili ia te i latou,", "not want to do something most unto them"], ["e le talia", "by the received"], ["i matou e ia.", "in we (excl) by him"]]},
  {num:10,words:[["O le mea lea,", "therefore"], ["pe a a'u alu atu,", "whether but I go away"], ["ou te faamanatu ai lana amio", "I will to remind his conduct"], ["o loo faia e ia,", "made by him"], ["o loo tuaupua", "tuaupua"], ["mai ia i matou", "from to in we (excl)"], ["i upu leaga;", "in word evil"], ["e le gata foi i", "by the a snake also in"], ["ia mea,", "to thing"], ["a e le talia lava", "but by the received indeed"], ["e ia le au", "by him the I"], ["uso,", "brother"], ["e vavao atu foi i", "to to forbid also in"], ["e loto", "to heart"], ["i ai,", "therein"], ["na te faateaina foi i latou", "he faateaina also them"], ["i le ekalesia.", "in the church"]]},
  {num:11,words:[["Le pele e,", "the dear by"], ["aua e te faaa'oa'o", "for by make excellent"], ["i le leaga,", "in the evil"], ["na o le lelei.", "the good"], ["O lē amio lelei,", "not conduct good"], ["mai le Atua lava lea;", "from God indeed"], ["peitai o lē amio leaga,", "however of not iniquity"], ["e lei iloa atu lava", "by not see indeed"], ["e ia le Atua.", "by him God"]]},
  {num:12,words:[["Ua logoleleia Temetiu", "logoleleia Temetiu"], ["e tagata uma lava,", "to man all indeed"], ["atoa ma le upu moni lava;", "and the word true indeed"], ["o i matou foi matou", "in we (excl) also we (excl)"], ["te molimau", "a witness"], ["i ai,", "therein"], ["ua outou iloa foi e moni la matou mau.", "you (all) knew also verily our opinion"]]},
  {num:13,words:[["Ua ia te au", "unto me"], ["mea e tele", "great things"], ["e tusi atu ai,", "to book"], ["a ou te le fia tusi atu ia te oe", "but I will the want to do something book unto you"], ["i le vaitusi", "in the ink"], ["ma le fulu tusi.", "and the fulu book"]]},
  {num:14,words:[["Auā ou te faamoemoe", "for I will hope"], ["o le a vave feiloai", "what quick meet one another"], ["i taua,", "in precious"], ["ina ia ta fetautalatalai.", "so that a stroke converse with one another"], ["Ia ia te oe", "to him you"], ["le manuia.", "the peace"], ["O loo alolofa atu le aumea mamae", "alolofa the aumea mamae"], ["ia te oe;", "unto you"], ["ua ou alofa", "I loved"], ["i le aumea mamae uma lava.", "in the aumea mamae all indeed"]]},
];
renderVerseSet(_3jn_ch_1_Verses, '3jn-ch1-verses');

})();