(function() {
var _amo_ch_1_Verses = [
  {num:1,words:[["O upu", "word"], ["a Amosa", "of Amos"], ["o le", "the"], ["na i ai", "therein"], ["i le au fagamanu", "in the I fagamanu"], ["i Tikoa,", "in Tikoa"], ["na ia iloa ai ia", "to known to"], ["Isaraelu,", "Israel"], ["i ona po o Usia", "in then night of Usia"], ["le tupu o Iuta,", "the king of Judas"], ["o ona po foi o Ierepoamo", "then night also of Jeroboam"], ["le atalii o Ioasa,", "the son of Joash"], ["le tupu o Isaraelu;", "the king of Israel"], ["e lua tausaga", "by two year"], ["na va a'i lea mea", "divided thing"], ["i le oo", "in the oo"], ["mai le mafuie.", "from the mafuie"]]},
  {num:2,words:[["Ua ia faapea", "to thus"], ["mai,", "from"], ["E leo tele", "to voice great"], ["mai Ieova mai Siona,", "from the LORD from Zion"], ["e tŭlei ifo foi lona siufofoga", "by tŭlei down also his voice"], ["mai Ierusalema;", "from Jerusalem"], ["e faanoanoa foi mea", "to to mourn also thing"], ["e tataa ai manu", "to animal"], ["a e fagamanu,", "but by fagamanu"], ["e mago foi", "to a small eel also"], ["le tumutumu o Karamelu.", "the top of Carmel"]]},
  {num:3,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["E tolu agasala", "by three sin"], ["a Tamaseko,", "of Damascus"], ["e fa foi,", "by four also"], ["ou te", "I"], ["le liliu ese ai lana sala;", "the turned away his a fine"], ["auā na latou solia ia", "for they despised to"], ["Kiliata i uamea", "Gilead in iron"], ["e soli ai saito.", "to to tread upon wheat"]]},
  {num:4,words:[["A e ou te tuuina atu", "but to I will give"], ["le afi", "the fire"], ["i le fale o Asaeli,", "in the house of Asaeli"], ["e faaumatia ai foi maota", "to destroyed also the name of a tree"], ["o Peniata.", "Peniata"]]},
  {num:5,words:[["Ou te gauia foi", "I gauia also"], ["le faamaufaalava o Tamaseko,", "the faamaufaalava of Damascus"], ["ou te faaumatia", "I destroyed"], ["le ua mau", "the opinion"], ["i le vanu o Avene,", "in the valley of Avene"], ["atoa ma le", "and the"], ["ua 'u'u", "oil"], ["le tootoo", "the staff"], ["i Pete-etena;", "in Pete-etena"], ["e tāfea foi", "by tāfea also"], ["le nuu o Suria", "the nation of Syria"], ["i Kira,", "in Kira"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:6,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["E tolu agasala", "by three sin"], ["a Kasa,", "of Kasa"], ["e fa foi,", "by four also"], ["ou te", "I"], ["le liliu ese ai lana sala;", "the turned away his a fine"], ["auā na latou faatāfeaina", "for they faatāfeaina"], ["le tafeaga atoatoa ia", "the exiles in wa^ completely to"], ["tuuina atu ai", "given"], ["i Etoma.", "in Edom"]]},
  {num:7,words:[["A e ou te tuuina atu", "but to I will give"], ["le afi", "the fire"], ["i le pa o Kasa,", "in the a wall of Kasa"], ["e faaumatia ai", "to destroyed"], ["ona maota.", "and the name of a tree"]]},
  {num:8,words:[["Ou te faaumatia foi", "I destroyed also"], ["le ua mau", "the opinion"], ["i Asetota,", "in Asetota"], ["ma le", "and the"], ["ua 'u'u", "oil"], ["le tootoo", "the staff"], ["i Asekelona;", "in Asekelona"], ["ou te liliu atu lo'u lima", "I turned my five"], ["i Ekerona,", "in Ekron"], ["e fano", "to perish"], ["e ua totoe o Filisitia,", "by phiral of foe of Philistine"], ["o loo o fetalai", "of said"], ["mai ai", "from"], ["le Alii o Ieova.", "the Lord the LORD"]]},
  {num:9,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["E tolu agasala", "by three sin"], ["a Turo,", "of Tyre"], ["e fa foi,", "by four also"], ["ou te", "I"], ["le liliu ese ai lana sala;", "the turned away his a fine"], ["auā na latou tuuina atu", "for they given"], ["le tafeaga atoatoa", "the exiles in wa^ completely"], ["i Etoma,", "in Edom"], ["mona ua", "to burst forth (as faiai"], ["le manatua", "the remember"], ["le feagaiga", "the covenant"], ["a uso.", "but brother"]]},
  {num:10,words:[["A e ou te tuuina atu", "but to I will give"], ["le afi", "the fire"], ["i le pa o Turo,", "in the a wall of Tyre"], ["e faaumatia ai", "to destroyed"], ["ona maota.", "and the name of a tree"]]},
  {num:11,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["E tolu agasala", "by three sin"], ["a Etoma,", "of Edom"], ["e fa foi,", "by four also"], ["ou te", "I"], ["le liliu ese ai lana sala;", "the turned away his a fine"], ["auā na ia tuliloa", "for to pursue"], ["i le pelu lona uso,", "by the sword his brother"], ["na ia le alofa lava,", "to the love indeed"], ["na saei pea lava lona ita;", "to tear continually indeed his angry"], ["na ia tausi pea lava lona ita tele.", "to keep continually indeed his angry great"]]},
  {num:12,words:[["A e ou te tuuina atu", "but to I will give"], ["le afi", "the fire"], ["i Timanu,", "in Timanu"], ["e faaumatia ai maota o Posara.", "to destroyed the name of a tree of Posara"]]},
  {num:13,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["E tolu agasala", "by three sin"], ["a le fanauga", "but the children"], ["a Amoni,", "of Ammon"], ["e fa foi,", "by four also"], ["ou te", "I"], ["le liliu ese ai lana sala;", "the turned away his a fine"], ["auā na latou faatiau", "for they to disembowel"], ["i fafine totō", "in woman totō"], ["i Kiliata,", "in Gilead"], ["ina ia faateleina e", "so that multiplied by"], ["i latou lo latou laueleele.", "them their ground"]]},
  {num:14,words:[["A e ou te tŭtŭ", "but to I tŭtŭ"], ["se afi", "a fire"], ["i le pa o Rapa,", "in the a wall of Rapa"], ["e faaumatia ai", "to destroyed"], ["ma le alaga", "and the cry"], ["ona maota,", "and the name of a tree"], ["i le aso", "in the day"], ["e tau ai", "to season"], ["le taua,", "the precious"], ["ma le afā", "and the cyclone"], ["i le aso e", "in the day by"], ["i ai", "therein"], ["le asiosio.", "the asiosio"]]},
  {num:15,words:[["E alu", "to go"], ["i le tafeaga Malekama,", "in the exiles in wa^ Malekama"], ["o ia", "he"], ["atoa ma alii", "and Lord"], ["ua ia te ia", "to him"], ["faatasi ma ia,", "with him"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
];
renderVerseSet(_amo_ch_1_Verses, 'amo-ch1-verses');

var _amo_ch_2_Verses = [
  {num:1,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["E tolu agasala", "by three sin"], ["a Moapi,", "of Moab"], ["e fa foi,", "by four also"], ["ou te", "I"], ["le liliu ese ai lana sala;", "the turned away his a fine"], ["auā na ia susunuina ivi", "for to burned bone"], ["o le tupu o Etoma", "the king of Edom"], ["na liu panisina.", "liu lime"]]},
  {num:2,words:[["A e ou te tuuina atu", "but to I will give"], ["le afi", "the fire"], ["i Moapi,", "in Moab"], ["e faaumatia ai maota o Kiriota;", "to destroyed the name of a tree of Kiriota"], ["e oti Moapi", "to die Moab"], ["i le vāvāō,", "in the vāvāō"], ["ma le alaga,", "and the cry"], ["ma le leo", "and the voice"], ["o le pu.", "the the tail"]]},
  {num:3,words:[["Ou te faaumatia", "I destroyed"], ["le faamasino o", "the a judge of"], ["i lea mea,", "in thing"], ["ou te fasiotia faatasi", "I slain once"], ["ma ia", "and to"], ["o alii uma,", "Lord all"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:4,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["E tolu agasala", "by three sin"], ["a Iuta,", "of Judas"], ["e fa foi,", "by four also"], ["ou te", "I"], ["le liliu ese ai lana sala;", "the turned away his a fine"], ["auā na latou lafoai", "for they forsaken"], ["le tulafono", "the law"], ["a Ieova,", "of the LORD"], ["e lei tausi foi", "by not keep also"], ["e i latou ana poloaiga;", "by them his commandment"], ["ua faaseseina", "deceived astray"], ["i latou", "them"], ["i a latou mea pepelo,", "in but they thing false"], ["sa naunau atu", "desire"], ["i ai o latou", "therein of they"], ["tamā.", "father"]]},
  {num:5,words:[["A e ou te tuuina atu", "but to I will give"], ["le afi", "the fire"], ["i Iuta,", "in Judas"], ["e faaumatia ai maota o Ierusalema.", "to destroyed the name of a tree of Jerusalem"]]},
  {num:6,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["E tolu agasala", "by three sin"], ["a Isaraelu,", "of Israel"], ["e fa foi,", "by four also"], ["ou te", "I"], ["le liliu ese ai lana sala;", "the turned away his a fine"], ["auā na latou faatauina atu", "for they bought"], ["le ua amiotonu", "the righteous"], ["i ario,", "in silver"], ["ma le", "and the"], ["ua mativa", "want"], ["i seevae", "in a shoe"], ["e lua.", "by two"]]},
  {num:7,words:[["O e naunau atu", "who desire"], ["i le efuefu", "in the dust"], ["o le laueleele", "the ground"], ["i ulu o", "in head of"], ["e matitiva,", "to poor"], ["ma latou liliu ese", "and they turned away"], ["le ala o", "the way"], ["e agamalu;", "to meek"], ["e alu ane foi", "to go along also"], ["le tagata", "the man"], ["atoa ma lona tamā", "and his father"], ["i le teine", "in the girl"], ["e toatasi,", "to one One"], ["ina ia ta'uvaleina ai lo'u igoa paia.", "so that ta'uvaleina my name holy"]]},
  {num:8,words:[["Ua latou taooto foi", "they lie down also"], ["i ofu", "in garment"], ["ua tuu faafaatau", "put faafaatau"], ["i tafatafa o fata faitaulaga uma;", "in to cut in many places of altar all"], ["ma ua latou inu uaina", "and they drink wine"], ["a e", "but by"], ["ua faasalaina", "punished"], ["i le fale o latou", "in the house of they"], ["atua.", "God"]]},
  {num:9,words:[["A o a'u,", "but I am"], ["na ou faaumatia", "I destroyed"], ["le sa Amorī ai o latou", "the of the clan of Amorites of they"], ["luma,", "before"], ["o lona maualuga", "his Iiigli"], ["e pei o le maualuga", "like the Iiigli"], ["o arasi ia,", "cedar to"], ["sa malosi foi o ia", "strong also he"], ["e pei o aluna;", "to like of aluna"], ["na ou faaumatia foi lona fua", "I destroyed also his fruit"], ["i luga", "in above"], ["ma ona aa", "and then aa"], ["i lalo.", "in under"]]},
  {num:10,words:[["Na ou aveina", "I taken away"], ["ae foi outou ai", "but also you (all)"], ["le nuu o Aikupito;", "the nation of Egypt"], ["na ou ta'ita'iina outou", "I led you (all)"], ["i tausaga", "in year"], ["e fagafulu", "to forty"], ["i le vao", "in the wilderness"], ["e maua ai", "to received"], ["le laueleele", "the ground"], ["o le", "the"], ["sa Amorī.", "of the clan of Amorites"]]},
  {num:11,words:[["Na ou faatuina ni o outou", "I built some of you (all)"], ["atalii e fai", "son to make"], ["ma perofeta,", "and prophet"], ["ma ni o outou", "and some of you (all)"], ["taulelea e fai", "young men to make"], ["ma naseri.", "and naseri"], ["Le fanauga", "the children"], ["a Isaraelu", "of Israel"], ["e,", "by"], ["e le", "by the"], ["ua faapea lava ea? o loo fetalai", "and it was so to rise (as a diver to the sur- of said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:12,words:[["A ua outou avatua uaina", "but you (all) given away wine"], ["i le au naseri", "in the I naseri"], ["e inu ai,", "to drink"], ["ma vavao atu", "and to forbid"], ["i le au perofeta,", "in the I prophet"], ["o loo faapea atu,", "saying"], ["Aua le vavalo", "do not prophesy"], ["mai.", "from"]]},
  {num:13,words:[["Faauta,", "behold"], ["ou te taomia outou", "I taomia you (all)"], ["i lalo,", "in under"], ["e pei ona", "as"], ["taomia o le eleele", "taomia Earth"], ["i le fata faataavalevale", "in the altar to roll round and"], ["ua tumu", "fill"], ["i fusi saito.", "in bind wheat"]]},
  {num:14,words:[["E iu vale", "to attain foolish"], ["le solaaga", "the solaaga"], ["o le tele vave,", "the great quick"], ["e le faateleina", "by the multiplied"], ["e le", "by the"], ["ua malosi lona malosi;", "strong his strong"], ["o le toa foi", "the heroic also"], ["na te", "he"], ["le faasaoina lona lava ola.", "the spared his indeed life"]]},
  {num:15,words:[["O le", "the"], ["ua fai aufana", "make bow"], ["e le tumau ia;", "by the enduring to"], ["ma le", "and the"], ["ua momo'e tele vave", "lie down great quick"], ["e le sao ai o ia;", "by the the appointed portion of he"], ["o lē tietie", "not ride"], ["i le solofanua", "in the horse"], ["e le faasaoina ai foi", "by the spared also"], ["e ia lona ola.", "by him his life"]]},
  {num:16,words:[["O le toa", "the heroic"], ["ua sili lona loto tele,", "most his heart great"], ["e sola lē lavalavā o ia", "to escape not naked he"], ["i lea aso,", "in day"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
];
renderVerseSet(_amo_ch_2_Verses, 'amo-ch2-verses');

var _amo_ch_3_Verses = [
  {num:1,words:[["Le fanauga", "the children"], ["a Isaraelu", "of Israel"], ["e,", "by"], ["ia outou faalogologo", "to you (all) listen"], ["mai i lenei upu,", "from in this word"], ["o loo fetalai", "said"], ["mai ai Ieova ia te outou,", "from the LORD unto you"], ["atoa ma le aiga uma", "and the family all"], ["na ou aveina", "I taken away"], ["ae ai", "but"], ["le nuu o Aikupito;", "the nation of Egypt"], ["o loo faapea", "saying"], ["mai,", "from"]]},
  {num:2,words:[["Ua na o outou", "of you (all)"], ["lava ua ou iloa", "indeed I known"], ["i aiga uma", "in family all"], ["o le lalolagi;", "the earth"], ["o le mea lea ou te faasalaina ai outou", "therefore I punished you (all)"], ["ona o", "because of"], ["a outou agasala uma.", "but you (all) sin all"]]},
  {num:3,words:[["E feoai faatasi ea", "by feoai once to rise (as a diver to the sur-"], ["se toalua,", "a two (people)"], ["pe a le loto gatasi", "whether but the heart gatasi"], ["i laua?", "them"]]},
  {num:4,words:[["E tagi ea", "to cry to rise (as a diver to the sur-"], ["le leona", "the lion"], ["i le vao,", "in the wilderness"], ["pe a leai", "whether but no"], ["se mea", "a thing"], ["ua na saeia?", "spared"], ["E lagona atu ea", "to to understand to rise (as a diver to the sur-"], ["le leo", "the voice"], ["o le tamai leona ai lona lua,", "the son lion his two"], ["pe afai", "whether if"], ["ua na", "ua na"], ["le maua", "the received"], ["se mea?", "a thing"]]},
  {num:5,words:[["E lavea ea", "to saved to rise (as a diver to the sur-"], ["le manu lele", "the animal fly"], ["i le mailei", "in the a trap"], ["i le laueleele,", "in the earth"], ["a ua leai", "but there was not"], ["se mailei", "a a trap"], ["mo ia?", "for to"], ["E avae ea", "to take away to rise (as a diver to the sur-"], ["le mailei ai", "the a trap"], ["le laueleele,", "the ground"], ["a ua", "but"], ["le maua", "the received"], ["se mea?", "a thing"]]},
  {num:6,words:[["E ilia ea", "by ilia to rise (as a diver to the sur-"], ["le pu", "the the tail"], ["i le aai,", "in the city"], ["a e le atuatuvale ai tagata?", "but by the to be greatly dis- man"], ["E tupu ea", "to king to rise (as a diver to the sur-"], ["se malaia", "a disaster"], ["i le aai,", "in the city"], ["a e le faia", "but by the made"], ["e Ieova?", "the LORD"]]},
  {num:7,words:[["E le faia lava", "by the made indeed"], ["se mea", "a thing"], ["e le Alii o Ieova,", "by the Lord the LORD"], ["a e faaalia lona finagalo", "but to revealed his a chiefs will or desire"], ["i ana auauna o perofeta.", "in his servant of prophet"]]},
  {num:8,words:[["Ua tagi", "cry"], ["le leona,", "the lion"], ["po o ai", "night of"], ["se le fefe?", "a the get scared"], ["ua fetalai mai", "said"], ["le Alii o Ieova,", "the Lord the LORD"], ["po o ai", "night of"], ["se le vavalo?", "a the prophesy"]]},
  {num:9,words:[["Ia outou tala'iina atu", "to you (all) preached"], ["i maota o Asetota,", "in the name of a tree of Asetota"], ["ma maota", "and the name of a tree"], ["i le nuu o Aikupito,", "in the land Egypt"], ["ma ia outou faapea atu,", "and to you (all) thus"], ["Ia outou faapotopoto", "to you (all) gather"], ["mai i mauga o Samaria,", "from in mountain of Samaria"], ["ma vaavaai atu ai", "and watch"], ["i vāvāō tetele o", "in vāvāō great of"], ["i ai,", "therein"], ["atoa ma sauaga o", "and sauaga of"], ["i ai.", "therein"]]},
  {num:10,words:[["Auā o loo fetalai", "for of said"], ["mai Ieova,", "from the LORD"], ["Latou te", "they"], ["le iloa", "the known"], ["ona fai mea tonu,", "and make thing right"], ["o e faaputu", "who to gather together"], ["i o latou maota o mea", "in of they the name of a tree of thing"], ["e maua", "to received"], ["i le saua", "in the to have a return of sick-"], ["ma le vete.", "and the plunder"]]},
  {num:11,words:[["O le mea lea o loo faapea", "therefore saying"], ["mai ai", "from"], ["le Alii o Ieova,", "the Lord the LORD"], ["O le", "the"], ["ua ita mai", "angry from"], ["e fealuai o ia", "by fealuai he"], ["i le nuu;", "in the land"], ["e aveesea foi e ia", "to removed away also by him"], ["lou malosi ai ia te oe,", "your strong unto you"], ["e vetea ou maota.", "by vetea I the name of a tree"]]},
  {num:12,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["Faapei ona fao", "like then to seize"], ["e le leoleo mamoe o alaga", "by the shepherd of cry"], ["e lua,", "by two"], ["po o se fasi taliga", "night a kill ear"], ["i le gutu", "in the mouth"], ["o le leona,", "the lion"], ["e faapea ona", "saying and"], ["laveaiina o le fanauga", "delivered the children"], ["a Isaraelu o", "of Israel of"], ["e nonofo", "to dwell"], ["i Samaria,", "in Samaria"], ["i le pito moega,", "in the edge bed"], ["ma Tamaseko foi", "and Damascus also"], ["i le moega.", "in the bed"]]},
  {num:13,words:[["Ia outou faalogologo,", "to you (all) listen"], ["ma faailo atu", "and faailo"], ["i le aiga o Iakopo,", "in the family of James"], ["o loo faapea", "saying"], ["mai le Alii o Ieova,", "from the Lord the LORD"], ["o le Atua o 'au.", "of God I"]]},
  {num:14,words:[["O le aso ou te taui atu ai agasala", "the day I a reward sin"], ["a Isaraelu ia te ia,", "of Israel to him"], ["ou te asiasi foi", "I spy out also"], ["i fata faitaulaga", "in altar"], ["i Peteli;", "in Bethel"], ["e vavaeeseina foi nifo o fata faitaulaga,", "to separated apart also tooth of altar"], ["ona pauu ai lea", "and fell"], ["i le eleele.", "the ground"]]},
  {num:15,words:[["Ou te taia", "I struck"], ["le fale", "the house"], ["o le tausaga maalili,", "the year maalili"], ["atoa ma le fale", "and the house"], ["o le tausaga vevela;", "the year to be hot"], ["e faaumatia fale nifo elefane,", "to destroyed house tooth elefane"], ["e mavae atu foi o fale tetele,", "to passed also of house great"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
];
renderVerseSet(_amo_ch_3_Verses, 'amo-ch3-verses');

var _amo_ch_4_Verses = [
  {num:1,words:[["Ia outou faalogologo", "to you (all) listen"], ["i lenei upu o outou", "in this word of you (all)"], ["povi fafine o Vasana,", "cattle woman of Bashan"], ["o loo", "o loo"], ["i le mauga o Samaria,", "in the mountain of Samaria"], ["o e faasaua", "who to be oppressive"], ["i e vaivai,", "in to weak"], ["ma faasaunoa", "and faasaunoa"], ["i e matitiva,", "in to poor"], ["o e faapea atu", "who thus"], ["i o latou matai,", "in of they chief"], ["Au mai ia,", "bring to"], ["matou te feinu ai.", "we (excl) feinu"]]},
  {num:2,words:[["Ua tauto", "to take an oath"], ["le Alii o Ieova", "the Lord the LORD"], ["i lona paia,", "in his holy"], ["faauta,", "behold"], ["e oo mai aso ia te outou", "it shall come to pass from day unto you"], ["na te aveeseina ai outou", "he carried away you (all)"], ["i mātau,", "in mātau"], ["ma la outou fanau", "and your born"], ["i mātau i'a.", "in mātau fish"]]},
  {num:3,words:[["Tou te o atu foi", "second person plural of also"], ["i mea", "in thing"], ["ua lepetia,", "overthrown"], ["taitasi i le mea", "each in the thing"], ["ua ia lumanai ai,", "to lumanai"], ["e lafoaiina outou ai", "to forsaken you (all)"], ["le maota,", "the the name of a tree"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:4,words:[["Ia outou", "to you (all)"], ["o mai", "from"], ["i Peteli,", "in Bethel"], ["ma fai ai amio leaga;", "and make iniquity"], ["ina faatele ia agasala", "let faatele to sin"], ["i Kilikala;", "in Gilgal"], ["ia outou avatu", "to you (all) give away"], ["i taeao", "in morning"], ["a outou taulaga,", "but you (all) offering"], ["ma mea", "and thing"], ["e sefulu a'i", "by ten"], ["a outou mea", "but you (all) thing"], ["i lona tolu o tausaga.", "in his three of year"]]},
  {num:5,words:[["Ina fai ia se taulaga faafetai", "let make to an offering to tliank"], ["i mea", "in thing"], ["ua faafefeteina;", "feared"], ["ia outou tala'iina taulaga", "to you (all) preached offering"], ["e faia", "to made"], ["ma le loto,", "and the heart"], ["ia outou logo atu ai;", "to you (all) to hear"], ["auā o lo outou loto lea,", "for your heart"], ["le fanauga", "the children"], ["a Isaraelu", "of Israel"], ["e,", "by"], ["o loo fetalai", "said"], ["mai ai", "from"], ["le Alii o Ieova.", "the Lord the LORD"]]},
  {num:6,words:[["O a'u foi,", "I am also"], ["ua ou avatu ia te outou", "I give away unto you"], ["nifo mamā", "tooth clean"], ["i a outou aai uma,", "in but you (all) city all"], ["ma le oge", "and the a famine"], ["i mea", "in thing"], ["e 'ai", "to eat"], ["i o outou nuu uma;", "in of you (all) nation all"], ["a ua outou", "but you (all)"], ["le toe foi", "the again also"], ["mai lava ia te au,", "from indeed unto me"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:7,words:[["Ua ou taofia foi", "I held back also"], ["le ua ia te outou,", "the unto you"], ["a e toe tolu masina", "but to again three moon"], ["i le oo ai", "in the oo"], ["le seleselegāsaito;", "the seleselegāsaito"], ["ua ou faatotō ifo", "I faatotō down"], ["le ua", "the"], ["i le tasi aai,", "in the one city"], ["a o le isi aai", "but the other city"], ["ua ou", "I"], ["le faauaina;", "the faauaina"], ["ua uaina", "wine"], ["le tasi pito nuu,", "the one edge nation"], ["a o le nuu", "but the nation"], ["e lei uaina", "by not wine"], ["ua mago lea.", "a small eel"]]},
  {num:8,words:[["Ona o atu ai lea", "because of"], ["o aai", "city"], ["pe lua", "whether two"], ["pe tolu", "whether three"], ["i le tasi aai", "in the one city"], ["e inu vai ai;", "to drink water"], ["a ua", "but"], ["le malilie;", "the malilie"], ["a ua", "but"], ["le toe foi", "the again also"], ["mai lava outou ia te au,", "from indeed you (all) unto me"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:9,words:[["Ua ou taia outou", "I struck you (all)"], ["i le mamae", "in the mamae"], ["ma le polopologā;", "and the polopologā"], ["ua 'aina", "edible"], ["e le sē kasama o outou", "by the sē kasama of you (all)"], ["faatoaga,", "garden"], ["ma o outou tovine,", "and of you (all) vineyard"], ["ma o outou mati,", "and of you (all) fig"], ["ma outou olive;", "with you olive"], ["a na", "but"], ["le toe foi", "the again also"], ["mai outou ia te au,", "from you (all) unto me"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:10,words:[["Ua ou auina atu ia te outou", "I sent unto you"], ["le faamai,", "the faamai"], ["e pei ona", "as"], ["i ai", "therein"], ["i Aikupito;", "in Egypt"], ["ua ou fasia", "I struck"], ["i le pelu o outou", "by the sword you (all)"], ["taulelea,", "young men"], ["o outou solofanua foi", "you (all) horse also"], ["ua aveeseina;", "carried away"], ["ua ou faaoo", "I bring upon"], ["ae i o outou", "but in of you (all)"], ["pogaiisu le elo o", "the nostrils the elo of"], ["a outou toagālauapi;", "but you (all) toagālauapi"], ["a ua outou", "but you (all)"], ["le toe foi", "the again also"], ["mai ia te au,", "from I"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:11,words:[["Ua ou faaumatia nisi o outou,", "I destroyed some of you (all)"], ["faapei ona faaumatia", "like then destroyed"], ["e le Atua o Sotoma", "God Sodom"], ["ma Komoro;", "and Gomorrah"], ["e pei o le motumotu", "like the motumotu"], ["o le afi outou", "the fire you (all)"], ["ua seia mai", "until from"], ["le afi;", "the fire"], ["a ua outou", "but you (all)"], ["le toe foi", "the again also"], ["mai ia te au,", "from I"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:12,words:[["O le mea lea", "therefore"], ["e faapea ai", "saying"], ["ona ou faia ia te oe", "and I made unto you"], ["Isaraelu e,", "Israel by"], ["Ou te fai lenei mea", "I make this thing"], ["ia te oe,", "unto you"], ["o le mea lava lea Isaraelu", "the thing indeed Israel"], ["e,", "by"], ["ia e sauni ai lua te fetaiai", "to to he who beg^ins the game two fetaiai"], ["ma lou Atua.", "and your God"]]},
  {num:13,words:[["Auā faauta mai,", "for behold from"], ["o le", "the"], ["na faia mauga,", "made mountain"], ["ma na faia", "and made"], ["le matagi,", "the wind"], ["ma ua faailoaina atu", "and faailoaina"], ["i le tagata lona manatu,", "in the man his thought"], ["o le", "the"], ["na te liua", "he turned into"], ["le taeao", "the morning"], ["i le pouliuli,", "in the darkness"], ["o lē savali", "not walk"], ["i luga o mea maualuluga", "upon thing most high"], ["o le lalolagi,", "the earth"], ["o Ieova,", "the LORD"], ["o le Atua o 'au,", "of God I"], ["o lona suafa lea.", "his name"]]},
];
renderVerseSet(_amo_ch_4_Verses, 'amo-ch4-verses');

var _amo_ch_5_Verses = [
  {num:1,words:[["Le aiga o Isaraelu", "the family of Israel"], ["e,", "by"], ["ia outou faalogologo", "to you (all) listen"], ["i lenei upu ou te sauni atu ai", "in this word I he who beg^ins the game"], ["ia te outou,", "unto you"], ["o le pese", "the a song"], ["e aualofa a'i lava .", "to a keepsake indeed"]]},
  {num:2,words:[["Ua paū", "paū"], ["le taupou o Isaraelu,", "the virgin of Israel"], ["e le toe tulai;", "by the again arose up"], ["ua taatia o ia", "taatia he"], ["i lona laueleele,", "in his ground"], ["e leai", "there is not"], ["se na te faatulaiina o ia.", "a he faatulaiina he"]]},
  {num:3,words:[["Auā o loo faapea", "for saying"], ["mai le Alii o Ieova,", "from the Lord the LORD"], ["O le aai", "the city"], ["na o atu ai", "of"], ["le toaafe,", "the toaafe"], ["e totoe", "to phiral of foe"], ["le toaselau;", "the a hundred (people)"], ["i le", "in the"], ["ma le aai", "and the city"], ["na o atu ai", "of"], ["le toaselau,", "the a hundred (people)"], ["e totoe", "to phiral of foe"], ["le toatinoagafulu", "the ten (people)"], ["i le aiga o Isaraelu.", "in the family of Israel"]]},
  {num:4,words:[["Auā o loo faapea", "for saying"], ["mai Ieova", "from the LORD"], ["i le aiga o Isaraelu,", "in the family of Israel"], ["Ia outou saili", "to you (all) seek"], ["mai ia te au,", "from I"], ["tou te ola ai.", "second person plural life"]]},
  {num:5,words:[["A e aua", "but to for"], ["le saili ia Peteli,", "the seek to Bethel"], ["aua le o", "for the of"], ["i Kilikala,", "in Gilgal"], ["aua foi", "for also"], ["le ui atu", "the although"], ["i Peresepa;", "in Peresepa"], ["auā e matuā tāfea Kilikala,", "for to exceedingly tāfea Gilgal"], ["e iu vale Peteli.", "to attain foolish Bethel"]]},
  {num:6,words:[["Ia outou saili ia", "to you (all) seek to"], ["Ieova,", "the LORD"], ["tou te ola ai,", "second person plural life"], ["ina ne'i oo atu o ia", "let now arrived he"], ["pei se afi", "like a fire"], ["i le aiga o Iosefa,", "in the family of Joseph"], ["ma faaumatia ai,", "and destroyed"], ["e leai foi", "there is not also"], ["se tasi", "a one"], ["i Peteli", "in Bethel"], ["na te tineia.", "he tineia"]]},
  {num:7,words:[["O outou", "you (all)"], ["o e liliu", "who turned"], ["le faamasinoga", "the judgment"], ["i laena,", "in laena"], ["ma lafo", "and cloth used as gratuity for a talking chief"], ["i lalo", "in under"], ["le amiotonu", "the righteous"], ["i le eleele,", "the ground"]]},
  {num:8,words:[["ia outou saili", "to you (all) seek"], ["i le", "in the"], ["na na faia Kima", "made Kima"], ["ma Kisila;", "and Kisila"], ["o le", "the"], ["na te liua", "he turned into"], ["le ata", "the a shadow"], ["o le oti", "the die"], ["i le taeao,", "in the morning"], ["ma faapouliuligia", "and faapouliuligia"], ["le ao peiseai", "the day as if"], ["ua po;", "night"], ["o le", "the"], ["na te valaauina", "he called"], ["le suāsami", "the suāsami"], ["o le sami,", "Sea"], ["ma liligi ifo ai", "and to pour down"], ["i le fogāeleele;", "the face of the earth"], ["o Ieova", "the LORD"], ["o lona suafa lea.", "his name"]]},
  {num:9,words:[["O le", "the"], ["na te faaoo faafuasei atu", "he bring upon faafuasei"], ["le faatafunaga", "the faatafunaga"], ["i le", "in the"], ["ua malosi,", "strong"], ["ona oo atu ai lea", "and arrived"], ["o le faatafunaga", "the faatafunaga"], ["i le 'olo.", "in the fortress"]]},
  {num:10,words:[["Ua latou ita atu", "they angry"], ["i le", "in the"], ["ua aoai", "chastise"], ["i le faitotoa;", "at the door"], ["ma ua latou 'ino'ino", "and they hate"], ["i le", "in the"], ["ua tautala faamaoni.", "to talk faithful"]]},
  {num:11,words:[["O lenei foi,", "this also"], ["ua outou soli", "you (all) to tread upon"], ["i le", "in the"], ["ua vaivai,", "weak"], ["mona ua outou tali foi", "to burst forth (as faiai you (all) respond also"], ["ia te ia", "to him"], ["o taulaga saito;", "offering wheat"], ["o le mea lea", "therefore"], ["e ui", "to although"], ["ina faia e outou", "let made by you (all)"], ["o fale maa talai,", "house stone preach"], ["a e tou te", "but to second person plural"], ["le nonofo ai;", "the dwelling"], ["ua outou totōina tovine lelei,", "you (all) totōina vineyard good"], ["a e tou te", "but to second person plural"], ["le inu uaina ai.", "the drink wine"]]},
  {num:12,words:[["Auā ua ou iloa", "for I known"], ["a outou agasala", "but you (all) sin"], ["ua matuā tele,", "exceedingly great"], ["ma a outou amio", "and but you (all) conduct"], ["e matuā leaga;", "to exceedingly evil"], ["o loo faasaua", "to be oppressive"], ["i le", "in the"], ["ua amiotonu,", "righteous"], ["ua talia", "received"], ["se taui,", "a a reward"], ["ma ua faafoi atu", "and return back"], ["i e", "in by"], ["ua matitiva o", "poor of"], ["i le faitotoa.", "at the door"]]},
  {num:13,words:[["O le mea lea", "therefore"], ["e faalologo ai", "to to hold one's tongue"], ["le ua poto", "the wise"], ["i ia", "in to"], ["ona po;", "and night"], ["auā e leaga ia", "for to evil to"], ["ona po.", "and night"]]},
  {num:14,words:[["Ia outou saili", "to you (all) seek"], ["i le lelei,", "in the good"], ["a e le", "but by the"], ["o le leaga,", "the evil"], ["ina ia ola ai outou;", "so that life you (all)"], ["ona i ai lea ia te outou", "and therein unto you"], ["o Ieova", "the LORD"], ["o le Atua o 'au,", "of God I"], ["e pei ona", "as"], ["outou fai mai ai.", "you (all) said"]]},
  {num:15,words:[["Ia outou 'ino'ino", "to you (all) hate"], ["i le leaga,", "in the evil"], ["a e loto atu", "but to heart"], ["i le lelei,", "in the good"], ["ma ia outou faatumau", "and to you (all) faatumau"], ["le faamasinoga", "the judgment"], ["i le faitotoa;", "at the door"], ["atonu e alofa Ieova", "impers to love the LORD"], ["le Atua o 'au", "God I"], ["i e", "in by"], ["ua totoe ia Iosefa.", "phiral of foe to Joseph"]]},
  {num:16,words:[["O le mea lea o loo faapea", "therefore saying"], ["mai ai Ieova,", "from the LORD"], ["le Atua o 'au,", "God I"], ["o le Alii lava,", "the Lord indeed"], ["E pa", "to a wall"], ["le lauaitu", "the a weeping"], ["i ala uma lava;", "in way all indeed"], ["latou te faapea ane", "they thus"], ["i ala tele uma,", "in way great all"], ["Aue!", "alas! oh!"], ["aue!", "alas! oh!"], ["latou te valaau foi", "they call also"], ["i lē galue", "in not till"], ["i fanua ia te faanoanoa;", "in land unto to mourn"], ["ma e", "and by"], ["ua iloa pese e au", "knew a song to I"], ["alofa a'i,", "love"], ["ia tagitu'i", "to tagitu'i"], ["i latou.", "them"]]},
  {num:17,words:[["E pa foi", "to a wall also"], ["le lauaitu", "the a weeping"], ["i tovine uma,", "in vineyard all"], ["auā ou te ui atu", "for I although"], ["ia te oe,", "unto you"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:18,words:[["Talofa ia te outou", "hello unto you"], ["o e mananao", "who desire"], ["i le aso o Ieova!", "in the day the LORD"], ["Se a ea lona aoga", "a but to rise (as a diver to the sur- his useful"], ["ia te outou?", "unto you"], ["O le aso o Ieova,", "the day the LORD"], ["o le pouliuli lea,", "the darkness"], ["a e le", "but by the"], ["o le malamalama.", "the light"]]},
  {num:19,words:[["E pei o le tagata", "like the man"], ["ua sola ese", "escape away"], ["i le leona,", "in the lion"], ["a ua la fetaiai", "but la fetaiai"], ["ma le urosa;", "and the urosa"], ["pe ulufale atu", "whether enter"], ["i le fale,", "in the house"], ["ma totoo ai lona lima", "and totoo his five"], ["i le pa puipui,", "in the a wall a duor"], ["ona utia ai lea o ia", "and utia he"], ["i le gata.", "in the a snake"]]},
  {num:20,words:[["E le", "by the"], ["o le pouliuli ea", "the darkness to rise (as a diver to the sur-"], ["le aso o Ieova,", "the day the LORD"], ["a e le malamalama;", "but by the light"], ["e pogisa lava,", "to darkness indeed"], ["e leai sona pupula?", "there is not sona brightness"]]},
  {num:21,words:[["Ua ou 'ino'ino,", "I hate"], ["ua leaga ia te au", "evil unto me"], ["o outou tausamiga;", "you (all) feast"], ["ou te", "I"], ["le fiafia", "the competition"], ["i o outou faapotopotoga.", "in of you (all) gathering"]]},
  {num:22,words:[["E ui", "to although"], ["ina outou au", "let you (all) I"], ["mai ia te au", "from I"], ["o taulaga mu,", "burnt offerings"], ["ma a outou taulaga", "and but you (all) offering"], ["i mea", "in thing"], ["e 'ai,", "to eat"], ["ou te", "I"], ["le talia;", "the received"], ["o le taulaga faafetai", "the offering to tliank"], ["i a outou manu pepeti,", "in but you (all) animal fat portions"], ["ou te", "I"], ["le vaai atu", "the looked toward"], ["i ai.", "therein"]]},
  {num:23,words:[["Ia e ave ese ia te au", "to to take away unto me"], ["le taalili o ou pese;", "the resounding of I a song"], ["o le leo mălie foi", "the voice mălie also"], ["o au napeli ou te", "I am napeli I"], ["le faalogo ai.", "the hearken"]]},
  {num:24,words:[["A ia tafe ifo", "but to to flow down"], ["le faamasinoga", "the judgment"], ["e pei o vai,", "to like of water"], ["ma le amiotonu", "and the righteous"], ["e pei o le vai", "like the water"], ["e tafe tetele lava.", "to to flow great indeed"]]},
  {num:25,words:[["Le aiga o Isaraelu", "the family of Israel"], ["e,", "by"], ["pe na outou au", "whether you (all) I"], ["mai ea ia te au", "from to rise (as a diver to the sur- unto me"], ["o taulaga,", "offering"], ["ma taulaga", "and offering"], ["i mea", "in thing"], ["e 'ai", "to eat"], ["i le vao", "in the wilderness"], ["i tausaga", "in year"], ["e fagafulu?", "to forty"]]},
  {num:26,words:[["Na outou tauave lava", "you (all) tauave indeed"], ["le malumalu", "the temple"], ["o lo outou Moloka,", "your Molech"], ["ma Kiuna,", "and Kiuna"], ["o outou tupua,", "you (all) pillar"], ["o le fetu", "the star"], ["o lo outou atua", "your God"], ["na outou faia", "you (all) made"], ["mo outou.", "for you"]]},
  {num:27,words:[["Ou te faatāfeaina outou", "I faatāfeaina you (all)"], ["i ona tala atu o Tamaseko,", "in then side of Damascus"], ["o loo fetalai", "said"], ["mai ai Ieova,", "from the LORD"], ["o le Atua o 'au,", "of God I"], ["o lona suafa lea.", "his name"]]},
];
renderVerseSet(_amo_ch_5_Verses, 'amo-ch5-verses');

var _amo_ch_6_Verses = [
  {num:1,words:[["Talofa i", "hello in"], ["e o faatalanoa", "by of faatalanoa"], ["i Siona,", "in Zion"], ["ma e o nonofo faatalanoa", "and by of dwelling faatalanoa"], ["i le mauga o Samaria,", "in the mountain of Samaria"], ["e ua ta'ua", "by us (two, incl)"], ["i atu nuu silisili,", "in nation very much"], ["na ō", "go (plural)"], ["i ai", "therein"], ["le aiga o Isaraelu.", "the family of Israel"]]},
  {num:2,words:[["Ia outou", "to you (all)"], ["o atu", "o atu"], ["i Kalene,", "in Kalene"], ["ma vaavaai atu,", "and watch"], ["i le tou o atu ai", "in the second person plural of"], ["i Amato tele;", "in Amato great"], ["i le o ifo ai", "in the of down"], ["i Kata", "in Gad"], ["i Filisitia;", "in Philistine"], ["e sili ea lo latou lelei", "to most to rise (as a diver to the sur- their good"], ["i na malo,", "in government"], ["pe sili ea", "whether most to rise (as a diver to the sur-"], ["ona tele", "and great"], ["o lo latou laueleele", "their ground"], ["i lo outou laueleele?", "in the you (all) ground"]]},
  {num:3,words:[["Talofa i", "hello in"], ["e ua manatu", "by thought"], ["ua mamao", "to be far ofl\""], ["le aso vale,", "the day foolish"], ["ma faalatalata mai", "and draw near from"], ["le nofoa o", "the a seat of"], ["i ai", "therein"], ["le faasaua;", "the to be oppressive"]]},
  {num:4,words:[["o e taooto", "who lie down"], ["i moega nifo elefane,", "in bed tooth elefane"], ["ma latou taooto", "and they lie down"], ["i o latou moega;", "in of they bed"], ["ma aai", "and city"], ["i tamai mamoe", "in son sheep"], ["o le lafu,", "the herd"], ["ma tamai povi ai", "and son cattle"], ["le fale povi;", "the house cattle"]]},
  {num:5,words:[["o e pepese faatasi", "who sing once"], ["ma le leo", "and the voice"], ["o le napeli,", "the napeli"], ["ma latou sauni", "and they he who beg^ins the game"], ["mo i latou laaupese,", "for them laaupese"], ["e pei o Tavita;", "to like of David"]]},
  {num:6,words:[["o e inu uaina", "who drink wine"], ["i ipu tetele,", "in cup great"], ["ma uu ia te", "and oil unto"], ["i latou", "them"], ["i uu", "in oil"], ["e sili", "to most"], ["ona lelei;", "and good"], ["a ua", "but"], ["le tiga", "the grieved"], ["i latou", "them"], ["ona o le malaia o Iosefa.", "because of the disaster of Joseph"]]},
  {num:7,words:[["O le mea lea", "therefore"], ["e tāfea ai nei", "by tāfea this"], ["i latou,", "them"], ["e muamua", "to first"], ["i e tāfea,", "in by tāfea"], ["e mavae atu", "to passed"], ["le alaga fiafia o", "the cry competition of"], ["e taooto.", "to lie down"]]},
  {num:8,words:[["Ua tauto", "to take an oath"], ["le Alii o Ieova", "the Lord the LORD"], ["i lona soifua,", "in his live"], ["o loo fetalai", "said"], ["mai ai Ieova", "from the LORD"], ["le Atua o 'au,", "God I"], ["Ua ou 'ino'ino", "I hate"], ["i le mamalu o Iakopo,", "in the glory of James"], ["ua ou 'ino'ino foi", "I hate also"], ["i ona maota;", "in then the name of a tree"], ["o le mea lea ou te tuuina atu ai", "therefore I will give"], ["le aai", "the city"], ["atoa ma mea", "and thing"], ["ua tumu ai.", "fill"]]},
  {num:9,words:[["Afai foi", "if also"], ["e totoe tagata", "to phiral of foe man"], ["e toatinoagafulu", "to ten (people)"], ["i le fale", "in the house"], ["e tasi,", "by one"], ["latou te oti ai lava.", "they die indeed"]]},
  {num:10,words:[["E siitia", "to lifted up"], ["se tasi", "a one"], ["e le uso", "by the brother"], ["o lona tamā,", "his father"], ["o le", "the"], ["na te susunu foi ia te ia,", "he burn also to him"], ["e au mai ai ivi ai", "to bring bone"], ["le fale;", "the house"], ["na te faapea atu", "he thus"], ["i le", "in the"], ["ua i mea aupito", "in thing ^ to be"], ["i totonu", "in inside"], ["o le fale,", "the house"], ["Pe ai", "whether"], ["se tasi", "a one"], ["ua i ai pea ia te oe?", "therein continually unto you"], ["Ona tali atu foi lea", "and respond also"], ["o ia,", "he"], ["E leai lava.", "there is not indeed"], ["Ona faapea mai lea o ia,", "and thus from he"], ["Faalologo ia auā", "to hold one's tongue to for"], ["e le tatau ona", "by the to wring out then"], ["ta'ua o le suafa o Ieova.", "us (two, incl) the name the LORD"]]},
  {num:11,words:[["Auā faauta mai ea,", "for behold from to rise (as a diver to the sur-"], ["ua poloai atu Ieova,", "command the LORD"], ["na te taia foi", "he struck also"], ["le fale tele ia", "the house great to"], ["solo,", "to move swiftly"], ["ma le fale itiiti ia", "and the house small to"], ["lepetia.", "overthrown"]]},
  {num:12,words:[["E taufetuli ea solofanua", "by taufetuli to rise (as a diver to the sur- horse"], ["i le papa?", "in the burster"], ["pe suatia ai ea", "whether suatia to rise (as a diver to the sur-"], ["e se tasi", "by a one"], ["i povi? auā", "in cattle for"], ["ua outou liu", "you (all) liu"], ["i rosa", "in rosa"], ["le faamasinoga,", "the judgment"], ["ma le fua", "and the fruit"], ["o le amiotonu", "the righteous"], ["i laena.", "in laena"]]},
  {num:13,words:[["O outou", "you (all)"], ["o e fiafia", "who competition"], ["i se mea faatauvaa,", "in a thing vain"], ["o e faapea", "who thus"], ["mai,", "from"], ["Po ua", "night"], ["le maua mai ea", "the received from to rise (as a diver to the sur-"], ["i lo tatou malosi o nifo", "in the we (incl) strong of tooth"], ["mo i tatou?", "for in we (incl)"]]},
  {num:14,words:[["A o lenei,", "but of this"], ["faauta mai,", "behold from"], ["le aiga o Isaraelu", "the family of Israel"], ["e,", "by"], ["ou te faatuina", "I built"], ["se tasi nuu,", "a one nation"], ["latou te fai oe", "they make you"], ["mo latou fili,", "for they to choose"], ["o loo fetalai", "said"], ["mai ai Ieova", "from the LORD"], ["le Atua o 'au;", "God I"], ["latou te faasaua ia te outou,", "they to be oppressive unto you"], ["e pau mai", "to fall from"], ["i le mea", "in the thing"], ["e ui atu ai", "to although"], ["i Amato,", "in Amato"], ["e pau mai", "to fall from"], ["i le vaitafe", "in the river"], ["o le vao.", "the vegetation"]]},
];
renderVerseSet(_amo_ch_6_Verses, 'amo-ch6-verses');

var _amo_ch_7_Verses = [
  {num:1,words:[["Ua faapea ona", "saying and"], ["faailoaina mai ia te au", "faailoaina from I"], ["e le Alii o Ieova;", "by the Lord the LORD"], ["faauta,", "behold"], ["na ia faatupuina o sē akerise", "to raised up of sē akerise"], ["i ona faatoa tutupu", "in then just now bring forth"], ["ae o le vao mulimuli;", "but the vegetation follow after"], ["faauta foi,", "and behold"], ["o le vao mulimuli ia,", "the vegetation follow after to"], ["a ua mavae atu seleselegāmutia", "but after seleselegāmutia"], ["a le tupu.", "but the king"]]},
  {num:2,words:[["Ona oo lea", "and oo"], ["ina uma ona", "let all then"], ["aai o le vao iti", "city the vegetation small"], ["o le fanua,", "the land"], ["ona ou faapea atu ai lea,", "and I thus"], ["Le Alii Ieova", "the Lord the LORD"], ["e,", "by"], ["ou te aioi atu ia", "I cry out to"], ["e faamagalo mai.", "to forgive from"], ["Pe tulai ia te ai Iakopo,", "whether arose up unto James"], ["auā ua vaivai lava ia?", "for weak indeed to"]]},
  {num:3,words:[["Ua salamo Ieova", "repent the LORD"], ["i lena mea;", "in that thing"], ["ua faapea mai Ieova,", "and said the LORD"], ["E le oo.", "by the oo"]]},
  {num:4,words:[["Ua faapea ona", "saying and"], ["faailoaina mai ia te au", "faailoaina from I"], ["e le Alii o Ieova;", "by the Lord the LORD"], ["faauta,", "behold"], ["na valaau atu", "call"], ["le Alii o Ieova ia", "the Lord the LORD to"], ["tauia i le afi,", "recompense in the fire"], ["i le", "in the"], ["ua faaumatia", "destroyed"], ["le moana tele,", "the deep great"], ["ma faaumatia ai", "and destroyed"], ["le tasi mea.", "the one thing"]]},
  {num:5,words:[["Ona ou fai atu lea,", "and I said to"], ["Le Alii Ieova", "the Lord the LORD"], ["e,", "by"], ["ou te aioi atu,", "I cry out"], ["ina soia;", "let stop"], ["pe tulai ia te ai Iakopo,", "whether arose up unto James"], ["auā ua vaivai lava ia?", "for weak indeed to"]]},
  {num:6,words:[["Ua salamo Ieova", "repent the LORD"], ["i lenei mea;", "in this thing"], ["ua faapea mai", "and said"], ["le Alii o Ieova,", "the Lord the LORD"], ["E le oo foi lenei mea.", "by the oo also this thing"]]},
  {num:7,words:[["Sa faapea ona", "saying and"], ["faailoaina mai e ia", "faailoaina from by him"], ["ia te au;", "unto me"], ["faauta,", "behold"], ["ua tu", "stand"], ["le Alii", "the Lord"], ["i le aupa tu sa'o,", "in the aupa stand the appointed portion of"], ["ua i ai", "therein"], ["i lona aao", "in his hand (extended)"], ["o le fua faatautau.", "the fruit faatautau"]]},
  {num:8,words:[["Ona fetalai mai lea o Ieova", "and said the LORD"], ["ia te au,", "unto me"], ["Amosa e,", "Amos by"], ["se a ea", "a but to rise (as a diver to the sur-"], ["se mea", "a thing"], ["ua e iloa?", "to known"], ["I le", "in the"], ["ua ou faapea atu,", "I thus"], ["O le fua faatautau.", "the fruit faatautau"], ["Ona fetalai mai ai lea", "and said"], ["o le Alii,", "the Lord"], ["Faauta,", "behold"], ["ou te tuu", "I put"], ["se fua faatautau", "a fruit faatautau"], ["i totonu", "in inside"], ["o lo'u nuu o Isaraelu,", "my nation of Israel"], ["ou te", "I"], ["le toe sopoia lava.", "the again crossed over indeed"]]},
  {num:9,words:[["E faatafunaina mea maualuluga", "to destroyed thing most high"], ["a Isaako,", "of Isaac"], ["e faatafunaina foi malumalu o Isaraelu;", "to destroyed also temple of Israel"], ["ou te tulai atu", "I arose up"], ["ma le pelu", "and the a sword"], ["i le aiga o Ierepoamo.", "in the family of Jeroboam"]]},
  {num:10,words:[["Ona alu lea", "And he went"], ["o le feau", "the errand"], ["a Amasia", "of Amasia"], ["le ositaulaga", "the high priest"], ["a Peteli ia Ierepoamo", "of Bethel to Jeroboam"], ["le tupu o Isaraelu,", "the king of Israel"], ["ua faapea atu,", "and said"], ["Ua fouvale Amosa ia te oe", "to rebel Amos unto you"], ["i le aiga o Isaraelu,", "in the family of Israel"], ["ua le lavā onosai", "the lavā patience"], ["le nuu", "the nation"], ["i ana upu uma.", "in his word all"]]},
  {num:11,words:[["Auā ua faapea", "for saying"], ["mai Amosa,", "from Amos"], ["E maliu Ierepoamo", "to die Jeroboam"], ["i le pelu,", "by the sword"], ["e matuā ta'ita'iina Isaraelu faatagata", "to exceedingly led Israel faatagata"], ["o taua ai lo latou", "precious their"], ["lava laueleele.", "indeed ground"]]},
  {num:12,words:[["Ua faapea mai foi Amasia", "and said also Amasia"], ["ia Amosa,", "to Amos"], ["Le tagata vaai", "the man look"], ["e,", "by"], ["alu ia,", "go to"], ["ina sola oe", "let escape you"], ["i le nuu o Iuta,", "in the land Judas"], ["ma e 'ai", "and to eat"], ["i lea mea,", "in thing"], ["ma vavalo ai.", "and prophesy"]]},
  {num:13,words:[["A e aua", "but to for"], ["e te toe vavalo", "by again prophesy"], ["i Peteli;", "in Bethel"], ["auā o le malumalu lea", "for the temple"], ["o le tupu,", "the king"], ["o le maota foi", "the the name of a tree also"], ["o le tupu.", "the king"]]},
  {num:14,words:[["Ona tali atu lea o Amosa", "and respond of Amos"], ["ua faapea atu ia", "and said to"], ["Amasia,", "Amasia"], ["Ou te", "I"], ["le se perofeta a'u", "the a prophet I"], ["nei,", "this"], ["ou te", "I"], ["le se atalii foi", "the a son also"], ["o se perofeta;", "a prophet"], ["a o le fagamanu a'u,", "but the fagamanu I"], ["ma le galue", "and the till"], ["i sukamoru.", "in sukamoru"]]},
  {num:15,words:[["A ua avea a'u", "but become I"], ["e Ieova", "the LORD"], ["sa ou mulimuli", "I follow after"], ["i le lafu mamoe,", "in the herd sheep"], ["ma ua faapea", "and saying"], ["mai Ieova ia te au,", "from the LORD unto me"], ["Alu ia,", "go to"], ["ina e vavalo", "let to prophesy"], ["i lo'u nuu o Isaraelu.", "in my nation of Israel"]]},
  {num:16,words:[["O lenei,", "this"], ["ina e faalogo", "let to hearken"], ["mai ia", "from to"], ["i le afioga", "the word"], ["a Ieova.", "of the LORD"], ["Ua e fai mai,", "to said"], ["aua le vavalo ia", "do not prophesy to"], ["Isaraelu,", "Israel"], ["aua foi", "for also"], ["le tautala atu", "the to talk"], ["i le aiga o Isaako.", "in the family of Isaac"]]},
  {num:17,words:[["O le mea lea o loo faapea", "therefore saying"], ["mai ai Ieova,", "from the LORD"], ["E avea lau avā", "to become your wife"], ["ma fafine faitaaga", "and woman fornication"], ["i le aai,", "in the city"], ["e pauu foi", "to fell also"], ["i le pelu o ou atalii", "by the sword I son"], ["ma ou afafine,", "and I daughter"], ["e vaevaeina", "by vaevaeina"], ["i le fua lou fanua;", "in the fruit your land"], ["e oti foi oe", "to die also you"], ["i le nuu leaga;", "in the land evil"], ["e matuā tāfea Isaraelu ai lona laueleele.", "to exceedingly tāfea Israel his ground"]]},
];
renderVerseSet(_amo_ch_7_Verses, 'amo-ch7-verses');

var _amo_ch_8_Verses = [
  {num:1,words:[["Ua faapea ona", "saying and"], ["faaalia mai ia te au", "revealed from I"], ["e le Alii o Ieova;", "by the Lord the LORD"], ["faauta mai,", "behold from"], ["o le ato fua otatā.", "the to thatch fruit otatā"]]},
  {num:2,words:[["Ona faapea mai lea o ia,", "and thus from he"], ["Amosa e,", "Amos by"], ["pe se", "whether a"], ["a ea", "but to rise (as a diver to the sur-"], ["se mea", "a thing"], ["ua e iloa?", "to known"], ["I le", "in the"], ["ua ou tali atu,", "I respond"], ["O le ato fua otatā.", "the to thatch fruit otatā"], ["Ona faapea mai ai lea", "and thus from"], ["o Ieova ia te au,", "the LORD unto me"], ["Ua oo mai", "it came to pass from"], ["le iuga", "the end"], ["i lo'u nuu o Isaraelu,", "in my nation of Israel"], ["ou te", "I"], ["le toe sopoia lava.", "the again crossed over indeed"]]},
  {num:3,words:[["E fai", "to make"], ["ma uio pese", "and uio a song"], ["o le maota", "the the name of a tree"], ["i lea aso,", "in day"], ["o loo fetalai", "said"], ["mai ai", "from"], ["le Alii o Ieova;", "the Lord the LORD"], ["e i ai", "by therein"], ["i mea uma tino o tagata oti", "in all things body of men die"], ["e tele,", "to great"], ["e lafoaiina", "to forsaken"], ["ma le", "and the"], ["le feganavai.", "the feganavai"]]},
  {num:4,words:[["Ia outou faalogologo", "to you (all) listen"], ["i lenei mea,", "in this thing"], ["o outou", "you (all)"], ["o e faasaua", "who to be oppressive"], ["i e matitiva,", "in to poor"], ["ina ia faaumatia lava", "so that destroyed indeed"], ["le au matitiva", "the I poor"], ["o le nuu,", "the nation"]]},
  {num:5,words:[["o loo faapea", "saying"], ["mai,", "from"], ["Pe mavae atu afea", "whether passed when ?"], ["le masina faatoa vaaia ia", "the moon just now seen to"], ["tatou faatau ai saito?", "we (incl) equally wheat"], ["pe mavae afea foi", "whether passed when ? also"], ["le sapati ia tatou", "the Sabbath to we (incl)"], ["tatalaina atu ai saito? o loo faaitiitiina", "opened wheat of faaitiitiina"], ["foi le efa,", "also the ephah"], ["ma faateleina", "and multiplied"], ["le sekeli,", "the shekel"], ["o loo fai fua faaletatau", "make fruit faaletatau"], ["e pepelo ai.", "to false"]]},
  {num:6,words:[["Tatou te faatau foi tagata matitiva", "we (incl) equally also man poor"], ["i ario,", "in silver"], ["ma le tagata vaivai", "and the man weak"], ["i seevae", "in a shoe"], ["e lua;", "by two"], ["tatou te faatau atu foi saito leaga.", "we (incl) equally also wheat evil"]]},
  {num:7,words:[["Ua tauto Ieova", "to take an oath the LORD"], ["i le mamalu o Iakopo,", "in the glory of James"], ["E le galo lava ia te au", "by the forgotten indeed unto me"], ["e faavavau", "forever/everlasting"], ["a latou galuega uma.", "but they work all"]]},
  {num:8,words:[["E le gatete ea", "by the tremble to rise (as a diver to the sur-"], ["le laueleele", "the ground"], ["ona o lenei mea,", "because of this thing"], ["ma faanoanoa ai", "and to mourn"], ["i latou uma o", "them all of"], ["e nonofo ai?", "to dwell"], ["e le matuā alu", "by the exceedingly go"], ["ae ea", "but to rise (as a diver to the sur-"], ["e pei o se vaitafe?", "to like a river"], ["e le lafoaiina ea ia", "by the forsaken to rise (as a diver to the sur- to"], ["ma lofia,", "and lofia"], ["e pei o le vaitafe", "like the river"], ["o Aikupito?", "Egypt"]]},
  {num:9,words:[["O loo fetalai", "said"], ["mai le Alii o Ieova,", "from the Lord the LORD"], ["O lea aso ou te faagotoina ai", "therefore day I faagotoina"], ["le la", "the la"], ["i le aoauli,", "in the aoauli"], ["ou te faapouliuligia foi", "I faapouliuligia also"], ["le lalolagi", "the earth"], ["i le ao malamalama.", "in the cloud light"]]},
  {num:10,words:[["Ou te liu", "I liu"], ["i faanoanoaga", "in grief"], ["a outou tausamiga,", "but you (all) feast"], ["ou te liliu foi o outou", "I turned also of you (all)"], ["pese uma", "a song all"], ["i auega;", "in auega"], ["ou te faalavalava foi sulugatiti uma", "I a weal also the place where the all"], ["i le ie talatala,", "in the faamaise to untie"], ["o ulu foi o tagata uma", "head also of men all"], ["e selemamaina ia;", "by selemamaina to"], ["ou te faia lea mea", "I will make thing"], ["ia pei o le pese", "to like the a song"], ["e aualofa a'i", "to a keepsake"], ["ona o le atalii", "because of the son"], ["e toatasi,", "to one One"], ["o lona iuga foi,", "his end also"], ["o le aso vale lava lea.", "the day foolish indeed"]]},
  {num:11,words:[["O loo faapea", "saying"], ["mai le Alii o Ieova,", "from the Lord the LORD"], ["Faauta,", "behold"], ["e oo mai aso ou te tuuina atu ai", "it shall come to pass from day I will give"], ["le oge", "the a famine"], ["i le nuu;", "in the land"], ["e le", "by the"], ["se oge", "a a famine"], ["i mea", "in thing"], ["e 'ai,", "to eat"], ["po o se gālala", "night a gālala"], ["i le fia inu vai,", "in the want to do something drink water"], ["a o le oge", "but the a famine"], ["i le faalogologo", "in the listen"], ["i afioga", "in a word"], ["a Ieova.", "of the LORD"]]},
  {num:12,words:[["Latou te feoai", "they feoai"], ["e pau mai", "to fall from"], ["i le tasi vasa", "in the one ocean"], ["e oo atu", "it shall come to pass"], ["i le isi vasa,", "in the other ocean"], ["e pau mai", "to fall from"], ["i le itu", "on the side"], ["i matu", "northward"], ["e oo atu", "it shall come to pass"], ["i le itu", "on the side"], ["i sasae latou te feoai ai", "eastward they feoai"], ["e sailiili atu ai", "to search"], ["le afioga", "the a word"], ["a Ieova,", "of the LORD"], ["a e le maua.", "but by the received"]]},
  {num:13,words:[["E vaivai", "to weak"], ["i le fia inu", "in the want to do something drink"], ["i lea aso o taupou lalelei", "in day of virgin beautiful"], ["atoa ma taulelea.", "and young men"]]},
  {num:14,words:[["O i latou", "them"], ["o e tauto", "who to take an oath"], ["i le agasala", "in the sin"], ["a Samaria,", "of Samaria"], ["ma faapea atu,", "and thus"], ["Tanu e,", "to bury by"], ["ua soifua lou atua;", "live your God"], ["i le", "in the"], ["ma lea,", "and"], ["Ua ola", "life"], ["le ala o Peresepa;", "the way Peresepa"], ["e pauu lava", "to fell indeed"], ["i latou,", "them"], ["latou te", "they"], ["le toe tutulai.", "the again tutulai"]]},
];
renderVerseSet(_amo_ch_8_Verses, 'amo-ch8-verses');

var _amo_ch_9_Verses = [
  {num:1,words:[["Na ou iloa", "I known"], ["le Alii,", "the Lord"], ["o loo tu", "stand"], ["i luga", "in above"], ["o le fata faitaulaga;", "the altar"], ["ma ua faapea", "and saying"], ["mai o ia,", "from he"], ["Ina ta ia le laau faalava", "let a stroke to the tree crossbar"], ["o le faitotoa,", "the door"], ["ia luluina ai o pou;", "to shaken of pillar"], ["ia gaugau ai", "to gaugau"], ["i luga o latou", "upon they"], ["ulu uma;", "head all"], ["ou te fasioti foi", "I killed also"], ["i le pelu", "by the sword"], ["e ua totoe o", "by phiral of foe of"], ["i latou;", "them"], ["ai so latou", "so they"], ["e sola", "to escape"], ["e le sao ia,", "by the the appointed portion of to"], ["ai so latou", "so they"], ["e sola ese", "to escape away"], ["e le laveaiina o ia.", "by the delivered he"]]},
  {num:2,words:[["Afai latou te eli ia", "if they Eli to"], ["oo i seoli,", "oo in Sheol"], ["e aumaia", "to bring here"], ["i latou", "them"], ["e lo'u lima ai lea mea;", "to my five thing"], ["afai latou te feaei", "if they feaei"], ["i le lagi,", "in heaven"], ["ou te aveina ifo", "I taken away down"], ["i latou ai lea mea.", "them thing"]]},
  {num:3,words:[["Afai latou te lalafi", "if they lalafi"], ["i le tumutumu o Karamelu,", "in the top of Carmel"], ["ou te suesue ai,", "I examine"], ["ma au mai ai", "and bring"], ["i latou ai lea mea;", "them thing"], ["afai foi", "if also"], ["e lalafi", "by lalafi"], ["i latou ai o'u luma", "them my before"], ["i le loloto", "in the deep"], ["o le sami,", "Sea"], ["ou te fai atu ai", "I said to"], ["i le gata,", "in the a snake"], ["ona utia ai lea o", "and utia of"], ["i latou e ia.", "them by him"]]},
  {num:4,words:[["Afai foi", "if also"], ["e tāfea", "by tāfea"], ["i latou", "them"], ["i luma o", "before"], ["e o fai", "by of make"], ["i latou", "them"], ["ma fili,", "and to choose"], ["ou te fai atu ai", "I said to"], ["i le pelu,", "by the sword"], ["ona fasiotia ai lea o", "and slain of"], ["i latou;", "them"], ["ou te faasaga atu", "I toward"], ["i ai,", "therein"], ["ina ia malaia o", "so that disaster of"], ["i latou,", "them"], ["a e le", "but by the"], ["ona ia manuia.", "and to peace"]]},
  {num:5,words:[["O le Alii,", "the Lord"], ["o Ieova o 'au o ia", "the LORD I he"], ["o le pai atu", "the pie"], ["i le laueleele,", "in the earth"], ["ona liu suāvai ai lea,", "and liu suāvai"], ["e faanoanoa foi", "to to mourn also"], ["i latou uma o", "them all of"], ["e nonofo ai;", "to dwell"], ["e matuā alu", "to exceedingly go"], ["ae e pei o se vaitafe,", "but to like a river"], ["e lofia o ia", "by lofia he"], ["e pei o le vaitafe", "like the river"], ["o Aikupito.", "Egypt"]]},
  {num:6,words:[["O ia lava", "he indeed"], ["o le", "the"], ["na te faia", "he made"], ["ona afioaga", "and afioaga"], ["i le lagi,", "in heaven"], ["ma na faavaeina lana faaputugāmea", "and faavaeina his faaputugāmea"], ["i le lalolagi;", "on the earth"], ["o le", "the"], ["na te valaauina", "he called"], ["i le suāsami", "in the suāsami"], ["o le sami,", "Sea"], ["ma faamaligi ai", "and faamaligi"], ["i le fogāeleele;", "the face of the earth"], ["o Ieova,", "the LORD"], ["o lona suafa lea.", "his name"]]},
  {num:7,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["Le fanauga", "the children"], ["a Isaraelu", "of Israel"], ["e,", "by"], ["e le", "by the"], ["ua pei o tagata Aitiope ea outou", "like of men Aitiope to rise (as a diver to the sur- you (all)"], ["ia te au?", "unto me"], ["Pe na", "whether"], ["le aveina", "the taken away"], ["ae Isaraelu", "but Israel"], ["e a'u ai", "to I"], ["le nuu o Aikupito? o Filisitia", "the nation of Egypt of Philistine"], ["foi ai Kafetori,", "also Kafetori"], ["ma Suria ai Kira?", "and Syria Kira"]]},
  {num:8,words:[["Faauta,", "behold"], ["ua faasaga fofoga", "toward face"], ["o le Alii o Ieova", "the Lord the LORD"], ["i le malo amio leaga,", "in the government iniquity"], ["ou te faaumatia ai ai", "I destroyed"], ["le fogāeleele;", "the face of the earth"], ["na o le aiga o Iakopo ou te", "the family of James I"], ["le matuā faaumatia,", "the exceedingly destroyed"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
  {num:9,words:[["Faauta mai foi,", "behold from also"], ["ou te fai atu,", "I said to"], ["ou te luluina foi", "I shaken also"], ["le aiga o Isaraelu", "the family of Israel"], ["i nuu uma,", "in nation all"], ["e pei ona", "as"], ["luluina o saito", "shaken of wheat"], ["i le lulu,", "in the barn owl"], ["a e le paū sina fua", "but by the paū white fruit"], ["i le eleele.", "the ground"]]},
  {num:10,words:[["E oti", "to die"], ["i le pelu o", "by the sword"], ["i latou uma", "them all"], ["o lo'u nuu o", "my nation of"], ["e agasala,", "to sin"], ["o e faapea ane,", "who thus"], ["E le aulia", "by the aulia"], ["mai le malaia,", "from the disaster"], ["pe maua mai", "whether received from"], ["i tatou.", "in we (incl)"]]},
  {num:11,words:[["O le aso lea ou te faatuina ai", "the day I built"], ["le fale apitaga o Tavita", "the house a tempoiary of David"], ["ua paū;", "paū"], ["ou te pupuni", "I shut"], ["i ana mea", "in his thing"], ["ua lepetia;", "overthrown"], ["o ana mea foi", "his thing also"], ["ua solo ou te atiina", "to move swiftly I atiina"], ["ae,", "but"], ["ou te atiina", "I atiina"], ["ae e pei ona", "but as"], ["faia i", "made in"], ["ona po anamua.", "and night ancient"]]},
  {num:12,words:[["Ina ia fai", "so that make"], ["mo latou tofi", "for they appoint"], ["e ua totoe o Etoma,", "by phiral of foe of Edom"], ["atoa ma nuu uma,", "and nation all"], ["o e", "who"], ["ua faaigoaina", "named"], ["i lo'u igoa,", "in my name"], ["o loo fetalai", "said"], ["mai ai Ieova", "from the LORD"], ["o le", "the"], ["na te faia lenei mea.", "he made this thing"]]},
  {num:13,words:[["O loo faapea", "saying"], ["mai Ieova,", "from the LORD"], ["Faauta,", "behold"], ["e oo mai", "it shall come to pass from"], ["ona aso", "and day"], ["e aulia ai lē suatia", "by aulia not suatia"], ["le fanua", "the land"], ["i le selesele saito,", "in the an evenly cut head of wheat"], ["ma lē solivine", "and not solivine"], ["i le lulu saito;", "in the barn owl wheat"], ["e tautulu mauga", "by tautulu mountain"], ["i le suāvine,", "in the suāvine"], ["e tafea ai mea maupuepue uma.", "to exiled captive thing maupuepue all"]]},
  {num:14,words:[["Ou te faafoisia", "I restored"], ["mai le tafeaga", "from the exiles in wa^"], ["o lo'u nuu o Isaraelu,", "my nation of Israel"], ["ona latou faatuina ai lea", "and they built"], ["o aai", "city"], ["ua faatafunaina,", "destroyed"], ["ma nonofo ai;", "and dwelling"], ["latou te totōina foi tovine,", "they totōina also vineyard"], ["ma inu uaina ai;", "and drink wine"], ["latou te fai foi faatoaga,", "they make also garden"], ["ma aai ai", "and city"], ["ona fua.", "its fruit"]]},
  {num:15,words:[["Ou te totōina", "I totōina"], ["i latou", "them"], ["i lo latou laueleele;", "in the they ground"], ["e le toe liaiina", "by the again liaiina"], ["i latou ai lo latou laueleele", "them their ground"], ["na ou foaiina atu ai", "I given"], ["ia te", "unto"], ["i latou,", "them"], ["o loo fetalai", "said"], ["mai ai Ieova lou Atua.", "from the LORD your God"]]},
];
renderVerseSet(_amo_ch_9_Verses, 'amo-ch9-verses');

})();