(function() {
var _amo_ch_1_Verses = [
  {num:1,words:[["O 'upu", "word"], ["a Amosa", "of Amos"], ["o le", "the"], ["na", "na"], ["i ai", "therein"], ["i le au", "in the me"], ["fagamanu", "fagamanu"], ["i Tikoa,", "in Tikoa"], ["na ia iloa ai", "to knew"], ["ia Isaraelu,", "to Israel"], ["i ona po", "in his nights"], ["o Usia", "Usia"], ["le tupu o Iuta,", "the king of Judas"], ["o", "o"], ["ona po foi", "and night also"], ["o Ierepoamo", "Jeroboam"], ["le atali'i o Ioasa,", "the son of Joash"], ["le tupu o Isaraelu;", "the king of Israel"], ["e lua tausaga", "by two year"], ["na va a'i", "divided"], ["lea mea", "thing"], ["i le oo mai le mafuie.", "in the came the mafuie"]]},
  {num:2,words:[["Ua ia fa'apea mai,", "to thus from"], ["E leo tele", "to voice great"], ["mai Ieova mai Siona,", "from the LORD from Zion"], ["e tŭlei ifo foi", "by tŭlei down also"], ["lona siufofoga mai Ierusalema;", "his voice from Jerusalem"], ["e fa'anoanoa foi", "to mourn also"], ["mea", "thing"], ["e tataa ai", "to"], ["manu", "animal"], ["a", "but"], ["e fagamanu,", "by fagamanu"], ["e mago foi", "to a small eel also"], ["le tumutumu o Karamelu.", "the top of Carmel"]]},
  {num:3,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["E tolu agasala", "by three sin"], ["a Tamaseko,", "of Damascus"], ["e fa foi,", "by four also"], ["ou te", "I will"], ["le liliu ese ai", "the turn away"], ["lana sala;", "his a fine"], ["auā", "for"], ["na lātou solia ia", "they despised to"], ["Kiliata", "Gilead"], ["i uamea", "in iron"], ["e soli ai", "to to tread upon"], ["saito.", "wheat"]]},
  {num:4,words:[["A", "but"], ["e ou te tuuina atu", "to I will give"], ["le afi", "the fire"], ["i le fale", "in the house"], ["o Asaeli,", "Asaeli"], ["e fa'aumatia ai", "to destroyed"], ["foi maota o Peniata.", "also the name of a tree of Peniata"]]},
  {num:5,words:[["Ou te gauia foi", "I will was to break also"], ["le fa'amaufaalava o Tamaseko,", "the faamaufaalava of Damascus"], ["ou te fa'aumatia", "I will destroyed"], ["le", "the"], ["ua mau", "opinion"], ["i le vanu", "in the valley"], ["o Avene,", "Avene"], ["atoa ma le", "and the"], ["ua 'u'u", "oil"], ["le tootoo", "the staff"], ["i Pete-etena;", "in Pete-etena"], ["e tāfea foi", "to exiled captive also"], ["le nuu o Suria", "the nation of Syria"], ["i Kira,", "in Kira"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:6,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["E tolu agasala", "by three sin"], ["a Kasa,", "of Kasa"], ["e fa foi,", "by four also"], ["ou te", "I will"], ["le liliu ese ai", "the turn away"], ["lana sala;", "his a fine"], ["auā", "for"], ["na lātou fa'atāfeaina", "they made exiled captive"], ["le tafeaga atoatoa", "the exiles in wa^ completely"], ["ia tuuina atu ai", "to given / delivered"], ["i Etoma.", "in Edom"]]},
  {num:7,words:[["A", "but"], ["e ou te tuuina atu", "to I will give"], ["le afi", "the fire"], ["i le pa", "in the wall"], ["o Kasa,", "Kasa"], ["e fa'aumatia ai", "to destroyed"], ["ona maota.", "and the name of a tree"]]},
  {num:8,words:[["Ou te fa'aumatia foi", "I will destroyed also"], ["le", "the"], ["ua mau", "opinion"], ["i Asetota,", "in Asetota"], ["ma le", "and the"], ["ua 'u'u", "oil"], ["le tootoo", "the staff"], ["i Asekelona;", "in Asekelona"], ["ou te liliu atu", "I will turn"], ["lo'u lima", "my hand"], ["i Ekerona,", "in Ekron"], ["e fano", "to perish"], ["e ua totoe", "by phiral of foe"], ["o Filisitia,", "Philistine"], ["o loo o fetalai mai ai", "is said"], ["le Ali'i o Ieova.", "the Lord the LORD"]]},
  {num:9,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["E tolu agasala", "by three sin"], ["a Turo,", "of Tyre"], ["e fa foi,", "by four also"], ["ou te", "I will"], ["le liliu ese ai", "the turn away"], ["lana sala;", "his a fine"], ["auā", "for"], ["na lātou tuuina atu", "they given / delivered"], ["le tafeaga atoatoa", "the exiles in wa^ completely"], ["i Etoma,", "in Edom"], ["mona", "to burst forth (as faiai"], ["ua", "ua"], ["le manatua", "the remember"], ["le feagaiga", "the covenant"], ["a uso.", "but brother"]]},
  {num:10,words:[["A", "but"], ["e ou te tuuina atu", "to I will give"], ["le afi", "the fire"], ["i le pa", "in the wall"], ["o Turo,", "Tyre"], ["e fa'aumatia ai", "to destroyed"], ["ona maota.", "and the name of a tree"]]},
  {num:11,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["E tolu agasala", "by three sin"], ["a Etoma,", "of Edom"], ["e fa foi,", "by four also"], ["ou te", "I will"], ["le liliu ese ai", "the turn away"], ["lana sala;", "his a fine"], ["auā", "for"], ["na ia tuliloa", "to pursued"], ["i le pelu", "by the sword"], ["lona uso,", "his brother"], ["na ia le alofa lava,", "to the loved very"], ["na saei pea lava", "to tear continually very"], ["lona ita;", "his angry"], ["na ia tausi", "to nurse"], ["pea lava", "continually very"], ["lona ita tele.", "his angry great"]]},
  {num:12,words:[["A", "but"], ["e ou te tuuina atu", "to I will give"], ["le afi", "the fire"], ["i Timanu,", "in Timanu"], ["e fa'aumatia ai", "to destroyed"], ["maota o Posara.", "the name of a tree of Posara"]]},
  {num:13,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["E tolu agasala", "by three sin"], ["a le fanauga", "but the children"], ["a Amoni,", "of Ammon"], ["e fa foi,", "by four also"], ["ou te", "I will"], ["le liliu ese ai", "the turn away"], ["lana sala;", "his a fine"], ["auā", "for"], ["na lātou fa'atiau", "they to disembowel"], ["i fafine totō", "in women blood"], ["i Kiliata,", "in Gilead"], ["ina ia fa'ateleina", "so that multiplied"], ["e", "by"], ["i lātou lo lātou laueleele.", "them their ground"]]},
  {num:14,words:[["A", "but"], ["e ou te tŭtŭ", "to I will tŭtŭ"], ["se afi", "a fire"], ["i le pa", "in the wall"], ["o Rapa,", "Rapa"], ["e fa'aumatia ai", "to destroyed"], ["ma le alaga", "and the cry"], ["ona maota,", "and the name of a tree"], ["i le aso", "in the day"], ["e tau ai", "to fight"], ["le taua,", "the battle"], ["ma le afā", "and the cyclone"], ["i le aso", "in the day"], ["e", "by"], ["i ai", "therein"], ["le asiosio.", "the asiosio"]]},
  {num:15,words:[["E alu", "to go"], ["i le tafeaga Malekama,", "in the exiles in wa^ Malekama"], ["o ia", "he"], ["atoa ma ali'i", "and Lord"], ["ua ia te ia", "to him"], ["fa'atasi ma ia,", "with him"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
];
renderVerseSet(_amo_ch_1_Verses, 'amo-ch1-verses');

var _amo_ch_2_Verses = [
  {num:1,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["E tolu agasala", "by three sin"], ["a Moapi,", "of Moab"], ["e fa foi,", "by four also"], ["ou te", "I will"], ["le liliu ese ai", "the turn away"], ["lana sala;", "his a fine"], ["auā", "for"], ["na ia susunuina", "to burned"], ["ivi", "bone"], ["o le tupu", "the king"], ["o Etoma", "Edom"], ["na liu panisina.", "liu lime"]]},
  {num:2,words:[["A", "but"], ["e ou te tuuina atu", "to I will give"], ["le afi", "the fire"], ["i Moapi,", "in Moab"], ["e fa'aumatia ai", "to destroyed"], ["maota o Kiriota;", "the name of a tree of Kiriota"], ["e oti Moapi", "to die Moab"], ["i le vāvāō,", "in the vegetation"], ["ma le alaga,", "and the cry"], ["ma le leo", "and the voice"], ["o le pu.", "the the tail"]]},
  {num:3,words:[["Ou te fa'aumatia", "I will destroyed"], ["le fa'amasino o", "the judge of"], ["i lea", "in"], ["mea,", "thing"], ["ou te fasiotia fa'atasi ma ia", "I will slain with him"], ["o ali'i uma,", "Lord all"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:4,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["E tolu agasala", "by three sin"], ["a Iuta,", "of Judas"], ["e fa foi,", "by four also"], ["ou te", "I will"], ["le liliu ese ai", "the turn away"], ["lana sala;", "his a fine"], ["auā", "for"], ["na lātou lafoai", "they forsaken"], ["le tulafono", "the law"], ["a Ieova,", "of the LORD"], ["e lei tausi foi", "by not nurse also"], ["e", "by"], ["i lātou ana poloaiga;", "them his commandment"], ["ua fa'aseseina", "deceived astray"], ["i lātou", "them"], ["i", "in"], ["a lātou mea pepelo,", "their thing false"], ["sa naunau atu", "desired"], ["i ai", "therein"], ["o lātou tamā.", "they child"]]},
  {num:5,words:[["A", "but"], ["e ou te tuuina atu", "to I will give"], ["le afi", "the fire"], ["i Iuta,", "in Judas"], ["e fa'aumatia ai", "to destroyed"], ["maota o Ierusalema.", "the name of a tree of Jerusalem"]]},
  {num:6,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["E tolu agasala", "by three sin"], ["a Isaraelu,", "of Israel"], ["e fa foi,", "by four also"], ["ou te", "I will"], ["le liliu ese ai", "the turn away"], ["lana sala;", "his a fine"], ["auā", "for"], ["na lātou fa'atauina atu", "they bought"], ["le", "the"], ["ua amiotonu", "righteous"], ["i ario,", "in silver"], ["ma le", "and the"], ["ua mativa", "wanted"], ["i seevae", "in a shoe"], ["e lua.", "by two"]]},
  {num:7,words:[["O", "O"], ["e naunau atu", "to desire"], ["i le efuefu", "in the dust"], ["o le laueleele", "the ground"], ["i ulu o", "in head of"], ["e matitiva,", "to poor"], ["ma lātou liliu ese", "and they turn away"], ["le ala o", "the way"], ["e agamalu;", "to meek"], ["e alu ane foi", "to go forth also"], ["le tagata", "the man"], ["atoa ma lona tamā", "and his child"], ["i le teine", "in the girl"], ["e toatasi,", "to one One"], ["ina ia ta'uvaleina ai", "so that to come inopportunely"], ["lo'u igoa paia.", "my name holy"]]},
  {num:8,words:[["Ua lātou taooto foi", "they lay down also"], ["i ofu", "in garment"], ["ua tuu fa'afaatau", "put made buy"], ["i tafatafa o fata faitaulaga uma;", "in to cut in many places of altar all"], ["ma", "and"], ["ua lātou inu", "they drank"], ["uaina", "wine"], ["a", "but"], ["e ua fa'asalaina", "by punished"], ["i le fale", "in the house"], ["o lātou atua.", "they God"]]},
  {num:9,words:[["A", "but"], ["o a'u,", "I am"], ["na ou fa'aumatia", "I destroyed"], ["le", "the"], ["sa Amorī ai", "of the clan of Amorites"], ["o lātou luma,", "they before"], ["o lona maualuga", "his Iiigli"], ["e pei o le maualuga", "like the Iiigli"], ["o arasi ia,", "cedar to"], ["sa malosi foi", "strong also"], ["o ia", "he"], ["e pei o aluna;", "like aluna"], ["na ou fa'aumatia foi", "I destroyed also"], ["lona fua", "his fruit"], ["i luga", "in above"], ["ma", "and"], ["ona aa", "and aa"], ["i lalo.", "in under"]]},
  {num:10,words:[["Na ou aveina", "I taken away"], ["ae foi", "but also"], ["outou ai", "you all"], ["le nuu o Aikupito;", "the nation of Egypt"], ["na ou ta'ita'iina", "I led"], ["outou", "you all"], ["i tausaga", "in year"], ["e fagafulu", "to forty"], ["i le vao", "in the wilderness"], ["e maua ai", "to received"], ["le laueleele", "the ground"], ["o le", "the"], ["sa Amorī.", "of the clan of Amorites"]]},
  {num:11,words:[["Na ou fa'atuina", "I built"], ["ni o outou", "some of you all"], ["atali'i", "son"], ["e fai ma perofeta,", "to be prophet"], ["ma ni o outou", "and some of you all"], ["taulelea", "young men"], ["e fai ma naseri.", "to be naseri"], ["Le fanauga", "the children"], ["a Isaraelu e,", "of Israel by"], ["e le", "by the"], ["ua fa'apea lava", "and it was so"], ["ea? o loo fetalai mai ai", "indeed?/really? is said"], ["Ieova.", "the LORD"]]},
  {num:12,words:[["A", "but"], ["ua outou avatua", "you all given away"], ["uaina", "wine"], ["i le au", "in the me"], ["naseri", "naseri"], ["e inu ai,", "to drink"], ["ma vavao atu", "and to forbid"], ["i le au", "in the me"], ["perofeta,", "prophet"], ["o loo fa'apea atu,", "saying"], ["Aua", "for"], ["le vavalo mai.", "the prophesy from"]]},
  {num:13,words:[["Fa'auta,", "behold"], ["ou te taomia outou", "I will taomia you all"], ["i lalo,", "in under"], ["e pei ona", "as"], ["taomia", "taomia"], ["o le eleele", "Earth"], ["i le fata fa'ataavalevale", "in the altar to roll round and"], ["ua tumu", "filled"], ["i fusi saito.", "in belt wheat"]]},
  {num:14,words:[["E iu vale", "to become of foolish"], ["le solaaga", "the was escape"], ["o le tele vave,", "the great quick"], ["e le fa'ateleina", "shall not multiplied"], ["e le", "by the"], ["ua malosi", "strong"], ["lona malosi;", "his strong"], ["o le toa foi", "the champion also"], ["na te", "he"], ["le fa'asaoina", "the spared"], ["lona lava ola.", "his very life"]]},
  {num:15,words:[["O le", "the"], ["ua fai aufana", "made bow"], ["e le tumau", "shall not enduring"], ["ia;", "to"], ["ma le", "and the"], ["ua momo'e tele", "ran great"], ["vave", "quick"], ["e le sao ai", "shall not the appointed portion of"], ["o ia;", "he"], ["o lē tietie", "the ride"], ["i le solofanua", "in the horse"], ["e le fa'asaoina ai", "shall not spared"], ["foi e ia", "also by him"], ["lona ola.", "his life"]]},
  {num:16,words:[["O le toa", "the champion"], ["ua sili", "most"], ["lona loto tele,", "his heart great"], ["e sola lē lavalavā", "to escape the naked"], ["o ia", "he"], ["i lea aso,", "on that day"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
];
renderVerseSet(_amo_ch_2_Verses, 'amo-ch2-verses');

var _amo_ch_3_Verses = [
  {num:1,words:[["Le fanauga", "the children"], ["a Isaraelu e,", "of Israel by"], ["ia outou fa'alogologo", "to you all listen"], ["mai", "from"], ["i lenei", "in this"], ["'upu,", "word"], ["o loo fetalai mai ai", "is said"], ["Ieova ia te outou,", "the LORD unto you all"], ["atoa ma le 'āiga uma", "and all the family"], ["na ou aveina", "I taken away"], ["ae ai", "but"], ["le nuu o Aikupito;", "the nation of Egypt"], ["o loo fa'apea mai,", "saying from"]]},
  {num:2,words:[["Ua", "Ua"], ["na o outou", "of you all"], ["lava", "very"], ["ua ou iloa", "I knew"], ["i 'āiga uma", "in family all"], ["o le lalolagi;", "the earth"], ["o le mea lea", "therefore"], ["ou te fa'asalaina ai", "I will punished"], ["outou", "you all"], ["ona o", "because of"], ["a outou agasala uma.", "your sin all"]]},
  {num:3,words:[["E feoai fa'atasi ea", "to walk about together indeed?/really?"], ["se toalua,", "a two"], ["pe a le loto gatasi", "even though / although the heart gatasi"], ["i laua?", "them both"]]},
  {num:4,words:[["E tagi ea", "to cry indeed?/really?"], ["le leona", "the lion"], ["i le vao,", "in the wilderness"], ["pe a leai se mea", "even though / although no a thing"], ["ua", "ua"], ["na saeia?", "spared"], ["E lagona atu ea", "to to understand indeed?/really?"], ["le leo", "the voice"], ["o le tamai leona ai", "the son lion"], ["lona lua,", "his two"], ["pe afai", "whether if"], ["ua", "ua"], ["na", "na"], ["le maua", "the received"], ["se mea?", "a thing"]]},
  {num:5,words:[["E lavea ea", "to struck indeed?/really?"], ["le manu lele", "the animal fly"], ["i le mailei", "in the a trap"], ["i le laueleele,", "in the earth"], ["a", "but"], ["ua leai se", "there was no"], ["mailei", "a trap"], ["mo ia?", "for to"], ["E avae ea", "to take away indeed?/really?"], ["le mailei ai", "the a trap"], ["le laueleele,", "the ground"], ["a", "but"], ["ua", "ua"], ["le maua", "the received"], ["se mea?", "a thing"]]},
  {num:6,words:[["E ilia ea", "by ilia indeed?/really?"], ["le pu", "the the tail"], ["i le aai,", "in the cities"], ["a", "but"], ["e le atuatuvale ai", "shall not to be greatly dis-"], ["tagata?", "man"], ["E tupu ea", "to king indeed?/really?"], ["se malaia", "a disaster"], ["i le aai,", "in the cities"], ["a", "but"], ["e le faia", "shall not made"], ["e Ieova?", "the LORD"]]},
  {num:7,words:[["E le faia", "shall not made"], ["lava", "very"], ["se mea", "a thing"], ["e le Ali'i", "shall not Lord"], ["o Ieova,", "the LORD"], ["a", "but"], ["e fa'aalia", "to revealed"], ["lona finagalo", "his a chiefs will or desire"], ["i ana auauna", "in his servant"], ["o perofeta.", "prophet"]]},
  {num:8,words:[["Ua tagi", "cried"], ["le leona,", "the lion"], ["po o ai", "who?"], ["se", "a"], ["le fefe?", "the get scared"], ["ua fetalai mai le Ali'i", "said the Lord"], ["o Ieova,", "the LORD"], ["po o ai", "who?"], ["se", "a"], ["le vavalo?", "the prophesy"]]},
  {num:9,words:[["Ia outou tala'iina atu i", "to you all preached in"], ["maota o Asetota,", "the name of a tree of Asetota"], ["ma maota", "and the name of a tree"], ["i le nuu", "in the land"], ["o Aikupito,", "Egypt"], ["ma ia outou", "and to you all"], ["fa'apea atu,", "thus"], ["Ia outou fa'apotopoto", "to you all gather"], ["mai", "from"], ["i mauga o Samaria,", "in mountain of Samaria"], ["ma vaavaai atu ai", "and looked around"], ["i vāvāō tetele", "in vegetation great"], ["o", "o"], ["i ai,", "therein"], ["atoa ma sauaga", "and persecution"], ["o", "o"], ["i ai.", "therein"]]},
  {num:10,words:[["Auā o loo fetalai mai Ieova,", "for is said the LORD"], ["Lātou te", "they will"], ["le iloa", "the know"], ["ona fai mea tonu,", "and make thing right"], ["o", "o"], ["e fa'aputu", "to to gather together"], ["i o lātou", "in of they"], ["maota o mea", "the name of a tree of thing"], ["e maua", "to received"], ["i le saua", "in the to have a return of sick-"], ["ma le vete.", "and the plunder"]]},
  {num:11,words:[["O le mea lea", "therefore"], ["o loo fa'apea mai ai", "saying from"], ["le Ali'i o Ieova,", "the Lord the LORD"], ["O le", "the"], ["ua ita mai", "angry from"], ["e fealuai o ia", "to walk about he"], ["i le nuu;", "in the land"], ["e aveesea foi", "to removed away also"], ["e ia", "by him"], ["lou malosi ai", "your strong"], ["ia te oe,", "unto you"], ["e vetea ou maota.", "to plundered I the name of a tree"]]},
  {num:12,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["Fa'apei", "like"], ["ona fao", "and to seize"], ["e le leoleo mamoe", "shall not shepherd"], ["o alaga", "cry"], ["e lua,", "by two"], ["po", "night"], ["o se fasi taliga", "a kill ear"], ["i le gutu", "in the mouth"], ["o le leona,", "the lion"], ["e fa'apea ona", "saying and"], ["laveaiina", "delivered"], ["o le fanauga", "the children"], ["a Isaraelu o", "of Israel of"], ["e nonofo", "to dwell"], ["i Samaria,", "in Samaria"], ["i le pito moega,", "in the edge bed"], ["ma Tamaseko foi", "and Damascus also"], ["i le moega.", "in the bed"]]},
  {num:13,words:[["Ia outou fa'alogologo,", "to you all listen"], ["ma fa'ailo atu", "and make maggot"], ["i le 'āiga", "in the family"], ["o Iakopo,", "Jacob"], ["o loo fa'apea mai le Ali'i", "saying from the Lord"], ["o Ieova,", "the LORD"], ["o le Atua", "of God"], ["o 'au.", "troops"]]},
  {num:14,words:[["O le aso ou te taui atu ai", "the day I will a reward"], ["agasala", "sin"], ["a Isaraelu ia te ia,", "of Israel to him"], ["ou te asiasi foi", "I will visit also"], ["i fata faitaulaga", "in altar"], ["i Peteli;", "in Bethel"], ["e vavaeeseina foi", "shall be cut off also"], ["nifo o fata faitaulaga,", "tooth of altar"], ["ona pauu ai lea", "and fell then then"], ["i le eleele.", "the ground"]]},
  {num:15,words:[["Ou te taia", "I will struck"], ["le fale", "the house"], ["o le tausaga maalili,", "the year maalili"], ["atoa ma le fale", "and the house"], ["o le tausaga vevela;", "the year to be hot"], ["e fa'aumatia fale nifo elefane,", "to destroyed house tooth elefane"], ["e mavae atu foi", "to passed also"], ["o fale tetele,", "house great"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
];
renderVerseSet(_amo_ch_3_Verses, 'amo-ch3-verses');

var _amo_ch_4_Verses = [
  {num:1,words:[["Ia outou fa'alogologo i", "to you all listen in"], ["lenei 'upu o outou", "this word of you all"], ["povi fafine o Vasana,", "cattle women of Bashan"], ["o loo", "is/are"], ["i le mauga", "in the mountain"], ["o Samaria,", "Samaria"], ["o", "o"], ["e fa'asaua", "to cruel"], ["i", "in"], ["e vaivai,", "to weak"], ["ma fa'asaunoa", "and make to damage"], ["i", "in"], ["e matitiva,", "to poor"], ["o", "o"], ["e fa'apea atu", "saying"], ["i o lātou", "in of they"], ["matai,", "chief"], ["Au mai ia,", "bring to"], ["mātou te feinu ai.", "we feinu"]]},
  {num:2,words:[["Ua tauto", "to take an oath"], ["le Ali'i o Ieova", "the Lord the LORD"], ["i lona paia,", "in his holy"], ["fa'auta,", "behold"], ["e oo mai aso", "it shall come to pass from day"], ["ia te outou", "unto you all"], ["na te aveeseina ai", "he carried away"], ["outou", "you all"], ["i mātau,", "in mātau"], ["ma la outou fānau", "and your born"], ["i mātau i'a.", "in mātau fish"]]},
  {num:3,words:[["Tou te o atu foi", "second person plural went also"], ["i mea", "in thing"], ["ua lepetia,", "overthrown"], ["taitasi", "each"], ["i le mea", "in the thing"], ["ua ia lumanai ai,", "to lumanai"], ["e lafoaiina outou", "to forsaken you all"], ["ai", "ai"], ["le maota,", "the the name of a tree"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:4,words:[["Ia outou", "to you all"], ["o mai", "came"], ["i Peteli,", "in Bethel"], ["ma fai ai", "and make"], ["amio leaga;", "iniquity/wickedness"], ["ina fa'atele ia", "so that make great to"], ["agasala", "sin"], ["i Kilikala;", "in Gilgal"], ["ia outou avatu i", "to you all give away in"], ["taeao", "morning"], ["a outou taulaga,", "your offering"], ["ma mea", "and thing"], ["e sefulu a'i", "by ten"], ["a outou mea", "your thing"], ["i lona tolu", "in his three"], ["o tausaga.", "year"]]},
  {num:5,words:[["Ina fai ia", "so that make to"], ["se taulaga fa'afetai", "an offering thank"], ["i mea", "in thing"], ["ua fa'afefeteina;", "feared"], ["ia outou tala'iina", "to you all preached"], ["taulaga", "offering"], ["e faia", "to made"], ["ma le loto,", "and the heart"], ["ia outou logo atu ai;", "to you all to hear"], ["auā", "for"], ["o lo outou loto lea,", "your heart"], ["le fanauga", "the children"], ["a Isaraelu e,", "of Israel by"], ["o loo fetalai mai ai", "is said"], ["le Ali'i o Ieova.", "the Lord the LORD"]]},
  {num:6,words:[["O a'u foi,", "I am also"], ["ua ou avatu ia te outou", "I gave away unto you all"], ["nifo mamā", "tooth clean"], ["i", "in"], ["a outou aai uma,", "your every city"], ["ma le oge", "and the a famine"], ["i mea", "in thing"], ["e 'ai", "to eat"], ["i o outou", "in of you all"], ["nuu uma;", "nation all"], ["a", "but"], ["ua outou", "you all"], ["le toe foi mai", "the returned"], ["lava ia te au,", "very unto me"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:7,words:[["Ua ou taofia foi", "I held back also"], ["le", "the"], ["ua ia te outou,", "unto you all"], ["a", "but"], ["e toe tolu masina", "to again three month"], ["i le oo ai", "in the oo"], ["le seleselegāsaito;", "the seleselegāsaito"], ["ua ou fa'atotō ifo", "I made blood down"], ["le", "the"], ["ua", "ua"], ["i le tasi aai,", "in the one cities"], ["a", "but"], ["o le isi aai", "the other cities"], ["ua ou", "I"], ["le fa'auaina;", "the was to insist on"], ["ua uaina", "wine"], ["le tasi pito nuu,", "the one edge nation"], ["a", "but"], ["o le nuu", "the nation"], ["e lei uaina", "by not wine"], ["ua mago lea.", "a small eel"]]},
  {num:8,words:[["Ona o atu ai lea", "and went out"], ["o aai", "cities"], ["pe lua", "whether two"], ["pe tolu", "whether three"], ["i le tasi aai", "in the one cities"], ["e inu vai ai;", "to drink water"], ["a", "but"], ["ua", "ua"], ["le malilie;", "the malilie"], ["a", "but"], ["ua", "ua"], ["le toe foi mai", "the returned"], ["lava outou ia te au,", "very you all unto me"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:9,words:[["Ua ou taia", "I struck"], ["outou", "you all"], ["i le mamae", "in the mamae"], ["ma le polopologā;", "and the Chili pepper"], ["ua 'aina", "edible"], ["e le sē kasama", "by the a kasama"], ["o outou fa'atoaga,", "you all garden"], ["ma o outou", "and of you all"], ["tovine,", "vineyard"], ["ma o outou", "and of you all"], ["mati,", "fig"], ["ma outou olive;", "with you olive"], ["a", "but"], ["na", "na"], ["le toe foi mai outou", "the returned you all"], ["ia te au,", "unto me"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:10,words:[["Ua ou auina atu ia te outou", "I sent unto you all"], ["le fa'amai,", "the faamai"], ["e pei ona", "as"], ["i ai", "therein"], ["i Aikupito;", "in Egypt"], ["ua ou fasia", "I slaughtered"], ["i le pelu", "by the sword"], ["o outou taulelea,", "you all young men"], ["o outou solofanua foi", "you all horse also"], ["ua aveeseina;", "carried away"], ["ua ou fa'aoo", "I brought upon"], ["ae", "but"], ["i o outou", "in of you all"], ["pogaiisu", "the nostrils"], ["le elo o", "the elo of"], ["a outou toagālauapi;", "your camp"], ["a", "but"], ["ua outou", "you all"], ["le toe foi mai ia te au,", "the returned unto me"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:11,words:[["Ua ou fa'aumatia", "I destroyed"], ["nisi o outou,", "some of you all"], ["fa'apei", "like"], ["ona fa'aumatia", "and destroyed"], ["e le Atua", "God"], ["o Sotoma", "Sodom"], ["ma Komoro;", "and Gomorrah"], ["e pei o le motumotu", "like the island"], ["o le afi outou", "the fire you all"], ["ua seia mai le afi;", "until from the fire"], ["a", "but"], ["ua outou", "you all"], ["le toe foi mai ia te au,", "the returned unto me"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:12,words:[["O le mea lea", "therefore"], ["e fa'apea ai", "saying"], ["ona ou faia", "and I made"], ["ia te oe", "unto you"], ["Isaraelu e,", "Israel by"], ["Ou te fai lenei", "I will make this"], ["mea ia te oe,", "thing unto you"], ["o le mea", "the thing"], ["lava lea", "very"], ["Isaraelu e,", "Israel by"], ["ia e sauni ai", "to to he who beg^ins the game"], ["lua te fetaiai", "you two will meet one another"], ["ma lou Atua.", "and your God"]]},
  {num:13,words:[["Auā", "for"], ["fa'auta mai,", "behold from"], ["o le", "the"], ["na faia mauga,", "made mountain"], ["ma", "and"], ["na faia", "made"], ["le matagi,", "the wind"], ["ma", "and"], ["ua fa'ailoaina atu", "revealed"], ["i le tagata", "in the man"], ["lona manatu,", "his thought"], ["o le", "the"], ["na te liua", "he turned"], ["le taeao", "the morning"], ["i le pouliuli,", "in the darkness"], ["o lē sāvali", "the walk"], ["i luga o mea maualuluga", "upon thing most high"], ["o le lalolagi,", "the earth"], ["o Ieova,", "the LORD"], ["o le Atua", "of God"], ["o 'au,", "troops"], ["o lona suafa lea.", "his name"]]},
];
renderVerseSet(_amo_ch_4_Verses, 'amo-ch4-verses');

var _amo_ch_5_Verses = [
  {num:1,words:[["Le 'āiga o Isaraelu e,", "the family of Israel by"], ["ia outou fa'alogologo i", "to you all listen in"], ["lenei 'upu ou te sauni atu ai", "this word I will he who beg^ins the game"], ["ia te outou,", "unto you all"], ["o le pese", "the a song"], ["e aualofa a'i", "to a keepsake"], ["lava .", "very"]]},
  {num:2,words:[["Ua paū", "fell"], ["le taupou o Isaraelu,", "the virgin of Israel"], ["e le toe tulai;", "shall not again arise up"], ["ua taatia o ia", "taatia he"], ["i lona laueleele,", "in his ground"], ["e leai se", "there is no"], ["na te fa'atulaiina", "he made arise up"], ["o ia.", "he"]]},
  {num:3,words:[["Auā o loo fa'apea mai le Ali'i", "for saying from the Lord"], ["o Ieova,", "the LORD"], ["O le aai", "the cities"], ["na o atu ai", "went"], ["le toaafe,", "the thousand"], ["e totoe", "to phiral of foe"], ["le toaselau;", "the a hundred people"], ["i le", "in the"], ["ma le aai", "and the cities"], ["na o atu ai", "went"], ["le toaselau,", "the a hundred people"], ["e totoe", "to phiral of foe"], ["le toatinoagafulu", "the ten people"], ["i le 'āiga", "in the family"], ["o Isaraelu.", "Israel"]]},
  {num:4,words:[["Auā o loo fa'apea mai Ieova", "for saying from the LORD"], ["i le 'āiga", "in the family"], ["o Isaraelu,", "Israel"], ["Ia outou saili", "to you all seek"], ["mai ia te au,", "from me"], ["tou te ola ai.", "second person plural life"]]},
  {num:5,words:[["A", "but"], ["e aua", "to for"], ["le saili ia", "the seek to"], ["Peteli,", "Bethel"], ["aua", "for"], ["le o", "the of"], ["i Kilikala,", "in Gilgal"], ["aua foi", "for also"], ["le ui atu", "the although"], ["i Peresepa;", "in Peresepa"], ["auā", "for"], ["e matuā tāfea Kilikala,", "to great exiled captive Gilgal"], ["e iu vale Peteli.", "to become of foolish Bethel"]]},
  {num:6,words:[["Ia outou saili ia", "to you all seek to"], ["Ieova,", "the LORD"], ["tou te ola ai,", "second person plural life"], ["ina ne'i oo atu", "so that now arrived"], ["o ia pei", "he like"], ["se afi", "a fire"], ["i le 'āiga", "in the family"], ["o Iosefa,", "Joseph"], ["ma fa'aumatia ai,", "and destroyed"], ["e leai foi", "there is not also"], ["se tasi", "a one"], ["i Peteli", "in Bethel"], ["na te tineia.", "he tineia"]]},
  {num:7,words:[["O outou", "you all"], ["o", "o"], ["e liliu", "to turn"], ["le fa'amasinoga", "the judgment"], ["i laena,", "in laena"], ["ma lafo", "and cloth used as gratuity for a talking chief"], ["i lalo", "in under"], ["le amiotonu", "the righteous"], ["i le eleele,", "the ground"]]},
  {num:8,words:[["ia outou saili i le", "to you all seek in the"], ["na", "na"], ["na faia Kima", "made Kima"], ["ma Kisila;", "and Kisila"], ["o le", "the"], ["na te liua", "he turned"], ["le ata", "the a shadow"], ["o le oti", "the die"], ["i le taeao,", "in the morning"], ["ma fa'apouliuligia", "and faapouliuligia"], ["le ao peiseai", "the day as if"], ["ua po;", "night"], ["o le", "the"], ["na te valaauina", "he called"], ["le suāsami", "the waters"], ["o le sami,", "Sea"], ["ma liligi ifo ai", "and to pour down"], ["i le fogāeleele;", "the face of the earth"], ["o Ieova", "the LORD"], ["o lona suafa lea.", "his name"]]},
  {num:9,words:[["O le", "the"], ["na te fa'aoo", "he brought upon"], ["fa'afuasei atu", "faafuasei"], ["le fa'atafunaga", "the foundation"], ["i le", "in the"], ["ua malosi,", "strong"], ["ona oo atu ai lea", "and arrived then then"], ["o le fa'atafunaga", "the foundation"], ["i le 'olo.", "in the trench"]]},
  {num:10,words:[["Ua lātou ita atu", "they angry"], ["i le", "in the"], ["ua aoai", "chastise"], ["i le faitotoa;", "at the door"], ["ma", "and"], ["ua lātou 'ino'ino", "they disdained"], ["i le", "in the"], ["ua tautala fa'amaoni.", "spoke faithful"]]},
  {num:11,words:[["O lenei", "now"], ["foi,", "also"], ["ua outou soli", "you all to tread upon"], ["i le", "in the"], ["ua vaivai,", "weak"], ["mona", "to burst forth (as faiai"], ["ua outou tali foi", "you all responded also"], ["ia te ia", "to him"], ["o taulaga saito;", "offering wheat"], ["o le mea lea", "therefore"], ["e ui", "to although"], ["ina faia e", "so that made by"], ["outou", "you all"], ["o fale maa talai,", "house stone preach"], ["a", "but"], ["e tou te", "to second person plural"], ["le nonofo ai;", "the dwelling"], ["ua outou totōina", "you all planted"], ["tovine lelei,", "vineyard good"], ["a", "but"], ["e tou te", "to second person plural"], ["le inu uaina ai.", "the drink wine"]]},
  {num:12,words:[["Auā", "for"], ["ua ou iloa", "I knew"], ["a outou agasala", "your sin"], ["ua matuā tele,", "great great"], ["ma", "and"], ["a outou amio", "your conduct"], ["e matuā leaga;", "to great evil"], ["o loo fa'asaua", "is cruel"], ["i le", "in the"], ["ua amiotonu,", "righteous"], ["ua talia", "received"], ["se taui,", "a a reward"], ["ma", "and"], ["ua fa'afoi atu", "returned back"], ["i", "in"], ["e ua matitiva", "by poor"], ["o", "o"], ["i le faitotoa.", "at the door"]]},
  {num:13,words:[["O le mea lea", "therefore"], ["e fa'alologo ai", "to to hold one's tongue"], ["le", "the"], ["ua poto", "wise"], ["i ia", "in to"], ["ona po;", "and night"], ["auā", "for"], ["e leaga ia", "to evil to"], ["ona po.", "and night"]]},
  {num:14,words:[["Ia outou saili i le", "to you all seek in the"], ["lelei,", "good"], ["a", "but"], ["e le", "by the"], ["o le leaga,", "the evil"], ["ina ia ola ai", "so that life"], ["outou;", "you all"], ["ona", "and"], ["i ai lea", "therein"], ["ia te outou", "unto you all"], ["o Ieova", "the LORD"], ["o le Atua", "of God"], ["o 'au,", "troops"], ["e pei ona", "as"], ["outou fai mai ai.", "you all said"]]},
  {num:15,words:[["Ia outou 'ino'ino i le", "to you all disdained in the"], ["leaga,", "evil"], ["a", "but"], ["e loto atu", "to heart"], ["i le lelei,", "in the good"], ["ma ia outou", "and to you all"], ["fa'atumau", "make enduring"], ["le fa'amasinoga", "the judgment"], ["i le faitotoa;", "at the door"], ["atonu", "impers"], ["e alofa Ieova", "to love the LORD"], ["le Atua o 'au", "God troops"], ["i", "in"], ["e ua totoe", "by phiral of foe"], ["ia Iosefa.", "to Joseph"]]},
  {num:16,words:[["O le mea lea", "therefore"], ["o loo fa'apea mai ai", "saying from"], ["Ieova,", "the LORD"], ["le Atua o 'au,", "God troops"], ["o le Ali'i", "the Lord"], ["lava,", "very"], ["E pa", "to wall"], ["le lauaitu", "the a weeping"], ["i ala uma lava;", "in way all very"], ["lātou te fa'apea ane", "they will thus"], ["i ala tele uma,", "in way great all"], ["Aue!", "alas! oh!"], ["aue!", "alas! oh!"], ["lātou te valaau foi", "they will cried out also"], ["i lē galue", "in the till"], ["i fanua ia te fa'anoanoa;", "in land unto mourn"], ["ma", "and"], ["e ua iloa pese", "by knew a song"], ["e au alofa a'i,", "to me love"], ["ia tagitu'i i lātou.", "to tagitu'i them"]]},
  {num:17,words:[["E pa foi", "to wall also"], ["le lauaitu", "the a weeping"], ["i tovine uma,", "in vineyard all"], ["auā ou te ui atu", "for I will although"], ["ia te oe,", "unto you"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:18,words:[["Talofa ia te outou", "hello unto you all"], ["o", "o"], ["e mananao", "to desire"], ["i le aso", "in the day"], ["o Ieova!", "the LORD"], ["Se a ea", "what indeed? / why?"], ["lona aoga ia te outou?", "his useful unto you all"], ["O le aso", "the day"], ["o Ieova,", "the LORD"], ["o le pouliuli lea,", "the darkness"], ["a", "but"], ["e le", "by the"], ["o le malamalama.", "the light"]]},
  {num:19,words:[["E pei o le tagata", "like the man"], ["ua sola ese", "fled away"], ["i le leona,", "in the lion"], ["a", "but"], ["ua la fetaiai", "la meet one another"], ["ma le urosa;", "and the bear"], ["pe ulufale atu", "whether enter"], ["i le fale,", "in the house"], ["ma totoo ai", "and tlic last"], ["lona lima", "his hand"], ["i le pa puipui,", "in the wall gate"], ["ona utia ai lea", "and utia then then"], ["o ia", "he"], ["i le gata.", "in the a snake"]]},
  {num:20,words:[["E le", "by the"], ["o le pouliuli ea", "the darkness indeed?/really?"], ["le aso o Ieova,", "the day the LORD"], ["a", "but"], ["e le malamalama;", "shall not light"], ["e pogisa lava,", "to darkness very"], ["e leai sona pupula?", "there is not sona brightness"]]},
  {num:21,words:[["Ua ou 'ino'ino,", "I disdained"], ["ua leaga ia te au", "evil unto me"], ["o outou tausamiga;", "you all feast"], ["ou te", "I will"], ["le fiafia", "the pleased"], ["i o outou", "in of you all"], ["fa'apotopotoga.", "assembly"]]},
  {num:22,words:[["E ui", "to although"], ["ina outou au mai ia te au", "so that you all bring unto me"], ["o taulaga mu,", "burnt offerings"], ["ma", "and"], ["a outou taulaga", "your offering"], ["i mea", "in thing"], ["e 'ai,", "to eat"], ["ou te", "I will"], ["le talia;", "the received"], ["o le taulaga fa'afetai", "the offering thank"], ["i", "in"], ["a outou manu pepeti,", "your animal fat portions"], ["ou te", "I will"], ["le vaai atu", "the looked toward"], ["i ai.", "therein"]]},
  {num:23,words:[["Ia e ave ese ia te au", "to to take away unto me"], ["le taalili o ou pese;", "the resounding of I a song"], ["o le leo mălie foi", "the voice mălie also"], ["o au napeli ou te", "I am napeli I will"], ["le fa'alogo ai.", "the hearken"]]},
  {num:24,words:[["A ia tafe ifo", "his to flow down"], ["le fa'amasinoga", "the judgment"], ["e pei o vai,", "like water"], ["ma le amiotonu", "and the righteous"], ["e pei o le vai", "like the water"], ["e tafe tetele", "to to flow great"], ["lava.", "very"]]},
  {num:25,words:[["Le 'āiga o Isaraelu e,", "the family of Israel by"], ["pe", "whether"], ["na outou au mai", "you all brought"], ["ea ia te au", "indeed?/really? unto me"], ["o taulaga,", "offering"], ["ma taulaga", "and offering"], ["i mea", "in thing"], ["e 'ai", "to eat"], ["i le vao", "in the wilderness"], ["i tausaga", "in year"], ["e fagafulu?", "to forty"]]},
  {num:26,words:[["Na outou tauave lava", "you all carried very"], ["le malumalu", "the temple"], ["o lo outou Moloka,", "your Molech"], ["ma Kiuna,", "and Kiuna"], ["o outou tupua,", "you all pillar"], ["o le fetu", "the star"], ["o lo outou atua", "your God"], ["na outou faia", "you all made"], ["mo outou.", "for you"]]},
  {num:27,words:[["Ou te fa'atāfeaina outou", "I will make exiled captive you all"], ["i ona tala atu", "in then side"], ["o Tamaseko,", "Damascus"], ["o loo fetalai mai ai", "is said"], ["Ieova,", "the LORD"], ["o le Atua", "of God"], ["o 'au,", "troops"], ["o lona suafa lea.", "his name"]]},
];
renderVerseSet(_amo_ch_5_Verses, 'amo-ch5-verses');

var _amo_ch_6_Verses = [
  {num:1,words:[["Talofa", "hello"], ["i", "in"], ["e o fa'atalanoa", "by of faatalanoa"], ["i Siona,", "in Zion"], ["ma", "and"], ["e o nonofo fa'atalanoa", "by of dwelling faatalanoa"], ["i le mauga", "in the mountain"], ["o Samaria,", "Samaria"], ["e ua ta'ua", "by us two"], ["i atu nuu silisili,", "in nation very much"], ["na ō", "ō"], ["i ai", "therein"], ["le 'āiga o Isaraelu.", "the family of Israel"]]},
  {num:2,words:[["Ia outou", "to you all"], ["o atu", "went"], ["i Kalene,", "in Kalene"], ["ma vaavaai atu,", "and looked around"], ["i le tou", "in the second person plural"], ["o atu ai", "went"], ["i Amato tele;", "in Amato great"], ["i le o ifo ai", "in the went down"], ["i Kata", "in Gad"], ["i Filisitia;", "in Philistine"], ["e sili ea lo lātou lelei", "to most indeed?/really? their good"], ["i", "in"], ["na mālō,", "kingdom"], ["pe sili ea", "whether most indeed?/really?"], ["ona tele", "and great"], ["o lo lātou laueleele", "their ground"], ["i lo", "than"], ["outou laueleele?", "you all ground"]]},
  {num:3,words:[["Talofa", "hello"], ["i", "in"], ["e ua manatu", "by thought"], ["ua mamao", "far"], ["le aso vale,", "the day foolish"], ["ma fa'alatalata mai le nofoa", "and drew near from the a seat"], ["o", "o"], ["i ai", "therein"], ["le fa'asaua;", "the cruel"]]},
  {num:4,words:[["o", "o"], ["e taooto", "to lie down"], ["i moega nifo elefane,", "in bed tooth elefane"], ["ma lātou taooto", "and they lie down"], ["i o lātou", "in of they"], ["moega;", "bed"], ["ma aai", "and cities"], ["i tamai mamoe", "in son sheep"], ["o le lafu,", "the flock"], ["ma tamai povi ai", "and son cattle"], ["le fale povi;", "the house cattle"]]},
  {num:5,words:[["o", "o"], ["e pepese fa'atasi ma le leo", "to sang together and the voice"], ["o le napeli,", "the napeli"], ["ma lātou sauni", "and they he who beg^ins the game"], ["mo", "for"], ["i lātou laaupese,", "them laaupese"], ["e pei o Tavita;", "like David"]]},
  {num:6,words:[["o", "o"], ["e inu uaina", "to drink wine"], ["i ipu tetele,", "in cup great"], ["ma uu ia te", "and oil unto"], ["i lātou", "them"], ["i uu", "in oil"], ["e sili", "to most"], ["ona lelei;", "and good"], ["a", "but"], ["ua", "ua"], ["le tiga", "the grieved"], ["i lātou", "them"], ["ona", "and"], ["o le malaia", "the disaster"], ["o Iosefa.", "Joseph"]]},
  {num:7,words:[["O le mea lea", "therefore"], ["e tāfea ai", "to exiled captive"], ["nei", "this"], ["i lātou,", "them"], ["e muamua", "to first the beginning"], ["i", "in"], ["e tāfea,", "to exiled captive"], ["e mavae atu", "to passed"], ["le alaga fiafia", "the cry pleased"], ["o", "o"], ["e taooto.", "to lie down"]]},
  {num:8,words:[["Ua tauto", "to take an oath"], ["le Ali'i o Ieova", "the Lord the LORD"], ["i lona soifua,", "in his life"], ["o loo fetalai mai ai", "is said"], ["Ieova", "the LORD"], ["le Atua o 'au,", "God troops"], ["Ua ou 'ino'ino", "I disdained"], ["i le mamalu", "in the glory"], ["o Iakopo,", "Jacob"], ["ua ou 'ino'ino foi", "I disdained also"], ["i ona maota;", "in then the name of a tree"], ["o le mea lea", "therefore"], ["ou te tuuina atu ai", "I will give"], ["le aai", "the cities"], ["atoa ma mea", "and thing"], ["ua tumu ai.", "filled"]]},
  {num:9,words:[["Afai foi", "if also"], ["e totoe tagata", "to phiral of foe man"], ["e toatinoagafulu", "to ten people"], ["i le fale", "in the house"], ["e tasi,", "by one"], ["lātou te oti ai", "they will die"], ["lava.", "very"]]},
  {num:10,words:[["E siitia", "to lifted up"], ["se tasi", "a one"], ["e le uso", "shall not brother"], ["o lona tamā,", "of his father"], ["o le", "the"], ["na te susunu foi", "he burned also"], ["ia te ia,", "to him"], ["e au mai ai", "to bring"], ["ivi ai", "bone"], ["le fale;", "the house"], ["na te fa'apea atu", "he thus"], ["i le", "in the"], ["ua", "ua"], ["i mea aupito", "in thing ^ to be"], ["i totonu", "in inside"], ["o le fale,", "the house"], ["Pe ai", "whether"], ["se tasi", "a one"], ["ua", "ua"], ["i ai", "therein"], ["pea ia te oe?", "continually unto you"], ["Ona tali atu foi", "and respond also"], ["lea o ia,", "he"], ["E leai lava.", "there is not very"], ["Ona fa'apea mai lea", "and thus from"], ["o ia,", "he"], ["Fa'alologo ia auā", "to hold one's tongue to for"], ["e le tatau ona", "shall not to wring out then"], ["ta'ua", "us two"], ["o le suafa", "the name"], ["o Ieova.", "the LORD"]]},
  {num:11,words:[["Auā", "for"], ["fa'auta mai ea,", "behold from indeed?/really?"], ["ua poloai atu", "commanded"], ["Ieova,", "the LORD"], ["na te taia foi", "he struck also"], ["le fale tele", "the house great"], ["ia solo,", "to to move swiftly"], ["ma le fale itiiti", "and the house small"], ["ia lepetia.", "to overthrown"]]},
  {num:12,words:[["E taufetuli ea solofanua", "to running indeed?/really? horse"], ["i le papa?", "in the rock"], ["pe suatia ai ea", "whether suatia indeed?/really?"], ["e se tasi", "by a one"], ["i povi? auā", "in cattle for"], ["ua outou liu", "you all liu"], ["i rosa", "in rosa"], ["le fa'amasinoga,", "the judgment"], ["ma le fua", "and the fruit"], ["o le amiotonu", "the righteous"], ["i laena.", "in laena"]]},
  {num:13,words:[["O outou", "you all"], ["o", "o"], ["e fiafia", "to pleased"], ["i se mea fa'atauvaa,", "in a thing vain"], ["o", "o"], ["e fa'apea mai,", "saying from"], ["Po", "night"], ["ua", "ua"], ["le maua mai ea", "the received from indeed?/really?"], ["i lo tātou malosi", "than we strong"], ["o nifo", "tooth"], ["mo", "for"], ["i tātou?", "us"]]},
  {num:14,words:[["A o lenei,", "but now"], ["fa'auta mai,", "behold from"], ["le 'āiga o Isaraelu e,", "the family of Israel by"], ["ou te fa'atuina", "I will built"], ["se tasi nuu,", "a one nation"], ["lātou te fai oe", "they will make you"], ["mo lātou fili,", "for they to choose"], ["o loo fetalai mai ai", "is said"], ["Ieova", "the LORD"], ["le Atua o 'au;", "God troops"], ["lātou te fa'asaua", "they will cruel"], ["ia te outou,", "unto you all"], ["e pau mai", "to fall from"], ["i le mea", "in the thing"], ["e ui atu ai", "to although"], ["i Amato,", "in Amato"], ["e pau mai", "to fall from"], ["i le vaitafe", "in the river"], ["o le vao.", "the vegetation"]]},
];
renderVerseSet(_amo_ch_6_Verses, 'amo-ch6-verses');

var _amo_ch_7_Verses = [
  {num:1,words:[["Ua fa'apea ona", "saying and"], ["fa'ailoaina mai ia te au", "revealed from me"], ["e le Ali'i", "shall not Lord"], ["o Ieova;", "the LORD"], ["fa'auta,", "behold"], ["na ia fa'atupuina", "to raised up"], ["o sē akerise", "a akerise"], ["i ona fa'atoa tutupu", "in then just now bring forth"], ["ae", "but"], ["o le vao mulimuli;", "the vegetation follow after"], ["fa'auta foi,", "and behold"], ["o le vao mulimuli", "the vegetation follow after"], ["ia,", "to"], ["a", "but"], ["ua mavae atu", "after"], ["seleselegāmutia", "seleselegāmutia"], ["a le tupu.", "but the king"]]},
  {num:2,words:[["Ona oo lea", "and oo"], ["ina uma ona", "so that all then"], ["aai", "cities"], ["o le vao iti", "the grass"], ["o le fanua,", "the land"], ["ona ou fa'apea atu ai lea,", "and I thus then then"], ["Le Ali'i Ieova e,", "the Lord O LORD!"], ["ou te aioi atu", "I will cry out"], ["ia e fa'amagalo", "to to forgive"], ["mai.", "from"], ["Pe tulai ia te ai", "whether arise up unto"], ["Iakopo,", "Jacob"], ["auā", "for"], ["ua vaivai lava ia?", "weak very to"]]},
  {num:3,words:[["Ua salamo Ieova", "repented the LORD"], ["i lena", "in that"], ["mea;", "thing"], ["ua fa'apea mai", "and said"], ["Ieova,", "the LORD"], ["E le oo.", "by the oo"]]},
  {num:4,words:[["Ua fa'apea ona", "saying and"], ["fa'ailoaina mai ia te au", "revealed from me"], ["e le Ali'i", "shall not Lord"], ["o Ieova;", "the LORD"], ["fa'auta,", "behold"], ["na valaau atu", "cried out"], ["le Ali'i o Ieova", "the Lord the LORD"], ["ia tauia i le afi,", "to repay in the fire"], ["i le", "in the"], ["ua fa'aumatia", "are destroyed"], ["le moana tele,", "the deep great"], ["ma fa'aumatia ai", "and destroyed"], ["le tasi mea.", "the one thing"]]},
  {num:5,words:[["Ona ou fai atu lea,", "and I said to"], ["Le Ali'i Ieova e,", "the Lord O LORD!"], ["ou te aioi atu,", "I will cry out"], ["ina soia;", "so that stop"], ["pe tulai ia te ai", "whether arise up unto"], ["Iakopo,", "Jacob"], ["auā", "for"], ["ua vaivai lava ia?", "weak very to"]]},
  {num:6,words:[["Ua salamo Ieova", "repented the LORD"], ["i lenei", "in this"], ["mea;", "thing"], ["ua fa'apea mai le Ali'i", "and said the Lord"], ["o Ieova,", "the LORD"], ["E le oo foi", "by the oo also"], ["lenei mea.", "this thing"]]},
  {num:7,words:[["Sa fa'apea ona", "saying and"], ["fa'ailoaina mai e", "revealed from by"], ["ia ia te au;", "to him me"], ["fa'auta,", "behold"], ["ua tu", "stood"], ["le Ali'i", "the Lord"], ["i le aupa tu sa'o,", "in the aupa stand the appointed portion of"], ["ua", "ua"], ["i ai", "therein"], ["i lona aao", "in his hand"], ["o le fua fa'atautau.", "the fruit make to hang up"]]},
  {num:8,words:[["Ona fetalai mai lea", "and said"], ["o Ieova ia te au,", "the LORD unto me"], ["Amosa e,", "Amos by"], ["se a ea", "what indeed? / why?"], ["se mea", "a thing"], ["ua e iloa?", "you knew"], ["I le", "in the"], ["ua ou fa'apea atu,", "I thus"], ["O le fua fa'atautau.", "the fruit make to hang up"], ["Ona fetalai mai ai lea", "and said then then"], ["o le Ali'i,", "the Lord"], ["Fa'auta,", "behold"], ["ou te tuu", "I will put"], ["se fua fa'atautau", "a fruit make to hang up"], ["i totonu", "in inside"], ["o lo'u nuu", "my nation"], ["o Isaraelu,", "Israel"], ["ou te", "I will"], ["le toe sopoia", "the again crossed over"], ["lava.", "very"]]},
  {num:9,words:[["E fa'atafunaina mea maualuluga", "to destroyed thing most high"], ["a Isaako,", "of Isaac"], ["e fa'atafunaina foi", "to destroyed also"], ["malumalu o Isaraelu;", "temple of Israel"], ["ou te tulai atu", "I will arise up"], ["ma le pelu", "and the sword"], ["i le 'āiga", "in the family"], ["o Ierepoamo.", "Jeroboam"]]},
  {num:10,words:[["Ona alu lea", "And he went"], ["o le feau", "the errand"], ["a Amasia", "of Amasia"], ["le ositaulaga", "the high priest"], ["a Peteli ia", "of Bethel to"], ["Ierepoamo", "Jeroboam"], ["le tupu o Isaraelu,", "the king of Israel"], ["ua fa'apea atu,", "and said"], ["Ua fouvale Amosa ia te oe", "to rebel Amos unto you"], ["i le 'āiga", "in the family"], ["o Isaraelu,", "Israel"], ["ua", "ua"], ["le lavā onosai", "the very patience"], ["le nuu", "the nation"], ["i ana 'upu uma.", "in his word all"]]},
  {num:11,words:[["Auā", "for"], ["ua fa'apea mai", "and said"], ["Amosa,", "Amos"], ["E māliu Ierepoamo", "to die Jeroboam"], ["i le pelu,", "by the sword"], ["e matuā ta'ita'iina Isaraelu fa'atagata", "to great led Israel make human"], ["o taua ai", "war"], ["lo lātou lava laueleele.", "their very ground"]]},
  {num:12,words:[["Ua fa'apea mai foi", "and said also"], ["Amasia ia Amosa,", "Amasia to Amos"], ["Le tagata vaai e,", "the man look by"], ["alu ia,", "go to"], ["ina sola oe", "so that escape you"], ["i le nuu", "in the land"], ["o Iuta,", "Judas"], ["ma", "and"], ["e 'ai", "to eat"], ["i lea", "in"], ["mea,", "thing"], ["ma vavalo ai.", "and prophesy"]]},
  {num:13,words:[["A", "but"], ["e aua", "to for"], ["e te toe vavalo", "by again prophesy"], ["i Peteli;", "in Bethel"], ["auā", "for"], ["o le malumalu lea", "the temple"], ["o le tupu,", "the king"], ["o le maota foi", "the the name of a tree also"], ["o le tupu.", "the king"]]},
  {num:14,words:[["Ona tali atu lea", "and respond"], ["o Amosa", "Amos"], ["ua fa'apea atu ia", "and said to"], ["Amasia,", "Amasia"], ["Ou te", "I will"], ["le", "the"], ["se perofeta a'u", "a prophet me"], ["nei,", "this"], ["ou te", "I will"], ["le", "the"], ["se atali'i foi", "a son also"], ["o se perofeta;", "a prophet"], ["a", "but"], ["o le fagamanu a'u,", "the fagamanu me"], ["ma le galue", "and the till"], ["i sukamoru.", "in sukamoru"]]},
  {num:15,words:[["A", "but"], ["ua avea a'u", "became me"], ["e Ieova", "the LORD"], ["sa ou mulimuli", "I followed after"], ["i le lafu mamoe,", "in the flock sheep"], ["ma", "and"], ["ua fa'apea mai", "and said"], ["Ieova ia te au,", "the LORD unto me"], ["Alu ia,", "go to"], ["ina", "so that"], ["e vavalo", "to prophesy"], ["i lo'u nuu", "in my nation"], ["o Isaraelu.", "Israel"]]},
  {num:16,words:[["O lenei,", "now"], ["ina", "so that"], ["e fa'alogo mai ia", "to hearken from to"], ["i le afioga", "the word"], ["a Ieova.", "of the LORD"], ["Ua e fai mai,", "you said"], ["aua", "for"], ["le vavalo ia", "the prophesy to"], ["Isaraelu,", "Israel"], ["aua foi", "for also"], ["le tautala atu", "the speak toward"], ["i le 'āiga", "in the family"], ["o Isaako.", "Isaac"]]},
  {num:17,words:[["O le mea lea", "therefore"], ["o loo fa'apea mai ai", "saying from"], ["Ieova,", "the LORD"], ["E avea", "to become"], ["lau avā", "your wife"], ["ma fafine faitaaga", "and women fornication"], ["i le aai,", "in the cities"], ["e pauu foi", "to fell also"], ["i le pelu", "by the sword"], ["o ou atali'i", "I son"], ["ma ou afafine,", "and I daughter"], ["e vaevaeina", "to foot"], ["i le fua", "in the fruit"], ["lou fanua;", "your land"], ["e oti foi", "to die also"], ["oe", "you"], ["i le nuu leaga;", "in the land evil"], ["e matuā tāfea Isaraelu ai", "to great exiled captive Israel"], ["lona laueleele.", "his ground"]]},
];
renderVerseSet(_amo_ch_7_Verses, 'amo-ch7-verses');

var _amo_ch_8_Verses = [
  {num:1,words:[["Ua fa'apea ona", "saying and"], ["fa'aalia mai ia te au", "revealed from me"], ["e le Ali'i", "shall not Lord"], ["o Ieova;", "the LORD"], ["fa'auta mai,", "behold from"], ["o le ato fua otatā.", "the basket fruit otatā"]]},
  {num:2,words:[["Ona fa'apea mai lea", "and thus from"], ["o ia,", "he"], ["Amosa e,", "Amos by"], ["pe", "whether"], ["se a ea", "what indeed? / why?"], ["se mea", "a thing"], ["ua e iloa?", "you knew"], ["I le", "in the"], ["ua ou tali atu,", "I responded"], ["O le ato fua otatā.", "the basket fruit otatā"], ["Ona fa'apea mai ai lea", "and thus from then then"], ["o Ieova ia te au,", "the LORD unto me"], ["Ua oo mai le", "it came to pass from the"], ["iuga", "end"], ["i lo'u nuu", "in my nation"], ["o Isaraelu,", "Israel"], ["ou te", "I will"], ["le toe sopoia", "the again crossed over"], ["lava.", "very"]]},
  {num:3,words:[["E fai ma uio pese", "to be uio a song"], ["o le maota", "the the name of a tree"], ["i lea aso,", "on that day"], ["o loo fetalai mai ai", "is said"], ["le Ali'i o Ieova;", "the Lord the LORD"], ["e", "by"], ["i ai", "therein"], ["i mea uma tino", "in all things body"], ["o tagata oti", "of men die"], ["e tele,", "to great"], ["e lafoaiina", "to forsaken"], ["ma le", "and the"], ["le feganavai.", "the battle one another"]]},
  {num:4,words:[["Ia outou fa'alogologo i", "to you all listen in"], ["lenei mea,", "this thing"], ["o outou", "you all"], ["o", "o"], ["e fa'asaua", "to cruel"], ["i", "in"], ["e matitiva,", "to poor"], ["ina ia fa'aumatia", "so that destroyed"], ["lava", "very"], ["le au matitiva", "the me poor"], ["o le nuu,", "the nation"]]},
  {num:5,words:[["o loo fa'apea mai,", "saying from"], ["Pe mavae atu afea", "whether passed when?"], ["le masina fa'atoa vaaia", "the month just now seen"], ["ia tātou fa'atau ai", "to we buy"], ["saito?", "wheat"], ["pe mavae afea foi", "whether passed when? also"], ["le sapati ia", "the Sabbath to"], ["tātou tatalaina atu ai", "we opened"], ["saito? o loo fa'aitiitiina foi", "wheat is make small also"], ["le efa,", "the ephah"], ["ma fa'ateleina", "and multiplied"], ["le sekeli,", "the shekel"], ["o loo fai fua", "is make fruit"], ["fa'aletatau", "faaletatau"], ["e pepelo ai.", "to false"]]},
  {num:6,words:[["Tātou te fa'atau foi", "we will buy also"], ["tagata matitiva", "man poor"], ["i ario,", "in silver"], ["ma le tagata vaivai", "and the man weak"], ["i seevae", "in a shoe"], ["e lua;", "by two"], ["tātou te fa'atau atu foi", "we will buy also"], ["saito leaga.", "wheat evil"]]},
  {num:7,words:[["Ua tauto Ieova", "to take an oath the LORD"], ["i le mamalu", "in the glory"], ["o Iakopo,", "Jacob"], ["E le galo", "shall not forgotten"], ["lava ia te au", "very unto me"], ["e fa'avavau", "forever/everlasting"], ["a lātou galuega uma.", "their work all"]]},
  {num:8,words:[["E le gatete ea", "shall not tremble indeed?/really?"], ["le laueleele", "the ground"], ["ona o lenei", "because of this"], ["mea,", "thing"], ["ma fa'anoanoa ai", "and mourn"], ["i lātou uma", "them all"], ["o", "o"], ["e nonofo ai?", "to dwell"], ["e le matuā alu ae ea", "shall not great go up indeed?/really?"], ["e pei o se vaitafe?", "like a river"], ["e le lafoaiina ea", "shall not forsaken indeed?/really?"], ["ia", "to"], ["ma lofia,", "and lofia"], ["e pei o le vaitafe", "like the river"], ["o Aikupito?", "Egypt"]]},
  {num:9,words:[["O loo fetalai mai le Ali'i", "is said the Lord"], ["o Ieova,", "the LORD"], ["O lea aso ou te fa'agotoina ai", "therefore day I will make sank"], ["le la", "the la"], ["i le aoauli,", "in the aoauli"], ["ou te fa'apouliuligia foi", "I will faapouliuligia also"], ["le lalolagi", "the earth"], ["i le ao malamalama.", "in the cloud light"]]},
  {num:10,words:[["Ou te liu", "I will liu"], ["i fa'anoanoaga", "in grief"], ["a outou tausamiga,", "your feast"], ["ou te liliu foi", "I will turn also"], ["o outou pese uma", "you all a song all"], ["i auega;", "in alas! oh!"], ["ou te fa'alavalava foi", "I will a weal also"], ["sulugatiti uma", "the place where the all"], ["i le ie talatala,", "in the faamaise to untie"], ["o ulu foi", "head also"], ["o tagata uma", "of men all"], ["e selemamaina ia;", "by selemamaina to"], ["ou te faia lea", "I will make"], ["mea ia pei", "thing to like"], ["o le pese", "the a song"], ["e aualofa a'i", "to a keepsake"], ["ona", "and"], ["o le atali'i", "the son"], ["e toatasi,", "to one One"], ["o lona iuga foi,", "his end also"], ["o le aso vale", "the day foolish"], ["lava lea.", "very"]]},
  {num:11,words:[["O loo fa'apea mai le Ali'i", "saying from the Lord"], ["o Ieova,", "the LORD"], ["Fa'auta,", "behold"], ["e oo mai aso ou te tuuina atu ai", "it shall come to pass from day I will give"], ["le oge", "the a famine"], ["i le nuu;", "in the land"], ["e le", "by the"], ["se oge", "a a famine"], ["i mea", "in thing"], ["e 'ai,", "to eat"], ["po", "night"], ["o se gālala", "a gālala"], ["i le fia inu vai,", "in the want to do something drink water"], ["a", "but"], ["o le oge", "the a famine"], ["i le fa'alogologo", "in the listen"], ["i afioga", "in word"], ["a Ieova.", "of the LORD"]]},
  {num:12,words:[["Lātou te feoai", "they will walk about"], ["e pau mai", "to fall from"], ["i le tasi vasa", "in the one ocean"], ["e oo atu", "it shall come to pass"], ["i le isi vasa,", "in the other ocean"], ["e pau mai", "to fall from"], ["i le itu", "on the side"], ["i matu", "northward"], ["e oo atu", "it shall come to pass"], ["i le itu", "on the side"], ["i sasae lātou te feoai ai", "eastward they will walk about"], ["e sailiili atu ai", "to search"], ["le afioga", "the word"], ["a Ieova,", "of the LORD"], ["a", "but"], ["e le maua.", "shall not received"]]},
  {num:13,words:[["E vaivai", "to weak"], ["i le fia inu", "in the want to do something drink"], ["i lea aso", "on that day"], ["o taupou lalelei", "virgin beautiful"], ["atoa ma taulelea.", "and young men"]]},
  {num:14,words:[["O", "O"], ["i lātou", "them"], ["o", "o"], ["e tauto", "to to take an oath"], ["i le agasala", "in the sin"], ["a Samaria,", "of Samaria"], ["ma fa'apea atu,", "and thus"], ["Tanu e,", "to bury by"], ["ua soifua", "life"], ["lou atua;", "your God"], ["i le", "in the"], ["ma lea,", "and"], ["Ua ola", "life"], ["le ala o Peresepa;", "the way Peresepa"], ["e pauu lava", "to fell very"], ["i lātou,", "them"], ["lātou te", "they will"], ["le toe tutulai.", "the again arise up"]]},
];
renderVerseSet(_amo_ch_8_Verses, 'amo-ch8-verses');

var _amo_ch_9_Verses = [
  {num:1,words:[["Na ou iloa", "I knew"], ["le Ali'i,", "the Lord"], ["o loo tu", "is stand"], ["i luga", "in above"], ["o le fata faitaulaga;", "the altar"], ["ma", "and"], ["ua fa'apea mai", "and said"], ["o ia,", "he"], ["Ina tā ia", "so that struck to"], ["le lā'au fa'alava", "the tree crossbar"], ["o le faitotoa,", "the door"], ["ia luluina ai", "to shaken"], ["o pou;", "pillar"], ["ia gaugau ai", "to to break"], ["i luga o lātou", "upon they"], ["ulu uma;", "head all"], ["ou te fasioti foi", "I will killed also"], ["i le pelu", "by the sword"], ["e ua totoe", "by phiral of foe"], ["o", "o"], ["i lātou;", "them"], ["ai so lātou", "so they"], ["e sola", "to escape"], ["e le sao", "shall not the appointed portion of"], ["ia,", "to"], ["ai so lātou", "so they"], ["e sola ese", "to flee away"], ["e le laveaiina", "shall not delivered"], ["o ia.", "he"]]},
  {num:2,words:[["Afai lātou te eli", "if they will Eli"], ["ia oo i", "to oo in"], ["seoli,", "Sheol"], ["e aumaia", "to bring here"], ["i lātou", "them"], ["e lo'u lima ai lea", "to my hand then then"], ["mea;", "thing"], ["afai lātou te feaei", "if they will feaei"], ["i le lagi,", "in heaven"], ["ou te aveina ifo", "I will taken away down"], ["i lātou ai lea", "them then/and then"], ["mea.", "thing"]]},
  {num:3,words:[["Afai lātou te lalafi", "if they will lalafi"], ["i le tumutumu", "in the top"], ["o Karamelu,", "Carmel"], ["ou te suesue ai,", "I will examine"], ["ma au mai ai", "and bring"], ["i lātou ai lea", "them then/and then"], ["mea;", "thing"], ["afai foi", "if also"], ["e lalafi", "by lalafi"], ["i lātou ai", "them"], ["o'u luma", "my before"], ["i le loloto", "in the deep"], ["o le sami,", "Sea"], ["ou te fai atu ai", "I will said to"], ["i le gata,", "in the a snake"], ["ona utia ai lea", "and utia then then"], ["o", "o"], ["i lātou e", "them by"], ["ia.", "to"]]},
  {num:4,words:[["Afai foi", "if also"], ["e tāfea", "to exiled captive"], ["i lātou", "them"], ["i luma o", "before"], ["e o fai", "by of make"], ["i lātou", "them"], ["ma fili,", "and to choose"], ["ou te fai atu ai", "I will said to"], ["i le pelu,", "by the sword"], ["ona fasiotia ai lea", "and slain then then"], ["o", "o"], ["i lātou;", "them"], ["ou te fa'asaga atu", "I will face"], ["i ai,", "therein"], ["ina ia malaia", "so that disaster"], ["o", "o"], ["i lātou,", "them"], ["a", "but"], ["e le", "by the"], ["ona ia manuia.", "and to peace"]]},
  {num:5,words:[["O le Ali'i,", "the Lord"], ["o Ieova o 'au", "the LORD troops"], ["o ia", "he"], ["o le pai atu", "the pie"], ["i le laueleele,", "in the earth"], ["ona liu suāvai ai lea,", "and liu water then then"], ["e fa'anoanoa foi", "to mourn also"], ["i lātou uma", "them all"], ["o", "o"], ["e nonofo ai;", "to dwell"], ["e matuā alu ae", "to great go up"], ["e pei o se vaitafe,", "like a river"], ["e lofia o ia", "by lofia he"], ["e pei o le vaitafe", "like the river"], ["o Aikupito.", "Egypt"]]},
  {num:6,words:[["O ia lava", "he very"], ["o le", "the"], ["na te faia", "he made"], ["ona afioaga", "and dwelling place"], ["i le lagi,", "in heaven"], ["ma", "and"], ["na fa'avaeina", "foundation"], ["lana fa'aputugāmea", "his faaputugāmea"], ["i le lalolagi;", "on the earth"], ["o le", "the"], ["na te valaauina", "he called"], ["i le suāsami", "in the waters"], ["o le sami,", "Sea"], ["ma fa'amaligi ai", "and faamaligi"], ["i le fogāeleele;", "the face of the earth"], ["o Ieova,", "the LORD"], ["o lona suafa lea.", "his name"]]},
  {num:7,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["Le fanauga", "the children"], ["a Isaraelu e,", "of Israel by"], ["e le", "by the"], ["ua pei o tagata", "like of men"], ["Aitiope ea outou", "Aitiope indeed?/really? you all"], ["ia te au?", "unto me"], ["Pe", "whether"], ["na", "na"], ["le aveina ae Isaraelu", "the taken away up Israel"], ["e a'u ai", "to me"], ["le nuu o Aikupito?", "the nation of Egypt"], ["o Filisitia foi", "Philistine also"], ["ai Kafetori,", "Kafetori"], ["ma Suria ai", "and Syria"], ["Kira?", "Kira"]]},
  {num:8,words:[["Fa'auta,", "behold"], ["ua fa'asaga fofoga", "face face"], ["o le Ali'i", "the Lord"], ["o Ieova", "the LORD"], ["i le mālō amio leaga,", "in the kingdom iniquity"], ["ou te fa'aumatia ai", "I will destroyed"], ["ai", "ai"], ["le fogāeleele;", "the face of the earth"], ["na", "na"], ["o le 'āiga", "the family"], ["o Iakopo ou te", "Jacob I will"], ["le matuā fa'aumatia,", "the great destroyed"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
  {num:9,words:[["Fa'auta mai foi,", "behold from also"], ["ou te fai atu,", "I will said to"], ["ou te luluina foi", "I will shaken also"], ["le 'āiga o Isaraelu", "the family of Israel"], ["i nuu uma,", "in nation all"], ["e pei ona", "as"], ["luluina o saito", "shaken of wheat"], ["i le lulu,", "in the barn owl"], ["a", "but"], ["e le paū sina fua", "shall not fall white fruit"], ["i le eleele.", "the ground"]]},
  {num:10,words:[["E oti", "to die"], ["i le pelu", "by the sword"], ["o", "o"], ["i lātou uma", "them all"], ["o lo'u nuu", "my nation"], ["o", "o"], ["e agasala,", "to sin"], ["o", "o"], ["e fa'apea ane,", "saying"], ["E le aulia", "by the aulia"], ["mai le malaia,", "from the disaster"], ["pe maua mai", "whether received from"], ["i tātou.", "us"]]},
  {num:11,words:[["O le aso lea", "the day"], ["ou te fa'atuina ai", "I will built"], ["le fale apitaga", "the house a tempoiary"], ["o Tavita", "David"], ["ua paū;", "fell"], ["ou te pupuni", "I will shut"], ["i ana mea", "in his thing"], ["ua lepetia;", "overthrown"], ["o ana mea foi", "his thing also"], ["ua solo ou te", "to move swiftly I will"], ["atiina ae,", "to pull up up"], ["ou te atiina", "I will to pull up"], ["ae", "but"], ["e pei ona faia", "as made"], ["i ona po anamua.", "in his nights ancient"]]},
  {num:12,words:[["Ina ia fai", "so that make"], ["mo lātou tofi", "for they lot"], ["e ua totoe", "by phiral of foe"], ["o Etoma,", "Edom"], ["atoa ma nuu uma,", "and nation all"], ["o", "o"], ["e ua fa'aigoaina", "by named"], ["i lo'u igoa,", "in my name"], ["o loo fetalai mai ai", "is said"], ["Ieova", "the LORD"], ["o le", "the"], ["na te faia", "he made"], ["lenei mea.", "this thing"]]},
  {num:13,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["Fa'auta,", "behold"], ["e oo mai", "it shall come to pass from"], ["ona aso", "and day"], ["e aulia ai", "by aulia"], ["lē suatia", "the suatia"], ["le fanua", "the land"], ["i le selesele saito,", "in the an evenly cut head of wheat"], ["ma lē solivine", "and the solivine"], ["i le lulu saito;", "in the barn owl wheat"], ["e tautulu mauga", "by tautulu mountain"], ["i le suāvine,", "in the suāvine"], ["e tafea ai", "to exiled captive"], ["mea maupuepue uma.", "thing maupuepue all"]]},
  {num:14,words:[["Ou te fa'afoisia", "I will restored"], ["mai le tafeaga", "from the exiles in wa^"], ["o lo'u nuu", "my nation"], ["o Isaraelu,", "Israel"], ["ona lātou fa'atuina ai lea", "and they built then then"], ["o aai", "cities"], ["ua fa'atafunaina,", "destroyed"], ["ma nonofo ai;", "and dwelling"], ["lātou te totōina foi", "they will planted also"], ["tovine,", "vineyard"], ["ma inu uaina ai;", "and drink wine"], ["lātou te fai foi", "they will make also"], ["fa'atoaga,", "garden"], ["ma aai ai", "and cities"], ["ona fua.", "its fruit"]]},
  {num:15,words:[["Ou te totōina", "I will planted"], ["i lātou", "them"], ["i lo lātou laueleele;", "than they ground"], ["e le toe liaiina", "shall not again liaiina"], ["i lātou ai", "them"], ["lo lātou laueleele", "their ground"], ["na ou foaiina atu ai", "I given"], ["ia te i lātou,", "unto them"], ["o loo fetalai mai ai", "is said"], ["Ieova", "the LORD"], ["lou Atua.", "your God"]]},
];
renderVerseSet(_amo_ch_9_Verses, 'amo-ch9-verses');

})();