(function() {
var amo_ch_1_Verses = [
  {num:1,words:[["O upu a Amosa o le na i ai i le au fagamanu i Tikoa,", "word but amosa the therein in the I fagamanu in tikoa"], ["na ia iloa ai ia Isaraelu,", "to known to Israel"], ["i ona po o Usia le tupu o Iuta,", "in then night usia the grow Judas"], ["o ona po foi o Ierepoamo le atalii o Ioasa,", "then night also ierepoamo the son ioasa"], ["le tupu o Isaraelu;", "the grow Israel"], ["e lua tausaga na va a'i lea mea i le oo mai le mafuie.", "by two year space thing in the oo from the mafuie"]]},
  {num:2,words:[["Ua ia faapea mai,", "to thus from"], ["E leo tele mai Ieova mai Siona,", "to voice great from Jehovah from Zion"], ["e tŭlei ifo foi lona siufofoga mai Ierusalema;", "by tŭlei also his voice from Jerusalem"], ["e faanoanoa foi mea e tataa ai manu a e fagamanu,", "to to mourn also thing to animal but by fagamanu"], ["e mago foi le tumutumu o Karamelu.", "to a small eel also the tumutumu karamelu"]]},
  {num:3,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["E tolu agasala a Tamaseko,", "by three sin but tamaseko"], ["e fa foi,", "by four also"], ["ou te le liliu ese ai lana sala;", "I the turned away his a fine"], ["auā na latou solia ia Kiliata i uamea e soli ai saito.", "for them solia to kiliata in uamea to to tread upon wheat"]]},
  {num:4,words:[["A e ou te tuuina atu le afi i le fale o Asaeli,", "but to I given the fire in the house asaeli"], ["e faaumatia ai foi maota o Peniata.", "to destroy also the name of a tree peniata"]]},
  {num:5,words:[["Ou te gauia foi le faamaufaalava o Tamaseko,", "I gauia also the faamaufaalava tamaseko"], ["ou te faaumatia le ua mau i le vanu o Avene,", "I destroy the opinion in the valley avene"], ["atoa ma le ua 'u'u le tootoo i Pete-etena;", "and the oil the tootoo in pete-etena"], ["e tāfea foi le nuu o Suria i Kira,", "by tāfea also the nation suria in kira"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:6,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["E tolu agasala a Kasa,", "by three sin but kasa"], ["e fa foi,", "by four also"], ["ou te le liliu ese ai lana sala;", "I the turned away his a fine"], ["auā na latou faatāfeaina le tafeaga atoatoa ia tuuina atu ai i Etoma.", "for them faatāfeaina the exiles in wa^ completely to given in Edom"]]},
  {num:7,words:[["A e ou te tuuina atu le afi i le pa o Kasa,", "but to I given the fire in the a wall kasa"], ["e faaumatia ai ona maota.", "to destroy then the name of a tree"]]},
  {num:8,words:[["Ou te faaumatia foi le ua mau i Asetota,", "I destroy also the opinion in asetota"], ["ma le ua 'u'u le tootoo i Asekelona;", "and the oil the tootoo in asekelona"], ["ou te liliu atu lo'u lima i Ekerona,", "I turned my five in ekerona"], ["e fano e ua totoe o Filisitia,", "to perish by phiral of foe Philistine"], ["o loo o fetalai mai ai le Alii o Ieova.", "said from the Lord Jehovah"]]},
  {num:9,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["E tolu agasala a Turo,", "by three sin but turo"], ["e fa foi,", "by four also"], ["ou te le liliu ese ai lana sala;", "I the turned away his a fine"], ["auā na latou tuuina atu le tafeaga atoatoa i Etoma,", "for them given the exiles in wa^ completely in Edom"], ["mona ua le manatua le feagaiga a uso.", "to burst forth (as faiai the remember the covenant but a relative of the same generation and gender"]]},
  {num:10,words:[["A e ou te tuuina atu le afi i le pa o Turo,", "but to I given the fire in the a wall turo"], ["e faaumatia ai ona maota.", "to destroy then the name of a tree"]]},
  {num:11,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["E tolu agasala a Etoma,", "by three sin but Edom"], ["e fa foi,", "by four also"], ["ou te le liliu ese ai lana sala;", "I the turned away his a fine"], ["auā na ia tuliloa i le pelu lona uso,", "for to tuliloa in the a sword his a relative of the same generation and gender"], ["na ia le alofa lava,", "to the love indeed"], ["na saei pea lava lona ita;", "to tear continually indeed his angry"], ["na ia tausi pea lava lona ita tele.", "to keep continually indeed his angry great"]]},
  {num:12,words:[["A e ou te tuuina atu le afi i Timanu,", "but to I given the fire in timanu"], ["e faaumatia ai maota o Posara.", "to destroy the name of a tree posara"]]},
  {num:13,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["E tolu agasala a le fanauga a Amoni,", "by three sin but the children but amoni"], ["e fa foi,", "by four also"], ["ou te le liliu ese ai lana sala;", "I the turned away his a fine"], ["auā na latou faatiau i fafine totō i Kiliata,", "for them to disembowel in woman totō in kiliata"], ["ina ia faateleina e i latou lo latou laueleele.", "so that faateleina by them their ground"]]},
  {num:14,words:[["A e ou te tŭtŭ se afi i le pa o Rapa,", "but to I tŭtŭ a fire in the a wall rapa"], ["e faaumatia ai ma le alaga ona maota,", "to destroy and the a shoulder or leg of aa ' then the name of a tree"], ["i le aso e tau ai le taua,", "in the day to season the war"], ["ma le afā i le aso e i ai le asiosio.", "and the cyclone in the day by therein the asiosio"]]},
  {num:15,words:[["E alu i le tafeaga Malekama,", "to go in the exiles in wa^ malekama"], ["o ia atoa ma alii ua ia te ia faatasi ma ia,", "he together with and Lord unto to once and to"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
];
renderVerseSet(amo_ch_1_Verses, 'amo-ch1-verses');

var amo_ch_2_Verses = [
  {num:1,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["E tolu agasala a Moapi,", "by three sin but moapi"], ["e fa foi,", "by four also"], ["ou te le liliu ese ai lana sala;", "I the turned away his a fine"], ["auā na ia susunuina ivi o le tupu o Etoma na liu panisina.", "for to susunuina bone the grow Edom liu lime"]]},
  {num:2,words:[["A e ou te tuuina atu le afi i Moapi,", "but to I given the fire in moapi"], ["e faaumatia ai maota o Kiriota;", "to destroy the name of a tree kiriota"], ["e oti Moapi i le vāvāō,", "to die moapi in the vāvāō"], ["ma le alaga,", "and the a shoulder or leg of aa '"], ["ma le leo o le pu.", "and the voice the the tail"]]},
  {num:3,words:[["Ou te faaumatia le faamasino o i lea mea,", "I destroy the a judge in thing"], ["ou te fasiotia faatasi ma ia o alii uma,", "I slain once and to Lord all"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:4,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["E tolu agasala a Iuta,", "by three sin but Judas"], ["e fa foi,", "by four also"], ["ou te le liliu ese ai lana sala;", "I the turned away his a fine"], ["auā na latou lafoai le tulafono a Ieova,", "for them lafoai the law but Jehovah"], ["e lei tausi foi e i latou ana poloaiga;", "to whale's teeth keep also by them his commandment"], ["ua faaseseina i latou i a latou mea pepelo,", "faaseseina them in but them thing false"], ["sa naunau atu i ai o latou tamā.", "naunau therein them father"]]},
  {num:5,words:[["A e ou te tuuina atu le afi i Iuta,", "but to I given the fire in Judas"], ["e faaumatia ai maota o Ierusalema.", "to destroy the name of a tree Jerusalem"]]},
  {num:6,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["E tolu agasala a Isaraelu,", "by three sin but Israel"], ["e fa foi,", "by four also"], ["ou te le liliu ese ai lana sala;", "I the turned away his a fine"], ["auā na latou faatauina atu le ua amiotonu i ario,", "for them faatauina the righteous in silver"], ["ma le ua mativa i seevae e lua.", "and the mativa in a shoe by two"]]},
  {num:7,words:[["O e naunau atu i le efuefu o le laueleele i ulu o e matitiva,", "who naunau in the efuefu the ground in head by matitiva"], ["ma latou liliu ese le ala o e agamalu;", "and them turned away the arise by agamalu"], ["e alu ane foi le tagata atoa ma lona tamā i le teine e toatasi,", "to go also the man together with and his father in the girl to one One"], ["ina ia ta'uvaleina ai lo'u igoa paia.", "so that ta'uvaleina my name holy"]]},
  {num:8,words:[["Ua latou taooto foi i ofu ua tuu faafaatau i tafatafa o fata faitaulaga uma;", "them taooto also in garment put faafaatau in to cut in many places altar priest all"], ["ma ua latou inu uaina a e ua faasalaina i le fale o latou atua.", "and them drink wine but by faasalaina in the house them God"]]},
  {num:9,words:[["A o a'u,", "but I am"], ["na ou faaumatia le sa Amorī ai o latou luma,", "I destroy the amorī them before"], ["o lona maualuga e pei o le maualuga o arasi ia,", "his Iiigli to to be broken the Iiigli arasi to"], ["sa malosi foi o ia e pei o aluna;", "strong also he to to be broken aluna"], ["na ou faaumatia foi lona fua i luga ma ona aa i lalo.", "I destroy also his fruit in above and then aa in under"]]},
  {num:10,words:[["Na ou aveina ae foi outou ai le nuu o Aikupito;", "I aveina but also ye all the nation Egypt"], ["na ou ta'ita'iina outou i tausaga e fagafulu i le vao e maua ai le laueleele o le sa Amorī.", "I ta'ita'iina ye all in year by fagafulu in the vegetation to received the ground the amorī"]]},
  {num:11,words:[["Na ou faatuina ni o outou atalii e fai ma perofeta,", "I built some ye all son to make and prophet"], ["ma ni o outou taulelea e fai ma naseri.", "and some ye all taulelea to make and naseri"], ["Le fanauga a Isaraelu e,", "the children but Israel by"], ["e le ua faapea lava ea? o loo fetalai mai ai Ieova.", "by the thus indeed to rise (as a diver to the sur- said from Jehovah"]]},
  {num:12,words:[["A ua outou avatua uaina i le au naseri e inu ai,", "but ye all given away wine in the I naseri to drink"], ["ma vavao atu i le au perofeta,", "and to forbid in the I prophet"], ["o loo faapea atu,", "thus"], ["Aua le vavalo mai.", "for the prophesy from"]]},
  {num:13,words:[["Faauta,", "behold"], ["ou te taomia outou i lalo,", "I taomia ye all in under"], ["e pei ona taomia o le eleele i le fata faataavalevale ua tumu i fusi saito.", "to to be broken then taomia the earth in the altar to roll round and fill in fusi wheat"]]},
  {num:14,words:[["E iu vale le solaaga o le tele vave,", "to attain foolish the solaaga the great quick"], ["e le faateleina e le ua malosi lona malosi;", "by the faateleina by the strong his strong"], ["o le toa foi na te le faasaoina lona lava ola.", "the heroic also the saved his indeed life"]]},
  {num:15,words:[["O le ua fai aufana e le tumau ia;", "the make aufana by the endure to"], ["ma le ua momo'e tele vave e le sao ai o ia;", "and the momo'e great quick by the the appointed portion of he"], ["o lē tietie i le solofanua e le faasaoina ai foi e ia lona ola.", "not tietie in the horse by the saved also by him his life"]]},
  {num:16,words:[["O le toa ua sili lona loto tele,", "the heroic most his heart great"], ["e sola lē lavalavā o ia i lea aso,", "to flee not lavalavā he in day"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
];
renderVerseSet(amo_ch_2_Verses, 'amo-ch2-verses');

var amo_ch_3_Verses = [
  {num:1,words:[["Le fanauga a Isaraelu e,", "the children but Israel by"], ["ia outou faalogologo mai i lenei upu,", "to ye all listen from in this word"], ["o loo fetalai mai ai Ieova ia te outou,", "said from Jehovah unto ye all"], ["atoa ma le aiga uma na ou aveina ae ai le nuu o Aikupito;", "and the family all I aveina but the nation Egypt"], ["o loo faapea mai,", "thus from"]]},
  {num:2,words:[["Ua na o outou lava ua ou iloa i aiga uma o le lalolagi;", "ye all indeed I known in family all the earth"], ["o le mea lea ou te faasalaina ai outou ona o a outou agasala uma.", "therefore I faasalaina ye all then but ye all sin all"]]},
  {num:3,words:[["E feoai faatasi ea se toalua,", "by feoai once to rise (as a diver to the sur- a companion"], ["pe a le loto gatasi i laua?", "or but the heart gatasi them"]]},
  {num:4,words:[["E tagi ea le leona i le vao,", "to to cry to rise (as a diver to the sur- the leona in the vegetation"], ["pe a leai se mea ua na saeia? E lagona atu ea le leo o le tamai leona ai lona lua,", "or but no a thing saeia to to understand to rise (as a diver to the sur- the voice the son leona his two"], ["pe afai ua na le maua se mea?", "or if the received a thing"]]},
  {num:5,words:[["E lavea ea le manu lele i le mailei i le laueleele,", "to saved to rise (as a diver to the sur- the animal fly in the a trap in the ground"], ["a ua leai se mailei mo ia? E avae ea le mailei ai le laueleele,", "but no a a trap for to by avae to rise (as a diver to the sur- the a trap the ground"], ["a ua le maua se mea?", "but the received a thing"]]},
  {num:6,words:[["E ilia ea le pu i le aai,", "by ilia to rise (as a diver to the sur- the the tail in the eat"], ["a e le atuatuvale ai tagata? E tupu ea se malaia i le aai,", "but by the to be greatly dis- man to grow to rise (as a diver to the sur- a a calamity in the eat"], ["a e le faia e Ieova?", "but by the made to Jehovah"]]},
  {num:7,words:[["E le faia lava se mea e le Alii o Ieova,", "by the made indeed a thing by the Lord Jehovah"], ["a e faaalia lona finagalo i ana auauna o perofeta.", "but by faaalia his a chiefs will or desire in his servant prophet"]]},
  {num:8,words:[["Ua tagi le leona,", "to cry the leona"], ["po o ai se le fefe? ua fetalai mai le Alii o Ieova,", "night a the get scared said from the Lord Jehovah"], ["po o ai se le vavalo?", "night a the prophesy"]]},
  {num:9,words:[["Ia outou tala'iina atu i maota o Asetota,", "to ye all tala'iina in the name of a tree asetota"], ["ma maota i le nuu o Aikupito,", "and the name of a tree in the nation Egypt"], ["ma ia outou faapea atu,", "and to ye all thus"], ["Ia outou faapotopoto mai i mauga o Samaria,", "to ye all gather together from in mountain Samaria"], ["ma vaavaai atu ai i vāvāō tetele o i ai,", "and vaavaai in vāvāō great therein"], ["atoa ma sauaga o i ai.", "and sauaga therein"]]},
  {num:10,words:[["Auā o loo fetalai mai Ieova,", "for said from Jehovah"], ["Latou te le iloa ona fai mea tonu,", "them the known then make thing right"], ["o e faaputu i o latou maota o mea e maua i le saua ma le vete.", "who to gather together in them the name of a tree thing to received in the to have a return of sick- and the vete"]]},
  {num:11,words:[["O le mea lea o loo faapea mai ai le Alii o Ieova,", "therefore thus from the Lord Jehovah"], ["O le ua ita mai e fealuai o ia i le nuu;", "the angry from by fealuai he in the nation"], ["e aveesea foi e ia lou malosi ai ia te oe,", "by aveesea also by him your strong unto you"], ["e vetea ou maota.", "by vetea I the name of a tree"]]},
  {num:12,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["Faapei ona fao e le leoleo mamoe o alaga e lua,", "like then to seize by the police sheep a shoulder or leg of aa ' by two"], ["po o se fasi taliga i le gutu o le leona,", "night a kill ear in the mouth the leona"], ["e faapea ona laveaiina o le fanauga a Isaraelu o e nonofo i Samaria,", "by thus then delivered the children but Israel to dwelling in Samaria"], ["i le pito moega,", "in the pito moega"], ["ma Tamaseko foi i le moega.", "and tamaseko also in the moega"]]},
  {num:13,words:[["Ia outou faalogologo,", "to ye all listen"], ["ma faailo atu i le aiga o Iakopo,", "and faailo in the family James"], ["o loo faapea mai le Alii o Ieova,", "thus from the Lord Jehovah"], ["o le Atua o 'au.", "of God I"]]},
  {num:14,words:[["O le aso ou te taui atu ai agasala a Isaraelu ia te ia,", "the day I a reward sin but Israel unto to"], ["ou te asiasi foi i fata faitaulaga i Peteli;", "I asiasi also in altar priest in peteli"], ["e vavaeeseina foi nifo o fata faitaulaga,", "by vavaeeseina also tooth altar priest"], ["ona pauu ai lea i le eleele.", "and fell in the earth"]]},
  {num:15,words:[["Ou te taia le fale o le tausaga maalili,", "I taia the house the year maalili"], ["atoa ma le fale o le tausaga vevela;", "and the house the year to be hot"], ["e faaumatia fale nifo elefane,", "to destroy house tooth elefane"], ["e mavae atu foi o fale tetele,", "to a parting also house great"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
];
renderVerseSet(amo_ch_3_Verses, 'amo-ch3-verses');

var amo_ch_4_Verses = [
  {num:1,words:[["Ia outou faalogologo i lenei upu o outou povi fafine o Vasana,", "to ye all listen in this word ye all cattle woman vasana"], ["o loo i le mauga o Samaria,", "in the mountain Samaria"], ["o e faasaua i e vaivai,", "who to be oppressive in to weak"], ["ma faasaunoa i e matitiva,", "and faasaunoa in by matitiva"], ["o e faapea atu i o latou matai,", "who thus in them chief"], ["Au mai ia,", "bring to"], ["matou te feinu ai.", "we feinu"]]},
  {num:2,words:[["Ua tauto le Alii o Ieova i lona paia,", "to take an oath the Lord Jehovah in his holy"], ["faauta,", "behold"], ["e oo mai aso ia te outou na te aveeseina ai outou i mātau,", "it shall come to pass from day unto ye all aveeseina ye all in mātau"], ["ma la outou fanau i mātau i'a.", "and your born in mātau fish"]]},
  {num:3,words:[["Tou te o atu foi i mea ua lepetia,", "second person plural also in thing lepetia"], ["taitasi i le mea ua ia lumanai ai,", "each in the thing to lumanai"], ["e lafoaiina outou ai le maota,", "by lafoaiina ye all the the name of a tree"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:4,words:[["Ia outou o mai i Peteli,", "to ye all from in peteli"], ["ma fai ai amio leaga;", "and make conduct evil"], ["ina faatele ia agasala i Kilikala;", "let faatele to sin in kilikala"], ["ia outou avatu i taeao a outou taulaga,", "to ye all give away in morning but ye all offering"], ["ma mea e sefulu a'i a outou mea i lona tolu o tausaga.", "and thing by ten but ye all thing in his three year"]]},
  {num:5,words:[["Ina fai ia se taulaga faafetai i mea ua faafefeteina;", "let make to a offering to tliank in thing faafefeteina"], ["ia outou tala'iina taulaga e faia ma le loto,", "to ye all tala'iina offering to made and the heart"], ["ia outou logo atu ai;", "to ye all to hear"], ["auā o lo outou loto lea,", "for your heart"], ["le fanauga a Isaraelu e,", "the children but Israel by"], ["o loo fetalai mai ai le Alii o Ieova.", "said from the Lord Jehovah"]]},
  {num:6,words:[["O a'u foi,", "I am also"], ["ua ou avatu ia te outou nifo mamā i a outou aai uma,", "I give away unto ye all tooth clean in but ye all eat all"], ["ma le oge i mea e 'ai i o outou nuu uma;", "and the a famine in thing to eat in ye all nation all"], ["a ua outou le toe foi mai lava ia te au,", "but ye all the again also from indeed unto I"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:7,words:[["Ua ou taofia foi le ua ia te outou,", "I taofia also the unto ye all"], ["a e toe tolu masina i le oo ai le seleselegāsaito;", "but to again three moon in the oo the seleselegāsaito"], ["ua ou faatotō ifo le ua i le tasi aai,", "I faatotō the in the one eat"], ["a o le isi aai ua ou le faauaina;", "but the other eat I the faauaina"], ["ua uaina le tasi pito nuu,", "wine the one pito nation"], ["a o le nuu e lei uaina ua mago lea.", "but the nation to whale's teeth wine a small eel"]]},
  {num:8,words:[["Ona o atu ai lea o aai pe lua pe tolu i le tasi aai e inu vai ai;", "because of eat or two or three in the one eat to drink water"], ["a ua le malilie;", "but the malilie"], ["a ua le toe foi mai lava outou ia te au,", "but the again also from indeed ye all unto I"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:9,words:[["Ua ou taia outou i le mamae ma le polopologā;", "I taia ye all in the mamae and the polopologā"], ["ua 'aina e le sē kasama o outou faatoaga,", "edible by the sē kasama ye all faatoaga"], ["ma o outou tovine,", "and ye all tovine"], ["ma o outou mati,", "and ye all mati"], ["ma outou olive;", "and ye all olive"], ["a na le toe foi mai outou ia te au,", "but the again also from ye all unto I"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:10,words:[["Ua ou auina atu ia te outou le faamai,", "I sent unto ye all the faamai"], ["e pei ona i ai i Aikupito;", "to to be broken then therein in Egypt"], ["ua ou fasia i le pelu o outou taulelea,", "I struck in the a sword ye all taulelea"], ["o outou solofanua foi ua aveeseina;", "ye all horse also aveeseina"], ["ua ou faaoo ae i o outou pogaiisu le elo o a outou toagālauapi;", "I faaoo but in ye all the nostrils the elo but ye all toagālauapi"], ["a ua outou le toe foi mai ia te au,", "but ye all the again also from unto I"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:11,words:[["Ua ou faaumatia nisi o outou,", "I destroy some ye all"], ["faapei ona faaumatia e le Atua o Sotoma ma Komoro;", "like then destroy by the God sotoma and komoro"], ["e pei o le motumotu o le afi outou ua seia mai le afi;", "to to be broken the motumotu the fire ye all until from the fire"], ["a ua outou le toe foi mai ia te au,", "but ye all the again also from unto I"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:12,words:[["O le mea lea e faapea ai ona ou faia ia te oe Isaraelu e,", "therefore by thus then I made unto you Israel by"], ["Ou te fai lenei mea ia te oe,", "I make this thing unto you"], ["o le mea lava lea Isaraelu e,", "the thing indeed Israel by"], ["ia e sauni ai lua te fetaiai ma lou Atua.", "to to he who beg^ins the game two fetaiai and your God"]]},
  {num:13,words:[["Auā faauta mai,", "for behold from"], ["o le na faia mauga,", "the made mountain"], ["ma na faia le matagi,", "and made the wind"], ["ma ua faailoaina atu i le tagata lona manatu,", "and faailoaina in the man his thought"], ["o le na te liua le taeao i le pouliuli,", "the wide (as a canoe of too the morning in the darkness"], ["o lē savali i luga o mea maualuluga o le lalolagi,", "not walk in above thing maualuluga the earth"], ["o Ieova,", "Jehovah"], ["o le Atua o 'au,", "of God I"], ["o lona suafa lea.", "his name"]]},
];
renderVerseSet(amo_ch_4_Verses, 'amo-ch4-verses');

var amo_ch_5_Verses = [
  {num:1,words:[["Le aiga o Isaraelu e,", "the family Israel by"], ["ia outou faalogologo i lenei upu ou te sauni atu ai ia te outou,", "to ye all listen in this word I he who beg^ins the game unto ye all"], ["o le pese e aualofa a'i lava .", "the a song to a keepsake indeed"]]},
  {num:2,words:[["Ua paū le taupou o Isaraelu,", "paū the taupou Israel"], ["e le toe tulai;", "by the again arose up"], ["ua taatia o ia i lona laueleele,", "taatia he in his ground"], ["e leai se na te faatulaiina o ia.", "there is no faatulaiina he"]]},
  {num:3,words:[["Auā o loo faapea mai le Alii o Ieova,", "for thus from the Lord Jehovah"], ["O le aai na o atu ai le toaafe,", "the eat the toaafe"], ["e totoe le toaselau;", "to phiral of foe the toaselau"], ["i le ma le aai na o atu ai le toaselau,", "in the and the eat the toaselau"], ["e totoe le toatinoagafulu i le aiga o Isaraelu.", "to phiral of foe the toatinoagafulu in the family Israel"]]},
  {num:4,words:[["Auā o loo faapea mai Ieova i le aiga o Isaraelu,", "for thus from Jehovah in the family Israel"], ["Ia outou saili mai ia te au,", "to ye all seek from unto I"], ["tou te ola ai.", "second person plural life"]]},
  {num:5,words:[["A e aua le saili ia Peteli,", "but to for the seek to peteli"], ["aua le o i Kilikala,", "for the in kilikala"], ["aua foi le ui atu i Peresepa;", "for also the although in peresepa"], ["auā e matuā tāfea Kilikala,", "for to very tāfea kilikala"], ["e iu vale Peteli.", "to attain foolish peteli"]]},
  {num:6,words:[["Ia outou saili ia Ieova,", "to ye all seek to Jehovah"], ["tou te ola ai,", "second person plural life"], ["ina ne'i oo atu o ia pei se afi i le aiga o Iosefa,", "let now oo he to be broken a fire in the family Joseph"], ["ma faaumatia ai,", "and destroy"], ["e leai foi se tasi i Peteli na te tineia.", "there is not also a one in peteli tineia"]]},
  {num:7,words:[["O outou o e liliu le faamasinoga i laena,", "ye all to turned the judgment in laena"], ["ma lafo i lalo le amiotonu i le eleele,", "and cloth used as gratuity for a talking chief in under the righteous in the earth"]]},
  {num:8,words:[["ia outou saili i le na na faia Kima ma Kisila;", "to ye all seek in the made kima and kisila"], ["o le na te liua le ata o le oti i le taeao,", "the wide (as a canoe of too the a shadow the die in the morning"], ["ma faapouliuligia le ao peiseai ua po;", "and faapouliuligia the day as if night"], ["o le na te valaauina le suāsami o le sami,", "the called the suāsami the sea"], ["ma liligi ifo ai i le fogāeleele;", "and to pour in the face of the earth"], ["o Ieova o lona suafa lea.", "Jehovah his name"]]},
  {num:9,words:[["O le na te faaoo faafuasei atu le faatafunaga i le ua malosi,", "the faaoo faafuasei the faatafunaga in the strong"], ["ona oo atu ai lea o le faatafunaga i le 'olo.", "and oo the faatafunaga in the fortress"]]},
  {num:10,words:[["Ua latou ita atu i le ua aoai i le faitotoa;", "them angry in the aoai in the gate"], ["ma ua latou 'ino'ino i le ua tautala faamaoni.", "and them 'ino'ino in the to talk faithful"]]},
  {num:11,words:[["O lenei foi,", "this also"], ["ua outou soli i le ua vaivai,", "ye all to tread upon in the weak"], ["mona ua outou tali foi ia te ia o taulaga saito;", "to burst forth (as faiai ye all respond also unto to offering wheat"], ["o le mea lea e ui ina faia e outou o fale maa talai,", "therefore to although let made by ye all house stone preach"], ["a e tou te le nonofo ai;", "but to second person plural the dwelling"], ["ua outou totōina tovine lelei,", "ye all totōina tovine good"], ["a e tou te le inu uaina ai.", "but to second person plural the drink wine"]]},
  {num:12,words:[["Auā ua ou iloa a outou agasala ua matuā tele,", "for I known but ye all sin very great"], ["ma a outou amio e matuā leaga;", "and but ye all conduct to very evil"], ["o loo faasaua i le ua amiotonu,", "to be oppressive in the righteous"], ["ua talia se taui,", "received a a reward"], ["ma ua faafoi atu i e ua matitiva o i le faitotoa.", "and faafoi in by matitiva in the gate"]]},
  {num:13,words:[["O le mea lea e faalologo ai le ua poto i ia ona po;", "therefore to to hold one's tongue the wise in to then night"], ["auā e leaga ia ona po.", "for to evil to then night"]]},
  {num:14,words:[["Ia outou saili i le lelei,", "to ye all seek in the good"], ["a e le o le leaga,", "but by the the evil"], ["ina ia ola ai outou;", "so that life ye all"], ["ona i ai lea ia te outou o Ieova o le Atua o 'au,", "and therein unto ye all Jehovah the God I"], ["e pei ona outou fai mai ai.", "to to be broken then ye all make from"]]},
  {num:15,words:[["Ia outou 'ino'ino i le leaga,", "to ye all 'ino'ino in the evil"], ["a e loto atu i le lelei,", "but to heart in the good"], ["ma ia outou faatumau le faamasinoga i le faitotoa;", "and to ye all faatumau the judgment in the gate"], ["atonu e alofa Ieova le Atua o 'au i e ua totoe ia Iosefa.", "impers to love Jehovah the God I in by phiral of foe to Joseph"]]},
  {num:16,words:[["O le mea lea o loo faapea mai ai Ieova,", "therefore thus from Jehovah"], ["le Atua o 'au,", "God I"], ["o le Alii lava,", "the Lord indeed"], ["E pa le lauaitu i ala uma lava;", "to a wall the a weeping in arise all indeed"], ["latou te faapea ane i ala tele uma,", "them thus in arise great all"], ["Aue! aue! latou te valaau foi i lē galue i fanua ia te faanoanoa;", "alas! oh! alas! oh! them call also in not work in land unto to mourn"], ["ma e ua iloa pese e au alofa a'i,", "and by known a song to I love"], ["ia tagitu'i i latou.", "to tagitu'i them"]]},
  {num:17,words:[["E pa foi le lauaitu i tovine uma,", "to a wall also the a weeping in tovine all"], ["auā ou te ui atu ia te oe,", "for I although unto you"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:18,words:[["Talofa ia te outou o e mananao i le aso o Ieova! Se a ea lona aoga ia te outou? O le aso o Ieova,", "hello unto ye all by mananao in the day Jehovah a but to rise (as a diver to the sur- his useful unto ye all the day Jehovah"], ["o le pouliuli lea,", "the darkness"], ["a e le o le malamalama.", "but by the the light"]]},
  {num:19,words:[["E pei o le tagata ua sola ese i le leona,", "to to be broken the man flee away in the leona"], ["a ua la fetaiai ma le urosa;", "but la fetaiai and the urosa"], ["pe ulufale atu i le fale,", "or ulufale in the house"], ["ma totoo ai lona lima i le pa puipui,", "and totoo his five in the a wall a duor"], ["ona utia ai lea o ia i le gata.", "and utia he in the a snake"]]},
  {num:20,words:[["E le o le pouliuli ea le aso o Ieova,", "by the the darkness to rise (as a diver to the sur- the day Jehovah"], ["a e le malamalama;", "but by the light"], ["e pogisa lava,", "to to be quite dark indeed"], ["e leai sona pupula?", "there is not sona brightness"]]},
  {num:21,words:[["Ua ou 'ino'ino,", "I 'ino'ino"], ["ua leaga ia te au o outou tausamiga;", "evil unto I ye all tausamiga"], ["ou te le fiafia i o outou faapotopotoga.", "I the competition in ye all gathering"]]},
  {num:22,words:[["E ui ina outou au mai ia te au o taulaga mu,", "to although let ye all I from unto I offering mu"], ["ma a outou taulaga i mea e 'ai,", "and but ye all offering in thing to eat"], ["ou te le talia;", "I the received"], ["o le taulaga faafetai i a outou manu pepeti,", "the offering to tliank in but ye all animal plural of peti"], ["ou te le vaai atu i ai.", "I the to look at therein"]]},
  {num:23,words:[["Ia e ave ese ia te au le taalili o ou pese;", "to to take away unto I the resounding I a song"], ["o le leo mălie foi o au napeli ou te le faalogo ai.", "the voice mălie also I am napeli I the hearken"]]},
  {num:24,words:[["A ia tafe ifo le faamasinoga e pei o vai,", "but to to flow the judgment to to be broken water"], ["ma le amiotonu e pei o le vai e tafe tetele lava.", "and the righteous to to be broken the water to to flow great indeed"]]},
  {num:25,words:[["Le aiga o Isaraelu e,", "the family Israel by"], ["pe na outou au mai ea ia te au o taulaga,", "or ye all I from to rise (as a diver to the sur- unto I offering"], ["ma taulaga i mea e 'ai i le vao i tausaga e fagafulu?", "and offering in thing to eat in the vegetation in year by fagafulu"]]},
  {num:26,words:[["Na outou tauave lava le malumalu o lo outou Moloka,", "ye all tauave indeed the temple your moloka"], ["ma Kiuna,", "and kiuna"], ["o outou tupua,", "ye all idol"], ["o le fetu o lo outou atua na outou faia mo outou.", "the star your God ye all made for ye all"]]},
  {num:27,words:[["Ou te faatāfeaina outou i ona tala atu o Tamaseko,", "I faatāfeaina ye all in then side tamaseko"], ["o loo fetalai mai ai Ieova,", "said from Jehovah"], ["o le Atua o 'au,", "of God I"], ["o lona suafa lea.", "his name"]]},
];
renderVerseSet(amo_ch_5_Verses, 'amo-ch5-verses');

var amo_ch_6_Verses = [
  {num:1,words:[["Talofa i e o faatalanoa i Siona,", "hello in by faatalanoa in Zion"], ["ma e o nonofo faatalanoa i le mauga o Samaria,", "and by dwelling faatalanoa in the mountain Samaria"], ["e ua ta'ua i atu nuu silisili,", "by war in nation very much"], ["na ō i ai le aiga o Isaraelu.", "ō therein the family Israel"]]},
  {num:2,words:[["Ia outou o atu i Kalene,", "to ye all in kalene"], ["ma vaavaai atu,", "and vaavaai"], ["i le tou o atu ai i Amato tele;", "in the second person plural in amato great"], ["i le o ifo ai i Kata i Filisitia;", "in the in kata in Philistine"], ["e sili ea lo latou lelei i na malo,", "to most to rise (as a diver to the sur- their good in government"], ["pe sili ea ona tele o lo latou laueleele i lo outou laueleele?", "or most to rise (as a diver to the sur- then great their ground in the ye all ground"]]},
  {num:3,words:[["Talofa i e ua manatu ua mamao le aso vale,", "hello in by thought to be far ofl\" the day foolish"], ["ma faalatalata mai le nofoa o i ai le faasaua;", "and faalatalata from the a seat therein the to be oppressive"]]},
  {num:4,words:[["o e taooto i moega nifo elefane,", "who taooto in moega tooth elefane"], ["ma latou taooto i o latou moega;", "and them taooto in them moega"], ["ma aai i tamai mamoe o le lafu,", "and eat in son sheep the a herd"], ["ma tamai povi ai le fale povi;", "and son cattle the house cattle"]]},
  {num:5,words:[["o e pepese faatasi ma le leo o le napeli,", "who pepese once and the voice the napeli"], ["ma latou sauni mo i latou laaupese,", "and them he who beg^ins the game for them laaupese"], ["e pei o Tavita;", "to to be broken David"]]},
  {num:6,words:[["o e inu uaina i ipu tetele,", "who drink wine in cup great"], ["ma uu ia te i latou i uu e sili ona lelei;", "and oil unto them in oil to most then good"], ["a ua le tiga i latou ona o le malaia o Iosefa.", "but the pain them then the a calamity Joseph"]]},
  {num:7,words:[["O le mea lea e tāfea ai nei i latou,", "therefore by tāfea this them"], ["e muamua i e tāfea,", "to first in by tāfea"], ["e mavae atu le alaga fiafia o e taooto.", "to a parting the a shoulder or leg of aa ' competition by taooto"]]},
  {num:8,words:[["Ua tauto le Alii o Ieova i lona soifua,", "to take an oath the Lord Jehovah in his live"], ["o loo fetalai mai ai Ieova le Atua o 'au,", "said from Jehovah the God I"], ["Ua ou 'ino'ino i le mamalu o Iakopo,", "I 'ino'ino in the glory James"], ["ua ou 'ino'ino foi i ona maota;", "I 'ino'ino also in then the name of a tree"], ["o le mea lea ou te tuuina atu ai le aai atoa ma mea ua tumu ai.", "therefore I will give the eat together with and thing fill"]]},
  {num:9,words:[["Afai foi e totoe tagata e toatinoagafulu i le fale e tasi,", "if also to phiral of foe man by toatinoagafulu in the house by one"], ["latou te oti ai lava.", "them die indeed"]]},
  {num:10,words:[["E siitia se tasi e le uso o lona tamā,", "by siitia a one by the a relative of the same generation and gender his father"], ["o le na te susunu foi ia te ia,", "the burn also unto to"], ["e au mai ai ivi ai le fale;", "to I from bone the house"], ["na te faapea atu i le ua i mea aupito i totonu o le fale,", "thus in the in thing ^ to be in inside the house"], ["Pe ai se tasi ua i ai pea ia te oe? Ona tali atu foi lea o ia,", "or a one therein continually unto you then respond also he"], ["E leai lava.", "there is not indeed"], ["Ona faapea mai lea o ia,", "and thus from he"], ["Faalologo ia auā e le tatau ona ta'ua o le suafa o Ieova.", "to hold one's tongue to for by the to wring out then war the name Jehovah"]]},
  {num:11,words:[["Auā faauta mai ea,", "for behold from to rise (as a diver to the sur-"], ["ua poloai atu Ieova,", "command Jehovah"], ["na te taia foi le fale tele ia solo,", "taia also the house great to to move swiftly"], ["ma le fale itiiti ia lepetia.", "and the house small to lepetia"]]},
  {num:12,words:[["E taufetuli ea solofanua i le papa? pe suatia ai ea e se tasi i povi? auā ua outou liu i rosa le faamasinoga,", "by taufetuli to rise (as a diver to the sur- horse in the burster or suatia to rise (as a diver to the sur- by a one in cattle for ye all liu in rosa the judgment"], ["ma le fua o le amiotonu i laena.", "and the fruit the righteous in laena"]]},
  {num:13,words:[["O outou o e fiafia i se mea faatauvaa,", "ye all to competition in a thing faatauvaa"], ["o e faapea mai,", "who thus from"], ["Po ua le maua mai ea i lo tatou malosi o nifo mo i tatou?", "night the received from to rise (as a diver to the sur- in the us strong tooth for in us"]]},
  {num:14,words:[["A o lenei,", "but this"], ["faauta mai,", "behold from"], ["le aiga o Isaraelu e,", "the family Israel by"], ["ou te faatuina se tasi nuu,", "I built a one nation"], ["latou te fai oe mo latou fili,", "them make you for them to choose"], ["o loo fetalai mai ai Ieova le Atua o 'au;", "said from Jehovah the God I"], ["latou te faasaua ia te outou,", "them to be oppressive unto ye all"], ["e pau mai i le mea e ui atu ai i Amato,", "to to be as far as from in the thing to although in amato"], ["e pau mai i le vaitafe o le vao.", "to to be as far as from in the river the vegetation"]]},
];
renderVerseSet(amo_ch_6_Verses, 'amo-ch6-verses');

var amo_ch_7_Verses = [
  {num:1,words:[["Ua faapea ona faailoaina mai ia te au e le Alii o Ieova;", "saying and faailoaina from unto I by the Lord Jehovah"], ["faauta,", "behold"], ["na ia faatupuina o sē akerise i ona faatoa tutupu ae o le vao mulimuli;", "to faatupuina sē akerise in then faatoa bring forth but the vegetation follow after"], ["faauta foi,", "behold also"], ["o le vao mulimuli ia,", "the vegetation follow after to"], ["a ua mavae atu seleselegāmutia a le tupu.", "but a parting seleselegāmutia but the grow"]]},
  {num:2,words:[["Ona oo lea ina uma ona aai o le vao iti o le fanua,", "and oo let all then eat the vegetation iti the land"], ["ona ou faapea atu ai lea,", "and I thus"], ["Le Alii Ieova e,", "the Lord Jehovah by"], ["ou te aioi atu ia e faamagalo mai.", "I aioi to to forgive from"], ["Pe tulai ia te ai Iakopo,", "or arose up unto James"], ["auā ua vaivai lava ia?", "for weak indeed to"]]},
  {num:3,words:[["Ua salamo Ieova i lena mea;", "repent Jehovah in that thing"], ["ua faapea mai Ieova,", "saying Jehovah"], ["E le oo.", "by the oo"]]},
  {num:4,words:[["Ua faapea ona faailoaina mai ia te au e le Alii o Ieova;", "saying and faailoaina from unto I by the Lord Jehovah"], ["faauta,", "behold"], ["na valaau atu le Alii o Ieova ia tauia i le afi,", "call the Lord Jehovah to tauia in the fire"], ["i le ua faaumatia le moana tele,", "in the destroy the deep great"], ["ma faaumatia ai le tasi mea.", "and destroy the one thing"]]},
  {num:5,words:[["Ona ou fai atu lea,", "and I make"], ["Le Alii Ieova e,", "the Lord Jehovah by"], ["ou te aioi atu,", "I aioi"], ["ina soia;", "let soia"], ["pe tulai ia te ai Iakopo,", "or arose up unto James"], ["auā ua vaivai lava ia?", "for weak indeed to"]]},
  {num:6,words:[["Ua salamo Ieova i lenei mea;", "repent Jehovah in this thing"], ["ua faapea mai le Alii o Ieova,", "saying the Lord Jehovah"], ["E le oo foi lenei mea.", "by the oo also this thing"]]},
  {num:7,words:[["Sa faapea ona faailoaina mai e ia ia te au;", "saying and faailoaina from by him unto I"], ["faauta,", "behold"], ["ua tu le Alii i le aupa tu sa'o,", "stand the Lord in the aupa stand the appointed portion of"], ["ua i ai i lona aao o le fua faatautau.", "therein in his hand (extended) the fruit faatautau"]]},
  {num:8,words:[["Ona fetalai mai lea o Ieova ia te au,", "and said from Jehovah unto I"], ["Amosa e,", "amosa by"], ["se a ea se mea ua e iloa? I le ua ou faapea atu,", "a but to rise (as a diver to the sur- a thing to known in the I thus"], ["O le fua faatautau.", "the fruit faatautau"], ["Ona fetalai mai ai lea o le Alii,", "and said from the Lord"], ["Faauta,", "behold"], ["ou te tuu se fua faatautau i totonu o lo'u nuu o Isaraelu,", "I put a fruit faatautau in inside my nation Israel"], ["ou te le toe sopoia lava.", "I the again sopoia indeed"]]},
  {num:9,words:[["E faatafunaina mea maualuluga a Isaako,", "by faatafunaina thing maualuluga but Isaac"], ["e faatafunaina foi malumalu o Isaraelu;", "by faatafunaina also temple Israel"], ["ou te tulai atu ma le pelu i le aiga o Ierepoamo.", "I arose up and the a sword in the family ierepoamo"]]},
  {num:10,words:[["Ona alu lea o le feau a Amasia le ositaulaga a Peteli ia Ierepoamo le tupu o Isaraelu,", "And he went the feau but amasia the high priest but peteli to ierepoamo the grow Israel"], ["ua faapea atu,", "saying"], ["Ua fouvale Amosa ia te oe i le aiga o Isaraelu,", "to rebel amosa unto you in the family Israel"], ["ua le lavā onosai le nuu i ana upu uma.", "the lavā onosai the nation in his word all"]]},
  {num:11,words:[["Auā ua faapea mai Amosa,", "for thus from amosa"], ["E maliu Ierepoamo i le pelu,", "to die ierepoamo in the a sword"], ["e matuā ta'ita'iina Isaraelu faatagata o taua ai lo latou lava laueleele.", "to very ta'ita'iina Israel faatagata war their indeed ground"]]},
  {num:12,words:[["Ua faapea mai foi Amasia ia Amosa,", "saying also amasia to amosa"], ["Le tagata vaai e,", "the man to look at by"], ["alu ia,", "go to"], ["ina sola oe i le nuu o Iuta,", "let flee you in the nation Judas"], ["ma e 'ai i lea mea,", "and to eat in thing"], ["ma vavalo ai.", "and prophesy"]]},
  {num:13,words:[["A e aua e te toe vavalo i Peteli;", "but to for by again prophesy in peteli"], ["auā o le malumalu lea o le tupu,", "for the temple the grow"], ["o le maota foi o le tupu.", "the the name of a tree also the grow"]]},
  {num:14,words:[["Ona tali atu lea o Amosa ua faapea atu ia Amasia,", "and respond amosa thus to amasia"], ["Ou te le se perofeta a'u nei,", "I the a prophet I this"], ["ou te le se atalii foi o se perofeta;", "I the a son also a prophet"], ["a o le fagamanu a'u,", "but the fagamanu I"], ["ma le galue i sukamoru.", "and the work in sukamoru"]]},
  {num:15,words:[["A ua avea a'u e Ieova sa ou mulimuli i le lafu mamoe,", "but become I to Jehovah I follow after in the a herd sheep"], ["ma ua faapea mai Ieova ia te au,", "and thus from Jehovah unto I"], ["Alu ia,", "go to"], ["ina e vavalo i lo'u nuu o Isaraelu.", "let to prophesy in my nation Israel"]]},
  {num:16,words:[["O lenei,", "this"], ["ina e faalogo mai ia i le afioga a Ieova.", "let to hearken from to in the a word but Jehovah"], ["Ua e fai mai,", "to make from"], ["aua le vavalo ia Isaraelu,", "for the prophesy to Israel"], ["aua foi le tautala atu i le aiga o Isaako.", "for also the to talk in the family Isaac"]]},
  {num:17,words:[["O le mea lea o loo faapea mai ai Ieova,", "therefore thus from Jehovah"], ["E avea lau avā ma fafine faitaaga i le aai,", "to become your wife and woman fornication in the eat"], ["e pauu foi i le pelu o ou atalii ma ou afafine,", "to fell also in the a sword I son and I daughter"], ["e vaevaeina i le fua lou fanua;", "by vaevaeina in the fruit your land"], ["e oti foi oe i le nuu leaga;", "to die also you in the nation evil"], ["e matuā tāfea Isaraelu ai lona laueleele.", "to very tāfea Israel his ground"]]},
];
renderVerseSet(amo_ch_7_Verses, 'amo-ch7-verses');

var amo_ch_8_Verses = [
  {num:1,words:[["Ua faapea ona faaalia mai ia te au e le Alii o Ieova;", "saying and faaalia from unto I by the Lord Jehovah"], ["faauta mai,", "behold from"], ["o le ato fua otatā.", "the to thatch fruit otatā"]]},
  {num:2,words:[["Ona faapea mai lea o ia,", "and thus from he"], ["Amosa e,", "amosa by"], ["pe se a ea se mea ua e iloa? I le ua ou tali atu,", "or a but to rise (as a diver to the sur- a thing to known in the I respond"], ["O le ato fua otatā.", "the to thatch fruit otatā"], ["Ona faapea mai ai lea o Ieova ia te au,", "and thus from Jehovah unto I"], ["Ua oo mai le iuga i lo'u nuu o Isaraelu,", "it came to pass from the iuga in my nation Israel"], ["ou te le toe sopoia lava.", "I the again sopoia indeed"]]},
  {num:3,words:[["E fai ma uio pese o le maota i lea aso,", "to be uio a song the the name of a tree in day"], ["o loo fetalai mai ai le Alii o Ieova;", "said from the Lord Jehovah"], ["e i ai i mea uma tino o tagata oti e tele,", "by therein in thing all body man die to great"], ["e lafoaiina ma le le feganavai.", "by lafoaiina and the the feganavai"]]},
  {num:4,words:[["Ia outou faalogologo i lenei mea,", "to ye all listen in this thing"], ["o outou o e faasaua i e matitiva,", "ye all to to be oppressive in by matitiva"], ["ina ia faaumatia lava le au matitiva o le nuu,", "so that destroy indeed the I matitiva the nation"]]},
  {num:5,words:[["o loo faapea mai,", "thus from"], ["Pe mavae atu afea le masina faatoa vaaia ia tatou faatau ai saito? pe mavae afea foi le sapati ia tatou tatalaina atu ai saito? o loo faaitiitiina foi le efa,", "or a parting when ? the moon faatoa seen to us equally wheat or a parting when ? also the sapati to us tatalaina wheat faaitiitiina also the efa"], ["ma faateleina le sekeli,", "and faateleina the sekeli"], ["o loo fai fua faaletatau e pepelo ai.", "make fruit faaletatau to false"]]},
  {num:6,words:[["Tatou te faatau foi tagata matitiva i ario,", "us equally also man matitiva in silver"], ["ma le tagata vaivai i seevae e lua;", "and the man weak in a shoe by two"], ["tatou te faatau atu foi saito leaga.", "us equally also wheat evil"]]},
  {num:7,words:[["Ua tauto Ieova i le mamalu o Iakopo,", "to take an oath Jehovah in the glory James"], ["E le galo lava ia te au e faavavau a latou galuega uma.", "by the galo indeed unto I to a stone connected with but them work all"]]},
  {num:8,words:[["E le gatete ea le laueleele ona o lenei mea,", "by the gatete to rise (as a diver to the sur- the ground then this thing"], ["ma faanoanoa ai i latou uma o e nonofo ai? e le matuā alu ae ea e pei o se vaitafe? e le lafoaiina ea ia ma lofia,", "and to mourn them all to dwelling by the very go but to rise (as a diver to the sur- to to be broken a river by the lafoaiina to rise (as a diver to the sur- to and lofia"], ["e pei o le vaitafe o Aikupito?", "to to be broken the river Egypt"]]},
  {num:9,words:[["O loo fetalai mai le Alii o Ieova,", "said from the Lord Jehovah"], ["O lea aso ou te faagotoina ai le la i le aoauli,", "therefore day I faagotoina the la in the aoauli"], ["ou te faapouliuligia foi le lalolagi i le ao malamalama.", "I faapouliuligia also the earth in the day light"]]},
  {num:10,words:[["Ou te liu i faanoanoaga a outou tausamiga,", "I liu in grief but ye all tausamiga"], ["ou te liliu foi o outou pese uma i auega;", "I turned also ye all a song all in auega"], ["ou te faalavalava foi sulugatiti uma i le ie talatala,", "I a weal also the place where the all in the faamaise to untie"], ["o ulu foi o tagata uma e selemamaina ia;", "head also man all by selemamaina to"], ["ou te faia lea mea ia pei o le pese e aualofa a'i ona o le atalii e toatasi,", "I made thing to to be broken the a song to a keepsake then the son to one One"], ["o lona iuga foi,", "his iuga also"], ["o le aso vale lava lea.", "the day foolish indeed"]]},
  {num:11,words:[["O loo faapea mai le Alii o Ieova,", "thus from the Lord Jehovah"], ["Faauta,", "behold"], ["e oo mai aso ou te tuuina atu ai le oge i le nuu;", "it shall come to pass from day I given the a famine in the nation"], ["e le se oge i mea e 'ai,", "by the a a famine in thing to eat"], ["po o se gālala i le fia inu vai,", "night a gālala in the want to do something drink water"], ["a o le oge i le faalogologo i afioga a Ieova.", "but the a famine in the listen in a word but Jehovah"]]},
  {num:12,words:[["Latou te feoai e pau mai i le tasi vasa e oo atu i le isi vasa,", "them feoai to to be as far as from in the one ocean by oo in the other ocean"], ["e pau mai i le itu i matu e oo atu i le itu i sasae latou te feoai ai e sailiili atu ai le afioga a Ieova,", "to to be as far as from in the itu in a northerly gale by oo in the itu in to tear them feoai by sailiili the a word but Jehovah"], ["a e le maua.", "but by the received"]]},
  {num:13,words:[["E vaivai i le fia inu i lea aso o taupou lalelei atoa ma taulelea.", "to weak in the want to do something drink in day taupou lalelei together with and taulelea"]]},
  {num:14,words:[["O i latou o e tauto i le agasala a Samaria,", "them to to take an oath in the sin but Samaria"], ["ma faapea atu,", "and thus"], ["Tanu e,", "to bury by"], ["ua soifua lou atua;", "live your God"], ["i le ma lea,", "in the and"], ["Ua ola le ala o Peresepa;", "life the arise peresepa"], ["e pauu lava i latou,", "to fell indeed them"], ["latou te le toe tutulai.", "them the again tutulai"]]},
];
renderVerseSet(amo_ch_8_Verses, 'amo-ch8-verses');

var amo_ch_9_Verses = [
  {num:1,words:[["Na ou iloa le Alii,", "I known the Lord"], ["o loo tu i luga o le fata faitaulaga;", "stand in above the altar priest"], ["ma ua faapea mai o ia,", "and thus from he"], ["Ina ta ia le laau faalava o le faitotoa,", "let a stroke to the tree faalava the gate"], ["ia luluina ai o pou;", "to luluina pou"], ["ia gaugau ai i luga o latou ulu uma;", "to gaugau in above them head all"], ["ou te fasioti foi i le pelu e ua totoe o i latou;", "I killed also in the a sword by phiral of foe them"], ["ai so latou e sola e le sao ia,", "so them to flee by the the appointed portion of to"], ["ai so latou e sola ese e le laveaiina o ia.", "so them to flee away by the delivered he"]]},
  {num:2,words:[["Afai latou te eli ia oo i seoli,", "if them eli to oo in seoli"], ["e aumaia i latou e lo'u lima ai lea mea;", "to bring here them to my five thing"], ["afai latou te feaei i le lagi,", "if them feaei in the heaven"], ["ou te aveina ifo i latou ai lea mea.", "I aveina them thing"]]},
  {num:3,words:[["Afai latou te lalafi i le tumutumu o Karamelu,", "if them lalafi in the tumutumu karamelu"], ["ou te suesue ai,", "I suesue"], ["ma au mai ai i latou ai lea mea;", "and I from them thing"], ["afai foi e lalafi i latou ai o'u luma i le loloto o le sami,", "if also by lalafi them I before in the deep the sea"], ["ou te fai atu ai i le gata,", "I make in the a snake"], ["ona utia ai lea o i latou e ia.", "and utia them by him"]]},
  {num:4,words:[["Afai foi e tāfea i latou i luma o e o fai i latou ma fili,", "if also by tāfea them in before by make them and to choose"], ["ou te fai atu ai i le pelu,", "I make in the a sword"], ["ona fasiotia ai lea o i latou;", "and slain them"], ["ou te faasaga atu i ai,", "I toward therein"], ["ina ia malaia o i latou,", "so that a calamity them"], ["a e le ona ia manuia.", "but by the then to peace"]]},
  {num:5,words:[["O le Alii,", "the Lord"], ["o Ieova o 'au o ia o le pai atu i le laueleele,", "Jehovah I he the pie in the ground"], ["ona liu suāvai ai lea,", "and liu suāvai"], ["e faanoanoa foi i latou uma o e nonofo ai;", "to to mourn also them all to dwelling"], ["e matuā alu ae e pei o se vaitafe,", "to very go but to to be broken a river"], ["e lofia o ia e pei o le vaitafe o Aikupito.", "by lofia he to to be broken the river Egypt"]]},
  {num:6,words:[["O ia lava o le na te faia ona afioaga i le lagi,", "he indeed the made then afioaga in the heaven"], ["ma na faavaeina lana faaputugāmea i le lalolagi;", "and faavaeina his faaputugāmea in the earth"], ["o le na te valaauina i le suāsami o le sami,", "the called in the suāsami the sea"], ["ma faamaligi ai i le fogāeleele;", "and faamaligi in the face of the earth"], ["o Ieova,", "Jehovah"], ["o lona suafa lea.", "his name"]]},
  {num:7,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["Le fanauga a Isaraelu e,", "the children but Israel by"], ["e le ua pei o tagata Aitiope ea outou ia te au? Pe na le aveina ae Isaraelu e a'u ai le nuu o Aikupito? o Filisitia foi ai Kafetori,", "by the to be broken man aitiope to rise (as a diver to the sur- ye all unto I or the aveina but Israel to I the nation Egypt Philistine also kafetori"], ["ma Suria ai Kira?", "and suria kira"]]},
  {num:8,words:[["Faauta,", "behold"], ["ua faasaga fofoga o le Alii o Ieova i le malo amio leaga,", "toward face the Lord Jehovah in the government conduct evil"], ["ou te faaumatia ai ai le fogāeleele;", "I destroy the face of the earth"], ["na o le aiga o Iakopo ou te le matuā faaumatia,", "the family James I the very destroy"], ["o loo fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:9,words:[["Faauta mai foi,", "behold from also"], ["ou te fai atu,", "I make"], ["ou te luluina foi le aiga o Isaraelu i nuu uma,", "I luluina also the family Israel in nation all"], ["e pei ona luluina o saito i le lulu,", "to to be broken then luluina wheat in the barn owl"], ["a e le paū sina fua i le eleele.", "but by the paū white fruit in the earth"]]},
  {num:10,words:[["E oti i le pelu o i latou uma o lo'u nuu o e agasala,", "to die in the a sword them all my nation to sin"], ["o e faapea ane,", "who thus"], ["E le aulia mai le malaia,", "by the aulia from the a calamity"], ["pe maua mai i tatou.", "or received from in us"]]},
  {num:11,words:[["O le aso lea ou te faatuina ai le fale apitaga o Tavita ua paū;", "the day I built the house a tempoiary David paū"], ["ou te pupuni i ana mea ua lepetia;", "I shut in his thing lepetia"], ["o ana mea foi ua solo ou te atiina ae,", "his thing also to move swiftly I atiina but"], ["ou te atiina ae e pei ona faia i ona po anamua.", "I atiina but to to be broken then made in then night anamua"]]},
  {num:12,words:[["Ina ia fai mo latou tofi e ua totoe o Etoma,", "so that make for them appoint by phiral of foe Edom"], ["atoa ma nuu uma,", "and nation all"], ["o e ua faaigoaina i lo'u igoa,", "who faaigoaina in my name"], ["o loo fetalai mai ai Ieova o le na te faia lenei mea.", "said from Jehovah the made this thing"]]},
  {num:13,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["Faauta,", "behold"], ["e oo mai ona aso e aulia ai lē suatia le fanua i le selesele saito,", "it shall come to pass from then day by aulia not suatia the land in the an evenly cut head of wheat"], ["ma lē solivine i le lulu saito;", "and not solivine in the barn owl wheat"], ["e tautulu mauga i le suāvine,", "by tautulu mountain in the suāvine"], ["e tafea ai mea maupuepue uma.", "to to be carried away (as by thing maupuepue all"]]},
  {num:14,words:[["Ou te faafoisia mai le tafeaga o lo'u nuu o Isaraelu,", "I faafoisia from the exiles in wa^ my nation Israel"], ["ona latou faatuina ai lea o aai ua faatafunaina,", "and them built eat faatafunaina"], ["ma nonofo ai;", "and dwelling"], ["latou te totōina foi tovine,", "them totōina also tovine"], ["ma inu uaina ai;", "and drink wine"], ["latou te fai foi faatoaga,", "them make also faatoaga"], ["ma aai ai ona fua.", "and eat then fruit"]]},
  {num:15,words:[["Ou te totōina i latou i lo latou laueleele;", "I totōina them in the them ground"], ["e le toe liaiina i latou ai lo latou laueleele na ou foaiina atu ai ia te i latou,", "by the again liaiina them their ground I given unto them"], ["o loo fetalai mai ai Ieova lou Atua.", "said from Jehovah your God"]]},
];
renderVerseSet(amo_ch_9_Verses, 'amo-ch9-verses');

})();