(function() {
var af_ch_1_Verses = [
  {num:1,words:[["Matou te talitonu i le Atua ,", "We believe in God ,"], ["le Tamā Faavavau,", "the Eternal Father,"], ["ma Lona Alo ,", "and in His Son ,"], ["o Iesu Keriso,", "Jesus Christ,"], ["ma le Agaga Paia.", "and in the Holy Ghost ."]]},
  {num:2,words:[["Matou te talitonu o le a faasalaina tagata ona o a latou lava agasala,", "We believe that men will be punished for their own sins,"], ["ae lē ona o le solitulafono a Atamu.", "and not for Adam’s transgression."]]},
  {num:3,words:[["Matou te talitonu e ala i le Togiola a Keriso,", "We believe that through the Atonement of Christ,"], ["e mafai ai ona faaolaina tagata uma,", "all mankind may be saved ,"], ["e ala i le usiusitai i tulafono ma sauniga o le Talalelei.", "by obedience to the laws and ordinances of the Gospel."]]},
  {num:4,words:[["Matou te talitonu o uluai mataupu autu ma sauniga nei o le Talalelei:", "We believe that the first principles and ordinances of the Gospel are:"], ["muamua,", "first,"], ["Faatuatua i le Alii o Iesu Keriso;", "Faith in the Lord Jesus Christ;"], ["o lona lua,", "second,"], ["Salamo ;", "Repentance ;"], ["o lona tolu,", "third,"], ["Papatisoga e ala i le faatofuina mo le faamagaloga o agasala;", "Baptism by immersion for the remission of sins;"], ["o lona fa,", "fourth,"], ["Faaeega o lima mo le meaalofa o le Agaga Paia.", "Laying on of hands for the gift of the Holy Ghost."]]},
  {num:5,words:[["Matou te talitonu e ao ina valaauina se tagata e le Atua,", "We believe that a man must be called of God,"], ["e ala i le valoaga ,", "by prophecy ,"], ["ma ala i le faaeega o lima o i latou o e o i ai le pule ,", "and by the laying on of hands by those who are in authority ,"], ["e tala'i atu ai le Talalelei ma faia sauniga o i ai.", "to preach the Gospel and administer in the ordinances thereof."]]},
  {num:6,words:[["Matou te talitonu i le faatulagaga lava lea sa i ai i le Ekalesia Anamua,", "We believe in the same organization that existed in the Primitive Church,"], ["e pei o,", "namely,"], ["aposetolo ,", "apostles,"], ["perofeta ,", "prophets ,"], ["epikopo ,", "pastors ,"], ["aoao,", "teachers ,"], ["tagata folafola le talalelei,", "evangelists ,"], ["ma isi tofiga faapena.", "and so forth."]]},
  {num:7,words:[["Matou te talitonu i le meaalofa o gagana ,", "We believe in the gift of tongues ,"], ["valoaga ,", "prophecy ,"], ["faaaliga ,", "revelation ,"], ["faaaliga vaaia,", "visions ,"], ["faamaloloina o ma'i,", "healing ,"], ["faamatalaga o gagana,", "interpretation of tongues,"], ["ma isi mea faapena.", "and so forth."]]},
  {num:8,words:[["Matou te talitonu o le Tusi Paia o le afioga ia a le Atua e tusa ma mea ua tonu ona faaliliuina;", "We believe the Bible to be the word of God as far as it is translated correctly ;"], ["matou te talitonu foi o le Tusi a Mamona o le afioga ia a le Atua.", "we also believe the Book of Mormon to be the word of God."]]},
  {num:9,words:[["Matou te talitonu i mea uma na faaali mai e le Atua,", "We believe all that God has revealed ,"], ["mea uma ua ia faaali mai nei,", "all that He does now reveal,"], ["ma matou te talitonu foi o le a ia faaali mai le tele o mea silisili ma le tāua tau i le Malo o le Atua i le lumanai.", "and we believe that He will yet reveal many great and important things pertaining to the Kingdom of God."]]},
  {num:10,words:[["Matou te talitonu i le faapotopotoina moni o Isaraelu ma le toefuataiga mai o Ituaiga e Sefulu;", "We believe in the literal gathering of Israel and in the restoration of the Ten Tribes ;"], ["ma o le a faatuina Siona (le Ierusalema Fou) i luga o le konetineta o Amerika;", "that Zion (the New Jerusalem) will be built upon the American continent;"], ["o le a nofotupu lava Keriso i le lalolagi;", "that Christ will reign personally upon the earth;"], ["ma,", "and,"], ["o le a faafouina le lalolagi ma maua lona mamalu faaparataiso .", "that the earth will be renewed and receive its paradisiacal glory ."]]},
  {num:11,words:[["Matou te ta'utino atu ua ia i matou le aiā tatau matou te tapuai atu ai i le Atua Mamana e tusa ai ma o matou lava lotofuatiaifo ,", "We claim the privilege of worshiping Almighty God according to the dictates of our own conscience ,"], ["ma ua matou tuuina atu foi lea lava aiā tatau i tagata uma,", "and allow all men the same privilege,"], ["e faitalia i latou, pe faapefea,", "let them worship how,"], ["po o fea,", "where,"], ["po o le a foi le mea latou te tapuai atu i ai.", "or what they may."]]},
  {num:12,words:[["Matou te talitonu i le usiusitai i tupu,", "We believe in being subject to kings ,"], ["peresitene,", "presidents,"], ["faipule,", "rulers,"], ["ma faamasino,", "and magistrates,"], ["i le usiusitai,", "in obeying ,"], ["faamamaluina,", "honoring,"], ["ma le lagolagoina o le tulafono .", "and sustaining the law ."]]},
  {num:13,words:[["Matou te talitonu i le faamaoni ,", "We believe in being honest ,"], ["amiotonu,", "true,"], ["nofomama ,", "chaste ,"], ["agalelei,", "benevolent ,"], ["amiomama,", "virtuous,"], ["ma le faia o mea lelei i tagata uma; e moni,", "and in doing good to all men;"], ["e mafai ona matou faapea atu,", "indeed,"], ["ua matou mulimuli i le apoapoaiga a Paulo—Matou te talitonu i mea uma,", "we may say that we follow the admonition of Paul—We believe all things,"], ["matou te faamoemoe i mea uma,", "we hope all things,"], ["ua uma ona matou onosai i mea e tele,", "we have endured many things,"], ["ma ua faamoemoe o le a mafai ona matou onosai i mea uma.", "and hope to be able to endure all things."], ["Afai o i ai nisi mea e mamā ,", "If there is anything virtuous ,"], ["matagofie,", "lovely ,"], ["pe logoleleia pe tauleleia,", "or of good report or praiseworthy,"], ["matou te saili atu i nei mea.", "we seek after these things."], ["Iosefa Samita.", "Joseph Smith."]]},
];
renderVerseSet(af_ch_1_Verses, 'af-ch1-verses');

})();