(function() {
var af_ch_1_Verses = [
  {num:1,words:[["Matou te talitonu", "we (excl) believe"], ["i le Atua ,", "in the God"], ["le Tamā Faavavau,", "the father a stone connected with"], ["ma Lona Alo ,", "and his Son"], ["o Iesu Keriso,", "Jesus Christ"], ["ma le Agaga Paia.", "and the Holy Spirit"]]},
  {num:2,words:[["Matou te talitonu", "we (excl) believe"], ["o le a faasalaina tagata", "what faasalaina man"], ["ona o", "because of"], ["a latou lava agasala,", "but they indeed sin"], ["ae lē", "but not"], ["ona o le solitulafono", "because of the transgression"], ["a Atamu.", "of Adam"]]},
  {num:3,words:[["Matou te talitonu", "we (excl) believe"], ["e ala", "to way"], ["i le Togiola", "in the atonement"], ["a Keriso,", "of Christ"], ["e mafai ai", "it is possible"], ["ona faaolaina tagata uma,", "and saved alive man all"], ["e ala", "to way"], ["i le usiusitai", "in the obeyed"], ["i tulafono", "in law"], ["ma sauniga", "and preparation"], ["o le Talalelei.", "the gospel"]]},
  {num:4,words:[["Matou te talitonu o uluai mataupu autu", "we (excl) believe first chapter autu"], ["ma sauniga nei", "and preparation this"], ["o le Talalelei:", "the gospel"], ["muamua,", "first"], ["Faatuatua i le Alii o Iesu Keriso;", "faith in the Lord Jesus Christ"], ["o lona lua,", "his two"], ["Salamo ;", "repent"], ["o lona tolu,", "his three"], ["Papatisoga e ala", "baptism to way"], ["i le faatofuina", "in the faatofuina"], ["mo le faamagaloga o agasala;", "for the faamagaloga sin"], ["o lona fa,", "his four"], ["Faaeega o lima", "faaeega five"], ["mo le meaalofa", "for the meaalofa"], ["o le Agaga Paia.", "the Holy Spirit"]]},
  {num:5,words:[["Matou te talitonu", "we (excl) believe"], ["e ao ina", "must needs"], ["valaauina se tagata", "called a man"], ["e le Atua,", "God"], ["e ala", "to way"], ["i le valoaga ,", "in the a prediction"], ["ma ala", "and way"], ["i le faaeega o lima", "in the faaeega five"], ["o i latou", "them"], ["o e o", "who"], ["i ai", "therein"], ["le pule ,", "the rule"], ["e tala'i atu ai", "to preach"], ["le Talalelei", "the gospel"], ["ma faia sauniga o", "and made preparation"], ["i ai.", "therein"]]},
  {num:6,words:[["Matou te talitonu", "we (excl) believe"], ["i le faatulagaga lava lea", "in the faatulagaga indeed"], ["sa i ai", "therein"], ["i le Ekalesia Anamua,", "in the church ancient"], ["e pei o,", "to like"], ["aposetolo ,", "apostle"], ["perofeta ,", "prophet"], ["epikopo ,", "bishop"], ["aoao,", "excellent"], ["tagata folafola", "man to spread out"], ["le talalelei,", "the gospel"], ["ma isi tofiga faapena.", "and other tofiga likewise"]]},
  {num:7,words:[["Matou te talitonu", "we (excl) believe"], ["i le meaalofa o gagana ,", "in the meaalofa language"], ["valoaga ,", "a prediction"], ["faaaliga ,", "revelation"], ["faaaliga vaaia,", "revelation seen"], ["faamaloloina o ma'i,", "faamaloloina from"], ["faamatalaga o gagana,", "faamatalaga language"], ["ma isi mea faapena.", "and other thing likewise"]]},
  {num:8,words:[["Matou te talitonu", "we (excl) believe"], ["o le Tusi Paia", "the the scriptures"], ["o le afioga ia", "the a word to"], ["a le Atua e", "of God by"], ["tusa ma mea", "according to and thing"], ["ua tonu", "right"], ["ona faaliliuina;", "and faaliliuina"], ["matou te talitonu foi", "we (excl) believe also"], ["o le Tusi", "the book"], ["a Mamona", "of Mormon"], ["o le afioga ia", "the a word to"], ["a le Atua.", "of God"]]},
  {num:9,words:[["Matou te talitonu", "we (excl) believe"], ["i mea uma", "in all things"], ["na faaali mai", "revealed"], ["e le Atua,", "God"], ["mea uma", "all things"], ["ua ia faaali", "to appear"], ["mai nei,", "from this"], ["ma matou te talitonu foi", "and we (excl) believe also"], ["o le a ia", "what to"], ["faaali mai", "revealed"], ["le tele o mea silisili", "many things very much"], ["ma le tāua tau", "and the tāua season"], ["i le Malo", "in the government"], ["o le Atua", "of God"], ["i le lumanai.", "in the lumanai"]]},
  {num:10,words:[["Matou te talitonu", "we (excl) believe"], ["i le faapotopotoina moni o Isaraelu", "in the gathered together true Israel"], ["ma le toefuataiga", "and the restoration"], ["mai o Ituaiga", "from tribe"], ["e Sefulu;", "by ten"], ["ma o le a faatuina Siona", "and will built Zion"], ["(le Ierusalema Fou)", "the Jerusalem new"], ["i luga", "in above"], ["o le konetineta o Amerika;", "the konetineta amerika"], ["o le a nofotupu lava Keriso", "what nofotupu indeed Christ"], ["i le lalolagi;", "on the earth"], ["ma,", "and"], ["o le a faafouina", "what faafouina"], ["le lalolagi", "the earth"], ["ma maua lona mamalu faaparataiso .", "and received his glory faaparataiso"]]},
  {num:11,words:[["Matou te ta'utino atu", "we (excl) to hang near the body"], ["ua ia", "to"], ["i matou", "in we (excl)"], ["le aiā tatau matou", "the aiā to wring out we (excl)"], ["te tapuai atu ai", "tapuai"], ["i le Atua Mamana", "in the God mamana"], ["e tusa ai", "to according to"], ["ma o matou lava lotofuatiaifo ,", "and we (excl) indeed lotofuatiaifo"], ["ma ua matou tuuina atu", "and we (excl) given"], ["foi lea lava aiā tatau", "also indeed aiā to wring out"], ["i tagata uma,", "in man all"], ["e faitalia", "to as I"], ["i latou,", "them"], ["pe faapefea,", "whether how ?"], ["po o fea,", "night fea"], ["po o le a foi", "night will also"], ["le mea latou te tapuai atu", "the thing they tapuai"], ["i ai.", "therein"]]},
  {num:12,words:[["Matou te talitonu", "we (excl) believe"], ["i le usiusitai", "in the obeyed"], ["i tupu,", "in king"], ["peresitene,", "President"], ["faipule,", "a councillor"], ["ma faamasino,", "and a judge"], ["i le usiusitai,", "in the obeyed"], ["faamamaluina,", "faamamaluina"], ["ma le lagolagoina", "and the lagolagoina"], ["o le tulafono .", "the law"]]},
  {num:13,words:[["Matou te talitonu", "we (excl) believe"], ["i le faamaoni ,", "in the faithful"], ["amiotonu,", "righteous"], ["nofomama ,", "nofomama"], ["agalelei,", "treated well"], ["amiomama,", "amiomama"], ["ma le faia o mea lelei", "and the made thing good"], ["i tagata uma;", "in man all"], ["e moni,", "verily/truly"], ["e mafai ona", "could"], ["matou faapea atu,", "we (excl) thus"], ["ua matou mulimuli", "we (excl) follow after"], ["i le apoapoaiga", "in the apoapoaiga"], ["a Paulo—Matou te talitonu", "of paulo—matou believe"], ["i mea uma,", "in all things"], ["matou te faamoemoe", "we (excl) to expect"], ["i mea uma,", "in all things"], ["ua uma ona", "finished"], ["matou onosai", "we (excl) patience"], ["i mea e tele,", "in great things"], ["ma ua faamoemoe", "and to expect"], ["o le a mafai ona", "what able then"], ["matou onosai", "we (excl) patience"], ["i mea uma.", "in all things"], ["Afai o", "if"], ["i ai nisi mea", "therein some thing"], ["e mamā ,", "to clean"], ["matagofie,", "beautiful"], ["pe logoleleia", "whether logoleleia"], ["pe tauleleia,", "whether tauleleia"], ["matou te saili atu", "we (excl) seek"], ["i nei mea.", "these things"], ["Iosefa Samita.", "Joseph Smith"]]},
];
renderVerseSet(af_ch_1_Verses, 'af-ch1-verses');

})();