(function() {
var _af_ch_1_Verses = [
  {num:1,words:[["Matou te talitonu", "we (excl) believe"], ["i le Atua ,", "in the God"], ["le Tamā Faavavau,", "the father everlasting"], ["ma Lona Alo ,", "and his Son"], ["o Iesu Keriso,", "Jesus Christ"], ["ma le Agaga Paia.", "and the Holy Spirit"]]},
  {num:2,words:[["Matou te talitonu", "we (excl) believe"], ["o le a faasalaina tagata", "what punished man"], ["ona o", "because of"], ["a latou lava agasala,", "but they indeed sin"], ["ae lē", "but not"], ["ona o le solitulafono", "because of the transgression"], ["a Atamu.", "of Adam"]]},
  {num:3,words:[["Matou te talitonu", "we (excl) believe"], ["e ala i le Togiola", "through the atonement"], ["a Keriso,", "of Christ"], ["e mafai ai", "it is possible"], ["ona faaolaina tagata uma,", "and saved alive man all"], ["e ala i le usiusitai", "through the obeyed"], ["i tulafono", "in law"], ["ma sauniga", "and preparation"], ["o le Talalelei.", "the gospel"]]},
  {num:4,words:[["Matou te talitonu o uluai mataupu autu", "we (excl) believe of first chapter autu"], ["ma sauniga nei", "and preparation this"], ["o le Talalelei:", "the gospel"], ["muamua,", "first"], ["Faatuatua i le Alii o Iesu Keriso;", "faith in the Lord of Jesus Christ"], ["o lona lua,", "his two"], ["Salamo ;", "repent"], ["o lona tolu,", "his three"], ["Papatisoga e ala i le faatofuina", "baptism through the make was without form"], ["mo le faamagaloga o agasala;", "for the faamagaloga of sin"], ["o lona fa,", "his four"], ["Faaeega o lima", "Faaeega of five"], ["mo le meaalofa o le Agaga Paia.", "for the gift the Holy Spirit"]]},
  {num:5,words:[["Matou te talitonu", "we (excl) believe"], ["e ao ina", "must needs"], ["valaauina se tagata", "called a man"], ["e le Atua,", "God"], ["e ala i le valoaga ,", "through the a prediction"], ["ma ala i le faaeega", "and way in the faaeega"], ["o lima o", "five of"], ["i latou", "them"], ["o e o", "who"], ["i ai le pule ,", "therein the rule"], ["e tala'i atu ai le Talalelei", "to preach the gospel"], ["ma faia sauniga o", "and made preparation of"], ["i ai.", "therein"]]},
  {num:6,words:[["Matou te talitonu", "we (excl) believe"], ["i le faatulagaga lava lea", "in the order indeed"], ["sa i ai", "therein"], ["i le Ekalesia Anamua,", "in the church ancient"], ["e pei o,", "to like of"], ["aposetolo ,", "apostle"], ["perofeta ,", "prophet"], ["epikopo ,", "bishop"], ["aoao,", "excellent"], ["tagata folafola", "man to spread out"], ["le talalelei,", "the gospel"], ["ma isi tofiga faapena.", "and other tofiga likewise"]]},
  {num:7,words:[["Matou te talitonu", "we (excl) believe"], ["i le meaalofa o gagana ,", "in the gift of language"], ["valoaga ,", "a prediction"], ["faaaliga ,", "revelation"], ["faaaliga vaaia,", "revelation seen"], ["faamaloloina o ma'i,", "healed of from"], ["faamatalaga o gagana,", "faamatalaga of language"], ["ma isi mea faapena.", "and other thing likewise"]]},
  {num:8,words:[["Matou te talitonu", "we (excl) believe"], ["o le Tusi Paia", "the the scriptures"], ["o le afioga ia", "the word (divine) to"], ["a le Atua e tusa ma mea", "of God according to thing"], ["ua tonu", "right"], ["ona faaliliuina;", "and to turn round"], ["matou te talitonu foi", "we (excl) believe also"], ["o le Tusi", "the book"], ["a Mamona", "of Mormon"], ["o le afioga ia", "the word (divine) to"], ["a le Atua.", "of God"]]},
  {num:9,words:[["Matou te talitonu", "we (excl) believe"], ["i mea uma", "in all things"], ["na faaali mai e le Atua,", "revealed God"], ["mea uma", "all things"], ["ua ia faaali mai nei,", "to revealed this"], ["ma matou te talitonu foi", "and we (excl) believe also"], ["o le a ia", "what to"], ["faaali mai le tele o mea silisili", "revealed many things very much"], ["ma le tāua tau", "and the tāua season"], ["i le Malo o le Atua i le lumanai.", "in the government of God in the lumanai"]]},
  {num:10,words:[["Matou te talitonu", "we (excl) believe"], ["i le faapotopotoina moni o Isaraelu", "in the gathered together true of Israel"], ["ma le toefuataiga", "and the restoration"], ["mai o Ituaiga", "from of tribe"], ["e Sefulu;", "by ten"], ["ma o le a faatuina Siona", "and will built Zion"], ["(le Ierusalema Fou)", "the Jerusalem new"], ["i luga o le konetineta", "upon the konetineta"], ["o Amerika;", "Amerika"], ["o le a nofotupu lava Keriso", "what nofotupu indeed Christ"], ["i le lalolagi;", "on the earth"], ["ma,", "and"], ["o le a faafouina", "what make new"], ["le lalolagi ma maua lona mamalu faaparataiso .", "the earth and received his glory make paradise"]]},
  {num:11,words:[["Matou te ta'utino atu", "we (excl) to hang near the body"], ["ua ia i matou", "to in we (excl)"], ["le aiā tatau matou", "the aiā to wring out we (excl)"], ["te tapuai atu ai", "worship"], ["i le Atua Mamana", "in the God Mamana"], ["e tusa ai", "to according to"], ["ma o matou lava lotofuatiaifo ,", "and of we (excl) indeed lotofuatiaifo"], ["ma ua matou tuuina atu foi lea", "and we (excl) given also"], ["lava aiā tatau", "indeed aiā to wring out"], ["i tagata uma,", "in man all"], ["e faitalia", "to as I"], ["i latou,", "them"], ["pe faapefea,", "whether how"], ["po o fea,", "night of where?/which?"], ["po o le a foi le mea latou te tapuai atu i ai.", "night will also the thing they worship therein"]]},
  {num:12,words:[["Matou te talitonu", "we (excl) believe"], ["i le usiusitai", "in the obeyed"], ["i tupu,", "in king"], ["peresitene,", "President"], ["faipule,", "a councillor"], ["ma faamasino,", "and judge"], ["i le usiusitai,", "in the obeyed"], ["faamamaluina,", "to protect"], ["ma le lagolagoina", "and the lagolagoina"], ["o le tulafono .", "the law"]]},
  {num:13,words:[["Matou te talitonu", "we (excl) believe"], ["i le faamaoni ,", "in the faithful"], ["amiotonu,", "righteous"], ["nofomama ,", "nofomama"], ["agalelei,", "treated well"], ["amiomama,", "amiomama"], ["ma le faia o mea lelei", "and the made of thing good"], ["i tagata uma;", "in man all"], ["e moni,", "verily/truly"], ["e mafai ona", "could"], ["matou faapea atu,", "we (excl) thus"], ["ua matou mulimuli", "we (excl) followed after"], ["i le apoapoaiga", "in the apoapoaiga"], ["a Paulo—Matou te talitonu", "of Paulo—Matou believe"], ["i mea uma,", "in all things"], ["matou te faamoemoe", "we (excl) hope"], ["i mea uma,", "in all things"], ["ua uma ona", "finished"], ["matou onosai", "we (excl) patience"], ["i mea e tele,", "in great things"], ["ma ua faamoemoe", "and hoped"], ["o le a mafai ona", "what able then"], ["matou onosai", "we (excl) patience"], ["i mea uma.", "in all things"], ["Afai o", "if of"], ["i ai nisi mea e mamā ,", "therein some thing to clean"], ["matagofie,", "beautiful"], ["pe logoleleia", "whether logoleleia"], ["pe tauleleia,", "whether tauleleia"], ["matou te saili atu i nei mea.", "we (excl) seek these things"], ["Iosefa Samita.", "Joseph Smith"]]},
];
renderVerseSet(_af_ch_1_Verses, 'af-ch1-verses');

})();