(function() {
var en_ch_1_Verses = [
  {num:1,words:[["Faauta,", "behold"], ["sa oo ina ua iloa e a'u,", "it came to pass that known to I"], ["o Enosa ,", "Enos"], ["o lo'u tamā o se tagata amiotonu o ia—ona sa ia aoaoina a'u i lana gagana,", "my father a man righteous ia—ona to taught I in his language"], ["ma i le aoaoga ma le apoapoaiga foi a le Alii—ma ia faamanūina lava le suafa o lo'u Atua mo lena mea—", "and in the aoaoga and the apoapoaiga also but the alii—ma to faamanūina indeed the name my God for that mea—"]]},
  {num:2,words:[["Ma o le a ou faamatala atu ia te outou le fagatuaga na ou faia i luma o le Atua,", "and the but I faamatala unto ye all the fagatuaga I made in before the God"], ["ae ou te lei maua se faamagaloga o a'u agasala.", "but I whale's teeth received a faamagaloga I am sin"]]},
  {num:3,words:[["Faauta,", "behold"], ["sa ou alu e tuli manu i le vao;", "I go to drive animal in the vegetation"], ["ma o upu sa ou faalogo soo o tautala i ai lo'u tamā e uiga i le ola e faavavau,", "and word I hearken frequently to talk therein my father to kind in the life to a stone connected with"], ["ma le olioli o le au paia,", "and the rejoice the I holy"], ["sa gotouga ifo i lo'u loto.", "to sink like an uga in my heart"]]},
  {num:4,words:[["Ma sa matelaina lo'u agaga;", "and matelaina my spirit"], ["ma sa ou tootuli i lalo i luma o lo'u Tufuga,", "and I tootuli in under in before my master builder"], ["ma ou tagi atu ia te ia i le tatalo malosi ma le faatauanau mo lo'u lava agaga;", "and I to cry unto to in the pray strong and the faatauanau for my indeed spirit"], ["ma sa ou tagi atu ia te ia i le aso atoa;", "and I to cry unto to in the day together with"], ["ioe,", "yea"], ["ma ina ua oo mai le po sa ou sii maualuga a'e pea lo'u leo sa oo ina oo atu i le lagi.", "and let oo from the night I lift up Iiigli up continually my voice oo let oo in the heaven"]]},
  {num:5,words:[["Ma sa oo mai se siufofoga ia te a'u,", "and oo from a voice unto I"], ["ua fetalai mai:", "said from"], ["Enosa e,", "Enos by"], ["ua faamagaloina au agasala,", "faamagaloina I sin"], ["ma o le a faamanuiaina oe.", "and the but faamanuiaina you"]]},
  {num:6,words:[["Ma o a'u,", "and I am"], ["o Enosa,", "Enos"], ["sa ou iloa e le mafai ona pepelo le Atua;", "I known by the able then false the God"], ["o le mea lea,", "therefore/wherefore"], ["sa tafi ese ai lo'u lagona o a'u sese.", "to brush away my to understand I am sese"]]},
  {num:7,words:[["Ma sa ou fai atu:", "and I make"], ["Le Alii e,", "the Lord by"], ["ua faapefea ea ona faia lenei mea?", "how ? to rise (as a diver to the sur- then made this thing"]]},
  {num:8,words:[["Ma sa fetalai mai o ia ia te a'u:", "and said from he unto I"], ["Ona o lou faatuatua ia Keriso,", "because of your faith to Christ"], ["o lē e te lei faalogo lava pe na e vaai muamua i ai.", "not by whale's teeth hearken indeed or to to look at first therein"], ["Ma e tele tausaga e mavae atu ae lei faaali mai e ia o ia lava i le tino;", "and to great year to a parting but whale's teeth reveal from by him he indeed in the body"], ["o le mea lea,", "therefore/wherefore"], ["inā alu ia,", "inā go to"], ["ua faamamāina oe i lou faatuatua.", "faamamāina you in your faith"]]},
  {num:9,words:[["O lenei,", "this"], ["sa oo ina ua ou faalogo atu i nei upu sa amata ona ou lagona se naunauga mo le manuia o o'u uso,", "it came to pass that I hearken in this word began then I to understand a naunauga for the peace I a relative of the same generation and gender"], ["o sa Nifaē;", "Nephi"], ["o le mea lea,", "therefore/wherefore"], ["sa ou sasaa atu ai lo'u agaga atoa i le Atua mo i latou.", "I plurzH x)^ saasaa my spirit together with in the God for them"]]},
  {num:10,words:[["Ma a'o faapea ona ou fagatua i le agaga,", "and day thus then I fagatua in the spirit"], ["faauta,", "behold"], ["sa toe tulei mai le siufofoga o le Alii i lo'u mafaufau ,", "again to push from the voice the Lord in my think"], ["ua fetalai mai:", "said from"], ["O le a Ou asiasi atu i ou uso e tusa ma lo latou filiga i le tausiga o a'u poloaiga.", "what I asiasi in I a relative of the same generation and gender to according to and the them perseverance in the tausiga I am commandment"], ["Ua Ou tuu atu ia te i latou lenei laueleele,", "I put unto them this ground"], ["ma o se laueleele ua paia;", "and a ground holy"], ["ma Ou te lē fetuuina lava,", "and I not fetuuina indeed"], ["vagana ai ona o le amioletonu;", "except then the wickedness"], ["o le mea lea,", "therefore/wherefore"], ["o le a Ou asiasi atu ai i ou uso e pei ona Ou fai atu ai;", "what I asiasi in I a relative of the same generation and gender to to be broken then I make"], ["ma o a latou solitulafono o le a Ou ave ifo i lalo ma le faanoanoa i luga o o latou lava ulu.", "and but them solitulafono the but I take in under and the to mourn in above them indeed head"]]},
  {num:11,words:[["Ma ina ua uma ona faalogo atu o a'u,", "and let all then hearken I am"], ["o Enosa i nei upu,", "Enos in this word"], ["sa amata ona lē maluelue o lo'u faatuatua i le Alii;", "began then not maluelue my faith in the Lord"], ["ma sa ou tatalo atu ia te ia i ni fagatuaga uumi e tele mo o'u uso,", "and I pray unto to in some fagatuaga uumi to great for I a relative of the same generation and gender"], ["o sa Lamanā.", "Lamanite"]]},
  {num:12,words:[["Ma sa oo ina ua uma ona ou tatalo atu ma galue ma le filiga atoa,", "and oo let all then I pray and work and the perseverance together with"], ["sa fetalai mai le Alii ia te a'u:", "said from the Lord unto I"], ["O le a Ou tuu atu ia te oe e tusa ma ou naunauga ,", "what I put unto you to according to and I naunauga"], ["ona o lou faatuatua.", "because of your faith"]]},
  {num:13,words:[["Ma o lenei faauta,", "and now behold"], ["o le naunauga lenei sa ou manao i ai mai ia te ia—e faapea afai e oo ina pauu lo'u nuu o sa Nifaē i le solitulafono,", "the naunauga this I desire therein from unto ia—e thus if by oo let fell my nation Nephi in the solitulafono"], ["ma i'u ina faaumatia ai,", "and attain let destroy"], ["ma o le a lē faaumatiaina sa Lamanā,", "and the but not faaumatiaina Lamanite"], ["ia faasaoina e le Alii le Atua se talafaamaumau o lo'u nuu,", "to saved by the Lord the God a record my nation"], ["o sa Nifaē;", "Nephi"], ["e tusa pe tatau ai ona faasaoina e ala i le mana o lona aao paia,", "to according to or to wring out then saved to arise in the to get his hand (extended) holy"], ["ina ia mafai ona aumai i se aso o lumanai i sa Lamanā,", "that it might be and bring in a day lumanai in Lamanite"], ["ina atonu e mafai ona aumai ai i latou i le olataga—", "let impers to able then bring them in the olataga—"]]},
  {num:14,words:[["Ona o le taimi nei ua lē aoga a matou tauiviga e toefuatai mai i latou i le faatuatuaga moni.", "because of the time this not useful but we tauiviga by toefuatai from them in the something to rely true"], ["Ma ua latou tauto i lo latou ita e faapea,", "and them to take an oath in the them angry by thus"], ["afai e mafai,", "if to able"], ["o le a latou faaumatia a matou talafaamaumau ma i matou,", "what them destroy but we record and in we"], ["ma uputuu uma foi a o matou tamā.", "and uputuu all also but we father"]]},
  {num:15,words:[["O le mea lea,", "therefore/wherefore"], ["i lo'u iloa e mafai e le Alii le Atua ona faasaoina a matou talafaamaumau,", "in my known to able by the Lord the God then saved but we record"], ["o lea na ou tagi atu ai ia te ia e lē aunoa,", "therefore I to cry unto to by not without"], ["aua sa fetalai mai o ia ia te a'u:", "for said from he unto I"], ["Soo se mea e te ole mai ai i le faatuatua,", "frequently a thing by entreat from in the faith"], ["ma talitonu o le a e maua e ala i le suafa o Keriso,", "and believe the but to received to arise in the name Christ"], ["o le a e mauaina.", "what by mauaina"]]},
  {num:16,words:[["Ma sa ia te a'u le faatuatua,", "and unto I the faith"], ["ma sa ou tagi atu i le Atua ia faasaoina e ia talafaamaumau ;", "and I to cry in the God to saved by him record"], ["ma sa osifeagaiga o ia ma a'u o le a ia aumai i latou ia sa Lamanā i lona lava taimi e tatau ai.", "and osifeagaiga he and I the but to bring them to Lamanite in his indeed time to to wring out"]]},
  {num:17,words:[["Ma o a'u,", "and I am"], ["o Enosa,", "Enos"], ["sa ou iloa o le a faia lava e tusa ma le feagaiga ua faia e ia;", "I known the but made indeed to according to and the covenant made by him"], ["o le mea lea na mapu ai lo'u agaga.", "therefore mapu my spirit"]]},
  {num:18,words:[["Ma sa fetalai mai le Alii ia te a'u:", "and said from the Lord unto I"], ["Sa mananao foi ou tamā i lenei mea mai ia te a'u;", "mananao also I father in this thing from unto I"], ["ma o le a faia ia te i latou e tusa ma lo latou faatuatua;", "and the but made unto them to according to and the them faith"], ["ona o lo latou faatuatua sa pei o lou.", "because of their faith to be broken your"]]},
  {num:19,words:[["Ma o lenei sa oo ina alu atu a'u,", "and now it came to pass that go away I"], ["o Enosa,", "Enos"], ["i totonu o le nuu o Nifae,", "in the midst of the nation Nephi"], ["ma ou vavalo atu e uiga i mea o le a oo mai,", "and I prophesy to kind in thing the but oo from"], ["ma molimau atu e uiga i mea sa ou faalogo ma vaai i ai.", "and a witness to kind in thing I hearken and to look at therein"]]},
  {num:20,words:[["Ma ou te molimau atu sa saili ma le filiga le nuu o Nifae e toefuatai mai sa Lamanā i le faatuatuaga moni i le Atua.", "and I a witness seek and the perseverance the nation Nephi by toefuatai from Lamanite in the something to rely true in the God"], ["Peitai sa lē aoga a matou galuega ;", "however not useful but we work"], ["sa mausali lo latou ita,", "to be Hrmly fixed their angry"], ["ma sa taitaiina i latou i o latou natura leaga,", "and taitaiina them in them natura evil"], ["sa avea i latou ma tagata aivao ma feai,", "become them and man aivao and feai"], ["ma inutoto ,", "and inutoto"], ["ua tumu i le ifo i tupua ma mea eleelea;", "fill in the in idol and thing eleelea"], ["ua aai i manu 'ai manu;", "eat in animal eat animal"], ["ua nonofo i faleie,", "dwelling in faleie"], ["ma feoai solo i le vao ma se pa'u manu pupuu e fusi i o latou sulugatiti ma o latou ulu ua tafi;", "and feoai to move swiftly in the vegetation and a to be as far as animal pupuu by fusi in them the place where the and them head to brush"], ["ma sa popoto i latou i le 'aufana ,", "and round (as the trunk of a them in the 'aufana"], ["ma le simetea,", "and the simetea"], ["ma le to'i.", "and the a male given name"], ["Ma o le toatele o i latou sa leai se mea sa latou 'aia sa na o aano mata o manu;", "and the many them no a thing them to be galled or chafed aano eye animal"], ["ma sa latou saili e lē aunoa e faaumatia i matou.", "and them seek by not without to destroy in we"]]},
  {num:21,words:[["Ma sa oo ina galueaiina e le nuu o Nifae le laueleele,", "and oo let galueaiina by the nation Nephi the ground"], ["ma toto ituaiga eseese o kuranuma,", "and blood ituaiga divided kuranuma"], ["ma laau e 'aina fua,", "and tree to edible fruit"], ["ma fai lafu ma fagaga,", "and make a herd and fagaga"], ["ma lafu manu faatoaga o ituaiga eseese uma,", "and a herd animal faatoaga ituaiga divided all"], ["ma 'oti,", "and cut"], ["ma 'oti aivao,", "and cut aivao"], ["ma solofanua foi e tele.", "and horse also to great"]]},
  {num:22,words:[["Ma sa matua toatele lava perofeta sa i ai i totonu o i matou.", "and very many indeed prophet therein in inside in we"], ["Ma o le nuu,", "and the nation"], ["o ni tagata sa ua maaa,", "some man maaa"], ["sa faigata ona malamalama i ai.", "difficult then light therein"]]},
  {num:23,words:[["Ma sa leai se mea vagana ai upu malolosi,", "and no a thing except word mighty"], ["ma le talai ma le vavalo atu e uiga i taua,", "and the preach and the prophesy to kind in war"], ["ma finauga,", "and argument"], ["ma faafanoga,", "and destruction"], ["ma le faamanatu atu pea lava pea ia te i latou e uiga i le oti,", "and the to remind continually indeed continually unto them to kind in the die"], ["ma le umi o le faavavau,", "and the long the a stone connected with"], ["ma faamasinoga ma le mana o le Atua,", "and judgment and the to get the God"], ["ma nei mea uma,", "and this thing all"], ["sa mafai ona faia—e uunai ai pea lava pea i latou,", "able then faia—e uunai continually indeed continually them"], ["e taofi ai i latou i le matata'u i le Alii.", "to hold them in the fear in the Lord"], ["Ou te fai atu,", "I make"], ["sa leai se mea sa itiiti mai nei mea,", "no a thing small from this thing"], ["ma le tautala atu ma le manino tele lava,", "and the to talk and the manino great indeed"], ["sa mafai ona taofia ai i latou mai le o ifo vave i lalo i le faafanoga.", "able then taofia them from the quick in under in the destruction"], ["Ma ua faapea le ala ua ou tusia ai e uiga ia te i latou.", "and thus the arise I written to kind unto them"]]},
  {num:24,words:[["Ma sa ou vaaia taua i le va o sa Nifaē ma sa Lamanā i le gasologa o o'u aso.", "and I seen war in the space Nephi and Lamanite in the gasologa I day"]]},
  {num:25,words:[["Ma sa oo ina amata ona ou toeaina,", "and oo let began then I elder"], ["ma ua selau fitu sefulu ma le iva nei tausaga ua mavae atu mai le taimi na tuua ai Ierusalema e lo matou tamā o Liae.", "and hundred seven ten and the nine this year a parting from the time left Jerusalem by our father Lehi"]]},
  {num:26,words:[["Ma sa ou vaai ua lata ona ou alu ifo i lalo i lo'u tuugamau,", "and I to look at lata then I go in under in my tuugamau"], ["ina ua uma ona galue o le mana o le Atua i o'u luga ia ou talai ma vavalo atu i lenei nuu,", "let all then work the to get the God in I above to I preach and prophesy in this nation"], ["ma folafola atu le afioga e tusa ma le upumoni ua ia Keriso.", "and to spread out the a word to according to and the upumoni to Christ"], ["Ma sa ou folafolaina atu i o'u aso uma,", "and I folafolaina in I day all"], ["ma sa sili ona ou fiafia i ai i lo o mea o le lalolagi.", "and most then I competition therein in the thing the earth"]]},
  {num:27,words:[["Ma ua lata ona ou alu i le nofoaga o lo'u malologa ,", "and lata then I go in the place my a resting place"], ["lea ou te faatasi ai ma lo'u Togiola;", "I once and my atonement"], ["ona ua ou mautinoa o ia ou te malolo ai.", "and I mautinoa he I rest"], ["Ma ou te olioli i le aso o le a faaofuina ai lo'u tino faaletino i le tino ola pea,", "and I rejoice in the day the but faaofuina my body relating to the body in the body life continually"], ["ma ou tu ai i ona luma;", "and I stand in then before"], ["ona ou vaai ai lea i ona fofoga ma le fiafia,", "and I to look at in then face and the competition"], ["ma o le a fetalai mai o ia ia te a'u:", "and the but said from he unto I"], ["Sau ia ia te a'u,", "come to unto I"], ["oe ua faamanuiaina,", "you faamanuiaina"], ["ua i ai se nofoaga ua saunia mo oe i maota o lo'u Tamā.", "therein a place prepared for you in the name of a tree my father"], ["Amene.", "amen"]]},
];
renderVerseSet(en_ch_1_Verses, 'en-ch1-verses');

})();