(function() {
var est_ch_1_Verses = [
  {num:1,words:[["O ona po o Asueru,", "Now it came to pass in the days of Ahasuerus, (this is Ahasuerus which reigned,"], ["o Asueru lea o le na fai ma tupu e gata mai i Initia e oo atu i Aitiope,", "from India even unto Ethiopia,"], ["i itu malo e tasi le selau e lua sefulu ma le fitu;", "over an hundred and seven and twenty provinces: )"]]},
  {num:2,words:[["o ona po ia,", "That in those days,"], ["ina o nofo le tupu o Asueru i le nofoālii o lona malo,", "when the king Ahasuerus sat on the throne of his kingdom,"], ["sa i ai i Susana le maota,", "which was in Shushan the palace,"]]},
  {num:3,words:[["o le tolu o tausaga o lana nofoaiga na ia fai ai le tausamiga mā alii uma ua ia te ia ma ana auauna;", "In the third year of his reign,"], ["o e ua sili o Peresia ma Metai,", "he made a feast unto all his princes and his servants;"], ["o alii ma alii o itu malo,", "the power of Persia and Media, the nobles and princes of the provinces,"], ["na i ona luma;", "being before him:"]]},
  {num:4,words:[["ina o faaaliatua le sosia o lona malo mamalu, ma le silisili o le matagofie o lona malualii,", "When he shewed the riches of his glorious kingdom and the honour of his excellent majesty many days,"], ["i aso e tele, o aso e selau ma le valu sefulu.", "even an hundred and fourscore days."]]},
  {num:5,words:[["Ua atoatoa ia aso,", "And when these days were expired,"], ["ona fai ai lea e le tupu o le tausamiga mā tagata uma na i Susana le maota,", "the king made a feast unto all the people that were present in Shushan the palace,"], ["o alii atoa ma tagata nuu,", "both unto great and small,"], ["i aso e fitu,", "seven days,"], ["i le lotoā o le fanua o le maota o le tupu.", "in the court of the garden of the king's palace;"]]},
  {num:6,words:[["Na tautau ai ie lino sinasina;", "Where were white, green,"], ["o ie lelei ma ie uli,", "and blue,"], ["na faamauina i maea vavae ma le pāuli i mama ario ma pou sesa;", "hangings, fastened with cords of fine linen and purple to silver rings and pillars of marble:"], ["na i ai moega auro ma ario i luga o le paepae o paata,", "the beds were of gold and silver,"], ["ma sesa,", "upon a pavement of red, and blue,"], ["ma tara,", "and white,"], ["ma sokere.", "and black, marble."]]},
  {num:7,words:[["Na avatu ipu auro latou te feinu ai,", "And they gave them drink in vessels of gold,"], ["o ipu e tino eseese,", "(the vessels being diverse one from another,"], ["ma uaina a le tupu e tele,", ") and royal wine in abundance,"], ["e pei ona tatau i le tupu.", "according to the state of the king."]]},
  {num:8,words:[["Na faatatau foi i le tulafono ona inu;", "And the drinking was according to the law;"], ["ua leai se na faatauanau atu i se tasi;", "none did compel:"], ["auā sa faapea ona poloai e le tupu i e pule uma i lona aiga,", "for so the king had appointed to all the officers of his house,"], ["ia taitasi le tagata ma lana faitalia.", "that they should do according to every man's pleasure."]]},
  {num:9,words:[["O Vasati foi le masiofo, na ia faia le tausamiga mā fafine i le fale o le tupu, o le fale lea o le tupu o Asueru.", "Also Vashti the queen made a feast for the women in the royal house which belonged to king Ahasuerus."]]},
  {num:10,words:[["O le aso e fitu ina o fiafia le loto o le tupu i le uaina,", "On the seventh day,"], ["na ia fai atu ai ia Meumanu,", "when the heart of the king was merry with wine,"], ["ma Piseta,", "he commanded Mehuman, Biztha,"], ["ma Harepona,", "Harbona,"], ["ma Pigeta,", "Bigtha,"], ["ma Avageta,", "and Abagtha, Zethar,"], ["o Setara ma Karekase,", "and Carcas,"], ["o eunuka ia e toafitu e na auauna atu i luma o le tupu o Asueru,", "the seven chamberlains that served in the presence of Ahasuerus the king,"]]},
  {num:11,words:[["ia au mai le masiofo o Vasati i luma o le tupu,", "To bring Vashti the queen before the king with the crown royal,"], ["ma le palealii o le masiofo, ina ia faaali atu lona lalelei i le nuu ma alii;", "to shew the people and the princes her beauty:"], ["auā e lalelei lava o ia.", "for she was fair to look on."]]},
  {num:12,words:[["A e lei mafai le masiofo o Vasati ona alu ane i le feau a le tupu na o atu ai eunuka;", "But the queen Vashti refused to come at the king's commandment by his chamberlains:"], ["ona matuā ita ai lea o le tupu,", "therefore was the king very wroth,"], ["na tupu tele lava le tiga o lona loto.", "and his anger burned in him."]]},
  {num:13,words:[["Ona fai atu lea o le tupu i e popoto,", "Then the king said to the wise men,"], ["e na iloa tausaga;", "which knew the times,"], ["(auā na faapea le masani a le tupu ia te i latou uma na iloa tulafono ma faamasinoga;", "(for so was the king's manner toward all that knew law and judgment:"]]},
  {num:14,words:[["na latalata ane ia te ia o Karesena,", "And the next unto him was Carshena,"], ["o Setaru,", "Shethar,"], ["o Atematu,", "Admatha,"], ["o Tasesa,", "Tarshish,"], ["o Merese,", "Meres, Marsena,"], ["o Maresena,", "and Memucan,"], ["o Memukana,", "the seven princes of Persia and Media,"], ["o alii ia e toafitu o Peresia ma Metai o e na iloa fofoga o le tupu,", "which saw the king's face,"], ["e na sili i le malo;", "and which sat the first in the kingdom;"], [")", ")"]]},
  {num:15,words:[["Se a se mea e faia i le masiofo o Vasati, e tusa ma le tulafono,", "What shall we do unto the queen Vashti according to law,"], ["ina ua le mafai o ia i le upu a le tupu o Asueru na o atu ai eunuka?", "because she hath not performed the commandment of the king Ahasuerus by the chamberlains?"]]},
  {num:16,words:[["Ona tali mai lea o Memukana i luma o le tupu ma alii,", "And Memucan answered before the king and the princes,"], ["E le na o le tupu na aga faapiopio i ai le masiofo o Vasati,", "Vashti the queen hath not done wrong to the king only, but also to all the princes,"], ["a e atoa ma alii uma ma tagata uma o i itu malo uma o le tupu o Asueru;", "and to all the people that are in all the provinces of the king Ahasuerus."]]},
  {num:17,words:[["auā e oo atu le tala i le masiofo i fafine uma ona inosia ai lea e i latou o a latou tane,", "For this deed of the queen shall come abroad unto all women,"], ["pe a latou ta'u ane,", "so that they shall despise their husbands in their eyes,"], ["Na poloai atu le tupu o Asueru ia au mai i ona luma le masiofo o Vasati,", "when it shall be reported, The king Ahasuerus commanded Vashti the queen to be brought in before him,"], ["a e lei alu ane o ia.", "but she came not."]]},
  {num:18,words:[["O tamaitai foi o Peresia ma Metai e ua faalogo i le tala i le masiofo, e fai atu ai i latou i le aso nei i alii uma ua i le tupu,", "Likewise shall the ladies of Persia and Media say this day unto all the king's princes,"], ["ona tele ai lea o le 'ino'ino ma le feitagai.", "which have heard of the deed of the queen. Thus shall there arise too much contempt and wrath."]]},
  {num:19,words:[["Afai e lelei i le tupu,", "If it please the king,"], ["ia oo atu lana afioga mai ia te ia lava,", "let there go a royal commandment from him,"], ["ma ia tusia faatasi ma tulafono a Peresia ma Metai, e le toe tālaina,", "and let it be written among the laws of the Persians and the Medes,"], ["aua le toe oo mai o Vasati i luma o le tupu o Asueru;", "that it be not altered,"], ["a ia fai se masiofo a le tupu e sui ai o ia,", "That Vashti come no more before king Ahasuerus;"], ["o se tasi e sili ona lelei ia te ia.", "and let the king give her royal estate unto another that is better than she."]]},
  {num:20,words:[["A logo atu foi le pule a le tupu, na te faia,", "And when the king's decree which he shall make shall be published throughout all his empire,"], ["i lona malo uma,", "(for it is great,"], ["auā ua tele lea,", ") all the wives shall give to their husbands honour,"], ["ona faaaloalo ai lea o fafine uma i a latou tane, o alii atoa ma tagatā nuu.", "both to great and small."]]},
  {num:21,words:[["Ua lelei foi lena upu i le manatu o le tupu ma alii;", "And the saying pleased the king and the princes;"], ["ona faia lea e le tupu e pei ona fai atu ai Memukana.", "and the king did according to the word of Memucan:"]]},
  {num:22,words:[["Ua ia avatu tusi i itu malo uma o le tupu,", "For he sent letters into all the king's provinces,"], ["ua faatatau ma le tusilima a lea itu malo ma lea itu malo,", "into every province according to the writing thereof,"], ["e tusa foi ma le gagana a lea nuu ma lea nuu,", "and to every people after their language,"], ["ina ia taitoatasi le tane ma pule i lona aiga,", "that every man should bear rule in his own house,"], ["ma ia tautala i le gagana a lona nuu.", "and that it should be published according to the language of every people."]]},
];
renderVerseSet(est_ch_1_Verses, 'est-ch1-verses');

var est_ch_2_Verses = [
  {num:1,words:[["Ua mavae ia mea,", "After these things,"], ["ua maona foi le ita o le tupu o Asueru,", "when the wrath of king Ahasuerus was appeased,"], ["ona manatua lea e ia o Vasati,", "he remembered Vashti,"], ["ma le mea na ia faia,", "and what she had done,"], ["i le ma le tulafono na faia ia te ia.", "and what was decreed against her."]]},
  {num:2,words:[["Ona fai atu ai lea o auauna, e na auauna i le tupu,", "Then said the king's servants that ministered unto him,"], ["Ia sailiili mai mā le tupu o teine taupou lalelei.", "Let there be fair young virgins sought for the king:"]]},
  {num:3,words:[["Ia tofia foi e le tupu o matai i itu malo uma o lona malo,", "And let the king appoint officers in all the provinces of his kingdom,"], ["latou te faapotopotoina teine taupou lalelei uma i Susana le maota,", "that they may gather together all the fair young virgins unto Shushan the palace,"], ["i le fale o fafine,", "to the house of the women,"], ["ia Hege le eunuka a le tupu,", "unto the custody of Hege the king's chamberlain,"], ["o lē tausi i fafine;", "keeper of the women;"], ["ma ia avatua ia te i latou mea e faamamāina a'i i latou.", "and let their things for purification be given them:"]]},
  {num:4,words:[["O le teine foi e fiafia i ai le tupu ia avea o ia ma masiofo e sui ai Vasati. Ua lelei lea upu i le manatu o le tupu;", "And let the maiden which pleaseth the king be queen instead of Vashti. And the thing pleased the king;"], ["ona ia faia lea faapea.", "and he did so."]]},
  {num:5,words:[["Ua i ai i Susana le maota o le tasi tagata o sa Iutā,", "Now in Shushan the palace there was a certain Jew,"], ["o Moretekai lona igoa,", "whose name was Mordecai,"], ["o le atalii o Iairo,", "the son of Jair,"], ["o le atalii ia o Semi,", "the son of Shimei,"], ["o le atalii ia o Kiso,", "the son of Kish,"], ["o lo sa Peniaminā.", "a Benjamite;"]]},
  {num:6,words:[["Ua tāfea mai o ia mai Ierusalema faatasi ma le tafeaga na tāfea faatasi ma Iekonia le tupu o Iuta,", "Who had been carried away from Jerusalem with the captivity which had been carried away with Jeconiah king of Judah,"], ["o le na tāfea e Nepukanesa le tupu o Papelonia.", "whom Nebuchadnezzar the king of Babylon had carried away."]]},
  {num:7,words:[["Ua fai o ia ma tamā o Hatesa,", "And he brought up Hadassah,"], ["o Eseta foi lea,", "that is, Esther,"], ["o le afafine o le uso o lona tamā,", "his uncle's daughter:"], ["ina ua leai sona tamā po o sona tinā;", "for she had neither father nor mother,"], ["o le teine foi ua lalelei lona tino,", "and the maid was fair and beautiful;"], ["ma ua lalelei ona mata. Ua oti lona tamā ma lona tinā,", "whom Mordecai, when her father and mother were dead,"], ["ona avea ai lea o ia e Moretekai e fai mona afafine.", "took for his own daughter."]]},
  {num:8,words:[["Ua lagona e ia le upu a le tupu ma lana tulafono,", "So it came to pass, when the king's commandment and his decree was heard,"], ["ma ua faapotopotoina ai teine e toatele i Susana le maota ia Hege,", "and when many maidens were gathered together unto Shushan the palace, to the custody of Hegai,"], ["ona avea ai lea o Eseta i le fale o le tupu ia Hege,", "that Esther was brought also unto the king's house,"], ["lē tausi i fafine.", "to the custody of Hegai, keeper of the women."]]},
  {num:9,words:[["Ua lelei le teine i lona manatu,", "And the maiden pleased him,"], ["ua alofaina o ia e ia;", "and she obtained kindness of him; and he speedily gave her her things for purification,"], ["ona ia vave tuuina atu ai lea ia te ia ana mea e faamamāina a'i,", "with such things as belonged to her,"], ["atoa ma mea na tofia māna,", "and seven maidens,"], ["ma teine e toafitu e na filifilia mai le aiga o le tupu e tuuina atu ia te ia;", "which were meet to be given her, out of the king's house:"], ["ua ia tuu atu foi ia te ia ma lona galu teine i le mea sili i le fale o fafine.", "and he preferred her and her maids unto the best place of the house of the women."]]},
  {num:10,words:[["E lei faailoa atu e Eseta lona nuu po o lona aiga;", "Esther had not shewed her people nor her kindred:"], ["auā na fai atu e Moretekai ia te ia aua na te faailoa atu.", "for Mordecai had charged her that she should not shew it."]]},
  {num:11,words:[["O lea aso ma lea aso foi na fealualuai ai o Moetekai i luma o le lotoā o le fale o fafine ina ia iloa po o malolo Eseta;", "And Mordecai walked every day before the court of the women's house, to know how Esther did,"], ["pe se a foi se mea e faia ia te ia.", "and what should become of her."]]},
  {num:12,words:[["Na aua'i ona solo taitoatasi o teine i lo latou o atu i le tupu o Asueru ina ua atoatoa masina e sefulu ma le lua,", "Now when every maid's turn was come to go in to king Ahasuerus, after that she had been twelve months,"], ["e tusa ma le tulafono i fafine;", "according to the manner of the women,"], ["auā na faapea ona atoatoa ai o aso o le faamamāina o i latou;", "(for so were the days of their purifications accomplished,"], ["o masina e ono e uu ai i le suāuu muro,", "to wit, six months with oil of myrrh,"], ["ma masina e ono i mea manogi,", "and six months with sweet odours, and with other things for the purifying of the women;"], ["ma mea e faamamāina a'i fafine.", ")"]]},
  {num:13,words:[["Ua faapea foi ona alu atu o le teine i le tupu;", "Then thus came every maiden unto the king;"], ["na avatua ia te ia mea uma na ia fai atu ai e alu ai ma ia mai le fale o fafine i le fale o le tupu.", "whatsoever she desired was given her to go with her out of the house of the women unto the king's house."]]},
  {num:14,words:[["O le afiafi na alu atu ai o ia,", "In the evening she went,"], ["o le taeao foi na toe foi ai i le lua o fale o fafine ia Sasekasa le eunuka a le tupu,", "and on the morrow she returned into the second house of the women, to the custody of Shaashgaz,"], ["o le leoleo i palake;", "the king's chamberlain,"], ["na ia le toe alu atu i le tupu,", "which kept the concubines:"], ["vagana ona fiafia o le tupu ia te ia,", "she came in unto the king no more, except the king delighted in her,"], ["ma ua valaauina lona igoa.", "and that she were called by name."]]},
  {num:15,words:[["Ua oo foi ia Eseta le afafine o Aviaila le uso o le tamā o Moretekai,", "Now when the turn of Esther,"], ["o le na faia o ia mona afafine,", "the daughter of Abihail the uncle of Mordecai, who had taken her for his daughter,"], ["ona alu atu i le tupu,", "was come to go in unto the king,"], ["e lei fai atu ai o ia i se mea ua na o mea na fai atu ai Hege le eunuka a le tupu,", "she required nothing but what Hegai the king's chamberlain, the keeper of the women,"], ["o le tausi fafine.", "appointed."], ["Ua alofagia foi Eseta e i latou uma e na iloa o ia.", "And Esther obtained favour in the sight of all them that looked upon her."]]},
  {num:16,words:[["Ua avea Eseta i le tupu o Asueru i le fale o le tupu i le sefulu o masina,", "So Esther was taken unto king Ahasuerus into his house royal in the tenth month,"], ["o le masina lea o Tapeta,", "which is the month Tebeth,"], ["i le fitu o tausaga o lana nofoaiga.", "in the seventh year of his reign."]]},
  {num:17,words:[["Ua sili foi le manao o le tupu ia Eseta i fafine uma,", "And the king loved Esther above all the women,"], ["ua sili foi ona alofaina ma faapelepeleina o ia e ia i taupou uma;", "and she obtained grace and favour in his sight more than all the virgins;"], ["ona ia tuu atu ai lea o le palealii i lona ulu,", "so that he set the royal crown upon her head,"], ["ma fai o ia ma masiofo e sui a'i Vasati.", "and made her queen instead of Vashti."]]},
  {num:18,words:[["Ona faia lea e le tupu o le tausamiga tele mā alii uma ua ia te ia ma ana auauna,", "Then the king made a great feast unto all his princes and his servants,"], ["o le tausamiga ona o Eseta;", "even Esther's feast;"], ["na ia tuuina atu ia malolo tagata o itu malo,", "and he made a release to the provinces, and gave gifts,"], ["na ia foai atu foi mea alofa e pei ona tatau i le tupu.", "according to the state of the king."]]},
  {num:19,words:[["Ua nofo Moretekai i le faitotoa o le tupu,", "And when the virgins were gathered together the second time,"], ["ina o faapotopotoina faalua o taupou.", "then Mordecai sat in the king's gate."]]},
  {num:20,words:[["E lei faailoa atu e Eseta lona aiga po o lona nuu;", "Esther had not yet shewed her kindred nor her people;"], ["e pei ona fai atu ai Moretekai ia te ia;", "as Mordecai had charged her:"], ["auā na faia e Eseta mea na fai atu ai Moretekai,", "for Esther did the commandment of Mordecai,"], ["e pei ona ia faia ina o tausia o ia e ia.", "like as when she was brought up with him."]]},
  {num:21,words:[["O ona po ia ina o nofo Moretekai i le faitotoa o le tupu,", "In those days,"], ["na ita ai Piketano ma Tirese,", "while Mordecai sat in the king's gate, two of the king's chamberlains,"], ["o eunuka ia e toalua a le tupu,", "Bigthan and Teresh,"], ["o e na leoleo i le faitotoa,", "of those which kept the door, were wroth,"], ["na la fia faaoo foi o la lima i le tupu o Asueru.", "and sought to lay hand on the king Ahasuerus."]]},
  {num:22,words:[["Ua iloa le mea e Moretekai,", "And the thing was known to Mordecai,"], ["ona ia faailoa atu lea i le masiofo o Eseta;", "who told it unto Esther the queen;"], ["ona ta'u atu ai lea e Eseta i le tupu i le igoa o Moretekai.", "and Esther certified the king thereof in Mordecai's name."]]},
  {num:23,words:[["Ua suesueina le mea,", "And when inquisition was made of the matter,"], ["ona iloa lea;", "it was found out; therefore they were both hanged on a tree:"], ["ona faatautauina ai lea o i laua i le laau. Na tusia ai foi i luma o le tupu i le tusi o tala i nofoaiga.", "and it was written in the book of the chronicles before the king."]]},
];
renderVerseSet(est_ch_2_Verses, 'est-ch2-verses');

var est_ch_3_Verses = [
  {num:1,words:[["Ua mavae ia mea,", "After these things did king Ahasuerus promote Haman the son of Hammedatha the Agagite,"], ["ona faasili lea e le tupu o Asueru ia Hamanu le atalii o Hametatu o lo sa Akakō, ma na faaeaina o ia,", "and advanced him,"], ["ma faasili lona nofoa i alii uma ua faatasi ma ia.", "and set his seat above all the princes that were with him."]]},
  {num:2,words:[["Ona punou lea ma ifo atu ia Hamanu o auauna uma a le tupu,", "And all the king's servants,"], ["o e na i ai i le faitotoa o le tupu;", "that were in the king's gate,"], ["auā na faapea ona poloai atu e le tupu ia faia ia te ia;", "bowed, and reverenced Haman:"], ["a e lei punou Moretekai,", "for the king had so commanded concerning him. But Mordecai bowed not,"], ["e lei ifo foi.", "nor did him reverence."]]},
  {num:3,words:[["Ona fai atu lea o auauna a le tupu,", "Then the king's servants,"], ["e na i ai i le faitotoa o le tupu,", "which were in the king's gate,"], ["ia Moretekai,", "said unto Mordecai,"], ["Se a le mea ua e soli ai le poloaiga a le tupu?", "Why transgressest thou the king's commandment?"]]},
  {num:4,words:[["Na fai atu pea i latou ia te ia i aso uma,", "Now it came to pass, when they spake daily unto him,"], ["ae na lē tali mai o ia. O lea na latou fa'ailoa atu ai ia Hamana,", "and he hearkened not unto them,"], ["e va'ai pe o le a tumau le tulaga a Moredekai;", "that they told Haman,"], ["auā na ia fa'amatala atu o ia o se tagata Iuta.", "to see whether Mordecai's matters would stand: for he had told them that he was a Jew."]]},
  {num:5,words:[["Ua iloa e Hamanu ua le punou Moretekai,", "And when Haman saw that Mordecai bowed not,"], ["ua le ifo foi ia te ia;", "nor did him reverence,"], ["ona matuā ita ai lea o Hamanu.", "then was Haman full of wrath."]]},
  {num:6,words:[["Na 'ino'ino o ia e faaoo lona lima ia Moretekai tau o ia;", "And he thought scorn to lay hands on Mordecai alone;"], ["auā ua latou faailoa atu ia te ia le nuu o Moretekai;", "for they had shewed him the people of Mordecai:"], ["ona manao lea o Hamanu e faaumatia sa Iutā uma lava, le nuu o Moretekai,", "wherefore Haman sought to destroy all the Jews that were throughout the whole kingdom of Ahasuerus,"], ["e na i ai i le malo uma o Asueru.", "even the people of Mordecai."]]},
  {num:7,words:[["O le masina muamua,", "In the first month,"], ["o le masina lea o Nisani,", "that is, the month Nisan,"], ["o le sefulu ma le lua o tausaga o le tupu o Asueru,", "in the twelfth year of king Ahasuerus,"], ["na fai ai le Puro,", "they cast Pur,"], ["o le vili lea,", "that is, the lot,"], ["i luma o Hamanu i lea aso ma lea aso,", "before Haman from day to day,"], ["i lea masina foi ma lea masina,", "and from month to month,"], ["e oo i le masina e sefulu ma le lua,", "to the twelfth month, that is,"], ["o le masina lea o Atara.", "the month Adar."]]},
  {num:8,words:[["Ona fai atu lea o Hamanu i le tupu o Asueru,", "And Haman said unto king Ahasuerus,"], ["O loo i ai le tasi nuu ua taapeape ma nonofo solo faatasi ma tagata o itu malo uma o lou malo. E ese foi a latou tulafono i tulafono a nuu uma,", "There is a certain people scattered abroad and dispersed among the people in all the provinces of thy kingdom;"], ["ma ua latou le usiusitai i tulafono a oe le tupu;", "and their laws are diverse from all people;"], ["o le mea lea,", "neither keep they the king's laws:"], ["e le tatau ai i lau afio ona tuu pea ia te i latou.", "therefore it is not for the king's profit to suffer them."]]},
  {num:9,words:[["Afai e lelei ia te oe le tupu,", "If it please the king,"], ["ia tusia ia fano i latou;", "let it be written that they may be destroyed:"], ["ou te fuaina atu ai taleni ario e sefulu afe i lima o e faia lenei mea,", "and I will pay ten thousand talents of silver to the hands of those that have the charge of the business,"], ["ina ia latou avatu ai i mea e teu ai oloa a le tupu.", "to bring it into the king's treasuries."]]},
  {num:10,words:[["Ona to ese ai lea e le tupu o lana mama i lona lima,", "And the king took his ring from his hand,"], ["ma avatu ai ia Hamanu le atalii o Hametatu o lo sa Akakō,", "and gave it unto Haman the son of Hammedatha the Agagite,"], ["o lē faasaua i sa Iutā.", "the Jews' enemy."]]},
  {num:11,words:[["Ua fai atu foi le tupu ia Hamanu,", "And the king said unto Haman,"], ["Ua avatua ia te oe le ario atoa ma lena nuu,", "The silver is given to thee, the people also,"], ["ina ia e faia i ai le mea e lelei ia te oe.", "to do with them as it seemeth good to thee."]]},
  {num:12,words:[["Ona valaauina lea o e tusiupu a le tupu i le aso e tasi le sefulu ma le tolu o le masina muamua,", "Then were the king's scribes called on the thirteenth day of the first month,"], ["ona tusia ai lea o mea uma ua fai atu ai Hamanu e avatu i alii sili ua i le tupu, ma e pule,", "and there was written according to all that Haman had commanded unto the king's lieutenants,"], ["o e na pule i lea itu malo ma lea itu malo,", "and to the governors that were over every province,"], ["o alii foi o lea nuu ma lea nuu,", "and to the rulers of every people of every province according to the writing thereof,"], ["e faatatau ma le tusilima a lea itu malo ma lea itu malo,", "and to every people after their language;"], ["e tusa foi ma le gagana a lea nuu ma lea nuu; na tusia i le igoa o le tupu o Asueru,", "in the name of king Ahasuerus was it written,"], ["na faamaufaailogaina foi i le mama a le tupu.", "and sealed with the king's ring."]]},
  {num:13,words:[["Ona molia lea o tusi e ua tele vavave i itu malo uma o le tupu,", "And the letters were sent by posts into all the king's provinces,"], ["ina ia faaumatia,", "to destroy,"], ["ma ia fasiotia,", "to kill,"], ["ma ia fano sa Iutā uma,", "and to cause to perish,"], ["o taulelea atoa ma toeaina,", "all Jews, both young and old,"], ["o tama iti atoa ma fafine,", "little children and women,"], ["i le aso e tasi,", "in one day,"], ["o le sefulu ma le tolu lea o aso o le sefulu ma le lua o masina,", "even upon the thirteenth day of the twelfth month,"], ["o le masina lea a Atara;", "which is the month Adar,"], ["ma a latou mea ia vetea.", "and to take the spoil of them for a prey."]]},
  {num:14,words:[["O le ata o le tusi e avatua e fai ma tulafono i lea itu malo ma lea itu malo uma,", "The copy of the writing for a commandment to be given in every province was published unto all people,"], ["ua faailoa atu ai i nuu uma ina ia saunia i latou i lea aso.", "that they should be ready against that day."]]},
  {num:15,words:[["Na o atu e ua tele vavave o faataaliseina i le poloaiga a le tupu;", "The posts went out,"], ["na avatua foi le tulafono ai Susana le maota. Ona la nonofo lea o le tupu ma Hamanu,", "being hastened by the king's commandment,"], ["ua la feinu;", "and the decree was given in Shushan the palace. And the king and Haman sat down to drink;"], ["a ua atuatuvale le aai o Susana.", "but the city Shushan was perplexed."]]},
];
renderVerseSet(est_ch_3_Verses, 'est-ch3-verses');

var est_ch_4_Verses = [
  {num:1,words:[["Ua iloa e Moretekai mea uma ua faia,", "When Mordecai perceived all that was done,"], ["ona saei ai lea e Moretekai ona ofu,", "Mordecai rent his clothes,"], ["ma ua ofu o ia i le ie talatala ma le lefulefu,", "and put on sackcloth with ashes,"], ["ma alu atu i totonu o le aai,", "and went out into the midst of the city,"], ["ma alaga i le alaga tele ma ua lotulotu.", "and cried with a loud and a bitter cry;"]]},
  {num:2,words:[["Ua alu atu lava o ia i luma o le faitotoa o le tupu,", "And came even before the king's gate:"], ["auā ua sa ona ulu atu i le faitotoa o le tupu a o ofu i le ie talatala.", "for none might enter into the king's gate clothed with sackcloth."]]},
  {num:3,words:[["O lea itu malo foi ma lea itu malo uma na oo i ai le upu a le tupu ma lana tulafono,", "And in every province,"], ["ua faanoanoa tele ai sa Iutā,", "whithersoever the king's commandment and his decree came,"], ["ma ua anapogi,", "there was great mourning among the Jews, and fasting,"], ["ma fetagisi,", "and weeping,"], ["ma tagitu'i;", "and wailing;"], ["ua fofola foi e le toatele o latou moega i ie talatala ma le lefulefu.", "and many lay in sackcloth and ashes."]]},
  {num:4,words:[["Ona o atu lea o le galu teine o Eseta ma ana eunuka, ma latou ta'u atu ai ia te ia.", "So Esther's maids and her chamberlains came and told it her."], ["Ona matuā tiga ai lea o le masiofo;", "Then was the queen exceedingly grieved;"], ["ua ia avatu foi ofu e ofu ai Moretekai,", "and she sent raiment to clothe Mordecai,"], ["ma ia ave ese lona ie talatala ia te ia;", "and to take away his sackcloth from him:"], ["a e lei talia e ia.", "but he received it not."]]},
  {num:5,words:[["Ona valaau atu lea e Eseta ia Hatako,", "Then called Esther for Hatach, one of the king's chamberlains,"], ["o le tasi eunuka a le tupu,", "whom he had appointed to attend upon her,"], ["le na ia tofia mo ia,", "and gave him a commandment to Mordecai,"], ["ma na tuuina atu ia te ia le feau ia Moretekai ia iloa pe se a lena? Ona o le a foi?", "to know what it was, and why it was."]]},
  {num:6,words:[["Ona alu atu ai lea o Hatako ia Moretekai i le malae o le aai sa i luma o le faitotoa o le tupu.", "So Hatach went forth to Mordecai unto the street of the city, which was before the king's gate."]]},
  {num:7,words:[["Ona faailoa mai lea e Moretekai ia te ia o mea uma ua oo ia te ia,", "And Mordecai told him of all that had happened unto him,"], ["ma le tala tonu i le ario na fai atu ai Hamanu na te fuaina atu i mea e teu ai oloa a le tupu ona o sa Iutā,", "and of the sum of the money that Haman had promised to pay to the king's treasuries for the Jews,"], ["ina ia fano i latou.", "to destroy them."]]},
  {num:8,words:[["Na ia aumaia foi ia te ia le ata o le tusi o le tulafono na avatua mai Susana ia faaumatia i latou,", "Also he gave him the copy of the writing of the decree that was given at Shushan to destroy them,"], ["ina ia faaali atu ai ia Eseta,", "to shew it unto Esther,"], ["ma ta'u atu ia te ia,", "and to declare it unto her,"], ["ma fai atu ia te ia ia alu atu o ia i le tupu,", "and to charge her that she should go in unto the king,"], ["e aioi atu ia te ia,", "to make supplication unto him,"], ["ma faatoga atu ia te ia mo lona nuu.", "and to make request before him for her people."]]},
  {num:9,words:[["Ona sau lea o Hatako, ma ta'u mai ia Eseta upu a Moretekai.", "And Hatach came and told Esther the words of Mordecai."]]},
  {num:10,words:[["Ona tali atu lea o Eseta ia Hatako,", "Again Esther spake unto Hatach,"], ["ma na tuuina atu ia te ia le feau ia Moretekai,", "and gave him commandment unto Mordecai;"]]},
  {num:11,words:[["ua faapea ,", "All the king's servants,"], ["Ua iloa e auauna uma a le tupu,", "and the people of the king's provinces,"], ["ma tagata o itu malo o le tupu,", "do know, that whosoever,"], ["ai se tane po o se fafine e alu atu i le tupu i le lotoā i totonu,", "whether man or woman,"], ["a o lei amia,", "shall come unto the king into the inner court,"], ["e tasi lana tulafono,", "who is not called,"], ["e oti o ia;", "there is one law of his to put him to death, except such to whom the king shall hold out the golden sceptre,"], ["ua na o le e faaloaloa mai i ai e le tupu le tootoo auro e ola ai o ia. O a'u foi,", "that he may live:"], ["ua le amia a'u e alu i le tupu i aso ia e tolu sefulu.", "but I have not been called to come in unto the king these thirty days."]]},
  {num:12,words:[["Ona latou ta'u atu lea ia Moretekai o upu a Eseta.", "And they told to Mordecai Esther's words."]]},
  {num:13,words:[["Ona fai mai lea o Moretekai ia tali atu ia Eseta,", "Then Mordecai commanded to answer Esther,"], ["Ne'i e manatu i lou loto, ina ua e i ai i le aiga o le tupu,", "Think not with thyself that thou shalt escape in the king's house,"], ["e faasaoina ai oe ai sa Iutā uma.", "more than all the Jews."]]},
  {num:14,words:[["Auā afai e te matuā faalologo i nei ona po,", "For if thou altogether holdest thy peace at this time,"], ["e tupu mai le tuusaunoaina ma le laveaiina o sa Iutā mai se tasi mea;", "then shall there enlargement and deliverance arise to the Jews from another place;"], ["a o oe, ma le aiga o lou tamā e fano outou;", "but thou and thy father's house shall be destroyed:"], ["e iloa foi e ai po ua fai oe ma masiofo ona o se aso faapenei?", "and who knoweth whether thou art come to the kingdom for such a time as this?"]]},
  {num:15,words:[["Ona fai atu lea o Eseta, ia tali atu ia Moretekai,", "Then Esther bade them return Mordecai this answer,"]]},
  {num:16,words:[["Alu ia oe,", "Go,"], ["ia e faapotopoto i sa Iutā uma e o i ai i Susana,", "gather together all the Jews that are present in Shushan,"], ["ma ia anapopogi outou ona o a'u,", "and fast ye for me,"], ["aua foi ne'i outou aai,", "and neither eat nor drink three days,"], ["aua foi le inu i aso e tolu i le po ma le ao;", "night or day:"], ["o a'u foi,", "I also and my maidens will fast likewise;"], ["ma lo'u galu teine matou te anapopogi faapenā;", "and so will I go in unto the king,"], ["e faapena foi ona ou alu atu ai i le tupu o le mea e le tusa ma le tulafono;", "which is not according to the law:"], ["afai ou te oti ai,", "and if I perish,"], ["oti ai pea ia.", "I perish."]]},
  {num:17,words:[["Ona alu ai lea o Moretekai,", "So Mordecai went his way,"], ["ma na faia o mea uma e pei ona poloai atu ai e Eseta ia te ia.", "and did according to all that Esther had commanded him."]]},
];
renderVerseSet(est_ch_4_Verses, 'est-ch4-verses');

var est_ch_5_Verses = [
  {num:1,words:[["Ua oo i le aso tolu,", "Now it came to pass on the third day,"], ["ona ofu ai lea o Eseta i ofu o le masiofo,", "that Esther put on her royal apparel,"], ["ma tu atu i le lotoā o le fale o le tupu,", "and stood in the inner court of the king's house,"], ["o le lotoā i totonu i luma o le fale o le tupu,", "over against the king's house:"], ["o loo nofo mai le tupu i le nofoālii o le tupu i le fale o le tupu,", "and the king sat upon his royal throne in the royal house,"], ["ua feagai ma le faitotoa o le fale.", "over against the gate of the house."]]},
  {num:2,words:[["Ua iloa mai e le tupu o le masiofo o Eseta o loo tu atu i le lotoā,", "And it was so,"], ["ona alofaina,", "when the king saw Esther the queen standing in the court,"], ["lea o ia e ia; ua faaloaloa mai foi e le tupu lona tootoo auro na i ai i lona lima ia Eseta;", "that she obtained favour in his sight:"], ["ona faalatalata atu ai lea o Eseta,", "and the king held out to Esther the golden sceptre that was in his hand. So Esther drew near,"], ["ma pai atu i le iu o le tootoo.", "and touched the top of the sceptre."]]},
  {num:3,words:[["Ona fai mai lea o le tupu ia te ia,", "Then said the king unto her,"], ["Le masiofo e, Eseta,", "What wilt thou,"], ["se a ea lou manao? Se a le mea e te faatoga mai ai? E oo lava i le vaeluaina o le malo e avatua lava ia te oe.", "queen Esther? and what is thy request? it shall be even given thee to the half of the kingdom."]]},
  {num:4,words:[["Ona tali atu lea o Eseta, Afai e lelei i le tupu,", "And Esther answered,"], ["ia maliu atu le tupu ma Hamanu,", "If it seem good unto the king,"], ["i le asō, i le tautega ua ou saunia mo ia.", "let the king and Haman come this day unto the banquet that I have prepared for him."]]},
  {num:5,words:[["Ona fai mai lea o le tupu,", "Then the king said, Cause Haman to make haste,"], ["Ia faavave ia Hamanu ina ia fai le mea a Eseta.", "that he may do as Esther hath said."], ["Ona ō lea o le tupu ma Hamanu i le taumafataga na saunia o Eseta.", "So the king and Haman came to the banquet that Esther had prepared."]]},
  {num:6,words:[["Ona fai mai lea o le tupu ia Eseta i le taumafataga o le uaina,", "And the king said unto Esther at the banquet of wine,"], ["Se a le mea e te fai mai ai? E avatua lava ia te oe;", "What is thy petition? and it shall be granted thee:"], ["pe se a foi le mea e te faatoga mai ai? E oo lava i le vaeluagalemu o le malo e faia lava.", "and what is thy request? even to the half of the kingdom it shall be performed."]]},
  {num:7,words:[["Ona tali atu lea o Eseta,", "Then answered Esther,"], ["ua faapea atu, O le mea ou te ole atu ai,", "and said,"], ["ma faatoga atu ai o lenei;", "My petition and my request is;"]]},
  {num:8,words:[["afai ua alofaina a'u e le tupu,", "If I have found favour in the sight of the king,"], ["afai foi e lelei i le tupu ona faia le mea ou te faatoga atu ai,", "and if it please the king to grant my petition,"], ["ma ia faia le mea ou te manao i ai,", "and to perform my request,"], ["ina toe afio mai ia le tupu ma Hamanu i le tautega ou te saunia mo i laua,", "let the king and Haman come to the banquet that I shall prepare for them,"], ["ona ou faia lea taeao e pei ona fetalai mai ai o le tupu.", "and I will do to morrow as the king hath said."]]},
  {num:9,words:[["Ona alu atu lea o Hamanu i lena aso ma le olioli ma le loto fiafia;", "Then went Haman forth that day joyful and with a glad heart:"], ["a ua vaai atu Hamanu ia Moretekai i le faitotoa o le tupu,", "but when Haman saw Mordecai in the king's gate,"], ["ua le tulai,", "that he stood not up,"], ["ua le faaaloalo foi ia te ia,", "nor moved for him,"], ["ona tele ai lea o le ita o Hamanu ia Moretekai.", "he was full of indignation against Mordecai."]]},
  {num:10,words:[["A ua oono Hamanu;", "Nevertheless Haman refrained himself:"], ["ua alu atu foi i lona fale,", "and when he came home,"], ["ma na aauina atu nisi e amia ana uo,", "he sent and called for his friends,"], ["ma Seresa lana avā.", "and Zeresh his wife."]]},
  {num:11,words:[["Ona faamatalaina atu lea e Hamanu ia te i latou o le mamalu o lona tamaoaiga,", "And Haman told them of the glory of his riches,"], ["ma le toatele o ana fanau,", "and the multitude of his children,"], ["ma mea uma ua faasilisiliina ai o ia e le tupu,", "and all the things wherein the king had promoted him,"], ["ma ona ua faaeaina ai o ia ia sili i alii ma auauna a le tupu.", "and how he had advanced him above the princes and servants of the king."]]},
  {num:12,words:[["Ua fai atu foi Hamanu,", "Haman said moreover,"], ["Sa le mafai foi le masiofo o Eseta ona alu atu se isi faatasi ma le tupu i le taumafataga na ia saunia,", "Yea, Esther the queen did let no man come in with the king unto the banquet that she had prepared but myself;"], ["na o a'u lava. Ua fai mai foi ia te au e alu ia te ia a taeao faatasi ma le tupu.", "and to morrow am I invited unto her also with the king."]]},
  {num:13,words:[["A e peitai e le aoga lava ia te au o ia mea uma i aso uma ou te vaai atu ai ia Moretekai o lo sa Iutā o loo nofo i le faitotoa o le tupu.", "Yet all this availeth me nothing, so long as I see Mordecai the Jew sitting at the king's gate."]]},
  {num:14,words:[["Ona fai atu ai lea ia te ia o Seresa lana avā, ma ana uo uma,", "Then said Zeresh his wife and all his friends unto him,"], ["Ia saunia se laau, ia limagafulu kupita lona maualuga,", "Let a gallows be made of fifty cubits high,"], ["ma ia e fai atu i le tupu i le taeao,", "and to morrow speak thou unto the king that Mordecai may be hanged thereon:"], ["ia faatautauina ai Moretekai; ona e alu ai lea ma le fiafia faatasi ma le tupu i le taumafataga.", "then go thou in merrily with the king unto the banquet."], ["Ua lelei lena upu ia Hamanu;", "And the thing pleased Haman;"], ["ona ia faia lea o le laau.", "and he caused the gallows to be made."]]},
];
renderVerseSet(est_ch_5_Verses, 'est-ch5-verses');

var est_ch_6_Verses = [
  {num:1,words:[["O lena lava po na le iloa ai e le tupu sina moe. Ona fai atu lea o le tupu e au mai le tusi e faamanatu a'i tala i nofoaiga. Ona faitaulia ai lea i luma o le tupu.", "On that night could not the king sleep, and he commanded to bring the book of records of the chronicles; and they were read before the king."]]},
  {num:2,words:[["Ona iloa lea ua tusia le mea na ta'u atu e Moretekai ia Piketano ma Terese,", "And it was found written,"], ["o eunuka ia e toalua a le tupu,", "that Mordecai had told of Bigthana and Teresh,"], ["e na leoleo i le faitotoa,", "two of the king's chamberlains, the keepers of the door,"], ["o e na fia faaoo o la lima i le tupu o Asueru.", "who sought to lay hand on the king Ahasuerus."]]},
  {num:3,words:[["Ona fai atu lea o le tupu,", "And the king said,"], ["Pe se a se mea lelei ma se mamalu ua faia mo Moretekai ona o lenei mea? Ona tali mai lea o auauna a le tupu o e na auauna atu ia te ia,", "What honour and dignity hath been done to Mordecai for this? Then said the king's servants that ministered unto him,"], ["E leai se mea ua faia mo ia.", "There is nothing done for him."]]},
  {num:4,words:[["Ona fai atu lea o le tupu,", "And the king said, Who is in the court? Now Haman was come into the outward court of the king's house,"], ["O ai ea ua i le lotoā? Auā ua alu ane Hamanu i le lotoā? Auā ua alu ane Hamanu i le lotoā i fafo o le fale o le tupu e fai atu ai i le tupu ia faatautauina Moretekai i le laau ua ia saunia mo ia.", "to speak unto the king to hang Mordecai on the gallows that he had prepared for him."]]},
  {num:5,words:[["Ona tali mai lea o auauna a le tupu ia te ia,", "And the king's servants said unto him,"], ["Faauta,", "Behold,"], ["o loo tu mai Hamanu i le lotoā. Ona fai atu lea o le tupu,", "Haman standeth in the court. And the king said,"], ["Ina sau ia o ia.", "Let him come in."]]},
  {num:6,words:[["Ua ulufale mai Hamanu,", "So Haman came in. And the king said unto him,"], ["ona fai atu lea o le tupu ia te ia Se a se mea e faia i le tagata ua loto i ai le tupu ona ia faaneeneeina o ia? Ona faapea ifo lea o Hamanu i lona loto, Po o ai se isi e finagalo le tupu ona faaneeneeina o ia,", "What shall be done unto the man whom the king delighteth to honour? Now Haman thought in his heart,"], ["na o a'u lava?", "To whom would the king delight to do honour more than to myself?"]]},
  {num:7,words:[["Ona tali mai lea o Hamanu i le tupu,", "And Haman answered the king,"], ["O le tagata ua finagalo i ai le tupu ona faaneeneeina o ia,", "For the man whom the king delighteth to honour,"]]},
  {num:8,words:[["ia aumaia le ofu o le tupu e ofu ai le tupu,", "Let the royal apparel be brought which the king useth to wear,"], ["ma le solofanua e tietie ai le tupu,", "and the horse that the king rideth upon,"], ["ma le palealii o le tupu e tuuina i lona ao;", "and the crown royal which is set upon his head:"]]},
  {num:9,words:[["ia tuuina atu lena ofu ma lena solofanua i se tasi alii o alii sili ua i le tupu,", "And let this apparel and horse be delivered to the hand of one of the king's most noble princes,"], ["ma ia latou faaofu ai le tagata ua finagalo i ai le tupu ona ia faaneeneeina o ia;", "that they may array the man withal whom the king delighteth to honour,"], ["ia latou faatietie foi ia te ia i le solofanua i le malae o le aai,", "and bring him on horseback through the street of the city,"], ["ma ia latou alalaga i ona luma,", "and proclaim before him,"], ["E faapea ona faia i le tagata ua finagalo i ai le tupu ona ia faaneeneeina o ia.", "Thus shall it be done to the man whom the king delighteth to honour."]]},
  {num:10,words:[["Ona fai atu lea o le tupu ia Hamanu,", "Then the king said to Haman,"], ["Ina vave ia,", "Make haste,"], ["ia e ave le ofu ma le solofanua,", "and take the apparel and the horse,"], ["e pei ona e fai mai na,", "as thou hast said,"], ["ia e fai faapea ia Moretekai o lo sa Iutā,", "and do even so to Mordecai the Jew,"], ["o le nofo i le faitotoa o le tupu,", "that sitteth at the king's gate:"], ["aua le tuua se mea e tasi i mea uma ua e fai mai na.", "let nothing fail of all that thou hast spoken."]]},
  {num:11,words:[["Ona ave lea e Hamanu o le ofu ma le solofanua,", "Then took Haman the apparel and the horse,"], ["ma na faaofu ia Moretekai,", "and arrayed Mordecai,"], ["na ia faatietie foi ia te ia i le solofanua i le malae o le aai,", "and brought him on horseback through the street of the city,"], ["ma alaga i ona luma,", "and proclaimed before him,"], ["E faapea ona faia i le tagata ua finagalo i ai le tupu ona faaneeneeina o ia.", "Thus shall it be done unto the man whom the king delighteth to honour."]]},
  {num:12,words:[["Ona foi atu lea o Moretekai i le faitotoa o le tupu; a ua faataalise atu Hamanu i lona fale ma le faanoanoa,", "And Mordecai came again to the king's gate. But Haman hasted to his house mourning,"], ["ma ua ufiufi lona ulu.", "and having his head covered."]]},
  {num:13,words:[["Ona faamatalaina atu lea e Hamanu ia Seresa lana avā ma ana uo uma, o mea uma ua oo ia te ia.", "And Haman told Zeresh his wife and all his friends every thing that had befallen him."], ["Ona fai atu ai lea ia te ia o ona tagata popoto ma Seresa lana avā,", "Then said his wise men and Zeresh his wife unto him,"], ["Afai o so le fanau a sa Iutā o Moretekai,", "If Mordecai be of the seed of the Jews,"], ["le ua e amata ai ona paū i ona luma,", "before whom thou hast begun to fall,"], ["e te le manumalo ia te ia,", "thou shalt not prevail against him,"], ["a e matuā paū lava oe i ona luma.", "but shalt surely fall before him."]]},
  {num:14,words:[["Ona oo mai lea o eunuka a le tupu,", "And while they were yet talking with him,"], ["a o tautalatala i latou ma Hamanu, ma latou nanati ia te ia,", "came the king's chamberlains,"], ["ia alu i le taumafataga ua saunia e Eseta.", "and hasted to bring Haman unto the banquet that Esther had prepared."]]},
];
renderVerseSet(est_ch_6_Verses, 'est-ch6-verses');

var est_ch_7_Verses = [
  {num:1,words:[["Ua o atu le tupu ma Hamanu e taumamafa faatasi ma le masiofo o Eseta.", "So the king and Haman came to banquet with Esther the queen."]]},
  {num:2,words:[["Ona fai atu ai lea o le tupu ia Eseta i lena aso e lua ao fai le taumafataga o le uaina,", "And the king said again unto Esther on the second day at the banquet of wine,"], ["Le masiofo e,", "What is thy petition,"], ["Eseta,", "queen Esther? and it shall be granted thee:"], ["se a le mea e te ole mai ai? E avatua lava ia te oe;", "and what is thy request? and it shall be performed,"], ["pe se a foi le mea e te faatoga mai ai? E oo lava i le vaeluaina o le malo e faia lava.", "even to the half of the kingdom."]]},
  {num:3,words:[["Ona tali mai lea e le masiofo o Eseta,", "Then Esther the queen answered and said,"], ["ua faapea mai,", "If I have found favour in thy sight,"], ["Le tupu e, afai ua alofaina a'u e oe,", "O king,"], ["afai e lelei foi i le tupu,", "and if it please the king,"], ["se'i e faaola mai ia te au i lo'u ole atu,", "let my life be given me at my petition,"], ["ia faaola foi lo'u nuu i lo'u faatoga atu;", "and my people at my request:"]]},
  {num:4,words:[["auā ua faatauina i matou,", "For we are sold,"], ["o a'u ma lo'u nuu,", "I and my people,"], ["ina ia faaumatia,", "to be destroyed,"], ["ma ia fasiotia,", "to be slain,"], ["ma ia fano.", "and to perish."], ["A e afai ana faatauina atu i matou o tane ma fafine e fai ma pologa e ui ina le mafai i le ua ita mai ona faia o se mea e tusa ona aoga ma mea a le tupu a faamaumauina,", "But if we had been sold for bondmen and bondwomen, I had held my tongue,"], ["a ua ou faalologo.", "although the enemy could not countervail the king's damage."]]},
  {num:5,words:[["Ona fai atu lea o le tupu o Asueru,", "Then the king Ahasuerus answered and said unto Esther the queen,"], ["ua faapea atu i le masiofo o Eseta,", "Who is he, and where is he,"], ["Po o ai lena? Po o fea o iai le ua manatu i lona loto ia faia faapena?", "that durst presume in his heart to do so?"]]},
  {num:6,words:[["Ona fai mai lea o Eseta, O le tagata ua ita mai ma faasaua mai,", "And Esther said,"], ["o lenei tagata amio leaga o Hamanu.", "The adversary and enemy is this wicked Haman."], ["Ona mata'u tele ai lea o Hamanu i luma o le tupu ma le masiofo.", "Then Haman was afraid before the king and the queen."]]},
  {num:7,words:[["Ona tulai lea o le tupu nai le taumafataga o le uaina ua ita,", "And the king arising from the banquet of wine in his wrath went into the palace garden:"], ["ua alu i le fanua o le maota. Ona tulai lea o Hamanu e aioi i le masiofo o Eseta, ia faaolaina o ia;", "and Haman stood up to make request for his life to Esther the queen;"], ["auā ua ia iloa ua tonu i le tupu e faaoo ia te ia se leaga.", "for he saw that there was evil determined against him by the king."]]},
  {num:8,words:[["Ua foi atu le tupu mai le fanua o le maota i le fale na fai ai le taumafataga o le uaina,", "Then the king returned out of the palace garden into the place of the banquet of wine;"], ["ua paū foi Hamanu i le moega o i ai Eseta;", "and Haman was fallen upon the bed whereon Esther was. Then said the king,"], ["ona fai ane lea o le tupu, Pe a toso ea foi le masiofo i o'u luma i le fale? Ua mavae atu le upu i le fofoga o le tupu,", "Will he force the queen also before me in the house? As the word went out of the king's mouth,"], ["ona latou ufitia lea mata o Hamanu.", "they covered Haman's face."]]},
  {num:9,words:[["Ua fai ane foi i luma o le tupu e Harepono,", "And Harbonah, one of the chamberlains,"], ["o le tasi eunuka ia,", "said before the king,"], ["Faauta foi i le laau na saunia e Hamanu mo Moretekai o le na ta'u le mea e sao ai le tupu,", "Behold also, the gallows fifty cubits high,"], ["o loo tu i le fale o Hamanu,", "which Haman had made for Mordecai,"], ["e limagafulu kupita lona maualuga.", "who had spoken good for the king, standeth in the house of Haman."], ["Ona fai atu lea e le tupu,", "Then the king said,"], ["Ia outou faatautau ia te ia i ai.", "Hang him thereon."]]},
  {num:10,words:[["Ona latou faatautau ai lea ia Hamanu i le laau na ia saunia mo Moretekai. Ona maona ai lea o le ita o le tupu.", "So they hanged Haman on the gallows that he had prepared for Mordecai. Then was the king's wrath pacified."]]},
];
renderVerseSet(est_ch_7_Verses, 'est-ch7-verses');

var est_ch_8_Verses = [
  {num:1,words:[["O lena lava aso na foaiina atu ai e le tupu o Asueru mo le masiofo o Eseta, le fale o Hamanu o le na ita i sa Iutā.", "On that day did the king Ahasuerus give the house of Haman the Jews' enemy unto Esther the queen."], ["Ua alu atu foi Moretekai i luma o le tupu,", "And Mordecai came before the king;"], ["auā ua ta'u atu e Eseta la te aiga.", "for Esther had told what he was unto her."]]},
  {num:2,words:[["Ona to ese ai lea e le tupu o lana mama ua ia aveeseina ia Hamanu,", "And the king took off his ring, which he had taken from Haman,"], ["ma na tuuina atu ai ia Moretekai.", "and gave it unto Mordecai."], ["Ua tofia foi Moretekai e Eseta e pule i le fale o Hamanu.", "And Esther set Mordecai over the house of Haman."]]},
  {num:3,words:[["Ona toe tautala atu lea o Eseta i le tupu, ua ia faapaū foi i luma o ona vae,", "And Esther spake yet again before the king,"], ["ma tagi,", "and fell down at his feet,"], ["ma aioi ia te ia,", "and besought him with tears to put away the mischief of Haman the Agagite,"], ["ia faaliliuseina e ia le leaga a Hamanu o lo sa Akakō, ma lana manatu na ia manatu ai i sa Iutā.", "and his device that he had devised against the Jews."]]},
  {num:4,words:[["Ona faaloaloa mai lea e le tupu o le tootoo auro ia Eseta.", "Then the king held out the golden sceptre toward Esther."], ["Ona tulai ai lea o Eseta, ma tu atu i luma o le tupu,", "So Esther arose,"], ["ona ia fai atu lea,", "and stood before the king,"]]},
  {num:5,words:[["Afai e lelei i le tupu,", "And said,"], ["afai foi ua alofaina a'u e ia,", "If it please the king,"], ["ma ua tonu lenei mea i le finagalo o le tupu,", "and if I have found favour in his sight,"], ["ma ua fiafia o ia ia te au, ia tusia ina ia liliueseina tusi o le manatu a Hamanu le atalii o Hametatu,", "and the thing seem right before the king,"], ["o lo sa Akakō,", "and I be pleasing in his eyes,"], ["o le na tusi atu ina ia fano sa Iutā,", "let it be written to reverse the letters devised by Haman the son of Hammedatha the Agagite,"], ["o e o i ai i itu malo uma o le tupu;", "which he wrote to destroy the Jews which are in all the king's provinces:"]]},
  {num:6,words:[["auā ou te mafaia faapefea ona ou vaai atu i le leaga o le a oo i lo'u nuu? Ou te mafaia faapefea ona ou vaai atu i le fanoga o lo'u aiga?", "For how can I endure to see the evil that shall come unto my people? or how can I endure to see the destruction of my kindred?"]]},
  {num:7,words:[["Ona fai mai lea o le tupu o Asueru i le masiofo o Eseta,", "Then the king Ahasuerus said unto Esther the queen and to Mordecai the Jew,"], ["ma Moretekai o lo sa Iutā,", "Behold,"], ["Faauta, ua ou tuuina atu ia Eseta le fale o Hamanu,", "I have given Esther the house of Haman,"], ["ua latou faatautau foi ia te ia i le laau,", "and him they have hanged upon the gallows,"], ["auā ua na faaoo lona lima i sa Iutā.", "because he laid his hand upon the Jews."]]},
  {num:8,words:[["Ina tusi foi ia oulua ona o sa Iutā,", "Write ye also for the Jews,"], ["faitalia oulua se mea e tusi i le igoa o le tupu,", "as it liketh you, in the king's name,"], ["ma ia faamaufaailogaina i le mama a le tupu;", "and seal it with the king's ring:"], ["auā o le tusi ua tusia i le igoa o le tupu,", "for the writing which is written in the king's name, and sealed with the king's ring,"], ["ma faamaufaailogaina i le mama a le tupu e le mafai ona liliueseina.", "may no man reverse."]]},
  {num:9,words:[["Ona valaauina lea o e tusiupu a le tupu i lena lava itu aso i le tolu o masina,", "Then were the king's scribes called at that time in the third month,"], ["o le masina lea o Sevana,", "that is,"], ["i lona aso e lua sefulu ma le tolu;", "the month Sivan,"], ["ona tusia lea o mea uma e pei ona fai atu ai o Moretekai e avatu i sa Iutā,", "on the three and twentieth day thereof;"], ["ma alii sili,", "and it was written according to all that Mordecai commanded unto the Jews,"], ["ma e pule i nuu,", "and to the lieutenants, and the deputies and rulers of the provinces which are from India unto Ethiopia,"], ["ma alii e pule i itu malo e gata mai i Initia e oo atu i Aitiope,", "an hundred twenty and seven provinces,"], ["o itu malo e tasi le selau ma le lua sefulu ma le fitu;", "unto every province according to the writing thereof,"], ["na tusi atu i lea itu malo ma lea itu malo e tusa ma a latou tusilima,", "and unto every people after their language,"], ["ma lea nuu ma lea nuu e tusa ma a latou gagana,", "and to the Jews according to their writing,"], ["o sa Iutā foi e tusa ma la latou tusilima ma la latou gagana.", "and according to their language."]]},
  {num:10,words:[["Ua ia tusi atu foi i le igoa o le tupu o Asueru,", "And he wrote in the king Ahasuerus' name,"], ["ma faamaufaailogaina ai i le mama a le tupu;", "and sealed it with the king's ring,"], ["ona molia atu lea o ia tusi e ua tele vavave e na tietie i solofanua,", "and sent letters by posts on horseback,"], ["o e na tietie i manu tele vavave,", "and riders on mules,"], ["ma falata,", "camels,"], ["o tama ia a solofanua fafine.", "and young dromedaries:"]]},
  {num:11,words:[["Auā ua tuuina atu e le tupu i sa Iutā o e ua i lea aai ma lea aai,", "Wherein the king granted the Jews which were in every city to gather themselves together,"], ["ia latou potopoto,", "and to stand for their life,"], ["ma tetee atu ia ola ai i latou;", "to destroy,"], ["ia faaumatia,", "to slay,"], ["ia fasiotia,", "and to cause to perish,"], ["ma fano o 'au uma a le nuu ma le itu malo o e faasaua mai ia te i latou,", "all the power of the people and province that would assault them,"], ["o tama iti atoa ma fafine,", "both little ones and women,"], ["ma ia vetea a latou mea,", "and to take the spoil of them for a prey,"]]},
  {num:12,words:[["i le aso e tasi ia fai ai i itu malo uma o le tupu o Asueru,", "Upon one day in all the provinces of king Ahasuerus, namely,"], ["o le aso e tasi le sefulu ma le tolu o le masina e sefulu ma le lua o le masina lea o Atara.", "upon the thirteenth day of the twelfth month, which is the month Adar."]]},
  {num:13,words:[["Ua faailoa i nuu uma le tusi na tusia e avatua e fai ma tulafono i itu malo uma,", "The copy of the writing for a commandment to be given in every province was published unto all people,"], ["ina ia saunia sa Iutā i lena aso e taui ma sui e ua ita ia te i latou.", "and that the Jews should be ready against that day to avenge themselves on their enemies."]]},
  {num:14,words:[["Ua o atu e ua tele vavave e na tietie manu tele vavave, ma falata,", "So the posts that rode upon mules and camels went out,"], ["ua faataaliseina, ma faavaveina i le poloaiga a le tupu.", "being hastened and pressed on by the king's commandment."], ["Na avatua foi tulafono ai Susana le maota.", "And the decree was given at Shushan the palace."]]},
  {num:15,words:[["Ona alu atu lea o Moretekai nai luma o le tupu ua ofu i ofu o tupu,", "And Mordecai went out from the presence of the king in royal apparel of blue and white,"], ["o le ie uli,", "and with a great crown of gold,"], ["ma le ie lino sinasina, ma le pale auro tele,", "and with a garment of fine linen and purple:"], ["ma le ofu talaloa o le ie vavae ma le pāuli. Ua alalaga fiafia foi ma olioli le aai o Susana.", "and the city of Shushan rejoiced and was glad."]]},
  {num:16,words:[["Na i ai foi i sa Iutā o le malamalama,", "The Jews had light,"], ["ma le olioli,", "and gladness,"], ["ma le fiafia,", "and joy,"], ["ma le mamalu.", "and honour."]]},
  {num:17,words:[["O mea foi na oo i ai le poloaiga a le tupu ma lana tulafono,", "And in every province,"], ["i itu malo uma,", "and in every city,"], ["ma aai uma,", "whithersoever the king's commandment and his decree came,"], ["ua tupu ai le olioli ma le fiafia i sa Iutā,", "the Jews had joy and gladness,"], ["ua fai foi le tausamiga ma le aso lelei. E toatele foi tagata o le nuu ua fai ma tagata o sa Iutā;", "a feast and a good day. And many of the people of the land became Jews;"], ["auā ua matatau i latou i sa Iutā.", "for the fear of the Jews fell upon them."]]},
];
renderVerseSet(est_ch_8_Verses, 'est-ch8-verses');

var est_ch_9_Verses = [
  {num:1,words:[["O le masina e sefulu ma le lua,", "Now in the twelfth month,"], ["o le masina lea o Atara,", "that is,"], ["o lona aso e sefulu ma le tolu,", "the month Adar,"], ["a oo ina taunuu ai le poloaiga a le tupu ma lana tulafono,", "on the thirteenth day of the same,"], ["o le aso na faamoemoe ai o e na ita i sa Iutā latou te manumalo ai ia te i latou,", "when the king's commandment and his decree drew near to be put in execution, in the day that the enemies of the Jews hoped to have power over them,"], ["(a ua liua,", "(though it was turned to the contrary,"], ["ma ua manumalo ai sa Iutā i e na 'ino'ino ia te i latou;", "that the Jews had rule over them that hated them;"], [")", ")"]]},
  {num:2,words:[["na potopoto ai sa Iutā i a latou aai i itu malo uma o le tupu o Asueru,", "The Jews gathered themselves together in their cities throughout all the provinces of the king Ahasuerus,"], ["e faaoo o latou lima i e na saili e agaleaga ia te i latou;", "to lay hand on such as sought their hurt:"], ["a e lei tu mai se tasi i o latou luma;", "and no man could withstand them;"], ["auā ua matatau tagata uma ia te i latou.", "for the fear of them fell upon all people."]]},
  {num:3,words:[["Ua fesoasoani foi i sa Iutā o alii uma o itu malo,", "And all the rulers of the provinces,"], ["ma alii sili,", "and the lieutenants,"], ["ma e pule i nuu,", "and the deputies, and officers of the king,"], ["ma e na faia feau a le tupu;", "helped the Jews;"], ["auā ua matatau i latou ia Moretekai;", "because the fear of Mordecai fell upon them."]]},
  {num:4,words:[["auā ua sili Moretekai i le aiga o le tupu,", "For Mordecai was great in the king's house,"], ["ua oo foi lona logo i itu malo uma;", "and his fame went out throughout all the provinces:"], ["auā ua alualu ona sili o lenei tagata o Moretekai.", "for this man Mordecai waxed greater and greater."]]},
  {num:5,words:[["Ua fasia foi e sa Iutā o e na ita uma ia te i latou i le fasiga i le pelu,", "Thus the Jews smote all their enemies with the stroke of the sword,"], ["ma ua fasioti,", "and slaughter,"], ["ua fano;", "and destruction,"], ["ua latou faia la latou faitalia i e na 'ino'ino ia te i latou.", "and did what they would unto those that hated them."]]},
  {num:6,words:[["Ua fasiotia foi, ma faaumatia e sa Iutā i Susana le maota o tagata e lima selau,", "And in Shushan the palace the Jews slew and destroyed five hundred men."]]},
  {num:7,words:[["atoa foi ma Paresaneta,", "And Parshandatha,"], ["ma Tafono,", "and Dalphon,"], ["ma Asefata,", "and Aspatha,"]]},
  {num:8,words:[["ma Porata,", "And Poratha,"], ["ma Ataleia, ma Aritatu,", "and Adalia,"], ["ma Paremaseta,", "and Aridatha,"]]},
  {num:9,words:[["ma Arisai,", "And Parmashta,"], ["ma Arita,", "and Arisai, and Aridai,"], ["ma Vaisato.", "and Vajezatha,"]]},
  {num:10,words:[["O atalii ia e toasefulu o Hamanu le atalii o Hametatu,", "The ten sons of Haman the son of Hammedatha,"], ["o le na faasaua i sa Iutā na fasiotia i latou;", "the enemy of the Jews, slew they;"], ["a e lei vetea e i latou le oloa.", "but on the spoil laid they not their hand."]]},
  {num:11,words:[["O lena aso na avatua ai i le tupu le faitau aofai o e na fasiotia i Susana le maota.", "On that day the number of those that were slain in Shushan the palace was brought before the king."]]},
  {num:12,words:[["Ona fai atu lea o le tupu i le masiofo o Eseta,", "And the king said unto Esther the queen,"], ["Ua fasiotia, ma faaumatia e sa Iutā i Susana le maota o tagata e lima selau,", "The Jews have slain and destroyed five hundred men in Shushan the palace,"], ["atoa ma atalii o Hamanu e toasefulu;", "and the ten sons of Haman;"], ["se a se mea ua latou faia i isi itumalo uma o le tupu? O lenei, se a se mea e te toe ole mai ai? E avatua ia te oe;", "what have they done in the rest of the king's provinces? now what is thy petition? and it shall be granted thee:"], ["se a foi se mea e te toe faatoga mai i ai? E faia lava.", "or what is thy request further? and it shall be done."]]},
  {num:13,words:[["Ona tali mai lea o Eseta,", "Then said Esther,"], ["Afai a lelei i le tupu,", "If it please the king,"], ["ia tuuina foi taeao i sa Iutā o e i Susuna ona ia faia e pei o le tulafono i le asō,", "let it be granted to the Jews which are in Shushan to do to morrow also according unto this day's decree,"], ["ma ia latou faatautauina i le laau atalii o Hamanu e toatinoagafulu.", "and let Haman's ten sons be hanged upon the gallows."]]},
  {num:14,words:[["Ona fai atu lea o le tupu,", "And the king commanded it so to be done: and the decree was given at Shushan;"], ["Ia faia faapea. Ona tala'iina lea o le tulafono i Susana. Ona faatautauina lea e i latou atalii o Hamanu e toatinoagafulu.", "and they hanged Haman's ten sons."]]},
  {num:15,words:[["Ua potopoto foi sa Iutā e na i Susana i le aso e sefulu ma le fa o le masina o Atara,", "For the Jews that were in Shushan gathered themselves together on the fourteenth day also of the month Adar,"], ["ona latou fasiotia lea i Susana o tagata e tolu selau;", "and slew three hundred men at Shushan;"], ["a e lei vetea e i latou le oloa.", "but on the prey they laid not their hand."]]},
  {num:16,words:[["O sa Iutā uma foi e na i ai i itu malo o le tupu,", "But the other Jews that were in the king's provinces gathered themselves together,"], ["na potopoto i latou e tetee atu ia ola ai i latou,", "and stood for their lives,"], ["ona mapu ai lea o i latou i e na ita ia te i latou;", "and had rest from their enemies, and slew of their foes seventy and five thousand,"], ["na latou fasiotia foi e na 'ino'ino ia te i latou e fitu sefulu o afe ma afe e lima a e lei vetea e i latou le oloa,", "but they laid not their hands on the prey,"]]},
  {num:17,words:[["o le aso e sefulu ma le tolu o le masina o Atara na fasia ai;", "On the thirteenth day of the month Adar;"], ["ona mapu ai lea o i latou i lona aso e sefulu ma le fa, ma fai ai lena ma aso e fai ai le tausamiga,", "and on the fourteenth day of the same rested they,"], ["ma olioli ai.", "and made it a day of feasting and gladness."]]},
  {num:18,words:[["O lona aso e sefulu ma le tolu,", "But the Jews that were at Shushan assembled together on the thirteenth day thereof,"], ["ma lona aso e sefulu ma le fa na potopoto ai sa Iutā e na i Susana;", "and on the fourteenth thereof;"], ["ona mapu ai lea o i latou i lona aso e sefulu ma le lima, ma ua fai lena ma aso e fai ai le tausamiga,", "and on the fifteenth day of the same they rested,"], ["ma olioli ai.", "and made it a day of feasting and gladness."]]},
  {num:19,words:[["O le mea lea na fai ai e sa Iutā sa i faoa aai,", "Therefore the Jews of the villages,"], ["e na nonofo i aai e le nofo 'olo,", "that dwelt in the unwalled towns,"], ["o le aso e sefulu ma le fa o le masina o Atara ma aso lelei e olioli ai,", "made the fourteenth day of the month Adar a day of gladness and feasting,"], ["ma fai ai le tausamiga,", "and a good day,"], ["ma feaveai ai tufaaga.", "and of sending portions one to another."]]},
  {num:20,words:[["Na tusia foi e Moretekai o ia mea,", "And Mordecai wrote these things,"], ["na ia avatua foi tusi i sa Iutā uma e na i ai i itu malo uma o le tupu o Asueru,", "and sent letters unto all the Jews that were in all the provinces of the king Ahasuerus,"], ["o e na latalata mai atoa ma e mamao atu,", "both nigh and far,"]]},
  {num:21,words:[["e faamau ai ia te i latou,", "To stablish this among them,"], ["ona ia faia le aso e sefulu ma le fa o le masina o Atara,", "that they should keep the fourteenth day of the month Adar, and the fifteenth day of the same,"], ["ma lona aso e sefulu ma le lima i tausaga uma,", "yearly,"]]},
  {num:22,words:[["auā o aso ia na mapu ai sa Iutā i e na ita ia te i latou,", "As the days wherein the Jews rested from their enemies,"], ["o le masina foi na liliuina ai mo i latou o le faanoanoa i le olioli,", "and the month which was turned unto them from sorrow to joy,"], ["ma le faavauvau i le aso lelei; ona ia faia ia aso ma aso e fai ai le tausamiga,", "and from mourning into a good day:"], ["ma olioli ai,", "that they should make them days of feasting and joy,"], ["ma feaveai ai tufaaga,", "and of sending portions one to another,"], ["ma mea alofa i e matitiva.", "and gifts to the poor."]]},
  {num:23,words:[["Ona talia lea e sa Iutā e fai ma tu o mea na latou amata ona faia,", "And the Jews undertook to do as they had begun,"], ["ma mea na tusi atu ai e Moretekai ia te i latou;", "and as Mordecai had written unto them;"]]},
  {num:24,words:[["auā o Hamanu le atalii o Hametatu o lo sa Akakō,", "Because Haman the son of Hammedatha, the Agagite,"], ["o le na faasaua i sa Iutā uma,", "the enemy of all the Jews,"], ["na ia manatu i sa Iutā ona ia fano i latou. Na ia fai foi le Puro,", "had devised against the Jews to destroy them,"], ["o le vili lea,", "and had cast Pur, that is,"], ["ina ia faaumatia i latou,", "the lot, to consume them,"], ["ma ia fano i latou.", "and to destroy them;"]]},
  {num:25,words:[["A ua alu atu Eseta i le tupu,", "But when Esther came before the king, he commanded by letters that his wicked device,"], ["ona poloai atu ai lea e ia i lana tusi ia toe foi atu i lona lava ulu lana manatu leaga na ia manatu ai i sa Iutā,", "which he devised against the Jews,"], ["ma ia faatautauina o ia ma ona atalii i le laau.", "should return upon his own head, and that he and his sons should be hanged on the gallows."]]},
  {num:26,words:[["O le mea lea na ta'ua ai o ia aso o Puro, i le igoa o le Puro.", "Wherefore they called these days Purim after the name of Pur."], ["O mea uma foi o le tusi,", "Therefore for all the words of this letter,"], ["ma mea na latou vaavaaia i lenei mea,", "and of that which they had seen concerning this matter,"], ["ma mea na oo ia te i latou,", "and which had come unto them,"]]},
  {num:27,words:[["na faamauina ai e sa Iutā,", "The Jews ordained,"], ["ma talia ai mo i latou ma a latou fanau,", "and took upon them,"], ["ma e ua faatasia ma i latou,", "and upon their seed, and upon all such as joined themselves unto them,"], ["ia le toe mavae ona faia o ia lava aso e lua e tusa ma a latou tusi,", "so as it should not fail,"], ["i ona lava po,", "that they would keep these two days according to their writing,"], ["i tausaga uma;", "and according to their appointed time every year;"]]},
  {num:28,words:[["ma ia manatua ma faia o ia lava aso i tupulaga uma,", "And that these days should be remembered and kept throughout every generation,"], ["i lea aiga ma lea aiga,", "every family,"], ["i lea itu malo ma lea itu malo,", "every province,"], ["i lea aai ma lea aai;", "and every city;"], ["aua foi le toe mavae i sa Iutā o ia lava aso o Puro,", "and that these days of Purim should not fail from among the Jews,"], ["ma ia le tuua le faamanatunatu i ai i la latou fanau.", "nor the memorial of them perish from their seed."]]},
  {num:29,words:[["O le masiofo o Eseta,", "Then Esther the queen,"], ["le afafine o Aviaila,", "the daughter of Abihail,"], ["ma Moretekai o lo sa Iutā,", "and Mordecai the Jew, wrote with all authority,"], ["na la tusi atu ma le pule lava e faamauina ai lenei lua o tusi i Puro.", "to confirm this second letter of Purim."]]},
  {num:30,words:[["Ua ia avatua foi tusi i sa Iutā uma i itu malo e tasi le selau e lua sefulu ma le fitu o le malo o Asueru,", "And he sent the letters unto all the Jews, to the hundred twenty and seven provinces of the kingdom of Ahasuerus,"], ["o upu alofa ma le faamaoni,", "with words of peace and truth,"]]},
  {num:31,words:[["ina ia faamauina o ia aso o Puro i ona lava po,", "To confirm these days of Purim in their times appointed,"], ["e pei ona pule e Moretekai o lo sa Iutā ma le masiofo o Eseta ia te i latou,", "according as Mordecai the Jew and Esther the queen had enjoined them,"], ["e pei ona latou faatuina foi mo i latou ma a latou fanau,", "and as they had decreed for themselves and for their seed,"], ["o mea o anapogi ma lo latou alalaga.", "the matters of the fastings and their cry."]]},
  {num:32,words:[["O le poloaiga a Eseta na faamauina ai o ia mea o Puro;", "And the decree of Esther confirmed these matters of Purim;"], ["na tusia ai foi i le tusi.", "and it was written in the book."]]},
];
renderVerseSet(est_ch_9_Verses, 'est-ch9-verses');

var est_ch_10_Verses = [
  {num:1,words:[["Na totogi atu e le tupu o Asueru i le vao nuu, ma nuu tuloto i tai,", "And the king Ahasuerus laid a tribute upon the land,"], ["ia faia le taulaga ia te ia.", "and upon the isles of the sea."]]},
  {num:2,words:[["O mea uma na faia i lana pule ma lona malosi,", "And all the acts of his power and of his might,"], ["ma le tala i le silisili o Moretekai na faasilisiliina ai o ia e le tupu,", "and the declaration of the greatness of Mordecai, whereunto the king advanced him,"], ["e lei tusia ea ia mea i le tusi o tala i nofoaiga a tupu o Metai ma Peresia?", "are they not written in the book of the chronicles of the kings of Media and Persia?"]]},
  {num:3,words:[["Auā na aupito Moretekai o lo sa Iutā i le tupu o Asueru;", "For Mordecai the Jew was next unto king Ahasuerus,"], ["na silisili o ia i sa Iutā;", "and great among the Jews,"], ["na fiafia ia te ia le toatele o ona uso;", "and accepted of the multitude of his brethren,"], ["ua saili e ia ia manuia lona nuu;", "seeking the wealth of his people,"], ["ua tautala foi ma le alofa i lona nuu uma.", "and speaking peace to all his seed."]]},
];
renderVerseSet(est_ch_10_Verses, 'est-ch10-verses');

})();