(function() {
var _est_ch_1_Verses = [
  {num:1,words:[["O ona po o Asueru,", "then night of Asueru"], ["o Asueru lea o le", "Asueru the"], ["na fai ma tupu", "to be king"], ["e gata mai i Initia", "to a snake from in Initia"], ["e oo atu i Aitiope,", "it shall come to pass in Aitiope"], ["i itu malo", "in side government"], ["e tasi", "by one"], ["le selau", "the hundred"], ["e lua sefulu", "by two ten"], ["ma le fitu;", "and seven"]]},
  {num:2,words:[["o ona po ia,", "then night to"], ["ina o nofo", "so that of dwell"], ["le tupu o Asueru", "the king of Asueru"], ["i le nofoālii", "in the throne"], ["o lona malo,", "his government"], ["sa i ai", "therein"], ["i Susana", "in Susana"], ["le maota,", "the the name of a tree"]]},
  {num:3,words:[["o le tolu o tausaga", "the three of year"], ["o lana nofoaiga", "his reign"], ["na ia fai ai le tausamiga mā alii uma", "to make the feast First person dual exclusive Lord all"], ["ua ia te ia ma ana auauna;", "to him and his servant"], ["o e ua sili o Peresia", "who most of Persia"], ["ma Metai,", "and Metai"], ["o alii", "Lord"], ["ma alii o itu malo,", "and Lord of side government"], ["na i ona luma;", "before him"]]},
  {num:4,words:[["ina o faaaliatua", "so that of faaaliatua"], ["le sosia", "the sosia"], ["o lona malo mamalu,", "his government glory"], ["ma le silisili", "and the very much"], ["o le matagofie", "the beautiful"], ["o lona malualii,", "his malualii"], ["i aso e tele,", "in day to great"], ["o aso e selau", "day by hundred"], ["ma le valu sefulu.", "and eight ten"]]},
  {num:5,words:[["Ua atoatoa ia aso,", "completely to day"], ["ona fai ai lea e le tupu", "and make by the king"], ["o le tausamiga mā tagata uma", "the feast First person dual exclusive man all"], ["na i Susana", "in Susana"], ["le maota,", "the the name of a tree"], ["o alii", "Lord"], ["atoa ma tagata nuu,", "and man nation"], ["i aso e fitu,", "in day by seven"], ["i le lotoā", "in the court"], ["o le fanua", "the land"], ["o le maota", "the the name of a tree"], ["o le tupu.", "the king"]]},
  {num:6,words:[["Na tautau ai ie lino sinasina;", "to hang up faamaise linen white"], ["o ie lelei ma ie uli,", "faamaise good and faamaise black"], ["na faamauina", "established"], ["i maea vavae", "in rope to divide"], ["ma le pāuli", "and the pāuli"], ["i mama ario", "in n silver"], ["ma pou sesa;", "and pillar Caesar"], ["na i ai moega auro", "therein bed gold"], ["ma ario", "and silver"], ["i luga o le paepae", "upon the to heap up"], ["o paata,", "to forbid"], ["ma sesa,", "and Caesar"], ["ma tara,", "and tara"], ["ma sokere.", "and sokere"]]},
  {num:7,words:[["Na avatu ipu auro latou te feinu ai,", "give away cup gold they feinu"], ["o ipu", "cup"], ["e tino eseese,", "to body divided"], ["ma uaina", "and wine"], ["a le tupu e tele,", "but the king to great"], ["e pei ona", "as"], ["tatau i le tupu.", "to wring out in the king"]]},
  {num:8,words:[["Na faatatau foi i le tulafono", "liken also in the law"], ["ona inu;", "and drink"], ["ua leai se", "there was no"], ["na faatauanau atu i se tasi;", "make to be urgent in a one"], ["auā sa faapea ona", "for saying then"], ["poloai e le tupu", "command by the king"], ["i e pule uma", "in to rule all"], ["i lona aiga,", "in his family"], ["ia taitasi", "to each"], ["le tagata", "the man"], ["ma lana faitalia.", "and his as I"]]},
  {num:9,words:[["O Vasati foi le masiofo,", "Vasati also the wife of a Samoan paramount chief"], ["na ia faia le tausamiga mā fafine", "he made the feast First person dual exclusive woman"], ["i le fale", "in the house"], ["o le tupu,", "the king"], ["o le fale lea o le tupu", "the house the king"], ["o Asueru.", "Asueru"]]},
  {num:10,words:[["O le aso e fitu", "the day by seven"], ["ina o fiafia", "so that of competition"], ["le loto", "the heart"], ["o le tupu", "the king"], ["i le uaina,", "in the wine"], ["na ia fai atu ai ia", "he said to"], ["Meumanu,", "Meumanu"], ["ma Piseta,", "and Piseta"], ["ma Harepona,", "and Harepona"], ["ma Pigeta,", "and Pigeta"], ["ma Avageta,", "and Avageta"], ["o Setara", "Setara"], ["ma Karekase,", "and Karekase"], ["o eunuka ia", "eunuch to"], ["e toafitu", "to seven (people)"], ["e na auauna atu i luma o le tupu", "by servant before the king"], ["o Asueru,", "Asueru"]]},
  {num:11,words:[["ia au mai le masiofo", "to bring the wife of a Samoan paramount chief"], ["o Vasati", "Vasati"], ["i luma o le tupu,", "before the king"], ["ma le palealii", "and the palealii"], ["o le masiofo,", "the wife of a Samoan paramount chief"], ["ina ia faaali atu lona lalelei", "so that revealed his beautiful"], ["i le nuu", "in the land"], ["ma alii;", "and Lord"], ["auā e lalelei lava o ia.", "for to beautiful indeed he"]]},
  {num:12,words:[["A e lei mafai", "but by not able"], ["le masiofo o Vasati", "the wife of a Samoan paramount chief of Vasati"], ["ona alu ane", "and go along"], ["i le feau", "in the errand"], ["a le tupu", "but the king"], ["na o atu ai eunuka;", "of eunuch"], ["ona matuā ita ai lea o le tupu,", "and exceedingly angry the king"], ["na tupu tele lava", "king great indeed"], ["le tiga", "the grieved"], ["o lona loto.", "his heart"]]},
  {num:13,words:[["Ona fai atu lea o le tupu", "And he said the king"], ["i e popoto,", "in to round (as the trunk of a"], ["e na iloa tausaga;", "by knew year"], ["(auā na faapea", "for thus"], ["le masani", "the a custom"], ["a le tupu ia te i latou", "but the king unto them"], ["uma na iloa tulafono", "all knew law"], ["ma faamasinoga;", "and judgment"]]},
  {num:14,words:[["na latalata ane ia te ia o Karesena,", "near to him of Karesena"], ["o Setaru,", "Setaru"], ["o Atematu,", "Atematu"], ["o Tasesa,", "Tasesa"], ["o Merese,", "Merese"], ["o Maresena,", "Maresena"], ["o Memukana,", "Memukana"], ["o alii ia", "Lord to"], ["e toafitu o Peresia", "to seven (people) of Persia"], ["ma Metai o e", "and Metai who"], ["na iloa fofoga", "knew face"], ["o le tupu,", "the king"], ["e na sili", "by most"], ["i le malo;)", "in the government"]]},
  {num:15,words:[["Se a se mea e faia", "a but a thing to made"], ["i le masiofo o Vasati,", "in the wife of a Samoan paramount chief of Vasati"], ["e tusa ma le tulafono,", "according to the law"], ["ina ua", "so that"], ["le mafai o ia i le upu", "the able he in the word"], ["a le tupu o Asueru", "but the king of Asueru"], ["na o atu ai eunuka?", "of eunuch"]]},
  {num:16,words:[["Ona tali mai lea o Memukana", "and respond from of Memukana"], ["i luma o le tupu ma alii,", "before the king and Lord"], ["E le", "by the"], ["na o le tupu", "the king"], ["na aga faapiopio", "to do faapiopio"], ["i ai le masiofo o Vasati,", "therein the wife of a Samoan paramount chief of Vasati"], ["a e", "but by"], ["atoa ma alii uma", "and Lord all"], ["ma tagata uma o", "and people all of"], ["i itu malo uma", "in side government all"], ["o le tupu o Asueru;", "the king of Asueru"]]},
  {num:17,words:[["auā e oo atu le tala", "for it shall come to pass the side"], ["i le masiofo", "in the wife of a Samoan paramount chief"], ["i fafine uma ona", "in woman all then"], ["inosia ai lea e i latou", "abominable by them"], ["o a latou tane,", "but they man"], ["pe a latou ta'u ane,", "whether but they tell"], ["Na poloai atu le tupu", "command the king"], ["o Asueru ia au mai i ona luma", "Asueru to bring before him"], ["le masiofo o Vasati,", "the wife of a Samoan paramount chief of Vasati"], ["a e lei alu ane", "but by not go along"], ["o ia.", "he"]]},
  {num:18,words:[["O tamaitai foi o Peresia", "woman also of Persia"], ["ma Metai", "and Metai"], ["e ua faalogo", "by heard"], ["i le tala", "in the side"], ["i le masiofo,", "in the wife of a Samoan paramount chief"], ["e fai atu ai", "to said to"], ["i latou", "them"], ["i le aso nei", "in the day this"], ["i alii uma", "in Lord all"], ["ua i le tupu,", "in the king"], ["ona tele ai lea o le 'ino'ino", "and great the hate"], ["ma le feitagai.", "and the look upon one another"]]},
  {num:19,words:[["Afai e lelei", "if to good"], ["i le tupu,", "in the king"], ["ia oo atu lana afioga", "to arrived his word (divine)"], ["mai ia te ia lava,", "from him indeed"], ["ma ia tusia faatasi ma tulafono", "and to written together and law"], ["a Peresia", "of Persia"], ["ma Metai,", "and Metai"], ["e le toe tālaina,", "by the again tālaina"], ["aua le toe oo mai o Vasati", "do not again came of Vasati"], ["i luma o le tupu", "before the king"], ["o Asueru;", "Asueru"], ["a ia fai", "but to make"], ["se masiofo", "a wife of a Samoan paramount chief"], ["a le tupu", "but the king"], ["e sui ai o ia,", "to to dilute he"], ["o se tasi", "a one"], ["e sili", "to most"], ["ona lelei ia te ia.", "and good to him"]]},
  {num:20,words:[["A logo atu foi le pule", "but to hear also the rule"], ["a le tupu,", "but the king"], ["na te faia,", "he made"], ["i lona malo uma,", "in his government all"], ["auā ua tele lea,", "for great"], ["ona faaaloalo ai lea o fafine uma", "and faaaloalo of woman all"], ["i a latou tane,", "in but they man"], ["o alii", "Lord"], ["atoa ma tagatā nuu.", "and tagatā nation"]]},
  {num:21,words:[["Ua lelei foi lena upu", "that it was good also that word"], ["i le manatu", "in the thought"], ["o le tupu ma alii;", "the king and Lord"], ["ona faia lea e le tupu", "And he made by the king"], ["e pei ona fai atu ai Memukana.", "as said to Memukana"]]},
  {num:22,words:[["Ua ia avatu tusi", "to give away book"], ["i itu malo uma", "in side government all"], ["o le tupu,", "the king"], ["ua faatatau", "liken"], ["ma le tusilima", "and the tusilima"], ["a lea itu malo", "but side government"], ["ma lea itu malo,", "and side government"], ["e tusa foi ma le gagana", "to according to also and the language"], ["a lea nuu", "but nation"], ["ma lea nuu,", "and nation"], ["ina ia taitoatasi", "so that each one"], ["le tane ma pule i lona aiga,", "the man and rule in his family"], ["ma ia tautala", "and to spoke"], ["i le gagana", "in the language"], ["a lona nuu.", "but his nation"]]},
];
renderVerseSet(_est_ch_1_Verses, 'est-ch1-verses');

var _est_ch_2_Verses = [
  {num:1,words:[["Ua mavae ia mea,", "after these things"], ["ua maona foi le ita", "to subside also the angry"], ["o le tupu o Asueru,", "the king of Asueru"], ["ona manatua lea e ia o Vasati,", "and remember by him of Vasati"], ["ma le mea", "and the thing"], ["na ia faia,", "he made/did"], ["i le", "in the"], ["ma le tulafono", "and the law"], ["na faia ia te ia.", "made to him"]]},
  {num:2,words:[["Ona fai atu ai lea o auauna,", "and said to of servant"], ["e na auauna", "by servant"], ["i le tupu,", "in the king"], ["Ia sailiili mai mā", "to search from First person dual exclusive"], ["le tupu o teine taupou lalelei.", "the king of girl virgin beautiful"]]},
  {num:3,words:[["Ia tofia foi e le tupu", "to chosen also by the king"], ["o matai", "chief"], ["i itu malo uma", "in side government all"], ["o lona malo,", "his government"], ["latou te faapotopotoina teine taupou lalelei uma", "they gathered together girl virgin beautiful all"], ["i Susana", "in Susana"], ["le maota,", "the the name of a tree"], ["i le fale o fafine,", "in the house of woman"], ["ia Hege", "to Hege"], ["le eunuka", "the eunuch"], ["a le tupu,", "but the king"], ["o lē tausi", "not keep"], ["i fafine;", "in woman"], ["ma ia avatua ia te i latou", "and to given away unto them"], ["mea e faamamāina a'i", "thing to make clean"], ["i latou.", "them"]]},
  {num:4,words:[["O le teine foi e fiafia", "the girl also to competition"], ["i ai le tupu ia", "therein the king to"], ["avea o ia ma masiofo", "become he and wife of a Samoan paramount chief"], ["e sui ai Vasati.", "to to dilute Vasati"], ["Ua lelei lea upu", "that it was good word"], ["i le manatu", "in the thought"], ["o le tupu;", "the king"], ["ona ia faia lea faapea.", "and to made thus"]]},
  {num:5,words:[["Ua i ai", "therein"], ["i Susana", "in Susana"], ["le maota", "the the name of a tree"], ["o le tasi tagata o", "the one man of"], ["sa Iutā,", "of the clan of Iutā"], ["o Moretekai lona igoa,", "Mordecai his name"], ["o le atalii o Iairo,", "the son of Iairo"], ["o le atalii ia o Semi,", "the son to of Shimei"], ["o le atalii ia o Kiso,", "the son to of Kiso"], ["o lo", "lo"], ["sa Peniaminā.", "of the clan of Peniaminā"]]},
  {num:6,words:[["Ua tāfea mai o ia", "tāfea from he"], ["mai Ierusalema faatasi ma le tafeaga", "from Jerusalem together and the exiles in wa^"], ["na tāfea faatasi ma Iekonia", "tāfea together and Iekonia"], ["le tupu o Iuta,", "the king of Judas"], ["o le", "the"], ["na tāfea", "tāfea"], ["e Nepukanesa", "to Nebuchadnezzar"], ["le tupu o Papelonia.", "the king of Babylon"]]},
  {num:7,words:[["Ua fai o ia ma tamā", "make he and father"], ["o Hatesa,", "Hatesa"], ["o Eseta foi lea,", "Esther also"], ["o le afafine", "the daughter"], ["o le uso", "the brother"], ["o lona tamā,", "his father"], ["ina ua leai sona tamā po", "so that there was not sona father night"], ["o sona tinā;", "sona mother"], ["o le teine foi", "the girl also"], ["ua lalelei lona tino,", "beautiful his body"], ["ma ua lalelei", "and beautiful"], ["ona mata.", "and eye"], ["Ua oti lona tamā", "die his father"], ["ma lona tinā,", "and his mother"], ["ona avea ai lea o ia", "and become he"], ["e Moretekai", "to Mordecai"], ["e fai mona afafine.", "to make to burst forth (as faiai daughter"]]},
  {num:8,words:[["Ua lagona e ia", "to understand by him"], ["le upu", "the word"], ["a le tupu ma lana tulafono,", "but the king and his law"], ["ma ua faapotopotoina ai teine", "and gathered together girl"], ["e toatele", "many"], ["i Susana", "in Susana"], ["le maota ia Hege,", "the the name of a tree to Hege"], ["ona avea ai lea o Eseta", "and become of Esther"], ["i le fale", "in the house"], ["o le tupu ia", "the king to"], ["Hege,", "Hege"], ["lē tausi", "not keep"], ["i fafine.", "in woman"]]},
  {num:9,words:[["Ua lelei", "that it was good"], ["le teine", "the girl"], ["i lona manatu,", "in his thought"], ["ua alofaina o ia", "beloved he"], ["e ia;", "by him"], ["ona ia vave tuuina atu ai lea", "and to quick given"], ["ia te ia", "to him"], ["ana mea e faamamāina a'i,", "his thing to make clean"], ["atoa ma mea", "and thing"], ["na tofia māna,", "chosen māna"], ["ma teine", "and girl"], ["e toafitu", "to seven (people)"], ["e na filifilia", "by chosen"], ["mai le aiga o le tupu", "from the family the king"], ["e tuuina atu ia te ia;", "shall be given to him"], ["ua ia tuu atu foi ia te ia ma lona galu teine", "to placed also to him and his wave girl"], ["i le mea sili", "in the thing most"], ["i le fale o fafine.", "in the house of woman"]]},
  {num:10,words:[["E lei faailoa atu e Eseta lona nuu po", "by not declared to Esther his nation night"], ["o lona aiga;", "his family"], ["auā na fai atu e Moretekai", "for said to Mordecai"], ["ia te ia", "to him"], ["aua na te faailoa atu.", "for he declared"]]},
  {num:11,words:[["O lea aso", "therefore day"], ["ma lea aso foi", "and day also"], ["na fealualuai ai o Moetekai", "walk about of Moetekai"], ["i luma o le lotoā", "before the court"], ["o le fale o fafine", "the house of woman"], ["ina ia iloa po o malolo Eseta;", "so that known night of rest Esther"], ["pe se a foi", "whether a but also"], ["se mea e faia ia te ia.", "a thing to made to him"]]},
  {num:12,words:[["Na aua'i", "present"], ["ona solo taitoatasi o teine", "and to move swiftly each one of girl"], ["i lo latou", "in the they"], ["o atu i le tupu", "in the king"], ["o Asueru", "Asueru"], ["ina ua atoatoa masina", "so that completely moon"], ["e sefulu", "by ten"], ["ma le lua,", "and two"], ["e tusa ma le tulafono", "according to the law"], ["i fafine;", "in woman"], ["auā na faapea ona", "for thus then"], ["atoatoa ai o aso", "completely of day"], ["o le faamamāina o", "the make clean of"], ["i latou;", "them"], ["o masina", "moon"], ["e ono", "by six"], ["e uu ai", "to oil"], ["i le suāuu muro,", "in the suāuu muro"], ["ma masina", "and moon"], ["e ono", "by six"], ["i mea manogi,", "in thing fragrant"], ["ma mea e faamamāina a'i fafine.", "and thing to make clean woman"]]},
  {num:13,words:[["Ua faapea foi", "saying also"], ["ona alu atu o le teine", "and go away the girl"], ["i le tupu;", "in the king"], ["na avatua ia te ia mea uma", "given away to him all things"], ["na ia fai atu ai e alu ai", "he said to go"], ["ma ia mai le fale", "and to from the house"], ["o fafine", "woman"], ["i le fale", "in the house"], ["o le tupu.", "the king"]]},
  {num:14,words:[["O le afiafi", "the evening"], ["na alu atu ai o ia,", "go away he"], ["o le taeao foi", "the morning also"], ["na toe foi ai", "again also"], ["i le lua o fale", "in the two of house"], ["o fafine ia Sasekasa", "woman to Sasekasa"], ["le eunuka", "the eunuch"], ["a le tupu,", "but the king"], ["o le leoleo", "the guard"], ["i palake;", "in palake"], ["na ia le toe alu atu i le tupu,", "to the again go away in the king"], ["vagana ona fiafia", "save then competition"], ["o le tupu ia te ia,", "the king to him"], ["ma ua valaauina lona igoa.", "and called his name"]]},
  {num:15,words:[["Ua oo foi ia", "it came to pass also to"], ["Eseta le afafine o Aviaila", "Esther the daughter of Aviaila"], ["le uso", "the brother"], ["o le tamā o Moretekai,", "the father of Mordecai"], ["o le", "the"], ["na faia o ia", "made he"], ["mona afafine,", "to burst forth (as faiai daughter"], ["ona alu atu i le tupu,", "and go away in the king"], ["e lei fai atu ai o ia i se mea", "by not said to he in a thing"], ["ua na o mea", "of thing"], ["na fai atu ai Hege", "said Hege"], ["le eunuka", "the eunuch"], ["a le tupu,", "but the king"], ["o le tausi fafine.", "the keep woman"], ["Ua alofagia foi Eseta", "favored also Esther"], ["e i latou uma", "by them all"], ["e na iloa o ia.", "by knew he"]]},
  {num:16,words:[["Ua avea Eseta", "become Esther"], ["i le tupu o Asueru", "in the king of Asueru"], ["i le fale", "in the house"], ["o le tupu", "the king"], ["i le sefulu o masina,", "in the ten of moon"], ["o le masina lea o Tapeta,", "the moon of Tapeta"], ["i le fitu o tausaga", "in the seven of year"], ["o lana nofoaiga.", "his reign"]]},
  {num:17,words:[["Ua sili foi le manao", "most also the desire"], ["o le tupu ia", "the king to"], ["Eseta i fafine uma,", "Esther in woman all"], ["ua sili foi", "most also"], ["ona alofaina", "and beloved"], ["ma faapelepeleina o ia", "and to take care of he"], ["e ia i taupou uma;", "by him in virgin all"], ["ona ia tuu atu ai lea o le palealii", "and to placed the palealii"], ["i lona ulu,", "in his head"], ["ma fai o ia ma masiofo", "and make he and wife of a Samoan paramount chief"], ["e sui a'i Vasati.", "to to dilute Vasati"]]},
  {num:18,words:[["Ona faia lea e le tupu", "And he made by the king"], ["o le tausamiga tele mā alii uma", "the feast great First person dual exclusive Lord all"], ["ua ia te ia ma ana auauna,", "to him and his servant"], ["o le tausamiga", "the feast"], ["ona o Eseta;", "because of Esther"], ["na ia tuuina atu ia", "he gave to"], ["malolo tagata o itu malo,", "rest man of side government"], ["na ia foai atu foi mea alofa", "to give also thing love"], ["e pei ona", "as"], ["tatau i le tupu.", "to wring out in the king"]]},
  {num:19,words:[["Ua nofo Moretekai", "dwell Mordecai"], ["i le faitotoa o le tupu,", "at the door the king"], ["ina o faapotopotoina faalua o taupou.", "so that of gathered together twice of virgin"]]},
  {num:20,words:[["E lei faailoa atu e Eseta lona aiga po", "by not declared to Esther his family night"], ["o lona nuu;", "his nation"], ["e pei ona fai atu ai Moretekai", "as said to Mordecai"], ["ia te ia;", "to him"], ["auā na faia e Eseta mea", "for made to Esther thing"], ["na fai atu ai Moretekai,", "said Mordecai"], ["e pei ona", "as"], ["ia faia", "to made"], ["ina o tausia o ia", "so that of kept he"], ["e ia.", "by him"]]},
  {num:21,words:[["O ona po ia", "then night to"], ["ina o nofo Moretekai", "so that of dwell Mordecai"], ["i le faitotoa o le tupu,", "at the door the king"], ["na ita ai Piketano", "angry Piketano"], ["ma Tirese,", "and Tirese"], ["o eunuka ia", "eunuch to"], ["e toalua", "to two (people)"], ["a le tupu,", "but the king"], ["o e", "who"], ["na leoleo", "guard"], ["i le faitotoa,", "at the door"], ["na la fia faaoo foi", "la want to do something bring upon also"], ["o la lima", "la five"], ["i le tupu o Asueru.", "in the king of Asueru"]]},
  {num:22,words:[["Ua iloa", "knew"], ["le mea e Moretekai,", "the thing to Mordecai"], ["ona ia faailoa atu lea", "and to declared"], ["i le masiofo o Eseta;", "in the wife of a Samoan paramount chief of Esther"], ["ona ta'u atu ai lea e Eseta", "and told to Esther"], ["i le tupu", "in the king"], ["i le igoa o Moretekai.", "in the name of Mordecai"]]},
  {num:23,words:[["Ua suesueina", "examine"], ["le mea,", "the thing"], ["ona iloa lea;", "and known"], ["ona faatautauina ai lea o", "and make to hang up of"], ["i laua", "them"], ["i le laau.", "in the tree"], ["Na tusia ai foi i luma o le tupu", "written also before the king"], ["i le tusi o tala", "in the book of side"], ["i nofoaiga.", "in reign"]]},
];
renderVerseSet(_est_ch_2_Verses, 'est-ch2-verses');

var _est_ch_3_Verses = [
  {num:1,words:[["Ua mavae ia mea,", "after these things"], ["ona faasili lea e le tupu", "and make most by the king"], ["o Asueru ia Hamanu", "Asueru to Haman"], ["le atalii o Hametatu", "the son of Hametatu"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["ma na faaeaina o ia,", "and faaeaina he"], ["ma faasili lona nofoa", "and make most his a seat"], ["i alii uma", "in Lord all"], ["ua faatasi ma ia.", "with him"]]},
  {num:2,words:[["Ona punou lea", "and punou"], ["ma ifo atu ia", "and down to"], ["Hamanu o auauna uma", "Haman of servant all"], ["a le tupu,", "but the king"], ["o e", "who"], ["na i ai", "therein"], ["i le faitotoa o le tupu;", "at the door the king"], ["auā na faapea ona", "for thus then"], ["poloai atu e le tupu", "command by the king"], ["ia faia ia te ia;", "to made to him"], ["a e lei punou Moretekai,", "but by not punou Mordecai"], ["e lei ifo foi.", "by not down also"]]},
  {num:3,words:[["Ona fai atu lea o auauna", "then said a servant"], ["a le tupu,", "of the king"], ["e na", "which was"], ["i ai", "therein"], ["i le faitotoa o le tupu,", "at the door the king"], ["ia Moretekai,", "to Mordecai"], ["Se a le mea", "what is this?"], ["ua e soli ai le poloaiga", "to to tread upon the commandment"], ["a le tupu?", "of the king"]]},
  {num:4,words:[["Na fai atu pea i latou ia te ia i aso uma,", "They kept urging him every day"], ["ae na lē tali mai o ia.", "but he did not respond to them"], ["O lea", "therefore"], ["na latou fa'ailoa atu ai ia Hamana,", "they reported it to Haman"], ["e va'ai pe o le a tumau le tulaga a Moredekai;", "to see whether Mordecai's position would hold"], ["auā na ia fa'amatala atu o ia o se tagata Iuta.", "because he had explained to them that he was a Jew"]]},
  {num:5,words:[["Ua iloa", "knew"], ["e Hamanu", "to Haman"], ["ua le punou Moretekai,", "the punou Mordecai"], ["ua le ifo foi ia te ia;", "not down also to him"], ["ona matuā ita ai lea o Hamanu.", "and exceedingly angry of Haman"]]},
  {num:6,words:[["Na 'ino'ino o ia", "hate he"], ["e faaoo lona lima ia", "to bring upon his five to"], ["Moretekai tau o ia;", "Mordecai season he"], ["auā ua latou faailoa atu ia te ia", "for they declared to him"], ["le nuu o Moretekai;", "the nation of Mordecai"], ["ona manao lea o Hamanu", "and desire of Haman"], ["e faaumatia", "to destroyed"], ["sa Iutā uma lava,", "of the clan of Iutā all indeed"], ["le nuu o Moretekai,", "the nation of Mordecai"], ["e na", "by"], ["i ai", "therein"], ["i le malo uma o Asueru.", "in the government all of Asueru"]]},
  {num:7,words:[["O le masina muamua,", "the moon first"], ["o le masina lea o Nisani,", "the moon of Nisani"], ["o le sefulu", "the ten"], ["ma le lua o tausaga", "and two year"], ["o le tupu o Asueru,", "the king of Asueru"], ["na fai ai le Puro,", "make the Puro"], ["o le vili lea,", "the a gimblet"], ["i luma o Hamanu", "before Haman"], ["i lea aso", "in day"], ["ma lea aso,", "and day"], ["i lea masina foi ma lea masina,", "in moon also and moon"], ["e oo i le masina", "unto the moon"], ["e sefulu", "by ten"], ["ma le lua,", "and two"], ["o le masina lea o Atara.", "the moon of Atara"]]},
  {num:8,words:[["Ona fai atu lea o Hamanu", "And he said Haman"], ["i le tupu o Asueru,", "in the king of Asueru"], ["O loo", "O loo"], ["i ai le tasi nuu", "therein the one nation"], ["ua taapeape", "taapeape"], ["ma nonofo solo faatasi ma tagata", "and dwelling to move swiftly together and people"], ["o itu malo uma", "side government all"], ["o lou malo.", "your government"], ["E ese foi a latou", "to away also but they"], ["tulafono i tulafono", "law in law"], ["a nuu uma,", "but nation all"], ["ma ua latou", "and they"], ["le usiusitai", "the obeyed"], ["i tulafono", "in law"], ["a oe", "but you"], ["le tupu;", "the king"], ["o le mea lea,", "therefore"], ["e le tatau ai", "by the to wring out"], ["i lau afio", "in your dwell (respectful)"], ["ona tuu pea ia te i latou.", "and put continually unto them"]]},
  {num:9,words:[["Afai e lelei ia te oe", "if to good unto you"], ["le tupu,", "the king"], ["ia tusia ia fano", "to written to perish"], ["i latou;", "them"], ["ou te fuaina atu ai taleni ario", "I fruit talent silver"], ["e sefulu afe", "by ten thousand"], ["i lima o e faia lenei mea,", "in five who made this thing"], ["ina ia latou avatu ai", "so that they give away"], ["i mea e teu ai oloa", "in thing to store goods"], ["a le tupu.", "but the king"]]},
  {num:10,words:[["Ona to ese ai lea e le tupu", "and to plant away by the king"], ["o lana mama", "his n"], ["i lona lima,", "in his five"], ["ma avatu ai ia", "and give away to"], ["Hamanu le atalii o Hametatu", "Haman the son of Hametatu"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["o lē faasaua", "not cruel"], ["i sa Iutā.", "in of the clan of Iutā"]]},
  {num:11,words:[["Ua fai atu foi le tupu", "said to also the king"], ["ia Hamanu,", "to Haman"], ["Ua avatua ia te oe", "given away unto you"], ["le ario", "the silver"], ["atoa ma lena nuu,", "and that nation"], ["ina ia", "so that"], ["e faia", "to made"], ["i ai le mea e lelei", "therein the thing to good"], ["ia te oe.", "unto you"]]},
  {num:12,words:[["Ona valaauina lea o e tusiupu", "and called who scribe"], ["a le tupu", "but the king"], ["i le aso e tasi", "in the day by one"], ["le sefulu", "the ten"], ["ma le tolu", "and three"], ["o le masina muamua,", "the moon first"], ["ona tusia ai lea o mea uma", "and written everything"], ["ua fai atu ai Hamanu", "said to Haman"], ["e avatu", "to give away"], ["i alii sili", "in Lord most"], ["ua i le tupu,", "in the king"], ["ma e pule,", "and to rule"], ["o e", "who"], ["na pule i lea itu malo", "rule in side government"], ["ma lea itu malo,", "and side government"], ["o alii foi o lea nuu", "Lord also therefore nation"], ["ma lea nuu,", "and nation"], ["e faatatau", "to liken"], ["ma le tusilima", "and the tusilima"], ["a lea itu malo", "but side government"], ["ma lea itu malo,", "and side government"], ["e tusa foi ma le gagana", "to according to also and the language"], ["a lea nuu", "but nation"], ["ma lea nuu;", "and nation"], ["na tusia", "written"], ["i le igoa", "in the name"], ["o le tupu o Asueru,", "the king of Asueru"], ["na faamaufaailogaina foi i le mama", "faamaufaailogaina also in the n"], ["a le tupu.", "but the king"]]},
  {num:13,words:[["Ona molia lea o tusi", "and accused of book"], ["e ua tele vavave", "by great vavave"], ["i itu malo uma", "in side government all"], ["o le tupu,", "the king"], ["ina ia faaumatia,", "so that destroyed"], ["ma ia fasiotia,", "and to slain"], ["ma ia fano", "and to perish"], ["sa Iutā uma,", "of the clan of Iutā all"], ["o taulelea", "young men"], ["atoa ma toeaina,", "and elder"], ["o tama iti", "child small"], ["atoa ma fafine,", "and woman"], ["i le aso e tasi,", "in the day by one"], ["o le sefulu", "the ten"], ["ma le tolu lea o aso", "and three of day"], ["o le sefulu", "the ten"], ["ma le lua o masina,", "and two moon"], ["o le masina lea", "the moon"], ["a Atara;", "of Atara"], ["ma a latou mea ia", "and but they thing to"], ["vetea.", "vetea"]]},
  {num:14,words:[["O le ata", "the a shadow"], ["o le tusi", "the book"], ["e avatua", "to given away"], ["e fai ma tulafono", "to be law"], ["i lea itu malo", "in side government"], ["ma lea itu malo uma,", "and side government all"], ["ua faailoa atu ai", "declared"], ["i nuu uma", "in nation all"], ["ina ia saunia", "so that prepared"], ["i latou", "them"], ["i lea aso.", "in day"]]},
  {num:15,words:[["Na o atu e ua tele vavave", "of by great vavave"], ["o faataaliseina", "to make haste"], ["i le poloaiga", "in the commandment"], ["a le tupu;", "but the king"], ["na avatua foi le tulafono ai Susana", "given away also the law Susana"], ["le maota.", "the the name of a tree"], ["Ona la nonofo lea o le tupu ma Hamanu,", "and la dwelling the king and Haman"], ["ua la feinu;", "la feinu"], ["a ua atuatuvale", "but to be greatly dis-"], ["le aai o Susana.", "the city of Susana"]]},
];
renderVerseSet(_est_ch_3_Verses, 'est-ch3-verses');

var _est_ch_4_Verses = [
  {num:1,words:[["Ua iloa", "knew"], ["e Moretekai mea uma", "to Mordecai all things"], ["ua faia,", "made"], ["ona saei ai lea e Moretekai", "and to tear to Mordecai"], ["ona ofu,", "and garment"], ["ma ua ofu o ia i le ie talatala", "and garment he in the faamaise to untie"], ["ma le lefulefu,", "and the ashes"], ["ma alu atu i totonu o le aai,", "and go away in the midst of the city"], ["ma alaga", "and cry"], ["i le alaga tele", "in the cry great"], ["ma ua lotulotu.", "and to dn iinylliing liastilv"]]},
  {num:2,words:[["Ua alu atu lava o ia i luma o le faitotoa o le tupu,", "go away indeed he before the door the king"], ["auā ua", "for"], ["sa ona ulu atu i le faitotoa o le tupu", "then head at the door the king"], ["a o ofu", "but of garment"], ["i le ie talatala.", "in the faamaise to untie"]]},
  {num:3,words:[["O lea itu malo foi ma lea itu malo uma", "therefore side government also and side government all"], ["na oo i ai le upu", "oo therein the word"], ["a le tupu ma lana tulafono,", "but the king and his law"], ["ua faanoanoa tele ai", "mourn great"], ["sa Iutā,", "of the clan of Iutā"], ["ma ua anapogi,", "and to fast"], ["ma fetagisi,", "and wept"], ["ma tagitu'i;", "and tagitu'i"], ["ua fofola foi e le toatele", "fofola also by the many"], ["o latou moega", "they bed"], ["i ie talatala", "in faamaise to untie"], ["ma le lefulefu.", "and the ashes"]]},
  {num:4,words:[["Ona o atu lea o le galu teine", "because of the wave girl"], ["o Eseta", "Esther"], ["ma ana eunuka,", "and his eunuch"], ["ma latou ta'u atu ai ia te ia.", "and they told to him"], ["Ona matuā tiga ai lea o le masiofo;", "and exceedingly grieved the wife of a Samoan paramount chief"], ["ua ia avatu foi ofu", "to give away also garment"], ["e ofu ai Moretekai,", "to garment Mordecai"], ["ma ia ave ese lona ie talatala", "and to take away his faamaise to untie"], ["ia te ia;", "to him"], ["a e lei talia", "but by not received"], ["e ia.", "by him"]]},
  {num:5,words:[["Ona valaau atu lea e Eseta", "then called to Esther"], ["ia Hatako,", "to Hatako"], ["o le tasi eunuka", "the one eunuch"], ["a le tupu,", "but the king"], ["le na ia tofia", "the to chosen"], ["mo ia,", "for to"], ["ma na tuuina atu ia te ia", "and given to him"], ["le feau ia Moretekai ia iloa", "the errand to Mordecai to known"], ["pe se a lena?", "whether a but that"], ["Ona o le a foi?", "because of the but also"]]},
  {num:6,words:[["Ona alu atu ai lea o Hatako", "and go away of Hatako"], ["ia Moretekai", "to Mordecai"], ["i le malae", "in the the"], ["o le aai", "the city"], ["sa i luma o le faitotoa o le tupu.", "before the door the king"]]},
  {num:7,words:[["Ona faailoa mai lea e Moretekai", "and revealed from to Mordecai"], ["ia te ia o mea uma", "to him everything"], ["ua oo ia te ia,", "it came to pass to him"], ["ma le tala tonu", "and the side right"], ["i le ario", "in the silver"], ["na fai atu ai Hamanu", "said Haman"], ["na te fuaina atu i mea e teu ai oloa", "he fruit in thing to store goods"], ["a le tupu", "but the king"], ["ona o", "because of"], ["sa Iutā,", "of the clan of Iutā"], ["ina ia fano", "so that perish"], ["i latou.", "them"]]},
  {num:8,words:[["Na ia aumaia foi ia te ia", "to bring here also to him"], ["le ata", "the a shadow"], ["o le tusi", "the book"], ["o le tulafono", "the law"], ["na avatua mai Susana ia", "given away from Susana to"], ["faaumatia i latou,", "destroyed them"], ["ina ia faaali atu ai ia", "so that revealed to"], ["Eseta,", "Esther"], ["ma ta'u atu ia te ia,", "and told to him"], ["ma fai atu ia te ia ia", "and said to to him to"], ["alu atu o ia i le tupu,", "go away he in the king"], ["e aioi atu ia te ia,", "to cry out to him"], ["ma faatoga atu ia te ia", "and order to him"], ["mo lona nuu.", "for his nation"]]},
  {num:9,words:[["Ona sau lea o Hatako,", "And he came Hatako"], ["ma ta'u mai ia", "and tell from to"], ["Eseta upu", "Esther word"], ["a Moretekai.", "of Mordecai"]]},
  {num:10,words:[["Ona tali atu lea o Eseta", "and respond of Esther"], ["ia Hatako,", "to Hatako"], ["ma na tuuina atu ia te ia", "and given to him"], ["le feau ia Moretekai,", "the errand to Mordecai"]]},
  {num:11,words:[["ua faapea ,", "saying"], ["Ua iloa", "knew"], ["e auauna uma", "to servant all"], ["a le tupu,", "but the king"], ["ma tagata o itu malo o le tupu,", "and people side government the king"], ["ai se tane po", "a man night"], ["o se fafine", "a woman"], ["e alu atu i le tupu", "to go away in the king"], ["i le lotoā", "in the court"], ["i totonu,", "in inside"], ["a o lei amia,", "but of not amia"], ["e tasi lana tulafono,", "by one his law"], ["e oti o ia;", "to die he"], ["ua na o le", "the"], ["e faaloaloa mai i ai e le tupu le tootoo auro", "to stretch out from therein by the king the staff gold"], ["e ola ai o ia.", "to life he"], ["O a'u foi,", "I am also"], ["ua le amia a'u", "the amia I"], ["e alu", "to go"], ["i le tupu", "in the king"], ["i aso ia", "in day to"], ["e tolu sefulu.", "by three ten"]]},
  {num:12,words:[["Ona latou ta'u atu lea", "and they told"], ["ia Moretekai o upu", "to Mordecai of word"], ["a Eseta.", "of Esther"]]},
  {num:13,words:[["Ona fai mai lea o Moretekai", "And he said Mordecai"], ["ia tali atu ia", "to respond to"], ["Eseta,", "Esther"], ["Ne'i e manatu", "now to thought"], ["i lou loto,", "in your heart"], ["ina ua e i ai", "so that by therein"], ["i le aiga o le tupu,", "in the family of the king"], ["e faasaoina ai oe", "to spared you"], ["ai sa Iutā uma.", "of the clan of Iutā all"]]},
  {num:14,words:[["Auā afai", "for if"], ["e te matuā faalologo", "by exceedingly to hold one's tongue"], ["i nei", "in this"], ["ona po,", "and night"], ["e tupu mai le tuusaunoaina", "to king from the tuusaunoaina"], ["ma le laveaiina o", "and the delivered of"], ["sa Iutā mai", "of the clan of Iutā from"], ["se tasi mea;", "a one thing"], ["a o oe,", "but of you"], ["ma le aiga o lou tamā", "and the family your father"], ["e fano outou;", "to perish you (all)"], ["e iloa foi e ai po", "to known also by night"], ["ua fai oe", "make you"], ["ma masiofo", "and wife of a Samoan paramount chief"], ["ona o se aso faapenei?", "because of a day make like this"]]},
  {num:15,words:[["Ona fai atu lea o Eseta,", "And he said Esther"], ["ia tali atu ia", "to respond to"], ["Moretekai,", "Mordecai"]]},
  {num:16,words:[["Alu ia oe,", "go to you"], ["ia e faapotopoto", "to to gather"], ["i sa Iutā uma", "in of the clan of Iutā all"], ["e o", "by of"], ["i ai", "therein"], ["i Susana,", "in Susana"], ["ma ia anapopogi outou", "and to anapopogi you (all)"], ["ona o a'u,", "because of I"], ["aua foi ne'i outou", "for also now you (all)"], ["aai,", "city"], ["aua foi le inu", "for also the drink"], ["i aso e tolu", "in day by three"], ["i le po", "in the night"], ["ma le ao;", "and the day"], ["o a'u foi,", "I am also"], ["ma lo'u galu teine matou", "and my wave girl we (excl)"], ["te anapopogi faapenā;", "anapopogi faapenā"], ["e faapena foi", "to likewise also"], ["ona ou alu atu ai", "and I go away"], ["i le tupu", "in the king"], ["o le mea e le tusa ma le tulafono;", "the thing by the according to and the law"], ["afai ou te oti ai,", "if I die"], ["oti ai pea ia.", "die continually to"]]},
  {num:17,words:[["Ona alu ai lea o Moretekai,", "and go of Mordecai"], ["ma na faia o mea uma", "and made everything"], ["e pei ona", "as"], ["poloai atu ai e Eseta", "command to Esther"], ["ia te ia.", "to him"]]},
];
renderVerseSet(_est_ch_4_Verses, 'est-ch4-verses');

var _est_ch_5_Verses = [
  {num:1,words:[["Ua oo i le aso tolu,", "it came to pass in the day three"], ["ona ofu ai lea o Eseta", "and garment of Esther"], ["i ofu", "in garment"], ["o le masiofo,", "the wife of a Samoan paramount chief"], ["ma tu atu i le lotoā", "and stood in the court"], ["o le fale", "the house"], ["o le tupu,", "the king"], ["o le lotoā", "the court"], ["i totonu", "in inside"], ["i luma o le fale", "before the house"], ["o le tupu,", "the king"], ["o loo nofo mai le tupu", "dwelt the king"], ["i le nofoālii", "in the throne"], ["o le tupu", "the king"], ["i le fale", "in the house"], ["o le tupu,", "the king"], ["ua feagai", "opposite"], ["ma le faitotoa o le fale.", "and the door the house"]]},
  {num:2,words:[["Ua iloa mai e le tupu", "knew from by the king"], ["o le masiofo o Eseta", "the wife of a Samoan paramount chief of Esther"], ["o loo tu atu i le lotoā,", "stood in the court"], ["ona alofaina,", "and beloved"], ["lea o ia e ia;", "he by him"], ["ua faaloaloa mai foi e le tupu lona tootoo auro", "stretch out from also by the king his staff gold"], ["na i ai", "therein"], ["i lona lima ia", "in his five to"], ["Eseta;", "Esther"], ["ona faalatalata atu ai lea o Eseta,", "and draw near of Esther"], ["ma pai atu i le iu", "and pie in the attain"], ["o le tootoo.", "the staff"]]},
  {num:3,words:[["Ona fai mai lea o le tupu", "And he said the king"], ["ia te ia,", "to him"], ["Le masiofo e,", "the wife of a Samoan paramount chief by"], ["Eseta,", "Esther"], ["se a ea lou manao?", "a but to rise (as a diver to the sur- your desire"], ["Se a le mea e te faatoga", "what by order"], ["mai ai? E oo lava", "from it shall come to pass indeed"], ["i le vaeluaina", "in the vaeluaina"], ["o le malo", "the government"], ["e avatua lava ia te oe.", "to given away indeed unto you"]]},
  {num:4,words:[["Ona tali atu lea o Eseta,", "and respond of Esther"], ["Afai e lelei", "if to good"], ["i le tupu,", "in the king"], ["ia maliu atu le tupu ma Hamanu,", "to die the king and Haman"], ["i le asō,", "in the asō"], ["i le tautega", "in the tautega"], ["ua ou saunia", "I prepared"], ["mo ia.", "for to"]]},
  {num:5,words:[["Ona fai mai lea o le tupu,", "And he said the king"], ["Ia faavave ia Hamanu", "to make quick to Haman"], ["ina ia fai", "so that make"], ["le mea", "the thing"], ["a Eseta.", "of Esther"], ["Ona ō lea o le tupu ma Hamanu", "and go (plural) the king and Haman"], ["i le taumafataga", "in the taumafataga"], ["na saunia o Eseta.", "prepared of Esther"]]},
  {num:6,words:[["Ona fai mai lea o le tupu", "And he said the king"], ["ia Eseta", "to Esther"], ["i le taumafataga", "in the taumafataga"], ["o le uaina,", "the wine"], ["Se a le mea e te fai mai ai? E avatua", "what by said to given away"], ["lava ia te oe;", "indeed unto you"], ["pe se a foi le mea e te faatoga", "whether a but also the thing by order"], ["mai ai? E oo lava", "from it shall come to pass indeed"], ["i le vaeluagalemu", "in the vaeluagalemu"], ["o le malo", "the government"], ["e faia lava.", "to made indeed"]]},
  {num:7,words:[["Ona tali atu lea o Eseta,", "and respond of Esther"], ["ua faapea atu,", "and said"], ["O le mea ou te ole atu ai,", "the thing I entreat"], ["ma faatoga atu ai o lenei;", "and order now"]]},
  {num:8,words:[["afai ua alofaina a'u", "if beloved I"], ["e le tupu,", "by the king"], ["afai foi e lelei", "if also to good"], ["i le tupu", "in the king"], ["ona faia le mea ou te faatoga atu ai,", "and made the thing I order"], ["ma ia faia le mea ou te manao", "and to made the thing I desire"], ["i ai,", "therein"], ["ina toe afio mai ia", "so that again dwell (respectful) from to"], ["le tupu ma Hamanu", "the king and Haman"], ["i le tautega ou te saunia", "in the tautega I prepared"], ["mo i laua,", "for them"], ["ona ou faia lea taeao", "and I made morning"], ["e pei ona fetalai mai ai o le tupu.", "as said the king"]]},
  {num:9,words:[["Ona alu atu lea o Hamanu", "and go away of Haman"], ["i lena aso", "in that day"], ["ma le olioli", "and the rejoice"], ["ma le loto fiafia;", "and the heart competition"], ["a ua vaai atu Hamanu", "but looked toward Haman"], ["ia Moretekai", "to Mordecai"], ["i le faitotoa o le tupu,", "at the door the king"], ["ua le tulai,", "not arose up"], ["ua le faaaloalo foi ia te ia,", "the faaaloalo also to him"], ["ona tele ai lea o le ita", "and great the angry"], ["o Hamanu ia Moretekai.", "Haman to Mordecai"]]},
  {num:10,words:[["A ua oono Hamanu;", "but oono Haman"], ["ua alu atu foi i lona fale,", "go away also in his house"], ["ma na aauina atu nisi", "and sent some"], ["e amia ana uo,", "by amia his uo"], ["ma Seresa lana avā.", "and Seresa his wife"]]},
  {num:11,words:[["Ona faamatalaina atu lea e Hamanu", "and faamatalaina to Haman"], ["ia te i latou", "unto them"], ["o le mamalu", "the glory"], ["o lona tamaoaiga,", "his economy"], ["ma le toatele", "and the many"], ["o ana fanau,", "his born"], ["ma mea uma", "and all things"], ["ua faasilisiliina ai o ia", "make very much he"], ["e le tupu,", "by the king"], ["ma ona", "and then"], ["ua faaeaina ai o ia ia", "faaeaina he to"], ["sili i alii", "most in Lord"], ["ma auauna", "and servant"], ["a le tupu.", "but the king"]]},
  {num:12,words:[["Ua fai atu foi Hamanu,", "said to also Haman"], ["Sa le mafai foi le masiofo", "not able also the wife of a Samoan paramount chief"], ["o Eseta", "Esther"], ["ona alu atu", "and go away"], ["se isi faatasi ma le tupu", "a other together and the king"], ["i le taumafataga", "in the taumafataga"], ["na ia saunia,", "to prepared"], ["na o a'u lava.", "I am indeed"], ["Ua fai mai foi ia te au", "said also unto me"], ["e alu ia te ia", "to go to him"], ["a taeao faatasi ma le tupu.", "but morning together and the king"]]},
  {num:13,words:[["A e peitai", "but"], ["e le aoga lava ia te au", "by the useful indeed unto me"], ["o ia mea uma", "he all things"], ["i aso uma ou te vaai atu ai ia", "all the days I looked toward to"], ["Moretekai o lo", "Mordecai lo"], ["sa Iutā o loo nofo", "of the clan of Iutā of dwell"], ["i le faitotoa o le tupu.", "at the door the king"]]},
  {num:14,words:[["Ona fai atu ai lea", "and said to"], ["ia te ia o Seresa lana avā,", "to him Seresa his wife"], ["ma ana uo uma,", "and his uo all"], ["Ia saunia", "to prepared"], ["se laau,", "a tree"], ["ia limagafulu kupita lona maualuga,", "to fifty cubit his Iiigli"], ["ma ia", "and to"], ["e fai atu i le tupu", "to said to in the king"], ["i le taeao,", "in the morning"], ["ia faatautauina ai Moretekai;", "to make to hang up Mordecai"], ["ona e alu ai lea", "and to go"], ["ma le fiafia faatasi ma le tupu", "and the competition together and the king"], ["i le taumafataga.", "in the taumafataga"], ["Ua lelei lena upu ia", "that it was good that word to"], ["Hamanu;", "Haman"], ["ona ia faia lea o le laau.", "and to made the tree"]]},
];
renderVerseSet(_est_ch_5_Verses, 'est-ch5-verses');

var _est_ch_6_Verses = [
  {num:1,words:[["O lena lava po", "that indeed night"], ["na le iloa ai e le tupu sina moe.", "not known by the king white sleep"], ["Ona fai atu lea o le tupu", "And he said the king"], ["e au mai le tusi", "to bring the book"], ["e faamanatu a'i tala", "to to remind side"], ["i nofoaiga.", "in reign"], ["Ona faitaulia ai lea", "and counted"], ["i luma o le tupu.", "before the king"]]},
  {num:2,words:[["Ona iloa lea", "and known"], ["ua tusia", "written"], ["le mea", "the thing"], ["na ta'u atu e Moretekai", "told to Mordecai"], ["ia Piketano", "to Piketano"], ["ma Terese,", "and Terese"], ["o eunuka ia", "eunuch to"], ["e toalua", "to two (people)"], ["a le tupu,", "but the king"], ["e na leoleo", "by guard"], ["i le faitotoa,", "at the door"], ["o e", "who"], ["na fia faaoo", "want to do something bring upon"], ["o la lima", "la five"], ["i le tupu o Asueru.", "in the king of Asueru"]]},
  {num:3,words:[["Ona fai atu lea o le tupu,", "And he said the king"], ["Pe se a se mea lelei ma", "whether a but a thing good and"], ["se mamalu", "a glory"], ["ua faia", "made"], ["mo Moretekai", "for Mordecai"], ["ona o lenei mea?", "because of this thing"], ["Ona tali mai lea o auauna", "and respond from of servant"], ["a le tupu o e", "but the king who"], ["na auauna atu ia te ia,", "servant to him"], ["E leai se mea", "there is nothing"], ["ua faia", "made"], ["mo ia.", "for to"]]},
  {num:4,words:[["Ona fai atu lea o le tupu,", "And he said the king"], ["O ai ea", "who"], ["ua i le lotoā? Auā", "in the court for"], ["ua alu ane Hamanu", "go along Haman"], ["i le lotoā? Auā", "in the court for"], ["ua alu ane Hamanu", "go along Haman"], ["i le lotoā", "in the court"], ["i fafo o le fale", "outside of the house"], ["o le tupu", "the king"], ["e fai atu ai", "to said to"], ["i le tupu ia", "in the king to"], ["faatautauina Moretekai", "make to hang up Mordecai"], ["i le laau", "in the tree"], ["ua ia saunia", "to prepared"], ["mo ia.", "for to"]]},
  {num:5,words:[["Ona tali mai lea o auauna", "and respond from of servant"], ["a le tupu ia te ia,", "but the king to him"], ["Faauta,", "behold"], ["o loo tu mai Hamanu", "stood Haman"], ["i le lotoā.", "in the court"], ["Ona fai atu lea o le tupu,", "And he said the king"], ["Ina sau ia o ia.", "so that come to he"]]},
  {num:6,words:[["Ua ulufale mai Hamanu,", "enter from Haman"], ["ona fai atu lea o le tupu", "And he said the king"], ["ia te ia", "to him"], ["Se a se mea e faia", "a but a thing to made"], ["i le tagata", "in the man"], ["ua loto", "heart"], ["i ai le tupu", "therein the king"], ["ona ia faaneeneeina o ia?", "and to to\" praise he"], ["Ona faapea ifo lea o Hamanu", "and thus down of Haman"], ["i lona loto,", "in his heart"], ["Po o ai", "night of"], ["se isi", "a other"], ["e finagalo", "to a chiefs will or desire"], ["le tupu", "the king"], ["ona faaneeneeina o ia,", "and to\" praise he"], ["na o a'u lava?", "I am indeed"]]},
  {num:7,words:[["Ona tali mai lea o Hamanu", "and respond from of Haman"], ["i le tupu,", "in the king"], ["O le tagata", "man"], ["ua finagalo", "a chiefs will or desire"], ["i ai le tupu", "therein the king"], ["ona faaneeneeina o ia,", "and to\" praise he"]]},
  {num:8,words:[["ia aumaia", "to bring here"], ["le ofu", "the garment"], ["o le tupu", "the king"], ["e ofu ai le tupu,", "to garment the king"], ["ma le solofanua", "and the horse"], ["e tietie ai le tupu,", "to ride the king"], ["ma le palealii", "and the palealii"], ["o le tupu", "the king"], ["e tuuina", "to given"], ["i lona ao;", "in his day"]]},
  {num:9,words:[["ia tuuina atu lena ofu", "to given that garment"], ["ma lena solofanua", "and that horse"], ["i se tasi alii o alii sili", "in a one Lord of Lord most"], ["ua i le tupu,", "in the king"], ["ma ia latou faaofu ai le tagata", "and to they make garment the man"], ["ua finagalo", "a chiefs will or desire"], ["i ai le tupu", "therein the king"], ["ona ia faaneeneeina o ia;", "and to to\" praise he"], ["ia latou faatietie foi ia te ia i le solofanua", "to they make ride also to him in the horse"], ["i le malae", "in the the"], ["o le aai,", "the city"], ["ma ia latou alalaga", "and to they cry out"], ["i ona luma,", "before him"], ["E faapea ona faia", "saying and made"], ["i le tagata", "in the man"], ["ua finagalo", "a chiefs will or desire"], ["i ai le tupu", "therein the king"], ["ona ia faaneeneeina o ia.", "and to to\" praise he"]]},
  {num:10,words:[["Ona fai atu lea o le tupu", "And he said the king"], ["ia Hamanu,", "to Haman"], ["Ina vave ia,", "so that quick to"], ["ia e ave", "to to take"], ["le ofu", "the garment"], ["ma le solofanua,", "and the horse"], ["e pei ona", "as"], ["e fai mai", "to said"], ["na,", "na,"], ["ia e fai faapea ia", "to to make thus to"], ["Moretekai o lo", "Mordecai lo"], ["sa Iutā,", "of the clan of Iutā"], ["o le nofo", "the dwell"], ["i le faitotoa o le tupu,", "at the door the king"], ["aua le tuua", "do not left"], ["se mea e tasi", "a thing by one"], ["i mea uma", "in all things"], ["ua e fai mai", "to said"], ["na.", "na."]]},
  {num:11,words:[["Ona ave lea e Hamanu", "and take to Haman"], ["o le ofu", "the garment"], ["ma le solofanua,", "and the horse"], ["ma na faaofu ia", "and make garment to"], ["Moretekai,", "Mordecai"], ["na ia faatietie foi ia te ia i le solofanua", "to make ride also to him in the horse"], ["i le malae", "in the the"], ["o le aai,", "the city"], ["ma alaga", "and cry"], ["i ona luma,", "before him"], ["E faapea ona faia", "saying and made"], ["i le tagata", "in the man"], ["ua finagalo", "a chiefs will or desire"], ["i ai le tupu", "therein the king"], ["ona faaneeneeina o ia.", "and to\" praise he"]]},
  {num:12,words:[["Ona foi atu lea o Moretekai", "and also of Mordecai"], ["i le faitotoa o le tupu;", "at the door the king"], ["a ua faataalise atu Hamanu", "but to make haste Haman"], ["i lona fale", "in his house"], ["ma le faanoanoa,", "and the mourn"], ["ma ua ufiufi lona ulu.", "and covering his head"]]},
  {num:13,words:[["Ona faamatalaina atu lea e Hamanu", "and faamatalaina to Haman"], ["ia Seresa lana avā", "to Seresa his wife"], ["ma ana uo uma,", "and his uo all"], ["o mea uma", "everything"], ["ua oo ia te ia.", "it came to pass to him"], ["Ona fai atu ai lea", "and said to"], ["ia te ia o ona tagata popoto", "to him then man round (as the trunk of a"], ["ma Seresa lana avā,", "and Seresa his wife"], ["Afai o so", "if of so"], ["le fanau", "the born"], ["a sa Iutā o Moretekai,", "but of the clan of Iutā of Mordecai"], ["le ua", "the"], ["e amata ai", "to began"], ["ona paū", "and paū"], ["i ona luma,", "before him"], ["e te le manumalo ia te ia,", "by the overcome to him"], ["a e matuā paū lava oe", "but to exceedingly paū indeed you"], ["i ona luma.", "before him"]]},
  {num:14,words:[["Ona oo mai lea o eunuka", "and came of eunuch"], ["a le tupu,", "but the king"], ["a o tautalatala", "but of tautalatala"], ["i latou", "them"], ["ma Hamanu,", "and Haman"], ["ma latou nanati ia te ia,", "and they urged to him"], ["ia alu", "to go"], ["i le taumafataga", "in the taumafataga"], ["ua saunia", "prepared"], ["e Eseta.", "to Esther"]]},
];
renderVerseSet(_est_ch_6_Verses, 'est-ch6-verses');

var _est_ch_7_Verses = [
  {num:1,words:[["Ua o atu le tupu ma Hamanu", "of the king and Haman"], ["e taumamafa faatasi ma le masiofo", "by taumamafa together and the wife of a Samoan paramount chief"], ["o Eseta.", "Esther"]]},
  {num:2,words:[["Ona fai atu ai lea o le tupu", "and said to the king"], ["ia Eseta", "to Esther"], ["i lena aso e lua ao fai", "in that day by two day make"], ["le taumafataga", "the taumafataga"], ["o le uaina,", "the wine"], ["Le masiofo e,", "the wife of a Samoan paramount chief by"], ["Eseta,", "Esther"], ["se a le mea e te ole", "what by entreat"], ["mai ai? E avatua lava", "from to given away indeed"], ["ia te oe;", "unto you"], ["pe se a foi le mea e te faatoga", "whether a but also the thing by order"], ["mai ai? E oo lava", "from it shall come to pass indeed"], ["i le vaeluaina", "in the vaeluaina"], ["o le malo", "the government"], ["e faia lava.", "to made indeed"]]},
  {num:3,words:[["Ona tali mai lea e le masiofo", "and respond from by the wife of a Samoan paramount chief"], ["o Eseta,", "Esther"], ["ua faapea mai,", "and said"], ["Le tupu e,", "the king by"], ["afai ua alofaina a'u", "if beloved I"], ["e oe,", "to you"], ["afai e lelei foi i le tupu,", "if to good also in the king"], ["se'i e faaola", "a flower put into the hair or to save"], ["mai ia te au", "from I"], ["i lo'u ole atu,", "in my entreat"], ["ia faaola foi lo'u nuu", "to save also my nation"], ["i lo'u faatoga atu;", "in my order"]]},
  {num:4,words:[["auā ua faatauina", "for bought"], ["i matou,", "in we (excl)"], ["o a'u", "I am"], ["ma lo'u nuu,", "and my nation"], ["ina ia faaumatia,", "so that destroyed"], ["ma ia fasiotia,", "and to slain"], ["ma ia fano.", "and to perish"], ["A e afai ana faatauina atu i matou", "but to if his bought in we (excl)"], ["o tane ma fafine", "man and woman"], ["e fai ma pologa", "to be mouldy"], ["e ui", "to although"], ["ina le mafai", "so that the able"], ["i le ua ita", "in the angry"], ["mai ona faia", "from then made"], ["o se mea e tusa", "a thing to according to"], ["ona aoga", "and useful"], ["ma mea", "and thing"], ["a le tupu", "but the king"], ["a faamaumauina,", "but faamaumauina"], ["a ua ou faalologo.", "but I to hold one's tongue"]]},
  {num:5,words:[["Ona fai atu lea o le tupu", "And he said the king"], ["o Asueru,", "Asueru"], ["ua faapea atu i le masiofo", "and said in the wife of a Samoan paramount chief"], ["o Eseta,", "Esther"], ["Po o ai lena? Po", "night of that night"], ["o fea o iai", "where?/which? there is"], ["le ua manatu", "the thought"], ["i lona loto ia faia faapena?", "in his heart to made likewise"]]},
  {num:6,words:[["Ona fai mai lea o Eseta,", "And he said Esther"], ["O le tagata", "man"], ["ua ita mai", "angry from"], ["ma faasaua mai,", "and cruel from"], ["o lenei tagata amio leaga", "now man iniquity"], ["o Hamanu.", "Haman"], ["Ona mata'u tele ai lea o Hamanu", "and ax great of Haman"], ["i luma o le tupu ma le masiofo.", "before the king and the wife of a Samoan paramount chief"]]},
  {num:7,words:[["Ona tulai lea o le tupu", "and arose up the king"], ["nai le taumafataga", "from the taumafataga"], ["o le uaina", "the wine"], ["ua ita,", "angry"], ["ua alu", "go"], ["i le fanua", "in the land"], ["o le maota.", "the the name of a tree"], ["Ona tulai lea o Hamanu", "and arose up of Haman"], ["e aioi", "to cry out"], ["i le masiofo o Eseta,", "in the wife of a Samoan paramount chief of Esther"], ["ia faaolaina o ia;", "to keep alive he"], ["auā ua ia iloa", "for to known"], ["ua tonu", "right"], ["i le tupu", "in the king"], ["e faaoo ia te ia", "to bring upon to him"], ["se leaga.", "a evil"]]},
  {num:8,words:[["Ua foi atu le tupu mai le fanua", "also the king from the land"], ["o le maota", "the the name of a tree"], ["i le fale", "in the house"], ["na fai ai le taumafataga", "make the taumafataga"], ["o le uaina,", "the wine"], ["ua paū foi Hamanu", "paū also Haman"], ["i le moega o", "in the bed of"], ["i ai Eseta;", "therein Esther"], ["ona fai ane lea o le tupu,", "and make the king"], ["Pe a toso ea foi le masiofo", "whether but toso to rise (as a diver to the sur- also the wife of a Samoan paramount chief"], ["i o'u luma", "before me"], ["i le fale?", "in the house"], ["Ua mavae atu le upu", "after the word"], ["i le fofoga", "in the face"], ["o le tupu,", "the king"], ["ona latou ufitia lea mata", "and they covered eye"], ["o Hamanu.", "Haman"]]},
  {num:9,words:[["Ua fai ane foi i luma o le tupu", "make also before the king"], ["e Harepono,", "by Harepono"], ["o le tasi eunuka ia,", "the one eunuch to"], ["Faauta foi i le laau", "and behold in the tree"], ["na saunia", "prepared"], ["e Hamanu", "to Haman"], ["mo Moretekai", "for Mordecai"], ["o le", "the"], ["na ta'u", "tell"], ["le mea e sao ai le tupu,", "the thing to the appointed portion of the king"], ["o loo tu", "stand"], ["i le fale o Hamanu,", "in the house of Haman"], ["e limagafulu kupita lona maualuga.", "to fifty cubit his Iiigli"], ["Ona fai atu lea e le tupu,", "And he said by the king"], ["Ia outou faatautau ia te ia i ai.", "to you (all) make to hang up to him therein"]]},
  {num:10,words:[["Ona latou faatautau ai lea", "and they make to hang up"], ["ia Hamanu", "to Haman"], ["i le laau", "in the tree"], ["na ia saunia", "to prepared"], ["mo Moretekai.", "for Mordecai"], ["Ona maona ai lea o le ita", "and to subside the angry"], ["o le tupu.", "the king"]]},
];
renderVerseSet(_est_ch_7_Verses, 'est-ch7-verses');

var _est_ch_8_Verses = [
  {num:1,words:[["O lena lava aso", "that indeed day"], ["na foaiina atu ai e le tupu", "given by the king"], ["o Asueru", "Asueru"], ["mo le masiofo o Eseta,", "for the wife of a Samoan paramount chief of Esther"], ["le fale o Hamanu", "the house of Haman"], ["o le", "the"], ["na ita", "angry"], ["i sa Iutā.", "in of the clan of Iutā"], ["Ua alu atu foi Moretekai", "go away also Mordecai"], ["i luma o le tupu,", "before the king"], ["auā ua ta'u atu e Eseta la te aiga.", "for told to Esther la family"]]},
  {num:2,words:[["Ona to ese ai lea e le tupu", "and to plant away by the king"], ["o lana mama", "his n"], ["ua ia aveeseina ia", "to carried away to"], ["Hamanu,", "Haman"], ["ma na tuuina atu ai ia", "and given to"], ["Moretekai.", "Mordecai"], ["Ua tofia foi Moretekai", "chosen also Mordecai"], ["e Eseta", "to Esther"], ["e pule i le fale", "to rule in the house"], ["o Hamanu.", "Haman"]]},
  {num:3,words:[["Ona toe tautala atu lea o Eseta", "and again spoke of Esther"], ["i le tupu,", "in the king"], ["ua ia faapaū foi i luma o ona vae,", "to faapaū also before then foot"], ["ma tagi,", "and cry"], ["ma aioi ia te ia,", "and cry out to him"], ["ia faaliliuseina e ia", "to faaliliuseina by him"], ["le leaga", "the evil"], ["a Hamanu", "of Haman"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["ma lana manatu", "and his thought"], ["na ia manatu ai", "to thought"], ["i sa Iutā.", "in of the clan of Iutā"]]},
  {num:4,words:[["Ona faaloaloa mai lea e le tupu", "and stretch out from by the king"], ["o le tootoo auro ia", "the staff gold to"], ["Eseta.", "Esther"], ["Ona tulai ai lea o Eseta,", "and arose up of Esther"], ["ma tu atu i luma o le tupu,", "and stood before the king"], ["ona ia fai atu lea,", "and to said to"]]},
  {num:5,words:[["Afai e lelei", "if to good"], ["i le tupu,", "in the king"], ["afai foi", "if also"], ["ua alofaina a'u e ia,", "beloved I by him"], ["ma ua tonu lenei mea", "and right this thing"], ["i le finagalo", "in the a chiefs will or desire"], ["o le tupu,", "the king"], ["ma ua fiafia o ia ia te au,", "and competition he unto me"], ["ia tusia", "to written"], ["ina ia liliueseina tusi", "so that liliueseina book"], ["o le manatu", "the thought"], ["a Hamanu", "of Haman"], ["le atalii o Hametatu,", "the son of Hametatu"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["o le", "the"], ["na tusi atu", "book"], ["ina ia fano", "so that perish"], ["sa Iutā,", "of the clan of Iutā"], ["o e o", "who"], ["i ai", "therein"], ["i itu malo uma", "in side government all"], ["o le tupu;", "the king"]]},
  {num:6,words:[["auā ou te mafaia faapefea ona ou vaai atu i le leaga", "for I able how then I looked toward in the evil"], ["o le a oo i lo'u nuu? Ou te mafaia faapefea ona ou vaai atu i le fanoga", "what oo in my nation I able how then I looked toward in the fanoga"], ["o lo'u aiga?", "my family"]]},
  {num:7,words:[["Ona fai mai lea o le tupu", "And he said the king"], ["o Asueru", "Asueru"], ["i le masiofo o Eseta,", "in the wife of a Samoan paramount chief of Esther"], ["ma Moretekai", "and Mordecai"], ["o lo", "lo"], ["sa Iutā,", "of the clan of Iutā"], ["Faauta,", "behold"], ["ua ou tuuina atu ia", "I have given to"], ["Eseta le fale o Hamanu,", "Esther the house of Haman"], ["ua latou faatautau foi ia te ia i le laau,", "they make to hang up also to him in the tree"], ["auā ua na faaoo lona lima", "for bring upon his five"], ["i sa Iutā.", "in of the clan of Iutā"]]},
  {num:8,words:[["Ina tusi foi ia", "so that book also to"], ["oulua ona o", "you (two) because of"], ["sa Iutā,", "of the clan of Iutā"], ["faitalia oulua", "as I you (two)"], ["se mea e tusi", "a thing to book"], ["i le igoa", "in the name"], ["o le tupu,", "the king"], ["ma ia faamaufaailogaina", "and to faamaufaailogaina"], ["i le mama", "in the n"], ["a le tupu;", "but the king"], ["auā o le tusi", "for the book"], ["ua tusia", "written"], ["i le igoa", "in the name"], ["o le tupu,", "the king"], ["ma faamaufaailogaina", "and faamaufaailogaina"], ["i le mama", "in the n"], ["a le tupu", "but the king"], ["e le mafai ona", "by the able then"], ["liliueseina.", "liliueseina"]]},
  {num:9,words:[["Ona valaauina lea o e tusiupu", "and called who scribe"], ["a le tupu", "but the king"], ["i lena lava itu aso", "in that indeed side day"], ["i le tolu o masina,", "in the three of moon"], ["o le masina lea o Sevana,", "the moon of Sevana"], ["i lona aso e lua sefulu", "in his day by two ten"], ["ma le tolu;", "and three"], ["ona tusia lea o mea uma", "and written everything"], ["e pei ona fai atu ai o Moretekai", "as said to of Mordecai"], ["e avatu", "to give away"], ["i sa Iutā,", "in of the clan of Iutā"], ["ma alii sili,", "and Lord most"], ["ma e pule i nuu,", "and to rule in nation"], ["ma alii e pule i itu malo", "and Lord to rule in side government"], ["e gata mai i Initia", "to a snake from in Initia"], ["e oo atu i Aitiope,", "it shall come to pass in Aitiope"], ["o itu malo", "side government"], ["e tasi", "by one"], ["le selau", "the hundred"], ["ma le lua sefulu", "and two ten"], ["ma le fitu;", "and seven"], ["na tusi atu i lea itu malo", "book in side government"], ["ma lea itu malo", "and side government"], ["e tusa ma a latou", "according to but they"], ["tusilima,", "tusilima"], ["ma lea nuu", "and nation"], ["ma lea nuu", "and nation"], ["e tusa ma a latou gagana,", "according to but they language"], ["o sa Iutā foi e tusa ma la latou tusilima", "of the clan of Iutā also according to their tusilima"], ["ma la latou gagana.", "and their language"]]},
  {num:10,words:[["Ua ia tusi atu foi i le igoa", "to book also in the name"], ["o le tupu o Asueru,", "the king of Asueru"], ["ma faamaufaailogaina ai", "and faamaufaailogaina"], ["i le mama", "in the n"], ["a le tupu;", "but the king"], ["ona molia atu lea o ia", "and accused he"], ["tusi e ua tele vavave", "book by great vavave"], ["e na tietie", "by ride"], ["i solofanua,", "in horse"], ["o e", "who"], ["na tietie", "ride"], ["i manu tele vavave,", "in animal great vavave"], ["ma falata,", "and falata"], ["o tama ia", "child to"], ["a solofanua fafine.", "but horse woman"]]},
  {num:11,words:[["Auā ua tuuina atu e le tupu", "for was given by the king"], ["i sa Iutā o e ua", "in of the clan of Iutā who"], ["i lea aai", "in city"], ["ma lea aai,", "and city"], ["ia latou potopoto,", "to they gather"], ["ma tetee atu ia", "and to refuse to"], ["ola ai", "life"], ["i latou;", "them"], ["ia faaumatia,", "to destroyed"], ["ia fasiotia,", "to slain"], ["ma fano o 'au uma", "and perish of I all"], ["a le nuu", "but the nation"], ["ma le itu malo o e faasaua", "and the side government who cruel"], ["mai ia te i latou,", "from them"], ["o tama iti", "child small"], ["atoa ma fafine,", "and woman"], ["ma ia vetea", "and to vetea"], ["a latou mea,", "but they thing"]]},
  {num:12,words:[["i le aso e tasi", "in the day by one"], ["ia fai ai", "to make"], ["i itu malo uma", "in side government all"], ["o le tupu o Asueru,", "the king of Asueru"], ["o le aso e tasi", "the day by one"], ["le sefulu", "the ten"], ["ma le tolu", "and three"], ["o le masina", "the moon"], ["e sefulu", "by ten"], ["ma le lua", "and two"], ["o le masina lea o Atara.", "the moon of Atara"]]},
  {num:13,words:[["Ua faailoa", "revealed"], ["i nuu uma", "in nation all"], ["le tusi", "the book"], ["na tusia", "written"], ["e avatua", "to given away"], ["e fai ma tulafono", "to be law"], ["i itu malo uma,", "in side government all"], ["ina ia saunia", "so that prepared"], ["sa Iutā", "of the clan of Iutā"], ["i lena aso e taui", "in that day to a reward"], ["ma sui", "and to dilute"], ["e ua ita ia te i latou.", "by angry unto them"]]},
  {num:14,words:[["Ua o atu e ua tele vavave", "of by great vavave"], ["e na tietie manu tele vavave,", "by ride animal great vavave"], ["ma falata,", "and falata"], ["ua faataaliseina,", "to make haste"], ["ma faavaveina", "and make quick"], ["i le poloaiga", "in the commandment"], ["a le tupu.", "but the king"], ["Na avatua foi tulafono ai Susana", "given away also law Susana"], ["le maota.", "the the name of a tree"]]},
  {num:15,words:[["Ona alu atu lea o Moretekai", "and go away of Mordecai"], ["nai luma o le tupu", "from before the king"], ["ua ofu", "garment"], ["i ofu o tupu,", "in garment of king"], ["o le ie uli,", "the faamaise black"], ["ma le ie lino sinasina,", "and the faamaise linen white"], ["ma le pale auro tele,", "and the to row gold great"], ["ma le ofu talaloa", "and the garment to whistle as they fly"], ["o le ie vavae", "the faamaise to divide"], ["ma le pāuli.", "and the pāuli"], ["Ua alalaga fiafia foi ma olioli", "cry out competition also and rejoice"], ["le aai o Susana.", "the city of Susana"]]},
  {num:16,words:[["Na i ai foi i", "therein also in"], ["sa Iutā", "of the clan of Iutā"], ["o le malamalama,", "the light"], ["ma le olioli,", "and the rejoice"], ["ma le fiafia,", "and the competition"], ["ma le mamalu.", "and the glory"]]},
  {num:17,words:[["O mea foi", "thing also"], ["na oo i ai le poloaiga", "oo therein the commandment"], ["a le tupu ma lana tulafono,", "but the king and his law"], ["i itu malo uma,", "in side government all"], ["ma aai uma,", "and city all"], ["ua tupu ai le olioli", "king the rejoice"], ["ma le fiafia", "and the competition"], ["i sa Iutā,", "in of the clan of Iutā"], ["ua fai foi le tausamiga", "make also the feast"], ["ma le aso lelei.", "and the day good"], ["E toatele foi tagata", "many also man"], ["o le nuu", "the nation"], ["ua fai ma tagata o", "to be man of"], ["sa Iutā;", "of the clan of Iutā"], ["auā ua matatau", "for fear"], ["i latou", "them"], ["i sa Iutā.", "in of the clan of Iutā"]]},
];
renderVerseSet(_est_ch_8_Verses, 'est-ch8-verses');

var _est_ch_9_Verses = [
  {num:1,words:[["O le masina", "the moon"], ["e sefulu", "by ten"], ["ma le lua,", "and two"], ["o le masina lea o Atara,", "the moon of Atara"], ["o lona aso e sefulu", "his day by ten"], ["ma le tolu,", "and three"], ["a oo ina taunuu ai le poloaiga", "but oo so that fulfilled the commandment"], ["a le tupu ma lana tulafono,", "but the king and his law"], ["o le aso", "the day"], ["na faamoemoe ai o e", "hope who"], ["na ita", "angry"], ["i sa Iutā latou te manumalo ai ia te i latou,", "in of the clan of Iutā they overcome unto them"], ["(a ua liua,", "but turned into"], ["ma ua manumalo ai", "and overcome"], ["sa Iutā", "of the clan of Iutā"], ["i e", "in by"], ["na 'ino'ino ia te i latou;)", "hate unto them"]]},
  {num:2,words:[["na potopoto ai", "gather"], ["sa Iutā", "of the clan of Iutā"], ["i a latou aai", "in but they city"], ["i itu malo uma", "in side government all"], ["o le tupu o Asueru,", "the king of Asueru"], ["e faaoo o latou", "to bring upon of they"], ["lima i", "five in"], ["e na saili", "by sought"], ["e agaleaga ia te i latou;", "to unkind unto them"], ["a e lei tu mai", "but by not stood"], ["se tasi", "a one"], ["i o latou luma;", "before them"], ["auā ua matatau tagata uma", "for fear man all"], ["ia te i latou.", "unto them"]]},
  {num:3,words:[["Ua fesoasoani foi i", "to help also in"], ["sa Iutā o alii uma", "of the clan of Iutā of Lord all"], ["o itu malo,", "side government"], ["ma alii sili,", "and Lord most"], ["ma e pule i nuu,", "and to rule in nation"], ["ma e", "and by"], ["na faia feau", "made errand"], ["a le tupu;", "but the king"], ["auā ua matatau", "for fear"], ["i latou ia Moretekai;", "them to Mordecai"]]},
  {num:4,words:[["auā ua sili Moretekai", "for most Mordecai"], ["i le aiga o le tupu,", "in the family of the king"], ["ua oo foi lona logo", "it came to pass also his to hear"], ["i itu malo uma;", "in side government all"], ["auā ua alualu", "for pursue"], ["ona sili o lenei tagata", "and most now man"], ["o Moretekai.", "Mordecai"]]},
  {num:5,words:[["Ua fasia foi e", "struck also by"], ["sa Iutā o e", "of the clan of Iutā who"], ["na ita uma ia te i latou", "angry all unto them"], ["i le fasiga", "in the fasiga"], ["i le pelu,", "by the sword"], ["ma ua fasioti,", "and killed"], ["ua fano;", "perish"], ["ua latou faia la latou faitalia", "they did their as I"], ["i e", "in by"], ["na 'ino'ino ia te i latou.", "hate unto them"]]},
  {num:6,words:[["Ua fasiotia foi,", "slain also"], ["ma faaumatia", "and destroyed"], ["e sa Iutā", "by of the clan of Iutā"], ["i Susana", "in Susana"], ["le maota o tagata", "the the name of a tree of men"], ["e lima selau,", "five hundred"]]},
  {num:7,words:[["atoa foi ma Paresaneta,", "together with also and Paresaneta"], ["ma Tafono,", "and Tafono"], ["ma Asefata,", "and Asefata"]]},
  {num:8,words:[["ma Porata,", "and Porata"], ["ma Ataleia,", "and Ataleia"], ["ma Aritatu,", "and Aritatu"], ["ma Paremaseta,", "and Paremaseta"]]},
  {num:9,words:[["ma Arisai,", "and Arisai"], ["ma Arita,", "and Arita"], ["ma Vaisato.", "and Vaisato"]]},
  {num:10,words:[["O atalii ia", "sons to"], ["e toasefulu o Hamanu", "to ten (people) of Haman"], ["le atalii o Hametatu,", "the son of Hametatu"], ["o le", "the"], ["na faasaua", "cruel"], ["i sa Iutā", "in of the clan of Iutā"], ["na fasiotia", "slain"], ["i latou;", "them"], ["a e lei vetea", "but by not vetea"], ["e i latou", "by them"], ["le oloa.", "the goods"]]},
  {num:11,words:[["O lena aso", "that day"], ["na avatua ai", "given away"], ["i le tupu le faitau aofai", "in the king the to count number"], ["o e", "who"], ["na fasiotia", "slain"], ["i Susana", "in Susana"], ["le maota.", "the the name of a tree"]]},
  {num:12,words:[["Ona fai atu lea o le tupu", "And he said the king"], ["i le masiofo o Eseta,", "in the wife of a Samoan paramount chief of Esther"], ["Ua fasiotia,", "slain"], ["ma faaumatia", "and destroyed"], ["e sa Iutā", "by of the clan of Iutā"], ["i Susana", "in Susana"], ["le maota o tagata", "the the name of a tree of men"], ["e lima selau,", "five hundred"], ["atoa ma atalii o Hamanu", "and son of Haman"], ["e toasefulu;", "to ten (people)"], ["se a se mea", "a but a thing"], ["ua latou faia", "they did"], ["i isi itumalo uma", "in other itumalo all"], ["o le tupu? O lenei,", "the king now"], ["se a se mea e te toe ole", "a but a thing by again entreat"], ["mai ai? E avatua ia te oe;", "from to given away unto you"], ["se a foi", "a but also"], ["se mea e te toe faatoga", "a thing by again order"], ["mai i ai? E faia", "from therein to made"], ["lava.", "indeed"]]},
  {num:13,words:[["Ona tali mai lea o Eseta,", "and respond from of Esther"], ["Afai a lelei", "if but good"], ["i le tupu,", "in the king"], ["ia tuuina foi taeao", "to given also morning"], ["i sa Iutā o e i Susuna", "in of the clan of Iutā who in Susuna"], ["ona ia faia e pei o le tulafono", "and to made like the law"], ["i le asō,", "in the asō"], ["ma ia latou faatautauina", "and to they make to hang up"], ["i le laau atalii o Hamanu", "in the tree son of Haman"], ["e toatinoagafulu.", "to ten (people)"]]},
  {num:14,words:[["Ona fai atu lea o le tupu,", "And he said the king"], ["Ia faia faapea.", "to made thus"], ["Ona tala'iina lea o le tulafono", "and preached the law"], ["i Susana.", "in Susana"], ["Ona faatautauina lea e i latou", "and make to hang up by them"], ["atalii o Hamanu", "son of Haman"], ["e toatinoagafulu.", "to ten (people)"]]},
  {num:15,words:[["Ua potopoto foi", "gather also"], ["sa Iutā", "of the clan of Iutā"], ["e na", "by"], ["i Susana", "in Susana"], ["i le aso e sefulu", "in the day by ten"], ["ma le fa", "and four"], ["o le masina o Atara,", "the moon of Atara"], ["ona latou fasiotia lea", "and they slain"], ["i Susana o tagata", "in Susana of men"], ["e tolu selau;", "three hundred"], ["a e lei vetea", "but by not vetea"], ["e i latou", "by them"], ["le oloa.", "the goods"]]},
  {num:16,words:[["O sa Iutā uma foi e", "of the clan of Iutā all also by"], ["na i ai", "therein"], ["i itu malo o le tupu,", "in side government the king"], ["na potopoto i latou", "gather them"], ["e tetee atu ia", "to to refuse to"], ["ola ai", "life"], ["i latou,", "them"], ["ona mapu ai lea o", "and mapu of"], ["i latou", "them"], ["i e", "in by"], ["na ita ia te i latou;", "angry unto them"], ["na latou fasiotia foi e", "they slain also by"], ["na 'ino'ino ia te i latou", "hate unto them"], ["e fitu sefulu o afe", "by seven ten of thousand"], ["ma afe", "and thousand"], ["e lima", "by five"], ["a e lei vetea", "but by not vetea"], ["e i latou", "by them"], ["le oloa,", "the goods"]]},
  {num:17,words:[["o le aso e sefulu", "the day by ten"], ["ma le tolu", "and three"], ["o le masina o Atara", "the moon of Atara"], ["na fasia ai;", "struck"], ["ona mapu ai lea o", "and mapu of"], ["i latou", "them"], ["i lona aso e sefulu", "in his day by ten"], ["ma le fa,", "and four"], ["ma fai ai lena", "and make that"], ["ma aso e fai ai le tausamiga,", "and for days to make the feast"], ["ma olioli ai.", "and rejoice"]]},
  {num:18,words:[["O lona aso e sefulu", "his day by ten"], ["ma le tolu,", "and three"], ["ma lona aso e sefulu", "and his day by ten"], ["ma le fa", "and four"], ["na potopoto ai", "gather"], ["sa Iutā", "of the clan of Iutā"], ["e na", "by"], ["i Susana;", "in Susana"], ["ona mapu ai lea o", "and mapu of"], ["i latou", "them"], ["i lona aso e sefulu", "in his day by ten"], ["ma le lima,", "and five"], ["ma ua fai lena", "and make that"], ["ma aso e fai ai le tausamiga,", "and for days to make the feast"], ["ma olioli ai.", "and rejoice"]]},
  {num:19,words:[["O le mea lea", "therefore"], ["na fai ai e", "make by"], ["sa Iutā", "of the clan of Iutā"], ["sa i faoa aai,", "in seized captive city"], ["e na nonofo", "by dwelling"], ["i aai", "in city"], ["e le nofo 'olo,", "by the dwell fortress"], ["o le aso e sefulu", "the day by ten"], ["ma le fa", "and four"], ["o le masina o Atara", "the moon of Atara"], ["ma aso lelei", "and for days good"], ["e olioli ai,", "to rejoice"], ["ma fai ai le tausamiga,", "and make the feast"], ["ma feaveai ai tufaaga.", "and carry about portion"]]},
  {num:20,words:[["Na tusia foi e Moretekai", "written also to Mordecai"], ["o ia mea,", "he thing"], ["na ia avatua foi tusi", "to given away also book"], ["i sa Iutā uma", "in of the clan of Iutā all"], ["e na", "by"], ["i ai", "therein"], ["i itu malo uma", "in side government all"], ["o le tupu o Asueru,", "the king of Asueru"], ["o e", "who"], ["na latalata mai", "near from"], ["atoa ma", "and"], ["e mamao atu,", "to to be far ofl\""]]},
  {num:21,words:[["e faamau ai ia te i latou,", "to establish unto them"], ["ona ia faia le aso e sefulu", "and to made the day by ten"], ["ma le fa", "and four"], ["o le masina o Atara,", "the moon of Atara"], ["ma lona aso e sefulu", "and his day by ten"], ["ma le lima", "and five"], ["i tausaga uma,", "in year all"]]},
  {num:22,words:[["auā o aso ia", "for of day to"], ["na mapu ai", "mapu"], ["sa Iutā", "of the clan of Iutā"], ["i e", "in by"], ["na ita ia te i latou,", "angry unto them"], ["o le masina foi", "the moon also"], ["na liliuina ai", "turned"], ["mo i latou", "for them"], ["o le faanoanoa", "the mourn"], ["i le olioli,", "in the rejoice"], ["ma le faavauvau", "and the faavauvau"], ["i le aso lelei;", "in the day good"], ["ona ia faia ia", "and to made to"], ["aso ma aso e fai ai le tausamiga,", "day and for days to make the feast"], ["ma olioli ai,", "and rejoice"], ["ma feaveai ai tufaaga,", "and carry about portion"], ["ma mea alofa", "and thing love"], ["i e matitiva.", "in to poor"]]},
  {num:23,words:[["Ona talia lea e", "and received by"], ["sa Iutā", "of the clan of Iutā"], ["e fai ma tu o mea", "to be stand of thing"], ["na latou amata", "they began"], ["ona faia,", "and made"], ["ma mea", "and thing"], ["na tusi atu ai e Moretekai", "book to Mordecai"], ["ia te i latou;", "unto them"]]},
  {num:24,words:[["auā o Hamanu", "for of Haman"], ["le atalii o Hametatu", "the son of Hametatu"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["o le", "the"], ["na faasaua", "cruel"], ["i sa Iutā uma,", "in of the clan of Iutā all"], ["na ia manatu", "to thought"], ["i sa Iutā", "in of the clan of Iutā"], ["ona ia fano", "and to perish"], ["i latou.", "them"], ["Na ia fai foi le Puro,", "to make also the Puro"], ["o le vili lea,", "the a gimblet"], ["ina ia faaumatia", "so that destroyed"], ["i latou,", "them"], ["ma ia fano", "and to perish"], ["i latou.", "them"]]},
  {num:25,words:[["A ua alu atu Eseta", "but go away Esther"], ["i le tupu,", "in the king"], ["ona poloai atu ai lea e ia i lana tusi", "and command by him in his book"], ["ia toe foi atu i lona", "to went back in his"], ["lava ulu lana manatu leaga", "indeed head his thought evil"], ["na ia manatu ai", "to thought"], ["i sa Iutā,", "in of the clan of Iutā"], ["ma ia faatautauina o ia ma ona atalii", "and to make to hang up he and then son"], ["i le laau.", "in the tree"]]},
  {num:26,words:[["O le mea lea", "therefore"], ["na ta'ua ai o ia", "us (two, incl) he"], ["aso o Puro,", "day of Puro"], ["i le igoa", "in the name"], ["o le Puro.", "the Puro"], ["O mea uma foi", "everything also"], ["o le tusi,", "the book"], ["ma mea", "and thing"], ["na latou vaavaaia", "they vaavaaia"], ["i lenei mea,", "in this thing"], ["ma mea", "and thing"], ["na oo ia te i latou,", "oo unto them"]]},
  {num:27,words:[["na faamauina ai e", "established by"], ["sa Iutā,", "of the clan of Iutā"], ["ma talia ai", "and received"], ["mo i latou", "for them"], ["ma a latou fanau,", "and but they born"], ["ma e ua faatasia", "and by faatasia"], ["ma i latou,", "and them"], ["ia le toe mavae ona faia", "to the again passed then made"], ["o ia lava aso e lua", "he indeed day by two"], ["e tusa ma a latou", "according to but they"], ["tusi,", "book"], ["i ona lava po,", "in then indeed night"], ["i tausaga uma;", "in year all"]]},
  {num:28,words:[["ma ia manatua", "and to remember"], ["ma faia o ia lava aso", "and made he indeed day"], ["i tupulaga uma,", "in generation all"], ["i lea aiga", "in family"], ["ma lea aiga,", "and family"], ["i lea itu malo", "in side government"], ["ma lea itu malo,", "and side government"], ["i lea aai", "in city"], ["ma lea aai;", "and city"], ["aua foi le toe mavae", "for also the again passed"], ["i sa Iutā o ia lava aso", "in of the clan of Iutā he indeed day"], ["o Puro,", "Puro"], ["ma ia le tuua", "and to the left"], ["le faamanatunatu", "the make meditate"], ["i ai", "therein"], ["i la latou fanau.", "in their born"]]},
  {num:29,words:[["O le masiofo o Eseta,", "the wife of a Samoan paramount chief of Esther"], ["le afafine o Aviaila,", "the daughter of Aviaila"], ["ma Moretekai", "and Mordecai"], ["o lo", "lo"], ["sa Iutā,", "of the clan of Iutā"], ["na la tusi atu", "la book"], ["ma le pule lava", "and the rule indeed"], ["e faamauina ai lenei lua", "to established this two"], ["o tusi", "book"], ["i Puro.", "in Puro"]]},
  {num:30,words:[["Ua ia avatua foi tusi", "to given away also book"], ["i sa Iutā uma", "in of the clan of Iutā all"], ["i itu malo", "in side government"], ["e tasi", "by one"], ["le selau", "the hundred"], ["e lua sefulu", "by two ten"], ["ma le fitu", "and seven"], ["o le malo o Asueru,", "the government of Asueru"], ["o upu alofa", "word love"], ["ma le faamaoni,", "and the faithful"]]},
  {num:31,words:[["ina ia faamauina o ia", "so that established he"], ["aso o Puro", "day of Puro"], ["i ona lava po,", "in then indeed night"], ["e pei ona", "as"], ["pule e Moretekai", "rule to Mordecai"], ["o lo", "lo"], ["sa Iutā", "of the clan of Iutā"], ["ma le masiofo o Eseta", "and the wife of a Samoan paramount chief of Esther"], ["ia te i latou,", "unto them"], ["e pei ona", "as"], ["latou faatuina foi", "they built also"], ["mo i latou", "for them"], ["ma a latou fanau,", "and but they born"], ["o mea o anapogi", "thing of to fast"], ["ma lo latou alalaga.", "and the they cry out"]]},
  {num:32,words:[["O le poloaiga", "the commandment"], ["a Eseta", "of Esther"], ["na faamauina ai o ia mea", "established he thing"], ["o Puro;", "Puro"], ["na tusia ai foi i le tusi.", "written also in the book"]]},
];
renderVerseSet(_est_ch_9_Verses, 'est-ch9-verses');

var _est_ch_10_Verses = [
  {num:1,words:[["Na totogi atu e le tupu", "wages by the king"], ["o Asueru", "Asueru"], ["i le vao nuu,", "in the wilderness nation"], ["ma nuu tuloto", "and nation tuloto"], ["i tai,", "towards the sea"], ["ia faia le taulaga ia te ia.", "to made the offering to him"]]},
  {num:2,words:[["O mea uma", "everything"], ["na faia", "made"], ["i lana pule", "in his rule"], ["ma lona malosi,", "and his strong"], ["ma le tala", "and the side"], ["i le silisili o Moretekai", "in the very much of Mordecai"], ["na faasilisiliina ai o ia", "make very much he"], ["e le tupu,", "by the king"], ["e lei tusia ea ia mea", "by not written to rise (as a diver to the sur- to thing"], ["i le tusi o tala", "in the book of side"], ["i nofoaiga", "in reign"], ["a tupu o Metai", "but king of Metai"], ["ma Peresia?", "and Persia"]]},
  {num:3,words:[["Auā na aupito Moretekai", "for ^ to be Mordecai"], ["o lo", "lo"], ["sa Iutā", "of the clan of Iutā"], ["i le tupu o Asueru;", "in the king of Asueru"], ["na silisili o ia i", "very much he in"], ["sa Iutā;", "of the clan of Iutā"], ["na fiafia ia te ia", "competition to him"], ["le toatele", "the many"], ["o ona uso;", "then brother"], ["ua saili e ia ia", "seek by him to"], ["manuia lona nuu;", "peace his nation"], ["ua tautala foi ma le alofa", "spoke also and the love"], ["i lona nuu uma.", "in his nation all"]]},
];
renderVerseSet(_est_ch_10_Verses, 'est-ch10-verses');

})();