(function() {
var _est_ch_1_Verses = [
  {num:1,words:[["O", "O"], ["ona po o Asueru,", "and night of Asueru"], ["o Asueru lea", "Asueru"], ["o le", "the"], ["na fai ma", "to be"], ["tupu", "king"], ["e gata mai", "a snake from"], ["i Initia", "in Initia"], ["e oo atu", "it shall come to pass"], ["i Aitiope,", "in Aitiope"], ["i itu mālō", "in side kingdom"], ["e tasi", "one"], ["le selau", "the hundred"], ["e lua sefulu", "two ten"], ["ma le fitu;", "and seven"]]},
  {num:2,words:[["o", "o"], ["ona po ia,", "and night he"], ["ina o nofo", "so that of dwell"], ["le tupu o Asueru", "the king of Asueru"], ["i le nofoālii", "in the throne"], ["o lona mālō,", "his kingdom"], ["sa", "sa"], ["i ai", "therein"], ["i Susana", "in Susana"], ["le maota,", "the name of a tree"]]},
  {num:3,words:[["o le tolu", "the three"], ["o tausaga", "year"], ["o lana nofoaiga", "his reign"], ["na ia fai ai", "he did"], ["le tausamiga mā ali'i uma", "the feast and Lord all"], ["ua ia te ia", "to him"], ["ma ana auauna;", "and cave servant"], ["o ē ua sili", "who most"], ["o Peresia", "Persia"], ["ma Metai,", "and Metai"], ["o ali'i", "Lord"], ["ma ali'i o itu mālō,", "and Lord of side kingdom"], ["na", "na"], ["i ona luma;", "before him"]]},
  {num:4,words:[["ina o fa'aaliatua", "so that of faaaliatua"], ["le sosia", "the sosia"], ["o lona mālō mamalu,", "his kingdom glory"], ["ma le silisili", "and the very much"], ["o le matagofie", "the beautiful"], ["o lona malualii,", "his malualii"], ["i aso e tele,", "in day to great"], ["o aso", "day"], ["e selau", "hundred"], ["ma le valu sefulu.", "and eight ten"]]},
  {num:5,words:[["Ua atoatoa ia", "completely he"], ["aso,", "day"], ["ona fai ai lea", "and do then"], ["e le tupu", "shall not king"], ["o le tausamiga mā tagata uma", "the feast and man all"], ["na", "na"], ["i Susana", "in Susana"], ["le maota,", "the name of a tree"], ["o ali'i", "Lord"], ["atoa ma tagata nu'u,", "and man nation"], ["i aso", "in day"], ["e fitu,", "seven"], ["i le lotoā", "in the court"], ["o le fanua", "the land"], ["o le maota", "the name of a tree"], ["o le tupu.", "the king"]]},
  {num:6,words:[["Na tautau ai", "hung up"], ["ie lino sinasina;", "faamaise linen white"], ["o ie lelei", "faamaise good"], ["ma ie uli,", "and faamaise black"], ["na fa'amauina", "established"], ["i maea vavae", "in rope divide"], ["ma le pāuli", "and the blue"], ["i mama ario", "in clean silver"], ["ma pou sesa;", "and pillar Caesar"], ["na", "na"], ["i ai", "therein"], ["moega auro", "bed gold"], ["ma ario", "and silver"], ["i luga", "in above"], ["o le paepae", "the heap up"], ["o paata,", "forbid"], ["ma sesa,", "and Caesar"], ["ma tara,", "and tara"], ["ma sokere.", "and sokere"]]},
  {num:7,words:[["Na avatu ipu", "gave away cup"], ["auro lātou te feinu ai,", "gold they will feinu"], ["o ipu", "cup"], ["e tino eseese,", "body divided"], ["ma uaina", "and wine"], ["a le tupu", "but the king"], ["e tele,", "great"], ["e pei ona", "as"], ["tatau", "ought"], ["i le tupu.", "in the king"]]},
  {num:8,words:[["Na fa'atatau foi", "likened also"], ["i le tulafono", "in the law"], ["ona inu;", "and drink"], ["ua leai se", "there was no"], ["na fa'atauanau atu", "made to be urgent"], ["i se tasi;", "in a one"], ["auā", "for"], ["sa fa'apea ona", "saying and"], ["poloai", "command"], ["e le tupu", "shall not king"], ["i", "in"], ["e pule uma", "rule all"], ["i lona 'āiga,", "in his family"], ["ia taitasi", "he each"], ["le tagata", "the man"], ["ma lana faitalia.", "and his as I"]]},
  {num:9,words:[["O Vasati foi", "Vasati also"], ["le masiofo,", "the wife of a Samoan paramount chief"], ["na ia faia", "he made/did"], ["le tausamiga mā fafine", "the feast and women"], ["i le fale", "in the house"], ["o le tupu,", "the king"], ["o le fale lea", "the house"], ["o le tupu", "the king"], ["o Asueru.", "Asueru"]]},
  {num:10,words:[["O le aso", "the day"], ["e fitu", "seven"], ["ina o fiafia", "so that of pleased"], ["le loto", "the heart"], ["o le tupu", "the king"], ["i le uaina,", "in the wine"], ["na ia fai atu ai", "he said"], ["ia Meumanu,", "he Meumanu"], ["ma Piseta,", "and Piseta"], ["ma Harepona,", "and Harepona"], ["ma Pigeta,", "and Pigeta"], ["ma Avageta,", "and Avageta"], ["o Setara", "Setara"], ["ma Karekase,", "and Karekase"], ["o eunuka ia", "eunuch he"], ["e toafitu", "seven people"], ["e na auauna atu", "by servant"], ["i luma", "in before"], ["o le tupu", "the king"], ["o Asueru,", "Asueru"]]},
  {num:11,words:[["ia aʻu mai le", "he bring the"], ["masiofo o Vasati", "wife of a Samoan paramount chief of Vasati"], ["i luma", "in before"], ["o le tupu,", "the king"], ["ma le palealii", "and the palealii"], ["o le masiofo,", "the wife of a Samoan paramount chief"], ["ina ia fa'aali atu", "so that revealed"], ["lona lalelei", "his beautiful"], ["i le nu'u", "in the land"], ["ma ali'i;", "and Lord"], ["auā", "for"], ["e lalelei lava", "beautiful very"], ["o ia.", "it/he/she"]]},
  {num:12,words:[["A e lei mafai", "but by not able"], ["le masiofo o Vasati", "the wife of a Samoan paramount chief of Vasati"], ["ona alu ane", "and go forth"], ["i le feau", "in the errand"], ["a le tupu", "but the king"], ["na o atu ai", "went"], ["eunuka;", "eunuch"], ["ona matuā ita ai lea", "and exceedingly angry then"], ["o le tupu,", "the king"], ["na tupu tele lava", "king great very"], ["le tiga", "the grieved"], ["o lona loto.", "his heart"]]},
  {num:13,words:[["Ona fai atu lea", "And he said"], ["o le tupu", "the king"], ["i", "in"], ["e popoto,", "short"], ["e na iloa tausaga;", "by knew year"], ["(auā", "for"], ["na fa'apea", "saying"], ["le masani", "the custom"], ["a le tupu", "but the king"], ["ia te i lātou", "unto them"], ["uma", "all"], ["na iloa tulafono", "knew law"], ["ma fa'amasinoga;", "and judgments"]]},
  {num:14,words:[["na latalata ane ia te ia", "near to him"], ["o Karesena,", "Karesena"], ["o Setaru,", "Setaru"], ["o Atematu,", "Atematu"], ["o Tasesa,", "Tasesa"], ["o Merese,", "Merese"], ["o Maresena,", "Maresena"], ["o Memukana,", "Memukana"], ["o ali'i ia", "Lord he"], ["e toafitu o Peresia", "seven people of Persia"], ["ma Metai o", "and Metai of"], ["e na iloa fofoga", "by knew face"], ["o le tupu,", "the king"], ["e na sili", "by most"], ["i le mālō;)", "in the kingdom"]]},
  {num:15,words:[["Se a se mea", "what/how"], ["e faia", "do"], ["i le masiofo", "in the wife of a Samoan paramount chief"], ["o Vasati,", "Vasati"], ["e tusa ma le tulafono,", "according to the law"], ["ina ua", "when"], ["lē mafai o ia", "not able it"], ["i le 'upu", "in the word"], ["a le tupu", "but the king"], ["o Asueru", "Asueru"], ["na o atu ai", "went"], ["eunuka?", "eunuch"]]},
  {num:16,words:[["Ona tali mai lea", "and respond from"], ["o Memukana", "Memukana"], ["i luma", "in before"], ["o le tupu", "the king"], ["ma ali'i,", "and Lord"], ["E le", "by the"], ["na", "na"], ["o le tupu", "the king"], ["na aga fa'apiopio", "did faapiopio"], ["i ai", "therein"], ["le masiofo o Vasati,", "the wife of a Samoan paramount chief of Vasati"], ["a e", "but by"], ["atoa ma ali'i uma", "and Lord all"], ["ma tagata uma", "and people all"], ["o", "o"], ["i itu mālō uma", "in side kingdom all"], ["o le tupu", "the king"], ["o Asueru;", "Asueru"]]},
  {num:17,words:[["auā", "for"], ["e oo atu", "it shall come to pass"], ["le tala", "the side"], ["i le masiofo", "in the wife of a Samoan paramount chief"], ["i fafine uma ona", "in women all his"], ["inosia ai lea", "abominable then"], ["e", "by"], ["i lātou", "them"], ["o", "o"], ["a lātou tāne,", "their man"], ["pe a lātou", "even though / although they"], ["ta'u ane,", "tell"], ["Na poloai atu", "commanded"], ["le tupu o Asueru", "the king of Asueru"], ["ia aʻu mai i ona luma", "he bring before him"], ["le masiofo o Vasati,", "the wife of a Samoan paramount chief of Vasati"], ["a e lei alu ane", "but by not go forth"], ["o ia.", "it/he/she"]]},
  {num:18,words:[["O tamaitai foi", "woman also"], ["o Peresia", "Persia"], ["ma Metai", "and Metai"], ["e ua fa'alogo", "heard"], ["i le tala", "in the side"], ["i le masiofo,", "in the wife of a Samoan paramount chief"], ["e fai atu ai", "said to"], ["i lātou", "them"], ["i le aso nei", "this day"], ["i ali'i uma", "in Lord all"], ["ua", "ua"], ["i le tupu,", "in the king"], ["ona tele ai lea", "and great then"], ["o le 'ino'ino", "the disdained"], ["ma le feitagai.", "and the look upon one another"]]},
  {num:19,words:[["'Āfai", "if"], ["e lelei", "good"], ["i le tupu,", "in the king"], ["ia oo atu", "he arrived"], ["lana afioga mai ia te ia", "his word from him"], ["lava,", "very"], ["ma ia tusia fa'atasi ma tulafono", "and he written together and law"], ["a Peresia", "of Persia"], ["ma Metai,", "and Metai"], ["e le toe tālaina,", "shall not again side"], ["aua", "for"], ["le toe oo mai", "the again came"], ["o Vasati", "Vasati"], ["i luma", "in before"], ["o le tupu", "the king"], ["o Asueru;", "Asueru"], ["a ia fai", "his do"], ["se masiofo", "a wife of a Samoan paramount chief"], ["a le tupu", "but the king"], ["e sui ai", "replace"], ["o ia,", "it/he/she"], ["o se tasi", "a one"], ["e sili", "preferred"], ["ona lelei ia te ia.", "and good to him"]]},
  {num:20,words:[["A logo atu foi", "but hear also"], ["lē pule", "not rule"], ["a le tupu,", "but the king"], ["na te faia,", "he did"], ["i lona mālō uma,", "in his kingdom all"], ["auā", "for"], ["ua tele lea,", "great"], ["ona fa'aaloalo ai lea", "and faaaloalo then"], ["o fafine uma", "all the women"], ["i", "in"], ["a lātou tāne,", "their man"], ["o ali'i", "Lord"], ["atoa ma tagatā nu'u.", "and man nation"]]},
  {num:21,words:[["Ua lelei foi", "that it was good also"], ["lena 'upu", "that word"], ["i le manatu", "in the thought"], ["o le tupu", "the king"], ["ma ali'i;", "and Lord"], ["ona faia lea", "And he made"], ["e le tupu", "shall not king"], ["e pei ona fai atu ai", "as said to"], ["Memukana.", "Memukana"]]},
  {num:22,words:[["Ua ia avatu", "he gave away"], ["tusi", "book"], ["i itu mālō uma", "in side kingdom all"], ["o le tupu,", "the king"], ["ua fa'atatau", "likened"], ["ma le tusilima", "and the tusilima"], ["a lea", "but"], ["itu mālō", "side kingdom"], ["ma lea", "and"], ["itu mālō,", "side kingdom"], ["e tusa foi", "according to also"], ["ma le gagana", "and the language"], ["a lea", "but"], ["nu'u", "nation"], ["ma lea", "and"], ["nu'u,", "nation"], ["ina ia taitoatasi", "so that each one"], ["le tāne", "the man"], ["ma pule", "and rule"], ["i lona 'āiga,", "in his family"], ["ma ia tautala", "and he speak"], ["i le gagana", "in the language"], ["a lona nu'u.", "his nation"]]},
];
renderVerseSet(_est_ch_1_Verses, 'est-ch1-verses');

var _est_ch_2_Verses = [
  {num:1,words:[["Ua mavae ia", "after he"], ["mea,", "thing"], ["ua maona foi", "subside also"], ["le ita", "the angry"], ["o le tupu", "the king"], ["o Asueru,", "Asueru"], ["ona manatua lea", "and remember"], ["e ia", "he"], ["o Vasati,", "Vasati"], ["ma le mea", "and the thing"], ["na ia faia,", "he made/did"], ["i le", "in the"], ["ma le tulafono", "and the law"], ["na faia ia te ia.", "did to him"]]},
  {num:2,words:[["Ona fai atu ai lea", "and said to then"], ["o auauna,", "servant"], ["e na auauna", "by servant"], ["i le tupu,", "in the king"], ["Ia sailiili mai", "he search from"], ["mā", "and"], ["le tupu o teine taupou lalelei.", "the king of girl virgin beautiful"]]},
  {num:3,words:[["Ia tofia foi", "he was chosen also"], ["e le tupu", "shall not king"], ["o matai", "chief"], ["i itu mālō uma", "in side kingdom all"], ["o lona mālō,", "his kingdom"], ["lātou te fa'apotopotoina teine taupou lalelei uma", "they will gathered together girl virgin beautiful all"], ["i Susana", "in Susana"], ["le maota,", "the name of a tree"], ["i le fale", "in the house"], ["o fafine,", "the women"], ["ia Hege", "he Hege"], ["le eunuka", "the eunuch"], ["a le tupu,", "but the king"], ["o lē tausi", "not nurse"], ["i fafine;", "in women"], ["ma ia avatua", "and he given away"], ["ia te i lātou", "unto them"], ["mea", "thing"], ["e fa'amamāina a'i", "cleansed"], ["i lātou.", "them"]]},
  {num:4,words:[["O le teine foi", "the girl also"], ["e fiafia", "pleased"], ["i ai", "therein"], ["le tupu ia", "the king he"], ["avea o ia", "become it"], ["ma masiofo", "and wife of a Samoan paramount chief"], ["e sui ai", "replace"], ["Vasati.", "Vasati"], ["Ua lelei lea", "that it was good"], ["'upu", "word"], ["i le manatu", "in the thought"], ["o le tupu;", "the king"], ["ona ia faia lea", "and he do"], ["fa'apea.", "saying"]]},
  {num:5,words:[["Ua", "Ua"], ["i ai", "therein"], ["i Susana", "in Susana"], ["le maota", "the name of a tree"], ["o le tasi tagata", "the one man"], ["o", "o"], ["sa Iutā,", "of the clan of Judas"], ["o Moretekai", "Mordecai"], ["lona igoa,", "his name"], ["o le atali'i", "the son"], ["o Iairo,", "Iairo"], ["o le atali'i", "the son"], ["ia", "he"], ["o Semi,", "Shimei"], ["o le atali'i", "the son"], ["ia", "he"], ["o Kiso,", "Kiso"], ["o lo", "lo"], ["sa Peniaminā.", "of the clan of Benjamin"]]},
  {num:6,words:[["Ua tāfea mai", "exiled from"], ["o ia mai Ierusalema fa'atasi ma le tafeaga", "it from Jerusalem together and the exiles in wa^"], ["na tāfea fa'atasi ma", "exiled together and"], ["Iekonia", "Iekonia"], ["le tupu o Iuta,", "the king of Judas"], ["o le", "the"], ["na tāfea", "exiled"], ["e Nepukanesa", "Nebuchadnezzar"], ["le tupu o Papelonia.", "the king of Babylon"]]},
  {num:7,words:[["Ua fai o ia", "did it"], ["ma tamā o Hatesa,", "and father of Hatesa"], ["o Eseta foi", "Esther also"], ["o le afafine", "the daughter"], ["o le uso", "the brother"], ["o lona tamā,", "of his father"], ["ina ua leai sona tamā po", "when no sona father night"], ["o sona tinā;", "sona mother"], ["o le teine foi", "the girl also"], ["ua lalelei", "beautiful"], ["lona tino,", "his body"], ["ma", "and"], ["ua lalelei", "beautiful"], ["ona mata.", "and eye"], ["Ua oti", "died"], ["lona tamā", "his father"], ["ma lona tinā,", "and his mother"], ["ona avea ai lea", "and become then"], ["o ia", "it/he/she"], ["e Moretekai", "Mordecai"], ["e fai mona afafine.", "do for him daughter"]]},
  {num:8,words:[["Ua lagona e", "felt by"], ["ia le 'upu", "he the word"], ["a le tupu", "but the king"], ["ma lana tulafono,", "and his law"], ["ma", "and"], ["ua fa'apotopotoina ai", "gathered together"], ["teine", "girl"], ["e toatele", "many"], ["i Susana", "in Susana"], ["le maota ia", "the name of a tree he"], ["Hege,", "Hege"], ["ona avea ai lea", "and become then"], ["o Eseta", "Esther"], ["i le fale", "in the house"], ["o le tupu", "the king"], ["ia Hege,", "he Hege"], ["lē tausi", "not nurse"], ["i fafine.", "in women"]]},
  {num:9,words:[["Ua lelei", "that it was good"], ["le teine", "the girl"], ["i lona manatu,", "in his thought"], ["ua alofaina o ia", "beloved it"], ["e ia;", "he"], ["ona ia vave tuuina atu ai lea", "and he quick given / delivered then"], ["ia te ia", "to him"], ["ana mea", "cave thing"], ["e fa'amamāina a'i,", "cleansed"], ["atoa ma mea", "and thing"], ["na tofia māna,", "was chosen māna"], ["ma teine", "and girl"], ["e toafitu", "seven people"], ["e na filifilia", "by chosen"], ["mai le 'āiga", "from the family"], ["o le tupu", "the king"], ["e tuuina atu", "shall be given"], ["ia te ia;", "to him"], ["ua ia tuu atu foi", "he placed also"], ["ia te ia", "to him"], ["ma lona galu teine", "and his maidens"], ["i le mea sili", "in the thing most"], ["i le fale", "in the house"], ["o fafine.", "the women"]]},
  {num:10,words:[["E lei fa'ailoa atu", "by not declared"], ["e Eseta", "Esther"], ["lona nu'u po", "his nation night"], ["o lona 'āiga;", "his family"], ["auā", "for"], ["na fai atu", "said"], ["e Moretekai ia te ia", "Mordecai to him"], ["aua", "for"], ["na te fa'ailoa atu.", "he declared"]]},
  {num:11,words:[["O lea aso", "therefore day"], ["ma lea aso foi", "and day also"], ["na fealualuai ai", "walked about"], ["o Moetekai", "Moetekai"], ["i luma", "in before"], ["o le lotoā", "the court"], ["o le fale", "the house"], ["o fafine", "the women"], ["ina ia iloa po", "so that know night"], ["o malolo Eseta;", "rest Esther"], ["pe", "whether"], ["se a foi", "a but also"], ["se mea", "a thing"], ["e faia ia te ia.", "do to him"]]},
  {num:12,words:[["Na aua'i", "present"], ["ona solo taitoatasi", "and move swiftly each one"], ["o teine", "girl"], ["i lo lātou", "than they"], ["o atu", "went"], ["i le tupu", "in the king"], ["o Asueru", "Asueru"], ["ina ua atoatoa masina", "when completely month"], ["e sefulu", "ten"], ["ma le lua,", "and two"], ["e tusa ma le tulafono", "according to the law"], ["i fafine;", "in women"], ["auā", "for"], ["na fa'apea ona", "thus"], ["atoatoa ai", "completely"], ["o aso", "day"], ["o le fa'amamāina", "the cleansed"], ["o", "o"], ["i lātou;", "them"], ["o masina", "month"], ["e ono", "six"], ["e uu ai", "oil"], ["i le suāuu muro,", "in the oil muro"], ["ma masina", "and month"], ["e ono", "six"], ["i mea manogi,", "things fragrant"], ["ma mea", "and thing"], ["e fa'amamāina a'i fafine.", "cleansed women"]]},
  {num:13,words:[["Ua fa'apea foi", "saying also"], ["ona alu atu", "and go away"], ["o le teine", "the girl"], ["i le tupu;", "in the king"], ["na avatua ia te ia", "given away to him"], ["mea uma", "all things"], ["na ia fai atu ai", "he said"], ["e alu ai", "go"], ["ma ia mai le fale", "and he from the house"], ["o fafine", "the women"], ["i le fale", "in the house"], ["o le tupu.", "the king"]]},
  {num:14,words:[["O le afiafi", "the evening"], ["na alu atu ai", "went away"], ["o ia,", "it/he/she"], ["o le taeao foi", "the morning also"], ["na toe foi", "returned again"], ["i le lua", "in the two"], ["o fale o fafine", "house the women"], ["ia Sasekasa", "he Sasekasa"], ["le eunuka", "the eunuch"], ["a le tupu,", "but the king"], ["o le leoleo", "the guard"], ["i palake;", "in palake"], ["na ia le", "he the"], ["toe alu atu", "again go away"], ["i le tupu,", "in the king"], ["vagana", "save"], ["ona fiafia", "and pleased"], ["o le tupu", "the king"], ["ia te ia,", "to him"], ["ma", "and"], ["ua valaauina", "called"], ["lona igoa.", "his name"]]},
  {num:15,words:[["Ua oo foi", "it came to pass also"], ["ia Eseta", "he Esther"], ["le afafine o Aviaila", "the daughter of Aviaila"], ["le uso", "the brother"], ["o le tamā", "the father"], ["o Moretekai,", "Mordecai"], ["o le", "the"], ["na faia o ia", "did it"], ["mona afafine,", "for him daughter"], ["ona alu atu", "and go away"], ["i le tupu,", "in the king"], ["e lei fai atu ai", "by not said to"], ["o ia", "it/he/she"], ["i se mea", "in a thing"], ["ua", "ua"], ["na o mea", "only thing"], ["na fai atu ai", "said"], ["Hege", "Hege"], ["le eunuka", "the eunuch"], ["a le tupu,", "but the king"], ["o le tausi fafine.", "the nurse women"], ["Ua alofagia foi", "favored also"], ["Eseta e", "Esther"], ["i lātou uma", "them all"], ["e na iloa", "by knew"], ["o ia.", "it/he/she"]]},
  {num:16,words:[["Ua avea Eseta", "became Esther"], ["i le tupu", "in the king"], ["o Asueru", "Asueru"], ["i le fale", "in the house"], ["o le tupu", "the king"], ["i le sefulu", "in the ten"], ["o masina,", "month"], ["o le masina lea", "the month"], ["o Tapeta,", "Tapeta"], ["i le fitu", "in the seven"], ["o tausaga", "year"], ["o lana nofoaiga.", "his reign"]]},
  {num:17,words:[["Ua sili foi", "most also"], ["le manao", "the desire"], ["o le tupu", "the king"], ["ia Eseta i", "he Esther in"], ["fafine uma,", "women all"], ["ua sili foi", "most also"], ["ona alofaina", "and beloved"], ["ma fa'apelepeleina o ia", "and take care of it"], ["e ia", "he"], ["i taupou uma;", "in virgin all"], ["ona ia tuu atu ai lea", "and he placed then"], ["o le palealii", "the palealii"], ["i lona ulu,", "in his head"], ["ma fai o ia", "and do it"], ["ma masiofo", "and wife of a Samoan paramount chief"], ["e sui a'i Vasati.", "in its place Vasati"]]},
  {num:18,words:[["Ona faia lea", "And he made"], ["e le tupu", "shall not king"], ["o le tausamiga tele mā ali'i uma", "the feast great and Lord all"], ["ua ia te ia", "to him"], ["ma ana auauna,", "and cave servant"], ["o le tausamiga", "the feast"], ["ona o Eseta;", "because of Esther"], ["na ia tuuina atu ia", "he gave he"], ["malolo tagata o itu mālō,", "rest man of side kingdom"], ["na ia foai atu foi", "he gave also"], ["mea alofa", "thing love"], ["e pei ona", "as"], ["tatau", "ought"], ["i le tupu.", "in the king"]]},
  {num:19,words:[["Ua nofo Moretekai", "dwelt Mordecai"], ["i le faitotoa", "at the door"], ["o le tupu,", "the king"], ["ina o fa'apotopotoina fa'alua", "so that of gathered together twice"], ["o taupou.", "virgin"]]},
  {num:20,words:[["E lei fa'ailoa atu", "by not declared"], ["e Eseta", "Esther"], ["lona 'āiga po", "his family night"], ["o lona nu'u;", "his nation"], ["e pei ona fai atu ai", "as said to"], ["Moretekai ia te ia;", "Mordecai to him"], ["auā", "for"], ["na faia", "did"], ["e Eseta mea", "Esther thing"], ["na fai atu ai", "said"], ["Moretekai,", "Mordecai"], ["e pei ona", "as"], ["ia faia", "he do"], ["ina o tausia", "so that of nursed"], ["o ia e", "it by"], ["ia.", "he"]]},
  {num:21,words:[["O", "O"], ["ona po ia", "and night he"], ["ina o nofo Moretekai", "so that of dwell Mordecai"], ["i le faitotoa", "at the door"], ["o le tupu,", "the king"], ["na ita ai", "angry"], ["Piketano", "Piketano"], ["ma Tirese,", "and Tirese"], ["o eunuka ia", "eunuch he"], ["e toalua", "by two"], ["a le tupu,", "but the king"], ["o ē na leoleo", "who guard"], ["i le faitotoa,", "at the door"], ["na lā fia", "sun wanted to do something"], ["fa'aoo foi", "bring upon also"], ["o lā lima", "sun hand"], ["i le tupu", "in the king"], ["o Asueru.", "Asueru"]]},
  {num:22,words:[["Ua iloa", "knew"], ["le mea", "the thing"], ["e Moretekai,", "Mordecai"], ["ona ia fa'ailoa atu lea", "and he declared"], ["i le masiofo", "in the wife of a Samoan paramount chief"], ["o Eseta;", "Esther"], ["ona ta'u atu ai lea", "and told then"], ["e Eseta", "Esther"], ["i le tupu", "in the king"], ["i le igoa", "in the name"], ["o Moretekai.", "Mordecai"]]},
  {num:23,words:[["Ua suesueina", "examined"], ["le mea,", "the thing"], ["ona iloa lea;", "and know"], ["ona fa'atautauina ai lea", "and make to hang up then"], ["o", "o"], ["i laua", "them both"], ["i le lā'au.", "in the tree"], ["Na tusia ai", "written"], ["foi", "also"], ["i luma", "in before"], ["o le tupu", "the king"], ["i le tusi", "in the book"], ["o tala", "side"], ["i nofoaiga.", "in reign"]]},
];
renderVerseSet(_est_ch_2_Verses, 'est-ch2-verses');

var _est_ch_3_Verses = [
  {num:1,words:[["Ua mavae ia", "after he"], ["mea,", "thing"], ["ona fa'asili lea", "and make most"], ["e le tupu", "shall not king"], ["o Asueru ia", "Asueru he"], ["Hamanu", "Haman"], ["le atali'i o Hametatu", "the son of Hametatu"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["ma", "and"], ["na fa'aeaina o ia,", "faaeaina it"], ["ma fa'asili", "and make most"], ["lona nofoa", "his a seat"], ["i ali'i uma", "in Lord all"], ["ua fa'atasi ma ia.", "with him"]]},
  {num:2,words:[["Ona punou lea", "and punou"], ["ma ifo atu", "and down"], ["ia Hamanu o", "he Haman of"], ["auauna uma", "servant all"], ["a le tupu,", "but the king"], ["o ē na", "who"], ["i ai", "therein"], ["i le faitotoa", "at the door"], ["o le tupu;", "the king"], ["auā", "for"], ["na fa'apea ona", "thus"], ["poloai atu", "command"], ["e le tupu", "shall not king"], ["ia faia ia te ia;", "he do to him"], ["a e lei punou Moretekai,", "but by not punou Mordecai"], ["e lei ifo foi.", "by not down also"]]},
  {num:3,words:[["Ona fai atu lea", "And he said"], ["o auauna", "servant"], ["a le tupu,", "of the king"], ["e na", "which was"], ["i ai", "therein"], ["i le faitotoa", "in the gate"], ["o le tupu,", "of the king"], ["ia Moretekai,", "to Mordecai"], ["Se a le mea", "what is this?"], ["ua e soli ai", "why do you transgress"], ["le poloaiga", "the commandment"], ["a le tupu?", "of the king"]]},
  {num:4,words:[["Na fai atu", "said"], ["pea", "continually"], ["i lātou ia te ia", "them to him"], ["i aso uma,", "every day"], ["ae", "but"], ["na lē tali mai", "not responded from"], ["o ia.", "it/he/she"], ["O lea", "therefore"], ["na lātou fa'ailoa atu ai", "they revealed"], ["ia Hamana,", "to Haman"], ["e va'ai", "see"], ["pe", "whether"], ["o le a tumau", "what enduring"], ["le tulaga", "the standing"], ["a Moredekai;", "of Mordecai"], ["auā", "for"], ["na ia fa'amatala atu", "he explained"], ["o ia", "to him"], ["o se tagata Iuta.", "he is a Jew"]]},
  {num:5,words:[["Ua iloa", "knew"], ["e Hamanu", "Haman"], ["ua", "ua"], ["le punou Moretekai,", "the punou Mordecai"], ["ua", "ua"], ["le ifo foi", "the down also"], ["ia te ia;", "to him"], ["ona matuā ita ai lea", "and exceedingly angry then"], ["o Hamanu.", "Haman"]]},
  {num:6,words:[["Na 'ino'ino o ia", "disdained it"], ["e fa'aoo", "bring upon"], ["lona lima ia", "his hand he"], ["Moretekai tau o ia;", "Mordecai fight it"], ["auā", "for"], ["ua lātou fa'ailoa atu ia te ia", "they declared to him"], ["le nu'u o Moretekai;", "the nation of Mordecai"], ["ona manao lea", "and desire"], ["o Hamanu", "Haman"], ["e fa'aumatia", "destroy"], ["sa Iutā uma lava,", "of the clan of Judas all very"], ["le nu'u o Moretekai,", "the nation of Mordecai"], ["e na", "by"], ["i ai", "therein"], ["i le mālō uma", "in all the kingdom"], ["o Asueru.", "Asueru"]]},
  {num:7,words:[["O le masina muamua,", "the month first"], ["o le masina lea", "the month"], ["o Nisani,", "Nisani"], ["o le sefulu", "the ten"], ["ma le lua", "and two"], ["o tausaga", "year"], ["o le tupu", "the king"], ["o Asueru,", "Asueru"], ["na fai ai", "did"], ["le Puro,", "the Puro"], ["o le vili lea,", "the a gimblet"], ["i luma o Hamanu", "before Haman"], ["i lea aso", "on that day"], ["ma lea aso,", "and day"], ["i lea", "in"], ["masina foi", "month also"], ["ma lea", "and"], ["masina,", "month"], ["e oo", "it shall come to pass"], ["i le masina", "in the month"], ["e sefulu", "ten"], ["ma le lua,", "and two"], ["o le masina lea", "the month"], ["o Atara.", "Atara"]]},
  {num:8,words:[["Ona fai atu lea", "And he said"], ["o Hamanu", "Haman"], ["i le tupu", "in the king"], ["o Asueru,", "Asueru"], ["ʻO loʻo", "is/are"], ["i ai", "therein"], ["le tasi nu'u", "the one nation"], ["ua taapeape", "taapeape"], ["ma nonofo solo fa'atasi ma tagata", "and dwelling move swiftly together and people"], ["o itu mālō uma", "side kingdom all"], ["o lou mālō.", "your kingdom"], ["E ese foi", "away also"], ["a lātou tulafono", "their law"], ["i tulafono", "in law"], ["a nu'u uma,", "but nation all"], ["ma", "and"], ["ua lātou", "they"], ["le usiusitai", "the obeyed"], ["i tulafono", "in law"], ["a 'oe", "but you"], ["le tupu;", "the king"], ["o le mea lea,", "therefore"], ["e le tatau ai", "shall not ought"], ["i lau afio", "in your dwell"], ["ona tuu pea", "and put continually"], ["ia te i lātou.", "unto them"]]},
  {num:9,words:[["'Āfai", "if"], ["e lelei ia te 'oe", "good unto you"], ["le tupu,", "the king"], ["ia tusia ia fano i lātou;", "he written to perish them"], ["ou te fuaina atu ai", "I will fruit"], ["taleni ario", "talent silver"], ["e sefulu afe", "ten thousand"], ["i lima o", "in hand of"], ["e faia lenei", "do this"], ["mea,", "thing"], ["ina ia lātou", "so that they"], ["avatu ai", "give away"], ["i mea", "things"], ["e teu ai", "store"], ["oloa", "goods"], ["a le tupu.", "but the king"]]},
  {num:10,words:[["Ona to ese ai lea", "and stripped off then"], ["e le tupu", "shall not king"], ["o lana mama", "his clean"], ["i lona lima,", "with his hand"], ["ma avatu ai", "and give away"], ["ia Hamanu", "he Haman"], ["le atali'i o Hametatu", "the son of Hametatu"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["o lē fa'asaua", "not cruel"], ["i", "in"], ["sa Iutā.", "of the clan of Judas"]]},
  {num:11,words:[["Ua fai atu foi", "said to also"], ["le tupu ia", "the king he"], ["Hamanu,", "Haman"], ["Ua avatua ia te 'oe", "given away unto you"], ["le ario", "the silver"], ["atoa ma lena", "and that"], ["nu'u,", "nation"], ["ina ia", "so that"], ["e faia", "do"], ["i ai", "therein"], ["le mea", "the thing"], ["e lelei ia te 'oe.", "good unto you"]]},
  {num:12,words:[["Ona valaauina lea", "and called"], ["o ē tusiupu", "whose scribe"], ["a le tupu", "but the king"], ["i le aso", "in the day"], ["e tasi", "one"], ["le sefulu", "the ten"], ["ma le tolu", "and three"], ["o le masina muamua,", "the month first"], ["ona tusia ai lea", "and written then"], ["o mea uma", "everything"], ["ua fai atu ai", "said to"], ["Hamanu", "Haman"], ["e avatu", "give away"], ["i ali'i sili", "in Lord most"], ["ua", "ua"], ["i le tupu,", "in the king"], ["ma", "and"], ["e pule,", "rule"], ["o ē na pule", "who rule"], ["i lea", "in"], ["itu mālō", "side kingdom"], ["ma lea", "and"], ["itu mālō,", "side kingdom"], ["o ali'i foi", "Lord also"], ["o lea", "therefore"], ["nu'u", "nation"], ["ma lea", "and"], ["nu'u,", "nation"], ["e fa'atatau", "liken"], ["ma le tusilima", "and the tusilima"], ["a lea", "but"], ["itu mālō", "side kingdom"], ["ma lea", "and"], ["itu mālō,", "side kingdom"], ["e tusa foi", "according to also"], ["ma le gagana", "and the language"], ["a lea", "but"], ["nu'u", "nation"], ["ma lea", "and"], ["nu'u;", "nation"], ["na tusia", "written"], ["i le igoa", "in the name"], ["o le tupu", "the king"], ["o Asueru,", "Asueru"], ["na fa'amaufaailogaina foi", "sealed also"], ["i le mama", "in the clean"], ["a le tupu.", "but the king"]]},
  {num:13,words:[["Ona molia lea", "and accused"], ["o tusi", "book"], ["e ua tele vavave", "great quick"], ["i itu mālō uma", "in side kingdom all"], ["o le tupu,", "the king"], ["ina ia fa'aumatia,", "so that destroy"], ["ma ia fasiotia,", "and he slain"], ["ma ia fano", "and to perish"], ["sa Iutā uma,", "of the clan of Judas all"], ["o taulelea", "young men"], ["atoa ma toeaina,", "and elder"], ["o tama iti", "child small"], ["atoa ma fafine,", "and women"], ["i le aso", "in the day"], ["e tasi,", "one"], ["o le sefulu", "the ten"], ["ma le tolu lea", "and three"], ["o aso", "day"], ["o le sefulu", "the ten"], ["ma le lua", "and two"], ["o masina,", "month"], ["o le masina lea", "the month"], ["a Atara;", "of Atara"], ["ma", "and"], ["a lātou mea", "their thing"], ["ia vetea.", "he plundered"]]},
  {num:14,words:[["O le ata", "the a shadow"], ["o le tusi", "the book"], ["e avatua", "given away"], ["e fai ma tulafono", "to be law"], ["i lea", "in"], ["itu mālō", "side kingdom"], ["ma lea", "and"], ["itu mālō uma,", "side kingdom all"], ["ua fa'ailoa atu ai", "declared"], ["i nu'u uma", "in nation all"], ["ina ia saunia", "so that prepared"], ["i lātou", "them"], ["i lea aso.", "on that day"]]},
  {num:15,words:[["Na o atu", "went"], ["e ua tele vavave", "great quick"], ["o fa'ataaliseina", "made haste"], ["i le poloaiga", "in the commandment"], ["a le tupu;", "but the king"], ["na avatua foi", "given away also"], ["le tulafono ai", "the law"], ["Susana", "Susana"], ["le maota.", "the name of a tree"], ["Ona lā nonofo lea", "and sun dwelling"], ["o le tupu", "the king"], ["ma Hamanu,", "and Haman"], ["ua lā feinu;", "sun feinu"], ["a", "but"], ["ua atuatuvale", "greatly distressed"], ["le aai o Susana.", "the cities of Susana"]]},
];
renderVerseSet(_est_ch_3_Verses, 'est-ch3-verses');

var _est_ch_4_Verses = [
  {num:1,words:[["Ua iloa", "knew"], ["e Moretekai mea uma", "Mordecai all things"], ["ua faia,", "did"], ["ona saei ai lea", "and tear then"], ["e Moretekai", "Mordecai"], ["ona ofu,", "and garment"], ["ma", "and"], ["ua ofu o ia", "garment it"], ["i le ie talatala", "in the faamaise untie"], ["ma le lefulefu,", "and the ashes"], ["ma alu atu", "and go away"], ["i totonu", "within"], ["o le aai,", "the cities"], ["ma alaga", "and cry"], ["i le alaga tele", "in the cry great"], ["ma", "and"], ["ua lotulotu.", "dn iinylliing liastilv"]]},
  {num:2,words:[["Ua alu atu lava", "went away very"], ["o ia", "it/he/she"], ["i luma", "in before"], ["o le faitotoa", "the door"], ["o le tupu,", "the king"], ["auā", "for"], ["ua", "ua"], ["sa", "sa"], ["ona ulu atu", "and head"], ["i le faitotoa", "at the door"], ["o le tupu", "the king"], ["a o ofu", "but garment"], ["i le ie talatala.", "in the faamaise untie"]]},
  {num:3,words:[["O lea", "therefore"], ["itu mālō foi", "side kingdom also"], ["ma lea", "and"], ["itu mālō uma", "side kingdom all"], ["na oo", "oo"], ["i ai", "therein"], ["le 'upu", "the word"], ["a le tupu", "but the king"], ["ma lana tulafono,", "and his law"], ["ua fa'anoanoa tele ai", "mourned great"], ["sa Iutā,", "of the clan of Judas"], ["ma", "and"], ["ua anapogi,", "fasting"], ["ma fetagisi,", "and wept"], ["ma tagitu'i;", "and tagitu'i"], ["ua fofola foi", "spread out also"], ["e le toatele", "shall not many"], ["o lātou moega", "their bed"], ["i ie talatala", "in faamaise untie"], ["ma le lefulefu.", "and the ashes"]]},
  {num:4,words:[["Ona o atu lea", "because of"], ["o le galu teine", "the maidens"], ["o Eseta", "Esther"], ["ma ana eunuka,", "and cave eunuch"], ["ma lātou ta'u atu ai", "and they told"], ["ia te ia.", "to him"], ["Ona matuā tiga ai lea", "and exceedingly grieved then"], ["o le masiofo;", "the wife of a Samoan paramount chief"], ["ua ia avatu foi", "he gave away also"], ["ofu", "garment"], ["e ofu ai", "garment"], ["Moretekai,", "Mordecai"], ["ma ia ave ese", "and he take away"], ["lona ie talatala", "his faamaise untie"], ["ia te ia;", "to him"], ["a e lei talia", "but by not received"], ["e ia.", "he"]]},
  {num:5,words:[["Ona valaau atu lea", "then called"], ["e Eseta ia", "Esther he"], ["Hatako,", "Hatako"], ["o le tasi eunuka", "the one eunuch"], ["a le tupu,", "but the king"], ["le", "the"], ["na ia tofia", "he was chosen"], ["mo ia,", "for he"], ["ma", "and"], ["na tuuina atu ia te ia", "given / delivered to him"], ["le feau ia", "the errand he"], ["Moretekai ia iloa", "Mordecai he know"], ["pe", "whether"], ["se a lena?", "a but that"], ["Ona", "and"], ["o le a foi?", "what also"]]},
  {num:6,words:[["Ona alu atu ai lea", "and go away then"], ["o Hatako ia", "Hatako he"], ["Moretekai", "Mordecai"], ["i le malae", "in the"], ["o le aai", "the cities"], ["sa", "sa"], ["i luma", "in before"], ["o le faitotoa", "the door"], ["o le tupu.", "the king"]]},
  {num:7,words:[["Ona fa'ailoa mai lea", "and revealed from"], ["e Moretekai ia te ia", "Mordecai to him"], ["o mea uma", "everything"], ["ua oo ia te ia,", "it came to pass to him"], ["ma le tala tonu", "and the side right"], ["i le ario", "in the silver"], ["na fai atu ai", "said"], ["Hamanu", "Haman"], ["na te fuaina atu", "he fruit"], ["i mea", "things"], ["e teu ai", "store"], ["oloa", "goods"], ["a le tupu", "but the king"], ["ona o", "because of"], ["sa Iutā,", "of the clan of Judas"], ["ina ia fano", "so that perish"], ["i lātou.", "them"]]},
  {num:8,words:[["Na ia aumaia foi", "he brought here also"], ["ia te ia", "to him"], ["le ata", "the a shadow"], ["o le tusi", "the book"], ["o le tulafono", "the law"], ["na avatua mai", "given away from"], ["Susana ia fa'aumatia", "Susana he destroy"], ["i lātou,", "them"], ["ina ia fa'aali atu ai", "so that revealed"], ["ia Eseta,", "he Esther"], ["ma ta'u atu", "and told"], ["ia te ia,", "to him"], ["ma fai atu", "and said to"], ["ia te ia ia", "to him he"], ["alu atu o ia", "go away it"], ["i le tupu,", "in the king"], ["e aioi atu", "cry out"], ["ia te ia,", "to him"], ["ma fa'atoga atu", "and order"], ["ia te ia", "to him"], ["mo lona nu'u.", "for his nation"]]},
  {num:9,words:[["Ona sau lea", "And he came"], ["o Hatako,", "Hatako"], ["ma ta'u mai ia", "and tell from he"], ["Eseta 'upu", "Esther word"], ["a Moretekai.", "of Mordecai"]]},
  {num:10,words:[["Ona tali atu lea", "and respond"], ["o Eseta ia", "Esther he"], ["Hatako,", "Hatako"], ["ma", "and"], ["na tuuina atu ia te ia", "given / delivered to him"], ["le feau ia", "the errand he"], ["Moretekai,", "Mordecai"]]},
  {num:11,words:[["ua fa'apea ,", "saying"], ["Ua iloa", "knew"], ["e auauna uma", "servant all"], ["a le tupu,", "but the king"], ["ma tagata o itu mālō", "and people side kingdom"], ["o le tupu,", "the king"], ["se tāne po", "a man night"], ["o se fafine", "a women"], ["e alu atu", "go away"], ["i le tupu", "in the king"], ["i le lotoā", "in the court"], ["i totonu,", "within"], ["a o lei amia,", "but not amia"], ["e tasi", "one"], ["lana tulafono,", "his law"], ["e oti o ia;", "die it"], ["ua", "ua"], ["na", "na"], ["o le", "the"], ["e fa'aloaloa mai", "stretch out from"], ["i ai", "therein"], ["e le tupu", "shall not king"], ["le tootoo auro", "the staff gold"], ["e ola ai", "life"], ["o ia.", "it/he/she"], ["O aʻu foi,", "I am also"], ["ua", "ua"], ["le amia aʻu", "the amia me"], ["e alu", "go"], ["i le tupu", "in the king"], ["i aso ia", "in day he"], ["e tolu sefulu.", "three ten"]]},
  {num:12,words:[["Ona lātou ta'u atu lea", "and they told"], ["ia Moretekai o", "he Mordecai of"], ["'upu", "word"], ["a Eseta.", "of Esther"]]},
  {num:13,words:[["Ona fai mai lea", "And he said"], ["o Moretekai ia", "Mordecai he"], ["tali atu ia", "respond he"], ["Eseta,", "Esther"], ["Ne'i", "now"], ["e manatu", "thought"], ["i lou loto,", "in your heart"], ["ina ua e", "when by"], ["i ai", "therein"], ["i le 'āiga", "in the family"], ["o le tupu,", "the king"], ["e fa'asaoina ai", "spared"], ["'oe ai", "you"], ["sa Iutā uma.", "of the clan of Judas all"]]},
  {num:14,words:[["Auā 'āfai", "do not if"], ["e te matuā fa'alologo", "you exceedingly hold one's tongue"], ["i nei", "in these"], ["ona po,", "and night"], ["e tupu mai le tuusaunoaina", "king from the tuusaunoaina"], ["ma le laveaiina", "and the delivered"], ["o", "o"], ["sa Iutā mai", "of the clan of Judas from"], ["se tasi mea;", "a one thing"], ["a o 'oe,", "but you"], ["ma le 'āiga", "and the family"], ["o lou tamā", "your father"], ["e fano 'outou;", "perish you all"], ["e iloa foi", "know also"], ["e ai", "by"], ["po", "night"], ["ua fai 'oe", "did you"], ["ma masiofo", "and wife of a Samoan paramount chief"], ["ona", "and"], ["o se aso fa'apenei?", "a day make like this"]]},
  {num:15,words:[["Ona fai atu lea", "And he said"], ["o Eseta,", "Esther"], ["ia tali atu ia", "he respond he"], ["Moretekai,", "Mordecai"]]},
  {num:16,words:[["Alu ia 'oe,", "go he you"], ["ia e fa'apotopoto i", "he to gather in"], ["sa Iutā uma", "of the clan of Judas all"], ["e o", "by of"], ["i ai", "therein"], ["i Susana,", "in Susana"], ["ma ia anapopogi 'outou", "and he anapopogi you all"], ["ona", "and"], ["o aʻu,", "I am"], ["aua foi", "for also"], ["ne'i 'outou aai,", "now you all cities"], ["aua foi", "for also"], ["lē inu", "not drink"], ["i aso", "in day"], ["e tolu", "three"], ["i le po", "at night"], ["ma le ao;", "and the day"], ["o aʻu foi,", "I am also"], ["ma lo'u galu teine mātou", "and my maidens we"], ["te anapopogi fa'apenā;", "anapopogi likewise"], ["e fa'apena foi", "likewise also"], ["ona ou alu atu ai", "and I go away"], ["i le tupu", "in the king"], ["o le mea", "the thing"], ["e le tusa ma le tulafono;", "shall not according to and the law"], ["'āfai ou te oti ai,", "if I will die"], ["oti ai", "die"], ["pea ia.", "continually he"]]},
  {num:17,words:[["Ona alu ai lea", "and go then"], ["o Moretekai,", "Mordecai"], ["ma", "and"], ["na faia o mea uma", "did everything"], ["e pei ona", "as"], ["poloai atu ai", "command"], ["e Eseta ia te ia.", "Esther to him"]]},
];
renderVerseSet(_est_ch_4_Verses, 'est-ch4-verses');

var _est_ch_5_Verses = [
  {num:1,words:[["Ua oo", "it came to pass"], ["i le aso tolu,", "in the day three"], ["ona ofu ai lea", "and garment then"], ["o Eseta", "Esther"], ["i ofu", "in garment"], ["o le masiofo,", "the wife of a Samoan paramount chief"], ["ma tu atu", "and stood"], ["i le lotoā", "in the court"], ["o le fale", "the house"], ["o le tupu,", "the king"], ["o le lotoā", "the court"], ["i totonu", "within"], ["i luma", "in before"], ["o le fale", "the house"], ["o le tupu,", "the king"], ["ʻo loʻo nofo mai le", "is dwelt the"], ["tupu", "king"], ["i le nofoālii", "in the throne"], ["o le tupu", "the king"], ["i le fale", "in the house"], ["o le tupu,", "the king"], ["ua feagai", "opposite"], ["ma le faitotoa", "and the door"], ["o le fale.", "the house"]]},
  {num:2,words:[["Ua iloa mai", "knew from"], ["e le tupu", "shall not king"], ["o le masiofo", "the wife of a Samoan paramount chief"], ["o Eseta ʻo loʻo tu atu", "Esther is stood"], ["i le lotoā,", "in the court"], ["ona alofaina,", "and beloved"], ["lea o ia", "it"], ["e ia;", "he"], ["ua fa'aloaloa mai foi", "stretched out from also"], ["e le tupu", "shall not king"], ["lona tootoo auro", "his staff gold"], ["na", "na"], ["i ai", "therein"], ["i lona lima", "with his hand"], ["ia Eseta;", "he Esther"], ["ona fa'alatalata atu ai lea", "and drew near then"], ["o Eseta,", "Esther"], ["ma pai atu", "and pie"], ["i le iu", "in the become of"], ["o le tootoo.", "the staff"]]},
  {num:3,words:[["Ona fai mai lea", "And he said"], ["o le tupu", "the king"], ["ia te ia,", "to him"], ["Le masiofo e,", "the wife of a Samoan paramount chief by"], ["Eseta,", "Esther"], ["se a ea", "what indeed? / why?"], ["lou manao?", "your desire"], ["Se a le mea", "what / why"], ["e te fa'atoga", "you order"], ["mai ai?", "from"], ["E oo lava", "it shall come to pass very"], ["i le vaeluaina", "in the vaeluaina"], ["o le mālō", "the kingdom"], ["e avatua lava", "given away very"], ["ia te 'oe.", "unto you"]]},
  {num:4,words:[["Ona tali atu lea", "and respond"], ["o Eseta,", "Esther"], ["'Āfai", "if"], ["e lelei", "good"], ["i le tupu,", "in the king"], ["ia māliu atu", "he die"], ["le tupu", "the king"], ["ma Hamanu,", "and Haman"], ["i le asō,", "in the day"], ["i le tautega", "in the eat"], ["ua ou saunia", "I prepared"], ["mo ia.", "for he"]]},
  {num:5,words:[["Ona fai mai lea", "And he said"], ["o le tupu,", "the king"], ["Ia fa'avave ia", "he make quick he"], ["Hamanu", "Haman"], ["ina ia fai", "so that do"], ["le mea", "the thing"], ["a Eseta.", "of Esther"], ["Ona ō lea", "and go"], ["o le tupu", "the king"], ["ma Hamanu", "and Haman"], ["i le taumafataga", "in the feast"], ["na saunia o", "prepared of"], ["Eseta.", "Esther"]]},
  {num:6,words:[["Ona fai mai lea", "And he said"], ["o le tupu", "the king"], ["ia Eseta i le", "he Esther in the"], ["taumafataga", "feast"], ["o le uaina,", "the wine"], ["Se a le mea", "what / why"], ["e te fai mai ai?", "you said"], ["E avatua lava", "given away very"], ["ia te 'oe;", "unto you"], ["pe", "whether"], ["se a foi", "a but also"], ["le mea", "the thing"], ["e te fa'atoga", "you order"], ["mai ai?", "from"], ["E oo lava", "it shall come to pass very"], ["i le vaeluagalemu", "in the vaeluagalemu"], ["o le mālō", "the kingdom"], ["e faia lava.", "do very"]]},
  {num:7,words:[["Ona tali atu lea", "and respond"], ["o Eseta,", "Esther"], ["ua fa'apea atu,", "and said"], ["O le mea ou te ole atu ai,", "the thing I will entreat"], ["ma fa'atoga atu ai", "and order"], ["o lenei;", "now"]]},
  {num:8,words:[["'āfai", "if"], ["ua alofaina aʻu", "beloved me"], ["e le tupu,", "shall not king"], ["'āfai foi", "if also"], ["e lelei", "good"], ["i le tupu", "in the king"], ["ona faia", "and do"], ["le mea ou te fa'atoga atu ai,", "the thing I will order"], ["ma ia faia", "and he do"], ["le mea ou te manao", "the thing I will desire"], ["i ai,", "therein"], ["ina toe afio mai ia", "so that again dwell from he"], ["le tupu", "the king"], ["ma Hamanu", "and Haman"], ["i le tautega ou te saunia", "in the eat I will prepared"], ["mo", "for"], ["i laua,", "them both"], ["ona ou faia lea", "and I do"], ["taeao", "morning"], ["e pei ona", "as"], ["fetalai mai ai", "says"], ["o le tupu.", "the king"]]},
  {num:9,words:[["Ona alu atu lea", "and go away"], ["o Hamanu", "Haman"], ["i lena", "in that"], ["aso", "day"], ["ma le olioli", "and the joy"], ["ma le loto fiafia;", "and the heart pleased"], ["a", "but"], ["ua vaai atu", "looked toward"], ["Hamanu ia Moretekai", "Haman he Mordecai"], ["i le faitotoa", "at the door"], ["o le tupu,", "the king"], ["ua", "ua"], ["le tulai,", "the arise"], ["ua", "ua"], ["le fa'aaloalo foi", "the faaaloalo also"], ["ia te ia,", "to him"], ["ona tele ai lea", "and great then"], ["o le ita", "the angry"], ["o Hamanu ia", "Haman he"], ["Moretekai.", "Mordecai"]]},
  {num:10,words:[["A", "but"], ["ua oono Hamanu;", "oono Haman"], ["ua alu atu foi", "went away also"], ["i lona fale,", "in his house"], ["ma", "and"], ["na aauina atu", "sent"], ["nisi", "some"], ["e amia ana uo,", "by amia cave uo"], ["ma Seresa", "and Seresa"], ["lana avā.", "his wife"]]},
  {num:11,words:[["Ona fa'amatalaina atu lea", "and faamatalaina"], ["e Hamanu ia te", "Haman unto"], ["i lātou", "them"], ["o le mamalu", "the glory"], ["o lona tamaoaiga,", "his economy"], ["ma le toatele", "and the many"], ["o ana fānau,", "cave born"], ["ma mea uma", "and all things"], ["ua fa'asilisiliina ai", "made very much"], ["o ia", "it/he/she"], ["e le tupu,", "shall not king"], ["ma", "and"], ["ona", "and"], ["ua fa'aeaina ai", "faaeaina"], ["o ia ia", "he unto"], ["sili", "most"], ["i ali'i", "in Lord"], ["ma auauna", "and servant"], ["a le tupu.", "but the king"]]},
  {num:12,words:[["Ua fai atu foi", "said to also"], ["Hamanu,", "Haman"], ["Sa", "Sa"], ["lē mafai foi", "not able also"], ["le masiofo o Eseta", "the wife of a Samoan paramount chief of Esther"], ["ona alu atu", "and go away"], ["se isi fa'atasi ma le tupu", "a other together and the king"], ["i le taumafataga", "in the feast"], ["na ia saunia,", "he prepared"], ["na", "na"], ["o aʻu lava.", "I am very"], ["Ua fai mai foi", "said also"], ["ia te aʻu", "unto me"], ["e alu ia te ia", "go to him"], ["a taeao fa'atasi ma le tupu.", "but morning together and the king"]]},
  {num:13,words:[["A e peitai", "but"], ["e le aoga", "shall not useful"], ["lava ia te aʻu", "very unto me"], ["o ia mea uma", "it all things"], ["i aso uma ou te vaai atu ai", "all the days I will looked toward"], ["ia Moretekai", "he Mordecai"], ["o lo", "lo"], ["sa Iutā ʻo loʻo", "of the clan of Judas is"], ["nofo", "dwell"], ["i le faitotoa", "at the door"], ["o le tupu.", "the king"]]},
  {num:14,words:[["Ona fai atu ai lea", "and said to then"], ["ia te ia", "to him"], ["o Seresa", "Seresa"], ["lana avā,", "his wife"], ["ma ana uo uma,", "and cave uo all"], ["Ia saunia", "he prepared"], ["se lā'au,", "a tree"], ["ia limagafulu kupita", "he fifty cubit"], ["lona maualuga,", "his Iiigli"], ["ma ia", "and he"], ["e fai atu", "said to"], ["i le tupu", "in the king"], ["i le taeao,", "in the morning"], ["ia fa'atautauina ai", "he make to hang up"], ["Moretekai;", "Mordecai"], ["ona", "and"], ["e alu ai lea", "go then"], ["ma le fiafia fa'atasi ma le tupu", "and the pleased together and the king"], ["i le taumafataga.", "in the feast"], ["Ua lelei lena", "that it was good that"], ["'upu ia Hamanu;", "word he Haman"], ["ona ia faia lea", "and he do"], ["o le lā'au.", "the tree"]]},
];
renderVerseSet(_est_ch_5_Verses, 'est-ch5-verses');

var _est_ch_6_Verses = [
  {num:1,words:[["O lena", "that"], ["lava po", "very night"], ["na", "na"], ["lē iloa ai", "not know"], ["e le tupu sina moe.", "shall not king white sleep"], ["Ona fai atu lea", "And he said"], ["o le tupu", "the king"], ["e aʻu mai le tusi", "bring the book"], ["e fa'amanatu a'i tala", "remind side"], ["i nofoaiga.", "in reign"], ["Ona faitaulia ai lea", "and counted then"], ["i luma", "in before"], ["o le tupu.", "the king"]]},
  {num:2,words:[["Ona iloa lea", "and know"], ["ua tusia", "written"], ["le mea", "the thing"], ["na ta'u atu", "told"], ["e Moretekai ia", "Mordecai he"], ["Piketano", "Piketano"], ["ma Terese,", "and Terese"], ["o eunuka ia", "eunuch he"], ["e toalua", "by two"], ["a le tupu,", "but the king"], ["e na leoleo", "by guarded"], ["i le faitotoa,", "at the door"], ["o ē na fia fa'aoo", "who want to do something bring upon"], ["o lā lima", "sun hand"], ["i le tupu", "in the king"], ["o Asueru.", "Asueru"]]},
  {num:3,words:[["Ona fai atu lea", "And he said"], ["o le tupu,", "the king"], ["Pe", "whether"], ["se a se mea lelei", "what good"], ["ma se mamalu", "and a glory"], ["ua faia", "did"], ["mo Moretekai", "for Mordecai"], ["ona o lenei", "because of this"], ["mea?", "thing"], ["Ona tali mai lea", "and respond from"], ["o auauna", "servant"], ["a le tupu", "but the king"], ["o ē na auauna atu", "who servant"], ["ia te ia,", "to him"], ["E leai se mea", "there is nothing"], ["ua faia", "did"], ["mo ia.", "for he"]]},
  {num:4,words:[["Ona fai atu lea", "And he said"], ["o le tupu,", "the king"], ["O ai ea", "who"], ["ua", "ua"], ["i le lotoā?", "in the court"], ["Auā", "do not"], ["ua alu ane", "went forth"], ["Hamanu", "Haman"], ["i le lotoā?", "in the court"], ["Auā", "do not"], ["ua alu ane", "went forth"], ["Hamanu", "Haman"], ["i le lotoā", "in the court"], ["i fafo", "in outside"], ["o le fale", "the house"], ["o le tupu", "the king"], ["e fai atu ai", "said to"], ["i le tupu", "in the king"], ["ia fa'atautauina Moretekai i le lā'au", "he make to hang up Mordecai in the tree"], ["ua ia saunia", "he prepared"], ["mo ia.", "for he"]]},
  {num:5,words:[["Ona tali mai lea", "and respond from"], ["o auauna", "servant"], ["a le tupu", "but the king"], ["ia te ia,", "to him"], ["Fa'auta,", "behold"], ["ʻo loʻo tu mai", "is stood"], ["Hamanu", "Haman"], ["i le lotoā.", "in the court"], ["Ona fai atu lea", "And he said"], ["o le tupu,", "the king"], ["Ina sau ia", "so that come he"], ["o ia.", "it/he/she"]]},
  {num:6,words:[["Ua ulufale mai", "entered from"], ["Hamanu,", "Haman"], ["ona fai atu lea", "And he said"], ["o le tupu", "the king"], ["ia te ia", "to him"], ["Se a se mea", "what/how"], ["e faia", "do"], ["i le tagata", "in the man"], ["ua loto", "heart"], ["i ai", "therein"], ["le tupu", "the king"], ["ona ia fa'aneeneeina", "and he to\" praise"], ["o ia?", "it/he/she"], ["Ona fa'apea ifo lea", "and saying down"], ["o Hamanu", "Haman"], ["i lona loto,", "in his heart"], ["Po o ai", "who?"], ["se isi", "a other"], ["e finagalo", "will"], ["le tupu", "the king"], ["ona fa'aneeneeina o ia,", "and to\" praise it"], ["na", "na"], ["o aʻu lava?", "I am very"]]},
  {num:7,words:[["Ona tali mai lea", "and respond from"], ["o Hamanu", "Haman"], ["i le tupu,", "in the king"], ["O le tagata", "man"], ["ua finagalo", "will"], ["i ai", "therein"], ["le tupu", "the king"], ["ona fa'aneeneeina o ia,", "and to\" praise it"]]},
  {num:8,words:[["ia aumaia", "he bring here"], ["le ofu", "the garment"], ["o le tupu", "the king"], ["e ofu ai", "garment"], ["le tupu,", "the king"], ["ma le solofanua", "and the horse"], ["e tietie ai", "ride"], ["le tupu,", "the king"], ["ma le palealii", "and the palealii"], ["o le tupu", "the king"], ["e tuuina", "given"], ["i lona ao;", "in his day"]]},
  {num:9,words:[["ia tuuina atu", "he given / delivered"], ["lena ofu", "that garment"], ["ma lena", "and that"], ["solofanua", "horse"], ["i se tasi ali'i", "in a one Lord"], ["o ali'i sili", "Lord most"], ["ua", "ua"], ["i le tupu,", "in the king"], ["ma ia lātou", "and he they"], ["fa'aofu ai", "armed"], ["le tagata", "the man"], ["ua finagalo", "will"], ["i ai", "therein"], ["le tupu", "the king"], ["ona ia fa'aneeneeina", "and he to\" praise"], ["o ia;", "it/he/she"], ["ia lātou fa'atietie foi", "he they make ride also"], ["ia te ia", "to him"], ["i le solofanua", "in the horse"], ["i le malae", "in the"], ["o le aai,", "the cities"], ["ma ia lātou", "and he they"], ["alalaga", "cry out"], ["i ona luma,", "before him"], ["E fa'apea ona faia", "saying and do"], ["i le tagata", "in the man"], ["ua finagalo", "will"], ["i ai", "therein"], ["le tupu", "the king"], ["ona ia fa'aneeneeina", "and he to\" praise"], ["o ia.", "it/he/she"]]},
  {num:10,words:[["Ona fai atu lea", "And he said"], ["o le tupu", "the king"], ["ia Hamanu,", "he Haman"], ["Ina vave ia,", "so that quick he"], ["ia e ave", "he to take"], ["le ofu", "the garment"], ["ma le solofanua,", "and the horse"], ["e pei ona", "as"], ["e fai mai", "said"], ["na,", "na,"], ["ia e fai", "he to do"], ["fa'apea ia Moretekai", "saying he Mordecai"], ["o lo", "lo"], ["sa Iutā,", "of the clan of Judas"], ["o le nofo", "the dwell"], ["i le faitotoa", "at the door"], ["o le tupu,", "the king"], ["aua", "for"], ["le tuua", "the left"], ["se mea", "a thing"], ["e tasi", "one"], ["i mea uma", "things all"], ["ua e fai mai", "you said"], ["na.", "na."]]},
  {num:11,words:[["Ona ave lea", "and take"], ["e Hamanu", "Haman"], ["o le ofu", "the garment"], ["ma le solofanua,", "and the horse"], ["ma", "and"], ["na fa'aofu ia", "armed he"], ["Moretekai,", "Mordecai"], ["na ia fa'atietie foi", "he made ride also"], ["ia te ia", "to him"], ["i le solofanua", "in the horse"], ["i le malae", "in the"], ["o le aai,", "the cities"], ["ma alaga", "and cry"], ["i ona luma,", "before him"], ["E fa'apea ona faia", "saying and do"], ["i le tagata", "in the man"], ["ua finagalo", "will"], ["i ai", "therein"], ["le tupu", "the king"], ["ona fa'aneeneeina o ia.", "and to\" praise it"]]},
  {num:12,words:[["Ona foi atu lea", "and also"], ["o Moretekai", "Mordecai"], ["i le faitotoa", "at the door"], ["o le tupu;", "the king"], ["a", "but"], ["ua fa'ataalise atu", "made haste"], ["Hamanu", "Haman"], ["i lona fale", "in his house"], ["ma le fa'anoanoa,", "and the mourn"], ["ma", "and"], ["ua ufiufi", "covering"], ["lona ulu.", "his head"]]},
  {num:13,words:[["Ona fa'amatalaina atu lea", "and faamatalaina"], ["e Hamanu ia", "Haman he"], ["Seresa", "Seresa"], ["lana avā", "his wife"], ["ma ana uo uma,", "and cave uo all"], ["o mea uma", "everything"], ["ua oo ia te ia.", "it came to pass to him"], ["Ona fai atu ai lea", "and said to then"], ["ia te ia", "to him"], ["o", "o"], ["ona tagata popoto", "and man short"], ["ma Seresa", "and Seresa"], ["lana avā,", "his wife"], ["'Āfai o so", "if of so"], ["lē fānau", "not born"], ["a", "but"], ["sa Iutā o", "of the clan of Judas of"], ["Moretekai,", "Mordecai"], ["le", "the"], ["ua e amata ai", "you began"], ["ona paū", "and fell"], ["i ona luma,", "before him"], ["e te", "you"], ["le manumalo ia te ia,", "the victory to him"], ["a e matuā paū", "but to exceedingly fell"], ["lava 'oe", "very you"], ["i ona luma.", "before him"]]},
  {num:14,words:[["Ona oo mai lea", "and came"], ["o eunuka", "eunuch"], ["a le tupu,", "but the king"], ["a o tautalatala", "but speak"], ["i lātou", "them"], ["ma Hamanu,", "and Haman"], ["ma lātou nanati", "and they urged"], ["ia te ia,", "to him"], ["ia alu i le", "he go in the"], ["taumafataga", "feast"], ["ua saunia", "prepared"], ["e Eseta.", "Esther"]]},
];
renderVerseSet(_est_ch_6_Verses, 'est-ch6-verses');

var _est_ch_7_Verses = [
  {num:1,words:[["Ua o atu", "went"], ["le tupu", "the king"], ["ma Hamanu", "and Haman"], ["e taumamafa fa'atasi ma le masiofo", "by taumamafa together and the wife of a Samoan paramount chief"], ["o Eseta.", "Esther"]]},
  {num:2,words:[["Ona fai atu ai lea", "and said to then"], ["o le tupu", "the king"], ["ia Eseta i", "he Esther in"], ["lena aso", "that day"], ["e lua ao fai", "two day do"], ["le taumafataga", "the feast"], ["o le uaina,", "the wine"], ["Le masiofo e,", "the wife of a Samoan paramount chief by"], ["Eseta,", "Esther"], ["se a le mea", "what / why"], ["e te ole", "you entreat"], ["mai ai?", "from"], ["E avatua lava", "given away very"], ["ia te 'oe;", "unto you"], ["pe", "whether"], ["se a foi", "a but also"], ["le mea", "the thing"], ["e te fa'atoga", "you order"], ["mai ai?", "from"], ["E oo lava", "it shall come to pass very"], ["i le vaeluaina", "in the vaeluaina"], ["o le mālō", "the kingdom"], ["e faia lava.", "do very"]]},
  {num:3,words:[["Ona tali mai lea", "and respond from"], ["e le masiofo", "shall not wife of a Samoan paramount chief"], ["o Eseta,", "Esther"], ["ua fa'apea mai,", "and said"], ["Le tupu e,", "the king by"], ["'āfai", "if"], ["ua alofaina aʻu", "beloved me"], ["e 'oe,", "you"], ["'āfai", "if"], ["e lelei foi", "good also"], ["i le tupu,", "in the king"], ["se'i", "a flower put into the hair or"], ["e fa'aola mai ia te aʻu", "save from me"], ["i lo'u ole atu,", "in my entreat"], ["ia fa'aola foi", "he save also"], ["lo'u nu'u", "my nation"], ["i lo'u fa'atoga atu;", "in my order"]]},
  {num:4,words:[["auā", "for"], ["ua fa'atauina", "bought"], ["i mātou,", "us"], ["o aʻu", "I am"], ["ma lo'u nu'u,", "and my nation"], ["ina ia fa'aumatia,", "so that destroy"], ["ma ia fasiotia,", "and he slain"], ["ma ia fano.", "and to perish"], ["A e 'āfai ana fa'atauina atu", "but to if cave bought"], ["i mātou", "us"], ["o tāne", "man"], ["ma fafine", "and women"], ["e fai ma pologa", "to be bondage"], ["e ui", "although"], ["ina", "so that"], ["lē mafai", "not able"], ["i le", "in the"], ["ua ita mai", "angry from"], ["ona faia", "and do"], ["o se mea", "a thing"], ["e tusa", "according to"], ["ona aoga", "and useful"], ["ma mea", "and thing"], ["a le tupu", "but the king"], ["a fa'amaumauina,", "but make dwell"], ["a", "but"], ["ua ou fa'alologo.", "I held one's tongue"]]},
  {num:5,words:[["Ona fai atu lea", "And he said"], ["o le tupu", "the king"], ["o Asueru,", "Asueru"], ["ua fa'apea atu", "and said"], ["i le masiofo", "in the wife of a Samoan paramount chief"], ["o Eseta,", "Esther"], ["Po o ai", "who?"], ["lena? Po o fea", "that night of where?"], ["o iai", "there is"], ["le", "the"], ["ua manatu", "thought"], ["i lona loto", "in his heart"], ["ia faia fa'apena?", "he do likewise"]]},
  {num:6,words:[["Ona fai mai lea", "And he said"], ["o Eseta,", "Esther"], ["O le tagata", "man"], ["ua ita mai", "angry from"], ["ma fa'asaua mai,", "and cruel from"], ["o lenei", "now"], ["tagata amio leaga", "man iniquity"], ["o Hamanu.", "Haman"], ["Ona mata'u tele ai lea", "and afraid great then"], ["o Hamanu", "Haman"], ["i luma", "in before"], ["o le tupu", "the king"], ["ma le masiofo.", "and the wife of a Samoan paramount chief"]]},
  {num:7,words:[["Ona tulai lea", "and arise"], ["o le tupu", "the king"], ["nai", "from"], ["le taumafataga", "the feast"], ["o le uaina", "the wine"], ["ua ita,", "angry"], ["ua alu", "went"], ["i le fanua", "in the land"], ["o le maota.", "the name of a tree"], ["Ona tulai lea", "and arise"], ["o Hamanu", "Haman"], ["e aioi", "cry out"], ["i le masiofo", "in the wife of a Samoan paramount chief"], ["o Eseta,", "Esther"], ["ia fa'aolaina o ia;", "to keep alive it"], ["auā", "for"], ["ua ia iloa", "he knew"], ["ua tonu", "right"], ["i le tupu", "in the king"], ["e fa'aoo ia te ia", "bring upon to him"], ["se leaga.", "a evil"]]},
  {num:8,words:[["Ua foi atu", "also"], ["le tupu mai le fanua", "the king from the land"], ["o le maota", "the name of a tree"], ["i le fale", "in the house"], ["na fai ai", "did"], ["le taumafataga", "the feast"], ["o le uaina,", "the wine"], ["ua paū foi", "fell also"], ["Hamanu", "Haman"], ["i le moega", "in the bed"], ["o", "o"], ["i ai", "therein"], ["Eseta;", "Esther"], ["ona fai ane lea", "and said"], ["o le tupu,", "the king"], ["Pe a toso ea foi", "even though / although toso also"], ["le masiofo", "the wife of a Samoan paramount chief"], ["i o'u luma", "before me"], ["i le fale?", "in the house"], ["Ua mavae atu", "after"], ["le 'upu", "the word"], ["i le fofoga", "in the face"], ["o le tupu,", "the king"], ["ona lātou ufitia lea", "and they covered"], ["mata o Hamanu.", "eye of Haman"]]},
  {num:9,words:[["Ua fai ane foi", "said also"], ["i luma", "in before"], ["o le tupu", "the king"], ["e Harepono,", "by Harepono"], ["o le tasi eunuka", "the one eunuch"], ["ia,", "he"], ["Fa'auta foi", "and behold"], ["i le lā'au", "in the tree"], ["na saunia", "prepared"], ["e Hamanu", "Haman"], ["mo Moretekai", "for Mordecai"], ["o le", "the"], ["na ta'u", "told"], ["le mea", "the thing"], ["e sao ai", "the appointed portion of"], ["le tupu,", "the king"], ["ʻo loʻo tu", "is stand"], ["i le fale", "in the house"], ["o Hamanu,", "Haman"], ["e limagafulu kupita", "fifty cubit"], ["lona maualuga.", "his Iiigli"], ["Ona fai atu lea", "And he said"], ["e le tupu,", "shall not king"], ["Ia 'outou fa'atautau ia te ia", "he you all make to hang up to him"], ["i ai.", "therein"]]},
  {num:10,words:[["Ona lātou fa'atautau ai lea", "and they make to hang up then"], ["ia Hamanu i le lā'au", "he Haman in the tree"], ["na ia saunia", "he prepared"], ["mo Moretekai.", "for Mordecai"], ["Ona maona ai lea", "and subside then"], ["o le ita", "the angry"], ["o le tupu.", "the king"]]},
];
renderVerseSet(_est_ch_7_Verses, 'est-ch7-verses');

var _est_ch_8_Verses = [
  {num:1,words:[["O lena", "that"], ["lava aso", "very day"], ["na foaiina atu ai", "given"], ["e le tupu", "shall not king"], ["o Asueru", "Asueru"], ["mo le masiofo", "for the wife of a Samoan paramount chief"], ["o Eseta,", "Esther"], ["le fale o Hamanu", "the house of Haman"], ["o le", "the"], ["na ita", "angry"], ["i", "in"], ["sa Iutā.", "of the clan of Judas"], ["Ua alu atu foi", "went away also"], ["Moretekai", "Mordecai"], ["i luma", "in before"], ["o le tupu,", "the king"], ["auā", "for"], ["ua ta'u atu", "told"], ["e Eseta lā te 'āiga.", "Esther sun family"]]},
  {num:2,words:[["Ona to ese ai lea", "and stripped off then"], ["e le tupu", "shall not king"], ["o lana mama", "his clean"], ["ua ia aveeseina ia", "he carried away he"], ["Hamanu,", "Haman"], ["ma", "and"], ["na tuuina atu ai", "given / delivered"], ["ia Moretekai.", "he Mordecai"], ["Ua tofia foi", "was chosen also"], ["Moretekai", "Mordecai"], ["e Eseta", "Esther"], ["e pule", "rule"], ["i le fale", "in the house"], ["o Hamanu.", "Haman"]]},
  {num:3,words:[["Ona toe tautala atu lea", "and again speak toward"], ["o Eseta", "Esther"], ["i le tupu,", "in the king"], ["ua ia fa'apaū foi", "he overthrow also"], ["i luma", "in before"], ["o", "o"], ["ona vae,", "and foot"], ["ma tagi,", "and cry"], ["ma aioi ia te ia,", "and cry out to him"], ["ia fa'aliliuseina e", "he faaliliuseina by"], ["ia le leaga", "he the evil"], ["a Hamanu", "of Haman"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["ma lana manatu", "and his thought"], ["na ia manatu ai", "he thought"], ["i", "in"], ["sa Iutā.", "of the clan of Judas"]]},
  {num:4,words:[["Ona fa'aloaloa mai lea", "and stretch out from"], ["e le tupu", "shall not king"], ["o le tootoo auro", "the staff gold"], ["ia Eseta.", "he Esther"], ["Ona tulai ai lea", "and arise then"], ["o Eseta,", "Esther"], ["ma tu atu", "and stood"], ["i luma", "in before"], ["o le tupu,", "the king"], ["ona ia fai atu lea,", "and he said to"]]},
  {num:5,words:[["'Āfai", "if"], ["e lelei", "good"], ["i le tupu,", "in the king"], ["'āfai foi", "if also"], ["ua alofaina aʻu", "beloved me"], ["e ia,", "he"], ["ma", "and"], ["ua tonu lenei", "right this"], ["mea", "thing"], ["i le finagalo", "in the will"], ["o le tupu,", "the king"], ["ma", "and"], ["ua fiafia o ia ia te aʻu,", "pleased he unto me"], ["ia tusia", "he written"], ["ina ia liliueseina tusi", "so that liliueseina book"], ["o le manatu", "the thought"], ["a Hamanu", "of Haman"], ["le atali'i o Hametatu,", "the son of Hametatu"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["o le", "the"], ["na tusi atu", "book"], ["ina ia fano", "so that perish"], ["sa Iutā,", "of the clan of Judas"], ["o ē o", "whose"], ["i ai", "therein"], ["i itu mālō uma", "in side kingdom all"], ["o le tupu;", "the king"]]},
  {num:6,words:[["auā ou te mafaia fa'apefea ona ou vaai atu", "for I will able how his I looked toward"], ["i le leaga", "in the evil"], ["o le a oo", "what oo"], ["i lo'u nu'u? Ou te mafaia fa'apefea ona ou vaai atu", "in my nation I will able how his I looked toward"], ["i le fanoga", "in the perish"], ["o lo'u 'āiga?", "my family"]]},
  {num:7,words:[["Ona fai mai lea", "And he said"], ["o le tupu", "the king"], ["o Asueru", "Asueru"], ["i le masiofo", "in the wife of a Samoan paramount chief"], ["o Eseta,", "Esther"], ["ma Moretekai", "and Mordecai"], ["o lo", "lo"], ["sa Iutā,", "of the clan of Judas"], ["Fa'auta,", "behold"], ["ua ou tuuina atu ia", "I have given he"], ["Eseta", "Esther"], ["le fale o Hamanu,", "the house of Haman"], ["ua lātou fa'atautau foi", "they made to hang up also"], ["ia te ia", "to him"], ["i le lā'au,", "in the tree"], ["auā", "for"], ["ua", "ua"], ["na fa'aoo", "brought upon"], ["lona lima", "his hand"], ["i", "in"], ["sa Iutā.", "of the clan of Judas"]]},
  {num:8,words:[["Ina tusi foi", "so that book also"], ["ia 'oulua", "he you two"], ["ona o", "because of"], ["sa Iutā,", "of the clan of Judas"], ["faitalia 'oulua", "as I you two"], ["se mea", "a thing"], ["e tusi", "book"], ["i le igoa", "in the name"], ["o le tupu,", "the king"], ["ma ia fa'amaufaailogaina", "and he seal"], ["i le mama", "in the clean"], ["a le tupu;", "but the king"], ["auā", "for"], ["o le tusi", "the book"], ["ua tusia", "written"], ["i le igoa", "in the name"], ["o le tupu,", "the king"], ["ma fa'amaufaailogaina", "and seal"], ["i le mama", "in the clean"], ["a le tupu", "but the king"], ["e le mafai ona", "cannot"], ["liliueseina.", "liliueseina"]]},
  {num:9,words:[["Ona valaauina lea", "and called"], ["o ē tusiupu", "whose scribe"], ["a le tupu", "but the king"], ["i lena", "in that"], ["lava itu aso", "very side day"], ["i le tolu", "in the three"], ["o masina,", "month"], ["o le masina lea", "the month"], ["o Sevana,", "Sevana"], ["i lona aso", "in his day"], ["e lua sefulu", "two ten"], ["ma le tolu;", "and three"], ["ona tusia lea", "and written"], ["o mea uma", "everything"], ["e pei ona fai atu ai", "as said to"], ["o Moretekai", "Mordecai"], ["e avatu", "give away"], ["i", "in"], ["sa Iutā,", "of the clan of Judas"], ["ma ali'i sili,", "and Lord most"], ["ma", "and"], ["e pule", "rule"], ["i nu'u,", "in nation"], ["ma ali'i e", "and Lord by"], ["pule", "rule"], ["i itu mālō", "in side kingdom"], ["e gata mai", "a snake from"], ["i Initia", "in Initia"], ["e oo atu", "it shall come to pass"], ["i Aitiope,", "in Aitiope"], ["o itu mālō", "side kingdom"], ["e tasi", "one"], ["le selau", "the hundred"], ["ma le lua sefulu", "and two ten"], ["ma le fitu;", "and seven"], ["na tusi atu", "book"], ["i lea", "in"], ["itu mālō", "side kingdom"], ["ma lea", "and"], ["itu mālō", "side kingdom"], ["e tusa ma", "according to"], ["a lātou tusilima,", "their tusilima"], ["ma lea", "and"], ["nu'u", "nation"], ["ma lea", "and"], ["nu'u", "nation"], ["e tusa ma", "according to"], ["a lātou gagana,", "their language"], ["o", "o"], ["sa Iutā foi", "of the clan of Judas also"], ["e tusa ma lā lātou tusilima", "according to their tusilima"], ["ma lā lātou gagana.", "and their language"]]},
  {num:10,words:[["Ua ia tusi atu foi", "he book also"], ["i le igoa", "in the name"], ["o le tupu", "the king"], ["o Asueru,", "Asueru"], ["ma fa'amaufaailogaina ai", "and seal"], ["i le mama", "in the clean"], ["a le tupu;", "but the king"], ["ona molia atu lea", "and accused"], ["o ia tusi", "it book"], ["e ua tele vavave", "great quick"], ["e na tietie", "by rode"], ["i solofanua,", "in horse"], ["o ē na tietie", "who ride"], ["i manu tele vavave,", "in animal great quick"], ["ma falata,", "and falata"], ["o tama ia", "child he"], ["a solofanua fafine.", "but horse women"]]},
  {num:11,words:[["Auā", "do not"], ["ua tuuina atu", "was given"], ["e le tupu", "shall not king"], ["i", "in"], ["sa Iutā o", "of the clan of Judas of"], ["e ua", "e ua"], ["i lea", "in"], ["aai", "cities"], ["ma lea", "and"], ["aai,", "cities"], ["ia lātou potopoto,", "he they gather"], ["ma tetee atu", "and refuse"], ["ia ola ai", "he life"], ["i lātou;", "them"], ["ia fa'aumatia,", "he destroy"], ["ia fasiotia,", "he slain"], ["ma fano o 'au uma", "and perish of troops all"], ["a le nu'u", "but the nation"], ["ma le itu mālō", "and the side kingdom"], ["o ē fa'asaua", "whose cruel"], ["mai ia te", "from"], ["i lātou,", "them"], ["o tama iti", "child small"], ["atoa ma fafine,", "and women"], ["ma ia vetea", "and he plundered"], ["a lātou mea,", "their thing"]]},
  {num:12,words:[["i le aso", "in the day"], ["e tasi ia", "one he"], ["fai ai", "do"], ["i itu mālō uma", "in side kingdom all"], ["o le tupu", "the king"], ["o Asueru,", "Asueru"], ["o le aso", "the day"], ["e tasi", "one"], ["le sefulu", "the ten"], ["ma le tolu", "and three"], ["o le masina", "the month"], ["e sefulu", "ten"], ["ma le lua", "and two"], ["o le masina lea", "the month"], ["o Atara.", "Atara"]]},
  {num:13,words:[["Ua fa'ailoa", "revealed"], ["i nu'u uma", "in nation all"], ["le tusi", "the book"], ["na tusia", "written"], ["e avatua", "given away"], ["e fai ma tulafono", "to be law"], ["i itu mālō uma,", "in side kingdom all"], ["ina ia saunia", "so that prepared"], ["sa Iutā", "of the clan of Judas"], ["i lena", "in that"], ["aso", "day"], ["e taui", "a reward"], ["ma sui", "and replace"], ["e ua ita", "angry"], ["ia te i lātou.", "unto them"]]},
  {num:14,words:[["Ua o atu", "went"], ["e ua tele vavave", "great quick"], ["e na tietie manu tele vavave,", "by rode animal great quick"], ["ma falata,", "and falata"], ["ua fa'ataaliseina,", "made haste"], ["ma fa'avaveina", "and make quick"], ["i le poloaiga", "in the commandment"], ["a le tupu.", "but the king"], ["Na avatua foi", "given away also"], ["tulafono ai", "law"], ["Susana", "Susana"], ["le maota.", "the name of a tree"]]},
  {num:15,words:[["Ona alu atu lea", "and go away"], ["o Moretekai", "Mordecai"], ["nai luma", "from before"], ["o le tupu", "the king"], ["ua ofu", "garment"], ["i ofu o tupu,", "in garment of king"], ["o le ie uli,", "the faamaise black"], ["ma le ie lino sinasina,", "and the faamaise linen white"], ["ma le pale auro tele,", "and the row gold great"], ["ma le ofu talaloa", "and the robe"], ["o le ie vavae", "the faamaise divide"], ["ma le pāuli.", "and the blue"], ["Ua alalaga fiafia foi", "cried out pleased also"], ["ma olioli", "and joy"], ["le aai o Susana.", "the cities of Susana"]]},
  {num:16,words:[["Na", "Na"], ["i ai", "therein"], ["foi", "also"], ["i", "in"], ["sa Iutā", "of the clan of Judas"], ["o le malamalama,", "the light"], ["ma le olioli,", "and the joy"], ["ma le fiafia,", "and the pleased"], ["ma le mamalu.", "and the glory"]]},
  {num:17,words:[["O mea foi", "thing also"], ["na oo", "oo"], ["i ai", "therein"], ["le poloaiga", "the commandment"], ["a le tupu", "but the king"], ["ma lana tulafono,", "and his law"], ["i itu mālō uma,", "in side kingdom all"], ["ma aai uma,", "and every city"], ["ua tupu ai", "king"], ["le olioli", "the joy"], ["ma le fiafia", "and the pleased"], ["i", "in"], ["sa Iutā,", "of the clan of Judas"], ["ua fai foi", "did also"], ["le tausamiga", "the feast"], ["ma le aso lelei.", "and the day good"], ["E toatele foi", "many also"], ["tagata", "man"], ["o le nu'u", "the nation"], ["ua fai ma tagata", "to be man"], ["o", "o"], ["sa Iutā;", "of the clan of Judas"], ["auā", "for"], ["ua matatau", "dismayed"], ["i lātou", "them"], ["i", "in"], ["sa Iutā.", "of the clan of Judas"]]},
];
renderVerseSet(_est_ch_8_Verses, 'est-ch8-verses');

var _est_ch_9_Verses = [
  {num:1,words:[["O le masina", "the month"], ["e sefulu", "ten"], ["ma le lua,", "and two"], ["o le masina lea", "the month"], ["o Atara,", "Atara"], ["o lona aso", "his day"], ["e sefulu", "ten"], ["ma le tolu,", "and three"], ["a oo ina taunuu ai", "but oo so that fulfilled"], ["le poloaiga", "the commandment"], ["a le tupu", "but the king"], ["ma lana tulafono,", "and his law"], ["o le aso", "the day"], ["na fa'amoemoe ai", "hoped"], ["o ē na ita", "who angry"], ["i", "in"], ["sa Iutā lātou te", "of the clan of Judas they will"], ["manumalo ai", "victory"], ["ia te i lātou,", "unto them"], ["(a", "but"], ["ua liua,", "turned"], ["ma", "and"], ["ua manumalo ai", "victory"], ["sa Iutā", "of the clan of Judas"], ["i", "in"], ["e na 'ino'ino", "by disdained"], ["ia te i lātou;)", "unto them"]]},
  {num:2,words:[["na potopoto ai", "gathered"], ["sa Iutā", "of the clan of Judas"], ["i", "in"], ["a lātou aai", "their cities"], ["i itu mālō uma", "in side kingdom all"], ["o le tupu", "the king"], ["o Asueru,", "Asueru"], ["e fa'aoo o lātou", "bring upon their"], ["lima", "hand"], ["i", "in"], ["e na saili", "by sought"], ["e agaleaga ia te", "unkind unto"], ["i lātou;", "them"], ["a e lei tu mai", "but by not stood"], ["se tasi", "a one"], ["i o lātou", "in their"], ["luma;", "before"], ["auā", "for"], ["ua matatau tagata", "dismayed man"], ["uma ia te", "all unto"], ["i lātou.", "them"]]},
  {num:3,words:[["Ua fesoasoani foi", "helped also"], ["i", "in"], ["sa Iutā o", "of the clan of Judas of"], ["ali'i uma o itu mālō,", "Lord all of side kingdom"], ["ma ali'i sili,", "and Lord most"], ["ma", "and"], ["e pule", "rule"], ["i nu'u,", "in nation"], ["ma", "and"], ["e na faia feau", "by did errand"], ["a le tupu;", "but the king"], ["auā", "for"], ["ua matatau", "dismayed"], ["i lātou ia", "them he"], ["Moretekai;", "Mordecai"]]},
  {num:4,words:[["auā", "for"], ["ua sili Moretekai", "most Mordecai"], ["i le 'āiga", "in the family"], ["o le tupu,", "the king"], ["ua oo foi", "it came to pass also"], ["lona logo", "his hear"], ["i itu mālō uma;", "in side kingdom all"], ["auā", "for"], ["ua alualu", "pursued"], ["ona sili o lenei", "and most now"], ["tagata o Moretekai.", "man of Mordecai"]]},
  {num:5,words:[["Ua fasia foi", "slaughtered also"], ["e sa Iutā", "by of the clan of Judas"], ["o ē na ita uma", "who angry all"], ["ia te i lātou", "unto them"], ["i le fasiga", "in the slaughter"], ["i le pelu,", "by the sword"], ["ma", "and"], ["ua fasioti,", "killed"], ["ua fano;", "perished"], ["ua lātou faia", "they did"], ["lā lātou faitalia", "their as I"], ["i", "in"], ["e na 'ino'ino", "by disdained"], ["ia te i lātou.", "unto them"]]},
  {num:6,words:[["Ua fasiotia foi,", "slain also"], ["ma fa'aumatia", "and destroy"], ["e sa Iutā", "by of the clan of Judas"], ["i Susana", "in Susana"], ["le maota o tagata", "the name of a tree men"], ["e lima selau,", "five hundred"]]},
  {num:7,words:[["atoa foi", "together with also"], ["ma Paresaneta,", "and Paresaneta"], ["ma Tafono,", "and Tafono"], ["ma Asefata,", "and Asefata"]]},
  {num:8,words:[["ma Porata,", "and Porata"], ["ma Ataleia,", "and Ataleia"], ["ma Aritatu,", "and Aritatu"], ["ma Paremaseta,", "and Paremaseta"]]},
  {num:9,words:[["ma Arisai,", "and Arisai"], ["ma Arita,", "and Arita"], ["ma Vaisato.", "and Vaisato"]]},
  {num:10,words:[["O atali'i ia", "sons he"], ["e toasefulu o Hamanu", "ten people of Haman"], ["le atali'i o Hametatu,", "the son of Hametatu"], ["o le", "the"], ["na fa'asaua", "cruel"], ["i", "in"], ["sa Iutā", "of the clan of Judas"], ["na fasiotia", "slain"], ["i lātou;", "them"], ["a e lei vetea", "but by not plundered"], ["e", "by"], ["i lātou", "them"], ["le oloa.", "the goods"]]},
  {num:11,words:[["O lena", "that"], ["aso", "day"], ["na avatua ai", "given away"], ["i le tupu", "in the king"], ["le faitau aofai", "the count number"], ["o ē na fasiotia", "who slain"], ["i Susana", "in Susana"], ["le maota.", "the name of a tree"]]},
  {num:12,words:[["Ona fai atu lea", "And he said"], ["o le tupu", "the king"], ["i le masiofo", "in the wife of a Samoan paramount chief"], ["o Eseta,", "Esther"], ["Ua fasiotia,", "slain"], ["ma fa'aumatia", "and destroy"], ["e sa Iutā", "by of the clan of Judas"], ["i Susana", "in Susana"], ["le maota o tagata", "the name of a tree men"], ["e lima selau,", "five hundred"], ["atoa ma atali'i", "and son"], ["o Hamanu", "Haman"], ["e toasefulu;", "ten people"], ["se a se mea", "what/how"], ["ua lātou faia", "they did"], ["i isi itumalo uma", "in other itumalo all"], ["o le tupu?", "the king"], ["O lenei,", "now"], ["se a se mea", "what/how"], ["e te toe ole", "you again entreat"], ["mai ai?", "from"], ["E avatua ia te 'oe;", "given away unto you"], ["se a foi", "a but also"], ["se mea", "a thing"], ["e te toe fa'atoga", "you again order"], ["mai", "from"], ["i ai?", "therein"], ["E faia lava.", "do very"]]},
  {num:13,words:[["Ona tali mai lea", "and respond from"], ["o Eseta,", "Esther"], ["'Āfai", "if"], ["a lelei", "but good"], ["i le tupu,", "in the king"], ["ia tuuina foi", "he given also"], ["taeao", "morning"], ["i", "in"], ["sa Iutā o", "of the clan of Judas of"], ["e", "by"], ["i Susuna", "in Susuna"], ["ona ia faia", "and he do"], ["e pei o le tulafono", "like the law"], ["i le asō,", "in the day"], ["ma ia lātou", "and he they"], ["fa'atautauina", "make to hang up"], ["i le lā'au atali'i", "in the tree son"], ["o Hamanu", "Haman"], ["e toatinoagafulu.", "ten people"]]},
  {num:14,words:[["Ona fai atu lea", "And he said"], ["o le tupu,", "the king"], ["Ia faia fa'apea.", "he do saying"], ["Ona tala'iina lea", "and preached"], ["o le tulafono", "the law"], ["i Susana.", "in Susana"], ["Ona fa'atautauina lea", "and make to hang up"], ["e", "by"], ["i lātou atali'i", "them son"], ["o Hamanu", "Haman"], ["e toatinoagafulu.", "ten people"]]},
  {num:15,words:[["Ua potopoto foi", "gathered also"], ["sa Iutā", "of the clan of Judas"], ["e na", "by"], ["i Susana", "in Susana"], ["i le aso", "in the day"], ["e sefulu", "ten"], ["ma le fa", "and four"], ["o le masina", "the month"], ["o Atara,", "Atara"], ["ona lātou fasiotia lea", "and they slain"], ["i Susana o tagata", "in Susana men"], ["e tolu selau;", "three hundred"], ["a e lei vetea", "but by not plundered"], ["e", "by"], ["i lātou", "them"], ["le oloa.", "the goods"]]},
  {num:16,words:[["O", "O"], ["sa Iutā uma foi", "of the clan of Judas all also"], ["e na", "by"], ["i ai", "therein"], ["i itu mālō", "in side kingdom"], ["o le tupu,", "the king"], ["na potopoto", "gathered"], ["i lātou", "them"], ["e tetee atu", "refuse"], ["ia ola ai", "he life"], ["i lātou,", "them"], ["ona mapu ai lea", "and mapu then"], ["o", "o"], ["i lātou", "them"], ["i", "in"], ["e na ita", "by angry"], ["ia te i lātou;", "unto them"], ["na lātou fasiotia foi", "they slain also"], ["e na 'ino'ino", "by disdained"], ["ia te i lātou", "unto them"], ["e fitu sefulu", "seven ten"], ["o afe", "thousand"], ["ma afe", "and thousand"], ["e lima", "five"], ["a e lei vetea", "but by not plundered"], ["e", "by"], ["i lātou", "them"], ["le oloa,", "the goods"]]},
  {num:17,words:[["o le aso", "the day"], ["e sefulu", "ten"], ["ma le tolu", "and three"], ["o le masina", "the month"], ["o Atara", "Atara"], ["na fasia ai;", "slaughtered"], ["ona mapu ai lea", "and mapu then"], ["o", "o"], ["i lātou", "them"], ["i lona aso", "in his day"], ["e sefulu", "ten"], ["ma le fa,", "and four"], ["ma fai ai", "and do"], ["lena", "that"], ["ma aso", "and for days"], ["e fai ai", "do"], ["le tausamiga,", "the feast"], ["ma olioli ai.", "and joy"]]},
  {num:18,words:[["O lona aso", "his day"], ["e sefulu", "ten"], ["ma le tolu,", "and three"], ["ma lona aso", "and his day"], ["e sefulu", "ten"], ["ma le fa", "and four"], ["na potopoto ai", "gathered"], ["sa Iutā", "of the clan of Judas"], ["e na", "by"], ["i Susana;", "in Susana"], ["ona mapu ai lea", "and mapu then"], ["o", "o"], ["i lātou", "them"], ["i lona aso", "in his day"], ["e sefulu", "ten"], ["ma le lima,", "and five"], ["ma", "and"], ["ua fai lena", "did that"], ["ma aso", "and for days"], ["e fai ai", "do"], ["le tausamiga,", "the feast"], ["ma olioli ai.", "and joy"]]},
  {num:19,words:[["O le mea lea", "therefore"], ["na fai ai", "did"], ["e sa Iutā", "by of the clan of Judas"], ["sa", "sa"], ["i faoa aai,", "in seized cities"], ["e na nonofo", "by dwelling"], ["i aai", "in cities"], ["e le nofo 'olo,", "shall not dwell trench"], ["o le aso", "the day"], ["e sefulu", "ten"], ["ma le fa", "and four"], ["o le masina", "the month"], ["o Atara", "Atara"], ["ma aso lelei", "and for days good"], ["e olioli ai,", "joy"], ["ma fai ai", "and do"], ["le tausamiga,", "the feast"], ["ma feaveai ai", "and carry about"], ["tufaaga.", "portion"]]},
  {num:20,words:[["Na tusia foi", "written also"], ["e Moretekai o ia", "Mordecai it"], ["mea,", "thing"], ["na ia avatua foi", "he given away also"], ["tusi", "book"], ["i", "in"], ["sa Iutā uma", "of the clan of Judas all"], ["e na", "by"], ["i ai", "therein"], ["i itu mālō uma", "in side kingdom all"], ["o le tupu", "the king"], ["o Asueru,", "Asueru"], ["o ē na latalata", "who near"], ["mai", "from"], ["atoa ma", "and"], ["e māmao atu,", "is far/is much more"]]},
  {num:21,words:[["e fa'amau ai", "establish"], ["ia te i lātou,", "unto them"], ["ona ia faia", "and he do"], ["le aso", "the day"], ["e sefulu", "ten"], ["ma le fa", "and four"], ["o le masina", "the month"], ["o Atara,", "Atara"], ["ma lona aso", "and his day"], ["e sefulu", "ten"], ["ma le lima", "and five"], ["i tausaga uma,", "in year all"]]},
  {num:22,words:[["auā o aso", "for day"], ["ia", "he"], ["na mapu ai", "mapu"], ["sa Iutā", "of the clan of Judas"], ["i", "in"], ["e na ita", "by angry"], ["ia te i lātou,", "unto them"], ["o le masina foi", "the month also"], ["na liliuina ai", "turned"], ["mo", "for"], ["i lātou", "them"], ["o le fa'anoanoa", "the mourn"], ["i le olioli,", "in the joy"], ["ma le fa'avauvau", "and the make to rub down"], ["i le aso lelei;", "in the day good"], ["ona ia faia", "and he do"], ["ia aso", "he day"], ["ma aso", "and for days"], ["e fai ai", "do"], ["le tausamiga,", "the feast"], ["ma olioli ai,", "and joy"], ["ma feaveai ai", "and carry about"], ["tufaaga,", "portion"], ["ma mea alofa", "and thing love"], ["i", "in"], ["e matitiva.", "poor"]]},
  {num:23,words:[["Ona talia lea", "and received"], ["e sa Iutā", "by of the clan of Judas"], ["e fai ma tu", "to be stand"], ["o mea", "thing"], ["na lātou amata", "they began"], ["ona faia,", "and do"], ["ma mea", "and thing"], ["na tusi atu ai", "book"], ["e Moretekai ia te", "Mordecai unto"], ["i lātou;", "them"]]},
  {num:24,words:[["auā o Hamanu", "for Haman"], ["le atali'i o Hametatu", "the son of Hametatu"], ["o lo", "lo"], ["sa Akakō,", "of the clan of Akakō"], ["o le", "the"], ["na fa'asaua", "cruel"], ["i", "in"], ["sa Iutā uma,", "of the clan of Judas all"], ["na ia manatu", "he thought"], ["i", "in"], ["sa Iutā", "of the clan of Judas"], ["ona ia fano", "and to perish"], ["i lātou.", "them"], ["Na ia fai foi", "he did also"], ["le Puro,", "the Puro"], ["o le vili lea,", "the a gimblet"], ["ina ia fa'aumatia", "so that destroy"], ["i lātou,", "them"], ["ma ia fano", "and to perish"], ["i lātou.", "them"]]},
  {num:25,words:[["A", "but"], ["ua alu atu", "went away"], ["Eseta", "Esther"], ["i le tupu,", "in the king"], ["ona poloai atu ai lea", "and command then"], ["e ia", "he"], ["i lana tusi", "in his book"], ["ia toe foi atu i lona lava", "to return again in his very"], ["ulu", "head"], ["lana manatu leaga", "his thought evil"], ["na ia manatu ai", "he thought"], ["i", "in"], ["sa Iutā,", "of the clan of Judas"], ["ma ia fa'atautauina", "and he make to hang up"], ["o ia", "it/he/she"], ["ma", "and"], ["ona atali'i", "and son"], ["i le lā'au.", "in the tree"]]},
  {num:26,words:[["O le mea lea", "therefore"], ["na ta'ua ai", "us two"], ["o ia aso", "it day"], ["o Puro,", "Puro"], ["i le igoa", "in the name"], ["o le Puro.", "the Puro"], ["O mea uma foi", "everything also"], ["o le tusi,", "the book"], ["ma mea", "and thing"], ["na lātou vaavaaia", "they was ship"], ["i lenei", "in this"], ["mea,", "thing"], ["ma mea", "and thing"], ["na oo ia te", "oo unto"], ["i lātou,", "them"]]},
  {num:27,words:[["na fa'amauina ai", "established"], ["e sa Iutā,", "by of the clan of Judas"], ["ma talia ai", "and received"], ["mo", "for"], ["i lātou", "them"], ["ma", "and"], ["a lātou fānau,", "their born"], ["ma", "and"], ["e ua fa'atasia", "faatasia"], ["ma", "and"], ["i lātou,", "them"], ["ia le toe", "he the again"], ["mavae ona faia", "after do"], ["o ia lava aso", "it very day"], ["e lua", "two"], ["e tusa ma", "according to"], ["a lātou tusi,", "their book"], ["i ona lava po,", "in his very night"], ["i tausaga uma;", "in year all"]]},
  {num:28,words:[["ma ia manatua", "and he remember"], ["ma faia o ia", "and do it"], ["lava aso", "very day"], ["i tupulaga uma,", "in generation all"], ["i lea", "in"], ["'āiga", "family"], ["ma lea", "and"], ["'āiga,", "family"], ["i lea", "in"], ["itu mālō", "side kingdom"], ["ma lea", "and"], ["itu mālō,", "side kingdom"], ["i lea", "in"], ["aai", "cities"], ["ma lea", "and"], ["aai;", "cities"], ["aua foi", "for also"], ["le toe mavae", "the again passed"], ["i", "in"], ["sa Iutā o ia", "of the clan of Judas it"], ["lava aso o Puro,", "very day of Puro"], ["ma ia le tuua", "and he the left"], ["lē fa'amanatunatu", "not make meditate"], ["i ai", "therein"], ["i lā lātou fānau.", "in their born"]]},
  {num:29,words:[["O le masiofo", "the wife of a Samoan paramount chief"], ["o Eseta,", "Esther"], ["le afafine o Aviaila,", "the daughter of Aviaila"], ["ma Moretekai", "and Mordecai"], ["o lo", "lo"], ["sa Iutā,", "of the clan of Judas"], ["na lā tusi atu", "sun book"], ["ma le pule", "and the rule"], ["lava", "very"], ["e fa'amauina ai", "established"], ["lenei lua o tusi", "this two of book"], ["i Puro.", "in Puro"]]},
  {num:30,words:[["Ua ia avatua foi", "he given away also"], ["tusi", "book"], ["i", "in"], ["sa Iutā uma", "of the clan of Judas all"], ["i itu mālō", "in side kingdom"], ["e tasi", "one"], ["le selau", "the hundred"], ["e lua sefulu", "two ten"], ["ma le fitu", "and seven"], ["o le mālō", "the kingdom"], ["o Asueru,", "Asueru"], ["o 'upu alofa", "word love"], ["ma le fa'amaoni,", "and the faithful"]]},
  {num:31,words:[["ina ia fa'amauina", "so that established"], ["o ia aso", "it day"], ["o Puro", "Puro"], ["i ona lava po,", "in his very night"], ["e pei ona", "as"], ["pule", "rule"], ["e Moretekai", "Mordecai"], ["o lo", "lo"], ["sa Iutā", "of the clan of Judas"], ["ma le masiofo", "and the wife of a Samoan paramount chief"], ["o Eseta ia te", "Esther unto"], ["i lātou,", "them"], ["e pei ona", "as"], ["lātou fa'atuina foi", "they built also"], ["mo", "for"], ["i lātou", "them"], ["ma", "and"], ["a lātou fānau,", "their born"], ["o mea o anapogi", "thing of fasting"], ["ma lo lātou alalaga.", "and the they cry out"]]},
  {num:32,words:[["O le poloaiga", "the commandment"], ["a Eseta", "of Esther"], ["na fa'amauina ai", "established"], ["o ia mea", "it thing"], ["o Puro;", "Puro"], ["na tusia ai", "written"], ["foi", "also"], ["i le tusi.", "in the book"]]},
];
renderVerseSet(_est_ch_9_Verses, 'est-ch9-verses');

var _est_ch_10_Verses = [
  {num:1,words:[["Na totogi atu", "wages"], ["e le tupu", "shall not king"], ["o Asueru", "Asueru"], ["i le vao nu'u,", "in the wilderness nation"], ["ma nu'u tuloto", "and nation tuloto"], ["i tai,", "towards the sea"], ["ia faia", "he do"], ["le taulaga ia te ia.", "the offering to him"]]},
  {num:2,words:[["O mea uma", "everything"], ["na faia", "did"], ["i lana pule", "in his rule"], ["ma lona malosi,", "and his strong"], ["ma le tala", "and the side"], ["i le silisili", "in the very much"], ["o Moretekai", "Mordecai"], ["na fa'asilisiliina ai", "made very much"], ["o ia", "it/he/she"], ["e le tupu,", "shall not king"], ["e lei tusia ea", "by not written"], ["ia mea i le", "he thing in the"], ["tusi o tala", "book of side"], ["i nofoaiga", "in reign"], ["a tupu o Metai", "but king of Metai"], ["ma Peresia?", "and Persia"]]},
  {num:3,words:[["Auā", "do not"], ["na aupito Moretekai", "^ to be Mordecai"], ["o lo", "lo"], ["sa Iutā", "of the clan of Judas"], ["i le tupu", "in the king"], ["o Asueru;", "Asueru"], ["na silisili o ia", "very much it"], ["i", "in"], ["sa Iutā;", "of the clan of Judas"], ["na fiafia ia te ia", "pleased to him"], ["le toatele", "the many"], ["o", "o"], ["ona uso;", "and brother"], ["ua saili e", "sought by"], ["ia ia manuia", "to him prosper"], ["lona nu'u;", "his nation"], ["ua tautala foi", "spoke also"], ["ma le alofa", "and the love"], ["i lona nu'u uma.", "in his nation all"]]},
];
renderVerseSet(_est_ch_10_Verses, 'est-ch10-verses');

})();