(function() {
var _hab_ch_1_Verses = [
  {num:1,words:[["O le avega", "the burden"], ["na vaaia e le perofeta", "seen by the prophet"], ["o Sapakuka.", "Habakkuk"]]},
  {num:2,words:[["Ieova e,", "the LORD by"], ["ou te valaau seia afea,", "I will call until when ?"], ["ae te le faafofoga", "but the listen"], ["mai;", "from"], ["ou te alaga atu ia te oe", "I will cry unto you"], ["ona o le sauaga,", "because of the sauaga"], ["ae te le faaola", "but the save"], ["mai?", "from"]]},
  {num:3,words:[["Se a ea", "a but to rise (as a diver to the sur-"], ["le mea", "the thing"], ["ua e faaali mai ai ia te au", "to revealed unto me"], ["le amio leaga,", "the iniquity"], ["ma e silasila", "and to saw"], ["i le puapuaga? e i o'u luma", "in the affliction by before me"], ["le faatafunaina", "the destroyed"], ["ma le saua,", "and the to have a return of sick-"], ["e i ai foi le fefinauaiga", "by therein also the dispute"], ["ma le faatupuina", "and the raised up"], ["o le misa.", "the to quarrel"]]},
  {num:4,words:[["O le mea lea", "therefore"], ["ua faaleaogaina ai le tulafono,", "to make of no value the law"], ["ua le faia foi le faamasinoga faamaoni;", "not made also the judgment faithful"], ["auā ua siosioina", "for surrounded"], ["le ua amiotonu", "the righteous"], ["e le ua amio leaga,", "by the iniquity"], ["o le mea lea", "therefore"], ["ua fai ai le faamasinoga faapiopio.", "made the judgment faapiopio"]]},
  {num:5,words:[["Ia outou vaai atu i nuu ese,", "to you (all) looked toward in nation away"], ["ma ia outou iloa,", "and to you (all) know"], ["ma ia matuā taufaiofo lava;", "and to exceedingly taufaiofo indeed"], ["auā ou te faia", "for I will make"], ["se galuega", "a work"], ["i ona aso o outou,", "in then day of you (all)"], ["e ui lava", "to although indeed"], ["ina talaina atu,", "so that side"], ["tou te le talitonu ai lava.", "second person plural the believe indeed"]]},
  {num:6,words:[["Auā faauta,", "for behold"], ["ou te lagaina Kaletaia,", "I will to rise to arms Chaldean"], ["o le nuu saua", "the nation to have a return of sick-"], ["ma le tele vavave,", "and the great vavave"], ["o loo latou", "they"], ["o atu i le lautele", "in the wide"], ["o le lalolagi,", "the earth"], ["e fai", "to make"], ["mo latou", "for they"], ["o mea e nonofo ai,", "thing to dwell"], ["ae le ni o latou nuu .", "but the some of they nation"]]},
  {num:7,words:[["O i latou", "them"], ["e matautia", "to fearful"], ["ma le fefefe", "and the afraid"], ["i ai o tagata;", "therein of men"], ["e tupu mai ia te i latou", "to king from them"], ["lava lo latou faamasinoga", "indeed their judgment"], ["ma lo latou mamalu.", "and the they glory"]]},
  {num:8,words:[["E sili", "to most"], ["ona tele vavave foi a latou", "and great vavave also but they"], ["solofanua i nameri,", "horse in nameri"], ["e sili", "to most"], ["ona feai foi i luko", "and wild also in wolf"], ["i le afiafi;", "in the evening"], ["e faalialia foi a latou", "to to make a display also but they"], ["'au e tietie", "I to ride"], ["i solofanua,", "in horse"], ["o a latou 'au foi e tietie", "but they I also to ride"], ["i solofanua", "in horse"], ["e o mai i le mea mamao;", "by of from in the thing far"], ["latou te felelei pei o aeto", "they will flying like of aeto"], ["e tele vavave", "to great vavave"], ["e aai ai.", "to city"]]},
  {num:9,words:[["Latou te o uma", "they will all"], ["mai ina ia saua;", "from so that to have a return of sick-"], ["o le faasaga", "the toward"], ["mai o latou mata", "from of they eye"], ["e pei o le matagi", "like the wind"], ["mai sasae;", "from east"], ["latou te faapotopotoina tagata o taua", "they will gathered together man of precious"], ["e pei o le oneone.", "like the sand"]]},
  {num:10,words:[["Latou te tauemu", "they will mock"], ["i tupu,", "in king"], ["latou te tapisa foi i tamaalii;", "they will tapisa also in tamaalii"], ["latou te tapisa", "they will tapisa"], ["i 'olo uma,", "in fortress all"], ["auā latou te tanu ai le eleele,", "for they will to bury the earth"], ["ma latou aea.", "and they aea"]]},
  {num:11,words:[["Ona atili naunau ai lea o", "and more desire of"], ["i latou,", "them"], ["ona latou", "and they"], ["o atu lea,", "o atu lea,"], ["ma latou nofo sala ai,", "and they dwell a fine"], ["o loo faapea ane ,", "saying"], ["O lo latou malosi lea", "their strong"], ["i lo latou atua.", "in the they God"]]},
  {num:12,words:[["Ieova e,", "the LORD by"], ["lo'u Atua,", "my God"], ["le Paia e,", "the holy by"], ["e te le", "by the"], ["mai le faavavau ea? matou", "from the everlasting to rise (as a diver to the sur- we (excl)"], ["te le oti;", "the die"], ["Ieova e,", "the LORD by"], ["ua e tuu ia te i latou", "to put unto them"], ["e faaoo ai sala,", "to bring upon a fine"], ["le Papa e,", "the rock by"], ["ua e tofia", "to chosen"], ["i latou", "them"], ["e fai ai aoaiga.", "to make discipline"]]},
  {num:13,words:[["E sili", "to most"], ["ona manino ou fofoga,", "and plain I face"], ["e te le fia silasila", "by the want to do something saw"], ["i le amio leaga,", "in the iniquity"], ["e le mafai foi", "by the able also"], ["ona e silasila", "and to saw"], ["i le agasala;", "in the sin"], ["se a ea", "a but to rise (as a diver to the sur-"], ["le mea e te silasila ai", "the thing by saw"], ["i e o fai amio faa'ole'ole,", "in by of make conduct deceit"], ["ma ē", "and who"], ["le fetalai", "the said"], ["ina o fasioti", "so that of killed"], ["e le tagata agasala", "by the man sin"], ["le tagata", "the man"], ["e sili", "to most"], ["ona amiotonu ia te ia?", "and righteous to him"]]},
  {num:14,words:[["ma ē faia tagata ia", "and who made man to"], ["pei o i'a o le sami,", "like of fish of the sea"], ["pei o mea fetolofi,", "like of creeping thing"], ["e leai so latou", "there is not so they"], ["faipule?", "a councillor"]]},
  {num:15,words:[["Ua latou avae ia te i latou", "they took away unto them"], ["uma i le mātau,", "all in the mātau"], ["ua aofia", "aofia"], ["i latou", "them"], ["i lo latou upega,", "in the they net"], ["ua taena'i foi ia te i latou", "taena'i also unto them"], ["i lo latou tu'i;", "in the they '2l high chief"], ["o le mea lea", "therefore"], ["ua latou fiafia ai,", "they competition"], ["ma ua mitamita lava.", "and to boast indeed"]]},
  {num:16,words:[["O le mea lea latou te fai ai taulaga i lo latou upega,", "therefore they will make offering in the they net"], ["latou te faamu ai foi mea manogi", "they will burn incense also thing fragrant"], ["i lo latou tu'i;", "in the they '2l high chief"], ["auā o ia mea e lelei ai", "for he thing to good"], ["a latou mea", "but they thing"], ["ua maua,", "received"], ["e lololo ai foi a latou", "by lololo also but they"], ["mea e 'ai.", "thing to eat"]]},
  {num:17,words:[["O le mea ea lea latou te sasaa atu ai lo latou upega,", "the thing to rise (as a diver to the sur- they will plurzH x)^ saasaa their net"], ["ma le", "and the"], ["le mapu", "the mapu"], ["ona fasioti pea lava", "and killed continually indeed"], ["i atunuu?", "in nations"]]},
];
renderVerseSet(_hab_ch_1_Verses, 'hab-ch1-verses');

var _hab_ch_2_Verses = [
  {num:1,words:[["Ou te tu", "I will stand"], ["i le mea ou te leoleo ai,", "in the thing I will guard"], ["ou te tu foi a'u", "I will stand also I"], ["i le 'olo,", "in the fortress"], ["ou te vaavaai foi", "I will watch also"], ["ina ia ou iloa", "so that I know"], ["pe se a se mea e fetalai mai ai o ia ia te au,", "whether a but a thing to said he unto me"], ["pe se a foi", "whether a but also"], ["se mea ou te tali atu ai", "a thing I will respond"], ["i la'u finauga.", "in my disputation"]]},
  {num:2,words:[["Ua tali mai foi Ieova ia te au,", "responded from also the LORD unto me"], ["ua faapea mai,", "and said"], ["Ia e tusi", "to to book"], ["le faaaliga,", "the revelation"], ["ia e togitogi", "to by togitogi"], ["i papa,", "in rock"], ["ina ia momo'e o ia", "so that lie down he"], ["le na te faitauina.", "the he counted"]]},
  {num:3,words:[["Auā o le faaaliga", "for the revelation"], ["ua tuuina", "given"], ["mo ona aso", "for then day"], ["ua tuupoina,", "tuupoina"], ["a e tautala", "but to spoke"], ["mai pe a oo i le iuga,", "from whether but oo in the end"], ["e le pepelo lava;", "by the false indeed"], ["e ui lava", "to although indeed"], ["ina tuai mai,", "so that to be a long time from"], ["a ia faatalitali pea i ai;", "but to waited continually therein"], ["auā e oo mai lava,", "for it shall come to pass from indeed"], ["e le faatuai", "by the make to be a long time"], ["mai.", "from"]]},
  {num:4,words:[["Faauta,", "behold"], ["o le ua faafefeteina", "the feared"], ["e le tonu lona loto", "by the right his heart"], ["i totonu ia te ia;", "in inside to him"], ["a o le ua amiotonu", "but the righteous"], ["e ola ia i lona faatuatua.", "to life to in his faith"]]},
  {num:5,words:[["A e moni lava,", "but verily I say"], ["o le uaina", "the wine"], ["o le faa'ole'ole lea;", "the deceit"], ["o le tagata faafefeteina", "man feared"], ["e le nofo foi o ia i lona fale,", "by the dwell also he in his house"], ["na te faateleina lona manao pei o seoli,", "he multiplied his desired like of Sheol"], ["e pei o le oti", "like the die"], ["lava ia,", "indeed to"], ["e le maona lava;", "by the to subside indeed"], ["na te faapotopotoina nuu uma lava", "he gathered together nation all indeed"], ["ia te ia,", "to him"], ["na te aofaiina foi ia te ia", "he numbered also to him"], ["nuu uma.", "nation all"]]},
  {num:6,words:[["E le sauni ea", "by the he who beg^ins the game to rise (as a diver to the sur-"], ["e i latou uma", "by them all"], ["le faataoto ia te ia,", "the lay down to him"], ["atoa ma le pese faatauemu", "and the a song mock"], ["foi ia te ia,", "also to him"], ["ma latou faapea atu,", "and they thus"], ["Oi talofa", "wo"], ["i le", "in the"], ["na te faaputu mea e le ni ana mea!", "he to gather together thing by the some his thing"], ["Seia afea? Oi talofa foi ia te ia o le", "until when ? wo also to him the"], ["na te faafaupue ia te ia", "he faafaupue to him"], ["oloa ese!", "goods away"]]},
  {num:7,words:[["E le faafuasei ea", "by the faafuasei to rise (as a diver to the sur-"], ["ona tulai atu i latou", "and arose up them"], ["o e", "who"], ["a feutia oe,", "but feutia you"], ["ma latou ala", "and they way"], ["mai o e faatigaina oe,", "from who afflicted you"], ["ona avea lea o oe", "and become of you"], ["ma vete mā latou?", "and plunder First person dual exclusive they"]]},
  {num:8,words:[["Sa e vetea nuu e tele,", "by vetea nation to great"], ["o le mea lea e vetea ai oe", "therefore by vetea you"], ["e nuu uma o totoe;", "to nation all of phiral of foe"], ["ona o le toto o tagata,", "because of the blood of men"], ["ma le saua", "and the to have a return of sick-"], ["i le nuu,", "in the land"], ["ma le aai,", "and the city"], ["ma i latou uma o e nonofo ai.", "and them all who dwelling"]]},
  {num:9,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te maua", "he received"], ["i le amio leaga", "in the iniquity"], ["le oloa mā lona aiga,", "the goods First person dual exclusive his family"], ["ina ia tuu lona ofaga", "so that put his a nest"], ["i le mea maualuga,", "in the thing Iiigli"], ["ina ia laveaiina o ia i le malaia!", "so that delivered he in the disaster"]]},
  {num:10,words:[["Ua e filifili", "to chose"], ["se mea e oo ai le mā", "a thing it shall come to pass the First person dual exclusive"], ["i lou lava aiga,", "in your indeed family"], ["i lou faaumatia o nuu", "in your destroyed of nation"], ["e tele;", "to great"], ["ua e agasala foi ia te oe", "to sinned also unto you"], ["lava.", "indeed"]]},
  {num:11,words:[["Auā e alaga", "for to cry"], ["mai le maa ai le pa puipui,", "from the stone the a wall a duor"], ["o le faalava foi ai le laau e tali atu i ai.", "the crossbar also the tree to respond therein"]]},
  {num:12,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te faia", "he made"], ["se aai", "a city"], ["i le toto,", "in the blood"], ["ma faatumauina", "and established"], ["se aai", "a city"], ["i le amioletonu!", "in the wickedness"]]},
  {num:13,words:[["Faauta,", "behold"], ["e le mai ia", "by the from to"], ["Ieova o 'au ea", "the LORD of I to rise (as a diver to the sur-"], ["ona ia galulue tagata mā", "and to labour man First person dual exclusive"], ["le afi,", "the fire"], ["ma ia lailoa nuu ia i latou", "and to to be exhausted nation to them"], ["lava i mea", "indeed in thing"], ["le aoga lava?", "the useful indeed"]]},
  {num:14,words:[["Auā e tumu le lalolagi i le malamalama", "for to fill the earth in the light"], ["o le mamalu o Ieova,", "the glory the LORD"], ["faapei ona ufitia", "like then covered"], ["o le iliti tai", "the iliti the heart of a tree"], ["i le suāsami.", "in the suāsami"]]},
  {num:15,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te faainu", "he made drink"], ["i le tasi tagata,", "in the one man"], ["o oe", "you"], ["o lē liligi atu lau mea oona", "not to pour your thing drunk"], ["ia te ia", "to him"], [",", ","], ["ua e faaonā foi ia te ia", "to made drunk also to him"], [",", ","], ["ina ia", "so that"], ["e vaai atu i lo latou", "to looked toward in the they"], ["le lavalavā.", "the naked"]]},
  {num:16,words:[["E tumu oe", "to fill you"], ["i le mā", "in the First person dual exclusive"], ["e le", "by the"], ["o le mamalu;", "the glory"], ["ia e inu foi oe,", "to to drink also you"], ["ma ia aliali lou", "and to to appear your"], ["le peritomeina;", "the circumcised"], ["e liliu atu ia te oe", "to turned unto you"], ["le ipu", "the cup"], ["a le aao taumatau o Ieova,", "but the hand (extended) right hand the LORD"], ["e i ai foi le puaiga", "by therein also the puaiga"], ["e faamāina ai", "by faamāina"], ["i luga o lou mamalu.", "upon your glory"]]},
  {num:17,words:[["Auā e liloia oe", "for to to be covered you"], ["i le saua", "in the to have a return of sick-"], ["na faia", "made"], ["i Lepanona,", "in Lebanon"], ["ma le faaumatia o manu", "and the destroyed of animal"], ["e matuā matatau ai", "to exceedingly fear"], ["i latou;", "them"], ["ona o le toto o tagata,", "because of the blood of men"], ["ma le saua", "and the to have a return of sick-"], ["i le nuu,", "in the land"], ["ma le aai,", "and the city"], ["ma i latou uma o e nonofo ai.", "and them all who dwelling"]]},
  {num:18,words:[["Se a ea", "a but to rise (as a diver to the sur-"], ["le aoga", "the useful"], ["o le tupua", "the pillar"], ["ua ta", "a stroke"], ["ina ua taia", "so that struck"], ["e le", "by the"], ["na na faia;", "made"], ["o le tupua uamea,", "the pillar iron"], ["ma le a'oa'o", "and the excellent"], ["i le pepelo,", "in the false"], ["ina ua faatuatua", "so that faith"], ["le na faia", "the made"], ["i lana mea", "in his thing"], ["na fai,", "made"], ["ia fai ai e ia", "to make by him"], ["tupua e le magagana?", "pillar by the magagana"]]},
  {num:19,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te fai atu i le laau,", "he said to in the tree"], ["Ala mai ia;", "way from to"], ["ma le maa", "and the stone"], ["e le magagana,", "by the magagana"], ["Tulai mai ia!", "arose up from to"], ["E a'oa'o mai ea lena mea?", "to excellent from to rise (as a diver to the sur- that thing"], ["Faauta ia te ia,", "behold to him"], ["ua ufitia", "covered"], ["i le auro", "in the gold"], ["ma le ario,", "and the silver"], ["ae leai lava", "but no indeed"], ["se mānava", "a mānava"], ["i totonu ia te ia.", "in inside to him"]]},
  {num:20,words:[["A o Ieova", "but the LORD"], ["ua i lona malumalu paia", "in his temple holy"], ["o ia;", "he"], ["ina faalologo ia le lalolagi uma", "so that to hold one's tongue to the earth all"], ["i ona luma.", "before him"]]},
];
renderVerseSet(_hab_ch_2_Verses, 'hab-ch2-verses');

var _hab_ch_3_Verses = [
  {num:1,words:[["O le tatalo", "the pray"], ["a le perofeta o Sapakuka,", "but the prophet of Habakkuk"], ["na fai ma pese.", "to be a song"]]},
  {num:2,words:[["Ieova e,", "the LORD by"], ["ua ou faalogo", "I hearken"], ["i le tala ia te oe,", "in the side unto you"], ["ua ou mata'u ai;", "I ax"], ["Ieova e,", "the LORD by"], ["ia e toe faaolaolaina lau galuega", "to to again make the wedge in the handle your work"], ["i ia tausaga,", "in to year"], ["o ia tausaga ia", "he year to"], ["e faailoa mai ai;", "to revealed from"], ["ia e manatu", "to to thought"], ["i le alofa ao", "in the love day"], ["e toasa.", "to wrath"]]},
  {num:3,words:[["Na afio mai le Atua", "dwelt (respectful) from God"], ["mai Timanu,", "from Timanu"], ["na afio mai foi le Paia", "dwelt (respectful) from also the holy"], ["mai le mauga o Parana.", "from the mountain of Parana"], ["Selā.", "Selah"], ["Sa ufitia", "covered"], ["le lagi", "the heaven"], ["i lona pupula,", "in his brightness"], ["o lona viiga foi", "his praise also"], ["sa tumu ai le lalolagi.", "filled the earth"]]},
  {num:4,words:[["O le pupula foi", "the brightness also"], ["sa faapei", "like"], ["o le la,", "the la"], ["sa oo mai 'ave ai lona aao,", "it came to pass from take his hand (extended)"], ["sa iai foi le ufiufi", "there also the covering"], ["o lona mana.", "his to get"]]},
  {num:5,words:[["Sa muamua atu le faamai", "first the faamai"], ["i ona luma,", "before him"], ["sa mulimuli foi ia te ia", "followed after also to him"], ["le ma'i vevela", "the from to be hot"]]},
  {num:6,words:[["Sa tu o ia ma fuafua", "stood he and abscesses in the hands or"], ["le lalolagi;", "the earth"], ["na ia silasila mai,", "to looked"], ["ma na faagateteina nuu ese;", "and made tremble nation away"], ["na faataapeapeina ai foi mauga", "scattered also mountain"], ["o le vavau;", "the ancient times"], ["na faamaualaloina ai mauga iti", "made low mountain small"], ["o le vavau;", "the ancient times"], ["o ona ala ia", "then way to"], ["mai le vavau.", "from the ancient times"]]},
  {num:7,words:[["Na ou iloa fale ie", "I knew house faamaise"], ["o Kusa", "Kusa"], ["ua puapuagatia;", "puapuagatia"], ["na gatete ie puipui", "tremble faamaise a duor"], ["o le nuu o Mitiana.", "the nation of Midian"]]},
  {num:8,words:[["Na toatamai ea Ieova", "toatamai to rise (as a diver to the sur- the LORD"], ["i vaitafe?", "in river"], ["pe na", "whether"], ["e toasa ea", "to wrath to rise (as a diver to the sur-"], ["i vaitafe?", "in river"], ["pe na", "whether"], ["e maemaea ea", "by maemaea to rise (as a diver to the sur-"], ["i le sami,", "in the sea"], ["ina ua", "so that"], ["e tietie", "to ride"], ["i au solofanua", "in I horse"], ["ma ou nofoa faataavalevale", "and I a seat to roll round and"], ["o le faaolataga?", "the salvation"]]},
  {num:9,words:[["Na to ese lava", "to plant away indeed"], ["le faamoega", "the make bed"], ["o lau aufana,", "your bow"], ["o tautoga", "oath"], ["na e fetalai mai ai", "to said"], ["i itu aiga.", "in side family"], ["Selā.", "Selah"], ["Na e vaevaea", "by vaevaea"], ["le lalolagi i vaitafe.", "the earth in river"]]},
  {num:10,words:[["Na iloa oe", "knew you"], ["e mauga,", "to mountain"], ["ua latou gatete ai;", "they tremble"], ["ua tafe ane", "to flow"], ["le tafega o vai;", "the a fresh of water"], ["na gagana mai le moana,", "language from the deep"], ["ua na sisii", "to lift"], ["i luga", "in above"], ["ona lima.", "and five"]]},
  {num:11,words:[["Sa tutū pea", "stood up continually"], ["le la", "the la"], ["ma le masina", "and the month"], ["i le mea la te mau ai;", "in the thing la opinion"], ["o le malamalama o au", "the light I am"], ["u fanafana", "u arrow"], ["na latou savavali ai,", "they walked"], ["ma le malamalama", "and the light"], ["o lou tao pupula.", "your spear brightness"]]},
  {num:12,words:[["Sa e afio atu i le lalolagi ma le toatamai,", "to dwelt (respectful) on the earth and the toatamai"], ["sa e soli nuu ese", "to to tread upon nation away"], ["i lou toasa.", "in your wrath"]]},
  {num:13,words:[["Sa e afio atu e faaola", "to dwelt (respectful) to save"], ["i lou nuu,", "in your nation"], ["e faaola", "to save"], ["i le", "in the"], ["na e faauuina;", "to anointed"], ["sa e foa", "by foa"], ["le ulu", "the head"], ["i le fale o lē amio leaga,", "in the house of not iniquity"], ["i lou faataatia fua", "in your faataatia fruit"], ["le faavae ia oo i le ua", "the foundation to oo in the"], ["lava.", "indeed"], ["Selā.", "Selah"]]},
  {num:14,words:[["Sa e sosoa", "to to dance accompanied by"], ["le alii sili", "the Lord most"], ["o ona ta'ita'i", "then lead"], ["i ona lava tao;", "in then indeed spear"], ["sa latou feosofi", "they feosofi"], ["mai pei", "from like"], ["se afā", "a cyclone"], ["e faataapeape ia te au;", "by faataapeape unto me"], ["sa fai", "made"], ["mo latou mitamita", "for they to boast"], ["le faaumatia faalilolilo", "the destroyed secret"], ["o le tagata mativa.", "man want"]]},
  {num:15,words:[["Sa e afio", "to dwelt (respectful)"], ["i totonu o le sami", "in the midst of the sea"], ["ma au solofanua,", "and I horse"], ["sa e afio foi i le faupuegāvai", "to dwelt (respectful) also in the faupuegāvai"], ["e tele.", "to great"]]},
  {num:16,words:[["Na ou faalogo ai,", "I hearken"], ["ona sapotuvale ai lea o lo'u manava,", "and sapotuvale my womb"], ["sa tete o'u laugutu", "tete my lips"], ["i le leo;", "in the voice"], ["ua oo mai ai le pala", "it came to pass from the a muddy deposit in the sea"], ["i o'u ivi,", "in my bone"], ["ua ou tetemu ai lava;", "I to tremble indeed"], ["a e filemu a'u", "but to peace I"], ["i le aso", "in the day"], ["o le puapuaga,", "the affliction"], ["pe a alu ae o ia i le nuu", "whether but go up he in the land"], ["e sii mai le taua", "to lift up from the precious"], ["ia te i tatou.", "unto us"]]},
  {num:17,words:[["E ui lava", "to although indeed"], ["ina le fuga", "so that the flower"], ["mai le mati,", "from the fig"], ["e leai foi ni fua", "there is not also some fruit"], ["i vine,", "in vine"], ["e iuvale", "by iuvale"], ["le fua", "the fruit"], ["o le olive,", "the olive"], ["e le tupu mai foi ni mea e 'ai", "by the king from also some thing to eat"], ["i le fanua;", "in the land"], ["e faaumatia", "to destroyed"], ["le lafu mamoe", "the herd sheep"], ["i le lotoā", "in the court"], ["e leai foi ni povi", "there is not also some cattle"], ["i le fale povi;", "in the house cattle"]]},
  {num:18,words:[["a e peitai a'u,", "but I"], ["ou te olioli lava ia", "I will rejoice indeed to"], ["Ieova,", "the LORD"], ["ou te fiafia lava", "I will competition indeed"], ["i le Atua o lo'u faaolataga.", "in the God my salvation"]]},
  {num:19,words:[["O Ieova le Alii,", "the LORD the Lord"], ["o lo'u malosi ia,", "my strong to"], ["na te faia o'u vae", "he made my foot"], ["e pei o vae o aila,", "to like of foot of aila"], ["o ia foi ou te savali ai", "he also I will walk"], ["i a'u mea maualuluga.", "in I thing most high"], ["Ma le usu pese", "and the to lead the singing a song"], ["i nekina.", "in nekina"]]},
];
renderVerseSet(_hab_ch_3_Verses, 'hab-ch3-verses');

})();