(function() {
var _hab_ch_1_Verses = [
  {num:1,words:[["O le avega", "the burden"], ["na vaaia", "seen"], ["e le perofeta", "shall not prophet"], ["o Sapakuka.", "Habakkuk"]]},
  {num:2,words:[["Ieova e,", "O LORD!"], ["ou te valaau seia afea,", "I will cried out how long?/until when?"], ["ae te", "but"], ["le fa'afofoga mai;", "the listen from"], ["ou te alaga atu", "I will cry"], ["ia te oe", "unto you"], ["ona", "and"], ["o le sauaga,", "the persecution"], ["ae te", "but"], ["le fa'aola mai?", "the save from"]]},
  {num:3,words:[["Se a ea", "what indeed? / why?"], ["le mea", "the thing"], ["ua e fa'aali mai ai", "you revealed"], ["ia te au", "unto me"], ["le amio leaga,", "the iniquity"], ["ma", "and"], ["e silasila", "to saw"], ["i le puapuaga?", "in the affliction"], ["e", "by"], ["i o'u luma", "before me"], ["le fa'atafunaina", "the destroyed"], ["ma le saua,", "and the to have a return of sick-"], ["e", "by"], ["i ai", "therein"], ["foi", "also"], ["le fefinauaiga", "the dispute"], ["ma le fa'atupuina", "and the raised up"], ["o le misa.", "the to quarrel"]]},
  {num:4,words:[["O le mea lea", "therefore"], ["ua fa'aleaogaina ai", "made void"], ["le tulafono,", "the law"], ["ua", "ua"], ["le faia foi", "the made also"], ["le fa'amasinoga fa'amaoni;", "the judgment faithful"], ["auā", "for"], ["ua siosioina", "surrounded"], ["le", "the"], ["ua amiotonu", "righteous"], ["e le", "by the"], ["ua amio leaga,", "iniquity"], ["o le mea lea", "therefore"], ["ua fai ai", "made"], ["le fa'amasinoga fa'apiopio.", "the judgment faapiopio"]]},
  {num:5,words:[["Ia outou vaai atu i", "to you all looked toward in"], ["nuu ese,", "nation away"], ["ma ia outou", "and to you all"], ["iloa,", "know"], ["ma ia matuā taufaiofo", "and to great taufaiofo"], ["lava;", "very"], ["auā ou te faia", "for I will make"], ["se galuega", "a work"], ["i ona aso", "in his days"], ["o outou,", "you all"], ["e ui lava", "to although very"], ["ina talaina atu,", "so that side"], ["tou te", "second person plural"], ["le talitonu ai", "the believe"], ["lava.", "very"]]},
  {num:6,words:[["Auā fa'auta,", "for behold"], ["ou te lagaina Kaletaia,", "I will to rise to arms Chaldean"], ["o le nuu saua", "the nation to have a return of sick-"], ["ma le tele vavave,", "and the great quick"], ["o loo lātou", "is they"], ["o atu", "went"], ["i le lautele", "in the wide"], ["o le lalolagi,", "the earth"], ["e fai", "to make"], ["mo lātou", "for they"], ["o mea", "thing"], ["e nonofo ai,", "to dwell"], ["ae", "but"], ["le ni o lātou", "the some of they"], ["nuu .", "nation"]]},
  {num:7,words:[["O", "O"], ["i lātou", "them"], ["e matautia", "to fearful"], ["ma le fefefe", "and the afraid"], ["i ai", "therein"], ["o tagata;", "of men"], ["e tupu mai ia te", "to king from"], ["i lātou lava lo lātou fa'amasinoga", "them very their judgment"], ["ma lo lātou mamalu.", "and the they glory"]]},
  {num:8,words:[["E sili", "to most"], ["ona tele vavave foi", "and great quick also"], ["a lātou solofanua", "their horse"], ["i nameri,", "in nameri"], ["e sili", "to most"], ["ona feai foi", "and wild also"], ["i luko", "in wolf"], ["i le afiafi;", "in the evening"], ["e fa'alialia foi", "to to make a display also"], ["a lātou 'au", "their troops"], ["e tietie", "to ride"], ["i solofanua,", "in horse"], ["o", "o"], ["a lātou 'au foi", "their troops also"], ["e tietie", "to ride"], ["i solofanua", "in horse"], ["e o mai", "shall come"], ["i le mea mamao;", "in the thing far"], ["lātou te felelei pei", "they will flying like"], ["o aeto e tele vavave", "aeto to great quick"], ["e aai ai.", "to cities"]]},
  {num:9,words:[["Lātou te o uma", "they will all"], ["mai", "from"], ["ina ia saua;", "so that to have a return of sick-"], ["o le fa'asaga", "the face"], ["mai o lātou", "from of they"], ["mata", "eye"], ["e pei o le matagi", "like the wind"], ["mai sasae;", "from east"], ["lātou te fa'apotopotoina tagata", "they will gathered together man"], ["o taua", "war"], ["e pei o le oneone.", "like the sand"]]},
  {num:10,words:[["Lātou te tauemu", "they will mock"], ["i tupu,", "in king"], ["lātou te tapisa foi", "they will tapisa also"], ["i tamaalii;", "in tamaalii"], ["lātou te tapisa", "they will tapisa"], ["i 'olo uma,", "in trench all"], ["auā lātou te tanu ai", "for they will to bury"], ["le eleele,", "the earth"], ["ma lātou aea.", "and they aea"]]},
  {num:11,words:[["Ona atili naunau ai lea", "and more desire then then"], ["o", "o"], ["i lātou,", "them"], ["ona lātou", "and they"], ["o atu lea,", "went"], ["ma lātou nofo sala ai,", "and they dwell a fine"], ["o loo fa'apea ane", "saying"], [",", ","], ["O lo lātou malosi lea", "their strong"], ["i lo lātou atua.", "than they God"]]},
  {num:12,words:[["Ieova e,", "O LORD!"], ["lo'u Atua,", "my God"], ["le Paia e,", "the holy by"], ["e te", "by"], ["le mai le fa'avavau ea? mātou", "the from the everlasting indeed?/really? we"], ["te", "te"], ["le oti;", "the die"], ["Ieova e,", "O LORD!"], ["ua e tuu ia te", "you put unto"], ["i lātou", "them"], ["e fa'aoo ai", "to bring upon"], ["sala,", "a fine"], ["le Papa e,", "the rock by"], ["ua e tofia", "you was chosen"], ["i lātou", "them"], ["e fai ai", "to make"], ["aoaiga.", "discipline"]]},
  {num:13,words:[["E sili", "to most"], ["ona manino ou fofoga,", "and plain I face"], ["e te", "by"], ["le fia silasila", "the want to do something saw"], ["i le amio leaga,", "in the iniquity"], ["e le mafai foi", "shall not able also"], ["ona", "and"], ["e silasila", "to saw"], ["i le agasala;", "in the sin"], ["se a ea", "what indeed? / why?"], ["le mea", "the thing"], ["e te silasila ai", "by saw"], ["i", "in"], ["e o fai amio fa'a'ole'ole,", "by of make conduct treacherous"], ["ma ē", "and by"], ["le fetalai", "the said"], ["ina o fasioti", "so that of killed"], ["e le tagata agasala", "shall not man sin"], ["le tagata", "the man"], ["e sili", "to most"], ["ona amiotonu ia te ia?", "and righteous to him"]]},
  {num:14,words:[["ma ē faia tagata", "and by made man"], ["ia pei o", "to like of"], ["i'a", "fish"], ["o le sami,", "Sea"], ["pei o mea fetolofi,", "like of creeping thing"], ["e leai so lātou", "there is not so they"], ["faipule?", "a councillor"]]},
  {num:15,words:[["Ua lātou avae ia te", "they took away unto"], ["i lātou uma", "them all"], ["i le mātau,", "in the mātau"], ["ua aofia", "aofia"], ["i lātou", "them"], ["i lo lātou upega,", "than they net"], ["ua taena'i foi", "taena'i also"], ["ia te i lātou", "unto them"], ["i lo lātou tu'i;", "than they '2l high chief"], ["o le mea lea", "therefore"], ["ua lātou fiafia ai,", "they pleased"], ["ma", "and"], ["ua mitamita lava.", "to boast very"]]},
  {num:16,words:[["O le mea lea", "therefore"], ["lātou te fai ai", "they will make"], ["taulaga", "offering"], ["i lo lātou upega,", "than they net"], ["lātou te fa'amu ai", "they will burn incense"], ["foi mea manogi", "also thing fragrant"], ["i lo lātou tu'i;", "than they '2l high chief"], ["auā o ia", "for he"], ["mea", "thing"], ["e lelei ai", "to good"], ["a lātou mea", "their thing"], ["ua maua,", "received"], ["e lololo ai", "to to overfl(jw"], ["foi", "also"], ["a lātou mea", "their thing"], ["e 'ai.", "to eat"]]},
  {num:17,words:[["O le mea ea lea", "the thing indeed?/really?"], ["lātou te sasaa atu ai", "they will plurzH x)^ saasaa"], ["lo lātou upega,", "their net"], ["ma le", "and the"], ["le mapu", "the mapu"], ["ona fasioti pea", "and killed continually"], ["lava", "very"], ["i atunuu?", "in nations"]]},
];
renderVerseSet(_hab_ch_1_Verses, 'hab-ch1-verses');

var _hab_ch_2_Verses = [
  {num:1,words:[["Ou te tu", "I will stand"], ["i le mea ou te leoleo ai,", "in the thing I will guard"], ["ou te tu foi", "I will stand also"], ["a'u", "me"], ["i le 'olo,", "in the trench"], ["ou te vaavaai foi", "I will looked around also"], ["ina ia ou iloa", "so that I know"], ["pe", "whether"], ["se a se mea", "a but a thing"], ["e fetalai mai ai", "to said"], ["o ia ia te au,", "he unto me"], ["pe", "whether"], ["se a foi", "a but also"], ["se mea ou te tali atu ai", "a thing I will respond"], ["i la'u finauga.", "in my disputation"]]},
  {num:2,words:[["Ua tali mai foi", "responded from also"], ["Ieova ia te au,", "the LORD unto me"], ["ua fa'apea mai,", "and said"], ["Ia e tusi", "to to book"], ["le fa'aaliga,", "the revelation"], ["ia e togitogi i", "to to to throw in"], ["papa,", "rock"], ["ina ia momo'e", "so that ran"], ["o ia le", "he the"], ["na te faitauina.", "he counted"]]},
  {num:3,words:[["Auā", "for"], ["o le fa'aaliga", "the revelation"], ["ua tuuina", "given"], ["mo", "for"], ["ona aso", "and day"], ["ua tuupoina,", "tuupoina"], ["a", "but"], ["e tautala mai", "to speak from"], ["pe a oo", "even though / although oo"], ["i le iuga,", "in the end"], ["e le pepelo", "shall not false"], ["lava;", "very"], ["e ui lava", "to although very"], ["ina tuai mai,", "so that to be a long time from"], ["a ia fa'atalitali pea", "his waited continually"], ["i ai;", "therein"], ["auā", "for"], ["e oo mai", "it shall come to pass from"], ["lava,", "very"], ["e le fa'atuai", "shall not make to be a long time"], ["mai.", "from"]]},
  {num:4,words:[["Fa'auta,", "behold"], ["o le", "the"], ["ua fa'afefeteina", "feared"], ["e le tonu", "shall not right"], ["lona loto", "his heart"], ["i totonu ia te ia;", "in inside to him"], ["a", "but"], ["o le", "the"], ["ua amiotonu", "righteous"], ["e ola ia", "to life to"], ["i lona fa'atuatua.", "in his faith"]]},
  {num:5,words:[["A", "but"], ["e moni lava,", "verily I say"], ["o le uaina", "the wine"], ["o le fa'a'ole'ole lea;", "the treacherous"], ["o le tagata fa'afefeteina", "man feared"], ["e le nofo foi", "shall not dwell also"], ["o ia", "he"], ["i lona fale,", "in his house"], ["na te fa'ateleina", "he multiplied"], ["lona manao pei", "his desire like"], ["o seoli,", "Sheol"], ["e pei o le oti", "like the die"], ["lava ia,", "very to"], ["e le maona", "shall not to subside"], ["lava;", "very"], ["na te fa'apotopotoina", "he gathered together"], ["nuu uma lava", "nation all very"], ["ia te ia,", "to him"], ["na te aofaiina foi", "he numbered also"], ["ia te ia", "to him"], ["nuu uma.", "nation all"]]},
  {num:6,words:[["E le sauni ea", "shall not he who beg^ins the game indeed?/really?"], ["e", "by"], ["i lātou uma", "them all"], ["le fa'ataoto ia te ia,", "the lay down to him"], ["atoa ma le pese fa'atauemu foi", "and the a song mock also"], ["ia te ia,", "to him"], ["ma lātou fa'apea atu,", "and they thus"], ["Oi talofa", "wo"], ["i le", "in the"], ["na te fa'aputu", "he to gather together"], ["mea", "thing"], ["e le ni ana mea!", "by the some his thing"], ["Seia afea? Oi talofa foi", "how long?/until when? wo also"], ["ia te ia", "to him"], ["o le", "the"], ["na te fa'afaupue ia te ia", "he faafaupue to him"], ["oloa ese!", "goods away"]]},
  {num:7,words:[["E le fa'afuasei ea", "by the faafuasei indeed?/really?"], ["ona tulai atu", "and arise up"], ["i lātou", "them"], ["o", "o"], ["e", "by"], ["a feutia oe,", "but feutia you"], ["ma lātou ala", "and they way"], ["mai o", "from of"], ["e fa'atigaina oe,", "to afflicted you"], ["ona avea lea", "and become"], ["o oe", "you"], ["ma vete mā lātou?", "and plunder and they"]]},
  {num:8,words:[["Sa e vetea", "you plundered"], ["nuu e tele,", "nation to great"], ["o le mea lea", "therefore"], ["e vetea ai", "to plundered"], ["oe", "you"], ["e nuu uma", "to nation all"], ["o totoe;", "phiral of foe"], ["ona", "and"], ["o le toto", "the blood"], ["o tagata,", "of men"], ["ma le saua", "and the to have a return of sick-"], ["i le nuu,", "in the land"], ["ma le aai,", "and the cities"], ["ma", "and"], ["i lātou uma", "them all"], ["o", "o"], ["e nonofo ai.", "to dwell"]]},
  {num:9,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te maua", "he received"], ["i le amio leaga", "in the iniquity"], ["le oloa mā", "the goods and"], ["lona 'āiga,", "his family"], ["ina ia tuu", "so that put"], ["lona ofaga", "his a nest"], ["i le mea maualuga,", "in the thing Iiigli"], ["ina ia laveaiina", "so that delivered"], ["o ia", "he"], ["i le malaia!", "in the disaster"]]},
  {num:10,words:[["Ua e filifili", "you chose"], ["se mea", "a thing"], ["e oo ai", "it shall come to pass"], ["le mā", "the and"], ["i lou lava 'āiga,", "in your very family"], ["i lou fa'aumatia", "in your destroyed"], ["o nuu e tele;", "nation to great"], ["ua e agasala foi", "you sinned also"], ["ia te oe", "unto you"], ["lava.", "very"]]},
  {num:11,words:[["Auā", "for"], ["e alaga mai le maa ai", "to cry from the stone"], ["le pa puipui,", "the wall gate"], ["o le fa'alava foi", "the crossbar also"], ["ai", "ai"], ["le lā'au", "the tree"], ["e tali atu", "to respond"], ["i ai.", "therein"]]},
  {num:12,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te faia", "he made"], ["se aai", "a cities"], ["i le toto,", "in the blood"], ["ma fa'atumauina", "and established"], ["se aai", "a cities"], ["i le amioletonu!", "in the wickedness"]]},
  {num:13,words:[["Fa'auta,", "behold"], ["e le mai ia", "by the from to"], ["Ieova o 'au ea", "the LORD of troops indeed?/really?"], ["ona ia galulue tagata mā", "and to labour man and"], ["le afi,", "the fire"], ["ma ia lailoa nuu", "and to weary nation"], ["ia", "to"], ["i lātou lava", "them very"], ["i mea", "in thing"], ["le aoga lava?", "the useful very"]]},
  {num:14,words:[["Auā", "for"], ["e tumu", "to fill"], ["le lalolagi", "the earth"], ["i le malamalama", "in the light"], ["o le mamalu", "the glory"], ["o Ieova,", "the LORD"], ["fa'apei", "like"], ["ona ufitia", "and covered"], ["o le iliti tai", "the iliti the heart of a tree"], ["i le suāsami.", "in the waters"]]},
  {num:15,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te fa'ainu", "he made drink"], ["i le tasi tagata,", "in the one man"], ["o oe", "you"], ["o lē liligi atu", "the to pour"], ["lau mea oona", "your thing drunk"], ["ia te ia", "to him"], [",", ","], ["ua e fa'aonā foi", "you made then also"], ["ia te ia", "to him"], [",", ","], ["ina ia", "so that"], ["e vaai atu", "to looked toward"], ["i lo lātou", "than they"], ["le lavalavā.", "the naked"]]},
  {num:16,words:[["E tumu oe", "to fill you"], ["i le mā", "in the and"], ["e le", "by the"], ["o le mamalu;", "the glory"], ["ia e inu foi", "to to drink also"], ["oe,", "you"], ["ma ia aliali", "and to to appear"], ["lou", "your"], ["le peritomeina;", "the circumcised"], ["e liliu atu", "to turn"], ["ia te oe", "unto you"], ["le ipu", "the cup"], ["a le aao taumatau", "but the hand right hand"], ["o Ieova,", "the LORD"], ["e", "by"], ["i ai", "therein"], ["foi", "also"], ["le puaiga", "the family"], ["e fa'amāina ai", "to to put to shame"], ["i luga", "in above"], ["o lou mamalu.", "your glory"]]},
  {num:17,words:[["Auā", "for"], ["e liloia oe", "to to be covered you"], ["i le saua", "in the to have a return of sick-"], ["na faia", "made"], ["i Lepanona,", "in Lebanon"], ["ma le fa'aumatia", "and the destroyed"], ["o manu", "animal"], ["e matuā matatau ai", "to great dismayed"], ["i lātou;", "them"], ["ona", "and"], ["o le toto", "the blood"], ["o tagata,", "of men"], ["ma le saua", "and the to have a return of sick-"], ["i le nuu,", "in the land"], ["ma le aai,", "and the cities"], ["ma", "and"], ["i lātou uma", "them all"], ["o", "o"], ["e nonofo ai.", "to dwell"]]},
  {num:18,words:[["Se a ea", "what indeed? / why?"], ["le aoga", "the useful"], ["o le tupua", "the pillar"], ["ua tā", "struck"], ["ina ua taia", "when struck"], ["e le", "by the"], ["na", "na"], ["na faia;", "made"], ["o le tupua uamea,", "the pillar iron"], ["ma le a'oa'o", "and the excellent"], ["i le pepelo,", "in the false"], ["ina ua fa'atuatua", "when faith"], ["le", "the"], ["na faia", "made"], ["i lana mea", "in his thing"], ["na fai,", "made"], ["ia fai ai", "to make"], ["e ia tupua", "by him pillar"], ["e le magagana?", "by the magagana"]]},
  {num:19,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te fai atu", "he said to"], ["i le lā'au,", "in the tree"], ["Ala mai ia;", "way from to"], ["ma le maa", "and the stone"], ["e le magagana,", "by the magagana"], ["Tulai mai ia!", "arise up from to"], ["E a'oa'o mai ea lena", "to excellent from indeed?/really? that"], ["mea?", "thing"], ["Fa'auta ia te ia,", "behold to him"], ["ua ufitia", "covered"], ["i le auro", "in the gold"], ["ma le ario,", "and the silver"], ["ae leai lava", "but no very"], ["se mānava", "a womb"], ["i totonu ia te ia.", "in inside to him"]]},
  {num:20,words:[["A o Ieova", "but the LORD"], ["ua", "ua"], ["i lona malumalu paia", "in his temple holy"], ["o ia;", "he"], ["ina fa'alologo ia", "so that to hold one's tongue to"], ["le lalolagi uma", "all the earth"], ["i ona luma.", "before him"]]},
];
renderVerseSet(_hab_ch_2_Verses, 'hab-ch2-verses');

var _hab_ch_3_Verses = [
  {num:1,words:[["O le tatalo", "the pray"], ["a le perofeta", "but the prophet"], ["o Sapakuka,", "Habakkuk"], ["na fai ma", "to be"], ["pese.", "a song"]]},
  {num:2,words:[["Ieova e,", "O LORD!"], ["ua ou fa'alogo", "I hearken"], ["i le tala", "in the side"], ["ia te oe,", "unto you"], ["ua ou mata'u ai;", "I ax"], ["Ieova e,", "O LORD!"], ["ia e toe", "to to again"], ["fa'aolaolaina", "make the wedge in the handle"], ["lau galuega", "your work"], ["i ia tausaga,", "in to year"], ["o ia tausaga", "he year"], ["ia e fa'ailoa", "to to revealed"], ["mai ai;", "from"], ["ia e manatu i le alofa", "to to thought in the love"], ["ao", "day"], ["e toasa.", "to wrath"]]},
  {num:3,words:[["Na afio mai le Atua mai", "dwelt from God from"], ["Timanu,", "Timanu"], ["na afio mai foi", "dwelt from also"], ["le Paia mai le mauga", "the holy from the mountain"], ["o Parana.", "Parana"], ["Selā.", "Selah"], ["Sa ufitia", "covered"], ["le lagi", "the heaven"], ["i lona pupula,", "in his brightness"], ["o lona viiga foi", "his praise also"], ["sa tumu ai", "filled"], ["le lalolagi.", "the earth"]]},
  {num:4,words:[["O le pupula foi", "the brightness also"], ["sa fa'apei", "like"], ["o le la,", "the la"], ["sa oo mai", "it came to pass from"], ["'ave ai", "take"], ["lona aao,", "his hand"], ["sa iai foi", "there also"], ["le ufiufi", "the covering"], ["o lona mana.", "his to get"]]},
  {num:5,words:[["Sa muamua atu", "first the beginning"], ["le fa'amai", "the faamai"], ["i ona luma,", "before him"], ["sa mulimuli foi", "followed after also"], ["ia te ia", "to him"], ["le ma'i vevela", "the from to be hot"]]},
  {num:6,words:[["Sa tu o ia", "stood he"], ["ma fuafua", "and abscesses in the hands or"], ["le lalolagi;", "the earth"], ["na ia silasila mai,", "to looked"], ["ma", "and"], ["na fa'agateteina nuu ese;", "made tremble nation away"], ["na fa'ataapeapeina ai", "scattered"], ["foi mauga", "also mountain"], ["o le vavau;", "the ancient times"], ["na fa'amaualaloina ai", "made low"], ["mauga iti", "mountain small"], ["o le vavau;", "the ancient times"], ["o", "o"], ["ona ala ia", "and way to"], ["mai le vavau.", "from the ancient times"]]},
  {num:7,words:[["Na ou iloa", "I knew"], ["fale ie o Kusa", "tent Kusa"], ["ua puapuagatia;", "puapuagatia"], ["na gatete ie", "tremble faamaise"], ["puipui", "gate"], ["o le nuu", "the nation"], ["o Mitiana.", "Midian"]]},
  {num:8,words:[["Na toatamai ea", "toatamai indeed?/really?"], ["Ieova", "the LORD"], ["i vaitafe?", "in river"], ["pe", "whether"], ["na e toasa", "you wrath"], ["ea", "indeed?/really?"], ["i vaitafe?", "in river"], ["pe", "whether"], ["na e maemaea", "you maemaea"], ["ea", "indeed?/really?"], ["i le sami,", "in the sea"], ["ina ua e tietie", "when to ride"], ["i au solofanua", "in me horse"], ["ma ou nofoa fa'ataavalevale", "and I a seat to roll round and"], ["o le fa'aolataga?", "the salvation"]]},
  {num:9,words:[["Na to ese lava", "stripped off very"], ["le fa'amoega", "the sheath"], ["o lau aufana,", "your bow"], ["o tautoga", "oath"], ["na e fetalai mai ai", "you said"], ["i itu 'āiga.", "in side family"], ["Selā.", "Selah"], ["Na e vaevaea", "you was foot"], ["le lalolagi", "the earth"], ["i vaitafe.", "in river"]]},
  {num:10,words:[["Na iloa oe", "knew you"], ["e mauga,", "to mountain"], ["ua lātou gatete ai;", "they tremble"], ["ua tafe ane", "to flow"], ["le tafega o vai;", "the a fresh of water"], ["na gagana mai le", "language from the"], ["moana,", "deep"], ["ua", "ua"], ["na sisii", "to lift"], ["i luga", "in above"], ["ona lima.", "and hand"]]},
  {num:11,words:[["Sa tutū pea", "stood up continually"], ["le la", "the la"], ["ma le masina", "and the month"], ["i le mea la te mau ai;", "in the thing la opinion"], ["o le malamalama", "the light"], ["o au u fanafana", "I am u arrow"], ["na lātou savavali ai,", "they walked"], ["ma le malamalama", "and the light"], ["o lou tao pupula.", "your spear brightness"]]},
  {num:12,words:[["Sa e afio atu", "you dwelt"], ["i le lalolagi", "on the earth"], ["ma le toatamai,", "and the toatamai"], ["sa e soli", "you to tread upon"], ["nuu ese", "nation away"], ["i lou toasa.", "in your wrath"]]},
  {num:13,words:[["Sa e afio atu", "you dwelt"], ["e fa'aola", "to save"], ["i lou nuu,", "in your nation"], ["e fa'aola", "to save"], ["i le", "in the"], ["na e fa'auuina;", "you anointed"], ["sa e foa", "you foa"], ["le ulu", "the head"], ["i le fale", "in the house"], ["o lē amio leaga,", "the iniquity"], ["i lou fa'ataatia fua", "in your faataatia fruit"], ["le fa'avae ia", "the foundation to"], ["oo", "oo"], ["i le", "in the"], ["ua lava.", "very"], ["Selā.", "Selah"]]},
  {num:14,words:[["Sa e sosoa", "you to dance accompanied by"], ["le ali'i sili", "the Lord most"], ["o", "o"], ["ona ta'ita'i", "and lead"], ["i ona lava tao;", "in then very spear"], ["sa lātou feosofi mai", "they rushed upon from"], ["pei", "like"], ["se afā", "a cyclone"], ["e fa'ataapeape ia te au;", "by faataapeape unto me"], ["sa fai", "made"], ["mo lātou mitamita", "for they to boast"], ["le fa'aumatia fa'alilolilo", "the destroyed secret"], ["o le tagata mativa.", "man want"]]},
  {num:15,words:[["Sa e afio", "you dwelt"], ["i totonu", "in inside"], ["o le sami", "Sea"], ["ma au solofanua,", "and me horse"], ["sa e afio foi", "you dwelt also"], ["i le faupuegāvai", "in the faupuegāvai"], ["e tele.", "to great"]]},
  {num:16,words:[["Na ou fa'alogo ai,", "I hearken"], ["ona sapotuvale ai lea", "and sapotuvale then then"], ["o lo'u manava,", "my womb"], ["sa tete o'u", "tete my"], ["laugutu", "lips"], ["i le leo;", "in the voice"], ["ua oo mai ai", "it came to pass from"], ["le pala", "the a muddy deposit in the sea"], ["i o'u ivi,", "in my bone"], ["ua ou tetemu ai", "I to tremble"], ["lava;", "very"], ["a", "but"], ["e filemu a'u", "to peace me"], ["i le aso", "in the day"], ["o le puapuaga,", "the affliction"], ["pe a alu ae", "even though / although go up"], ["o ia", "he"], ["i le nuu", "in the land"], ["e sii mai le taua", "to lift up from the battle"], ["ia te i tātou.", "unto us"]]},
  {num:17,words:[["E ui lava", "to although very"], ["ina", "so that"], ["le fuga mai le mati,", "the flower from the fig"], ["e leai foi", "there is not also"], ["ni fua", "some fruit"], ["i vine,", "in vine"], ["e iuvale", "by iuvale"], ["le fua", "the fruit"], ["o le olive,", "the olive"], ["e le tupu", "shall not king"], ["mai foi", "from also"], ["ni mea", "some thing"], ["e 'ai", "to eat"], ["i le fanua;", "in the land"], ["e fa'aumatia", "to destroyed"], ["le lafu mamoe", "the flock sheep"], ["i le lotoā", "in the fold"], ["e leai foi", "there is not also"], ["ni povi", "some cattle"], ["i le fale povi;", "in the house cattle"]]},
  {num:18,words:[["a", "but"], ["e peitai a'u,", "to however me"], ["ou te olioli", "I will joy"], ["lava ia Ieova,", "very to the LORD"], ["ou te fiafia", "I will pleased"], ["lava", "very"], ["i le Atua", "in the God"], ["o lo'u fa'aolataga.", "my salvation"]]},
  {num:19,words:[["O Ieova", "the LORD"], ["le Ali'i,", "the Lord"], ["o lo'u malosi", "my strong"], ["ia,", "to"], ["na te faia", "he made"], ["o'u vae", "my foot"], ["e pei o vae", "like foot"], ["o aila,", "aila"], ["o ia foi", "he also"], ["ou te sāvali ai", "I will walk"], ["i a'u mea maualuluga.", "in me thing most high"], ["Ma le usu pese", "and the to lead the singing a song"], ["i nekina.", "in nekina"]]},
];
renderVerseSet(_hab_ch_3_Verses, 'hab-ch3-verses');

})();