(function() {
var hab_ch_1_Verses = [
  {num:1,words:[["O le avega", "the avega"], ["na vaaia", "seen"], ["e le perofeta o Sapakuka.", "by the prophet sapakuka"]]},
  {num:2,words:[["Ieova e,", "Jehovah by"], ["ou te valaau seia afea,", "I call until when ?"], ["ae te", "but"], ["le faafofoga mai;", "the listen from"], ["ou te alaga atu ia te oe", "I a shoulder or leg of aa ' unto you"], ["ona o le sauaga,", "because of the sauaga"], ["ae te", "but"], ["le faaola mai?", "the save from"]]},
  {num:3,words:[["Se a ea", "a but to rise (as a diver to the sur-"], ["le mea", "the thing"], ["ua e faaali", "to reveal"], ["mai ai ia te au", "from unto me"], ["le amio leaga,", "the iniquity"], ["ma e silasila", "and to saw"], ["i le puapuaga? e", "in the affliction by"], ["i o'u luma", "before me"], ["le faatafunaina", "the faatafunaina"], ["ma le saua,", "and the to have a return of sick-"], ["e i ai foi", "by therein also"], ["le fefinauaiga", "the fefinauaiga"], ["ma le faatupuina", "and the faatupuina"], ["o le misa.", "the to quarrel"]]},
  {num:4,words:[["O le mea lea", "therefore/wherefore"], ["ua faaleaogaina ai", "faaleaogaina"], ["le tulafono,", "the law"], ["ua le faia foi", "the made also"], ["le faamasinoga faamaoni;", "the judgment faithful"], ["auā ua siosioina", "for siosioina"], ["le ua amiotonu", "the righteous"], ["e le", "by the"], ["ua amio leaga,", "iniquity"], ["o le mea lea", "therefore/wherefore"], ["ua fai ai", "make"], ["le faamasinoga faapiopio.", "the judgment faapiopio"]]},
  {num:5,words:[["Ia outou vaai atu", "to you (all) to look at"], ["i nuu ese,", "in nation away"], ["ma ia outou iloa,", "and to you (all) known"], ["ma ia matuā taufaiofo lava;", "and to very taufaiofo indeed"], ["auā ou te faia", "for I make"], ["se galuega", "a work"], ["i ona aso o outou,", "in then day you (all)"], ["e ui lava", "to although indeed"], ["ina talaina atu,", "let talaina"], ["tou te", "second person plural"], ["le talitonu ai lava.", "the believe indeed"]]},
  {num:6,words:[["Auā faauta,", "for behold"], ["ou te lagaina Kaletaia,", "I lagaina kaletaia"], ["o le nuu saua", "the nation to have a return of sick-"], ["ma le tele vavave,", "and the great vavave"], ["o loo latou", "they"], ["o atu", "o atu"], ["i le lautele", "in the lautele"], ["o le lalolagi,", "the earth"], ["e fai", "to make"], ["mo latou", "for they"], ["o mea", "thing"], ["e nonofo ai,", "to dwelling"], ["ae le ni o latou", "but the some they"], ["nuu .", "nation"]]},
  {num:7,words:[["O i latou", "them"], ["e matautia", "by matautia"], ["ma le fefefe", "and the fefefe"], ["i ai o tagata;", "therein man"], ["e tupu mai ia te", "to king from"], ["i latou lava lo latou faamasinoga", "them indeed their judgment"], ["ma lo latou mamalu.", "and the they glory"]]},
  {num:8,words:[["E sili", "to most"], ["ona tele vavave foi", "and great vavave also"], ["a latou solofanua", "but they horse"], ["i nameri,", "in nameri"], ["e sili", "to most"], ["ona feai foi", "and feai also"], ["i luko", "in wolf"], ["i le afiafi;", "in the evening"], ["e faalialia foi", "to to make a display also"], ["a latou 'au", "but they I"], ["e tietie", "by tietie"], ["i solofanua,", "in horse"], ["o a latou 'au foi", "but they I also"], ["e tietie", "by tietie"], ["i solofanua", "in horse"], ["e o mai", "by from"], ["i le mea mamao;", "in the thing to be far ofl\""], ["latou te felelei pei o aeto", "they flying to be broken aeto"], ["e tele vavave", "to great vavave"], ["e aai ai.", "to city"]]},
  {num:9,words:[["Latou te o uma", "they all"], ["mai ina ia saua;", "from so that to have a return of sick-"], ["o le faasaga", "the toward"], ["mai o latou mata", "from they eye"], ["e pei o le matagi", "like the wind"], ["mai sasae;", "from to tear"], ["latou te faapotopotoina tagata o taua", "they faapotopotoina man war"], ["e pei o le oneone.", "like the sand"]]},
  {num:10,words:[["Latou te tauemu", "they tauemu"], ["i tupu,", "in king"], ["latou te tapisa foi", "they tapisa also"], ["i tamaalii;", "in tamaalii"], ["latou te tapisa", "they tapisa"], ["i 'olo uma,", "in fortress all"], ["auā latou te tanu ai", "for they to bury"], ["le eleele,", "the earth"], ["ma latou aea.", "and they aea"]]},
  {num:11,words:[["Ona atili naunau ai lea", "and atili naunau"], ["o i latou,", "them"], ["ona latou", "and they"], ["o atu lea,", "o atu lea,"], ["ma latou nofo sala ai,", "and they dwell a fine"], ["o loo faapea ane ,", "thus"], ["O lo latou malosi lea", "their strong"], ["i lo latou atua.", "in the they God"]]},
  {num:12,words:[["Ieova e,", "Jehovah by"], ["lo'u Atua,", "my God"], ["le Paia e,", "the holy by"], ["e te", "by"], ["le mai", "the from"], ["le faavavau ea? matou", "the a stone connected with to rise (as a diver to the sur- we (excl)"], ["te le oti;", "the die"], ["Ieova e,", "Jehovah by"], ["ua e tuu ia te", "to put unto"], ["i latou", "them"], ["e faaoo ai sala,", "by faaoo a fine"], ["le Papa e,", "the burster by"], ["ua e tofia", "to chosen"], ["i latou", "them"], ["e fai ai aoaiga.", "to make aoaiga"]]},
  {num:13,words:[["E sili", "to most"], ["ona manino ou fofoga,", "and manino I face"], ["e te", "by"], ["le fia silasila", "the want to do something saw"], ["i le amio leaga,", "in the iniquity"], ["e le mafai foi", "by the able also"], ["ona e silasila", "and to saw"], ["i le agasala;", "in the sin"], ["se a ea", "a but to rise (as a diver to the sur-"], ["le mea", "the thing"], ["e te silasila ai", "by saw"], ["i e o fai amio faa'ole'ole,", "in by make conduct faa'ole'ole"], ["ma ē", "and who"], ["le fetalai", "the said"], ["ina o fasioti", "let killed"], ["e le tagata agasala", "by the man sin"], ["le tagata", "the man"], ["e sili", "to most"], ["ona amiotonu ia te ia?", "and righteous unto him"]]},
  {num:14,words:[["ma ē faia tagata ia", "and who made man to"], ["pei o i'a", "to be broken fish"], ["o le sami,", "Sea"], ["pei o mea fetolofi,", "to be broken creeping thing"], ["e leai so latou", "there is not so they"], ["faipule?", "a councillor"]]},
  {num:15,words:[["Ua latou avae ia te", "they avae unto"], ["i latou uma", "them all"], ["i le mātau,", "in the mātau"], ["ua aofia", "aofia"], ["i latou", "them"], ["i lo latou upega,", "in the they upega"], ["ua taena'i foi ia te", "taena'i also unto"], ["i latou", "them"], ["i lo latou tu'i;", "in the they '2l high chief"], ["o le mea lea", "therefore/wherefore"], ["ua latou fiafia ai,", "they competition"], ["ma ua mitamita lava.", "and to boast indeed"]]},
  {num:16,words:[["O le mea lea latou", "therefore they"], ["te fai ai taulaga", "make offering"], ["i lo latou upega,", "in the they upega"], ["latou te faamu ai foi mea manogi", "they faamu also thing fragrant"], ["i lo latou tu'i;", "in the they '2l high chief"], ["auā o ia mea", "for he thing"], ["e lelei ai", "to good"], ["a latou mea", "but they thing"], ["ua maua,", "received"], ["e lololo ai foi", "by lololo also"], ["a latou mea", "but they thing"], ["e 'ai.", "to eat"]]},
  {num:17,words:[["O le mea ea lea latou", "the thing to rise (as a diver to the sur- they"], ["te sasaa atu ai lo latou upega,", "plurzH x)^ saasaa their upega"], ["ma le", "and the"], ["le mapu", "the mapu"], ["ona fasioti pea lava", "and killed continually indeed"], ["i atunuu?", "in nations"]]},
];
renderVerseSet(hab_ch_1_Verses, 'hab-ch1-verses');

var hab_ch_2_Verses = [
  {num:1,words:[["Ou te tu", "I stand"], ["i le mea ou te leoleo ai,", "in the thing I police"], ["ou te tu foi a'u", "I stand also I"], ["i le 'olo,", "in the fortress"], ["ou te vaavaai foi", "I vaavaai also"], ["ina ia ou iloa", "so that I known"], ["pe se", "whether a"], ["a se mea", "but a thing"], ["e fetalai mai ai o ia", "to said he"], ["ia te au,", "unto me"], ["pe se", "whether a"], ["a foi", "but also"], ["se mea ou te tali atu ai", "a thing I respond"], ["i la'u finauga.", "in my argument"]]},
  {num:2,words:[["Ua tali mai foi Ieova", "respond from also Jehovah"], ["ia te au,", "unto me"], ["ua faapea mai,", "saying"], ["Ia e tusi", "to to book"], ["le faaaliga,", "the revelation"], ["ia e togitogi", "to by togitogi"], ["i papa,", "in burster"], ["ina ia momo'e o ia", "so that momo'e he"], ["le na te faitauina.", "the he faitauina"]]},
  {num:3,words:[["Auā o le faaaliga", "for the revelation"], ["ua tuuina", "given"], ["mo ona aso", "for then day"], ["ua tuupoina,", "tuupoina"], ["a e tautala", "but to to talk"], ["mai pe", "from whether"], ["a oo", "but oo"], ["i le iuga,", "in the iuga"], ["e le pepelo lava;", "by the false indeed"], ["e ui lava", "to although indeed"], ["ina tuai mai,", "let to be a long time from"], ["a ia faatalitali pea", "but to faatalitali continually"], ["i ai;", "therein"], ["auā e oo", "for it shall come to pass"], ["mai lava,", "from indeed"], ["e le faatuai", "by the faatuai"], ["mai.", "from"]]},
  {num:4,words:[["Faauta,", "behold"], ["o le", "the"], ["ua faafefeteina", "faafefeteina"], ["e le tonu lona loto", "by the right his heart"], ["i totonu ia te ia;", "in inside unto him"], ["a o le", "but the"], ["ua amiotonu", "righteous"], ["e ola ia", "to life to"], ["i lona faatuatua.", "in his faith"]]},
  {num:5,words:[["A e moni lava,", "but verily I say"], ["o le uaina", "the wine"], ["o le faa'ole'ole lea;", "the faa'ole'ole"], ["o le tagata faafefeteina", "man faafefeteina"], ["e le nofo foi o ia", "by the dwell also he"], ["i lona fale,", "in his house"], ["na te faateleina lona manao pei", "he faateleina his desire to be broken"], ["o seoli,", "seoli"], ["e pei o le oti", "like the die"], ["lava ia,", "indeed to"], ["e le maona lava;", "by the to subside indeed"], ["na te faapotopotoina nuu uma", "he faapotopotoina nation all"], ["lava ia te ia,", "indeed unto him"], ["na te aofaiina foi ia te ia", "he aofaiina also unto him"], ["nuu uma.", "nation all"]]},
  {num:6,words:[["E le sauni ea", "by the he who beg^ins the game to rise (as a diver to the sur-"], ["e i latou uma", "by them all"], ["le faataoto ia te ia,", "the a parable unto him"], ["atoa ma le pese faatauemu", "and the a song mock"], ["foi ia te ia,", "also unto him"], ["ma latou faapea atu,", "and they thus"], ["Oi talofa", "wo"], ["i le", "in the"], ["na te faaputu mea", "he to gather together thing"], ["e le ni ana mea!", "by the some his thing"], ["Seia afea? Oi talofa foi", "until when ? wo also"], ["ia te ia", "unto him"], ["o le", "the"], ["na te faafaupue ia te ia", "he faafaupue unto him"], ["oloa ese!", "goods away"]]},
  {num:7,words:[["E le faafuasei ea", "by the faafuasei to rise (as a diver to the sur-"], ["ona tulai atu", "and arose up"], ["i latou", "them"], ["o e", "who"], ["a feutia oe,", "but feutia you"], ["ma latou ala", "and they arise"], ["mai o", "from"], ["e faatigaina oe,", "by faatigaina you"], ["ona avea lea o oe", "and become you"], ["ma vete mā latou?", "and vete First person dual exclusive they"]]},
  {num:8,words:[["Sa e vetea nuu e tele,", "by vetea nation to great"], ["o le mea lea", "therefore/wherefore"], ["e vetea ai oe", "by vetea you"], ["e nuu uma o totoe;", "to nation all phiral of foe"], ["ona o le toto o tagata,", "because of the blood man"], ["ma le saua", "and the to have a return of sick-"], ["i le nuu,", "in the land"], ["ma le aai,", "and the city"], ["ma i latou uma o", "and them all"], ["e nonofo ai.", "to dwelling"]]},
  {num:9,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te maua", "he received"], ["i le amio leaga", "in the iniquity"], ["le oloa mā lona aiga,", "the goods First person dual exclusive his family"], ["ina ia tuu lona ofaga", "so that put his a nest"], ["i le mea maualuga,", "in the thing Iiigli"], ["ina ia laveaiina o ia", "so that delivered he"], ["i le malaia!", "in the a calamity"]]},
  {num:10,words:[["Ua e filifili", "to choose"], ["se mea", "a thing"], ["e oo ai", "it shall come to pass"], ["le mā", "the First person dual exclusive"], ["i lou lava aiga,", "in your indeed family"], ["i lou faaumatia o nuu", "in your destroy nation"], ["e tele;", "to great"], ["ua e agasala foi ia te oe", "to sin also unto you"], ["lava.", "indeed"]]},
  {num:11,words:[["Auā e alaga", "for to a shoulder or leg of aa '"], ["mai le maa ai", "from the stone"], ["le pa puipui,", "the a wall a duor"], ["o le faalava foi ai", "the faalava also"], ["le laau", "the tree"], ["e tali atu", "to respond"], ["i ai.", "therein"]]},
  {num:12,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te faia", "he made"], ["se aai", "a city"], ["i le toto,", "in the blood"], ["ma faatumauina", "and faatumauina"], ["se aai", "a city"], ["i le amioletonu!", "in the wickedness"]]},
  {num:13,words:[["Faauta,", "behold"], ["e le mai ia", "by the from to"], ["Ieova o 'au ea", "Jehovah I to rise (as a diver to the sur-"], ["ona ia galulue tagata mā", "and to galulue man First person dual exclusive"], ["le afi,", "the fire"], ["ma ia lailoa nuu ia", "and to to be exhausted nation to"], ["i latou lava", "them indeed"], ["i mea", "in thing"], ["le aoga lava?", "the useful indeed"]]},
  {num:14,words:[["Auā e tumu", "for to fill"], ["le lalolagi", "the earth"], ["i le malamalama", "in the knowledge"], ["o le mamalu o Ieova,", "the glory Jehovah"], ["faapei ona ufitia", "like then covered"], ["o le iliti tai", "the iliti the heart of a tree"], ["i le suāsami.", "in the suāsami"]]},
  {num:15,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te faainu", "he faainu"], ["i le tasi tagata,", "in the one man"], ["o oe", "you"], ["o lē liligi atu lau mea oona", "not to pour your thing oona"], ["ia te ia", "unto him"], [",", ","], ["ua e faaonā foi ia te ia", "by faaonā also unto him"], [",", ","], ["ina ia", "so that"], ["e vaai atu", "to to look at"], ["i lo latou", "in the they"], ["le lavalavā.", "the lavalavā"]]},
  {num:16,words:[["E tumu oe", "to fill you"], ["i le mā", "in the First person dual exclusive"], ["e le", "by the"], ["o le mamalu;", "the glory"], ["ia e inu foi oe,", "to to drink also you"], ["ma ia aliali lou", "and to to appear your"], ["le peritomeina;", "the peritomeina"], ["e liliu atu ia te oe", "to turned unto you"], ["le ipu", "the cup"], ["a le aao taumatau o Ieova,", "but the hand (extended) right hand Jehovah"], ["e i ai foi", "by therein also"], ["le puaiga", "the puaiga"], ["e faamāina ai", "by faamāina"], ["i luga", "in above"], ["o lou mamalu.", "your glory"]]},
  {num:17,words:[["Auā e liloia oe", "for to to be covered you"], ["i le saua", "in the to have a return of sick-"], ["na faia", "made"], ["i Lepanona,", "in lepanona"], ["ma le faaumatia o manu", "and the destroy animal"], ["e matuā matatau ai", "to very fear"], ["i latou;", "them"], ["ona o le toto o tagata,", "because of the blood man"], ["ma le saua", "and the to have a return of sick-"], ["i le nuu,", "in the land"], ["ma le aai,", "and the city"], ["ma i latou uma o", "and them all"], ["e nonofo ai.", "to dwelling"]]},
  {num:18,words:[["Se a ea", "a but to rise (as a diver to the sur-"], ["le aoga", "the useful"], ["o le tupua", "the idol"], ["ua ta", "a stroke"], ["ina ua taia", "let taia"], ["e le", "by the"], ["na na faia;", "made"], ["o le tupua uamea,", "the idol uamea"], ["ma le a'oa'o", "and the excellent"], ["i le pepelo,", "in the false"], ["ina ua faatuatua", "let faith"], ["le na faia", "the made"], ["i lana mea", "in his thing"], ["na fai,", "make"], ["ia fai ai e ia", "to make by him"], ["tupua e le magagana?", "idol by the magagana"]]},
  {num:19,words:[["Oi talofa", "wo"], ["i le", "in the"], ["na te fai atu", "he said to"], ["i le laau,", "in the tree"], ["Ala mai ia;", "arise from to"], ["ma le maa", "and the stone"], ["e le magagana,", "by the magagana"], ["Tulai mai ia!", "arose up from to"], ["E a'oa'o mai ea lena mea?", "to excellent from to rise (as a diver to the sur- that thing"], ["Faauta ia te ia,", "behold unto him"], ["ua ufitia", "covered"], ["i le auro", "in the gold"], ["ma le ario,", "and the silver"], ["ae leai lava", "but no indeed"], ["se mānava", "a mānava"], ["i totonu ia te ia.", "in inside unto him"]]},
  {num:20,words:[["A o Ieova", "but Jehovah"], ["ua i lona malumalu paia", "in his temple holy"], ["o ia;", "he"], ["ina faalologo ia le lalolagi uma", "let to hold one's tongue to the earth all"], ["i ona luma.", "before him"]]},
];
renderVerseSet(hab_ch_2_Verses, 'hab-ch2-verses');

var hab_ch_3_Verses = [
  {num:1,words:[["O le tatalo", "the pray"], ["a le perofeta o Sapakuka,", "but the prophet sapakuka"], ["na fai", "make"], ["ma pese.", "and a song"]]},
  {num:2,words:[["Ieova e,", "Jehovah by"], ["ua ou faalogo", "I hearken"], ["i le tala ia te oe,", "in the side unto you"], ["ua ou mata'u ai;", "I ax"], ["Ieova e,", "Jehovah by"], ["ia e toe faaolaolaina lau galuega", "to to again faaolaolaina your work"], ["i ia tausaga,", "in to year"], ["o ia tausaga ia", "he year to"], ["e faailoa mai ai;", "to declared from"], ["ia e manatu", "to to thought"], ["i le alofa ao", "in the love day"], ["e toasa.", "to wrath"]]},
  {num:3,words:[["Na afio mai", "dwell (respectful) from"], ["le Atua mai Timanu,", "God from timanu"], ["na afio mai foi", "dwell (respectful) from also"], ["le Paia mai", "the holy from"], ["le mauga o Parana.", "the mountain parana"], ["Selā.", "selā"], ["Sa ufitia", "covered"], ["le lagi", "the heaven"], ["i lona pupula,", "in his brightness"], ["o lona viiga foi", "his viiga also"], ["sa tumu ai", "fill"], ["le lalolagi.", "the earth"]]},
  {num:4,words:[["O le pupula foi", "the brightness also"], ["sa faapei", "like"], ["o le la,", "the la"], ["sa oo mai 'ave ai lona aao,", "it came to pass from take his hand (extended)"], ["sa iai foi", "there also"], ["le ufiufi", "the ufiufi"], ["o lona mana.", "his to get"]]},
  {num:5,words:[["Sa muamua atu", "first"], ["le faamai", "the faamai"], ["i ona luma,", "before him"], ["sa mulimuli foi ia te ia", "follow after also unto him"], ["le ma'i vevela", "the from to be hot"]]},
  {num:6,words:[["Sa tu o ia", "stand he"], ["ma fuafua", "and abscesses in the hands or"], ["le lalolagi;", "the earth"], ["na ia silasila", "to saw"], ["mai,", "from"], ["ma na faagateteina nuu ese;", "and faagateteina nation away"], ["na faataapeapeina ai foi mauga", "faataapeapeina also mountain"], ["o le vavau;", "the ancient times"], ["na faamaualaloina ai mauga iti", "faamaualaloina mountain iti"], ["o le vavau;", "the ancient times"], ["o ona ala ia", "then arise to"], ["mai le vavau.", "from the ancient times"]]},
  {num:7,words:[["Na ou iloa fale ie", "I known house faamaise"], ["o Kusa", "kusa"], ["ua puapuagatia;", "puapuagatia"], ["na gatete ie puipui", "gatete faamaise a duor"], ["o le nuu o Mitiana.", "the nation mitiana"]]},
  {num:8,words:[["Na toatamai ea Ieova", "toatamai to rise (as a diver to the sur- Jehovah"], ["i vaitafe?", "in river"], ["pe na", "whether"], ["e toasa ea", "to wrath to rise (as a diver to the sur-"], ["i vaitafe?", "in river"], ["pe na", "whether"], ["e maemaea ea", "by maemaea to rise (as a diver to the sur-"], ["i le sami,", "in the sea"], ["ina ua", "let"], ["e tietie", "by tietie"], ["i au solofanua", "in I horse"], ["ma ou nofoa faataavalevale", "and I a seat to roll round and"], ["o le faaolataga?", "the faaolataga"]]},
  {num:9,words:[["Na to ese lava", "to plant away indeed"], ["le faamoega", "the faamoega"], ["o lau aufana,", "your aufana"], ["o tautoga", "tautoga"], ["na e fetalai", "to said"], ["mai ai", "from"], ["i itu aiga.", "in itu family"], ["Selā.", "selā"], ["Na e vaevaea", "by vaevaea"], ["le lalolagi", "the earth"], ["i vaitafe.", "in river"]]},
  {num:10,words:[["Na iloa oe", "known you"], ["e mauga,", "to mountain"], ["ua latou gatete ai;", "they gatete"], ["ua tafe ane", "to flow"], ["le tafega o vai;", "the a fresh water"], ["na gagana mai", "language from"], ["le moana,", "the deep"], ["ua na sisii", "to lift"], ["i luga", "in above"], ["ona lima.", "and five"]]},
  {num:11,words:[["Sa tutū pea", "tutū continually"], ["le la", "the la"], ["ma le masina", "and the moon"], ["i le mea la te mau ai;", "in the thing la opinion"], ["o le malamalama o au", "the light I am"], ["u fanafana", "u fanafana"], ["na latou savavali ai,", "they walked"], ["ma le malamalama", "and the knowledge"], ["o lou tao pupula.", "your spear brightness"]]},
  {num:12,words:[["Sa e afio atu", "to dwell (respectful)"], ["i le lalolagi", "in the world"], ["ma le toatamai,", "and the toatamai"], ["sa e soli nuu ese", "to to tread upon nation away"], ["i lou toasa.", "in your wrath"]]},
  {num:13,words:[["Sa e afio atu", "to dwell (respectful)"], ["e faaola", "to save"], ["i lou nuu,", "in your nation"], ["e faaola", "to save"], ["i le", "in the"], ["na e faauuina;", "by faauuina"], ["sa e foa", "by foa"], ["le ulu", "the head"], ["i le fale o lē amio leaga,", "in the house not iniquity"], ["i lou faataatia fua", "in your faataatia fruit"], ["le faavae ia oo", "the faavae to oo"], ["i le", "in the"], ["ua lava.", "indeed"], ["Selā.", "selā"]]},
  {num:14,words:[["Sa e sosoa", "to to dance accompanied by"], ["le alii sili", "the Lord most"], ["o ona ta'ita'i", "then ta'ita'i"], ["i ona lava tao;", "in then indeed spear"], ["sa latou feosofi", "they feosofi"], ["mai pei", "from to be broken"], ["se afā", "a cyclone"], ["e faataapeape ia te au;", "by faataapeape unto me"], ["sa fai", "make"], ["mo latou mitamita", "for they to boast"], ["le faaumatia faalilolilo", "the destroy faalilolilo"], ["o le tagata mativa.", "man mativa"]]},
  {num:15,words:[["Sa e afio", "to dwell (respectful)"], ["i totonu", "in inside"], ["o le sami", "Sea"], ["ma au solofanua,", "and I horse"], ["sa e afio foi", "to dwell (respectful) also"], ["i le faupuegāvai e tele.", "in the faupuegāvai to great"]]},
  {num:16,words:[["Na ou faalogo ai,", "I hearken"], ["ona sapotuvale ai lea", "and sapotuvale"], ["o lo'u manava,", "my manava"], ["sa tete o'u laugutu", "tete my laugutu"], ["i le leo;", "in the voice"], ["ua oo mai ai", "it came to pass from"], ["le pala", "the a muddy deposit in the sea"], ["i o'u ivi,", "in my bone"], ["ua ou tetemu ai lava;", "I to tremble indeed"], ["a e filemu a'u", "but to peace I"], ["i le aso", "in the day"], ["o le puapuaga,", "the affliction"], ["pe a alu", "whether but go"], ["ae o ia", "but he"], ["i le nuu", "in the land"], ["e sii mai", "to lift up from"], ["le taua ia te", "the war unto"], ["i tatou.", "in we (incl)"]]},
  {num:17,words:[["E ui lava", "to although indeed"], ["ina le fuga", "let the flower"], ["mai le mati,", "from the mati"], ["e leai foi ni fua", "there is not also some fruit"], ["i vine,", "in vine"], ["e iuvale", "by iuvale"], ["le fua", "the fruit"], ["o le olive,", "the olive"], ["e le tupu", "by the king"], ["mai foi ni mea", "from also some thing"], ["e 'ai", "to eat"], ["i le fanua;", "in the land"], ["e faaumatia", "to destroy"], ["le lafu mamoe", "the a herd sheep"], ["i le lotoā", "in the lotoā"], ["e leai foi ni povi", "there is not also some cattle"], ["i le fale povi;", "in the house cattle"]]},
  {num:18,words:[["a e peitai a'u,", "but to however I"], ["ou te olioli lava ia", "I rejoice indeed to"], ["Ieova,", "Jehovah"], ["ou te fiafia lava", "I competition indeed"], ["i le Atua", "in the God"], ["o lo'u faaolataga.", "my faaolataga"]]},
  {num:19,words:[["O Ieova", "Jehovah"], ["le Alii,", "the Lord"], ["o lo'u malosi ia,", "my strong to"], ["na te faia o'u vae", "he made my foot"], ["e pei o vae o aila,", "to to be broken foot aila"], ["o ia foi ou te savali ai", "he also I walk"], ["i a'u mea maualuluga.", "in I thing maualuluga"], ["Ma le usu pese", "and the to lead the singing a song"], ["i nekina.", "in nekina"]]},
];
renderVerseSet(hab_ch_3_Verses, 'hab-ch3-verses');

})();