(function() {
var _hag_ch_1_Verses = [
  {num:1,words:[["muamua", "first the beginning"], ["o le masina,", "the month"], ["na au mai ai", "brought"], ["le afioga", "the word"], ["a Ieova", "of the LORD"], ["e le perofeta", "shall not prophesied"], ["o Hakai ia", "Haggai he"], ["Serupapelu", "Serupapelu"], ["le atali'i o Salatielu,", "the son of Salatielu"], ["le ali'i e", "the Lord by"], ["pule ia Iuta,", "rule he Judas"], ["atoa ma Iosua", "and Joshua"], ["le atali'i o Iosataka", "the son of Iosataka"], ["o le faitaulaga sili,", "the priest most"], ["o loo fa'apea mai,", "saying from"]]},
  {num:2,words:[["Ua fa'apea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "troops"], ["o loo fa'apea mai,", "saying from"], ["Ua fai mai", "said"], ["lenei nuu,", "this nation"], ["E lei oo", "by not oo"], ["i ona aso,", "in his days"], ["o aso", "day"], ["e fai ai", "to make"], ["le fale o Ieova.", "the house the LORD"]]},
  {num:3,words:[["Ona au mai ai lea", "and bring then"], ["o le afioga", "the word"], ["a Ieova", "of the LORD"], ["e le perofeta", "shall not prophesied"], ["o Hakai,", "Haggai"], ["o loo fa'apea,", "saying"]]},
  {num:4,words:[["O", "O"], ["ona po nei ea tou te nonofo ai", "and night this indeed?/really? second person plural dwelling"], ["i o outou", "in of you all"], ["fale", "house"], ["ua tăpapa,", "tăpapa"], ["a o lenei", "but now"], ["fale", "house"], ["ua fa'atafunaina.", "destroyed"]]},
  {num:5,words:[["O lenei,", "now"], ["o loo fa'apea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "troops"], ["Ia outou mafaufau i", "he you all think in"], ["o outou ala.", "you all way"]]},
  {num:6,words:[["Ua outou totō", "you all blood"], ["mea e tele,", "great things"], ["a", "but"], ["e itiiti mea", "to small thing"], ["na outou au mai ai;", "you all brought"], ["ua outou aai,", "you all cities"], ["a", "but"], ["e lei maoona ai", "by not maoona"], ["outou;", "you all"], ["ua outou feinu,", "you all feinu"], ["a", "but"], ["e lei malilie ai", "by not malilie"], ["outou;", "you all"], ["ua outou oofu,", "you all oofu"], ["a", "but"], ["e lei mafanafana ai", "by not to be warm"], ["outou;", "you all"], ["o le", "the"], ["ua galue foi", "till also"], ["i se taui,", "in a a reward"], ["e fai", "to make"], ["lana taui", "his a reward"], ["e fafao", "to put in"], ["i le taga", "in the bag"], ["ua pūpū solo.", "the tail to move swiftly"]]},
  {num:7,words:[["O loo fa'apea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "troops"], ["Ia outou mafaufau i", "he you all think in"], ["o outou ala.", "you all way"]]},
  {num:8,words:[["Ina o ae", "so that went up"], ["ia outou i le", "he you all in the"], ["mauga,", "mountain"], ["ma outou aumaia lā'au,", "with you bring here tree"], ["ma outou faia", "with you made"], ["le fale;", "the house"], ["ona ou fiafia lea", "and I pleased"], ["i ai,", "therein"], ["e viia ai", "to praised"], ["foi au,", "also me"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:9,words:[["Ua outou fa'amoemoe", "you all hoped"], ["i mea e tele,", "in great things"], ["fa'auta foi,", "and behold"], ["ua itiiti;", "small"], ["ua outou aumaia", "you all brought here"], ["i fale,", "in house"], ["ona a'u ulafia lea;", "and me ulafia"], ["ai", "ai"], ["se a? o loo fetalai mai ai", "a but is said"], ["Ieova o 'au.", "the LORD of troops"], ["Auā", "for"], ["o lo'u fale", "my house"], ["o loo", "is/are"], ["ua fa'atafunaina lea,", "destroyed"], ["a", "but"], ["e taitasi outou", "by each you all"], ["ma momo'e atu", "and ran"], ["i lona lava fale.", "in his very house"]]},
  {num:10,words:[["O le mea lea", "therefore"], ["ua taofia ai", "held back"], ["e le lagi", "shall not heaven"], ["i o outou", "in of you all"], ["luga,", "above"], ["ina ne'i totō", "so that now blood"], ["mai ai", "from"], ["le sau;", "the come"], ["o le laueleele foi", "the ground also"], ["ua taofi e", "held by"], ["ia", "he"], ["ona fua.", "its fruit"]]},
  {num:11,words:[["Ua ou valaau foi", "I cried out also"], ["i le lāmala", "in the lāmala"], ["i luga", "in above"], ["o le eleele", "Earth"], ["ma luga o mauga,", "and above of mountain"], ["ma luga", "and above"], ["o le saito,", "the wheat"], ["ma luga", "and above"], ["o le uaina,", "the wine"], ["ma luga", "and above"], ["o le suāuu,", "the oil"], ["ma luga o mea", "and above of thing"], ["e tutupu", "to bring forth"], ["i le eleele,", "the ground"], ["ma luga o tagata,", "and above of men"], ["ma luga o manu vaefa,", "and above of beasts"], ["ma luga o galuega uma", "and above of work all"], ["a o outou", "but of you all"], ["lima.", "hand"]]},
  {num:12,words:[["Ona fa'alogo ai lea", "and hearken then"], ["o Serupapelu", "Serupapelu"], ["le atali'i o Salatielu,", "the son of Salatielu"], ["ma Iosua", "and Joshua"], ["le atali'i o Iosataka", "the son of Iosataka"], ["le faitaulaga sili,", "the priest most"], ["atoa ma", "and"], ["e", "by"], ["na totoe uma", "phiral of foe all"], ["o le nuu,", "the nation"], ["i le siufofoga", "in the voice"], ["o Ieova lo lātou Atua,", "the LORD their God"], ["ma 'upu", "and word"], ["a le perofeta", "but the prophesied"], ["o Hakai,", "Haggai"], ["e tusa ma mea", "according to thing"], ["na auina mai ai", "sent from"], ["o ia", "he"], ["e Ieova lo lātou Atua;", "the LORD their God"], ["ua matatau foi", "dismayed also"], ["le nuu ia", "the nation he"], ["Ieova.", "the LORD"]]},
  {num:13,words:[["Ona fai mai lea", "And he said"], ["o Hakai", "Haggai"], ["le sāvali", "the walk"], ["a Ieova", "of the LORD"], ["i le feau", "in the errand"], ["a Ieova", "of the LORD"], ["i le nuu,", "in the land"], ["ua fa'apea mai,", "and said"], ["O loo fetalai mai", "is/are said"], ["Ieova,", "the LORD"], ["O a'u,", "I am"], ["ou te ia te outou.", "I will unto you all"]]},
  {num:14,words:[["Ona lagaina ai lea", "and to rise to arms then"], ["e Ieova", "the LORD"], ["o le loto", "the heart"], ["o Serupapelu", "Serupapelu"], ["le atali'i o Salatielu,", "the son of Salatielu"], ["o le ali'i e", "the Lord by"], ["pule ia Iuta,", "rule he Judas"], ["ma le loto", "and the heart"], ["o Iosua", "Joshua"], ["le atali'i o Iosataka", "the son of Iosataka"], ["le faitaulaga sili,", "the priest most"], ["ma loto o", "and heart of"], ["e", "by"], ["na totoe uma", "phiral of foe all"], ["o le nuu;", "the nation"], ["ua lātou", "they"], ["o mai,", "came"], ["ma lātou faia", "and they made"], ["le galuega", "the work"], ["o le fale", "the house"], ["o Ieova o 'au", "the LORD troops"], ["o lo lātou Atua,", "their God"]]},
  {num:15,words:[["i le aso", "in the day"], ["e luafulu", "to twenty"], ["ma le fa,", "and four"], ["i le onoga masina,", "in the six month"], ["i le lua", "in the two"], ["o tausaga o Tariu", "year of Darius"], ["le tupu.", "the king"]]},
];
renderVerseSet(_hag_ch_1_Verses, 'hag-ch1-verses');

var _hag_ch_2_Verses = [
  {num:1,words:[["O le fitu", "the seven"], ["o masina,", "month"], ["o le aso", "the day"], ["e lua sefulu", "by two ten"], ["ma le tasi", "and the one"], ["i le masina,", "in the month"], ["na au mai ai", "brought"], ["le afioga", "the word"], ["a Ieova", "of the LORD"], ["e le perofeta", "shall not prophesied"], ["o Hakai,", "Haggai"], ["o loo fa'apea mai,", "saying from"]]},
  {num:2,words:[["Ina", "so that"], ["e fai atu", "to said to"], ["lava ia Serupapelu", "very he Serupapelu"], ["le atali'i o Salatielu,", "the son of Salatielu"], ["le ali'i e", "the Lord by"], ["pule ia Iuta,", "rule he Judas"], ["ma Iosua", "and Joshua"], ["le atali'i o Iosataka", "the son of Iosataka"], ["le faitaulaga sili,", "the priest most"], ["atoa ma", "and"], ["e ua totoe", "to phiral of foe"], ["o le nuu,", "the nation"], ["ia fa'apea atu.", "he so"]]},
  {num:3,words:[["O ai ea so outou", "who so you all"], ["ua toe,", "again"], ["o le", "the"], ["na iloa lenei", "knew this"], ["fale", "house"], ["i lona muai matagofie?", "in his first beautiful"], ["Pe", "whether"], ["se a lo outou vaai nei", "a but your look this"], ["i ai?", "therein"], ["E le", "by the"], ["ua peiseai", "as if"], ["ua leai ea", "there was not indeed?/really?"], ["i o outou", "in of you all"], ["manatu,", "thought"], ["pe a fa'atusa", "even though / although image"], ["ma lena?", "and that"]]},
  {num:4,words:[["A o lenei,", "but now"], ["ia e fa'amalosi", "he to be strong"], ["o oe", "you"], ["o Serupapelu,", "Serupapelu"], ["ua fetalai mai ai", "said"], ["Ieova;", "the LORD"], ["ma ia", "and he"], ["e fa'amalosi o oe", "to be strong of you"], ["o Iosua", "Joshua"], ["le atali'i o Iosataka", "the son of Iosataka"], ["le faitaulaga sili;", "the priest most"], ["ma ia fa'amalolosi outou", "and he strengthen you all"], ["tagata uma", "man all"], ["o le nuu,", "the nation"], ["ua fetalai mai ai", "said"], ["Ieova,", "the LORD"], ["ma ia outou", "and he you all"], ["galulue;", "labour"], ["auā", "for"], ["o a'u,", "I am"], ["ou te ia te outou,", "I will unto you all"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:5,words:[["O le feagaiga", "the covenant"], ["na ou osia", "I hewn"], ["ma outou", "with you"], ["ina ua o mai outou", "when came you all"], ["nai Aikupito,", "from Egypt"], ["atoa ma lo'u Agaga", "and my spirit"], ["o loo tumau", "is enduring"], ["ia te outou;", "unto you all"], ["aua", "for"], ["le fefefe outou.", "the afraid you all"]]},
  {num:6,words:[["Auā o loo fa'apea ona", "for saying his"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "troops"], ["E toe tasi,", "to again one"], ["e toe itiiti", "to again small"], ["lava,", "very"], ["ona ou luluina ai lea", "and I shaken then"], ["o le lagi,", "Heaven"], ["ma le lalolagi,", "and the earth"], ["ma le sami,", "and the sea"], ["atoa ma le eleele matutu.", "and the dry land"]]},
  {num:7,words:[["Ou te luluina foi", "I will shaken also"], ["nuu uma;", "nation all"], ["ona oo mai ai lea", "and came then"], ["o mea", "thing"], ["ua manaomia", "desired"], ["e nuu uma;", "to nation all"], ["ou te fa'atumuina foi", "I will filled also"], ["lenei fale", "this house"], ["i le pupula,", "in the brightness"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:8,words:[["O loo ia te au", "is/are unto me"], ["le ario,", "the silver"], ["o loo ia te au", "is/are unto me"], ["foi", "also"], ["le auro,", "the gold"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:9,words:[["E sili", "to most"], ["le mamalu o lenei", "the glory now"], ["fale", "house"], ["ua mulimuli", "followed after"], ["i le", "in the"], ["na muamua,", "first the beginning"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of troops"], ["ou te avatu foi", "I will give away also"], ["le manuia", "the prosper"], ["i le mea nei,", "in the thing this"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:10,words:[["O le aso", "the day"], ["e luafulu", "to twenty"], ["ma le fa,", "and four"], ["o le ivaga masina", "the nine month"], ["o le lua", "the two"], ["o tausaga o Tariu,", "year of Darius"], ["na au mai ai", "brought"], ["le afioga", "the word"], ["a Ieova", "of the LORD"], ["e le perofeta", "shall not prophesied"], ["o Hakai,", "Haggai"], ["o loo fa'apea mai,", "saying from"]]},
  {num:11,words:[["Ua fa'apea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "troops"], ["Fesili ia", "asked he"], ["i faitaulaga", "in priest"], ["i le tulafono,", "in the law"], ["ia fa'apea,", "he so"]]},
  {num:12,words:[["Afai", "if"], ["e ave", "to take"], ["e se tasi", "by a one"], ["se tufaaga paia", "a portion holy"], ["i lona pito ofu,", "in his edge garment"], ["ona pai atu lea", "and pie"], ["o lona pito ofu", "his edge garment"], ["i se areto,", "in a bread"], ["po", "night"], ["o se mea", "a thing"], ["ua tunua,", "was roast"], ["po", "night"], ["o se uaina,", "a wine"], ["po", "night"], ["o se suāuu,", "a oil"], ["po", "night"], ["o se tasi mea", "a one thing"], ["e 'aina,", "to edible"], ["pe fa'apaiaina ai ea", "whether consecrated indeed?/really?"], ["ia mea?", "he thing"], ["Ona tali mai lea", "and respond from"], ["o faitaulaga,", "priest"], ["ua fa'apea mai,", "and said"], ["E leai.", "there is not"]]},
  {num:13,words:[["Ona fai atu lea", "And he said"], ["o Hakai,", "Haggai"], ["Afai", "if"], ["ua pai atu", "pie"], ["le", "the"], ["ua leaga", "evil"], ["i le tagata oti", "in the man die"], ["i se mea", "in a thing"], ["o ia mea,", "he thing"], ["pe leaga ai ea", "whether evil indeed?/really?"], ["ia mea?", "he thing"], ["Ona tali mai lea", "and respond from"], ["o faitaulaga,", "priest"], ["ua fa'apea,", "saying"], ["E leaga ai.", "to evil"]]},
  {num:14,words:[["Ona tali atu lea", "and respond"], ["o Hakai,", "Haggai"], ["ua fa'apea atu,", "and said"], ["Ua fa'apena nei", "likewise this"], ["tagata,", "man"], ["ua fa'apena foi", "likewise also"], ["lenei nuu", "this nation"], ["i o'u luma,", "before me"], ["o loo fetalai mai ai", "is said"], ["Ieova;", "the LORD"], ["ua fa'apena foi", "likewise also"], ["mea uma", "all things"], ["ua faia", "made"], ["e o lātou", "by of they"], ["lima,", "hand"], ["o mea foi", "thing also"], ["ua lātou avatua", "they given away"], ["iina", "there"], ["ua leaga lava ia.", "evil very he"]]},
  {num:15,words:[["O lenei", "now"], ["foi,", "also"], ["ia mafaufau lava outou,", "he think very you all"], ["ia afua mai i", "he beginning from / starting from in"], ["lenei lava aso", "this very day"], ["e oo", "it shall come to pass"], ["i aso", "in day"], ["ua tuanai,", "tuanai"], ["a o lei fa'aeetia", "but of not faaeetia"], ["se maa", "a stone"], ["i luga", "in above"], ["o le tasi maa", "the one stone"], ["i le malumalu", "in the temple"], ["o Ieova;", "the LORD"]]},
  {num:16,words:[["e afua mai", "to beginning from / starting from"], ["i ia", "in he"], ["ona po,", "and night"], ["na alu ane ai", "went forth"], ["le tagata", "the man"], ["i le fa'aputugāsaito,", "in the faaputugāsaito"], ["o fuataga", "measure"], ["e luafulu,", "to twenty"], ["a", "but"], ["ua", "ua"], ["i ai", "therein"], ["na", "na"], ["o le sefulu;", "the ten"], ["na alu ane", "went forth"], ["le tagata", "the man"], ["i le tuugāuaina", "in the tuugāuaina"], ["e asu ai", "by asu"], ["tumu", "fill"], ["e limagafulu ai", "to fifty"], ["le tuugāuaina,", "the tuugāuaina"], ["a", "but"], ["ua", "ua"], ["i ai", "therein"], ["na", "na"], ["o le luafulu.", "the twenty"]]},
  {num:17,words:[["Na ou taia", "I struck"], ["outou", "you all"], ["i le mamae,", "in the mamae"], ["ma le polopologa,", "and the Chili pepper"], ["ma le uato'a,", "and the uato'a"], ["i galuega uma", "in work all"], ["a outou lima;", "your hand"], ["a", "but"], ["ua outou", "you all"], ["le foi mai ia te au,", "the returned unto me"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:18,words:[["Se'i mafaufau lava outou,", "a flower put into the hair or think very you all"], ["ia afua mai i", "he beginning from / starting from in"], ["lenei lava aso,", "this very day"], ["e oo", "it shall come to pass"], ["i aso", "in day"], ["ua tuanai,", "tuanai"], ["o le aso", "the day"], ["e luafulu", "to twenty"], ["ma le fa", "and four"], ["i le ivaga masina ,", "in the nine month"], ["talu", "since"], ["le aso", "the day"], ["na fa'avaeina ai", "foundation"], ["le malumalu o Ieova;", "the temple the LORD"], ["ina outou mafaufau", "so that you all think"], ["ia.", "he"]]},
  {num:19,words:[["E", "by"], ["i ai", "therein"], ["pea ea", "continually indeed?/really?"], ["le saito", "the wheat"], ["i le fale saito?", "in the house wheat"], ["Ua oo foi", "it came to pass also"], ["i lenei", "in this"], ["aso", "day"], ["ua", "ua"], ["le fua mai le vine,", "the fruit from the vine"], ["ma le mati,", "and the fig"], ["ma le rimoni,", "and the Rimmon"], ["ma le olive;", "and the olive"], ["e amata mai", "to began from"], ["i lenei", "in this"], ["lava aso", "very day"], ["ona ou fa'amanuia", "and I blessed"], ["ia te outou", "unto you all"], [".", "."]]},
  {num:20,words:[["Ua oo mai foi", "it came to pass from also"], ["le afioga", "the word"], ["a Ieova,", "of the LORD"], ["o le atu lua lea,", "the two"], ["ia Hakai i le aso", "he Haggai in the day"], ["e luafulu", "to twenty"], ["ma le fa", "and four"], ["o le masina,", "the month"], ["o loo fa'apea mai,", "saying from"]]},
  {num:21,words:[["Fai atu ia", "said to he"], ["Serupapelu", "Serupapelu"], ["le ali'i e", "the Lord by"], ["pule ia Iuta,", "rule he Judas"], ["ia fa'apea atu,", "he so"], ["Ou te luluina", "I will shaken"], ["le lagi", "the heaven"], ["ma le lalolagi;", "and the earth"]]},
  {num:22,words:[["ou te fulisia", "I will fulisia"], ["le nofoālii o mālō;", "the throne of kingdom"], ["ou te fa'aumatia foi", "I will destroyed also"], ["le malosi o mālō", "the strong of kingdom"], ["o nuu ese;", "nation away"], ["ou te fulisia foi", "I will fulisia also"], ["kariota", "chariot"], ["ma ē tietie ai;", "and by ride"], ["e pauu solofanua", "to fell horse"], ["ma ē tietie ai,", "and by ride"], ["e fegaseai", "by fegaseai"], ["i lātou", "them"], ["i", "in"], ["a lātou pelu.", "their sword"]]},
  {num:23,words:[["Ua fetalai mai", "said"], ["Ieova o 'au,", "the LORD of troops"], ["O lea", "therefore"], ["lava aso ou te avea ai", "very day I will become"], ["oe", "you"], ["la'u auauna o Serupapelu", "my servant of Serupapelu"], ["le atali'i o Salatielu,", "the son of Salatielu"], ["ua fetalai mai ai", "said"], ["Ieova;", "the LORD"], ["ou te faia oe", "I will make you"], ["e pei", "like"], ["se fa'amaufaailoga;", "a seal"], ["auā", "for"], ["ua ou filifilia oe,", "I chosen you"], ["ua fetalai mai ai", "said"], ["Ieova", "the LORD"], ["o a'u.", "I am"]]},
];
renderVerseSet(_hag_ch_2_Verses, 'hag-ch2-verses');

})();