(function() {
var _hag_ch_1_Verses = [
  {num:1,words:[["muamua o le masina,", "first the moon"], ["na au mai ai", "bring"], ["le afioga", "the a word"], ["a Ieova", "of the LORD"], ["e le perofeta o Hakai", "by the prophet of Haggai"], ["ia Serupapelu", "to Serupapelu"], ["le atalii o Salatielu,", "the son of Salatielu"], ["le alii e", "the Lord by"], ["pule ia Iuta,", "rule to Judas"], ["atoa ma Iosua", "and Joshua"], ["le atalii o Iosataka", "the son of Iosataka"], ["o le faitaulaga sili,", "the priest most"], ["o loo faapea", "saying"], ["mai,", "from"]]},
  {num:2,words:[["Ua faapea ona", "saying and"], ["fetalai mai o Ieova o 'au,", "said the LORD I"], ["o loo faapea", "saying"], ["mai,", "from"], ["Ua fai mai lenei nuu,", "said this nation"], ["E lei oo", "by not oo"], ["i ona aso,", "in then day"], ["o aso", "day"], ["e fai ai", "to make"], ["le fale o Ieova.", "the house the LORD"]]},
  {num:3,words:[["Ona au mai ai lea", "and bring"], ["o le afioga", "the a word"], ["a Ieova", "of the LORD"], ["e le perofeta o Hakai,", "by the prophet of Haggai"], ["o loo faapea,", "saying"]]},
  {num:4,words:[["O ona po nei ea tou te nonofo ai", "then night this to rise (as a diver to the sur- second person plural dwelling"], ["i o outou fale", "in of you (all) house"], ["ua tăpapa,", "tăpapa"], ["a o lenei fale", "but of this house"], ["ua faatafunaina.", "destroyed"]]},
  {num:5,words:[["O lenei,", "this"], ["o loo faapea ona", "saying and"], ["fetalai mai o Ieova o 'au,", "said the LORD I"], ["Ia outou mafaufau", "to you (all) think"], ["i o outou ala.", "in of you (all) way"]]},
  {num:6,words:[["Ua outou totō mea e tele,", "you (all) totō great things"], ["a e itiiti mea", "but to small thing"], ["na outou au", "you (all) I"], ["mai ai;", "from"], ["ua outou aai,", "you (all) city"], ["a e lei maoona ai outou;", "but by not maoona you (all)"], ["ua outou feinu,", "you (all) feinu"], ["a e lei malilie ai outou;", "but by not malilie you (all)"], ["ua outou oofu,", "you (all) oofu"], ["a e lei mafanafana ai outou;", "but by not to be warm you (all)"], ["o le", "the"], ["ua galue foi", "till also"], ["i se taui,", "in a a reward"], ["e fai lana taui", "to make his a reward"], ["e fafao", "by fafao"], ["i le taga", "in the the shark's stomach"], ["ua pūpū solo.", "pūpū to move swiftly"]]},
  {num:7,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova o 'au,", "said the LORD I"], ["Ia outou mafaufau", "to you (all) think"], ["i o outou ala.", "in of you (all) way"]]},
  {num:8,words:[["Ina o", "let of"], ["ae ia outou", "but to you (all)"], ["i le mauga,", "in the mountain"], ["ma outou aumaia laau,", "with you bring here tree"], ["ma outou faia", "with you made"], ["le fale;", "the house"], ["ona ou fiafia lea", "and I competition"], ["i ai,", "therein"], ["e viia ai foi au,", "to praised also I"], ["ua fetalai mai ai Ieova.", "said the LORD"]]},
  {num:9,words:[["Ua outou faamoemoe", "you (all) to expect"], ["i mea e tele,", "in great things"], ["faauta foi,", "and behold"], ["ua itiiti;", "small"], ["ua outou aumaia", "you (all) bring here"], ["i fale,", "in house"], ["ona a'u ulafia lea;", "and I ulafia"], ["ai se", "a"], ["a? o loo fetalai", "but of said"], ["mai ai Ieova o 'au.", "from the LORD of I"], ["Auā o lo'u fale o loo", "for my house of"], ["ua faatafunaina lea,", "destroyed"], ["a e taitasi outou", "but by each you (all)"], ["ma momo'e atu", "and lie down"], ["i lona lava fale.", "in his indeed house"]]},
  {num:10,words:[["O le mea lea", "therefore"], ["ua taofia ai", "held back"], ["e le lagi", "by the heaven"], ["i o outou luga,", "in of you (all) above"], ["ina ne'i totō", "let now totō"], ["mai ai", "from"], ["le sau;", "the come"], ["o le laueleele foi", "the ground also"], ["ua taofi e ia", "hold by him"], ["ona fua.", "its fruit"]]},
  {num:11,words:[["Ua ou valaau foi", "I call also"], ["i le lāmala", "in the lāmala"], ["i luga", "in above"], ["o le eleele", "Earth"], ["ma luga o mauga,", "and above of mountain"], ["ma luga", "and above"], ["o le saito,", "the wheat"], ["ma luga", "and above"], ["o le uaina,", "the wine"], ["ma luga", "and above"], ["o le suāuu,", "the suāuu"], ["ma luga o mea", "and above of thing"], ["e tutupu", "to bring forth"], ["i le eleele,", "the ground"], ["ma luga o tagata,", "and above of men"], ["ma luga o manu vaefa,", "and above of beast"], ["ma luga o galuega uma", "and above of work all"], ["a o outou lima.", "but of you (all) five"]]},
  {num:12,words:[["Ona faalogo ai lea o Serupapelu", "and hearken of Serupapelu"], ["le atalii o Salatielu,", "the son of Salatielu"], ["ma Iosua", "and Joshua"], ["le atalii o Iosataka", "the son of Iosataka"], ["le faitaulaga sili,", "the priest most"], ["atoa ma", "and"], ["e na totoe uma", "by phiral of foe all"], ["o le nuu,", "the nation"], ["i le siufofoga o Ieova lo latou Atua,", "in the voice the LORD their God"], ["ma upu", "and word"], ["a le perofeta o Hakai,", "but the prophet of Haggai"], ["e tusa ma mea", "according to thing"], ["na auina mai ai o ia", "sent from he"], ["e Ieova lo latou Atua;", "the LORD their God"], ["ua matatau foi", "fear also"], ["le nuu ia Ieova.", "the nation to the LORD"]]},
  {num:13,words:[["Ona fai mai lea o Hakai", "And he said Haggai"], ["le sāvali", "the sāvali"], ["a Ieova", "of the LORD"], ["i le feau", "in the errand"], ["a Ieova", "of the LORD"], ["i le nuu,", "in the land"], ["ua faapea mai,", "and said"], ["O loo fetalai", "said"], ["mai Ieova,", "from the LORD"], ["O a'u,", "I am"], ["ou te ia te outou.", "I unto you"]]},
  {num:14,words:[["Ona lagaina ai lea", "and lagaina"], ["e Ieova", "the LORD"], ["o le loto o Serupapelu", "the heart of Serupapelu"], ["le atalii o Salatielu,", "the son of Salatielu"], ["o le alii e", "the Lord by"], ["pule ia Iuta,", "rule to Judas"], ["ma le loto o Iosua", "and the heart of Joshua"], ["le atalii o Iosataka", "the son of Iosataka"], ["le faitaulaga sili,", "the priest most"], ["ma loto o", "and heart of"], ["e na totoe uma", "by phiral of foe all"], ["o le nuu;", "the nation"], ["ua latou", "they"], ["o mai,", "from"], ["ma latou faia", "and they made"], ["le galuega", "the work"], ["o le fale o Ieova", "the house the LORD"], ["o 'au", "I"], ["o lo latou Atua,", "their God"]]},
  {num:15,words:[["i le aso", "in the day"], ["e luafulu", "to twenty"], ["ma le fa,", "and four"], ["i le onoga masina,", "in the onoga moon"], ["i le lua o tausaga", "in the two of year"], ["o Tariu", "Darius"], ["le tupu.", "the king"]]},
];
renderVerseSet(_hag_ch_1_Verses, 'hag-ch1-verses');

var _hag_ch_2_Verses = [
  {num:1,words:[["O le fitu o masina,", "the seven of moon"], ["o le aso", "the day"], ["e lua sefulu", "by two ten"], ["ma le tasi", "and the one"], ["i le masina,", "in the moon"], ["na au mai ai", "bring"], ["le afioga", "the a word"], ["a Ieova", "of the LORD"], ["e le perofeta o Hakai,", "by the prophet of Haggai"], ["o loo faapea", "saying"], ["mai,", "from"]]},
  {num:2,words:[["Ina e fai atu lava", "let to said to indeed"], ["ia Serupapelu", "to Serupapelu"], ["le atalii o Salatielu,", "the son of Salatielu"], ["le alii e", "the Lord by"], ["pule ia Iuta,", "rule to Judas"], ["ma Iosua", "and Joshua"], ["le atalii o Iosataka", "the son of Iosataka"], ["le faitaulaga sili,", "the priest most"], ["atoa ma", "and"], ["e ua totoe", "by phiral of foe"], ["o le nuu,", "the nation"], ["ia faapea atu.", "to thus"]]},
  {num:3,words:[["O ai ea so outou", "who so you (all)"], ["ua toe,", "again"], ["o le", "the"], ["na iloa lenei fale", "knew this house"], ["i lona muai matagofie?", "in his first beautiful"], ["Pe se", "whether a"], ["a lo outou vaai nei", "but your to look at this"], ["i ai?", "therein"], ["E le", "by the"], ["ua peiseai", "as if"], ["ua leai ea", "there was not to rise (as a diver to the sur-"], ["i o outou manatu,", "in of you (all) thought"], ["pe a faatusa", "whether but image"], ["ma lena?", "and that"]]},
  {num:4,words:[["A o lenei,", "but of this"], ["ia e faamalosi o oe", "to to be strong of you"], ["o Serupapelu,", "Serupapelu"], ["ua fetalai mai ai Ieova;", "said the LORD"], ["ma ia", "and to"], ["e faamalosi o oe", "to be strong of you"], ["o Iosua", "Joshua"], ["le atalii o Iosataka", "the son of Iosataka"], ["le faitaulaga sili;", "the priest most"], ["ma ia faamalolosi outou", "and to faamalolosi you (all)"], ["tagata uma", "man all"], ["o le nuu,", "the nation"], ["ua fetalai mai ai Ieova,", "said the LORD"], ["ma ia outou galulue;", "and to you (all) labour"], ["auā o a'u,", "for I am"], ["ou te ia te outou,", "I unto you"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:5,words:[["O le feagaiga", "the covenant"], ["na ou osia", "I hewn"], ["ma outou", "with you"], ["ina ua o", "let of"], ["mai outou", "from you (all)"], ["nai Aikupito,", "from Egypt"], ["atoa ma lo'u Agaga o loo tumau", "and my spirit of enduring"], ["ia te outou;", "unto you"], ["aua le fefefe outou.", "for the afraid you (all)"]]},
  {num:6,words:[["Auā o loo faapea ona", "for saying then"], ["fetalai mai o Ieova o 'au,", "said the LORD I"], ["E toe tasi,", "to again one"], ["e toe itiiti lava,", "to again small indeed"], ["ona ou luluina ai lea", "and I shaken"], ["o le lagi,", "Heaven"], ["ma le lalolagi,", "and the earth"], ["ma le sami,", "and the sea"], ["atoa ma le eleele matutu.", "and the dry land"]]},
  {num:7,words:[["Ou te luluina foi nuu uma;", "I shaken also nation all"], ["ona oo mai ai lea", "and came"], ["o mea", "thing"], ["ua manaomia", "desired"], ["e nuu uma;", "to nation all"], ["ou te faatumuina foi lenei fale", "I filled also this house"], ["i le pupula,", "in the brightness"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:8,words:[["O loo ia te au", "unto me"], ["le ario,", "the silver"], ["o loo ia te au", "unto me"], ["foi le auro,", "also the gold"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:9,words:[["E sili", "to most"], ["le mamalu o lenei fale", "the glory of this house"], ["ua mulimuli", "follow after"], ["i le", "in the"], ["na muamua,", "first"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["ou te avatu foi", "I give away also"], ["le manuia", "the peace"], ["i le mea nei,", "in the thing this"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:10,words:[["O le aso", "the day"], ["e luafulu", "to twenty"], ["ma le fa,", "and four"], ["o le ivaga masina", "the ivaga moon"], ["o le lua o tausaga", "the two of year"], ["o Tariu,", "Darius"], ["na au mai ai", "bring"], ["le afioga", "the a word"], ["a Ieova", "of the LORD"], ["e le perofeta o Hakai,", "by the prophet of Haggai"], ["o loo faapea", "saying"], ["mai,", "from"]]},
  {num:11,words:[["Ua faapea ona", "saying and"], ["fetalai mai o Ieova o 'au,", "said the LORD I"], ["Fesili ia", "to question to"], ["i faitaulaga", "in priest"], ["i le tulafono,", "in the law"], ["ia faapea,", "to thus"]]},
  {num:12,words:[["Afai e ave", "if to take"], ["e se tasi", "by a one"], ["se tufaaga paia", "a portion holy"], ["i lona pito ofu,", "in his edge garment"], ["ona pai atu lea", "and pie"], ["o lona pito ofu", "his edge garment"], ["i se areto,", "in a bread"], ["po o se mea", "night a thing"], ["ua tunua,", "tunua"], ["po o se uaina,", "night a wine"], ["po o se suāuu,", "night a suāuu"], ["po o se tasi mea", "night a one thing"], ["e 'aina,", "to edible"], ["pe faapaiaina ai ea ia", "whether consecrated to rise (as a diver to the sur- to"], ["mea? Ona tali", "thing then respond"], ["mai lea o faitaulaga,", "from of priest"], ["ua faapea mai,", "and said"], ["E leai.", "there is not"]]},
  {num:13,words:[["Ona fai atu lea o Hakai,", "And he said Haggai"], ["Afai ua pai atu", "if pie"], ["le ua leaga", "the evil"], ["i le tagata oti", "in the man die"], ["i se mea o ia", "in a thing he"], ["mea,", "thing"], ["pe leaga ai ea ia", "whether evil to rise (as a diver to the sur- to"], ["mea? Ona tali", "thing then respond"], ["mai lea o faitaulaga,", "from of priest"], ["ua faapea,", "saying"], ["E leaga ai.", "to evil"]]},
  {num:14,words:[["Ona tali atu lea o Hakai,", "and respond of Haggai"], ["ua faapea atu,", "and said"], ["Ua faapena nei tagata,", "likewise this man"], ["ua faapena foi lenei nuu", "likewise also this nation"], ["i o'u luma,", "before me"], ["o loo fetalai", "said"], ["mai ai Ieova;", "from the LORD"], ["ua faapena foi mea uma", "likewise also all things"], ["ua faia", "made"], ["e o latou lima,", "by of they five"], ["o mea foi", "thing also"], ["ua latou avatua iina", "they given away there"], ["ua leaga lava ia.", "evil indeed to"]]},
  {num:15,words:[["O lenei foi,", "this also"], ["ia mafaufau lava outou,", "to think indeed you (all)"], ["ia afua mai", "to begin from"], ["i lenei lava aso", "in this indeed day"], ["e oo", "it shall come to pass"], ["i aso", "in day"], ["ua tuanai,", "tuanai"], ["a o lei faaeetia", "but of not faaeetia"], ["se maa", "a stone"], ["i luga", "in above"], ["o le tasi maa", "the one stone"], ["i le malumalu o Ieova;", "in the temple the LORD"]]},
  {num:16,words:[["e afua mai", "to begin from"], ["i ia", "in to"], ["ona po,", "and night"], ["na alu ane ai", "go along"], ["le tagata", "the man"], ["i le faaputugāsaito,", "in the faaputugāsaito"], ["o fuataga", "fuataga"], ["e luafulu,", "to twenty"], ["a ua", "but"], ["i ai", "therein"], ["na o le sefulu;", "the ten"], ["na alu ane", "go along"], ["le tagata", "the man"], ["i le tuugāuaina", "in the tuugāuaina"], ["e asu ai tumu", "by asu fill"], ["e limagafulu ai", "to fifty"], ["le tuugāuaina,", "the tuugāuaina"], ["a ua", "but"], ["i ai", "therein"], ["na o le luafulu.", "the twenty"]]},
  {num:17,words:[["Na ou taia outou", "I struck you (all)"], ["i le mamae,", "in the mamae"], ["ma le polopologa,", "and the polopologa"], ["ma le uato'a,", "and the uato'a"], ["i galuega uma", "in work all"], ["a outou lima;", "but you (all) five"], ["a ua outou", "but you (all)"], ["le foi mai ia te au,", "the return unto me"], ["ua fetalai mai ai Ieova.", "said the LORD"]]},
  {num:18,words:[["Se'i mafaufau lava outou,", "a flower put into the hair or think indeed you (all)"], ["ia afua mai", "to begin from"], ["i lenei lava aso,", "in this indeed day"], ["e oo", "it shall come to pass"], ["i aso", "in day"], ["ua tuanai,", "tuanai"], ["o le aso", "the day"], ["e luafulu", "to twenty"], ["ma le fa", "and four"], ["i le ivaga masina ,", "in the ivaga moon"], ["talu le aso", "since the day"], ["na faavaeina ai", "faavaeina"], ["le malumalu o Ieova;", "the temple the LORD"], ["ina outou mafaufau ia.", "let you (all) think to"]]},
  {num:19,words:[["E i ai pea ea", "by therein continually to rise (as a diver to the sur-"], ["le saito", "the wheat"], ["i le fale saito?", "in the house wheat"], ["Ua oo foi", "it came to pass also"], ["i lenei aso", "in this day"], ["ua le fua", "the fruit"], ["mai le vine,", "from the vine"], ["ma le mati,", "and the fig"], ["ma le rimoni,", "and the Rimmon"], ["ma le olive;", "and the olive"], ["e amata mai", "to began from"], ["i lenei lava aso", "in this indeed day"], ["ona ou faamanuia ia te outou", "and I blessed unto you"], [".", "."]]},
  {num:20,words:[["Ua oo mai foi", "it came to pass from also"], ["le afioga", "the a word"], ["a Ieova,", "of the LORD"], ["o le atu lua lea,", "the two"], ["ia Hakai", "to Haggai"], ["i le aso", "in the day"], ["e luafulu", "to twenty"], ["ma le fa", "and four"], ["o le masina,", "the moon"], ["o loo faapea", "saying"], ["mai,", "from"]]},
  {num:21,words:[["Fai atu ia Serupapelu", "said to to Serupapelu"], ["le alii e", "the Lord by"], ["pule ia Iuta,", "rule to Judas"], ["ia faapea atu,", "to thus"], ["Ou te luluina", "I shaken"], ["le lagi", "the heaven"], ["ma le lalolagi;", "and the earth"]]},
  {num:22,words:[["ou te fulisia", "I fulisia"], ["le nofoālii o malo;", "the throne of government"], ["ou te faaumatia foi", "I destroyed also"], ["le malosi o malo o nuu ese;", "the strong of government of nation away"], ["ou te fulisia foi kariota", "I fulisia also chariot"], ["ma ē tietie ai;", "and who ride"], ["e pauu solofanua", "to fell horse"], ["ma ē tietie ai,", "and who ride"], ["e fegaseai", "by fegaseai"], ["i latou", "them"], ["i a latou pelu.", "in but they a sword"]]},
  {num:23,words:[["Ua fetalai mai Ieova o 'au,", "said the LORD of I"], ["O lea lava aso ou te avea ai oe", "therefore indeed day I become you"], ["la'u auauna o Serupapelu", "my servant of Serupapelu"], ["le atalii o Salatielu,", "the son of Salatielu"], ["ua fetalai mai ai Ieova;", "said the LORD"], ["ou te faia oe", "I will make you"], ["e pei", "to like"], ["se faamaufaailoga;", "a faamaufaailoga"], ["auā ua ou filifilia oe,", "for I chosen you"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o a'u.", "I am"]]},
];
renderVerseSet(_hag_ch_2_Verses, 'hag-ch2-verses');

})();