(function() {
var hag_ch_1_Verses = [
  {num:1,words:[["muamua o le masina,", "first the moon"], ["na au mai ai le afioga a Ieova e le perofeta o Hakai ia Serupapelu le atalii o Salatielu,", "I from the a word but Jehovah by the prophet hakai to serupapelu the son salatielu"], ["le alii e pule ia Iuta,", "the Lord to rule to Judas"], ["atoa ma Iosua le atalii o Iosataka o le faitaulaga sili,", "and Joshua the son iosataka the priest most"], ["o loo faapea mai,", "thus from"]]},
  {num:2,words:[["Ua faapea ona fetalai mai o Ieova o 'au,", "saying and said from Jehovah I"], ["o loo faapea mai,", "thus from"], ["Ua fai mai lenei nuu,", "make from this nation"], ["E lei oo i ona aso,", "to whale's teeth oo in then day"], ["o aso e fai ai le fale o Ieova.", "day to make the house Jehovah"]]},
  {num:3,words:[["Ona au mai ai lea o le afioga a Ieova e le perofeta o Hakai,", "and I from the a word but Jehovah by the prophet hakai"], ["o loo faapea,", "thus"]]},
  {num:4,words:[["O ona po nei ea tou te nonofo ai i o outou fale ua tăpapa,", "then night this to rise (as a diver to the sur- second person plural dwelling in ye all house tăpapa"], ["a o lenei fale ua faatafunaina.", "but this house faatafunaina"]]},
  {num:5,words:[["O lenei,", "this"], ["o loo faapea ona fetalai mai o Ieova o 'au,", "thus saith the LORD I"], ["Ia outou mafaufau i o outou ala.", "to ye all think in ye all arise"]]},
  {num:6,words:[["Ua outou totō mea e tele,", "ye all totō thing to great"], ["a e itiiti mea na outou au mai ai;", "but to small thing ye all I from"], ["ua outou aai,", "ye all eat"], ["a e lei maoona ai outou;", "but to whale's teeth maoona ye all"], ["ua outou feinu,", "ye all feinu"], ["a e lei malilie ai outou;", "but to whale's teeth malilie ye all"], ["ua outou oofu,", "ye all oofu"], ["a e lei mafanafana ai outou;", "but to whale's teeth to be warm ye all"], ["o le ua galue foi i se taui,", "the work also in a a reward"], ["e fai lana taui e fafao i le taga ua pūpū solo.", "to make his a reward by fafao in the the shark's stomach pūpū to move swiftly"]]},
  {num:7,words:[["O loo faapea ona fetalai mai o Ieova o 'au,", "thus saith the LORD I"], ["Ia outou mafaufau i o outou ala.", "to ye all think in ye all arise"]]},
  {num:8,words:[["Ina o ae ia outou i le mauga,", "let but to ye all in the mountain"], ["ma outou aumaia laau,", "and ye all bring here tree"], ["ma outou faia le fale;", "and ye all made the house"], ["ona ou fiafia lea i ai,", "and I competition therein"], ["e viia ai foi au,", "by viia also I"], ["ua fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:9,words:[["Ua outou faamoemoe i mea e tele,", "ye all to expect in thing to great"], ["faauta foi,", "behold also"], ["ua itiiti;", "small"], ["ua outou aumaia i fale,", "ye all bring here in house"], ["ona a'u ulafia lea;", "and I ulafia"], ["ai se a? o loo fetalai mai ai Ieova o 'au.", "a but said from Jehovah I"], ["Auā o lo'u fale o loo ua faatafunaina lea,", "for my house faatafunaina"], ["a e taitasi outou ma momo'e atu i lona lava fale.", "but by each ye all and momo'e in his indeed house"]]},
  {num:10,words:[["O le mea lea ua taofia ai e le lagi i o outou luga,", "therefore taofia by the heaven in ye all above"], ["ina ne'i totō mai ai le sau;", "let now totō from the come"], ["o le laueleele foi ua taofi e ia ona fua.", "the ground also hold by him then fruit"]]},
  {num:11,words:[["Ua ou valaau foi i le lāmala i luga o le eleele ma luga o mauga,", "I call also in the lāmala in above the earth and above mountain"], ["ma luga o le saito,", "and above the wheat"], ["ma luga o le uaina,", "and above the wine"], ["ma luga o le suāuu,", "and above the suāuu"], ["ma luga o mea e tutupu i le eleele,", "and above thing to bring forth in the earth"], ["ma luga o tagata,", "and above man"], ["ma luga o manu vaefa,", "and above animal four-footed"], ["ma luga o galuega uma a o outou lima.", "and above work all but ye all five"]]},
  {num:12,words:[["Ona faalogo ai lea o Serupapelu le atalii o Salatielu,", "and hearken serupapelu the son salatielu"], ["ma Iosua le atalii o Iosataka le faitaulaga sili,", "and Joshua the son iosataka the priest most"], ["atoa ma e na totoe uma o le nuu,", "and by phiral of foe all the nation"], ["i le siufofoga o Ieova lo latou Atua,", "in the voice Jehovah their God"], ["ma upu a le perofeta o Hakai,", "and word but the prophet hakai"], ["e tusa ma mea na auina mai ai o ia e Ieova lo latou Atua;", "to according to and thing sent from he to Jehovah their God"], ["ua matatau foi le nuu ia Ieova.", "fear also the nation to Jehovah"]]},
  {num:13,words:[["Ona fai mai lea o Hakai le sāvali a Ieova i le feau a Ieova i le nuu,", "And he said hakai the sāvali but Jehovah in the feau but Jehovah in the nation"], ["ua faapea mai,", "saying"], ["O loo fetalai mai Ieova,", "said from Jehovah"], ["O a'u,", "I am"], ["ou te ia te outou.", "I unto ye all"]]},
  {num:14,words:[["Ona lagaina ai lea e Ieova o le loto o Serupapelu le atalii o Salatielu,", "and lagaina to Jehovah the heart serupapelu the son salatielu"], ["o le alii e pule ia Iuta,", "the Lord to rule to Judas"], ["ma le loto o Iosua le atalii o Iosataka le faitaulaga sili,", "and the heart Joshua the son iosataka the priest most"], ["ma loto o e na totoe uma o le nuu;", "and heart by phiral of foe all the nation"], ["ua latou o mai,", "them from"], ["ma latou faia le galuega o le fale o Ieova o 'au o lo latou Atua,", "and them made the work the house Jehovah I their God"]]},
  {num:15,words:[["i le aso e luafulu ma le fa,", "in the day by luafulu and the four"], ["i le onoga masina,", "in the onoga moon"], ["i le lua o tausaga o Tariu le tupu.", "in the two year tariu the grow"]]},
];
renderVerseSet(hag_ch_1_Verses, 'hag-ch1-verses');

var hag_ch_2_Verses = [
  {num:1,words:[["O le fitu o masina,", "the seven moon"], ["o le aso e lua sefulu ma le tasi i le masina,", "the day by two ten and the one in the moon"], ["na au mai ai le afioga a Ieova e le perofeta o Hakai,", "I from the a word but Jehovah by the prophet hakai"], ["o loo faapea mai,", "thus from"]]},
  {num:2,words:[["Ina e fai atu lava ia Serupapelu le atalii o Salatielu,", "let to make indeed to serupapelu the son salatielu"], ["le alii e pule ia Iuta,", "the Lord to rule to Judas"], ["ma Iosua le atalii o Iosataka le faitaulaga sili,", "and Joshua the son iosataka the priest most"], ["atoa ma e ua totoe o le nuu,", "and by phiral of foe the nation"], ["ia faapea atu.", "to thus"]]},
  {num:3,words:[["O ai ea so outou ua toe,", "to rise (as a diver to the sur- so ye all again"], ["o le na iloa lenei fale i lona muai matagofie? Pe se a lo outou vaai nei i ai? E le ua peiseai ua leai ea i o outou manatu,", "the known this house in his first beautiful or a but your to look at this therein by the as if no to rise (as a diver to the sur- in ye all thought"], ["pe a faatusa ma lena?", "or but image and that"]]},
  {num:4,words:[["A o lenei,", "but this"], ["ia e faamalosi o oe o Serupapelu,", "to by faamalosi you serupapelu"], ["ua fetalai mai ai Ieova;", "said from Jehovah"], ["ma ia e faamalosi o oe o Iosua le atalii o Iosataka le faitaulaga sili;", "and to by faamalosi you Joshua the son iosataka the priest most"], ["ma ia faamalolosi outou tagata uma o le nuu,", "and to faamalolosi ye all man all the nation"], ["ua fetalai mai ai Ieova,", "said from Jehovah"], ["ma ia outou galulue;", "and to ye all galulue"], ["auā o a'u,", "for I am"], ["ou te ia te outou,", "I unto ye all"], ["ua fetalai mai ai Ieova o 'au.", "said from Jehovah I"]]},
  {num:5,words:[["O le feagaiga na ou osia ma outou ina ua o mai outou nai Aikupito,", "the covenant I osia and ye all let from ye all from Egypt"], ["atoa ma lo'u Agaga o loo tumau ia te outou;", "and my spirit endure unto ye all"], ["aua le fefefe outou.", "for the fefefe ye all"]]},
  {num:6,words:[["Auā o loo faapea ona fetalai mai o Ieova o 'au,", "for thus then said from Jehovah I"], ["E toe tasi,", "to again one"], ["e toe itiiti lava,", "to again small indeed"], ["ona ou luluina ai lea o le lagi,", "and I luluina the heaven"], ["ma le lalolagi,", "and the earth"], ["ma le sami,", "and the sea"], ["atoa ma le eleele matutu.", "and the dry land"]]},
  {num:7,words:[["Ou te luluina foi nuu uma;", "I luluina also nation all"], ["ona oo mai ai lea o mea ua manaomia e nuu uma;", "and oo from thing manaomia to nation all"], ["ou te faatumuina foi lenei fale i le pupula,", "I faatumuina also this house in the brightness"], ["ua fetalai mai ai Ieova o 'au.", "said from Jehovah I"]]},
  {num:8,words:[["O loo ia te au le ario,", "unto I the silver"], ["o loo ia te au foi le auro,", "unto I also the gold"], ["ua fetalai mai ai Ieova o 'au.", "said from Jehovah I"]]},
  {num:9,words:[["E sili le mamalu o lenei fale ua mulimuli i le na muamua,", "to most the glory this house follow after in the first"], ["ua fetalai mai ai Ieova o 'au;", "said from Jehovah I"], ["ou te avatu foi le manuia i le mea nei,", "I give away also the peace in the thing this"], ["ua fetalai mai ai Ieova o 'au.", "said from Jehovah I"]]},
  {num:10,words:[["O le aso e luafulu ma le fa,", "the day by luafulu and the four"], ["o le ivaga masina o le lua o tausaga o Tariu,", "the ivaga moon the two year tariu"], ["na au mai ai le afioga a Ieova e le perofeta o Hakai,", "I from the a word but Jehovah by the prophet hakai"], ["o loo faapea mai,", "thus from"]]},
  {num:11,words:[["Ua faapea ona fetalai mai o Ieova o 'au,", "saying and said from Jehovah I"], ["Fesili ia i faitaulaga i le tulafono,", "to question to in priest in the law"], ["ia faapea,", "to thus"]]},
  {num:12,words:[["Afai e ave e se tasi se tufaaga paia i lona pito ofu,", "if to take by a one a tufaaga holy in his pito garment"], ["ona pai atu lea o lona pito ofu i se areto,", "and pie his pito garment in a bread"], ["po o se mea ua tunua,", "night a thing tunua"], ["po o se uaina,", "night a wine"], ["po o se suāuu,", "night a suāuu"], ["po o se tasi mea e 'aina,", "night a one thing to edible"], ["pe faapaiaina ai ea ia mea? Ona tali mai lea o faitaulaga,", "or faapaiaina to rise (as a diver to the sur- to thing then respond from priest"], ["ua faapea mai,", "saying"], ["E leai.", "there is not"]]},
  {num:13,words:[["Ona fai atu lea o Hakai,", "And he said hakai"], ["Afai ua pai atu le ua leaga i le tagata oti i se mea o ia mea,", "if pie the evil in the man die in a thing he thing"], ["pe leaga ai ea ia mea? Ona tali mai lea o faitaulaga,", "or evil to rise (as a diver to the sur- to thing then respond from priest"], ["ua faapea,", "saying"], ["E leaga ai.", "to evil"]]},
  {num:14,words:[["Ona tali atu lea o Hakai,", "and respond hakai"], ["ua faapea atu,", "saying"], ["Ua faapena nei tagata,", "faapena this man"], ["ua faapena foi lenei nuu i o'u luma,", "faapena also this nation in I before"], ["o loo fetalai mai ai Ieova;", "said from Jehovah"], ["ua faapena foi mea uma ua faia e o latou lima,", "faapena also thing all made by them five"], ["o mea foi ua latou avatua iina ua leaga lava ia.", "thing also them given away there evil indeed to"]]},
  {num:15,words:[["O lenei foi,", "this also"], ["ia mafaufau lava outou,", "to think indeed ye all"], ["ia afua mai i lenei lava aso e oo i aso ua tuanai,", "to afua from in this indeed day by oo in day tuanai"], ["a o lei faaeetia se maa i luga o le tasi maa i le malumalu o Ieova;", "but whale's teeth faaeetia a stone in above the one stone in the temple Jehovah"]]},
  {num:16,words:[["e afua mai i ia ona po,", "by afua from in to then night"], ["na alu ane ai le tagata i le faaputugāsaito,", "go the man in the faaputugāsaito"], ["o fuataga e luafulu,", "fuataga by luafulu"], ["a ua i ai na o le sefulu;", "but therein the ten"], ["na alu ane le tagata i le tuugāuaina e asu ai tumu e limagafulu ai le tuugāuaina,", "go the man in the tuugāuaina by asu fill by limagafulu the tuugāuaina"], ["a ua i ai na o le luafulu.", "but therein the luafulu"]]},
  {num:17,words:[["Na ou taia outou i le mamae,", "I taia ye all in the mamae"], ["ma le polopologa,", "and the polopologa"], ["ma le uato'a,", "and the uato'a"], ["i galuega uma a outou lima;", "in work all but ye all five"], ["a ua outou le foi mai ia te au,", "but ye all the also from unto I"], ["ua fetalai mai ai Ieova.", "said from Jehovah"]]},
  {num:18,words:[["Se'i mafaufau lava outou,", "a flower put into the hair or think indeed ye all"], ["ia afua mai i lenei lava aso,", "to afua from in this indeed day"], ["e oo i aso ua tuanai,", "it shall come to pass in day tuanai"], ["o le aso e luafulu ma le fa i le ivaga masina ,", "the day by luafulu and the four in the ivaga moon"], ["talu le aso na faavaeina ai le malumalu o Ieova;", "since the day faavaeina the temple Jehovah"], ["ina outou mafaufau ia.", "let ye all think to"]]},
  {num:19,words:[["E i ai pea ea le saito i le fale saito? Ua oo foi i lenei aso ua le fua mai le vine,", "by therein continually to rise (as a diver to the sur- the wheat in the house wheat oo also in this day the fruit from the vine"], ["ma le mati,", "and the mati"], ["ma le rimoni,", "and the rimoni"], ["ma le olive;", "and the olive"], ["e amata mai i lenei lava aso ona ou faamanuia ia te outou .", "to began from in this indeed day then I blessed unto ye all"]]},
  {num:20,words:[["Ua oo mai foi le afioga a Ieova,", "it came to pass from also the a word but Jehovah"], ["o le atu lua lea,", "the two"], ["ia Hakai i le aso e luafulu ma le fa o le masina,", "to hakai in the day by luafulu and the four the moon"], ["o loo faapea mai,", "thus from"]]},
  {num:21,words:[["Fai atu ia Serupapelu le alii e pule ia Iuta,", "said to to serupapelu the Lord to rule to Judas"], ["ia faapea atu,", "to thus"], ["Ou te luluina le lagi ma le lalolagi;", "I luluina the heaven and the earth"]]},
  {num:22,words:[["ou te fulisia le nofoālii o malo;", "I fulisia the nofoālii government"], ["ou te faaumatia foi le malosi o malo o nuu ese;", "I destroy also the strong government nation away"], ["ou te fulisia foi kariota ma ē tietie ai;", "I fulisia also kariota and who tietie"], ["e pauu solofanua ma ē tietie ai,", "to fell horse and who tietie"], ["e fegaseai i latou i a latou pelu.", "by fegaseai them in but them a sword"]]},
  {num:23,words:[["Ua fetalai mai Ieova o 'au,", "said from Jehovah I"], ["O lea lava aso ou te avea ai oe la'u auauna o Serupapelu le atalii o Salatielu,", "therefore indeed day I become you my servant serupapelu the son salatielu"], ["ua fetalai mai ai Ieova;", "said from Jehovah"], ["ou te faia oe e pei se faamaufaailoga;", "I made you to to be broken a faamaufaailoga"], ["auā ua ou filifilia oe,", "for I chosen you"], ["ua fetalai mai ai Ieova o a'u.", "said from Jehovah I am"]]},
];
renderVerseSet(hag_ch_2_Verses, 'hag-ch2-verses');

})();