(function() {
var _hos_ch_1_Verses = [
  {num:1,words:[["O le afioga", "the word"], ["a Ieova", "of the LORD"], ["na oo atu ia", "arrived to"], ["Hosea", "Hosea"], ["le atali'i o Peri,", "the son of Peri"], ["i ona po", "in his nights"], ["o Usia,", "Usia"], ["Iotama,", "Iotama"], ["Aasa,", "Asa"], ["ma Esekia,", "and Hezekiah"], ["o tupu o Iuta;", "king of Judas"], ["o", "o"], ["ona po foi", "and night also"], ["o Ierepoamo", "Jeroboam"], ["le atali'i o Ioasa", "the son of Joash"], ["le tupu o Isaraelu.", "the king of Israel"]]},
  {num:2,words:[["O le amataga", "the beginning"], ["o le afioga", "the word"], ["a Ieova ia", "of the LORD to"], ["Hosea.", "Hosea"], ["Ua fetalai mai", "said"], ["Ieova ia Hosea,", "the LORD to Hosea"], ["Alu ia oe,", "go to you"], ["ia e fai", "to to make"], ["avā", "wife"], ["i le fafine talitane,", "in the women harlot"], ["ma ia fai māu", "and to make māu"], ["le fānau", "the born"], ["a le faitaaga,", "but the fornication"], ["auā", "for"], ["ua matuā faitaaga lava", "great fornication very"], ["le nuu,", "the nation"], ["ua o ese ia", "of away to"], ["Ieova.", "the LORD"]]},
  {num:3,words:[["Ona alu lea", "And he went"], ["o ia", "he"], ["ua fai mana", "made to get"], ["avā o Komeri", "wife of Komeri"], ["le afafine o Tipelaima,", "the daughter of Tipelaima"], ["ua to ai", "to plant"], ["foi o ia,", "also he"], ["ua fānau mai ai", "born"], ["lona atali'i.", "his son"]]},
  {num:4,words:[["Ua fetalai mai foi", "said also"], ["Ieova ia te ia,", "the LORD to him"], ["Ia e fa'aigoa ia te ia,", "to to called to him"], ["o Isereelu;", "Israelite"], ["auā", "for"], ["e toe itiiti,", "to again small"], ["ona ou taui atu ai lea", "and I a reward then then"], ["o le toto", "the blood"], ["o Isereelu", "Israelite"], ["i le 'āiga", "in the family"], ["o Ieu,", "Jehu"], ["ou te fa'aumatia foi", "I will destroyed also"], ["le mālō", "the kingdom"], ["o le 'āiga", "the family"], ["o Isaraelu.", "Israel"]]},
  {num:5,words:[["O lea aso ou te gauia ai", "therefore day I will was to break"], ["le aufana", "the bow"], ["a Isaraelu", "of Israel"], ["i le vanu", "in the valley"], ["o Isereelu.", "Israelite"]]},
  {num:6,words:[["Ua toe to foi", "again to plant also"], ["o ia,", "he"], ["ua fānau ai", "born"], ["le tama teine;", "the daughter"], ["ona fetalai mai lea", "and said"], ["o Ieova ia te ia,", "the LORD to him"], ["Ia e fa'aigoa ia te ia,", "to to called to him"], ["o Loruama;", "Loruama"], ["auā ou te", "for I will"], ["le toe alofa atu", "the again love"], ["i le 'āiga", "in the family"], ["o Isaraelu,", "Israel"], ["a", "but"], ["e ou te matuā aveesea", "to I will great removed away"], ["i lātou.", "them"]]},
  {num:7,words:[["A", "but"], ["o le 'āiga", "the family"], ["o Iuta,", "Judas"], ["ou te alofa", "I will love"], ["i ai,", "therein"], ["ou te fa'aola", "I will save"], ["ia te i lātou", "unto them"], ["ona o Ieova lo lātou Atua;", "because of the LORD their God"], ["ou te", "I will"], ["le fa'aola ia te", "the save unto"], ["i lātou", "them"], ["i le aufana,", "in the bow"], ["po", "night"], ["o le pelu,", "the sword"], ["po", "night"], ["o le taua,", "the war"], ["po o solofanua,", "night of horse"], ["po o 'au", "night of troops"], ["e tietie", "to ride"], ["i solofanua.", "in horse"]]},
  {num:8,words:[["Ua ia fa'ate'a", "to made depart"], ["Loruama", "Loruama"], ["ma le susu;", "and the milk"], ["ona to ai lea", "and to plant then then"], ["o ia,", "he"], ["ua fānau mai ai", "born"], ["le tama tāne.", "the son"]]},
  {num:9,words:[["Ona fa'apea mai ai lea", "and thus from then then"], ["a le Atua ,", "of God"], ["Ia e fa'aigoa ia te ia,", "to to called to him"], ["o Loama;", "Loama"], ["auā", "for"], ["e le so'u nuu outou,", "by the so'u nation you all"], ["e le so outou", "by the so you all"], ["Atua foi", "God also"], ["a'u.", "me"]]},
  {num:10,words:[["A", "but"], ["o le faitau aofai", "the to count number"], ["o le fanauga", "the children"], ["a Isaraelu", "of Israel"], ["e pei o le oneone", "like the sand"], ["o le sami", "Sea"], ["ia,", "to"], ["e le mafuatia,", "by the mafuatia"], ["e le mafaitaulia;", "by the mafaitaulia"], ["o", "o"], ["i le mea foi", "in the thing also"], ["na fa'apeaina atu ai", "thus"], ["ia te i lātou,", "unto them"], ["E le so'u nuu outou,", "by the so'u nation you all"], ["e iu", "to become of"], ["ina fa'apeaina atu ai", "so that thus"], ["ia te i lātou,", "unto them"], ["O atali'i", "sons"], ["o le Atua soifua outou", "of God life you all"], [".", "."]]},
  {num:11,words:[["Ona fa'apotopotoina fa'atasi ai lea", "and gathered together together then then"], ["o le fanauga", "the children"], ["a Iuta,", "of Judas"], ["atoa ma le fanauga", "and the children"], ["a Isaraelu,", "of Israel"], ["lātou te tofia foi", "they will was chosen also"], ["le ta'ita'i", "the lead"], ["e toatasi", "to one One"], ["mo", "for"], ["i lātou,", "them"], ["lātou te o ae foi", "they will went up also"], ["ma le nuu;", "and the nation"], ["auā", "for"], ["e sili", "to most"], ["le aso o Isereelu.", "the day of Israelite"]]},
];
renderVerseSet(_hos_ch_1_Verses, 'hos-ch1-verses');

var _hos_ch_2_Verses = [
  {num:1,words:[["-2 Ia outou", "-2 to you all"], ["fa'apea atu", "thus"], ["i o outou", "in of you all"], ["uso,", "brother"], ["Ama e;", "ignorant by"], ["ia fa'apea atu foi", "to thus also"], ["i o outou", "in of you all"], ["tuafafine,", "sister"], ["Ruama e.", "Ruama by"], ["Ia outou finau atu i lo", "to you all contend toward than"], ["outou tinā,", "you all mother"], ["ina finafinau atu", "so that finafinau"], ["ia;", "to"], ["auā", "for"], ["e le", "by the"], ["o la'u avā", "my wife"], ["ia,", "to"], ["e le", "by the"], ["o lana tāne foi", "his man also"], ["a'u;", "me"], ["ina lafoai ia", "so that forsaken to"], ["e ia ana faitaaga ai", "by him his fornication"], ["ia te ia,", "to him"], ["ma ana mulilua foi", "and his whoring also"], ["ai", "ai"], ["le va", "the expanse"], ["o", "o"], ["ona susu;", "and milk"]]},
  {num:2,words:[["Ona ou fa'atauina ai lea", "and I bought then then"], ["o ia ma'u", "he opinion"], ["i tupe", "in St. Thomas bean"], ["e sefulu", "by ten"], ["ma le lima,", "and five"], ["ma le omera", "and the omera"], ["o karite,", "barley"], ["ma le leteka", "and the leteka"], ["o karite.", "barley"]]},
  {num:3,words:[["ne'i ou talaeseina", "now I talaeseina"], ["ona ofu,", "and garment"], ["ma tuu atu", "and placed"], ["ia te ia", "to him"], ["pei ona", "as/just as"], ["i ai", "therein"], ["i le aso", "in the day"], ["na fānau mai ai", "was born"], ["o ia,", "he"], ["e avea foi", "to become also"], ["o ia pei", "he like"], ["o se vao,", "a vegetation"], ["ma avea foi", "and become also"], ["pei o se nuu naumati,", "like a nation dry"], ["ma ou fa'aumatia", "and I destroyed"], ["o ia", "he"], ["i le fia inu.", "in the want to do something drink"]]},
  {num:4,words:[["Ou te", "I will"], ["le alofa atu", "the love"], ["i lana fānau,", "in his born"], ["auā", "for"], ["o le fānau", "the born"], ["a le faitaaga", "but the fornication"], ["i lātou.", "them"]]},
  {num:5,words:[["Auā", "for"], ["ua faitaaga lo lātou", "fornication their"], ["tinā,", "mother"], ["ua agavale lava", "agavale very"], ["le", "the"], ["na fanaua", "born"], ["i lātou;", "them"], ["auā", "for"], ["na ia fa'apea mai,", "to thus from"], ["Ou te mulimuli atu", "I will follow after"], ["i", "in"], ["e o mananao", "by of desire"], ["ia te au,", "unto me"], ["o", "o"], ["e o au mai a'u", "by I am from me"], ["mea", "thing"], ["e a'i,", "to"], ["ma o'u vai,", "and my water"], ["ma a'u fulufulu mamoe,", "and me hairy sheep"], ["ma a'u lino,", "and me linen"], ["ma a'u suāuu,", "and me oil"], ["ma a'u mea", "and me thing"], ["e inu.", "to drink"]]},
  {num:6,words:[["O le mea lea,", "therefore"], ["fa'auta,", "behold"], ["ou te pupuni ai", "I will shut"], ["lou ala", "your way"], ["i lā'au tuitui,", "in tree prickly"], ["ou te siosioina foi", "I will surrounded also"], ["o ia", "he"], ["i le pa,", "in the wall"], ["ia le iloa", "to the know"], ["e ia", "by him"], ["ona ala.", "and way"]]},
  {num:7,words:[["E mulimuli atu", "to follow after"], ["lava o ia", "very he"], ["i", "in"], ["e o mananao", "by of desire"], ["ia te ia,", "to him"], ["a", "but"], ["e le maua atu", "shall not received"], ["i lātou e", "them by"], ["ia;", "to"], ["e sailiili o ia ia te", "to search he unto"], ["i lātou,", "them"], ["a", "but"], ["e le iloa;", "shall not know"], ["ona fa'apea mai ai lea", "and thus from then then"], ["o ia,", "he"], ["Ou te alu,", "I will go"], ["ou te toe foi", "I will returned again"], ["i la'u tāne muamua,", "in my man first the beginning"], ["auā", "for"], ["sa sili", "most"], ["lo'u manuia anamua,", "my peace ancient"], ["i lo'u manuia", "in my peace"], ["i nei", "in this"], ["ona po.", "and night"]]},
  {num:8,words:[["Auā", "for"], ["na", "na"], ["le iloa e", "the know by"], ["ia,", "to"], ["o a'u lava", "I am very"], ["sa foaiina atu ia te ia", "given to him"], ["o saito,", "wheat"], ["ma uaina,", "and wine"], ["ma suāuu;", "and oil"], ["na a'u fa'ateleina foi", "me multiplied also"], ["ana ario,", "his silver"], ["ma ana auro", "and his gold"], ["na lātou saunia", "they prepared"], ["mo Paala.", "for a small fly-fishhook"]]},
  {num:9,words:[["O le mea lea", "therefore"], ["ou te toe foi", "I will returned again"], ["ai,", "ai,"], ["ma ave ese", "and take away"], ["la'u saito", "my wheat"], ["i ona lava aso,", "in then very day"], ["ma la'u uaina", "and my wine"], ["i ona lava po;", "in then very night"], ["ou te aveesea foi", "I will removed away also"], ["a'u fulufulu mamoe,", "me hairy sheep"], ["ma a'u lino,", "and me linen"], ["sa tuuina atu", "given / delivered"], ["e ufiufi a'i", "to covering"], ["lona", "his"], ["le lavalavā.", "the naked"]]},
  {num:10,words:[["O lenei,", "now"], ["ou te fa'aali", "I will revealed"], ["lana amio ulavale", "his conduct mischievous"], ["i luma o", "before"], ["e o mananao", "by of desire"], ["ia te ia,", "to him"], ["e leai foi", "there is not also"], ["se tasi", "a one"], ["na te laveaiina", "he delivered"], ["o ia ai", "he"], ["lo'u lima.", "my hand"]]},
  {num:11,words:[["Ou te fa'aumatia foi", "I will destroyed also"], ["lona fiafia uma lava,", "his pleased all very"], ["o ana tausamiga,", "his feast"], ["ma", "and"], ["ona masina fa'atoa vaaia,", "and month just now seen"], ["ma", "and"], ["ona sapati,", "and Sabbath"], ["atoa ma", "and"], ["ona nuu uma.", "and nation all"]]},
  {num:12,words:[["Ou te fa'aumatia", "I will destroyed"], ["ona vine,", "and vine"], ["ma", "and"], ["ona mati,", "and fig"], ["na ia fa'apea mai ai,", "to thus from"], ["O o'u taui", "my a reward"], ["lava ia", "very to"], ["na au mai ia te au", "brought unto me"], ["e", "by"], ["i lātou", "them"], ["ua mananao ia te au;", "desired unto me"], ["e avea foi", "to become also"], ["i lātou ia te au", "them unto me"], ["ma vao mātua,", "and vegetation great"], ["e 'aina", "to edible"], ["i lātou", "them"], ["e manu feai.", "to wild beasts"]]},
  {num:13,words:[["Ua fetalai mai", "said"], ["Ieova,", "the LORD"], ["Ou te taui atu", "I will a reward"], ["ia te ia", "to him"], ["ona", "and"], ["o", "o"], ["ona po o Paala,", "and night of a small fly-fishhook"], ["na ia fa'amu ai", "to burned incense"], ["mea manogi ia te", "thing fragrant unto"], ["i lātou;", "them"], ["na ia tifitifi foi", "to to adorn also"], ["ia te ia", "to him"], ["i ona mama,", "in then clean"], ["ma", "and"], ["ona teuga,", "and store"], ["na ia mulimuli atu foi", "to followed after also"], ["i", "in"], ["e", "by"], ["na mananao ia te ia,", "desired to him"], ["a", "but"], ["ua fa'agalogalo lava ia te au.", "to forget very unto me"]]},
  {num:14,words:[["A", "but"], ["e peitai a'u", "to however me"], ["fa'auta,", "behold"], ["ou te fa'aoleole", "I will make entreat"], ["ia te ia,", "to him"], ["ma ta'ita'i ia te ia", "and lead to him"], ["i le vao,", "in the wilderness"], ["ou te fa'amafanafana", "I will to hearten"], ["ia te ia.", "to him"]]},
  {num:15,words:[["Ou te tuuina atu foi", "I will give also"], ["ia te ia", "to him"], ["ana tovine", "his vineyard"], ["i lea", "in"], ["mea,", "thing"], ["ma le vanu", "and the valley"], ["o Akori", "Akori"], ["e fai ma faitotoa", "to be door"], ["e fa'amoemoe ai;", "to hope"], ["e pese foi", "to a song also"], ["o ia", "he"], ["i ai,", "therein"], ["fa'apei", "like"], ["ona fai", "and make"], ["i ona po", "in his nights"], ["ina o teine muli", "so that of girl muli"], ["o ia,", "he"], ["pei o aso foi", "like of day also"], ["na sau ai", "came"], ["o ia", "he"], ["i le nuu", "in the land"], ["o Aikupito.", "Egypt"]]},
  {num:16,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["O le aso", "the day"], ["lava lea", "very"], ["e oo ai", "it shall come to pass"], ["ona", "and"], ["e fa'aaigoa ia te au,", "by faaaigoa unto me"], ["O Ise;", "Ise"], ["e te", "by"], ["le toe fa'aigoa", "the again called"], ["ia te au,", "unto me"], ["O Paale.", "Paale"]]},
  {num:17,words:[["Auā ou te aveesea", "for I will removed away"], ["i lona gutu", "in his mouth"], ["o igoa o Paala,", "name of a small fly-fishhook"], ["e le toe ta'ua", "shall not again us two"], ["lava", "very"], ["i lātou", "them"], ["i o lātou", "in of they"], ["igoa.", "name"]]},
  {num:18,words:[["O le aso foi", "the day also"], ["lea mātou te osi ai", "we made"], ["ma", "and"], ["i lātou", "them"], ["le feagaiga", "the covenant"], ["ma manu feai,", "and wild beasts"], ["ma manu felelei,", "and birds of the air"], ["ma mea fetolofi", "and creeping things"], ["i le eleele;", "the ground"], ["ou te gausia foi", "I will gausia also"], ["le aufana", "the bow"], ["ma le pelu,", "and the sword"], ["ma le taua ai", "and the war"], ["le nuu,", "the nation"], ["o a'u", "I am"], ["e taooto ai", "to lie down"], ["i lātou", "them"], ["ma le filemu.", "and the peace"]]},
  {num:19,words:[["Tā te osi", "struck made"], ["sa tā feagaiga", "struck covenant"], ["ma a'u", "and me"], ["e fa'avavau;", "forever/everlasting"], ["tā te osi", "struck made"], ["sa tā feagaiga", "struck covenant"], ["ma a'u", "and me"], ["i le amiotonu,", "in the righteous"], ["ma le fa'amasinoga,", "and the judgment"], ["ma le agalelei,", "with kindness"], ["ma le alofa.", "and the love"]]},
  {num:20,words:[["Tā te osi", "struck made"], ["sa tā feagaiga", "struck covenant"], ["ma a'u", "and me"], ["ma le fa'amaoni;", "and the faithful"], ["e te iloa foi", "by know also"], ["Ieova.", "the LORD"]]},
  {num:21,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["O lea aso,", "therefore day"], ["ou te tali atu ai,", "I will respond"], ["ou te tali atu", "I will respond"], ["i le lagi,", "in heaven"], ["o ia foi", "he also"], ["na te tali atu", "he responded"], ["i le lalolagi.", "on the earth"]]},
  {num:22,words:[["E tali atu foi", "to respond also"], ["le lalolagi", "the earth"], ["i le saito,", "in the wheat"], ["ma le uaina,", "and the wine"], ["ma le suāuu;", "and the oil"], ["o", "o"], ["i lātou foi", "them also"], ["lātou te tali atu", "they will respond"], ["ia Isereelu.", "to Israelite"]]},
  {num:23,words:[["Ou te totōina", "I will planted"], ["o ia", "he"], ["i le eleele", "the ground"], ["e fai mo'u;", "to make many"], ["ou te alofa foi", "I will love also"], ["i le", "in the"], ["sa", "sa"], ["le alofagia;", "the favored"], ["ou te fa'apea atu foi", "I will thus also"], ["i le", "in the"], ["ua", "ua"], ["le so'u nuu,", "the so'u nation"], ["O lo'u nuu oe;", "my nation you"], ["ona lātou fa'apea mai ai lea,", "and they thus from then then"], ["O lo mātou Atua.", "our God"]]},
];
renderVerseSet(_hos_ch_2_Verses, 'hos-ch2-verses');

var _hos_ch_3_Verses = [
  {num:1,words:[["Ua fetalai mai", "said"], ["Ieova ia te au,", "the LORD unto me"], ["Ia e toe", "to to again"], ["alu,", "go"], ["ia e loto atu i se", "to to heart in a"], ["fafine", "women"], ["o le", "the"], ["ua loto", "heart"], ["i ai", "therein"], ["lana uo,", "his uo"], ["a", "but"], ["o le fafine mulilua", "the women whoring"], ["ia,", "to"], ["e pei ona", "as"], ["alofa o Ieova", "love the LORD"], ["i le fanauga", "in the children"], ["a Isaraelu o", "of Israel of"], ["e fa'asagasaga", "to facing"], ["i atua ese,", "in foreign gods"], ["ma mananao", "and desire"], ["i ipu uaina.", "in cup wine"]]},
  {num:2,words:[["Ona ou fa'atauina ai lea", "and I bought then then"], ["o ia ma'u", "he opinion"], ["i tupe", "in St. Thomas bean"], ["e sefulu", "by ten"], ["ma le lima,", "and five"], ["ma le omera", "and the omera"], ["o karite,", "barley"], ["ma le leteka", "and the leteka"], ["o karite.", "barley"]]},
  {num:3,words:[["Na a'u fai atu foi", "me said to also"], ["ia te ia,", "to him"], ["E te nofo fa'atali", "by dwell wait"], ["mai ia te au", "from me"], ["i aso e tele,", "in day to great"], ["aua", "for"], ["e te faitaaga,", "by fornication"], ["aua", "for"], ["e te nofo", "by dwell"], ["i se tāne;", "in a man"], ["ou te nofo fa'atali foi", "I will dwell wait also"], ["ia te oe.", "unto you"]]},
  {num:4,words:[["Auā e tele aso", "for to great day"], ["e nonofo ai", "to dwell"], ["le fanauga", "the children"], ["a Isaraelu,", "of Israel"], ["e leai se tupu,", "there is no king"], ["e leai se ali'i,", "there is no Lord"], ["e leai se taulaga,", "there is no offering"], ["e leai se fata faitaulaga,", "there is no altar"], ["e leai foi", "there is not also"], ["se efota po", "a ephod night"], ["o se tupua.", "a pillar"]]},
  {num:5,words:[["E mulimuli ane,", "to follow after"], ["e toe foi mai le fanauga", "to returned the children"], ["a Isaraelu,", "of Israel"], ["lātou te saili", "they will seek"], ["ia Ieova lo lātou", "to the LORD their"], ["Atua,", "God"], ["ma Tavita lo lātou tupu;", "and David their king"], ["lātou te matatau foi", "they will dismayed also"], ["ia Ieova", "to the LORD"], ["ma lona agalelei", "and his kindness"], ["i ona po", "in his nights"], ["e gata ai.", "to a snake"]]},
];
renderVerseSet(_hos_ch_3_Verses, 'hos-ch3-verses');

var _hos_ch_4_Verses = [
  {num:1,words:[["Le fanauga", "the children"], ["a Isaraelu e,", "of Israel by"], ["ia outou fa'alogologo", "to you all listen"], ["mai", "from"], ["i le afioga", "the word"], ["a Ieova;", "of the LORD"], ["auā o loo", "for is"], ["ia Ieova", "to the LORD"], ["le finauga", "the disputation"], ["ma", "and"], ["e o nonofo", "by of dwelling"], ["i le nuu;", "in the land"], ["auā", "for"], ["e leai se fa'amaoni,", "there is no faithful"], ["e leai se alofa,", "there is no love"], ["e leai foi", "there is not also"], ["se", "a"], ["na te iloa", "he knew"], ["le Atua", "God"], ["i le nuu.", "in the land"]]},
  {num:2,words:[["O loo o tauto,", "is to take an oath"], ["ma tala pepelo,", "and side false"], ["ma fasioti tagata,", "and killed man"], ["ma gaoi,", "and to steal"], ["ma mulilua,", "and whoring"], ["ua lātou fa'asaua lava,", "they cruel very"], ["ua fepaia'i toto.", "pie one another blood"]]},
  {num:3,words:[["O le mea lea", "therefore"], ["e fa'anoanoa ai", "shall mourn"], ["le nuu,", "the nation"], ["e tauāu", "by tauāu"], ["ina vaivai o", "so that weak of"], ["i lātou uma", "them all"], ["o", "o"], ["e nonofo ai;", "to dwell"], ["atoa ma manu vaefa,", "and beasts"], ["ma manu felelei,", "and birds of the air"], ["e mavae atu foi", "to passed also"], ["lava o i'a", "very of fish"], ["o le sami.", "Sea"]]},
  {num:4,words:[["A", "but"], ["e aua ne'i", "to for now"], ["i ai", "therein"], ["se tagata", "a man"], ["e finau atu,", "to contend toward"], ["ma aoai atu", "and chastise"], ["i se tasi tagata;", "in a one man"], ["auā", "for"], ["o lou nuu", "your nation"], ["ua pei o", "like of"], ["e fefinauai", "to disputing"], ["ma le ositaulaga.", "and the high priest"]]},
  {num:5,words:[["O lea", "therefore"], ["e te paū ai", "by fall"], ["i le ao,", "in the cloud"], ["e pauu foi", "to fell also"], ["le perofeta fa'atasi ma oe", "the prophet with you"], ["i le po;", "at night"], ["ou te fasioti foi", "I will killed also"], ["lou tinā.", "your mother"]]},
  {num:6,words:[["Ua fa'aumatia", "are destroyed"], ["lo'u nuu", "my nation"], ["ina ua leai se poto;", "when no a wise"], ["o oe foi", "you also"], ["na e tetee atu", "you to refuse"], ["i le poto,", "in the wise"], ["o le mea lea", "therefore"], ["ou te tetee atu ai", "I will to refuse"], ["ia te oe,", "unto you"], ["e le fai oe", "shall not make you"], ["ma ositaulaga ia te au;", "and high priest unto me"], ["ua e fa'agalogalo", "you to forget"], ["le tulafono", "the law"], ["a lou Atua,", "but your God"], ["o a'u foi,", "I am also"], ["ou te fa'agalogalo", "I will to forget"], ["i lau fānau.", "in your born"]]},
  {num:7,words:[["E pei ona", "as"], ["fa'atoateleina o", "make many of"], ["i lātou,", "them"], ["ua fa'apea ona", "saying and"], ["agasala mai o", "sin from of"], ["i lātou ia te au;", "them unto me"], ["ou te liliu", "I will turn"], ["i le mā lo lātou mamalu.", "in the and their glory"]]},
  {num:8,words:[["Ua lātou aai", "they cities"], ["le agasala", "sin"], ["a lo'u nuu,", "but my nation"], ["ma", "and"], ["ua lātou naunau", "they desired"], ["i lo lātou leaga.", "than they evil"]]},
  {num:9,words:[["E oo ina gatusa", "it shall come to pass so that equal"], ["lava", "very"], ["o le nuu", "the nation"], ["ma le ositaulaga;", "and the high priest"], ["ou te taui atu foi", "I will a reward also"], ["ia te i lātou", "unto them"], ["a lātou amio,", "their conduct"], ["ou te taui foi", "I will a reward also"], ["ia te i lātou", "unto them"], ["a lātou mea", "their thing"], ["ua fai.", "made"]]},
  {num:10,words:[["Auā lātou te aai,", "for they will cities"], ["a", "but"], ["e le maoona;", "by the maoona"], ["e faitaaga", "to fornication"], ["i lātou,", "them"], ["a", "but"], ["e le fa'atoateleina;", "shall not make many"], ["auā", "for"], ["ua", "ua"], ["le toe usiusitai", "the again obeyed"], ["i lātou ia", "them to"], ["Ieova.", "the LORD"]]},
  {num:11,words:[["O le faitaaga,", "the fornication"], ["ma le uaina,", "and the wine"], ["ma le uaina fou", "and the wine new"], ["e aveeseina ai", "to carried away"], ["le loto.", "the heart"]]},
  {num:12,words:[["O lo'u nuu", "my nation"], ["ua lātou fesili", "they asked"], ["i lo lātou lā'au;", "than they tree"], ["ua fa'asino mai ai", "declared from"], ["lo lātou tootoo", "their staff"], ["ia te i lātou;", "unto them"], ["auā", "for"], ["o le fia faitaaga", "the want to do something fornication"], ["ua fa'aseseina ai", "deceived astray"], ["i lātou ,", "them"], ["ma", "and"], ["ua lātou", "they"], ["o ese", "away"], ["nai lo lātou Atua e", "more than they God by"], ["faitaaga ai.", "fornication"]]},
  {num:13,words:[["Ua lātou faitaulaga", "they priest"], ["i tumutumu o mauga,", "in top of mountain"], ["ma fa'amu mea manogi", "and burn incense thing fragrant"], ["i mea maupuepue,", "in thing maupuepue"], ["ma lalo ifo", "and under down"], ["o aluna,", "aluna"], ["ma lipeno,", "and lipeno"], ["ma tapeneto,", "and tapeneto"], ["auā", "for"], ["ua lelei lo lātou", "that it was good their"], ["paolo;", "paolo"], ["o le mea lea", "therefore"], ["e faitaaga ai", "to fornication"], ["o outou afafine,", "you all daughter"], ["e mulilulua foi", "to whoring also"], ["a outou avā.", "your wife"]]},
  {num:14,words:[["Ou te", "I will"], ["le fa'asalaina o outou", "the punished of you all"], ["afafine", "daughter"], ["pe a lātou", "even though / although they"], ["faitaaga,", "fornication"], ["ma", "and"], ["a outou avā", "your wife"], ["pe a lātou", "even though / although they"], ["mulilulua;", "whoring"], ["auā o", "for of"], ["i lātou lava", "them very"], ["ua lātou", "they"], ["o ese fa'atasi ma fafine faitaaga,", "away together and women fornication"], ["ua lātou faitaulaga", "they priest"], ["fa'atasi ma fafine talitane;", "together and women harlot"], ["o le nuu foi", "the nation also"], ["ua", "ua"], ["le mafaufau", "the think"], ["e pauu", "to fell"], ["i lātou.", "them"]]},
  {num:15,words:[["Isaraelu e,", "Israel by"], ["e ui", "to although"], ["ina", "so that"], ["e faitaaga,", "to fornication"], ["a", "but"], ["e aua ne'i agasala Iuta;", "to for now sin Judas"], ["aua tou te", "for second person plural"], ["o mai", "came"], ["i Kilikala,", "in Gilgal"], ["aua tou te", "for second person plural"], ["o ae", "went up"], ["i Petavene,", "in Beth-aven"], ["aua foi", "for also"], ["tou te tauto,", "second person plural to take an oath"], ["O loo soifua Ieova.", "is life the LORD"]]},
  {num:16,words:[["Auā", "for"], ["e fa'apei", "to like"], ["ona vaogata", "and disobedient"], ["o se povi fafine taanoa,", "a cattle women an animal that is weaned"], ["ua fa'apea ona", "saying and"], ["vaogata o Isaraelu;", "disobedient of Israel"], ["a", "but"], ["e fagaina", "to a bay"], ["i lātou", "them"], ["i nei", "in this"], ["ona po", "and night"], ["e Ieova", "the LORD"], ["e fa'apei", "to like"], ["o se tamai mamoe", "a son sheep"], ["i le mea lautele.", "in the thing wide"]]},
  {num:17,words:[["Ua pipii Efaraima", "clung to to Ephraim"], ["i tupua;", "in pillar"], ["ina tuu ai", "so that put"], ["pea ia ia te ia.", "continually to him to"]]},
  {num:18,words:[["A uma lo lātou inuga'ava,", "but all their inuga'ava"], ["ua matuā faitaaga", "great fornication"], ["i lātou;", "them"], ["ua loto atu", "heart"], ["o lātou ali'i", "they Lord"], ["i mea", "in thing"], ["e masiasi ai.", "to to be ashamied"]]},
  {num:19,words:[["Ua saisaitia o ia", "saisaitia he"], ["e le matagi", "shall not wind"], ["i ona apaau,", "in then a wing"], ["e masiasi foi", "to to be ashamied also"], ["i lātou", "them"], ["ona o", "because of"], ["a lātou taulaga.", "their offering"]]},
];
renderVerseSet(_hos_ch_4_Verses, 'hos-ch4-verses');

var _hos_ch_5_Verses = [
  {num:1,words:[["Le au ositaulaga e,", "the me high priest by"], ["fa'alogologo mai ia", "listen from to"], ["i lenei", "in this"], ["mea.", "thing"], ["Le 'āiga o Isaraelu e,", "the family of Israel by"], ["ina fa'alogologo mai ia.", "so that listen from to"], ["Le 'āiga", "the family"], ["o le tupu e,", "the king by"], ["ina liliu mai ia", "so that turn from to"], ["o outou fofoga,", "you all face"], ["auā", "for"], ["ua fa'asalaina outou,", "punished you all"], ["ua avea outou", "became you all"], ["ma matāsele", "and matāsele"], ["i Mesepa,", "in Mizpah"], ["ma upega", "and net"], ["ua folasia", "folasia"], ["i Tapora.", "in Tapora"]]},
  {num:2,words:[["Ua fa'ateleina", "multiplied"], ["le fasi e", "the kill by"], ["i lātou", "them"], ["ua liliu ese,", "turned away"], ["a", "but"], ["o a'u,", "I am"], ["ou te aoai atu", "I will chastise"], ["ia te i lātou", "unto them"], ["uma.", "all"]]},
  {num:3,words:[["O a'u", "I am"], ["ua ou iloa", "I knew"], ["Efaraima,", "Ephraim"], ["o Isaraelu foi", "Israel also"], ["ua", "ua"], ["le lilo lava", "the secret very"], ["ia ia te au;", "to him me"], ["auā,", "for"], ["Efaraima e,", "Ephraim by"], ["ua e faitaaga nei,", "you fornication this"], ["ua leaga Isaraelu.", "evil Israel"]]},
  {num:4,words:[["Lātou te", "they will"], ["le sauniuni", "the prepared"], ["a lātou galuega", "their work"], ["ina ia lātou", "so that they"], ["liliu mai", "turn from"], ["i lo lātou Atua;", "than they God"], ["auā o", "for of"], ["i totonu ia te", "in inside unto"], ["i lātou", "them"], ["le fia faitaaga,", "the want to do something fornication"], ["lātou te", "they will"], ["le iloa Ieova.", "the know the LORD"]]},
  {num:5,words:[["Ua molimau", "a witness"], ["le fa'amaualuga o Isaraelu", "the pride of Israel"], ["i o lātou", "in of they"], ["luma,", "before"], ["e pauu Isaraelu", "to fell Israel"], ["ma Efaraima", "and Ephraim"], ["i", "in"], ["a lātou agasala;", "their sin"], ["e paū foi", "to fall also"], ["Iuta fa'atasi ma", "Judas together and"], ["i lātou.", "them"]]},
  {num:6,words:[["Lātou te o atu", "they will went"], ["ma", "and"], ["a lātou mamoe", "their sheep"], ["ma", "and"], ["a lātou povi", "their cattle"], ["e sailiili atu ai", "to search"], ["ia Ieova;", "to the LORD"], ["a e lātou te", "but by they will"], ["le maua;", "the received"], ["ua afio ese", "dwelt away"], ["o ia ia te", "he unto"], ["i lātou.", "them"]]},
  {num:7,words:[["Ua pepelo", "false"], ["i lātou ia", "them to"], ["Ieova;", "the LORD"], ["auā", "for"], ["ua fānau e", "born you"], ["i lātou", "them"], ["a lātou tama ese;", "their child away"], ["o le a 'aina nei", "what edible this"], ["i lātou,", "them"], ["atoa ma o lātou", "and they"], ["tofi", "lot"], ["i le masina", "in the month"], ["e tasi .", "by one"]]},
  {num:8,words:[["Ia outou ilia", "to you all ilia"], ["le sofao", "the sofao"], ["i Kipea,", "in Gibeah"], ["ma le pu", "and the the tail"], ["i Rama;", "in Ramah"], ["ia outou alalaga i", "to you all cry out in"], ["Petavene;", "Beth-aven"], ["Peniamina e,", "Benjamin by"], ["o loo mulimuli atu", "is follow after"], ["o ia ia te oe.", "he unto you"]]},
  {num:9,words:[["E fa'atafunaina Efaraima", "to destroyed Ephraim"], ["i ona po", "in his nights"], ["o le aoaiga;", "the discipline"], ["ua ou fa'ailoaina atu", "I revealed"], ["i itu 'āiga", "in side family"], ["o Isaraelu,", "Israel"], ["o le 'upu moni lava.", "the word true very"]]},
  {num:10,words:[["O ali'i o Iuta", "Lord of Judas"], ["sa fa'apei o tagata", "like of men"], ["e sii", "to lift up"], ["le tuaoi", "the border"], ["i lātou;", "them"], ["ou te liligi atu", "I will to pour"], ["lo'u ita fa'apei", "my angry like"], ["o le vai", "the water"], ["ia te i lātou.", "unto them"]]},
  {num:11,words:[["Ua fa'asauaina Efaraima,", "cruel Ephraim"], ["ua lomia", "lomia"], ["i le fa'amasinoga;", "in the judgment"], ["auā", "for"], ["ua usiusitai o ia", "he obeyed"], ["ma lona loto", "and his heart"], ["i le poloaiga.", "in the commandment"]]},
  {num:12,words:[["O a'u foi", "I am also"], ["e pei o se mogamoga", "like a cockroach"], ["i Efaraima;", "in Ephraim"], ["e pei o se mea", "like a thing"], ["e pala foi", "to a muddy deposit in the sea also"], ["i le 'āiga", "in the family"], ["o Iuta.", "Judas"]]},
  {num:13,words:[["Na iloa", "knew"], ["e Efaraima", "by Ephraim"], ["lona ma'i,", "his from"], ["na iloa foi", "knew also"], ["e Iuta", "by Judas"], ["lona manua,", "his was animal"], ["ona alu lea", "And he went"], ["o Efaraima", "Ephraim"], ["i Asuria,", "in Assyria"], ["na alu", "went"], ["lana feau ia", "his errand to"], ["Iarepa", "Iarepa"], ["le tupu;", "the king"], ["a", "but"], ["ua", "ua"], ["le mafai lava", "not able at all"], ["ia te ia", "to him"], ["ona fa'amalolo ia te outou,", "and refresh unto you all"], ["pe fa'amafuina o outou", "whether make stale of you all"], ["manua.", "was animal"]]},
  {num:14,words:[["Auā", "for"], ["e avea a'u", "to become me"], ["e pei o se leona", "like a lion"], ["ia Efaraima,", "to Ephraim"], ["e pei o se leona taanoa foi", "like a lion an animal that is weaned also"], ["i le 'āiga", "in the family"], ["o Iuta;", "Judas"], ["o a'u lava ou te saeia", "I am very I will spared"], ["ma alu ese,", "and go away"], ["ou te aveesea,", "I will removed away"], ["e leai foi", "there is not also"], ["se", "a"], ["na te laveaiina.", "he delivered"]]},
  {num:15,words:[["Ou te alu,", "I will go"], ["ou te toe foi", "I will returned again"], ["lava", "very"], ["i le mea ou te nofo ai,", "in the thing I will dwell"], ["seia fa'asalaina lava", "until punished very"], ["i lātou,", "them"], ["ma lātou saili", "and they seek"], ["ia te au;", "unto me"], ["lātou te vave saili", "they will quick seek"], ["ia te au", "unto me"], ["pe a puapuagatia", "even though / although puapuagatia"], ["i lātou.", "them"]]},
];
renderVerseSet(_hos_ch_5_Verses, 'hos-ch5-verses');

var _hos_ch_6_Verses = [
  {num:1,words:[["O mai ia,", "came to"], ["ina tātou toe foi atu", "so that we went back"], ["ia Ieova;", "to the LORD"], ["auā o ia", "for he"], ["ua", "ua"], ["na saeia,", "spared"], ["na te fa'amaloloina foi", "he healed also"], ["i tātou;", "us"], ["ua ia fasia,", "to slaughtered"], ["na te fofoina foi", "he to doctor also"], ["i tātou.", "us"]]},
  {num:2,words:[["Na te fa'aolaina mai", "he saved alive from"], ["i tātou", "us"], ["pe a mavae aso", "even though / although passed day"], ["e lua;", "by two"], ["a oo", "but oo"], ["i lona tolu", "in his three"], ["o aso", "day"], ["na te fa'atutūina", "he pitched up"], ["i tātou,", "us"], ["tātou te ola", "we will life"], ["mai ai", "from"], ["i ona luma.", "before him"]]},
  {num:3,words:[["Tātou te iloa foi", "we will know also"], ["o loo o tātou", "is we"], ["tausisi atu ia", "strive for to"], ["iloa Ieova;", "know the LORD"], ["ua saunia", "prepared"], ["lona afio atu", "his dwell"], ["e pei o le taeao,", "like the morning"], ["e afio mai foi", "to dwell from also"], ["o ia ia te", "he unto"], ["i tātou", "us"], ["e pei o le", "like the"], ["ua,", "ua,"], ["e pei o le timu mulimuli", "like the rain follow after"], ["ma le timu muamua", "and the rain first the beginning"], ["i le eleele.", "the ground"]]},
  {num:4,words:[["Efaraima e,", "Ephraim by"], ["se a ea", "what indeed? / why?"], ["se mea ou te faia", "a thing I will make"], ["ia te oe?", "unto you"], ["Iuta e,", "Judas by"], ["se a ea", "what indeed? / why?"], ["se mea ou te faia", "a thing I will make"], ["ia te oe?", "unto you"], ["auā", "for"], ["ua pei o le", "like the"], ["puao", "puao"], ["i le taeao la outou amio lelei,", "in the morning your conduct good"], ["e pei o le sau foi", "like the come also"], ["i le vave ao", "in the quick day"], ["ona mavae atu.", "and passed"]]},
  {num:5,words:[["O le mea lea", "therefore"], ["ua ou fasia ai", "I slaughtered"], ["i lātou", "them"], ["e le au", "shall not me"], ["perofeta,", "prophet"], ["ua ou fasiotia", "I slain"], ["i lātou", "them"], ["i 'upu", "in word"], ["a lo'u gutu;", "but my mouth"], ["o au fa'amasinoga foi", "I am judgment also"], ["o le malamalama", "the light"], ["e alu atu lea.", "to go away"]]},
  {num:6,words:[["Auā", "for"], ["o le alofa ou te loto", "the love I will heart"], ["i ai,", "therein"], ["a", "but"], ["e le", "by the"], ["o le taulaga;", "the offering"], ["ia iloa foi", "to know also"], ["le Atua e sili lea", "God to most"], ["i lo'u manatu", "in my thought"], ["i taulaga mu.", "in burnt offerings"]]},
  {num:7,words:[["A", "but"], ["ua lātou soli", "they to tread upon"], ["le feagaiga,", "the covenant"], ["e pei o Atamu;", "like Adam"], ["ua lātou pepelo ia te au", "they false unto me"], ["i lea", "in"], ["mea.", "thing"]]},
  {num:8,words:[["O Kiliata", "Gilead"], ["o le aai lea", "the cities"], ["o", "o"], ["e fai amio leaga,", "to make iniquity"], ["o loo leaga,", "is evil"], ["i le toto.", "in the blood"]]},
  {num:9,words:[["Fa'apei", "like"], ["ona lamalama", "and watched"], ["i se tagata", "in a man"], ["o", "o"], ["e fao mea,", "to to seize thing"], ["e fa'apea foi", "saying also"], ["le au ositaulaga", "the me high priest"], ["ona fasioti tagata", "and killed man"], ["i le ala", "in the way"], ["i Sekema;", "in Shechem"], ["auā", "for"], ["ua ulavale", "mischievous"], ["i lātou.", "them"]]},
  {num:10,words:[["Ua a'u iloa", "me knew"], ["i le 'āiga", "in the family"], ["o Isaraelu", "Israel"], ["le mea", "the thing"], ["e matuā leaga;", "to great evil"], ["ua", "ua"], ["i ai", "therein"], ["le faitaaga o Efaraima,", "the fornication of Ephraim"], ["ua leaga Isaraelu.", "evil Israel"]]},
  {num:11,words:[["Iuta e,", "Judas by"], ["ua tuu", "put"], ["mo oe lava", "for you very"], ["le seleselegāsaito", "the seleselegāsaito"], ["ina ua ou fa'afoisia", "when I restored"], ["le tafeaga", "the exiles in wa^"], ["a lo'u nuu.", "but my nation"]]},
];
renderVerseSet(_hos_ch_6_Verses, 'hos-ch6-verses');

var _hos_ch_7_Verses = [
  {num:1,words:[["Na fai", "made"], ["a a'u fa'amaloloina", "but me healed"], ["o Isaraelu,", "Israel"], ["ona mānu mai ai lea", "and animal from then then"], ["o le leaga", "the evil"], ["o Efaraima", "Ephraim"], ["ma amio leaga", "and iniquity"], ["a Samaria;", "of Samaria"], ["auā", "for"], ["ua lātou fai", "they made"], ["le amio pepelo;", "the conduct false"], ["e ulufale mai le gaoi,", "to enter from the to steal"], ["a", "but"], ["e osofia", "to was possessed"], ["i fafo", "in outside"], ["e le au", "shall not me"], ["fao mea.", "to seize thing"]]},
  {num:2,words:[["Lātou to", "they to plant"], ["le fa'apea ifo", "the thus down"], ["i o lātou", "in of they"], ["loto,", "heart"], ["Ou te manatua la lātou amio leaga uma;", "I will remember their iniquity all"], ["o lenei,", "now"], ["ua siosiomia", "surrounded"], ["i lātou", "them"], ["i", "in"], ["a lātou lava galuega,", "their very work"], ["ua", "ua"], ["i o'u luma", "before me"], ["ia mea.", "to thing"]]},
  {num:3,words:[["Lātou te fa'afiafia", "they will to please"], ["le tupu", "the king"], ["i", "in"], ["a lātou amio leaga;", "their iniquity/wickedness"], ["atoa ma ali'i", "and Lord"], ["i", "in"], ["a lātou tala pepelo.", "their side false"]]},
  {num:4,words:[["Ua mulilulua", "whoring"], ["i lātou uma;", "them all"], ["pei", "like"], ["se ogaumu", "a ogaumu"], ["i lātou", "them"], ["ua fa'aaasaina", "faaaasaina"], ["e le fai areto;", "shall not make bread"], ["ua", "ua"], ["le toe tafu", "the again to make up the fire"], ["pe a uma ona", "even though / although all then"], ["lolomi", "lolomi"], ["o le palugāfalaoa seia fa'afefeteina.", "the palugāfalaoa until feared"]]},
  {num:5,words:[["O le aso", "the day"], ["o lo tātou tupu", "our king"], ["na mama'i ai", "from"], ["ali'i", "Lord"], ["i le oona", "in the drunk"], ["o uaina;", "wine"], ["na ia fa'aloaloa atu", "to stretched out"], ["lona lima fa'atasi ma ē tauemu.", "his hand together and by mock"]]},
  {num:6,words:[["Auā", "for"], ["ua lātou fa'alatalata", "they drew near"], ["ma o lātou", "and of they"], ["loto,", "heart"], ["e pei o se ogaumu,", "like a ogaumu"], ["a o lātou", "but of they"], ["o lamalama;", "watched"], ["ua aoina o", "aoina of"], ["moe lo lātou fai areto,", "sleep their make bread"], ["ua mu", "mu"], ["i le taeao pei", "in the morning like"], ["se afi mumū.", "a fire scarlet"]]},
  {num:7,words:[["Ua aasa", "Asa"], ["i lātou uma", "them all"], ["e pei o se ogaumu,", "like a ogaumu"], ["ua lātou fa'aumatia", "they destroyed"], ["o lātou ali'i fa'amasino;", "they Lord judge"], ["ua pauu o", "fell of"], ["lātou tupu uma,", "they king all"], ["e leai so lātou", "there is not so they"], ["e valaau ia te au.", "to cried out unto me"]]},
  {num:8,words:[["O Efaraima", "Ephraim"], ["ua numia o ia", "numia he"], ["e ia fa'atasi ma le nuu;", "by him together and the nation"], ["o Efaraima", "Ephraim"], ["o le potoi areto", "the cake bread"], ["ia e lei", "to by not"], ["liua.", "turned"]]},
  {num:9,words:[["Ua fa'aumatia", "are destroyed"], ["e tagata ese", "to man away"], ["lona malosi,", "his strong"], ["a", "but"], ["ua", "ua"], ["le iloa e", "the know by"], ["ia;", "to"], ["ua pule", "ruled"], ["le sinā", "the sinā"], ["o lona lauulu,", "his hair"], ["a", "but"], ["ua", "ua"], ["le iloa e", "the know by"], ["ia.", "to"]]},
  {num:10,words:[["Ua molimau", "a witness"], ["le fa'amaualuga o Isaraelu", "the pride of Israel"], ["i o lātou", "in of they"], ["luma;", "before"], ["e ui lava", "to although very"], ["i ia mea uma,", "in to all things"], ["ua lātou", "they"], ["le toe foi", "the returned again"], ["ia Ieova lo lātou", "to the LORD their"], ["Atua,", "God"], ["ua lātou", "they"], ["le saili foi", "the seek also"], ["ia te ia.", "to him"]]},
  {num:11,words:[["O Efaraima foi", "Ephraim also"], ["e pei o se lupe valea", "like a dove foolish"], ["ia,", "to"], ["e leai sona mafaufau;", "there is not sona think"], ["lātou te valaau", "they will cried out"], ["ia Aikupito,", "to Egypt"], ["ua o foi", "of also"], ["i lātou", "them"], ["i Asuria.", "in Assyria"]]},
  {num:12,words:[["A lātou o,", "their"], ["ou te lafo", "I will cloth used as gratuity for a talking chief"], ["la'u upega", "my net"], ["i luga ia te", "in above unto"], ["i lātou;", "them"], ["ou te lafo", "I will cloth used as gratuity for a talking chief"], ["i lalo ia te", "in under unto"], ["i lātou pei ni manu felelei;", "them like some birds of the air"], ["ou te sasa foi", "I will a scourge also"], ["ia te i lātou", "unto them"], ["e pei ona", "as"], ["fa'alogo", "hearken"], ["i ai", "therein"], ["lo lātou potopotoga.", "their gathering"]]},
  {num:13,words:[["O", "O"], ["i talofa ia te", "in hello unto"], ["i lātou!", "them"], ["auā", "for"], ["ua sosola ese", "fled away"], ["i lātou ia te au;", "them unto me"], ["ia malaia i lātou!", "to disaster them"], ["auā", "for"], ["ua lātou fouvale ia te au;", "they to rebel unto me"], ["na ou togiola foi", "I atonement also"], ["ia te i lātou,", "unto them"], ["a", "but"], ["ua lātou tala", "they side"], ["pepelo ia leaga ai", "false to evil"], ["a'u.", "me"]]},
  {num:14,words:[["Ua", "Ua"], ["le valaau mai", "the cried out from"], ["i lātou ia te au", "them unto me"], ["ma o lātou", "and of they"], ["loto,", "heart"], ["ina ua lātou", "when they"], ["uio", "uio"], ["i o lātou", "in of they"], ["moega;", "bed"], ["lātou te fa'apotopoto", "they will gather"], ["i saito", "in wheat"], ["ma uaina;", "and wine"], ["lātou te o ese", "they will away"], ["ia te au.", "unto me"]]},
  {num:15,words:[["O a'u foi,", "I am also"], ["na ou a'oa'o atu,", "I excellent"], ["na ou fa'amalosiina", "I was strong"], ["o lātou lima,", "they hand"], ["a", "but"], ["ua lātou taupulepule", "they conspire"], ["i mea", "in thing"], ["e leaga ai", "to evil"], ["a'u.", "me"]]},
  {num:16,words:[["Ua lātou toe foi,", "they returned again"], ["a", "but"], ["e le o lē Silisili ese", "by the of the very much away"], ["ua lātou foi", "they also"], ["i ai;", "therein"], ["e pei o le aufana pepelo", "like the bow false"], ["i lātou;", "them"], ["e pauu o lātou", "to fell of they"], ["ali'i", "Lord"], ["i le pelu", "by the sword"], ["ona", "and"], ["o le fa'asiasia", "the haughty"], ["o lātou laulaufaiva;", "they tongue"], ["e fai", "to make"], ["mo lātou gao lea", "for they gao"], ["mea", "thing"], ["i le nuu", "in the land"], ["o Aikupito.", "Egypt"]]},
];
renderVerseSet(_hos_ch_7_Verses, 'hos-ch7-verses');

var _hos_ch_8_Verses = [
  {num:1,words:[["Ia e ili", "to by ili"], ["le pu;", "the the tail"], ["e sau o ia", "to come he"], ["e pei o se aeto", "like a aeto"], ["i le 'āiga", "in the family"], ["o Ieova;", "the LORD"], ["auā", "for"], ["ua lātou soli", "they to tread upon"], ["la'u feagaiga,", "my covenant"], ["ma", "and"], ["ua lātou fouvale", "they to rebel"], ["i la'u tulafono.", "in my law"]]},
  {num:2,words:[["E alalaga", "to cry out"], ["i lātou ia te au,", "them unto me"], ["Lo mātou Atua e,", "our God by"], ["o Isaraelu", "Israel"], ["i mātou ,", "us"], ["ua mātou iloa oe.", "we knew you"]]},
  {num:3,words:[["Ua lafoaiina", "forsaken"], ["e Isaraelu", "by Israel"], ["le mea lelei;", "the thing good"], ["e tuliloaina o ia", "to pursued he"], ["e le", "by the"], ["ua ita ia te ia", "angry to him"], [".", "."]]},
  {num:4,words:[["Ua lātou tofia", "they was chosen"], ["tupu", "king"], ["a", "but"], ["e le mai ia te au;", "by the from me"], ["ua lātou tofia", "they was chosen"], ["ali'i", "Lord"], ["a", "but"], ["e le iloa", "shall not know"], ["e a'u;", "to me"], ["o lātou ario,", "they silver"], ["ma o lātou", "and of they"], ["auro", "gold"], ["ua lātou fai a'i", "they thereby"], ["tupua", "pillar"], ["mo", "for"], ["i lātou,", "them"], ["ina ia fa'aumatia ai", "so that destroyed"], ["i lātou .", "them"]]},
  {num:5,words:[["Samaria e,", "Samaria by"], ["ua lafoaiina oe", "forsaken you"], ["e lau tamai povi;", "by your son cattle"], ["ua tupu", "king"], ["lo'u ita ia te", "my angry unto"], ["i lātou;", "them"], ["pe lātou te", "whether they will"], ["le mafai seia afea", "not able how long?/until when?"], ["ona mamā?", "and clean"]]},
  {num:6,words:[["Auā mai ia", "for from to"], ["Isaraelu lava ia;", "Israel very to"], ["na faia o ia", "made he"], ["e le tufuga;", "shall not master builder"], ["e le", "by the"], ["o le Atua", "of God"], ["lava ia,", "very to"], ["o le mea lea", "therefore"], ["e nutililiiina ai", "by nutililiiina"], ["le tamai povi", "the son cattle"], ["o Samaria.", "Samaria"]]},
  {num:7,words:[["Na lātou luluina", "they shaken"], ["le matagi,", "the wind"], ["o le mea lea", "therefore"], ["lātou te selesele", "they will an evenly cut head of"], ["mai ai", "from"], ["le afā;", "the cyclone"], ["ua leai sona", "there was not sona"], ["tino;", "body"], ["e le tupu", "shall not king"], ["se saito", "a wheat"], ["i le fuga,", "in the flower"], ["a", "but"], ["e afai", "to if"], ["e fua,", "to fruit"], ["e 'aina", "to edible"], ["e tagata ese.", "to man away"]]},
  {num:8,words:[["Ua fa'aumatia Isaraelu;", "are destroyed Israel"], ["lātou te", "they will"], ["i ai", "therein"], ["nei", "this"], ["i nuu ese,", "in nation away"], ["e pei o se ipu", "like a cup"], ["e leai sē fiafia", "there is not a pleased"], ["i ai.", "therein"]]},
  {num:9,words:[["Auā", "for"], ["ua lātou", "they"], ["o ae", "went up"], ["i Asuria,", "in Assyria"], ["ua", "ua"], ["se asini", "a donkey"], ["o le vao", "the vegetation"], ["ua nofo toatasi;", "dwelt one One"], ["ua fa'aoloaina", "made goods"], ["e Efaraima", "by Ephraim"], ["e o mananao", "by of desire"], ["ia te ia", "to him"], [".", "."]]},
  {num:10,words:[["A", "but"], ["e ui", "to although"], ["ina lātou fa'aoloaina nuu ese,", "so that they make goods nation away"], ["ou te fa'apotopoto nei", "I will gather this"], ["ia te i lātou;", "unto them"], ["e le pine", "shall not to be long"], ["ona tiga o", "and grieved of"], ["i lātou", "them"], ["ona", "and"], ["o le avega", "the burden"], ["mai le tupu", "from the king"], ["o ali'i.", "Lord"]]},
  {num:11,words:[["Ua faia", "made"], ["e Efaraima fata faitaulaga", "by Ephraim altar"], ["e tele,", "to great"], ["e agasala ai;", "to sin"], ["o le mea lea", "therefore"], ["ua avea ai", "became"], ["fata faitaulaga", "altar"], ["ma mea", "and thing"], ["e agasala ai", "to sin"], ["o ia.", "he"]]},
  {num:12,words:[["Ua ou tusi atu ia te ia", "I book to him"], ["o mea tetele", "thing great"], ["i la'u tulafono;", "in my law"], ["a", "but"], ["ua ta'ua ia", "us two to"], ["mea o mea ese.", "thing of thing away"]]},
  {num:13,words:[["Lātou te fai taulaga", "they will make offering"], ["i manu", "in animal"], ["e fai ma taulaga", "to be offering"], ["mo a'u,", "for me"], ["ma lātou aai ai;", "and they cities"], ["a", "but"], ["ua", "ua"], ["le talia", "the received"], ["i lātou", "them"], ["e Ieova;", "the LORD"], ["e manatua nei", "to remember this"], ["e ia", "by him"], ["a lātou amio leaga,", "their iniquity/wickedness"], ["ma taui", "and a reward"], ["i", "in"], ["a lātou agasala;", "their sin"], ["lātou te toe foi", "they will returned again"], ["i Aikupito.", "in Egypt"]]},
  {num:14,words:[["Auā", "for"], ["ua fa'agalogalo", "to forget"], ["e Isaraelu", "by Israel"], ["i Lē", "in the"], ["na faia o ia,", "made he"], ["ua fa'atuina e", "built you"], ["ia", "to"], ["o malumalu;", "temple"], ["o Iuta foi", "Judas also"], ["ua ia fa'ateleina", "to multiplied"], ["o aai nofo 'olo;", "cities dwell trench"], ["ou te tuuina atu", "I will give"], ["le afi", "the fire"], ["i ana aai,", "in his cities"], ["e fa'aumatia ai", "to destroyed"], ["ona maota.", "and the name of a tree"]]},
];
renderVerseSet(_hos_ch_8_Verses, 'hos-ch8-verses');

var _hos_ch_9_Verses = [
  {num:1,words:[["Isaraelu e,", "Israel by"], ["aua", "for"], ["e te fiafia", "by pleased"], ["ma le olioli,", "and the joy"], ["fa'apei o isi nuu;", "like of other nation"], ["auā", "for"], ["ua e alu ese", "you went away"], ["i lou Atua e", "in your God by"], ["faitaaga ai;", "fornication"], ["ua e fia", "you wanted to do something"], ["fai taui", "make a reward"], ["i mea uma", "in all things"], ["e sasa ai", "to a scourge"], ["saito.", "wheat"]]},
  {num:2,words:[["E le fagaina", "shall not a bay"], ["i lātou", "them"], ["i le mea", "in the thing"], ["e sasa ai", "to a scourge"], ["saito", "wheat"], ["ma le soligāvine,", "and the soligāvine"], ["e oge ai", "to a famine"], ["uaina fou.", "wine new"]]},
  {num:3,words:[["Lātou te", "they will"], ["le nonofo", "the dwelling"], ["i le nuu", "in the land"], ["o Ieova,", "the LORD"], ["a", "but"], ["e toe foi", "to returned again"], ["Efaraima", "Ephraim"], ["i Aikupito,", "in Egypt"], ["lātou te aai mea leaga", "they will cities thing evil"], ["i Asuria.", "in Assyria"]]},
  {num:4,words:[["Lātou te", "they will"], ["le fai taulaga", "the make offering"], ["ia Ieova i", "to the LORD in"], ["uaina,", "wine"], ["e le fiafia", "shall not pleased"], ["o ia ia te", "he unto"], ["i lātou;", "them"], ["o", "o"], ["a lātou taulaga,", "their offering"], ["e ia te", "by him"], ["i lātou ia,", "them to"], ["peiseai o mea", "as if of thing"], ["e 'ai", "to eat"], ["a", "but"], ["e fa'anoanoa,", "to mourn"], ["o", "o"], ["i lātou uma", "them all"], ["e aai ai", "to cities"], ["e leaga ai", "to evil"], ["i lātou;", "them"], ["auā", "for"], ["o la lātou mea", "their thing"], ["e 'ai mā lātou", "to eat and they"], ["e le oo atu lea", "by the arrived"], ["i le fale", "in the house"], ["o Ieova.", "the LORD"]]},
  {num:5,words:[["Se a se mea tou te faia", "a but a thing second person plural made"], ["i le aso", "in the day"], ["e fai ai", "to make"], ["le tausamiga,", "the feast"], ["ma le aso", "and the day"], ["e fai ai", "to make"], ["le taulaga ia", "the offering to"], ["Ieova?", "the LORD"]]},
  {num:6,words:[["Auā,", "for"], ["fa'auta mai,", "behold from"], ["ua o", "of"], ["i lātou ne'i malaia;", "them now disaster"], ["e fa'apotopotoina", "to gathered together"], ["i lātou", "them"], ["e Aikupito,", "by Egypt"], ["e tanumia", "to buried"], ["i lātou", "them"], ["e Mafi;", "by Mafi"], ["o mea matagofie", "thing beautiful"], ["o", "o"], ["i ai", "therein"], ["o lātou ario", "they silver"], ["e vaoa ia", "to overgrown with weeds to"], ["i lā'au ogoogo;", "in tree to scorch"], ["e", "by"], ["i ai", "therein"], ["i o lātou", "in of they"], ["fale o lā'au talatala.", "house of tree to untie"]]},
  {num:7,words:[["Ua oo mai", "it came to pass from"], ["ona po", "and night"], ["e taui ai,", "to a reward"], ["ua oo mai", "it came to pass from"], ["ona po", "and night"], ["e totogi ai;", "to wages"], ["e iloa", "to know"], ["e Isaraelu;", "by Israel"], ["ua valea", "foolish"], ["le perofeta,", "the prophet"], ["ua valea lava", "foolish very"], ["le vaafaatau,", "the vaafaatau"], ["ona", "and"], ["o le tele", "the great"], ["o lau amio leaga,", "your iniquity"], ["ma le 'ino'ino tele.", "and the disdained great"]]},
  {num:8,words:[["O loo fa'atalitali Efaraima", "is waited Ephraim"], ["fa'atasi", "together"], ["i lo'u Atua;", "in my God"], ["ua", "ua"], ["se mailei o", "a a trap of"], ["e fāi manu", "to make animal"], ["le perofeta", "the prophet"], ["i ana amio uma;", "in his conduct all"], ["o le 'ino'ino", "the disdained"], ["i le fale", "in the house"], ["o lona Atua.", "his God"]]},
  {num:9,words:[["Ua matuā amio leaga", "great iniquity"], ["i lātou,", "them"], ["fa'apei", "like"], ["ona fai", "and make"], ["i ona po", "in his nights"], ["o Kipea;", "Gibeah"], ["e manatua e", "to remember by"], ["ia", "to"], ["a lātou agasala,", "their sin"], ["e taui atu", "to a reward"], ["i", "in"], ["a lātou amio leaga.", "their iniquity/wickedness"]]},
  {num:10,words:[["Na ou maua", "I received"], ["Isaraelu,", "Israel"], ["e pei o fuifui vine", "like to dip vine"], ["i le vao;", "in the wilderness"], ["na ou iloa", "I knew"], ["o outou mātua", "you all great"], ["e pei o uluai mati", "like first fig"], ["i le mati", "in the fig"], ["ina ua fa'atoa fua mai;", "when just now fruit from"], ["a", "but"], ["ua o", "of"], ["i lātou ia", "them to"], ["Paalapeoro,", "Paalapeoro"], ["ua vavae atu", "to divide"], ["i lātou", "them"], ["i le mea", "in the thing"], ["e masiasi ai;", "to to be ashamied"], ["ua inosia", "abominable"], ["i lātou", "them"], ["e tusa ma le mea", "according to the thing"], ["ua lātou naunau", "they desired"], ["i ai.", "therein"]]},
  {num:11,words:[["O Efaraima", "Ephraim"], ["e lele ese lo lātou mamalu fa'apei", "to fly away their glory like"], ["o le manu lele,", "the animal fly"], ["ai", "ai"], ["le fanauga,", "the children"], ["ma le manava,", "and the womb"], ["ma le fa'atoa afuafua.", "and the just now to become pregnant"]]},
  {num:12,words:[["E ui", "to although"], ["ina lātou tausi", "so that they nurse"], ["a lātou fānau,", "their born"], ["ou te aveeseina", "I will carried away"], ["i lātou", "them"], ["i tagata;", "in man"], ["oi talofa lava", "wo very"], ["ia te i lātou,", "unto them"], ["pe a a'u", "even though / although me"], ["alu ese ia te", "go away unto"], ["i lātou.", "them"]]},
  {num:13,words:[["Ua totōina Efaraima", "planted Ephraim"], ["i le mea matagofie,", "in the thing beautiful"], ["fa'apei", "like"], ["ona ou iloa", "and I know"], ["o Turo;", "Tyre"], ["a o Efaraima", "but of Ephraim"], ["na te ta'ita'iina atu", "he led"], ["lana fānau", "his born"], ["i le fasioti tagata.", "in the killed man"]]},
  {num:14,words:[["Ieova e,", "O LORD!"], ["ia e avatu ia te i lātou;", "to to give away unto them"], ["se a foi", "a but also"], ["se mea", "a thing"], ["e te avatua?", "by given away"], ["Ia e avatu ia te i lātou", "to to give away unto them"], ["le manava fānau", "the womb born"], ["le au,", "the me"], ["ma susu", "and milk"], ["e le susua.", "shall not plural of sua"]]},
  {num:15,words:[["O loo", "is/are"], ["i Kilikala lo lātou leaga uma;", "in Gilgal their evil all"], ["auā", "for"], ["na ou 'ino'ino ia te", "I disdained unto"], ["i lātou", "them"], ["i lea", "in"], ["mea,", "thing"], ["ou te tulia", "I will driven away"], ["i lātou ai", "them"], ["lo'u fale", "my house"], ["ina ua leaga mea", "when evil thing"], ["ua lātou faia;", "they did"], ["ou te", "I will"], ["le toe alofa", "the again love"], ["ia te i lātou;", "unto them"], ["o lātou ali'i uma,", "they Lord all"], ["o", "o"], ["e fouvale", "to to rebel"], ["i lātou.", "them"]]},
  {num:16,words:[["Ua taia Efaraima,", "struck Ephraim"], ["ua mago lo lātou", "a small eel their"], ["pogai;", "cause"], ["lātou te", "they will"], ["le fua mai ni fua;", "the fruit from some fruit"], ["afai foi", "if also"], ["lātou te fananau,", "they will fananau"], ["ou te fasiotia la lātou fānau pele.", "I will slain their born dear"]]},
  {num:17,words:[["E lafoaiina", "to forsaken"], ["i lātou", "them"], ["e lo'u Atua,", "to my God"], ["auā", "for"], ["ua lātou", "they"], ["le fa'alogo ia te ia;", "the hearken to him"], ["e taase", "to sojourn"], ["i lātou", "them"], ["i nuu ese.", "in nation away"]]},
];
renderVerseSet(_hos_ch_9_Verses, 'hos-ch9-verses');

var _hos_ch_10_Verses = [
  {num:1,words:[["O Isaraelu,", "Israel"], ["o le vine", "the vine"], ["ia e māfalā;", "to by māfalā"], ["ua ia fua mai", "to fruit from"], ["ni fua", "some fruit"], ["e fai mona;", "to make to burst forth (as faiai"], ["fa'apei", "like"], ["ona tele", "and great"], ["o lona fua,", "his fruit"], ["ua fa'apea ona", "saying and"], ["fa'ateleina e ia", "multiplied by him"], ["o fata faitaulaga;", "altar"], ["fa'apei", "like"], ["ona lelei", "and good"], ["o lona laueleele,", "his ground"], ["ua fa'apea ona", "saying and"], ["lātou gaosi lelei", "they gaosi good"], ["o tupua.", "pillar"]]},
  {num:2,words:[["Ua fa'alotoloto lua", "made heart two"], ["i lātou;", "them"], ["ua nofo sala nei", "dwelt a fine this"], ["i lātou;", "them"], ["na te lepetia", "he overthrown"], ["a lātou fata faitaulaga,", "their altar"], ["na te fa'aumatia", "he destroyed"], ["a lātou tupua.", "their pillar"]]},
  {num:3,words:[["Auā", "for"], ["e fa'apea mai nei", "saying from this"], ["i lātou,", "them"], ["Ua leai se", "there was no"], ["tupu ia te", "king unto"], ["i mātou,", "us"], ["auā", "for"], ["ua mātou", "we"], ["le matatau ia", "the dismayed to"], ["Ieova;", "the LORD"], ["se a foi", "a but also"], ["se mea", "a thing"], ["e faia", "to made"], ["e le tupu", "shall not king"], ["ia", "to"], ["i mātou?", "us"]]},
  {num:4,words:[["Ua lātou fai mai", "they said"], ["'upu,", "word"], ["ua tauto pepelo,", "to take an oath false"], ["ua osi", "made"], ["le feagaiga;", "the covenant"], ["e tupu ae foi", "to king up also"], ["le fa'amasinoga,", "the judgment"], ["e pei o lā'au oona", "like tree drunk"], ["i utu o fanua.", "in todraw water of land"]]},
  {num:5,words:[["E fefefe", "to afraid"], ["e ua nonofo", "by dwelling"], ["i Samaria", "in Samaria"], ["ona o tamai povi", "because of son cattle"], ["o Petavene;", "Beth-aven"], ["auā", "for"], ["e fetagisi ai", "to wept"], ["ona tagata,", "and man"], ["o", "o"], ["ona ositaulaga foi", "and high priest also"], ["e", "by"], ["na fiafia", "pleased"], ["i ai;", "therein"], ["auā", "for"], ["o lona mamalu", "his glory"], ["ua te'a", "departed"], ["ma ia.", "and to"]]},
  {num:6,words:[["E avea foi", "to become also"], ["lenei mea", "this thing"], ["i Asuria", "in Assyria"], ["e fai ma mea alofa", "to be thing love"], ["i le tupu", "in the king"], ["o Iarepa;", "Iarepa"], ["e mā Efaraima,", "by and Ephraim"], ["e masiasi foi", "to to be ashamied also"], ["Isaraelu", "Israel"], ["ona", "and"], ["o lana lava pule.", "his very rule"]]},
  {num:7,words:[["O Samaria", "Samaria"], ["ua fano", "perished"], ["lona tupu,", "his king"], ["e pei o si fasi lā'au", "like si kill tree"], ["i le fogāvai.", "in the fogāvai"]]},
  {num:8,words:[["E fa'aumatia foi", "to destroyed also"], ["mea maualuga", "thing Iiigli"], ["i Avene,", "in Avene"], ["o le agasala", "the sin"], ["a Isaraelu;", "of Israel"], ["e tutupu ae", "to bring forth up"], ["le lā'au tuitui", "the tree prickly"], ["ma le lā'au talatala", "and the tree to untie"], ["i o lātou", "in of they"], ["fata faitaulaga;", "altar"], ["lātou te fai atu foi", "they will said to also"], ["i mauga,", "in mountain"], ["Ina tanu mai ia ia te", "so that to bury from to him"], ["i mātou.", "us"], ["E fa'apea foi", "saying also"], ["i mea maupuepue,", "in thing maupuepue"], ["Ina mafuli mai ia", "so that mafuli from to"], ["i luga ia te", "in above unto"], ["i mātou.", "us"]]},
  {num:9,words:[["Isaraelu e,", "Israel by"], ["talu mai", "since from"], ["ona po o Kipea", "and night of Gibeah"], ["ua e agasala ai;", "you sinned"], ["ua lātou tutumau ai;", "they enduring"], ["na", "na"], ["le oo atu", "the arrived"], ["ia te i lātou", "unto them"], ["i Kipea", "in Gibeah"], ["le taua", "the battle"], ["i tagata agaleaga.", "in man unkind"]]},
  {num:10,words:[["O lo'u loto,", "my heart"], ["ou te aoai", "I will chastise"], ["ia te i lātou;", "unto them"], ["e fa'apotopotoina foi", "to gathered together also"], ["tagata", "man"], ["e tau ma", "to fight against"], ["i lātou,", "them"], ["pe a ou fusifusi", "even though I to bind hund and foot"], ["ia te i lātou", "unto them"], ["ona o", "because of"], ["a lātou agasala", "their sin"], ["e lua.", "by two"]]},
  {num:11,words:[["O Efaraima foi", "Ephraim also"], ["o le povi fafine", "the cattle women"], ["ia", "to"], ["ua a'oa'oina,", "taught"], ["ua fia soli", "wanted to do something to tread upon"], ["saito lava;", "wheat very"], ["a", "but"], ["ua ou alu atu lava a'u", "I went away very me"], ["i lona", "in his"], ["ua lalelei;", "beautiful"], ["ou te fa'atietie", "I will make ride"], ["se tasi ia", "a one to"], ["Efaraima,", "Ephraim"], ["e suatia", "by suatia"], ["le eleele", "the earth"], ["e Iuta", "by Judas"], ["e fa'amăluluina", "by faamăluluina"], ["e Iakopo", "by Jacob"], ["lona laueleele.", "his ground"]]},
  {num:12,words:[["Ia outou lulu", "to you all barn owl"], ["saito", "wheat"], ["mo outou", "for you"], ["ma le amiotonu,", "and the righteous"], ["ia outou selesele", "to you all an evenly cut head of"], ["mai", "from"], ["ma le amio lelei;", "and the conduct good"], ["ia outou suatia", "to you all suatia"], ["lo outou fanua vaoa;", "your land overgrown with weeds"], ["auā", "for"], ["ua oo", "it came to pass"], ["i ona po", "in his nights"], ["e saili atu ai", "to seek"], ["ia Ieova,", "to the LORD"], ["seia afio mai", "until dwell from"], ["o ia,", "he"], ["ma fa'atotō ifo", "and make blood down"], ["le amiotonu", "the righteous"], ["i luga ia te outou.", "in above unto you all"]]},
  {num:13,words:[["Ua outou suatia", "you all suatia"], ["le agasala,", "sin"], ["ua outou selesele mai le", "you all an evenly cut head of from the"], ["leaga;", "evil"], ["ua outou aai", "you all cities"], ["le fua", "the fruit"], ["o le pepelo;", "the false"], ["auā", "for"], ["na e fa'atuatua", "you faith"], ["i lou ala,", "in your way"], ["ma le toatele", "and the many"], ["o ou tagata totoa.", "I man p'ural o( fnt"]]},
  {num:14,words:[["O lea", "therefore"], ["e tupu ai", "to king"], ["le vāvāō", "the vegetation"], ["i ou tagata,", "in I man"], ["e fa'aumatia ou 'olo uma lava,", "to destroyed I trench all very"], ["e pei ona", "as"], ["fa'aumatia", "destroyed"], ["e Salemana o Petarepelu", "by Salemana of Petarepelu"], ["i le aso", "in the day"], ["na tau ai", "fought"], ["le taua;", "the battle"], ["na palasi", "to have children in"], ["le tinā fa'atasi ma ana tama.", "the mother together and his child"]]},
  {num:15,words:[["E fa'apea lava", "saying very"], ["ona faia ia te outou", "and made unto you all"], ["i Peteli", "in Bethel"], ["ona", "and"], ["o la outou amio", "your conduct"], ["e matuā leaga;", "to great evil"], ["e matuā fano", "to great perish"], ["lava", "very"], ["le tupu o Isaraelu", "the king of Israel"], ["i le taeao.", "in the morning"]]},
];
renderVerseSet(_hos_ch_10_Verses, 'hos-ch10-verses');

var _hos_ch_11_Verses = [
  {num:1,words:[["O", "O"], ["ona po", "and night"], ["na tama itiiti ai", "youth man"], ["Isaraelu,", "Israel"], ["na ou alofa atu ia te ia,", "I loved to him"], ["na ou valaauina foi", "I called also"], ["lo'u atali'i", "my son"], ["nai Aikupito.", "from Egypt"]]},
  {num:2,words:[["Na lātou alalaga ia te", "they cried out unto"], ["i lātou,", "them"], ["a", "but"], ["ua lātou", "they"], ["o ese ia te", "away unto"], ["i lātou;", "them"], ["na lātou fai", "they made"], ["taulaga ia Paala,", "offering to a small fly-fishhook"], ["ma fa'amu mea manogi", "and burn incense thing fragrant"], ["i tupua", "in pillar"], ["ua tā.", "struck"]]},
  {num:3,words:[["Na ou a'oa'oina", "I taught"], ["Efaraima ia sāvali,", "Ephraim to walk"], ["o loo o tauta'ita'i", "is tauta'ita'i"], ["ia te i lātou", "unto them"], ["i o lātou", "in of they"], ["lima;", "hand"], ["a", "but"], ["ua", "ua"], ["le iloa e", "the know by"], ["i lātou", "them"], ["ona ou fa'amaloloina", "and I healed"], ["o", "o"], ["i lātou.", "them"]]},
  {num:4,words:[["Na ou tosina", "I to be"], ["i lātou", "them"], ["i maea", "in rope"], ["a le tagata,", "but the man"], ["o maea alofa", "rope love"], ["lava;", "very"], ["na ou", "I"], ["i ai", "therein"], ["ia te i lātou", "unto them"], ["e pei o", "like"], ["e sii ae", "to lift up up"], ["le amo ai", "the carry"], ["o lātou aulamu,", "they aulamu"], ["na au tuuina atu foi", "me given / delivered also"], ["mea", "thing"], ["e 'ai ia te", "to eat unto"], ["i lātou.", "them"]]},
  {num:5,words:[["E le toe foi", "shall not returned again"], ["o ia", "he"], ["i le nuu", "in the land"], ["o Aikupito,", "Egypt"], ["a", "but"], ["e avea", "to become"], ["le Asuria mona tupu;", "the Assyria to burst forth (as faiai king"], ["auā", "for"], ["ua", "ua"], ["le mafafai", "the able"], ["i lātou", "them"], ["ona toe foi atu.", "and went back"]]},
  {num:6,words:[["E tumau", "to be firm"], ["le pelu", "the sword"], ["i ona aai,", "in then cities"], ["e fa'aumatia ai", "to destroyed"], ["foi", "also"], ["ona la,", "and la"], ["ma fano ai,", "and perish"], ["auā o", "for of"], ["a lātou lava filifiliga.", "their very choice"]]},
  {num:7,words:[["Ua naunau", "desired"], ["lo'u nuu", "my nation"], ["e liliu ese", "to turn away"], ["ia te au;", "unto me"], ["lātou te valaau", "they will cried out"], ["i ai", "therein"], ["e o mai", "shall come"], ["i lē Silisili ese,", "in the very much away"], ["a", "but"], ["e leai se tasi", "there is no one"], ["e vivii atu", "to praised"], ["ia te ia", "to him"], [".", "."]]},
  {num:8,words:[["Efaraima e,", "Ephraim by"], ["ou te mafai fa'apefea ona tuu atu", "I will able how then placed"], ["ia te oe?", "unto you"], ["Isaraelu e,", "Israel by"], ["ou te tuuina atu oe", "I will give you"], ["fa'apefea? ou te mafai fa'apefea ona tuuina atu", "how I will able how then given / delivered"], ["o oe", "you"], ["e pei o Atama? ou te tuuina atu oe", "like Atama I will give you"], ["fa'apefea", "how"], ["e pei o Sepoima?", "like Sepoima"], ["Ua liua", "turned"], ["lo'u loto", "my heart"], ["i totonu ia te au;", "in inside unto me"], ["atoa foi", "together with also"], ["ma lo'u alofa mutimutivale", "and my lovingkindness"], ["ua tupu.", "king"]]},
  {num:9,words:[["Ou te", "I will"], ["le fa'aoo", "the bring upon"], ["lo'u ita tele;", "my angry great"], ["ou te", "I will"], ["le toe fa'aumatia Efaraima;", "the again destroyed Ephraim"], ["auā", "for"], ["o a'u", "I am"], ["o le Atua,", "of God"], ["a", "but"], ["e le", "by the"], ["se tagata,", "a man"], ["o le Paia", "the holy"], ["o loo", "is/are"], ["i totonu ia te oe;", "in inside unto you"], ["ou te", "I will"], ["le alu atu", "the go away"], ["ma le ita.", "and the angry"]]},
  {num:10,words:[["Lātou te mulimuli atu", "they will follow after"], ["ia Ieova,", "to the LORD"], ["e tagi lava", "to cry very"], ["ia e pei", "to like"], ["o se leona;", "a lion"], ["a tagi o ia,", "but cry he"], ["ona taalise mai ai lea", "and to be quick from then then"], ["o le fānau mai sisifo.", "the born west"]]},
  {num:11,words:[["Lātou te taalise", "they will to be quick"], ["mai", "from"], ["e pei o se manu lele", "like a animal fly"], ["mai Aikupito,", "from Egypt"], ["e pei o se lupe foi mai le nuu", "like a dove returned the nation"], ["o Asuria;", "Assyria"], ["ou te fa'anonofo foi", "I will make dwelling also"], ["ia te i lātou", "unto them"], ["i o lātou", "in of they"], ["fale,", "house"], ["ua fa'apea mai ai", "and said"], ["Ieova.", "the LORD"]]},
  {num:12,words:[["Ua siosio Efaraima ia te au", "siosio Ephraim unto me"], ["i le pepelo,", "in the false"], ["o le 'āiga foi", "the family also"], ["o Isaraelu", "Israel"], ["ua siosio ia te au", "siosio unto me"], ["i le 'ole'ole;", "in the entreat"], ["a", "but"], ["ua pule pea", "ruled continually"], ["Iuta fa'atasi ma le Atua,", "Judas together and the God"], ["ua fa'amaoni ia", "faithful to"], ["fa'atasi ma le au paia.", "together and the saints"]]},
];
renderVerseSet(_hos_ch_11_Verses, 'hos-ch11-verses');

var _hos_ch_12_Verses = [
  {num:1,words:[["O loo 'ai Efaraima", "is eat Ephraim"], ["le matagi,", "the wind"], ["ua naunau atu", "desired"], ["o ia", "he"], ["i le matagi", "in the wind"], ["mai sasae;", "from east"], ["ua fa'ateleina e", "multiplied you"], ["ia le pepelo", "to the false"], ["ma le malaia", "and the disaster"], ["i aso uma lava;", "all the days very"], ["ua osia foi", "hewn also"], ["la lātou feagaiga", "their covenant"], ["ma Asuria,", "and Assyria"], ["ma", "and"], ["ua avatu", "gave away"], ["i Aikupito suāuu.", "in Egypt oil"]]},
  {num:2,words:[["Ua ia Ieova", "to the LORD"], ["le finauga", "the disputation"], ["ma Iuta,", "and Judas"], ["na te fa'asalaina", "he punished"], ["Iakopo", "Jacob"], ["e tusa ma ana amio;", "according to his conduct"], ["na te taui atu ia te ia", "he a reward to him"], ["e tusa ma ana galuega.", "according to his work"]]},
  {num:3,words:[["Na ia tago", "to reached"], ["i le mulivae", "in the the heel"], ["o lona uso", "his brother"], ["a o", "but of"], ["i ai", "therein"], ["i le manava;", "in the womb"], ["o lona malosi", "his strong"], ["na ia mālō ai", "to kingdom"], ["i le Atua.", "in the God"]]},
  {num:4,words:[["Na ia mālō", "to kingdom"], ["i le agelu,", "in the angel"], ["na manumalo ai", "victory"], ["lava;", "very"], ["na ia tagi,", "to cried"], ["ma aioi atu", "and cry out"], ["ia te ia;", "to him"], ["na ia iloa ia te ia", "to knew to him"], ["i Peteli,", "in Bethel"], ["na tŭlei mai ai", "tŭlei from"], ["foi", "also"], ["lona siufofoga ia te", "his voice unto"], ["i tātou.", "us"]]},
  {num:5,words:[["O Ieova lava", "the LORD very"], ["o le Atua", "of God"], ["o 'au;", "troops"], ["o Ieova", "the LORD"], ["o lona suafa lea", "his name"], ["e manatua ai", "to remember"], ["o ia.", "he"]]},
  {num:6,words:[["O lenei,", "now"], ["ia e toe foi", "to to returned again"], ["i lou Atua;", "in your God"], ["ia e tausi", "to to nurse"], ["le alofa", "the love"], ["ma le fa'amasinoga,", "and the judgment"], ["aua", "for"], ["le aunoa", "the without"], ["ona", "and"], ["e fa'atalitali atu", "to waited"], ["i lou Atua.", "in your God"]]},
  {num:7,words:[["O le fa'atauoa", "the make was to have a disgust at food"], ["ia ,", "to"], ["o", "o"], ["i lona lima", "with his hand"], ["o fua fa'atautau fa'aletatau;", "fruit make to hang up faaletatau"], ["e fiafia o ia", "to pleased he"], ["i le fa'asaua.", "in the cruel"]]},
  {num:8,words:[["Ua fa'apea mai foi", "and said also"], ["a Efaraima,", "of Ephraim"], ["E moni,", "verily/truly"], ["o a'u", "I am"], ["o le mau mea,", "the opinion thing"], ["ua ou maua", "I received"], ["oloa", "goods"], ["mo a'u;", "for me"], ["lātou te", "they will"], ["le iloa", "the know"], ["se leaga ia te au,", "a evil unto me"], ["se mea", "a thing"], ["o se agasala", "a sin"], ["i a'u galuega uma.", "in me work all"]]},
  {num:9,words:[["O a'u foi", "I am also"], ["o Ieova", "the LORD"], ["lou Atua talu", "your God since"], ["mai le nuu", "from the nation"], ["o Aikupito,", "Egypt"], ["ou te toe fa'anofo", "I will again a secondary wife intro-"], ["ia te oe", "unto you"], ["i fale ie fa'apei", "in tent like"], ["o", "o"], ["ona po", "and night"], ["o le tausamiga.", "the feast"]]},
  {num:10,words:[["Na ou tautala atu", "I spoke toward"], ["i perofeta,", "in prophet"], ["na ou fa'ateleina", "I multiplied"], ["fa'aaliga;", "revelation"], ["o le au", "the me"], ["perofeta foi", "prophet also"], ["na ou sauni atu ai", "I he who beg^ins the game"], ["'upu fa'ataoto.", "word lay down"]]},
  {num:11,words:[["Ua leaga lava", "evil very"], ["Kiliata,", "Gilead"], ["e pepelo lava", "to false very"], ["i lātou;", "them"], ["lātou te fai taulaga", "they will make offering"], ["i povi poa", "in cattle captive"], ["i Kilikala;", "in Gilgal"], ["o lātou fata faitaulaga foi,", "they altar also"], ["e pei o faupuegāmaa", "like faupuegāmaa"], ["ia", "to"], ["i atu pue", "in capture"], ["o le laueleele.", "the ground"]]},
  {num:12,words:[["Na sola Iakopo", "escaped Jacob"], ["i le nuu", "in the land"], ["o Suria;", "Syria"], ["na auauna Isaraelu", "servant Israel"], ["e maua ai", "to received"], ["lana avā;", "his wife"], ["na ia leoleo mamoe", "to shepherd"], ["e maua ai", "to received"], ["lana avā.", "his wife"]]},
  {num:13,words:[["O le perofeta", "the prophet"], ["na aveina ae ai", "taken away up"], ["Isaraelu", "Israel"], ["e Ieova mai Aikupito;", "the LORD from Egypt"], ["o le perofeta foi", "the prophet also"], ["na leoleoina ai", "guarded"], ["o ia.", "he"]]},
  {num:14,words:[["Na matuā fa'aonoono", "great vex"], ["Efaraima ia te ia", "Ephraim to him"], [",", ","], ["o le mea lea", "therefore"], ["na te tuu ai", "he put"], ["pea", "continually"], ["lona toto ia te ia;", "his blood to him"], ["o lona luma foi", "his before also"], ["e fa'afoisia ia te ia", "to restored to him"], ["e lona Ali'i.", "by his Lord"]]},
];
renderVerseSet(_hos_ch_12_Verses, 'hos-ch12-verses');

var _hos_ch_13_Verses = [
  {num:1,words:[["Na tautala Efaraima", "spoke Ephraim"], ["ona tupu ai lea", "and king then then"], ["o le tetemu,", "the to tremble"], ["sa mamalu o ia", "glory he"], ["i Isaraelu;", "in Israel"], ["a", "but"], ["ua oo ina", "it came to pass so that"], ["agasala o ia", "sin he"], ["i Paala,", "in a small fly-fishhook"], ["ona oti ai lea.", "and he died"]]},
  {num:2,words:[["A o nei", "but of this"], ["ona po", "and night"], ["ua lātou saga", "they saga"], ["agasala pea,", "sin continually"], ["ua lātou faia", "they did"], ["mo", "for"], ["i lātou", "them"], ["o tupua uamea,", "pillar iron"], ["o tupua", "pillar"], ["ua faia", "made"], ["i o lātou", "in of they"], ["ario,", "silver"], ["e tusa ma lo lātou manatu;", "according to their thought"], ["o le galuega", "the work"], ["a tufuga", "but master builder"], ["na mea uma;", "all things"], ["ua fa'apea la lātou", "saying their"], ["'upu", "word"], ["i ai,", "therein"], ["Ia feasogi", "to to salute by rubbJDg"], ["ma tamai povi tagata", "and son cattle man"], ["o", "o"], ["e fai taulaga.", "to make offering"]]},
  {num:3,words:[["O le mea lea", "therefore"], ["e avea ai", "to become"], ["i lātou", "them"], ["e pei o le puao", "like the puao"], ["i le taeao,", "in the morning"], ["e pei o le sau foi", "like the come also"], ["i le vave ao", "in the quick day"], ["ona mavae atu;", "and passed"], ["e pei o le aputi", "like the aputi"], ["ua lelea", "to be carried away by the"], ["i le matagi", "in the wind"], ["i le mea", "in the thing"], ["e sasa ai", "to a scourge"], ["saito,", "wheat"], ["e pei o le asu foi", "like the asu also"], ["ai", "ai"], ["le alaasu.", "the alaasu"]]},
  {num:4,words:[["A", "but"], ["o a'u", "I am"], ["o Ieova,", "the LORD"], ["o lou Atua talu", "your God since"], ["mai le nuu", "from the nation"], ["o Aikupito,", "Egypt"], ["e te", "by"], ["le iloa", "the know"], ["se tasi Atua", "a one God"], ["na", "na"], ["o a'u;", "I am"], ["e leai foi", "there is not also"], ["se isi fa'aola,", "a other save"], ["na", "na"], ["o a'u.", "I am"]]},
  {num:5,words:[["Na ou iloa oe", "I knew you"], ["i le vao,", "in the wilderness"], ["o le nuu naumati.", "the nation dry"]]},
  {num:6,words:[["E pei ona", "as"], ["fagaina o", "a bay of"], ["i lātou,", "them"], ["sa fa'apea ona", "saying and"], ["maoona o", "maoona of"], ["i lātou;", "them"], ["sa maoona", "maoona"], ["i lātou,", "them"], ["ona fa'amaualulugaina lea", "and exalted"], ["o lātou loto;", "they heart"], ["o le mea lea", "therefore"], ["na lātou fa'agalogalo ai", "they to forget"], ["ia te au.", "unto me"]]},
  {num:7,words:[["O lea", "therefore"], ["ua avea ai", "became"], ["a'u ia te", "me unto"], ["i lātou", "them"], ["e pei o se leona;", "like a lion"], ["ou te lamalama", "I will watched"], ["e pei o se nameri", "like a nameri"], ["i le auala.", "in the auala"]]},
  {num:8,words:[["Ou te oso atu", "I will sit"], ["ia te i lātou", "unto them"], ["e pei o se urosa", "like a bear"], ["ua avea ana", "became his"], ["tama ,", "child"], ["ou te saeia mea", "I will spared thing"], ["e ufitai o lātou", "by ufitai of they"], ["fatu;", "seed"], ["ou te 'aina", "I will edible"], ["i lātou", "them"], ["i lea", "in"], ["mea", "thing"], ["e pei o se leona;", "like a lion"], ["e saeia", "to spared"], ["i lātou", "them"], ["e le manu feai.", "shall not wild beasts"]]},
  {num:9,words:[["Isaraelu e,", "Israel by"], ["ua malaia oe", "disaster you"], ["ia te oe;", "unto you"], ["a", "but"], ["ua ia te au", "unto me"], ["lou fesoasoani.", "your to help"]]},
  {num:10,words:[["O ifea o", "where? of"], ["i ai", "therein"], ["nei", "this"], ["lou tupu", "your king"], ["le", "the"], ["na te fa'aolaina oe", "he saved alive you"], ["i o outou", "in of you all"], ["aai uma? o ifea ou fa'amasino foi", "every city where? I judge also"], ["na e fai mai ai,", "you said"], ["Au mai ia te au", "bring unto me"], ["se tupu", "a king"], ["atoa ma ni ali'i?", "and some Lord"]]},
  {num:11,words:[["Na ou avatu ia te oe", "I gave away unto you"], ["le tupu", "the king"], ["i lo'u tiga;", "in my grieved"], ["na ou aveeseina foi", "I carried away also"], ["o ia", "he"], ["i lo'u ita.", "in my angry"]]},
  {num:12,words:[["Ua fusifusi fa'atasi", "to bind hund and foot together"], ["le leaga o Efaraima;", "the evil of Ephraim"], ["ua teua", "teua"], ["lana agasala.", "his sin"]]},
  {num:13,words:[["E oo ia te ia", "it shall come to pass to him"], ["le fa'atiga", "the afflict"], ["o le fafine", "the women"], ["o le a fānau mai;", "what born"], ["o ia", "he"], ["o le tama fa'alemafaufau,", "the child faalemafaufau"], ["aua", "for"], ["e le tatau ona", "shall not to wring out then"], ["tuai mai o ia", "to be a long time from he"], ["nai", "from"], ["le mea", "the thing"], ["e o ifo ai", "by went down"], ["tama.", "child"]]},
  {num:14,words:[["Ou te laveai", "I will delivered"], ["ia te i lātou", "unto them"], ["ai", "ai"], ["le malosi", "the strong"], ["o le tuugamau;", "the grave"], ["ou te fa'aola", "I will save"], ["ia te i lātou", "unto them"], ["ai", "ai"], ["le oti.", "the die"], ["Le oti e,", "the die by"], ["o fea o", "where?/which? of"], ["i ai", "therein"], ["le malaia mai ia te oe?", "the disaster from you"], ["Le tuugamau e,", "the grave by"], ["o fea o", "where?/which? of"], ["i ai", "therein"], ["se mea", "a thing"], ["e fano ai", "to perish"], ["mai ia te oe?", "from you"], ["e lilo ia te au", "to secret unto me"], ["le salamo.", "the repent"]]},
  {num:15,words:[["E ui", "to although"], ["ina fa'auluolaina o ia", "so that make multiply he"], ["i luma", "in before"], ["o", "o"], ["ona uso,", "and brother"], ["e agi mai le matagi", "by agi from the wind"], ["mai sasae,", "from east"], ["o le matagi", "the wind"], ["o Ieova", "the LORD"], ["e oso atu", "to sit"], ["ia ai", "to"], ["le vao,", "the vegetation"], ["e", "by"], ["pe", "whether"], ["lona vaieli,", "his well"], ["e mate foi", "by mate also"], ["lona punavai;", "his punavai"], ["na te fa'aumatia", "he destroyed"], ["le oa o mea uma", "the riches everything"], ["e manaomia.", "to desired"]]},
  {num:16,words:[["E fa'asalaina Samaria,", "to punished Samaria"], ["auā", "for"], ["ua ia fouvale", "to to rebel"], ["i lona Atua;", "in his God"], ["o le pelu lātou te pauu ai;", "the sword they will fell"], ["e palasi", "to to have children in"], ["a lātou tama meamea,", "their child young"], ["e fa'atiauina o lātou", "to to disembowel of they"], ["fafine", "women"], ["ua totō.", "blood"]]},
];
renderVerseSet(_hos_ch_13_Verses, 'hos-ch13-verses');

var _hos_ch_14_Verses = [
  {num:1,words:[["Isaraelu", "Israel"], ["e", "by"], ["ina toe foi mai ia ia", "so that returned to him"], ["Ieova", "the LORD"], ["lou Atua;", "your God"], ["auā", "for"], ["o lau agasala", "your sin"], ["ua e paū ai.", "you fell"]]},
  {num:2,words:[["Ina sauni atu", "so that he who beg^ins the game"], ["ia ni", "to some"], ["a outou 'upu", "your word"], ["ma toe foi atu", "and went back"], ["ia Ieova.", "to the LORD"], ["Ia outou fa'apea atu ia te ia,", "to you all thus to him"], ["Ia e ave ese", "to to take away"], ["agasala uma,", "sin all"], ["ma talileleia mai,", "and talileleia from"], ["mātou te avatua", "we given away"], ["lava taulaga o mātou", "very offering of we"], ["laugutu.", "lips"]]},
  {num:3,words:[["E le fa'aolaina", "shall not saved alive"], ["i mātou", "us"], ["e Asuria;", "by Assyria"], ["mātou te", "we"], ["le tietie", "the ride"], ["i solofanua;", "in horse"], ["mātou te", "we"], ["le toe fa'apea ane", "the again thus"], ["lava", "very"], ["i galuega", "in work"], ["a o mātou", "but of we"], ["lima,", "hand"], ["O mātou atua", "we God"], ["ia;", "to"], ["auā", "for"], ["e alofagia e", "to favored by"], ["oe", "you"], ["le mātuaoti.", "the mātuaoti"]]},
  {num:4,words:[["Ou te fa'amaloloina lo lātou liliu ese;", "I will healed their turn away"], ["ou te alofa fua", "I will love fruit"], ["ia te i lātou;", "unto them"], ["auā", "for"], ["ua liliueseina", "liliueseina"], ["lo'u ita ia te", "my angry unto"], ["i lātou.", "them"]]},
  {num:5,words:[["E avea a'u", "to become me"], ["ma sau ia", "and come to"], ["Isaraelu;", "Israel"], ["e fuga mai", "to flower from"], ["o ia", "he"], ["e pei o le susana,", "like the susana"], ["e sosolo", "to to run"], ["ona aa", "and aa"], ["e pei o Lepanona.", "like Lebanon"]]},
  {num:6,words:[["E tutupu ae", "to bring forth up"], ["ona tātupu,", "and tātupu"], ["e pei o le olive", "like the olive"], ["lona matagofie;", "his beautiful"], ["e manogi foi", "to fragrant also"], ["ia e pei", "to like"], ["o Lepanona.", "Lebanon"]]},
  {num:7,words:[["O", "O"], ["i lātou", "them"], ["o", "o"], ["e nonofo", "to dwell"], ["i lalo ifo", "in under down"], ["o lona paolo,", "his paolo"], ["e toe ola", "to again life"], ["mai", "from"], ["i lātou", "them"], ["e pei o saito,", "like wheat"], ["e fua mai", "yielding fruit"], ["e pei o le vine;", "like the vine"], ["e ta'ua", "by us two"], ["o ia", "he"], ["e pei o le uaina", "like the wine"], ["o Lepanona.", "Lebanon"], ["E fa'apea mai", "saying from"], ["a Efaraima,", "of Ephraim"]]},
  {num:8,words:[["Se a ea sa'u toe mea", "what indeed? / why? come again thing"], ["e fai", "to make"], ["i tupua?", "in pillar"], ["Ua ou tali atu,", "I responded"], ["ma vaavaai atu", "and looked around"], ["ia te ia;", "to him"], ["e pei o se perosi lauolaola a'u", "like a perosi green me"], ["nei;", "this"], ["e maua", "to received"], ["lau fua mai ia te au.", "your fruit from me"]]},
  {num:9,words:[["Po o ai", "who?"], ["se tasi", "a one"], ["ua poto?", "wise"], ["e iloa lava", "to know very"], ["e ia", "by him"], ["na mea;", "thing"], ["po o ai", "who?"], ["lē fa'autauta?", "the was prudent"], ["e iloa ai", "to know"], ["e ia;", "by him"], ["auā", "for"], ["ua tonu ala", "right way"], ["o Ieova,", "the LORD"], ["e savavali ai", "to walked"], ["e ua amiotonu;", "by righteous"], ["a o", "but of"], ["e fouvale,", "to to rebel"], ["e tautevateva ai", "by tautevateva"], ["i lātou.", "them"]]},
];
renderVerseSet(_hos_ch_14_Verses, 'hos-ch14-verses');

})();