(function() {
var hos_ch_1_Verses = [
  {num:1,words:[["O le afioga", "the a word"], ["a Ieova", "of Jehovah"], ["na oo atu ia Hosea", "oo to hosea"], ["le atalii o Peri,", "the son peri"], ["i ona po o Usia,", "in then night usia"], ["Iotama,", "iotama"], ["Aasa,", "aasa"], ["ma Esekia,", "and esekia"], ["o tupu o Iuta;", "grow Judas"], ["o ona po foi o Ierepoamo", "then night also ierepoamo"], ["le atalii o Ioasa", "the son ioasa"], ["le tupu o Isaraelu.", "the grow Israel"]]},
  {num:2,words:[["O le amataga", "the beginning"], ["o le afioga", "the a word"], ["a Ieova ia Hosea.", "of Jehovah to hosea"], ["Ua fetalai mai Ieova ia Hosea,", "said Jehovah to hosea"], ["Alu ia oe,", "go to you"], ["ia e fai avā", "to to make wife"], ["i le fafine talitane,", "in the woman talitane"], ["ma ia fai māu", "and to make māu"], ["le fanau", "the born"], ["a le faitaaga,", "but the fornication"], ["auā ua matuā faitaaga lava", "for very fornication indeed"], ["le nuu,", "the nation"], ["ua o ese ia Ieova.", "away to Jehovah"]]},
  {num:3,words:[["Ona alu lea o ia", "And he went he"], ["ua fai mana avā o Komeri", "make to get wife komeri"], ["le afafine o Tipelaima,", "the daughter tipelaima"], ["ua to ai foi o", "to plant also"], ["ia,", "to"], ["ua fanau mai ai lona atalii.", "born his son"]]},
  {num:4,words:[["Ua fetalai mai foi Ieova", "said also Jehovah"], ["ia te ia,", "unto him"], ["Ia e faaigoa ia te", "to to called unto"], ["ia,", "to"], ["o Isereelu;", "isereelu"], ["auā e toe itiiti,", "for to again small"], ["ona ou taui atu ai lea", "and I a reward"], ["o le toto o Isereelu", "the blood isereelu"], ["i le aiga o Ieu,", "in the family of ieu"], ["ou te faaumatia foi", "I destroy also"], ["le malo", "the government"], ["o le aiga o Isaraelu.", "the family Israel"]]},
  {num:5,words:[["O lea aso ou te gauia ai", "therefore day I gauia"], ["le aufana", "the aufana"], ["a Isaraelu", "of Israel"], ["i le vanu o Isereelu.", "in the valley isereelu"]]},
  {num:6,words:[["Ua toe to foi o", "again to plant also"], ["ia,", "to"], ["ua fanau ai", "born"], ["le tama teine;", "the child girl"], ["ona fetalai mai lea o Ieova", "and said Jehovah"], ["ia te ia,", "unto him"], ["Ia e faaigoa ia te", "to to called unto"], ["ia,", "to"], ["o Loruama;", "loruama"], ["auā ou te", "for I"], ["le toe alofa atu", "the again love"], ["i le aiga o Isaraelu,", "in the family of Israel"], ["a e ou te matuā aveesea", "but to I very aveesea"], ["i latou.", "them"]]},
  {num:7,words:[["A o le aiga o Iuta,", "but the family Judas"], ["ou te alofa", "I love"], ["i ai,", "therein"], ["ou te faaola ia te", "I save unto"], ["i latou", "them"], ["ona o Ieova lo latou Atua;", "because of Jehovah their God"], ["ou te", "I"], ["le faaola ia te", "the save unto"], ["i latou", "them"], ["i le aufana,", "in the aufana"], ["po o le pelu,", "night the a sword"], ["po o le taua,", "night the war"], ["po o solofanua,", "night horse"], ["po o 'au", "night I"], ["e tietie", "by tietie"], ["i solofanua.", "in horse"]]},
  {num:8,words:[["Ua ia faate'a Loruama", "to faate'a loruama"], ["ma le susu;", "and the milk"], ["ona to ai lea o", "and to plant"], ["ia,", "to"], ["ua fanau mai ai", "born"], ["le tama tane.", "the child man"]]},
  {num:9,words:[["Ona faapea mai ai lea", "and thus from"], ["a le Atua ,", "of God"], ["Ia e faaigoa ia te", "to to called unto"], ["ia,", "to"], ["o Loama;", "loama"], ["auā e le so'u nuu outou,", "for by the so'u nation ye all"], ["e le so outou Atua", "by the so ye all God"], ["foi a'u.", "also I"]]},
  {num:10,words:[["A o le faitau aofai", "but the to count aofai"], ["o le fanauga", "the children"], ["a Isaraelu", "of Israel"], ["e pei", "to to be broken"], ["o le oneone", "the sand"], ["o le sami ia,", "Sea to"], ["e le mafuatia,", "by the mafuatia"], ["e le mafaitaulia;", "by the mafaitaulia"], ["o i le mea foi", "in the thing also"], ["na faapeaina atu ai ia te", "faapeaina unto"], ["i latou,", "them"], ["E le so'u nuu outou,", "by the so'u nation ye all"], ["e iu", "to attain"], ["ina faapeaina atu ai ia te", "let faapeaina unto"], ["i latou,", "them"], ["O atalii", "son"], ["o le Atua soifua outou .", "of God live ye all"]]},
  {num:11,words:[["Ona faapotopotoina faatasi ai lea", "and faapotopotoina once"], ["o le fanauga", "the children"], ["a Iuta,", "of Judas"], ["atoa ma le fanauga", "and the children"], ["a Isaraelu,", "of Israel"], ["latou te tofia foi", "them chosen also"], ["le ta'ita'i", "the ta'ita'i"], ["e toatasi", "to one One"], ["mo i latou,", "for them"], ["latou te o", "them"], ["ae foi", "but also"], ["ma le nuu;", "and the nation"], ["auā e sili", "for to most"], ["le aso o Isereelu.", "the day isereelu"]]},
];
renderVerseSet(hos_ch_1_Verses, 'hos-ch1-verses');

var hos_ch_2_Verses = [
  {num:1,words:[["-2 Ia outou faapea atu", "-2 to ye all thus"], ["i o outou uso,", "in ye all a relative of the same generation and gender"], ["Ama e;", "ignorant by"], ["ia faapea atu foi", "to thus also"], ["i o outou tuafafine,", "in ye all female relative of a male who belongs to the same generation"], ["Ruama e.", "ruama by"], ["Ia outou finau atu", "to ye all finau"], ["i lo outou tinā,", "in the ye all mother"], ["ina finafinau atu ia;", "let finafinau to"], ["auā e le o la'u avā", "for by the my wife"], ["ia,", "to"], ["e le o lana tane", "by the his man"], ["foi a'u;", "also I"], ["ina lafoai ia", "let lafoai to"], ["e ia ana faitaaga ai", "by him his fornication"], ["ia te ia,", "unto him"], ["ma ana mulilua foi ai", "and his whoring also"], ["le va o", "the space"], ["ona susu;", "and milk"]]},
  {num:2,words:[["Ona ou faatauina ai lea", "and I faatauina"], ["o ia ma'u", "he opinion"], ["i tupe", "in St. Thomas bean"], ["e sefulu", "by ten"], ["ma le lima,", "and the five"], ["ma le omera o karite,", "and the omera karite"], ["ma le leteka o karite.", "and the leteka karite"]]},
  {num:3,words:[["ne'i ou talaeseina", "now I talaeseina"], ["ona ofu,", "and garment"], ["ma tuu atu ia te", "and placed unto"], ["ia pei", "to to be broken"], ["ona i ai", "and therein"], ["i le aso", "in the day"], ["na fanau mai ai o", "was born"], ["ia,", "to"], ["e avea foi o ia pei", "to become also he to be broken"], ["o se vao,", "a vegetation"], ["ma avea foi pei", "and become also to be broken"], ["o se nuu naumati,", "a nation naumati"], ["ma ou faaumatia o ia", "and I destroy he"], ["i le fia inu.", "in the want to do something drink"]]},
  {num:4,words:[["Ou te", "I"], ["le alofa atu", "the love"], ["i lana fanau,", "in his born"], ["auā o le fanau", "for the born"], ["a le faitaaga", "but the fornication"], ["i latou.", "them"]]},
  {num:5,words:[["Auā ua faitaaga lo latou tinā,", "for fornication their mother"], ["ua agavale lava", "agavale indeed"], ["le na fanaua", "the born"], ["i latou;", "them"], ["auā na ia faapea", "for to thus"], ["mai,", "from"], ["Ou te mulimuli atu", "I follow after"], ["i e o mananao ia te au,", "in by mananao unto me"], ["o e o au", "who I am"], ["mai a'u mea", "from I thing"], ["e a'i,", "to"], ["ma o'u vai,", "and I water"], ["ma a'u fulufulu mamoe,", "and I fulufulu sheep"], ["ma a'u lino,", "and I lino"], ["ma a'u suāuu,", "and I suāuu"], ["ma a'u mea", "and I thing"], ["e inu.", "to drink"]]},
  {num:6,words:[["O le mea lea,", "therefore/wherefore"], ["faauta,", "behold"], ["ou te pupuni ai lou ala", "I shut your arise"], ["i laau tuitui,", "in tree prickly"], ["ou te siosioina foi o", "I siosioina also"], ["ia i le pa,", "to in the a wall"], ["ia le iloa", "to the known"], ["e ia", "by him"], ["ona ala.", "and arise"]]},
  {num:7,words:[["E mulimuli atu lava o", "to follow after indeed"], ["ia i", "to in"], ["e o mananao ia te", "by mananao unto"], ["ia,", "to"], ["a e le maua atu", "but by the received"], ["i latou", "them"], ["e ia;", "by him"], ["e sailiili o ia ia te", "by sailiili he unto"], ["i latou,", "them"], ["a e le iloa;", "but by the known"], ["ona faapea mai ai lea", "and thus from"], ["o ia,", "he"], ["Ou te alu,", "I go"], ["ou te toe foi", "I again also"], ["i la'u tane muamua,", "in my man first"], ["auā sa sili lo'u manuia anamua,", "for most my peace anamua"], ["i lo'u manuia", "in my peace"], ["i nei", "in this"], ["ona po.", "and night"]]},
  {num:8,words:[["Auā na", "for"], ["le iloa", "the known"], ["e ia,", "by him"], ["o a'u lava", "I am indeed"], ["sa foaiina atu ia te", "given unto"], ["ia o saito,", "to wheat"], ["ma uaina,", "and wine"], ["ma suāuu;", "and suāuu"], ["na a'u faateleina foi ana ario,", "I faateleina also his silver"], ["ma ana auro", "and his gold"], ["na latou saunia", "them prepared"], ["mo Paala.", "for a small fly-fishhook"]]},
  {num:9,words:[["O le mea lea ou te toe", "therefore I again"], ["foi ai,", "also"], ["ma ave ese la'u saito", "and take away my wheat"], ["i ona lava aso,", "in then indeed day"], ["ma la'u uaina", "and my wine"], ["i ona lava po;", "in then indeed night"], ["ou te aveesea foi a'u fulufulu mamoe,", "I aveesea also I fulufulu sheep"], ["ma a'u lino,", "and I lino"], ["sa tuuina atu", "given"], ["e ufiufi a'i lona", "by ufiufi his"], ["le lavalavā.", "the lavalavā"]]},
  {num:10,words:[["O lenei,", "this"], ["ou te faaali lana amio ulavale", "I reveal his conduct mischievous"], ["i luma o", "before"], ["e o mananao ia te", "by mananao unto"], ["ia,", "to"], ["e leai foi", "there is not also"], ["se tasi", "a one"], ["na te laveaiina o ia ai lo'u lima.", "delivered he my five"]]},
  {num:11,words:[["Ou te faaumatia foi lona fiafia uma", "I destroy also his competition all"], ["lava,", "indeed"], ["o ana tausamiga,", "his tausamiga"], ["ma ona masina faatoa vaaia,", "and then moon faatoa seen"], ["ma ona sapati,", "and then sapati"], ["atoa ma", "and"], ["ona nuu uma.", "and nation all"]]},
  {num:12,words:[["Ou te faaumatia", "I destroy"], ["ona vine,", "and vine"], ["ma ona mati,", "and then mati"], ["na ia faapea", "to thus"], ["mai ai,", "from"], ["O o'u taui lava ia", "I a reward indeed to"], ["na au mai ia te au", "bring unto me"], ["e i latou", "by them"], ["ua mananao ia te au;", "mananao unto me"], ["e avea foi", "to become also"], ["i latou ia te au", "them unto me"], ["ma vao matua,", "and vegetation very"], ["e 'aina", "to edible"], ["i latou", "them"], ["e manu feai.", "to animal feai"]]},
  {num:13,words:[["Ua fetalai mai Ieova,", "said Jehovah"], ["Ou te taui atu ia te", "I a reward unto"], ["ia ona o", "to because of"], ["ona po o Paala,", "and night a small fly-fishhook"], ["na ia faamu ai mea manogi", "to faamu thing fragrant"], ["ia te", "unto"], ["i latou;", "them"], ["na ia tifitifi foi ia te", "to tifitifi also unto"], ["ia i", "to in"], ["ona mama,", "and n"], ["ma ona teuga,", "and then teuga"], ["na ia mulimuli atu foi", "to follow after also"], ["i e", "in by"], ["na mananao ia te ia,", "mananao unto him"], ["a ua faagalogalo lava ia te au.", "but to forget indeed unto me"]]},
  {num:14,words:[["A e peitai a'u", "but to however I"], ["faauta,", "behold"], ["ou te faaoleole ia te", "I faaoleole unto"], ["ia,", "to"], ["ma ta'ita'i ia te ia", "and ta'ita'i unto him"], ["i le vao,", "in the wilderness"], ["ou te faamafanafana ia te", "I to hearten unto"], ["ia.", "to"]]},
  {num:15,words:[["Ou te tuuina atu foi", "I will give also"], ["ia te ia ana tovine", "unto him his tovine"], ["i lea mea,", "in thing"], ["ma le vanu o Akori", "and the valley akori"], ["e fai", "to make"], ["ma faitotoa", "and gate"], ["e faamoemoe ai;", "to to expect"], ["e pese foi o ia", "to a song also he"], ["i ai,", "therein"], ["faapei ona fai", "like then make"], ["i ona po", "in then night"], ["ina o teine muli o", "let girl muli"], ["ia,", "to"], ["pei o aso foi", "to be broken day also"], ["na sau ai o ia", "come he"], ["i le nuu o Aikupito.", "in the land Egypt"]]},
  {num:16,words:[["O loo faapea", "thus"], ["mai Ieova,", "from Jehovah"], ["O le aso lava lea", "the day indeed"], ["e oo ai", "it shall come to pass"], ["ona e faaaigoa ia te au,", "and by faaaigoa unto me"], ["O Ise;", "ise"], ["e te", "by"], ["le toe faaigoa ia te au,", "the again called unto me"], ["O Paale.", "paale"]]},
  {num:17,words:[["Auā ou te aveesea", "for I aveesea"], ["i lona gutu o igoa", "in his mouth name"], ["o Paala,", "a small fly-fishhook"], ["e le toe ta'ua lava", "by the again war indeed"], ["i latou", "them"], ["i o latou igoa.", "in them name"]]},
  {num:18,words:[["O le aso foi lea matou te osi ai", "the day also we osi"], ["ma i latou", "and them"], ["le feagaiga", "the covenant"], ["ma manu feai,", "and animal feai"], ["ma manu felelei,", "and fowl"], ["ma mea fetolofi", "and creeping thing"], ["i le eleele;", "in the earth"], ["ou te gausia foi", "I gausia also"], ["le aufana", "the aufana"], ["ma le pelu,", "and the a sword"], ["ma le taua ai", "and the war"], ["le nuu,", "the nation"], ["o a'u", "I am"], ["e taooto ai", "by taooto"], ["i latou", "them"], ["ma le filemu.", "and the peace"]]},
  {num:19,words:[["Ta te osi", "a stroke osi"], ["sa ta feagaiga", "a stroke covenant"], ["ma a'u", "and I"], ["e faavavau;", "forever/everlasting"], ["ta te osi", "a stroke osi"], ["sa ta feagaiga", "a stroke covenant"], ["ma a'u", "and I"], ["i le amiotonu,", "in the righteous"], ["ma le faamasinoga,", "and the judgment"], ["ma le agalelei,", "and the goodness"], ["ma le alofa.", "and the love"]]},
  {num:20,words:[["Ta te osi", "a stroke osi"], ["sa ta feagaiga", "a stroke covenant"], ["ma a'u", "and I"], ["ma le faamaoni;", "and the faithful"], ["e te iloa foi Ieova.", "by known also Jehovah"]]},
  {num:21,words:[["O loo faapea", "thus"], ["mai Ieova,", "from Jehovah"], ["O lea aso,", "therefore day"], ["ou te tali atu ai,", "I respond"], ["ou te tali atu", "I respond"], ["i le lagi,", "in heaven"], ["o ia foi", "he also"], ["na te tali atu", "respond"], ["i le lalolagi.", "in the world"]]},
  {num:22,words:[["E tali atu foi", "to respond also"], ["le lalolagi", "the earth"], ["i le saito,", "in the wheat"], ["ma le uaina,", "and the wine"], ["ma le suāuu;", "and the suāuu"], ["o i latou foi latou te tali atu", "them also them respond"], ["ia Isereelu.", "to isereelu"]]},
  {num:23,words:[["Ou te totōina o ia", "I totōina he"], ["i le eleele", "in the earth"], ["e fai mo'u;", "to make many"], ["ou te alofa foi", "I love also"], ["i le", "in the"], ["sa le alofagia;", "the blessed"], ["ou te faapea atu foi", "I thus also"], ["i le", "in the"], ["ua le so'u nuu,", "the so'u nation"], ["O lo'u nuu oe;", "my nation you"], ["ona latou faapea", "and them thus"], ["mai ai lea,", "from"], ["O lo matou Atua.", "our (excl) God"]]},
];
renderVerseSet(hos_ch_2_Verses, 'hos-ch2-verses');

var hos_ch_3_Verses = [
  {num:1,words:[["Ua fetalai mai Ieova ia te au,", "said Jehovah unto me"], ["Ia e toe alu,", "to to again go"], ["ia e loto atu", "to to heart"], ["i se fafine", "in a woman"], ["o le", "the"], ["ua loto", "heart"], ["i ai lana uo,", "therein his uo"], ["a o le fafine mulilua", "but the woman whoring"], ["ia,", "to"], ["e pei", "to to be broken"], ["ona alofa o Ieova", "and love Jehovah"], ["i le fanauga", "in the children"], ["a Isaraelu o", "of Israel"], ["e faasagasaga", "by faasagasaga"], ["i atua ese,", "in God away"], ["ma mananao", "and mananao"], ["i ipu uaina.", "in cup wine"]]},
  {num:2,words:[["Ona ou faatauina ai lea", "and I faatauina"], ["o ia ma'u", "he opinion"], ["i tupe", "in St. Thomas bean"], ["e sefulu", "by ten"], ["ma le lima,", "and the five"], ["ma le omera o karite,", "and the omera karite"], ["ma le leteka o karite.", "and the leteka karite"]]},
  {num:3,words:[["Na a'u fai atu foi", "I said to also"], ["ia te ia,", "unto him"], ["E te nofo faatali", "by dwell wait"], ["mai ia te au", "from I"], ["i aso", "in day"], ["e tele,", "to great"], ["aua e te faitaaga,", "for by fornication"], ["aua e te nofo", "for by dwell"], ["i se tane;", "in a man"], ["ou te nofo faatali foi", "I dwell wait also"], ["ia te oe.", "unto thee"]]},
  {num:4,words:[["Auā e tele aso", "for to great day"], ["e nonofo ai", "to dwelling"], ["le fanauga", "the children"], ["a Isaraelu,", "of Israel"], ["e leai", "there is not"], ["se tupu,", "a grow"], ["e leai", "there is not"], ["se alii,", "a Lord"], ["e leai", "there is not"], ["se taulaga,", "a offering"], ["e leai", "there is not"], ["se fata faitaulaga,", "a altar"], ["e leai foi", "there is not also"], ["se efota po", "a efota night"], ["o se tupua.", "a idol"]]},
  {num:5,words:[["E mulimuli ane,", "to follow after"], ["e toe foi", "to again also"], ["mai le fanauga", "from the children"], ["a Isaraelu,", "of Israel"], ["latou te saili ia Ieova lo latou Atua,", "them seek to Jehovah their God"], ["ma Tavita lo latou tupu;", "and David their grow"], ["latou te matatau foi ia Ieova", "them fear also to Jehovah"], ["ma lona agalelei", "and his goodness"], ["i ona po", "in then night"], ["e gata ai.", "to a snake"]]},
];
renderVerseSet(hos_ch_3_Verses, 'hos-ch3-verses');

var hos_ch_4_Verses = [
  {num:1,words:[["Le fanauga", "the children"], ["a Isaraelu", "of Israel"], ["e,", "by"], ["ia outou faalogologo", "to ye all listen"], ["mai i le afioga", "from in the a word"], ["a Ieova;", "of Jehovah"], ["auā o loo ia Ieova", "for to Jehovah"], ["le finauga", "the argument"], ["ma e o nonofo", "and by dwelling"], ["i le nuu;", "in the land"], ["auā e leai", "for there is not"], ["se faamaoni,", "a faithful"], ["e leai", "there is not"], ["se alofa,", "a love"], ["e leai foi", "there is not also"], ["se na te iloa", "a known"], ["le Atua", "God"], ["i le nuu.", "in the land"]]},
  {num:2,words:[["O loo o tauto,", "to take an oath"], ["ma tala pepelo,", "and side false"], ["ma fasioti tagata,", "and killed man"], ["ma gaoi,", "and to steal"], ["ma mulilua,", "and whoring"], ["ua latou faasaua lava,", "them to be oppressive indeed"], ["ua fepaia'i toto.", "fepaia'i blood"]]},
  {num:3,words:[["O le mea lea", "therefore/wherefore"], ["e faanoanoa ai", "to to mourn"], ["le nuu,", "the nation"], ["e tauāu", "by tauāu"], ["ina vaivai o", "let weak"], ["i latou uma o", "them all"], ["e nonofo ai;", "to dwelling"], ["atoa ma manu vaefa,", "and beast"], ["ma manu felelei,", "and fowl"], ["e mavae atu foi lava", "to a parting also indeed"], ["o i'a", "fish"], ["o le sami.", "Sea"]]},
  {num:4,words:[["A e aua ne'i", "but to for now"], ["i ai", "therein"], ["se tagata", "a man"], ["e finau atu,", "by finau"], ["ma aoai atu", "and aoai"], ["i se tasi tagata;", "in a one man"], ["auā o lou nuu", "for your nation"], ["ua pei o", "to be broken"], ["e fefinauai", "by fefinauai"], ["ma le ositaulaga.", "and the high priest"]]},
  {num:5,words:[["O lea", "therefore"], ["e te paū ai", "by paū"], ["i le ao,", "in the day"], ["e pauu foi", "to fell also"], ["le perofeta faatasi", "the prophet once"], ["ma oe", "and you"], ["i le po;", "in the night"], ["ou te fasioti foi lou tinā.", "I killed also your mother"]]},
  {num:6,words:[["Ua faaumatia lo'u nuu", "destroy my nation"], ["ina ua leai", "let there was not"], ["se poto;", "a wise"], ["o oe foi", "you also"], ["na e tetee atu", "to to refuse"], ["i le poto,", "in the wise"], ["o le mea lea ou te tetee atu ai", "therefore I to refuse"], ["ia te oe,", "unto thee"], ["e le fai oe", "by the make you"], ["ma ositaulaga ia te au;", "and high priest unto me"], ["ua e faagalogalo", "to to forget"], ["le tulafono", "the law"], ["a lou Atua,", "but your God"], ["o a'u foi,", "I am also"], ["ou te faagalogalo", "I to forget"], ["i lau fanau.", "in your born"]]},
  {num:7,words:[["E pei", "to to be broken"], ["ona faatoateleina o", "and faatoateleina"], ["i latou,", "them"], ["ua faapea", "saying"], ["ona agasala mai o", "and sin from"], ["i latou ia te au;", "them unto me"], ["ou te liliu", "I turned"], ["i le mā lo latou mamalu.", "in the First person dual exclusive their glory"]]},
  {num:8,words:[["Ua latou aai", "them eat"], ["le agasala", "the sin"], ["a lo'u nuu,", "but my nation"], ["ma ua latou naunau", "and them naunau"], ["i lo latou leaga.", "in the them evil"]]},
  {num:9,words:[["E oo", "it shall come to pass"], ["ina gatusa lava", "let equal indeed"], ["o le nuu", "the nation"], ["ma le ositaulaga;", "and the high priest"], ["ou te taui atu foi", "I a reward also"], ["ia te", "unto"], ["i latou", "them"], ["a latou amio,", "but them conduct"], ["ou te taui foi ia te", "I a reward also unto"], ["i latou", "them"], ["a latou mea", "but them thing"], ["ua fai.", "make"]]},
  {num:10,words:[["Auā latou te aai,", "for them eat"], ["a e le maoona;", "but by the maoona"], ["e faitaaga", "to fornication"], ["i latou,", "them"], ["a e le faatoateleina;", "but by the faatoateleina"], ["auā ua", "for"], ["le toe usiusitai", "the again usiusitai"], ["i latou ia Ieova.", "them to Jehovah"]]},
  {num:11,words:[["O le faitaaga,", "the fornication"], ["ma le uaina,", "and the wine"], ["ma le uaina fou", "and the wine new"], ["e aveeseina ai", "by aveeseina"], ["le loto.", "the heart"]]},
  {num:12,words:[["O lo'u nuu", "my nation"], ["ua latou fesili", "them to question"], ["i lo latou laau;", "in the them tree"], ["ua faasino mai ai lo latou tootoo", "declare from their tootoo"], ["ia te", "unto"], ["i latou;", "them"], ["auā o le fia faitaaga", "for the want to do something fornication"], ["ua faaseseina ai", "faaseseina"], ["i latou ,", "them"], ["ma ua latou o ese nai lo latou Atua", "and them away from their God"], ["e faitaaga ai.", "to fornication"]]},
  {num:13,words:[["Ua latou faitaulaga", "them priest"], ["i tumutumu o mauga,", "in tumutumu mountain"], ["ma faamu mea manogi", "and faamu thing fragrant"], ["i mea maupuepue,", "in thing maupuepue"], ["ma lalo ifo o aluna,", "and under aluna"], ["ma lipeno,", "and lipeno"], ["ma tapeneto,", "and tapeneto"], ["auā ua lelei lo latou paolo;", "for that it was good their paolo"], ["o le mea lea", "therefore/wherefore"], ["e faitaaga ai o outou afafine,", "to fornication ye all daughter"], ["e mulilulua foi", "to whoring also"], ["a outou avā.", "but ye all wife"]]},
  {num:14,words:[["Ou te", "I"], ["le faasalaina o outou afafine", "the faasalaina ye all daughter"], ["pe a latou faitaaga,", "whether but them fornication"], ["ma a outou avā", "and but ye all wife"], ["pe a latou mulilulua;", "whether but them whoring"], ["auā o", "for"], ["i latou lava", "them indeed"], ["ua latou o ese faatasi", "them away once"], ["ma fafine faitaaga,", "and woman fornication"], ["ua latou faitaulaga faatasi", "them priest once"], ["ma fafine talitane;", "and woman talitane"], ["o le nuu foi", "the nation also"], ["ua le mafaufau", "the think"], ["e pauu", "to fell"], ["i latou.", "them"]]},
  {num:15,words:[["Isaraelu e,", "Israel by"], ["e ui", "to although"], ["ina e faitaaga,", "let to fornication"], ["a e aua ne'i agasala Iuta;", "but to for now sin Judas"], ["aua tou te o", "for second person plural"], ["mai i Kilikala,", "from in kilikala"], ["aua tou te o", "for second person plural"], ["ae i Petavene,", "but in petavene"], ["aua foi tou te tauto,", "for also second person plural to take an oath"], ["O loo soifua Ieova.", "live Jehovah"]]},
  {num:16,words:[["Auā e faapei", "for to like"], ["ona vaogata", "and disobedient"], ["o se povi fafine taanoa,", "a cattle woman an animal that is weaned"], ["ua faapea", "saying"], ["ona vaogata o Isaraelu;", "and disobedient Israel"], ["a e fagaina", "but by fagaina"], ["i latou", "them"], ["i nei", "in this"], ["ona po", "and night"], ["e Ieova", "to Jehovah"], ["e faapei", "to like"], ["o se tamai mamoe", "a son sheep"], ["i le mea lautele.", "in the thing lautele"]]},
  {num:17,words:[["Ua pipii Efaraima", "pipii Ephraim"], ["i tupua;", "in idol"], ["ina tuu ai pea ia", "let put continually to"], ["ia te ia.", "unto him"]]},
  {num:18,words:[["A uma lo latou inuga'ava,", "but all their inuga'ava"], ["ua matuā faitaaga", "very fornication"], ["i latou;", "them"], ["ua loto atu o latou alii", "heart them Lord"], ["i mea", "in thing"], ["e masiasi ai.", "to to be ashamied"]]},
  {num:19,words:[["Ua saisaitia o ia", "saisaitia he"], ["e le matagi", "by the wind"], ["i ona apaau,", "in then a wing"], ["e masiasi foi", "to to be ashamied also"], ["i latou", "them"], ["ona o", "because of"], ["a latou taulaga.", "but them offering"]]},
];
renderVerseSet(hos_ch_4_Verses, 'hos-ch4-verses');

var hos_ch_5_Verses = [
  {num:1,words:[["Le au ositaulaga", "the I high priest"], ["e,", "by"], ["faalogologo mai ia", "listen from to"], ["i lenei mea.", "in this thing"], ["Le aiga o Isaraelu", "the family Israel"], ["e,", "by"], ["ina faalogologo mai ia.", "let listen from to"], ["Le aiga", "the family"], ["o le tupu", "the grow"], ["e,", "by"], ["ina liliu mai ia o outou fofoga,", "let turned from to ye all face"], ["auā ua faasalaina outou,", "for faasalaina ye all"], ["ua avea outou", "become ye all"], ["ma matāsele", "and matāsele"], ["i Mesepa,", "in mesepa"], ["ma upega", "and upega"], ["ua folasia", "folasia"], ["i Tapora.", "in tapora"]]},
  {num:2,words:[["Ua faateleina", "faateleina"], ["le fasi", "the kill"], ["e i latou", "by them"], ["ua liliu ese,", "turned away"], ["a o a'u,", "but I am"], ["ou te aoai atu ia te", "I aoai unto"], ["i latou uma.", "them all"]]},
  {num:3,words:[["O a'u", "I am"], ["ua ou iloa Efaraima,", "I known Ephraim"], ["o Isaraelu foi", "Israel also"], ["ua le lilo lava ia", "the secret indeed to"], ["ia te au;", "unto me"], ["auā,", "for"], ["Efaraima e,", "Ephraim by"], ["ua e faitaaga nei,", "to fornication this"], ["ua leaga Isaraelu.", "evil Israel"]]},
  {num:4,words:[["Latou te", "them"], ["le sauniuni", "the sauniuni"], ["a latou galuega", "but them work"], ["ina ia latou liliu", "so that them turned"], ["mai i lo latou Atua;", "from in the them God"], ["auā o", "for"], ["i totonu ia te", "in inside unto"], ["i latou", "them"], ["le fia faitaaga,", "the want to do something fornication"], ["latou te", "them"], ["le iloa Ieova.", "the known Jehovah"]]},
  {num:5,words:[["Ua molimau", "a witness"], ["le faamaualuga o Isaraelu", "the to be proud Israel"], ["i o latou luma,", "before them"], ["e pauu Isaraelu", "to fell Israel"], ["ma Efaraima", "and Ephraim"], ["i a latou agasala;", "in but them sin"], ["e paū foi Iuta faatasi", "by paū also Judas once"], ["ma i latou.", "and them"]]},
  {num:6,words:[["Latou te o atu", "them"], ["ma a latou mamoe", "and but them sheep"], ["ma a latou povi", "and but them cattle"], ["e sailiili atu ai ia Ieova;", "by sailiili to Jehovah"], ["a e latou te", "but by them"], ["le maua;", "the received"], ["ua afio ese o ia", "dwell (respectful) away he"], ["ia te", "unto"], ["i latou.", "them"]]},
  {num:7,words:[["Ua pepelo", "false"], ["i latou ia Ieova;", "them to Jehovah"], ["auā ua fanau", "for born"], ["e i latou", "by them"], ["a latou tama ese;", "but them child away"], ["o le a 'aina nei", "what edible this"], ["i latou,", "them"], ["atoa ma o latou tofi", "and them appoint"], ["i le masina", "in the moon"], ["e tasi .", "by one"]]},
  {num:8,words:[["Ia outou ilia", "to ye all ilia"], ["le sofao", "the sofao"], ["i Kipea,", "in kipea"], ["ma le pu", "and the the tail"], ["i Rama;", "in rama"], ["ia outou alalaga", "to ye all alalaga"], ["i Petavene;", "in petavene"], ["Peniamina e,", "Benjamin by"], ["o loo mulimuli atu o", "follow after"], ["ia ia te oe.", "to unto thee"]]},
  {num:9,words:[["E faatafunaina Efaraima", "by faatafunaina Ephraim"], ["i ona po", "in then night"], ["o le aoaiga;", "the aoaiga"], ["ua ou faailoaina atu", "I faailoaina"], ["i itu aiga o Isaraelu,", "in itu family Israel"], ["o le upu moni lava.", "the word true indeed"]]},
  {num:10,words:[["O alii o Iuta", "Lord Judas"], ["sa faapei o tagata", "like man"], ["e sii", "to lift up"], ["le tuaoi", "the border"], ["i latou;", "them"], ["ou te liligi atu lo'u ita faapei", "I to pour my angry like"], ["o le vai ia te", "the water unto"], ["i latou.", "them"]]},
  {num:11,words:[["Ua faasauaina Efaraima,", "faasauaina Ephraim"], ["ua lomia", "lomia"], ["i le faamasinoga;", "in the judgment"], ["auā ua usiusitai o ia", "for usiusitai he"], ["ma lona loto", "and his heart"], ["i le poloaiga.", "in the commandment"]]},
  {num:12,words:[["O a'u foi", "I am also"], ["e pei", "to to be broken"], ["o se mogamoga", "a cockroach"], ["i Efaraima;", "in Ephraim"], ["e pei", "to to be broken"], ["o se mea", "a thing"], ["e pala foi", "to a muddy deposit in the sea also"], ["i le aiga o Iuta.", "in the family of Judas"]]},
  {num:13,words:[["Na iloa", "known"], ["e Efaraima lona ma'i,", "to Ephraim his from"], ["na iloa foi", "known also"], ["e Iuta lona manua,", "to Judas his manua"], ["ona alu lea o Efaraima", "And he went Ephraim"], ["i Asuria,", "in Assyria"], ["na alu lana feau ia Iarepa", "go his feau to iarepa"], ["le tupu;", "the grow"], ["a ua", "but"], ["le mafai lava ia te", "the able indeed unto"], ["ia ona faamalolo ia te outou,", "to then faamalolo unto you"], ["pe faamafuina o outou manua.", "whether faamafuina ye all manua"]]},
  {num:14,words:[["Auā e avea a'u", "for to become I"], ["e pei", "to to be broken"], ["o se leona ia Efaraima,", "a leona to Ephraim"], ["e pei", "to to be broken"], ["o se leona taanoa foi", "a leona an animal that is weaned also"], ["i le aiga o Iuta;", "in the family of Judas"], ["o a'u lava ou te saeia", "I am indeed I saeia"], ["ma alu ese,", "and go away"], ["ou te aveesea,", "I aveesea"], ["e leai foi", "there is not also"], ["se na te laveaiina.", "a delivered"]]},
  {num:15,words:[["Ou te alu,", "I go"], ["ou te toe foi lava", "I again also indeed"], ["i le mea ou te nofo ai,", "in the thing I dwell"], ["seia faasalaina lava", "until faasalaina indeed"], ["i latou,", "them"], ["ma latou saili ia te au;", "and them seek unto me"], ["latou te vave saili ia te au", "them quick seek unto me"], ["pe a puapuagatia", "whether but puapuagatia"], ["i latou.", "them"]]},
];
renderVerseSet(hos_ch_5_Verses, 'hos-ch5-verses');

var hos_ch_6_Verses = [
  {num:1,words:[["O mai ia,", "from to"], ["ina tatou toe foi atu", "let us again also"], ["ia Ieova;", "to Jehovah"], ["auā o ia", "for he"], ["ua na saeia,", "saeia"], ["na te faamaloloina foi", "faamaloloina also"], ["i tatou;", "in us"], ["ua ia fasia,", "to struck"], ["na te fofoina foi", "fofoina also"], ["i tatou.", "in us"]]},
  {num:2,words:[["Na te faaolaina", "saved"], ["mai i tatou", "from in us"], ["pe a mavae aso", "whether but a parting day"], ["e lua;", "by two"], ["a oo", "but oo"], ["i lona tolu o aso", "in his three day"], ["na te faatutūina", "faatutūina"], ["i tatou,", "in us"], ["tatou te ola", "us life"], ["mai ai", "from"], ["i ona luma.", "before him"]]},
  {num:3,words:[["Tatou te iloa foi o loo", "us known also"], ["o tatou tausisi atu ia iloa Ieova;", "us tausisi to known Jehovah"], ["ua saunia lona afio atu", "prepared his dwell (respectful)"], ["e pei", "to to be broken"], ["o le taeao,", "the morning"], ["e afio mai foi o", "to dwell (respectful) from also"], ["ia ia te", "to unto"], ["i tatou", "in us"], ["e pei", "to to be broken"], ["o le", "the"], ["ua,", "ua,"], ["e pei", "to to be broken"], ["o le timu mulimuli", "the rain follow after"], ["ma le timu muamua", "and the rain first"], ["i le eleele.", "in the earth"]]},
  {num:4,words:[["Efaraima e,", "Ephraim by"], ["se a ea", "a but to rise (as a diver to the sur-"], ["se mea ou te faia", "a thing I made"], ["ia te oe? Iuta", "unto thee Judas"], ["e,", "by"], ["se a ea", "a but to rise (as a diver to the sur-"], ["se mea ou te faia", "a thing I made"], ["ia te oe? auā", "unto thee for"], ["ua pei", "to be broken"], ["o le puao", "the puao"], ["i le taeao la outou amio lelei,", "in the morning your conduct good"], ["e pei", "to to be broken"], ["o le sau foi", "the come also"], ["i le vave ao", "in the quick day"], ["ona mavae atu.", "and a parting"]]},
  {num:5,words:[["O le mea lea", "therefore/wherefore"], ["ua ou fasia ai", "I struck"], ["i latou", "them"], ["e le au perofeta,", "by the I prophet"], ["ua ou fasiotia", "I slain"], ["i latou", "them"], ["i upu", "in word"], ["a lo'u gutu;", "but my mouth"], ["o au faamasinoga foi", "I am judgment also"], ["o le malamalama", "the light"], ["e alu atu lea.", "to go away"]]},
  {num:6,words:[["Auā o le alofa ou te loto", "for the love I heart"], ["i ai,", "therein"], ["a e le", "but by the"], ["o le taulaga;", "the offering"], ["ia iloa foi", "to known also"], ["le Atua", "God"], ["e sili lea", "to most"], ["i lo'u manatu", "in my thought"], ["i taulaga mu.", "in burnt offering"]]},
  {num:7,words:[["A ua latou soli", "but them to tread upon"], ["le feagaiga,", "the covenant"], ["e pei o Atamu;", "to to be broken Adam"], ["ua latou pepelo ia te au", "them false unto me"], ["i lea mea.", "in thing"]]},
  {num:8,words:[["O Kiliata", "kiliata"], ["o le aai lea o", "the eat"], ["e fai amio leaga,", "to make iniquity"], ["o loo leaga,", "evil"], ["i le toto.", "in the blood"]]},
  {num:9,words:[["Faapei ona lamalama", "like then lamalama"], ["i se tagata o", "in a man"], ["e fao mea,", "to to seize thing"], ["e faapea foi", "by thus also"], ["le au ositaulaga", "the I high priest"], ["ona fasioti tagata", "and killed man"], ["i le ala", "in the arise"], ["i Sekema;", "in sekema"], ["auā ua ulavale", "for mischievous"], ["i latou.", "them"]]},
  {num:10,words:[["Ua a'u iloa", "I known"], ["i le aiga o Isaraelu", "in the family of Israel"], ["le mea", "the thing"], ["e matuā leaga;", "to very evil"], ["ua i ai", "therein"], ["le faitaaga o Efaraima,", "the fornication Ephraim"], ["ua leaga Isaraelu.", "evil Israel"]]},
  {num:11,words:[["Iuta e,", "Judas by"], ["ua tuu", "put"], ["mo oe lava", "for you indeed"], ["le seleselegāsaito", "the seleselegāsaito"], ["ina ua ou faafoisia", "let I faafoisia"], ["le tafeaga", "the exiles in wa^"], ["a lo'u nuu.", "but my nation"]]},
];
renderVerseSet(hos_ch_6_Verses, 'hos-ch6-verses');

var hos_ch_7_Verses = [
  {num:1,words:[["Na fai", "make"], ["a a'u faamaloloina o Isaraelu,", "but I faamaloloina Israel"], ["ona mānu mai ai lea", "and mānu from"], ["o le leaga o Efaraima", "the evil Ephraim"], ["ma amio leaga", "and iniquity"], ["a Samaria;", "of Samaria"], ["auā ua latou fai", "for them make"], ["le amio pepelo;", "the conduct false"], ["e ulufale mai", "by ulufale from"], ["le gaoi,", "the to steal"], ["a e osofia", "but by osofia"], ["i fafo", "in outside"], ["e le au fao mea.", "by the I to seize thing"]]},
  {num:2,words:[["Latou to", "them to plant"], ["le faapea ifo", "the thus"], ["i o latou loto,", "in them heart"], ["Ou te manatua la latou amio leaga uma;", "I remember their iniquity all"], ["o lenei,", "this"], ["ua siosiomia", "siosiomia"], ["i latou", "them"], ["i a latou lava galuega,", "in but them indeed work"], ["ua i o'u luma ia mea.", "before me to thing"]]},
  {num:3,words:[["Latou te faafiafia", "them to please"], ["le tupu", "the grow"], ["i a latou amio leaga;", "in but them iniquity"], ["atoa ma alii", "and Lord"], ["i a latou tala pepelo.", "in but them side false"]]},
  {num:4,words:[["Ua mulilulua", "whoring"], ["i latou uma;", "them all"], ["pei se ogaumu", "to be broken a ogaumu"], ["i latou", "them"], ["ua faaaasaina", "faaaasaina"], ["e le fai areto;", "by the make bread"], ["ua le toe tafu", "the again to make up the fire"], ["pe a uma", "whether but all"], ["ona lolomi", "and lolomi"], ["o le palugāfalaoa seia faafefeteina.", "the palugāfalaoa until faafefeteina"]]},
  {num:5,words:[["O le aso", "the day"], ["o lo tatou tupu", "our grow"], ["na mama'i ai alii", "mama'i Lord"], ["i le oona o uaina;", "in the oona wine"], ["na ia faaloaloa atu lona lima faatasi", "to to stretch out his five once"], ["ma ē tauemu.", "and who tauemu"]]},
  {num:6,words:[["Auā ua latou faalatalata", "for them faalatalata"], ["ma o latou loto,", "and them heart"], ["e pei", "to to be broken"], ["o se ogaumu,", "a ogaumu"], ["a o latou o lamalama;", "but them lamalama"], ["ua aoina o moe lo latou fai areto,", "aoina sleep their make bread"], ["ua mu", "mu"], ["i le taeao pei", "in the morning to be broken"], ["se afi mumū.", "a fire mumū"]]},
  {num:7,words:[["Ua aasa", "aasa"], ["i latou uma", "them all"], ["e pei", "to to be broken"], ["o se ogaumu,", "a ogaumu"], ["ua latou faaumatia o latou alii faamasino;", "them destroy them Lord a judge"], ["ua pauu o latou tupu uma,", "fell them grow all"], ["e leai so latou", "there is not so them"], ["e valaau ia te au.", "to call unto me"]]},
  {num:8,words:[["O Efaraima", "Ephraim"], ["ua numia o ia", "numia he"], ["e ia faatasi", "by him once"], ["ma le nuu;", "and the nation"], ["o Efaraima", "Ephraim"], ["o le potoi areto ia", "the a cake bread to"], ["e lei liua.", "to whale's teeth wide (as a canoe of too"]]},
  {num:9,words:[["Ua faaumatia", "destroy"], ["e tagata ese lona malosi,", "to man away his strong"], ["a ua", "but"], ["le iloa", "the known"], ["e ia;", "by him"], ["ua pule", "rule"], ["le sinā o lona lauulu,", "the sinā his the hair of the head"], ["a ua", "but"], ["le iloa", "the known"], ["e ia.", "by him"]]},
  {num:10,words:[["Ua molimau", "a witness"], ["le faamaualuga o Isaraelu", "the to be proud Israel"], ["i o latou luma;", "before them"], ["e ui lava", "to although indeed"], ["i ia mea uma,", "in to all things"], ["ua latou", "them"], ["le toe foi ia Ieova lo latou Atua,", "the again also to Jehovah their God"], ["ua latou", "them"], ["le saili foi ia te", "the seek also unto"], ["ia.", "to"]]},
  {num:11,words:[["O Efaraima foi", "Ephraim also"], ["e pei", "to to be broken"], ["o se lupe valea ia,", "a dove valea to"], ["e leai sona mafaufau;", "there is not sona think"], ["latou te valaau ia Aikupito,", "them call to Egypt"], ["ua o foi", "also"], ["i latou", "them"], ["i Asuria.", "in Assyria"]]},
  {num:12,words:[["A latou o,", "but them"], ["ou te lafo la'u upega", "I cloth used as gratuity for a talking chief my upega"], ["i luga ia te", "in above unto"], ["i latou;", "them"], ["ou te lafo", "I cloth used as gratuity for a talking chief"], ["i lalo ia te", "in under unto"], ["i latou pei ni manu felelei;", "them to be broken some fowl"], ["ou te sasa foi ia te", "I a scourge also unto"], ["i latou", "them"], ["e pei", "to to be broken"], ["ona faalogo", "and hearken"], ["i ai lo latou potopotoga.", "therein their gathering"]]},
  {num:13,words:[["O i talofa ia te", "in hello unto"], ["i latou!", "them"], ["auā ua sosola ese", "for fled away"], ["i latou ia te au;", "them unto me"], ["ia malaia", "to a calamity"], ["i latou!", "them"], ["auā ua latou fouvale ia te au;", "for them to rebel unto me"], ["na ou togiola foi ia te", "I atonement also unto"], ["i latou,", "them"], ["a ua latou tala pepelo", "but them side false"], ["ia leaga ai a'u.", "to evil I"]]},
  {num:14,words:[["Ua le valaau", "the call"], ["mai i latou ia te au", "from them unto me"], ["ma o latou loto,", "and them heart"], ["ina ua latou uio", "let them uio"], ["i o latou moega;", "in them moega"], ["latou te faapotopoto", "them gather together"], ["i saito", "in wheat"], ["ma uaina;", "and wine"], ["latou te o ese ia te au.", "them away unto me"]]},
  {num:15,words:[["O a'u foi,", "I am also"], ["na ou a'oa'o atu,", "I excellent"], ["na ou faamalosiina o latou lima,", "I faamalosiina them five"], ["a ua latou taupulepule", "but them taupulepule"], ["i mea", "in thing"], ["e leaga ai a'u.", "to evil I"]]},
  {num:16,words:[["Ua latou toe foi,", "them again also"], ["a e le o lē Silisili ese", "but by the not very much away"], ["ua latou foi", "them also"], ["i ai;", "therein"], ["e pei", "to to be broken"], ["o le aufana pepelo", "the aufana false"], ["i latou;", "them"], ["e pauu o latou alii", "to fell them Lord"], ["i le pelu", "in the a sword"], ["ona o le faasiasia o latou laulaufaiva;", "because of the haughty them tongue"], ["e fai", "to make"], ["mo latou gao lea mea", "for them gao thing"], ["i le nuu o Aikupito.", "in the land Egypt"]]},
];
renderVerseSet(hos_ch_7_Verses, 'hos-ch7-verses');

var hos_ch_8_Verses = [
  {num:1,words:[["Ia e ili", "to by ili"], ["le pu;", "the the tail"], ["e sau o ia", "to come he"], ["e pei", "to to be broken"], ["o se aeto", "a aeto"], ["i le aiga o Ieova;", "in the family of Jehovah"], ["auā ua latou soli la'u feagaiga,", "for them to tread upon my covenant"], ["ma ua latou fouvale", "and them to rebel"], ["i la'u tulafono.", "in my law"]]},
  {num:2,words:[["E alalaga", "by alalaga"], ["i latou ia te au,", "them unto me"], ["Lo matou Atua", "our God"], ["e,", "by"], ["o Isaraelu", "Israel"], ["i matou ,", "in we"], ["ua matou iloa oe.", "we known you"]]},
  {num:3,words:[["Ua lafoaiina", "lafoaiina"], ["e Isaraelu", "to Israel"], ["le mea lelei;", "the thing good"], ["e tuliloaina o ia", "by tuliloaina he"], ["e le", "by the"], ["ua ita ia te ia .", "angry unto him"]]},
  {num:4,words:[["Ua latou tofia tupu", "them chosen grow"], ["a e le", "but by the"], ["mai ia te au;", "from I"], ["ua latou tofia alii", "them chosen Lord"], ["a e le iloa", "but by the known"], ["e a'u;", "to I"], ["o latou ario,", "them silver"], ["ma o latou auro", "and them gold"], ["ua latou fai a'i tupua", "them thereby idol"], ["mo i latou,", "for them"], ["ina ia faaumatia ai", "so that destroy"], ["i latou .", "them"]]},
  {num:5,words:[["Samaria e,", "Samaria by"], ["ua lafoaiina oe", "lafoaiina you"], ["e lau tamai povi;", "by your son cattle"], ["ua tupu lo'u ita ia te", "grow my angry unto"], ["i latou;", "them"], ["pe latou te", "whether them"], ["le mafai seia afea", "the able until when ?"], ["ona mamā?", "and clean"]]},
  {num:6,words:[["Auā mai ia Isaraelu lava", "for from to Israel indeed"], ["ia;", "to"], ["na faia o ia", "made he"], ["e le tufuga;", "by the master builder"], ["e le", "by the"], ["o le Atua lava ia,", "of God indeed to"], ["o le mea lea", "therefore/wherefore"], ["e nutililiiina ai", "by nutililiiina"], ["le tamai povi o Samaria.", "the son cattle Samaria"]]},
  {num:7,words:[["Na latou luluina", "them luluina"], ["le matagi,", "the wind"], ["o le mea lea latou te selesele", "therefore them an evenly cut head of"], ["mai ai", "from"], ["le afā;", "the cyclone"], ["ua leai sona tino;", "there was not sona body"], ["e le tupu", "by the grow"], ["se saito", "a wheat"], ["i le fuga,", "in the flower"], ["a e afai", "but to if"], ["e fua,", "to fruit"], ["e 'aina", "to edible"], ["e tagata ese.", "to man away"]]},
  {num:8,words:[["Ua faaumatia Isaraelu;", "destroy Israel"], ["latou te", "them"], ["i ai nei", "therein this"], ["i nuu ese,", "in nation away"], ["e pei", "to to be broken"], ["o se ipu", "a cup"], ["e leai sē fiafia", "there is not sē competition"], ["i ai.", "therein"]]},
  {num:9,words:[["Auā ua latou o", "for them"], ["ae i Asuria,", "but in Assyria"], ["ua se asini", "a donkey"], ["o le vao", "the vegetation"], ["ua nofo toatasi;", "dwell one One"], ["ua faaoloaina", "faaoloaina"], ["e Efaraima", "to Ephraim"], ["e o mananao ia te", "by mananao unto"], ["ia .", "to"]]},
  {num:10,words:[["A e ui", "but to although"], ["ina latou faaoloaina nuu ese,", "let them faaoloaina nation away"], ["ou te faapotopoto nei ia te", "I gather together this unto"], ["i latou;", "them"], ["e le pine", "by the to be long"], ["ona tiga o", "and pain"], ["i latou", "them"], ["ona o le avega", "because of the avega"], ["mai le tupu o alii.", "from the grow Lord"]]},
  {num:11,words:[["Ua faia", "made"], ["e Efaraima fata faitaulaga", "to Ephraim altar"], ["e tele,", "to great"], ["e agasala ai;", "to sin"], ["o le mea lea", "therefore/wherefore"], ["ua avea ai fata faitaulaga", "become altar"], ["ma mea", "and thing"], ["e agasala ai o ia.", "to sin he"]]},
  {num:12,words:[["Ua ou tusi atu ia te", "I book unto"], ["ia o mea tetele", "to thing great"], ["i la'u tulafono;", "in my law"], ["a ua ta'ua ia mea", "but war to thing"], ["o mea ese.", "thing away"]]},
  {num:13,words:[["Latou te fai taulaga", "them make offering"], ["i manu", "in animal"], ["e fai", "to make"], ["ma taulaga", "and offering"], ["mo a'u,", "for I"], ["ma latou aai ai;", "and them eat"], ["a ua", "but"], ["le talia", "the received"], ["i latou", "them"], ["e Ieova;", "to Jehovah"], ["e manatua nei", "to remember this"], ["e ia", "by him"], ["a latou amio leaga,", "but them iniquity"], ["ma taui", "and a reward"], ["i a latou agasala;", "in but them sin"], ["latou te toe foi", "them again also"], ["i Aikupito.", "in Egypt"]]},
  {num:14,words:[["Auā ua faagalogalo", "for to forget"], ["e Isaraelu", "to Israel"], ["i Lē", "in not"], ["na faia o ia,", "made he"], ["ua faatuina", "built"], ["e ia o malumalu;", "by him temple"], ["o Iuta foi", "Judas also"], ["ua ia faateleina o aai nofo 'olo;", "to faateleina eat dwell fortress"], ["ou te tuuina atu", "I will give"], ["le afi", "the fire"], ["i ana aai,", "in his eat"], ["e faaumatia ai", "to destroy"], ["ona maota.", "and the name of a tree"]]},
];
renderVerseSet(hos_ch_8_Verses, 'hos-ch8-verses');

var hos_ch_9_Verses = [
  {num:1,words:[["Isaraelu e,", "Israel by"], ["aua e te fiafia", "for by competition"], ["ma le olioli,", "and the rejoice"], ["faapei o isi nuu;", "like other nation"], ["auā ua", "for"], ["e alu ese", "to go away"], ["i lou Atua", "in your God"], ["e faitaaga ai;", "to fornication"], ["ua e fia fai taui", "to want to do something make a reward"], ["i mea uma", "in all things"], ["e sasa ai saito.", "to a scourge wheat"]]},
  {num:2,words:[["E le fagaina", "by the fagaina"], ["i latou", "them"], ["i le mea", "in the thing"], ["e sasa ai saito", "to a scourge wheat"], ["ma le soligāvine,", "and the soligāvine"], ["e oge ai uaina fou.", "to a famine wine new"]]},
  {num:3,words:[["Latou te", "them"], ["le nonofo", "the dwelling"], ["i le nuu o Ieova,", "in the land Jehovah"], ["a e toe foi Efaraima", "but to again also Ephraim"], ["i Aikupito,", "in Egypt"], ["latou te aai mea leaga", "them eat thing evil"], ["i Asuria.", "in Assyria"]]},
  {num:4,words:[["Latou te", "them"], ["le fai taulaga ia Ieova", "the make offering to Jehovah"], ["i uaina,", "in wine"], ["e le fiafia o ia", "by the competition he"], ["ia te", "unto"], ["i latou;", "them"], ["o a latou taulaga,", "but them offering"], ["e ia te", "by him"], ["i latou ia,", "them to"], ["peiseai o mea", "as if thing"], ["e 'ai", "to eat"], ["a e faanoanoa,", "but to to mourn"], ["o i latou uma", "them all"], ["e aai ai", "to eat"], ["e leaga ai", "to evil"], ["i latou;", "them"], ["auā o la latou mea", "for their thing"], ["e 'ai mā latou", "to eat First person dual exclusive them"], ["e le oo atu lea", "by the oo"], ["i le fale o Ieova.", "in the house Jehovah"]]},
  {num:5,words:[["Se a se mea tou te faia", "a but a thing second person plural made"], ["i le aso", "in the day"], ["e fai ai", "to make"], ["le tausamiga,", "the tausamiga"], ["ma le aso", "and the day"], ["e fai ai", "to make"], ["le taulaga ia Ieova?", "the offering to Jehovah"]]},
  {num:6,words:[["Auā,", "for"], ["faauta mai,", "behold from"], ["ua o", "ua o"], ["i latou ne'i malaia;", "them now a calamity"], ["e faapotopotoina", "by faapotopotoina"], ["i latou", "them"], ["e Aikupito,", "to Egypt"], ["e tanumia", "by tanumia"], ["i latou", "them"], ["e Mafi;", "by mafi"], ["o mea matagofie o", "thing beautiful"], ["i ai o latou ario", "therein them silver"], ["e vaoa ia", "to overgrown with weeds to"], ["i laau ogoogo;", "in tree ogoogo"], ["e i ai", "by therein"], ["i o latou fale o laau talatala.", "in them house tree to untie"]]},
  {num:7,words:[["Ua oo mai", "it came to pass from"], ["ona po", "and night"], ["e taui ai,", "to a reward"], ["ua oo mai", "it came to pass from"], ["ona po", "and night"], ["e totogi ai;", "by totogi"], ["e iloa", "to known"], ["e Isaraelu;", "to Israel"], ["ua valea", "valea"], ["le perofeta,", "the prophet"], ["ua valea lava", "valea indeed"], ["le vaafaatau,", "the vaafaatau"], ["ona o le tele o lau amio leaga,", "because of the great your iniquity"], ["ma le 'ino'ino tele.", "and the 'ino'ino great"]]},
  {num:8,words:[["O loo faatalitali Efaraima faatasi", "faatalitali Ephraim once"], ["i lo'u Atua;", "in my God"], ["ua se mailei o", "a a trap"], ["e fāi manu", "by fāi animal"], ["le perofeta", "the prophet"], ["i ana amio uma;", "in his conduct all"], ["o le 'ino'ino", "the 'ino'ino"], ["i le fale o lona Atua.", "in the house his God"]]},
  {num:9,words:[["Ua matuā amio leaga", "very iniquity"], ["i latou,", "them"], ["faapei ona fai", "like then make"], ["i ona po o Kipea;", "in then night kipea"], ["e manatua", "to remember"], ["e ia", "by him"], ["a latou agasala,", "but them sin"], ["e taui atu", "to a reward"], ["i a latou amio leaga.", "in but them iniquity"]]},
  {num:10,words:[["Na ou maua Isaraelu,", "I received Israel"], ["e pei o fuifui vine", "to to be broken to dip vine"], ["i le vao;", "in the wilderness"], ["na ou iloa o outou mātua", "I known ye all mātua"], ["e pei o uluai mati", "to to be broken first mati"], ["i le mati", "in the mati"], ["ina ua faatoa fua", "let faatoa fruit"], ["mai;", "from"], ["a ua o", "but"], ["i latou ia Paalapeoro,", "them to paalapeoro"], ["ua vavae atu", "to divide"], ["i latou", "them"], ["i le mea", "in the thing"], ["e masiasi ai;", "to to be ashamied"], ["ua inosia", "abominable"], ["i latou", "them"], ["e tusa", "to according to"], ["ma le mea", "and the thing"], ["ua latou naunau", "them naunau"], ["i ai.", "therein"]]},
  {num:11,words:[["O Efaraima", "Ephraim"], ["e lele ese lo latou mamalu faapei", "to fly away their glory like"], ["o le manu lele,", "the animal fly"], ["ai le fanauga,", "the children"], ["ma le manava,", "and the manava"], ["ma le faatoa afuafua.", "and the faatoa to become pregnant"]]},
  {num:12,words:[["E ui", "to although"], ["ina latou tausi", "let them keep"], ["a latou fanau,", "but them born"], ["ou te aveeseina", "I aveeseina"], ["i latou", "them"], ["i tagata;", "in man"], ["oi talofa lava ia te", "alas ! oh ! hello indeed unto"], ["i latou,", "them"], ["pe a a'u alu ese", "whether but I go away"], ["ia te", "unto"], ["i latou.", "them"]]},
  {num:13,words:[["Ua totōina Efaraima", "totōina Ephraim"], ["i le mea matagofie,", "in the thing beautiful"], ["faapei ona ou iloa o Turo;", "like then I known turo"], ["a o Efaraima", "but Ephraim"], ["na te ta'ita'iina atu lana fanau", "ta'ita'iina his born"], ["i le fasioti tagata.", "in the killed man"]]},
  {num:14,words:[["Ieova e,", "Jehovah by"], ["ia e avatu ia te", "to to give away unto"], ["i latou;", "them"], ["se a foi", "a but also"], ["se mea", "a thing"], ["e te avatua? Ia", "by given away to"], ["e avatu ia te", "to give away unto"], ["i latou", "them"], ["le manava fanau", "the manava born"], ["le au,", "the I"], ["ma susu", "and milk"], ["e le susua.", "by the plural of sua"]]},
  {num:15,words:[["O loo", "o loo"], ["i Kilikala lo latou leaga uma;", "in kilikala their evil all"], ["auā na ou 'ino'ino ia te", "for I 'ino'ino unto"], ["i latou", "them"], ["i lea mea,", "in thing"], ["ou te tulia", "I tulia"], ["i latou ai lo'u fale", "them my house"], ["ina ua leaga mea", "let evil thing"], ["ua latou faia;", "they did"], ["ou te", "I"], ["le toe alofa ia te", "the again love unto"], ["i latou;", "them"], ["o latou alii uma,", "them Lord all"], ["o e fouvale", "who to rebel"], ["i latou.", "them"]]},
  {num:16,words:[["Ua taia Efaraima,", "taia Ephraim"], ["ua mago lo latou pogai;", "a small eel their the root and stump of a"], ["latou te", "them"], ["le fua mai ni fua;", "the fruit from some fruit"], ["afai foi latou te fananau,", "if also them fananau"], ["ou te fasiotia la latou fanau pele.", "I slain their born dear"]]},
  {num:17,words:[["E lafoaiina", "by lafoaiina"], ["i latou", "them"], ["e lo'u Atua,", "to my God"], ["auā ua latou", "for them"], ["le faalogo ia te ia;", "the hearken unto him"], ["e taase", "by taase"], ["i latou", "them"], ["i nuu ese.", "in nation away"]]},
];
renderVerseSet(hos_ch_9_Verses, 'hos-ch9-verses');

var hos_ch_10_Verses = [
  {num:1,words:[["O Isaraelu,", "Israel"], ["o le vine ia", "the vine to"], ["e māfalā;", "by māfalā"], ["ua ia fua", "to fruit"], ["mai ni fua", "from some fruit"], ["e fai mona;", "to make to burst forth (as faiai"], ["faapei ona tele o lona fua,", "like then great his fruit"], ["ua faapea", "saying"], ["ona faateleina", "and faateleina"], ["e ia o fata faitaulaga;", "by him altar"], ["faapei ona lelei o lona laueleele,", "like then good his ground"], ["ua faapea", "saying"], ["ona latou gaosi lelei o tupua.", "and them gaosi good idol"]]},
  {num:2,words:[["Ua faalotoloto lua", "faalotoloto two"], ["i latou;", "them"], ["ua nofo sala nei", "dwell a fine this"], ["i latou;", "them"], ["na te lepetia", "lepetia"], ["a latou fata faitaulaga,", "but them altar"], ["na te faaumatia", "destroy"], ["a latou tupua.", "but them idol"]]},
  {num:3,words:[["Auā e faapea", "for by thus"], ["mai nei", "from this"], ["i latou,", "them"], ["Ua leai", "there was not"], ["se tupu ia te", "a grow unto"], ["i matou,", "in we"], ["auā ua matou", "for we"], ["le matatau ia Ieova;", "the fear to Jehovah"], ["se a foi", "a but also"], ["se mea", "a thing"], ["e faia", "to made"], ["e le tupu ia", "by the grow to"], ["i matou?", "in we"]]},
  {num:4,words:[["Ua latou fai", "them make"], ["mai upu,", "from word"], ["ua tauto pepelo,", "to take an oath false"], ["ua osi", "osi"], ["le feagaiga;", "the covenant"], ["e tupu", "to grow"], ["ae foi", "but also"], ["le faamasinoga,", "the judgment"], ["e pei o laau oona", "to to be broken tree oona"], ["i utu o fanua.", "in todraw water land"]]},
  {num:5,words:[["E fefefe", "by fefefe"], ["e ua nonofo", "by dwelling"], ["i Samaria", "in Samaria"], ["ona o tamai povi o Petavene;", "because of son cattle petavene"], ["auā e fetagisi ai", "for by fetagisi"], ["ona tagata,", "and man"], ["o ona ositaulaga foi", "then high priest also"], ["e na fiafia", "by competition"], ["i ai;", "therein"], ["auā o lona mamalu", "for his glory"], ["ua te'a", "te'a"], ["ma ia.", "and to"]]},
  {num:6,words:[["E avea foi lenei mea", "to become also this thing"], ["i Asuria", "in Assyria"], ["e fai", "to make"], ["ma mea alofa", "and thing love"], ["i le tupu o Iarepa;", "in the grow iarepa"], ["e mā Efaraima,", "to First person dual exclusive Ephraim"], ["e masiasi foi Isaraelu", "to to be ashamied also Israel"], ["ona o lana lava pule.", "because of his indeed rule"]]},
  {num:7,words:[["O Samaria", "Samaria"], ["ua fano lona tupu,", "perish his grow"], ["e pei o si fasi laau", "to to be broken si kill tree"], ["i le fogāvai.", "in the fogāvai"]]},
  {num:8,words:[["E faaumatia foi mea maualuga", "to destroy also thing Iiigli"], ["i Avene,", "in avene"], ["o le agasala", "the sin"], ["a Isaraelu;", "of Israel"], ["e tutupu", "to bring forth"], ["ae le laau tuitui", "but the tree prickly"], ["ma le laau talatala", "and the tree to untie"], ["i o latou fata faitaulaga;", "in them altar"], ["latou te fai atu foi", "them said to also"], ["i mauga,", "in mountain"], ["Ina tanu mai ia ia te", "let to bury from to unto"], ["i matou.", "in we"], ["E faapea foi", "by thus also"], ["i mea maupuepue,", "in thing maupuepue"], ["Ina mafuli mai ia", "let mafuli from to"], ["i luga ia te", "in above unto"], ["i matou.", "in we"]]},
  {num:9,words:[["Isaraelu e,", "Israel by"], ["talu mai", "since from"], ["ona po o Kipea", "and night kipea"], ["ua e agasala ai;", "to sin"], ["ua latou tutumau ai;", "them tutumau"], ["na le oo atu ia te", "the oo unto"], ["i latou", "them"], ["i Kipea", "in kipea"], ["le taua", "the war"], ["i tagata agaleaga.", "in man unkind"]]},
  {num:10,words:[["O lo'u loto,", "my heart"], ["ou te aoai ia te", "I aoai unto"], ["i latou;", "them"], ["e faapotopotoina foi tagata", "by faapotopotoina also man"], ["e tau", "to season"], ["ma i latou,", "and them"], ["pe a ou fusifusi ia te", "whether but I to bind hund and foot unto"], ["i latou", "them"], ["ona o", "because of"], ["a latou agasala", "but them sin"], ["e lua.", "by two"]]},
  {num:11,words:[["O Efaraima foi", "Ephraim also"], ["o le povi fafine ia", "the cattle woman to"], ["ua a'oa'oina,", "taught"], ["ua fia soli saito lava;", "want to do something to tread upon wheat indeed"], ["a ua ou alu atu", "but I go away"], ["lava a'u", "indeed I"], ["i lona", "in his"], ["ua lalelei;", "lalelei"], ["ou te faatietie", "I faatietie"], ["se tasi ia Efaraima,", "a one to Ephraim"], ["e suatia", "by suatia"], ["le eleele", "the earth"], ["e Iuta", "to Judas"], ["e faamăluluina", "by faamăluluina"], ["e Iakopo lona laueleele.", "to James his ground"]]},
  {num:12,words:[["Ia outou lulu saito", "to ye all barn owl wheat"], ["mo outou", "for you"], ["ma le amiotonu,", "and the righteous"], ["ia outou selesele", "to ye all an evenly cut head of"], ["mai ma le amio lelei;", "from and the conduct good"], ["ia outou suatia lo outou fanua vaoa;", "to ye all suatia your land overgrown with weeds"], ["auā ua oo", "for it came to pass"], ["i ona po", "in then night"], ["e saili atu ai ia Ieova,", "to seek to Jehovah"], ["seia afio mai o ia,", "until dwell (respectful) from he"], ["ma faatotō ifo", "and faatotō"], ["le amiotonu", "the righteous"], ["i luga ia te outou.", "in above unto you"]]},
  {num:13,words:[["Ua outou suatia", "ye all suatia"], ["le agasala,", "the sin"], ["ua outou selesele", "ye all an evenly cut head of"], ["mai le leaga;", "from the evil"], ["ua outou aai", "ye all eat"], ["le fua", "the fruit"], ["o le pepelo;", "the false"], ["auā na", "for"], ["e faatuatua", "to faith"], ["i lou ala,", "in your arise"], ["ma le toatele o ou tagata totoa.", "and the many I man p'ural o( fnt"]]},
  {num:14,words:[["O lea", "therefore"], ["e tupu ai", "to grow"], ["le vāvāō", "the vāvāō"], ["i ou tagata,", "in I man"], ["e faaumatia ou 'olo uma", "to destroy I fortress all"], ["lava,", "indeed"], ["e pei", "to to be broken"], ["ona faaumatia", "and destroy"], ["e Salemana o Petarepelu", "by salemana petarepelu"], ["i le aso", "in the day"], ["na tau ai", "season"], ["le taua;", "the war"], ["na palasi", "to have children in"], ["le tinā faatasi", "the mother once"], ["ma ana tama.", "and his child"]]},
  {num:15,words:[["E faapea lava", "by thus indeed"], ["ona faia ia te outou", "and made unto you"], ["i Peteli", "in peteli"], ["ona o la outou amio", "because of your conduct"], ["e matuā leaga;", "to very evil"], ["e matuā fano lava", "to very perish indeed"], ["le tupu o Isaraelu", "the grow Israel"], ["i le taeao.", "in the morning"]]},
];
renderVerseSet(hos_ch_10_Verses, 'hos-ch10-verses');

var hos_ch_11_Verses = [
  {num:1,words:[["O ona po", "then night"], ["na tama itiiti ai Isaraelu,", "child small Israel"], ["na ou alofa atu ia te", "I love unto"], ["ia,", "to"], ["na ou valaauina foi lo'u atalii nai Aikupito.", "I called also my son from Egypt"]]},
  {num:2,words:[["Na latou alalaga ia te", "them alalaga unto"], ["i latou,", "them"], ["a ua latou o ese", "but them away"], ["ia te", "unto"], ["i latou;", "them"], ["na latou fai taulaga ia Paala,", "them make offering to a small fly-fishhook"], ["ma faamu mea manogi", "and faamu thing fragrant"], ["i tupua", "in idol"], ["ua ta.", "a stroke"]]},
  {num:3,words:[["Na ou a'oa'oina Efaraima ia savali,", "I taught Ephraim to walk"], ["o loo o tauta'ita'i ia te", "tauta'ita'i unto"], ["i latou", "them"], ["i o latou lima;", "in them five"], ["a ua", "but"], ["le iloa", "the known"], ["e i latou", "by them"], ["ona ou faamaloloina o", "and I faamaloloina"], ["i latou.", "them"]]},
  {num:4,words:[["Na ou tosina", "I to be"], ["i latou", "them"], ["i maea", "in maea"], ["a le tagata,", "but the man"], ["o maea alofa lava;", "maea love indeed"], ["na ou", "I"], ["i ai ia te", "therein unto"], ["i latou", "them"], ["e pei o", "to to be broken"], ["e sii", "to lift up"], ["ae le amo ai o latou aulamu,", "but the amo them aulamu"], ["na au tuuina atu foi mea", "I given also thing"], ["e 'ai ia te", "to eat unto"], ["i latou.", "them"]]},
  {num:5,words:[["E le toe foi o", "by the again also"], ["ia i le nuu o Aikupito,", "to in the land Egypt"], ["a e avea", "but to become"], ["le Asuria mona tupu;", "the Assyria to burst forth (as faiai grow"], ["auā ua", "for"], ["le mafafai", "the mafafai"], ["i latou", "them"], ["ona toe foi atu.", "and again also"]]},
  {num:6,words:[["E tumau", "to endure"], ["le pelu", "the a sword"], ["i ona aai,", "in then eat"], ["e faaumatia ai foi", "to destroy also"], ["ona la,", "and la"], ["ma fano ai,", "and perish"], ["auā o", "for"], ["a latou lava filifiliga.", "but them indeed filifiliga"]]},
  {num:7,words:[["Ua naunau lo'u nuu", "naunau my nation"], ["e liliu ese ia te au;", "to turned away unto me"], ["latou te valaau", "them call"], ["i ai", "therein"], ["e o mai", "by from"], ["i lē Silisili ese,", "in not very much away"], ["a e leai", "but there is not"], ["se tasi", "a one"], ["e vivii atu ia te", "to to praise unto"], ["ia .", "to"]]},
  {num:8,words:[["Efaraima e,", "Ephraim by"], ["ou te mafai faapefea", "I able how ?"], ["ona tuu atu ia te oe? Isaraelu", "and placed unto thee Israel"], ["e,", "by"], ["ou te tuuina atu oe faapefea? ou te mafai faapefea", "I will give you how ? I able how ?"], ["ona tuuina atu o oe", "and given you"], ["e pei o Atama? ou te tuuina atu oe faapefea", "to to be broken atama I will give you how ?"], ["e pei o Sepoima?", "to to be broken sepoima"], ["Ua liua lo'u loto", "wide (as a canoe of too my heart"], ["i totonu ia te au;", "in inside unto me"], ["atoa foi", "together with also"], ["ma lo'u alofa mutimutivale", "and my love to be distressed in"], ["ua tupu.", "grow"]]},
  {num:9,words:[["Ou te", "I"], ["le faaoo lo'u ita tele;", "the faaoo my angry great"], ["ou te", "I"], ["le toe faaumatia Efaraima;", "the again destroy Ephraim"], ["auā o a'u", "for I am"], ["o le Atua,", "of God"], ["a e le", "but by the"], ["se tagata,", "a man"], ["o le Paia o loo", "the holy"], ["i totonu ia te oe;", "in inside unto thee"], ["ou te", "I"], ["le alu atu", "the go away"], ["ma le ita.", "and the angry"]]},
  {num:10,words:[["Latou te mulimuli atu ia Ieova,", "them follow after to Jehovah"], ["e tagi lava ia", "to to cry indeed to"], ["e pei", "to to be broken"], ["o se leona;", "a leona"], ["a tagi o ia,", "but to cry he"], ["ona taalise mai ai lea", "and to be quick from"], ["o le fanau", "the born"], ["mai sisifo.", "from sisifo"]]},
  {num:11,words:[["Latou te taalise", "them to be quick"], ["mai e pei", "from to to be broken"], ["o se manu lele", "a animal fly"], ["mai Aikupito,", "from Egypt"], ["e pei", "to to be broken"], ["o se lupe foi", "a dove also"], ["mai le nuu o Asuria;", "from the nation Assyria"], ["ou te faanonofo foi ia te", "I faanonofo also unto"], ["i latou", "them"], ["i o latou fale,", "in them house"], ["ua faapea mai ai Ieova.", "saying Jehovah"]]},
  {num:12,words:[["Ua siosio Efaraima ia te au", "siosio Ephraim unto me"], ["i le pepelo,", "in the false"], ["o le aiga foi o Isaraelu", "the family also Israel"], ["ua siosio ia te au", "siosio unto me"], ["i le 'ole'ole;", "in the 'ole'ole"], ["a ua pule pea Iuta faatasi", "but rule continually Judas once"], ["ma le Atua,", "and the God"], ["ua faamaoni ia faatasi", "faithful to once"], ["ma le au paia.", "and the saints"]]},
];
renderVerseSet(hos_ch_11_Verses, 'hos-ch11-verses');

var hos_ch_12_Verses = [
  {num:1,words:[["O loo 'ai Efaraima", "eat Ephraim"], ["le matagi,", "the wind"], ["ua naunau atu o ia", "naunau he"], ["i le matagi", "in the wind"], ["mai sasae;", "from to tear"], ["ua faateleina", "faateleina"], ["e ia le pepelo", "by him the false"], ["ma le malaia", "and the a calamity"], ["i aso uma lava;", "in day all indeed"], ["ua osia foi la latou feagaiga", "osia also their covenant"], ["ma Asuria,", "and Assyria"], ["ma ua avatu", "and give away"], ["i Aikupito suāuu.", "in Egypt suāuu"]]},
  {num:2,words:[["Ua ia Ieova", "to Jehovah"], ["le finauga", "the argument"], ["ma Iuta,", "and Judas"], ["na te faasalaina Iakopo", "faasalaina James"], ["e tusa", "to according to"], ["ma ana amio;", "and his conduct"], ["na te taui atu ia te", "a reward unto"], ["ia e tusa", "to to according to"], ["ma ana galuega.", "and his work"]]},
  {num:3,words:[["Na ia tago", "to reach"], ["i le mulivae o lona uso", "in the the heel his a relative of the same generation and gender"], ["a o", "but"], ["i ai", "therein"], ["i le manava;", "in the manava"], ["o lona malosi", "his strong"], ["na ia malo ai", "to government"], ["i le Atua.", "in the God"]]},
  {num:4,words:[["Na ia malo", "to government"], ["i le agelu,", "in the angel"], ["na manumalo ai lava;", "overcome indeed"], ["na ia tagi,", "to to cry"], ["ma aioi atu ia te", "and aioi unto"], ["ia;", "to"], ["na ia iloa ia te", "to known unto"], ["ia i Peteli,", "to in peteli"], ["na tŭlei mai ai foi lona siufofoga", "tŭlei from also his voice"], ["ia te", "unto"], ["i tatou.", "in us"]]},
  {num:5,words:[["O Ieova lava", "Jehovah indeed"], ["o le Atua o 'au;", "of God I"], ["o Ieova o lona suafa lea", "Jehovah his name"], ["e manatua ai o ia.", "to remember he"]]},
  {num:6,words:[["O lenei,", "this"], ["ia e toe foi", "to to again also"], ["i lou Atua;", "in your God"], ["ia e tausi", "to to keep"], ["le alofa", "the love"], ["ma le faamasinoga,", "and the judgment"], ["aua le aunoa", "for the without"], ["ona e faatalitali atu", "and by faatalitali"], ["i lou Atua.", "in your God"]]},
  {num:7,words:[["O le faatauoa ia ,", "the faatauoa to"], ["o i lona lima o fua faatautau faaletatau;", "in his five fruit faatautau faaletatau"], ["e fiafia o ia", "to competition he"], ["i le faasaua.", "in the to be oppressive"]]},
  {num:8,words:[["Ua faapea mai foi", "saying also"], ["a Efaraima,", "of Ephraim"], ["E moni,", "verily/truly"], ["o a'u", "I am"], ["o le mau mea,", "the opinion thing"], ["ua ou maua oloa", "I received goods"], ["mo a'u;", "for I"], ["latou te", "them"], ["le iloa", "the known"], ["se leaga ia te au,", "a evil unto me"], ["se mea", "a thing"], ["o se agasala", "a sin"], ["i a'u galuega uma.", "in I work all"]]},
  {num:9,words:[["O a'u foi o Ieova lou Atua talu", "I am also Jehovah your God since"], ["mai le nuu o Aikupito,", "from the nation Egypt"], ["ou te toe faanofo ia te oe", "I again a secondary wife intro- unto thee"], ["i fale ie faapei o", "in house faamaise like"], ["ona po", "and night"], ["o le tausamiga.", "the tausamiga"]]},
  {num:10,words:[["Na ou tautala atu", "I to talk"], ["i perofeta,", "in prophet"], ["na ou faateleina faaaliga;", "I faateleina revelation"], ["o le au perofeta foi", "the I prophet also"], ["na ou sauni atu ai upu faataoto.", "I he who beg^ins the game word a parable"]]},
  {num:11,words:[["Ua leaga lava Kiliata,", "evil indeed kiliata"], ["e pepelo lava", "to false indeed"], ["i latou;", "them"], ["latou te fai taulaga", "them make offering"], ["i povi poa", "in cattle captive"], ["i Kilikala;", "in kilikala"], ["o latou fata faitaulaga foi,", "them altar also"], ["e pei o faupuegāmaa ia", "to to be broken faupuegāmaa to"], ["i atu pue", "in pue"], ["o le laueleele.", "the ground"]]},
  {num:12,words:[["Na sola Iakopo", "flee James"], ["i le nuu o Suria;", "in the land suria"], ["na auauna Isaraelu", "servant Israel"], ["e maua ai lana avā;", "to received his wife"], ["na ia leoleo mamoe", "to shepherd"], ["e maua ai lana avā.", "to received his wife"]]},
  {num:13,words:[["O le perofeta", "the prophet"], ["na aveina", "aveina"], ["ae ai Isaraelu", "but Israel"], ["e Ieova mai Aikupito;", "to Jehovah from Egypt"], ["o le perofeta foi", "the prophet also"], ["na leoleoina ai o ia.", "leoleoina he"]]},
  {num:14,words:[["Na matuā faaonoono Efaraima ia te", "very faaonoono Ephraim unto"], ["ia ,", "to"], ["o le mea lea", "therefore/wherefore"], ["na te tuu ai pea lona toto", "put continually his blood"], ["ia te ia;", "unto him"], ["o lona luma foi", "his before also"], ["e faafoisia ia te ia", "by faafoisia unto him"], ["e lona Alii.", "by his Lord"]]},
];
renderVerseSet(hos_ch_12_Verses, 'hos-ch12-verses');

var hos_ch_13_Verses = [
  {num:1,words:[["Na tautala Efaraima", "to talk Ephraim"], ["ona tupu ai lea", "and grow"], ["o le tetemu,", "the to tremble"], ["sa mamalu o ia", "glory he"], ["i Isaraelu;", "in Israel"], ["a ua oo", "but it came to pass"], ["ina agasala o ia", "let sin he"], ["i Paala,", "in a small fly-fishhook"], ["ona oti ai lea.", "and die"]]},
  {num:2,words:[["A o nei", "but this"], ["ona po", "and night"], ["ua latou saga agasala pea,", "them saga sin continually"], ["ua latou faia", "they did"], ["mo i latou o tupua uamea,", "for them idol uamea"], ["o tupua", "idol"], ["ua faia", "made"], ["i o latou ario,", "in them silver"], ["e tusa", "to according to"], ["ma lo latou manatu;", "and the them thought"], ["o le galuega", "the work"], ["a tufuga", "but master builder"], ["na mea uma;", "all things"], ["ua faapea la latou upu", "saying their word"], ["i ai,", "therein"], ["Ia feasogi", "to to salute by rubbJDg"], ["ma tamai povi tagata o", "and son cattle man"], ["e fai taulaga.", "to make offering"]]},
  {num:3,words:[["O le mea lea", "therefore/wherefore"], ["e avea ai", "to become"], ["i latou", "them"], ["e pei", "to to be broken"], ["o le puao", "the puao"], ["i le taeao,", "in the morning"], ["e pei", "to to be broken"], ["o le sau foi", "the come also"], ["i le vave ao", "in the quick day"], ["ona mavae atu;", "and a parting"], ["e pei", "to to be broken"], ["o le aputi", "the aputi"], ["ua lelea", "to be carried away by the"], ["i le matagi", "in the wind"], ["i le mea", "in the thing"], ["e sasa ai saito,", "to a scourge wheat"], ["e pei", "to to be broken"], ["o le asu foi ai", "the asu also"], ["le alaasu.", "the alaasu"]]},
  {num:4,words:[["A o a'u o Ieova,", "but I am Jehovah"], ["o lou Atua talu", "your God since"], ["mai le nuu o Aikupito,", "from the nation Egypt"], ["e te", "by"], ["le iloa", "the known"], ["se tasi Atua", "a one God"], ["na o a'u;", "I am"], ["e leai foi", "there is not also"], ["se isi faaola,", "a other save"], ["na o a'u.", "I am"]]},
  {num:5,words:[["Na ou iloa oe", "I known you"], ["i le vao,", "in the wilderness"], ["o le nuu naumati.", "the nation naumati"]]},
  {num:6,words:[["E pei", "to to be broken"], ["ona fagaina o", "and fagaina"], ["i latou,", "them"], ["sa faapea", "saying"], ["ona maoona o", "and maoona"], ["i latou;", "them"], ["sa maoona", "maoona"], ["i latou,", "them"], ["ona faamaualulugaina lea o latou loto;", "and faamaualulugaina them heart"], ["o le mea lea", "therefore/wherefore"], ["na latou faagalogalo ai ia te au.", "them to forget unto me"]]},
  {num:7,words:[["O lea", "therefore"], ["ua avea ai a'u ia te", "become I unto"], ["i latou", "them"], ["e pei", "to to be broken"], ["o se leona;", "a leona"], ["ou te lamalama", "I lamalama"], ["e pei", "to to be broken"], ["o se nameri", "a nameri"], ["i le auala.", "in the auala"]]},
  {num:8,words:[["Ou te oso atu ia te", "I food for a journey unto"], ["i latou", "them"], ["e pei", "to to be broken"], ["o se urosa", "a urosa"], ["ua avea ana tama ,", "become his child"], ["ou te saeia mea", "I saeia thing"], ["e ufitai o latou fatu;", "by ufitai them seed"], ["ou te 'aina", "I edible"], ["i latou", "them"], ["i lea mea", "in thing"], ["e pei", "to to be broken"], ["o se leona;", "a leona"], ["e saeia", "by saeia"], ["i latou", "them"], ["e le manu feai.", "by the animal feai"]]},
  {num:9,words:[["Isaraelu e,", "Israel by"], ["ua malaia oe ia te oe;", "a calamity you unto thee"], ["a ua ia te au lou fesoasoani.", "but unto me your to help"]]},
  {num:10,words:[["O ifea o", "ifea"], ["i ai nei lou tupu", "therein this your grow"], ["le na te faaolaina oe", "the saved you"], ["i o outou aai uma?", "in ye all eat all"], ["o ifea ou faamasino foi", "ifea I a judge also"], ["na e fai", "to make"], ["mai ai,", "from"], ["Au mai ia te au", "bring unto me"], ["se tupu", "a grow"], ["atoa ma ni alii?", "and some Lord"]]},
  {num:11,words:[["Na ou avatu ia te oe", "I give away unto thee"], ["le tupu", "the grow"], ["i lo'u tiga;", "in my pain"], ["na ou aveeseina foi o", "I aveeseina also"], ["ia i lo'u ita.", "to in my angry"]]},
  {num:12,words:[["Ua fusifusi faatasi", "to bind hund and foot once"], ["le leaga o Efaraima;", "the evil Ephraim"], ["ua teua lana agasala.", "teua his sin"]]},
  {num:13,words:[["E oo ia te ia", "it shall come to pass unto him"], ["le faatiga", "the a"], ["o le fafine o le", "the woman the"], ["a fanau mai;", "but born"], ["o ia", "he"], ["o le tama faalemafaufau,", "the child faalemafaufau"], ["aua e le tatau", "for by the to wring out"], ["ona tuai mai o ia nai", "and to be a long time from he from"], ["le mea", "the thing"], ["e o ifo ai tama.", "by child"]]},
  {num:14,words:[["Ou te laveai ia te", "I deliver unto"], ["i latou ai", "them"], ["le malosi", "the strong"], ["o le tuugamau;", "the tuugamau"], ["ou te faaola ia te", "I save unto"], ["i latou ai", "them"], ["le oti.", "the die"], ["Le oti e,", "the die by"], ["o fea o", "fea"], ["i ai", "therein"], ["le malaia mai ia te oe?", "the a calamity from you"], ["Le tuugamau", "the tuugamau"], ["e,", "by"], ["o fea o", "fea"], ["i ai", "therein"], ["se mea", "a thing"], ["e fano ai", "to perish"], ["mai ia te oe?", "from you"], ["e lilo ia te au", "to secret unto me"], ["le salamo.", "the repent"]]},
  {num:15,words:[["E ui", "to although"], ["ina faauluolaina o ia", "let faauluolaina he"], ["i luma o", "before"], ["ona uso,", "and a relative of the same generation and gender"], ["e agi mai", "by agi from"], ["le matagi mai sasae,", "the wind from to tear"], ["o le matagi o Ieova", "the wind Jehovah"], ["e oso atu ia ai", "to food for a journey to"], ["le vao,", "the vegetation"], ["e pe lona vaieli,", "by whether his vaieli"], ["e mate foi lona punavai;", "by mate also his punavai"], ["na te faaumatia", "destroy"], ["le oa o mea uma", "the a couple all things"], ["e manaomia.", "by manaomia"]]},
  {num:16,words:[["E faasalaina Samaria,", "by faasalaina Samaria"], ["auā ua ia fouvale", "for to to rebel"], ["i lona Atua;", "in his God"], ["o le pelu latou te pauu ai;", "the a sword them fell"], ["e palasi", "to to have children in"], ["a latou tama meamea,", "but them child young"], ["e faatiauina o latou fafine", "by faatiauina them woman"], ["ua totō.", "totō"]]},
];
renderVerseSet(hos_ch_13_Verses, 'hos-ch13-verses');

var hos_ch_14_Verses = [
  {num:1,words:[["Isaraelu e", "Israel by"], ["ina toe foi", "let again also"], ["mai ia ia Ieova lou Atua;", "from to to Jehovah your God"], ["auā o lau agasala", "for your sin"], ["ua e paū ai.", "by paū"]]},
  {num:2,words:[["Ina sauni atu ia ni", "let he who beg^ins the game to some"], ["a outou upu", "but ye all word"], ["ma toe foi atu ia Ieova.", "and again also to Jehovah"], ["Ia outou faapea atu ia te", "to ye all thus unto"], ["ia,", "to"], ["Ia e ave ese agasala uma,", "to to take away sin all"], ["ma talileleia mai,", "and talileleia from"], ["matou te avatua lava taulaga", "we given away indeed offering"], ["o matou laugutu.", "we laugutu"]]},
  {num:3,words:[["E le faaolaina", "by the saved"], ["i matou", "in we"], ["e Asuria;", "to Assyria"], ["matou te", "we"], ["le tietie", "the tietie"], ["i solofanua;", "in horse"], ["matou te", "we"], ["le toe faapea ane lava", "the again thus indeed"], ["i galuega", "in work"], ["a o matou lima,", "but we five"], ["O matou atua ia;", "we God to"], ["auā e alofagia", "for to blessed"], ["e oe", "to you"], ["le mātuaoti.", "the mātuaoti"]]},
  {num:4,words:[["Ou te faamaloloina lo latou liliu ese;", "I faamaloloina their turned away"], ["ou te alofa fua ia te", "I love fruit unto"], ["i latou;", "them"], ["auā ua liliueseina lo'u ita", "for liliueseina my angry"], ["ia te", "unto"], ["i latou.", "them"]]},
  {num:5,words:[["E avea a'u", "to become I"], ["ma sau ia Isaraelu;", "and come to Israel"], ["e fuga mai o ia", "to flower from he"], ["e pei", "to to be broken"], ["o le susana,", "the susana"], ["e sosolo", "to to run"], ["ona aa", "and aa"], ["e pei o Lepanona.", "to to be broken lepanona"]]},
  {num:6,words:[["E tutupu", "to bring forth"], ["ae ona tātupu,", "but then tātupu"], ["e pei", "to to be broken"], ["o le olive lona matagofie;", "the olive his beautiful"], ["e manogi foi ia", "to fragrant also to"], ["e pei o Lepanona.", "to to be broken lepanona"]]},
  {num:7,words:[["O i latou o", "them"], ["e nonofo", "to dwelling"], ["i lalo ifo o lona paolo,", "in under his paolo"], ["e toe ola", "to again life"], ["mai i latou", "from them"], ["e pei o saito,", "to to be broken wheat"], ["e fua mai", "yielding fruit"], ["e pei", "to to be broken"], ["o le vine;", "the vine"], ["e ta'ua o ia", "to war he"], ["e pei", "to to be broken"], ["o le uaina o Lepanona.", "the wine lepanona"], ["E faapea mai", "by thus from"], ["a Efaraima,", "of Ephraim"]]},
  {num:8,words:[["Se a ea sa'u toe mea", "a but to rise (as a diver to the sur- come again thing"], ["e fai", "to make"], ["i tupua?", "in idol"], ["Ua ou tali atu,", "I respond"], ["ma vaavaai atu ia te", "and vaavaai unto"], ["ia;", "to"], ["e pei", "to to be broken"], ["o se perosi lauolaola a'u nei;", "a perosi green I this"], ["e maua lau fua", "to received your fruit"], ["mai ia te au.", "from I"]]},
  {num:9,words:[["Po o ai", "night"], ["se tasi", "a one"], ["ua poto?", "wise"], ["e iloa lava", "to known indeed"], ["e ia", "by him"], ["na mea;", "thing"], ["po o ai lē faautauta?", "night not to devise"], ["e iloa ai", "to known"], ["e ia;", "by him"], ["auā ua tonu ala o Ieova,", "for right arise Jehovah"], ["e savavali ai", "to walked"], ["e ua amiotonu;", "by righteous"], ["a o", "but"], ["e fouvale,", "to to rebel"], ["e tautevateva ai", "by tautevateva"], ["i latou.", "them"]]},
];
renderVerseSet(hos_ch_14_Verses, 'hos-ch14-verses');

})();