(function() {
var _hos_ch_1_Verses = [
  {num:1,words:[["O le afioga", "the word (divine)"], ["a Ieova", "of the LORD"], ["na oo atu ia", "arrived to"], ["Hosea", "Hosea"], ["le atalii o Peri,", "the son of Peri"], ["i ona po", "in then night"], ["o Usia,", "Usia"], ["Iotama,", "Iotama"], ["Aasa,", "Asa"], ["ma Esekia,", "and Hezekiah"], ["o tupu o Iuta;", "king of Judas"], ["o", "o"], ["ona po foi", "and night also"], ["o Ierepoamo", "Jeroboam"], ["le atalii o Ioasa", "the son of Joash"], ["le tupu o Isaraelu.", "the king of Israel"]]},
  {num:2,words:[["O le amataga", "the beginning"], ["o le afioga", "the word (divine)"], ["a Ieova ia", "of the LORD to"], ["Hosea.", "Hosea"], ["Ua fetalai mai", "said"], ["Ieova ia Hosea,", "the LORD to Hosea"], ["Alu ia oe,", "go to you"], ["ia", "to"], ["e fai avā", "to make wife"], ["i le fafine talitane,", "in the woman harlot"], ["ma ia fai māu", "and to make māu"], ["le fanau", "the born"], ["a le faitaaga,", "but the fornication"], ["auā", "for"], ["ua matuā faitaaga lava", "exceedingly fornication indeed"], ["le nuu,", "the nation"], ["ua o ese ia", "of away to"], ["Ieova.", "the LORD"]]},
  {num:3,words:[["Ona alu lea", "And he went"], ["o ia", "he"], ["ua fai mana", "made to get"], ["avā o Komeri", "wife of Komeri"], ["le afafine o Tipelaima,", "the daughter of Tipelaima"], ["ua to ai", "to plant"], ["foi o ia,", "also he"], ["ua fanau mai ai", "born"], ["lona atalii.", "his son"]]},
  {num:4,words:[["Ua fetalai mai foi", "said also"], ["Ieova ia te ia,", "the LORD to him"], ["Ia", "to"], ["e faaigoa ia te ia,", "to called to him"], ["o Isereelu;", "Israelite"], ["auā", "for"], ["e toe itiiti,", "to again small"], ["ona ou taui atu ai lea", "and I a reward then then"], ["o le toto", "the blood"], ["o Isereelu", "Israelite"], ["i le aiga", "in the family"], ["o Ieu,", "Jehu"], ["ou te faaumatia foi", "I will destroyed also"], ["le malo", "the government"], ["o le aiga", "the family"], ["o Isaraelu.", "Israel"]]},
  {num:5,words:[["O lea", "therefore"], ["aso ou te gauia ai", "day I will gauia"], ["le aufana", "the bow"], ["a Isaraelu", "of Israel"], ["i le vanu", "in the valley"], ["o Isereelu.", "Israelite"]]},
  {num:6,words:[["Ua toe to foi", "again to plant also"], ["o ia,", "he"], ["ua fanau ai", "born"], ["le tama teine;", "the daughter"], ["ona fetalai mai lea", "and said"], ["o Ieova ia te ia,", "the LORD to him"], ["Ia", "to"], ["e faaigoa ia te ia,", "to called to him"], ["o Loruama;", "Loruama"], ["auā ou te", "for I will"], ["le toe alofa atu", "the again love"], ["i le aiga", "in the family"], ["o Isaraelu,", "Israel"], ["a", "but"], ["e ou te matuā aveesea", "to I will exceedingly removed away"], ["i latou.", "them"]]},
  {num:7,words:[["A", "but"], ["o le aiga", "the family"], ["o Iuta,", "Judas"], ["ou te alofa", "I will love"], ["i ai,", "therein"], ["ou te faaola", "I will save"], ["ia te", "unto"], ["i latou", "them"], ["ona o Ieova lo latou Atua;", "because of the LORD their God"], ["ou te", "I will"], ["le faaola ia te", "the save unto"], ["i latou", "them"], ["i le aufana,", "in the bow"], ["po", "night"], ["o le pelu,", "the sword"], ["po", "night"], ["o le taua,", "the precious"], ["po o solofanua,", "night of horse"], ["po o 'au", "night of me"], ["e tietie", "to ride"], ["i solofanua.", "in horse"]]},
  {num:8,words:[["Ua ia faate'a", "to made depart"], ["Loruama", "Loruama"], ["ma le susu;", "and the milk"], ["ona to ai lea", "and to plant then then"], ["o ia,", "he"], ["ua fanau mai ai", "born"], ["le tama tane.", "the son"]]},
  {num:9,words:[["Ona faapea mai ai lea", "and thus from then then"], ["a le Atua ,", "of God"], ["Ia", "to"], ["e faaigoa ia te ia,", "to called to him"], ["o Loama;", "Loama"], ["auā", "for"], ["e le so'u nuu outou,", "by the so'u nation you (all)"], ["e le so outou", "by the so you (all)"], ["Atua foi", "God also"], ["a'u.", "me"]]},
  {num:10,words:[["A", "but"], ["o le faitau aofai", "the to count number"], ["o le fanauga", "the children"], ["a Isaraelu", "of Israel"], ["e pei o le oneone", "like the sand"], ["o le sami", "Sea"], ["ia,", "to"], ["e le mafuatia,", "by the mafuatia"], ["e le mafaitaulia;", "by the mafaitaulia"], ["o", "o"], ["i le mea foi", "in the thing also"], ["na faapeaina atu ai", "thus"], ["ia te", "unto"], ["i latou,", "them"], ["E le so'u nuu outou,", "by the so'u nation you (all)"], ["e iu", "to become of"], ["ina faapeaina atu ai", "so that thus"], ["ia te", "unto"], ["i latou,", "them"], ["O atalii", "sons"], ["o le Atua soifua outou", "of God live you (all)"], [".", "."]]},
  {num:11,words:[["Ona faapotopotoina faatasi ai lea", "and gathered together together then then"], ["o le fanauga", "the children"], ["a Iuta,", "of Judas"], ["atoa ma le fanauga", "and the children"], ["a Isaraelu,", "of Israel"], ["latou te tofia foi", "they will chosen also"], ["le ta'ita'i", "the lead"], ["e toatasi", "to one One"], ["mo", "for"], ["i latou,", "them"], ["latou te o ae foi", "they will go up also"], ["ma le nuu;", "and the nation"], ["auā", "for"], ["e sili", "to most"], ["le aso o Isereelu.", "the day of Israelite"]]},
];
renderVerseSet(_hos_ch_1_Verses, 'hos-ch1-verses');

var _hos_ch_2_Verses = [
  {num:1,words:[["-2 Ia outou", "-2 to you (all)"], ["faapea atu", "thus"], ["i o outou", "in of you (all)"], ["uso,", "brother"], ["Ama e;", "ignorant by"], ["ia faapea atu foi", "to thus also"], ["i o outou", "in of you (all)"], ["tuafafine,", "sister"], ["Ruama e.", "Ruama by"], ["Ia outou finau atu", "to you (all) contend toward"], ["i lo", "than"], ["outou tinā,", "you (all) mother"], ["ina finafinau atu", "so that finafinau"], ["ia;", "to"], ["auā", "for"], ["e le", "by the"], ["o la'u avā", "my wife"], ["ia,", "to"], ["e le", "by the"], ["o lana tane foi", "his man also"], ["a'u;", "me"], ["ina lafoai ia", "so that forsaken to"], ["e ia ana faitaaga ai", "by him his fornication"], ["ia te ia,", "to him"], ["ma ana mulilua foi", "and his whoring also"], ["ai", "ai"], ["le va", "the expanse"], ["o", "o"], ["ona susu;", "and milk"]]},
  {num:2,words:[["Ona ou faatauina ai lea", "and I bought then then"], ["o ia ma'u", "he opinion"], ["i tupe", "in St. Thomas bean"], ["e sefulu", "by ten"], ["ma le lima,", "and five"], ["ma le omera", "and the omera"], ["o karite,", "barley"], ["ma le leteka", "and the leteka"], ["o karite.", "barley"]]},
  {num:3,words:[["ne'i ou talaeseina", "now I talaeseina"], ["ona ofu,", "and garment"], ["ma tuu atu", "and placed"], ["ia te ia", "to him"], ["pei ona", "like then"], ["i ai", "therein"], ["i le aso", "in the day"], ["na fanau mai ai", "was born"], ["o ia,", "he"], ["e avea foi", "to become also"], ["o ia pei", "he like"], ["o se vao,", "a vegetation"], ["ma avea foi", "and become also"], ["pei o se nuu naumati,", "like a nation dry"], ["ma ou faaumatia", "and I destroyed"], ["o ia", "he"], ["i le fia inu.", "in the want to do something drink"]]},
  {num:4,words:[["Ou te", "I will"], ["le alofa atu", "the love"], ["i lana fanau,", "in his born"], ["auā", "for"], ["o le fanau", "the born"], ["a le faitaaga", "but the fornication"], ["i latou.", "them"]]},
  {num:5,words:[["Auā", "for"], ["ua faitaaga lo latou", "fornication their"], ["tinā,", "mother"], ["ua agavale lava", "agavale indeed"], ["le", "the"], ["na fanaua", "born"], ["i latou;", "them"], ["auā", "for"], ["na ia faapea mai,", "to thus from"], ["Ou te mulimuli atu", "I will follow after"], ["i", "in"], ["e o mananao", "by of desire"], ["ia te au,", "unto me"], ["o", "o"], ["e o au mai a'u", "by I am from me"], ["mea", "thing"], ["e a'i,", "to"], ["ma o'u vai,", "and my water"], ["ma a'u fulufulu mamoe,", "and me hairy sheep"], ["ma a'u lino,", "and me linen"], ["ma a'u suāuu,", "and me suāuu"], ["ma a'u mea", "and me thing"], ["e inu.", "to drink"]]},
  {num:6,words:[["O le mea lea,", "therefore"], ["faauta,", "behold"], ["ou te pupuni ai", "I will shut"], ["lou ala", "your way"], ["i laau tuitui,", "in tree prickly"], ["ou te siosioina foi", "I will surrounded also"], ["o ia", "he"], ["i le pa,", "in the a wall"], ["ia le iloa", "to the know"], ["e ia", "by him"], ["ona ala.", "and way"]]},
  {num:7,words:[["E mulimuli atu", "to follow after"], ["lava o ia", "indeed he"], ["i", "in"], ["e o mananao", "by of desire"], ["ia te ia,", "to him"], ["a", "but"], ["e le maua atu", "shall not received"], ["i latou e", "them by"], ["ia;", "to"], ["e sailiili o ia ia te", "to search he unto"], ["i latou,", "them"], ["a", "but"], ["e le iloa;", "shall not know"], ["ona faapea mai ai lea", "and thus from then then"], ["o ia,", "he"], ["Ou te alu,", "I will go"], ["ou te toe foi", "I will again also"], ["i la'u tane muamua,", "in my man first the beginning"], ["auā", "for"], ["sa sili", "most"], ["lo'u manuia anamua,", "my peace ancient"], ["i lo'u manuia", "in my peace"], ["i nei", "in this"], ["ona po.", "and night"]]},
  {num:8,words:[["Auā", "for"], ["na", "na"], ["le iloa e", "the know by"], ["ia,", "to"], ["o a'u lava", "I am indeed"], ["sa foaiina atu ia te ia", "given to him"], ["o saito,", "wheat"], ["ma uaina,", "and wine"], ["ma suāuu;", "and suāuu"], ["na a'u faateleina foi", "me multiplied also"], ["ana ario,", "his silver"], ["ma ana auro", "and his gold"], ["na latou saunia", "they prepared"], ["mo Paala.", "for a small fly-fishhook"]]},
  {num:9,words:[["O le mea lea", "therefore"], ["ou te toe foi", "I will again also"], ["ai,", "ai,"], ["ma ave ese", "and take away"], ["la'u saito", "my wheat"], ["i ona lava aso,", "in then indeed day"], ["ma la'u uaina", "and my wine"], ["i ona lava po;", "in then indeed night"], ["ou te aveesea foi", "I will removed away also"], ["a'u fulufulu mamoe,", "me hairy sheep"], ["ma a'u lino,", "and me linen"], ["sa tuuina atu", "given / delivered"], ["e ufiufi a'i", "to covering"], ["lona", "his"], ["le lavalavā.", "the naked"]]},
  {num:10,words:[["O lenei,", "now"], ["ou te faaali", "I will revealed"], ["lana amio ulavale", "his conduct mischievous"], ["i luma o", "before"], ["e o mananao", "by of desire"], ["ia te ia,", "to him"], ["e leai foi", "there is not also"], ["se tasi", "a one"], ["na te laveaiina", "he delivered"], ["o ia ai", "he"], ["lo'u lima.", "my five"]]},
  {num:11,words:[["Ou te faaumatia foi", "I will destroyed also"], ["lona fiafia uma lava,", "his competition all indeed"], ["o ana tausamiga,", "his feast"], ["ma", "and"], ["ona masina faatoa vaaia,", "and month just now seen"], ["ma", "and"], ["ona sapati,", "and Sabbath"], ["atoa ma", "and"], ["ona nuu uma.", "and nation all"]]},
  {num:12,words:[["Ou te faaumatia", "I will destroyed"], ["ona vine,", "and vine"], ["ma", "and"], ["ona mati,", "and fig"], ["na ia faapea mai ai,", "to thus from"], ["O o'u taui", "my a reward"], ["lava ia", "indeed to"], ["na au mai ia te au", "brought unto me"], ["e", "by"], ["i latou", "them"], ["ua mananao ia te au;", "desired unto me"], ["e avea foi", "to become also"], ["i latou ia te au", "them unto me"], ["ma vao matua,", "and vegetation great"], ["e 'aina", "to edible"], ["i latou", "them"], ["e manu feai.", "to animal wild"]]},
  {num:13,words:[["Ua fetalai mai", "said"], ["Ieova,", "the LORD"], ["Ou te taui atu", "I will a reward"], ["ia te ia", "to him"], ["ona", "and"], ["o", "o"], ["ona po o Paala,", "and night of a small fly-fishhook"], ["na ia faamu ai", "to burned incense"], ["mea manogi ia te", "thing fragrant unto"], ["i latou;", "them"], ["na ia tifitifi foi", "to tifitifi also"], ["ia te ia", "to him"], ["i ona mama,", "in then n"], ["ma", "and"], ["ona teuga,", "and teuga"], ["na ia mulimuli atu foi", "to followed after also"], ["i", "in"], ["e", "by"], ["na mananao ia te ia,", "desired to him"], ["a", "but"], ["ua faagalogalo lava ia te au.", "to forget indeed unto me"]]},
  {num:14,words:[["A", "but"], ["e peitai a'u", "to however me"], ["faauta,", "behold"], ["ou te faaoleole", "I will faaoleole"], ["ia te ia,", "to him"], ["ma ta'ita'i ia te ia", "and lead to him"], ["i le vao,", "in the wilderness"], ["ou te faamafanafana", "I will to hearten"], ["ia te ia.", "to him"]]},
  {num:15,words:[["Ou te tuuina atu foi", "I will give also"], ["ia te ia", "to him"], ["ana tovine", "his vineyard"], ["i lea", "in"], ["mea,", "thing"], ["ma le vanu", "and the valley"], ["o Akori", "Akori"], ["e fai ma faitotoa", "to be door"], ["e faamoemoe ai;", "to hope"], ["e pese foi", "to a song also"], ["o ia", "he"], ["i ai,", "therein"], ["faapei", "like"], ["ona fai", "and make"], ["i ona po", "in then night"], ["ina o teine muli", "so that of girl muli"], ["o ia,", "he"], ["pei o aso foi", "like of day also"], ["na sau ai", "came"], ["o ia", "he"], ["i le nuu", "in the land"], ["o Aikupito.", "Egypt"]]},
  {num:16,words:[["O loo faapea mai", "saying from"], ["Ieova,", "the LORD"], ["O le aso", "the day"], ["lava lea", "indeed"], ["e oo ai", "it shall come to pass"], ["ona", "and"], ["e faaaigoa ia te au,", "by faaaigoa unto me"], ["O Ise;", "Ise"], ["e te", "by"], ["le toe faaigoa", "the again called"], ["ia te au,", "unto me"], ["O Paale.", "Paale"]]},
  {num:17,words:[["Auā ou te aveesea", "for I will removed away"], ["i lona gutu", "in his mouth"], ["o igoa o Paala,", "name of a small fly-fishhook"], ["e le toe ta'ua", "shall not again us (two, incl)"], ["lava", "indeed"], ["i latou", "them"], ["i o latou", "in of they"], ["igoa.", "name"]]},
  {num:18,words:[["O le aso foi", "the day also"], ["lea matou te osi ai", "we (excl) osi"], ["ma", "and"], ["i latou", "them"], ["le feagaiga", "the covenant"], ["ma manu feai,", "and animal wild"], ["ma manu felelei,", "and fowl"], ["ma mea fetolofi", "and creeping things"], ["i le eleele;", "the ground"], ["ou te gausia foi", "I will gausia also"], ["le aufana", "the bow"], ["ma le pelu,", "and the sword"], ["ma le taua ai", "and the precious"], ["le nuu,", "the nation"], ["o a'u", "I am"], ["e taooto ai", "to lie down"], ["i latou", "them"], ["ma le filemu.", "and the peace"]]},
  {num:19,words:[["Ta te osi", "a stroke osi"], ["sa ta feagaiga", "a stroke covenant"], ["ma a'u", "and me"], ["e faavavau;", "forever/everlasting"], ["ta te osi", "a stroke osi"], ["sa ta feagaiga", "a stroke covenant"], ["ma a'u", "and me"], ["i le amiotonu,", "in the righteous"], ["ma le faamasinoga,", "and the judgment"], ["ma le agalelei,", "and the treated well"], ["ma le alofa.", "and the love"]]},
  {num:20,words:[["Ta te osi", "a stroke osi"], ["sa ta feagaiga", "a stroke covenant"], ["ma a'u", "and me"], ["ma le faamaoni;", "and the faithful"], ["e te iloa foi", "by know also"], ["Ieova.", "the LORD"]]},
  {num:21,words:[["O loo faapea mai", "saying from"], ["Ieova,", "the LORD"], ["O lea", "therefore"], ["aso,", "day"], ["ou te tali atu ai,", "I will respond"], ["ou te tali atu", "I will respond"], ["i le lagi,", "in heaven"], ["o ia foi", "he also"], ["na te tali atu", "he responded"], ["i le lalolagi.", "on the earth"]]},
  {num:22,words:[["E tali atu foi", "to respond also"], ["le lalolagi", "the earth"], ["i le saito,", "in the wheat"], ["ma le uaina,", "and the wine"], ["ma le suāuu;", "and the suāuu"], ["o", "o"], ["i latou foi", "them also"], ["latou te tali atu", "they will respond"], ["ia Isereelu.", "to Israelite"]]},
  {num:23,words:[["Ou te totōina", "I will planted"], ["o ia", "he"], ["i le eleele", "the ground"], ["e fai mo'u;", "to make many"], ["ou te alofa foi", "I will love also"], ["i le", "in the"], ["sa", "sa"], ["le alofagia;", "the favored"], ["ou te faapea atu foi", "I will thus also"], ["i le", "in the"], ["ua", "ua"], ["le so'u nuu,", "the so'u nation"], ["O lo'u nuu oe;", "my nation you"], ["ona latou faapea mai ai lea,", "and they thus from then then"], ["O lo matou Atua.", "our (excl) God"]]},
];
renderVerseSet(_hos_ch_2_Verses, 'hos-ch2-verses');

var _hos_ch_3_Verses = [
  {num:1,words:[["Ua fetalai mai", "said"], ["Ieova ia te au,", "the LORD unto me"], ["Ia", "to"], ["e toe alu,", "to again go"], ["ia", "to"], ["e loto atu", "to heart"], ["i se fafine", "in a woman"], ["o le", "the"], ["ua loto", "heart"], ["i ai", "therein"], ["lana uo,", "his uo"], ["a", "but"], ["o le fafine mulilua", "the woman whoring"], ["ia,", "to"], ["e pei ona", "as"], ["alofa o Ieova", "love the LORD"], ["i le fanauga", "in the children"], ["a Isaraelu o", "of Israel of"], ["e faasagasaga", "by faasagasaga"], ["i atua ese,", "in foreign gods"], ["ma mananao", "and desire"], ["i ipu uaina.", "in cup wine"]]},
  {num:2,words:[["Ona ou faatauina ai lea", "and I bought then then"], ["o ia ma'u", "he opinion"], ["i tupe", "in St. Thomas bean"], ["e sefulu", "by ten"], ["ma le lima,", "and five"], ["ma le omera", "and the omera"], ["o karite,", "barley"], ["ma le leteka", "and the leteka"], ["o karite.", "barley"]]},
  {num:3,words:[["Na a'u fai atu foi", "me said to also"], ["ia te ia,", "to him"], ["E te nofo faatali", "by dwell wait"], ["mai ia te au", "from me"], ["i aso e tele,", "in day to great"], ["aua", "for"], ["e te faitaaga,", "by fornication"], ["aua", "for"], ["e te nofo", "by dwell"], ["i se tane;", "in a man"], ["ou te nofo faatali foi", "I will dwell wait also"], ["ia te oe.", "unto you"]]},
  {num:4,words:[["Auā e tele aso", "for to great day"], ["e nonofo ai", "to dwell"], ["le fanauga", "the children"], ["a Isaraelu,", "of Israel"], ["e leai se tupu,", "there is no king"], ["e leai se alii,", "there is no Lord"], ["e leai se taulaga,", "there is no offering"], ["e leai se fata faitaulaga,", "there is no altar"], ["e leai foi", "there is not also"], ["se efota po", "a ephod night"], ["o se tupua.", "a pillar"]]},
  {num:5,words:[["E mulimuli ane,", "to follow after"], ["e toe foi mai le fanauga", "to returned the children"], ["a Isaraelu,", "of Israel"], ["latou te saili", "they will seek"], ["ia Ieova lo latou Atua,", "to the LORD their God"], ["ma Tavita lo latou tupu;", "and David their king"], ["latou te matatau foi", "they will fear also"], ["ia Ieova", "to the LORD"], ["ma lona agalelei", "and his treated well"], ["i ona po", "in then night"], ["e gata ai.", "to a snake"]]},
];
renderVerseSet(_hos_ch_3_Verses, 'hos-ch3-verses');

var _hos_ch_4_Verses = [
  {num:1,words:[["Le fanauga", "the children"], ["a Isaraelu e,", "of Israel by"], ["ia outou faalogologo", "to you (all) listen"], ["mai", "from"], ["i le afioga", "the word"], ["a Ieova;", "of the LORD"], ["auā o loo", "for is (progressive)"], ["ia Ieova", "to the LORD"], ["le finauga", "the disputation"], ["ma", "and"], ["e o nonofo", "by of dwelling"], ["i le nuu;", "in the land"], ["auā", "for"], ["e leai se faamaoni,", "there is no faithful"], ["e leai se alofa,", "there is no love"], ["e leai foi", "there is not also"], ["se", "a"], ["na te iloa", "he knew"], ["le Atua", "God"], ["i le nuu.", "in the land"]]},
  {num:2,words:[["O loo o tauto,", "is (progressive) to take an oath"], ["ma tala pepelo,", "and side false"], ["ma fasioti tagata,", "and killed man"], ["ma gaoi,", "and to steal"], ["ma mulilua,", "and whoring"], ["ua latou faasaua lava,", "they cruel indeed"], ["ua fepaia'i toto.", "pie one another blood"]]},
  {num:3,words:[["O le mea lea", "therefore"], ["e faanoanoa ai", "shall mourn"], ["le nuu,", "the nation"], ["e tauāu", "by tauāu"], ["ina vaivai o", "so that weak of"], ["i latou uma", "them all"], ["o", "o"], ["e nonofo ai;", "to dwell"], ["atoa ma manu vaefa,", "and beasts"], ["ma manu felelei,", "and fowl"], ["e mavae atu foi", "to passed also"], ["lava o i'a", "indeed of fish"], ["o le sami.", "Sea"]]},
  {num:4,words:[["A", "but"], ["e aua ne'i", "to for now"], ["i ai", "therein"], ["se tagata", "a man"], ["e finau atu,", "to contend toward"], ["ma aoai atu", "and chastise"], ["i se tasi tagata;", "in a one man"], ["auā", "for"], ["o lou nuu", "your nation"], ["ua pei o", "like of"], ["e fefinauai", "to disputing"], ["ma le ositaulaga.", "and the high priest"]]},
  {num:5,words:[["O lea", "therefore"], ["e te paū ai", "by paū"], ["i le ao,", "in the cloud"], ["e pauu foi", "to fell also"], ["le perofeta faatasi ma oe", "the prophet with you"], ["i le po;", "in the night"], ["ou te fasioti foi", "I will killed also"], ["lou tinā.", "your mother"]]},
  {num:6,words:[["Ua faaumatia", "are destroyed"], ["lo'u nuu", "my nation"], ["ina", "so that"], ["ua leai se", "there was no"], ["poto;", "wise"], ["o oe foi", "you also"], ["na e tetee atu", "you to refuse"], ["i le poto,", "in the wise"], ["o le mea lea", "therefore"], ["ou te tetee atu ai", "I will to refuse"], ["ia te oe,", "unto you"], ["e le fai oe", "shall not make you"], ["ma ositaulaga ia te au;", "and high priest unto me"], ["ua e faagalogalo", "you to forget"], ["le tulafono", "the law"], ["a lou Atua,", "but your God"], ["o a'u foi,", "I am also"], ["ou te faagalogalo", "I will to forget"], ["i lau fanau.", "in your born"]]},
  {num:7,words:[["E pei ona", "as"], ["faatoateleina o", "make many of"], ["i latou,", "them"], ["ua faapea ona", "saying and"], ["agasala mai o", "sin from of"], ["i latou ia te au;", "them unto me"], ["ou te liliu", "I will turned"], ["i le mā lo latou mamalu.", "in the First person dual exclusive their glory"]]},
  {num:8,words:[["Ua latou aai", "they city"], ["le agasala", "sin"], ["a lo'u nuu,", "but my nation"], ["ma", "and"], ["ua latou naunau", "they desired"], ["i lo latou leaga.", "than they evil"]]},
  {num:9,words:[["E oo ina gatusa", "it shall come to pass so that equal"], ["lava", "indeed"], ["o le nuu", "the nation"], ["ma le ositaulaga;", "and the high priest"], ["ou te taui atu foi", "I will a reward also"], ["ia te", "unto"], ["i latou", "them"], ["a latou amio,", "but they conduct"], ["ou te taui foi", "I will a reward also"], ["ia te", "unto"], ["i latou", "them"], ["a latou mea", "but they thing"], ["ua fai.", "made"]]},
  {num:10,words:[["Auā latou te aai,", "for they will city"], ["a", "but"], ["e le maoona;", "by the maoona"], ["e faitaaga", "to fornication"], ["i latou,", "them"], ["a", "but"], ["e le faatoateleina;", "shall not make many"], ["auā", "for"], ["ua", "ua"], ["le toe usiusitai", "the again obeyed"], ["i latou ia", "them to"], ["Ieova.", "the LORD"]]},
  {num:11,words:[["O le faitaaga,", "the fornication"], ["ma le uaina,", "and the wine"], ["ma le uaina fou", "and the wine new"], ["e aveeseina ai", "to carried away"], ["le loto.", "the heart"]]},
  {num:12,words:[["O lo'u nuu", "my nation"], ["ua latou fesili", "they asked"], ["i lo latou laau;", "than they tree"], ["ua faasino mai ai", "declared from"], ["lo latou tootoo", "their staff"], ["ia te", "unto"], ["i latou;", "them"], ["auā", "for"], ["o le fia faitaaga", "the want to do something fornication"], ["ua faaseseina ai", "deceived astray"], ["i latou ,", "them"], ["ma", "and"], ["ua latou", "they"], ["o ese", "away"], ["nai lo latou Atua e", "more than they God by"], ["faitaaga ai.", "fornication"]]},
  {num:13,words:[["Ua latou faitaulaga", "they priest"], ["i tumutumu o mauga,", "in top of mountain"], ["ma faamu mea manogi", "and burn incense thing fragrant"], ["i mea maupuepue,", "in thing maupuepue"], ["ma lalo ifo", "and under down"], ["o aluna,", "aluna"], ["ma lipeno,", "and lipeno"], ["ma tapeneto,", "and tapeneto"], ["auā", "for"], ["ua lelei lo latou", "that it was good their"], ["paolo;", "paolo"], ["o le mea lea", "therefore"], ["e faitaaga ai", "to fornication"], ["o outou afafine,", "you (all) daughter"], ["e mulilulua foi", "to whoring also"], ["a outou avā.", "but you (all) wife"]]},
  {num:14,words:[["Ou te", "I will"], ["le faasalaina o outou", "the punished of you (all)"], ["afafine", "daughter"], ["pe a latou", "even though / although they"], ["faitaaga,", "fornication"], ["ma", "and"], ["a outou avā", "but you (all) wife"], ["pe a latou", "even though / although they"], ["mulilulua;", "whoring"], ["auā o", "for of"], ["i latou lava", "them indeed"], ["ua latou", "they"], ["o ese faatasi ma fafine faitaaga,", "away together and woman fornication"], ["ua latou faitaulaga", "they priest"], ["faatasi ma fafine talitane;", "together and woman harlot"], ["o le nuu foi", "the nation also"], ["ua", "ua"], ["le mafaufau", "the think"], ["e pauu", "to fell"], ["i latou.", "them"]]},
  {num:15,words:[["Isaraelu e,", "Israel by"], ["e ui", "to although"], ["ina", "so that"], ["e faitaaga,", "to fornication"], ["a", "but"], ["e aua ne'i agasala Iuta;", "to for now sin Judas"], ["aua tou te", "for second person plural"], ["o mai", "from"], ["i Kilikala,", "in Gilgal"], ["aua tou te", "for second person plural"], ["o ae", "go up"], ["i Petavene,", "in Beth-aven"], ["aua foi", "for also"], ["tou te tauto,", "second person plural to take an oath"], ["O loo soifua Ieova.", "is (progressive) live the LORD"]]},
  {num:16,words:[["Auā", "for"], ["e faapei", "to like"], ["ona vaogata", "and disobedient"], ["o se povi fafine taanoa,", "a cattle woman an animal that is weaned"], ["ua faapea ona", "saying and"], ["vaogata o Isaraelu;", "disobedient of Israel"], ["a", "but"], ["e fagaina", "to a bay"], ["i latou", "them"], ["i nei", "in this"], ["ona po", "and night"], ["e Ieova", "the LORD"], ["e faapei", "to like"], ["o se tamai mamoe", "a son sheep"], ["i le mea lautele.", "in the thing wide"]]},
  {num:17,words:[["Ua pipii Efaraima", "pipii Ephraim"], ["i tupua;", "in pillar"], ["ina tuu ai", "so that put"], ["pea ia ia te ia.", "continually to him to"]]},
  {num:18,words:[["A uma lo latou inuga'ava,", "but all their inuga'ava"], ["ua matuā faitaaga", "exceedingly fornication"], ["i latou;", "them"], ["ua loto atu", "heart"], ["o latou alii", "they Lord"], ["i mea", "in thing"], ["e masiasi ai.", "to to be ashamied"]]},
  {num:19,words:[["Ua saisaitia o ia", "saisaitia he"], ["e le matagi", "shall not wind"], ["i ona apaau,", "in then a wing"], ["e masiasi foi", "to to be ashamied also"], ["i latou", "them"], ["ona o", "because of"], ["a latou taulaga.", "but they offering"]]},
];
renderVerseSet(_hos_ch_4_Verses, 'hos-ch4-verses');

var _hos_ch_5_Verses = [
  {num:1,words:[["Le au ositaulaga e,", "the me high priest by"], ["faalogologo mai ia", "listen from to"], ["i lenei", "in this"], ["mea.", "thing"], ["Le aiga o Isaraelu e,", "the family of Israel by"], ["ina faalogologo mai ia.", "so that listen from to"], ["Le aiga", "the family"], ["o le tupu e,", "the king by"], ["ina liliu mai ia", "so that turned from to"], ["o outou fofoga,", "you (all) face"], ["auā", "for"], ["ua faasalaina outou,", "punished you (all)"], ["ua avea outou", "became you (all)"], ["ma matāsele", "and matāsele"], ["i Mesepa,", "in Mizpah"], ["ma upega", "and net"], ["ua folasia", "folasia"], ["i Tapora.", "in Tapora"]]},
  {num:2,words:[["Ua faateleina", "multiplied"], ["le fasi e", "the kill by"], ["i latou", "them"], ["ua liliu ese,", "turned away"], ["a", "but"], ["o a'u,", "I am"], ["ou te aoai atu", "I will chastise"], ["ia te", "unto"], ["i latou uma.", "them all"]]},
  {num:3,words:[["O a'u", "I am"], ["ua ou iloa", "I knew"], ["Efaraima,", "Ephraim"], ["o Isaraelu foi", "Israel also"], ["ua", "ua"], ["le lilo lava", "the secret indeed"], ["ia ia te au;", "to him me"], ["auā,", "for"], ["Efaraima e,", "Ephraim by"], ["ua e faitaaga nei,", "you fornication this"], ["ua leaga Isaraelu.", "evil Israel"]]},
  {num:4,words:[["Latou te", "they will"], ["le sauniuni", "the prepared"], ["a latou galuega", "but they work"], ["ina ia latou", "so that they"], ["liliu mai", "turned from"], ["i lo latou Atua;", "than they God"], ["auā o", "for of"], ["i totonu ia te", "in inside unto"], ["i latou", "them"], ["le fia faitaaga,", "the want to do something fornication"], ["latou te", "they will"], ["le iloa Ieova.", "the know the LORD"]]},
  {num:5,words:[["Ua molimau", "a witness"], ["le faamaualuga o Isaraelu", "the exalted of Israel"], ["i o latou", "in of they"], ["luma,", "before"], ["e pauu Isaraelu", "to fell Israel"], ["ma Efaraima", "and Ephraim"], ["i", "in"], ["a latou agasala;", "but they sin"], ["e paū foi", "by paū also"], ["Iuta faatasi ma", "Judas together and"], ["i latou.", "them"]]},
  {num:6,words:[["Latou te o atu", "they will"], ["ma", "and"], ["a latou mamoe", "but they sheep"], ["ma", "and"], ["a latou povi", "but they cattle"], ["e sailiili atu ai", "to search"], ["ia Ieova;", "to the LORD"], ["a e latou te", "but by they will"], ["le maua;", "the received"], ["ua afio ese", "dwelt (respectful) away"], ["o ia ia te", "he unto"], ["i latou.", "them"]]},
  {num:7,words:[["Ua pepelo", "false"], ["i latou ia", "them to"], ["Ieova;", "the LORD"], ["auā", "for"], ["ua fanau e", "born you"], ["i latou", "them"], ["a latou tama ese;", "but they child away"], ["o le a 'aina nei", "what edible this"], ["i latou,", "them"], ["atoa ma o latou", "and they"], ["tofi", "lot"], ["i le masina", "in the month"], ["e tasi .", "by one"]]},
  {num:8,words:[["Ia outou ilia", "to you (all) ilia"], ["le sofao", "the sofao"], ["i Kipea,", "in Gibeah"], ["ma le pu", "and the the tail"], ["i Rama;", "in Ramah"], ["ia outou alalaga", "to you (all) cry out"], ["i Petavene;", "in Beth-aven"], ["Peniamina e,", "Benjamin by"], ["o loo mulimuli atu", "is (progressive) follow after"], ["o ia ia te oe.", "he unto you"]]},
  {num:9,words:[["E faatafunaina Efaraima", "to destroyed Ephraim"], ["i ona po", "in then night"], ["o le aoaiga;", "the discipline"], ["ua ou faailoaina atu", "I revealed"], ["i itu aiga", "in side family"], ["o Isaraelu,", "Israel"], ["o le upu moni lava.", "the word true indeed"]]},
  {num:10,words:[["O alii o Iuta", "Lord of Judas"], ["sa faapei o tagata", "like of men"], ["e sii", "to lift up"], ["le tuaoi", "the border"], ["i latou;", "them"], ["ou te liligi atu", "I will to pour"], ["lo'u ita faapei", "my angry like"], ["o le vai", "the water"], ["ia te", "unto"], ["i latou.", "them"]]},
  {num:11,words:[["Ua faasauaina Efaraima,", "cruel Ephraim"], ["ua lomia", "lomia"], ["i le faamasinoga;", "in the judgment"], ["auā", "for"], ["ua usiusitai o ia", "he obeyed"], ["ma lona loto", "and his heart"], ["i le poloaiga.", "in the commandment"]]},
  {num:12,words:[["O a'u foi", "I am also"], ["e pei o se mogamoga", "like a cockroach"], ["i Efaraima;", "in Ephraim"], ["e pei o se mea", "like a thing"], ["e pala foi", "to a muddy deposit in the sea also"], ["i le aiga", "in the family"], ["o Iuta.", "Judas"]]},
  {num:13,words:[["Na iloa", "knew"], ["e Efaraima", "to Ephraim"], ["lona ma'i,", "his from"], ["na iloa foi", "knew also"], ["e Iuta", "to Judas"], ["lona manua,", "his manua"], ["ona alu lea", "And he went"], ["o Efaraima", "Ephraim"], ["i Asuria,", "in Assyria"], ["na alu", "went"], ["lana feau ia", "his errand to"], ["Iarepa", "Iarepa"], ["le tupu;", "the king"], ["a", "but"], ["ua", "ua"], ["le mafai lava", "the able indeed"], ["ia te ia", "to him"], ["ona faamalolo ia te outou,", "and refresh unto you"], ["pe faamafuina o outou", "whether make stale of you (all)"], ["manua.", "manua"]]},
  {num:14,words:[["Auā", "for"], ["e avea a'u", "to become me"], ["e pei o se leona", "like a lion"], ["ia Efaraima,", "to Ephraim"], ["e pei o se leona taanoa foi", "like a lion an animal that is weaned also"], ["i le aiga", "in the family"], ["o Iuta;", "Judas"], ["o a'u lava ou te saeia", "I am indeed I will spared"], ["ma alu ese,", "and go away"], ["ou te aveesea,", "I will removed away"], ["e leai foi", "there is not also"], ["se", "a"], ["na te laveaiina.", "he delivered"]]},
  {num:15,words:[["Ou te alu,", "I will go"], ["ou te toe foi", "I will again also"], ["lava", "indeed"], ["i le mea ou te nofo ai,", "in the thing I will dwell"], ["seia faasalaina lava", "until punished indeed"], ["i latou,", "them"], ["ma latou saili", "and they seek"], ["ia te au;", "unto me"], ["latou te vave saili", "they will quick seek"], ["ia te au", "unto me"], ["pe a puapuagatia", "even though / although puapuagatia"], ["i latou.", "them"]]},
];
renderVerseSet(_hos_ch_5_Verses, 'hos-ch5-verses');

var _hos_ch_6_Verses = [
  {num:1,words:[["O mai ia,", "from to"], ["ina tatou toe foi atu", "so that we (incl) went back"], ["ia Ieova;", "to the LORD"], ["auā o ia", "for he"], ["ua", "ua"], ["na saeia,", "spared"], ["na te faamaloloina foi", "he healed also"], ["i tatou;", "in we (incl)"], ["ua ia fasia,", "to slaughtered"], ["na te fofoina foi", "he to doctor also"], ["i tatou.", "in we (incl)"]]},
  {num:2,words:[["Na te faaolaina mai", "he saved alive from"], ["i tatou", "in we (incl)"], ["pe a mavae aso", "even though / although passed day"], ["e lua;", "by two"], ["a oo", "but oo"], ["i lona tolu", "in his three"], ["o aso", "day"], ["na te faatutūina", "he made stood up"], ["i tatou,", "in we (incl)"], ["tatou te ola", "we will life"], ["mai ai", "from"], ["i ona luma.", "before him"]]},
  {num:3,words:[["Tatou te iloa foi", "we will know also"], ["o loo o tatou", "is (progressive) we (incl)"], ["tausisi atu ia", "tausisi to"], ["iloa Ieova;", "know the LORD"], ["ua saunia", "prepared"], ["lona afio atu", "his dwell (respectful)"], ["e pei o le taeao,", "like the morning"], ["e afio mai foi", "to dwell (respectful) from also"], ["o ia ia te", "he unto"], ["i tatou", "in we (incl)"], ["e pei o le", "like the"], ["ua,", "ua,"], ["e pei o le timu mulimuli", "like the rain follow after"], ["ma le timu muamua", "and the rain first the beginning"], ["i le eleele.", "the ground"]]},
  {num:4,words:[["Efaraima e,", "Ephraim by"], ["se a ea", "what indeed? / why?"], ["se mea ou te faia", "a thing I will make"], ["ia te oe?", "unto you"], ["Iuta e,", "Judas by"], ["se a ea", "what indeed? / why?"], ["se mea ou te faia", "a thing I will make"], ["ia te oe?", "unto you"], ["auā", "for"], ["ua pei o le", "like the"], ["puao", "puao"], ["i le taeao la outou amio lelei,", "in the morning your conduct good"], ["e pei o le sau foi", "like the come also"], ["i le vave ao", "in the quick day"], ["ona mavae atu.", "and passed"]]},
  {num:5,words:[["O le mea lea", "therefore"], ["ua ou fasia ai", "I slaughtered"], ["i latou", "them"], ["e le au", "shall not me"], ["perofeta,", "prophet"], ["ua ou fasiotia", "I slain"], ["i latou", "them"], ["i upu", "in word"], ["a lo'u gutu;", "but my mouth"], ["o au faamasinoga foi", "I am judgment also"], ["o le malamalama", "the light"], ["e alu atu lea.", "to go away"]]},
  {num:6,words:[["Auā", "for"], ["o le alofa ou te loto", "the love I will heart"], ["i ai,", "therein"], ["a", "but"], ["e le", "by the"], ["o le taulaga;", "the offering"], ["ia iloa foi", "to know also"], ["le Atua e sili lea", "God to most"], ["i lo'u manatu", "in my thought"], ["i taulaga mu.", "in burnt offerings"]]},
  {num:7,words:[["A", "but"], ["ua latou soli", "they to tread upon"], ["le feagaiga,", "the covenant"], ["e pei o Atamu;", "like Adam"], ["ua latou pepelo ia te au", "they false unto me"], ["i lea", "in"], ["mea.", "thing"]]},
  {num:8,words:[["O Kiliata", "Gilead"], ["o le aai lea", "the city"], ["o", "o"], ["e fai amio leaga,", "to make iniquity"], ["o loo leaga,", "is (progressive) evil"], ["i le toto.", "in the blood"]]},
  {num:9,words:[["Faapei", "like"], ["ona lamalama", "and lamalama"], ["i se tagata", "in a man"], ["o", "o"], ["e fao mea,", "to to seize thing"], ["e faapea foi", "saying also"], ["le au ositaulaga", "the me high priest"], ["ona fasioti tagata", "and killed man"], ["i le ala", "in the way"], ["i Sekema;", "in Shechem"], ["auā", "for"], ["ua ulavale", "mischievous"], ["i latou.", "them"]]},
  {num:10,words:[["Ua a'u iloa", "me knew"], ["i le aiga", "in the family"], ["o Isaraelu", "Israel"], ["le mea", "the thing"], ["e matuā leaga;", "to exceedingly evil"], ["ua", "ua"], ["i ai", "therein"], ["le faitaaga o Efaraima,", "the fornication of Ephraim"], ["ua leaga Isaraelu.", "evil Israel"]]},
  {num:11,words:[["Iuta e,", "Judas by"], ["ua tuu", "put"], ["mo oe lava", "for you indeed"], ["le seleselegāsaito", "the seleselegāsaito"], ["ina", "so that"], ["ua ou faafoisia", "I restored"], ["le tafeaga", "the exiles in wa^"], ["a lo'u nuu.", "but my nation"]]},
];
renderVerseSet(_hos_ch_6_Verses, 'hos-ch6-verses');

var _hos_ch_7_Verses = [
  {num:1,words:[["Na fai", "made"], ["a a'u faamaloloina", "but me healed"], ["o Isaraelu,", "Israel"], ["ona mānu mai ai lea", "and mānu from then then"], ["o le leaga", "the evil"], ["o Efaraima", "Ephraim"], ["ma amio leaga", "and iniquity"], ["a Samaria;", "of Samaria"], ["auā", "for"], ["ua latou fai", "they made"], ["le amio pepelo;", "the conduct false"], ["e ulufale mai le gaoi,", "to enter from the to steal"], ["a", "but"], ["e osofia", "by osofia"], ["i fafo", "in outside"], ["e le au", "shall not me"], ["fao mea.", "to seize thing"]]},
  {num:2,words:[["Latou to", "they to plant"], ["le faapea ifo", "the thus down"], ["i o latou", "in of they"], ["loto,", "heart"], ["Ou te manatua la latou amio leaga uma;", "I will remember their iniquity all"], ["o lenei,", "now"], ["ua siosiomia", "surrounded"], ["i latou", "them"], ["i", "in"], ["a latou lava galuega,", "but they indeed work"], ["ua", "ua"], ["i o'u luma", "before me"], ["ia mea.", "to thing"]]},
  {num:3,words:[["Latou te faafiafia", "they will to please"], ["le tupu", "the king"], ["i", "in"], ["a latou amio leaga;", "but they iniquity"], ["atoa ma alii", "and Lord"], ["i", "in"], ["a latou tala pepelo.", "but they side false"]]},
  {num:4,words:[["Ua mulilulua", "whoring"], ["i latou uma;", "them all"], ["pei", "like"], ["se ogaumu", "a ogaumu"], ["i latou", "them"], ["ua faaaasaina", "faaaasaina"], ["e le fai areto;", "shall not make bread"], ["ua", "ua"], ["le toe tafu", "the again to make up the fire"], ["pe a uma ona", "even though / although all then"], ["lolomi", "lolomi"], ["o le palugāfalaoa seia faafefeteina.", "the palugāfalaoa until feared"]]},
  {num:5,words:[["O le aso", "the day"], ["o lo tatou tupu", "our king"], ["na mama'i ai", "mama'i"], ["alii", "Lord"], ["i le oona", "in the drunk"], ["o uaina;", "wine"], ["na ia faaloaloa atu", "to stretched out"], ["lona lima faatasi ma ē tauemu.", "his five together and who mock"]]},
  {num:6,words:[["Auā", "for"], ["ua latou faalatalata", "they drew near"], ["ma o latou", "and of they"], ["loto,", "heart"], ["e pei o se ogaumu,", "like a ogaumu"], ["a o latou", "but of they"], ["o lamalama;", "lamalama"], ["ua aoina o", "aoina of"], ["moe lo latou fai areto,", "sleep their make bread"], ["ua mu", "mu"], ["i le taeao pei", "in the morning like"], ["se afi mumū.", "a fire mumū"]]},
  {num:7,words:[["Ua aasa", "Asa"], ["i latou uma", "them all"], ["e pei o se ogaumu,", "like a ogaumu"], ["ua latou faaumatia", "they destroyed"], ["o latou alii faamasino;", "they Lord judge"], ["ua pauu o", "fell of"], ["latou tupu uma,", "they king all"], ["e leai so latou", "there is not so they"], ["e valaau ia te au.", "to call unto me"]]},
  {num:8,words:[["O Efaraima", "Ephraim"], ["ua numia o ia", "numia he"], ["e ia faatasi ma le nuu;", "by him together and the nation"], ["o Efaraima", "Ephraim"], ["o le potoi areto", "the cake bread"], ["ia", "to"], ["e lei liua.", "by not turned into"]]},
  {num:9,words:[["Ua faaumatia", "are destroyed"], ["e tagata ese", "to man away"], ["lona malosi,", "his strong"], ["a", "but"], ["ua", "ua"], ["le iloa e", "the know by"], ["ia;", "to"], ["ua pule", "ruled"], ["le sinā", "the sinā"], ["o lona lauulu,", "his the hair of the head"], ["a", "but"], ["ua", "ua"], ["le iloa e", "the know by"], ["ia.", "to"]]},
  {num:10,words:[["Ua molimau", "a witness"], ["le faamaualuga o Isaraelu", "the exalted of Israel"], ["i o latou", "in of they"], ["luma;", "before"], ["e ui lava", "to although indeed"], ["i ia mea uma,", "in to all things"], ["ua latou", "they"], ["le toe foi", "the again also"], ["ia Ieova lo latou Atua,", "to the LORD their God"], ["ua latou", "they"], ["le saili foi", "the seek also"], ["ia te ia.", "to him"]]},
  {num:11,words:[["O Efaraima foi", "Ephraim also"], ["e pei o se lupe valea", "like a dove foolish"], ["ia,", "to"], ["e leai sona mafaufau;", "there is not sona think"], ["latou te valaau", "they will call"], ["ia Aikupito,", "to Egypt"], ["ua o foi", "of also"], ["i latou", "them"], ["i Asuria.", "in Assyria"]]},
  {num:12,words:[["A latou o,", "but they of"], ["ou te lafo", "I will cloth used as gratuity for a talking chief"], ["la'u upega", "my net"], ["i luga ia te", "in above unto"], ["i latou;", "them"], ["ou te lafo", "I will cloth used as gratuity for a talking chief"], ["i lalo ia te", "in under unto"], ["i latou pei ni manu felelei;", "them like some fowl"], ["ou te sasa foi", "I will a scourge also"], ["ia te", "unto"], ["i latou", "them"], ["e pei ona", "as"], ["faalogo", "hearken"], ["i ai", "therein"], ["lo latou potopotoga.", "their gathering"]]},
  {num:13,words:[["O", "O"], ["i talofa ia te", "in hello unto"], ["i latou!", "them"], ["auā", "for"], ["ua sosola ese", "fled away"], ["i latou ia te au;", "them unto me"], ["ia malaia", "to disaster"], ["i latou!", "them"], ["auā", "for"], ["ua latou fouvale ia te au;", "they to rebel unto me"], ["na ou togiola foi", "I atonement also"], ["ia te", "unto"], ["i latou,", "them"], ["a", "but"], ["ua latou tala", "they side"], ["pepelo ia leaga ai", "false to evil"], ["a'u.", "me"]]},
  {num:14,words:[["Ua", "Ua"], ["le valaau mai", "the call from"], ["i latou ia te au", "them unto me"], ["ma o latou", "and of they"], ["loto,", "heart"], ["ina", "so that"], ["ua latou uio", "they uio"], ["i o latou", "in of they"], ["moega;", "bed"], ["latou te faapotopoto", "they will gather"], ["i saito", "in wheat"], ["ma uaina;", "and wine"], ["latou te o ese", "they will away"], ["ia te au.", "unto me"]]},
  {num:15,words:[["O a'u foi,", "I am also"], ["na ou a'oa'o atu,", "I excellent"], ["na ou faamalosiina", "I was strong"], ["o latou lima,", "they five"], ["a", "but"], ["ua latou taupulepule", "they taupulepule"], ["i mea", "in thing"], ["e leaga ai", "to evil"], ["a'u.", "me"]]},
  {num:16,words:[["Ua latou toe foi,", "they again also"], ["a", "but"], ["e le o lē Silisili ese", "by the of not very much away"], ["ua latou foi", "they also"], ["i ai;", "therein"], ["e pei o le aufana pepelo", "like the bow false"], ["i latou;", "them"], ["e pauu o latou", "to fell of they"], ["alii", "Lord"], ["i le pelu", "by the sword"], ["ona", "and"], ["o le faasiasia", "the haughty"], ["o latou laulaufaiva;", "they tongue"], ["e fai", "to make"], ["mo latou gao lea", "for they gao"], ["mea", "thing"], ["i le nuu", "in the land"], ["o Aikupito.", "Egypt"]]},
];
renderVerseSet(_hos_ch_7_Verses, 'hos-ch7-verses');

var _hos_ch_8_Verses = [
  {num:1,words:[["Ia", "to"], ["e ili", "by ili"], ["le pu;", "the the tail"], ["e sau o ia", "to come he"], ["e pei o se aeto", "like a aeto"], ["i le aiga", "in the family"], ["o Ieova;", "the LORD"], ["auā", "for"], ["ua latou soli", "they to tread upon"], ["la'u feagaiga,", "my covenant"], ["ma", "and"], ["ua latou fouvale", "they to rebel"], ["i la'u tulafono.", "in my law"]]},
  {num:2,words:[["E alalaga", "to cry out"], ["i latou ia te au,", "them unto me"], ["Lo matou Atua e,", "our God by"], ["o Isaraelu", "Israel"], ["i matou ,", "in we (excl)"], ["ua matou iloa oe.", "we (excl) knew you"]]},
  {num:3,words:[["Ua lafoaiina", "forsaken"], ["e Isaraelu", "to Israel"], ["le mea lelei;", "the thing good"], ["e tuliloaina o ia", "to pursue he"], ["e le", "by the"], ["ua ita ia te ia", "angry to him"], [".", "."]]},
  {num:4,words:[["Ua latou tofia", "they chosen"], ["tupu", "king"], ["a", "but"], ["e le mai ia te au;", "by the from me"], ["ua latou tofia", "they chosen"], ["alii", "Lord"], ["a", "but"], ["e le iloa", "shall not know"], ["e a'u;", "to me"], ["o latou ario,", "they silver"], ["ma o latou", "and of they"], ["auro", "gold"], ["ua latou fai a'i", "they thereby"], ["tupua", "pillar"], ["mo", "for"], ["i latou,", "them"], ["ina ia faaumatia ai", "so that destroyed"], ["i latou .", "them"]]},
  {num:5,words:[["Samaria e,", "Samaria by"], ["ua lafoaiina oe", "forsaken you"], ["e lau tamai povi;", "by your son cattle"], ["ua tupu", "king"], ["lo'u ita ia te", "my angry unto"], ["i latou;", "them"], ["pe latou te", "whether they will"], ["le mafai seia afea", "the able how long?/until when?"], ["ona mamā?", "and clean"]]},
  {num:6,words:[["Auā mai ia", "for from to"], ["Isaraelu lava ia;", "Israel indeed to"], ["na faia o ia", "made he"], ["e le tufuga;", "shall not master builder"], ["e le", "by the"], ["o le Atua", "of God"], ["lava ia,", "indeed to"], ["o le mea lea", "therefore"], ["e nutililiiina ai", "by nutililiiina"], ["le tamai povi", "the son cattle"], ["o Samaria.", "Samaria"]]},
  {num:7,words:[["Na latou luluina", "they shaken"], ["le matagi,", "the wind"], ["o le mea lea", "therefore"], ["latou te selesele", "they will an evenly cut head of"], ["mai ai", "from"], ["le afā;", "the cyclone"], ["ua leai sona", "there was not sona"], ["tino;", "body"], ["e le tupu", "shall not king"], ["se saito", "a wheat"], ["i le fuga,", "in the flower"], ["a", "but"], ["e afai", "to if"], ["e fua,", "to fruit"], ["e 'aina", "to edible"], ["e tagata ese.", "to man away"]]},
  {num:8,words:[["Ua faaumatia Isaraelu;", "are destroyed Israel"], ["latou te", "they will"], ["i ai", "therein"], ["nei", "this"], ["i nuu ese,", "in nation away"], ["e pei o se ipu", "like a cup"], ["e leai sē fiafia", "there is not sē competition"], ["i ai.", "therein"]]},
  {num:9,words:[["Auā", "for"], ["ua latou", "they"], ["o ae", "go up"], ["i Asuria,", "in Assyria"], ["ua", "ua"], ["se asini", "a donkey"], ["o le vao", "the vegetation"], ["ua nofo toatasi;", "dwelt one One"], ["ua faaoloaina", "made goods"], ["e Efaraima", "to Ephraim"], ["e o mananao", "by of desire"], ["ia te ia", "to him"], [".", "."]]},
  {num:10,words:[["A", "but"], ["e ui", "to although"], ["ina latou faaoloaina nuu ese,", "so that they make goods nation away"], ["ou te faapotopoto nei", "I will gather this"], ["ia te", "unto"], ["i latou;", "them"], ["e le pine", "shall not to be long"], ["ona tiga o", "and grieved of"], ["i latou", "them"], ["ona", "and"], ["o le avega", "the burden"], ["mai le tupu", "from the king"], ["o alii.", "Lord"]]},
  {num:11,words:[["Ua faia", "made"], ["e Efaraima fata faitaulaga", "to Ephraim altar"], ["e tele,", "to great"], ["e agasala ai;", "to sin"], ["o le mea lea", "therefore"], ["ua avea ai", "became"], ["fata faitaulaga", "altar"], ["ma mea", "and thing"], ["e agasala ai", "to sin"], ["o ia.", "he"]]},
  {num:12,words:[["Ua ou tusi atu ia te ia", "I book to him"], ["o mea tetele", "thing great"], ["i la'u tulafono;", "in my law"], ["a", "but"], ["ua ta'ua ia", "us (two, incl) to"], ["mea o mea ese.", "thing of thing away"]]},
  {num:13,words:[["Latou te fai taulaga", "they will make offering"], ["i manu", "in animal"], ["e fai ma taulaga", "to be offering"], ["mo a'u,", "for me"], ["ma latou aai ai;", "and they city"], ["a", "but"], ["ua", "ua"], ["le talia", "the received"], ["i latou", "them"], ["e Ieova;", "the LORD"], ["e manatua nei", "to remember this"], ["e ia", "by him"], ["a latou amio leaga,", "but they iniquity"], ["ma taui", "and a reward"], ["i", "in"], ["a latou agasala;", "but they sin"], ["latou te toe foi", "they will again also"], ["i Aikupito.", "in Egypt"]]},
  {num:14,words:[["Auā", "for"], ["ua faagalogalo", "to forget"], ["e Isaraelu", "to Israel"], ["i Lē", "in not"], ["na faia o ia,", "made he"], ["ua faatuina e", "built you"], ["ia", "to"], ["o malumalu;", "temple"], ["o Iuta foi", "Judas also"], ["ua ia faateleina", "to multiplied"], ["o aai nofo 'olo;", "city dwell fortress"], ["ou te tuuina atu", "I will give"], ["le afi", "the fire"], ["i ana aai,", "in his city"], ["e faaumatia ai", "to destroyed"], ["ona maota.", "and the name of a tree"]]},
];
renderVerseSet(_hos_ch_8_Verses, 'hos-ch8-verses');

var _hos_ch_9_Verses = [
  {num:1,words:[["Isaraelu e,", "Israel by"], ["aua", "for"], ["e te fiafia", "by competition"], ["ma le olioli,", "and the rejoice"], ["faapei o isi nuu;", "like of other nation"], ["auā", "for"], ["ua e alu ese", "you went away"], ["i lou Atua e", "in your God by"], ["faitaaga ai;", "fornication"], ["ua e fia", "you wanted to do something"], ["fai taui", "make a reward"], ["i mea uma", "in all things"], ["e sasa ai", "to a scourge"], ["saito.", "wheat"]]},
  {num:2,words:[["E le fagaina", "shall not a bay"], ["i latou", "them"], ["i le mea", "in the thing"], ["e sasa ai", "to a scourge"], ["saito", "wheat"], ["ma le soligāvine,", "and the soligāvine"], ["e oge ai", "to a famine"], ["uaina fou.", "wine new"]]},
  {num:3,words:[["Latou te", "they will"], ["le nonofo", "the dwelling"], ["i le nuu", "in the land"], ["o Ieova,", "the LORD"], ["a", "but"], ["e toe foi", "to again also"], ["Efaraima", "Ephraim"], ["i Aikupito,", "in Egypt"], ["latou te aai mea leaga", "they will city thing evil"], ["i Asuria.", "in Assyria"]]},
  {num:4,words:[["Latou te", "they will"], ["le fai taulaga", "the make offering"], ["ia Ieova", "to the LORD"], ["i uaina,", "in wine"], ["e le fiafia", "shall not competition"], ["o ia ia te", "he unto"], ["i latou;", "them"], ["o", "o"], ["a latou taulaga,", "but they offering"], ["e ia te", "by him"], ["i latou ia,", "them to"], ["peiseai o mea", "as if of thing"], ["e 'ai", "to eat"], ["a", "but"], ["e faanoanoa,", "to mourn"], ["o", "o"], ["i latou uma", "them all"], ["e aai ai", "to city"], ["e leaga ai", "to evil"], ["i latou;", "them"], ["auā", "for"], ["o la latou mea", "their thing"], ["e 'ai mā latou", "to eat First person dual exclusive they"], ["e le oo atu lea", "by the arrived"], ["i le fale", "in the house"], ["o Ieova.", "the LORD"]]},
  {num:5,words:[["Se a se mea tou te faia", "a but a thing second person plural made"], ["i le aso", "in the day"], ["e fai ai", "to make"], ["le tausamiga,", "the feast"], ["ma le aso", "and the day"], ["e fai ai", "to make"], ["le taulaga ia", "the offering to"], ["Ieova?", "the LORD"]]},
  {num:6,words:[["Auā,", "for"], ["faauta mai,", "behold from"], ["ua o", "of"], ["i latou ne'i malaia;", "them now disaster"], ["e faapotopotoina", "to gathered together"], ["i latou", "them"], ["e Aikupito,", "to Egypt"], ["e tanumia", "to buried"], ["i latou", "them"], ["e Mafi;", "by Mafi"], ["o mea matagofie", "thing beautiful"], ["o", "o"], ["i ai", "therein"], ["o latou ario", "they silver"], ["e vaoa ia", "to overgrown with weeds to"], ["i laau ogoogo;", "in tree ogoogo"], ["e", "by"], ["i ai", "therein"], ["i o latou", "in of they"], ["fale o laau talatala.", "house of tree to untie"]]},
  {num:7,words:[["Ua oo mai", "it came to pass from"], ["ona po", "and night"], ["e taui ai,", "to a reward"], ["ua oo mai", "it came to pass from"], ["ona po", "and night"], ["e totogi ai;", "to wages"], ["e iloa", "to know"], ["e Isaraelu;", "to Israel"], ["ua valea", "foolish"], ["le perofeta,", "the prophet"], ["ua valea lava", "foolish indeed"], ["le vaafaatau,", "the vaafaatau"], ["ona", "and"], ["o le tele", "the great"], ["o lau amio leaga,", "your iniquity"], ["ma le 'ino'ino tele.", "and the hate great"]]},
  {num:8,words:[["O loo faatalitali Efaraima", "is (progressive) waited Ephraim"], ["faatasi", "together"], ["i lo'u Atua;", "in my God"], ["ua", "ua"], ["se mailei o", "a a trap of"], ["e fāi manu", "by fāi animal"], ["le perofeta", "the prophet"], ["i ana amio uma;", "in his conduct all"], ["o le 'ino'ino", "the hate"], ["i le fale", "in the house"], ["o lona Atua.", "his God"]]},
  {num:9,words:[["Ua matuā amio leaga", "exceedingly iniquity"], ["i latou,", "them"], ["faapei", "like"], ["ona fai", "and make"], ["i ona po", "in then night"], ["o Kipea;", "Gibeah"], ["e manatua e", "to remember by"], ["ia", "to"], ["a latou agasala,", "but they sin"], ["e taui atu", "to a reward"], ["i", "in"], ["a latou amio leaga.", "but they iniquity"]]},
  {num:10,words:[["Na ou maua", "I received"], ["Isaraelu,", "Israel"], ["e pei o fuifui vine", "like to dip vine"], ["i le vao;", "in the wilderness"], ["na ou iloa", "I knew"], ["o outou mātua", "you (all) mātua"], ["e pei o uluai mati", "like first fig"], ["i le mati", "in the fig"], ["ina", "so that"], ["ua faatoa fua mai;", "just now fruit from"], ["a", "but"], ["ua o", "of"], ["i latou ia", "them to"], ["Paalapeoro,", "Paalapeoro"], ["ua vavae atu", "to divide"], ["i latou", "them"], ["i le mea", "in the thing"], ["e masiasi ai;", "to to be ashamied"], ["ua inosia", "abominable"], ["i latou", "them"], ["e tusa ma le mea", "according to the thing"], ["ua latou naunau", "they desired"], ["i ai.", "therein"]]},
  {num:11,words:[["O Efaraima", "Ephraim"], ["e lele ese lo latou mamalu faapei", "to fly away their glory like"], ["o le manu lele,", "the animal fly"], ["ai", "ai"], ["le fanauga,", "the children"], ["ma le manava,", "and the womb"], ["ma le faatoa afuafua.", "and the just now to become pregnant"]]},
  {num:12,words:[["E ui", "to although"], ["ina latou tausi", "so that they nurse"], ["a latou fanau,", "but they born"], ["ou te aveeseina", "I will carried away"], ["i latou", "them"], ["i tagata;", "in man"], ["oi talofa lava", "wo indeed"], ["ia te", "unto"], ["i latou,", "them"], ["pe a a'u", "even though / although me"], ["alu ese ia te", "go away unto"], ["i latou.", "them"]]},
  {num:13,words:[["Ua totōina Efaraima", "planted Ephraim"], ["i le mea matagofie,", "in the thing beautiful"], ["faapei", "like"], ["ona ou iloa", "and I know"], ["o Turo;", "Tyre"], ["a o Efaraima", "but of Ephraim"], ["na te ta'ita'iina atu", "he led"], ["lana fanau", "his born"], ["i le fasioti tagata.", "in the killed man"]]},
  {num:14,words:[["Ieova e,", "O LORD!"], ["ia", "to"], ["e avatu ia te", "to give away unto"], ["i latou;", "them"], ["se a foi", "a but also"], ["se mea", "a thing"], ["e te avatua?", "by given away"], ["Ia", "to"], ["e avatu ia te", "to give away unto"], ["i latou", "them"], ["le manava fanau", "the womb born"], ["le au,", "the me"], ["ma susu", "and milk"], ["e le susua.", "shall not plural of sua"]]},
  {num:15,words:[["O loo", "is/are (progressive)"], ["i Kilikala lo latou leaga uma;", "in Gilgal their evil all"], ["auā", "for"], ["na ou 'ino'ino ia te", "I hated unto"], ["i latou", "them"], ["i lea", "in"], ["mea,", "thing"], ["ou te tulia", "I will driven away"], ["i latou ai", "them"], ["lo'u fale", "my house"], ["ina", "so that"], ["ua leaga mea", "evil thing"], ["ua latou faia;", "they did"], ["ou te", "I will"], ["le toe alofa", "the again love"], ["ia te", "unto"], ["i latou;", "them"], ["o latou alii uma,", "they Lord all"], ["o", "o"], ["e fouvale", "to to rebel"], ["i latou.", "them"]]},
  {num:16,words:[["Ua taia Efaraima,", "struck Ephraim"], ["ua mago lo latou", "a small eel their"], ["pogai;", "cause"], ["latou te", "they will"], ["le fua mai ni fua;", "the fruit from some fruit"], ["afai foi", "if also"], ["latou te fananau,", "they will fananau"], ["ou te fasiotia la latou fanau pele.", "I will slain their born dear"]]},
  {num:17,words:[["E lafoaiina", "to forsaken"], ["i latou", "them"], ["e lo'u Atua,", "to my God"], ["auā", "for"], ["ua latou", "they"], ["le faalogo ia te ia;", "the hearken to him"], ["e taase", "to sojourn"], ["i latou", "them"], ["i nuu ese.", "in nation away"]]},
];
renderVerseSet(_hos_ch_9_Verses, 'hos-ch9-verses');

var _hos_ch_10_Verses = [
  {num:1,words:[["O Isaraelu,", "Israel"], ["o le vine", "the vine"], ["ia", "to"], ["e māfalā;", "by māfalā"], ["ua ia fua mai", "to fruit from"], ["ni fua", "some fruit"], ["e fai mona;", "to make to burst forth (as faiai"], ["faapei", "like"], ["ona tele", "and great"], ["o lona fua,", "his fruit"], ["ua faapea ona", "saying and"], ["faateleina e ia", "multiplied by him"], ["o fata faitaulaga;", "altar"], ["faapei", "like"], ["ona lelei", "and good"], ["o lona laueleele,", "his ground"], ["ua faapea ona", "saying and"], ["latou gaosi lelei", "they gaosi good"], ["o tupua.", "pillar"]]},
  {num:2,words:[["Ua faalotoloto lua", "faalotoloto two"], ["i latou;", "them"], ["ua nofo sala nei", "dwelt a fine this"], ["i latou;", "them"], ["na te lepetia", "he overthrown"], ["a latou fata faitaulaga,", "but they altar"], ["na te faaumatia", "he destroyed"], ["a latou tupua.", "but they pillar"]]},
  {num:3,words:[["Auā", "for"], ["e faapea mai nei", "saying from this"], ["i latou,", "them"], ["Ua leai se", "there was no"], ["tupu ia te", "king unto"], ["i matou,", "in we (excl)"], ["auā", "for"], ["ua matou", "we (excl)"], ["le matatau ia", "the fear to"], ["Ieova;", "the LORD"], ["se a foi", "a but also"], ["se mea", "a thing"], ["e faia", "to made"], ["e le tupu", "shall not king"], ["ia", "to"], ["i matou?", "in we (excl)"]]},
  {num:4,words:[["Ua latou fai mai", "they said"], ["upu,", "word"], ["ua tauto pepelo,", "to take an oath false"], ["ua osi", "osi"], ["le feagaiga;", "the covenant"], ["e tupu ae foi", "to king up also"], ["le faamasinoga,", "the judgment"], ["e pei o laau oona", "like tree drunk"], ["i utu o fanua.", "in todraw water of land"]]},
  {num:5,words:[["E fefefe", "to afraid"], ["e ua nonofo", "by dwelling"], ["i Samaria", "in Samaria"], ["ona o tamai povi", "because of son cattle"], ["o Petavene;", "Beth-aven"], ["auā", "for"], ["e fetagisi ai", "to wept"], ["ona tagata,", "and man"], ["o", "o"], ["ona ositaulaga foi", "and high priest also"], ["e", "by"], ["na fiafia", "competition"], ["i ai;", "therein"], ["auā", "for"], ["o lona mamalu", "his glory"], ["ua te'a", "departed"], ["ma ia.", "and to"]]},
  {num:6,words:[["E avea foi", "to become also"], ["lenei mea", "this thing"], ["i Asuria", "in Assyria"], ["e fai ma mea alofa", "to be thing love"], ["i le tupu", "in the king"], ["o Iarepa;", "Iarepa"], ["e mā Efaraima,", "to First person dual exclusive Ephraim"], ["e masiasi foi", "to to be ashamied also"], ["Isaraelu", "Israel"], ["ona", "and"], ["o lana lava pule.", "his indeed rule"]]},
  {num:7,words:[["O Samaria", "Samaria"], ["ua fano", "perished"], ["lona tupu,", "his king"], ["e pei o si fasi laau", "like si kill tree"], ["i le fogāvai.", "in the fogāvai"]]},
  {num:8,words:[["E faaumatia foi", "to destroyed also"], ["mea maualuga", "thing Iiigli"], ["i Avene,", "in Avene"], ["o le agasala", "the sin"], ["a Isaraelu;", "of Israel"], ["e tutupu ae", "to bring forth up"], ["le laau tuitui", "the tree prickly"], ["ma le laau talatala", "and the tree to untie"], ["i o latou", "in of they"], ["fata faitaulaga;", "altar"], ["latou te fai atu foi", "they will said to also"], ["i mauga,", "in mountain"], ["Ina tanu mai ia ia te", "so that to bury from to him"], ["i matou.", "in we (excl)"], ["E faapea foi", "saying also"], ["i mea maupuepue,", "in thing maupuepue"], ["Ina mafuli mai ia", "so that mafuli from to"], ["i luga ia te", "in above unto"], ["i matou.", "in we (excl)"]]},
  {num:9,words:[["Isaraelu e,", "Israel by"], ["talu mai", "since from"], ["ona po o Kipea", "and night of Gibeah"], ["ua e agasala ai;", "you sinned"], ["ua latou tutumau ai;", "they tutumau"], ["na", "na"], ["le oo atu", "the arrived"], ["ia te", "unto"], ["i latou", "them"], ["i Kipea", "in Gibeah"], ["le taua", "the precious"], ["i tagata agaleaga.", "in man unkind"]]},
  {num:10,words:[["O lo'u loto,", "my heart"], ["ou te aoai", "I will chastise"], ["ia te", "unto"], ["i latou;", "them"], ["e faapotopotoina foi", "to gathered together also"], ["tagata", "man"], ["e tau", "to season"], ["ma", "and"], ["i latou,", "them"], ["pe a ou fusifusi", "even though I to bind hund and foot"], ["ia te", "unto"], ["i latou", "them"], ["ona o", "because of"], ["a latou agasala", "but they sin"], ["e lua.", "by two"]]},
  {num:11,words:[["O Efaraima foi", "Ephraim also"], ["o le povi fafine", "the cattle woman"], ["ia", "to"], ["ua a'oa'oina,", "taught"], ["ua fia soli", "wanted to do something to tread upon"], ["saito lava;", "wheat indeed"], ["a", "but"], ["ua ou alu atu lava a'u", "I went away indeed me"], ["i lona", "in his"], ["ua lalelei;", "beautiful"], ["ou te faatietie", "I will make ride"], ["se tasi ia", "a one to"], ["Efaraima,", "Ephraim"], ["e suatia", "by suatia"], ["le eleele", "the earth"], ["e Iuta", "to Judas"], ["e faamăluluina", "by faamăluluina"], ["e Iakopo", "to Jacob"], ["lona laueleele.", "his ground"]]},
  {num:12,words:[["Ia outou lulu saito", "to you (all) barn owl wheat"], ["mo outou", "for you"], ["ma le amiotonu,", "and the righteous"], ["ia outou selesele", "to you (all) an evenly cut head of"], ["mai", "from"], ["ma le amio lelei;", "and the conduct good"], ["ia outou suatia lo outou fanua vaoa;", "to you (all) suatia your land overgrown with weeds"], ["auā", "for"], ["ua oo", "it came to pass"], ["i ona po", "in then night"], ["e saili atu ai", "to seek"], ["ia Ieova,", "to the LORD"], ["seia afio mai", "until dwell (respectful) from"], ["o ia,", "he"], ["ma faatotō ifo", "and faatotō down"], ["le amiotonu", "the righteous"], ["i luga ia te outou.", "in above unto you"]]},
  {num:13,words:[["Ua outou suatia", "you (all) suatia"], ["le agasala,", "sin"], ["ua outou selesele mai le", "you (all) an evenly cut head of from the"], ["leaga;", "evil"], ["ua outou aai", "you (all) city"], ["le fua", "the fruit"], ["o le pepelo;", "the false"], ["auā", "for"], ["na e faatuatua", "you faith"], ["i lou ala,", "in your way"], ["ma le toatele", "and the many"], ["o ou tagata totoa.", "I man p'ural o( fnt"]]},
  {num:14,words:[["O lea", "therefore"], ["e tupu ai", "to king"], ["le vāvāō", "the vāvāō"], ["i ou tagata,", "in I man"], ["e faaumatia ou 'olo uma lava,", "to destroyed I fortress all indeed"], ["e pei ona", "as"], ["faaumatia", "destroyed"], ["e Salemana o Petarepelu", "by Salemana of Petarepelu"], ["i le aso", "in the day"], ["na tau ai", "season"], ["le taua;", "the precious"], ["na palasi", "to have children in"], ["le tinā faatasi ma ana tama.", "the mother together and his child"]]},
  {num:15,words:[["E faapea lava", "saying indeed"], ["ona faia ia te outou", "and made unto you"], ["i Peteli", "in Bethel"], ["ona", "and"], ["o la outou amio", "your conduct"], ["e matuā leaga;", "to exceedingly evil"], ["e matuā fano", "to exceedingly perish"], ["lava", "indeed"], ["le tupu o Isaraelu", "the king of Israel"], ["i le taeao.", "in the morning"]]},
];
renderVerseSet(_hos_ch_10_Verses, 'hos-ch10-verses');

var _hos_ch_11_Verses = [
  {num:1,words:[["O", "O"], ["ona po", "and night"], ["na tama itiiti ai", "child small"], ["Isaraelu,", "Israel"], ["na ou alofa atu ia te ia,", "I loved to him"], ["na ou valaauina foi", "I called also"], ["lo'u atalii", "my son"], ["nai Aikupito.", "from Egypt"]]},
  {num:2,words:[["Na latou alalaga ia te", "they cried out unto"], ["i latou,", "them"], ["a", "but"], ["ua latou", "they"], ["o ese ia te", "away unto"], ["i latou;", "them"], ["na latou fai", "they made"], ["taulaga ia Paala,", "offering to a small fly-fishhook"], ["ma faamu mea manogi", "and burn incense thing fragrant"], ["i tupua", "in pillar"], ["ua ta.", "a stroke"]]},
  {num:3,words:[["Na ou a'oa'oina", "I taught"], ["Efaraima ia savali,", "Ephraim to walk"], ["o loo o tauta'ita'i", "is (progressive) tauta'ita'i"], ["ia te", "unto"], ["i latou", "them"], ["i o latou", "in of they"], ["lima;", "five"], ["a", "but"], ["ua", "ua"], ["le iloa e", "the know by"], ["i latou", "them"], ["ona ou faamaloloina", "and I healed"], ["o", "o"], ["i latou.", "them"]]},
  {num:4,words:[["Na ou tosina", "I to be"], ["i latou", "them"], ["i maea", "in rope"], ["a le tagata,", "but the man"], ["o maea alofa", "rope love"], ["lava;", "indeed"], ["na ou", "I"], ["i ai", "therein"], ["ia te", "unto"], ["i latou", "them"], ["e pei o", "like"], ["e sii ae", "to lift up up"], ["le amo ai", "the carry"], ["o latou aulamu,", "they aulamu"], ["na au tuuina atu foi", "me given / delivered also"], ["mea", "thing"], ["e 'ai ia te", "to eat unto"], ["i latou.", "them"]]},
  {num:5,words:[["E le toe foi", "shall not again also"], ["o ia", "he"], ["i le nuu", "in the land"], ["o Aikupito,", "Egypt"], ["a", "but"], ["e avea", "to become"], ["le Asuria mona tupu;", "the Assyria to burst forth (as faiai king"], ["auā", "for"], ["ua", "ua"], ["le mafafai", "the able"], ["i latou", "them"], ["ona toe foi atu.", "and went back"]]},
  {num:6,words:[["E tumau", "to be firm"], ["le pelu", "the sword"], ["i ona aai,", "in then city"], ["e faaumatia ai", "to destroyed"], ["foi", "also"], ["ona la,", "and la"], ["ma fano ai,", "and perish"], ["auā o", "for of"], ["a latou lava filifiliga.", "but they indeed filifiliga"]]},
  {num:7,words:[["Ua naunau", "desired"], ["lo'u nuu", "my nation"], ["e liliu ese", "to turned away"], ["ia te au;", "unto me"], ["latou te valaau", "they will call"], ["i ai", "therein"], ["e o mai", "by of from"], ["i lē Silisili ese,", "in not very much away"], ["a", "but"], ["e leai se tasi", "there is no one"], ["e vivii atu", "to praised"], ["ia te ia", "to him"], [".", "."]]},
  {num:8,words:[["Efaraima e,", "Ephraim by"], ["ou te mafai faapefea ona tuu atu", "I will able how then placed"], ["ia te oe?", "unto you"], ["Isaraelu e,", "Israel by"], ["ou te tuuina atu oe", "I will give you"], ["faapefea? ou te mafai faapefea ona tuuina atu", "how I will able how then given / delivered"], ["o oe", "you"], ["e pei o Atama? ou te tuuina atu oe", "like Atama I will give you"], ["faapefea", "how"], ["e pei o Sepoima?", "like Sepoima"], ["Ua liua", "turned into"], ["lo'u loto", "my heart"], ["i totonu ia te au;", "in inside unto me"], ["atoa foi", "together with also"], ["ma lo'u alofa mutimutivale", "and my mercy"], ["ua tupu.", "king"]]},
  {num:9,words:[["Ou te", "I will"], ["le faaoo", "the bring upon"], ["lo'u ita tele;", "my angry great"], ["ou te", "I will"], ["le toe faaumatia Efaraima;", "the again destroyed Ephraim"], ["auā", "for"], ["o a'u", "I am"], ["o le Atua,", "of God"], ["a", "but"], ["e le", "by the"], ["se tagata,", "a man"], ["o le Paia", "the holy"], ["o loo", "is/are (progressive)"], ["i totonu ia te oe;", "in inside unto you"], ["ou te", "I will"], ["le alu atu", "the go away"], ["ma le ita.", "and the angry"]]},
  {num:10,words:[["Latou te mulimuli atu", "they will follow after"], ["ia Ieova,", "to the LORD"], ["e tagi lava", "to cry indeed"], ["ia", "to"], ["e pei o se leona;", "like a lion"], ["a tagi o ia,", "but cry he"], ["ona taalise mai ai lea", "and to be quick from then then"], ["o le fanau mai sisifo.", "the born west"]]},
  {num:11,words:[["Latou te taalise", "they will to be quick"], ["mai", "from"], ["e pei o se manu lele", "like a animal fly"], ["mai Aikupito,", "from Egypt"], ["e pei o se lupe foi mai le nuu", "like a dove return the nation"], ["o Asuria;", "Assyria"], ["ou te faanonofo foi", "I will make dwelling also"], ["ia te", "unto"], ["i latou", "them"], ["i o latou", "in of they"], ["fale,", "house"], ["ua faapea mai ai", "and said"], ["Ieova.", "the LORD"]]},
  {num:12,words:[["Ua siosio Efaraima ia te au", "siosio Ephraim unto me"], ["i le pepelo,", "in the false"], ["o le aiga foi", "the family also"], ["o Isaraelu", "Israel"], ["ua siosio ia te au", "siosio unto me"], ["i le 'ole'ole;", "in the 'ole'ole"], ["a", "but"], ["ua pule pea", "ruled continually"], ["Iuta faatasi ma le Atua,", "Judas together and the God"], ["ua faamaoni ia", "faithful to"], ["faatasi ma le au paia.", "together and the saints"]]},
];
renderVerseSet(_hos_ch_11_Verses, 'hos-ch11-verses');

var _hos_ch_12_Verses = [
  {num:1,words:[["O loo 'ai Efaraima", "is (progressive) eat Ephraim"], ["le matagi,", "the wind"], ["ua naunau atu", "desired"], ["o ia", "he"], ["i le matagi", "in the wind"], ["mai sasae;", "from east"], ["ua faateleina e", "multiplied you"], ["ia le pepelo", "to the false"], ["ma le malaia", "and the disaster"], ["i aso uma lava;", "all the days indeed"], ["ua osia foi", "hewn also"], ["la latou feagaiga", "their covenant"], ["ma Asuria,", "and Assyria"], ["ma", "and"], ["ua avatu", "gave away"], ["i Aikupito suāuu.", "in Egypt suāuu"]]},
  {num:2,words:[["Ua ia Ieova", "to the LORD"], ["le finauga", "the disputation"], ["ma Iuta,", "and Judas"], ["na te faasalaina", "he punished"], ["Iakopo", "Jacob"], ["e tusa ma ana amio;", "according to his conduct"], ["na te taui atu ia te ia", "he a reward to him"], ["e tusa ma ana galuega.", "according to his work"]]},
  {num:3,words:[["Na ia tago", "to reached"], ["i le mulivae", "in the the heel"], ["o lona uso", "his brother"], ["a o", "but of"], ["i ai", "therein"], ["i le manava;", "in the womb"], ["o lona malosi", "his strong"], ["na ia malo ai", "to government"], ["i le Atua.", "in the God"]]},
  {num:4,words:[["Na ia malo", "to government"], ["i le agelu,", "in the angel"], ["na manumalo ai", "overcame"], ["lava;", "indeed"], ["na ia tagi,", "to cried"], ["ma aioi atu", "and cry out"], ["ia te ia;", "to him"], ["na ia iloa ia te ia", "to knew to him"], ["i Peteli,", "in Bethel"], ["na tŭlei mai ai", "tŭlei from"], ["foi", "also"], ["lona siufofoga ia te", "his voice unto"], ["i tatou.", "in we (incl)"]]},
  {num:5,words:[["O Ieova lava", "the LORD indeed"], ["o le Atua", "of God"], ["o 'au;", "me"], ["o Ieova", "the LORD"], ["o lona suafa lea", "his name"], ["e manatua ai", "to remember"], ["o ia.", "he"]]},
  {num:6,words:[["O lenei,", "now"], ["ia", "to"], ["e toe foi", "to again also"], ["i lou Atua;", "in your God"], ["ia", "to"], ["e tausi", "to nurse"], ["le alofa", "the love"], ["ma le faamasinoga,", "and the judgment"], ["aua", "for"], ["le aunoa", "the without"], ["ona", "and"], ["e faatalitali atu", "to waited"], ["i lou Atua.", "in your God"]]},
  {num:7,words:[["O le faatauoa", "the faatauoa"], ["ia ,", "to"], ["o", "o"], ["i lona lima", "in his five"], ["o fua faatautau faaletatau;", "fruit make to hang up faaletatau"], ["e fiafia o ia", "to competition he"], ["i le faasaua.", "in the cruel"]]},
  {num:8,words:[["Ua faapea mai foi", "and said also"], ["a Efaraima,", "of Ephraim"], ["E moni,", "verily/truly"], ["o a'u", "I am"], ["o le mau mea,", "the opinion thing"], ["ua ou maua", "I received"], ["oloa", "goods"], ["mo a'u;", "for me"], ["latou te", "they will"], ["le iloa", "the know"], ["se leaga ia te au,", "a evil unto me"], ["se mea", "a thing"], ["o se agasala", "a sin"], ["i a'u galuega uma.", "in me work all"]]},
  {num:9,words:[["O a'u foi", "I am also"], ["o Ieova", "the LORD"], ["lou Atua talu", "your God since"], ["mai le nuu", "from the nation"], ["o Aikupito,", "Egypt"], ["ou te toe faanofo", "I will again a secondary wife intro-"], ["ia te oe", "unto you"], ["i fale ie faapei", "in house faamaise like"], ["o", "o"], ["ona po", "and night"], ["o le tausamiga.", "the feast"]]},
  {num:10,words:[["Na ou tautala atu", "I spoke toward"], ["i perofeta,", "in prophet"], ["na ou faateleina", "I multiplied"], ["faaaliga;", "revelation"], ["o le au", "the me"], ["perofeta foi", "prophet also"], ["na ou sauni atu ai", "I he who beg^ins the game"], ["upu faataoto.", "word lay down"]]},
  {num:11,words:[["Ua leaga lava", "evil indeed"], ["Kiliata,", "Gilead"], ["e pepelo lava", "to false indeed"], ["i latou;", "them"], ["latou te fai taulaga", "they will make offering"], ["i povi poa", "in cattle captive"], ["i Kilikala;", "in Gilgal"], ["o latou fata faitaulaga foi,", "they altar also"], ["e pei o faupuegāmaa", "like faupuegāmaa"], ["ia", "to"], ["i atu pue", "in capture"], ["o le laueleele.", "the ground"]]},
  {num:12,words:[["Na sola Iakopo", "escaped Jacob"], ["i le nuu", "in the land"], ["o Suria;", "Syria"], ["na auauna Isaraelu", "servant Israel"], ["e maua ai", "to received"], ["lana avā;", "his wife"], ["na ia leoleo mamoe", "to shepherd"], ["e maua ai", "to received"], ["lana avā.", "his wife"]]},
  {num:13,words:[["O le perofeta", "the prophet"], ["na aveina ae ai", "taken away up"], ["Isaraelu", "Israel"], ["e Ieova mai Aikupito;", "the LORD from Egypt"], ["o le perofeta foi", "the prophet also"], ["na leoleoina ai", "guarded"], ["o ia.", "he"]]},
  {num:14,words:[["Na matuā faaonoono", "exceedingly vex"], ["Efaraima ia te ia", "Ephraim to him"], [",", ","], ["o le mea lea", "therefore"], ["na te tuu ai", "he put"], ["pea", "continually"], ["lona toto ia te ia;", "his blood to him"], ["o lona luma foi", "his before also"], ["e faafoisia ia te ia", "to restored to him"], ["e lona Alii.", "by his Lord"]]},
];
renderVerseSet(_hos_ch_12_Verses, 'hos-ch12-verses');

var _hos_ch_13_Verses = [
  {num:1,words:[["Na tautala Efaraima", "spoke Ephraim"], ["ona tupu ai lea", "and king then then"], ["o le tetemu,", "the to tremble"], ["sa mamalu o ia", "glory he"], ["i Isaraelu;", "in Israel"], ["a", "but"], ["ua oo ina", "it came to pass so that"], ["agasala o ia", "sin he"], ["i Paala,", "in a small fly-fishhook"], ["ona oti ai lea.", "and he died"]]},
  {num:2,words:[["A o nei", "but of this"], ["ona po", "and night"], ["ua latou saga", "they saga"], ["agasala pea,", "sin continually"], ["ua latou faia", "they did"], ["mo", "for"], ["i latou", "them"], ["o tupua uamea,", "pillar iron"], ["o tupua", "pillar"], ["ua faia", "made"], ["i o latou", "in of they"], ["ario,", "silver"], ["e tusa ma lo latou manatu;", "according to their thought"], ["o le galuega", "the work"], ["a tufuga", "but master builder"], ["na mea uma;", "all things"], ["ua faapea la", "saying la"], ["latou upu", "they word"], ["i ai,", "therein"], ["Ia feasogi", "to to salute by rubbJDg"], ["ma tamai povi tagata", "and son cattle man"], ["o", "o"], ["e fai taulaga.", "to make offering"]]},
  {num:3,words:[["O le mea lea", "therefore"], ["e avea ai", "to become"], ["i latou", "them"], ["e pei o le puao", "like the puao"], ["i le taeao,", "in the morning"], ["e pei o le sau foi", "like the come also"], ["i le vave ao", "in the quick day"], ["ona mavae atu;", "and passed"], ["e pei o le aputi", "like the aputi"], ["ua lelea", "to be carried away by the"], ["i le matagi", "in the wind"], ["i le mea", "in the thing"], ["e sasa ai", "to a scourge"], ["saito,", "wheat"], ["e pei o le asu foi", "like the asu also"], ["ai", "ai"], ["le alaasu.", "the alaasu"]]},
  {num:4,words:[["A", "but"], ["o a'u", "I am"], ["o Ieova,", "the LORD"], ["o lou Atua talu", "your God since"], ["mai le nuu", "from the nation"], ["o Aikupito,", "Egypt"], ["e te", "by"], ["le iloa", "the know"], ["se tasi Atua", "a one God"], ["na", "na"], ["o a'u;", "I am"], ["e leai foi", "there is not also"], ["se isi faaola,", "a other save"], ["na", "na"], ["o a'u.", "I am"]]},
  {num:5,words:[["Na ou iloa oe", "I knew you"], ["i le vao,", "in the wilderness"], ["o le nuu naumati.", "the nation dry"]]},
  {num:6,words:[["E pei ona", "as"], ["fagaina o", "a bay of"], ["i latou,", "them"], ["sa faapea ona", "saying and"], ["maoona o", "maoona of"], ["i latou;", "them"], ["sa maoona", "maoona"], ["i latou,", "them"], ["ona faamaualulugaina lea", "and make most high"], ["o latou loto;", "they heart"], ["o le mea lea", "therefore"], ["na latou faagalogalo ai", "they to forget"], ["ia te au.", "unto me"]]},
  {num:7,words:[["O lea", "therefore"], ["ua avea ai", "became"], ["a'u ia te", "me unto"], ["i latou", "them"], ["e pei o se leona;", "like a lion"], ["ou te lamalama", "I will lamalama"], ["e pei o se nameri", "like a nameri"], ["i le auala.", "in the auala"]]},
  {num:8,words:[["Ou te oso atu", "I will food for a journey"], ["ia te", "unto"], ["i latou", "them"], ["e pei o se urosa", "like a urosa"], ["ua avea ana", "became his"], ["tama ,", "child"], ["ou te saeia mea", "I will spared thing"], ["e ufitai o latou", "by ufitai of they"], ["fatu;", "seed"], ["ou te 'aina", "I will edible"], ["i latou", "them"], ["i lea", "in"], ["mea", "thing"], ["e pei o se leona;", "like a lion"], ["e saeia", "to spared"], ["i latou", "them"], ["e le manu feai.", "shall not animal wild"]]},
  {num:9,words:[["Isaraelu e,", "Israel by"], ["ua malaia oe", "disaster you"], ["ia te oe;", "unto you"], ["a", "but"], ["ua ia te au", "unto me"], ["lou fesoasoani.", "your to help"]]},
  {num:10,words:[["O ifea o", "where? of"], ["i ai", "therein"], ["nei", "this"], ["lou tupu", "your king"], ["le", "the"], ["na te faaolaina oe", "he saved alive you"], ["i o outou", "in of you (all)"], ["aai uma? o ifea ou faamasino foi", "city all of where? I judge also"], ["na e fai mai ai,", "you said"], ["Au mai ia te au", "bring unto me"], ["se tupu", "a king"], ["atoa ma ni alii?", "and some Lord"]]},
  {num:11,words:[["Na ou avatu ia te oe", "I gave away unto you"], ["le tupu", "the king"], ["i lo'u tiga;", "in my grieved"], ["na ou aveeseina foi", "I carried away also"], ["o ia", "he"], ["i lo'u ita.", "in my angry"]]},
  {num:12,words:[["Ua fusifusi faatasi", "to bind hund and foot together"], ["le leaga o Efaraima;", "the evil of Ephraim"], ["ua teua", "teua"], ["lana agasala.", "his sin"]]},
  {num:13,words:[["E oo ia te ia", "it shall come to pass to him"], ["le faatiga", "the afflict"], ["o le fafine", "the woman"], ["o le a fanau mai;", "what born"], ["o ia", "he"], ["o le tama faalemafaufau,", "the child faalemafaufau"], ["aua", "for"], ["e le tatau ona", "shall not to wring out then"], ["tuai mai o ia", "to be a long time from he"], ["nai", "from"], ["le mea", "the thing"], ["e o ifo ai", "by of down"], ["tama.", "child"]]},
  {num:14,words:[["Ou te laveai", "I will deliver"], ["ia te", "unto"], ["i latou ai", "them"], ["le malosi", "the strong"], ["o le tuugamau;", "the grave"], ["ou te faaola", "I will save"], ["ia te", "unto"], ["i latou ai", "them"], ["le oti.", "the die"], ["Le oti e,", "the die by"], ["o fea o", "where?/which? of"], ["i ai", "therein"], ["le malaia mai ia te oe?", "the disaster from you"], ["Le tuugamau e,", "the grave by"], ["o fea o", "where?/which? of"], ["i ai", "therein"], ["se mea", "a thing"], ["e fano ai", "to perish"], ["mai ia te oe?", "from you"], ["e lilo ia te au", "to secret unto me"], ["le salamo.", "the repent"]]},
  {num:15,words:[["E ui", "to although"], ["ina faauluolaina o ia", "so that make multiply he"], ["i luma", "in before"], ["o", "o"], ["ona uso,", "and brother"], ["e agi mai le matagi", "by agi from the wind"], ["mai sasae,", "from east"], ["o le matagi", "the wind"], ["o Ieova", "the LORD"], ["e oso atu", "to food for a journey"], ["ia ai", "to"], ["le vao,", "the vegetation"], ["e", "by"], ["pe", "whether"], ["lona vaieli,", "his well"], ["e mate foi", "by mate also"], ["lona punavai;", "his punavai"], ["na te faaumatia", "he destroyed"], ["le oa o mea uma", "the a couple everything"], ["e manaomia.", "to desired"]]},
  {num:16,words:[["E faasalaina Samaria,", "to punished Samaria"], ["auā", "for"], ["ua ia fouvale", "to to rebel"], ["i lona Atua;", "in his God"], ["o le pelu latou te pauu ai;", "the sword they will fell"], ["e palasi", "to to have children in"], ["a latou tama meamea,", "but they child young"], ["e faatiauina o latou", "to to disembowel of they"], ["fafine", "woman"], ["ua totō.", "totō"]]},
];
renderVerseSet(_hos_ch_13_Verses, 'hos-ch13-verses');

var _hos_ch_14_Verses = [
  {num:1,words:[["Isaraelu", "Israel"], ["e", "by"], ["ina toe foi mai ia ia", "so that returned to him"], ["Ieova", "the LORD"], ["lou Atua;", "your God"], ["auā", "for"], ["o lau agasala", "your sin"], ["ua e paū ai.", "you paū"]]},
  {num:2,words:[["Ina sauni atu", "so that he who beg^ins the game"], ["ia ni", "to some"], ["a outou upu", "but you (all) word"], ["ma toe foi atu", "and went back"], ["ia Ieova.", "to the LORD"], ["Ia outou faapea atu", "to you (all) thus"], ["ia te ia,", "to him"], ["Ia", "to"], ["e ave ese agasala uma,", "to take away sin all"], ["ma talileleia mai,", "and talileleia from"], ["matou te avatua", "we (excl) given away"], ["lava taulaga o matou", "indeed offering of we (excl)"], ["laugutu.", "lips"]]},
  {num:3,words:[["E le faaolaina", "shall not saved alive"], ["i matou", "in we (excl)"], ["e Asuria;", "to Assyria"], ["matou te", "we (excl)"], ["le tietie", "the ride"], ["i solofanua;", "in horse"], ["matou te", "we (excl)"], ["le toe faapea ane", "the again thus"], ["lava", "indeed"], ["i galuega", "in work"], ["a o matou", "but of we (excl)"], ["lima,", "five"], ["O matou atua", "we (excl) God"], ["ia;", "to"], ["auā", "for"], ["e alofagia e", "to favored by"], ["oe", "you"], ["le mātuaoti.", "the mātuaoti"]]},
  {num:4,words:[["Ou te faamaloloina lo latou liliu ese;", "I will healed their turned away"], ["ou te alofa fua", "I will love fruit"], ["ia te", "unto"], ["i latou;", "them"], ["auā", "for"], ["ua liliueseina", "liliueseina"], ["lo'u ita ia te", "my angry unto"], ["i latou.", "them"]]},
  {num:5,words:[["E avea a'u", "to become me"], ["ma sau ia", "and come to"], ["Isaraelu;", "Israel"], ["e fuga mai", "to flower from"], ["o ia", "he"], ["e pei o le susana,", "like the susana"], ["e sosolo", "to to run"], ["ona aa", "and aa"], ["e pei o Lepanona.", "like Lebanon"]]},
  {num:6,words:[["E tutupu ae", "to bring forth up"], ["ona tātupu,", "and tātupu"], ["e pei o le olive", "like the olive"], ["lona matagofie;", "his beautiful"], ["e manogi foi", "to fragrant also"], ["ia", "to"], ["e pei o Lepanona.", "like Lebanon"]]},
  {num:7,words:[["O", "O"], ["i latou", "them"], ["o", "o"], ["e nonofo", "to dwell"], ["i lalo ifo", "in under down"], ["o lona paolo,", "his paolo"], ["e toe ola", "to again life"], ["mai", "from"], ["i latou", "them"], ["e pei o saito,", "like wheat"], ["e fua mai", "yielding fruit"], ["e pei o le vine;", "like the vine"], ["e ta'ua", "by us (two, incl)"], ["o ia", "he"], ["e pei o le uaina", "like the wine"], ["o Lepanona.", "Lebanon"], ["E faapea mai", "saying from"], ["a Efaraima,", "of Ephraim"]]},
  {num:8,words:[["Se a ea sa'u toe mea", "what indeed? / why? come again thing"], ["e fai", "to make"], ["i tupua?", "in pillar"], ["Ua ou tali atu,", "I responded"], ["ma vaavaai atu", "and watch"], ["ia te ia;", "to him"], ["e pei o se perosi lauolaola a'u", "like a perosi green me"], ["nei;", "this"], ["e maua", "to received"], ["lau fua mai ia te au.", "your fruit from me"]]},
  {num:9,words:[["Po o ai", "who?"], ["se tasi", "a one"], ["ua poto?", "wise"], ["e iloa lava", "to know indeed"], ["e ia", "by him"], ["na mea;", "thing"], ["po o ai", "who?"], ["lē faautauta?", "not careful"], ["e iloa ai", "to know"], ["e ia;", "by him"], ["auā", "for"], ["ua tonu ala", "right way"], ["o Ieova,", "the LORD"], ["e savavali ai", "to walked"], ["e ua amiotonu;", "by righteous"], ["a o", "but of"], ["e fouvale,", "to to rebel"], ["e tautevateva ai", "by tautevateva"], ["i latou.", "them"]]},
];
renderVerseSet(_hos_ch_14_Verses, 'hos-ch14-verses');

})();