(function() {
var jr_ch_1_Verses = [
  {num:1,words:[["O Lenei faauta,", "this behold"], ["o a'u o Iaroma,", "I am iaroma"], ["ou te tusia ni nai upu itiiti e tusa ma le poloaiga a lo'u tamā,", "I written some from word small to according to and the commandment but my father"], ["o Enosa,", "Enos"], ["ina ia mafai ona tausia lo matou gafa .", "that it might be and kept our genealogy"]]},
  {num:2,words:[["Ma ona ua laiti nei papatusi,", "and then laiti this plates"], ["ma ona o nei mea ua tusia mo le faamoemoe mo le manuia o o matou uso o sa Lamanā ,", "and then this thing written for the to expect for the peace we a relative of the same generation and gender Lamanite"], ["o le mea lea e tatau ai ona ou tusia nao ni nai mea itiiti;", "therefore it is fitting then I written nao some from thing small"], ["peitai o le a ou lē tusia mea e uiga i a'u valoaga,", "however the but I not written thing to kind in I a prediction"], ["po o a'u faaaliga.", "night I am revelation"], ["Ona o se a se isi mea e sili atu e mafai ona ou tusia nai lo mea ua tusia e o'u tamā? Aua pe latou te lei faaali mai ea le fuafuaga o le faaolataga? Ou te fai atu ia te outou,", "because of a but a other thing to most to able then I written from lo thing written to I father for or them whale's teeth reveal from to rise (as a diver to the sur- the fuafuaga the faaolataga I make unto ye all"], ["Ioe;", "yea"], ["ma ua lava lea ia te a'u.", "and indeed unto I"]]},
  {num:3,words:[["Faauta,", "behold"], ["e tele mea e tatau ona faia i totonu o lenei nuu,", "to great thing to to wring out then made in inside this nation"], ["ona o le maaa o o latou loto,", "because of the maaa them heart"], ["ma le tutuli o o latou taliga,", "and the tutuli them ear"], ["ma le tauaso o o latou mafaufau,", "and the a blind man them think"], ["ma le malolo o o latou ūa;", "and the rest them ūa"], ["e ui i lea,", "to although in"], ["o loo alofa mutimutivale tele mai pea le Atua ia te i latou,", "love to be distressed in great from continually the God unto them"], ["ma e lei tafieseina lava i latou mai luga o le laueleele.", "and to whale's teeth tafieseina indeed them from above the ground"]]},
  {num:4,words:[["Ma e toatele o i ai i totonu o i matou o e ua maua faaaliga e tele,", "and to many therein in inside in we by received revelation to great"], ["ona ua latou lē ua maaa uma.", "and them not maaa all"], ["Ma o le toatele o e sa lē ua maaa ma faatuatua,", "and the many by not maaa and faith"], ["sa mafuta ma le Agaga Paia,", "communion and the spirit holy"], ["o lē na te faaali mai mea i le fanauga a tagata,", "not reveal from thing in the children but man"], ["e tusa ma lo latou faatuatua.", "to according to and the them faith"]]},
  {num:5,words:[["Ma o lenei,", "and now"], ["faauta,", "behold"], ["ua lua selau tausaga ua mavae atu,", "two hundred year a parting"], ["ma ua faasolo malolosi le nuu o Nifae i le laueleele.", "and faasolo mighty the nation Nephi in the ground"], ["Sa latou tausisi e tausi le tulafono a Mose ma le aso Sapati ua paia i le Alii.", "them tausisi to keep the law but Moses and the day sapati holy in the Lord"], ["Ma sa latou lē upuvale;", "and them not upuvale"], ["pe sa latou faifai .", "or them to become"], ["Ma sa matua sa'olele lava tulafono o le laueleele.", "and very sa'olele indeed law the ground"]]},
  {num:6,words:[["Ma sa latou salalau i luga o le tele o le laueleele,", "and them to be scattered in above the great the ground"], ["ma sa Lamanā foi.", "and Lamanite also"], ["Ma sa sili atu lo latou toatele nai lo i latou o sa Nifaē;", "and most their many from lo them Nephi"], ["ma sa latou fiafia i le fasioti tagata ma inu le toto o manu.", "and them competition in the killed man and drink the blood animal"]]},
  {num:7,words:[["Ma sa oo ina latou o mai i le tele o taimi e faasaga mai ia te i matou,", "and oo let them from in the great time to toward from unto in we"], ["o sa Nifaē,", "Nephi"], ["e tau.", "to season"], ["Peitai o o matou tupu ma o matou taitai o ni tagata malolosi i le faatuatua i le Alii;", "however we grow and we taitai some man mighty in the faith in the Lord"], ["ma sa latou aoaoina le nuu i ala o le Alii;", "and them taught the nation in arise the Lord"], ["o le mea lea na matou tutetee atu ai ia sa Lamanā ma tafi ese i latou i fafo mai o matou laueleele,", "therefore we tutetee to Lamanite and to brush away them in outside from we ground"], ["ma amata ona matou tu'i'olo faamalolosi o matou aai,", "and began then we tu'i'olo faamalolosi we eat"], ["po o soo se nofoaga lava o lo matou tofi.", "night frequently a place indeed our appoint"]]},
  {num:8,words:[["Ma sa matou matua uluola tele lava,", "and we very multiply great indeed"], ["ma salalau atu i luga o le laueleele,", "and to be scattered in above the ground"], ["ma matua mau'oa tele i le auro,", "and very mau'oa great in the gold"], ["ma le ario,", "and the silver"], ["atoa ma mea taua,", "and thing war"], ["ma mea matagofie e faia i laau,", "and thing beautiful to made in tree"], ["i fale,", "in house"], ["ma i mea faamasini,", "and in thing faamasini"], ["ma i u'amea ma le kopa foi,", "and in u'amea and the kopa also"], ["ma le apamemea ma le sila,", "and the apamemea and the sila"], ["ma fai ai ituaiga o mea faigaluega eseese uma e galueaiina ai le eleele,", "and make ituaiga thing faigaluega divided all by galueaiina the earth"], ["ma auupega o taua—ioe,", "and auupega taua—ioe"], ["o le ufanafana mata ma'ai,", "the ufanafana eye ma'ai"], ["ma le utu,", "and the todraw water"], ["ma le mataotao,", "and the mataotao"], ["ma le tao,", "and the spear"], ["ma sauniuniga uma mo taua.", "and sauniuniga all for war"]]},
  {num:9,words:[["Ma ona sa faapea ona matou saunia e faafetaia'i sa Lamanā,", "and then thus then we prepared by faafetaia'i Lamanite"], ["o lea sa latou lē manumalo ai ia te i matou.", "therefore them not overcome unto in we"], ["Ae sa faamaonia le afioga a le Alii,", "but faamaonia the a word but the Lord"], ["na fetalai mai e ia i o matou tamā,", "said from by him in we father"], ["fai mai,", "said/told"], ["e faapea:", "by thus"], ["O le tulaga e oo i ai la outou tausiga o a'u poloaiga,", "the standing by oo therein your tausiga I am commandment"], ["o le a outou manuia i le laueleele.", "what ye all peace in the ground"]]},
  {num:10,words:[["Ma sa oo ina faamata'u e perofeta a le Alii le nuu o Nifae,", "and oo let faamata'u to prophet but the Lord the nation Nephi"], ["e tusa ma le afioga a le Atua,", "to according to and the a word but the God"], ["e faapea afai latou te lē tausia poloaiga,", "by thus if them not kept commandment"], ["ae pauu atu i le solitulafono,", "but fell in the solitulafono"], ["o le a faaumatia ese i latou mai luga o le laueleele.", "what destroy away them from above the ground"]]},
  {num:11,words:[["O le mea lea,", "therefore/wherefore"], ["sa galulue ai ma le filiga perofeta,", "galulue and the perseverance prophet"], ["ma faitaulaga,", "and priest"], ["ma aoao,", "and excellent"], ["e apoapoai atu i tagata ma le tali-tiga atoa ia filiga;", "by apoapoai in man and the tali-tiga together with to perseverance"], ["ma latou aoao atu le tulafono a Mose,", "and them excellent the law but Moses"], ["ma le faamoemoe na tuuina mai ai;", "and the to expect given from"], ["ma faatauanau atu ia te i latou ia latou tepa taulai i luma i le Mesia,", "and faatauanau unto them to them to look towards taulai in before in the Messiah"], ["ma talitonu o le a afio mai o ia e peiseai ua uma ona afio mai o ia.", "and believe the but dwell (respectful) from he to as if all then dwell (respectful) from he"], ["Ma sa faapea le ala sa latou aoaoina ai i latou.", "and thus the arise them taught them"]]},
  {num:12,words:[["Ma sa oo o le faia faapea sa latou taofi ai i latou mai le faaumatiaina i luga o le laueleele,", "and oo the made thus them hold them from the faaumatiaina in above the ground"], ["ona sa latou tuia o latou loto i le afioga,", "and them tuia them heart in the a word"], ["ma uunai pea i latou ia salamo.", "and uunai continually them to repent"]]},
  {num:13,words:[["Ma sa oo ina mavae atu le lua selau tolu sefulu ma le valu o tausaga—e ala i taua,", "and oo let a parting the two hundred three ten and the eight tausaga—e arise in war"], ["ma finauga,", "and argument"], ["ma fevaevaeaiga,", "and fevaevaeaiga"], ["mo le va tele o le taimi.", "for the space great the time"]]},
  {num:14,words:[["Ma o a'u,", "and I am"], ["o Iaroma,", "iaroma"], ["ou te lē toe tusia ni isi mea,", "I not again written some other thing"], ["ona ua laiti papatusi.", "and laiti plates"], ["Ae faauta,", "but behold"], ["o'u uso e,", "I a relative of the same generation and gender by"], ["e mafai ona outou o atu i isi papatusi a Nifae;", "it is possible and ye all in other plates but Nephi"], ["aua faauta,", "for behold"], ["ua togitogia i luga o i latou talafaamaumau o a matou taua,", "togitogia in above them record but we war"], ["e tusa ma tusitusiga a tupu,", "to according to and scripture but grow"], ["po o tala sa latou faatonuina ia tusia.", "night side them faatonuina to written"]]},
  {num:15,words:[["Ma ou te tuu atu nei papatusi i lima o lo'u atalii,", "and I put this plates in five my son"], ["o Ominae,", "Omni"], ["ina ia tausia i latou e tusa ma poloaiga a o'u tamā.", "so that kept them to according to and commandment but I father"]]},
];
renderVerseSet(jr_ch_1_Verses, 'jr-ch1-verses');

})();