(function() {
var jon_ch_1_Verses = [
  {num:1,words:[["Ua oo mai", "it came to pass from"], ["le afioga", "the a word"], ["a Ieova ia Iona", "of Jehovah to Jonah"], ["le atalii o Amitai,", "the son amitai"], ["ua faapea mai,", "saying"]]},
  {num:2,words:[["Ina tulai ia,", "let arose up to"], ["ina alu", "let go"], ["i Nineva", "in nineva"], ["le aai tele,", "the city great"], ["ma alaga atu", "and a shoulder or leg of aa '"], ["i ai;", "therein"], ["auā ua oo", "for it came to pass"], ["mai a latou agasala", "from but they sin"], ["i o'u luma.", "before me"]]},
  {num:3,words:[["A ua tulai Iona", "but arose up Jonah"], ["e sola", "to flee"], ["i Tasesa ai luma o Ieova,", "in tasesa before Jehovah"], ["ua alu ifo foi o ia", "go also he"], ["i Iopa,", "in Job"], ["ma na maua", "and received"], ["le vaa", "the vaa"], ["a alu", "but go"], ["i Tasesa;", "in tasesa"], ["ona avatu ai lea", "and give away"], ["e ia", "by him"], ["o le totogi,", "the totogi"], ["ma alu ifo", "and go"], ["i ai,", "therein"], ["e o", "by"], ["ma i latou", "and them"], ["i Tasesa ai luma o Ieova.", "in tasesa before Jehovah"]]},
  {num:4,words:[["A ua tuuina ifo", "but given"], ["e Ieova", "to Jehovah"], ["le matagi tetele", "the wind great"], ["i le vasa,", "in the ocean"], ["ona afā tetele ai lea", "and cyclone great"], ["i le vasa,", "in the ocean"], ["se manū", "a manū"], ["a lepetia", "but lepetia"], ["le vaa.", "the vaa"]]},
  {num:5,words:[["Ona matatau ai lea", "and fear"], ["o le auvaa,", "the auvaa"], ["ma latou taitasi", "and they each"], ["ma valaau", "and call"], ["i lona atua;", "in his God"], ["ua latou lafo foi", "they cloth used as gratuity for a talking chief also"], ["le oloa", "the goods"], ["na i le vaa", "in the vaa"], ["i le sami,", "in the sea"], ["e faamāmāina ai.", "by faamāmāina"], ["A e peitai o Iona", "but to however Jonah"], ["na alu ifo o ia", "go he"], ["i totonu lava", "in inside indeed"], ["o le vaa;", "the vaa"], ["na taoto foi o ia,", "taoto also he"], ["ma moegase.", "and moegase"]]},
  {num:6,words:[["Ona alu atu lea", "and go away"], ["o le aliivaa ia te ia,", "the aliivaa unto him"], ["ma fai atu ia te ia,", "and said to unto him"], ["A faapefea ea oe,", "but how ? to rise (as a diver to the sur- you"], ["lē moe gase?", "not sleep gase"], ["ina tulai ia,", "let arose up to"], ["ina valaau", "let call"], ["i lou Atua,", "in your God"], ["atonu e manatu", "impers to thought"], ["mai le Atua ia te", "from God unto"], ["i tatou,", "in we (incl)"], ["ina ia le oti", "so that the die"], ["i tatou.", "in we (incl)"]]},
  {num:7,words:[["Ona latou fetautalatalai lea,", "and they fetautalatalai"], ["Ina o mai ia,", "let from to"], ["se'i tatou faia", "a flower put into the hair or let us make"], ["le vili,", "the a gimblet"], ["ina ia tatou iloa po", "so that we (incl) known night"], ["o ai", "o ai"], ["ua oo mai ai lenei malaia", "it came to pass from this a calamity"], ["ia te", "unto"], ["i tatou.", "in we (incl)"], ["Ona latou faia lea", "and they made"], ["o le vili,", "the a gimblet"], ["ua faasaga foi", "toward also"], ["le vili ia Iona.", "the a gimblet to Jonah"]]},
  {num:8,words:[["Ona latou fai atu ai lea", "and they said to"], ["ia te ia,", "unto him"], ["Ina ta'u mai ia", "let tell from to"], ["ia te", "unto"], ["i matou,", "in we (excl)"], ["po o ai", "night"], ["ua oo mai ai lenei malaia", "it came to pass from this a calamity"], ["ia te", "unto"], ["i tatou?", "in we (incl)"], ["o le a ea lou faiva?", "what to rise (as a diver to the sur- your ministry"], ["o fea ea", "fea to rise (as a diver to the sur-"], ["na e sau ai? o ifea ea lou nuu?", "to come ifea to rise (as a diver to the sur- your nation"], ["o ai ea tagata", "to rise (as a diver to the sur- man"], ["na e tupu", "to king"], ["mai ai?", "from"]]},
  {num:9,words:[["Ona fai mai ai lea", "and said"], ["o ia ia te", "he unto"], ["i latou,", "them"], ["O a'u", "I am"], ["o le Eperu;", "the eperu"], ["ou te mata'u ia", "I ax to"], ["Ieova le Atua", "Jehovah God"], ["o le lagi,", "Heaven"], ["o le", "the"], ["na faia", "made"], ["le sami", "the sea"], ["ma le eleele matutu.", "and the earth dry"]]},
  {num:10,words:[["Ona matuā fefefe ai lea", "and very fefefe"], ["o ia tagata,", "he man"], ["ma latou faapea atu ia te ia,", "and they thus unto him"], ["Se a lenei mea", "a but this thing"], ["ua e faia? Auā", "to made for"], ["na iloa ia tagata", "known to man"], ["ua sola o ia", "flee he"], ["ai luma o Ieova,", "before Jehovah"], ["auā na ia ta'u atu ai", "for he told"], ["ia te", "unto"], ["i latou.", "them"]]},
  {num:11,words:[["Ona latou fai atu ai lea", "and they said to"], ["ia te ia,", "unto him"], ["Se a se mea matou", "a but a thing we (excl)"], ["te faia ia te oe,", "made unto thee"], ["ina ia malū ai", "so that malū"], ["le sami", "the sea"], ["mo i matou? Auā", "for in we (excl) for"], ["ua tuputupu pea", "tuputupu continually"], ["le sousou", "the sousou"], ["o le vasa.", "the ocean"]]},
  {num:12,words:[["Ona fai mai lea o ia", "And he said he"], ["ia te", "unto"], ["i latou,", "them"], ["Ina sii ia ia te au,", "let lift up to unto me"], ["ma lafo ifo ia te au", "and cloth used as gratuity for a talking chief unto me"], ["i le sami,", "in the sea"], ["ona malū ai lea", "and malū"], ["o le vasa ia te outou;", "the ocean unto you"], ["auā ua ou iloa", "for I known"], ["o a'u", "I am"], ["ua oo mai ai lenei afā tetele", "it came to pass from this cyclone great"], ["ia te outou.", "unto you"]]},
  {num:13,words:[["A ua taualo faamalosi lava", "but to row or paddle faamalosi indeed"], ["o ia tagata,", "he man"], ["ina ia toe oo", "so that again oo"], ["i uta;", "in uta"], ["a ua", "but"], ["le mafaia e", "the able by"], ["i latou,", "them"], ["auā ua tuputupu pea", "for tuputupu continually"], ["le sousou", "the sousou"], ["o le vasa", "the ocean"], ["sa tiga ai", "pain"], ["i latou.", "them"]]},
  {num:14,words:[["Ona latou valaau atu lea", "and they call"], ["ia Ieova,", "to Jehovah"], ["ua faapea atu,", "saying"], ["Matou te aioi atu ia te oe,", "we (excl) aioi unto thee"], ["Ieova e,", "Jehovah by"], ["aua ne'i fano", "for now perish"], ["i matou", "in we (excl)"], ["ona o le ola o lenei tagata", "because of the life this man"], ["o le aveesea ,", "the aveesea"], ["auā foi ne'i faaee", "for also now to place upon"], ["i luga ia", "in above to"], ["i matou", "in we (excl)"], ["le toto", "the blood"], ["o le tagata", "man"], ["e le sala;", "by the a fine"], ["auā o oe Ieova", "for you Jehovah"], ["e,", "by"], ["ua e faia", "to made"], ["le mea", "the thing"], ["ua e finagalo", "to a chiefs will or desire"], ["i ai.", "therein"]]},
  {num:15,words:[["Ona latou sii", "and they lift up"], ["ae lea ia Iona,", "but to Jonah"], ["ma lafo ia te ia", "and cloth used as gratuity for a talking chief unto him"], ["i le sami,", "in the sea"], ["ona mavae lea", "and a parting"], ["o le sousou", "the sousou"], ["o le sami.", "Sea"]]},
  {num:16,words:[["Ona matuā matatau ai lea", "and very fear"], ["o ia tagata ia", "he man to"], ["Ieova,", "Jehovah"], ["ma latou faia", "and they made"], ["le taulaga ia Ieova,", "the offering to Jehovah"], ["ma latou tauto", "and they to take an oath"], ["i ni tautoga.", "in some tautoga"]]},
  {num:17,words:[["Na tofia", "chosen"], ["e Ieova", "to Jehovah"], ["le i'a tele", "the fish great"], ["e foloina Iona.", "by foloina Jonah"], ["Na i ai foi Iona", "therein also Jonah"], ["i le manava", "in the manava"], ["o le i'a", "the fish"], ["e tolu ao", "by three day"], ["e tolu foi po.", "by three also night"]]},
  {num:18,words:[["E fai foi", "to make also"], ["le aiga o lakopo", "the family lakopo"], ["ma aй,", "and aй"], ["e fai foi Ie aiga", "to make also faamaise family"], ["o Iosefa", "Joseph"], ["ma aб mumú,", "and aб mumú"], ["a e fai", "but to make"], ["le aiga o Esau", "the family Esau"], ["ma tagutugutu o saito;", "and tagutugutu wheat"], ["latou te faamu foi ia te", "they faamu also unto"], ["i latou,", "them"], ["ma faauma ia te", "and faauma unto"], ["i latou;", "them"], ["e leai foi sé toe", "there is not also sé again"], ["i le aiga o Esau;", "in the family of Esau"], ["aua ua fetalai", "for said"], ["mai ai", "from"], ["le Alii.", "the Lord"]]},
  {num:19,words:[["O i latou foi o", "them also"], ["i le itu", "on the side"], ["i toga", "in Tonga"], ["e fai", "to make"], ["mo i latou", "for them"], ["le mauga o Esau;", "the mountain Esau"], ["o i latou foi o", "them also"], ["i le itu maulalo", "on the side maulalo"], ["e fai", "to make"], ["mo i latou", "for them"], ["le nuu o Filisitia;", "the nation Philistine"], ["e fai foi", "to make also"], ["mo i latou", "for them"], ["le laueleele o Ffaraima,", "the ground ffaraima"], ["ma le laueleele o Samaria;", "and the ground Samaria"], ["e fai foi Kiliata", "to make also kiliata"], ["mo Peniamina.", "for Benjamin"]]},
  {num:20,words:[["O le tafeaga foi o lenei itu taua", "the exiles in wa^ also this itu war"], ["a le fanauga", "but the children"], ["a Isaraelu", "of Israel"], ["e ua", "by"], ["i sa Kananā", "in kananā"], ["e oo", "it shall come to pass"], ["i Sarefata;", "in sarefata"], ["o le tafeaga foi o Ierusalema", "the exiles in wa^ also Jerusalem"], ["o i Sefarata,", "in sefarata"], ["e fai", "to make"], ["mo i latou", "for them"], ["o aai o", "city"], ["i le itu", "on the side"], ["i toga.", "in Tonga"]]},
  {num:21,words:[["E o", "by"], ["ae foi faaola", "but also save"], ["i le mauga o Siona,", "in the mountain Zion"], ["ina ia faasalaina", "so that faasalaina"], ["le mauga o Esau;", "the mountain Esau"], ["e fai foi", "to make also"], ["le malo", "the government"], ["mo le ALII.", "for the Lord"], ["O LE TUSI", "the book"], ["A LE PEROFETA O IONA", "of the prophet Jonah"], ["Ua auina lona", "sent his"], ["e le Alii", "by the Lord"]]},
];
renderVerseSet(jon_ch_1_Verses, 'jon-ch1-verses');

var jon_ch_2_Verses = [
  {num:1,words:[["Na tatalo foi Iona ia", "pray also Jonah to"], ["Ieova lona Atua", "Jehovah his God"], ["i le manava", "in the manava"], ["o le i'a,", "the fish"]]},
  {num:2,words:[["ua faapea atu,", "saying"], ["Na a'u valaau atu ia", "I call to"], ["Ieova ona", "Jehovah then"], ["o lo'u puapuaga,", "my affliction"], ["ua na faafofoga", "listen"], ["mai foi ia te au;", "from also unto me"], ["na ou alaga atu", "I a shoulder or leg of aa '"], ["nai le mea maulalo", "from the thing maulalo"], ["i tuugamau,", "in tuugamau"], ["ua e faafofoga", "to listen"], ["i lo'u leo.", "in my voice"]]},
  {num:3,words:[["Na e lafoina a'u", "by lafoina I"], ["i le moana,", "in the deep"], ["i totonu lava", "in inside indeed"], ["o le sami;", "Sea"], ["na siosioina lava a'u", "siosioina indeed I"], ["e le au;", "by the I"], ["na lofia a'u", "lofia I"], ["i ou galu", "in I wave"], ["ma ou peau uma lava.", "and I a wave all indeed"]]},
  {num:4,words:[["Ona ou faapea ai lea,", "and I thus"], ["Ua lafoaiina a'u ai luma", "lafoaiina I before"], ["o ou fofoga;", "I face"], ["a ou te toe faasaga atu", "but I again toward"], ["i lou malumalu paia.", "in your temple holy"]]},
  {num:5,words:[["Ua siosioina a'u", "siosioina I"], ["e le sami,", "by the sea"], ["na manū a'u oti;", "manū I die"], ["ua ufitia a'u", "covered I"], ["i le moana,", "in the deep"], ["ua fusia lo'u ulu", "fusia my head"], ["i le limu.", "in the seaweed"]]},
  {num:6,words:[["Ua ou alu ifo", "I go"], ["i vae mauga;", "in foot mountain"], ["ua faamauina faamau", "faamauina a hinge"], ["o le lalolagi", "the earth"], ["i luga ia te au", "in above unto me"], ["e faavavau;", "forever/everlasting"], ["a e te aveina", "but by aveina"], ["ae lo'u ola ai", "but my life"], ["le lua,", "the two"], ["Ieova e lo'u Atua.", "Jehovah to my God"]]},
  {num:7,words:[["Na ou manatua Ieova", "I remember Jehovah"], ["ina o vaivai", "let weak"], ["o lo'u loto", "my heart"], ["i totonu ia te au;", "in inside unto me"], ["na oo atu foi la'u tatalo", "oo also my pray"], ["ia te oe", "unto thee"], ["i lou malumalu paia.", "in your temple holy"]]},
  {num:8,words:[["O e", "who"], ["ua anaana", "his own"], ["i mea faatauvaa", "in thing faatauvaa"], ["ma le pepelo", "and the false"], ["ua lafoaiina e", "lafoaiina by"], ["i latou", "them"], ["o mea", "thing"], ["e manuia ai", "to peace"], ["i latou.", "them"]]},
  {num:9,words:[["A o a'u,", "but I am"], ["ou te faitaulaga ia te oe", "I priest unto thee"], ["ma le upu faafetai;", "and the word to tliank"], ["ou te faia", "I make"], ["le mea", "the thing"], ["na ou tauto ai.", "I to take an oath"], ["Mai ia Ieova", "from to Jehovah"], ["le olataga.", "the a means of deliverance"]]},
  {num:10,words:[["Ua fetalai atu Ieova", "said to Jehovah"], ["i le i'a,", "in the fish"], ["ona luai lea e ia", "and luai by him"], ["o Iona", "Jonah"], ["i le eleele matutu.", "in the earth dry"]]},
];
renderVerseSet(jon_ch_2_Verses, 'jon-ch2-verses');

var jon_ch_3_Verses = [
  {num:1,words:[["Ona oo mai lea", "and oo from"], ["o le afioga", "the a word"], ["a Ieova ia Iona,", "of Jehovah to Jonah"], ["o le foi faalua", "the also faalua"], ["mai lea,", "from"], ["ua faapea mai,", "saying"]]},
  {num:2,words:[["Ina tulai ia,", "let arose up to"], ["ina alu", "let go"], ["i Nineva", "in nineva"], ["le aai tele,", "the city great"], ["ma tala'i atu", "and preach"], ["i ai", "therein"], ["le tala'iga ou te fai atu ai", "the tala'iga I said to"], ["ia te oe.", "unto thee"]]},
  {num:3,words:[["Ona tulai ai lea o Iona,", "and arose up Jonah"], ["ua alu", "go"], ["i Nineva,", "in nineva"], ["e faapei", "to like"], ["ona fetalai mai o Ieova.", "and said Jehovah"], ["O le aai matuā tele", "the city very great"], ["lava Nineva,", "indeed nineva"], ["e tusa ma le savaliga", "according to the savaliga"], ["o aso", "day"], ["e tolu.", "by three"]]},
  {num:4,words:[["Ua amata", "began"], ["ona ulu atu o Iona", "and head Jonah"], ["i le aai,", "in the city"], ["o le savaliga", "the savaliga"], ["o le aso", "the day"], ["e tasi,", "by one"], ["na alaga foi o ia,", "a shoulder or leg of aa ' also he"], ["ua faapea atu,", "saying"], ["E toe fagafulu po", "to again fagafulu night"], ["ona faaumatia lea o Nineva.", "and destroy nineva"]]},
  {num:5,words:[["Ona talitonu ai lea o tagata", "and believe man"], ["o Nineva", "nineva"], ["i le Atua,", "in the God"], ["ua tala'i atu foi", "preach also"], ["e i latou la latou anapogi,", "by them their to fast"], ["ua latou oofu foi", "they oofu also"], ["i le ie talatala,", "in the faamaise to untie"], ["o alii", "Lord"], ["atoa ma tagatānuu.", "and tagatānuu"]]},
  {num:6,words:[["Auā ua oo", "for it came to pass"], ["le tala", "the side"], ["i le tupu o Nineva,", "in the king nineva"], ["ona tulai ai lea o ia", "and arose up he"], ["i lona nofoālii,", "in his nofoālii"], ["ma tuu ese ia te ia", "and put away unto him"], ["lona ofu tele,", "his garment great"], ["ona ufutia lea o ia", "and ufutia he"], ["e ia", "by him"], ["i le ie talatala,", "in the faamaise to untie"], ["ma nofo", "and dwell"], ["i le lefulefu.", "in the lefulefu"]]},
  {num:7,words:[["Ua ia tala'i atu,", "to preach"], ["ma faailo atu", "and faailo"], ["i Nineva", "in nineva"], ["i le pule", "in the rule"], ["a le tupu", "but the king"], ["ma alii", "and Lord"], ["sa ia te ia,", "unto him"], ["ua faapea atu,", "saying"], ["Aua ne'i 'ai sina mea", "for now eat white thing"], ["e tagata,", "to man"], ["po o manu,", "night animal"], ["po o lafu povi,", "night a herd cattle"], ["po o lafu mamoe;", "night a herd sheep"], ["aua lava ne'i latou", "for indeed now they"], ["aai,", "city"], ["aua foi latou te inu vai;", "for also they drink water"]]},
  {num:8,words:[["a ia ufitia lava tagata", "but to covered indeed man"], ["ma manu", "and animal"], ["i ie talatala,", "in faamaise to untie"], ["ma ia latou matuā alalaga atu", "and to they very alalaga"], ["i le Atua;", "in the God"], ["ia latou taitasi foi", "to they each also"], ["ma liliu mai", "and turned from"], ["i lana amioga leaga,", "in his amioga evil"], ["ma le faasaua", "and the to be oppressive"], ["ua i o latou", "in they"], ["lima.", "five"]]},
  {num:9,words:[["O ai", "o ai"], ["se na te iloa,", "a he known"], ["atonu e liliu", "impers to turned"], ["mai le Atua,", "from God"], ["ma salamo,", "and repent"], ["ma liliu ese", "and turned away"], ["i lona toasa mamafa,", "in his wrath mamafa"], ["ina ia le fano ai", "so that the perish"], ["i tatou.", "in we (incl)"]]},
  {num:10,words:[["Ua silafia", "seen"], ["e le Atua", "by God"], ["a latou galuega,", "but they work"], ["ina ua liliu ese", "let turned away"], ["i latou", "them"], ["i lo latou ala leaga;", "in the they arise evil"], ["ona salamo ai lea", "and repent"], ["o le Atua", "of God"], ["i le malaia", "in the a calamity"], ["na ia fetalaia", "to fetalaia"], ["mai na te faia ia te", "from he made unto"], ["i latou;", "them"], ["e lei faia.", "to whale's teeth made"]]},
];
renderVerseSet(jon_ch_3_Verses, 'jon-ch3-verses');

var jon_ch_4_Verses = [
  {num:1,words:[["Ua matuā leaga lava lenei mea", "very evil indeed this thing"], ["ia Iona,", "to Jonah"], ["ua ita lava o ia.", "angry indeed he"]]},
  {num:2,words:[["Ona tatalo ai lea o ia", "and pray he"], ["ia Ieova,", "to Jehovah"], ["ua faapea atu,", "saying"], ["O lenei,", "this"], ["Ieova e,", "Jehovah by"], ["e le", "by the"], ["o la'u upu ea lenei", "my word to rise (as a diver to the sur- this"], ["ina ou", "let I"], ["i ai", "therein"], ["i lo'u nuu?", "in my nation"], ["O le mea foi lea", "the thing also"], ["na ou muai sola ai", "I first flee"], ["i Tasesa;", "in tasesa"], ["auā ua ou iloa oe", "for I known you"], ["o le Atua alofa fua,", "of God love fruit"], ["ma le alofa mutimutivale,", "and the mercy"], ["e tele gese lou toasa,", "to great slow your wrath"], ["ua tele foi lou alofa,", "great also your love"], ["ua e salamo foi", "to repent also"], ["ma ua", "and"], ["le faaoo", "the faaoo"], ["le malaia.", "the a calamity"]]},
  {num:3,words:[["O lenei foi,", "this also"], ["Ieova e,", "Jehovah by"], ["ou te aioi atu ia te oe,", "I aioi unto thee"], ["ia e ave ese lo'u ola;", "to to take away my life"], ["auā e lelei", "for to good"], ["ona ou oti,", "and I die"], ["a e leaga", "but to evil"], ["ona ou ola.", "and I life"]]},
  {num:4,words:[["Ona fetalai mai ai lea", "and said"], ["o Ieova,", "Jehovah"], ["Ua lelei ea lou ita?", "that it was good to rise (as a diver to the sur- your angry"]]},
  {num:5,words:[["Ona alu atu lea o Iona ai", "and go away Jonah"], ["le aai,", "the city"], ["ua nofo foi", "dwell also"], ["i le itu", "on the side"], ["i sasae", "in to tear"], ["o le aai,", "the city"], ["ua na faia foi", "made also"], ["mo ia", "for to"], ["i lea mea", "in thing"], ["le fale apitaga,", "the house a tempoiary"], ["ua nofo", "dwell"], ["i ona lalo", "in then under"], ["i le paolo,", "in the paolo"], ["seia iloa e ia", "until known by him"], ["pe se", "whether a"], ["a se mea", "but a thing"], ["e oo", "it shall come to pass"], ["i le aai.", "in the city"]]},
  {num:6,words:[["Na saunia foi", "prepared also"], ["e Ieova", "to Jehovah"], ["le Atua", "God"], ["le kikaiona,", "the kikaiona"], ["ua na faasosolo", "faasosolo"], ["i ai", "therein"], ["i luga o Iona,", "upon Jonah"], ["e fai", "to make"], ["ma faapaologa", "and faapaologa"], ["i luga", "in above"], ["o lona ulu,", "his head"], ["e laveai ia te ia", "to deliver unto him"], ["ai lona tiga.", "his pain"], ["Ona matuā fiafia ai lea", "and very competition"], ["o Iona", "Jonah"], ["ona o le kikaiona.", "because of the kikaiona"]]},
  {num:7,words:[["Ua oo", "it came to pass"], ["ina malama", "let malama"], ["ae o le taeao,", "but the morning"], ["ona saunia lea", "and prepared"], ["o le Atua", "of God"], ["o le anufe;", "the anufe"], ["ua atia foi", "atia also"], ["e le anufe", "by the anufe"], ["o le kikaiona,", "the kikaiona"], ["ona mago ai lea.", "and a small eel"]]},
  {num:8,words:[["Ua alu", "go"], ["ae le la,", "but the la"], ["ona saunia lea", "and prepared"], ["e le Atua", "by God"], ["o le matagi vevela", "the wind to be hot"], ["mai sasae;", "from to tear"], ["ona ogotia ai lea", "and ogotia"], ["o le ulu o Iona", "the head Jonah"], ["i le la,", "in the la"], ["ona vaivai ai lea o ia,", "and weak he"], ["ma ia faatoga atu ia", "and to to bog to"], ["oti o ia,", "die he"], ["ua ia faapea atu,", "to thus"], ["E lelei", "to good"], ["ona ou oti,", "and I die"], ["a e leaga", "but to evil"], ["ona ou ola.", "and I life"]]},
  {num:9,words:[["Ona fetalai mai lea", "and said"], ["o le Atua ia", "of God to"], ["Iona,", "Jonah"], ["E lelei ea lou ita", "to good to rise (as a diver to the sur- your angry"], ["ona o le kikaiona?", "because of the kikaiona"], ["Ona fai atu lea o ia,", "And he said he"], ["Ou te ita tele lava,", "I angry great indeed"], ["e oo lava", "it shall come to pass indeed"], ["i le oti.", "in the die"]]},
  {num:10,words:[["Ona fetalai mai lea o Ieova,", "and said Jehovah"], ["Ua e alofa", "to love"], ["i le kikaiona,", "in the kikaiona"], ["o le mea", "the thing"], ["na e le galue ai,", "by the work"], ["pe faatupuina;", "whether faatupuina"], ["o le mea", "the thing"], ["na tupu", "king"], ["i le po", "in the night"], ["e tasi,", "by one"], ["na mamae foi", "mamae also"], ["i le po", "in the night"], ["e tasi.", "by one"]]},
  {num:11,words:[["O a'u foi ou te", "I am also I"], ["le alofa ea", "the love to rise (as a diver to the sur-"], ["i Nineva", "in nineva"], ["le aai tele,", "the city great"], ["o loo", "o loo"], ["i ai tagata", "therein man"], ["e sili", "to most"], ["ona toatele", "and many"], ["i le selau afe", "in the hundred thousand"], ["ma afe", "and thousand"], ["e lua fulu,", "by two fulu"], ["o e le iloa o latou", "who the known they"], ["lima taumatau po o latou", "five right hand night they"], ["lima tauagavale;", "five tauagavale"], ["ma manu vaefa foi e tele.", "and beast also to great"]]},
];
renderVerseSet(jon_ch_4_Verses, 'jon-ch4-verses');

})();