(function() {
var _jon_ch_1_Verses = [
  {num:1,words:[["Ua oo mai le afioga", "it came to pass from the word (divine)"], ["a Ieova ia", "of the LORD to"], ["Iona", "Jonah"], ["le atalii o Amitai,", "the son of Amitai"], ["ua faapea mai,", "and said"]]},
  {num:2,words:[["Ina tulai ia,", "so that arise up to"], ["ina alu", "so that go"], ["i Nineva", "in Nineveh"], ["le aai tele,", "the city great"], ["ma alaga atu", "and cry"], ["i ai;", "therein"], ["auā", "for"], ["ua oo mai", "it came to pass from"], ["a latou agasala", "but they sin"], ["i o'u luma.", "before me"]]},
  {num:3,words:[["A", "but"], ["ua tulai Iona", "arose up Jonah"], ["e sola", "to escape"], ["i Tasesa ai", "in Tasesa"], ["luma o Ieova,", "before the LORD"], ["ua alu ifo foi", "went down also"], ["o ia", "he"], ["i Iopa,", "in Job"], ["ma", "and"], ["na maua", "received"], ["le vaa", "the ship"], ["a alu", "but go"], ["i Tasesa;", "in Tasesa"], ["ona avatu ai lea", "and give away then then"], ["e ia", "by him"], ["o le totogi,", "the wages"], ["ma alu ifo", "and go down"], ["i ai,", "therein"], ["e o", "by of"], ["ma", "and"], ["i latou", "them"], ["i Tasesa ai", "in Tasesa"], ["luma o Ieova.", "before the LORD"]]},
  {num:4,words:[["A", "but"], ["ua tuuina ifo", "given down"], ["e Ieova", "the LORD"], ["le matagi tetele", "the wind great"], ["i le vasa,", "in the ocean"], ["ona afā tetele ai lea", "and cyclone great then then"], ["i le vasa,", "in the ocean"], ["se manū", "a manū"], ["a lepetia", "but overthrown"], ["le vaa.", "the ship"]]},
  {num:5,words:[["Ona matatau ai lea", "and fear then then"], ["o le auvaa,", "the auvaa"], ["ma latou taitasi", "and they each"], ["ma valaau", "and call"], ["i lona atua;", "in his God"], ["ua latou lafo foi", "they cloth used as gratuity for a talking chief also"], ["le oloa", "the goods"], ["na", "na"], ["i le vaa", "in the ship"], ["i le sami,", "in the sea"], ["e faamāmāina ai.", "to make lung"], ["A", "but"], ["e peitai o Iona", "to however of Jonah"], ["na alu ifo", "went down"], ["o ia", "he"], ["i totonu lava", "in inside indeed"], ["o le vaa;", "the ship"], ["na taoto foi", "lay down also"], ["o ia,", "he"], ["ma moegase.", "and moegase"]]},
  {num:6,words:[["Ona alu atu lea", "and go away"], ["o le aliivaa", "the aliivaa"], ["ia te ia,", "to him"], ["ma fai atu", "and said to"], ["ia te ia,", "to him"], ["A faapefea ea oe,", "but how indeed?/really? you"], ["lē moe gase?", "not sleep gase"], ["ina tulai ia,", "so that arise up to"], ["ina valaau", "so that call"], ["i lou Atua,", "in your God"], ["atonu", "impers"], ["e manatu mai le Atua", "to thought from God"], ["ia te", "unto"], ["i tatou,", "in we (incl)"], ["ina ia le oti", "so that the die"], ["i tatou.", "in we (incl)"]]},
  {num:7,words:[["Ona latou fetautalatalai lea,", "and they converse with one another"], ["Ina o mai ia,", "so that of from to"], ["se'i tatou faia", "a flower put into the hair or let us make"], ["le vili,", "the a gimblet"], ["ina ia tatou", "so that we (incl)"], ["iloa po o ai", "know who?"], ["ua oo mai ai", "it came to pass from"], ["lenei malaia ia te", "this disaster unto"], ["i tatou.", "in we (incl)"], ["Ona latou faia lea", "and they made"], ["o le vili,", "the a gimblet"], ["ua faasaga foi", "toward also"], ["le vili ia", "the a gimblet to"], ["Iona.", "Jonah"]]},
  {num:8,words:[["Ona latou fai atu ai lea", "and they said to then then"], ["ia te ia,", "to him"], ["Ina ta'u mai ia ia te", "so that tell from to him"], ["i matou,", "in we (excl)"], ["po o ai", "who?"], ["ua oo mai ai", "it came to pass from"], ["lenei malaia ia te", "this disaster unto"], ["i tatou?", "in we (incl)"], ["o le a ea", "what indeed?/really?"], ["lou faiva? o fea ea", "your ministry of where?/which? indeed?/really?"], ["na e sau ai?", "you came"], ["o ifea ea", "where? indeed?/really?"], ["lou nuu? o ai ea tagata", "your nation who man"], ["na e tupu mai ai?", "you king from"]]},
  {num:9,words:[["Ona fai mai ai lea", "and said then then"], ["o ia ia te", "he unto"], ["i latou,", "them"], ["O a'u", "I am"], ["o le Eperu;", "the Hebrew"], ["ou te mata'u", "I will ax"], ["ia Ieova", "to the LORD"], ["le Atua", "God"], ["o le lagi,", "Heaven"], ["o le", "the"], ["na faia", "made"], ["le sami", "the sea"], ["ma le eleele matutu.", "and the earth dry"]]},
  {num:10,words:[["Ona matuā fefefe ai lea", "and exceedingly afraid then then"], ["o ia tagata,", "he man"], ["ma latou faapea atu", "and they thus"], ["ia te ia,", "to him"], ["Se a lenei", "a but this"], ["mea", "thing"], ["ua e faia?", "you made"], ["Auā", "for"], ["na iloa ia", "knew to"], ["tagata", "man"], ["ua sola o ia", "escaped he"], ["ai luma o Ieova,", "before the LORD"], ["auā", "for"], ["na ia ta'u atu ai", "he told"], ["ia te", "unto"], ["i latou.", "them"]]},
  {num:11,words:[["Ona latou fai atu ai lea", "and they said to then then"], ["ia te ia,", "to him"], ["Se a se mea matou", "a but a thing we (excl)"], ["te faia ia te oe,", "made unto you"], ["ina ia malū ai", "so that malū"], ["le sami", "the sea"], ["mo", "for"], ["i matou? Auā", "in we (excl) for"], ["ua tuputupu pea", "tuputupu continually"], ["le sousou", "the sousou"], ["o le vasa.", "the ocean"]]},
  {num:12,words:[["Ona fai mai lea", "And he said"], ["o ia ia te", "he unto"], ["i latou,", "them"], ["Ina sii ia ia te au,", "so that lift up to him me"], ["ma lafo ifo", "and cloth used as gratuity for a talking chief down"], ["ia te au", "unto me"], ["i le sami,", "in the sea"], ["ona malū ai lea", "and malū then then"], ["o le vasa", "the ocean"], ["ia te outou;", "unto you"], ["auā", "for"], ["ua ou iloa", "I knew"], ["o a'u", "I am"], ["ua oo mai ai", "it came to pass from"], ["lenei afā tetele", "this cyclone great"], ["ia te outou.", "unto you"]]},
  {num:13,words:[["A", "but"], ["ua taualo faamalosi lava", "to row or paddle was strong indeed"], ["o ia tagata,", "he man"], ["ina ia toe oo", "so that again oo"], ["i uta;", "inland"], ["a", "but"], ["ua", "ua"], ["le mafaia e", "the able by"], ["i latou,", "them"], ["auā", "for"], ["ua tuputupu pea", "tuputupu continually"], ["le sousou", "the sousou"], ["o le vasa", "the ocean"], ["sa tiga ai", "grieved"], ["i latou.", "them"]]},
  {num:14,words:[["Ona latou valaau atu lea", "and they call"], ["ia Ieova,", "to the LORD"], ["ua faapea atu,", "and said"], ["Matou te aioi atu", "we (excl) cry out"], ["ia te oe,", "unto you"], ["Ieova e,", "O LORD!"], ["aua ne'i fano", "for now perish"], ["i matou", "in we (excl)"], ["ona", "and"], ["o le ola", "the life"], ["o lenei", "now"], ["tagata", "man"], ["o le aveesea ,", "the removed away"], ["auā foi", "for also"], ["ne'i faaee", "now to place upon"], ["i luga ia", "in above to"], ["i matou", "in we (excl)"], ["le toto", "the blood"], ["o le tagata", "man"], ["e le sala;", "shall not a fine"], ["auā o oe", "for of you"], ["Ieova e,", "O LORD!"], ["ua e faia", "you made"], ["le mea", "the thing"], ["ua e finagalo", "you a chiefs will or desire"], ["i ai.", "therein"]]},
  {num:15,words:[["Ona latou sii", "and they lift up"], ["ae lea", "but"], ["ia Iona,", "to Jonah"], ["ma lafo ia te ia", "and cloth used as gratuity for a talking chief to him"], ["i le sami,", "in the sea"], ["ona mavae lea", "and passed"], ["o le sousou", "the sousou"], ["o le sami.", "Sea"]]},
  {num:16,words:[["Ona matuā matatau ai lea", "and exceedingly fear then then"], ["o ia tagata", "he man"], ["ia Ieova,", "to the LORD"], ["ma latou faia", "and they made"], ["le taulaga ia", "the offering to"], ["Ieova,", "the LORD"], ["ma latou tauto", "and they to take an oath"], ["i ni tautoga.", "in some oath"]]},
  {num:17,words:[["Na tofia", "chosen"], ["e Ieova", "the LORD"], ["le i'a tele", "the fish great"], ["e foloina Iona.", "by foloina Jonah"], ["Na", "Na"], ["i ai", "therein"], ["foi Iona", "also Jonah"], ["i le manava", "in the womb"], ["o le i'a", "the fish"], ["e tolu ao", "by three day"], ["e tolu foi", "by three also"], ["po.", "night"]]},
  {num:18,words:[["E fai foi", "to make also"], ["le aiga o lakopo", "the family of lakopo"], ["ma aй,", "and aй"], ["e fai foi", "to make also"], ["Ie aiga o Iosefa", "faamaise family of Joseph"], ["ma aб mumú,", "and aб mumú"], ["a", "but"], ["e fai", "to make"], ["le aiga o Esau", "the family of Esau"], ["ma tagutugutu o saito;", "and tagutugutu of wheat"], ["latou te faamu foi", "they will burn incense also"], ["ia te", "unto"], ["i latou,", "them"], ["ma faauma ia te", "and finish unto"], ["i latou;", "them"], ["e leai foi", "there is not also"], ["sé toe", "sé again"], ["i le aiga", "in the family"], ["o Esau;", "Esau"], ["aua", "for"], ["ua fetalai mai ai", "said"], ["le Alii.", "the Lord"]]},
  {num:19,words:[["O", "O"], ["i latou foi", "them also"], ["o", "o"], ["i le itu", "on the side"], ["i toga", "southward"], ["e fai", "to make"], ["mo", "for"], ["i latou", "them"], ["le mauga o Esau;", "the mountain of Esau"], ["o", "o"], ["i latou foi", "them also"], ["o", "o"], ["i le itu maulalo", "on the side lowly"], ["e fai", "to make"], ["mo", "for"], ["i latou", "them"], ["le nuu o Filisitia;", "the nation of Philistine"], ["e fai foi", "to make also"], ["mo", "for"], ["i latou", "them"], ["le laueleele o Ffaraima,", "the ground Ffaraima"], ["ma le laueleele", "and the ground"], ["o Samaria;", "Samaria"], ["e fai foi", "to make also"], ["Kiliata", "Gilead"], ["mo Peniamina.", "for Benjamin"]]},
  {num:20,words:[["O le tafeaga foi", "the exiles in wa^ also"], ["o lenei", "now"], ["itu taua", "side precious"], ["a le fanauga", "but the children"], ["a Isaraelu", "of Israel"], ["e ua", "by"], ["i", "in"], ["sa Kananā", "of the clan of Canaanites"], ["e oo", "it shall come to pass"], ["i Sarefata;", "in Sarefata"], ["o le tafeaga foi", "the exiles in wa^ also"], ["o Ierusalema o", "Jerusalem of"], ["i Sefarata,", "in Sefarata"], ["e fai", "to make"], ["mo", "for"], ["i latou", "them"], ["o aai o", "city of"], ["i le itu", "on the side"], ["i toga.", "southward"]]},
  {num:21,words:[["E o ae foi", "by go up also"], ["faaola", "save"], ["i le mauga", "in the mountain"], ["o Siona,", "Zion"], ["ina ia faasalaina", "so that punished"], ["le mauga o Esau;", "the mountain of Esau"], ["e fai foi", "to make also"], ["le malo", "the government"], ["mo le ALII.", "for the Lord"], ["O LE TUSI", "the book"], ["A LE PEROFETA", "of the prophet"], ["O IONA", "Jonah"], ["Ua auina", "sent"], ["lona", "his"], ["e le Alii", "shall not Lord"]]},
];
renderVerseSet(_jon_ch_1_Verses, 'jon-ch1-verses');

var _jon_ch_2_Verses = [
  {num:1,words:[["Na tatalo foi", "prayed also"], ["Iona ia Ieova", "Jonah to the LORD"], ["lona Atua", "his God"], ["i le manava", "in the womb"], ["o le i'a,", "the fish"]]},
  {num:2,words:[["ua faapea atu,", "and said"], ["Na a'u valaau atu ia", "me called to"], ["Ieova", "the LORD"], ["ona", "and"], ["o lo'u puapuaga,", "my affliction"], ["ua", "ua"], ["na faafofoga mai foi", "listen from also"], ["ia te au;", "unto me"], ["na ou alaga atu nai", "I cried from"], ["le mea maulalo", "the thing lowly"], ["i tuugamau,", "in grave"], ["ua e faafofoga", "you listen"], ["i lo'u leo.", "in my voice"]]},
  {num:3,words:[["Na e lafoina a'u", "you cast me"], ["i le moana,", "in the deep"], ["i totonu lava", "in inside indeed"], ["o le sami;", "Sea"], ["na siosioina lava a'u", "surrounded indeed me"], ["e le au;", "shall not me"], ["na lofia a'u", "lofia me"], ["i ou galu", "in I wave"], ["ma ou peau uma lava.", "and I a wave all indeed"]]},
  {num:4,words:[["Ona ou faapea ai lea,", "and I thus then then"], ["Ua lafoaiina a'u", "forsaken me"], ["ai luma o ou fofoga;", "before of I face"], ["a ou te toe faasaga atu", "but I will again toward"], ["i lou malumalu paia.", "in your temple holy"]]},
  {num:5,words:[["Ua siosioina a'u", "surrounded me"], ["e le sami,", "shall not sea"], ["na manū a'u", "manū me"], ["oti;", "die"], ["ua ufitia a'u", "covered me"], ["i le moana,", "in the deep"], ["ua fusia", "fusia"], ["lo'u ulu", "my head"], ["i le limu.", "in the seaweed"]]},
  {num:6,words:[["Ua ou alu ifo", "I went down"], ["i vae mauga;", "in foot mountain"], ["ua faamauina faamau", "established established"], ["o le lalolagi", "the earth"], ["i luga ia te au", "in above unto me"], ["e faavavau;", "forever/everlasting"], ["a", "but"], ["e te aveina", "by taken away"], ["ae", "but"], ["lo'u ola ai", "my life"], ["le lua,", "the two"], ["Ieova", "the LORD"], ["e lo'u Atua.", "to my God"]]},
  {num:7,words:[["Na ou manatua", "I remembered"], ["Ieova", "the LORD"], ["ina o vaivai", "so that of weak"], ["o lo'u loto", "my heart"], ["i totonu ia te au;", "in inside unto me"], ["na oo atu foi", "arrived also"], ["la'u tatalo ia te oe", "my pray unto you"], ["i lou malumalu paia.", "in your temple holy"]]},
  {num:8,words:[["O", "O"], ["e ua anaana", "by his own"], ["i mea faatauvaa", "in thing vain"], ["ma le pepelo", "and the false"], ["ua lafoaiina e", "forsaken you"], ["i latou", "them"], ["o mea", "thing"], ["e manuia ai", "to peace"], ["i latou.", "them"]]},
  {num:9,words:[["A", "but"], ["o a'u,", "I am"], ["ou te faitaulaga", "I will priest"], ["ia te oe", "unto you"], ["ma le upu faafetai;", "and the word thank"], ["ou te faia", "I will make"], ["le mea", "the thing"], ["na ou tauto ai.", "I to take an oath"], ["Mai ia Ieova", "from to the LORD"], ["le olataga.", "the salvation"]]},
  {num:10,words:[["Ua fetalai atu", "said"], ["Ieova", "the LORD"], ["i le i'a,", "in the fish"], ["ona luai lea", "and luai"], ["e ia", "by him"], ["o Iona", "Jonah"], ["i le eleele matutu.", "the ground dry"]]},
];
renderVerseSet(_jon_ch_2_Verses, 'jon-ch2-verses');

var _jon_ch_3_Verses = [
  {num:1,words:[["Ona oo mai lea", "and came"], ["o le afioga", "the word (divine)"], ["a Ieova ia", "of the LORD to"], ["Iona,", "Jonah"], ["o le foi", "the also"], ["faalua mai lea,", "twice from"], ["ua faapea mai,", "and said"]]},
  {num:2,words:[["Ina tulai ia,", "so that arise up to"], ["ina alu", "so that go"], ["i Nineva", "in Nineveh"], ["le aai tele,", "the city great"], ["ma tala'i atu", "and preach"], ["i ai", "therein"], ["le tala'iga ou te fai atu ai", "the tala'iga I will said to"], ["ia te oe.", "unto you"]]},
  {num:3,words:[["Ona tulai ai lea", "and arise up then then"], ["o Iona,", "Jonah"], ["ua alu", "went"], ["i Nineva,", "in Nineveh"], ["e faapei", "to like"], ["ona fetalai mai", "and said"], ["o Ieova.", "the LORD"], ["O le aai matuā tele", "the city exceedingly great"], ["lava Nineva,", "indeed Nineveh"], ["e tusa ma le savaliga", "according to the savaliga"], ["o aso", "day"], ["e tolu.", "by three"]]},
  {num:4,words:[["Ua amata", "began"], ["ona ulu atu", "and head"], ["o Iona", "Jonah"], ["i le aai,", "in the city"], ["o le savaliga", "the savaliga"], ["o le aso", "the day"], ["e tasi,", "by one"], ["na alaga foi", "cried also"], ["o ia,", "he"], ["ua faapea atu,", "and said"], ["E toe fagafulu po", "to again forty night"], ["ona faaumatia lea", "and destroyed"], ["o Nineva.", "Nineveh"]]},
  {num:5,words:[["Ona talitonu ai lea", "and believe then then"], ["o tagata o Nineva", "of men Nineveh"], ["i le Atua,", "in the God"], ["ua tala'i atu foi", "preached also"], ["e", "by"], ["i latou la latou anapogi,", "them their to fast"], ["ua latou oofu foi", "they oofu also"], ["i le ie talatala,", "in the faamaise to untie"], ["o alii", "Lord"], ["atoa ma tagatānuu.", "and tagatānuu"]]},
  {num:6,words:[["Auā", "for"], ["ua oo", "it came to pass"], ["le tala", "the side"], ["i le tupu", "in the king"], ["o Nineva,", "Nineveh"], ["ona tulai ai lea", "and arise up then then"], ["o ia", "he"], ["i lona nofoālii,", "in his throne"], ["ma tuu ese", "and put away"], ["ia te ia", "to him"], ["lona ofu tele,", "his garment great"], ["ona ufutia lea", "and ufutia"], ["o ia e", "he by"], ["ia", "to"], ["i le ie talatala,", "in the faamaise to untie"], ["ma nofo", "and dwell"], ["i le lefulefu.", "in the ashes"]]},
  {num:7,words:[["Ua ia tala'i atu,", "to preached"], ["ma faailo atu", "and make maggot"], ["i Nineva", "in Nineveh"], ["i le pule", "in the rule"], ["a le tupu", "but the king"], ["ma alii", "and Lord"], ["sa ia te ia,", "to him"], ["ua faapea atu,", "and said"], ["Aua ne'i 'ai sina mea", "for now eat white thing"], ["e tagata,", "to man"], ["po o manu,", "night of animal"], ["po o lafu povi,", "night of herd cattle"], ["po o lafu mamoe;", "night of herd sheep"], ["aua lava ne'i latou", "for indeed now they"], ["aai,", "city"], ["aua foi", "for also"], ["latou te inu vai;", "they will drink water"]]},
  {num:8,words:[["a ia ufitia", "but to covered"], ["lava tagata", "indeed man"], ["ma manu", "and animal"], ["i ie talatala,", "in faamaise to untie"], ["ma ia latou", "and to they"], ["matuā alalaga atu", "exceedingly cry out"], ["i le Atua;", "in the God"], ["ia latou taitasi foi", "to they each also"], ["ma liliu mai", "and turned from"], ["i lana amioga leaga,", "in his amioga evil"], ["ma le faasaua", "and the cruel"], ["ua", "ua"], ["i o latou", "in of they"], ["lima.", "five"]]},
  {num:9,words:[["O ai", "O ai"], ["se", "a"], ["na te iloa,", "he knew"], ["atonu", "impers"], ["e liliu mai le Atua,", "to turned from God"], ["ma salamo,", "and repent"], ["ma liliu ese", "and turned away"], ["i lona toasa mamafa,", "in his wrath heavy"], ["ina ia le fano ai", "so that the perish"], ["i tatou.", "in we (incl)"]]},
  {num:10,words:[["Ua silafia", "knew"], ["e le Atua", "God"], ["a latou galuega,", "but they work"], ["ina", "so that"], ["ua liliu ese", "turned away"], ["i latou", "them"], ["i lo latou ala leaga;", "than they way evil"], ["ona salamo ai lea", "and repent then then"], ["o le Atua", "of God"], ["i le malaia", "in the disaster"], ["na ia fetalaia mai", "to fetalaia from"], ["na te faia ia te", "he made unto"], ["i latou;", "them"], ["e lei faia.", "by not made"]]},
];
renderVerseSet(_jon_ch_3_Verses, 'jon-ch3-verses');

var _jon_ch_4_Verses = [
  {num:1,words:[["Ua matuā leaga lava", "exceedingly evil indeed"], ["lenei mea ia", "this thing to"], ["Iona,", "Jonah"], ["ua ita lava", "angry indeed"], ["o ia.", "he"]]},
  {num:2,words:[["Ona tatalo ai lea", "and pray then then"], ["o ia ia", "he to"], ["Ieova,", "the LORD"], ["ua faapea atu,", "and said"], ["O lenei,", "now"], ["Ieova e,", "O LORD!"], ["e le", "by the"], ["o la'u upu ea lenei", "my word indeed?/really? this"], ["ina ou", "so that I"], ["i ai", "therein"], ["i lo'u nuu?", "in my nation"], ["O le mea foi", "the thing also"], ["lea", "lea"], ["na ou muai", "I first"], ["sola ai", "escape"], ["i Tasesa;", "in Tasesa"], ["auā", "for"], ["ua ou iloa oe", "I knew you"], ["o le Atua alofa fua,", "of God love fruit"], ["ma le alofa mutimutivale,", "and the mercy"], ["e tele gese", "to great slow"], ["lou toasa,", "your wrath"], ["ua tele foi", "great also"], ["lou alofa,", "your love"], ["ua e salamo foi", "you repented also"], ["ma", "and"], ["ua", "ua"], ["le faaoo", "the bring upon"], ["le malaia.", "the disaster"]]},
  {num:3,words:[["O lenei", "now"], ["foi,", "also"], ["Ieova e,", "O LORD!"], ["ou te aioi atu", "I will cry out"], ["ia te oe,", "unto you"], ["ia", "to"], ["e ave ese", "to take away"], ["lo'u ola;", "my life"], ["auā", "for"], ["e lelei", "to good"], ["ona ou oti,", "and I die"], ["a", "but"], ["e leaga", "to evil"], ["ona ou ola.", "and I life"]]},
  {num:4,words:[["Ona fetalai mai ai lea", "and said then then"], ["o Ieova,", "the LORD"], ["Ua lelei ea", "that it was good indeed?/really?"], ["lou ita?", "your angry"]]},
  {num:5,words:[["Ona alu atu lea", "and go away"], ["o Iona ai", "Jonah"], ["le aai,", "the city"], ["ua nofo foi", "dwelt also"], ["i le itu", "on the side"], ["i sasae", "eastward"], ["o le aai,", "the city"], ["ua", "ua"], ["na faia foi", "made also"], ["mo ia", "for to"], ["i lea", "in"], ["mea", "thing"], ["le fale apitaga,", "the house a tempoiary"], ["ua nofo", "dwelt"], ["i ona lalo", "in then under"], ["i le paolo,", "in the paolo"], ["seia iloa e", "until know by"], ["ia", "to"], ["pe", "whether"], ["se a se mea", "a but a thing"], ["e oo", "it shall come to pass"], ["i le aai.", "in the city"]]},
  {num:6,words:[["Na saunia foi", "prepared also"], ["e Ieova", "the LORD"], ["le Atua", "God"], ["le kikaiona,", "the kikaiona"], ["ua", "ua"], ["na faasosolo", "made to run"], ["i ai", "therein"], ["i luga o Iona,", "upon Jonah"], ["e fai ma faapaologa", "to be captivity"], ["i luga", "in above"], ["o lona ulu,", "his head"], ["e laveai ia te ia", "to deliver to him"], ["ai", "ai"], ["lona tiga.", "his grieved"], ["Ona matuā fiafia ai lea", "and exceedingly competition then then"], ["o Iona", "Jonah"], ["ona", "and"], ["o le kikaiona.", "the kikaiona"]]},
  {num:7,words:[["Ua oo ina", "it came to pass so that"], ["malama ae", "malama up"], ["o le taeao,", "the morning"], ["ona saunia lea", "and prepared"], ["o le Atua", "of God"], ["o le anufe;", "the anufe"], ["ua atia foi", "atia also"], ["e le anufe", "by the anufe"], ["o le kikaiona,", "the kikaiona"], ["ona mago ai lea.", "and a small eel then then"]]},
  {num:8,words:[["Ua alu ae", "went up"], ["le la,", "the la"], ["ona saunia lea", "and prepared"], ["e le Atua", "God"], ["o le matagi vevela", "the wind to be hot"], ["mai sasae;", "from east"], ["ona ogotia ai lea", "and ogotia then then"], ["o le ulu", "the head"], ["o Iona", "Jonah"], ["i le la,", "in the la"], ["ona vaivai ai lea", "and weak then then"], ["o ia,", "he"], ["ma ia faatoga atu", "and to order"], ["ia oti o ia,", "to die he"], ["ua ia faapea atu,", "to thus"], ["E lelei", "to good"], ["ona ou oti,", "and I die"], ["a", "but"], ["e leaga", "to evil"], ["ona ou ola.", "and I life"]]},
  {num:9,words:[["Ona fetalai mai lea", "and said"], ["o le Atua", "of God"], ["ia Iona,", "to Jonah"], ["E lelei ea", "to good indeed?/really?"], ["lou ita", "your angry"], ["ona", "and"], ["o le kikaiona?", "the kikaiona"], ["Ona fai atu lea", "And he said"], ["o ia,", "he"], ["Ou te ita tele", "I will angry great"], ["lava,", "indeed"], ["e oo lava", "it shall come to pass indeed"], ["i le oti.", "in the die"]]},
  {num:10,words:[["Ona fetalai mai lea", "and said"], ["o Ieova,", "the LORD"], ["Ua e alofa", "you loved"], ["i le kikaiona,", "in the kikaiona"], ["o le mea", "the thing"], ["na e le", "you the"], ["galue ai,", "till"], ["pe faatupuina;", "whether raised up"], ["o le mea", "the thing"], ["na tupu", "king"], ["i le po", "in the night"], ["e tasi,", "by one"], ["na mamae foi", "mamae also"], ["i le po", "in the night"], ["e tasi.", "by one"]]},
  {num:11,words:[["O a'u foi", "I am also"], ["ou te", "I will"], ["le alofa ea", "the love indeed?/really?"], ["i Nineva", "in Nineveh"], ["le aai tele,", "the city great"], ["o loo", "is/are (progressive)"], ["i ai", "therein"], ["tagata", "man"], ["e sili", "to most"], ["ona toatele", "and many"], ["i le selau afe", "in the hundred thousand"], ["ma afe", "and thousand"], ["e lua fulu,", "by two fulu"], ["o", "o"], ["e le iloa", "shall not know"], ["o latou lima taumatau po", "they five right hand night"], ["o latou lima tauagavale;", "they five left"], ["ma manu vaefa foi", "and cattle also"], ["e tele.", "to great"]]},
];
renderVerseSet(_jon_ch_4_Verses, 'jon-ch4-verses');

})();