(function() {
var jon_ch_1_Verses = [
  {num:1,words:[["Ua oo mai le afioga a Ieova ia Iona le atalii o Amitai,", "it came to pass from the a word but Jehovah to Jonah the son amitai"], ["ua faapea mai,", "saying"]]},
  {num:2,words:[["Ina tulai ia,", "let arose up to"], ["ina alu i Nineva le aai tele,", "let go in nineva the eat great"], ["ma alaga atu i ai;", "and a shoulder or leg of aa ' therein"], ["auā ua oo mai a latou agasala i o'u luma.", "for oo from but them sin in I before"]]},
  {num:3,words:[["A ua tulai Iona e sola i Tasesa ai luma o Ieova,", "but arose up Jonah to flee in tasesa before Jehovah"], ["ua alu ifo foi o ia i Iopa,", "go also he in Job"], ["ma na maua le vaa a alu i Tasesa;", "and received the vaa but go in tasesa"], ["ona avatu ai lea e ia o le totogi,", "and give away by him the totogi"], ["ma alu ifo i ai,", "and go therein"], ["e o ma i latou i Tasesa ai luma o Ieova.", "by and them in tasesa before Jehovah"]]},
  {num:4,words:[["A ua tuuina ifo e Ieova le matagi tetele i le vasa,", "but given to Jehovah the wind great in the ocean"], ["ona afā tetele ai lea i le vasa,", "and cyclone great in the ocean"], ["se manū a lepetia le vaa.", "a manū but lepetia the vaa"]]},
  {num:5,words:[["Ona matatau ai lea o le auvaa,", "and fear the auvaa"], ["ma latou taitasi ma valaau i lona atua;", "and them each and call in his God"], ["ua latou lafo foi le oloa na i le vaa i le sami,", "them cloth used as gratuity for a talking chief also the goods in the vaa in the sea"], ["e faamāmāina ai.", "by faamāmāina"], ["A e peitai o Iona na alu ifo o ia i totonu lava o le vaa;", "but to however Jonah go he in inside indeed the vaa"], ["na taoto foi o ia,", "taoto also he"], ["ma moegase.", "and moegase"]]},
  {num:6,words:[["Ona alu atu lea o le aliivaa ia te ia,", "and go the aliivaa unto to"], ["ma fai atu ia te ia,", "and make unto to"], ["A faapefea ea oe,", "but how ? to rise (as a diver to the sur- you"], ["lē moe gase? ina tulai ia,", "not sleep gase let arose up to"], ["ina valaau i lou Atua,", "let call in your God"], ["atonu e manatu mai le Atua ia te i tatou,", "impers to thought from the God unto in us"], ["ina ia le oti i tatou.", "so that the die in us"]]},
  {num:7,words:[["Ona latou fetautalatalai lea,", "and them fetautalatalai"], ["Ina o mai ia,", "let from to"], ["se'i tatou faia le vili,", "a flower put into the hair or us made the a gimblet"], ["ina ia tatou iloa po o ai ua oo mai ai lenei malaia ia te i tatou.", "so that us known night oo from this a calamity unto in us"], ["Ona latou faia lea o le vili,", "and them made the a gimblet"], ["ua faasaga foi le vili ia Iona.", "toward also the a gimblet to Jonah"]]},
  {num:8,words:[["Ona latou fai atu ai lea ia te ia,", "and them make unto to"], ["Ina ta'u mai ia ia te i matou,", "let tell from to unto in we"], ["po o ai ua oo mai ai lenei malaia ia te i tatou? o le a ea lou faiva? o fea ea na e sau ai? o ifea ea lou nuu? o ai ea tagata na e tupu mai ai?", "night oo from this a calamity unto in us the but to rise (as a diver to the sur- your ministry fea to rise (as a diver to the sur- to come ifea to rise (as a diver to the sur- your nation to rise (as a diver to the sur- man to grow from"]]},
  {num:9,words:[["Ona fai mai ai lea o ia ia te i latou,", "and make from he unto them"], ["O a'u o le Eperu;", "I am the eperu"], ["ou te mata'u ia Ieova le Atua o le lagi,", "I ax to Jehovah the God the heaven"], ["o le na faia le sami ma le eleele matutu.", "the made the sea and the earth dry"]]},
  {num:10,words:[["Ona matuā fefefe ai lea o ia tagata,", "and very fefefe he man"], ["ma latou faapea atu ia te ia,", "and them thus unto to"], ["Se a lenei mea ua e faia? Auā na iloa ia tagata ua sola o ia ai luma o Ieova,", "a but this thing to made for known to man flee he before Jehovah"], ["auā na ia ta'u atu ai ia te i latou.", "for to tell unto them"]]},
  {num:11,words:[["Ona latou fai atu ai lea ia te ia,", "and them make unto to"], ["Se a se mea matou te faia ia te oe,", "a but a thing we made unto you"], ["ina ia malū ai le sami mo i matou? Auā ua tuputupu pea le sousou o le vasa.", "so that malū the sea for in we for tuputupu continually the sousou the ocean"]]},
  {num:12,words:[["Ona fai mai lea o ia ia te i latou,", "And he said he unto them"], ["Ina sii ia ia te au,", "let lift up to unto I"], ["ma lafo ifo ia te au i le sami,", "and cloth used as gratuity for a talking chief unto I in the sea"], ["ona malū ai lea o le vasa ia te outou;", "and malū the ocean unto ye all"], ["auā ua ou iloa o a'u ua oo mai ai lenei afā tetele ia te outou.", "for I known I am oo from this cyclone great unto ye all"]]},
  {num:13,words:[["A ua taualo faamalosi lava o ia tagata,", "but to row or paddle faamalosi indeed he man"], ["ina ia toe oo i uta;", "so that again oo in uta"], ["a ua le mafaia e i latou,", "but the able by them"], ["auā ua tuputupu pea le sousou o le vasa sa tiga ai i latou.", "for tuputupu continually the sousou the ocean pain them"]]},
  {num:14,words:[["Ona latou valaau atu lea ia Ieova,", "and them call to Jehovah"], ["ua faapea atu,", "saying"], ["Matou te aioi atu ia te oe,", "we aioi unto you"], ["Ieova e,", "Jehovah by"], ["aua ne'i fano i matou ona o le ola o lenei tagata o le aveesea ,", "for now perish in we then the life this man the aveesea"], ["auā foi ne'i faaee i luga ia i matou le toto o le tagata e le sala;", "for also now to place upon in above to in we the blood the man by the a fine"], ["auā o oe Ieova e,", "for you Jehovah by"], ["ua e faia le mea ua e finagalo i ai.", "to made the thing to a chiefs will or desire therein"]]},
  {num:15,words:[["Ona latou sii ae lea ia Iona,", "and them lift up but to Jonah"], ["ma lafo ia te ia i le sami,", "and cloth used as gratuity for a talking chief unto to in the sea"], ["ona mavae lea o le sousou o le sami.", "and a parting the sousou the sea"]]},
  {num:16,words:[["Ona matuā matatau ai lea o ia tagata ia Ieova,", "and very fear he man to Jehovah"], ["ma latou faia le taulaga ia Ieova,", "and them made the offering to Jehovah"], ["ma latou tauto i ni tautoga.", "and them to take an oath in some tautoga"]]},
  {num:17,words:[["Na tofia e Ieova le i'a tele e foloina Iona.", "chosen to Jehovah the fish great by foloina Jonah"], ["Na i ai foi Iona i le manava o le i'a e tolu ao e tolu foi po.", "therein also Jonah in the manava the fish by three day by three also night"]]},
  {num:18,words:[["E fai foi le aiga o lakopo ma aй,", "to make also the family lakopo and aй"], ["e fai foi Ie aiga o Iosefa ma aб mumú,", "to make also faamaise family Joseph and aб mumú"], ["a e fai le aiga o Esau ma tagutugutu o saito;", "but to make the family Esau and tagutugutu wheat"], ["latou te faamu foi ia te i latou,", "them faamu also unto them"], ["ma faauma ia te i latou;", "and faauma unto them"], ["e leai foi sé toe i le aiga o Esau;", "there is not also sé again in the family Esau"], ["aua ua fetalai mai ai le Alii.", "for said from the Lord"]]},
  {num:19,words:[["O i latou foi o i le itu i toga e fai mo i latou le mauga o Esau;", "them also in the itu in Tonga to make for them the mountain Esau"], ["o i latou foi o i le itu maulalo e fai mo i latou le nuu o Filisitia;", "them also in the itu maulalo to make for them the nation Philistine"], ["e fai foi mo i latou le laueleele o Ffaraima,", "to make also for them the ground ffaraima"], ["ma le laueleele o Samaria;", "and the ground Samaria"], ["e fai foi Kiliata mo Peniamina.", "to make also kiliata for Benjamin"]]},
  {num:20,words:[["O le tafeaga foi o lenei itu taua a le fanauga a Isaraelu e ua i sa Kananā e oo i Sarefata;", "the exiles in wa^ also this itu war but the children but Israel by in kananā by oo in sarefata"], ["o le tafeaga foi o Ierusalema o i Sefarata,", "the exiles in wa^ also Jerusalem in sefarata"], ["e fai mo i latou o aai o i le itu i toga.", "to make for them eat in the itu in Tonga"]]},
  {num:21,words:[["E o ae foi faaola i le mauga o Siona,", "by but also save in the mountain Zion"], ["ina ia faasalaina le mauga o Esau;", "so that faasalaina the mountain Esau"], ["e fai foi le malo mo le ALII.", "to make also the government for the Lord"], ["O LE TUSI A LE PEROFETA O IONA Ua auina lona e le Alii", "the book but the prophet Jonah sent his by the Lord"]]},
];
renderVerseSet(jon_ch_1_Verses, 'jon-ch1-verses');

var jon_ch_2_Verses = [
  {num:1,words:[["Na tatalo foi Iona ia Ieova lona Atua i le manava o le i'a,", "pray also Jonah to Jehovah his God in the manava the fish"]]},
  {num:2,words:[["ua faapea atu,", "saying"], ["Na a'u valaau atu ia Ieova ona o lo'u puapuaga,", "I call to Jehovah then my pain"], ["ua na faafofoga mai foi ia te au;", "listen from also unto I"], ["na ou alaga atu nai le mea maulalo i tuugamau,", "I a shoulder or leg of aa ' from the thing maulalo in tuugamau"], ["ua e faafofoga i lo'u leo.", "to listen in my voice"]]},
  {num:3,words:[["Na e lafoina a'u i le moana,", "by lafoina I in the deep"], ["i totonu lava o le sami;", "in inside indeed the sea"], ["na siosioina lava a'u e le au;", "siosioina indeed I by the I"], ["na lofia a'u i ou galu ma ou peau uma lava.", "lofia I in I wave and I a wave all indeed"]]},
  {num:4,words:[["Ona ou faapea ai lea,", "and I thus"], ["Ua lafoaiina a'u ai luma o ou fofoga;", "lafoaiina I before I face"], ["a ou te toe faasaga atu i lou malumalu paia.", "but I again toward in your temple holy"]]},
  {num:5,words:[["Ua siosioina a'u e le sami,", "siosioina I by the sea"], ["na manū a'u oti;", "manū I die"], ["ua ufitia a'u i le moana,", "covered I in the deep"], ["ua fusia lo'u ulu i le limu.", "fusia my head in the seaweed"]]},
  {num:6,words:[["Ua ou alu ifo i vae mauga;", "I go in foot mountain"], ["ua faamauina faamau o le lalolagi i luga ia te au e faavavau;", "faamauina a hinge the earth in above unto I to a stone connected with"], ["a e te aveina ae lo'u ola ai le lua,", "but by aveina but my life the two"], ["Ieova e lo'u Atua.", "Jehovah to my God"]]},
  {num:7,words:[["Na ou manatua Ieova ina o vaivai o lo'u loto i totonu ia te au;", "I remember Jehovah let weak my heart in inside unto I"], ["na oo atu foi la'u tatalo ia te oe i lou malumalu paia.", "oo also my pray unto you in your temple holy"]]},
  {num:8,words:[["O e ua anaana i mea faatauvaa ma le pepelo ua lafoaiina e i latou o mea e manuia ai i latou.", "who his own in thing faatauvaa and the false lafoaiina by them thing to peace them"]]},
  {num:9,words:[["A o a'u,", "but I am"], ["ou te faitaulaga ia te oe ma le upu faafetai;", "I priest unto you and the word to tliank"], ["ou te faia le mea na ou tauto ai.", "I made the thing I to take an oath"], ["Mai ia Ieova le olataga.", "from to Jehovah the a means of deliverance"]]},
  {num:10,words:[["Ua fetalai atu Ieova i le i'a,", "said Jehovah in the fish"], ["ona luai lea e ia o Iona i le eleele matutu.", "and luai by him Jonah in the earth dry"]]},
];
renderVerseSet(jon_ch_2_Verses, 'jon-ch2-verses');

var jon_ch_3_Verses = [
  {num:1,words:[["Ona oo mai lea o le afioga a Ieova ia Iona,", "and oo from the a word but Jehovah to Jonah"], ["o le foi faalua mai lea,", "the also faalua from"], ["ua faapea mai,", "saying"]]},
  {num:2,words:[["Ina tulai ia,", "let arose up to"], ["ina alu i Nineva le aai tele,", "let go in nineva the eat great"], ["ma tala'i atu i ai le tala'iga ou te fai atu ai ia te oe.", "and preach therein the tala'iga I make unto you"]]},
  {num:3,words:[["Ona tulai ai lea o Iona,", "and arose up Jonah"], ["ua alu i Nineva,", "go in nineva"], ["e faapei ona fetalai mai o Ieova.", "to like then said from Jehovah"], ["O le aai matuā tele lava Nineva,", "the eat very great indeed nineva"], ["e tusa ma le savaliga o aso e tolu.", "to according to and the savaliga day by three"]]},
  {num:4,words:[["Ua amata ona ulu atu o Iona i le aai,", "began then head Jonah in the eat"], ["o le savaliga o le aso e tasi,", "the savaliga the day by one"], ["na alaga foi o ia,", "a shoulder or leg of aa ' also he"], ["ua faapea atu,", "saying"], ["E toe fagafulu po ona faaumatia lea o Nineva.", "to again fagafulu night then destroy nineva"]]},
  {num:5,words:[["Ona talitonu ai lea o tagata o Nineva i le Atua,", "and believe man nineva in the God"], ["ua tala'i atu foi e i latou la latou anapogi,", "preach also by them their to fast"], ["ua latou oofu foi i le ie talatala,", "them oofu also in the faamaise to untie"], ["o alii atoa ma tagatānuu.", "Lord together with and tagatānuu"]]},
  {num:6,words:[["Auā ua oo le tala i le tupu o Nineva,", "for oo the side in the grow nineva"], ["ona tulai ai lea o ia i lona nofoālii,", "and arose up he in his nofoālii"], ["ma tuu ese ia te ia lona ofu tele,", "and put away unto to his garment great"], ["ona ufutia lea o ia e ia i le ie talatala,", "and ufutia he by him in the faamaise to untie"], ["ma nofo i le lefulefu.", "and dwell in the lefulefu"]]},
  {num:7,words:[["Ua ia tala'i atu,", "to preach"], ["ma faailo atu i Nineva i le pule a le tupu ma alii sa ia te ia,", "and faailo in nineva in the rule but the grow and Lord unto to"], ["ua faapea atu,", "saying"], ["Aua ne'i 'ai sina mea e tagata,", "for now eat white thing to man"], ["po o manu,", "night animal"], ["po o lafu povi,", "night a herd cattle"], ["po o lafu mamoe;", "night a herd sheep"], ["aua lava ne'i latou aai,", "for indeed now them eat"], ["aua foi latou te inu vai;", "for also them drink water"]]},
  {num:8,words:[["a ia ufitia lava tagata ma manu i ie talatala,", "but to covered indeed man and animal in faamaise to untie"], ["ma ia latou matuā alalaga atu i le Atua;", "and to them very alalaga in the God"], ["ia latou taitasi foi ma liliu mai i lana amioga leaga,", "to them each also and turned from in his amioga evil"], ["ma le faasaua ua i o latou lima.", "and the to be oppressive in them five"]]},
  {num:9,words:[["O ai se na te iloa,", "a known"], ["atonu e liliu mai le Atua,", "impers to turned from the God"], ["ma salamo,", "and repent"], ["ma liliu ese i lona toasa mamafa,", "and turned away in his wrath mamafa"], ["ina ia le fano ai i tatou.", "so that the perish in us"]]},
  {num:10,words:[["Ua silafia e le Atua a latou galuega,", "seen by the God but them work"], ["ina ua liliu ese i latou i lo latou ala leaga;", "let turned away them in the them arise evil"], ["ona salamo ai lea o le Atua i le malaia na ia fetalaia mai na te faia ia te i latou;", "and repent the God in the a calamity to fetalaia from made unto them"], ["e lei faia.", "to whale's teeth made"]]},
];
renderVerseSet(jon_ch_3_Verses, 'jon-ch3-verses');

var jon_ch_4_Verses = [
  {num:1,words:[["Ua matuā leaga lava lenei mea ia Iona,", "very evil indeed this thing to Jonah"], ["ua ita lava o ia.", "angry indeed he"]]},
  {num:2,words:[["Ona tatalo ai lea o ia ia Ieova,", "and pray he to Jehovah"], ["ua faapea atu,", "saying"], ["O lenei,", "this"], ["Ieova e,", "Jehovah by"], ["e le o la'u upu ea lenei ina ou i ai i lo'u nuu? O le mea foi lea na ou muai sola ai i Tasesa;", "by the my word to rise (as a diver to the sur- this let I therein in my nation the thing also I first flee in tasesa"], ["auā ua ou iloa oe o le Atua alofa fua,", "for I known you the God love fruit"], ["ma le alofa mutimutivale,", "and the love to be distressed in"], ["e tele gese lou toasa,", "to great slow your wrath"], ["ua tele foi lou alofa,", "great also your love"], ["ua e salamo foi ma ua le faaoo le malaia.", "to repent also and the faaoo the a calamity"]]},
  {num:3,words:[["O lenei foi,", "this also"], ["Ieova e,", "Jehovah by"], ["ou te aioi atu ia te oe,", "I aioi unto you"], ["ia e ave ese lo'u ola;", "to to take away my life"], ["auā e lelei ona ou oti,", "for to good then I die"], ["a e leaga ona ou ola.", "but to evil then I life"]]},
  {num:4,words:[["Ona fetalai mai ai lea o Ieova,", "and said from Jehovah"], ["Ua lelei ea lou ita?", "that it was good to rise (as a diver to the sur- your angry"]]},
  {num:5,words:[["Ona alu atu lea o Iona ai le aai,", "and go Jonah the eat"], ["ua nofo foi i le itu i sasae o le aai,", "dwell also in the itu in to tear the eat"], ["ua na faia foi mo ia i lea mea le fale apitaga,", "made also for to in thing the house a tempoiary"], ["ua nofo i ona lalo i le paolo,", "dwell in then under in the paolo"], ["seia iloa e ia pe se a se mea e oo i le aai.", "until known by him or a but a thing by oo in the eat"]]},
  {num:6,words:[["Na saunia foi e Ieova le Atua le kikaiona,", "prepared also to Jehovah the God the kikaiona"], ["ua na faasosolo i ai i luga o Iona,", "faasosolo therein in above Jonah"], ["e fai ma faapaologa i luga o lona ulu,", "to be faapaologa in above his head"], ["e laveai ia te ia ai lona tiga.", "to deliver unto to his pain"], ["Ona matuā fiafia ai lea o Iona ona o le kikaiona.", "and very competition Jonah then the kikaiona"]]},
  {num:7,words:[["Ua oo ina malama ae o le taeao,", "it came to pass let malama but the morning"], ["ona saunia lea o le Atua o le anufe;", "and prepared the God the anufe"], ["ua atia foi e le anufe o le kikaiona,", "atia also by the anufe the kikaiona"], ["ona mago ai lea.", "and a small eel"]]},
  {num:8,words:[["Ua alu ae le la,", "go but the la"], ["ona saunia lea e le Atua o le matagi vevela mai sasae;", "and prepared by the God the wind to be hot from to tear"], ["ona ogotia ai lea o le ulu o Iona i le la,", "and ogotia the head Jonah in the la"], ["ona vaivai ai lea o ia,", "and weak he"], ["ma ia faatoga atu ia oti o ia,", "and to to bog to die he"], ["ua ia faapea atu,", "to thus"], ["E lelei ona ou oti,", "to good then I die"], ["a e leaga ona ou ola.", "but to evil then I life"]]},
  {num:9,words:[["Ona fetalai mai lea o le Atua ia Iona,", "And God said to Jonah"], ["E lelei ea lou ita ona o le kikaiona? Ona fai atu lea o ia,", "to good to rise (as a diver to the sur- your angry then the kikaiona then make he"], ["Ou te ita tele lava,", "I angry great indeed"], ["e oo lava i le oti.", "it shall come to pass indeed in the die"]]},
  {num:10,words:[["Ona fetalai mai lea o Ieova,", "and said from Jehovah"], ["Ua e alofa i le kikaiona,", "to love in the kikaiona"], ["o le mea na e le galue ai,", "the thing by the work"], ["pe faatupuina;", "or faatupuina"], ["o le mea na tupu i le po e tasi,", "the thing grow in the night by one"], ["na mamae foi i le po e tasi.", "mamae also in the night by one"]]},
  {num:11,words:[["O a'u foi ou te le alofa ea i Nineva le aai tele,", "I am also I the love to rise (as a diver to the sur- in nineva the eat great"], ["o loo i ai tagata e sili ona toatele i le selau afe ma afe e lua fulu,", "therein man to most then many in the hundred thousand and thousand by two fulu"], ["o e le iloa o latou lima taumatau po o latou lima tauagavale;", "who the known them five right hand night them five tauagavale"], ["ma manu vaefa foi e tele.", "and animal four-footed also to great"]]},
];
renderVerseSet(jon_ch_4_Verses, 'jon-ch4-verses');

})();