(function() {
var _jud_ch_1_Verses = [
  {num:1,words:[["O aʻu", "I am"], ["o Iuta,", "Judas"], ["o le auauna", "the servant"], ["a Iesu Keriso,", "of Jesus Christ"], ["o le uso foi", "the brother also"], ["o Iakopo,", "Jacob"], ["o la'u tusi lenei", "this letter"], ["i", "in"], ["e ua fa'apaiaina", "consecrated"], ["e le Atua", "God"], ["le Tamā,", "the father"], ["ma leoleoina", "and guarded"], ["e Iesu Keriso", "Jesus Christ"], ["ma valaauina.", "and called"]]},
  {num:2,words:[["Ia fa'ateleina ia te outou", "he multiplied unto you all"], ["le alofa,", "not love"], ["ma le manuia,", "and peace"], ["ma le agalelei.", "with kindness"]]},
  {num:3,words:[["Le aʻu pele e,", "the beloved"], ["o loo ou mātua", "is I great"], ["fa'amalosi", "be strong"], ["e tusi atu", "book"], ["ia te outou", "unto you all"], ["i le fa'aolataga", "in the salvation"], ["ua tuu tele,", "put great"], ["e tatau ai", "it is fitting"], ["lava ona", "just/enough to"], ["ou tusi atu", "I book"], ["ia te outou", "unto you all"], ["ia apoapoai atu ia outou", "he exhort he you all"], ["fa'amalolosi", "strengthen"], ["ona finau", "and contend"], ["mo le fa'atuatua", "for the faith"], ["na tuuina mai", "given from"], ["fa'atasi", "together"], ["i le aʻu paia.", "in the saints"]]},
  {num:4,words:[["Auā", "do not"], ["ua o ane", "went"], ["fa'aleiloga o isi tagata,", "faaleiloga of other man"], ["ua leva foi", "the name of a tree also"], ["ona muai tusia", "and first written"], ["o", "o"], ["i lātou ia", "them he"], ["oo", "oo"], ["i lenei", "in this"], ["lava fa'asala,", "very judgment"], ["e fa'alematau", "by faalematau"], ["i lātou,", "them"], ["ua liua e", "turned you"], ["i lātou", "them"], ["le alofa tunoa", "grace"], ["o lo tātou Atua", "our God"], ["i le fa'amatāitu,", "in the faamatāitu"], ["ma", "and"], ["ua lātou fa'afiti", "they denied"], ["i le Ali'i e", "in the Lord"], ["tasi,", "one"], ["o le Atua,", "of God"], ["ma lo tātou Ali'i", "and the we Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
  {num:5,words:[["Ou te fia fa'amanatu atu foi", "I will want to do something remind also"], ["ia te outou", "unto you all"], ["i le mea", "in the thing"], ["na outou iloa", "you all knew"], ["anamua,", "ancient"], ["na fa'aolaina", "saved"], ["e le Ali'i", "by the Lord"], ["le nuu ai", "the nation"], ["le nuu o Aikupito,", "the nation of Egypt"], ["a", "but"], ["e mulimuli ane", "follow after"], ["ua fa'aumatia e", "are destroyed by"], ["ia", "he"], ["o", "o"], ["e", "by"], ["na", "na"], ["le fa'atuatua.", "the faith"]]},
  {num:6,words:[["O agelu foi", "angel also"], ["o", "o"], ["e", "by"], ["na", "na"], ["le taofi", "the hold"], ["i lo lātou mamalu,", "than they glory"], ["a", "but"], ["ua tuua e", "left you"], ["i lātou", "them"], ["le mea", "the thing"], ["sa lātou nofo ai,", "they dwelt"], ["ua taofia e", "held back you"], ["ia", "he"], ["i noanoataga", "in bond"], ["e fa'avavau", "forever/everlasting"], ["i lalo", "in under"], ["o le pogisa,", "the darkness"], ["seia oo", "until oo"], ["i le fa'amasinoga", "in the judgments"], ["o le aso tele.", "the day great"]]},
  {num:7,words:[["E pei o Sotoma", "like Sodom"], ["ma Komoro,", "and Gomorrah"], ["ma aai", "and cities"], ["sa vagavagai ai,", "surround"], ["ua faitaaga pei", "fornication like"], ["o", "o"], ["i lātou,", "them"], ["ma mulimuli atu", "and follow after"], ["i nisi tino,", "in some body"], ["o lea", "therefore"], ["ua tuu mai ai", "placed"], ["i lātou", "them"], ["e fai ma fa'ailoga,", "to be signs"], ["ua fa'asalaina", "punished"], ["i lātou", "them"], ["i le afi", "in the fire"], ["e fa'avavau.", "forever/everlasting"]]},
  {num:8,words:[["E fa'apea foi", "so it is also"], ["lava o ia", "very it"], ["tagata moemiti,", "man moemiti"], ["lātou te fa'aleaga", "they will abuse"], ["le tino,", "the body"], ["ma lātou ta'ufaatauvaa", "and they ta'ufaatauvaa"], ["i ali'i,", "in Lord"], ["ma 'upu leaga", "and word evil"], ["i", "in"], ["e ua mamalu.", "glory"]]},
  {num:9,words:[["A o Mekaeli", "but Mekaeli"], ["o le agelu silisili,", "the angel very much"], ["ina ua lā finau", "when sun contend"], ["ma le tiapolo", "and the devil"], ["na ia finau", "he contended"], ["i le tino", "in the body"], ["o Mose,", "Moses"], ["ua", "ua"], ["na", "na"], ["le fa'amalosi", "the be strong"], ["ona lafo atu", "and cloth used as gratuity for a talking chief"], ["o se 'upu leaga", "a word evil"], ["e fa'asala ia te ia", "judgment to him"], ["a", "but"], ["ua", "ua"], ["na fa'apea atu,", "saying"], ["Ia aoai", "he chastise"], ["le Ali'i ia te oe.", "the Lord unto you"]]},
  {num:10,words:[["A o ia", "but it"], ["tagata,", "man"], ["lātou te 'upu leaga", "they will word evil"], ["i mea lātou te", "things they will"], ["le iloa,", "not know"], ["o mea foi", "thing also"], ["e iloa fua", "know fruit"], ["e", "by"], ["i lātou,", "them"], ["e pei o mea ola", "like thing life"], ["e leai se mafaufau,", "there is no think"], ["lātou te fa'aleaga", "they will abuse"], ["ia te i lātou", "unto them"], ["i ia lava mea.", "in he very thing"]]},
  {num:11,words:[["Oi talofa ia te", "wo unto"], ["i lātou!", "them"], ["auā", "for"], ["ua lātou savavali", "they walked"], ["i le ala", "in the way"], ["o Kaino,", "Cain"], ["ma feosofi atu", "and rushed upon"], ["i le sese", "in the wrong"], ["o Palaamo", "Balaam"], ["ona", "and"], ["o le totogi,", "the wages"], ["ua fano foi", "perished also"], ["i lātou", "them"], ["i le fouvale", "in the rebel"], ["o Koru.", "Koru"]]},
  {num:12,words:[["O papa", "rock"], ["i lātou", "them"], ["i o outou", "in of you all"], ["faigaai alofa,", "faigaai love"], ["pe a lātou", "even though / although they"], ["aai fa'atasi ma outou", "cities together with you"], ["ma le", "and the"], ["le mata'u,", "not afraid"], ["ua", "ua"], ["na", "na"], ["ona aai lava", "and cities very"], ["i lātou;", "them"], ["o ao", "day"], ["i lātou", "them"], ["e le o", "by the of"], ["i ai", "therein"], ["se vai,", "a water"], ["ua feleleaiina", "flew one another"], ["i matagi;", "in wind"], ["o lā'aʻu", "tree"], ["ua malili o", "the name of a tree of"], ["lātou", "they"], ["lau,", "your"], ["ua", "ua"], ["le fua,", "the fruit"], ["ua mate fa'alua,", "mate twice"], ["ua liaiina lava;", "liaiina very"]]},
  {num:13,words:[["o peau sousou", "a wave sousou"], ["o le sami,", "Sea"], ["ua fa'apunaia ae", "made was spring of water up"], ["mea", "thing"], ["e masiasi ai", "be ashamied"], ["i lātou;", "them"], ["o fetu feoai", "star walk about"], ["ua tuu", "put"], ["mo", "for"], ["i lātou", "them"], ["le pogisa", "the darkness"], ["o le pouliuli", "the darkness"], ["e fa'avavau.", "forever/everlasting"]]},
  {num:14,words:[["Na valoia foi", "esteemed also"], ["i lātou", "them"], ["e Enoka,", "Enoch"], ["o le toafitu lea", "the seven people"], ["talu mai ia", "since from he"], ["Atamu,", "Adam"], ["ua fa'apea ane,", "saying"], ["Fa'auta,", "behold"], ["e afio mai le Ali'i", "dwell from the Lord"], ["ma", "and"], ["ona aʻu paia", "and saints"], ["e manomano,", "ten thousand"]]},
  {num:15,words:[["e fa'amasino ai", "judge"], ["i tagata uma,", "in man all"], ["ma fa'asalaina ai", "and punished"], ["e ua amio fa'alematau uma lava", "deeds faalematau all very"], ["o ia", "it/he/she"], ["i lātou,", "them"], ["ona o", "because of"], ["a lātou galuega fa'alematau uma", "their work faalematau all"], ["ua lātou faia", "they did"], ["ma le fa'alematau,", "and the faalematau"], ["ona o", "because of"], ["a lātou 'upu fa'atautala foi", "their word ill use also"], ["na fai ia te ia", "did to him"], ["e tagata agasala", "man sin"], ["ua fa'alematau.", "faalematau"]]},
  {num:16,words:[["O", "O"], ["e muimui", "murmur"], ["i lātou", "them"], ["ma fa'ameo,", "and faameo"], ["o loo o savavali", "is walked"], ["i lātou", "them"], ["e tusa ma", "according to"], ["o lātou tu'inanau,", "they tu'inanau"], ["ma", "and"], ["ua tautala mai", "spoke from"], ["o lātou gutu", "they mouth"], ["i 'upu fa'asausili,", "in word haughty"], ["o loo fa'aneenee atu foi", "is to\" praise also"], ["i lātou", "them"], ["i ali'i e", "in Lord by"], ["maua ai", "received"], ["ni mea.", "some thing"]]},
  {num:17,words:[["A o outou", "but you all"], ["le aʻu pele e,", "the beloved"], ["ia outou manatua", "he you all remember"], ["'upu", "word"], ["na fai mai", "said"], ["anamua", "ancient"], ["e le aʻu", "shall not me"], ["aposetolo", "apostle"], ["a lo tātou Ali'i", "but our Lord"], ["o Iesu Keriso;", "Jesus Christ"]]},
  {num:18,words:[["na lātou fai atu ia te outou,", "they said to unto you all"], ["E", "by"], ["i ai", "therein"], ["i ona aso", "in his days"], ["e gata ai", "a snake"], ["o tagata tauemu,", "men mock"], ["o", "o"], ["e savavali", "walked"], ["e tusa ma", "according to"], ["o lātou lava tu'inanau", "they very tu'inanau"], ["ma le fa'alematau.", "and the faalematau"]]},
  {num:19,words:[["O tagata lava", "men very"], ["ia", "he"], ["ua lātou vavae ese,", "they divided away"], ["ua amio fa'aletino,", "deeds bodily"], ["ua", "ua"], ["le", "the"], ["i ai", "therein"], ["le Agaga.", "the spirit"]]},
  {num:20,words:[["A o outou", "but you all"], ["le aʻu pele e,", "the beloved"], ["ia outou ati", "he you all pull up"], ["ae ia te outou", "but unto you all"], ["i lo", "than"], ["outou fa'atuatua", "you all faith"], ["e silisili", "very much"], ["ona paia,", "and holy"], ["o le Agaga Paia tou te tatalo ai,", "the Holy Spirit second person plural pray"]]},
  {num:21,words:[["ia outou fa'atumau ia te outou", "he you all make enduring unto you all"], ["i le alofa", "in the love"], ["o le Atua,", "of God"], ["ma fa'atalitali atu", "and waited"], ["i le alofa", "in the love"], ["o lo tātou Ali'i", "our Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["e oo atu", "it shall come to pass"], ["i le ola", "in the life"], ["e fa'avavau.", "forever/everlasting"]]},
  {num:22,words:[["Ia outou alofa atu i", "he you all love in"], ["nisi", "some"], ["ma ia fa'atatau;", "and he liken"]]},
  {num:23,words:[["a o isi", "but other"], ["ia outou fa'aola ia i lātou", "he you all save he them"], ["ma le mata'u,", "and the afraid"], ["ia se'i ia te i lātou", "he a flower put into the hair or unto them"], ["mai le afi,", "from the fire"], ["ma ia outou", "and he you all"], ["'ino'ino", "disdained"], ["i le ofu", "in the garment"], ["ua pisia", "pisia"], ["i le tino.", "in the body"]]},
  {num:24,words:[["O lenei,", "now"], ["ia ia te ia", "to him he"], ["na te mafaia", "he able"], ["ona leoleo ia te outou", "and guard unto you all"], ["ina ne'i pauu,", "so that now fell"], ["ma tuuina atu", "and given / delivered"], ["ia te outou", "unto you all"], ["ua", "ua"], ["le ponā", "the ponā"], ["i luma", "in before"], ["o lona lava mamalu", "his very glory"], ["ma le fiafia tele,", "and the pleased great"]]},
  {num:25,words:[["ia", "he"], ["i le Atua poto", "in the God wise"], ["e toatasi", "one"], ["o lo tātou Fa'aola,", "our save"], ["le viiga", "the praise"], ["ma le mamalu,", "and the glory"], ["o le malosi", "the strong"], ["ma le pule,", "and the rule"], ["i nei", "in these"], ["ona po,", "and night"], ["ma ia oo", "and he oo"], ["i le fa'avavau lava.", "in the everlasting very"], ["Amene.", "amen"]]},
];
renderVerseSet(_jud_ch_1_Verses, 'jud-ch1-verses');

})();