(function() {
var _jud_ch_1_Verses = [
  {num:1,words:[["O a'u", "I am"], ["o Iuta,", "Judas"], ["o le auauna", "the servant"], ["a Iesu Keriso,", "of Jesus Christ"], ["o le uso foi", "the brother also"], ["o Iakopo,", "Jacob"], ["o la'u tusi lenei", "this letter"], ["i", "in"], ["e ua faapaiaina", "by consecrated"], ["e le Atua", "God"], ["le Tamā,", "the father"], ["ma leoleoina", "and guarded"], ["e Iesu Keriso", "to Jesus Christ"], ["ma valaauina.", "and called"]]},
  {num:2,words:[["Ia faateleina ia te outou", "to multiplied unto you"], ["le alofa,", "the love"], ["ma le manuia,", "and peace"], ["ma le agalelei.", "and the treated well"]]},
  {num:3,words:[["Le au pele e,", "the I dear by"], ["o loo ou matua faamalosi", "I great be strong"], ["e tusi atu", "to book"], ["ia te outou", "unto you"], ["i le faaolataga", "in the salvation"], ["ua tuu tele,", "put great"], ["e tatau ai", "it is fitting"], ["lava ona", "indeed then"], ["ou tusi atu", "I book"], ["ia te outou", "unto you"], ["ia apoapoai atu", "to exhort"], ["ia outou faamalolosi", "to you (all) strengthen"], ["ona finau", "and contend"], ["mo le faatuatua", "for the faith"], ["na tuuina mai", "given from"], ["faatasi", "together"], ["i le au paia.", "in the saints"]]},
  {num:4,words:[["Auā", "for"], ["ua o ane", "of"], ["faaleiloga o isi tagata,", "faaleiloga of other man"], ["ua leva foi", "the name of a tree also"], ["ona muai tusia", "and first written"], ["o", "o"], ["i latou ia", "them to"], ["oo", "oo"], ["i lenei", "in this"], ["lava faasala,", "indeed to fine"], ["e faalematau", "by faalematau"], ["i latou,", "them"], ["ua liua e", "turned into by"], ["i latou", "them"], ["le alofa tunoa", "grace"], ["o lo tatou Atua", "our God"], ["i le faamatāitu,", "in the faamatāitu"], ["ma", "and"], ["ua latou faafiti", "they denied"], ["i le Alii e", "in the Lord by"], ["tasi,", "one"], ["o le Atua,", "of God"], ["ma lo tatou Alii", "and the we (incl) Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
  {num:5,words:[["Ou te fia faamanatu atu foi", "I will want to do something to remind also"], ["ia te outou", "unto you"], ["i le mea", "in the thing"], ["na outou iloa", "you (all) knew"], ["anamua,", "ancient"], ["na faaolaina", "saved alive"], ["e le Alii", "by the Lord"], ["le nuu ai", "the nation"], ["le nuu o Aikupito,", "the nation of Egypt"], ["a", "but"], ["e mulimuli ane", "to follow after"], ["ua faaumatia e", "destroyed by"], ["ia", "to"], ["o", "o"], ["e", "by"], ["na", "na"], ["le faatuatua.", "the faith"]]},
  {num:6,words:[["O agelu foi", "angel also"], ["o", "o"], ["e", "by"], ["na", "na"], ["le taofi", "the hold"], ["i lo latou mamalu,", "in the they glory"], ["a", "but"], ["ua tuua e", "left by"], ["i latou", "them"], ["le mea", "the thing"], ["sa latou nofo ai,", "they dwelt"], ["ua taofia e", "held back by"], ["ia", "to"], ["i noanoataga", "in noanoataga"], ["e faavavau", "forever/everlasting"], ["i lalo", "in under"], ["o le pogisa,", "the darkness"], ["seia oo", "until oo"], ["i le faamasinoga", "in the judgment"], ["o le aso tele.", "the day great"]]},
  {num:7,words:[["E pei o Sotoma", "to like of Sodom"], ["ma Komoro,", "and Gomorrah"], ["ma aai", "and city"], ["sa vagavagai ai,", "to surround"], ["ua faitaaga pei", "fornication like"], ["o", "o"], ["i latou,", "them"], ["ma mulimuli atu", "and follow after"], ["i nisi tino,", "in some body"], ["o lea", "therefore"], ["ua tuu mai ai", "placed"], ["i latou", "them"], ["e fai ma faailoga,", "to be sign"], ["ua faasalaina", "punished"], ["i latou", "them"], ["i le afi", "in the fire"], ["e faavavau.", "forever/everlasting"]]},
  {num:8,words:[["E faapea foi", "saying also"], ["lava o ia", "indeed he"], ["tagata moemiti,", "man moemiti"], ["latou te faaleaga", "they will to abuse"], ["le tino,", "the body"], ["ma latou ta'ufaatauvaa", "and they ta'ufaatauvaa"], ["i alii,", "in Lord"], ["ma upu leaga", "and word evil"], ["i", "in"], ["e ua mamalu.", "by glory"]]},
  {num:9,words:[["A o Mekaeli", "but of Mekaeli"], ["o le agelu silisili,", "the angel very much"], ["ina", "so that"], ["ua la finau", "la contend"], ["ma le tiapolo", "and the devil"], ["na ia finau", "to contended"], ["i le tino", "in the body"], ["o Mose,", "Moses"], ["ua", "ua"], ["na", "na"], ["le faamalosi", "the be strong"], ["ona lafo atu", "and cloth used as gratuity for a talking chief"], ["o se upu leaga", "a word evil"], ["e faasala ia te ia", "to to fine to him"], [",", ","], ["a", "but"], ["ua", "ua"], ["na faapea atu,", "saying"], ["Ia aoai", "to chastise"], ["le Alii ia te oe.", "the Lord unto you"]]},
  {num:10,words:[["A o ia", "but he"], ["tagata,", "man"], ["latou te upu leaga", "they will word evil"], ["i mea latou te", "in thing they will"], ["le iloa,", "the know"], ["o mea foi", "thing also"], ["e iloa fua", "to know fruit"], ["e", "by"], ["i latou,", "them"], ["e pei o mea ola", "to like of thing life"], ["e leai se mafaufau,", "there is no think"], ["latou te faaleaga", "they will to abuse"], ["ia te", "unto"], ["i latou", "them"], ["i ia lava mea.", "in to indeed thing"]]},
  {num:11,words:[["Oi talofa ia te", "wo unto"], ["i latou!", "them"], ["auā", "for"], ["ua latou savavali", "they walked"], ["i le ala", "in the way"], ["o Kaino,", "Cain"], ["ma feosofi atu", "and feosofi"], ["i le sese", "in the wrong"], ["o Palaamo", "Balaam"], ["ona", "and"], ["o le totogi,", "the wages"], ["ua fano foi", "perished also"], ["i latou", "them"], ["i le fouvale", "in the to rebel"], ["o Koru.", "Koru"]]},
  {num:12,words:[["O papa", "rock"], ["i latou", "them"], ["i o outou", "in of you (all)"], ["faigaai alofa,", "faigaai love"], ["pe a latou", "even though / although they"], ["aai faatasi ma outou", "city together with you"], ["ma le", "and the"], ["le mata'u,", "the ax"], ["ua", "ua"], ["na", "na"], ["ona aai lava", "and city indeed"], ["i latou;", "them"], ["o ao", "day"], ["i latou", "them"], ["e le o", "by the of"], ["i ai", "therein"], ["se vai,", "a water"], ["ua feleleaiina", "flew one another"], ["i matagi;", "in wind"], ["o laau", "tree"], ["ua malili o", "the name of a tree of"], ["latou", "they"], ["lau,", "your"], ["ua", "ua"], ["le fua,", "the fruit"], ["ua mate faalua,", "mate twice"], ["ua liaiina lava;", "liaiina indeed"]]},
  {num:13,words:[["o peau sousou", "a wave sousou"], ["o le sami,", "Sea"], ["ua faapunaia ae", "faapunaia up"], ["mea", "thing"], ["e masiasi ai", "to to be ashamied"], ["i latou;", "them"], ["o fetu feoai", "star walk about"], ["ua tuu", "put"], ["mo", "for"], ["i latou", "them"], ["le pogisa", "the darkness"], ["o le pouliuli", "the darkness"], ["e faavavau.", "forever/everlasting"]]},
  {num:14,words:[["Na valoia foi", "valoia also"], ["i latou", "them"], ["e Enoka,", "to Enoch"], ["o le toafitu lea", "the seven (people)"], ["talu mai ia", "since from to"], ["Atamu,", "Adam"], ["ua faapea ane,", "saying"], ["Faauta,", "behold"], ["e afio mai le Alii", "to dwell (respectful) from the Lord"], ["ma", "and"], ["ona au paia", "and saints"], ["e manomano,", "by manomano"]]},
  {num:15,words:[["e faamasino ai", "to judge"], ["i tagata uma,", "in man all"], ["ma faasalaina ai", "and punished"], ["e ua amio faalematau uma lava", "by conduct faalematau all indeed"], ["o ia", "he"], ["i latou,", "them"], ["ona o", "because of"], ["a latou galuega faalematau uma", "but they work faalematau all"], ["ua latou faia", "they did"], ["ma le faalematau,", "and the faalematau"], ["ona o", "because of"], ["a latou upu faatautala foi", "but they word to ill use also"], ["na fai ia te ia", "made to him"], ["e tagata agasala", "to man sin"], ["ua faalematau.", "faalematau"]]},
  {num:16,words:[["O", "O"], ["e muimui", "to to murmur"], ["i latou", "them"], ["ma faameo,", "and faameo"], ["o loo o savavali", "of walked"], ["i latou", "them"], ["e tusa ma", "according to"], ["o latou tu'inanau,", "they tu'inanau"], ["ma", "and"], ["ua tautala mai", "spoke from"], ["o latou gutu", "they mouth"], ["i upu faasausili,", "in word haughty"], ["o loo faaneenee atu foi", "to\" praise also"], ["i latou", "them"], ["i alii e", "in Lord by"], ["maua ai", "received"], ["ni mea.", "some thing"]]},
  {num:17,words:[["A o outou", "but of you (all)"], ["le au pele e,", "the I dear by"], ["ia outou manatua upu", "to you (all) remember word"], ["na fai mai", "said"], ["anamua", "ancient"], ["e le au", "by the I"], ["aposetolo", "apostle"], ["a lo tatou Alii", "but our Lord"], ["o Iesu Keriso;", "Jesus Christ"]]},
  {num:18,words:[["na latou fai atu", "they said to"], ["ia te outou,", "unto you"], ["E", "by"], ["i ai", "therein"], ["i ona aso", "in then day"], ["e gata ai", "to a snake"], ["o tagata tauemu,", "of men mock"], ["o", "o"], ["e savavali", "to walked"], ["e tusa ma", "according to"], ["o latou lava tu'inanau", "they indeed tu'inanau"], ["ma le faalematau.", "and the faalematau"]]},
  {num:19,words:[["O tagata lava", "of men indeed"], ["ia", "to"], ["ua latou vavae ese,", "they to divide away"], ["ua amio faaletino,", "conduct bodily the flesh"], ["ua", "ua"], ["le", "the"], ["i ai", "therein"], ["le Agaga.", "the spirit"]]},
  {num:20,words:[["A o outou", "but of you (all)"], ["le au pele e,", "the I dear by"], ["ia outou ati", "to you (all) to pull up"], ["ae ia te outou", "but unto you"], ["i lo outou faatuatua", "in the you (all) faith"], ["e silisili", "to very much"], ["ona paia,", "and holy"], ["o le Agaga Paia tou te tatalo ai,", "the Holy Spirit second person plural pray"]]},
  {num:21,words:[["ia outou faatumau", "to you (all) make enduring"], ["ia te outou", "unto you"], ["i le alofa", "in the love"], ["o le Atua,", "of God"], ["ma faatalitali atu", "and waited"], ["i le alofa", "in the love"], ["o lo tatou Alii", "our Lord"], ["o Iesu Keriso,", "Jesus Christ"], ["e oo atu", "it shall come to pass"], ["i le ola", "in the life"], ["e faavavau.", "forever/everlasting"]]},
  {num:22,words:[["Ia outou alofa atu", "to you (all) love"], ["i nisi", "in some"], ["ma ia faatatau;", "and to liken"]]},
  {num:23,words:[["a o isi", "but of other"], ["ia outou faaola", "to you (all) save"], ["ia", "to"], ["i latou", "them"], ["ma le mata'u,", "and the ax"], ["ia se'i ia te", "to a flower put into the hair or unto"], ["i latou mai le afi,", "them from the fire"], ["ma ia outou", "and to you (all)"], ["'ino'ino", "hate"], ["i le ofu", "in the garment"], ["ua pisia", "pisia"], ["i le tino.", "in the body"]]},
  {num:24,words:[["O lenei,", "now"], ["ia ia te ia", "to him to"], ["na te mafaia", "he able"], ["ona leoleo ia te outou", "and guard unto you"], ["ina ne'i pauu,", "so that now fell"], ["ma tuuina atu", "and given / delivered"], ["ia te outou", "unto you"], ["ua", "ua"], ["le ponā", "the ponā"], ["i luma", "in before"], ["o lona lava mamalu", "his indeed glory"], ["ma le fiafia tele,", "and the competition great"]]},
  {num:25,words:[["ia", "to"], ["i le Atua poto", "in the God wise"], ["e toatasi", "to one One"], ["o lo tatou Faaola,", "our save"], ["le viiga", "the praise"], ["ma le mamalu,", "and the glory"], ["o le malosi", "the strong"], ["ma le pule,", "and the rule"], ["i nei", "in this"], ["ona po,", "and night"], ["ma ia oo", "and to oo"], ["i le faavavau lava.", "in the everlasting indeed"], ["Amene.", "amen"]]},
];
renderVerseSet(_jud_ch_1_Verses, 'jud-ch1-verses');

})();