(function() {
var jud_ch_1_Verses = [
  {num:1,words:[["O a'u", "I am"], ["o Iuta,", "Judas"], ["o le auauna", "the servant"], ["a Iesu Keriso,", "of Jesus Christ"], ["o le uso foi o Iakopo,", "the a relative of the same generation and gender also James"], ["o la'u tusi lenei", "this letter"], ["i e", "in by"], ["ua faapaiaina", "faapaiaina"], ["e le Atua", "by God"], ["le Tamā,", "the father"], ["ma leoleoina", "and leoleoina"], ["e Iesu Keriso", "to Jesus Christ"], ["ma valaauina.", "and called"]]},
  {num:2,words:[["Ia faateleina ia te outou", "to faateleina unto you"], ["le alofa,", "the love"], ["ma le manuia,", "and peace"], ["ma le agalelei.", "and the goodness"]]},
  {num:3,words:[["Le au pele", "the I dear"], ["e,", "by"], ["o loo ou matua faamalosi", "I very faamalosi"], ["e tusi atu ia te outou", "to book unto you"], ["i le faaolataga", "in the faaolataga"], ["ua tuu tele,", "put great"], ["e tatau ai lava ona", "it is fitting indeed then"], ["ou tusi atu ia te outou", "I book unto you"], ["ia apoapoai atu ia", "to apoapoai to"], ["outou faamalolosi", "you (all) faamalolosi"], ["ona finau", "and finau"], ["mo le faatuatua", "for the faith"], ["na tuuina mai faatasi", "given from once"], ["i le au paia.", "in the saints"]]},
  {num:4,words:[["Auā ua o ane faaleiloga", "for faaleiloga"], ["o isi tagata,", "other man"], ["ua leva foi", "the name of a tree also"], ["ona muai tusia o", "and first written"], ["i latou ia oo", "them to oo"], ["i lenei lava faasala,", "in this indeed to fine"], ["e faalematau", "by faalematau"], ["i latou,", "them"], ["ua liua e", "wide (as a canoe of too by"], ["i latou", "them"], ["le alofa tunoa", "grace"], ["o lo tatou Atua", "our God"], ["i le faamatāitu,", "in the faamatāitu"], ["ma ua latou faafiti", "and they to deny"], ["i le Alii e", "in the Lord by"], ["tasi,", "one"], ["o le Atua,", "of God"], ["ma lo tatou Alii o Iesu Keriso.", "and the we (incl) Lord Jesus Christ"]]},
  {num:5,words:[["Ou te fia faamanatu atu", "I want to do something to remind"], ["foi ia te outou", "also unto you"], ["i le mea", "in the thing"], ["na outou iloa anamua,", "you (all) known anamua"], ["na faaolaina", "saved"], ["e le Alii", "by the Lord"], ["le nuu ai", "the nation"], ["le nuu o Aikupito,", "the nation Egypt"], ["a e mulimuli ane", "but to follow after"], ["ua faaumatia e ia", "destroy by him"], ["o e", "who"], ["na le faatuatua.", "the faith"]]},
  {num:6,words:[["O agelu foi o", "angel also"], ["e na", "by"], ["le taofi", "the hold"], ["i lo latou mamalu,", "in the they glory"], ["a ua tuua e", "but left by"], ["i latou", "them"], ["le mea", "the thing"], ["sa latou nofo ai,", "they dwell"], ["ua taofia e ia", "taofia by him"], ["i noanoataga", "in noanoataga"], ["e faavavau", "forever/everlasting"], ["i lalo", "in under"], ["o le pogisa,", "the to be quite dark"], ["seia oo", "until oo"], ["i le faamasinoga", "in the judgment"], ["o le aso tele.", "the day great"]]},
  {num:7,words:[["E pei o Sotoma", "to to be broken sotoma"], ["ma Komoro,", "and komoro"], ["ma aai", "and city"], ["sa vagavagai ai,", "to surround"], ["ua faitaaga pei o", "fornication to be broken"], ["i latou,", "them"], ["ma mulimuli atu", "and follow after"], ["i nisi tino,", "in some body"], ["o lea", "therefore"], ["ua tuu mai ai", "placed"], ["i latou", "them"], ["e fai", "to make"], ["ma faailoga,", "and sign"], ["ua faasalaina", "faasalaina"], ["i latou", "them"], ["i le afi", "in the fire"], ["e faavavau.", "forever/everlasting"]]},
  {num:8,words:[["E faapea foi lava o ia", "saying also indeed he"], ["tagata moemiti,", "man moemiti"], ["latou te faaleaga", "they to abuse"], ["le tino,", "the body"], ["ma latou ta'ufaatauvaa", "and they ta'ufaatauvaa"], ["i alii,", "in Lord"], ["ma upu leaga", "and word evil"], ["i e", "in by"], ["ua mamalu.", "glory"]]},
  {num:9,words:[["A o Mekaeli", "but mekaeli"], ["o le agelu silisili,", "the angel very much"], ["ina ua la finau", "let la finau"], ["ma le tiapolo", "and the tiapolo"], ["na ia finau", "to finau"], ["i le tino o Mose,", "in the body Moses"], ["ua na", "ua na"], ["le faamalosi", "the faamalosi"], ["ona lafo atu", "and cloth used as gratuity for a talking chief"], ["o se upu leaga", "a word evil"], ["e faasala ia te ia", "to to fine unto him"], [",", ","], ["a ua", "but"], ["na faapea atu,", "thus"], ["Ia aoai", "to aoai"], ["le Alii ia te oe.", "the Lord unto you"]]},
  {num:10,words:[["A o ia tagata,", "but he man"], ["latou te upu leaga", "they word evil"], ["i mea latou te", "in thing they"], ["le iloa,", "the known"], ["o mea foi", "thing also"], ["e iloa fua e", "to known fruit by"], ["i latou,", "them"], ["e pei o mea ola", "to to be broken thing life"], ["e leai", "there is not"], ["se mafaufau,", "a think"], ["latou te faaleaga ia te", "they to abuse unto"], ["i latou", "them"], ["i ia lava mea.", "in to indeed thing"]]},
  {num:11,words:[["Oi talofa ia te", "wo unto"], ["i latou!", "them"], ["auā ua latou savavali", "for they walked"], ["i le ala o Kaino,", "in the arise Cain"], ["ma feosofi atu", "and feosofi"], ["i le sese o Palaamo", "in the sese palaamo"], ["ona o le totogi,", "because of the totogi"], ["ua fano foi", "perish also"], ["i latou", "them"], ["i le fouvale o Koru.", "in the to rebel koru"]]},
  {num:12,words:[["O papa", "burster"], ["i latou", "them"], ["i o outou faigaai alofa,", "in you (all) faigaai love"], ["pe a latou aai faatasi", "whether but they city once"], ["ma outou", "and you (all)"], ["ma le", "and the"], ["le mata'u,", "the ax"], ["ua na", "ua na"], ["ona aai lava", "and city indeed"], ["i latou;", "them"], ["o ao", "day"], ["i latou", "them"], ["e le o", "by the"], ["i ai", "therein"], ["se vai,", "a water"], ["ua feleleaiina", "feleleaiina"], ["i matagi;", "in wind"], ["o laau", "tree"], ["ua malili o latou", "the name of a tree they"], ["lau,", "your"], ["ua le fua,", "the fruit"], ["ua mate faalua,", "mate faalua"], ["ua liaiina lava;", "liaiina indeed"]]},
  {num:13,words:[["o peau sousou", "a wave sousou"], ["o le sami,", "Sea"], ["ua faapunaia", "faapunaia"], ["ae mea", "but thing"], ["e masiasi ai", "to to be ashamied"], ["i latou;", "them"], ["o fetu feoai", "star feoai"], ["ua tuu", "put"], ["mo i latou", "for them"], ["le pogisa", "the to be quite dark"], ["o le pouliuli", "the darkness"], ["e faavavau.", "forever/everlasting"]]},
  {num:14,words:[["Na valoia foi", "valoia also"], ["i latou", "them"], ["e Enoka,", "to Enoch"], ["o le toafitu lea talu", "the toafitu since"], ["mai ia Atamu,", "from to Adam"], ["ua faapea ane,", "saying"], ["Faauta,", "behold"], ["e afio mai", "to dwell (respectful) from"], ["le Alii", "the Lord"], ["ma ona au paia", "and then saints"], ["e manomano,", "by manomano"]]},
  {num:15,words:[["e faamasino ai", "to a judge"], ["i tagata uma,", "in man all"], ["ma faasalaina ai", "and faasalaina"], ["e ua amio faalematau uma", "by conduct faalematau all"], ["lava o ia", "indeed he"], ["i latou,", "them"], ["ona o", "because of"], ["a latou galuega faalematau uma", "but they work faalematau all"], ["ua latou faia", "they did"], ["ma le faalematau,", "and the faalematau"], ["ona o", "because of"], ["a latou upu faatautala foi", "but they word to ill use also"], ["na fai ia te ia", "make unto him"], ["e tagata agasala", "to man sin"], ["ua faalematau.", "faalematau"]]},
  {num:16,words:[["O e muimui", "who to murmur"], ["i latou", "them"], ["ma faameo,", "and faameo"], ["o loo o savavali", "walked"], ["i latou", "them"], ["e tusa ma o latou", "according to they"], ["tu'inanau,", "tu'inanau"], ["ma ua tautala", "and to talk"], ["mai o latou gutu", "from they mouth"], ["i upu faasausili,", "in word haughty"], ["o loo faaneenee atu foi", "to\" praise also"], ["i latou", "them"], ["i alii e", "in Lord by"], ["maua ai ni mea.", "received some thing"]]},
  {num:17,words:[["A o outou", "but you (all)"], ["le au pele", "the I dear"], ["e,", "by"], ["ia outou manatua upu", "to you (all) remember word"], ["na fai mai anamua", "said anamua"], ["e le au aposetolo", "by the I apostle"], ["a lo tatou Alii o Iesu Keriso;", "but our Lord Jesus Christ"]]},
  {num:18,words:[["na latou fai atu ia te outou,", "they said to unto you"], ["E i ai", "by therein"], ["i ona aso", "in then day"], ["e gata ai o tagata tauemu,", "to a snake man tauemu"], ["o e savavali", "who walked"], ["e tusa ma o latou", "according to they"], ["lava tu'inanau", "indeed tu'inanau"], ["ma le faalematau.", "and the faalematau"]]},
  {num:19,words:[["O tagata lava ia", "man indeed to"], ["ua latou vavae ese,", "they to divide away"], ["ua amio faaletino,", "conduct relating to the body"], ["ua le", "the"], ["i ai", "therein"], ["le Agaga.", "the spirit"]]},
  {num:20,words:[["A o outou", "but you (all)"], ["le au pele", "the I dear"], ["e,", "by"], ["ia outou ati", "to you (all) to pull up"], ["ae ia te outou", "but unto you"], ["i lo outou faatuatua", "in the you (all) faith"], ["e silisili", "to very much"], ["ona paia,", "and holy"], ["o le Agaga Paia tou te tatalo ai,", "the Holy Spirit second person plural pray"]]},
  {num:21,words:[["ia outou faatumau ia te outou", "to you (all) faatumau unto you"], ["i le alofa", "in the love"], ["o le Atua,", "of God"], ["ma faatalitali atu", "and faatalitali"], ["i le alofa", "in the love"], ["o lo tatou Alii o Iesu Keriso,", "our Lord Jesus Christ"], ["e oo atu", "it shall come to pass"], ["i le ola", "in the life"], ["e faavavau.", "forever/everlasting"]]},
  {num:22,words:[["Ia outou alofa atu", "to you (all) love"], ["i nisi", "in some"], ["ma ia faatatau;", "and to to ht"]]},
  {num:23,words:[["a o isi ia", "but other to"], ["outou faaola ia", "you (all) save to"], ["i latou", "them"], ["ma le mata'u,", "and the ax"], ["ia se'i ia te", "to a flower put into the hair or unto"], ["i latou mai", "them from"], ["le afi,", "the fire"], ["ma ia outou 'ino'ino", "and to you (all) 'ino'ino"], ["i le ofu", "in the garment"], ["ua pisia", "pisia"], ["i le tino.", "in the body"]]},
  {num:24,words:[["O lenei,", "this"], ["ia ia te ia", "to unto him"], ["na te mafaia", "he able"], ["ona leoleo ia te outou", "and police unto you"], ["ina ne'i pauu,", "let now fell"], ["ma tuuina atu ia te outou", "and given unto you"], ["ua le ponā", "the ponā"], ["i luma", "in before"], ["o lona lava mamalu", "his indeed glory"], ["ma le fiafia tele,", "and the competition great"]]},
  {num:25,words:[["ia i le Atua poto", "to in the God wise"], ["e toatasi", "to one One"], ["o lo tatou Faaola,", "our save"], ["le viiga", "the viiga"], ["ma le mamalu,", "and the glory"], ["o le malosi", "the strong"], ["ma le pule,", "and the rule"], ["i nei", "in this"], ["ona po,", "and night"], ["ma ia oo", "and to oo"], ["i le faavavau lava.", "in the a stone connected with indeed"], ["Amene.", "amen"]]},
];
renderVerseSet(jud_ch_1_Verses, 'jud-ch1-verses');

})();