(function() {
var _mal_ch_1_Verses = [
  {num:1,words:[["O le avega", "the burden"], ["o le afioga", "the word"], ["a Ieova ia", "of the LORD he"], ["Isaraelu", "Israel"], ["na aumaia", "brought here"], ["e Malaki.", "Malachi"]]},
  {num:2,words:[["Ua ou alofa atu ia te outou,", "I loved unto you all"], ["ua fetalai mai ai", "said"], ["Ieova;", "the LORD"], ["a", "but"], ["ua outou fai mai,", "you all said"], ["Ua e alofa mai ia", "you loved from he"], ["i mātou", "us"], ["i ni", "in some"], ["a?", "but"], ["E le uso ea Esau", "shall not brother Esau"], ["ma Iakapo?", "and Iakapo"], ["ua fetalai mai ai", "said"], ["Ieova;", "the LORD"], ["a", "but"], ["ua ou alofa ia", "I loved he"], ["Iakopo,", "Jacob"]]},
  {num:3,words:[["ma ou 'ino'ino", "and I disdained"], ["ia Esau;", "he Esau"], ["ua faia foi", "did also"], ["e a'u", "me"], ["ona mauga", "and mountain"], ["ma mea tuufua,", "and thing tuufua"], ["ua faia foi", "did also"], ["lona tofi", "his lot"], ["ma fale", "and house"], ["i mea gaogao.", "things void"]]},
  {num:4,words:[["Ua fai mai", "said"], ["Etoma,", "Edom"], ["Ua fa'atafunaina", "destroyed"], ["i mātou,", "us"], ["a e mātou", "but by us"], ["te toe faia fale", "again do house"], ["ua masofasofa;", "masofasofa"], ["o le mea lea,", "therefore"], ["o loo fa'apea ona", "saying and"], ["fetalai mai ai", "said"], ["o Ieova o 'au,", "the LORD troops"], ["Lātou te faia,", "they will do"], ["a", "but"], ["o a'u,", "I am"], ["ou te lepetia,", "I will overthrown"], ["e ta'ua", "by us two"], ["i lātou,", "them"], ["O le laueleele", "the ground"], ["o", "o"], ["e amio leaga,", "iniquity"], ["ma Le nuu", "and the nation"], ["e toasa", "wrath"], ["i ai", "therein"], ["Ieova", "the LORD"], ["e fa'avavau.", "forever/everlasting"]]},
  {num:5,words:[["E vaai foi", "look also"], ["i ai", "therein"], ["o outou lava mata,", "you all very eye"], ["ona outou fa'apea ai lea,", "and you all so then"], ["Ia viia Ieova", "he praised the LORD"], ["mai le laueleele", "from the ground"], ["o Isaraelu.", "Israel"]]},
  {num:6,words:[["E ava", "passage through a coral reef for boats"], ["le atali'i", "the son"], ["i lona tamā,", "in his father"], ["e ava foi", "passage through a coral reef for boats also"], ["le auauna", "the servant"], ["i lona ali'i;", "in his Lord"], ["afai", "if"], ["o a'u", "I am"], ["o le tamā,", "the father"], ["o ifea ni o'u ava? afai foi", "where? some my passage through a coral reef for boats if also"], ["o a'u", "I am"], ["o le ali'i,", "the Lord"], ["o ifea", "where?"], ["lo'u matautia?", "my fearful"], ["ua fetalai mai ai", "said"], ["Ieova o 'au", "the LORD of troops"], ["ia te outou", "unto you all"], ["faitaulaga o", "priest of"], ["e 'ino'ino", "disdained"], ["i lo'u igoa;", "in my name"], ["a", "but"], ["ua outou fai mai,", "you all said"], ["Ua mātou ino'ino", "we ino'ino"], ["i lou suafa", "in your name"], ["i ni", "in some"], ["a?", "but"]]},
  {num:7,words:[["Ua 'ino'ino", "disdained"], ["ina ua outou", "when you all"], ["au mai o mea", "bring thing"], ["e 'ai", "eat"], ["ua leaga", "evil"], ["i la'u fata faitaulaga;", "in my altar"], ["a", "but"], ["ua outou fai mai,", "you all said"], ["Ua leaga oe", "evil you"], ["ia te i mātou", "unto us"], ["i ni", "in some"], ["a?", "but"], ["Ua leaga", "evil"], ["ina ua outou", "when you all"], ["fai ane,", "said/spoke"], ["O le laoai", "the table"], ["a Ieova,", "of the LORD"], ["o le mea fa'atauvaa", "the thing vain"], ["lava lea.", "very"]]},
  {num:8,words:[["A outou aumaia", "your bring here"], ["le mea tauaso", "the thing a blind man"], ["e fai ma taulaga,", "to be offering"], ["e le leaga ea?", "shall not evil"], ["A outou aumaia", "your bring here"], ["le mea pipili", "the thing a cripple"], ["ma le mea", "and the thing"], ["e ma'i,", "from"], ["e le leaga ea? Se'i avatu", "shall not evil a flower put into the hair or give away"], ["ia", "he"], ["i le ali'i e", "in the Lord by"], ["pule ia te oe;", "rule unto you"], ["pe fiafia mai ea", "whether pleased from"], ["o ia ia te oe?", "he unto you"], ["pe talia mai oe", "whether received from you"], ["e ia?", "he"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:9,words:[["O lenei,", "now"], ["ia outou ole atu i luma", "he you all entreat in before"], ["o le Atua", "of God"], ["ina ia alofa", "so that love"], ["mai o ia ia te", "from he unto"], ["i tātou;", "us"], ["ua tupu mai ia te outou", "king from you all"], ["lenei mea;", "this thing"], ["pe", "whether"], ["na te talia mai", "he received from"], ["ea outou?", "you all"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:10,words:[["O ai", "O ai"], ["lava so outou", "very so you all"], ["na te punitia", "he shut"], ["fua faitotoa? Tou te", "fruit door second person plural"], ["le tafu fua", "not to make up the fire fruit"], ["le afi", "the fire"], ["i la'u fata faitaulaga;", "in my altar"], ["e leai lava so'u fiafia", "there is not very so'u pleased"], ["ia te outou,", "unto you all"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of troops"], ["ou te", "I will"], ["le talia foi", "not received also"], ["se taulaga ai", "an offering"], ["o outou lima.", "you all hand"]]},
  {num:11,words:[["Auā", "do not"], ["e fua mai", "yielding fruit"], ["i le mea", "in the thing"], ["e alu ae ai", "go up"], ["le lā,", "the sun"], ["e oo", "it shall come to pass"], ["i le mea", "in the thing"], ["e alu ifo ai,", "go down"], ["e viia ai", "praised"], ["lo'u igoa", "my name"], ["i nuu ese;", "in nation away"], ["e aumaia foi", "bring here also"], ["le mea manogi", "the thing fragrant"], ["e mu", "by mu"], ["i lo'u igoa", "in my name"], ["i nuu uma lava,", "in nation all very"], ["atoa ma le taulaga lelei;", "and the offering good"], ["auā", "for"], ["e viia", "praised"], ["lo'u igoa", "my name"], ["i nuu ese,", "in nation away"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:12,words:[["A o outou,", "but of you all"], ["ua outou fa'aleagaina ai,", "you all destroyed"], ["ina ua outou", "when you all"], ["fai ane,", "said/spoke"], ["Ua leaga", "evil"], ["le laoai", "not table"], ["a Ieova;", "of the LORD"], ["mōna fua,", "mōna fruit"], ["o ana mea", "cave thing"], ["e 'ai lea", "eat"], [",", ","], ["o le mea fa'atauvaa", "the thing vain"], ["lava.", "very"]]},
  {num:13,words:[["Ua outou fai ane foi,", "you all said also"], ["Aue,", "alas! oh!"], ["o le mea tiga naua!", "the thing grieved exceedingly"], ["ma outou 'ino'ino", "with you disdained"], ["i ai", "therein"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of troops"], ["ua outou aumaia foi", "you all brought here also"], ["le mea", "the thing"], ["ua faoa,", "seized captive"], ["ma le mea pipili,", "and the thing a cripple"], ["ma le mea", "and the thing"], ["e ma'i;", "from"], ["ua outou au mai ai", "you all brought"], ["ma taulaga? Ou te talia ea lea", "and offering I will received"], ["mea ai", "thing"], ["o outou lima?", "you all hand"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:14,words:[["A ia fa'afanoina", "his to curse"], ["le tagata pepelo", "the man false"], ["ua", "ua"], ["i ai", "therein"], ["le poa", "the captive"], ["i lona lafu,", "in his flock"], ["a", "but"], ["ua tauto o ia", "to take an oath it"], ["ma fai taulaga", "and do offering"], ["i le Ali'i", "in the Lord"], ["i le mea leaga;", "in the thing evil"], ["auā", "for"], ["o le Tupu sili", "the king most"], ["lava a'u,", "very me"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of troops"], ["e matautia lava", "fearful very"], ["lo'u igoa", "my name"], ["i nuu ese.", "in nation away"]]},
];
renderVerseSet(_mal_ch_1_Verses, 'mal-ch1-verses');

var _mal_ch_2_Verses = [
  {num:1,words:[["O lenei", "now"], ["foi,", "also"], ["ua ia te outou", "unto you all"], ["le au faitaulaga lenei", "the priests this"], ["poloaiga.", "commandment"]]},
  {num:2,words:[["Afai tou te", "if second person plural"], ["le fa'alogo mai,", "not hearken from"], ["afai foi", "if also"], ["tou te", "second person plural"], ["le mafaufau", "the think"], ["ina ia aumaia", "so that bring here"], ["le viiga", "the praise"], ["i lo'u igoa,", "in my name"], ["ua fetalai mai ai", "said"], ["Ieova o 'au,", "the LORD of troops"], ["ona ou auina atu ai lea", "and I sent then"], ["o le fa'afanoga", "the destruction"], ["ia te outou,", "unto you all"], ["ma ou fa'afanoina mea tou te manuia ai;", "and I to curse thing second person plural prosper"], ["a", "but"], ["ua ou fa'afanoina lava;", "I to curse very"], ["auā", "for"], ["na outou", "you all"], ["le mafaufau", "the think"], ["i ai", "therein"], [".", "."]]},
  {num:3,words:[["Fa'auta,", "behold"], ["ou te aoai atu", "I will chastise"], ["i le fua saito", "in the fruit wheat"], ["ona o outou;", "because of you all"], ["ou te palasi foi", "I will to have children in also"], ["le otaota o manu", "the full of rubbish of animal"], ["i o outou", "in of you all"], ["mata,", "eye"], ["o le otaota", "the full of rubbish"], ["o taulaga o", "offering of"], ["a outou tausamiga,", "your feast"], ["e aveesea foi", "removed away also"], ["outou fa'atasi ma lea", "you all together and"], ["mea.", "thing"]]},
  {num:4,words:[["Tou te iloa ai,", "second person plural know"], ["ua ou avatu", "I gave away"], ["lenei poloaiga ia te outou;", "this commandment unto you all"], ["auā", "for"], ["sa ia Levi", "he Levi"], ["la'u feagaiga,", "my covenant"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:5,words:[["Sa ia te ia", "to him"], ["la'u feagaiga o", "my covenant"], ["i ai", "therein"], ["le ola", "the life"], ["ma le manuia;", "and peace"], ["na a'u avatu ia", "me gave away he"], ["mea ia te ia", "thing to him"], ["ona", "and"], ["o lona mata'u", "his afraid"], ["na mata'u ai", "afraid"], ["o ia ia te au;", "he unto me"], ["ua ia matuā", "he exceedingly"], ["mata'u", "afraid"], ["i lo'u igoa.", "in my name"]]},
  {num:6,words:[["O le mataupu", "the chapter"], ["o le fa'amaoni", "the faithful"], ["sa", "sa"], ["i lona gutu lea;", "in his mouth"], ["na", "na"], ["le iloa foi", "not know also"], ["se mea", "a thing"], ["le tonu", "the right"], ["i ona laugutu;", "in his lips"], ["na savavali fa'atasi ma a'u", "walked together and me"], ["i le amio filemu", "in the conduct peace"], ["ma le amio sa'o;", "and the conduct the appointed portion of"], ["na ia fa'aliliuina foi", "he to turn round also"], ["ē toatele", "by many"], ["nai", "from"], ["le amioletonu.", "the wickedness"]]},
  {num:7,words:[["Auā o laugutu", "do not of lips"], ["o le faitaulaga", "the priest"], ["e tausia ai", "nursed"], ["le poto,", "the wise"], ["lātou te sailia foi", "they will sought also"], ["le tulafono ai", "the law"], ["lona gutu;", "his mouth"], ["auā", "for"], ["o le sāvali", "the walk"], ["o ia", "it/he/she"], ["a Ieova o 'au.", "of the LORD of troops"]]},
  {num:8,words:[["A o outou,", "but of you all"], ["ua outou", "you all"], ["o ese", "away"], ["i le ala,", "in the way"], ["ma outou fa'atausuai", "with you to cause to stumble"], ["i", "in"], ["e toatele", "many"], ["i le tulafono;", "in the law"], ["ua leaga ia te outou", "evil unto you all"], ["le feagaiga", "the covenant"], ["a Levi,", "of Levi"], ["na fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:9,words:[["O a'u foi,", "I am also"], ["ua ou tuuina atu", "I have given"], ["outou ia inosia", "you all he abominable"], ["ma ta'ufaatauvaaina outou", "and ta'ufaatauvaaina you all"], ["e le nuu uma,", "shall not nation all"], ["e pei ona", "as"], ["outou", "you all"], ["le tausi", "the nurse"], ["i o'u ala,", "in my way"], ["ma outou fa'ailogaina tagata", "with you signs man"], ["i le tulafono.", "in the law"]]},
  {num:10,words:[["E le", "by the"], ["ua toatasi ea", "one One"], ["le Tamā o", "the father of"], ["i tātou uma lava.", "us all very"], ["E le faia ea", "shall not do"], ["i tātou", "us"], ["e le Atua e", "God"], ["toatasi?", "one One"], ["Pe", "whether"], ["se a le mea", "what / why"], ["ua tātou fa'a'ole'ole ai", "we treacherous"], ["le tasi", "the one"], ["i le tasi", "in the one"], ["i lo tātou soli", "than we to tread upon"], ["o le feagaiga", "the covenant"], ["a o tātou tamā?", "but of we father"]]},
  {num:11,words:[["Ua fa'a'ole'ole Iuta,", "treacherous Judas"], ["ua faia foi", "did also"], ["i Isaraelu", "in Israel"], ["ma Ierusalema", "and Jerusalem"], ["le mea", "the thing"], ["e inosia;", "abominable"], ["auā", "for"], ["ua solia", "trodden upon"], ["e Iuta", "Judas"], ["le mea", "the thing"], ["ua paia ia", "holy he"], ["Ieova,", "the LORD"], ["o le mea", "the thing"], ["ua ia alofaina;", "he beloved"], ["ua ia fai", "he did"], ["avā foi", "wife also"], ["i le afafine", "in the daughter"], ["o le atua ese.", "of God away"]]},
  {num:12,words:[["E vavaeeseina", "shall be cut off"], ["e Ieova", "the LORD"], ["le tagata", "the man"], ["ua faia lena", "did that"], ["mea ,", "thing"], ["o le", "the"], ["ua mataala,", "mataala"], ["ma le", "and the"], ["ua tali atu ai", "responded"], ["fale ie o Iakopo;", "tent Jacob"], ["atoa ma le", "and the"], ["ua avatu", "gave away"], ["le taulaga ia", "the offering he"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:13,words:[["Ua atu lua", "two"], ["ona faia e outou", "and do by you all"], ["o lenei", "now"], ["mea,", "thing"], ["o loo liloia ai", "is to be covered"], ["le fata faitaulaga", "the altar"], ["o Ieova", "the LORD"], ["i loimata,", "in loimata"], ["o le tagi,", "the cry"], ["ma le auega;", "and the alas! oh!"], ["o le mea lea", "therefore"], ["ua", "ua"], ["le toe silafia ai", "the again know"], ["lā outou taulaga,", "your offering"], ["e le talileleia foi mai", "by the talileleia returned"], ["o outou lima.", "you all hand"]]},
  {num:14,words:[["A", "but"], ["ua outou fai mai,", "you all said"], ["Aisea foi?", "Isaiah also"], ["Auā o Ieova,", "do not the LORD"], ["o ia", "it/he/she"], ["ua fai ma", "to be"], ["molimau ia te oe", "a witness unto you"], ["ma lau avā", "and your wife"], ["sa e fai", "you did"], ["a o ē taule'ale'a,", "but of by young man"], ["o le", "the"], ["ua e fa'a'ole'ole", "you treacherous"], ["i ai;", "therein"], ["a o ia", "but it"], ["sa lua mafuta,", "two communion"], ["o le avā foi", "the wife also"], ["o ia", "it/he/she"], ["o lau feagaiga.", "your covenant"]]},
  {num:15,words:[["Na ia le", "he the"], ["faia ea", "do"], ["le toatasi?", "the one One"], ["A", "but"], ["ua ia te ia", "to him"], ["foi", "also"], ["ona toe", "and again"], ["o le agaga.", "the spirit"], ["Se a foi", "a but also"], ["ua toatasi ai?", "one One"], ["Ina ia saili", "so that seek"], ["le fānau amio Atua;", "not born conduct God"], ["o lenei,", "now"], ["ia fa'aeteete outou", "he faaeteete you all"], ["i o outou", "in of you all"], ["loto,", "heart"], ["ina ne'i fa'a'ole'ole", "so that now treacherous"], ["se tasi", "a one"], ["i lana avā", "in his wife"], ["na fai", "did"], ["a o taule'ale'a.", "but of young man"]]},
  {num:16,words:[["Auā ou te 'ino'ino", "do not I will disdained"], ["i le alei,", "in the to drive"], ["ua fetalai mai ai", "said"], ["Ieova", "the LORD"], ["le Atua o Isaraelu;", "God Israel"], ["auā", "for"], ["ua ufiufi e", "covering you"], ["ia", "he"], ["lona ofu", "his garment"], ["i le fa'asaua,", "in the cruel"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of troops"], ["o le mea lea", "therefore"], ["ia outou fa'aeteete ai", "he you all faaeteete"], ["i o outou", "in of you all"], ["loto,", "heart"], ["a", "but"], ["e", "by"], ["aua tou te fa'a'ole'ole.", "for second person plural treacherous"]]},
  {num:17,words:[["Ua outou fa'atiga ia", "you all afflicted he"], ["Ieova", "the LORD"], ["i", "in"], ["a outou 'upu;", "your word"], ["a", "but"], ["ua outou fai mai,", "you all said"], ["Ua mātou fa'atiga ia te ia", "we afflicted to him"], ["i ni", "in some"], ["a?", "but"], ["Ua fa'atiga ia te ia", "afflicted to him"], ["ina ua outou", "when you all"], ["fai ane.", "said/spoke"], ["O", "O"], ["i lātou uma", "them all"], ["o", "o"], ["e fai mea leaga,", "do thing evil"], ["e lelei", "good"], ["i lātou", "them"], ["i luma o Ieova,", "before the LORD"], ["ua fiafia foi", "pleased also"], ["o ia ia", "he unto"], ["i lātou;", "them"], ["pe fa'apea ane outou", "whether so you all"], [",", ","], ["O ifea", "where?"], ["le Atua,", "God"], ["o lē fa'amasino?", "not judge"]]},
];
renderVerseSet(_mal_ch_2_Verses, 'mal-ch2-verses');

var _mal_ch_3_Verses = [
  {num:1,words:[["Fa'auta,", "behold"], ["ou te tuuina atu", "I will give"], ["la'u sāvali,", "my walk"], ["na te sauni", "he he who beg^ins the game"], ["le ala", "the way"], ["i o'u luma;", "before me"], ["e fa'afuasei foi", "by faafuasei also"], ["ona oo mai", "and came"], ["i lona malumalu", "in his temple"], ["o le Ali'i,", "the Lord"], ["o le", "the"], ["ua sailia e outou,", "sought by you all"], ["o le Agelu", "the angel"], ["lava lea", "very"], ["o le feagaiga,", "the covenant"], ["o le", "the"], ["ua outou naunau", "you all desired"], ["i ai;", "therein"], ["fa'auta,", "behold"], ["e afio mai", "dwell from"], ["lava o ia,", "very it"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:2,words:[["A o ai", "but of"], ["se", "a"], ["na te lavā", "he very"], ["tali", "respond"], ["le aso", "the day"], ["o lona afio mai?", "his dwell from"], ["o ai", "o ai"], ["foi", "also"], ["se", "a"], ["na te tulai", "he arose up"], ["pe a fa'aalia", "even though / although revealed"], ["mai o ia?", "from it"], ["auā o ia", "for it"], ["e tusa ma le afi", "according to the fire"], ["a lē tunu auro;", "but not roast gold"], ["e tusa foi", "according to also"], ["ma le moli", "and the moli"], ["a lē tāofu;", "but not tāofu"]]},
  {num:3,words:[["e nofo o ia,", "dwell it"], ["o lē tunu", "not roast"], ["ma fa'amamā", "and purify"], ["i le ario;", "in the silver"], ["na te fa'amamāina", "he cleansed"], ["le fanauga", "the children"], ["a Levi,", "of Levi"], ["na te fa'ate'a ese foi", "he made depart away also"], ["le eleele ia te", "the earth unto"], ["i lātou", "them"], ["e pei o le auro", "like the gold"], ["ma le ario;", "and the silver"], ["lātou te avatu ai", "they will give away"], ["ia Ieova", "he the LORD"], ["le taulaga", "the offering"], ["e fai", "do"], ["i le amiotonu.", "in the righteous"]]},
  {num:4,words:[["Ona mālie ai lea", "and mālie then"], ["ia Ieova", "he the LORD"], ["o le taulaga", "the offering"], ["a Iuta", "of Judas"], ["ma Ierusalema,", "and Jerusalem"], ["e pei o aso", "like day"], ["o le vavau,", "the ancient times"], ["e pei o tausaga anamua.", "like year ancient"]]},
  {num:5,words:[["Ou te fa'alatalata foi", "I will drew near also"], ["ia te outou", "unto you all"], ["i le fa'amasinoga;", "in the judgment"], ["e vave foi", "quick also"], ["ona fai", "and do"], ["o a'u", "I am"], ["ma molimau", "and a witness"], ["i", "in"], ["e fai togafiti fa'ataulāitu,", "do heal faataulāitu"], ["ma ē mulilulua,", "and by whoring"], ["ma ē tauto pepelo,", "and by to take an oath false"], ["ma ē fa'asaua", "and by cruel"], ["i le taui", "in the a reward"], ["o le auauna tauia,", "the servant repay"], ["o le fafine", "the women"], ["ua oti", "died"], ["lana tāne,", "his man"], ["ma le", "and the"], ["ua mātuaoti,", "mātuaoti"], ["atoa ma ē fa'apioina", "and by faapioina"], ["le fa'amasinoga", "the judgment"], ["o le tagata ese;", "man away"], ["ua lātou", "they"], ["le matatau foi", "the dismayed also"], ["ia te au,", "unto me"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:6,words:[["Auā", "do not"], ["o a'u", "I am"], ["o Ieova,", "the LORD"], ["ou te", "I will"], ["le liliu;", "not turn"], ["o le mea lea", "therefore"], ["ua", "ua"], ["le fa'aumatia ai", "not destroyed"], ["outou", "you all"], ["le fanauga", "the children"], ["a Iakopo.", "of Jacob"]]},
  {num:7,words:[["Talu mai aso", "since from day"], ["o outou tamā,", "you all father"], ["ua outou tete'a ese ai", "you all light colored : as away"], ["i a'u tulafono,", "in me law"], ["ma outou", "with you"], ["le tausiusi", "the obey"], ["i ai.", "therein"], ["Foi mai ia ia te au,", "returned to him me"], ["ona ou foi atu lea", "and I also"], ["ia te outou,", "unto you all"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"], ["A", "but"], ["ua outou fai mai,", "you all said"], ["Mātou te foi atu", "we also"], ["ma ni", "and some"], ["a?", "but"]]},
  {num:8,words:[["Pe faoa", "whether seized captive"], ["e le tagata mea", "shall not man thing"], ["a le Atua?", "of God"], ["a o outou,", "but of you all"], ["ua outou faoa a'u", "you all seized captive me"], ["mea.", "thing"], ["A", "but"], ["ua outou fai mai,", "you all said"], ["Ni", "some"], ["a ea au", "but me"], ["mea", "thing"], ["ua mātou faoa?", "we seized captive"], ["Ua outou faoa", "you all seized captive"], ["mea", "thing"], ["e sefulu a'i", "ten"], ["a outou mea,", "your thing"], ["atoa ma taulaga.", "and offering"]]},
  {num:9,words:[["Ua matuā fa'afanoina", "exceedingly to curse"], ["outou,", "you all"], ["o le nuu uma lava,", "all the nation very"], ["auā", "for"], ["ua outou faoa a'u", "you all seized captive me"], ["mea.", "thing"]]},
  {num:10,words:[["Ina aumaia mea", "so that bring here thing"], ["e sefulu a'i", "ten"], ["a outou mea uma lava", "your all things"], ["i le fale", "in the house"], ["e tuu ai", "put"], ["mea;", "thing"], ["ina ia", "so that"], ["i ai", "therein"], ["mea", "thing"], ["e 'ai", "eat"], ["i lo'u fale;", "in my house"], ["ma ia outou", "and he you all"], ["tofotofo mai ai", "to try from"], ["ia te au", "unto me"], ["i lenei", "in this"], ["mea,", "thing"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of troops"], ["pe ou te", "whether I will"], ["le toina pupuni", "the toina shut"], ["o le lagi", "Heaven"], ["mo outou,", "for you"], ["ma sasaa atu", "and plurzH x)^ saasaa"], ["le manuia", "the prosper"], ["mo outou,", "for you"], ["ina seia silisili", "until very much"], ["ona tele.", "and great"]]},
  {num:11,words:[["Ou te aoai atu,", "I will chastise"], ["ona o outou,", "because of you all"], ["le", "the"], ["na te 'aina", "he edible"], ["mea;", "thing"], ["na te", "he"], ["le fa'aumatia", "not destroyed"], ["le fua", "the fruit"], ["o lo outou laueleele;", "your ground"], ["e fua mai foi", "yielding fruit also"], ["le vine", "the vine"], ["i o outou", "in of you all"], ["fanua,", "land"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:12,words:[["E fa'aamuia foi", "make blessed also"], ["ia te outou", "unto you all"], ["e nuu uma lava;", "nation all very"], ["auā", "for"], ["e fai outou", "do you all"], ["ma nuu", "and nation"], ["e moomia,", "by moomia"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:13,words:[["Ua mamafa", "heavy"], ["a outou 'upu", "your word"], ["ia te au,", "unto me"], ["ua fetalai mai ai", "said"], ["Ieova;", "the LORD"], ["a", "but"], ["ua outou fai mai,", "you all said"], ["Se a", "a but"], ["sa mātou 'upu", "we word"], ["ua fai atu ai", "said to"], ["ia te oe?", "unto you"]]},
  {num:14,words:[["Ua outou fai ane,", "you all said"], ["E le aoga", "shall not useful"], ["ona auauna", "and servant"], ["i le Atua;", "in the God"], ["se a foi", "a but also"], ["se mea", "a thing"], ["ua maua", "received"], ["ina ua tātou", "when we"], ["tausiusi", "obey"], ["i ana sauniga,", "in cave ordinance"], ["ma tātou feoai", "and we walk about"], ["ma ofu eleelea", "and garment was earth"], ["i luma o Ieova", "before the LORD"], ["o 'au?", "troops"]]},
  {num:15,words:[["O lenei,", "now"], ["ua tātou fa'aamuia", "we made blessed"], ["i", "in"], ["e fa'amaualuluga;", "exaltation"], ["ua atiina ae foi", "to pull up also"], ["e ua fai amio leaga;", "did iniquity"], ["ua lātou tofotofo lava", "they to try very"], ["i le Atua,", "in the God"], ["a", "but"], ["e sao", "the appointed portion of"], ["i lātou.", "them"]]},
  {num:16,words:[["Ona fetautalatalai lea", "and converse with one another"], ["e", "by"], ["na matatau ia", "dismayed he"], ["Ieova;", "the LORD"], ["ua liliu mai foi", "turned from also"], ["e Ieova", "the LORD"], ["ona fofoga ,", "and face"], ["ma", "and"], ["ua fa'afofoga mai;", "listen from"], ["ona tusia lea", "and written"], ["o le tusi", "the book"], ["e fa'amanatu", "to remind"], ["i ona luma,", "before him"], ["mo", "for"], ["e matatau ia", "dismayed he"], ["Ieova,", "the LORD"], ["ma mafaufau", "and think"], ["i lona suafa.", "in his name"]]},
  {num:17,words:[["E fai foi", "do also"], ["i lātou ma'u oloa tāua,", "them opinion goods war"], ["ua fetalai mai ai", "said"], ["Ieova o 'au,", "the LORD of troops"], ["i le aso", "in the day"], ["ua ou tofia;", "I was chosen"], ["ou te alofa foi", "I will love also"], ["ia te i lātou,", "unto them"], ["e pei ona", "as"], ["alofa", "love"], ["o le tagata", "man"], ["i lona atali'i", "in his son"], ["ua auauna ia te ia.", "servant to him"]]},
  {num:18,words:[["Ona outou toe iloa lea", "and you all again know"], ["e eseese lē amiotonu", "divided not righteous"], ["ma lē amio leaga;", "and not iniquity"], ["e ese", "away"], ["le", "the"], ["ua auauna", "servant"], ["i le Atua,", "in the God"], ["ma le", "and the"], ["ua", "ua"], ["le auauna ia te ia.", "the servant to him"]]},
];
renderVerseSet(_mal_ch_3_Verses, 'mal-ch3-verses');

var _mal_ch_4_Verses = [
  {num:1,words:[["Auā fa'auta,", "do not behold"], ["o le a oo mai le aso", "what came the day"], ["e mu ai", "by mu"], ["pei", "like"], ["se umu;", "a oven"], ["ona fai ai lea", "and do then"], ["ma tagutugutu o saito", "and tagutugutu of wheat"], ["o", "o"], ["e fa'amaualuluga uma,", "exaltation all"], ["atoa ma ē fai amio leaga uma;", "and by do iniquity all"], ["e susunuina foi", "burned also"], ["i lātou", "them"], ["i le aso", "in the day"], ["o le a oo mai,", "what came"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of troops"], ["e le fa'atoeina ai", "shall not make again"], ["mo", "for"], ["i lātou", "them"], ["se aa po", "a aa night"], ["o se lā lā'au.", "a sun tree"]]},
  {num:2,words:[["A o outou", "but of you all"], ["o", "o"], ["e matatau", "dismayed"], ["i lo'u igoa,", "in my name"], ["e alu ae", "go up"], ["ia te outou", "unto you all"], ["le Lā", "the sun"], ["o le amiotonu;", "the righteous"], ["e", "by"], ["i ai", "therein"], ["foi", "also"], ["le mea", "the thing"], ["e malolo ai", "rest"], ["i ona apaau;", "in his a wing"], ["e o atu foi", "shall go also"], ["outou", "you all"], ["ma osooso,", "and sit"], ["pei o tamai povi", "like of son cattle"], ["mai le fale povi.", "from the house cattle"]]},
  {num:3,words:[["Ona outou solia lea", "and you all trodden upon"], ["o", "o"], ["e amio leaga;", "iniquity"], ["auā", "for"], ["e fai", "do"], ["i lātou", "them"], ["ma efuefu", "and dust"], ["i lalo o outou", "under you all"], ["alofivae", "soles of feet"], ["i le aso", "in the day"], ["ua ou tofia,", "I was chosen"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of troops"]]},
  {num:4,words:[["Ia outou manatunatu i le", "he you all meditate in the"], ["tulafono", "law"], ["a Mose", "of Moses"], ["la'u auauna,", "my servant"], ["na ou poloai atu ai", "I commanded"], ["ia te ia", "to him"], ["i Horepa ia", "in Horepa he"], ["Isaraelu uma,", "Israel all"], ["o tulafono", "law"], ["ma fa'amasinoga.", "and judgment"]]},
  {num:5,words:[["Fa'auta,", "behold"], ["ou te auina atu", "I will sent"], ["ia te outou", "unto you all"], ["o Elia", "Elijah"], ["le perofeta,", "the prophesied"], ["a o lei oo mai le aso", "but of not came the day"], ["o Ieova", "the LORD"], ["e sili,", "most"], ["ma le matautia.", "and the fearful"]]},
  {num:6,words:[["Na te fa'aliliuina", "he to turn round"], ["loto o mātua", "heart of great"], ["i fānau,", "in born"], ["ma loto o fānau", "and heart of born"], ["i o lātou", "in of they"], ["mātua;", "great"], ["ne'i ou alu atu,", "now I go away"], ["ma ou taia", "and I struck"], ["le nuu", "the nation"], ["i le fa'afanoga.", "in the destruction"]]},
];
renderVerseSet(_mal_ch_4_Verses, 'mal-ch4-verses');

})();