(function() {
var _mal_ch_1_Verses = [
  {num:1,words:[["O le avega", "the burden"], ["o le afioga", "the a word"], ["a Ieova ia Isaraelu", "of the LORD to Israel"], ["na aumaia", "bring here"], ["e Malaki.", "to Malachi"]]},
  {num:2,words:[["Ua ou alofa atu ia te outou,", "I love unto you"], ["ua fetalai mai ai Ieova;", "said the LORD"], ["a ua outou fai mai,", "but you (all) said"], ["Ua e alofa", "to love"], ["mai ia", "from to"], ["i matou", "in we (excl)"], ["i ni", "in some"], ["a? E le uso ea Esau", "of by the brother to rise (as a diver to the sur- Esau"], ["ma Iakapo?", "and Iakapo"], ["ua fetalai mai ai Ieova;", "said the LORD"], ["a ua ou alofa ia", "but I love to"], ["Iakopo,", "James"]]},
  {num:3,words:[["ma ou 'ino'ino ia", "and I hate to"], ["Esau;", "Esau"], ["ua faia foi", "made also"], ["e a'u", "to I"], ["ona mauga", "and mountain"], ["ma mea tuufua,", "and thing tuufua"], ["ua faia foi lona tofi", "made also his appoint"], ["ma fale", "and house"], ["i mea gaogao.", "in thing void"]]},
  {num:4,words:[["Ua fai mai Etoma,", "said Edom"], ["Ua faatafunaina", "destroyed"], ["i matou,", "in we (excl)"], ["a e matou te toe faia fale", "but by we (excl) again made house"], ["ua masofasofa;", "masofasofa"], ["o le mea lea,", "therefore"], ["o loo faapea ona", "saying and"], ["fetalai mai ai o Ieova", "said the LORD"], ["o 'au,", "I"], ["Latou te faia,", "they made"], ["a o a'u,", "but I am"], ["ou te lepetia,", "I overthrown"], ["e ta'ua", "by us (two, incl)"], ["i latou,", "them"], ["O le laueleele o", "the ground of"], ["e amio leaga,", "to iniquity"], ["ma Le nuu", "and the nation"], ["e toasa", "to wrath"], ["i ai Ieova", "therein the LORD"], ["e faavavau.", "forever/everlasting"]]},
  {num:5,words:[["E vaai foi", "to look also"], ["i ai o outou", "therein of you (all)"], ["lava mata,", "indeed eye"], ["ona outou faapea ai lea,", "and you (all) thus"], ["Ia viia Ieova", "to praised the LORD"], ["mai le laueleele o Isaraelu.", "from the ground of Israel"]]},
  {num:6,words:[["E ava", "to passage through a coral reef for boats"], ["le atalii", "the son"], ["i lona tamā,", "in his father"], ["e ava foi", "to passage through a coral reef for boats also"], ["le auauna", "the servant"], ["i lona alii;", "in his Lord"], ["afai o a'u", "if I am"], ["o le tamā,", "the father"], ["o ifea ni o'u ava? afai", "where? some my passage through a coral reef for boats if"], ["foi o a'u", "also I am"], ["o le alii,", "the Lord"], ["o ifea lo'u matautia?", "where? my fearful"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au ia te outou", "I unto you"], ["faitaulaga o", "priest of"], ["e 'ino'ino", "to hate"], ["i lo'u igoa;", "in my name"], ["a ua outou fai mai,", "but you (all) said"], ["Ua matou ino'ino", "we (excl) ino'ino"], ["i lou suafa", "in your name"], ["i ni", "in some"], ["a?", "but"]]},
  {num:7,words:[["Ua 'ino'ino", "hate"], ["ina ua outou au", "let you (all) I"], ["mai o mea", "from of thing"], ["e 'ai", "to eat"], ["ua leaga", "evil"], ["i la'u fata faitaulaga;", "in my altar"], ["a ua outou fai mai,", "but you (all) said"], ["Ua leaga oe ia te", "evil you unto"], ["i matou", "in we (excl)"], ["i ni", "in some"], ["a? Ua leaga", "of evil"], ["ina ua outou fai ane,", "let you (all) make"], ["O le laoai", "the table"], ["a Ieova,", "of the LORD"], ["o le mea faatauvaa lava lea.", "the thing vain indeed"]]},
  {num:8,words:[["A outou aumaia", "but you (all) bring here"], ["le mea tauaso", "the thing a blind man"], ["e fai", "to make"], ["ma taulaga,", "and offering"], ["e le leaga ea?", "by the evil to rise (as a diver to the sur-"], ["A outou aumaia", "but you (all) bring here"], ["le mea pipili", "the thing a cripple"], ["ma le mea", "and the thing"], ["e ma'i,", "to from"], ["e le leaga ea? Se'i avatu", "by the evil to rise (as a diver to the sur- a flower put into the hair or give away"], ["ia i le alii e", "to in the Lord by"], ["pule ia te oe;", "rule unto you"], ["pe fiafia mai ea o ia", "whether competition from to rise (as a diver to the sur- he"], ["ia te oe?", "unto you"], ["pe talia mai oe", "whether received from you"], ["e ia?", "by him"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:9,words:[["O lenei,", "this"], ["ia outou ole atu", "to you (all) entreat"], ["i luma", "in before"], ["o le Atua", "of God"], ["ina ia alofa", "so that love"], ["mai o ia ia te", "from he unto"], ["i tatou;", "in we (incl)"], ["ua tupu mai ia te outou", "king from you (all)"], ["lenei mea;", "this thing"], ["pe na te talia", "whether he received"], ["mai ea outou?", "from to rise (as a diver to the sur- you (all)"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:10,words:[["O ai lava so outou", "indeed so you (all)"], ["na te punitia fua faitotoa? Tou te", "he shut fruit door second person plural"], ["le tafu fua", "the to make up the fire fruit"], ["le afi", "the fire"], ["i la'u fata faitaulaga;", "in my altar"], ["e leai lava so'u fiafia", "there is not indeed so'u competition"], ["ia te outou,", "unto you"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["ou te", "I"], ["le talia foi", "the received also"], ["se taulaga ai o outou", "an offering of you (all)"], ["lima.", "five"]]},
  {num:11,words:[["Auā e fua", "for to fruit"], ["mai i le mea", "from in the thing"], ["e alu", "to go"], ["ae ai", "but"], ["le la,", "the la"], ["e oo", "it shall come to pass"], ["i le mea", "in the thing"], ["e alu ifo ai,", "to go down"], ["e viia ai lo'u igoa", "to praised my name"], ["i nuu ese;", "in nation away"], ["e aumaia foi", "to bring here also"], ["le mea manogi", "the thing fragrant"], ["e mu", "by mu"], ["i lo'u igoa", "in my name"], ["i nuu uma lava,", "in nation all indeed"], ["atoa ma le taulaga lelei;", "and the offering good"], ["auā e viia lo'u igoa", "for to praised my name"], ["i nuu ese,", "in nation away"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:12,words:[["A o outou,", "but of you (all)"], ["ua outou faaleagaina ai,", "you (all) faaleagaina"], ["ina ua outou fai ane,", "let you (all) make"], ["Ua leaga", "evil"], ["le laoai", "the table"], ["a Ieova;", "of the LORD"], ["mōna fua,", "mōna fruit"], ["o ana mea", "his thing"], ["e 'ai lea ,", "to eat"], ["o le mea faatauvaa lava.", "the thing vain indeed"]]},
  {num:13,words:[["Ua outou fai ane foi,", "you (all) make also"], ["Aue,", "alas! oh!"], ["o le mea tiga naua!", "the thing grieved exceedingly"], ["ma outou 'ino'ino", "with you hate"], ["i ai", "therein"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["ua outou aumaia foi", "you (all) bring here also"], ["le mea", "the thing"], ["ua faoa,", "seized captive"], ["ma le mea pipili,", "and the thing a cripple"], ["ma le mea", "and the thing"], ["e ma'i;", "to from"], ["ua outou au", "you (all) I"], ["mai ai", "from"], ["ma taulaga? Ou te talia ea lea mea ai", "and offering I received to rise (as a diver to the sur- thing"], ["o outou lima?", "you (all) five"], ["ua fetalai mai ai Ieova.", "said the LORD"]]},
  {num:14,words:[["A ia faafanoina", "but to faafanoina"], ["le tagata pepelo", "the man false"], ["ua i ai", "therein"], ["le poa", "the captive"], ["i lona lafu,", "in his herd"], ["a ua tauto o ia", "but to take an oath he"], ["ma fai taulaga", "and make offering"], ["i le Alii", "in the Lord"], ["i le mea leaga;", "in the thing evil"], ["auā o le Tupu sili", "for the king most"], ["lava a'u,", "indeed I"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["e matautia lava lo'u igoa", "to fearful indeed my name"], ["i nuu ese.", "in nation away"]]},
];
renderVerseSet(_mal_ch_1_Verses, 'mal-ch1-verses');

var _mal_ch_2_Verses = [
  {num:1,words:[["O lenei foi,", "this also"], ["ua ia te outou", "unto you"], ["le au faitaulaga lenei poloaiga.", "the priests this commandment"]]},
  {num:2,words:[["Afai tou te", "if second person plural"], ["le faalogo mai,", "the hearken from"], ["afai foi tou te", "if also second person plural"], ["le mafaufau", "the think"], ["ina ia aumaia", "so that bring here"], ["le viiga", "the praise"], ["i lo'u igoa,", "in my name"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au,", "I"], ["ona ou auina atu ai lea", "and I sent"], ["o le faafanoga ia te outou,", "the destruction unto you"], ["ma ou faafanoina mea tou te manuia ai;", "and I faafanoina thing second person plural peace"], ["a ua ou faafanoina lava;", "but I faafanoina indeed"], ["auā na outou", "for you (all)"], ["le mafaufau", "the think"], ["i ai .", "therein"]]},
  {num:3,words:[["Faauta,", "behold"], ["ou te aoai atu", "I chastise"], ["i le fua saito", "in the fruit wheat"], ["ona o outou;", "because of you (all)"], ["ou te palasi foi", "I to have children in also"], ["le otaota o manu", "the full of rubbish of animal"], ["i o outou mata,", "in of you (all) eye"], ["o le otaota o taulaga", "the full of rubbish of offering"], ["o a outou tausamiga,", "but you (all) feast"], ["e aveesea foi outou", "to removed away also you (all)"], ["faatasi ma lea mea.", "once and thing"]]},
  {num:4,words:[["Tou te iloa ai,", "second person plural known"], ["ua ou avatu lenei poloaiga", "I give away this commandment"], ["ia te outou;", "unto you"], ["auā sa ia Levi la'u feagaiga,", "for to Levi my covenant"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:5,words:[["Sa ia te ia", "to him"], ["la'u feagaiga o", "my covenant"], ["i ai", "therein"], ["le ola", "the life"], ["ma le manuia;", "and peace"], ["na a'u avatu ia", "I give away to"], ["mea ia te ia", "thing to him"], ["ona o lona mata'u", "because of his ax"], ["na mata'u ai o ia", "ax he"], ["ia te au;", "unto me"], ["ua ia matuā mata'u", "to exceedingly ax"], ["i lo'u igoa.", "in my name"]]},
  {num:6,words:[["O le mataupu", "the chapter"], ["o le faamaoni", "the faithful"], ["sa i lona gutu lea;", "in his mouth"], ["na le iloa foi", "not known also"], ["se mea", "a thing"], ["le tonu", "the right"], ["i ona laugutu;", "in then lips"], ["na savavali faatasi", "walked once"], ["ma a'u", "and I"], ["i le amio filemu", "in the conduct peace"], ["ma le amio sa'o;", "and the conduct the appointed portion of"], ["na ia faaliliuina foi ē toatele", "to faaliliuina also who many"], ["nai le amioletonu.", "from the wickedness"]]},
  {num:7,words:[["Auā o laugutu", "for of lips"], ["o le faitaulaga", "the priest"], ["e tausia ai", "to kept"], ["le poto,", "the wise"], ["latou te sailia foi", "they sought also"], ["le tulafono ai lona gutu;", "the law his mouth"], ["auā o le sāvali o ia", "for the sāvali he"], ["a Ieova o 'au.", "of the LORD of I"]]},
  {num:8,words:[["A o outou,", "but of you (all)"], ["ua outou", "you (all)"], ["o ese", "away"], ["i le ala,", "in the way"], ["ma outou faatausuai", "with you to cause to stumble"], ["i e toatele", "in many"], ["i le tulafono;", "in the law"], ["ua leaga ia te outou", "evil unto you"], ["le feagaiga", "the covenant"], ["a Levi,", "of Levi"], ["na fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:9,words:[["O a'u foi,", "I am also"], ["ua ou tuuina atu outou", "I have given you (all)"], ["ia inosia", "to abominable"], ["ma ta'ufaatauvaaina outou", "and ta'ufaatauvaaina you (all)"], ["e le nuu uma,", "by the nation all"], ["e pei ona", "as"], ["outou le tausi", "you (all) the keep"], ["i o'u ala,", "in my way"], ["ma outou faailogaina tagata", "with you faailogaina man"], ["i le tulafono.", "in the law"]]},
  {num:10,words:[["E le", "by the"], ["ua toatasi ea", "one One to rise (as a diver to the sur-"], ["le Tamā o", "the father of"], ["i tatou uma lava.", "in we (incl) all indeed"], ["E le faia ea", "by the made to rise (as a diver to the sur-"], ["i tatou", "in we (incl)"], ["e le Atua e", "God by"], ["toatasi? Pe", "one One whether"], ["se a le mea", "what"], ["ua tatou faa'ole'ole ai", "we (incl) deceit"], ["le tasi", "the one"], ["i le tasi", "in the one"], ["i lo tatou soli", "in the we (incl) to tread upon"], ["o le feagaiga", "the covenant"], ["a o tatou tamā?", "but of we (incl) father"]]},
  {num:11,words:[["Ua faa'ole'ole Iuta,", "deceit Judas"], ["ua faia foi", "made also"], ["i Isaraelu", "in Israel"], ["ma Ierusalema", "and Jerusalem"], ["le mea", "the thing"], ["e inosia;", "to abominable"], ["auā ua solia", "for despised"], ["e Iuta", "to Judas"], ["le mea", "the thing"], ["ua paia ia Ieova,", "holy to the LORD"], ["o le mea", "the thing"], ["ua ia alofaina;", "to beloved"], ["ua ia fai avā foi", "to make wife also"], ["i le afafine", "in the daughter"], ["o le atua ese.", "of God away"]]},
  {num:12,words:[["E vavaeeseina", "to separated apart"], ["e Ieova", "the LORD"], ["le tagata", "the man"], ["ua faia lena mea ,", "made that thing"], ["o le", "the"], ["ua mataala,", "mataala"], ["ma le", "and the"], ["ua tali atu ai fale ie", "respond house faamaise"], ["o Iakopo;", "James"], ["atoa ma le", "and the"], ["ua avatu", "give away"], ["le taulaga ia Ieova o 'au.", "the offering to the LORD of I"]]},
  {num:13,words:[["Ua atu lua", "two"], ["ona faia e outou", "and made by you (all)"], ["o lenei mea,", "this thing"], ["o loo liloia ai", "to be covered"], ["le fata faitaulaga o Ieova", "the altar of Jehovah"], ["i loimata,", "in loimata"], ["o le tagi,", "the cry"], ["ma le auega;", "and the auega"], ["o le mea lea", "therefore"], ["ua le toe silafia ai la outou taulaga,", "not again known your offering"], ["e le talileleia foi", "by the talileleia also"], ["mai o outou lima.", "from of you (all) five"]]},
  {num:14,words:[["A ua outou fai mai,", "but you (all) said"], ["Aisea foi? Auā o Ieova,", "Isaiah also for the LORD"], ["o ia", "he"], ["ua fai", "make"], ["ma molimau ia te oe", "and a witness unto you"], ["ma lau avā", "and your wife"], ["sa e fai", "to make"], ["a o ē taulealea,", "but of who young man"], ["o le", "the"], ["ua e faa'ole'ole", "to deceit"], ["i ai;", "therein"], ["a o ia", "but he"], ["sa lua mafuta,", "two communion"], ["o le avā foi o ia", "the wife also he"], ["o lau feagaiga.", "your covenant"]]},
  {num:15,words:[["Na ia le faia ea", "to the made to rise (as a diver to the sur-"], ["le toatasi?", "the one One"], ["A ua ia te ia", "but to him"], ["foi ona toe", "also then again"], ["o le agaga.", "the spirit"], ["Se a foi", "a but also"], ["ua toatasi ai?", "one One"], ["Ina ia saili", "so that seek"], ["le fanau amio Atua;", "the born conduct God"], ["o lenei,", "this"], ["ia faaeteete outou", "to faaeteete you (all)"], ["i o outou loto,", "in of you (all) heart"], ["ina ne'i faa'ole'ole", "let now deceit"], ["se tasi", "a one"], ["i lana avā", "in his wife"], ["na fai", "make"], ["a o taulealea.", "but of young man"]]},
  {num:16,words:[["Auā ou te 'ino'ino", "for I hate"], ["i le alei,", "in the to drive"], ["ua fetalai mai ai Ieova", "said the LORD"], ["le Atua o Isaraelu;", "God Israel"], ["auā ua ufiufi e ia", "for covering by him"], ["lona ofu", "his garment"], ["i le faasaua,", "in the to be oppressive"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["o le mea lea ia", "therefore to"], ["outou faaeteete ai", "you (all) faaeteete"], ["i o outou loto,", "in of you (all) heart"], ["a e aua tou te faa'ole'ole.", "but to for second person plural deceit"]]},
  {num:17,words:[["Ua outou faatiga ia", "you (all) a to"], ["Ieova i", "the LORD in"], ["a outou upu;", "but you (all) word"], ["a ua outou fai mai,", "but you (all) said"], ["Ua matou faatiga ia te ia", "we (excl) a to him"], ["i ni", "in some"], ["a? Ua faatiga ia te ia", "of a to him"], ["ina ua outou fai ane.", "let you (all) make"], ["O i latou uma o", "them all of"], ["e fai mea leaga,", "to make thing evil"], ["e lelei", "to good"], ["i latou", "them"], ["i luma o Ieova,", "before the LORD"], ["ua fiafia foi o ia", "competition also he"], ["ia i latou;", "to them"], ["pe faapea ane outou", "whether thus you (all)"], [",", ","], ["O ifea", "where?"], ["le Atua,", "God"], ["o lē faamasino?", "not a judge"]]},
];
renderVerseSet(_mal_ch_2_Verses, 'mal-ch2-verses');

var _mal_ch_3_Verses = [
  {num:1,words:[["Faauta,", "behold"], ["ou te tuuina atu la'u sāvali,", "I will give my sāvali"], ["na te sauni", "he he who beg^ins the game"], ["le ala", "the way"], ["i o'u luma;", "before me"], ["e faafuasei foi", "by faafuasei also"], ["ona oo mai", "and came"], ["i lona malumalu", "in his temple"], ["o le Alii,", "the Lord"], ["o le", "the"], ["ua sailia e outou,", "sought by you (all)"], ["o le Agelu lava lea", "the angel indeed"], ["o le feagaiga,", "the covenant"], ["o le", "the"], ["ua outou naunau", "you (all) desire"], ["i ai;", "therein"], ["faauta,", "behold"], ["e afio mai lava o ia,", "to dwell (respectful) from indeed he"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:2,words:[["A o ai", "but of"], ["se na te lavā tali", "a he lavā respond"], ["le aso", "the day"], ["o lona afio", "his dwell (respectful)"], ["mai? o ai foi", "from of also"], ["se na te tulai", "a he arose up"], ["pe a faaalia", "whether but revealed"], ["mai o ia? auā o ia", "from he for he"], ["e tusa ma le afi", "according to the fire"], ["a lē tunu auro;", "but not roast gold"], ["e tusa foi", "to according to also"], ["ma le moli", "and the moli"], ["a lē tāofu;", "but not tāofu"]]},
  {num:3,words:[["e nofo o ia,", "to dwell he"], ["o lē tunu", "not roast"], ["ma faamamā", "and faamamā"], ["i le ario;", "in the silver"], ["na te faamamāina", "he faamamāina"], ["le fanauga", "the children"], ["a Levi,", "of Levi"], ["na te faate'a ese foi", "he faate'a away also"], ["le eleele ia te", "the earth unto"], ["i latou", "them"], ["e pei o le auro", "like the gold"], ["ma le ario;", "and the silver"], ["latou te avatu ai ia", "they give away to"], ["Ieova le taulaga", "the LORD the offering"], ["e fai", "to make"], ["i le amiotonu.", "in the righteous"]]},
  {num:4,words:[["Ona mālie ai lea ia", "and mālie to"], ["Ieova o le taulaga", "the LORD the offering"], ["a Iuta", "of Judas"], ["ma Ierusalema,", "and Jerusalem"], ["e pei o aso", "to like of day"], ["o le vavau,", "the ancient times"], ["e pei o tausaga anamua.", "to like of year ancient"]]},
  {num:5,words:[["Ou te faalatalata foi ia te outou", "I draw near also unto you"], ["i le faamasinoga;", "in the judgment"], ["e vave foi", "to quick also"], ["ona fai", "and make"], ["o a'u", "I am"], ["ma molimau", "and a witness"], ["i e fai togafiti faataulāitu,", "in to make heal faataulāitu"], ["ma ē mulilulua,", "and who whoring"], ["ma ē tauto pepelo,", "and who to take an oath false"], ["ma ē faasaua", "and who to be oppressive"], ["i le taui", "in the a reward"], ["o le auauna tauia,", "the servant recompense"], ["o le fafine", "the woman"], ["ua oti lana tane,", "die his man"], ["ma le", "and the"], ["ua mātuaoti,", "mātuaoti"], ["atoa ma ē faapioina", "and who faapioina"], ["le faamasinoga", "the judgment"], ["o le tagata ese;", "man away"], ["ua latou", "they"], ["le matatau foi ia te au,", "the fear also unto me"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:6,words:[["Auā o a'u", "for I am"], ["o Ieova,", "the LORD"], ["ou te", "I"], ["le liliu;", "the turned"], ["o le mea lea", "therefore"], ["ua le faaumatia ai outou", "not destroyed you (all)"], ["le fanauga", "the children"], ["a Iakopo.", "of James"]]},
  {num:7,words:[["Talu mai aso o outou", "since from day of you (all)"], ["tamā,", "father"], ["ua outou tete'a ese ai", "you (all) light colored : as away"], ["i a'u tulafono,", "in I law"], ["ma outou", "with you"], ["le tausiusi", "the obey"], ["i ai.", "therein"], ["Foi mai ia ia te au,", "return to him I"], ["ona ou foi atu lea", "and I also"], ["ia te outou,", "unto you"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"], ["A ua outou fai mai,", "but you (all) said"], ["Matou te foi atu", "we (excl) also"], ["ma ni", "and some"], ["a?", "but"]]},
  {num:8,words:[["Pe faoa", "whether seized captive"], ["e le tagata mea", "by the man thing"], ["a le Atua?", "of God"], ["a o outou,", "but of you (all)"], ["ua outou faoa a'u", "you (all) seized captive I"], ["mea.", "thing"], ["A ua outou fai mai,", "but you (all) said"], ["Ni a ea au", "some but to rise (as a diver to the sur- I"], ["mea ua matou faoa?", "thing we (excl) seized captive"], ["Ua outou faoa mea", "you (all) seized captive thing"], ["e sefulu a'i", "by ten"], ["a outou mea,", "but you (all) thing"], ["atoa ma taulaga.", "and offering"]]},
  {num:9,words:[["Ua matuā faafanoina outou,", "exceedingly faafanoina you (all)"], ["o le nuu uma lava,", "the nation all indeed"], ["auā ua outou faoa a'u", "for you (all) seized captive I"], ["mea.", "thing"]]},
  {num:10,words:[["Ina aumaia mea", "let bring here thing"], ["e sefulu a'i", "by ten"], ["a outou mea uma lava", "but you (all) all things"], ["i le fale", "in the house"], ["e tuu ai mea;", "to put thing"], ["ina ia", "so that"], ["i ai mea", "therein thing"], ["e 'ai", "to eat"], ["i lo'u fale;", "in my house"], ["ma ia outou tofotofo", "and to you (all) to try"], ["mai ai ia te au", "from unto me"], ["i lenei mea,", "in this thing"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["pe ou te", "whether I"], ["le toina pupuni", "the toina shut"], ["o le lagi", "Heaven"], ["mo outou,", "for you"], ["ma sasaa atu", "and plurzH x)^ saasaa"], ["le manuia", "the peace"], ["mo outou,", "for you"], ["ina seia silisili", "until very much"], ["ona tele.", "and great"]]},
  {num:11,words:[["Ou te aoai atu,", "I chastise"], ["ona o outou,", "because of you (all)"], ["le na te 'aina mea;", "the he edible thing"], ["na te", "he"], ["le faaumatia", "the destroyed"], ["le fua", "the fruit"], ["o lo outou laueleele;", "your ground"], ["e fua mai foi", "yielding fruit also"], ["le vine", "the vine"], ["i o outou fanua,", "in of you (all) land"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:12,words:[["E faaamuia foi ia te outou", "by faaamuia also unto you"], ["e nuu uma lava;", "to nation all indeed"], ["auā e fai outou", "for to make you (all)"], ["ma nuu", "and nation"], ["e moomia,", "by moomia"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:13,words:[["Ua mamafa", "heavy"], ["a outou upu ia te au,", "but you (all) word unto me"], ["ua fetalai mai ai Ieova;", "said the LORD"], ["a ua outou fai mai,", "but you (all) said"], ["Se a", "a but"], ["sa matou upu", "we (excl) word"], ["ua fai atu ai ia te oe?", "said to unto you"]]},
  {num:14,words:[["Ua outou fai ane,", "you (all) make"], ["E le aoga", "by the useful"], ["ona auauna", "and servant"], ["i le Atua;", "in the God"], ["se a foi", "a but also"], ["se mea", "a thing"], ["ua maua", "received"], ["ina ua tatou tausiusi", "let we (incl) obey"], ["i ana sauniga,", "in his preparation"], ["ma tatou feoai", "and we (incl) feoai"], ["ma ofu eleelea", "and garment eleelea"], ["i luma o Ieova o 'au?", "before the LORD I"]]},
  {num:15,words:[["O lenei,", "this"], ["ua tatou faaamuia", "we (incl) faaamuia"], ["i e faamaualuluga;", "in by faamaualuluga"], ["ua atiina", "atiina"], ["ae foi", "but also"], ["e ua fai amio leaga;", "by make iniquity"], ["ua latou tofotofo lava", "they to try indeed"], ["i le Atua,", "in the God"], ["a e sao", "but to the appointed portion of"], ["i latou.", "them"]]},
  {num:16,words:[["Ona fetautalatalai lea", "and fetautalatalai"], ["e na matatau ia", "by fear to"], ["Ieova;", "the LORD"], ["ua liliu mai foi", "turned from also"], ["e Ieova", "the LORD"], ["ona fofoga ,", "and face"], ["ma ua faafofoga", "and listen"], ["mai;", "from"], ["ona tusia lea", "and written"], ["o le tusi", "the book"], ["e faamanatu", "to to remind"], ["i ona luma,", "before him"], ["mo e matatau ia", "for to fear to"], ["Ieova,", "the LORD"], ["ma mafaufau", "and think"], ["i lona suafa.", "in his name"]]},
  {num:17,words:[["E fai foi", "to make also"], ["i latou ma'u oloa tāua,", "them opinion goods tāua"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au,", "I"], ["i le aso", "in the day"], ["ua ou tofia;", "I chosen"], ["ou te alofa foi ia te", "I love also unto"], ["i latou,", "them"], ["e pei ona", "as"], ["alofa o le tagata", "love man"], ["i lona atalii", "in his son"], ["ua auauna ia te ia.", "servant to him"]]},
  {num:18,words:[["Ona outou toe iloa lea", "and you (all) again known"], ["e eseese lē amiotonu", "to divided not righteous"], ["ma lē amio leaga;", "and not iniquity"], ["e ese", "to away"], ["le ua auauna", "the servant"], ["i le Atua,", "in the God"], ["ma le", "and the"], ["ua le auauna ia te ia.", "not servant to him"]]},
];
renderVerseSet(_mal_ch_3_Verses, 'mal-ch3-verses');

var _mal_ch_4_Verses = [
  {num:1,words:[["Auā faauta,", "for behold"], ["o le a oo", "what oo"], ["mai le aso", "from the day"], ["e mu ai pei", "by mu like"], ["se umu;", "a oven"], ["ona fai ai lea", "and make"], ["ma tagutugutu o saito o", "and tagutugutu of wheat of"], ["e faamaualuluga uma,", "by faamaualuluga all"], ["atoa ma ē fai amio leaga uma;", "and who make iniquity all"], ["e susunuina foi", "to burned also"], ["i latou", "them"], ["i le aso", "in the day"], ["o le a oo", "what oo"], ["mai,", "from"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["e le faatoeina ai", "by the faatoeina"], ["mo i latou", "for them"], ["se aa po", "a aa night"], ["o se la laau.", "a la tree"]]},
  {num:2,words:[["A o outou", "but of you (all)"], ["o e matatau", "who fear"], ["i lo'u igoa,", "in my name"], ["e alu", "to go"], ["ae ia te outou", "but unto you"], ["le La", "the La"], ["o le amiotonu;", "the righteous"], ["e i ai foi", "by therein also"], ["le mea", "the thing"], ["e malolo ai", "to rest"], ["i ona apaau;", "in then a wing"], ["e o atu foi outou", "by of also you (all)"], ["ma osooso,", "and osooso"], ["pei o tamai povi", "like of son cattle"], ["mai le fale povi.", "from the house cattle"]]},
  {num:3,words:[["Ona outou solia lea o", "and you (all) despised of"], ["e amio leaga;", "to iniquity"], ["auā e fai", "for to make"], ["i latou", "them"], ["ma efuefu", "and dust"], ["i lalo o outou", "under you (all)"], ["alofivae i le aso", "alofivae in the day"], ["ua ou tofia,", "I chosen"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:4,words:[["Ia outou manatunatu", "to you (all) meditate"], ["i le tulafono", "in the law"], ["a Mose la'u auauna,", "of Moses my servant"], ["na ou poloai atu ai", "I command"], ["ia te ia", "to him"], ["i Horepa ia Isaraelu uma,", "in Horepa to Israel all"], ["o tulafono", "law"], ["ma faamasinoga.", "and judgment"]]},
  {num:5,words:[["Faauta,", "behold"], ["ou te auina atu ia te outou", "I sent unto you"], ["o Elia", "Elijah"], ["le perofeta,", "the prophet"], ["a o lei oo", "but of not oo"], ["mai le aso o Ieova", "from the day the LORD"], ["e sili,", "to most"], ["ma le matautia.", "and the fearful"]]},
  {num:6,words:[["Na te faaliliuina loto o mātua", "he faaliliuina heart of mātua"], ["i fanau,", "in born"], ["ma loto o fanau", "and heart of born"], ["i o latou mātua;", "in of they mātua"], ["ne'i ou alu atu,", "now I go away"], ["ma ou taia", "and I struck"], ["le nuu", "the nation"], ["i le faafanoga.", "in the destruction"]]},
];
renderVerseSet(_mal_ch_4_Verses, 'mal-ch4-verses');

})();