(function() {
var mal_ch_1_Verses = [
  {num:1,words:[["O le avega o le afioga a Ieova ia Isaraelu na aumaia e Malaki.", "The burden of the word of the LORD to Israel by Malachi."]]},
  {num:2,words:[["Ua ou alofa atu ia te outou,", "I have loved you,"], ["ua fetalai mai ai Ieova;", "saith the LORD. Yet ye say,"], ["a ua outou fai mai, Ua e alofa mai ia i matou i ni a? E le uso ea Esau ma Iakapo? ua fetalai mai ai Ieova;", "Wherein hast thou loved us? Was not Esau Jacob's brother? saith the LORD:"], ["a ua ou alofa ia Iakopo,", "yet I loved Jacob,"]]},
  {num:3,words:[["ma ou 'ino'ino ia Esau; ua faia foi e a'u ona mauga ma mea tuufua,", "And I hated Esau,"], ["ua faia foi lona tofi ma fale i mea gaogao.", "and laid his mountains and his heritage waste for the dragons of the wilderness."]]},
  {num:4,words:[["Ua fai mai Etoma,", "Whereas Edom saith,"], ["Ua faatafunaina i matou,", "We are impoverished,"], ["a e matou te toe faia fale ua masofasofa;", "but we will return and build the desolate places;"], ["o le mea lea,", "thus saith the LORD of hosts,"], ["o loo faapea ona fetalai mai ai o Ieova o 'au, Latou te faia,", "They shall build,"], ["a o a'u,", "but I will throw down;"], ["ou te lepetia,", "and they shall call them,"], ["e ta'ua i latou,", "The border of wickedness,"], ["O le laueleele o e amio leaga,", "and,"], ["ma Le nuu e toasa i ai Ieova e faavavau.", "The people against whom the LORD hath indignation for ever."]]},
  {num:5,words:[["E vaai foi i ai o outou lava mata,", "And your eyes shall see,"], ["ona outou faapea ai lea,", "and ye shall say,"], ["Ia viia Ieova mai le laueleele o Isaraelu.", "The LORD will be magnified from the border of Israel."]]},
  {num:6,words:[["E ava le atalii i lona tamā,", "A son honoureth his father,"], ["e ava foi le auauna i lona alii;", "and a servant his master:"], ["afai o a'u o le tamā,", "if then I be a father,"], ["o ifea ni o'u ava? afai foi o a'u o le alii,", "where is mine honour? and if I be a master, where is my fear? saith the LORD of hosts unto you,"], ["o ifea lo'u matautia? ua fetalai mai ai Ieova o 'au ia te outou faitaulaga o e 'ino'ino i lo'u igoa;", "O priests,"], ["a ua outou fai mai,", "that despise my name. And ye say,"], ["Ua matou ino'ino i lou suafa i ni a?", "Wherein have we despised thy name?"]]},
  {num:7,words:[["Ua 'ino'ino ina ua outou au mai o mea e 'ai ua leaga i la'u fata faitaulaga;", "Ye offer polluted bread upon mine altar;"], ["a ua outou fai mai,", "and ye say,"], ["Ua leaga oe ia te i matou i ni a? Ua leaga ina ua outou fai ane, O le laoai a Ieova,", "Wherein have we polluted thee? In that ye say,"], ["o le mea faatauvaa lava lea.", "The table of the LORD is contemptible."]]},
  {num:8,words:[["A outou aumaia le mea tauaso e fai ma taulaga,", "And if ye offer the blind for sacrifice,"], ["e le leaga ea? A outou aumaia le mea pipili ma le mea e ma'i,", "is it not evil? and if ye offer the lame and sick,"], ["e le leaga ea? Se'i avatu ia i le alii e pule ia te oe;", "is it not evil? offer it now unto thy governor; will he be pleased with thee,"], ["pe fiafia mai ea o ia ia te oe? pe talia mai oe e ia? ua fetalai mai ai Ieova o 'au.", "or accept thy person? saith the LORD of hosts."]]},
  {num:9,words:[["O lenei,", "And now,"], ["ia outou ole atu i luma o le Atua ina ia alofa mai o ia ia te i tatou;", "I pray you,"], ["ua tupu mai ia te outou lenei mea;", "beseech God that he will be gracious unto us: this hath been by your means:"], ["pe na te talia mai ea outou? ua fetalai mai ai Ieova o 'au.", "will he regard your persons? saith the LORD of hosts."]]},
  {num:10,words:[["O ai lava so outou na te punitia fua faitotoa? Tou te le tafu fua le afi i la'u fata faitaulaga;", "Who is there even among you that would shut the doors for nought? neither do ye kindle fire on mine altar for nought. I have no pleasure in you,"], ["e leai lava so'u fiafia ia te outou, ua fetalai mai ai Ieova o 'au;", "saith the LORD of hosts,"], ["ou te le talia foi se taulaga ai o outou lima.", "neither will I accept an offering at your hand."]]},
  {num:11,words:[["Auā e fua mai i le mea e alu ae ai le la,", "For from the rising of the sun even unto the going down of the same my name shall be great among the Gentiles;"], ["e oo i le mea e alu ifo ai, e viia ai lo'u igoa i nuu ese;", "and in every place incense shall be offered unto my name,"], ["e aumaia foi le mea manogi e mu i lo'u igoa i nuu uma lava,", "and a pure offering:"], ["atoa ma le taulaga lelei; auā e viia lo'u igoa i nuu ese,", "for my name shall be great among the heathen,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:12,words:[["A o outou,", "But ye have profaned it,"], ["ua outou faaleagaina ai,", "in that ye say,"], ["ina ua outou fai ane, Ua leaga le laoai a Ieova;", "The table of the LORD is polluted;"], ["mōna fua,", "and the fruit thereof,"], ["o ana mea e 'ai lea ,", "even his meat,"], ["o le mea faatauvaa lava.", "is contemptible."]]},
  {num:13,words:[["Ua outou fai ane foi,", "Ye said also,"], ["Aue,", "Behold, what a weariness is it! and ye have snuffed at it,"], ["o le mea tiga naua! ma outou 'ino'ino i ai ua fetalai mai ai Ieova o 'au;", "saith the LORD of hosts;"], ["ua outou aumaia foi le mea ua faoa,", "and ye brought that which was torn,"], ["ma le mea pipili,", "and the lame,"], ["ma le mea e ma'i;", "and the sick; thus ye brought an offering:"], ["ua outou au mai ai ma taulaga? Ou te talia ea lea mea ai o outou lima? ua fetalai mai ai Ieova.", "should I accept this of your hand? saith the LORD."]]},
  {num:14,words:[["A ia faafanoina le tagata pepelo ua i ai le poa i lona lafu,", "But cursed be the deceiver,"], ["a ua tauto o ia ma fai taulaga i le Alii i le mea leaga;", "which hath in his flock a male, and voweth,"], ["auā o le Tupu sili lava a'u,", "and sacrificeth unto the Lord a corrupt thing:"], ["ua fetalai mai ai Ieova o 'au;", "for I am a great King, saith the LORD of hosts,"], ["e matautia lava lo'u igoa i nuu ese.", "and my name is dreadful among the heathen."]]},
];
renderVerseSet(mal_ch_1_Verses, 'mal-ch1-verses');

var mal_ch_2_Verses = [
  {num:1,words:[["O lenei foi,", "And now, O ye priests,"], ["ua ia te outou le au faitaulaga lenei poloaiga.", "this commandment is for you."]]},
  {num:2,words:[["Afai tou te le faalogo mai,", "If ye will not hear,"], ["afai foi tou te le mafaufau ina ia aumaia le viiga i lo'u igoa,", "and if ye will not lay it to heart, to give glory unto my name,"], ["ua fetalai mai ai Ieova o 'au,", "saith the LORD of hosts,"], ["ona ou auina atu ai lea o le faafanoga ia te outou,", "I will even send a curse upon you,"], ["ma ou faafanoina mea tou te manuia ai;", "and I will curse your blessings:"], ["a ua ou faafanoina lava;", "yea, I have cursed them already,"], ["auā na outou le mafaufau i ai .", "because ye do not lay it to heart."]]},
  {num:3,words:[["Faauta,", "Behold,"], ["ou te aoai atu i le fua saito ona o outou;", "I will corrupt your seed,"], ["ou te palasi foi le otaota o manu i o outou mata,", "and spread dung upon your faces,"], ["o le otaota o taulaga o a outou tausamiga,", "even the dung of your solemn feasts;"], ["e aveesea foi outou faatasi ma lea mea.", "and one shall take you away with it."]]},
  {num:4,words:[["Tou te iloa ai,", "And ye shall know that I have sent this commandment unto you,"], ["ua ou avatu lenei poloaiga ia te outou; auā sa ia Levi la'u feagaiga,", "that my covenant might be with Levi,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:5,words:[["Sa ia te ia la'u feagaiga o i ai le ola ma le manuia;", "My covenant was with him of life and peace;"], ["na a'u avatu ia mea ia te ia ona o lona mata'u na mata'u ai o ia ia te au;", "and I gave them to him for the fear wherewith he feared me,"], ["ua ia matuā mata'u i lo'u igoa.", "and was afraid before my name."]]},
  {num:6,words:[["O le mataupu o le faamaoni sa i lona gutu lea;", "The law of truth was in his mouth,"], ["na le iloa foi se mea le tonu i ona laugutu;", "and iniquity was not found in his lips:"], ["na savavali faatasi ma a'u i le amio filemu ma le amio sa'o;", "he walked with me in peace and equity,"], ["na ia faaliliuina foi ē toatele nai le amioletonu.", "and did turn many away from iniquity."]]},
  {num:7,words:[["Auā o laugutu o le faitaulaga e tausia ai le poto,", "For the priest's lips should keep knowledge,"], ["latou te sailia foi le tulafono ai lona gutu;", "and they should seek the law at his mouth:"], ["auā o le sāvali o ia a Ieova o 'au.", "for he is the messenger of the LORD of hosts."]]},
  {num:8,words:[["A o outou,", "But ye are departed out of the way;"], ["ua outou o ese i le ala,", "ye have caused many to stumble at the law;"], ["ma outou faatausuai i e toatele i le tulafono; ua leaga ia te outou le feagaiga a Levi,", "ye have corrupted the covenant of Levi,"], ["na fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:9,words:[["O a'u foi,", "Therefore have I also made you contemptible and base before all the people,"], ["ua ou tuuina atu outou ia inosia ma ta'ufaatauvaaina outou e le nuu uma, e pei ona outou le tausi i o'u ala,", "according as ye have not kept my ways,"], ["ma outou faailogaina tagata i le tulafono.", "but have been partial in the law."]]},
  {num:10,words:[["E le ua toatasi ea le Tamā o i tatou uma lava. E le faia ea i tatou e le Atua e toatasi? Pe se a le mea ua tatou faa'ole'ole ai le tasi i le tasi i lo tatou soli o le feagaiga a o tatou tamā?", "Have we not all one father? hath not one God created us? why do we deal treacherously every man against his brother, by profaning the covenant of our fathers?"]]},
  {num:11,words:[["Ua faa'ole'ole Iuta,", "Judah hath dealt treacherously,"], ["ua faia foi i Isaraelu ma Ierusalema le mea e inosia;", "and an abomination is committed in Israel and in Jerusalem;"], ["auā ua solia e Iuta le mea ua paia ia Ieova, o le mea ua ia alofaina;", "for Judah hath profaned the holiness of the LORD which he loved,"], ["ua ia fai avā foi i le afafine o le atua ese.", "and hath married the daughter of a strange god."]]},
  {num:12,words:[["E vavaeeseina e Ieova le tagata ua faia lena mea ,", "The LORD will cut off the man that doeth this,"], ["o le ua mataala,", "the master and the scholar,"], ["ma le ua tali atu ai fale ie o Iakopo;", "out of the tabernacles of Jacob,"], ["atoa ma le ua avatu le taulaga ia Ieova o 'au.", "and him that offereth an offering unto the LORD of hosts."]]},
  {num:13,words:[["Ua atu lua ona faia e outou o lenei mea,", "And this have ye done again,"], ["o loo liloia ai le fata faitaulaga o Ieova i loimata,", "covering the altar of the LORD with tears,"], ["o le tagi,", "with weeping,"], ["ma le auega;", "and with crying out,"], ["o le mea lea ua le toe silafia ai la outou taulaga,", "insomuch that he regardeth not the offering any more,"], ["e le talileleia foi mai o outou lima.", "or receiveth it with good will at your hand."]]},
  {num:14,words:[["A ua outou fai mai,", "Yet ye say,"], ["Aisea foi? Auā o Ieova,", "Wherefore? Because the LORD hath been witness between thee and the wife of thy youth,"], ["o ia ua fai ma molimau ia te oe ma lau avā sa e fai a o ē taulealea, o le ua e faa'ole'ole i ai;", "against whom thou hast dealt treacherously:"], ["a o ia sa lua mafuta,", "yet is she thy companion,"], ["o le avā foi o ia o lau feagaiga.", "and the wife of thy covenant."]]},
  {num:15,words:[["Na ia le faia ea le toatasi? A ua ia te ia foi ona toe o le agaga. Se a foi ua toatasi ai? Ina ia saili le fanau amio Atua; o lenei,", "And did not he make one? Yet had he the residue of the spirit. And wherefore one? That he might seek a godly seed. Therefore take heed to your spirit,"], ["ia faaeteete outou i o outou loto, ina ne'i faa'ole'ole se tasi i lana avā na fai a o taulealea.", "and let none deal treacherously against the wife of his youth."]]},
  {num:16,words:[["Auā ou te 'ino'ino i le alei,", "For the LORD,"], ["ua fetalai mai ai Ieova le Atua o Isaraelu;", "the God of Israel,"], ["auā ua ufiufi e ia lona ofu i le faasaua,", "saith that he hateth putting away: for one covereth violence with his garment,"], ["ua fetalai mai ai Ieova o 'au;", "saith the LORD of hosts:"], ["o le mea lea ia outou faaeteete ai i o outou loto,", "therefore take heed to your spirit,"], ["a e aua tou te faa'ole'ole.", "that ye deal not treacherously."]]},
  {num:17,words:[["Ua outou faatiga ia Ieova i a outou upu; a ua outou fai mai, Ua matou faatiga ia te ia i ni a? Ua faatiga ia te ia ina ua outou fai ane.", "Ye have wearied the LORD with your words."], ["O i latou uma o e fai mea leaga,", "Yet ye say,"], ["e lelei i latou i luma o Ieova,", "Wherein have we wearied him? When ye say,"], ["ua fiafia foi o ia ia i latou;", "Every one that doeth evil is good in the sight of the LORD,"], ["pe faapea ane outou ,", "and he delighteth in them;"], ["O ifea le Atua,", "or,"], ["o lē faamasino?", "Where is the God of judgment?"]]},
];
renderVerseSet(mal_ch_2_Verses, 'mal-ch2-verses');

var mal_ch_3_Verses = [
  {num:1,words:[["Faauta,", "Behold,"], ["ou te tuuina atu la'u sāvali,", "I will send my messenger,"], ["na te sauni le ala i o'u luma;", "and he shall prepare the way before me:"], ["e faafuasei foi ona oo mai i lona malumalu o le Alii,", "and the Lord,"], ["o le ua sailia e outou,", "whom ye seek, shall suddenly come to his temple,"], ["o le Agelu lava lea o le feagaiga,", "even the messenger of the covenant,"], ["o le ua outou naunau i ai;", "whom ye delight in:"], ["faauta,", "behold,"], ["e afio mai lava o ia,", "he shall come,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:2,words:[["A o ai se na te lavā tali le aso o lona afio mai? o ai foi se na te tulai pe a faaalia mai o ia? auā o ia e tusa ma le afi a lē tunu auro;", "But who may abide the day of his coming? and who shall stand when he appeareth? for he is like a refiner's fire,"], ["e tusa foi ma le moli a lē tāofu;", "and like fullers' sope:"]]},
  {num:3,words:[["e nofo o ia,", "And he shall sit as a refiner and purifier of silver:"], ["o lē tunu ma faamamā i le ario;", "and he shall purify the sons of Levi,"], ["na te faamamāina le fanauga a Levi, na te faate'a ese foi le eleele ia te i latou e pei o le auro ma le ario;", "and purge them as gold and silver,"], ["latou te avatu ai ia Ieova le taulaga e fai i le amiotonu.", "that they may offer unto the LORD an offering in righteousness."]]},
  {num:4,words:[["Ona mālie ai lea ia Ieova o le taulaga a Iuta ma Ierusalema,", "Then shall the offering of Judah and Jerusalem be pleasant unto the LORD,"], ["e pei o aso o le vavau,", "as in the days of old,"], ["e pei o tausaga anamua.", "and as in former years."]]},
  {num:5,words:[["Ou te faalatalata foi ia te outou i le faamasinoga;", "And I will come near to you to judgment;"], ["e vave foi ona fai o a'u ma molimau i e fai togafiti faataulāitu,", "and I will be a swift witness against the sorcerers,"], ["ma ē mulilulua,", "and against the adulterers,"], ["ma ē tauto pepelo,", "and against false swearers,"], ["ma ē faasaua i le taui o le auauna tauia,", "and against those that oppress the hireling in his wages,"], ["o le fafine ua oti lana tane,", "the widow,"], ["ma le ua mātuaoti,", "and the fatherless,"], ["atoa ma ē faapioina le faamasinoga o le tagata ese;", "and that turn aside the stranger from his right,"], ["ua latou le matatau foi ia te au,", "and fear not me,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:6,words:[["Auā o a'u o Ieova,", "For I am the LORD,"], ["ou te le liliu;", "I change not;"], ["o le mea lea ua le faaumatia ai outou le fanauga a Iakopo.", "therefore ye sons of Jacob are not consumed."]]},
  {num:7,words:[["Talu mai aso o outou tamā, ua outou tete'a ese ai i a'u tulafono,", "Even from the days of your fathers ye are gone away from mine ordinances,"], ["ma outou le tausiusi i ai.", "and have not kept them."], ["Foi mai ia ia te au,", "Return unto me,"], ["ona ou foi atu lea ia te outou,", "and I will return unto you,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."], ["A ua outou fai mai,", "But ye said,"], ["Matou te foi atu ma ni a?", "Wherein shall we return?"]]},
  {num:8,words:[["Pe faoa e le tagata mea a le Atua? a o outou, ua outou faoa a'u mea.", "Will a man rob God? Yet ye have robbed me."], ["A ua outou fai mai, Ni a ea au mea ua matou faoa? Ua outou faoa mea e sefulu a'i a outou mea,", "But ye say,"], ["atoa ma taulaga.", "Wherein have we robbed thee? In tithes and offerings."]]},
  {num:9,words:[["Ua matuā faafanoina outou,", "Ye are cursed with a curse:"], ["o le nuu uma lava,", "for ye have robbed me,"], ["auā ua outou faoa a'u mea.", "even this whole nation."]]},
  {num:10,words:[["Ina aumaia mea e sefulu a'i a outou mea uma lava i le fale e tuu ai mea;", "Bring ye all the tithes into the storehouse,"], ["ina ia i ai mea e 'ai i lo'u fale;", "that there may be meat in mine house,"], ["ma ia outou tofotofo mai ai ia te au i lenei mea,", "and prove me now herewith,"], ["ua fetalai mai ai Ieova o 'au;", "saith the LORD of hosts,"], ["pe ou te le toina pupuni o le lagi mo outou,", "if I will not open you the windows of heaven,"], ["ma sasaa atu le manuia mo outou,", "and pour you out a blessing,"], ["ina seia silisili ona tele.", "that there shall not be room enough to receive it."]]},
  {num:11,words:[["Ou te aoai atu, ona o outou,", "And I will rebuke the devourer for your sakes,"], ["le na te 'aina mea;", "and he shall not destroy the fruits of your ground;"], ["na te le faaumatia le fua o lo outou laueleele;", "neither shall your vine cast her fruit before the time in the field,"], ["e fua mai foi le vine i o outou fanua, ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:12,words:[["E faaamuia foi ia te outou e nuu uma lava;", "And all nations shall call you blessed:"], ["auā e fai outou ma nuu e moomia,", "for ye shall be a delightsome land,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:13,words:[["Ua mamafa a outou upu ia te au,", "Your words have been stout against me,"], ["ua fetalai mai ai Ieova; a ua outou fai mai,", "saith the LORD. Yet ye say,"], ["Se a sa matou upu ua fai atu ai ia te oe?", "What have we spoken so much against thee?"]]},
  {num:14,words:[["Ua outou fai ane,", "Ye have said,"], ["E le aoga ona auauna i le Atua;", "It is vain to serve God:"], ["se a foi se mea ua maua ina ua tatou tausiusi i ana sauniga,", "and what profit is it that we have kept his ordinance,"], ["ma tatou feoai ma ofu eleelea i luma o Ieova o 'au?", "and that we have walked mournfully before the LORD of hosts?"]]},
  {num:15,words:[["O lenei,", "And now we call the proud happy;"], ["ua tatou faaamuia i e faamaualuluga;", "yea,"], ["ua atiina ae foi e ua fai amio leaga;", "they that work wickedness are set up;"], ["ua latou tofotofo lava i le Atua,", "yea,"], ["a e sao i latou.", "they that tempt God are even delivered."]]},
  {num:16,words:[["Ona fetautalatalai lea e na matatau ia Ieova;", "Then they that feared the LORD spake often one to another:"], ["ua liliu mai foi e Ieova ona fofoga ,", "and the LORD hearkened,"], ["ma ua faafofoga mai; ona tusia lea o le tusi e faamanatu i ona luma,", "and heard it,"], ["mo e matatau ia Ieova,", "and a book of remembrance was written before him for them that feared the LORD,"], ["ma mafaufau i lona suafa.", "and that thought upon his name."]]},
  {num:17,words:[["E fai foi i latou ma'u oloa tāua,", "And they shall be mine,"], ["ua fetalai mai ai Ieova o 'au,", "saith the LORD of hosts,"], ["i le aso ua ou tofia;", "in that day when I make up my jewels;"], ["ou te alofa foi ia te i latou,", "and I will spare them,"], ["e pei ona alofa o le tagata i lona atalii ua auauna ia te ia.", "as a man spareth his own son that serveth him."]]},
  {num:18,words:[["Ona outou toe iloa lea e eseese lē amiotonu ma lē amio leaga;", "Then shall ye return,"], ["e ese le ua auauna i le Atua,", "and discern between the righteous and the wicked,"], ["ma le ua le auauna ia te ia.", "between him that serveth God and him that serveth him not."]]},
];
renderVerseSet(mal_ch_3_Verses, 'mal-ch3-verses');

var mal_ch_4_Verses = [
  {num:1,words:[["Auā faauta,", "For, behold,"], ["o le a oo mai le aso e mu ai pei se umu;", "the day cometh,"], ["ona fai ai lea ma tagutugutu o saito o e faamaualuluga uma,", "that shall burn as an oven; and all the proud,"], ["atoa ma ē fai amio leaga uma;", "yea,"], ["e susunuina foi i latou i le aso o le a oo mai,", "and all that do wickedly, shall be stubble:"], ["ua fetalai mai ai Ieova o 'au;", "and the day that cometh shall burn them up,"], ["e le faatoeina ai mo i latou se aa po o se la laau.", "saith the LORD of hosts, that it shall leave them neither root nor branch."]]},
  {num:2,words:[["A o outou o e matatau i lo'u igoa, e alu ae ia te outou le La o le amiotonu;", "But unto you that fear my name shall the Sun of righteousness arise with healing in his wings;"], ["e i ai foi le mea e malolo ai i ona apaau;", "and ye shall go forth,"], ["e o atu foi outou ma osooso, pei o tamai povi mai le fale povi.", "and grow up as calves of the stall."]]},
  {num:3,words:[["Ona outou solia lea o e amio leaga;", "And ye shall tread down the wicked;"], ["auā e fai i latou ma efuefu i lalo o outou alofivae i le aso ua ou tofia,", "for they shall be ashes under the soles of your feet in the day that I shall do this,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:4,words:[["Ia outou manatunatu i le tulafono a Mose la'u auauna,", "Remember ye the law of Moses my servant,"], ["na ou poloai atu ai ia te ia i Horepa ia Isaraelu uma,", "which I commanded unto him in Horeb for all Israel,"], ["o tulafono ma faamasinoga.", "with the statutes and judgments."]]},
  {num:5,words:[["Faauta, ou te auina atu ia te outou o Elia le perofeta,", "Behold,"], ["a o lei oo mai le aso o Ieova e sili, ma le matautia.", "I will send you Elijah the prophet before the coming of the great and dreadful day of the LORD:"]]},
  {num:6,words:[["Na te faaliliuina loto o mātua i fanau,", "And he shall turn the heart of the fathers to the children,"], ["ma loto o fanau i o latou mātua; ne'i ou alu atu,", "and the heart of the children to their fathers,"], ["ma ou taia le nuu i le faafanoga.", "lest I come and smite the earth with a curse."]]},
];
renderVerseSet(mal_ch_4_Verses, 'mal-ch4-verses');

})();