(function() {
var mic_ch_1_Verses = [
  {num:1,words:[["O le afioga a Ieova na oo mai ia Mika le Morese i ona po o Iotama,", "The word of the LORD that came to Micah the Morasthite in the days of Jotham,"], ["ma Aasa,", "Ahaz,"], ["ma Esekia,", "and Hezekiah,"], ["o tupu o Iuta,", "kings of Judah,"], ["na ia iloa i mea a Samaria ma Ierusalema.", "which he saw concerning Samaria and Jerusalem."]]},
  {num:2,words:[["Faalogologo mai ia outou nuu uma;", "Hear,"], ["faasaga mai ia le lalolagi e,", "all ye people; hearken,"], ["atoa ma mea ua tumu ai,", "O earth,"], ["seia fai e le Alii o Ieova ana mau ia te outou,", "and all that therein is: and let the Lord GOD be witness against you,"], ["o le Alii lava ai lona malumalu paia.", "the Lord from his holy temple."]]},
  {num:3,words:[["Auā faauta,", "For,"], ["o loo afio mai Ieova ai lona afioga,", "behold,"], ["e afio ifo o ia,", "the LORD cometh forth out of his place, and will come down,"], ["ma soli i mea maualuluga o i le lalolagi.", "and tread upon the high places of the earth."]]},
  {num:4,words:[["E liu suāvai mauga i lalo ia te ia,", "And the mountains shall be molten under him,"], ["e māvaevae vanu,", "and the valleys shall be cleft,"], ["pei o le pulu i le afi,", "as wax before the fire,"], ["faapei o le vai ua tafe ifo i le tofē.", "and as the waters that are poured down a steep place."]]},
  {num:5,words:[["Ona o le solitulafono a Iakopo e oo ai ia mea uma,", "For the transgression of Jacob is all this,"], ["ona o agasala foi a le aiga o Isaraelu. Se a ea le solitulafono a Iakopo? E le o Samaria ea? O a ea foi mea maualuluga a Iuta?", "and for the sins of the house of Israel. What is the transgression of Jacob? is it not Samaria? and what are the high places of Judah? are they not Jerusalem?"]]},
  {num:6,words:[["E le o Ierusalema ea? O le mea lea ou te fai ai Samaria ma faupuegā maa i le fanua,", "Therefore I will make Samaria as an heap of the field,"], ["ma mea e totō ai vine,", "and as plantings of a vineyard:"], ["ou te tuleia foi i lalo i le vanu ona maa,", "and I will pour down the stones thereof into the valley,"], ["ou te faataatitiafuaina ona faavae.", "and I will discover the foundations thereof."]]},
  {num:7,words:[["E nutininiia foi ona tupua ua ta uma,", "And all the graven images thereof shall be beaten to pieces,"], ["e susunuina foi ona taui uma i le afi,", "and all the hires thereof shall be burned with the fire,"], ["ou te faatafunaina foi ona tupua uma;", "and all the idols thereof will I lay desolate:"], ["auā o le taui o le fafine talitane na ia faaputuina ai,", "for she gathered it of the hire of an harlot,"], ["e toe foi atu foi ia mea i le taui o le fafine talitane.", "and they shall return to the hire of an harlot."]]},
  {num:8,words:[["O le mea lea ou te tagitu'i ai,", "Therefore I will wail and howl,"], ["ma ou uio,", "I will go stripped and naked:"], ["ou te fealuai ma le le ofu ma le le lavalavā; ou te tagi pei o luko,", "I will make a wailing like the dragons,"], ["ma ou faanoanoa pei o iaena.", "and mourning as the owls."]]},
  {num:9,words:[["Auā e leaga ona manua;", "For her wound is incurable;"], ["auā ua oo lava i Iuta;", "for it is come unto Judah;"], ["ua pāia lava le faitotoa o lo'u nuu,", "he is come unto the gate of my people,"], ["o Ierusalema lava.", "even to Jerusalem."]]},
  {num:10,words:[["Aua ne'i ta'uatua i Kato,", "Declare ye it not at Gath,"], ["aua ne'i fetagisi i Ako;", "weep ye not at all:"], ["ia e taafili i le efuefu i Petofira.", "in the house of Aphrah roll thyself in the dust."]]},
  {num:11,words:[["Ina ui ane ia e le o lavalavā ma le mā,", "Pass ye away,"], ["o oe na lē mau i Safiri;", "thou inhabitant of Saphir,"], ["e lei alu atu le ua mau i Saanana;", "having thy shame naked: the inhabitant of Zaanan came not forth in the mourning of Beth-ezel;"], ["o le auega a Peteseli e aveeseina ia ia te outou le mea e tu ai o ia.", "he shall receive of you his standing."]]},
  {num:12,words:[["Ua faanoanoa lava le ua mau i Marota ona o le manuia;", "For the inhabitant of Maroth waited carefully for good:"], ["auā ua oo ifo le malaia mai ia Ieova i le faitotoa o Ierusalema.", "but evil came down from the LORD unto the gate of Jerusalem."]]},
  {num:13,words:[["O oe lē mau i Lakisa,", "O thou inhabitant of Lachish,"], ["ia e nonoa le nofoa faataavalevale i le solofanua televave;", "bind the chariot to the swift beast:"], ["(o ia o le amataga o le agasala i le tama fafine a Siona;", "she is the beginning of the sin to the daughter of Zion:"], [") auā ua iloa i totonu ia te oe solitulafono a Isaraelu.", "for the transgressions of Israel were found in thee."]]},
  {num:14,words:[["O le mea lea e te avatu ai se tusi alei ia Morese-Kato;", "Therefore shalt thou give presents to Moresheth-gath:"], ["e fai foi fale o Akasepa ma pepelo i tupu o Isaraelu.", "the houses of Achzib shall be a lie to the kings of Israel."]]},
  {num:15,words:[["I le ma lea,", "Yet will I bring an heir unto thee,"], ["o oe na o lē mau i Maresa, ou te au mai ia te oe o le na te fai oe mona;", "O inhabitant of Mareshah:"], ["e oo lava ia i Atulama le mamalu o Isaraelu.", "he shall come unto Adullam the glory of Israel."]]},
  {num:16,words:[["Ia e tafi lou lauulu ma ia e sele mamā ona o au fanau pele,", "Make thee bald,"], ["ia e faalautele le mea ua tafia pei o le aeto;", "and poll thee for thy delicate children; enlarge thy baldness as the eagle;"], ["auā ua tāfea ese i latou ia te oe.", "for they are gone into captivity from thee."]]},
];
renderVerseSet(mic_ch_1_Verses, 'mic-ch1-verses');

var mic_ch_2_Verses = [
  {num:1,words:[["Oi talofa i e mafaufau i amioletonu,", "Woe to them that devise iniquity,"], ["ma latou saunia mea leaga i o latou moega;", "and work evil upon their beds! when the morning is light,"], ["pe a malama ae le taeao ua latou faia,", "they practise it,"], ["auā ua mafai ia te i latou.", "because it is in the power of their hand."]]},
  {num:2,words:[["Ua latou mananao foi i fanua,", "And they covet fields,"], ["ma latou fao ai faasaua,", "and take them by violence;"], ["atoa ma fale,", "and houses,"], ["ma latou avea;", "and take them away:"], ["ua latou saua atu i le tagata ma lona aiga,", "so they oppress a man and his house,"], ["o le tagata ma lona tofi.", "even a man and his heritage."]]},
  {num:3,words:[["O le mea lea o loo faapea mai ai Ieova,", "Therefore thus saith the LORD;"], ["Faauta,", "Behold,"], ["o loo ou te mafaufau i se mea leaga i lenei lava aiga,", "against this family do I devise an evil,"], ["tou te le mafai ona 'alo ese ai o outou ua;", "from which ye shall not remove your necks;"], ["tou te le savavali foi ma le faasiasia;", "neither shall ye go haughtily:"], ["auā e leaga ia ona po.", "for this time is evil."]]},
  {num:4,words:[["E saunia se faataoto ia te outou i lea aso,", "In that day shall one take up a parable against you,"], ["e pese le pese e aualofa a'i tele lava,", "and lament with a doleful lamentation,"], ["e faapea, Ua matuā faatafunaina i tatou;", "and say,"], ["ua suia e ia le tofi o lo'u nuu;", "We be utterly spoiled:"], ["aue! ua ia aveeseina ai ia te au,", "he hath changed the portion of my people:"], ["ua na tufatufa i o tatou fanua ina ia liliueseina.", "how hath he removed it from me! turning away he hath divided our fields."]]},
  {num:5,words:[["O le mea lea o le a leai ai ia te oe se na te lāfolafoina se maea pe a fai le vili i le faapotopotoga a Ieova.", "Therefore thou shalt have none that shall cast a cord by lot in the congregation of the LORD."]]},
  {num:6,words:[["Ua latou faapea mai i e vavalo mai,", "Prophesy ye not,"], ["Aua ne'i outou vavalo. Latou te le vavalo ia te i latou nei,", "say they to them that prophesy: they shall not prophesy to them,"], ["e le mavae le masiasi.", "that they shall not take shame."]]},
  {num:7,words:[["Oi! o upu faapea a le aiga o Iakopo! E vaivai ea le Agaga o Ieova? O ana ea ia galuega? O a'u upu e le lelei ai ea le ua savali ma le amiotonu?", "O thou that art named the house of Jacob, is the spirit of the LORD straitened? are these his doings? do not my words do good to him that walketh uprightly?"]]},
  {num:8,words:[["A ua tulai lo'u nuu talu mai anamua pei o se ua ita mai lava; ua outou fao le pulupulu atoa ma le ofu tele ia te i latou o e ui ane ma le faatalanoa,", "Even of late my people is risen up as an enemy:"], ["o e ua foi mai i le taua.", "ye pull off the robe with the garment from them that pass by securely as men averse from war."]]},
  {num:9,words:[["Ua outou tulia fafine o lo'u nuu i o latou fale e fiafia i ai;", "The women of my people have ye cast out from their pleasant houses;"], ["ua outou ave ese foi lo'u mamalu i a latou fanau e faavavau.", "from their children have ye taken away my glory for ever."]]},
  {num:10,words:[["Tutū ia i luga outou,", "Arise ye,"], ["ina o ese ia;", "and depart;"], ["auā e le o lo outou malologa lenei;", "for this is not your rest:"], ["ua leaga,", "because it is polluted,"], ["o le mea lea e malaia ai outou,", "it shall destroy you,"], ["e matuā tele foi le malaia.", "even with a sore destruction."]]},
  {num:11,words:[["Ai se tagata e savali e tusa ma lona loto ma le faa'ole'ole e pepelo mai,", "If a man walking in the spirit and falsehood do lie,"], ["e faapea mai ,", "saying,"], ["Ou te vavalo ia te oe i le uaina ma le 'ava;", "I will prophesy unto thee of wine and of strong drink;"], ["e avea lava ia ma perofeta i lenei nuu.", "he shall even be the prophet of this people."]]},
  {num:12,words:[["Iakopo e,", "I will surely assemble,"], ["ou te faapotopoto lava ia te outou uma lava;", "O Jacob,"], ["ou te aofaiina lava e o totoe o Isaraelu,", "all of thee; I will surely gather the remnant of Israel;"], ["ou te faatasia i latou pei o le lafu mamoe i Posara,", "I will put them together as the sheep of Bozrah,"], ["pei o le lafu manu i totonu o le mea e fafaga ai,", "as the flock in the midst of their fold:"], ["latou te soona ualolo ona o le vao tagata.", "they shall make great noise by reason of the multitude of men."]]},
  {num:13,words:[["Ua alu ae i o latou luma le na te lepetia,", "The breaker is come up before them:"], ["ua latou lepeti,", "they have broken up,"], ["ma latou ui ane i le faitotoa,", "and have passed through the gate,"], ["ua latou o atu ai lava,", "and are gone out by it:"], ["e afio atu foi lo latou Tupu i o latou luma,", "and their king shall pass before them,"], ["e muamua foi Ieova ia te i latou.", "and the LORD on the head of them."]]},
];
renderVerseSet(mic_ch_2_Verses, 'mic-ch2-verses');

var mic_ch_3_Verses = [
  {num:1,words:[["Sa a'u faapea atu foi,", "And I said, Hear,"], ["Faafofoga mai ia outou matai o Iakopo,", "I pray you,"], ["ma outou faipule o le aiga o Isaraelu,", "O heads of Jacob,"], ["E le o ia te outou ea ona iloa le faamasinoga?", "and ye princes of the house of Israel; Is it not for you to know judgment?"]]},
  {num:2,words:[["O outou o loo 'ino'ino i mea lelei,", "Who hate the good,"], ["ma fiafia i mea leaga,", "and love the evil;"], ["o loo outou sae ese o latou pa'u,", "who pluck off their skin from off them,"], ["atoa ma aano i o latou ivi.", "and their flesh from off their bones;"]]},
  {num:3,words:[["O e aai foi i tino o lo'u nuu,", "Who also eat the flesh of my people,"], ["ma saeeseina o latou pa'u,", "and flay their skin from off them;"], ["ma gauia o latou ivi,", "and they break their bones, and chop them in pieces,"], ["e vaevaea lava pei o mea e tuu i le ulo,", "as for the pot,"], ["pei o tufaaga foi i totonu o le pani.", "and as flesh within the caldron."]]},
  {num:4,words:[["Ona latou alalaga atu ai lea ia Ieova,", "Then shall they cry unto the LORD,"], ["a e le faafofoga mai ai o ia ia te i latou;", "but he will not hear them:"], ["a e 'alo ese ona fofoga ia te i latou i ia lava ona po,", "he will even hide his face from them at that time,"], ["auā ua leaga lava a latou mea e fai.", "as they have behaved themselves ill in their doings."]]},
  {num:5,words:[["O loo faapea mai Ieova i perofeta o e faasese i lo'u nuu,", "Thus saith the LORD concerning the prophets that make my people err,"], ["o e fēu i o latou nifo,", "that bite with their teeth,"], ["ma latou alalaga atu,", "and cry,"], ["O le manuia;", "Peace;"], ["a o le ua le avane mea i o latou gutu,", "and he that putteth not into their mouths,"], ["latou te sauni lava le taua ia te ia.", "they even prepare war against him."]]},
  {num:6,words:[["O le mea lea e pogia ai outou ma le leai o se mea e vaaia,", "Therefore night shall be unto you, that ye shall not have a vision;"], ["e oo foi le pouliuli ia te outou ma le leai o se iite;", "and it shall be dark unto you,"], ["e goto foi le la i ia perofeta,", "that ye shall not divine;"], ["e pogisa foi le ao ia te i latou.", "and the sun shall go down over the prophets, and the day shall be dark over them."]]},
  {num:7,words:[["Ona masiasi ai lea o tagata vaai,", "Then shall the seers be ashamed,"], ["e fememeai ai foi o e iite;", "and the diviners confounded:"], ["latou te ufiufi foi i a latou 'ava,", "yea,"], ["o i latou uma lava,", "they shall all cover their lips;"], ["auā e leai se tali mai le Atua.", "for there is no answer of God."]]},
  {num:8,words:[["A e peitai o a'u,", "But truly I am full of power by the spirit of the LORD,"], ["e moni lava, ua faatumuina a'u i le mana e le Agaga o Ieova,", "and of judgment,"], ["o le faamasinoga foi,", "and of might,"], ["ma le malosi, e faailoa atu ai ia Iakopo o lana solitulafono,", "to declare unto Jacob his transgression,"], ["e faailoa atu foi ia Isaraelu o lana agasala.", "and to Israel his sin."]]},
  {num:9,words:[["Ina faafofoga mai ia i le mea nei o outou matai o le aiga o Iakopo,", "Hear this,"], ["ma outou faipule o le aiga o Isaraelu,", "I pray you,"], ["o e 'ino'ino i le faamasinoga,", "ye heads of the house of Jacob, and princes of the house of Israel,"], ["ma faapiopio i mea tonu uma;", "that abhor judgment,"], ["o e ati ae Siona i le toto,", "and pervert all equity."]]},
  {num:10,words:[["ma Ierusalema i le amio leaga.", "They build up Zion with blood, and Jerusalem with iniquity."]]},
  {num:11,words:[["O ona matai ua latou faamasino i le fia fai taui,", "The heads thereof judge for reward,"], ["o ana ositaulaga foi ua latou a'oa'o i le fia fai taui,", "and the priests thereof teach for hire,"], ["ma ana perofeta ua latou iite i le fia fai tupe;", "and the prophets thereof divine for money:"], ["a ua latou faalagolago ia Ieova,", "yet will they lean upon the LORD,"], ["ma faapea ane,", "and say,"], ["E le o ia te i tatou ea Ieova? e le oo mai se mea leaga ia te i tatou.", "Is not the LORD among us? none evil can come upon us."]]},
  {num:12,words:[["O le mea lea e fai ai Siona ma fanua e suatia ona o outou,", "Therefore shall Zion for your sake be plowed as a field,"], ["e fai foi Ierusalema ma faupuegāmaa,", "and Jerusalem shall become heaps,"], ["o le mauga foi o i ai le fale e fai lea ma mea maualuga i le vao matua.", "and the mountain of the house as the high places of the forest."]]},
  {num:13,words:[["Ua alu", "go"], ["ae i o latou luma", "but in them before"], ["le", "the"], ["na te lepetia,", "lepetia"], ["ua latou lepeti,", "them lepeti"], ["ma latou ui ane", "and them although"], ["i le faitotoa,", "in the gate"], ["ua latou o atu ai lava,", "them indeed"], ["e afio atu foi lo latou Tupu", "to dwell (respectful) also their grow"], ["i o latou luma,", "before them"], ["e muamua foi le ALII ia te i latou.", "to first also the Lord unto them"], ["O le иpи", "the иpи"], ["e aoai atu 1 alii o le nuu", "by aoai 1 Lord the nation"], ["ma perofeta pepelo", "and prophet false"], ["Sa a'u faapea atu foi,", "I thus also"], ["Faafofoga mai ia outou matai o lakopo,", "listen from to ye all chief lakopo"], ["ma outou faipule o le aiga o Isaraelu,", "and ye all a councillor the family Israel"], ["E le o ia te outou ea", "by the he ye all to rise (as a diver to the sur-"], ["ona iloa", "and known"], ["le faamasinoga?", "the judgment"]]},
];
renderVerseSet(mic_ch_3_Verses, 'mic-ch3-verses');

var mic_ch_4_Verses = [
  {num:1,words:[["A o aso e gata ai e oo ina faatumauina ai le mauga o i ai le fale o Ieova i tumutumu o mauga,", "But in the last days it shall come to pass,"], ["e faamaualugaina foi ia sili i mauga iti,", "that the mountain of the house of the LORD shall be established in the top of the mountains, and it shall be exalted above the hills;"], ["ona gasolo ane lea o nuu i ai.", "and people shall flow unto it."]]},
  {num:2,words:[["E o mai lava nuu ese e tele,", "And many nations shall come,"], ["ma latou faapea ane,", "and say,"], ["O mai ia,", "Come,"], ["tatou o ae ia i le mauga o Ieova,", "and let us go up to the mountain of the LORD,"], ["o le fale foi o le Atua o Iakopo;", "and to the house of the God of Jacob;"], ["e a'oa'o mai ai o ia ia te i tatou i ona ala,", "and he will teach us of his ways,"], ["ona tatou savavali ai lea i ona ala;", "and we will walk in his paths:"], ["auā e alu atu le tulafono mai Siona,", "for the law shall go forth of Zion,"], ["o le afioga foi a Ieova mai Ierusalema.", "and the word of the LORD from Jerusalem."]]},
  {num:3,words:[["E faamasino foi o ia i nuu e tele,", "And he shall judge among many people,"], ["e aoai atu foi i nuu malolosi e mamao;", "and rebuke strong nations afar off;"], ["ona latou tu'i ai lea i a latou pelu e fai ma uamea o suotosina,", "and they shall beat their swords into plowshares,"], ["o latou tao foi e fai ma polo teu vine;", "and their spears into pruninghooks:"], ["e le sii atu foi le pelu e le tasi nuu,", "nation shall not lift up a sword against nation,"], ["latou te le toe a'oa'o foi i taua.", "neither shall they learn war any more."]]},
  {num:4,words:[["A e taitasi ma nofo i lalo o lona vine,", "But they shall sit every man under his vine and under his fig tree;"], ["ma lalo o lona mati; e leai foi se na te faamatau mai;", "and none shall make them afraid:"], ["auā ua faapea ona tŭlei mai ai le siufofoga o Ieova o 'au.", "for the mouth of the LORD of hosts hath spoken it."]]},
  {num:5,words:[["Auā o nuu uma e taitasi ma savali i le igoa o latou atua, o i tatou foi,", "For all people will walk every one in the name of his god,"], ["tatou te savavali i le suafa o Ieova lo tatou Atua e faavavau faavavau lava.", "and we will walk in the name of the LORD our God for ever and ever."]]},
  {num:6,words:[["O loo faapea mai Ieova,", "In that day,"], ["O lea aso ou te faapotopoto ai le nuu ua setusetu,", "saith the LORD,"], ["ou te aofaiina faatasi foi le nuu ua tulia,", "will I assemble her that halteth, and I will gather her that is driven out,"], ["ma le nuu ua ou faatigaina.", "and her that I have afflicted;"]]},
  {num:7,words:[["Ou te faatotoe nisi o le nuu ua setusetu,", "And I will make her that halted a remnant,"], ["ou te faia foi ma nuu malosi e ua tāfea mamao,", "and her that was cast far off a strong nation:"], ["e pule foi Ieova ia te i latou i le mauga o Siona e amata i ona po nei,", "and the LORD shall reign over them in mount Zion from henceforth,"], ["e oo i le faavavau.", "even for ever."]]},
  {num:8,words:[["O oe foi le 'olo o le lafu mamoe,", "And thou,"], ["o le mauga o le tama fafine a Siona,", "O tower of the flock,"], ["e oo mai lava ia te oe,", "the strong hold of the daughter of Zion, unto thee shall it come,"], ["e oo mai lava le muai pule;", "even the first dominion;"], ["e oo mai le malo o le tama fafine a Ierusalema.", "the kingdom shall come to the daughter of Jerusalem."]]},
  {num:9,words:[["O lenei, se a le mea e te alaga tele ai? E leai ea se tupu ia te oe? Ua fano ea lou faipule? ina ua maua oe i tiga pei o se fafine a fanau mai.", "Now why dost thou cry out aloud? is there no king in thee? is thy counsellor perished? for pangs have taken thee as a woman in travail."]]},
  {num:10,words:[["Le tama fafine a Siona e,", "Be in pain,"], ["ina faatiga ia,", "and labour to bring forth,"], ["ma ia fanau mai,", "O daughter of Zion,"], ["pei o le fafine a fanau mai;", "like a woman in travail:"], ["auā e te alu ese nei i le aai a e mau i le vao,", "for now shalt thou go forth out of the city, and thou shalt dwell in the field,"], ["e te oo lava i Papelonia;", "and thou shalt go even to Babylon;"], ["e laveaiina oe i lea mea,", "there shalt thou be delivered;"], ["e laveai Ieova ia te oe i lea mea ai lima o i latou o e ita mai ia te oe.", "there the LORD shall redeem thee from the hand of thine enemies."]]},
  {num:11,words:[["Ua faapotopotoina nei foi o nuu e tele o le a tau ma oe,", "Now also many nations are gathered against thee,"], ["o e faapea ane,", "that say,"], ["Ia leaga o ia;", "Let her be defiled,"], ["se'i vaai foi o tatou mata i Siona.", "and let our eye look upon Zion."]]},
  {num:12,words:[["A o i latou,", "But they know not the thoughts of the LORD,"], ["latou te le iloa manatu o Ieova, latou te le iloa foi lana pule;", "neither understand they his counsel:"], ["auā e faapotopotoina i latou e ia pei o fusi saito i le mea e soli ai saito.", "for he shall gather them as the sheaves into the floor."]]},
  {num:13,words:[["Le tama fafine a Siona e,", "Arise and thresh,"], ["tu ia i luga,", "O daughter of Zion:"], ["ma soli;", "for I will make thine horn iron,"], ["auā ou te faia lou nifo ma uamea, ou te faia foi ou atigivae ma 'apa memea;", "and I will make thy hoofs brass:"], ["e te tu'imomomoina nuu e tele;", "and thou shalt beat in pieces many people:"], ["ou te faatoina foi mo Ieova a latou vete,", "and I will consecrate their gain unto the LORD,"], ["atoa ma a latou oloa mo le Alii o le lalolagi uma.", "and their substance unto the Lord of the whole earth."]]},
  {num:14,words:[["Ou te lepeti foi i au tupua o Asaira", "I lepeti also in I idol asaira"], ["i totonu ia te oe,", "in inside unto you"], ["ma ou faatafunaina ou aai.", "and I faatafunaina I eat"]]},
  {num:15,words:[["Ou te taui atu", "I a reward"], ["ma le ita", "and the angry"], ["e matuā tele", "to very great"], ["i nuu ese o e ua", "in nation away by"], ["le faalogo mai.", "the hearken from"], ["Ua aoai atu le Atua ia te 1 latou", "aoai the God unto 1 them"], ["ona o aтїo eseese", "because of aтїo divided"], ["Ina faalogo mai ia i le mea o loo fetalai mai ai le Ати,", "let hearken from to in the thing said from the ати"], ["Tu ia i luga,", "stand to in above"], ["ina finau atu ia i luma o mauga,", "let finau to in before mountain"], ["ia faalogo foi mauga iti", "to hearken also mountain iti"], ["i lou leo.", "in your voice"]]},
];
renderVerseSet(mic_ch_4_Verses, 'mic-ch4-verses');

var mic_ch_5_Verses = [
  {num:1,words:[["O lenei,", "Now gather thyself in troops,"], ["ina faalaei 'au ia o oe le tama fafine e ana 'au;", "O daughter of troops:"], ["ua ia siosioina i tatou i le taua;", "he hath laid siege against us:"], ["latou te ta i le tootoo le faamasino o Isaraelu i lona alafau.", "they shall smite the judge of Israel with a rod upon the cheek."]]},
  {num:2,words:[["A o oe,", "But thou,"], ["Peteleema-Efarata,", "Beth-lehem Ephratah,"], ["e itiiti oe i afe o Iuta,", "though thou be little among the thousands of Judah,"], ["a e tupu mai ia te oe mo a'u o le na te fai ma faipule ia Isaraelu,", "yet out of thee shall he come forth unto me that is to be ruler in Israel;"], ["o lona tupu mai talu mai anamuā lea,", "whose goings forth have been from of old,"], ["talu mai ona po o le vavau lava.", "from everlasting."]]},
  {num:3,words:[["A e peitai e tuua i latou e ia seia oo i ona po e fanau mai ai o ia o le a fanau;", "Therefore will he give them up, until the time that she which travaileth hath brought forth:"], ["ona toe foi mai ai lea i le fanauga a Isaraelu o e totoe i ona uso.", "then the remnant of his brethren shall return unto the children of Israel."]]},
  {num:4,words:[["E tu foi o ia ma leoleo ia te i latou i le mana o Ieova,", "And he shall stand and feed in the strength of the LORD,"], ["ma le mamalu o le suafa o Ieova lona Atua,", "in the majesty of the name of the LORD his God;"], ["ona latou nofo mau ai lea;", "and they shall abide:"], ["auā o ona po ia e mamalu ai o ia e oo i tuluiga o le lalolagi.", "for now shall he be great unto the ends of the earth."]]},
  {num:5,words:[["E fai foi o ia ma manuia. Pe a sau Asuria i lo tatou laueleele,", "And this man shall be the peace,"], ["pe a soli foi e ia o tatou maota,", "when the Assyrian shall come into our land:"], ["ona tatou totofi ai lea o leoleo e toafitu e tetee ia te ia,", "and when he shall tread in our palaces, then shall we raise against him seven shepherds,"], ["ma alii sili e toavalu.", "and eight principal men."]]},
  {num:6,words:[["Latou te faasaunoa foi le nuu o Asuria i le pelu,", "And they shall waste the land of Assyria with the sword,"], ["ma le nuu o Nimarota i ona lava faitotoa;", "and the land of Nimrod in the entrances thereof:"], ["na te laveai foi ia te i tatou ai Asuria,", "thus shall he deliver us from the Assyrian,"], ["pe a oo mai o ia i lo tatou laueleele,", "when he cometh into our land,"], ["pe a soli foi o ia i lo tatou nuu.", "and when he treadeth within our borders."]]},
  {num:7,words:[["E i ai foi e ua totoe o Iakopo i nuu e tele e pei o le sau mai ia Ieova,", "And the remnant of Jacob shall be in the midst of many people as a dew from the LORD,"], ["pei o le ua foi i luga o vao iti,", "as the showers upon the grass,"], ["o le mea e le faatalitali i tagata,", "that tarrieth not for man,"], ["e le faatalitali foi i le fanau a tagata.", "nor waiteth for the sons of men."]]},
  {num:8,words:[["E i ai foi e ua totoe o Iakopo i nuu ese,", "And the remnant of Jacob shall be among the Gentiles in the midst of many people as a lion among the beasts of the forest,"], ["o nuu e tele e pei o le leona i manu o le vao,", "as a young lion among the flocks of sheep:"], ["pei o le leona taanoa i lafu mamoe;", "who, if he go through,"], ["pe a ui ane o ia na te soli,", "both treadeth down,"], ["ma saei,", "and teareth in pieces,"], ["e leai foi se na te laveaiina.", "and none can deliver."]]},
  {num:9,words:[["E taualuga lou lima i e faasaua mai ia te oe,", "Thine hand shall be lifted up upon thine adversaries,"], ["e faaumatia foi e ua ita mai uma lava ia te oe.", "and all thine enemies shall be cut off."]]},
  {num:10,words:[["O loo faapea mai Ieova,", "And it shall come to pass in that day,"], ["O lea aso ou te faaumatia ai au solofanua o ia te oe,", "saith the LORD, that I will cut off thy horses out of the midst of thee,"], ["ou te faaumatia foi ou kariota.", "and I will destroy thy chariots:"]]},
  {num:11,words:[["Ou te faaumatia foi aai o lou nuu,", "And I will cut off the cities of thy land,"], ["ou te matuā sŏloia foi ou 'olo uma.", "and throw down all thy strong holds:"]]},
  {num:12,words:[["Ou te faaumatia togafiti faataulāitu ai lou lima,", "And I will cut off witchcrafts out of thine hand;"], ["e le i ai foi ia te oe ni e iite i ao o le lagi.", "and thou shalt have no more soothsayers:"]]},
  {num:13,words:[["Ou te faaumatia foi au tupua ua ta,", "Thy graven images also will I cut off,"], ["atoa ma au tupua maa;", "and thy standing images out of the midst of thee;"], ["ona e le toe ifo ai lea i galuega a ou lima.", "and thou shalt no more worship the work of thine hands."]]},
  {num:14,words:[["Ou te lepeti foi i au tupua o Asaira i totonu ia te oe,", "And I will pluck up thy groves out of the midst of thee:"], ["ma ou faatafunaina ou aai.", "so will I destroy thy cities."]]},
  {num:15,words:[["Ou te taui atu ma le ita e matuā tele i nuu ese o e ua le faalogo mai.", "And I will execute vengeance in anger and fury upon the heathen, such as they have not heard."]]},
];
renderVerseSet(mic_ch_5_Verses, 'mic-ch5-verses');

var mic_ch_6_Verses = [
  {num:1,words:[["Ina faalogo mai ia i le mea o loo fetalai mai ai Ieova,", "Hear ye now what the LORD saith;"], ["Tu ia i luga,", "Arise,"], ["ina finau atu ia i luma o mauga,", "contend thou before the mountains,"], ["ia faalogo foi mauga iti i lou leo.", "and let the hills hear thy voice."]]},
  {num:2,words:[["Outou mauga e,", "Hear ye,"], ["faalogo mai ia i le finauga a Ieova,", "O mountains,"], ["outou faavae tumau foi o le lalolagi;", "the LORD'S controversy, and ye strong foundations of the earth:"], ["auā ua ia Ieova le finauga ma lona nuu,", "for the LORD hath a controversy with his people,"], ["e fefinauai o ia ma Isaraelu.", "and he will plead with Israel."]]},
  {num:3,words:[["Lo'u nuu e,", "O my people,"], ["se a ea sa'u mea ua ou faia ia te oe? ua ou faatiga ia te oe i ni a? ina momoli ia o a'u.", "what have I done unto thee? and wherein have I wearied thee? testify against me."]]},
  {num:4,words:[["Auā na ou faaae mai ia te oe ai le nuu o Aikupito,", "For I brought thee up out of the land of Egypt,"], ["ma ou faaola ia te oe ai le mea sa nofo pologa ai,", "and redeemed thee out of the house of servants;"], ["na ou aauina foi i ou luma o Mose,", "and I sent before thee Moses,"], ["ma Arona,", "Aaron,"], ["ma Miriama.", "and Miriam."]]},
  {num:5,words:[["Lo'u nuu e,", "O my people,"], ["ina e manatua ia le mea sa filifilia e Palako le tupu o Moapi,", "remember now what Balak king of Moab consulted,"], ["ma le mea sa tali atu ai ia te ia e Palaamo le atalii o Peoro, ia e manatua i mea na faia e afua i Setima e oo i Kilikala;", "and what Balaam the son of Beor answered him from Shittim unto Gilgal;"], ["ina ia e iloa le agalelei o Ieova.", "that ye may know the righteousness of the LORD."]]},
  {num:6,words:[["Ou te alu atu ma ni a i luma o Ieova,", "Wherewith shall I come before the LORD,"], ["ou te ifo atu ma ni a i le Atua maualuga? Ou te alu atu ea i ona luma ma taulaga mu,", "and bow myself before the high God? shall I come before him with burnt offerings,"], ["ma tamai povi e tasi lo latou tausaga?", "with calves of a year old?"]]},
  {num:7,words:[["E fiafia ea Ieova i afe o mamoe poa,", "Will the LORD be pleased with thousands of rams,"], ["ma manomano alia o tafe suāuu? Ou te tuuina atu ea la'u ulumatua e sui a'i lo'u solitulafono,", "or with ten thousands of rivers of oil? shall I give my firstborn for my transgression,"], ["o la'u fanau to tino e sui a'i le agasala a lo'u agaga?", "the fruit of my body for the sin of my soul?"]]},
  {num:8,words:[["Sole,", "He hath shewed thee,"], ["ua faaali atu e ia ia te oe le mea lelei;", "O man,"], ["se a foi se mea e finagalo ai Ieova ia te oe,", "what is good;"], ["pe a le o ia mea ,", "and what doth the LORD require of thee,"], ["ia fai le amiotonu,", "but to do justly,"], ["ia naunau i le alofa,", "and to love mercy,"], ["ma ia feooai ma lou Atua ma le loto faamaulalo?", "and to walk humbly with thy God?"]]},
  {num:9,words:[["O loo alaga le siufofoga o Ieova i le aai,", "The LORD'S voice crieth unto the city,"], ["(o le ua poto e iloa e ia lou suafa;", "and the man of wisdom shall see thy name: hear ye the rod,"], [") Ia outou faalogo i le sasa ma le ua pule mai ai.", "and who hath appointed it."]]},
  {num:10,words:[["O loo i ai pea ea i le fale o le tagata amio leaga o le faaputugāoloa e maua i le amio leaga,", "Are there yet the treasures of wickedness in the house of the wicked,"], ["ma le efa faaaimago e inosia?", "and the scant measure that is abominable?"]]},
  {num:11,words:[["Ou te amio sao ea a o loo i ai fua faatautau faaletatau,", "Shall I count them pure with the wicked balances,"], ["ma le taga o loo i ai maa faaaimago?", "and with the bag of deceitful weights?"]]},
  {num:12,words:[["Ua tutumu ona tagata mauoa i le faasaua,", "For the rich men thereof are full of violence,"], ["ua tala pepelo foi i latou o e mau ai,", "and the inhabitants thereof have spoken lies,"], ["o latou laulaufaiva foi i o latou gutu ua faa'ole'ole ia.", "and their tongue is deceitful in their mouth."]]},
  {num:13,words:[["O lenei foi, ou te ta ia te oe e tupu ai lou ma'i,", "Therefore also will I make thee sick in smiting thee,"], ["ou te faatafunaina oe ona o au agasala.", "in making thee desolate because of thy sins."]]},
  {num:14,words:[["E te 'ai,", "Thou shalt eat,"], ["a e le ma'ona ai,", "but not be satisfied;"], ["o lou fia 'ai e ia te oe lea;", "and thy casting down shall be in the midst of thee;"], ["e te tua au mea ,", "and thou shalt take hold,"], ["a e le faasaoina ai;", "but shalt not deliver;"], ["o mea foi ua e faasaoina ou te tuuina atu ai i le pelu.", "and that which thou deliverest will I give up to the sword."]]},
  {num:15,words:[["E te lulu saito,", "Thou shalt sow,"], ["a e te le seleseleina;", "but thou shalt not reap;"], ["e te soli olive,", "thou shalt tread the olives,"], ["a e te le uu oe i le suāuu;", "but thou shalt not anoint thee with oil;"], ["atoa ma le suāvine,", "and sweet wine,"], ["a e te le inu i le uaina.", "but shalt not drink wine."]]},
  {num:16,words:[["Auā ua tausiusi sauniga a Omeri,", "For the statutes of Omri are kept,"], ["ma mea uma ua faia e le aiga o Aapo,", "and all the works of the house of Ahab,"], ["ua outou savavali foi i a latou pule,", "and ye walk in their counsels;"], ["ina ia ou faatafunaina ai oe,", "that I should make thee a desolation,"], ["ma ia fai ma mea e uisa ai e o mau ai;", "and the inhabitants thereof an hissing:"], ["tou te tauave foi le luma o lo'u nuu.", "therefore ye shall bear the reproach of my people."]]},
];
renderVerseSet(mic_ch_6_Verses, 'mic-ch6-verses');

var mic_ch_7_Verses = [
  {num:1,words:[["Aue a'u nei! auā ua avea a'u pei o le fuata ua uma ona faaputuina,", "Woe is me! for I am as when they have gathered the summer fruits,"], ["pei o toe fuifui vine i le taugāvine;", "as the grapegleanings of the vintage:"], ["e leai se fuifui vine e 'ai ai;", "there is no cluster to eat:"], ["na ou manao i le mati e muai matua.", "my soul desired the firstripe fruit."]]},
  {num:2,words:[["Ua fano le ua agalelei nai le nuu;", "The good man is perished out of the earth:"], ["e leai se tasi tagata ua amiotonu;", "and there is none upright among men:"], ["latou te lamalama uma ina ia fasioti tagata;", "they all lie in wait for blood;"], ["ua latou taitasi ma tuli lona uso ma le upega.", "they hunt every man his brother with a net."]]},
  {num:3,words:[["Ua matuā faia mea leaga i o latou lima;", "That they may do evil with both hands earnestly, the prince asketh,"], ["ua fai atu le alii sili atoa ma le faamasino i se taui;", "and the judge asketh for a reward;"], ["ua tautala atu foi le matai tagata i lona manumanu;", "and the great man,"], ["o lea ua latou faapiopio ai.", "he uttereth his mischievous desire: so they wrap it up."]]},
  {num:4,words:[["O so latou e lelei e tusa ia ma le laau tuitui;", "The best of them is as a brier:"], ["o sē amiotonu e sili ona matuitui o ia i le āi laau tuitui;", "the most upright is sharper than a thorn hedge:"], ["o loo oo mai le aso o ou tagata vaai, o lou asiasiga lava;", "the day of thy watchmen and thy visitation cometh;"], ["e i ai nei lava lo latou fememeai.", "now shall be their perplexity."]]},
  {num:5,words:[["Aua ne'i outou faatuatua i le uo,", "Trust ye not in a friend,"], ["aua ne'i faalagolago i le aumeamamae;", "put ye not confidence in a guide:"], ["ia e leoleo i puipui o lou gutu i lau avā pele.", "keep the doors of thy mouth from her that lieth in thy bosom."]]},
  {num:6,words:[["Auā o loo 'ino'ino le atalii i le tamā,", "For the son dishonoureth the father,"], ["o le tama teine ua tu o ia e tetee i lona tinā,", "the daughter riseth up against her mother,"], ["o le avā a le tama tane e tetee atu o ia i le tinā o lana tane; o e ua ita i le tagata,", "the daughter in law against her mother in law;"], ["o tagata ia o lona lava aiga.", "a man's enemies are the men of his own house."]]},
  {num:7,words:[["A o a'u,", "Therefore I will look unto the LORD;"], ["ou te faatalitali ia Ieova, ou te faamoemoe i le Atua o lo'u olataga;", "I will wait for the God of my salvation:"], ["e faafofoga mai lo'u Atua ia te au.", "my God will hear me."]]},
  {num:8,words:[["Aua e te mitamita ia te au,", "Rejoice not against me,"], ["o oe na,", "O mine enemy:"], ["le ua ita mai ia te au; e ui lava ina ou paū,", "when I fall,"], ["ou te toe tu lava i luga;", "I shall arise;"], ["e ui lava ina ou nofo i le pouliuli,", "when I sit in darkness,"], ["a o Ieova o lo'u malamalama ia.", "the LORD shall be a light unto me."]]},
  {num:9,words:[["Ou te faatoatoa i le toatamai o Ieova,", "I will bear the indignation of the LORD,"], ["auā ua ou agasala atu ia te ia;", "because I have sinned against him,"], ["seia faia e ia la'u finauga,", "until he plead my cause,"], ["ma na faia foi lo'u faamasinoga;", "and execute judgment for me:"], ["na te faaooina a'u i le malamalama,", "he will bring me forth to the light,"], ["ou te iloa lana amiotonu.", "and I shall behold his righteousness."]]},
  {num:10,words:[["E iloa ai foi e le ua ita mai ia te au,", "Then she that is mine enemy shall see it,"], ["e liloia foi o ia i le mā,", "and shame shall cover her which said unto me,"], ["o le na fai mai ia te au, O ifea ea Ieova lou Atua? E iloa o ia e o'u mata,", "Where is the LORD thy God? mine eyes shall behold her:"], ["e solia nei o ia pei o le palapala i le ala.", "now shall she be trodden down as the mire of the streets."]]},
  {num:11,words:[["O le aso e atiina ae ai ou pa,", "In the day that thy walls are to be built,"], ["o le aso lea e avea mamao ai le tulafono.", "in that day shall the decree be far removed."]]},
  {num:12,words:[["O lea aso latou te o mai ai lava ia te oe nai Asuria,", "In that day also he shall come even to thee from Assyria,"], ["atoa ma aai o Aikupito,", "and from the fortified cities,"], ["ma Aikupito lava e oo i le vaitafe,", "and from the fortress even to the river,"], ["mai le tasi sami e oo i le tasi sami,", "and from sea to sea,"], ["mai le tasi mauga e oo i le tasi mauga.", "and from mountain to mountain."]]},
  {num:13,words:[["A e faatafunaina le nuu ona o e mau ai,", "Notwithstanding the land shall be desolate because of them that dwell therein,"], ["ona o le fua o a latou amio.", "for the fruit of their doings."]]},
  {num:14,words:[["Ia e leoleo i lou nuu ma lou tootoo,", "Feed thy people with thy rod,"], ["o le lafu mamoe o lou tofi;", "the flock of thine heritage,"], ["o e nofo ese i le vao,", "which dwell solitarily in the wood,"], ["i Karamelu;", "in the midst of Carmel:"], ["ia latou aai i Vasana ma Kiliata,", "let them feed in Bashan and Gilead,"], ["pei o ona po anamuā lava.", "as in the days of old."]]},
  {num:15,words:[["Faapei o ona po sa e sau ai i le nuu o Aikupito, ou te faaali atu i ai vavega.", "According to the days of thy coming out of the land of Egypt will I shew unto him marvellous things."]]},
  {num:16,words:[["E iloa e nuu ese,", "The nations shall see and be confounded at all their might:"], ["ona masiasi ai lea o i latou i lo latou malosi uma; latou te ufiufi ai o latou gutu i o latou lima,", "they shall lay their hand upon their mouth,"], ["e tutuli foi o latou taliga.", "their ears shall be deaf."]]},
  {num:17,words:[["Latou te etoeto i le efuefu pei o le gata;", "They shall lick the dust like a serpent,"], ["e pei o mea fetolofi i le laueleele latou te tetemu ai i mea ua puipuia mo i latou;", "they shall move out of their holes like worms of the earth:"], ["latou te matatau ia Ieova lo tatou Atuā;", "they shall be afraid of the LORD our God,"], ["latou te fefefe foi ia te oe.", "and shall fear because of thee."]]},
  {num:18,words:[["O ai ea se Atua e tusa ma oe o le faamagalo agasala,", "Who is a God like unto thee,"], ["ma ua le manatua solitulafono a e o totoe o lona tofi? Na te le faamoemoe pea i lona toasa,", "that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever,"], ["auā e fiafia o ia i le alofa.", "because he delighteth in mercy."]]},
  {num:19,words:[["E toe alofa mai o ia ia te i tatou,", "He will turn again,"], ["e faatoilaloina e ia a tatou amioletonu;", "he will have compassion upon us; he will subdue our iniquities;"], ["e te lafo foi a latou agasala uma i mea loloto o le sami.", "and thou wilt cast all their sins into the depths of the sea."]]},
  {num:20,words:[["E te faaoo le faamaoni ia Iakopo,", "Thou wilt perform the truth to Jacob,"], ["o le alofa ia Aperaamo,", "and the mercy to Abraham,"], ["sa e tauto ai i o matou tamā talu mai ona po anamua.", "which thou hast sworn unto our fathers from the days of old."]]},
];
renderVerseSet(mic_ch_7_Verses, 'mic-ch7-verses');

})();