(function() {
var mic_ch_1_Verses = [
  {num:1,words:[["O le afioga a Ieova na oo mai ia Mika le Morese i ona po o Iotama,", "the a word but Jehovah oo from to mika the morese in then night iotama"], ["ma Aasa,", "and aasa"], ["ma Esekia,", "and esekia"], ["o tupu o Iuta,", "grow Judas"], ["na ia iloa i mea a Samaria ma Ierusalema.", "to known in thing but Samaria and Jerusalem"]]},
  {num:2,words:[["Faalogologo mai ia outou nuu uma;", "listen from to ye all nation all"], ["faasaga mai ia le lalolagi e,", "toward from to the earth by"], ["atoa ma mea ua tumu ai,", "and thing fill"], ["seia fai e le Alii o Ieova ana mau ia te outou,", "until make by the Lord Jehovah his opinion unto ye all"], ["o le Alii lava ai lona malumalu paia.", "the Lord indeed his temple holy"]]},
  {num:3,words:[["Auā faauta,", "for behold"], ["o loo afio mai Ieova ai lona afioga,", "dwell (respectful) from Jehovah his a word"], ["e afio ifo o ia,", "to dwell (respectful) he"], ["ma soli i mea maualuluga o i le lalolagi.", "and to tread upon in thing maualuluga in the earth"]]},
  {num:4,words:[["E liu suāvai mauga i lalo ia te ia,", "by liu suāvai mountain in under unto to"], ["e māvaevae vanu,", "by māvaevae valley"], ["pei o le pulu i le afi,", "to be broken the latex or milky sap secreted from any plant in general e.g. breadfruit in the fire"], ["faapei o le vai ua tafe ifo i le tofē.", "like the water to flow in the tofē"]]},
  {num:5,words:[["Ona o le solitulafono a Iakopo e oo ai ia mea uma,", "because of the solitulafono but James by oo to thing all"], ["ona o agasala foi a le aiga o Isaraelu.", "because of sin also but the family Israel"], ["Se a ea le solitulafono a Iakopo? E le o Samaria ea? O a ea foi mea maualuluga a Iuta?", "a but to rise (as a diver to the sur- the solitulafono but James by the Samaria to rise (as a diver to the sur- but to rise (as a diver to the sur- also thing maualuluga but Judas"]]},
  {num:6,words:[["E le o Ierusalema ea? O le mea lea ou te fai ai Samaria ma faupuegā maa i le fanua,", "by the Jerusalem to rise (as a diver to the sur- the thing I make Samaria and faupuegā stone in the land"], ["ma mea e totō ai vine,", "and thing by totō vine"], ["ou te tuleia foi i lalo i le vanu ona maa,", "I tuleia also in under in the valley then stone"], ["ou te faataatitiafuaina ona faavae.", "I faataatitiafuaina then faavae"]]},
  {num:7,words:[["E nutininiia foi ona tupua ua ta uma,", "by nutininiia also then idol a stroke all"], ["e susunuina foi ona taui uma i le afi,", "by susunuina also then a reward all in the fire"], ["ou te faatafunaina foi ona tupua uma;", "I faatafunaina also then idol all"], ["auā o le taui o le fafine talitane na ia faaputuina ai,", "for the a reward the woman talitane to faaputuina"], ["e toe foi atu foi ia mea i le taui o le fafine talitane.", "to again also also to thing in the a reward the woman talitane"]]},
  {num:8,words:[["O le mea lea ou te tagitu'i ai,", "therefore I tagitu'i"], ["ma ou uio,", "and I uio"], ["ou te fealuai ma le le ofu ma le le lavalavā;", "I fealuai and the the garment and the the lavalavā"], ["ou te tagi pei o luko,", "I to cry to be broken wolf"], ["ma ou faanoanoa pei o iaena.", "and I to mourn to be broken iaena"]]},
  {num:9,words:[["Auā e leaga ona manua;", "for to evil then manua"], ["auā ua oo lava i Iuta;", "for oo indeed in Judas"], ["ua pāia lava le faitotoa o lo'u nuu,", "pāia indeed the gate my nation"], ["o Ierusalema lava.", "Jerusalem indeed"]]},
  {num:10,words:[["Aua ne'i ta'uatua i Kato,", "for now ta'uatua in kato"], ["aua ne'i fetagisi i Ako;", "for now fetagisi in ako"], ["ia e taafili i le efuefu i Petofira.", "to by taafili in the efuefu in petofira"]]},
  {num:11,words:[["Ina ui ane ia e le o lavalavā ma le mā,", "let although to by the lavalavā and the First person dual exclusive"], ["o oe na lē mau i Safiri;", "you not opinion in safiri"], ["e lei alu atu le ua mau i Saanana;", "to whale's teeth go the opinion in saanana"], ["o le auega a Peteseli e aveeseina ia ia te outou le mea e tu ai o ia.", "the auega but peteseli by aveeseina to unto ye all the thing to stand he"]]},
  {num:12,words:[["Ua faanoanoa lava le ua mau i Marota ona o le manuia;", "to mourn indeed the opinion in marota then the peace"], ["auā ua oo ifo le malaia mai ia Ieova i le faitotoa o Ierusalema.", "for oo the a calamity from to Jehovah in the gate Jerusalem"]]},
  {num:13,words:[["O oe lē mau i Lakisa,", "you not opinion in lakisa"], ["ia e nonoa le nofoa faataavalevale i le solofanua televave;", "to to to tie the a seat to roll round and in the horse televave"], ["(o ia o le amataga o le agasala i le tama fafine a Siona;) auā ua iloa i totonu ia te oe solitulafono a Isaraelu.", "he the beginning the sin in the child woman but Zion for known in inside unto you solitulafono but Israel"]]},
  {num:14,words:[["O le mea lea e te avatu ai se tusi alei ia Morese-Kato;", "therefore by give away a book to drive to morese-kato"], ["e fai foi fale o Akasepa ma pepelo i tupu o Isaraelu.", "to make also house akasepa and false in grow Israel"]]},
  {num:15,words:[["I le ma lea,", "in the and"], ["o oe na o lē mau i Maresa,", "you not opinion in maresa"], ["ou te au mai ia te oe o le na te fai oe mona;", "I I from unto you the make you to burst forth (as faiai"], ["e oo lava ia i Atulama le mamalu o Isaraelu.", "it shall come to pass indeed to in atulama the glory Israel"]]},
  {num:16,words:[["Ia e tafi lou lauulu ma ia e sele mamā ona o au fanau pele,", "to to to brush your the hair of the head and to to a snare clean then I am born dear"], ["ia e faalautele le mea ua tafia pei o le aeto;", "to by faalautele the thing tafia to be broken the aeto"], ["auā ua tāfea ese i latou ia te oe.", "for tāfea away them unto you"]]},
];
renderVerseSet(mic_ch_1_Verses, 'mic-ch1-verses');

var mic_ch_2_Verses = [
  {num:1,words:[["Oi talofa i e mafaufau i amioletonu,", "alas ! oh ! hello in to think in wickedness"], ["ma latou saunia mea leaga i o latou moega;", "and them prepared thing evil in them moega"], ["pe a malama ae le taeao ua latou faia,", "or but malama but the morning them made"], ["auā ua mafai ia te i latou.", "for able unto them"]]},
  {num:2,words:[["Ua latou mananao foi i fanua,", "them mananao also in land"], ["ma latou fao ai faasaua,", "and them to seize to be oppressive"], ["atoa ma fale,", "and house"], ["ma latou avea;", "and them become"], ["ua latou saua atu i le tagata ma lona aiga,", "them to have a return of sick- in the man and his family"], ["o le tagata ma lona tofi.", "man and his appoint"]]},
  {num:3,words:[["O le mea lea o loo faapea mai ai Ieova,", "therefore thus from Jehovah"], ["Faauta,", "behold"], ["o loo ou te mafaufau i se mea leaga i lenei lava aiga,", "I think in a thing evil in this indeed family"], ["tou te le mafai ona 'alo ese ai o outou ua;", "second person plural the able then Son away ye all"], ["tou te le savavali foi ma le faasiasia;", "second person plural the walked also and the haughty"], ["auā e leaga ia ona po.", "for to evil to then night"]]},
  {num:4,words:[["E saunia se faataoto ia te outou i lea aso,", "to prepared a a parable unto ye all in day"], ["e pese le pese e aualofa a'i tele lava,", "to a song the a song to a keepsake great indeed"], ["e faapea,", "by thus"], ["Ua matuā faatafunaina i tatou;", "very faatafunaina in us"], ["ua suia e ia le tofi o lo'u nuu;", "suia by him the appoint my nation"], ["aue! ua ia aveeseina ai ia te au,", "alas! oh! to aveeseina unto I"], ["ua na tufatufa i o tatou fanua ina ia liliueseina.", "tufatufa in us land let to liliueseina"]]},
  {num:5,words:[["O le mea lea o le a leai ai ia te oe se na te lāfolafoina se maea pe a fai le vili i le faapotopotoga a Ieova.", "therefore what no unto you a lāfolafoina a maea or but make the a gimblet in the gathering but Jehovah"]]},
  {num:6,words:[["Ua latou faapea mai i e vavalo mai,", "them thus from in to prophesy from"], ["Aua ne'i outou vavalo.", "for now ye all prophesy"], ["Latou te le vavalo ia te i latou nei,", "them the prophesy unto them this"], ["e le mavae le masiasi.", "by the a parting the to be ashamied"]]},
  {num:7,words:[["Oi! o upu faapea a le aiga o Iakopo! E vaivai ea le Agaga o Ieova? O ana ea ia galuega? O a'u upu e le lelei ai ea le ua savali ma le amiotonu?", "alas ! oh ! word thus but the family James to weak to rise (as a diver to the sur- the spirit Jehovah his to rise (as a diver to the sur- to work I am word by the good to rise (as a diver to the sur- the walk and the righteous"]]},
  {num:8,words:[["A ua tulai lo'u nuu talu mai anamua pei o se ua ita mai lava;", "but arose up my nation since from anamua to be broken a angry from indeed"], ["ua outou fao le pulupulu atoa ma le ofu tele ia te i latou o e ui ane ma le faatalanoa,", "ye all to seize the pulupulu together with and the garment great unto them to although and the faatalanoa"], ["o e ua foi mai i le taua.", "who also from in the war"]]},
  {num:9,words:[["Ua outou tulia fafine o lo'u nuu i o latou fale e fiafia i ai;", "ye all tulia woman my nation in them house to competition therein"], ["ua outou ave ese foi lo'u mamalu i a latou fanau e faavavau.", "ye all take away also my glory in but them born to a stone connected with"]]},
  {num:10,words:[["Tutū ia i luga outou,", "tutū to in above ye all"], ["ina o ese ia;", "let away to"], ["auā e le o lo outou malologa lenei;", "for by the your a resting place this"], ["ua leaga,", "evil"], ["o le mea lea e malaia ai outou,", "therefore to a calamity ye all"], ["e matuā tele foi le malaia.", "to very great also the a calamity"]]},
  {num:11,words:[["Ai se tagata e savali e tusa ma lona loto ma le faa'ole'ole e pepelo mai,", "a man to walk to according to and his heart and the faa'ole'ole to false from"], ["e faapea mai ,", "by thus from"], ["Ou te vavalo ia te oe i le uaina ma le 'ava;", "I prophesy unto you in the wine and the kava"], ["e avea lava ia ma perofeta i lenei nuu.", "to become indeed to and prophet in this nation"]]},
  {num:12,words:[["Iakopo e,", "James by"], ["ou te faapotopoto lava ia te outou uma lava;", "I gather together indeed unto ye all all indeed"], ["ou te aofaiina lava e o totoe o Isaraelu,", "I aofaiina indeed by phiral of foe Israel"], ["ou te faatasia i latou pei o le lafu mamoe i Posara,", "I faatasia them to be broken the a herd sheep in posara"], ["pei o le lafu manu i totonu o le mea e fafaga ai,", "to be broken the a herd animal in inside the thing to a woman's burden"], ["latou te soona ualolo ona o le vao tagata.", "them without form rain with a flood then the vegetation man"]]},
  {num:13,words:[["Ua alu ae i o latou luma le na te lepetia,", "go but in them before the lepetia"], ["ua latou lepeti,", "them lepeti"], ["ma latou ui ane i le faitotoa,", "and them although in the gate"], ["ua latou o atu ai lava,", "them indeed"], ["e afio atu foi lo latou Tupu i o latou luma,", "to dwell (respectful) also their grow in them before"], ["e muamua foi Ieova ia te i latou.", "to first also Jehovah unto them"]]},
];
renderVerseSet(mic_ch_2_Verses, 'mic-ch2-verses');

var mic_ch_3_Verses = [
  {num:1,words:[["Sa a'u faapea atu foi,", "I thus also"], ["Faafofoga mai ia outou matai o Iakopo,", "listen from to ye all chief James"], ["ma outou faipule o le aiga o Isaraelu,", "and ye all a councillor the family Israel"], ["E le o ia te outou ea ona iloa le faamasinoga?", "by the he ye all to rise (as a diver to the sur- then known the judgment"]]},
  {num:2,words:[["O outou o loo 'ino'ino i mea lelei,", "ye all 'ino'ino in thing good"], ["ma fiafia i mea leaga,", "and competition in thing evil"], ["o loo outou sae ese o latou pa'u,", "ye all sae away them to be as far as"], ["atoa ma aano i o latou ivi.", "and aano in them bone"]]},
  {num:3,words:[["O e aai foi i tino o lo'u nuu,", "who eat also in body my nation"], ["ma saeeseina o latou pa'u,", "and saeeseina them to be as far as"], ["ma gauia o latou ivi,", "and gauia them bone"], ["e vaevaea lava pei o mea e tuu i le ulo,", "by vaevaea indeed to be broken thing to put in the ulo"], ["pei o tufaaga foi i totonu o le pani.", "to be broken tufaaga also in inside the bun"]]},
  {num:4,words:[["Ona latou alalaga atu ai lea ia Ieova,", "and them alalaga to Jehovah"], ["a e le faafofoga mai ai o ia ia te i latou;", "but by the listen from he unto them"], ["a e 'alo ese ona fofoga ia te i latou i ia lava ona po,", "but to Son away then face unto them in to indeed then night"], ["auā ua leaga lava a latou mea e fai.", "for evil indeed but them thing to make"]]},
  {num:5,words:[["O loo faapea mai Ieova i perofeta o e faasese i lo'u nuu,", "thus from Jehovah in prophet to to cause to go astray in my nation"], ["o e fēu i o latou nifo,", "who fēu in them tooth"], ["ma latou alalaga atu,", "and them alalaga"], ["O le manuia;", "the peace"], ["a o le ua le avane mea i o latou gutu,", "but the the avane thing in them mouth"], ["latou te sauni lava le taua ia te ia.", "them he who beg^ins the game indeed the war unto to"]]},
  {num:6,words:[["O le mea lea e pogia ai outou ma le leai o se mea e vaaia,", "therefore to passive oi' po ye all and the no a thing to seen"], ["e oo foi le pouliuli ia te outou ma le leai o se iite;", "it shall come to pass also the darkness unto ye all and the no a iite"], ["e goto foi le la i ia perofeta,", "by goto also the la in to prophet"], ["e pogisa foi le ao ia te i latou.", "to to be quite dark also the day unto them"]]},
  {num:7,words:[["Ona masiasi ai lea o tagata vaai,", "and to be ashamied man to look at"], ["e fememeai ai foi o e iite;", "by fememeai also by iite"], ["latou te ufiufi foi i a latou 'ava,", "them ufiufi also in but them kava"], ["o i latou uma lava,", "them all indeed"], ["auā e leai se tali mai le Atua.", "for to no a respond from the God"]]},
  {num:8,words:[["A e peitai o a'u,", "but to however I am"], ["e moni lava,", "verily I say"], ["ua faatumuina a'u i le mana e le Agaga o Ieova,", "faatumuina I in the to get by the spirit Jehovah"], ["o le faamasinoga foi,", "the judgment also"], ["ma le malosi,", "and the strong"], ["e faailoa atu ai ia Iakopo o lana solitulafono,", "to declared to James his solitulafono"], ["e faailoa atu foi ia Isaraelu o lana agasala.", "to declared also to Israel his sin"]]},
  {num:9,words:[["Ina faafofoga mai ia i le mea nei o outou matai o le aiga o Iakopo,", "let listen from to in the thing this ye all chief the family James"], ["ma outou faipule o le aiga o Isaraelu,", "and ye all a councillor the family Israel"], ["o e 'ino'ino i le faamasinoga,", "who 'ino'ino in the judgment"], ["ma faapiopio i mea tonu uma;", "and faapiopio in thing right all"], ["o e ati ae Siona i le toto,", "who to pull up but Zion in the blood"]]},
  {num:10,words:[["ma Ierusalema i le amio leaga.", "and Jerusalem in the conduct evil"]]},
  {num:11,words:[["O ona matai ua latou faamasino i le fia fai taui,", "then chief them a judge in the want to do something make a reward"], ["o ana ositaulaga foi ua latou a'oa'o i le fia fai taui,", "his high priest also them excellent in the want to do something make a reward"], ["ma ana perofeta ua latou iite i le fia fai tupe;", "and his prophet them iite in the want to do something make St. Thomas bean"], ["a ua latou faalagolago ia Ieova,", "but them to lean upon to Jehovah"], ["ma faapea ane,", "and thus"], ["E le o ia te i tatou ea Ieova? e le oo mai se mea leaga ia te i tatou.", "by the he in us to rise (as a diver to the sur- Jehovah by the oo from a thing evil unto in us"]]},
  {num:12,words:[["O le mea lea e fai ai Siona ma fanua e suatia ona o outou,", "therefore to make Zion and land by suatia then ye all"], ["e fai foi Ierusalema ma faupuegāmaa,", "to make also Jerusalem and faupuegāmaa"], ["o le mauga foi o i ai le fale e fai lea ma mea maualuga i le vao matua.", "the mountain also therein the house to make and thing Iiigli in the vegetation very"]]},
  {num:13,words:[["Ua alu ae i o latou luma le na te lepetia,", "go but in them before the lepetia"], ["ua latou lepeti,", "them lepeti"], ["ma latou ui ane i le faitotoa,", "and them although in the gate"], ["ua latou o atu ai lava,", "them indeed"], ["e afio atu foi lo latou Tupu i o latou luma,", "to dwell (respectful) also their grow in them before"], ["e muamua foi le ALII ia te i latou.", "to first also the Lord unto them"], ["O le иpи e aoai atu 1 alii o le nuu ma perofeta pepelo Sa a'u faapea atu foi,", "the иpи by aoai 1 Lord the nation and prophet false I thus also"], ["Faafofoga mai ia outou matai o lakopo,", "listen from to ye all chief lakopo"], ["ma outou faipule o le aiga o Isaraelu,", "and ye all a councillor the family Israel"], ["E le o ia te outou ea ona iloa le faamasinoga?", "by the he ye all to rise (as a diver to the sur- then known the judgment"]]},
];
renderVerseSet(mic_ch_3_Verses, 'mic-ch3-verses');

var mic_ch_4_Verses = [
  {num:1,words:[["A o aso e gata ai e oo ina faatumauina ai le mauga o i ai le fale o Ieova i tumutumu o mauga,", "but day to a snake by oo let faatumauina the mountain therein the house Jehovah in tumutumu mountain"], ["e faamaualugaina foi ia sili i mauga iti,", "by faamaualugaina also to most in mountain iti"], ["ona gasolo ane lea o nuu i ai.", "and swifi nation therein"]]},
  {num:2,words:[["E o mai lava nuu ese e tele,", "by from indeed nation away to great"], ["ma latou faapea ane,", "and them thus"], ["O mai ia,", "from to"], ["tatou o ae ia i le mauga o Ieova,", "us but to in the mountain Jehovah"], ["o le fale foi o le Atua o Iakopo;", "the house also the God James"], ["e a'oa'o mai ai o ia ia te i tatou i ona ala,", "to excellent from he unto in us in then arise"], ["ona tatou savavali ai lea i ona ala;", "and us walked in then arise"], ["auā e alu atu le tulafono mai Siona,", "for to go the law from Zion"], ["o le afioga foi a Ieova mai Ierusalema.", "the a word also but Jehovah from Jerusalem"]]},
  {num:3,words:[["E faamasino foi o ia i nuu e tele,", "to a judge also he in nation to great"], ["e aoai atu foi i nuu malolosi e mamao;", "by aoai also in nation mighty to to be far ofl\""], ["ona latou tu'i ai lea i a latou pelu e fai ma uamea o suotosina,", "and them '2l high chief in but them a sword to make and uamea suotosina"], ["o latou tao foi e fai ma polo teu vine;", "them spear also to make and Chili pepper teu vine"], ["e le sii atu foi le pelu e le tasi nuu,", "by the lift up also the a sword by the one nation"], ["latou te le toe a'oa'o foi i taua.", "them the again excellent also in war"]]},
  {num:4,words:[["A e taitasi ma nofo i lalo o lona vine,", "but by each and dwell in under his vine"], ["ma lalo o lona mati;", "and under his mati"], ["e leai foi se na te faamatau mai;", "there is not also a faamatau from"], ["auā ua faapea ona tŭlei mai ai le siufofoga o Ieova o 'au.", "for thus then tŭlei from the voice Jehovah I"]]},
  {num:5,words:[["Auā o nuu uma e taitasi ma savali i le igoa o latou atua,", "for nation all by each and walk in the name them God"], ["o i tatou foi,", "in us also"], ["tatou te savavali i le suafa o Ieova lo tatou Atua e faavavau faavavau lava.", "us walked in the name Jehovah our God to a stone connected with a stone connected with indeed"]]},
  {num:6,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["O lea aso ou te faapotopoto ai le nuu ua setusetu,", "therefore day I gather together the nation setusetu"], ["ou te aofaiina faatasi foi le nuu ua tulia,", "I aofaiina once also the nation tulia"], ["ma le nuu ua ou faatigaina.", "and the nation I faatigaina"]]},
  {num:7,words:[["Ou te faatotoe nisi o le nuu ua setusetu,", "I faatotoe some the nation setusetu"], ["ou te faia foi ma nuu malosi e ua tāfea mamao,", "I made also and nation strong by tāfea to be far ofl\""], ["e pule foi Ieova ia te i latou i le mauga o Siona e amata i ona po nei,", "to rule also Jehovah unto them in the mountain Zion to began in then night this"], ["e oo i le faavavau.", "it shall come to pass in the a stone connected with"]]},
  {num:8,words:[["O oe foi le 'olo o le lafu mamoe,", "you also the fortress the a herd sheep"], ["o le mauga o le tama fafine a Siona,", "the mountain the child woman but Zion"], ["e oo mai lava ia te oe,", "it shall come to pass from indeed unto you"], ["e oo mai lava le muai pule;", "it shall come to pass from indeed the first rule"], ["e oo mai le malo o le tama fafine a Ierusalema.", "it shall come to pass from the government the child woman but Jerusalem"]]},
  {num:9,words:[["O lenei,", "this"], ["se a le mea e te alaga tele ai? E leai ea se tupu ia te oe? Ua fano ea lou faipule? ina ua maua oe i tiga pei o se fafine a fanau mai.", "a but the thing by a shoulder or leg of aa ' great to no to rise (as a diver to the sur- a grow unto you perish to rise (as a diver to the sur- your a councillor let received you in pain to be broken a woman but born from"]]},
  {num:10,words:[["Le tama fafine a Siona e,", "the child woman but Zion by"], ["ina faatiga ia,", "let a to"], ["ma ia fanau mai,", "and to born from"], ["pei o le fafine a fanau mai;", "to be broken the woman but born from"], ["auā e te alu ese nei i le aai a e mau i le vao,", "for by go away this in the eat but to opinion in the vegetation"], ["e te oo lava i Papelonia;", "by oo indeed in Babylon"], ["e laveaiina oe i lea mea,", "to delivered you in thing"], ["e laveai Ieova ia te oe i lea mea ai lima o i latou o e ita mai ia te oe.", "to deliver Jehovah unto you in thing five them to angry from unto you"]]},
  {num:11,words:[["Ua faapotopotoina nei foi o nuu e tele o le a tau ma oe,", "faapotopotoina this also nation to great the but season and you"], ["o e faapea ane,", "who thus"], ["Ia leaga o ia;", "to evil he"], ["se'i vaai foi o tatou mata i Siona.", "a flower put into the hair or to look at also us eye in Zion"]]},
  {num:12,words:[["A o i latou,", "but them"], ["latou te le iloa manatu o Ieova,", "them the known thought Jehovah"], ["latou te le iloa foi lana pule;", "them the known also his rule"], ["auā e faapotopotoina i latou e ia pei o fusi saito i le mea e soli ai saito.", "for by faapotopotoina them by him to be broken fusi wheat in the thing to to tread upon wheat"]]},
  {num:13,words:[["Le tama fafine a Siona e,", "the child woman but Zion by"], ["tu ia i luga,", "stand to in above"], ["ma soli;", "and to tread upon"], ["auā ou te faia lou nifo ma uamea,", "for I made your tooth and uamea"], ["ou te faia foi ou atigivae ma 'apa memea;", "I made also I atigivae and can memea"], ["e te tu'imomomoina nuu e tele;", "by tu'imomomoina nation to great"], ["ou te faatoina foi mo Ieova a latou vete,", "I faatoina also for Jehovah but them vete"], ["atoa ma a latou oloa mo le Alii o le lalolagi uma.", "and but them goods for the Lord the earth all"]]},
  {num:14,words:[["Ou te lepeti foi i au tupua o Asaira i totonu ia te oe,", "I lepeti also in I idol asaira in inside unto you"], ["ma ou faatafunaina ou aai.", "and I faatafunaina I eat"]]},
  {num:15,words:[["Ou te taui atu ma le ita e matuā tele i nuu ese o e ua le faalogo mai.", "I a reward and the angry to very great in nation away by the hearken from"], ["Ua aoai atu le Atua ia te 1 latou ona o aтїo eseese Ina faalogo mai ia i le mea o loo fetalai mai ai le Ати,", "aoai the God unto 1 them then aтїo divided let hearken from to in the thing said from the ати"], ["Tu ia i luga,", "stand to in above"], ["ina finau atu ia i luma o mauga,", "let finau to in before mountain"], ["ia faalogo foi mauga iti i lou leo.", "to hearken also mountain iti in your voice"]]},
];
renderVerseSet(mic_ch_4_Verses, 'mic-ch4-verses');

var mic_ch_5_Verses = [
  {num:1,words:[["O lenei,", "this"], ["ina faalaei 'au ia o oe le tama fafine e ana 'au;", "let faalaei I to you the child woman by his I"], ["ua ia siosioina i tatou i le taua;", "to siosioina in us in the war"], ["latou te ta i le tootoo le faamasino o Isaraelu i lona alafau.", "them a stroke in the tootoo the a judge Israel in his the cheek"]]},
  {num:2,words:[["A o oe,", "but you"], ["Peteleema-Efarata,", "peteleema-efarata"], ["e itiiti oe i afe o Iuta,", "to small you in thousand Judas"], ["a e tupu mai ia te oe mo a'u o le na te fai ma faipule ia Isaraelu,", "but to grow from unto you for I the make and a councillor to Israel"], ["o lona tupu mai talu mai anamuā lea,", "his grow from since from anamuā"], ["talu mai ona po o le vavau lava.", "since from then night the ancient times indeed"]]},
  {num:3,words:[["A e peitai e tuua i latou e ia seia oo i ona po e fanau mai ai o ia o le a fanau;", "but to however to left them by him until oo in then night to born from he the but born"], ["ona toe foi mai ai lea i le fanauga a Isaraelu o e totoe i ona uso.", "and again also from in the children but Israel to phiral of foe in then a relative of the same generation and gender"]]},
  {num:4,words:[["E tu foi o ia ma leoleo ia te i latou i le mana o Ieova,", "to stand also he and police unto them in the to get Jehovah"], ["ma le mamalu o le suafa o Ieova lona Atua,", "and the glory the name Jehovah his God"], ["ona latou nofo mau ai lea;", "and them dwell opinion"], ["auā o ona po ia e mamalu ai o ia e oo i tuluiga o le lalolagi.", "for then night to to glory he by oo in tuluiga the earth"]]},
  {num:5,words:[["E fai foi o ia ma manuia.", "to make also he and peace"], ["Pe a sau Asuria i lo tatou laueleele,", "or but come Assyria in the us ground"], ["pe a soli foi e ia o tatou maota,", "or but to tread upon also by him us the name of a tree"], ["ona tatou totofi ai lea o leoleo e toafitu e tetee ia te ia,", "and us totofi police by toafitu to to refuse unto to"], ["ma alii sili e toavalu.", "and Lord most by toavalu"]]},
  {num:6,words:[["Latou te faasaunoa foi le nuu o Asuria i le pelu,", "them faasaunoa also the nation Assyria in the a sword"], ["ma le nuu o Nimarota i ona lava faitotoa;", "and the nation nimarota in then indeed gate"], ["na te laveai foi ia te i tatou ai Asuria,", "deliver also unto in us Assyria"], ["pe a oo mai o ia i lo tatou laueleele,", "or but oo from he in the us ground"], ["pe a soli foi o ia i lo tatou nuu.", "or but to tread upon also he in the us nation"]]},
  {num:7,words:[["E i ai foi e ua totoe o Iakopo i nuu e tele e pei o le sau mai ia Ieova,", "by therein also by phiral of foe James in nation to great to to be broken the come from to Jehovah"], ["pei o le ua foi i luga o vao iti,", "to be broken the also in above vegetation iti"], ["o le mea e le faatalitali i tagata,", "the thing by the faatalitali in man"], ["e le faatalitali foi i le fanau a tagata.", "by the faatalitali also in the born but man"]]},
  {num:8,words:[["E i ai foi e ua totoe o Iakopo i nuu ese,", "by therein also by phiral of foe James in nation away"], ["o nuu e tele e pei o le leona i manu o le vao,", "nation to great to to be broken the leona in animal the vegetation"], ["pei o le leona taanoa i lafu mamoe;", "to be broken the leona an animal that is weaned in a herd sheep"], ["pe a ui ane o ia na te soli,", "or but although he to tread upon"], ["ma saei,", "and to tear"], ["e leai foi se na te laveaiina.", "there is not also a delivered"]]},
  {num:9,words:[["E taualuga lou lima i e faasaua mai ia te oe,", "to the covering of the your five in to to be oppressive from unto you"], ["e faaumatia foi e ua ita mai uma lava ia te oe.", "to destroy also by angry from all indeed unto you"]]},
  {num:10,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["O lea aso ou te faaumatia ai au solofanua o ia te oe,", "therefore day I destroy I horse he you"], ["ou te faaumatia foi ou kariota.", "I destroy also I kariota"]]},
  {num:11,words:[["Ou te faaumatia foi aai o lou nuu,", "I destroy also eat your nation"], ["ou te matuā sŏloia foi ou 'olo uma.", "I very sŏloia also I fortress all"]]},
  {num:12,words:[["Ou te faaumatia togafiti faataulāitu ai lou lima,", "I destroy heal faataulāitu your five"], ["e le i ai foi ia te oe ni e iite i ao o le lagi.", "by the therein also unto you some by iite in day the heaven"]]},
  {num:13,words:[["Ou te faaumatia foi au tupua ua ta,", "I destroy also I idol a stroke"], ["atoa ma au tupua maa;", "and I idol stone"], ["ona e le toe ifo ai lea i galuega a ou lima.", "and by the again in work but I five"]]},
  {num:14,words:[["Ou te lepeti foi i au tupua o Asaira i totonu ia te oe,", "I lepeti also in I idol asaira in inside unto you"], ["ma ou faatafunaina ou aai.", "and I faatafunaina I eat"]]},
  {num:15,words:[["Ou te taui atu ma le ita e matuā tele i nuu ese o e ua le faalogo mai.", "I a reward and the angry to very great in nation away by the hearken from"]]},
];
renderVerseSet(mic_ch_5_Verses, 'mic-ch5-verses');

var mic_ch_6_Verses = [
  {num:1,words:[["Ina faalogo mai ia i le mea o loo fetalai mai ai Ieova,", "let hearken from to in the thing said from Jehovah"], ["Tu ia i luga,", "stand to in above"], ["ina finau atu ia i luma o mauga,", "let finau to in before mountain"], ["ia faalogo foi mauga iti i lou leo.", "to hearken also mountain iti in your voice"]]},
  {num:2,words:[["Outou mauga e,", "ye all mountain by"], ["faalogo mai ia i le finauga a Ieova,", "hearken from to in the argument but Jehovah"], ["outou faavae tumau foi o le lalolagi;", "ye all faavae endure also the earth"], ["auā ua ia Ieova le finauga ma lona nuu,", "for to Jehovah the argument and his nation"], ["e fefinauai o ia ma Isaraelu.", "by fefinauai he and Israel"]]},
  {num:3,words:[["Lo'u nuu e,", "my nation by"], ["se a ea sa'u mea ua ou faia ia te oe? ua ou faatiga ia te oe i ni a? ina momoli ia o a'u.", "a but to rise (as a diver to the sur- come thing I made unto you I a unto you in some but let to carry to I am"]]},
  {num:4,words:[["Auā na ou faaae mai ia te oe ai le nuu o Aikupito,", "for I faaae from unto you the nation Egypt"], ["ma ou faaola ia te oe ai le mea sa nofo pologa ai,", "and I save unto you the thing dwell mouldy"], ["na ou aauina foi i ou luma o Mose,", "I sent also in I before Moses"], ["ma Arona,", "and Aaron"], ["ma Miriama.", "and miriama"]]},
  {num:5,words:[["Lo'u nuu e,", "my nation by"], ["ina e manatua ia le mea sa filifilia e Palako le tupu o Moapi,", "let to remember to the thing chosen by palako the grow moapi"], ["ma le mea sa tali atu ai ia te ia e Palaamo le atalii o Peoro,", "and the thing respond unto to by palaamo the son peoro"], ["ia e manatua i mea na faia e afua i Setima e oo i Kilikala;", "to to remember in thing made by afua in setima by oo in kilikala"], ["ina ia e iloa le agalelei o Ieova.", "so that to known the goodness Jehovah"]]},
  {num:6,words:[["Ou te alu atu ma ni a i luma o Ieova,", "I go and some but in before Jehovah"], ["ou te ifo atu ma ni a i le Atua maualuga? Ou te alu atu ea i ona luma ma taulaga mu,", "I and some but in the God Iiigli I go to rise (as a diver to the sur- in then before and offering mu"], ["ma tamai povi e tasi lo latou tausaga?", "and son cattle by one their year"]]},
  {num:7,words:[["E fiafia ea Ieova i afe o mamoe poa,", "to competition to rise (as a diver to the sur- Jehovah in thousand sheep captive"], ["ma manomano alia o tafe suāuu? Ou te tuuina atu ea la'u ulumatua e sui a'i lo'u solitulafono,", "and manomano a young anae to flow suāuu I given to rise (as a diver to the sur- my the first-born to to dilute my solitulafono"], ["o la'u fanau to tino e sui a'i le agasala a lo'u agaga?", "my born to plant body to to dilute the sin but my spirit"]]},
  {num:8,words:[["Sole,", "alofi vae"], ["ua faaali atu e ia ia te oe le mea lelei;", "reveal by him unto you the thing good"], ["se a foi se mea e finagalo ai Ieova ia te oe,", "a but also a thing to a chiefs will or desire Jehovah unto you"], ["pe a le o ia mea ,", "or but the he thing"], ["ia fai le amiotonu,", "to make the righteous"], ["ia naunau i le alofa,", "to naunau in the love"], ["ma ia feooai ma lou Atua ma le loto faamaulalo?", "and to feooai and your God and the heart to be humble"]]},
  {num:9,words:[["O loo alaga le siufofoga o Ieova i le aai,", "a shoulder or leg of aa ' the voice Jehovah in the eat"], ["(o le ua poto e iloa e ia lou suafa;) Ia outou faalogo i le sasa ma le ua pule mai ai.", "the wise to known by him your name to ye all hearken in the a scourge and the rule from"]]},
  {num:10,words:[["O loo i ai pea ea i le fale o le tagata amio leaga o le faaputugāoloa e maua i le amio leaga,", "therein continually to rise (as a diver to the sur- in the house the man conduct evil the faaputugāoloa to received in the conduct evil"], ["ma le efa faaaimago e inosia?", "and the efa faaaimago to abominable"]]},
  {num:11,words:[["Ou te amio sao ea a o loo i ai fua faatautau faaletatau,", "I conduct the appointed portion of to rise (as a diver to the sur- but therein fruit faatautau faaletatau"], ["ma le taga o loo i ai maa faaaimago?", "and the the shark's stomach therein stone faaaimago"]]},
  {num:12,words:[["Ua tutumu ona tagata mauoa i le faasaua,", "tutumu then man mauoa in the to be oppressive"], ["ua tala pepelo foi i latou o e mau ai,", "side false also them to opinion"], ["o latou laulaufaiva foi i o latou gutu ua faa'ole'ole ia.", "them tongue also in them mouth faa'ole'ole to"]]},
  {num:13,words:[["O lenei foi,", "this also"], ["ou te ta ia te oe e tupu ai lou ma'i,", "I a stroke unto you to grow your from"], ["ou te faatafunaina oe ona o au agasala.", "I faatafunaina you then I am sin"]]},
  {num:14,words:[["E te 'ai,", "by eat"], ["a e le ma'ona ai,", "but by the to subside"], ["o lou fia 'ai e ia te oe lea;", "your want to do something eat by him you"], ["e te tua au mea ,", "by behind I thing"], ["a e le faasaoina ai;", "but by the saved"], ["o mea foi ua e faasaoina ou te tuuina atu ai i le pelu.", "thing also to saved I given in the a sword"]]},
  {num:15,words:[["E te lulu saito,", "by barn owl wheat"], ["a e te le seleseleina;", "but by the seleseleina"], ["e te soli olive,", "by to tread upon olive"], ["a e te le uu oe i le suāuu;", "but by the oil you in the suāuu"], ["atoa ma le suāvine,", "and the suāvine"], ["a e te le inu i le uaina.", "but by the drink in the wine"]]},
  {num:16,words:[["Auā ua tausiusi sauniga a Omeri,", "for tausiusi preparation but omeri"], ["ma mea uma ua faia e le aiga o Aapo,", "and thing all made by the family aapo"], ["ua outou savavali foi i a latou pule,", "ye all walked also in but them rule"], ["ina ia ou faatafunaina ai oe,", "so that I faatafunaina you"], ["ma ia fai ma mea e uisa ai e o mau ai;", "and to make and thing by uisa by opinion"], ["tou te tauave foi le luma o lo'u nuu.", "second person plural tauave also the before my nation"]]},
];
renderVerseSet(mic_ch_6_Verses, 'mic-ch6-verses');

var mic_ch_7_Verses = [
  {num:1,words:[["Aue a'u nei! auā ua avea a'u pei o le fuata ua uma ona faaputuina,", "alas! oh! I this for become I to be broken the fuata all then faaputuina"], ["pei o toe fuifui vine i le taugāvine;", "to be broken again to dip vine in the taugāvine"], ["e leai se fuifui vine e 'ai ai;", "there is no to dip vine to eat"], ["na ou manao i le mati e muai matua.", "I desire in the mati to first very"]]},
  {num:2,words:[["Ua fano le ua agalelei nai le nuu;", "perish the goodness from the nation"], ["e leai se tasi tagata ua amiotonu;", "there is no one man righteous"], ["latou te lamalama uma ina ia fasioti tagata;", "them lamalama all let to killed man"], ["ua latou taitasi ma tuli lona uso ma le upega.", "them each and drive his a relative of the same generation and gender and the upega"]]},
  {num:3,words:[["Ua matuā faia mea leaga i o latou lima;", "very made thing evil in them five"], ["ua fai atu le alii sili atoa ma le faamasino i se taui;", "make the Lord most together with and the a judge in a a reward"], ["ua tautala atu foi le matai tagata i lona manumanu;", "to talk also the chief man in his manumanu"], ["o lea ua latou faapiopio ai.", "therefore them faapiopio"]]},
  {num:4,words:[["O so latou e lelei e tusa ia ma le laau tuitui;", "so them to good to according to to and the tree prickly"], ["o sē amiotonu e sili ona matuitui o ia i le āi laau tuitui;", "sē righteous to most then matuitui he in the āi tree prickly"], ["o loo oo mai le aso o ou tagata vaai,", "oo from the day I man to look at"], ["o lou asiasiga lava;", "your asiasiga indeed"], ["e i ai nei lava lo latou fememeai.", "by therein this indeed their fememeai"]]},
  {num:5,words:[["Aua ne'i outou faatuatua i le uo,", "for now ye all faith in the uo"], ["aua ne'i faalagolago i le aumeamamae;", "for now to lean upon in the aumeamamae"], ["ia e leoleo i puipui o lou gutu i lau avā pele.", "to to police in a duor your mouth in your wife dear"]]},
  {num:6,words:[["Auā o loo 'ino'ino le atalii i le tamā,", "for 'ino'ino the son in the father"], ["o le tama teine ua tu o ia e tetee i lona tinā,", "the child girl stand he to to refuse in his mother"], ["o le avā a le tama tane e tetee atu o ia i le tinā o lana tane;", "the wife but the child man to to refuse he in the mother his man"], ["o e ua ita i le tagata,", "who angry in the man"], ["o tagata ia o lona lava aiga.", "man to his indeed family"]]},
  {num:7,words:[["A o a'u,", "but I am"], ["ou te faatalitali ia Ieova,", "I faatalitali to Jehovah"], ["ou te faamoemoe i le Atua o lo'u olataga;", "I to expect in the God my a means of deliverance"], ["e faafofoga mai lo'u Atua ia te au.", "to listen from my God unto I"]]},
  {num:8,words:[["Aua e te mitamita ia te au,", "for by to boast unto I"], ["o oe na,", "you"], ["le ua ita mai ia te au;", "the angry from unto I"], ["e ui lava ina ou paū,", "to although indeed let I paū"], ["ou te toe tu lava i luga;", "I again stand indeed in above"], ["e ui lava ina ou nofo i le pouliuli,", "to although indeed let I dwell in the darkness"], ["a o Ieova o lo'u malamalama ia.", "but Jehovah my light to"]]},
  {num:9,words:[["Ou te faatoatoa i le toatamai o Ieova,", "I faatoatoa in the toatamai Jehovah"], ["auā ua ou agasala atu ia te ia;", "for I sin unto to"], ["seia faia e ia la'u finauga,", "until made by him my argument"], ["ma na faia foi lo'u faamasinoga;", "and made also my judgment"], ["na te faaooina a'u i le malamalama,", "faaooina I in the light"], ["ou te iloa lana amiotonu.", "I known his righteous"]]},
  {num:10,words:[["E iloa ai foi e le ua ita mai ia te au,", "to known also by the angry from unto I"], ["e liloia foi o ia i le mā,", "to to be covered also he in the First person dual exclusive"], ["o le na fai mai ia te au,", "the make from unto I"], ["O ifea ea Ieova lou Atua? E iloa o ia e o'u mata,", "ifea to rise (as a diver to the sur- Jehovah your God to known he to I eye"], ["e solia nei o ia pei o le palapala i le ala.", "by solia this he to be broken the palapala in the arise"]]},
  {num:11,words:[["O le aso e atiina ae ai ou pa,", "the day by atiina but I a wall"], ["o le aso lea e avea mamao ai le tulafono.", "the day to become to be far ofl\" the law"]]},
  {num:12,words:[["O lea aso latou te o mai ai lava ia te oe nai Asuria,", "therefore day them from indeed unto you from Assyria"], ["atoa ma aai o Aikupito,", "and eat Egypt"], ["ma Aikupito lava e oo i le vaitafe,", "and Egypt indeed by oo in the river"], ["mai le tasi sami e oo i le tasi sami,", "from the one sea by oo in the one sea"], ["mai le tasi mauga e oo i le tasi mauga.", "from the one mountain by oo in the one mountain"]]},
  {num:13,words:[["A e faatafunaina le nuu ona o e mau ai,", "but by faatafunaina the nation then to opinion"], ["ona o le fua o a latou amio.", "because of the fruit but them conduct"]]},
  {num:14,words:[["Ia e leoleo i lou nuu ma lou tootoo,", "to to police in your nation and your tootoo"], ["o le lafu mamoe o lou tofi;", "the a herd sheep your appoint"], ["o e nofo ese i le vao,", "who dwell away in the vegetation"], ["i Karamelu;", "in karamelu"], ["ia latou aai i Vasana ma Kiliata,", "to them eat in vasana and kiliata"], ["pei o ona po anamuā lava.", "to be broken then night anamuā indeed"]]},
  {num:15,words:[["Faapei o ona po sa e sau ai i le nuu o Aikupito,", "like then night to come in the nation Egypt"], ["ou te faaali atu i ai vavega.", "I reveal therein a wonder"]]},
  {num:16,words:[["E iloa e nuu ese,", "to known to nation away"], ["ona masiasi ai lea o i latou i lo latou malosi uma;", "and to be ashamied them in the them strong all"], ["latou te ufiufi ai o latou gutu i o latou lima,", "them ufiufi them mouth in them five"], ["e tutuli foi o latou taliga.", "by tutuli also them ear"]]},
  {num:17,words:[["Latou te etoeto i le efuefu pei o le gata;", "them etoeto in the efuefu to be broken the a snake"], ["e pei o mea fetolofi i le laueleele latou te tetemu ai i mea ua puipuia mo i latou;", "to to be broken thing creep in the ground them to tremble in thing puipuia for them"], ["latou te matatau ia Ieova lo tatou Atuā;", "them fear to Jehovah our atuā"], ["latou te fefefe foi ia te oe.", "them fefefe also unto you"]]},
  {num:18,words:[["O ai ea se Atua e tusa ma oe o le faamagalo agasala,", "to rise (as a diver to the sur- a God to according to and you the forgive sin"], ["ma ua le manatua solitulafono a e o totoe o lona tofi? Na te le faamoemoe pea i lona toasa,", "and the remember solitulafono but by phiral of foe his appoint the to expect continually in his wrath"], ["auā e fiafia o ia i le alofa.", "for to competition he in the love"]]},
  {num:19,words:[["E toe alofa mai o ia ia te i tatou,", "to again love from he unto in us"], ["e faatoilaloina e ia a tatou amioletonu;", "by faatoilaloina by him but us wickedness"], ["e te lafo foi a latou agasala uma i mea loloto o le sami.", "by cloth used as gratuity for a talking chief also but them sin all in thing deep the sea"]]},
  {num:20,words:[["E te faaoo le faamaoni ia Iakopo,", "by faaoo the faithful to James"], ["o le alofa ia Aperaamo,", "the love to Abraham"], ["sa e tauto ai i o matou tamā talu mai ona po anamua.", "to to take an oath in we father since from then night anamua"]]},
];
renderVerseSet(mic_ch_7_Verses, 'mic-ch7-verses');

})();