(function() {
var _mic_ch_1_Verses = [
  {num:1,words:[["O le afioga", "the word"], ["a Ieova", "of the LORD"], ["na oo mai ia", "came he"], ["Mika", "Micah"], ["le Morese", "the Morese"], ["i ona po", "in his nights"], ["o Iotama,", "Iotama"], ["ma Aasa,", "and Asa"], ["ma Esekia,", "and Hezekiah"], ["o tupu o Iuta,", "king of Judas"], ["na ia iloa", "he knew"], ["i mea", "in thing"], ["a Samaria", "of Samaria"], ["ma Ierusalema.", "and Jerusalem"]]},
  {num:2,words:[["Fa'alogologo mai ia outou", "listen from he you all"], ["nuu uma;", "nation all"], ["fa'asaga mai ia", "face from he"], ["le lalolagi e,", "the earth by"], ["atoa ma mea", "and thing"], ["ua tumu ai,", "filled"], ["seia fai", "until make"], ["e le Ali'i", "shall not Lord"], ["o Ieova ana mau", "the LORD cave opinion"], ["ia te outou,", "unto you all"], ["o le Ali'i", "the Lord"], ["lava ai", "very"], ["lona malumalu paia.", "his temple holy"]]},
  {num:3,words:[["Auā fa'auta,", "for behold"], ["o loo afio mai", "is dwell from"], ["Ieova ai", "the LORD"], ["lona afioga,", "his word"], ["e afio ifo", "to dwell down"], ["o ia,", "he"], ["ma soli", "and to tread upon"], ["i mea maualuluga", "in thing most high"], ["o", "o"], ["i le lalolagi.", "on the earth"]]},
  {num:4,words:[["E liu suāvai mauga", "by liu water mountain"], ["i lalo ia te ia,", "in under to him"], ["e māvaevae vanu,", "by māvaevae valley"], ["pei o le pulu", "like the latex or milky sap secreted from any plant in general e.g. breadfruit"], ["i le afi,", "in the fire"], ["fa'apei", "like"], ["o le vai", "the water"], ["ua tafe ifo", "to flow down"], ["i le tofē.", "in the tofē"]]},
  {num:5,words:[["Ona", "and"], ["o le solitulafono", "the transgression"], ["a Iakopo", "of Jacob"], ["e oo ai", "it shall come to pass"], ["ia mea uma,", "he all things"], ["ona o agasala foi", "because of sin also"], ["a le 'āiga", "but the family"], ["o Isaraelu.", "Israel"], ["Se a ea", "what indeed? / why?"], ["le solitulafono", "the transgression"], ["a Iakopo?", "of Jacob"], ["E le o Samaria ea?", "by the of Samaria indeed?/really?"], ["O", "O"], ["a ea foi", "but indeed?/really? also"], ["mea maualuluga", "thing most high"], ["a Iuta?", "of Judas"]]},
  {num:6,words:[["E le o Ierusalema ea?", "by the of Jerusalem indeed?/really?"], ["O le mea lea", "therefore"], ["ou te fai ai", "I will make"], ["Samaria", "Samaria"], ["ma faupuegā maa", "and plan stone"], ["i le fanua,", "in the land"], ["ma mea", "and thing"], ["e totō ai", "to blood"], ["vine,", "vine"], ["ou te tuleia foi", "I will tuleia also"], ["i lalo", "in under"], ["i le vanu", "in the valley"], ["ona maa,", "and stone"], ["ou te fa'ataatitiafuaina", "I will faataatitiafuaina"], ["ona fa'avae.", "and foundation"]]},
  {num:7,words:[["E nutininiia foi", "by nutininiia also"], ["ona tupua", "and pillar"], ["ua tā uma,", "struck all"], ["e susunuina foi", "to burned also"], ["ona taui uma", "and a reward all"], ["i le afi,", "in the fire"], ["ou te fa'atafunaina foi", "I will destroyed also"], ["ona tupua uma;", "and pillar all"], ["auā", "for"], ["o le taui", "the a reward"], ["o le fafine talitane", "the women harlot"], ["na ia fa'aputuina ai,", "he to gather together"], ["e toe foi atu foi", "to went back also"], ["ia mea i le", "he thing in the"], ["taui", "a reward"], ["o le fafine talitane.", "the women harlot"]]},
  {num:8,words:[["O le mea lea", "therefore"], ["ou te tagitu'i ai,", "I will tagitu'i"], ["ma ou uio,", "and I uio"], ["ou te fealuai", "I will walk about"], ["ma le", "and the"], ["le ofu", "the garment"], ["ma le", "and the"], ["le lavalavā;", "the naked"], ["ou te tagi pei", "I will cry like"], ["o luko,", "wolf"], ["ma ou fa'anoanoa pei", "and I mourn like"], ["o iaena.", "iaena"]]},
  {num:9,words:[["Auā", "for"], ["e leaga", "to evil"], ["ona manua;", "and was animal"], ["auā", "for"], ["ua oo lava", "it came to pass very"], ["i Iuta;", "in Judas"], ["ua pāia lava", "holy very"], ["le faitotoa", "the door"], ["o lo'u nuu,", "my nation"], ["o Ierusalema lava.", "Jerusalem very"]]},
  {num:10,words:[["Aua ne'i ta'uatua", "for now ta'uatua"], ["i Kato,", "in Gath"], ["aua ne'i fetagisi", "for now wept"], ["i Ako;", "in Ako"], ["ia e taafili i le", "he by taafili in the"], ["efuefu", "dust"], ["i Petofira.", "in Petofira"]]},
  {num:11,words:[["Ina ui ane", "so that although"], ["ia e le", "he by the"], ["o lavalavā", "naked"], ["ma le mā,", "and the and"], ["o oe", "you"], ["na lē mau", "not opinion"], ["i Safiri;", "in Safiri"], ["e lei alu atu", "by not go away"], ["le", "the"], ["ua mau", "opinion"], ["i Saanana;", "in Saanana"], ["o le auega", "the alas! oh!"], ["a Peteseli", "of Peteseli"], ["e aveeseina ia ia te outou", "to carried away to him you all"], ["le mea", "the thing"], ["e tu ai", "to stand"], ["o ia.", "he"]]},
  {num:12,words:[["Ua fa'anoanoa lava", "mourned very"], ["le", "the"], ["ua mau", "opinion"], ["i Marota", "in Marota"], ["ona", "and"], ["o le manuia;", "the prosper"], ["auā", "for"], ["ua oo ifo", "it came to pass down"], ["le malaia mai ia", "the disaster from he"], ["Ieova", "the LORD"], ["i le faitotoa", "at the door"], ["o Ierusalema.", "Jerusalem"]]},
  {num:13,words:[["O oe lē mau", "you not opinion"], ["i Lakisa,", "in Lakisa"], ["ia e nonoa", "he to to tie"], ["le nofoa fa'ataavalevale", "the a seat to roll round and"], ["i le solofanua televave;", "in the horse televave"], ["(o ia", "he"], ["o le amataga", "the beginning"], ["o le agasala", "the sin"], ["i le tama fafine", "in the child women"], ["a Siona;)", "of Zion"], ["auā", "for"], ["ua iloa", "knew"], ["i totonu ia te oe", "in inside unto you"], ["solitulafono", "transgressions"], ["a Isaraelu.", "of Israel"]]},
  {num:14,words:[["O le mea lea", "therefore"], ["e te avatu ai", "by give away"], ["se tusi alei", "a book to drive"], ["ia Morese-Kato;", "he Morese-Kato"], ["e fai foi", "to make also"], ["fale o Akasepa", "house of Akasepa"], ["ma pepelo", "and false"], ["i tupu o Isaraelu.", "in king of Israel"]]},
  {num:15,words:[["I le", "in the"], ["ma lea,", "and"], ["o oe", "you"], ["na o lē", "only not"], ["mau", "opinion"], ["i Maresa,", "in Maresa"], ["ou te au mai ia te oe", "I will bring unto you"], ["o le", "the"], ["na te fai oe", "he made you"], ["mona;", "to burst forth (as faiai"], ["e oo lava", "it shall come to pass very"], ["ia", "he"], ["i Atulama", "in Atulama"], ["le mamalu o Isaraelu.", "the glory of Israel"]]},
  {num:16,words:[["Ia e tafi", "he to to brush"], ["lou lauulu", "your hair"], ["ma ia", "and he"], ["e sele mamā", "to a snare clean"], ["ona o au", "because of me"], ["fānau pele,", "born dear"], ["ia e fa'alautele", "he to make wide"], ["le mea", "the thing"], ["ua tafia pei", "tafia like"], ["o le aeto;", "the aeto"], ["auā", "for"], ["ua tāfea ese", "exiled captive away"], ["i lātou ia te oe.", "them unto you"]]},
];
renderVerseSet(_mic_ch_1_Verses, 'mic-ch1-verses');

var _mic_ch_2_Verses = [
  {num:1,words:[["Oi talofa", "wo"], ["i", "in"], ["e mafaufau", "to think"], ["i amioletonu,", "in wickedness"], ["ma lātou saunia mea leaga", "and they prepared thing evil"], ["i o lātou", "in of they"], ["moega;", "bed"], ["pe a malama", "even though / although malama"], ["ae", "but"], ["le taeao", "the morning"], ["ua lātou faia,", "they did"], ["auā", "for"], ["ua mafai ia te", "able unto"], ["i lātou.", "them"]]},
  {num:2,words:[["Ua lātou mananao foi", "they desired also"], ["i fanua,", "in land"], ["ma lātou fao ai", "and they to seize"], ["fa'asaua,", "cruel"], ["atoa ma fale,", "and house"], ["ma lātou avea;", "and they become"], ["ua lātou saua atu", "they to have a return of sick-"], ["i le tagata", "in the man"], ["ma lona 'āiga,", "and his family"], ["o le tagata", "man"], ["ma lona tofi.", "and his lot"]]},
  {num:3,words:[["O le mea lea", "therefore"], ["o loo fa'apea mai ai", "saying from"], ["Ieova,", "the LORD"], ["Fa'auta,", "behold"], ["o loo ou te", "is/are I will"], ["mafaufau", "think"], ["i se mea leaga", "in a thing evil"], ["i lenei", "in this"], ["lava 'āiga,", "very family"], ["tou te", "second person plural"], ["le mafai ona", "not able and"], ["'alo ese ai", "dodged away"], ["o outou", "you all"], ["ua;", "ua;"], ["tou te", "second person plural"], ["le savavali foi", "the walked also"], ["ma le fa'asiasia;", "and the haughty"], ["auā", "for"], ["e leaga ia", "to evil he"], ["ona po.", "and night"]]},
  {num:4,words:[["E saunia", "to prepared"], ["se fa'ataoto ia te outou", "a lay down unto you all"], ["i lea aso,", "on that day"], ["e pese", "to a song"], ["le pese", "the a song"], ["e aualofa a'i tele", "to a keepsake great"], ["lava,", "very"], ["e fa'apea,", "saying"], ["Ua matuā fa'atafunaina", "exceedingly destroyed"], ["i tātou;", "us"], ["ua suia e", "replaced you"], ["ia le tofi", "he the lot"], ["o lo'u nuu;", "my nation"], ["aue!", "alas! oh!"], ["ua ia aveeseina ai", "he carried away"], ["ia te au,", "unto me"], ["ua", "ua"], ["na tufatufa", "to divide"], ["i o tātou", "in of we"], ["fanua", "land"], ["ina ia liliueseina.", "so that liliueseina"]]},
  {num:5,words:[["O le mea lea", "therefore"], ["o le a leai ai", "what no"], ["ia te oe", "unto you"], ["se", "a"], ["na te lāfolafoina", "he cloth used as gratuity for a talking chief"], ["se maea", "a rope"], ["pe a fai", "even though / although make"], ["le vili", "the a gimblet"], ["i le fa'apotopotoga", "in the assembly"], ["a Ieova.", "of the LORD"]]},
  {num:6,words:[["Ua lātou fa'apea mai", "they so from"], ["i", "in"], ["e vavalo mai,", "to prophesy from"], ["Aua ne'i outou", "for now you all"], ["vavalo.", "prophesy"], ["Lātou te", "they will"], ["le vavalo ia te", "the prophesy unto"], ["i lātou nei,", "them this"], ["e le mavae", "shall not passed"], ["le masiasi.", "the to be ashamied"]]},
  {num:7,words:[["Oi!", "alas ! oh !"], ["o 'upu fa'apea", "word so"], ["a le 'āiga", "but the family"], ["o Iakopo!", "Jacob"], ["E vaivai ea", "to weak indeed?/really?"], ["le Agaga o Ieova?", "the spirit the LORD"], ["O ana ea", "cave indeed?/really?"], ["ia galuega?", "he work"], ["O a'u 'upu", "I am word"], ["e le lelei ai ea", "shall not good indeed?/really?"], ["le", "the"], ["ua sāvali", "walked"], ["ma le amiotonu?", "and the righteous"]]},
  {num:8,words:[["A", "but"], ["ua tulai", "arose up"], ["lo'u nuu talu", "my nation since"], ["mai anamua pei", "from ancient like"], ["o se", "a"], ["ua ita mai lava;", "angry from very"], ["ua outou fao", "you all to seize"], ["le pulupulu", "the latex or milky sap secreted from any plant in general e.g. breadfruit"], ["atoa ma le ofu tele", "and the garment great"], ["ia te i lātou", "unto them"], ["o", "o"], ["e ui ane", "to although"], ["ma le fa'atalanoa,", "and the faatalanoa"], ["o", "o"], ["e ua foi mai", "to returned"], ["i le taua.", "in the battle"]]},
  {num:9,words:[["Ua outou tulia", "you all driven away"], ["fafine", "women"], ["o lo'u nuu", "my nation"], ["i o lātou", "in of they"], ["fale", "house"], ["e fiafia", "to pleased"], ["i ai;", "therein"], ["ua outou ave ese foi", "you all took away also"], ["lo'u mamalu", "my glory"], ["i", "in"], ["a lātou fānau", "their born"], ["e fa'avavau.", "forever/everlasting"]]},
  {num:10,words:[["Tutū ia", "stood up he"], ["i luga outou,", "in above you all"], ["ina o ese", "so that of away"], ["ia;", "he"], ["auā", "for"], ["e le", "by the"], ["o lo outou malologa lenei;", "your a resting place this"], ["ua leaga,", "evil"], ["o le mea lea", "therefore"], ["e malaia ai", "to disaster"], ["outou,", "you all"], ["e matuā tele foi", "to exceedingly great also"], ["le malaia.", "the disaster"]]},
  {num:11,words:[["Ai", "Ai"], ["se tagata", "a man"], ["e sāvali", "to walk"], ["e tusa ma lona loto", "according to his heart"], ["ma le fa'a'ole'ole", "and the treacherous"], ["e pepelo mai,", "to false from"], ["e fa'apea mai ,", "saying from"], ["Ou te vavalo", "I will prophesy"], ["ia te oe", "unto you"], ["i le uaina", "in the wine"], ["ma le 'ava;", "and the beard"], ["e avea lava", "to become very"], ["ia", "he"], ["ma perofeta", "and prophesied"], ["i lenei", "in this"], ["nuu.", "nation"]]},
  {num:12,words:[["Iakopo e,", "Jacob by"], ["ou te fa'apotopoto", "I will gather"], ["lava ia te outou uma lava;", "very unto you all all very"], ["ou te aofaiina", "I will number"], ["lava", "very"], ["e o totoe", "by of phiral of foe"], ["o Isaraelu,", "Israel"], ["ou te fa'atasia", "I will faatasia"], ["i lātou pei", "them like"], ["o le lafu mamoe", "the flock sheep"], ["i Posara,", "in Posara"], ["pei o le lafu manu", "like the flock animal"], ["i totonu", "in inside"], ["o le mea", "the thing"], ["e fafaga ai,", "to a woman's burden"], ["lātou te soona ualolo", "they will without form rain with a flood"], ["ona", "and"], ["o le vao tagata.", "the vegetation man"]]},
  {num:13,words:[["Ua alu ae", "went up"], ["i o lātou", "in of they"], ["luma", "before"], ["le", "the"], ["na te lepetia,", "he overthrown"], ["ua lātou lepeti,", "they lepeti"], ["ma lātou ui ane", "and they although"], ["i le faitotoa,", "at the door"], ["ua lātou", "they"], ["o atu ai", "went"], ["lava,", "very"], ["e afio atu foi", "to dwell also"], ["lo lātou Tupu", "their king"], ["i o lātou", "in of they"], ["luma,", "before"], ["e muamua foi", "to first the beginning also"], ["Ieova ia te", "the LORD unto"], ["i lātou.", "them"]]},
];
renderVerseSet(_mic_ch_2_Verses, 'mic-ch2-verses');

var _mic_ch_3_Verses = [
  {num:1,words:[["Sa a'u fa'apea atu foi,", "me so also"], ["Fa'afofoga mai ia outou", "listen from he you all"], ["matai o Iakopo,", "chief of Jacob"], ["ma outou faipule", "with you a councillor"], ["o le 'āiga", "the family"], ["o Isaraelu,", "Israel"], ["E le o ia te outou", "by the he you all"], ["ea", "indeed?/really?"], ["ona iloa", "and know"], ["le fa'amasinoga?", "the judgment"]]},
  {num:2,words:[["O outou", "you all"], ["o loo 'ino'ino", "is disdained"], ["i mea lelei,", "in thing good"], ["ma fiafia", "and pleased"], ["i mea leaga,", "in thing evil"], ["o loo outou", "is you all"], ["sae ese o lātou", "sae away of they"], ["pa'u,", "fell"], ["atoa ma aano", "and body"], ["i o lātou", "in of they"], ["ivi.", "bone"]]},
  {num:3,words:[["O", "O"], ["e aai foi", "to cities also"], ["i tino", "in body"], ["o lo'u nuu,", "my nation"], ["ma saeeseina o lātou", "and saeeseina of they"], ["pa'u,", "fell"], ["ma gauia o lātou", "and was to break of they"], ["ivi,", "bone"], ["e vaevaea lava pei", "to was foot very like"], ["o mea", "thing"], ["e tuu", "to put"], ["i le ulo,", "in the ulo"], ["pei o tufaaga foi", "like of portion also"], ["i totonu", "in inside"], ["o le pani.", "the bun"]]},
  {num:4,words:[["Ona lātou alalaga atu ai lea", "and they cry out then"], ["ia Ieova,", "he the LORD"], ["a", "but"], ["e le fa'afofoga", "shall not listen"], ["mai ai", "from"], ["o ia ia te", "he unto"], ["i lātou;", "them"], ["a", "but"], ["e 'alo ese", "to dodged away"], ["ona fofoga ia te", "and face unto"], ["i lātou", "them"], ["i ia lava", "in he very"], ["ona po,", "and night"], ["auā", "for"], ["ua leaga lava", "evil very"], ["a lātou mea", "their thing"], ["e fai.", "to make"]]},
  {num:5,words:[["O loo fa'apea mai", "saying from"], ["Ieova", "the LORD"], ["i perofeta o", "in prophesied of"], ["e fa'asese", "to to cause to go astray"], ["i lo'u nuu,", "in my nation"], ["o", "o"], ["e fēu", "by fēu"], ["i o lātou", "in of they"], ["nifo,", "tooth"], ["ma lātou alalaga atu,", "and they cry out"], ["O le manuia;", "the prosper"], ["a", "but"], ["o le", "the"], ["ua", "ua"], ["le avane mea", "the gave thing"], ["i o lātou", "in of they"], ["gutu,", "mouth"], ["lātou te sauni", "they will he who beg^ins the game"], ["lava", "very"], ["le taua ia te ia.", "the battle to him"]]},
  {num:6,words:[["O le mea lea", "therefore"], ["e pogia ai", "to passive oi' po"], ["outou", "you all"], ["ma le leai", "and the no"], ["o se mea", "a thing"], ["e vaaia,", "to seen"], ["e oo foi", "it shall come to pass also"], ["le pouliuli ia te outou", "the darkness unto you all"], ["ma le leai", "and the no"], ["o se iite;", "a iite"], ["e goto foi", "to sank also"], ["le lā", "the sun"], ["i ia perofeta,", "in he prophesied"], ["e pogisa foi", "to darkness also"], ["le ao ia te", "the day unto"], ["i lātou.", "them"]]},
  {num:7,words:[["Ona masiasi ai lea", "and to be ashamied then"], ["o tagata vaai,", "of men look"], ["e fememeai ai", "to whisper to one another"], ["foi o", "also of"], ["e iite;", "by iite"], ["lātou te ufiufi foi", "they will covering also"], ["i", "in"], ["a lātou 'ava,", "their beard"], ["o", "o"], ["i lātou uma lava,", "them all very"], ["auā", "for"], ["e leai se tali", "there is no respond"], ["mai le Atua.", "from God"]]},
  {num:8,words:[["A", "but"], ["e peitai", "to however"], ["o a'u,", "I am"], ["e moni lava,", "verily I say"], ["ua fa'atumuina a'u", "filled me"], ["i le mana", "in the to get"], ["e le Agaga", "shall not spirit"], ["o Ieova,", "the LORD"], ["o le fa'amasinoga foi,", "the judgment also"], ["ma le malosi,", "and the strong"], ["e fa'ailoa atu ai", "to declared"], ["ia Iakopo", "he Jacob"], ["o lana solitulafono,", "his transgression"], ["e fa'ailoa atu foi", "to declared also"], ["ia Isaraelu", "he Israel"], ["o lana agasala.", "his sin"]]},
  {num:9,words:[["Ina fa'afofoga mai ia", "so that listen from he"], ["i le mea nei", "in the thing this"], ["o outou matai", "you all chief"], ["o le 'āiga", "the family"], ["o Iakopo,", "Jacob"], ["ma outou faipule", "with you a councillor"], ["o le 'āiga", "the family"], ["o Isaraelu,", "Israel"], ["o", "o"], ["e 'ino'ino", "to disdained"], ["i le fa'amasinoga,", "in the judgment"], ["ma fa'apiopio", "and faapiopio"], ["i mea tonu uma;", "in thing right all"], ["o", "o"], ["e ati ae Siona", "to to pull up up Zion"], ["i le toto,", "in the blood"]]},
  {num:10,words:[["ma Ierusalema", "and Jerusalem"], ["i le amio leaga.", "in the iniquity"]]},
  {num:11,words:[["O", "O"], ["ona matai", "and chief"], ["ua lātou fa'amasino", "they judged"], ["i le fia fai taui,", "in the want to do something make a reward"], ["o ana ositaulaga foi", "cave high priest also"], ["ua lātou a'oa'o", "they excellent"], ["i le fia fai taui,", "in the want to do something make a reward"], ["ma ana perofeta", "and cave prophesied"], ["ua lātou iite", "they iite"], ["i le fia fai tupe;", "in the want to do something make St. Thomas bean"], ["a", "but"], ["ua lātou fa'alagolago ia", "they rely he"], ["Ieova,", "the LORD"], ["ma fa'apea ane,", "and so"], ["E le o ia te", "by the he"], ["i tātou ea Ieova?", "us indeed?/really? the LORD"], ["e le oo mai", "by the came"], ["se mea leaga", "a thing evil"], ["ia te i tātou.", "unto us"]]},
  {num:12,words:[["O le mea lea", "therefore"], ["e fai ai", "to make"], ["Siona", "Zion"], ["ma fanua", "and land"], ["e suatia", "by suatia"], ["ona o outou,", "because of you all"], ["e fai foi", "to make also"], ["Ierusalema", "Jerusalem"], ["ma faupuegāmaa,", "and faupuegāmaa"], ["o le mauga foi", "the mountain also"], ["o", "o"], ["i ai", "therein"], ["le fale", "the house"], ["e fai lea", "to make"], ["ma mea maualuga", "and thing Iiigli"], ["i le vao mātua.", "in the wilderness great"]]},
  {num:13,words:[["Ua alu ae", "went up"], ["i o lātou", "in of they"], ["luma", "before"], ["le", "the"], ["na te lepetia,", "he overthrown"], ["ua lātou lepeti,", "they lepeti"], ["ma lātou ui ane", "and they although"], ["i le faitotoa,", "at the door"], ["ua lātou", "they"], ["o atu ai", "went"], ["lava,", "very"], ["e afio atu foi", "to dwell also"], ["lo lātou Tupu", "their king"], ["i o lātou", "in of they"], ["luma,", "before"], ["e muamua foi", "to first the beginning also"], ["le Ali'i ia te", "the Lord unto"], ["i lātou.", "them"], ["O le иpи", "the иpи"], ["e aoai atu 1 ali'i", "to chastise 1 Lord"], ["o le nuu", "the nation"], ["ma perofeta pepelo", "and prophesied false"], ["Sa a'u fa'apea atu foi,", "me so also"], ["Fa'afofoga mai ia outou", "listen from he you all"], ["matai o lakopo,", "chief of lakopo"], ["ma outou faipule", "with you a councillor"], ["o le 'āiga", "the family"], ["o Isaraelu,", "Israel"], ["E le o ia te outou", "by the he you all"], ["ea", "indeed?/really?"], ["ona iloa", "and know"], ["le fa'amasinoga?", "the judgment"]]},
];
renderVerseSet(_mic_ch_3_Verses, 'mic-ch3-verses');

var _mic_ch_4_Verses = [
  {num:1,words:[["A o aso", "but of day"], ["e gata ai", "to a snake"], ["e oo ina fa'atumauina ai", "it shall come to pass so that established"], ["le mauga o", "the mountain of"], ["i ai", "therein"], ["le fale o Ieova", "the house the LORD"], ["i tumutumu o mauga,", "in top of mountain"], ["e fa'amaualugaina foi", "to pride also"], ["ia sili i", "he most in"], ["mauga iti,", "mountain small"], ["ona gasolo ane lea", "and swifi"], ["o nuu", "nation"], ["i ai.", "therein"]]},
  {num:2,words:[["E o mai", "shall come"], ["lava nuu ese", "very nation away"], ["e tele,", "to great"], ["ma lātou fa'apea ane,", "and they so"], ["O mai ia,", "came he"], ["tātou", "we"], ["o ae ia", "went up he"], ["i le mauga", "in the mountain"], ["o Ieova,", "the LORD"], ["o le fale foi", "the house also"], ["o le Atua", "of God"], ["o Iakopo;", "Jacob"], ["e a'oa'o mai ai", "to excellent from"], ["o ia ia te", "he unto"], ["i tātou", "us"], ["i ona ala,", "in his way"], ["ona tātou savavali ai lea", "and we walked then"], ["i ona ala;", "in his way"], ["auā", "for"], ["e alu atu", "to go away"], ["le tulafono mai Siona,", "the law from Zion"], ["o le afioga foi", "the word also"], ["a Ieova mai Ierusalema.", "of the LORD from Jerusalem"]]},
  {num:3,words:[["E fa'amasino foi", "to judge also"], ["o ia", "he"], ["i nuu e tele,", "in nation to great"], ["e aoai atu foi", "to chastise also"], ["i nuu malolosi", "in nation mighty"], ["e mamao;", "to far"], ["ona lātou tu'i ai lea", "and they '2l high chief then"], ["i", "in"], ["a lātou pelu", "their sword"], ["e fai ma uamea", "to be iron"], ["o suotosina,", "suotosina"], ["o lātou tao foi", "they spear also"], ["e fai ma polo teu vine;", "to be Chili pepper store vine"], ["e le sii atu foi", "shall not lift up also"], ["le pelu", "the sword"], ["e le tasi nuu,", "shall not one nation"], ["lātou te", "they will"], ["le toe a'oa'o foi", "the again excellent also"], ["i taua.", "in war"]]},
  {num:4,words:[["A", "but"], ["e taitasi", "by each"], ["ma nofo", "and dwell"], ["i lalo", "in under"], ["o lona vine,", "his vine"], ["ma lalo", "and under"], ["o lona mati;", "his fig"], ["e leai foi", "there is not also"], ["se", "a"], ["na te fa'amatau mai;", "he made ax from"], ["auā", "for"], ["ua fa'apea ona", "saying and"], ["tŭlei mai ai", "tŭlei from"], ["le siufofoga o Ieova", "the voice the LORD"], ["o 'au.", "troops"]]},
  {num:5,words:[["Auā o nuu uma", "for of nation all"], ["e taitasi", "by each"], ["ma sāvali", "and walk"], ["i le igoa", "in the name"], ["o lātou atua,", "they God"], ["o", "o"], ["i tātou foi,", "us also"], ["tātou te savavali", "we will walked"], ["i le suafa", "in the name"], ["o Ieova lo tātou Atua e fa'avavau fa'avavau lava.", "the LORD our God forever everlasting very"]]},
  {num:6,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["O lea aso ou te fa'apotopoto ai", "therefore day I will gather"], ["le nuu", "the nation"], ["ua setusetu,", "'"], ["ou te aofaiina fa'atasi foi", "I will number together also"], ["le nuu", "the nation"], ["ua tulia,", "driven away"], ["ma le nuu", "and the nation"], ["ua ou fa'atigaina.", "I afflicted"]]},
  {num:7,words:[["Ou te fa'atotoe nisi", "I will make phiral of foe some"], ["o le nuu", "the nation"], ["ua setusetu,", "'"], ["ou te faia foi", "I will make also"], ["ma nuu malosi", "and nation strong"], ["e ua tāfea mamao,", "to exiled captive far"], ["e pule foi", "to rule also"], ["Ieova ia te", "the LORD unto"], ["i lātou", "them"], ["i le mauga", "in the mountain"], ["o Siona", "Zion"], ["e amata", "to began"], ["i ona po nei,", "in his nights this"], ["e oo", "it shall come to pass"], ["i le fa'avavau.", "in the everlasting"]]},
  {num:8,words:[["O oe foi", "you also"], ["le 'olo", "the trench"], ["o le lafu mamoe,", "the flock sheep"], ["o le mauga", "the mountain"], ["o le tama fafine", "the child women"], ["a Siona,", "of Zion"], ["e oo mai", "it shall come to pass from"], ["lava ia te oe,", "very unto you"], ["e oo mai", "it shall come to pass from"], ["lava", "very"], ["le muai pule;", "the first rule"], ["e oo mai le mālō", "it shall come to pass from the kingdom"], ["o le tama fafine", "the child women"], ["a Ierusalema.", "of Jerusalem"]]},
  {num:9,words:[["O lenei,", "now"], ["se a le mea", "what / why"], ["e te alaga tele ai?", "by cry great"], ["E leai ea", "there is not indeed?/really?"], ["se tupu ia te oe?", "a king unto you"], ["Ua fano ea", "perished indeed?/really?"], ["lou faipule?", "your a councillor"], ["ina ua maua oe", "when received you"], ["i tiga pei", "in grieved like"], ["o se fafine", "a women"], ["a fānau mai.", "but born"]]},
  {num:10,words:[["Le tama fafine", "the child women"], ["a Siona e,", "of Zion by"], ["ina fa'atiga ia,", "so that afflict he"], ["ma ia fānau mai,", "and he born"], ["pei o le fafine", "like the women"], ["a fānau mai;", "but born"], ["auā", "for"], ["e te alu ese nei", "by go away this"], ["i le aai", "in the cities"], ["a", "but"], ["e mau", "to opinion"], ["i le vao,", "in the wilderness"], ["e te oo", "by oo"], ["lava", "very"], ["i Papelonia;", "in Babylon"], ["e laveaiina oe", "to delivered you"], ["i lea", "in"], ["mea,", "thing"], ["e laveai Ieova", "to delivered the LORD"], ["ia te oe", "unto you"], ["i lea", "in"], ["mea ai", "thing"], ["lima o", "hand of"], ["i lātou", "them"], ["o", "o"], ["e ita mai ia te oe.", "to angry from you"]]},
  {num:11,words:[["Ua fa'apotopotoina nei foi", "gathered together this also"], ["o nuu e tele", "nation to great"], ["o le a tau ma oe,", "what fight against you"], ["o", "o"], ["e fa'apea ane,", "saying"], ["Ia leaga o ia;", "he evil he"], ["se'i vaai foi", "a flower put into the hair or look also"], ["o tātou mata", "we eye"], ["i Siona.", "in Zion"]]},
  {num:12,words:[["A o", "but of"], ["i lātou,", "them"], ["lātou te", "they will"], ["le iloa manatu", "the know thought"], ["o Ieova,", "the LORD"], ["lātou te", "they will"], ["le iloa foi", "the know also"], ["lana pule;", "his rule"], ["auā", "for"], ["e fa'apotopotoina", "to gathered together"], ["i lātou e", "them by"], ["ia pei o", "he like of"], ["fusi saito", "belt wheat"], ["i le mea", "in the thing"], ["e soli ai", "to to tread upon"], ["saito.", "wheat"]]},
  {num:13,words:[["Le tama fafine", "the child women"], ["a Siona e,", "of Zion by"], ["tu ia", "stand he"], ["i luga,", "in above"], ["ma soli;", "and to tread upon"], ["auā ou te faia", "for I will make"], ["lou nifo", "your tooth"], ["ma uamea,", "and iron"], ["ou te faia foi", "I will make also"], ["ou atigivae", "I atigivae"], ["ma 'apa memea;", "and can scarlet"], ["e te tu'imomomoina nuu", "by tu'imomomoina nation"], ["e tele;", "to great"], ["ou te fa'atoina foi", "I will accursed thing also"], ["mo Ieova", "for the LORD"], ["a lātou vete,", "their plunder"], ["atoa ma", "and"], ["a lātou oloa", "their goods"], ["mo le Ali'i", "for the Lord"], ["o le lalolagi uma.", "all the earth"]]},
  {num:14,words:[["Ou te lepeti foi", "I will lepeti also"], ["i au tupua", "in me pillar"], ["o Asaira", "Asherah"], ["i totonu ia te oe,", "in inside unto you"], ["ma ou fa'atafunaina ou aai.", "and I destroyed I cities"]]},
  {num:15,words:[["Ou te taui atu", "I will a reward"], ["ma le ita", "and the angry"], ["e matuā tele", "to exceedingly great"], ["i nuu ese", "in nation away"], ["o", "o"], ["e ua", "to"], ["le fa'alogo mai.", "the hearken from"], ["Ua aoai atu", "chastise"], ["le Atua ia te 1 lātou", "God unto 1 they"], ["ona o aтїo eseese", "because of aтїo divided"], ["Ina fa'alogo mai ia", "so that hearken from he"], ["i le mea", "in the thing"], ["o loo fetalai mai ai", "is said"], ["le Ати,", "the Ати"], ["Tu ia", "stand he"], ["i luga,", "in above"], ["ina finau atu", "so that contend toward"], ["ia", "he"], ["i luma o mauga,", "before mountain"], ["ia fa'alogo foi", "he hearken also"], ["mauga iti", "mountain small"], ["i lou leo.", "in your voice"]]},
];
renderVerseSet(_mic_ch_4_Verses, 'mic-ch4-verses');

var _mic_ch_5_Verses = [
  {num:1,words:[["O lenei,", "now"], ["ina fa'alaei 'au", "so that faalaei troops"], ["ia", "he"], ["o oe", "you"], ["le tama fafine", "the child women"], ["e ana 'au;", "by his troops"], ["ua ia siosioina", "he surrounded"], ["i tātou", "us"], ["i le taua;", "in the battle"], ["lātou te tā", "they will struck"], ["i le tootoo", "in the staff"], ["le fa'amasino o Isaraelu", "the judge of Israel"], ["i lona alafau.", "in his the cheek"]]},
  {num:2,words:[["A o oe,", "but of you"], ["Peteleema-Efarata,", "Peteleema-Efarata"], ["e itiiti oe", "to small you"], ["i afe o Iuta,", "in thousand of Judas"], ["a", "but"], ["e tupu mai ia te oe", "to king from you"], ["mo a'u", "for me"], ["o le", "the"], ["na te fai ma", "he to be"], ["faipule ia Isaraelu,", "a councillor he Israel"], ["o lona tupu", "his king"], ["mai talu mai anamuā lea,", "from since from ancient"], ["talu mai", "since from"], ["ona po", "and night"], ["o le vavau", "the ancient times"], ["lava.", "very"]]},
  {num:3,words:[["A", "but"], ["e peitai", "to however"], ["e tuua", "to left"], ["i lātou e", "them by"], ["ia seia oo i ona po", "he until oo in his nights"], ["e fānau mai ai", "to born"], ["o ia", "he"], ["o le a fānau;", "what born"], ["ona toe foi mai ai lea", "and returned then"], ["i le fanauga", "in the children"], ["a Isaraelu o", "of Israel of"], ["e totoe", "to phiral of foe"], ["i ona uso.", "in his brother"]]},
  {num:4,words:[["E tu foi", "to stand also"], ["o ia", "he"], ["ma leoleo ia te", "and guard unto"], ["i lātou", "them"], ["i le mana", "in the to get"], ["o Ieova,", "the LORD"], ["ma le mamalu", "and the glory"], ["o le suafa", "the name"], ["o Ieova", "the LORD"], ["lona Atua,", "his God"], ["ona lātou nofo mau ai lea;", "and they dwell opinion then"], ["auā", "for"], ["o", "o"], ["ona po ia", "and night he"], ["e mamalu ai", "to glory"], ["o ia", "he"], ["e oo", "it shall come to pass"], ["i tuluiga", "in anointing"], ["o le lalolagi.", "the earth"]]},
  {num:5,words:[["E fai foi", "to make also"], ["o ia", "he"], ["ma manuia.", "and prosper"], ["Pe a sau Asuria", "even though / although come Assyria"], ["i lo tātou laueleele,", "than we ground"], ["pe a soli foi", "even though / although to tread upon also"], ["e ia", "by him"], ["o tātou maota,", "we the name of a tree"], ["ona tātou totofi ai lea", "and we lot then"], ["o leoleo", "guard"], ["e toafitu", "to seven people"], ["e tetee ia te ia,", "to to refuse to him"], ["ma ali'i sili", "and Lord most"], ["e toavalu.", "to eight people"]]},
  {num:6,words:[["Lātou te fa'asaunoa foi", "they will make to damage also"], ["le nuu o Asuria", "the nation of Assyria"], ["i le pelu,", "by the sword"], ["ma le nuu", "and the nation"], ["o Nimarota", "Nimarota"], ["i ona lava faitotoa;", "in his very door"], ["na te laveai foi", "he delivered also"], ["ia te i tātou", "unto us"], ["ai Asuria,", "Assyria"], ["pe a oo mai", "even though / although came"], ["o ia", "he"], ["i lo tātou laueleele,", "than we ground"], ["pe a soli foi", "even though / although to tread upon also"], ["o ia", "he"], ["i lo tātou nuu.", "than we nation"]]},
  {num:7,words:[["E", "by"], ["i ai", "therein"], ["foi", "also"], ["e ua totoe", "to phiral of foe"], ["o Iakopo", "Jacob"], ["i nuu e tele", "in nation to great"], ["e pei o le sau mai ia", "like the come he"], ["Ieova,", "the LORD"], ["pei o le", "like the"], ["ua foi", "also"], ["i luga o vao iti,", "upon grass/herbs"], ["o le mea", "the thing"], ["e le fa'atalitali", "shall not waited"], ["i tagata,", "in man"], ["e le fa'atalitali foi", "shall not waited also"], ["i le fānau", "in the born"], ["a tagata.", "but man"]]},
  {num:8,words:[["E", "by"], ["i ai", "therein"], ["foi", "also"], ["e ua totoe", "to phiral of foe"], ["o Iakopo", "Jacob"], ["i nuu ese,", "in nation away"], ["o nuu e tele", "nation to great"], ["e pei o le leona", "like the lion"], ["i manu", "in animal"], ["o le vao,", "the vegetation"], ["pei o le leona taanoa", "like the lion an animal that is weaned"], ["i lafu mamoe;", "in flock sheep"], ["pe a ui ane", "even though / although although"], ["o ia", "he"], ["na te soli,", "he to tread upon"], ["ma saei,", "and to tear"], ["e leai foi", "there is not also"], ["se", "a"], ["na te laveaiina.", "he delivered"]]},
  {num:9,words:[["E taualuga", "to the covering of the"], ["lou lima", "your hand"], ["i", "in"], ["e fa'asaua mai ia te oe,", "to cruel from you"], ["e fa'aumatia foi", "to destroyed also"], ["e ua ita", "to angry"], ["mai uma lava", "from all very"], ["ia te oe.", "unto you"]]},
  {num:10,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["O lea aso ou te fa'aumatia ai", "therefore day I will destroyed"], ["au solofanua o ia te oe,", "me horse he you"], ["ou te fa'aumatia foi", "I will destroyed also"], ["ou kariota.", "I chariot"]]},
  {num:11,words:[["Ou te fa'aumatia foi", "I will destroyed also"], ["aai", "cities"], ["o lou nuu,", "your nation"], ["ou te matuā sŏloia foi", "I will exceedingly sŏloia also"], ["ou 'olo uma.", "I trench all"]]},
  {num:12,words:[["Ou te fa'aumatia togafiti fa'ataulāitu ai", "I will destroyed heal faataulāitu"], ["lou lima,", "your hand"], ["e le", "by the"], ["i ai", "therein"], ["foi ia te oe", "also unto you"], ["ni", "some"], ["e iite", "by iite"], ["i ao", "in day"], ["o le lagi.", "Heaven"]]},
  {num:13,words:[["Ou te fa'aumatia foi", "I will destroyed also"], ["au tupua", "me pillar"], ["ua tā,", "struck"], ["atoa ma au", "and me"], ["tupua maa;", "pillar stone"], ["ona", "and"], ["e le toe ifo ai lea", "shall not again down then"], ["i galuega", "in work"], ["a ou lima.", "but I hand"]]},
  {num:14,words:[["Ou te lepeti foi", "I will lepeti also"], ["i au tupua", "in me pillar"], ["o Asaira", "Asherah"], ["i totonu ia te oe,", "in inside unto you"], ["ma ou fa'atafunaina ou aai.", "and I destroyed I cities"]]},
  {num:15,words:[["Ou te taui atu", "I will a reward"], ["ma le ita", "and the angry"], ["e matuā tele", "to exceedingly great"], ["i nuu ese", "in nation away"], ["o", "o"], ["e ua", "to"], ["le fa'alogo mai.", "the hearken from"]]},
];
renderVerseSet(_mic_ch_5_Verses, 'mic-ch5-verses');

var _mic_ch_6_Verses = [
  {num:1,words:[["Ina fa'alogo mai ia", "so that hearken from he"], ["i le mea", "in the thing"], ["o loo fetalai mai ai", "is said"], ["Ieova,", "the LORD"], ["Tu ia", "stand he"], ["i luga,", "in above"], ["ina finau atu", "so that contend toward"], ["ia", "he"], ["i luma o mauga,", "before mountain"], ["ia fa'alogo foi", "he hearken also"], ["mauga iti", "mountain small"], ["i lou leo.", "in your voice"]]},
  {num:2,words:[["Outou mauga e,", "you all mountain by"], ["fa'alogo mai ia", "hearken from he"], ["i le finauga", "in the disputation"], ["a Ieova,", "of the LORD"], ["outou fa'avae tumau foi", "you all foundation enduring also"], ["o le lalolagi;", "the earth"], ["auā", "for"], ["ua ia Ieova", "he the LORD"], ["le finauga", "the disputation"], ["ma lona nuu,", "and his nation"], ["e fefinauai o ia", "to disputing he"], ["ma Isaraelu.", "and Israel"]]},
  {num:3,words:[["Lo'u nuu e,", "my nation by"], ["se a ea sa'u mea", "what indeed? / why? come thing"], ["ua ou faia ia te oe?", "I made unto you"], ["ua ou fa'atiga ia te oe", "I afflicted unto you"], ["i ni", "in some"], ["a?", "but"], ["ina momoli ia", "so that to carry he"], ["o a'u.", "I am"]]},
  {num:4,words:[["Auā", "for"], ["na ou fa'aae mai ia te oe", "I faaae from you"], ["ai", "ai"], ["le nuu o Aikupito,", "the nation of Egypt"], ["ma ou fa'aola", "and I save"], ["ia te oe", "unto you"], ["ai", "ai"], ["le mea", "the thing"], ["sa nofo pologa ai,", "dwelt bondage"], ["na ou aauina foi", "I sent also"], ["i ou luma", "before thee"], ["o Mose,", "Moses"], ["ma Arona,", "and Aaron"], ["ma Miriama.", "and Miriama"]]},
  {num:5,words:[["Lo'u nuu e,", "my nation by"], ["ina", "so that"], ["e manatua ia", "to remember he"], ["le mea", "the thing"], ["sa filifilia", "chosen"], ["e Palako", "by Balak"], ["le tupu o Moapi,", "the king of Moab"], ["ma le mea", "and the thing"], ["sa tali atu ai", "responded"], ["ia te ia", "to him"], ["e Palaamo", "by Balaam"], ["le atali'i o Peoro,", "the son of Peoro"], ["ia e manatua i", "he to remember in"], ["mea", "thing"], ["na faia", "made"], ["e afua", "to began"], ["i Setima", "in shittim wood"], ["e oo", "it shall come to pass"], ["i Kilikala;", "in Gilgal"], ["ina ia", "so that"], ["e iloa", "to know"], ["le agalelei o Ieova.", "the kindness the LORD"]]},
  {num:6,words:[["Ou te alu atu", "I will go away"], ["ma ni", "and some"], ["a", "but"], ["i luma o Ieova,", "before the LORD"], ["ou te ifo atu", "I will down"], ["ma ni", "and some"], ["a", "but"], ["i le Atua maualuga? Ou te alu atu ea", "in the God Iiigli I will go away indeed?/really?"], ["i ona luma", "before him"], ["ma taulaga mu,", "and burnt offerings"], ["ma tamai povi", "and son cattle"], ["e tasi lo lātou tausaga?", "by one their year"]]},
  {num:7,words:[["E fiafia ea Ieova", "to pleased indeed?/really? the LORD"], ["i afe o mamoe poa,", "in thousand of sheep captive"], ["ma manomano alia", "and ten thousand brook"], ["o tafe suāuu? Ou te tuuina atu ea", "to flow oil I will give indeed?/really?"], ["la'u ulumatua", "my firstborn"], ["e sui a'i", "in its place"], ["lo'u solitulafono,", "my transgression"], ["o la'u fānau to tino", "my born to plant body"], ["e sui a'i", "in its place"], ["le agasala", "sin"], ["a lo'u agaga?", "but my spirit"]]},
  {num:8,words:[["Sole,", "alofi vae"], ["ua fa'aali atu", "revealed"], ["e ia ia te oe", "by him unto you"], ["le mea lelei;", "the thing good"], ["se a foi", "a but also"], ["se mea", "a thing"], ["e finagalo ai", "to a chiefs will or desire"], ["Ieova ia te oe,", "the LORD unto you"], ["pe a le", "even though / although the"], ["o ia mea ,", "he thing"], ["ia fai", "he make"], ["le amiotonu,", "the righteous"], ["ia naunau i le alofa,", "he desire in the love"], ["ma ia feooai", "and he feooai"], ["ma lou Atua", "and your God"], ["ma le loto fa'amaulalo?", "and the heart to be humble"]]},
  {num:9,words:[["O loo alaga", "is cry"], ["le siufofoga o Ieova", "the voice the LORD"], ["i le aai,", "in the cities"], ["(o le", "the"], ["ua poto", "wise"], ["e iloa e", "to know by"], ["ia", "he"], ["lou suafa;)", "your name"], ["Ia outou fa'alogo i le", "he you all hearken in the"], ["sasa", "a scourge"], ["ma le", "and the"], ["ua pule mai ai.", "ruled from"]]},
  {num:10,words:[["O loo", "is/are"], ["i ai", "therein"], ["pea ea", "continually indeed?/really?"], ["i le fale", "in the house"], ["o le tagata amio leaga", "man iniquity/wickedness"], ["o le fa'aputugāoloa", "the faaputugāoloa"], ["e maua", "to received"], ["i le amio leaga,", "in the iniquity"], ["ma le efa fa'aaimago", "and the ephah faaaimago"], ["e inosia?", "to abominable"]]},
  {num:11,words:[["Ou te amio sao ea", "I will conduct the appointed portion of indeed?/really?"], ["a o loo", "but is"], ["i ai", "therein"], ["fua fa'atautau fa'aletatau,", "fruit make to hang up faaletatau"], ["ma le taga", "and the bag"], ["o loo", "is/are"], ["i ai", "therein"], ["maa fa'aaimago?", "stone faaaimago"]]},
  {num:12,words:[["Ua tutumu", "filled"], ["ona tagata mauoa", "and man wealthy"], ["i le fa'asaua,", "in the cruel"], ["ua tala pepelo foi", "side false also"], ["i lātou", "them"], ["o", "o"], ["e mau ai,", "to opinion"], ["o lātou laulaufaiva foi", "they tongue also"], ["i o lātou", "in of they"], ["gutu", "mouth"], ["ua fa'a'ole'ole ia.", "treacherous he"]]},
  {num:13,words:[["O lenei", "now"], ["foi,", "also"], ["ou te tā", "I will struck"], ["ia te oe", "unto you"], ["e tupu ai", "to king"], ["lou ma'i,", "your from"], ["ou te fa'atafunaina oe", "I will destroyed you"], ["ona o au", "because of me"], ["agasala.", "sin"]]},
  {num:14,words:[["E te 'ai,", "by eat"], ["a", "but"], ["e le ma'ona ai,", "shall not to subside"], ["o lou fia 'ai", "your want to do something eat"], ["e ia te oe", "by him you"], ["lea;", "lea;"], ["e te tua au", "by behind me"], ["mea ,", "thing"], ["a", "but"], ["e le fa'asaoina ai;", "shall not spared"], ["o mea foi", "thing also"], ["ua e fa'asaoina", "you spared"], ["ou te tuuina atu ai", "I will give"], ["i le pelu.", "by the sword"]]},
  {num:15,words:[["E te lulu saito,", "by barn owl wheat"], ["a", "but"], ["e te", "by"], ["le seleseleina;", "the an evenly cut head of"], ["e te soli olive,", "by to tread upon olive"], ["a", "but"], ["e te", "by"], ["le uu oe", "the oil you"], ["i le suāuu;", "in the oil"], ["atoa ma le suāvine,", "and the suāvine"], ["a", "but"], ["e te", "by"], ["le inu", "the drink"], ["i le uaina.", "in the wine"]]},
  {num:16,words:[["Auā", "for"], ["ua tausiusi sauniga", "obeyed ordinance"], ["a Omeri,", "of Omeri"], ["ma mea uma", "and all things"], ["ua faia", "made"], ["e le 'āiga", "shall not family"], ["o Aapo,", "Ahab"], ["ua outou savavali foi", "you all walked also"], ["i", "in"], ["a lātou pule,", "their rule"], ["ina ia ou fa'atafunaina ai", "so that I destroyed"], ["oe,", "you"], ["ma ia fai ma mea", "and he to be thing"], ["e uisa ai", "by uisa"], ["e o mau ai;", "by of opinion"], ["tou te tauave foi", "second person plural carry also"], ["le luma", "the before"], ["o lo'u nuu.", "my nation"]]},
];
renderVerseSet(_mic_ch_6_Verses, 'mic-ch6-verses');

var _mic_ch_7_Verses = [
  {num:1,words:[["Aue a'u nei!", "alas! oh! me this"], ["auā", "for"], ["ua avea a'u", "became me"], ["pei o le fuata", "like the fuata"], ["ua uma ona", "finished"], ["fa'aputuina,", "to gather together"], ["pei o toe fuifui vine", "like of again to dip vine"], ["i le taugāvine;", "in the taugāvine"], ["e leai se fuifui vine", "there is no to dip vine"], ["e 'ai ai;", "to eat"], ["na ou manao", "I desired"], ["i le mati", "in the fig"], ["e muai mātua.", "to first great"]]},
  {num:2,words:[["Ua fano", "perished"], ["le", "the"], ["ua agalelei", "kindness"], ["nai", "from"], ["le nuu;", "the nation"], ["e leai se tasi tagata", "there is no one man"], ["ua amiotonu;", "righteous"], ["lātou te lamalama uma", "they will watched all"], ["ina ia fasioti tagata;", "so that killed man"], ["ua lātou taitasi", "they each"], ["ma tuli", "and drive"], ["lona uso", "his brother"], ["ma le upega.", "and the net"]]},
  {num:3,words:[["Ua matuā faia", "exceedingly made"], ["mea leaga", "thing evil"], ["i o lātou", "in of they"], ["lima;", "hand"], ["ua fai atu", "said to"], ["le ali'i sili", "the Lord most"], ["atoa ma le fa'amasino", "and the judge"], ["i se taui;", "in a a reward"], ["ua tautala atu foi", "spoke toward also"], ["le matai tagata", "the chief man"], ["i lona manumanu;", "in his animal"], ["o lea", "therefore"], ["ua lātou fa'apiopio ai.", "they faapiopio"]]},
  {num:4,words:[["O so lātou", "so they"], ["e lelei", "to good"], ["e tusa ia", "to according to he"], ["ma le lā'au tuitui;", "and the tree prickly"], ["o sē amiotonu", "a righteous"], ["e sili", "to most"], ["ona matuitui o ia", "and matuitui he"], ["i le āi lā'au tuitui;", "in the thereof tree prickly"], ["o loo oo mai le aso", "is came the day"], ["o ou tagata vaai,", "I man look"], ["o lou asiasiga", "your visit"], ["lava;", "very"], ["e", "by"], ["i ai", "therein"], ["nei lava lo lātou fememeai.", "this very their whisper to one another"]]},
  {num:5,words:[["Aua ne'i outou", "for now you all"], ["fa'atuatua", "faith"], ["i le uo,", "in the uo"], ["aua ne'i fa'alagolago", "for now rely"], ["i le aumeamamae;", "in the aumeamamae"], ["ia e leoleo i", "he to guard in"], ["puipui", "gate"], ["o lou gutu", "your mouth"], ["i lau avā pele.", "in your wife dear"]]},
  {num:6,words:[["Auā o loo 'ino'ino", "for is disdained"], ["le atali'i", "the son"], ["i le tamā,", "in the father"], ["o le tama teine", "the daughters"], ["ua tu o ia", "stood he"], ["e tetee", "to to refuse"], ["i lona tinā,", "in his mother"], ["o le avā", "the wife"], ["a le tama tāne", "but the son"], ["e tetee atu", "to to refuse"], ["o ia", "he"], ["i le tinā", "in the mother"], ["o lana tāne;", "his man"], ["o", "o"], ["e ua ita", "to angry"], ["i le tagata,", "in the man"], ["o tagata ia", "of men he"], ["o lona lava 'āiga.", "his very family"]]},
  {num:7,words:[["A", "but"], ["o a'u,", "I am"], ["ou te fa'atalitali", "I will waited"], ["ia Ieova,", "he the LORD"], ["ou te fa'amoemoe", "I will hope"], ["i le Atua", "in the God"], ["o lo'u olataga;", "my salvation"], ["e fa'afofoga mai", "to listen from"], ["lo'u Atua ia te au.", "my God unto me"]]},
  {num:8,words:[["Aua", "for"], ["e te mitamita", "by to boast"], ["ia te au,", "unto me"], ["o oe", "you"], ["na,", "na,"], ["le", "the"], ["ua ita mai ia te au;", "angry from me"], ["e ui lava", "to although very"], ["ina ou paū,", "so that I fell"], ["ou te toe tu", "I will again stand"], ["lava", "very"], ["i luga;", "in above"], ["e ui lava", "to although very"], ["ina ou nofo", "so that I dwell"], ["i le pouliuli,", "in the darkness"], ["a o Ieova", "but the LORD"], ["o lo'u malamalama", "my light"], ["ia.", "he"]]},
  {num:9,words:[["Ou te fa'atoatoa", "I will make champion"], ["i le toatamai", "in the toatamai"], ["o Ieova,", "the LORD"], ["auā", "for"], ["ua ou agasala atu ia te ia;", "I sinned to him"], ["seia faia e", "until made by"], ["ia", "he"], ["la'u finauga,", "my disputation"], ["ma", "and"], ["na faia foi", "made also"], ["lo'u fa'amasinoga;", "my judgment"], ["na te fa'aooina a'u", "he brought upon me"], ["i le malamalama,", "in the light"], ["ou te iloa", "I will know"], ["lana amiotonu.", "his righteous"]]},
  {num:10,words:[["E iloa ai", "to know"], ["foi", "also"], ["e le", "by the"], ["ua ita mai ia te au,", "angry from me"], ["e liloia foi", "to to be covered also"], ["o ia", "he"], ["i le mā,", "in the and"], ["o le", "the"], ["na fai mai ia te au,", "said unto me"], ["O ifea ea Ieova", "where? indeed?/really? the LORD"], ["lou Atua? E", "your God by"], ["iloa o ia", "know he"], ["e o'u mata,", "to my eye"], ["e solia nei", "to trodden upon this"], ["o ia pei", "he like"], ["o le palapala", "the blood"], ["i le ala.", "in the way"]]},
  {num:11,words:[["O le aso", "the day"], ["e atiina ae ai", "to to pull up up"], ["ou pa,", "I wall"], ["o le aso lea", "the day"], ["e avea mamao ai", "to become far"], ["le tulafono.", "the law"]]},
  {num:12,words:[["O lea aso lātou te", "therefore day they will"], ["o mai ai", "came"], ["lava ia te oe", "very unto you"], ["nai Asuria,", "from Assyria"], ["atoa ma aai", "and cities"], ["o Aikupito,", "Egypt"], ["ma Aikupito lava", "and Egypt very"], ["e oo", "it shall come to pass"], ["i le vaitafe,", "in the river"], ["mai le tasi sami", "from the one sea"], ["e oo", "it shall come to pass"], ["i le tasi sami,", "in the one sea"], ["mai le tasi mauga", "from the one mountain"], ["e oo", "it shall come to pass"], ["i le tasi mauga.", "in the one mountain"]]},
  {num:13,words:[["A", "but"], ["e fa'atafunaina", "to destroyed"], ["le nuu", "the nation"], ["ona o", "because of"], ["e mau ai,", "to opinion"], ["ona", "and"], ["o le fua", "the fruit"], ["o", "o"], ["a lātou amio.", "their conduct"]]},
  {num:14,words:[["Ia e leoleo i", "he to guard in"], ["lou nuu", "your nation"], ["ma lou tootoo,", "and your staff"], ["o le lafu mamoe", "the flock sheep"], ["o lou tofi;", "your lot"], ["o", "o"], ["e nofo ese", "to dwell away"], ["i le vao,", "in the wilderness"], ["i Karamelu;", "in Carmel"], ["ia lātou aai i", "he they cities in"], ["Vasana", "Bashan"], ["ma Kiliata,", "and Gilead"], ["pei o", "like of"], ["ona po anamuā", "and night ancient"], ["lava.", "very"]]},
  {num:15,words:[["Fa'apei", "like"], ["o", "o"], ["ona po", "and night"], ["sa e sau ai", "you came"], ["i le nuu", "in the land"], ["o Aikupito,", "Egypt"], ["ou te fa'aali atu", "I will revealed"], ["i ai", "therein"], ["vavega.", "a wonder"]]},
  {num:16,words:[["E iloa", "to know"], ["e nuu ese,", "to nation away"], ["ona masiasi ai lea", "and to be ashamied then"], ["o", "o"], ["i lātou", "them"], ["i lo lātou malosi uma;", "than they strong all"], ["lātou te ufiufi ai", "they will covering"], ["o lātou gutu", "they mouth"], ["i o lātou", "in of they"], ["lima,", "hand"], ["e tutuli foi", "to cast out out also"], ["o lātou taliga.", "they ear"]]},
  {num:17,words:[["Lātou te etoeto", "they will etoeto"], ["i le efuefu pei", "in the dust like"], ["o le gata;", "the a snake"], ["e pei o mea fetolofi", "like creeping thing"], ["i le laueleele lātou te tetemu ai", "in the earth they will to tremble"], ["i mea", "in thing"], ["ua puipuia", "puipuia"], ["mo", "for"], ["i lātou;", "them"], ["lātou te matatau", "they will dismayed"], ["ia Ieova lo tātou", "he the LORD our"], ["Atuā;", "God"], ["lātou te fefefe foi", "they will afraid also"], ["ia te oe.", "unto you"]]},
  {num:18,words:[["O ai ea", "who"], ["se Atua e tusa ma oe", "a God according to you"], ["o le fa'amagalo agasala,", "the forgive sin"], ["ma", "and"], ["ua", "ua"], ["le manatua solitulafono", "the remember transgression"], ["a", "but"], ["e o totoe", "by of phiral of foe"], ["o lona tofi?", "his lot"], ["Na te", "he"], ["le fa'amoemoe pea", "the hope continually"], ["i lona toasa,", "in his wrath"], ["auā", "for"], ["e fiafia o ia", "to pleased he"], ["i le alofa.", "in the love"]]},
  {num:19,words:[["E toe alofa", "to again love"], ["mai o ia ia te", "from he unto"], ["i tātou,", "us"], ["e fa'atoilaloina e", "to spare by"], ["ia", "he"], ["a tātou amioletonu;", "our wickedness"], ["e te lafo foi", "by cloth used as gratuity for a talking chief also"], ["a lātou agasala uma", "their sin all"], ["i mea loloto", "in thing deep"], ["o le sami.", "Sea"]]},
  {num:20,words:[["E te fa'aoo", "by bring upon"], ["le fa'amaoni ia", "the faithful he"], ["Iakopo,", "Jacob"], ["o le alofa", "the love"], ["ia Aperaamo,", "he Abraham"], ["sa e tauto ai", "you to take an oath"], ["i o mātou", "in of we"], ["tamā talu mai", "father since from"], ["ona po anamua.", "and night ancient"]]},
];
renderVerseSet(_mic_ch_7_Verses, 'mic-ch7-verses');

})();