(function() {
var _mr_ch_1_Verses = [
  {num:1,words:[["O Lenei o au", "this I am"], ["o Moronae ,", "Moroni"], ["ina ua uma ona", "let finished"], ["ou faia", "I made"], ["o le faaiuga", "the faaiuga"], ["o le otootoga", "the abridgment"], ["o le tala", "the side"], ["o le nuu o Iareto,", "the nation of Jared"], ["sa ou manatu", "I thought"], ["o le a ou", "what I"], ["le toe tusia ni isi mea faaopoopo,", "the again written some other thing add"], ["peitai ou te lei oti", "however I not die"], ["lava;", "indeed"], ["ma ou te", "and I"], ["le faailoa atu au", "the declared I"], ["lava i", "indeed in"], ["sa Lamanā nei o latou", "thus Laman this of they"], ["faaumatia au.", "destroyed I"]]},
  {num:2,words:[["Aua faauta,", "for behold"], ["ua matua malolosi tele", "very mighty great"], ["a latou taua", "but they precious"], ["i totonu o", "in the midst of"], ["i latou lava;", "them indeed"], ["ma ona", "and then"], ["o lo latou ita", "their angry"], ["ua latou fasiotia ai", "they slain"], ["sa Nifaē uma o", "thus Nephi all of"], ["e e le faafitia", "by by the opposed"], ["le Keriso.", "the Christ"]]},
  {num:3,words:[["Ma o au,", "and I am"], ["o Moronae,", "Moroni"], ["ou te", "I"], ["le faafitia", "the opposed"], ["le Keriso;", "the Christ"], ["o le mea lea,", "therefore"], ["ou te fealuai solo ai", "I fealuai to move swiftly"], ["i soo", "in frequently"], ["se mea", "a thing"], ["e mafai ona", "could"], ["ou alu", "I go"], ["i ai", "therein"], ["mo le puipuiga", "for the puipuiga"], ["o lou lava ola.", "your indeed life"]]},
  {num:4,words:[["O le mea lea,", "therefore"], ["ou te tusia ai ni isi mea faaopoopo itiiti,", "I written some other thing add small"], ["e le tusa ma le mea", "by the according to and the thing"], ["na ou manatu", "I thought"], ["i ai;", "therein"], ["ona sa ou manatu", "and I thought"], ["o le a ou", "what I"], ["le toe tusia ni isi mea faaopoopo;", "the again written some other thing add"], ["ae o le a ou tusia ni", "but will I written some"], ["nai faaopoopo itiiti,", "from add small"], ["atonu o le a aoga", "impers will useful"], ["i ou uso,", "in I brother"], ["o sa Lamanā,", "thus Laman"], ["i se aso", "in a day"], ["i le lumanai,", "in the lumanai"], ["e tusa ai", "to according to"], ["ma le finagalo", "and the a chiefs will or desire"], ["o le Alii.", "the Lord"]]},
];
renderVerseSet(_mr_ch_1_Verses, 'mr-ch1-verses');

var _mr_ch_2_Verses = [
  {num:1,words:[["O afioga", "a word"], ["a Keriso,", "of Christ"], ["na ia fetalai", "to said"], ["i ona soo ,", "in then frequently"], ["le toasefululua o", "the twelve of"], ["e na ia filifilia,", "by to chosen"], ["ao faaee", "day to place upon"], ["ona aao", "and hand (extended)"], ["i o latou luga—", "in of they luga—"]]},
  {num:2,words:[["Ma sa ia valaau", "and to call"], ["i latou", "them"], ["i o latou igoa,", "in of they name"], ["ua fetalai:", "said"], ["Ia outou valaau atu", "to you (all) call"], ["i le Tamā", "in the father"], ["i lou igoa,", "in your name"], ["i le tatalo faatauanau;", "in the pray faatauanau"], ["ma a uma ona", "and but all then"], ["outou faia o lenei mea,", "you (all) made of this thing"], ["o le a outou", "what you (all)"], ["maua le mana tou te tuu atu ai", "received the to get second person plural placed"], ["le Agaga Paia ia te ia", "the Holy Spirit to him"], ["o le", "the"], ["o le a faaee atu", "what to place upon"], ["i ai o outou", "therein of you (all)"], ["lima i", "five in"], ["ona luga;", "and above"], ["ma o lou igoa ia", "and your name to"], ["outou tuuina atu ai,", "you (all) given"], ["ona sa faapea ona", "and saying then"], ["faia e au aposetolo.", "made to I apostle"]]},
  {num:3,words:[["O lenei", "this"], ["sa fetalai mai", "said"], ["e Keriso ia te", "to Christ unto"], ["i latou ia afioga", "them to a word"], ["i le taimi", "in the time"], ["o lona faatoa afio", "his just now dwell (respectful)"], ["mai;", "from"], ["ma sa", "and"], ["le faalogoina", "the faalogoina"], ["e le motu o tagata,", "by the island of men"], ["ae sa faalogoina", "but faalogoina"], ["e le au soo;", "by the I frequently"], ["ma o le toatele o", "and the many of"], ["i latou", "them"], ["o e", "who"], ["na faaee atu", "to place upon"], ["i ai o latou", "therein of they"], ["lima,", "five"], ["na taia", "struck"], ["i le Agaga Paia.", "in the Holy Spirit"]]},
];
renderVerseSet(_mr_ch_2_Verses, 'mr-ch2-verses');

var _mr_ch_3_Verses = [
  {num:1,words:[["O le ala", "the way"], ["na faauu ai faitaulaga", "anoint priest"], ["ma aoao", "and excellent"], ["e le au soo,", "by the I frequently"], ["o e", "who"], ["na taua o toeaina", "precious of elder"], ["o le ekalesia—", "the ekalesia—"]]},
  {num:2,words:[["Ina ua uma ona", "let finished"], ["latou tatalo atu", "they pray"], ["i le Tamā", "in the father"], ["i le suafa o Keriso,", "in the name of Christ"], ["sa latou faaee o latou", "they to place upon of they"], ["lima i o latou", "five in of they"], ["luga,", "above"], ["ma fai atu:", "and said to"]]},
  {num:3,words:[["I le suafa o Iesu Keriso ou te faauuina ai oe", "in the name of Jesus Christ I anointed you"], ["e avea", "to become"], ["o se faitaulaga,", "a priest"], ["(ae afai", "but if"], ["o se aoao,", "a excellent"], ["ou te faauuina ai oe", "I anointed you"], ["e avea", "to become"], ["o se aoao)", "a excellent"], ["e talai atu", "to preach"], ["le salamo", "the repent"], ["ma le faamagaloina o agasala", "and the forgiven of sin"], ["e ala ia Iesu Keriso,", "to way to Jesus Christ"], ["i le tumau", "in the enduring"], ["i le faatuatua", "in the faith"], ["i lona suafa", "in his name"], ["e oo", "it shall come to pass"], ["i le iuga.", "in the end"], ["Amene.", "amen"]]},
  {num:4,words:[["Ma o le ala lenei", "and the way this"], ["sa latou faauu ai faitaulaga", "they anoint priest"], ["ma aoao,", "and excellent"], ["e tusa ma meaalofa", "according to gift"], ["ma valaauga", "and valaauga"], ["a le Atua", "of God"], ["i tagata;", "in man"], ["ma sa latou faauuina", "and they anointed"], ["i latou", "them"], ["i le mana", "in the to get"], ["o le Agaga Paia,", "the Holy Spirit"], ["lea sa ia te", "unto"], ["i latou.", "them"]]},
];
renderVerseSet(_mr_ch_3_Verses, 'mr-ch3-verses');

var _mr_ch_4_Verses = [
  {num:1,words:[["O le ala", "the way"], ["e faamanuia", "to blessed"], ["ma tufa atu ai", "and to divide"], ["e o latou toeaina", "by of they elder"], ["ma faitaulaga", "and priest"], ["le tino", "the body"], ["ma le toto o Keriso", "and the blood of Christ"], ["i le ekalesia;", "in the church"], ["ma sa latou faia", "and they made"], ["e tusa ma poloaiga", "according to commandment"], ["a Keriso;", "of Christ"], ["o le mea lea", "therefore"], ["ua matou iloa ai", "we (excl) known"], ["ua sao", "the appointed portion of"], ["le ala;", "the way"], ["ma o le toeaina po", "and the elder night"], ["o le faitaulaga", "the priest"], ["na faia—", "faia—"]]},
  {num:2,words:[["Ma sa latou tootutuli", "and they tootutuli"], ["i lalo faatasi", "in under once"], ["ma le ekalesia,", "and the church"], ["ma tatalo atu", "and pray"], ["i le Tamā", "in the father"], ["i le suafa o Keriso,", "in the name of Christ"], ["ua fai atu:", "said to"]]},
  {num:3,words:[["Le Atua e,", "God by"], ["le Tamā Faavavau,", "the father everlasting"], ["matou te ole atu ia te oe", "we (excl) entreat unto you"], ["i le suafa", "in the name"], ["o lou Alo,", "your Son"], ["o Iesu Keriso,", "Jesus Christ"], ["ia e faamanuiaina", "to to blessed"], ["ma faapaiaina lenei areto", "and consecrated this bread"], ["i agaga o", "in spirit of"], ["i latou uma o", "them all of"], ["e e fetagofi", "by to seized"], ["i ai;", "therein"], ["ina ia latou taumamafa", "so that they taumamafa"], ["i le faamanatuina", "in the faamanatuina"], ["o le tino", "the body"], ["o lou Alo,", "your Son"], ["ma molimau atu ia te oe,", "and a witness unto you"], ["le Atua e,", "God by"], ["le Tamā Faavavau,", "the father everlasting"], ["latou te loto", "they heart"], ["ina e ave", "let to take"], ["i o latou luga", "in of they above"], ["le suafa", "the name"], ["o lou Alo,", "your Son"], ["ma manatua pea o ia,", "and remember continually he"], ["ma tausi", "and keep"], ["i ana poloaiga", "in his commandment"], ["ua ia tuuina", "to given"], ["mai ia te", "from"], ["i latou,", "them"], ["ina ia latou maua pea lona Agaga", "so that they received continually his spirit"], ["e faatasi", "to once"], ["ma i latou.", "and them"], ["Amene.", "amen"]]},
];
renderVerseSet(_mr_ch_4_Verses, 'mr-ch4-verses');

var _mr_ch_5_Verses = [
  {num:1,words:[["O le ala", "the way"], ["e faamanuia ai", "to blessed"], ["le uaina—Faauta,", "the uaina—faauta"], ["sa latou ave", "they take"], ["le ipu,", "the cup"], ["ma fai atu:", "and said to"]]},
  {num:2,words:[["Le Atua e,", "God by"], ["le Tamā Faavavau,", "the father everlasting"], ["matou te ole atu ia te oe", "we (excl) entreat unto you"], ["i le suafa", "in the name"], ["o lou Alo,", "your Son"], ["o Iesu Keriso,", "Jesus Christ"], ["ia e faamanuiaina", "to to blessed"], ["ma faapaiaina lenei uaina", "and consecrated this wine"], ["i agaga o", "in spirit of"], ["i latou uma o", "them all of"], ["e e feinu ai,", "by by feinu"], ["ina ia latou faia", "so that they made"], ["i le faamanatuina", "in the faamanatuina"], ["o le toto", "the blood"], ["o lou Alo,", "your Son"], ["sa faamaligiina", "faamaligiina"], ["mo i latou;", "for them"], ["ina ia latou molimau atu", "so that they a witness"], ["ia te oe,", "unto you"], ["le Atua e,", "God by"], ["le Tamā Faavavau,", "the father everlasting"], ["latou te manatua pea o ia,", "they remember continually he"], ["ina ia latou maua lona Agaga", "so that they received his spirit"], ["e faatasi", "to once"], ["ma i latou.", "and them"], ["Amene.", "amen"]]},
];
renderVerseSet(_mr_ch_5_Verses, 'mr-ch5-verses');

var _mr_ch_6_Verses = [
  {num:1,words:[["Ma o lenei ou te tautala atu", "and now I to talk"], ["e uiga", "concerning"], ["i le papatisoga .", "in the baptism"], ["Faauta,", "behold"], ["sa papatisoina toeaina,", "baptized elder"], ["faitaulaga,", "priest"], ["ma aoao;", "and excellent"], ["ma sa", "and"], ["le papatisoina", "the baptized"], ["i latou vagana ai", "them except"], ["ua latou fua", "they fruit"], ["mai fua", "from fruit"], ["e tatau ai", "it is fitting"], ["e iloa ai", "to known"], ["ua latou agavaa .", "they agavaa"]]},
  {num:2,words:[["Pe na latou talia foi soo", "whether they received also frequently"], ["se tasi", "a one"], ["i le papatisoga vagana ai", "in the baptism except"], ["ua latou", "they"], ["o mai", "from"], ["i luma", "in before"], ["ma le loto momomo", "and the heart to brrak in pieces"], ["ma le agaga salamo,", "and the spirit repent"], ["ma molimau mai", "and a witness from"], ["i le ekalesia", "in the church"], ["ua latou salamo faamaoni ia", "they repent faithful to"], ["latou agasala uma.", "they sin all"]]},
  {num:3,words:[["Ma sa leai", "and no"], ["se tasi", "a one"], ["na talia", "received"], ["i le papatisoga vagana ai", "in the baptism except"], ["ua latou ave", "they take"], ["i o latou luga", "in of they above"], ["le suafa o Keriso,", "the name of Christ"], ["ma ua", "and"], ["i ai", "therein"], ["le mauai", "the mauai"], ["e auauna atu ia te ia", "to servant to him"], ["e oo", "it shall come to pass"], ["i le iuga.", "in the end"]]},
  {num:4,words:[["Ma ina", "and let"], ["ua uma ona", "finished"], ["taliaina o", "taliaina of"], ["i latou", "them"], ["i le papatisoga,", "in the baptism"], ["ma galueaiina", "and galueaiina"], ["ma faamamaina", "and cleansed"], ["e le mana", "by the to get"], ["o le Agaga Paia,", "the Holy Spirit"], ["sa faitauina", "counted"], ["i latou", "them"], ["i totonu o tagata", "in the midst of man"], ["o le ekalesia", "the church"], ["a Keriso;", "of Christ"], ["ma sa ave o latou", "and take of they"], ["igoa ina ia manatua", "name so that remember"], ["i latou", "them"], ["ma tausia", "and kept"], ["i le afioga lelei", "the word good"], ["a le Atua,", "of God"], ["e faatutumau ai", "by faatutumau"], ["i latou", "them"], ["i le ala sao,", "in the way the appointed portion of"], ["e faatutumau ai", "by faatutumau"], ["i latou ia mataala", "them to mataala"], ["e le aunoa", "by the without"], ["i le tatalo,", "in the pray"], ["ua nao galuega", "only work"], ["a Keriso,", "of Christ"], ["o le", "the"], ["o le pogai", "the the root and stump of a"], ["ma le iuga", "and the end"], ["o lo latou faatuatua,", "their faith"], ["ua faalagolago", "to lean upon"], ["i ai.", "therein"]]},
  {num:5,words:[["Ma sa potopoto soo faatasi", "and gather frequently once"], ["le ekalesia ,", "the church"], ["e anapopogi", "by anapopogi"], ["ma tatalo,", "and pray"], ["ma talatalanoa,", "and to relate"], ["o le tasi", "the one"], ["i le tasi,", "in the one"], ["e uiga", "concerning"], ["i le uelefea o o latou", "in the uelefea of of they"], ["agaga.", "spirit"]]},
  {num:6,words:[["Ma sa latou potopoto soo faatasi", "and they gather frequently once"], ["e taumamafa", "by taumamafa"], ["i le areto", "in the bread"], ["ma le uaina,", "and the wine"], ["i le faamanatuina", "in the faamanatuina"], ["o le Alii o Iesu.", "the Lord of Jesus"]]},
  {num:7,words:[["Ma sa latou tausisi", "and they tausisi"], ["ma le faaeteete", "and the faaeteete"], ["ina ia leai", "so that no"], ["se amioletonu e", "a wickedness by"], ["i totonu o", "in the midst of"], ["i latou;", "them"], ["ma o soo", "and of frequently"], ["se tasi", "a one"], ["e maua", "to received"], ["ua ia faia", "he made/did"], ["le amioletonu,", "the wickedness"], ["ma e toatolu molimau", "and to three (people) a witness"], ["o le ekalesia", "the church"], ["e tausalaina ai", "by tausalaina"], ["i latou", "them"], ["i luma o toeaina ,", "before elder"], ["ma afai latou te", "and if they"], ["le salamo,", "the repent"], ["ma le faatoese,", "and the faatoese"], ["sa tineia ese o latou", "tineia away of they"], ["igoa,", "name"], ["ma sa", "and"], ["le faitauina", "the counted"], ["i latou", "them"], ["i totonu o tagata o Keriso.", "in the midst of man of Christ"]]},
  {num:8,words:[["Ae o soo", "but of frequently"], ["se taimi", "a time"], ["sa latou salamo ai", "they repent"], ["ma saili", "and seek"], ["le faamagaloga,", "the faamagaloga"], ["ma le faamoemoe faamaoni,", "and the to expect faithful"], ["sa faamagaloina", "forgiven"], ["i latou.", "them"]]},
  {num:9,words:[["Ma sa taitaia", "and taitaia"], ["a latou sauniga", "but they preparation"], ["e le ekalesia", "by the church"], ["e tusa ma galuega", "according to work"], ["a le Agaga,", "but the spirit"], ["ma le mana", "and the to get"], ["o le Agaga Paia;", "the Holy Spirit"], ["ona o soo", "because of frequently"], ["se mea", "a thing"], ["na taitaia ai", "taitaia"], ["i latou", "them"], ["e Agaga Paia", "to Holy Spirit"], ["e talai,", "to preach"], ["pe apoapoai,", "whether apoapoai"], ["pe tatalo,", "whether pray"], ["pe aioi,", "whether cry out"], ["pe pepese atu ai,", "whether sing"], ["sa faapea lava ona", "saying indeed then"], ["faia.", "made"]]},
];
renderVerseSet(_mr_ch_6_Verses, 'mr-ch6-verses');

var _mr_ch_7_Verses = [
  {num:1,words:[["Ma o lenei,", "and now"], ["o au,", "I am"], ["o Moronae,", "Moroni"], ["ou te tusia", "I written"], ["nai upu itiiti", "from word small"], ["a lou tamā,", "but your father"], ["o Mamona,", "Mormon"], ["ia na ia tautala", "to to to talk"], ["i ai", "therein"], ["e uiga", "concerning"], ["i le faatuatua ,", "in the faith"], ["faamoemoe,", "to expect"], ["ma le alofa mama;", "and the love n"], ["ona sa faapenei", "and faapenei"], ["le ala", "the way"], ["sa ia tautala atu ai", "to to talk"], ["i le nuu,", "in the land"], ["ao ia aoao atu ia te", "day to excellent unto"], ["i latou", "them"], ["i le sunako lea", "in the synagogue"], ["na latou fausia", "they built"], ["mo se nofoaga", "for a place"], ["e tapuai ai.", "to worship"]]},
  {num:2,words:[["Ma o lenei,", "and now"], ["o au,", "I am"], ["o Mamona,", "Mormon"], ["ou te tautala atu ia te outou,", "I to talk unto you"], ["ou uso pele", "I brother dear"], ["e;", "by"], ["ma ona", "and then"], ["o le alofa tunoa", "the grace"], ["o le Atua,", "of God"], ["le Tamā,", "the father"], ["ma lo tatou Alii o Iesu Keriso,", "and the we (incl) Lord of Jesus Christ"], ["ma lona finagalo paia,", "and his a chiefs will or desire holy"], ["ona o le meaalofa", "because of the gift"], ["o lana valaauga ia te au,", "his valaauga unto me"], ["lea ua faatagaina ai au", "faatagaina I"], ["ou te tautala atu ia te outou", "I to talk unto you"], ["i lenei taimi.", "in this time"]]},
  {num:3,words:[["O le mea lea,", "therefore"], ["ou te fia tautala atu", "I want to do something to talk"], ["ia te outou", "unto you"], ["o e", "who"], ["o le ekalesia,", "the church"], ["outou o soo fifilemu o Keriso,", "you (all) of frequently fifilemu of Christ"], ["ma outou", "with you"], ["ua outou maua", "you (all) received"], ["se faamoemoe", "a to expect"], ["ua lava", "indeed"], ["e mafai ai", "it is possible"], ["ona outou ulu atu", "and you (all) head"], ["i le malologa", "in the a resting place"], ["o le Alii,", "the Lord"], ["mai le taimi nei", "from the time this"], ["i luma seia oo", "in before until oo"], ["ina outou malolo faatasi", "let you (all) rest once"], ["ma ia", "and to"], ["i le lagi.", "in heaven"]]},
  {num:4,words:[["Ma o lenei ou uso", "and now I brother"], ["e,", "by"], ["ua ou matauina nei mea", "I matauina this thing"], ["ia te outou", "unto you"], ["ona o lo outou savavali", "because of your walked"], ["ma le filemu faatasi", "and the peace once"], ["ma le fanauga", "and the children"], ["a tagata.", "but man"]]},
  {num:5,words:[["Aua ou te manatua", "for I remember"], ["le afioga", "the a word"], ["a le Atua", "of God"], ["ua fetalai mai o", "said of"], ["a latou galuega tou te iloa ai", "but they work second person plural known"], ["i latou;", "them"], ["aua afai", "for if"], ["ua lelei", "that it was good"], ["a latou galuega,", "but they work"], ["ua lelei foi", "that it was good also"], ["i latou.", "them"]]},
  {num:6,words:[["Aua faauta,", "for behold"], ["na fetalai mai", "said"], ["le Atua", "God"], ["o se tagata", "a man"], ["ua leaga", "evil"], ["e le mafai ona", "by the able then"], ["fai e ia se mea", "make by him a thing"], ["ua lelei;", "that it was good"], ["aua afai", "for if"], ["na te ofo atu", "he n"], ["se meaalofa,", "a gift"], ["pe tatalo atu", "whether pray"], ["i le Atua,", "in the God"], ["vagana ai", "except"], ["e faia e ia", "to made by him"], ["ma le loto faamaoni", "and the heart faithful"], ["i ai", "therein"], ["e leai", "there is not"], ["se aoga ia te ia.", "a useful to him"]]},
  {num:7,words:[["Aua faauta,", "for behold"], ["e le faitauina ia te ia", "by the counted to him"], ["lena mea", "that thing"], ["mo le amiotonu.", "for the righteous"]]},
  {num:8,words:[["Aua faauta,", "for behold"], ["afai e avatu", "if to give away"], ["e se tagata", "by a man"], ["ua leaga", "evil"], ["se meaalofa,", "a gift"], ["e faia e ia", "to made by him"], ["ma le toai ;", "and the toai"], ["o le mea lea", "therefore"], ["e faitau tutusa ai ia te ia", "to to count equal to him"], ["e pei lava", "to like indeed"], ["na ia taofia", "to held back"], ["le meaalofa;", "the gift"], ["o le mea lea", "therefore"], ["e faitau leaga ai o ia", "to to count evil he"], ["i luma", "in before"], ["o le Atua.", "of God"]]},
  {num:9,words:[["Ma e faapea foi", "and saying also"], ["ona faitau leaga", "and to count evil"], ["i se tagata,", "in a man"], ["pe afai", "whether if"], ["e tatalo atu o ia", "to pray he"], ["ae ua", "but"], ["le i ai", "the therein"], ["ma le faamaoni", "and the faithful"], ["o le loto;", "the heart"], ["ioe,", "yea"], ["ma ua leai", "and there was not"], ["se aoga ia te ia,", "a useful to him"], ["ona e le talia", "and by the received"], ["e le Atua", "God"], ["se ua faapena.", "a likewise"]]},
  {num:10,words:[["O le mea lea,", "therefore"], ["e le mafai", "by the able"], ["e se tagata", "by a man"], ["ua leaga", "evil"], ["ona faia", "and made"], ["le mea", "the thing"], ["ua lelei;", "that it was good"], ["pe avatu foi e ia", "whether give away also by him"], ["se meaalofa lelei.", "a gift good"]]},
  {num:11,words:[["Aua faauta,", "for behold"], ["e le mafai", "by the able"], ["e se puna oona", "by a spring of water drunk"], ["ona puna mai", "and spring of water from"], ["i vai lelei;", "in water good"], ["pe mafai foi", "whether able also"], ["e se puna lelei", "by a spring of water good"], ["ona puna mai", "and spring of water from"], ["i vai oona;", "in water drunk"], ["o le mea lea,", "therefore"], ["o se tagata", "a man"], ["ua avea", "become"], ["o se auauna", "a servant"], ["a le tiapolo", "but the devil"], ["e le mafai ona", "by the able then"], ["mulimuli ia Keriso;", "follow after to Christ"], ["ma afai", "and if"], ["e mulimuli o ia", "to follow after he"], ["ia Keriso", "to Christ"], ["e le mafai ona", "by the able then"], ["avea o ia", "become he"], ["o se auauna", "a servant"], ["a le tiapolo.", "but the devil"]]},
  {num:12,words:[["O le mea lea,", "therefore"], ["o mea uma", "everything"], ["ua lelei", "that it was good"], ["e mai", "by from"], ["le Atua;", "God"], ["ma o le mea", "and the thing"], ["ua leaga", "evil"], ["e mai", "by from"], ["le tiapolo;", "the devil"], ["ona o le tiapolo", "because of the devil"], ["o se fili", "a to choose"], ["i le Atua,", "in the God"], ["ma ua faasagatau pea ia te ia,", "and faasagatau continually to him"], ["ma ua valaau", "and call"], ["ma faatosina tagata", "and faatosina man"], ["i le agasala ,", "in the sin"], ["ma ia latou faia pea", "and to they made continually"], ["le mea leaga.", "the thing evil"]]},
  {num:13,words:[["Ae faauta,", "but behold"], ["o le mea", "the thing"], ["ua mai", "from"], ["le Atua,", "God"], ["e valaau", "to call"], ["ma faatosina mai ia", "and faatosina from to"], ["faia mea lelei", "made thing good"], ["e le aunoa;", "by the without"], ["o le mea lea,", "therefore"], ["o mea uma", "everything"], ["e valaau mai", "to call from"], ["ma faatosina mai ia", "and faatosina from to"], ["faia mea lelei,", "made thing good"], ["ma alofa", "and love"], ["i le Atua,", "in the God"], ["ma auauna atu ia te ia,", "and servant to him"], ["ua musuia", "to be doomed to be killed"], ["e le Atua.", "God"]]},
  {num:14,words:[["O le mea lea,", "therefore"], ["ia outou faaeteete,", "to you (all) faaeteete"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["ina ia outou", "so that you (all)"], ["le faamasino", "the a judge"], ["le mea", "the thing"], ["ua leaga", "evil"], ["o se mea", "a thing"], ["mai le Atua,", "from God"], ["po o le mea", "night the thing"], ["ua lelei", "that it was good"], ["ma mai", "and from"], ["le Atua", "God"], ["o se mea", "a thing"], ["mai le tiapolo.", "from the devil"]]},
  {num:15,words:[["Aua faauta,", "for behold"], ["ou uso e,", "I brother by"], ["ua tuu mai ia te outou", "placed unto you"], ["ia outou faamasino ,", "to you (all) a judge"], ["ina ia outou iloa", "so that you (all) known"], ["le lelei mai", "the good from"], ["le leaga;", "the evil"], ["ma o le ala", "and the way"], ["e faamasino ai", "to a judge"], ["ua manino,", "plain"], ["ina ia mafai ona", "that it might be and"], ["outou iloa", "you (all) known"], ["ma se malamalama atoatoa,", "and a light completely"], ["e pei o le malamalama", "like the light"], ["o le ao", "Day"], ["mai le pouliuli", "from the darkness"], ["o le po.", "Night"]]},
  {num:16,words:[["Aua faauta,", "for behold"], ["ua tuuina mai", "given from"], ["i tagata taitoatasi", "in man each one"], ["le Agaga o Keriso,", "the spirit of Christ"], ["ina ia mafai ona", "that it might be and"], ["iloa e ia le lelei", "known by him the good"], ["mai le leaga;", "from the evil"], ["o le mea lea,", "therefore"], ["ou te faaali atu ai", "I revealed"], ["ia te outou", "unto you"], ["le ala", "the way"], ["e faamasino ai;", "to a judge"], ["ona o mea uma", "because of the things all"], ["e valaau mai ia", "to call from to"], ["fai le lelei,", "make the good"], ["ma faatauanau mai ia", "and faatauanau from to"], ["talitonu ia Keriso,", "believe to Christ"], ["ua auina mai", "sent from"], ["i le mana", "in the to get"], ["ma le meaalofa", "and the gift"], ["a Keriso;", "of Christ"], ["o le mea lea", "therefore"], ["e mafai ai", "it is possible"], ["ona outou iloa", "and you (all) known"], ["ma le malamalama atoatoa", "and the light completely"], ["ua mai", "from"], ["le Atua.", "God"]]},
  {num:17,words:[["Ae o soo", "but of frequently"], ["se mea", "a thing"], ["e faatauanauina tagata ia", "by faatauanauina man to"], ["latou faia", "they made"], ["le leaga ,", "the evil"], ["ma ia le talitonu ia", "and to the believe to"], ["Keriso,", "Christ"], ["ma faafiti o ia,", "and denied he"], ["ma ia le auauna", "and to the servant"], ["i le Atua,", "in the God"], ["ona outou iloa lea", "and you (all) known"], ["ma le malamalama atoatoa", "and the light completely"], ["ua mai", "from"], ["le tiapolo;", "the devil"], ["ona o le ala lea", "because of the way"], ["e galue ai", "to till"], ["le tiapolo,", "the devil"], ["aua e le faatauanauina", "for by the faatauanauina"], ["e ia se tagata ia", "by him a man to"], ["faia le lelei,", "made the good"], ["e leai,", "there is not"], ["e leai lava", "there is not indeed"], ["se tasi;", "a one"], ["pe faia foi", "whether made also"], ["e ana agelu;", "by his angel"], ["pe faia foi e", "whether made also by"], ["i latou", "them"], ["o e latou te tuu atu", "who they placed"], ["i latou lava ia te ia.", "them indeed to him"]]},
  {num:18,words:[["Ma o lenei,", "and now"], ["ou uso e,", "I brother by"], ["ina ua vaai", "let to look at"], ["ua outou iloa", "you (all) known"], ["le malamalama tou te faamasino ai,", "the light second person plural a judge"], ["o le malamalama lea o Keriso,", "the light of Christ"], ["vaai ia outou", "to look at to you (all)"], ["le faamasino sese;", "the a judge wrong"], ["aua o le faamasinoga lava lea tou te faamasino atu ai", "for the judgment indeed second person plural a judge"], ["o le a faamasino ai", "what a judge"], ["foi outou.", "also you (all)"]]},
  {num:19,words:[["O le mea lea,", "therefore"], ["ou te aioi atu ia te outou,", "I cry out unto you"], ["uso e,", "brother by"], ["ia outou sailiili", "to you (all) search"], ["ma le filiga", "and the perseverance"], ["i le malamalama o Keriso", "in the light of Christ"], ["ina ia outou iloa", "so that you (all) known"], ["le lelei mai", "the good from"], ["le leaga;", "the evil"], ["ma afai tou te taofi mau", "and if second person plural hold opinion"], ["i mea lelei uma,", "in thing good all"], ["ma lē tauleagaina ia", "and not tauleagaina to"], ["mea,", "thing"], ["o le a avea moni outou", "what become true you (all)"], ["ma ni fanau", "and some born"], ["a Keriso.", "of Christ"]]},
  {num:20,words:[["Ma o lenei,", "and now"], ["ou uso e,", "I brother by"], ["e mafai faapefea", "it is possible how ?"], ["ona outou taofi mau", "and you (all) hold opinion"], ["i mea lelei uma?", "in thing good all"]]},
  {num:21,words:[["Ma o lenei", "and now"], ["ua ou oo", "I oo"], ["mai nei", "from this"], ["i lena faatuatua,", "in that faith"], ["lea na ou fai atu", "I said to"], ["o le a ou tautala atu ai;", "what I to talk"], ["ma o le a ou tau atu", "and will I season"], ["ia te outou", "unto you"], ["le auala", "the auala"], ["e mafai ai", "it is possible"], ["ona outou taofi mau", "and you (all) hold opinion"], ["i mea lelei uma.", "in thing good all"]]},
  {num:22,words:[["Aua faauta,", "for behold"], ["ona ua silafia", "and known"], ["e le Atua mea uma,", "God all things"], ["ona ua mai", "and from"], ["le faavavau-tumau", "the faavavau-tumau"], ["i le faavavau-tumau,", "in the faavavau-tumau"], ["faauta,", "behold"], ["sa ia auina", "to sent"], ["mai agelu", "from angel"], ["e auauna mai", "to servant from"], ["i le fanauga", "in the children"], ["a tagata,", "but man"], ["e faaali mai", "to revealed"], ["e uiga", "concerning"], ["i le afio", "in the dwell (respectful)"], ["mai o Keriso;", "from of Christ"], ["ma o Keriso", "and of Christ"], ["o le a ala", "what way"], ["mai ai mea lelei uma.", "from thing good all"]]},
  {num:23,words:[["Ma sa tautino", "and to hang near the body"], ["mai foi", "from also"], ["e le Atua", "God"], ["i perofeta,", "in prophet"], ["i lona lava fofoga,", "in his indeed face"], ["o le a afio", "what dwell (respectful)"], ["mai Keriso.", "from Christ"]]},
  {num:24,words:[["Faauta foi,", "and behold"], ["e tele auala", "to great auala"], ["sa i ai", "therein"], ["na ia faaali", "to revealed"], ["mai ai mea", "from thing"], ["i le fanauga", "in the children"], ["a tagata,", "but man"], ["o ni mea", "some thing"], ["sa lelei;", "good"], ["ma o mea uma", "and everything"], ["ua lelei", "that it was good"], ["ua mai ia Keriso;", "from to Christ"], ["a na", "but"], ["le o lea po", "the therefore night"], ["ua pauu tagata,", "fell man"], ["ma ua leai", "and there was not"], ["se mea lelei", "a thing good"], ["e mafai ona", "could"], ["oo mai ia te", "came unto"], ["i latou.", "them"]]},
  {num:25,words:[["O le mea lea,", "therefore"], ["e ala", "to way"], ["i le auauna", "in the servant"], ["mai o agelu ,", "from of angel"], ["ma afioga uma", "and a word all"], ["na tulei mai", "to push from"], ["i le fofoga", "in the face"], ["o le Atua,", "of God"], ["sa amata", "began"], ["ona faaaoga ai", "and used"], ["e tagata", "to man"], ["le faatuatua ia Keriso;", "the faith to Christ"], ["ma sa faapea,", "and saying"], ["e ala", "to way"], ["i le faatuatua,", "in the faith"], ["ona latou taofi mau", "and they hold opinion"], ["i mea lelei uma;", "in thing good all"], ["ma sa faapea ona", "and saying then"], ["i ai seia oo", "therein until oo"], ["mai i le afio", "from in the dwell (respectful)"], ["mai o Keriso.", "from of Christ"]]},
  {num:26,words:[["Ma ina", "and let"], ["ua uma ona", "finished"], ["afio mai o ia,", "dwell (respectful) from he"], ["sa faaolaina foi tagata", "saved alive also man"], ["i le faatuatua", "in the faith"], ["i lona suafa;", "in his name"], ["ma e ala", "and to way"], ["i le faatuatua,", "in the faith"], ["na avea ai", "become"], ["i latou", "them"], ["ma atalii", "and son"], ["o le Atua.", "of God"], ["Ma e pei ona", "and as"], ["mautinoa o loo soifua Keriso,", "surely of live Christ"], ["sa ia fetalai", "to said"], ["mai upu nei", "from word this"], ["i o tatou tamā,", "in of we (incl) father"], ["ua fetalai mai:", "said"], ["Soo se mea,", "frequently a thing"], ["ua lelei,", "that it was good"], ["tou te ole atu ai", "second person plural entreat"], ["i le Tama", "in the child"], ["i lou igoa", "in your name"], ["i le faatuatua,", "in the faith"], ["i le talitonu", "in the believe"], ["o le a outou", "what you (all)"], ["maua,", "received"], ["faauta,", "behold"], ["o le a faia lava", "what made indeed"], ["ia te outou.", "unto you"]]},
  {num:27,words:[["O le mea lea,", "therefore"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["pe ua taofia ea vavega", "whether held back to rise (as a diver to the sur- a wonder"], ["ona ua toe afio atu Keriso", "and again dwell (respectful) Christ"], ["i le lagi,", "in heaven"], ["ma ua afio", "and dwell (respectful)"], ["i le itu aao taumatau", "on the side hand (extended) right hand"], ["o le Atua,", "of God"], ["e maua mai", "to received from"], ["i le Tamā ana aia", "in the father his to be galled or chafed"], ["o le alofa mutimutivale lea", "the mercy"], ["ua ia te ia", "to him"], ["mo le fanauga", "for the children"], ["a tagata?", "but man"]]},
  {num:28,words:[["Ona ua uma ona", "and finished"], ["tali e ia iuga", "respond by him end"], ["o le tulafono,", "the law"], ["ma ua", "and"], ["a ia", "but to"], ["i latou uma o", "them all of"], ["e ua faatuatua ia te ia;", "by faith to him"], ["ma o", "and of"], ["i latou", "them"], ["o e", "who"], ["ua faatuatua ia te ia", "faith to him"], ["o le a latou", "what they"], ["piimau i mea lelei uma;", "piimau in thing good all"], ["o le mea lea", "therefore"], ["ua fautuaina ai e ia", "fautuaina by him"], ["le faamoemoe", "the to expect"], ["o le fanauga", "the children"], ["a tagata;", "but man"], ["ma ua afio o ia", "and dwell (respectful) he"], ["e faavavau", "forever/everlasting"], ["i le lagi.", "in heaven"]]},
  {num:29,words:[["Ma ona", "and then"], ["ua faia e ia", "made by him"], ["lenei mea,", "this thing"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["pe ua taofia ai ea vavega?", "whether held back to rise (as a diver to the sur- a wonder"], ["Faauta ou te fai atu", "behold I said to"], ["ia te outou,", "unto you"], ["E leai;", "there is not"], ["pe ua taofia foi", "whether held back also"], ["le auauna mai o agelu", "the servant from of angel"], ["i le fanauga", "in the children"], ["a tagata.", "but man"]]},
  {num:30,words:[["Aua faauta,", "for behold"], ["ua i ai", "therein"], ["i latou", "them"], ["i lana pule,", "in his rule"], ["e auauna mai", "to servant from"], ["e tusa ma upu", "according to word"], ["e poloai ai o ia,", "to command he"], ["e faaali mai", "to revealed"], ["i latou lava ia te", "them indeed unto"], ["i latou", "them"], ["ua i ai", "therein"], ["le faatuatua malosi", "the faith strong"], ["ma le mafaufau mausali", "and the think to be Hrmly fixed"], ["i uiga uma", "in kind all"], ["o le amioatua.", "the amioatua"]]},
  {num:31,words:[["Ma o le tiute", "and the tiute"], ["o la latou auaunaga", "their auaunaga"], ["o le valaau atu lea", "the call"], ["i tagata ia salamo,", "in man to repent"], ["ma faataunuu", "and fulfilled"], ["ma faia", "and made"], ["le galuega o feagaiga", "the work of covenant"], ["a le Tamā,", "but the father"], ["ia na ia faia", "to he made"], ["i le fanauga", "in the children"], ["a tagata,", "but man"], ["e saunia", "to prepared"], ["le ala", "the way"], ["i totonu", "in inside"], ["o le fanauga", "the children"], ["a tagata,", "but man"], ["i le alaga atu", "in the cry"], ["o le afioga", "the a word"], ["a Keriso", "of Christ"], ["i ipu filifilia", "in cup chosen"], ["a le Alii,", "but the Lord"], ["ina ia latou molimau atu", "so that they a witness"], ["ia te ia.", "to him"]]},
  {num:32,words:[["Ma o le faia o lea mea,", "and the made therefore thing"], ["ua saunia ai", "prepared"], ["e le Alii", "by the Lord"], ["le Atua", "God"], ["le ala", "the way"], ["e mafai ai", "it is possible"], ["e le toe vaega o tagata", "by the again portion of men"], ["ona latou maua", "and they received"], ["o le faatuatua ia", "the faith to"], ["Keriso,", "Christ"], ["ina ia maua", "so that received"], ["e le Agaga Paia", "by the Holy Spirit"], ["se nofoaga", "a place"], ["i o latou loto,", "in of they heart"], ["e tusa ma lona mana;", "according to his to get"], ["ma o le ala lenei", "and the way this"], ["o le a faataunuu ai", "what fulfilled"], ["e le Tamā,", "by the father"], ["feagaiga na ia faia", "covenant he made"], ["i le fanauga", "in the children"], ["a tagata.", "but man"]]},
  {num:33,words:[["Ma ua fetalai", "and said"], ["mai Keriso:", "from Christ"], ["Afai tou te faatuatua", "if second person plural faith"], ["mai ia te au", "from I"], ["o le a outou", "what you (all)"], ["maua le mana", "received the to get"], ["e fai ai soo", "to make frequently"], ["se mea", "a thing"], ["e tatau ai ia te au.", "it is fitting unto me"]]},
  {num:34,words:[["Ma ua fetalai", "and said"], ["mai o ia:", "from he"], ["Ia outou salamo outou", "to you (all) repent you (all)"], ["tuluiga uma", "anointing all"], ["o le lalolagi,", "the earth"], ["ma o mai ia te au,", "and of from I"], ["ma ia papatiso", "and to baptize"], ["i lou igoa,", "in your name"], ["ma faatuatua mai ia te au,", "and faith from I"], ["ina ia faaolaina outou.", "so that saved alive you (all)"]]},
  {num:35,words:[["Ma o lenei,", "and now"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["afai o le tulaga lea", "if the matter"], ["e faapea", "saying"], ["ua moni nei mea", "true this thing"], ["ua ou tautala atu ai", "I to talk"], ["ia te outou,", "unto you"], ["ma o le a faaali", "and will revealed"], ["mai e le Atua ia te outou,", "from God unto you"], ["i le mana", "in the to get"], ["ma le mamalu tele", "and the glory great"], ["i le aso gataaga,", "in the day boundary"], ["ua moni", "true"], ["i latou,", "them"], ["ma afai", "and if"], ["ua moni", "true"], ["i latou,", "them"], ["pe ua uma ai ea", "whether it was finished to rise (as a diver to the sur-"], ["le aso o vavega?", "the day of a wonder"]]},
  {num:36,words:[["Pe ua taofia ea", "whether held back to rise (as a diver to the sur-"], ["le afifio mai o agelu", "the afifio from of angel"], ["i le fanauga", "in the children"], ["a tagata?", "but man"], ["Pe ua taofia e ia", "whether held back by him"], ["le mana", "the to get"], ["o le Agaga Paia", "the Holy Spirit"], ["mai ia te", "from"], ["i latou?", "them"], ["Pe e taofia ea", "whether to held back to rise (as a diver to the sur-"], ["e ia,", "by him"], ["ao tumau pea", "day enduring continually"], ["le taimi,", "the time"], ["pe ao tu pea", "whether day stand continually"], ["le lalolagi,", "the earth"], ["pe ao", "whether day"], ["i ai", "therein"], ["se tagata", "a man"], ["e toatasi", "to one One"], ["i luga", "in above"], ["o le lalolagi", "the earth"], ["e faaolaina?", "to saved alive"]]},
  {num:37,words:[["Faauta ou te fai atu", "behold I said to"], ["ia te outou,", "unto you"], ["E leai;", "there is not"], ["ona o le faatuatua", "because of the faith"], ["e faia ai vavega ;", "to made a wonder"], ["ma o le faatuatua", "and the faith"], ["e afifio mai ai agelu", "by afifio from angel"], ["ma auauna mai", "and servant from"], ["i tagata;", "in man"], ["o le mea lea,", "therefore"], ["afai ua taofia nei mea oi talofa", "if held back this thing wo"], ["i le fanauga", "in the children"], ["a tagata,", "but man"], ["ona o le", "because of the"], ["le talitonu", "the believe"], ["ua taofia ai,", "held back"], ["ma ua", "and"], ["le aoga ai mea uma.", "the useful all things"]]},
  {num:38,words:[["Ona e le mafai ona", "and by the able then"], ["faaolaina o se tagata,", "saved alive a man"], ["e tusa ma fetalaiga", "according to speech"], ["a Keriso,", "of Christ"], ["vagana ai", "except"], ["ua latou faatuatua", "they faith"], ["i lona suafa;", "in his name"], ["o le mea lea,", "therefore"], ["afai ua", "if"], ["le toe", "the again"], ["i ai nei mea,", "therein this thing"], ["ua le toe", "not again"], ["i ai foi", "therein also"], ["se faatuatua;", "a faith"], ["ma ua matua leaga lava", "and very evil indeed"], ["le tulaga o tagata,", "the matter of men"], ["ona o le a pei", "because of the but like"], ["i latou", "them"], ["e peiseai", "to as if"], ["e leai", "there is not"], ["se togiola", "a atonement"], ["ua faia.", "made"]]},
  {num:39,words:[["Ae faauta,", "but behold"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["ua ou matauina ni mea lelei", "I matauina some thing good"], ["mai ia te outou,", "from you (all)"], ["ona ua ou matauina", "and I matauina"], ["ua outou faatuatua ia", "you (all) faith to"], ["Keriso ona", "Christ then"], ["o lo outou agamalu;", "your meek"], ["ona a", "and but"], ["na fai tou te", "make second person plural"], ["le faatuatua ia te ia", "the faith to him"], ["po ua outou", "night you (all)"], ["le agavaa", "the agavaa"], ["e faitaulia", "to counted"], ["i totonu o tagata", "in the midst of man"], ["o lana ekalesia.", "his church"]]},
  {num:40,words:[["O lenei foi,", "this also"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["ou te fia tautala atu", "I want to do something to talk"], ["ia te outou", "unto you"], ["e uiga", "concerning"], ["i le faamoemoe .", "in the to expect"], ["E mafai faapefea", "it is possible how ?"], ["ona outou maua", "and you (all) received"], ["o le faatuatua,", "the faith"], ["vagana ai", "except"], ["ua ia te outou", "unto you"], ["le faamoemoe?", "the to expect"]]},
  {num:41,words:[["Ma o le a le mea tou te faamoemoe", "and what the thing second person plural to expect"], ["i ai?", "therein"], ["Faauta ou te fai atu", "behold I said to"], ["ia te outou,", "unto you"], ["tou te faamoemoe ,", "second person plural to expect"], ["e ala", "to way"], ["i le togiola", "in the atonement"], ["a Keriso", "of Christ"], ["ma le mana", "and the to get"], ["o lona toetu,", "his toetu"], ["ia faatutu mai outou", "to pitched up from you (all)"], ["i le ola faavavau,", "in the life everlasting"], ["ma o le pogai", "and the the root and stump of a"], ["ona o lo outou faatuatua", "because of your faith"], ["ia te ia", "to him"], ["e tusa ma le folafolaga.", "according to the the proclaiming"]]},
  {num:42,words:[["O le mea lea,", "therefore"], ["afai ua", "if"], ["i ai", "therein"], ["i se tagata", "in a man"], ["le faatuatua", "the faith"], ["e tatau ona", "should"], ["i ai ia te ia", "therein to him"], ["le faamoemoe;", "the to expect"], ["ona a aunoa", "and but without"], ["ma le faatuatua", "and the faith"], ["e le mafai ona", "by the able then"], ["i ai", "therein"], ["se faamoemoe.", "a to expect"]]},
  {num:43,words:[["O lenei foi,", "this also"], ["faauta ou te fai atu", "behold I said to"], ["ia te outou", "unto you"], ["e le mafai ona", "by the able then"], ["i ai ia te ia", "therein to him"], ["le faatuatua", "the faith"], ["ma le faamoemoe,", "and the to expect"], ["vagana ai", "except"], ["ua agamalu ,", "meek"], ["ma maualalo o ia", "and low he"], ["i le loto.", "in the heart"]]},
  {num:44,words:[["Afai e faapea,", "if saying"], ["ua le aoga lona faatuatua", "not useful his faith"], ["ma le faamoemoe,", "and the to expect"], ["ona e leai", "and there is not"], ["se tasi", "a one"], ["e ono talia", "by six received"], ["i luma", "in before"], ["o le Atua,", "of God"], ["vagana ai", "except"], ["i latou", "them"], ["o e", "who"], ["ua agamalu", "meek"], ["ma maualalalo", "and maualalalo"], ["i le loto;", "in the heart"], ["ma afai", "and if"], ["e agamalu", "to meek"], ["ma maualalo", "and low"], ["se tagata", "a man"], ["i le loto,", "in the heart"], ["ma tautino atu", "and to hang near the body"], ["i le mana", "in the to get"], ["o le Agaga Paia o Iesu", "the Holy Spirit of Jesus"], ["o le Keriso,", "the Christ"], ["e ao ina", "must needs"], ["i ai ia te ia", "therein to him"], ["le alofa mama;", "the love n"], ["aua afai", "for if"], ["e le", "by the"], ["i ai ia te ia", "therein to him"], ["le alofa mama,", "the love n"], ["o se mea noa o ia;", "a thing Noah he"], ["o le mea lea", "therefore"], ["e ao ai", "to day"], ["ina i ai ia te ia", "let therein to him"], ["le alofa mama.", "the love n"]]},
  {num:45,words:[["Ma o le alofa mama", "and the love n"], ["e loa", "to g:ra vest ones"], ["ona tali-tiga,", "and tali-tiga"], ["ma e agalelei,", "and to treated well"], ["ma e le losilosivale ,", "and by the losilosivale"], ["ma e le faafefeteina,", "and by the feared"], ["e le sailia e ia", "by the sought by him"], ["ana lava,", "his indeed"], ["e le faaitagofie,", "by the faaitagofie"], ["e le mafaufau", "by the think"], ["i se mea leaga,", "in a thing evil"], ["ma e le olioli", "and by the rejoice"], ["i le amioletonu", "in the wickedness"], ["ae olioli", "but rejoice"], ["i le upu moni,", "in the word true"], ["e onosaia mea uma,", "by onosaia all things"], ["e talia mea uma,", "to received all things"], ["e faamoemoe", "to to expect"], ["i mea uma,", "in all things"], ["e onosai", "to patience"], ["i mea uma.", "in all things"]]},
  {num:46,words:[["O le mea lea,", "therefore"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["afai e le ia te outou", "if by the unto you"], ["le alofa mama", "the love n"], ["o ni mea noa outou,", "some thing Noah you (all)"], ["ona e le uma", "and by the all"], ["le alofa mama.", "the love n"], ["O le mea lea,", "therefore"], ["ia outou fusi ai", "to you (all) bind"], ["i le alofa mama,", "in the love n"], ["le mea", "the thing"], ["ua silisili lea", "very much"], ["i mea uma,", "in all things"], ["ona e iu mea uma—", "and to attain thing uma—"]]},
  {num:47,words:[["Ae o le alofa mama", "but the love n"], ["o le alofa", "the love"], ["le pona lea o Keriso,", "the a knot of Christ"], ["ma e tumau", "and to be firm"], ["e faavavau;", "forever/everlasting"], ["ma o soo", "and of frequently"], ["se tasi", "a one"], ["e maua", "to received"], ["ua i ai ia te ia", "therein to him"], ["i le aso gataaga,", "in the day boundary"], ["o le a lelei ia te ia.", "what good to him"]]},
  {num:48,words:[["O le mea lea,", "therefore"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["ia outou tatalo atu", "to you (all) pray"], ["i le Tamā", "in the father"], ["ma le malosi", "and the strong"], ["atoa o le loto,", "together with the heart"], ["ina ia faatumulia outou", "so that faatumulia you (all)"], ["i lenei alofa,", "in this love"], ["lea ua ia faaee", "to to place upon"], ["mai i luga o", "from upon"], ["i latou uma o", "them all of"], ["e o soo moni", "by of frequently true"], ["o lona Alo,", "his Son"], ["o Iesu Keriso;", "Jesus Christ"], ["ina ia mafai ona", "that it might be and"], ["avea o outou", "become of you (all)"], ["ma atalii", "and son"], ["o le Atua;", "of God"], ["a oo ai", "but oo"], ["ina afio mai o ia", "let dwell (respectful) from he"], ["o le a tatou", "what we (incl)"], ["faapei o ia,", "like he"], ["ona o le a tatou", "because of the but we (incl)"], ["vaai ia te ia", "to look at to him"], ["e pei ona", "as"], ["i ai o ia;", "therein he"], ["tau ina ia tatou", "season so that we (incl)"], ["maua lenei faamoemoe;", "received this to expect"], ["tau ina ia mafai ona", "season that it might be then"], ["faamamaina i tatou", "cleansed in we (incl)"], ["e pei lava ona", "even as"], ["mama o ia.", "n he"], ["Amene.", "amen"]]},
];
renderVerseSet(_mr_ch_7_Verses, 'mr-ch7-verses');

var _mr_ch_8_Verses = [
  {num:1,words:[["O se tusi", "a book"], ["a lou tamā o Mamona,", "but your father of Mormon"], ["na tusi mai ia te au,", "book from I"], ["o Moronae;", "Moroni"], ["ma sa tusi", "and book"], ["mai ia te au", "from I"], ["ae lei pine", "but not to be long"], ["ona uma ona", "and all then"], ["valaauina o au", "called I am"], ["i le galuega.", "in the work"], ["Ma sa faapenei", "and faapenei"], ["ona ia tusi", "and to book"], ["mai ia te au,", "from I"], ["fai mai:", "said/told"]]},
  {num:2,words:[["Lou atalii pele", "your son dear"], ["e,", "by"], ["Moronae,", "Moroni"], ["ou te olioli tele", "I rejoice great"], ["ona ua manatu", "and thought"], ["mai lou Alii o Iesu Keriso", "from your Lord of Jesus Christ"], ["ia te oe,", "unto you"], ["ma ua ia valaauina oe", "and to called you"], ["i lana auaunaga,", "in his auaunaga"], ["ma i lana galuega paia.", "and in his work holy"]]},
  {num:3,words:[["Ou te manatu pea ia te oe", "I thought continually unto you"], ["i au talosaga,", "in I talosaga"], ["ma tatalo atu pea", "and pray continually"], ["i le Atua", "in the God"], ["le Tamā,", "the father"], ["i le suafa", "in the name"], ["o lona Alo Paia,", "his Son holy"], ["o Iesu,", "Jesus"], ["ia ona tausia oe,", "to then kept you"], ["e ala", "to way"], ["i lona agalelei", "in his treated well"], ["e le gata", "by the a snake"], ["ma lona alofa tunoa,", "and his grace"], ["i le tumau", "in the enduring"], ["i le faatuatua", "in the faith"], ["i lona suafa", "in his name"], ["e oo", "it shall come to pass"], ["i le iuga.", "in the end"]]},
  {num:4,words:[["Ma o lenei,", "and now"], ["lou atalii e,", "your son by"], ["ou te tautala atu ia te oe", "I to talk unto you"], ["e uiga", "concerning"], ["i lena mea", "in that thing"], ["ua ou faanoanoa tele ai:", "I to mourn great"], ["aua ou te faanoanoa", "for I to mourn"], ["i le tutulai", "in the tutulai"], ["mai o ni finauga", "from of some argument"], ["i totonu o outou.", "in the midst of you (all)"]]},
  {num:5,words:[["Aua,", "for"], ["afai ua ou iloaina", "if I recognized"], ["le mea moni,", "the thing true"], ["sa i ai ni finauga", "therein some argument"], ["i totonu o outou", "in the midst of you (all)"], ["e uiga", "concerning"], ["i le papatisoina o", "in the baptized of"], ["a outou fanau laiti.", "but you (all) born small"]]},
  {num:6,words:[["Ma o lenei,", "and now"], ["lou atalii e,", "your son by"], ["ou te manao ia", "I desire to"], ["e galue", "to till"], ["ma le filiga,", "and the perseverance"], ["ina ia aveeseina lenei sese tele", "so that removed away this wrong great"], ["mai totonu o outou;", "from inside of you (all)"], ["ona,", "and"], ["o le faamoemoe lenei", "the to expect this"], ["ua ou tusia ai lenei tusi.", "I written this book"]]},
  {num:7,words:[["Aua e lei pine", "for by not to be long"], ["ona mavae ona ou iloa", "and a parting then I known"], ["o nei mea", "this thing"], ["mai ia te oe,", "from you"], ["sa ou ole atu", "I entreat"], ["i le Alii e", "in the Lord by"], ["uiga i le mataupu.", "kind in the chapter"], ["Ma sa oo", "and it came to pass"], ["mai ia te au", "from I"], ["le afioga", "the a word"], ["a le Alii e", "but the Lord by"], ["ala i le mana", "way in the to get"], ["o le Agaga Paia,", "the Holy Spirit"], ["ua fetalai mai:", "said"]]},
  {num:8,words:[["Faalogo mai", "hearken from"], ["i upu", "in word"], ["a Keriso,", "of Christ"], ["lou Togiola,", "your atonement"], ["lou Alii", "your Lord"], ["ma lou Atua.", "and your God"], ["Faauta,", "behold"], ["ou te lei sau", "I not come"], ["i le lalolagi", "on the earth"], ["e valaau atu", "to call"], ["i e amiotonu", "in to righteous"], ["ae o", "but of"], ["e agasala ia salamo;", "to sin to repent"], ["ua le manaomia", "not desired"], ["e e", "by by"], ["ua maloloina", "maloloina"], ["se fomai,", "a fomai"], ["ae o", "but of"], ["i latou", "them"], ["o e", "who"], ["ua mamai;", "mamai"], ["o le mea lea,", "therefore"], ["ua maloloina tamaiti laiti,", "maloloina tamaiti small"], ["ona ua", "and"], ["le mafai ona", "the able then"], ["latou faia", "they made"], ["se agasala ;", "a sin"], ["o le mea lea", "therefore"], ["ua aveese mai ia te", "removed away from"], ["i latou,", "them"], ["ia te au,", "unto me"], ["le fetuu o Atamu ,", "the cursed of Adam"], ["ua leai ai sona mana", "there was not sona to get"], ["i luga o", "upon"], ["i latou;", "them"], ["ma ua aveese atu", "and removed away"], ["le tulafono", "the law"], ["o le peritomeina ,", "the circumcised"], ["e ala ia te au.", "to way unto me"]]},
  {num:9,words:[["Ma o le ala lenei", "and the way this"], ["na faaali mai ai", "revealed"], ["e le Agaga Paia ia te au", "by the Holy Spirit unto me"], ["le afioga", "the a word"], ["a le Atua;", "of God"], ["o le mea lea,", "therefore"], ["lou atalii pele", "your son dear"], ["e,", "by"], ["ua ou iloa ai", "I known"], ["o se ula totoa", "a to joke p'ural o( fnt"], ["i luma", "in before"], ["o le Atua,", "of God"], ["lo outou papatisoina o fanau laiti.", "your baptized of born small"]]},
  {num:10,words:[["Faauta ou te fai atu", "behold I said to"], ["ia te outou", "unto you"], ["o le mea lenei ia", "the thing this to"], ["outou aoao atu—o", "you (all) excellent atu—o"], ["le salamo", "the repent"], ["ma le papatisoga ia", "and the baptism to"], ["i latou", "them"], ["o e", "who"], ["ua tali atu", "respond"], ["ma mafai ona", "and able then"], ["faia le agasala;", "made sin"], ["ioe,", "yea"], ["aoao atu", "excellent"], ["i matua", "in very"], ["e tatau ona", "should"], ["latou salamo", "they repent"], ["ma papatisoina,", "and baptized"], ["ma faalotomaualalalo", "and faalotomaualalalo"], ["i latou lava", "them indeed"], ["e pei o", "to like of"], ["a latou fanau laiti,", "but they born small"], ["ma o le a faaolaina ai", "and will saved alive"], ["i latou uma faatasi", "them all once"], ["ma a latou fanau laiti.", "and but they born small"]]},
  {num:11,words:[["Ma e le manaomia", "and by the desired"], ["e a latou fanau laiti", "by but they born small"], ["se salamo,", "a repent"], ["po o le papatisoga.", "night the baptism"], ["Faauta,", "behold"], ["o le papatisoga", "the baptism"], ["ua mo le salamo", "for the repent"], ["i le faataunuuina o poloaiga", "in the fulfilled of commandment"], ["mo le faamagaloina o agasala.", "for the forgiven of sin"]]},
  {num:12,words:[["Ae o fanau laiti", "but of born small"], ["ua ola ia Keriso,", "life to Christ"], ["mai lava", "from indeed"], ["i le faavaega", "in the faavaega"], ["o le lalolagi;", "the earth"], ["afai ua", "if"], ["le faapea,", "the thus"], ["o le Atua", "of God"], ["o se Atua faaauau,", "a God continued"], ["ma o se Atua feliuliuai", "and a God turning"], ["foi,", "also"], ["ma o se", "and a"], ["ua faailoga tagata;", "sign man"], ["ona o le a le toatele", "because of the but the many"], ["o fanau laiti", "born small"], ["ua feoti", "feoti"], ["e aunoa", "to without"], ["ma le papatisoga!", "and the baptism"]]},
  {num:13,words:[["O le mea lea,", "therefore"], ["afai e le mafai ona", "if by the able then"], ["faaolaina o fanau laiti", "saved alive of born small"], ["e aunoa", "to without"], ["ma le papatisoga,", "and the baptism"], ["po ua latou", "night they"], ["o atu", "o atu"], ["i le seoli", "in the Sheol"], ["e le gata.", "by the a snake"]]},
  {num:14,words:[["Faauta ou te fai atu", "behold I said to"], ["ia te oe,", "unto you"], ["o ia", "he"], ["o le", "the"], ["ua manatu", "thought"], ["ua manaomia", "desired"], ["e fanau laiti", "to born small"], ["le papatisoga", "the baptism"], ["ua i ai o ia", "therein he"], ["i le au oona", "in the I drunk"], ["ma fusi", "and bind"], ["o le amioletonu;", "the wickedness"], ["aua ua", "for"], ["le i ai ia te ia", "the therein to him"], ["le faatuatua ,", "the faith"], ["faamoemoe,", "to expect"], ["po o le alofa mama;", "night the love n"], ["o le mea lea,", "therefore"], ["afai e vavae ese o ia", "if to to divide away he"], ["ao i ai ia te ia", "day therein to him"], ["lea manatu,", "thought"], ["o le a alu ifo", "what go down"], ["o ia", "he"], ["i lalo", "in under"], ["i seoli.", "in Sheol"]]},
  {num:15,words:[["Ona ua matua leaga lava", "and very evil indeed"], ["le amioleaga", "the wickedness"], ["o le manatu", "the thought"], ["e faapea", "saying"], ["e faaolaina", "to saved alive"], ["e le Atua", "God"], ["se tasi tamaitiiti", "a one child"], ["ona ua papatisoina,", "and baptized"], ["ae o le a fano", "but will perish"], ["le tasi", "the one"], ["ona ua", "and"], ["le papatisoina.", "the baptized"]]},
  {num:16,words:[["Oi talofa ia te", "wo unto"], ["i latou", "them"], ["e faapiopioina ala", "by faapiopioina way"], ["o le Alii", "the Lord"], ["i lenei ala,", "in this way"], ["ona o le a fano", "because of the but perish"], ["i latou vagana ai", "them except"], ["ua latou salamo.", "they repent"], ["Faauta,", "behold"], ["ou te tautala atu", "I to talk"], ["ma le lotoa,", "and the lotoa"], ["ona ua ou maua", "and I received"], ["le pule mai", "the rule from"], ["le Atua;", "God"], ["ma ou te", "and I"], ["le fefe po o", "the get scared night of"], ["a mea", "but thing"], ["e mafai ona", "could"], ["faia e tagata;", "made to man"], ["ona e lafo ese", "and to cloth used as gratuity for a talking chief away"], ["i fafo", "in outside"], ["e le alofa", "by the love"], ["ua atoatoa", "completely"], ["le fefe uma.", "the get scared all"]]},
  {num:17,words:[["Ma ua tumu au", "and fill I"], ["i le alofa mama,", "in the love n"], ["le alofa tumau-faavavau lea;", "the love tumau-faavavau"], ["o le mea lea,", "therefore"], ["ua tutusa fanau laiti uma", "equal born small all"], ["ia te au;", "unto me"], ["o le mea lea,", "therefore"], ["ua ou alofa", "I love"], ["i fanau laiti", "in born small"], ["i se alofa", "in a love"], ["ua atoatoa;", "completely"], ["ma ua tutusa", "and equal"], ["i latou uma", "them all"], ["ma ua tofusia", "and tofusia"], ["i le olataga.", "in the a means of deliverance"]]},
  {num:18,words:[["Ona ua ou iloa", "and I known"], ["o le Atua e", "of God by"], ["le o se Atua faaauau,", "the a God continued"], ["po o se tagata", "night a man"], ["ua feliuliuai;", "turning"], ["ae ua", "but"], ["le feliuliuai o ia", "the turning he"], ["mai le faavavau", "from the everlasting"], ["atoa i le faavavau", "together with in the everlasting"], ["atoa.", "together with"]]},
  {num:19,words:[["E le mafai", "by the able"], ["e fanau laiti", "to born small"], ["ona salamo;", "and repent"], ["o le mea lea,", "therefore"], ["o se amioleaga tele", "a wickedness great"], ["le faafitia", "the opposed"], ["o le alofa mutimutivale mama", "the mercy n"], ["o le Atua", "of God"], ["mai ia te", "from"], ["i latou,", "them"], ["ona ua ola uma", "and life all"], ["i latou ia te ia", "them to him"], ["ona o lona alofa mutimutivale.", "because of his mercy"]]},
  {num:20,words:[["Ma o ia", "and he"], ["o le", "the"], ["e fai mai", "to said"], ["e manaomia", "to desired"], ["e fanau laiti", "to born small"], ["le papatisoga", "the baptism"], ["ua ia faafitia", "to opposed"], ["le alofa mutimutivale o Keriso,", "the mercy of Christ"], ["ma fai", "and make"], ["ma meanoa lana togiola", "and meanoa his atonement"], ["ma le mana", "and the to get"], ["o lana togiola.", "his atonement"]]},
  {num:21,words:[["Oi talofa", "wo"], ["i e faapea,", "in saying"], ["ona ua latou onofia", "and they onofia"], ["i le oti,", "in the die"], ["seoli ,", "Sheol"], ["ma le mafatia", "and the the distribution of pro-"], ["e le gata.", "by the a snake"], ["Ou te tautala atu ia", "I to talk to"], ["upu ma le lotoa;", "word and the lotoa"], ["ua poloaiina ai au", "commanded I"], ["e le Atua.", "God"], ["Ia outou faalogo", "to you (all) hearken"], ["i ai", "therein"], ["ma uai", "and desire"], ["i ai,", "therein"], ["a leai", "but no"], ["o le a tutu", "what to set fire to"], ["e faasaga ia te outou", "to toward unto you"], ["i le nofoa-faamasino o Keriso.", "in the nofoa-faamasino of Christ"]]},
  {num:22,words:[["Aua faauta,", "for behold"], ["ua ola fanau laiti uma", "life born small all"], ["ia Keriso,", "to Christ"], ["ma i latou uma foi", "and them all also"], ["o e", "who"], ["ua aunoa", "without"], ["ma le tulafono .", "and the law"], ["Aua e oo", "for it shall come to pass"], ["mai le mana", "from the to get"], ["o le togiola", "the atonement"], ["i luga o", "upon"], ["i latou uma o", "them all of"], ["e ua aunoa", "by without"], ["ma le tulafono;", "and the law"], ["o le mea lea,", "therefore"], ["o ia", "he"], ["o le", "the"], ["ua le tausalaina,", "the tausalaina"], ["po o ia", "night he"], ["o le", "the"], ["ua le", "not"], ["i lalo", "in under"], ["o se tausalaga,", "a tausalaga"], ["e le mafai ona", "by the able then"], ["salamo;", "repent"], ["ma o", "and of"], ["e faapena", "to likewise"], ["ua le aoga", "not useful"], ["i ai", "therein"], ["le papatisoga—", "the papatisoga—"]]},
  {num:23,words:[["Ae o se ulaga", "but a ulaga"], ["i luma", "in before"], ["o le Atua,", "of God"], ["ua faafitia ai", "opposed"], ["le alofa mutimutivale o Keriso,", "the mercy of Christ"], ["ma le mana", "and the to get"], ["o lona Agaga Paia,", "his/her Holy Spirit"], ["ma le tuuina atu", "and the given"], ["o le faalagolago", "the to lean upon"], ["i galuega mamate .", "in work mamate"]]},
  {num:24,words:[["Faauta,", "behold"], ["lou atalii e,", "your son by"], ["e le tatau lava ona", "by the to wring out indeed then"], ["i ai o lenei mea;", "therein of this thing"], ["ona o le salamo", "because of the repent"], ["e mo", "by for"], ["i latou", "them"], ["ua i ai", "therein"], ["i lalo", "in under"], ["o le tausalaga", "the tausalaga"], ["ma lalo", "and under"], ["o le fetuu", "the cursed"], ["o le tulafono", "the law"], ["ua solia.", "despised"]]},
  {num:25,words:[["Ma o fua muamua", "and of fruit first"], ["o le salamo", "the repent"], ["o le papatisoga ;", "the baptism"], ["ma o le papatisoga", "and the baptism"], ["e oo mai", "it shall come to pass from"], ["e ala", "to way"], ["i le faatuatua", "in the faith"], ["e faataunuu ai poloaiga;", "to fulfilled commandment"], ["ma o le faataunuuina o poloaiga", "and the fulfilled of commandment"], ["e maua ai", "to received"], ["le faamagaloina o agasala;", "the forgiven of sin"]]},
  {num:26,words:[["Ma o le faamagaloina o agasala", "and the forgiven of sin"], ["e maua ai", "to received"], ["le agamalu ,", "the meek"], ["ma le maualalo", "and the low"], ["o le loto;", "the heart"], ["ma o le agamalu", "and the meek"], ["ma le maualalo", "and the low"], ["o le loto", "the heart"], ["e oo mai ai", "it shall come to pass from"], ["le asiasiga", "the asiasiga"], ["a le Agaga Paia,", "but the Holy Spirit"], ["o le Faamafanafana lea", "the to hearten"], ["na te faatumuina", "he filled"], ["le tagata", "the man"], ["i le faamoemoe", "in the to expect"], ["ma le alofa atoatoa,", "and the love completely"], ["o le alofa lea", "the love"], ["e tumau", "to be firm"], ["e ala", "to way"], ["i le filiga", "in the perseverance"], ["i le tatalo ,", "in the pray"], ["seia oo mai", "until came"], ["le iuga,", "the end"], ["pe a mau", "whether but opinion"], ["le au paia uma faatasi", "the saints all once"], ["ma le Atua.", "and the God"]]},
  {num:27,words:[["Faauta,", "behold"], ["lou atalii e,", "your son by"], ["o le a ou toe tusi atu", "what I again book"], ["ia te oe", "unto you"], ["pe a le vave", "whether but the quick"], ["ona ou alu atu", "and I go away"], ["i fafo", "in outside"], ["e faasaga ia", "to toward to"], ["sa Lamanā.", "thus Laman"], ["Faauta,", "behold"], ["o le faamaualuluga o lenei atunuu,", "the faamaualuluga of this nations"], ["po o tagata o", "night of men of"], ["sa Nifaē,", "thus Nephi"], ["ua faamaonia ai lo latou faaumatiaga vagana ai", "faamaonia their destruction except"], ["o le a latou", "what they"], ["salamo.", "repent"]]},
  {num:28,words:[["Ia e tatalo", "to to pray"], ["mo i latou,", "for them"], ["lou atalii e,", "your son by"], ["ina ia oo", "so that oo"], ["mai le salamo ia te", "from the repent unto"], ["i latou.", "them"], ["Peitai faauta,", "however behold"], ["ou te fefe nei", "I get scared this"], ["le toe taumafai", "the again to strive"], ["le Agaga ia te", "the spirit unto"], ["i latou;", "them"], ["ma i le vaega lenei", "and in the portion this"], ["o le laueleele,", "the ground"], ["o loo latou saili foi", "they seek also"], ["e tuu", "to put"], ["i lalo", "in under"], ["le mana", "the to get"], ["ma le pule", "and the rule"], ["atoa lea", "together with"], ["ua sau mai", "come"], ["le Atua;", "God"], ["ma ua latou teena", "and they rejected"], ["le Agaga Paia.", "the Holy Spirit"]]},
  {num:29,words:[["Ma ina", "and let"], ["ua uma ona", "finished"], ["latou teena", "they rejected"], ["se malamalama tele faapea naua,", "a great knowledge thus exceedingly"], ["lou atalii e,", "your son by"], ["o le a vave", "what quick"], ["ona fano o", "and perish of"], ["i latou,", "them"], ["i le faataunuuina o valoaga", "in the fulfilled of a prediction"], ["na fetalaia", "fetalaia"], ["e perofeta,", "to prophet"], ["faapea foi", "thus also"], ["ma fetalaiga", "and speech"], ["a lo tatou Faaola lava", "but our save indeed"], ["ia.", "to"]]},
  {num:30,words:[["Tofa ia,", "determination to"], ["lou atalii e,", "your son by"], ["seia ou tusi atu ia te oe,", "until I book unto you"], ["pe seia ou toe feiloai", "whether until I again feiloai"], ["ma oe.", "and you"], ["Amene.", "amen"]]},
];
renderVerseSet(_mr_ch_8_Verses, 'mr-ch8-verses');

var _mr_ch_9_Verses = [
  {num:1,words:[["Lou atalii pele", "your son dear"], ["e,", "by"], ["ua ou toe tusi atu", "I again book"], ["ia te oe", "unto you"], ["ina ia", "so that"], ["e iloa o loo ou ola pea;", "to known of I life continually"], ["ae ou te tusi teisi", "but I book in a short time"], ["e uiga", "concerning"], ["i mea", "in thing"], ["ua matua faanoanoa tele.", "very to mourn great"]]},
  {num:2,words:[["Aua faauta,", "for behold"], ["sa ou tauina", "I was told"], ["se taua tuga", "a precious a maggot"], ["ma sa Lamanā,", "and thus Laman"], ["lea sa matou", "we (excl)"], ["le manumalo ai;", "the overcome"], ["ma ua pau Akeanetusi", "and fall Akeanetusi"], ["i le pelu,", "by the sword"], ["ma Lurama", "and Lurama"], ["ma Emirona foi;", "and Emirona also"], ["ioe,", "yea"], ["ma ua toesea", "and toesea"], ["mai ia te", "from"], ["i tatou", "in we (incl)"], ["se aofai tele o o tatou", "a number great of of we (incl)"], ["tagata sili", "man most"], ["ona lelei.", "and good"]]},
  {num:3,words:[["Ma o lenei", "and now"], ["faauta,", "behold"], ["lou atalii e,", "your son by"], ["ou te fefe nei faaumatia", "I get scared this destroyed"], ["e sa Lamanā lenei nuu;", "by thus Laman this nation"], ["ona ua latou", "and they"], ["le salamo,", "the repent"], ["ma ua faaosooso pea", "and faaosooso continually"], ["i latou", "them"], ["e Satani ia feitagai", "to Satan to feitagai"], ["ma le tasi.", "and the one"]]},
  {num:4,words:[["Faauta,", "behold"], ["o loo ou galue pea", "I till continually"], ["e le aunoa ia te", "by the without unto"], ["i latou;", "them"], ["ma a ou tautala atu", "and but I to talk"], ["ia te", "unto"], ["i latou", "them"], ["le afioga", "the a word"], ["a le Atua", "of God"], ["ma le saolele latou", "and the saolele they"], ["te tetete", "tetete"], ["ma feita faasaga", "and feita toward"], ["mai ia te au;", "from I"], ["ma a ou", "and but I"], ["le tautala atu foi", "the to talk also"], ["ma le saolele", "and the saolele"], ["ua latou faamaaa o latou", "they hardened of they"], ["loto e faasaga", "heart to toward"], ["i ai;", "therein"], ["o le mea lea,", "therefore"], ["ou te fefe nei mea ane", "I get scared this thing"], ["ua le toe finafinau", "not again finafinau"], ["le Agaga", "the spirit"], ["o le Alii faatasi", "the Lord once"], ["ma i latou.", "and them"]]},
  {num:5,words:[["Ona ua latou matua feita tele", "and they very feita great"], ["e foliga mai ia te au", "to likeness from I"], ["ua leai so latou", "there was not so they"], ["fefefe i le oti;", "afraid in the die"], ["ma ua toesea lo latou alofa,", "and toesea their love"], ["o le tasi", "the one"], ["i le isi;", "in the other"], ["ma ua latou galala", "and they to have intense thirst"], ["i le toto", "in the blood"], ["ma le taui", "and the a reward"], ["ma sui", "and to dilute"], ["e le aunoa.", "by the without"]]},
  {num:6,words:[["Ma o lenei,", "and now"], ["lou atalii pele", "your son dear"], ["e,", "by"], ["e ui i lo latou maaa,", "to although in the they hardness"], ["ia ta galulue pea", "to a stroke labour continually"], ["ma le filiga ;", "and the perseverance"], ["aua afai ta te tuu", "for if a stroke put"], ["le galulue ,", "the labour"], ["o le a aumai", "what bring"], ["i taua", "in precious"], ["i lalo", "in under"], ["o le tausalaga;", "the tausalaga"], ["ona ua", "and"], ["i ai", "therein"], ["sa taua galuega", "precious work"], ["e fai ao ta", "to make day a stroke"], ["i ai", "therein"], ["i lenei fale apitaga omea,", "in this house a tempoiary mortar"], ["ina ia ta faatoilaloina", "so that a stroke faatoilaloina"], ["le fili", "the to choose"], ["o le amiotonu uma,", "of all righteousness"], ["ma malolo ai o taua agaga", "and rest of precious spirit"], ["i le malo", "in the government"], ["o le Atua.", "of God"]]},
  {num:7,words:[["Ma o lenei ou te tusi atu teisi", "and now I book in a short time"], ["e uiga", "concerning"], ["i mafatiaga o lenei nuu.", "in mafatiaga of this nation"], ["Aua e tusa ma le malamalama lea", "for according to the light"], ["na ou maua", "I received"], ["mai ia Amorona,", "from to Amorona"], ["faauta,", "behold"], ["ua maua", "received"], ["e sa Lamanā ni pagota", "by thus Laman some pagota"], ["e toatele,", "many"], ["ia sa latou aumai", "to they bring"], ["mai le olo o Serisa;", "from the fortress of Serisa"], ["ma sa", "and"], ["i ai tane,", "therein man"], ["fafine,", "woman"], ["ma tamaiti.", "and tamaiti"]]},
  {num:8,words:[["Ma o tane", "and of man"], ["ma tamā o ia", "and father he"], ["fafine ma tamaiti", "woman and tamaiti"], ["ua latou fasiotia;", "they slain"], ["ma ua latou fafaga fafine", "and they a woman's burden woman"], ["i aano o", "in body of"], ["a latou tane,", "but they man"], ["ma tamaiti", "and tamaiti"], ["i aano o o latou", "in body of of they"], ["tamā;", "father"], ["ma ua latou", "and they"], ["le avatu ia te", "the give away unto"], ["i latou", "them"], ["se vai,", "a water"], ["vagana ai sina mea itiiti.", "except white thing small"]]},
  {num:9,words:[["Ma e ui i lenei mea inosia tele", "and to although in this abominations great"], ["a sa Lamanā,", "but thus Laman"], ["ua le sili atu i", "not most in"], ["le mea", "the thing"], ["ua faia", "made"], ["e o tatou tagata", "by of we (incl) man"], ["i Morianetuma.", "in Morianetuma"], ["Aua faauta,", "for behold"], ["e toatele afafine o", "many daughter of"], ["sa Lamanā", "thus Laman"], ["ua latou ave faapagota;", "they take faapagota"], ["ma ina", "and let"], ["ua uma ona", "finished"], ["latou aveesea mai ia te", "they removed away from"], ["i latou", "them"], ["o le mea lena", "the thing that"], ["ua silisili", "very much"], ["ona pele", "and dear"], ["ma taua", "and precious"], ["i luga o mea uma", "upon all things"], ["lava,", "indeed"], ["o le lē gaōiā lea", "the not gaōiā"], ["ma le mama —", "and the n —"]]},
  {num:10,words:[["Ma ina", "and let"], ["ua uma ona", "finished"], ["latou faia o lenei mea,", "they made of this thing"], ["sa latou fasioti", "they killed"], ["i latou", "them"], ["i se auala", "in a auala"], ["e silisili", "to very much"], ["ona paaa,", "and crisp"], ["ua faatauga o latou", "to ill-use of they"], ["tino seia oo", "body until oo"], ["ina feoti;", "let feoti"], ["ma ina", "and let"], ["ua uma ona", "finished"], ["latou faia o lenei mea,", "they made of this thing"], ["ua latou ai lotulotu o latou", "they to dn iinylliing liastilv of they"], ["tino e pei o manu aivao,", "body to like of animal aivao"], ["ona o le maaa o", "because of the hardness of"], ["o latou loto;", "they heart"], ["ma ua latou faia lenei mea", "and they did this thing"], ["o se faailoga", "a sign"], ["o le toa.", "the heroic"]]},
  {num:11,words:[["E,", "by"], ["lou atalii pele", "your son dear"], ["e,", "by"], ["e mafai faapefea", "it is possible how ?"], ["e ni tagata faapenei,", "by some man faapenei"], ["ua aunoa", "without"], ["ma le tu malamalama—", "and the stand malamalama—"]]},
  {num:12,words:[["(Ma e nao ni", "and to only some"], ["nai tausaga itiiti", "from year small"], ["ua mavae atu,", "after"], ["sa avea ai", "become"], ["i latou", "them"], ["ma ni tagata tu malamalama", "and some man stand light"], ["ma tauagafau)", "and tauagafau"]]},
  {num:13,words:[["Ae lou atalii", "but your son"], ["e,", "by"], ["e mafai faapefea", "it is possible how ?"], ["e ni tagata faapenei,", "by some man faapenei"], ["o e", "who"], ["o lo latou fiafia", "their competition"], ["ua i ai lea", "therein"], ["i le faia o mea inosia", "in the made of abominations"], ["e tele—", "by tele—"]]},
  {num:14,words:[["E mafai faapefea", "it is possible how ?"], ["ona tatou faamoemoe", "and we (incl) to expect"], ["o le a taofi", "what hold"], ["e le Atua lona aao", "God his hand (extended)"], ["i le faamasinoga", "in the judgment"], ["e faasaga ia te", "to toward unto"], ["i tatou?", "in we (incl)"]]},
  {num:15,words:[["Faauta,", "behold"], ["ua tagi", "cry"], ["ae lo'u loto:", "but my heart"], ["Oi talofa", "wo"], ["i lenei nuu.", "in this nation"], ["Afio mai ia,", "dwell (respectful) from to"], ["le Atua e,", "God by"], ["i le faamasinoga,", "in the judgment"], ["ma natia", "and hide"], ["a latou agasala,", "but they sin"], ["ma amioleaga,", "and wickedness"], ["ma mea inosia", "and abominations"], ["mai luma o ou fofoga!", "from before of I face"]]},
  {num:16,words:[["O lenei foi,", "this also"], ["lou atalii e,", "your son by"], ["e toatele o fafine", "many woman"], ["ua oti", "die"], ["a latou tane,", "but they man"], ["ma a latou tama teine,", "and but they daughters"], ["o loo nonofo pea", "dwelling continually"], ["i Serisa;", "in Serisa"], ["ma o le vaega lena", "and the portion that"], ["o meaai", "food"], ["sa le avea", "not become"], ["e sa Lamanā,", "by thus Laman"], ["faauta,", "behold"], ["ua ave", "take"], ["e le autau", "by the fought"], ["a Senifae,", "of Senifae"], ["ma ua tuua ai", "and left"], ["i latou", "them"], ["e feoai solo", "by feoai to move swiftly"], ["i soo", "in frequently"], ["se mea", "a thing"], ["e mafai ona", "could"], ["latou o atu", "they of"], ["i ai", "therein"], ["mo ni meaai;", "for some food"], ["ma e toatele fafine matutua", "and many woman old"], ["ua matapogia", "matapogia"], ["i ala", "in way"], ["ma feoti ai.", "and feoti"]]},
  {num:17,words:[["Ma o le autau", "and the fought"], ["ua faatasi", "once"], ["ma au", "and I"], ["ua vaivai;", "weak"], ["ma o autau", "and of fought"], ["a sa Lamanā o loo", "but thus Laman of"], ["i le va o Serisa", "in the midst of Serisa"], ["ma au;", "and I"], ["ma o le toatele o", "and the many of"], ["e na sosola atu", "by fled"], ["i le autau", "in the fought"], ["a Arona", "of Aaron"], ["ua pauu fasia", "fell struck"], ["i lo latou saua matautia faamanu.", "in the they to have a return of sick- fearful to place a gift: on the"]]},
  {num:18,words:[["E,", "by"], ["le leaga", "the evil"], ["e o lou nuu!", "by your nation"], ["Ua latou aunoa", "they without"], ["ma le maopoopo", "and the compact"], ["ma aunoa", "and without"], ["ma le alofa mutimutivale.", "and the mercy"], ["Faauta,", "behold"], ["o au", "I am"], ["ua nao", "only"], ["se tagata,", "a man"], ["ma ua nao", "and only"], ["le malosi", "the strong"], ["o se tagata", "a man"], ["ua ia te au,", "unto me"], ["ma ua", "and"], ["le mafai ona", "the able then"], ["ou toe faamalosia au", "I again strengthened I"], ["faatonuga.", "faatonuga"]]},
  {num:19,words:[["Ma ua latou malolosi ia", "and they mighty to"], ["latou faapiopioga;", "they faapiopioga"], ["ma ua tutusa lo latou saua faamanu,", "and equal their to have a return of sick- to place a gift: on the"], ["ua latou", "they"], ["le faasaoina", "the spared"], ["se tasi,", "a one"], ["pe matutua", "whether old"], ["pe laiti;", "whether small"], ["ma ua latou fiafia", "and they competition"], ["i mea uma,", "in all things"], ["vagana ai", "except"], ["le mea lelei;", "the thing good"], ["ma o le mafatia o", "and the the distribution of pro- of"], ["o tatou fafine", "we (incl) woman"], ["ma a tatou fanau", "and but we (incl) born"], ["i luga", "in above"], ["o le laueleele", "the ground"], ["atoa lenei", "together with this"], ["ua sili atu i mea uma;", "most in all things"], ["ioe,", "yea"], ["e le mafai", "by the able"], ["e le laulaufaiva", "by the tongue"], ["ona faamatala,", "and faamatala"], ["pe mafai foi", "whether able also"], ["ona tusia.", "and written"]]},
  {num:20,words:[["Ma o lenei,", "and now"], ["lou atalii e,", "your son by"], ["ou te", "I"], ["le toe fia tautala umi atu", "the again want to do something to talk long"], ["e uiga", "concerning"], ["i lenei vaaiga leaga matautia.", "in this a prospect evil fearful"], ["Faauta,", "behold"], ["ua e iloa", "to known"], ["le amioleaga o lenei nuu;", "the wickedness of this nation"], ["ua e iloa", "to known"], ["ua latou aunoa", "they without"], ["ma se mafaufau lelei,", "and a think good"], ["ma ua latou", "and they"], ["le toe lagona", "the again to understand"], ["se lelei;", "a good"], ["ma o lo latou amioleaga", "and their wickedness"], ["ua sili atu i lo", "exceeded"], ["sa Lamanā.", "thus Laman"]]},
  {num:21,words:[["Faauta,", "behold"], ["lou atalii e,", "your son by"], ["e le mafai ona", "by the able then"], ["fautua atu", "fautua"], ["i latou", "them"], ["i le Atua nei taia au", "in the God this struck I"], ["e ia.", "by him"]]},
  {num:22,words:[["Ae faauta,", "but behold"], ["lou atalii e,", "your son by"], ["ou te fautua atu oe", "I fautua you"], ["i le Atua,", "in the God"], ["ou te faalagolago ia", "I to lean upon to"], ["Keriso ia faaolaina oe;", "Christ to keep alive you"], ["ma ou te tatalo atu", "and I pray"], ["i le Atua ia", "in the God to"], ["faasaoina e ia lou ola,", "spared by him your life"], ["e molimauina", "by molimauina"], ["le toe foi", "the again also"], ["mai o", "from of"], ["ona tagata ia te ia,", "and man to him"], ["po o lo latou faafanoga", "night their destruction"], ["atoa;", "together with"], ["ona ua ou iloa", "and I known"], ["e o le a fano", "by will perish"], ["i latou vagana ai", "them except"], ["ua latou salamo", "they repent"], ["ma toe foi", "and again also"], ["mai ia te ia.", "from him"]]},
  {num:23,words:[["Ma afai", "and if"], ["e fano", "to perish"], ["i latou", "them"], ["o le a pei o", "what like of"], ["sa Iaretō,", "of the clan of Iaretō"], ["ona o lo latou saili", "because of their seek"], ["ma le loto", "and the heart"], ["i ai o o latou", "therein of of they"], ["loto,", "heart"], ["mo le toto", "for the blood"], ["ma le tauimasui .", "and the tauimasui"]]},
  {num:24,words:[["Ma afai", "and if"], ["e faapea", "saying"], ["o le a fano", "shall perish"], ["i latou,", "them"], ["ua tatou iloa", "we (incl) known"], ["e toatele o tatou", "many we (incl)"], ["uso ua sosola atu ia", "brother fled to"], ["sa Lamanā,", "thus Laman"], ["ma e toatele atu foi ni isi", "and many also some other"], ["o le a sosola atu", "what fled"], ["ia te", "unto"], ["i latou;", "them"], ["o le mea lea,", "therefore"], ["ia e tusi teisi ni", "to to book in a short time some"], ["nai mea itiiti,", "from thing small"], ["pe afai", "whether if"], ["e faasaoina oe", "to spared you"], ["ma o le a ou fano", "and will I perish"], ["ma le vaai ia te oe;", "and the to look at unto you"], ["ae ou te faalagolago ia", "but I to lean upon to"], ["mafai ona", "able then"], ["lata ona ou vaai ia te oe;", "near then I to look at unto you"], ["ona ua ia te au", "and unto me"], ["ni au talafaamaumau paia ou te manao", "some I record holy I desire"], ["e tuu atu ia te oe.", "to placed unto you"]]},
  {num:25,words:[["Lou atalii e,", "your son by"], ["ia e faamaoni ia", "to to faithful to"], ["Keriso;", "Christ"], ["ma ia le avea mea", "and to the become thing"], ["ua ou tusia", "I written"], ["ma mea", "and thing"], ["e te faanoanoa ai,", "by to mourn"], ["e faamamafa ai oe", "by faamamafa you"], ["i lalo sei", "in under a flower put into the hair or"], ["e oti;", "to die"], ["ae talosia ia sii", "but passive of tatalo to lift up"], ["ae oe", "but you"], ["i luga", "in above"], ["e Keriso,", "to Christ"], ["ma talosia ia mau", "and passive of tatalo to opinion"], ["e faavavau", "forever/everlasting"], ["i lou mafaufau", "in your think"], ["ona mafatia", "and the distribution of pro-"], ["ma lona maliu,", "and his die"], ["ma le faaali", "and the revealed"], ["mai o lona tino", "from his body"], ["i o tatou tamā,", "in of we (incl) father"], ["ma lona alofa mutimutivale", "and his mercy"], ["ma le tali-tiga,", "and the tali-tiga"], ["ma le faamoemoe", "and the to expect"], ["o lona mamalu", "his glory"], ["ma le ola faavavau.", "and the life everlasting"]]},
  {num:26,words:[["Ma talosia ia", "and passive of tatalo to"], ["i ai,", "therein"], ["ma mau faatasi", "and opinion once"], ["ma oe", "and you"], ["e faavavau,", "forever/everlasting"], ["le alofa tunoa", "grace"], ["o le Atua", "of God"], ["le Tamā,", "the father"], ["o le", "the"], ["o lona nofoalii", "his throne"], ["ua maualuga", "Iiigli"], ["i le lagi,", "in heaven"], ["ma lo tatou Alii o Iesu Keriso,", "and the we (incl) Lord of Jesus Christ"], ["o le", "the"], ["ua afio", "dwell (respectful)"], ["i le itu aao taumatau", "on the side hand (extended) right hand"], ["o lona mana,", "his to get"], ["seia oo", "until oo"], ["ina pule o ia", "let rule he"], ["i mea uma.", "in all things"], ["Amene.", "amen"]]},
];
renderVerseSet(_mr_ch_9_Verses, 'mr-ch9-verses');

var _mr_ch_10_Verses = [
  {num:1,words:[["O lenei,", "this"], ["o au,", "I am"], ["o Moronae,", "Moroni"], ["ou te tusi teisi", "I book in a short time"], ["i ni mea ou te manatu", "in some thing I thought"], ["lava au", "indeed I"], ["ua lelei;", "that it was good"], ["ma ou te tusi atu", "and I book"], ["i ou uso,", "in I brother"], ["o sa Lamanā;", "thus Laman"], ["ma ou te manao ia", "and I desire to"], ["latou iloa", "they known"], ["ua sili atu i le fa selau", "most in the four hundred"], ["ma le lua sefulu tausaga", "and two ten year"], ["ua mavae atu talu", "after since"], ["ona tuuina mai", "and given from"], ["o le faailoga", "the sign"], ["o le afio", "the dwell (respectful)"], ["mai o Keriso.", "from of Christ"]]},
  {num:2,words:[["Ma ou te faamaufaailogaina nei talafaamaumau,", "and I faamaufaailogaina this record"], ["pe a uma ona", "whether but all then"], ["ou tautala atu ni", "I to talk some"], ["nai upu itiiti", "from word small"], ["e ala", "to way"], ["i le apoapoai atu ia te outou.", "in the apoapoai unto you"]]},
  {num:3,words:[["Faauta,", "behold"], ["ou te apoapoai atu ia te outou", "I apoapoai unto you"], ["pe a outou faitauina nei mea,", "whether but you (all) counted this thing"], ["pe afai", "whether if"], ["e tusa ai", "to according to"], ["ma le fingalo poto", "and the fingalo wise"], ["o le Atua ia", "of God to"], ["outou faitauina,", "you (all) counted"], ["ia outou manatua", "to you (all) remember"], ["le alofa mutimutivale tele", "the mercy great"], ["o le Alii", "the Lord"], ["i le fanauga", "in the children"], ["a tagata,", "but man"], ["mai i le foafoaga o Atamu", "from in the foafoaga of Adam"], ["e oo mai lava", "it shall come to pass from indeed"], ["i lalo seia oo", "in under until oo"], ["mai i le taimi", "from in the time"], ["o le a outou", "what you (all)"], ["maua ai nei mea,", "received this thing"], ["ma manatunatu", "and meditate"], ["i ai", "therein"], ["i o outou loto .", "in of you (all) heart"]]},
  {num:4,words:[["Ma pe", "and whether"], ["a outou maua nei mea,", "but you (all) received this thing"], ["ou te apoapoai atu ia te outou", "I apoapoai unto you"], ["ia outou ole atu", "to you (all) entreat"], ["i le Atua,", "in the God"], ["le Tamā Faavavau,", "the father everlasting"], ["i le suafa o Iesu Keriso,", "in the name of Jesus Christ"], ["pe ua", "whether"], ["le moni ea nei mea;", "the true to rise (as a diver to the sur- this thing"], ["ma afai tou ole atu", "and if second person plural entreat"], ["ma le loto faamaoni ,", "and the heart faithful"], ["ma le manatu moni", "and the thought true"], ["i ai,", "therein"], ["ma le faatuatua ia", "and the faith to"], ["Keriso,", "Christ"], ["o le a ia", "what to"], ["faaali mai", "revealed"], ["le moni o ia", "the true he"], ["mea ia te outou,", "thing unto you"], ["i le mana", "in the to get"], ["o le Agaga Paia.", "the Holy Spirit"]]},
  {num:5,words:[["Ma o le mana", "and the to get"], ["o le Agaga Paia", "the Holy Spirit"], ["e mafai ona", "could"], ["outou iloa ai", "you (all) known"], ["le moni o mea uma", "the true everything"], ["lava.", "indeed"]]},
  {num:6,words:[["Ma o soo", "and of frequently"], ["se mea", "a thing"], ["ua lelei,", "that it was good"], ["ua tonu", "right"], ["ma moni;", "and true"], ["o le mea lea,", "therefore"], ["e leai", "there is not"], ["se mea", "a thing"], ["ua lelei", "that it was good"], ["e faafitia", "to opposed"], ["le Keriso,", "the Christ"], ["ae tautino mai o loo soifua", "but to hang near the body from of live"], ["o ia.", "he"]]},
  {num:7,words:[["Ma e mafai ona", "and could"], ["outou iloa o loo soifua", "you (all) known of live"], ["o ia,", "he"], ["i le mana", "in the to get"], ["o le Agaga Paia;", "the Holy Spirit"], ["o le mea lea ou te apoapoai atu ai", "therefore I apoapoai"], ["ia te outou ia", "unto you to"], ["outou le faafitia", "you (all) the opposed"], ["le mana", "the to get"], ["o le Atua;", "of God"], ["aua e galue o ia", "for to till he"], ["e ala", "to way"], ["i le mana,", "in the to get"], ["e tusa ma le faatuatua", "according to the faith"], ["o le fanauga", "the children"], ["a tagata,", "but man"], ["e tutusa", "to equal"], ["i le aso", "in the day"], ["ma taeao,", "and morning"], ["ma le faavavau.", "and the everlasting"]]},
  {num:8,words:[["O lenei foi,", "this also"], ["ou te apoapoai atu ia te outou,", "I apoapoai unto you"], ["ou uso e,", "I brother by"], ["ia outou", "to you (all)"], ["le faafitia meaalofa", "the opposed gift"], ["a le Atua,", "of God"], ["ona e tele", "and to great"], ["i latou;", "them"], ["ma ua o", "and of"], ["mai i latou", "from them"], ["mai le Atua e", "from God by"], ["tasi.", "one"], ["Ma e eseese ala", "and to divided way"], ["e faatino ai ia", "by faatino to"], ["meaalofa;", "gift"], ["ae o le Atua e", "but of God by"], ["tasi o le", "one the"], ["na te galueaiina", "he galueaiina"], ["i soo", "in frequently"], ["se mea", "a thing"], ["ma i mea uma;", "and in all things"], ["ma ua tuuina", "and given"], ["mai nei meaalofa", "from this gift"], ["i tagata", "in man"], ["e ala", "to way"], ["i faaaliga", "in visions"], ["a le Agaga", "but the spirit"], ["o le Atua,", "of God"], ["ia latou manuia ai.", "to they peace"]]},
  {num:9,words:[["Aua faauta,", "for behold"], ["ua tuuina mai", "given from"], ["e le Agaga", "by the spirit"], ["o le Atua,", "of God"], ["i le tasi,", "in the one"], ["ina ia mafai ona", "that it might be and"], ["ia aoao atu", "to excellent"], ["le upu", "the word"], ["o le poto;", "the wise"]]},
  {num:10,words:[["Ma i le tasi,", "and in the one"], ["ina ia mafai ona", "that it might be and"], ["ia aoao atu", "to excellent"], ["le upu", "the word"], ["o le malamalama lea", "the light"], ["i le Agaga", "in the spirit"], ["e tasi;", "by one"]]},
  {num:11,words:[["Ma i le tasi,", "and in the one"], ["o le faatuatua tele naua;", "the faith great exceedingly"], ["ma i le tasi,", "and in the one"], ["o le meaalofa o faamalologa", "the gift of faamalologa"], ["e ala", "to way"], ["i le Agaga", "in the spirit"], ["e tasi;", "by one"]]},
  {num:12,words:[["O lenei foi,", "this also"], ["i le tasi,", "in the one"], ["ina ia mafai ona", "that it might be and"], ["ia faia vavega tetele;", "to made a wonder great"]]},
  {num:13,words:[["O lenei foi,", "this also"], ["i le tasi,", "in the one"], ["ina ia mafai ona", "that it might be and"], ["ia vavalo", "to prophesy"], ["e uiga", "concerning"], ["i mea uma;", "in all things"]]},
  {num:14,words:[["O lenei foi,", "this also"], ["i le tasi,", "in the one"], ["le vaaia o agelu", "the seen of angel"], ["ma agaga auauna", "and spirit servant"], ["mai;", "from"]]},
  {num:15,words:[["O lenei foi,", "this also"], ["i le tasi,", "in the one"], ["ituaiga uma o gagana eseese;", "tribe all of language divided"]]},
  {num:16,words:[["O lenei foi,", "this also"], ["i le tasi,", "in the one"], ["o le faaliliuga o gagana", "the faaliliuga of language"], ["ma ituaiga o gagana eseese.", "and tribe of language divided"]]},
  {num:17,words:[["Ma o nei meaalofa uma", "and of this gift all"], ["e oo mai", "it shall come to pass from"], ["e ala mai", "to way from"], ["i le Agaga o Keriso;", "in the spirit of Christ"], ["ma e oo", "and it shall come to pass"], ["mai i latou", "from them"], ["i tagata uma taitoatasi,", "in man all each one"], ["e tusa ma lona finagalo.", "according to his a chiefs will or desire"]]},
  {num:18,words:[["Ma ou te apoapoai atu ai", "and I apoapoai"], ["ia te outou,", "unto you"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["ia outou manatua o meaalofa lelei uma", "to you (all) remember of gift good all"], ["e mai ia Keriso.", "by from to Christ"]]},
  {num:19,words:[["Ma ou te fia apoapoai atu", "and I want to do something apoapoai"], ["ia te outou,", "unto you"], ["ou uso pele", "I brother dear"], ["e,", "by"], ["ia outou manatua", "to you (all) remember"], ["e tutusa o ia", "to equal he"], ["ananafi,", "ananafi"], ["le aso,", "the day"], ["ma le faavavau,", "and the everlasting"], ["ma o nei meaalofa uma", "and of this gift all"], ["ua ou tautala atu ai,", "I to talk"], ["ua faaleagaga,", "faaleagaga"], ["o le a le aveesea", "what the removed away"], ["lava,", "indeed"], ["pe o le a lava", "whether will indeed"], ["le umi", "the long"], ["e tu ai", "to stand"], ["le lalolagi,", "the earth"], ["ae nao", "but only"], ["le tusa ai", "the according to"], ["ma le", "and the"], ["le talitonu", "the believe"], ["o le fanauga", "the children"], ["a tagata.", "but man"]]},
  {num:20,words:[["O le mea lea,", "therefore"], ["e tatau ai", "it is fitting"], ["ona i ai", "and therein"], ["o le faatuatua ;", "the faith"], ["ma afai", "and if"], ["e tatau ona", "should"], ["i ai", "therein"], ["o le faatuatua", "the faith"], ["e tatau foi", "it is fitting also"], ["ona i ai", "and therein"], ["o le faamoemoe;", "the to expect"], ["ma afai", "and if"], ["e tatau ona", "should"], ["i ai", "therein"], ["o le faamoemoe,", "the to expect"], ["e tatau foi", "it is fitting also"], ["ona i ai", "and therein"], ["o le alofa mama.", "the love n"]]},
  {num:21,words:[["Ma e vagana ai", "and to except"], ["ua ia te outou", "unto you"], ["le alofa mama", "the love n"], ["e le mafai lava", "by the able indeed"], ["i se ala", "in a way"], ["ona faaolaina outou", "and saved alive you (all)"], ["i le malo", "in the government"], ["o le Atua;", "of God"], ["pe mafai foi", "whether able also"], ["ona faaolaina outou", "and saved alive you (all)"], ["i le malo", "in the government"], ["o le Atua", "of God"], ["pe afai", "whether if"], ["e le ia te outou", "by the unto you"], ["le faatuatua;", "the faith"], ["pe mafai foi e outou", "whether able also by you (all)"], ["pe afai", "whether if"], ["e leai so outou", "there is not so you (all)"], ["faamoemoe.", "to expect"]]},
  {num:22,words:[["Ma afai", "and if"], ["e leai so outou", "there is not so you (all)"], ["faamoemoe ua tatau ona", "to expect to wring out then"], ["outou lotovaivai;", "you (all) lotovaivai"], ["ma e oo", "and it shall come to pass"], ["mai le lotovaivai", "from the lotovaivai"], ["ona o le amioletonu.", "because of the wickedness"]]},
  {num:23,words:[["Ma sa fetalai moni Keriso", "and said true Christ"], ["i o tatou tamā:", "in of we (incl) father"], ["Afai e ia te outou", "if by him you (all)"], ["le faatuatua,", "the faith"], ["e mafai ona", "could"], ["outou faia o mea uma", "you (all) made everything"], ["e tatau ia te au.", "it is fitting/ought unto me"]]},
  {num:24,words:[["Ma ou te tautala atu nei", "and I to talk this"], ["i tuluiga uma", "in anointing all"], ["o le lalolagi—afai", "the lalolagi—afai"], ["e oo mai", "it shall come to pass from"], ["le aso", "the day"], ["e aveesea ai", "to removed away"], ["le mana", "the to get"], ["ma meaalofa", "and gift"], ["a le Atua", "of God"], ["mai totonu o outou,", "from inside of you (all)"], ["o le a faapea ona", "what thus then"], ["o le", "the"], ["le talitonu.", "the believe"]]},
  {num:25,words:[["Ma oi talofa", "and wo"], ["i le fanauga", "in the children"], ["a tagata", "but man"], ["pe afai", "whether if"], ["o le tulaga lea;", "the matter"], ["ona o le a leai", "because of the but no"], ["se tasi", "a one"], ["i totonu o outou", "in the midst of you (all)"], ["e faia", "to made"], ["le lelei,", "the good"], ["e leai,", "there is not"], ["e leai lava", "there is not indeed"], ["se tasi.", "a one"], ["Aua afai e", "for if by"], ["i ai", "therein"], ["se tasi", "a one"], ["i totonu o outou", "in the midst of you (all)"], ["e faia", "to made"], ["le lelei,", "the good"], ["e galue o ia", "to till he"], ["i le mana", "in the to get"], ["ma meaalofa", "and gift"], ["a le Atua.", "of God"]]},
  {num:26,words:[["Ma oi talofa ia te", "and wo unto"], ["i latou", "them"], ["o e latou te aveese nei mea", "who they removed away this thing"], ["ma feoti,", "and feoti"], ["ona latou te oti ia", "and they die to"], ["latou agasala ,", "they sin"], ["ma e le mafai ona", "and by the able then"], ["faaolaina i latou", "saved alive them"], ["i le malo", "in the government"], ["o le Atua;", "of God"], ["ma ou te tautala atu lenei mea", "and I to talk this thing"], ["e tusa ma afioga", "according to a word"], ["a Keriso;", "of Christ"], ["ma ou te", "and I"], ["le pepelo lava.", "the false indeed"]]},
  {num:27,words:[["Ma ou te apoapoai atu", "and I apoapoai"], ["ia te outou ia", "unto you to"], ["outou manatua nei mea;", "you (all) remember this thing"], ["ona e vave", "and to quick"], ["ona oo mai", "and came"], ["o le taimi", "the time"], ["o le a outou", "what you (all)"], ["iloa ai ou te", "known I"], ["le pepelo,", "the false"], ["aua o le a outou", "for will you (all)"], ["vaai ia te au", "to look at unto me"], ["i le pa faamasino", "in the a wall a judge"], ["a le Atua;", "of God"], ["ma o le a fetalai", "and will said"], ["mai le Alii", "from the Lord"], ["le Atua ia te outou:", "God unto you"], ["Ou te lei alaga atu ea", "I not cry to rise (as a diver to the sur-"], ["ia te outou au", "unto you I"], ["upu ,", "word"], ["ia sa tusia", "to written"], ["e lenei tagata,", "by this man"], ["e pei o se tasi", "to like a one"], ["ua alaga mai", "cry from"], ["e ua oti,", "the dead"], ["ioe,", "yea"], ["e pei lava", "to like indeed"], ["o se tasi", "a one"], ["ua tautala mai", "to talk from"], ["i fafo mai", "in outside from"], ["i le efuefu ?", "in the dust"]]},
  {num:28,words:[["Ou te tautino atu nei mea", "I to hang near the body this thing"], ["i le faataunuuina o valoaga.", "in the fulfilled of a prediction"], ["Faauta foi,", "and behold"], ["o le a tulei", "what to push"], ["mai i latou", "from them"], ["mai le fofoga", "from the face"], ["o le Atua tumau-faavavau;", "of God tumau-faavavau"], ["ma o le a uisa atu lana afioga", "and will uisa his a word"], ["mai lea tupulaga", "from generation"], ["i lea tupulaga.", "in generation"]]},
  {num:29,words:[["Ma o le a faaali atu", "and will revealed"], ["e le Atua ia te outou,", "God unto you"], ["ua moni mea", "true thing"], ["ua ou tusia.", "I written"]]},
  {num:30,words:[["Ma ou te toe apoapoai atu", "and I again apoapoai"], ["ia te outou,", "unto you"], ["ia outou", "to you (all)"], ["o mai ia Keriso,", "from to Christ"], ["ma taofimau", "and taofimau"], ["i meaalofa lelei uma,", "in gift good all"], ["ma aua", "and for"], ["le pai atu", "the pie"], ["i le meaalofa leaga,", "in the gift evil"], ["po o le mea", "night the thing"], ["ua le mama.", "not n"]]},
  {num:31,words:[["Ma ia ala", "and to way"], ["mai,", "from"], ["ma tulai mai", "and arose up from"], ["i le efuefu,", "in the dust"], ["Ierusalema e;", "Jerusalem by"], ["ioe,", "yea"], ["ma ofu ou ofu matagofie,", "and garment I garment beautiful"], ["le afafine", "the daughter"], ["e o Siona ;", "by of Zion"], ["ma faamalolosi ou siteki", "and faamalolosi I siteki"], ["ma faalautetele ou tuaoi", "and faalautetele I border"], ["e faavavau,", "forever/everlasting"], ["ina ia le toe faafelilonaiina oe,", "so that the again faafelilonaiina you"], ["ina ia mafai ona", "that it might be and"], ["faataunuuina o feagaiga", "fulfilled of covenant"], ["a le Tamā Faavavau", "but the father everlasting"], ["na faia e ia", "he made"], ["ia te oe,", "unto you"], ["le aiga", "the family"], ["e o Isaraelu.", "by of Israel"]]},
  {num:32,words:[["Ioe,", "yea"], ["o mai ia Keriso,", "from to Christ"], ["ma faaatoatoaina ia te ia,", "and faaatoatoaina to him"], ["ma faafiti outou lava", "and denied you (all) indeed"], ["mai mea uma", "from all things"], ["e le faaleatua;", "by the faaleatua"], ["ma afai tou te faafiti outou", "and if second person plural denied you (all)"], ["lava mai mea", "indeed from thing"], ["e le faaleatua uma,", "by the faaleatua all"], ["ma alolofa", "and alolofa"], ["i le Atua", "in the God"], ["ma o outou manatu", "and of you (all) thought"], ["atoa,", "together with"], ["mafaufau,", "think"], ["ma le malosi", "and the strong"], ["atoa,", "together with"], ["ona lava lea", "and indeed"], ["o lona alofa tunoa", "his/her grace"], ["mo outou,", "for you"], ["ma o lona alofa tunoa", "and his grace"], ["e mafai ai", "it is possible"], ["ona outou atoatoa ia", "and you (all) completely to"], ["Keriso;", "Christ"], ["ma afai tou te atoatoa", "and if second person plural completely"], ["ia Keriso", "to Christ"], ["e ala", "to way"], ["i le alofa tunoa", "in the grace"], ["o le Atua,", "of God"], ["e leai", "there is not"], ["se ala", "a way"], ["e mafai ai", "it is possible"], ["ona outou faafitia", "and you (all) opposed"], ["le mana", "the to get"], ["o le Atua.", "of God"]]},
  {num:33,words:[["Ma ou te toe fai atu,", "and I again said to"], ["afai tou te atoatoa ia", "if second person plural completely to"], ["Keriso e ala", "Christ to way"], ["i le alofa tunoa", "in the grace"], ["o le Atua,", "of God"], ["ma lē faafitia lona mana,", "and not opposed his to get"], ["ona faapaiaina lea o outou", "and consecrated of you (all)"], ["ia Keriso", "to Christ"], ["i le alofa tunoa", "in the grace"], ["o le Atua,", "of God"], ["e ala", "to way"], ["i le faamaligiina", "in the faamaligiina"], ["o le toto o Keriso,", "the blood of Christ"], ["lea ua", "lea ua"], ["i ai", "therein"], ["i le feagaiga", "in the covenant"], ["a le Tamā", "but the father"], ["mo le faamagaloina o", "for the forgiven of"], ["a outou agasala,", "but you (all) sin"], ["ina ia outou paia ,", "so that you (all) holy"], ["ua aunoa", "without"], ["ma se ila.", "and a spot"]]},
  {num:34,words:[["Ma o lenei ou te fai atu", "and now I said to"], ["ia te outou uma,", "unto you all"], ["tofa ia.", "determination to"], ["Ua lata", "near"], ["ona ou alu atu", "and I go away"], ["e malolo", "to rest"], ["i le parataiso", "in the paradise"], ["o le Atua,", "of God"], ["seia toe faatasia lou agaga", "until again faatasia your spirit"], ["ma lou tino,", "and your body"], ["ma aumai au", "and bring I"], ["i le ea", "in the to rise (as a diver to the sur-"], ["ma le manumalo,", "and the overcome"], ["e feiloai", "by feiloai"], ["ma outou", "with you"], ["i luma", "in before"], ["o le pa faamasino logomalie", "the a wall a judge logomalie"], ["a le Ieova silisili,", "but the the LORD very much"], ["le Faamasino Faavavau o", "the a judge everlasting of"], ["e o ola", "by of life"], ["ma e", "and by"], ["ua oti.", "die"], ["Amene.", "amen"], ["Ua I'u", "attain"]]},
];
renderVerseSet(_mr_ch_10_Verses, 'mr-ch10-verses');

})();