(function() {
var mr_ch_1_Verses = [
  {num:1,words:[["O Lenei o au o Moronae ,", "Now I,"], ["ina ua uma ona ou faia o le faaiuga o le otootoga o le tala o le nuu o Iareto,", "Moroni,"], ["sa ou manatu o le a ou le toe tusia ni isi mea faaopoopo,", "after having made an end of abridging the account of the people of Jared, I had supposed not to have written more,"], ["peitai ou te lei oti lava;", "but I have not as yet perished;"], ["ma ou te le faailoa atu au lava i sa Lamanā nei o latou faaumatia au.", "and I make not myself known to the Lamanites lest they should destroy me."]]},
  {num:2,words:[["Aua faauta,", "For behold,"], ["ua matua malolosi tele a latou taua i totonu o i latou lava;", "their wars are exceedingly fierce among themselves;"], ["ma ona o lo latou ita ua latou fasiotia ai sa Nifaē uma o e e le faafitia le Keriso.", "and because of their hatred they put to death every Nephite that will not deny the Christ."]]},
  {num:3,words:[["Ma o au,", "And I,"], ["o Moronae,", "Moroni,"], ["ou te le faafitia le Keriso;", "will not deny the Christ;"], ["o le mea lea,", "wherefore,"], ["ou te fealuai solo ai i soo se mea e mafai ona ou alu i ai mo le puipuiga o lou lava ola.", "I wander whither soever I can for the safety of mine own life."]]},
  {num:4,words:[["O le mea lea,", "Wherefore,"], ["ou te tusia ai ni isi mea faaopoopo itiiti,", "I write a few more things,"], ["e le tusa ma le mea na ou manatu i ai;", "contrary to that which I had supposed;"], ["ona sa ou manatu o le a ou le toe tusia ni isi mea faaopoopo;", "for I had supposed not to have written any more;"], ["ae o le a ou tusia ni nai faaopoopo itiiti,", "but I write a few more things,"], ["atonu o le a aoga i ou uso,", "that perhaps they may be of worth unto my brethren,"], ["o sa Lamanā,", "the Lamanites,"], ["i se aso i le lumanai,", "in some future day,"], ["e tusa ai ma le finagalo o le Alii.", "according to the will of the Lord."]]},
];
renderVerseSet(mr_ch_1_Verses, 'mr-ch1-verses');

var mr_ch_2_Verses = [
  {num:1,words:[["O afioga a Keriso,", "The words of Christ,"], ["na ia fetalai i ona soo ,", "which he spake unto his disciples,"], ["le toasefululua o e na ia filifilia,", "the twelve whom he had chosen,"], ["ao faaee ona aao i o latou luga—", "as he laid his hands upon them—"]]},
  {num:2,words:[["Ma sa ia valaau i latou i o latou igoa,", "And he called them by name,"], ["ua fetalai:", "saying:"], ["Ia outou valaau atu i le Tamā i lou igoa,", "Ye shall call on the Father in my name,"], ["i le tatalo faatauanau;", "in mighty prayer;"], ["ma a uma ona outou faia o lenei mea,", "and after ye have done this ye shall have power that to him upon whom ye shall lay your hands,"], ["o le a outou maua le mana tou te tuu atu ai le Agaga Paia ia te ia o le o le a faaee atu i ai o outou lima i ona luga;", "ye shall give the Holy Ghost;"], ["ma o lou igoa ia outou tuuina atu ai,", "and in my name shall ye give it,"], ["ona sa faapea ona faia e au aposetolo.", "for thus do mine apostles."]]},
  {num:3,words:[["O lenei sa fetalai mai e Keriso ia te i latou ia afioga i le taimi o lona faatoa afio mai;", "Now Christ spake these words unto them at the time of his first appearing;"], ["ma sa le faalogoina e le motu o tagata,", "and the multitude heard it not,"], ["ae sa faalogoina e le au soo;", "but the disciples heard it;"], ["ma o le toatele o i latou o e na faaee atu i ai o latou lima,", "and on as many as they laid their hands,"], ["na taia i le Agaga Paia.", "fell the Holy Ghost."]]},
];
renderVerseSet(mr_ch_2_Verses, 'mr-ch2-verses');

var mr_ch_3_Verses = [
  {num:1,words:[["O le ala na faauu ai faitaulaga ma aoao e le au soo,", "The manner which the disciples, who were called the elders of the church,"], ["o e na taua o toeaina o le ekalesia—", "ordained priests and teachers—"]]},
  {num:2,words:[["Ina ua uma ona latou tatalo atu i le Tamā i le suafa o Keriso,", "After they had prayed unto the Father in the name of Christ,"], ["sa latou faaee o latou lima i o latou luga,", "they laid their hands upon them,"], ["ma fai atu:", "and said:"]]},
  {num:3,words:[["I le suafa o Iesu Keriso ou te faauuina ai oe e avea o se faitaulaga,", "In the name of Jesus Christ I ordain you to be a priest,"], ["(ae afai o se aoao,", "(or,"], ["ou te faauuina ai oe e avea o se aoao) e talai atu le salamo ma le faamagaloina o agasala e ala ia Iesu Keriso,", "if he be a teacher) I ordain you to be a teacher, to preach repentance and remission of sins through Jesus Christ,"], ["i le tumau i le faatuatua i lona suafa e oo i le iuga.", "by the endurance of faith on his name to the end."], ["Amene.", "Amen."]]},
  {num:4,words:[["Ma o le ala lenei sa latou faauu ai faitaulaga ma aoao,", "And after this manner did they ordain priests and teachers,"], ["e tusa ma meaalofa ma valaauga a le Atua i tagata;", "according to the gifts and callings of God unto men;"], ["ma sa latou faauuina i latou i le mana o le Agaga Paia,", "and they ordained them by the power of the Holy Ghost,"], ["lea sa ia te i latou.", "which was in them."]]},
];
renderVerseSet(mr_ch_3_Verses, 'mr-ch3-verses');

var mr_ch_4_Verses = [
  {num:1,words:[["O le ala e faamanuia ma tufa atu ai e o latou toeaina ma faitaulaga le tino ma le toto o Keriso i le ekalesia;", "The manner of their elders and priests administering the flesh  and blood of Christ unto  the church;"], ["ma sa latou faia e tusa ma poloaiga a Keriso;", "and they administered it according to the commandments of Christ;"], ["o le mea lea ua matou iloa ai ua sao le ala;", "wherefore we know the manner to be true;"], ["ma o le toeaina po o le faitaulaga na faia—", "and the elder or priest did minister it—"]]},
  {num:2,words:[["Ma sa latou tootutuli i lalo faatasi ma le ekalesia,", "And they did kneel down with the church,"], ["ma tatalo atu i le Tamā i le suafa o Keriso,", "and pray to the Father in the name of Christ,"], ["ua fai atu:", "saying:"]]},
  {num:3,words:[["Le Atua e,", "O God,"], ["le Tamā Faavavau,", "the Eternal Father,"], ["matou te ole atu ia te oe i le suafa o lou Alo,", "we ask thee in the name of thy Son,"], ["o Iesu Keriso,", "Jesus Christ,"], ["ia e faamanuiaina ma faapaiaina lenei areto i agaga o i latou uma o e e fetagofi i ai;", "to bless and sanctify this bread to the souls of all those who partake of it;"], ["ina ia latou taumamafa i le faamanatuina o le tino o lou Alo,", "that they may eat in remembrance of the body of thy Son,"], ["ma molimau atu ia te oe,", "and witness unto thee,"], ["le Atua e,", "O God,"], ["le Tamā Faavavau,", "the Eternal Father,"], ["latou te loto ina e ave i o latou luga le suafa o lou Alo,", "that they are willing to take upon them the name of thy Son,"], ["ma manatua pea o ia,", "and always remember him,"], ["ma tausi i ana poloaiga ua ia tuuina mai ia te i latou,", "and keep his commandments which he hath given them,"], ["ina ia latou maua pea lona Agaga e faatasi ma i latou. Amene.", "that they may always have his Spirit to be with them. Amen."]]},
];
renderVerseSet(mr_ch_4_Verses, 'mr-ch4-verses');

var mr_ch_5_Verses = [
  {num:1,words:[["O le ala e faamanuia ai le uaina—Faauta,", "The manner of administering the wine—Behold,"], ["sa latou ave le ipu,", "they took the cup,"], ["ma fai atu:", "and said:"]]},
  {num:2,words:[["Le Atua e,", "O God,"], ["le Tamā Faavavau,", "the Eternal Father,"], ["matou te ole atu ia te oe i le suafa o lou Alo,", "we ask thee,"], ["o Iesu Keriso,", "in the name of thy Son,"], ["ia e faamanuiaina ma faapaiaina lenei uaina i agaga o i latou uma o e e feinu ai,", "Jesus Christ,"], ["ina ia latou faia i le faamanatuina o le toto o lou Alo,", "to bless and sanctify this wine to the souls of all those who drink of it,"], ["sa faamaligiina mo i latou;", "that they may do it in remembrance of the blood of thy Son, which was shed for them;"], ["ina ia latou molimau atu ia te oe,", "that they may witness unto thee,"], ["le Atua e,", "O God,"], ["le Tamā Faavavau,", "the Eternal Father,"], ["latou te manatua pea o ia,", "that they do always remember him,"], ["ina ia latou maua lona Agaga e faatasi ma i latou.", "that they may have his Spirit to be with them."], ["Amene.", "Amen."]]},
];
renderVerseSet(mr_ch_5_Verses, 'mr-ch5-verses');

var mr_ch_6_Verses = [
  {num:1,words:[["Ma o lenei ou te tautala atu e uiga i le papatisoga . Faauta,", "And now I speak concerning baptism. Behold,"], ["sa papatisoina toeaina,", "elders,"], ["faitaulaga,", "priests,"], ["ma aoao;", "and teachers were baptized;"], ["ma sa le papatisoina i latou vagana ai ua latou fua mai fua e tatau ai e iloa ai ua latou agavaa .", "and they were not baptized save they brought forth fruit meet that they were worthy of it."]]},
  {num:2,words:[["Pe na latou talia foi soo se tasi i le papatisoga vagana ai ua latou o mai i luma ma le loto momomo ma le agaga salamo,", "Neither did they receive any unto baptism save they came forth with a broken heart and a contrite spirit,"], ["ma molimau mai i le ekalesia ua latou salamo faamaoni ia latou agasala uma.", "and witnessed unto the church that they truly repented of all their sins."]]},
  {num:3,words:[["Ma sa leai se tasi na talia i le papatisoga vagana ai ua latou ave i o latou luga le suafa o Keriso,", "And none were received unto baptism save they took upon them the name of Christ,"], ["ma ua i ai le mauai e auauna atu ia te ia e oo i le iuga.", "having a determination to serve him to the end."]]},
  {num:4,words:[["Ma ina ua uma ona taliaina o i latou i le papatisoga,", "And after they had been received unto baptism,"], ["ma galueaiina ma faamamaina e le mana o le Agaga Paia,", "and were wrought upon and cleansed by the power of the Holy Ghost,"], ["sa faitauina i latou i totonu o tagata o le ekalesia a Keriso;", "they were numbered among the people of the church of Christ;"], ["ma sa ave o latou igoa ina ia manatua i latou ma tausia i le afioga lelei a le Atua,", "and their names were taken,"], ["e faatutumau ai i latou i le ala sao,", "that they might be remembered and nourished by the good word of God,"], ["e faatutumau ai i latou ia mataala e le aunoa i le tatalo,", "to keep them in the right way,"], ["ua nao galuega a Keriso,", "to keep them continually watchful unto prayer,"], ["o le o le pogai ma le iuga o lo latou faatuatua,", "relying alone upon the merits of Christ,"], ["ua faalagolago i ai.", "who was the author and the finisher of their faith."]]},
  {num:5,words:[["Ma sa potopoto soo faatasi le ekalesia , e anapopogi ma tatalo,", "And the church did meet together oft,"], ["ma talatalanoa,", "to fast and to pray,"], ["o le tasi i le tasi, e uiga i le uelefea o o latou agaga.", "and to speak one with another concerning the welfare of their souls."]]},
  {num:6,words:[["Ma sa latou potopoto soo faatasi e taumamafa i le areto ma le uaina,", "And they did meet together oft to partake of bread and wine,"], ["i le faamanatuina o le Alii o Iesu.", "in remembrance of the Lord Jesus."]]},
  {num:7,words:[["Ma sa latou tausisi ma le faaeteete ina ia leai se amioletonu e i totonu o i latou;", "And they were strict to observe that there should be no iniquity among them;"], ["ma o soo se tasi e maua ua ia faia le amioletonu,", "and whoso was found to commit iniquity,"], ["ma e toatolu molimau o le ekalesia e tausalaina ai i latou i luma o toeaina ,", "and three witnesses of the church did condemn them before the elders,"], ["ma afai latou te le salamo,", "and if they repented not,"], ["ma le faatoese,", "and confessed not,"], ["sa tineia ese o latou igoa,", "their names were blotted out,"], ["ma sa le faitauina i latou i totonu o tagata o Keriso.", "and they were not numbered among the people of Christ."]]},
  {num:8,words:[["Ae o soo se taimi sa latou salamo ai ma saili le faamagaloga,", "But as oft as they repented and sought forgiveness,"], ["ma le faamoemoe faamaoni,", "with real intent,"], ["sa faamagaloina i latou.", "they were forgiven."]]},
  {num:9,words:[["Ma sa taitaia a latou sauniga e le ekalesia e tusa ma galuega a le Agaga,", "And their meetings were conducted by the church after the manner of the workings of the Spirit,"], ["ma le mana o le Agaga Paia;", "and by the power of the Holy Ghost;"], ["ona o soo se mea na taitaia ai i latou e Agaga Paia e talai,", "for as the power of the Holy Ghost led them whether to preach,"], ["pe apoapoai,", "or to exhort,"], ["pe tatalo,", "or to pray,"], ["pe aioi,", "or to supplicate,"], ["pe pepese atu ai,", "or to sing,"], ["sa faapea lava ona faia.", "even so it was done."]]},
];
renderVerseSet(mr_ch_6_Verses, 'mr-ch6-verses');

var mr_ch_7_Verses = [
  {num:1,words:[["Ma o lenei,", "And now I,"], ["o au,", "Moroni,"], ["o Moronae, ou te tusia nai upu itiiti a lou tamā,", "write a few of the words of my father Mormon,"], ["o Mamona,", "which he spake concerning faith,"], ["ia na ia tautala i ai e uiga i le faatuatua ,", "hope,"], ["faamoemoe, ma le alofa mama;", "and charity;"], ["ona sa faapenei le ala sa ia tautala atu ai i le nuu,", "for after this manner did he speak unto the people,"], ["ao ia aoao atu ia te i latou i le sunako lea na latou fausia mo se nofoaga e tapuai ai.", "as he taught them in the synagogue which they had built for the place of worship."]]},
  {num:2,words:[["Ma o lenei,", "And now I,"], ["o au,", "Mormon,"], ["o Mamona, ou te tautala atu ia te outou,", "speak unto you,"], ["ou uso pele e;", "my beloved brethren;"], ["ma ona o le alofa tunoa o le Atua,", "and it is by the grace of God the Father,"], ["le Tamā,", "and our Lord Jesus Christ,"], ["ma lo tatou Alii o Iesu Keriso, ma lona finagalo paia,", "and his holy will,"], ["ona o le meaalofa o lana valaauga ia te au,", "because of the gift of his calling unto me,"], ["lea ua faatagaina ai au ou te tautala atu ia te outou i lenei taimi.", "that I am permitted to speak unto you at this time."]]},
  {num:3,words:[["O le mea lea,", "Wherefore,"], ["ou te fia tautala atu ia te outou o e o le ekalesia,", "I would speak unto you that are of the church,"], ["outou o soo fifilemu o Keriso,", "that are the peaceable followers of Christ,"], ["ma outou ua outou maua se faamoemoe ua lava e mafai ai ona outou ulu atu i le malologa o le Alii,", "and that have obtained a sufficient hope by which ye can enter into the rest of the Lord,"], ["mai le taimi nei i luma seia oo ina outou malolo faatasi ma ia i le lagi.", "from this time henceforth until ye shall rest with him in heaven."]]},
  {num:4,words:[["Ma o lenei ou uso e,", "And now my brethren,"], ["ua ou matauina nei mea ia te outou ona o lo outou savavali ma le filemu faatasi ma le fanauga a tagata.", "I judge these things of you because of your peaceable walk with the children of men."]]},
  {num:5,words:[["Aua ou te manatua le afioga a le Atua ua fetalai mai o a latou galuega tou te iloa ai i latou;", "For I remember the word of God,"], ["aua afai ua lelei a latou galuega,", "which saith by their works ye shall know them; for if their works be good,"], ["ua lelei foi i latou.", "then they are good also."]]},
  {num:6,words:[["Aua faauta,", "For behold,"], ["na fetalai mai le Atua o se tagata ua leaga e le mafai ona fai e ia se mea ua lelei;", "God hath said a man being evil cannot do that which is good;"], ["aua afai na te ofo atu se meaalofa,", "for if he offereth a gift,"], ["pe tatalo atu i le Atua,", "or prayeth unto God,"], ["vagana ai e faia e ia ma le loto faamaoni i ai e leai se aoga ia te ia.", "except he shall do it with real intent it profiteth him nothing."]]},
  {num:7,words:[["Aua faauta,", "For behold,"], ["e le faitauina ia te ia lena mea mo le amiotonu.", "it is not counted unto him for righteousness."]]},
  {num:8,words:[["Aua faauta,", "For behold,"], ["afai e avatu e se tagata ua leaga se meaalofa,", "if a man being evil giveth a gift,"], ["e faia e ia ma le toai ;", "he doeth it grudgingly;"], ["o le mea lea e faitau tutusa ai ia te ia e pei lava na ia taofia le meaalofa;", "wherefore it is counted unto him the same as if he had retained the gift;"], ["o le mea lea e faitau leaga ai o ia i luma o le Atua.", "wherefore he is counted evil before God."]]},
  {num:9,words:[["Ma e faapea foi ona faitau leaga i se tagata,", "And likewise also is it counted evil unto a man,"], ["pe afai e tatalo atu o ia ae ua le i ai ma le faamaoni o le loto;", "if he shall pray and not with real intent of heart;"], ["ioe,", "yea,"], ["ma ua leai se aoga ia te ia,", "and it profiteth him nothing,"], ["ona e le talia e le Atua se ua faapena.", "for God receiveth none such."]]},
  {num:10,words:[["O le mea lea,", "Wherefore,"], ["e le mafai e se tagata ua leaga ona faia le mea ua lelei;", "a man being evil cannot do that which is good;"], ["pe avatu foi e ia se meaalofa lelei.", "neither will he give a good gift."]]},
  {num:11,words:[["Aua faauta,", "For behold,"], ["e le mafai e se puna oona ona puna mai i vai lelei;", "a bitter fountain cannot bring forth good water;"], ["pe mafai foi e se puna lelei ona puna mai i vai oona;", "neither can a good fountain bring forth bitter water;"], ["o le mea lea,", "wherefore,"], ["o se tagata ua avea o se auauna a le tiapolo e le mafai ona mulimuli ia Keriso;", "a man being a servant of the devil cannot follow Christ;"], ["ma afai e mulimuli o ia ia Keriso e le mafai ona avea o ia o se auauna a le tiapolo.", "and if he follow Christ he cannot be a servant of the devil."]]},
  {num:12,words:[["O le mea lea,", "Wherefore,"], ["o mea uma ua lelei e mai le Atua;", "all things which are good cometh of God;"], ["ma o le mea ua leaga e mai le tiapolo;", "and that which is evil cometh of the devil;"], ["ona o le tiapolo o se fili i le Atua,", "for the devil is an enemy unto God,"], ["ma ua faasagatau pea ia te ia,", "and fighteth against him continually,"], ["ma ua valaau ma faatosina tagata i le agasala ,", "and inviteth and enticeth to sin,"], ["ma ia latou faia pea le mea leaga.", "and to do that which is evil continually."]]},
  {num:13,words:[["Ae faauta,", "But behold,"], ["o le mea ua mai le Atua,", "that which is of God inviteth and enticeth to do good continually;"], ["e valaau ma faatosina mai ia faia mea lelei e le aunoa;", "wherefore,"], ["o le mea lea, o mea uma e valaau mai ma faatosina mai ia faia mea lelei,", "every thing which inviteth and enticeth to do good,"], ["ma alofa i le Atua,", "and to love God,"], ["ma auauna atu ia te ia,", "and to serve him,"], ["ua musuia e le Atua.", "is inspired of God."]]},
  {num:14,words:[["O le mea lea,", "Wherefore,"], ["ia outou faaeteete,", "take heed,"], ["ou uso pele e,", "my beloved brethren,"], ["ina ia outou le faamasino le mea ua leaga o se mea mai le Atua,", "that ye do not judge that which is evil to be of God,"], ["po o le mea ua lelei ma mai le Atua o se mea mai le tiapolo.", "or that which is good and of God to be of the devil."]]},
  {num:15,words:[["Aua faauta,", "For behold,"], ["ou uso e,", "my brethren,"], ["ua tuu mai ia te outou ia outou faamasino ,", "it is given unto you to judge,"], ["ina ia outou iloa le lelei mai le leaga;", "that ye may know good from evil;"], ["ma o le ala e faamasino ai ua manino,", "and the way to judge is as plain,"], ["ina ia mafai ona outou iloa ma se malamalama atoatoa,", "that ye may know with a perfect knowledge,"], ["e pei o le malamalama o le ao mai le pouliuli o le po.", "as the daylight is from the dark night."]]},
  {num:16,words:[["Aua faauta,", "For behold,"], ["ua tuuina mai i tagata taitoatasi le Agaga o Keriso,", "the Spirit of Christ is given to every man,"], ["ina ia mafai ona iloa e ia le lelei mai le leaga;", "that he may know good from evil;"], ["o le mea lea,", "wherefore,"], ["ou te faaali atu ai ia te outou le ala e faamasino ai;", "I show unto you the way to judge;"], ["ona o mea uma e valaau mai ia fai le lelei,", "for every thing which inviteth to do good,"], ["ma faatauanau mai ia talitonu ia Keriso,", "and to persuade to believe in Christ,"], ["ua auina mai i le mana ma le meaalofa a Keriso;", "is sent forth by the power and gift of Christ;"], ["o le mea lea e mafai ai ona outou iloa ma le malamalama atoatoa ua mai le Atua.", "wherefore ye may know with a perfect knowledge it is of God."]]},
  {num:17,words:[["Ae o soo se mea e faatauanauina tagata ia latou faia le leaga ,", "But whatsoever thing persuadeth men to do evil,"], ["ma ia le talitonu ia Keriso,", "and believe not in Christ,"], ["ma faafiti o ia,", "and deny him,"], ["ma ia le auauna i le Atua,", "and serve not God,"], ["ona outou iloa lea ma le malamalama atoatoa ua mai le tiapolo;", "then ye may know with a perfect knowledge it is of the devil;"], ["ona o le ala lea e galue ai le tiapolo,", "for after this manner doth the devil work,"], ["aua e le faatauanauina e ia se tagata ia faia le lelei,", "for he persuadeth no man to do good,"], ["e leai,", "no,"], ["e leai lava se tasi;", "not one;"], ["pe faia foi e ana agelu;", "neither do his angels;"], ["pe faia foi e i latou o e latou te tuu atu i latou lava ia te ia.", "neither do they who subject themselves unto him."]]},
  {num:18,words:[["Ma o lenei,", "And now,"], ["ou uso e,", "my brethren,"], ["ina ua vaai ua outou iloa le malamalama tou te faamasino ai,", "seeing that ye know the light by which ye may judge,"], ["o le malamalama lea o Keriso,", "which light is the light of Christ,"], ["vaai ia outou le faamasino sese;", "see that ye do not judge wrongfully;"], ["aua o le faamasinoga lava lea tou te faamasino atu ai o le a faamasino ai foi outou.", "for with that same judgment which ye judge ye shall also be judged."]]},
  {num:19,words:[["O le mea lea,", "Wherefore,"], ["ou te aioi atu ia te outou,", "I beseech of you,"], ["uso e,", "brethren,"], ["ia outou sailiili ma le filiga i le malamalama o Keriso ina ia outou iloa le lelei mai le leaga;", "that ye should search diligently in the light of Christ that ye may know good from evil;"], ["ma afai tou te taofi mau i mea lelei uma,", "and if ye will lay hold upon every good thing,"], ["ma lē tauleagaina ia mea,", "and condemn it not,"], ["o le a avea moni outou ma ni fanau a Keriso.", "ye certainly will be a child of Christ."]]},
  {num:20,words:[["Ma o lenei,", "And now,"], ["ou uso e,", "my brethren,"], ["e mafai faapefea ona outou taofi mau i mea lelei uma?", "how is it possible that ye can lay hold upon every good thing?"]]},
  {num:21,words:[["Ma o lenei ua ou oo mai nei i lena faatuatua,", "And now I come to that faith,"], ["lea na ou fai atu o le a ou tautala atu ai;", "of which I said I would speak;"], ["ma o le a ou tau atu ia te outou le auala e mafai ai ona outou taofi mau i mea lelei uma.", "and I will tell you the way whereby ye may lay hold on every good thing."]]},
  {num:22,words:[["Aua faauta,", "For behold,"], ["ona ua silafia e le Atua mea uma,", "God knowing all things,"], ["ona ua mai le faavavau-tumau i le faavavau-tumau,", "being from everlasting to everlasting,"], ["faauta,", "behold,"], ["sa ia auina mai agelu e auauna mai i le fanauga a tagata,", "he sent angels to minister unto the children of men,"], ["e faaali mai e uiga i le afio mai o Keriso;", "to make manifest concerning the coming of Christ;"], ["ma o Keriso o le a ala mai ai mea lelei uma.", "and in Christ there should come every good thing."]]},
  {num:23,words:[["Ma sa tautino mai foi e le Atua i perofeta,", "And God also declared unto prophets,"], ["i lona lava fofoga,", "by his own mouth,"], ["o le a afio mai Keriso.", "that Christ should come."]]},
  {num:24,words:[["Faauta foi,", "And behold,"], ["e tele auala sa i ai na ia faaali mai ai mea i le fanauga a tagata,", "there were divers ways that he did manifest things unto the children of men,"], ["o ni mea sa lelei;", "which were good;"], ["ma o mea uma ua lelei ua mai ia Keriso;", "and all things which are good cometh of Christ;"], ["a na le o lea po ua pauu tagata,", "otherwise men were fallen,"], ["ma ua leai se mea lelei e mafai ona oo mai ia te i latou.", "and there could no good thing come unto them."]]},
  {num:25,words:[["O le mea lea,", "Wherefore,"], ["e ala i le auauna mai o agelu ,", "by the ministering of angels,"], ["ma afioga uma na tulei mai i le fofoga o le Atua,", "and by every word which proceeded forth out of the mouth of God,"], ["sa amata ona faaaoga ai e tagata le faatuatua ia Keriso; ma sa faapea,", "men began to exercise faith in Christ;"], ["e ala i le faatuatua,", "and thus by faith,"], ["ona latou taofi mau i mea lelei uma;", "they did lay hold upon every good thing;"], ["ma sa faapea ona i ai seia oo mai i le afio mai o Keriso.", "and thus it was until the coming of Christ."]]},
  {num:26,words:[["Ma ina ua uma ona afio mai o ia,", "And after that he came men also were saved by faith in his name;"], ["sa faaolaina foi tagata i le faatuatua i lona suafa; ma e ala i le faatuatua,", "and by faith,"], ["na avea ai i latou ma atalii o le Atua.", "they become the sons of God."], ["Ma e pei ona mautinoa o loo soifua Keriso,", "And as sure as Christ liveth he spake these words unto our fathers,"], ["sa ia fetalai mai upu nei i o tatou tamā, ua fetalai mai:", "saying:"], ["Soo se mea,", "Whatsoever thing ye shall ask the Father in my name,"], ["ua lelei,", "which is good,"], ["tou te ole atu ai i le Tama i lou igoa i le faatuatua,", "in faith believing that ye shall receive,"], ["i le talitonu o le a outou maua, faauta,", "behold,"], ["o le a faia lava ia te outou.", "it shall be done unto you."]]},
  {num:27,words:[["O le mea lea,", "Wherefore,"], ["ou uso pele e,", "my beloved brethren,"], ["pe ua taofia ea vavega ona ua toe afio atu Keriso i le lagi,", "have miracles ceased because Christ hath ascended into heaven,"], ["ma ua afio i le itu aao taumatau o le Atua,", "and hath sat down on the right hand of God,"], ["e maua mai i le Tamā ana aia o le alofa mutimutivale lea ua ia te ia mo le fanauga a tagata?", "to claim of the Father his rights of mercy which he hath upon the children of men?"]]},
  {num:28,words:[["Ona ua uma ona tali e ia iuga o le tulafono,", "For he hath answered the ends of the law,"], ["ma ua a ia i latou uma o e ua faatuatua ia te ia;", "and he claimeth all those who have faith in him;"], ["ma o i latou o e ua faatuatua ia te ia o le a latou piimau i mea lelei uma;", "and they who have faith in him will cleave unto every good thing;"], ["o le mea lea ua fautuaina ai e ia le faamoemoe o le fanauga a tagata;", "wherefore he advocateth the cause of the children of men;"], ["ma ua afio o ia e faavavau i le lagi.", "and he dwelleth eternally in the heavens."]]},
  {num:29,words:[["Ma ona ua faia e ia lenei mea,", "And because he hath done this,"], ["ou uso pele e,", "my beloved brethren,"], ["pe ua taofia ai ea vavega? Faauta ou te fai atu ia te outou,", "have miracles ceased? Behold I say unto you,"], ["E leai;", "Nay;"], ["pe ua taofia foi le auauna mai o agelu i le fanauga a tagata.", "neither have angels ceased to minister unto the children of men."]]},
  {num:30,words:[["Aua faauta,", "For behold,"], ["ua i ai i latou i lana pule,", "they are subject unto him,"], ["e auauna mai e tusa ma upu e poloai ai o ia,", "to minister according to the word of his command,"], ["e faaali mai i latou lava ia te i latou ua i ai le faatuatua malosi ma le mafaufau mausali i uiga uma o le amioatua.", "showing themselves unto them of strong faith and a firm mind in every form of godliness."]]},
  {num:31,words:[["Ma o le tiute o la latou auaunaga o le valaau atu lea i tagata ia salamo,", "And the office of their ministry is to call men unto repentance,"], ["ma faataunuu ma faia le galuega o feagaiga a le Tamā,", "and to fulfill and to do the work of the covenants of the Father,"], ["ia na ia faia i le fanauga a tagata,", "which he hath made unto the children of men,"], ["e saunia le ala i totonu o le fanauga a tagata,", "to prepare the way among the children of men,"], ["i le alaga atu o le afioga a Keriso i ipu filifilia a le Alii,", "by declaring the word of Christ unto the chosen vessels of the Lord,"], ["ina ia latou molimau atu ia te ia.", "that they may bear testimony of him."]]},
  {num:32,words:[["Ma o le faia o lea mea,", "And by so doing,"], ["ua saunia ai e le Alii le Atua le ala e mafai ai e le toe vaega o tagata ona latou maua o le faatuatua ia Keriso,", "the Lord God prepareth the way that the residue of men may have faith in Christ,"], ["ina ia maua e le Agaga Paia se nofoaga i o latou loto,", "that the Holy Ghost may have place in  their hearts,"], ["e tusa ma lona mana;", "according to the power thereof;"], ["ma o le ala lenei o le a faataunuu ai e le Tamā,", "and after this manner bringeth to pass the Father,"], ["feagaiga na ia faia i le fanauga a tagata.", "the covenants which he hath made unto the children of men."]]},
  {num:33,words:[["Ma ua fetalai mai Keriso:", "And Christ hath said:"], ["Afai tou te faatuatua mai ia te au o le a outou maua le mana e fai ai soo se mea e tatau ai ia te au.", "If ye will have faith in me ye shall have power to do whatsoever thing is expedient in me."]]},
  {num:34,words:[["Ma ua fetalai mai o ia:", "And he hath said:"], ["Ia outou salamo outou tuluiga uma o le lalolagi,", "Repent all ye ends of the earth,"], ["ma o mai ia te au,", "and come unto me,"], ["ma ia papatiso i lou igoa,", "and be baptized in my name,"], ["ma faatuatua mai ia te au,", "and have faith in me,"], ["ina ia faaolaina outou.", "that ye may be saved."]]},
  {num:35,words:[["Ma o lenei,", "And now,"], ["ou uso pele e,", "my beloved brethren,"], ["afai o le tulaga lea e faapea ua moni nei mea ua ou tautala atu ai ia te outou,", "if this be the case that these things are true which I have spoken unto you,"], ["ma o le a faaali mai e le Atua ia te outou, i le mana ma le mamalu tele i le aso gataaga,", "and God will show unto you,"], ["ua moni i latou,", "with power and great glory at the last day,"], ["ma afai ua moni i latou,", "that they are true,"], ["pe ua uma ai ea le aso o vavega?", "and if they are true has the day of miracles ceased?"]]},
  {num:36,words:[["Pe ua taofia ea le afifio mai o agelu i le fanauga a tagata? Pe ua taofia e ia le mana o le Agaga Paia mai ia te i latou? Pe e taofia ea e ia,", "Or have angels ceased to appear unto the children of men? Or has he withheld the power of the Holy Ghost from them? Or will he,"], ["ao tumau pea le taimi,", "so long as time shall last,"], ["pe ao tu pea le lalolagi,", "or the earth shall stand,"], ["pe ao i ai se tagata e toatasi i luga o le lalolagi e faaolaina?", "or there shall be one man upon the face thereof to be saved?"]]},
  {num:37,words:[["Faauta ou te fai atu ia te outou,", "Behold I say unto you,"], ["E leai;", "Nay;"], ["ona o le faatuatua e faia ai vavega ;", "for it is by faith that miracles are wrought;"], ["ma o le faatuatua e afifio mai ai agelu ma auauna mai i tagata;", "and it is by faith that angels appear and minister unto men;"], ["o le mea lea,", "wherefore,"], ["afai ua taofia nei mea oi talofa i le fanauga a tagata,", "if these things have ceased wo be unto the children of men,"], ["ona o le le talitonu ua taofia ai,", "for it is because of unbelief,"], ["ma ua le aoga ai mea uma.", "and all is vain."]]},
  {num:38,words:[["Ona e le mafai ona faaolaina o se tagata,", "For no man can be saved,"], ["e tusa ma fetalaiga a Keriso,", "according to the words of Christ,"], ["vagana ai ua latou faatuatua i lona suafa;", "save they shall have faith in his name;"], ["o le mea lea,", "wherefore,"], ["afai ua le toe i ai nei mea,", "if these things have ceased,"], ["ua le toe i ai foi se faatuatua;", "then has faith ceased also;"], ["ma ua matua leaga lava le tulaga o tagata,", "and awful is the state of man,"], ["ona o le a pei i latou e peiseai e leai se togiola ua faia.", "for they are as though there had been no redemption made."]]},
  {num:39,words:[["Ae faauta,", "But behold,"], ["ou uso pele e,", "my beloved brethren,"], ["ua ou matauina ni mea lelei mai ia te outou,", "I judge better things of you,"], ["ona ua ou matauina ua outou faatuatua ia Keriso ona o lo outou agamalu;", "for I judge that ye have faith in Christ because of your meekness;"], ["ona a na fai tou te le faatuatua ia te ia po ua outou le agavaa e faitaulia i totonu o tagata o lana ekalesia.", "for if ye have not faith in him then ye are not fit to be numbered among the people of his church."]]},
  {num:40,words:[["O lenei foi,", "And again,"], ["ou uso pele e,", "my beloved brethren,"], ["ou te fia tautala atu ia te outou e uiga i le faamoemoe . E mafai faapefea ona outou maua o le faatuatua,", "I would speak unto you concerning hope. How is it that ye can attain unto faith,"], ["vagana ai ua ia te outou le faamoemoe?", "save ye shall have hope?"]]},
  {num:41,words:[["Ma o le a le mea tou te faamoemoe i ai? Faauta ou te fai atu ia te outou, tou te faamoemoe ,", "And what is it that ye shall hope for? Behold I say unto you that ye shall have hope through the atonement of Christ and the power of his resurrection,"], ["e ala i le togiola a Keriso ma le mana o lona toetu,", "to be raised unto life eternal,"], ["ia faatutu mai outou i le ola faavavau, ma o le pogai ona o lo outou faatuatua ia te ia e tusa ma le folafolaga.", "and this because of your faith in him according to the promise."]]},
  {num:42,words:[["O le mea lea,", "Wherefore,"], ["afai ua i ai i se tagata le faatuatua e tatau ona i ai ia te ia le faamoemoe;", "if a man have faith he must needs have hope;"], ["ona a aunoa ma le faatuatua e le mafai ona i ai se faamoemoe.", "for without faith there cannot be any hope."]]},
  {num:43,words:[["O lenei foi,", "And again,"], ["faauta ou te fai atu ia te outou e le mafai ona i ai ia te ia le faatuatua ma le faamoemoe,", "behold I say unto you that he cannot have faith and hope,"], ["vagana ai ua agamalu ,", "save he shall be meek,"], ["ma maualalo o ia i le loto.", "and lowly of heart."]]},
  {num:44,words:[["Afai e faapea,", "If so,"], ["ua le aoga lona faatuatua ma le faamoemoe,", "his faith and hope is vain,"], ["ona e leai se tasi e ono talia i luma o le Atua,", "for none is acceptable before God,"], ["vagana ai i latou o e ua agamalu ma maualalalo i le loto;", "save the meek and lowly in heart;"], ["ma afai e agamalu ma maualalo se tagata i le loto, ma tautino atu i le mana o le Agaga Paia o Iesu o le Keriso,", "and if a man be meek and lowly in heart,"], ["e ao ina i ai ia te ia le alofa mama;", "and confesses by the power of the Holy  Ghost that Jesus is the Christ,"], ["aua afai e le i ai ia te ia le alofa mama,", "he must needs have charity;"], ["o se mea noa o ia;", "for if he have not charity he is nothing;"], ["o le mea lea e ao ai ina i ai ia te ia le alofa mama.", "wherefore he must needs have charity."]]},
  {num:45,words:[["Ma o le alofa mama e loa ona tali-tiga,", "And charity suffereth long,"], ["ma e agalelei,", "and is kind,"], ["ma e le losilosivale ,", "and envieth not,"], ["ma e le faafefeteina,", "and is not puffed up,"], ["e le sailia e ia ana lava,", "seeketh not her own,"], ["e le faaitagofie,", "is not easily provoked,"], ["e le mafaufau i se mea leaga,", "thinketh no evil,"], ["ma e le olioli i le amioletonu ae olioli i le upu moni,", "and rejoiceth not in iniquity but rejoiceth in the truth,"], ["e onosaia mea uma,", "beareth all things,"], ["e talia mea uma,", "believeth all things,"], ["e faamoemoe i mea uma,", "hopeth all things,"], ["e onosai i mea uma.", "endureth all things."]]},
  {num:46,words:[["O le mea lea,", "Wherefore,"], ["ou uso pele e,", "my beloved brethren,"], ["afai e le ia te outou le alofa mama o ni mea noa outou,", "if ye have not charity, ye are nothing,"], ["ona e le uma le alofa mama.", "for charity never faileth."], ["O le mea lea,", "Wherefore,"], ["ia outou fusi ai i le alofa mama,", "cleave unto charity,"], ["le mea ua silisili lea i mea uma,", "which is the greatest of all,"], ["ona e iu mea uma—", "for all things must fail—"]]},
  {num:47,words:[["Ae o le alofa mama o le alofa le pona lea o Keriso,", "But charity is the pure love of Christ,"], ["ma e tumau e faavavau;", "and it endureth forever;"], ["ma o soo se tasi e maua ua i ai ia te ia i le aso gataaga,", "and whoso is found possessed of it at the last day,"], ["o le a lelei ia te ia.", "it shall be well with him."]]},
  {num:48,words:[["O le mea lea,", "Wherefore,"], ["ou uso pele e,", "my beloved brethren,"], ["ia outou tatalo atu i le Tamā ma le malosi atoa o le loto,", "pray unto the Father with all the energy of heart,"], ["ina ia faatumulia outou i lenei alofa,", "that ye may be filled with this love,"], ["lea ua ia faaee mai i luga o i latou uma o e o soo moni o lona Alo,", "which he hath bestowed upon all who are true followers of his Son,"], ["o Iesu Keriso;", "Jesus Christ;"], ["ina ia mafai ona avea o outou ma atalii o le Atua;", "that ye may become the sons of God;"], ["a oo ai ina afio mai o ia o le a tatou faapei o ia,", "that when he shall appear we shall be like him,"], ["ona o le a tatou vaai ia te ia e pei ona i ai o ia;", "for we shall see him as he is;"], ["tau ina ia tatou maua lenei faamoemoe;", "that we may have this hope;"], ["tau ina ia mafai ona faamamaina i tatou e pei lava ona mama o ia. Amene.", "that we may be purified even as he is pure. Amen."]]},
];
renderVerseSet(mr_ch_7_Verses, 'mr-ch7-verses');

var mr_ch_8_Verses = [
  {num:1,words:[["O se tusi a lou tamā o Mamona,", "An epistle of my father Mormon,"], ["na tusi mai ia te au,", "written to me,"], ["o Moronae;", "Moroni;"], ["ma sa tusi mai ia te au ae lei pine ona uma ona valaauina o au i le galuega. Ma sa faapenei ona ia tusi mai ia te au,", "and it was written unto me soon after my calling to the ministry. And on this wise did he write unto me,"], ["fai mai:", "saying:"]]},
  {num:2,words:[["Lou atalii pele e,", "My beloved son,"], ["Moronae,", "Moroni,"], ["ou te olioli tele ona ua manatu mai lou Alii o Iesu Keriso ia te oe,", "I rejoice exceedingly that your Lord Jesus Christ hath been mindful of you,"], ["ma ua ia valaauina oe i lana auaunaga,", "and hath called you to his ministry,"], ["ma i lana galuega paia.", "and to his holy work."]]},
  {num:3,words:[["Ou te manatu pea ia te oe i au talosaga,", "I am mindful of you always in my prayers,"], ["ma tatalo atu pea i le Atua le Tamā,", "continually praying unto God the Father in the name of his Holy Child,"], ["i le suafa o lona Alo Paia, o Iesu,", "Jesus,"], ["ia ona tausia oe,", "that he,"], ["e ala i lona agalelei e le gata ma lona alofa tunoa,", "through his infinite goodness and grace,"], ["i le tumau i le faatuatua i lona suafa e oo i le iuga.", "will keep you through the endurance of faith on his name to the end."]]},
  {num:4,words:[["Ma o lenei,", "And now,"], ["lou atalii e,", "my son,"], ["ou te tautala atu ia te oe e uiga i lena mea ua ou faanoanoa tele ai:", "I speak unto you concerning that which grieveth me exceed– ingly;"], ["aua ou te faanoanoa i le tutulai mai o ni finauga i totonu o outou.", "for it grieveth me that there should disputations rise among you."]]},
  {num:5,words:[["Aua,", "For,"], ["afai ua ou iloaina le mea moni,", "if I have learned the truth,"], ["sa i ai ni finauga i totonu o outou e uiga i le papatisoina o a outou fanau laiti.", "there have been disputations among you concerning the baptism of your little children."]]},
  {num:6,words:[["Ma o lenei,", "And now,"], ["lou atalii e,", "my son,"], ["ou te manao ia e galue ma le filiga,", "I desire that ye should labor diligently,"], ["ina ia aveeseina lenei sese tele mai totonu o outou;", "that this gross error should be removed from among you;"], ["ona,", "for,"], ["o le faamoemoe lenei ua ou tusia ai lenei tusi.", "for this intent I have written this epistle."]]},
  {num:7,words:[["Aua e lei pine ona mavae ona ou iloa o nei mea mai ia te oe, sa ou ole atu i le Alii e uiga i le mataupu.", "For immediately after I had learned these things of you I inquired of the Lord concerning the matter."], ["Ma sa oo mai ia te au le afioga a le Alii e ala i le mana o le Agaga Paia,", "And the word of the Lord came to me by the power of the Holy Ghost,"], ["ua fetalai mai:", "saying:"]]},
  {num:8,words:[["Faalogo mai i upu a Keriso,", "Listen to the words of Christ,"], ["lou Togiola,", "your Redeemer,"], ["lou Alii ma lou Atua.", "your Lord and your God."], ["Faauta,", "Behold,"], ["ou te lei sau i le lalolagi e valaau atu i e amiotonu ae o e agasala ia salamo; ua le manaomia e e ua maloloina se fomai,", "I came into the  world not to call the righteous but sinners to repentance;"], ["ae o i latou o e ua mamai;", "the whole need no physician,"], ["o le mea lea,", "but they that are sick;"], ["ua maloloina tamaiti laiti,", "wherefore,"], ["ona ua le mafai ona latou faia se agasala ; o le mea lea ua aveese mai ia te i latou,", "little children are whole,"], ["ia te au,", "for they are not capable of committing sin;"], ["le fetuu o Atamu ,", "wherefore the curse of Adam is taken from them in me,"], ["ua leai ai sona mana i luga o i latou; ma ua aveese atu le tulafono o le peritomeina ,", "that it hath no power over them;"], ["e ala ia te au.", "and the law of circumcision is done away in me."]]},
  {num:9,words:[["Ma o le ala lenei na faaali mai ai e le Agaga Paia ia te au le afioga a le Atua;", "And after this manner did the Holy Ghost manifest the word of God unto me;"], ["o le mea lea,", "wherefore,"], ["lou atalii pele e,", "my beloved son,"], ["ua ou iloa ai o se ula totoa i luma o le Atua,", "I know that it is solemn mockery before God,"], ["lo outou papatisoina o fanau laiti.", "that ye should baptize little children."]]},
  {num:10,words:[["Faauta ou te fai atu ia te outou o le mea lenei ia outou aoao atu—o le salamo ma le papatisoga ia i latou o e ua tali atu ma mafai ona faia le agasala;", "Behold I say unto you that this thing shall ye teach—repentance and baptism unto those who are accountable and capable of committing sin;"], ["ioe,", "yea,"], ["aoao atu i matua e tatau ona latou salamo ma papatisoina,", "teach parents that they must repent and be baptized,"], ["ma faalotomaualalalo i latou lava e pei o a latou fanau laiti,", "and humble themselves as their little children,"], ["ma o le a faaolaina ai i latou uma faatasi ma a latou fanau laiti.", "and they shall all be saved with their little children."]]},
  {num:11,words:[["Ma e le manaomia e a latou fanau laiti se salamo,", "And their little children need no repentance,"], ["po o le papatisoga. Faauta,", "neither baptism. Behold,"], ["o le papatisoga ua mo le salamo i le faataunuuina o poloaiga mo le faamagaloina o agasala.", "baptism is unto repentance to the fulfilling the commandments unto the remission of sins."]]},
  {num:12,words:[["Ae o fanau laiti ua ola ia Keriso,", "But little children are alive in Christ,"], ["mai lava i le faavaega o le lalolagi;", "even from the foundation of the world;"], ["afai ua le faapea,", "if not so,"], ["o le Atua o se Atua faaauau,", "God is a partial God,"], ["ma o se Atua feliuliuai foi,", "and also a changeable God,"], ["ma o se ua faailoga tagata;", "and a respecter to persons;"], ["ona o le a le toatele o fanau laiti ua feoti e aunoa ma le papatisoga!", "for how many little children have died without baptism!"]]},
  {num:13,words:[["O le mea lea,", "Wherefore,"], ["afai e le mafai ona faaolaina o fanau laiti e aunoa ma le papatisoga,", "if little children could not be saved without baptism,"], ["po ua latou o atu i le seoli e le gata.", "these must have gone to an endless hell."]]},
  {num:14,words:[["Faauta ou te fai atu ia te oe,", "Behold I say unto you,"], ["o ia o le ua manatu ua manaomia e fanau laiti le papatisoga ua i ai o ia i le au oona ma fusi o le amioletonu;", "that he that supposeth that little children need baptism is in the gall of bitterness and in the bonds of iniquity,"], ["aua ua le i ai ia te ia le faatuatua ,", "for he hath neither faith,"], ["faamoemoe,", "hope,"], ["po o le alofa mama;", "nor charity;"], ["o le mea lea,", "wherefore,"], ["afai e vavae ese o ia ao i ai ia te ia lea manatu,", "should he be cut off while in the thought,"], ["o le a alu ifo o ia i lalo i seoli.", "he must go down to hell."]]},
  {num:15,words:[["Ona ua matua leaga lava le amioleaga o le manatu e faapea e faaolaina e le Atua se tasi tamaitiiti ona ua papatisoina,", "For awful is the wickedness to suppose that God saveth one child because of baptism,"], ["ae o le a fano le tasi ona ua le papatisoina.", "and the other must perish because he hath no baptism."]]},
  {num:16,words:[["Oi talofa ia te i latou e faapiopioina ala o le Alii i lenei ala,", "Wo be unto them that shall pervert the ways of the Lord after this manner,"], ["ona o le a fano i latou vagana ai ua latou salamo. Faauta,", "for they shall perish except they repent. Behold,"], ["ou te tautala atu ma le lotoa,", "I speak with boldness,"], ["ona ua ou maua le pule mai le Atua;", "having authority from God;"], ["ma ou te le fefe po o a mea e mafai ona faia e tagata;", "and I fear not what man can do;"], ["ona e lafo ese i fafo e le alofa ua atoatoa le fefe uma.", "for perfect love casteth out all fear."]]},
  {num:17,words:[["Ma ua tumu au i le alofa mama,", "And I am filled with charity,"], ["le alofa tumau-faavavau lea;", "which is everlasting love;"], ["o le mea lea,", "wherefore,"], ["ua tutusa fanau laiti uma ia te au;", "all children are alike unto me;"], ["o le mea lea,", "wherefore,"], ["ua ou alofa i fanau laiti i se alofa ua atoatoa;", "I love little children with a perfect love;"], ["ma ua tutusa i latou uma ma ua tofusia i le olataga.", "and they are all alike and partakers of salvation."]]},
  {num:18,words:[["Ona ua ou iloa o le Atua e le o se Atua faaauau,", "For I know that God is not a partial God,"], ["po o se tagata ua feliuliuai;", "neither a changeable being;"], ["ae ua le feliuliuai o ia mai le faavavau atoa i le faavavau atoa.", "but he is unchangeable from all eternity to all eternity."]]},
  {num:19,words:[["E le mafai e fanau laiti ona salamo;", "Little children cannot repent;"], ["o le mea lea,", "wherefore,"], ["o se amioleaga tele le faafitia o le alofa mutimutivale mama o le Atua mai ia te i latou,", "it is awful wicked– ness to deny the pure mercies of God unto them,"], ["ona ua ola uma i latou ia te ia ona o lona alofa mutimutivale.", "for they are all alive in him because of his mercy."]]},
  {num:20,words:[["Ma o ia o le e fai mai e manaomia e fanau laiti le papatisoga ua ia faafitia le alofa mutimutivale o Keriso,", "And he that saith that little children need baptism denieth the mercies of Christ,"], ["ma fai ma meanoa lana togiola ma le mana o lana togiola.", "and setteth at naught the atonement of him and the power of his redemption."]]},
  {num:21,words:[["Oi talofa i e faapea,", "Wo unto such,"], ["ona ua latou onofia i le oti,", "for they are in danger of death,"], ["seoli ,", "hell,"], ["ma le mafatia e le gata. Ou te tautala atu ia upu ma le lotoa;", "and an endless torment. I speak it boldly;"], ["ua poloaiina ai au e le Atua. Ia outou faalogo i ai ma uai i ai,", "God hath commanded me. Listen unto them and give heed,"], ["a leai o le a tutu e faasaga ia te outou i le nofoa-faamasino o Keriso.", "or they stand against you at the judgment– seat of Christ."]]},
  {num:22,words:[["Aua faauta, ua ola fanau laiti uma ia Keriso,", "For behold that all little children are alive in Christ,"], ["ma i latou uma foi o e ua aunoa ma le tulafono .", "and also all they that are without the law."], ["Aua e oo mai le mana o le togiola i luga o i latou uma o e ua aunoa ma le tulafono;", "For the power of redemption cometh on all them that have no law;"], ["o le mea lea,", "wherefore,"], ["o ia o le ua le tausalaina,", "he that is not condemned,"], ["po o ia o le ua le i lalo o se tausalaga,", "or he that is under no condemnation,"], ["e le mafai ona salamo;", "cannot repent;"], ["ma o e faapena ua le aoga i ai le papatisoga—", "and unto such baptism availeth nothing—"]]},
  {num:23,words:[["Ae o se ulaga i luma o le Atua,", "But it is mockery before God,"], ["ua faafitia ai le alofa mutimutivale o Keriso,", "denying the mercies of Christ,"], ["ma le mana o lona Agaga Paia,", "and the power of his Holy Spirit,"], ["ma le tuuina atu o le faalagolago i galuega mamate .", "and putting trust in dead works."]]},
  {num:24,words:[["Faauta,", "Behold,"], ["lou atalii e,", "my son,"], ["e le tatau lava ona i ai o lenei mea;", "this thing ought not to be;"], ["ona o le salamo e mo i latou ua i ai i lalo o le tausalaga ma lalo o le fetuu o le tulafono ua solia.", "for repentance is unto them that are under condemnation and under the curse of a broken law."]]},
  {num:25,words:[["Ma o fua muamua o le salamo o le papatisoga ;", "And the first fruits of repentance is baptism;"], ["ma o le papatisoga e oo mai e ala i le faatuatua e faataunuu ai poloaiga;", "and baptism cometh by faith unto the fulfilling the commandments;"], ["ma o le faataunuuina o poloaiga e maua ai le faamagaloina o agasala;", "and the fulfilling the commandments bringeth remission of sins;"]]},
  {num:26,words:[["Ma o le faamagaloina o agasala e maua ai le agamalu ,", "And the remission of sins bringeth meek– ness,"], ["ma le maualalo o le loto;", "and lowliness of heart;"], ["ma o le agamalu ma le maualalo o le loto e oo mai ai le asiasiga a le Agaga Paia,", "and because of meekness and lowliness of heart cometh the visitation of the Holy Ghost,"], ["o le Faamafanafana lea na te faatumuina le tagata i le faamoemoe ma le alofa atoatoa,", "which Comforter filleth with hope and perfect love,"], ["o le alofa lea e tumau e ala i le filiga i le tatalo ,", "which love endureth by diligence unto prayer,"], ["seia oo mai le iuga,", "until the end shall come,"], ["pe a mau le au paia uma faatasi ma le Atua.", "when all the saints shall dwell with God."]]},
  {num:27,words:[["Faauta,", "Behold,"], ["lou atalii e,", "my son,"], ["o le a ou toe tusi atu ia te oe pe a le vave ona ou alu atu i fafo e faasaga ia sa Lamanā. Faauta,", "I will write unto you again if I go not out soon against the Lamanites. Behold,"], ["o le faamaualuluga o lenei atunuu,", "the pride of this nation,"], ["po o tagata o sa Nifaē,", "or the people of the Nephites,"], ["ua faamaonia ai lo latou faaumatiaga vagana ai o le a latou salamo.", "hath proven their destruction except they should repent."]]},
  {num:28,words:[["Ia e tatalo mo i latou,", "Pray for them,"], ["lou atalii e,", "my son,"], ["ina ia oo mai le salamo ia te i latou.", "that repentance may come unto them."], ["Peitai faauta,", "But behold,"], ["ou te fefe nei le toe taumafai le Agaga ia te i latou;", "I fear lest the Spirit hath ceased striving with them;"], ["ma i le vaega lenei o le laueleele, o loo latou saili foi e tuu i lalo le mana ma le pule atoa lea ua sau mai le Atua;", "and in this part of the land they are also seeking to put down all power and authority which cometh from God;"], ["ma ua latou teena le Agaga Paia.", "and they are denying the Holy Ghost."]]},
  {num:29,words:[["Ma ina ua uma ona latou teena se malamalama tele faapea naua,", "And after rejecting so great a knowledge,"], ["lou atalii e,", "my son,"], ["o le a vave ona fano o i latou,", "they must perish soon,"], ["i le faataunuuina o valoaga na fetalaia e perofeta,", "unto the fulfilling of the prophecies which were spoken by the prophets,"], ["faapea foi ma fetalaiga a lo tatou Faaola lava ia.", "as well as the words of our Savior himself."]]},
  {num:30,words:[["Tofa ia,", "Farewell,"], ["lou atalii e,", "my son,"], ["seia ou tusi atu ia te oe,", "until I shall write unto you,"], ["pe seia ou toe feiloai ma oe. Amene.", "or shall meet you again. Amen."]]},
];
renderVerseSet(mr_ch_8_Verses, 'mr-ch8-verses');

var mr_ch_9_Verses = [
  {num:1,words:[["Lou atalii pele e,", "My beloved son,"], ["ua ou toe tusi atu ia te oe ina ia e iloa o loo ou ola pea;", "I write unto you again that ye may know that I am yet alive;"], ["ae ou te tusi teisi e uiga i mea ua matua faanoanoa tele.", "but I write somewhat of that which is grievous."]]},
  {num:2,words:[["Aua faauta,", "For behold,"], ["sa ou tauina se taua tuga ma sa Lamanā,", "I have had a sore battle with the Lamanites,"], ["lea sa matou le manumalo ai;", "in which we did not conquer;"], ["ma ua pau Akeanetusi i le pelu,", "and Archeantus has fallen by the sword,"], ["ma Lurama ma Emirona foi;", "and also Luram and Emron;"], ["ioe,", "yea,"], ["ma ua toesea mai ia te i tatou se aofai tele o o tatou tagata sili ona lelei.", "and we have lost a great number of our choice men."]]},
  {num:3,words:[["Ma o lenei faauta,", "And now behold,"], ["lou atalii e,", "my son,"], ["ou te fefe nei faaumatia e sa Lamanā lenei nuu;", "I fear lest the Lamanites shall destroy this people;"], ["ona ua latou le salamo,", "for they do not repent,"], ["ma ua faaosooso pea i latou e Satani ia feitagai ma le tasi.", "and Satan stirreth them up continually to anger one with another."]]},
  {num:4,words:[["Faauta,", "Behold,"], ["o loo ou galue pea e le aunoa ia te i latou;", "I am laboring with them continually;"], ["ma a ou tautala atu ia te i latou le afioga a le Atua ma le saolele latou te tetete ma feita faasaga mai ia te au;", "and when I speak the word of God with sharpness they tremble and anger against me;"], ["ma a ou le tautala atu foi ma le saolele ua latou faamaaa o latou loto e faasaga i ai;", "and when I use no sharpness they harden their hearts against it;"], ["o le mea lea,", "wherefore,"], ["ou te fefe nei mea ane ua le toe finafinau le Agaga o le Alii faatasi ma i latou.", "I fear lest the Spirit of the Lord hath ceased striving with them."]]},
  {num:5,words:[["Ona ua latou matua feita tele e foliga mai ia te au ua leai so latou fefefe i le oti;", "For so exceedingly do they anger that it seemeth me that they have no fear of death;"], ["ma ua toesea lo latou alofa,", "and they have lost their love,"], ["o le tasi i le isi;", "one towards another;"], ["ma ua latou galala i le toto ma le taui ma sui e le aunoa.", "and they thirst after blood and revenge continually."]]},
  {num:6,words:[["Ma o lenei,", "And now,"], ["lou atalii pele e,", "my beloved son,"], ["e ui i lo latou maaa,", "notwithstanding their hardness,"], ["ia ta galulue pea ma le filiga ;", "let us labor diligently;"], ["aua afai ta te tuu le galulue ,", "for if we should cease to labor,"], ["o le a aumai i taua i lalo o le tausalaga;", "we should be brought under condemnation;"], ["ona ua i ai sa taua galuega e fai ao ta i ai i lenei fale apitaga omea,", "for we have a labor to perform whilst in this tabernacle of clay,"], ["ina ia ta faatoilaloina le fili o le amiotonu uma,", "that we may conquer the enemy of all righteousness,"], ["ma malolo ai o taua agaga i le malo o le Atua.", "and rest our souls in the kingdom of God."]]},
  {num:7,words:[["Ma o lenei ou te tusi atu teisi e uiga i mafatiaga o lenei nuu. Aua e tusa ma le malamalama lea na ou maua mai ia Amorona,", "And now I write somewhat concerning the sufferings of this people. For according to the knowledge which I have received from Amoron,"], ["faauta,", "behold,"], ["ua maua e sa Lamanā ni pagota e toatele,", "the Lamanites have many prisoners,"], ["ia sa latou aumai mai le olo o Serisa;", "which they took from the tower of Sherrizah;"], ["ma sa i ai tane,", "and there were men,"], ["fafine,", "women,"], ["ma tamaiti.", "and children."]]},
  {num:8,words:[["Ma o tane ma tamā o ia fafine ma tamaiti ua latou fasiotia;", "And the husbands and fathers of those women and children they have slain;"], ["ma ua latou fafaga fafine i aano o a latou tane,", "and they feed the women upon the flesh of their husbands,"], ["ma tamaiti i aano o o latou tamā;", "and the children upon the flesh of their fathers; and no water,"], ["ma ua latou le avatu ia te i latou se vai,", "save a little,"], ["vagana ai sina mea itiiti.", "do they give unto them."]]},
  {num:9,words:[["Ma e ui i lenei mea inosia tele a sa Lamanā,", "And notwithstanding this great abomi– nation of the Lamanites,"], ["ua le sili atu i le mea ua faia e o tatou tagata i Morianetuma. Aua faauta,", "it doth not exceed that of our people in Moriantum. For behold,"], ["e toatele afafine o sa Lamanā ua latou ave faapagota;", "many of the daughters of the Lamanites have they taken prisoners;"], ["ma ina ua uma ona latou aveesea mai ia te i latou o le mea lena ua silisili ona pele ma taua i luga o mea uma lava,", "and after depriving them of that which was most dear and precious above all things,"], ["o le lē gaōiā lea ma le mama —", "which is chastity and virtue—"]]},
  {num:10,words:[["Ma ina ua uma ona latou faia o lenei mea,", "And after they had done this thing,"], ["sa latou fasioti i latou i se auala e silisili ona paaa,", "they did murder them in a most cruel manner,"], ["ua faatauga o latou tino seia oo ina feoti;", "torturing their bodies even unto death;"], ["ma ina ua uma ona latou faia o lenei mea,", "and after they have done this,"], ["ua latou ai lotulotu o latou tino e pei o manu aivao,", "they devour their flesh like unto wild beasts,"], ["ona o le maaa o o latou loto;", "because of the hardness of their hearts;"], ["ma ua latou faia lenei mea o se faailoga o le toa.", "and they do it for a token of bravery."]]},
  {num:11,words:[["E,", "O my beloved son,"], ["lou atalii pele e, e mafai faapefea e ni tagata faapenei,", "how can a people like this,"], ["ua aunoa ma le tu malamalama—", "that are without civilization—"]]},
  {num:12,words:[["(Ma e nao ni nai tausaga itiiti ua mavae atu,", "(And only a few years have passed away,"], ["sa avea ai i latou ma ni tagata tu malamalama ma tauagafau)", "and they were a civil and a delightsome people)"]]},
  {num:13,words:[["Ae lou atalii e,", "But O my son,"], ["e mafai faapefea e ni tagata faapenei,", "how can a people like this,"], ["o e o lo latou fiafia ua i ai lea i le faia o mea inosia e tele—", "whose delight is in so much abomination—"]]},
  {num:14,words:[["E mafai faapefea ona tatou faamoemoe o le a taofi e le Atua lona aao i le faamasinoga e faasaga ia te i tatou?", "How can we expect that God will stay his hand in judgment against us?"]]},
  {num:15,words:[["Faauta,", "Behold,"], ["ua tagi ae lo'u loto:", "my heart cries:"], ["Oi talofa i lenei nuu.", "Wo unto this people."], ["Afio mai ia,", "Come out in judgment,"], ["le Atua e,", "O God,"], ["i le faamasinoga, ma natia a latou agasala,", "and hide their sins,"], ["ma amioleaga,", "and wickedness,"], ["ma mea inosia mai luma o ou fofoga!", "and abominations from before thy face!"]]},
  {num:16,words:[["O lenei foi,", "And again,"], ["lou atalii e,", "my son,"], ["e toatele o fafine ua oti a latou tane, ma a latou tama teine,", "there are many widows and their daughters who remain in Sherrizah;"], ["o loo nonofo pea i Serisa;", "and that part of the provisions which the Lamanites did not carry away,"], ["ma o le vaega lena o meaai sa le avea e sa Lamanā,", "behold,"], ["faauta, ua ave e le autau a Senifae,", "the army of Zenephi has carried away,"], ["ma ua tuua ai i latou e feoai solo i soo se mea e mafai ona latou o atu i ai mo ni meaai;", "and left them to wander whithersoever they can for food;"], ["ma e toatele fafine matutua ua matapogia i ala ma feoti ai.", "and many old women do faint by the way and die."]]},
  {num:17,words:[["Ma o le autau ua faatasi ma au ua vaivai;", "And the army which is with me is weak;"], ["ma o autau a sa Lamanā o loo i le va o Serisa ma au;", "and the armies of the Lamanites are betwixt Sherrizah and me;"], ["ma o le toatele o e na sosola atu i le autau a Arona ua pauu fasia i lo latou saua matautia faamanu.", "and as many as have fled to the army of Aaron have fallen victims to their awful brutality."]]},
  {num:18,words:[["E, le leaga e o lou nuu! Ua latou aunoa ma le maopoopo ma aunoa ma le alofa mutimutivale.", "O the depravity of my people! They are without order and without mercy."], ["Faauta,", "Behold,"], ["o au ua nao se tagata,", "I am but a man,"], ["ma ua nao le malosi o se tagata ua ia te au,", "and I have but the strength of a man,"], ["ma ua le mafai ona ou toe faamalosia au faatonuga.", "and I cannot any longer enforce my commands."]]},
  {num:19,words:[["Ma ua latou malolosi ia latou faapiopioga;", "And they have become strong in their perversion;"], ["ma ua tutusa lo latou saua faamanu,", "and they are alike brutal,"], ["ua latou le faasaoina se tasi,", "sparing none,"], ["pe matutua pe laiti;", "neither old nor young;"], ["ma ua latou fiafia i mea uma, vagana ai le mea lelei;", "and they delight in everything save that which is good;"], ["ma o le mafatia o o tatou fafine ma a tatou fanau i luga o le laueleele atoa lenei ua sili atu i mea uma;", "and the suffering of our women and our children upon all the face of this land doth exceed everything;"], ["ioe,", "yea,"], ["e le mafai e le laulaufaiva ona faamatala,", "tongue cannot tell,"], ["pe mafai foi ona tusia.", "neither can it be written."]]},
  {num:20,words:[["Ma o lenei,", "And now,"], ["lou atalii e,", "my son,"], ["ou te le toe fia tautala umi atu e uiga i lenei vaaiga leaga matautia. Faauta,", "I dwell no longer upon this horrible scene. Behold,"], ["ua e iloa le amioleaga o lenei nuu;", "thou knowest the wickedness of this people;"], ["ua e iloa ua latou aunoa ma se mafaufau lelei,", "thou knowest that they are without principle,"], ["ma ua latou le toe lagona se lelei;", "and past feeling;"], ["ma o lo latou amioleaga ua sili atu i lo sa Lamanā.", "and their wickedness doth exceed that of the Lamanites."]]},
  {num:21,words:[["Faauta,", "Behold,"], ["lou atalii e,", "my son,"], ["e le mafai ona fautua atu i latou i le Atua nei taia au e ia.", "I cannot recommend them unto God lest he should smite me."]]},
  {num:22,words:[["Ae faauta,", "But behold,"], ["lou atalii e,", "my son,"], ["ou te fautua atu oe i le Atua,", "I recommend thee unto God,"], ["ou te faalagolago ia Keriso ia faaolaina oe;", "and I trust in Christ that thou wilt be saved;"], ["ma ou te tatalo atu i le Atua ia faasaoina e ia lou ola,", "and I pray unto God that he will spare thy life,"], ["e molimauina le toe foi mai o ona tagata ia te ia,", "to witness the return of his people unto him,"], ["po o lo latou faafanoga atoa;", "or their utter destruction;"], ["ona ua ou iloa e o le a fano i latou vagana ai ua latou salamo ma toe foi mai ia te ia.", "for I know that they must perish except they repent and return unto him."]]},
  {num:23,words:[["Ma afai e fano i latou o le a pei o sa Iaretō,", "And if they perish it will be like unto the Jaredites,"], ["ona o lo latou saili ma le loto i ai o o latou loto,", "because of the willfulness of their hearts,"], ["mo le toto ma le tauimasui .", "seeking for blood and revenge."]]},
  {num:24,words:[["Ma afai e faapea o le a fano i latou,", "And if it so be that they perish,"], ["ua tatou iloa e toatele o tatou uso ua sosola atu ia sa Lamanā,", "we know that many of our brethren have deserted over unto the Lamanites,"], ["ma e toatele atu foi ni isi o le a sosola atu ia te i latou;", "and many more will also desert over unto them;"], ["o le mea lea,", "wherefore,"], ["ia e tusi teisi ni nai mea itiiti,", "write somewhat a few things,"], ["pe afai e faasaoina oe ma o le a ou fano ma le vaai ia te oe;", "if thou art spared and I shall perish and not see thee;"], ["ae ou te faalagolago ia mafai ona lata ona ou vaai ia te oe;", "but I trust that I may see thee soon;"], ["ona ua ia te au ni au talafaamaumau paia ou te manao e tuu atu ia te oe.", "for I have sacred records that I would deliver up unto thee."]]},
  {num:25,words:[["Lou atalii e,", "My son,"], ["ia e faamaoni ia Keriso;", "be faithful in Christ;"], ["ma ia le avea mea ua ou tusia ma mea e te faanoanoa ai,", "and may not the things which I have written grieve thee,"], ["e faamamafa ai oe i lalo sei e oti;", "to weigh thee down unto death;"], ["ae talosia ia sii ae oe i luga e Keriso,", "but may Christ lift thee up, and may his sufferings and death,"], ["ma talosia ia mau e faavavau i lou mafaufau ona mafatia ma lona maliu,", "and the  showing his body unto our fathers,"], ["ma le faaali mai o lona tino i o tatou tamā,", "and his mercy and long– suffering,"], ["ma lona alofa mutimutivale ma le tali-tiga,", "and the hope of his glory and of eternal life,"], ["ma le faamoemoe o lona mamalu ma le ola faavavau.", "rest in your mind forever."]]},
  {num:26,words:[["Ma talosia ia i ai,", "And may the grace of God the Father,"], ["ma mau faatasi ma oe e faavavau,", "whose throne is high in the heavens,"], ["le alofa tunoa o le Atua le Tamā,", "and our Lord Jesus Christ,"], ["o le o lona nofoalii ua maualuga i le lagi,", "who sitteth on the right hand of his power,"], ["ma lo tatou Alii o Iesu Keriso,", "until all things shall become subject unto him,"], ["o le ua afio i le itu aao taumatau o lona mana,", "be,"], ["seia oo ina pule o ia i mea uma. Amene.", "and abide with you forever. Amen."]]},
];
renderVerseSet(mr_ch_9_Verses, 'mr-ch9-verses');

var mr_ch_10_Verses = [
  {num:1,words:[["O lenei,", "Now I,"], ["o au,", "Moroni,"], ["o Moronae, ou te tusi teisi i ni mea ou te manatu lava au ua lelei;", "write somewhat as seemeth me good;"], ["ma ou te tusi atu i ou uso,", "and I write unto my brethren,"], ["o sa Lamanā;", "the Lamanites;"], ["ma ou te manao ia latou iloa ua sili atu i le fa selau ma le lua sefulu tausaga ua mavae atu talu ona tuuina mai o le faailoga o le afio mai o Keriso.", "and I would that they should know that more than four hundred and twenty years have passed away since the sign was given of the coming of Christ."]]},
  {num:2,words:[["Ma ou te faamaufaailogaina nei talafaamaumau,", "And I seal up these records,"], ["pe a uma ona ou tautala atu ni nai upu itiiti e ala i le apoapoai atu ia te outou.", "after I have spoken a few words by way of exhortation unto you."]]},
  {num:3,words:[["Faauta,", "Behold,"], ["ou te apoapoai atu ia te outou pe a outou faitauina nei mea,", "I would exhort you that when ye shall read these things,"], ["pe afai e tusa ai ma le fingalo poto o le Atua ia outou faitauina,", "if it be wisdom in God that ye should read them,"], ["ia outou manatua le alofa mutimutivale tele o le Alii i le fanauga a tagata,", "that ye would remember how merciful the Lord hath been unto the children of men,"], ["mai i le foafoaga o Atamu e oo mai lava i lalo seia oo mai i le taimi o le a outou maua ai nei mea,", "from the creation of Adam even down unto the time that ye shall receive these things,"], ["ma manatunatu i ai i o outou loto .", "and ponder it in your hearts."]]},
  {num:4,words:[["Ma pe a outou maua nei mea,", "And when ye shall receive these things,"], ["ou te apoapoai atu ia te outou ia outou ole atu i le Atua,", "I would exhort you that ye would ask God,"], ["le Tamā Faavavau,", "the Eternal Father,"], ["i le suafa o Iesu Keriso,", "in the name of Christ,"], ["pe ua le moni ea nei mea;", "if these things are not true;"], ["ma afai tou ole atu ma le loto faamaoni ,", "and if ye shall ask with a sincere heart,"], ["ma le manatu moni i ai,", "with real intent,"], ["ma le faatuatua ia Keriso,", "having faith in Christ,"], ["o le a ia faaali mai le moni o ia mea ia te outou,", "he will manifest the truth of it unto you,"], ["i le mana o le Agaga Paia.", "by the power of the Holy Ghost."]]},
  {num:5,words:[["Ma o le mana o le Agaga Paia e mafai ona outou iloa ai le moni o mea uma lava.", "And by the power of the Holy Ghost ye may know the truth of all things."]]},
  {num:6,words:[["Ma o soo se mea ua lelei,", "And whatsoever thing is good is just and true;"], ["ua tonu ma moni;", "wherefore,"], ["o le mea lea, e leai se mea ua lelei e faafitia le Keriso,", "nothing that is good denieth the Christ,"], ["ae tautino mai o loo soifua o ia.", "but acknowledgeth that he is."]]},
  {num:7,words:[["Ma e mafai ona outou iloa o loo soifua o ia,", "And ye may know that he is,"], ["i le mana o le Agaga Paia;", "by the power of the Holy Ghost;"], ["o le mea lea ou te apoapoai atu ai ia te outou ia outou le faafitia le mana o le Atua;", "wherefore I would exhort you that ye deny not the power of God;"], ["aua e galue o ia e ala i le mana,", "for he worketh by power,"], ["e tusa ma le faatuatua o le fanauga a tagata,", "according to the faith of the children of men,"], ["e tutusa i le aso ma taeao,", "the same today and tomorrow,"], ["ma le faavavau.", "and forever."]]},
  {num:8,words:[["O lenei foi,", "And again,"], ["ou te apoapoai atu ia te outou,", "I exhort you,"], ["ou uso e,", "my brethren,"], ["ia outou le faafitia meaalofa a le Atua,", "that ye deny not the gifts of God,"], ["ona e tele i latou;", "for they are many;"], ["ma ua o mai i latou mai le Atua e tasi. Ma e eseese ala e faatino ai ia meaalofa;", "and they come from the same God. And there are different ways that these gifts are administered;"], ["ae o le Atua e tasi o le na te galueaiina i soo se mea ma i mea uma;", "but it is the same God who worketh all in all;"], ["ma ua tuuina mai nei meaalofa i tagata e ala i faaaliga a le Agaga o le Atua,", "and they are given by the manifestations of the Spirit of God unto men,"], ["ia latou manuia ai.", "to profit them."]]},
  {num:9,words:[["Aua faauta,", "For behold,"], ["ua tuuina mai e le Agaga o le Atua, i le tasi,", "to one is given by the Spirit of God,"], ["ina ia mafai ona ia aoao atu le upu o le poto;", "that he may teach the word of wisdom;"]]},
  {num:10,words:[["Ma i le tasi,", "And to another,"], ["ina ia mafai ona ia aoao atu le upu o le malamalama lea i le Agaga e tasi;", "that he may teach the word of knowledge by the same Spirit;"]]},
  {num:11,words:[["Ma i le tasi,", "And to another,"], ["o le faatuatua tele naua;", "exceedingly great faith;"], ["ma i le tasi,", "and to another,"], ["o le meaalofa o faamalologa e ala i le Agaga e tasi;", "the gifts of healing by the same Spirit;"]]},
  {num:12,words:[["O lenei foi,", "And again,"], ["i le tasi,", "to another,"], ["ina ia mafai ona ia faia vavega tetele;", "that he may work mighty miracles;"]]},
  {num:13,words:[["O lenei foi,", "And again,"], ["i le tasi,", "to another,"], ["ina ia mafai ona ia vavalo e uiga i mea uma;", "that he may prophesy concerning all things;"]]},
  {num:14,words:[["O lenei foi,", "And again,"], ["i le tasi,", "to another,"], ["le vaaia o agelu ma agaga auauna mai;", "the beholding of angels and ministering spirits;"]]},
  {num:15,words:[["O lenei foi,", "And again,"], ["i le tasi,", "to another,"], ["ituaiga uma o gagana eseese;", "all kinds of tongues;"]]},
  {num:16,words:[["O lenei foi,", "And again,"], ["i le tasi,", "to another,"], ["o le faaliliuga o gagana ma ituaiga o gagana eseese.", "the interpretation of languages and of divers kinds of tongues."]]},
  {num:17,words:[["Ma o nei meaalofa uma e oo mai e ala mai i le Agaga o Keriso;", "And all these gifts come by the Spirit of Christ;"], ["ma e oo mai i latou i tagata uma taitoatasi,", "and they come unto every man severally,"], ["e tusa ma lona finagalo.", "according as he will."]]},
  {num:18,words:[["Ma ou te apoapoai atu ai ia te outou,", "And I would exhort you,"], ["ou uso pele e,", "my beloved brethren,"], ["ia outou manatua o meaalofa lelei uma e mai ia Keriso.", "that ye remember that every good gift cometh of Christ."]]},
  {num:19,words:[["Ma ou te fia apoapoai atu ia te outou,", "And I would exhort you,"], ["ou uso pele e,", "my beloved brethren,"], ["ia outou manatua e tutusa o ia ananafi,", "that ye remember that he is the same yesterday,"], ["le aso,", "today,"], ["ma le faavavau,", "and forever,"], ["ma o nei meaalofa uma ua ou tautala atu ai,", "and that all these gifts of which I have spoken,"], ["ua faaleagaga,", "which are spiritual,"], ["o le a le aveesea lava,", "never will be done away,"], ["pe o le a lava le umi e tu ai le lalolagi,", "even as long as the world shall stand,"], ["ae nao le tusa ai ma le le talitonu o le fanauga a tagata.", "only according to the unbelief of the children of men."]]},
  {num:20,words:[["O le mea lea,", "Wherefore,"], ["e tatau ai ona i ai o le faatuatua ;", "there must be faith;"], ["ma afai e tatau ona i ai o le faatuatua e tatau foi ona i ai o le faamoemoe; ma afai e tatau ona i ai o le faamoemoe,", "and if there must be faith there must also be hope;"], ["e tatau foi ona i ai o le alofa mama.", "and if there must be hope there must also be charity."]]},
  {num:21,words:[["Ma e vagana ai ua ia te outou le alofa mama e le mafai lava i se ala ona faaolaina outou i le malo o le Atua;", "And except ye have charity ye can in nowise be saved in the kingdom of God;"], ["pe mafai foi ona faaolaina outou i le malo o le Atua pe afai e le ia te outou le faatuatua;", "neither can ye be saved in the kingdom of God if ye have not faith;"], ["pe mafai foi e outou pe afai e leai so outou faamoemoe.", "neither can ye if ye have no hope."]]},
  {num:22,words:[["Ma afai e leai so outou faamoemoe ua tatau ona outou lotovaivai;", "And if ye have no hope ye must needs be in despair;"], ["ma e oo mai le lotovaivai ona o le amioletonu.", "and despair cometh because of iniquity."]]},
  {num:23,words:[["Ma sa fetalai moni Keriso i o tatou tamā: Afai e ia te outou le faatuatua,", "And Christ truly said unto our fathers:"], ["e mafai ona outou faia o mea uma e tatau ia te au.", "If ye have faith ye can do all things which are expedient unto me."]]},
  {num:24,words:[["Ma ou te tautala atu nei i tuluiga uma o le lalolagi—afai e oo mai le aso e aveesea ai le mana ma meaalofa a le Atua mai totonu o outou,", "And now I speak unto all the ends of the earth—that if the day cometh that the power and gifts of God shall be done away among you,"], ["o le a faapea ona o le le talitonu.", "it shall be because of unbelief."]]},
  {num:25,words:[["Ma oi talofa i le fanauga a tagata pe afai o le tulaga lea;", "And wo be unto the children of men if this be the case;"], ["ona o le a leai se tasi i totonu o outou e faia le lelei, e leai,", "for there shall be none that doeth good among you,"], ["e leai lava se tasi.", "no not one."], ["Aua afai e i ai se tasi i totonu o outou e faia le lelei,", "For if there be one among you that doeth good,"], ["e galue o ia i le mana ma meaalofa a le Atua.", "he shall work by the power and gifts of God."]]},
  {num:26,words:[["Ma oi talofa ia te i latou o e latou te aveese nei mea ma feoti,", "And wo unto them who shall do these things away and die,"], ["ona latou te oti ia latou agasala ,", "for they die in their sins,"], ["ma e le mafai ona faaolaina i latou i le malo o le Atua;", "and they cannot be saved in the kingdom of God;"], ["ma ou te tautala atu lenei mea e tusa ma afioga a Keriso;", "and I speak it according to the words of Christ;"], ["ma ou te le pepelo lava.", "and I lie not."]]},
  {num:27,words:[["Ma ou te apoapoai atu ia te outou ia outou manatua nei mea;", "And I exhort you to remember these things;"], ["ona e vave ona oo mai o le taimi o le a outou iloa ai ou te le pepelo,", "for the time speedily cometh that ye shall know that I lie not,"], ["aua o le a outou vaai ia te au i le pa faamasino a le Atua;", "for ye shall see me at the bar of God;"], ["ma o le a fetalai mai le Alii le Atua ia te outou:", "and the Lord God will say unto you:"], ["Ou te lei alaga atu ea ia te outou au upu ,", "Did I not declare my words unto you,"], ["ia sa tusia e lenei tagata,", "which were written by this man,"], ["e pei o se tasi ua alaga mai e ua oti,", "like as one crying from the dead,"], ["ioe,", "yea,"], ["e pei lava o se tasi ua tautala mai i fafo mai i le efuefu ?", "even as one speaking out of the dust?"]]},
  {num:28,words:[["Ou te tautino atu nei mea i le faataunuuina o valoaga. Faauta foi,", "I declare these things unto the fulfilling of the prophecies. And behold,"], ["o le a tulei mai i latou mai le fofoga o le Atua tumau-faavavau;", "they shall proceed forth out of the mouth of the everlasting God;"], ["ma o le a uisa atu lana afioga mai lea tupulaga i lea tupulaga.", "and his word shall hiss forth from generation to generation."]]},
  {num:29,words:[["Ma o le a faaali atu e le Atua ia te outou,", "And God shall show unto you,"], ["ua moni mea ua ou tusia.", "that that which I have written is true."]]},
  {num:30,words:[["Ma ou te toe apoapoai atu ia te outou,", "And again I would exhort you that ye would come unto Christ,"], ["ia outou o mai ia Keriso,", "and lay hold upon every good gift,"], ["ma taofimau i meaalofa lelei uma, ma aua le pai atu i le meaalofa leaga,", "and touch not the evil gift,"], ["po o le mea ua le mama.", "nor the unclean thing."]]},
  {num:31,words:[["Ma ia ala mai,", "And awake,"], ["ma tulai mai i le efuefu,", "and arise from the dust,"], ["Ierusalema e;", "O Jerusalem;"], ["ioe,", "yea,"], ["ma ofu ou ofu matagofie,", "and put on thy beautiful garments, O daughter of Zion;"], ["le afafine e o Siona ;", "and strengthen thy stakes and enlarge thy borders forever,"], ["ma faamalolosi ou siteki ma faalautetele ou tuaoi e faavavau,", "that thou mayest no more be confounded,"], ["ina ia le toe faafelilonaiina oe,", "that the covenants of the Eternal Father which he hath made unto thee,"], ["ina ia mafai ona faataunuuina o feagaiga a le Tamā Faavavau na faia e ia ia te oe,", "O house of Israel,"], ["le aiga e o Isaraelu.", "may be fulfilled."]]},
  {num:32,words:[["Ioe,", "Yea,"], ["o mai ia Keriso,", "come unto Christ,"], ["ma faaatoatoaina ia te ia, ma faafiti outou lava mai mea uma e le faaleatua;", "and be perfected in him,"], ["ma afai tou te faafiti outou lava mai mea e le faaleatua uma,", "and deny yourselves of all ungodliness;"], ["ma alolofa i le Atua ma o outou manatu atoa,", "and if ye shall deny yourselves of all ungodliness and love God with all your might,"], ["mafaufau,", "mind and strength,"], ["ma le malosi atoa,", "then is his grace sufficient for you,"], ["ona lava lea o lona alofa tunoa mo outou, ma o lona alofa tunoa e mafai ai ona outou atoatoa ia Keriso;", "that by his grace ye may be perfect in Christ;"], ["ma afai tou te atoatoa ia Keriso e ala i le alofa tunoa o le Atua,", "and if by the grace of God ye are perfect in Christ,"], ["e leai se ala e mafai ai ona outou faafitia le mana o le Atua.", "ye can in nowise deny the power of God."]]},
  {num:33,words:[["Ma ou te toe fai atu,", "And again,"], ["afai tou te atoatoa ia Keriso e ala i le alofa tunoa o le Atua,", "if ye by the grace of God are perfect in Christ,"], ["ma lē faafitia lona mana,", "and deny not his power,"], ["ona faapaiaina lea o outou ia Keriso i le alofa tunoa o le Atua,", "then are ye sanctified in Christ by the grace of God,"], ["e ala i le faamaligiina o le toto o Keriso,", "through the shedding of the blood of Christ,"], ["lea ua i ai i le feagaiga a le Tamā mo le faamagaloina o a outou agasala,", "which is in the covenant of the Father unto the remission of your sins,"], ["ina ia outou paia ,", "that ye become holy,"], ["ua aunoa ma se ila.", "without spot."]]},
  {num:34,words:[["Ma o lenei ou te fai atu ia te outou uma,", "And now I bid unto all,"], ["tofa ia. Ua lata ona ou alu atu e malolo i le parataiso o le Atua,", "farewell. I soon go to rest in the paradise of God,"], ["seia toe faatasia lou agaga ma lou tino,", "until my spirit and body shall again reunite,"], ["ma aumai au i le ea ma le manumalo,", "and I am brought forth triumphant through the air,"], ["e feiloai ma outou i luma o le pa faamasino logomalie a le Ieova silisili,", "to meet you before the pleasing bar of the great Jehovah,"], ["le Faamasino Faavavau o e o ola ma e ua oti. Amene. Ua I'u", "the Eternal Judge of both quick and dead. Amen."]]},
];
renderVerseSet(mr_ch_10_Verses, 'mr-ch10-verses');

})();