(function() {
var _nah_ch_1_Verses = [
  {num:1,words:[["O le avega", "the burden"], ["ia Nineva.", "he Nineveh"], ["O le tusi", "the book"], ["o le fa'aaliga", "the revelation"], ["ia Nauma", "he Nahum"], ["le Elekosi.", "the Elekosi"]]},
  {num:2,words:[["O Ieova", "the LORD"], ["o le Atua fuā", "of God fruit"], ["ia,", "he"], ["o lē taui", "not a reward"], ["ma sui,", "and replace"], ["o Ieova o lē taui", "the LORD not a reward"], ["ma sui", "and replace"], ["ma lē matuā toasa;", "and not exceedingly wrath"], ["e taui", "a reward"], ["ma sui Ieova", "and replace the LORD"], ["i", "in"], ["e ita ia te ia,", "angry to him"], ["o loo fa'amoemoe foi", "is hope also"], ["o ia", "it/he/she"], ["i", "in"], ["e ua fai", "did"], ["o ia", "it/he/she"], ["ma o lātou", "and their"], ["fili.", "enemy"]]},
  {num:3,words:[["O Ieova e tele gese", "the LORD great slow"], ["lona toasa,", "his wrath"], ["a e tele", "but to great"], ["lona mana;", "his get"], ["na te", "he"], ["le fa'asaoina lava", "the spared very"], ["e ua agasala;", "sinned"], ["o Ieova o loo", "the LORD is"], ["i ai", "therein"], ["lona ala", "his way"], ["i le asiosio", "in the asiosio"], ["ma le afā,", "and the cyclone"], ["o ao", "day"], ["o le efuefu", "the dust"], ["ia", "he"], ["o", "o"], ["ona aao.", "and hand"]]},
  {num:4,words:[["E aoai e", "chastise by"], ["ia", "he"], ["i le sami,", "in the sea"], ["ma fa'amateina ai,", "and faamateina"], ["na te fa'amamateina foi", "he faamamateina also"], ["o vaitafe uma.", "river all"], ["E mamae Vasana", "by mamae Bashan"], ["ma Karamelu,", "and Carmel"], ["e mamae foi", "by mamae also"], ["fuga o Lepanona.", "flower of Lebanon"]]},
  {num:5,words:[["E gatete mauga", "tremble mountain"], ["ia te ia,", "to him"], ["e liu suāvai mauga iti;", "by liu water mountain small"], ["e mafuie", "by mafuie"], ["le eleele", "the earth"], ["i ona luma,", "before him"], ["o le lalolagi foi", "the world also"], ["atoa ma", "and"], ["i lātou uma", "them all"], ["o ē nonofo ai.", "whose dwelling"]]},
  {num:6,words:[["O ai", "O ai"], ["se tu", "a stand"], ["i luma", "in before"], ["o lona toasa?", "his wrath"], ["O ai", "O ai"], ["foi", "also"], ["se tu", "a stand"], ["i luga", "in above"], ["pe a tupu", "even though / although king"], ["lona maemaea?", "his maemaea"], ["Ua sasaa atu", "plurzH x)^ saasaa"], ["lona toatamai", "his toatamai"], ["e pei o le afi,", "like the fire"], ["ua fulisia papa", "fulisia rock"], ["e ia.", "he"]]},
  {num:7,words:[["O loo agalelei Ieova,", "is kindness the LORD"], ["o le 'olo", "the trench"], ["ia", "he"], ["i le aso", "in the day"], ["o le puapuaga;", "the affliction"], ["o loo silafia", "is know"], ["e ia", "he"], ["e o fa'atuatua", "by of faith"], ["ia te ia.", "to him"]]},
  {num:8,words:[["O le tafe", "the flow"], ["e lofia ai", "by lofia"], ["na te fa'aumatia ai", "he destroyed"], ["le mea o", "the thing of"], ["i ai", "therein"], ["le aai,", "the cities"], ["e tuliloaina", "pursued"], ["e le pouliuli", "shall not darkness"], ["e ua ita", "angry"], ["ia te ia.", "to him"]]},
  {num:9,words:[["Se a ea", "what indeed? / why?"], ["se mea", "a thing"], ["ua outou mafaufau ai", "you all thought"], ["ia Ieova?", "he the LORD"], ["E fa'aumatia lava", "destroyed very"], ["e ia;", "he"], ["e le tupu fa'alua", "shall not king twice"], ["mai le puapuaga.", "from the affliction"]]},
  {num:10,words:[["E ui lava", "although very"], ["ina filia", "so that filia"], ["i lātou", "them"], ["e pei o lā'au talatala,", "like tree untie"], ["ma lātou matuā onā", "and they exceedingly drunk"], ["i le inugāuaina,", "in the inugāuaina"], ["a e fa'aumatia", "but to destroyed"], ["i lātou pei", "them like"], ["o tagutugutu o saito", "tagutugutu of wheat"], ["e matuā magumagu", "exceedingly withered"], ["lava.", "very"]]},
  {num:11,words:[["Ua sau mai ia te oe", "came unto you"], ["o ia", "it/he/she"], ["o le", "the"], ["ua mafaufau", "thought"], ["i mea leaga", "things evil"], ["e faia ia", "do he"], ["Ieova,", "the LORD"], ["o le faipule amio leaga.", "the a councillor iniquity"]]},
  {num:12,words:[["O loo fa'apea mai", "saying from"], ["Ieova,", "the LORD"], ["E ui lava", "although very"], ["ina atoatoa", "so that completely"], ["i lātou,", "them"], ["ma", "and"], ["ua fa'apea ona", "saying and"], ["toatele,", "many"], ["a e fa'apea lava ona", "but saying just to"], ["fāsia", "slaughtered"], ["i lātou,", "them"], ["ona mavae atu ai lea", "and passed then"], ["o ia.", "it/he/she"], ["Na aʻu fa'atigaina oe;", "me afflicted you"], ["a e ou te", "but to I will"], ["le toe fa'atigaina oe.", "the again afflicted you"]]},
  {num:13,words:[["Auā ou te gauia nei", "do not I will was to break these"], ["lana amo o ia te oe,", "his carry it you"], ["ou te motusi foi", "I will motusi also"], ["ou noanoaga.", "I bonds"]]},
  {num:14,words:[["Ua fetalai Ieova ia te oe,", "said the LORD unto you"], ["E le toe totōina nisi", "shall not again planted some"], ["o lou igoa;", "your name"], ["ou te vavaeeseina", "I will cut off"], ["le tupua", "the pillar"], ["ua tā", "struck"], ["ma le tupua uamea", "and the pillar iron"], ["i le fale", "in the house"], ["o ou atua;", "I God"], ["ou te fai ai", "I will do"], ["lou tuugamau;", "your grave"], ["auā", "for"], ["ua leaga lava oe.", "evil very you"]]},
  {num:15,words:[["Fa'auta ea,", "behold"], ["o", "o"], ["i luga o mauga", "upon mountain"], ["o vae o lē fai mai le tala lelei,", "foot of not said the gospel"], ["o lē logologo", "not hear"], ["mai", "from"], ["i le manuia;", "in the prosper"], ["Iuta e,", "Judas"], ["ia e fai aʻu", "he to do me"], ["tausamiga,", "feast"], ["ia e avatu", "he to give away"], ["mea", "thing"], ["na e tauto ai;", "you swore"], ["auā", "for"], ["e le toe ui atu", "shall not again although"], ["lava ia te oe", "very unto you"], ["le tagata amio leaga;", "the man iniquity"], ["ua matuā fano", "exceedingly perished"], ["o ia.", "it/he/she"]]},
];
renderVerseSet(_nah_ch_1_Verses, 'nah-ch1-verses');

var _nah_ch_2_Verses = [
  {num:1,words:[["Ua alu ae", "went up"], ["i ou lava luma", "in I very before"], ["le", "the"], ["na te fa'ataapeapeina;", "he scattered"], ["ina leoleo ia", "so that guard he"], ["le 'olo,", "the trench"], ["vaavaai", "looked around"], ["i le ala,", "in the way"], ["ia fusi ae", "he belt up"], ["sulugatiti,", "the place where the"], ["ia matuā fa'ateleina", "he exceedingly multiplied"], ["lou malosi.", "your strong"]]},
  {num:2,words:[["Auā", "do not"], ["e ui lava", "although very"], ["ina tafia", "so that tafia"], ["i lātou e", "them by"], ["i lātou", "them"], ["o ē tafi,", "whose brush"], ["ma lātou fa'ataumaoi foi", "and they faataumaoi also"], ["a lātou lā lā'au,", "their sun tree"], ["a e toe fa'afoisia", "but to again restored"], ["e Ieova", "the LORD"], ["le mamalu o Iakopo,", "the glory of Jacob"], ["e fa'apea foi", "saying also"], ["le mamalu o Isaraelu.", "the glory of Israel"]]},
  {num:3,words:[["O talita", "shield"], ["o", "o"], ["ona tagata totoa", "and man p'ural o( fnt"], ["ua fa'alanu ulaula ia,", "made color joke he"], ["o tagata fitafita foi", "men policeman also"], ["ua oofu", "oofu"], ["i lātou", "them"], ["i ofu mūmū;", "in garment scarlet"], ["e fepulafi fa'aafi", "by fepulafi make fire"], ["o uamea o kariota", "iron of chariot"], ["i le aso", "in the day"], ["e sauniuni ai", "prepared"], ["o ia;", "it/he/she"], ["e fuafua foi", "abscesses in the hands or also"], ["o lātou tao.", "their spear"]]},
  {num:4,words:[["E matuā feasofai kariota", "exceedingly visit one another chariot"], ["i ala tele,", "in way great"], ["e soona fetaufetuliai", "without form contend with one another"], ["i malae;", "in the"], ["e tino mai pei", "body from like"], ["o sulu,", "graft"], ["e tele vavave pei", "great quick like"], ["o le uila.", "the uila"]]},
  {num:5,words:[["Ua manatua e", "remembered by"], ["ia", "he"], ["ona ali'i sili,", "and Lord most"], ["ua lātou tautevateva", "they tautevateva"], ["i lo lātou sāvali,", "than they walk"], ["ua lātou fa'atelelise", "they faatelelise"], ["i lona pa,", "in his wall"], ["ua saunia foi", "prepared also"], ["le talipupuni.", "the shield"]]},
  {num:6,words:[["Ua tatalaina puipui", "opened gate"], ["o vaitafe,", "river"], ["ua sŏloia foi", "sŏloia also"], ["le maota.", "the name of a tree"]]},
  {num:7,words:[["Na fa'atumauina o ia", "established it"], ["a", "but"], ["ua fa'alelavalavaina,", "made naked"], ["ua ta'ita'iina ae", "led up"], ["o ia,", "it/he/she"], ["ua gaegae foi", "gaegae also"], ["ana auauna fafine", "cave maidservant"], ["e pei o leo", "like voice"], ["o lupe,", "dove"], ["lātou te taufaitu'i", "they will taufaitu'i"], ["i o lātou", "in their"], ["fatafata.", "breast"]]},
  {num:8,words:[["O Nineva foi", "Nineveh also"], ["na fa'apei", "like"], ["o le vailepa", "the vailepa"], ["ia talu mai", "he since from"], ["anamua,", "ancient"], ["a", "but"], ["ua lātou sosola lava.", "they fled very"], ["Tutū mai ia,", "stood up from he"], ["ina tutū mai;", "so that stood up from"], ["a e leai se tepa", "but there is no look towards"], ["i tua.", "in behind"]]},
  {num:9,words:[["Ia outou vete", "he you all plunder"], ["ario,", "silver"], ["ina vete ia", "so that plunder he"], ["o auro;", "gold"], ["e le uma", "shall not all"], ["le oloa lelei,", "not goods good"], ["ua faulai mea uma", "faulai all things"], ["e manaomia.", "desired"]]},
  {num:10,words:[["Ua gaogao,", "void"], ["ua fa'agaogaoina,", "made void"], ["ua fa'atafunaina;", "destroyed"], ["ua fa'avaivai", "weakened"], ["le loto,", "not heart"], ["ua gatete tulivae,", "tremble tulivae"], ["ua tiga tele", "grieved great"], ["tua uma,", "behind all"], ["o lātou mata uma foi", "their eye all also"], ["ua matamatavale.", "matamatavale"]]},
  {num:11,words:[["O ifea ea", "where?"], ["le ana o leona,", "the cave of lion"], ["ma le mea", "and the thing"], ["na aai ai", "cities"], ["leona taanoa,", "lion an animal that is weaned"], ["o le mea", "the thing"], ["na fealuai ai", "walked about"], ["le leona,", "the lion"], ["le leona avilu,", "the lion stunted"], ["atoa ma le tamai leona,", "and the son lion"], ["e leai foi", "there is not also"], ["se tasi", "a one"], ["na fa'amatau atu ai?", "made ax"]]},
  {num:12,words:[["Na saei", "tore"], ["e le leona", "shall not lion"], ["ia maoona ai", "he maoona"], ["ana fānau,", "cave born"], ["ua", "ua"], ["na titina manu foi", "strangle animal also"], ["mo ana leona fafine,", "for cave lion women"], ["ua", "ua"], ["na fa'atumuina", "filled"], ["ona lua", "and two"], ["i mea", "things"], ["na maua,", "received"], ["o", "o"], ["ona ana foi", "and cave also"], ["ua fa'atumuina ia", "filled he"], ["i mea", "things"], ["ua saeia.", "spared"]]},
  {num:13,words:[["O loo fa'apea mai", "saying from"], ["o Ieova o 'au,", "the LORD troops"], ["Fa'auta,", "behold"], ["ou te tetee", "I will refuse"], ["ia te oe,", "unto you"], ["ou te susunu foi", "I will burn also"], ["ia liu asu", "he liu asu"], ["ona kariota,", "and chariot"], ["e fa'aumatia aʻu", "destroyed me"], ["leona taanoa", "lion an animal that is weaned"], ["i le pelu;", "by the sword"], ["ou te aveeseina foi", "I will carried away also"], ["i le nu'u aʻu", "in the land me"], ["mea", "thing"], ["na saeia;", "spared"], ["e le toe lagona foi", "shall not again feel also"], ["leo o aʻu", "voice I am"], ["sāvali.", "walk"]]},
];
renderVerseSet(_nah_ch_2_Verses, 'nah-ch2-verses');

var _nah_ch_3_Verses = [
  {num:1,words:[["Oi talofa", "wo"], ["i le aai", "in the cities"], ["o ē fasi tagata!", "whose kill man"], ["ua tumu lava", "filled very"], ["i le pepelo", "in the false"], ["ma le saua;", "and the cruel"], ["ua", "ua"], ["le aveeseina ai", "the carried away"], ["lava", "very"], ["le mea", "the thing"], ["na saeia.", "spared"]]},
  {num:2,words:[["O le paō", "the paō"], ["o le sasa,", "the a scourge"], ["o le taalili", "the resounding"], ["o mea taavalevale,", "thing taavalevale"], ["o solofanua", "horse"], ["ua feasofai,", "visit one another"], ["ma kariota", "and chariot"], ["ua osooso.", "sat"]]},
  {num:3,words:[["Ua", "Ua"], ["i ai", "therein"], ["le oso ae", "not rose up"], ["o ē ua tietie", "who ride"], ["i solofanua,", "in horse"], ["ma le fepulafi", "and the fepulafi"], ["mai o pelu,", "from of sword"], ["o le emoemo", "the emoemo"], ["mai foi", "from also"], ["o tao;", "spear"], ["o le toatele foi", "the many also"], ["o ē ua fāsia,", "who slaughtered"], ["ma le faupuega", "and the plan"], ["o tagata oti;", "men die"], ["e le masino tagata oti,", "by the masino man die"], ["ua lātou tautevateva", "they tautevateva"], ["i o lātou", "in their"], ["tagata oti.", "man die"]]},
  {num:4,words:[["Ona", "and"], ["o le tele", "the great"], ["o le talitane", "the harlot"], ["o le fafine talitane", "the women harlot"], ["o le", "the"], ["ua lalelei,", "beautiful"], ["o le tamaitai taulāitu,", "the woman taulāitu"], ["o le", "the"], ["ua fa'atau atu", "bought"], ["nu'u", "nation"], ["i lona talitane", "in his harlot"], ["atoa ma 'āiga", "and family"], ["o ana togafiti fa'ataulāitu.", "cave heal faataulāitu"]]},
  {num:5,words:[["O loo fa'apea mai", "saying from"], ["Ieova o 'au,", "the LORD of troops"], ["Fa'auta,", "behold"], ["ou te fai oe", "I will do you"], ["mo'u fili,", "many enemy"], ["ou te susue", "I will a hsh"], ["ae foi", "but also"], ["ou lavalava,", "I alternative form of lava-lava"], ["ma lafo ae", "and cloth used as gratuity for a talking chief up"], ["i ou mata,", "in I eye"], ["ou te fa'aali atu", "I will revealed"], ["lou tino", "your body"], ["i atu nu'u,", "in nation"], ["e fa'aali foi", "revealed also"], ["lou mā", "your and"], ["i mālō.", "in kingdom"]]},
  {num:6,words:[["Ou te lafo mea leaga", "I will cloth used as gratuity for a talking chief thing evil"], ["i luga ia te oe,", "in above unto you"], ["ou te fa'ainosia foi", "I will make abominable also"], ["oe,", "you"], ["ma ou faia oe", "and I do you"], ["ma mataaga.", "and be se[)arc*ted (as the"]]},
  {num:7,words:[["Ona oo ai lea", "and oo then"], ["ina sosola ese", "so that fled away"], ["ia te oe", "unto you"], ["o", "o"], ["i lātou uma", "them all"], ["o ē vaai atu", "whose looked toward"], ["ia te oe,", "unto you"], ["ma lātou fa'apea ane,", "and they saying"], ["Ua fa'atafunaina Nineva!", "destroyed Nineveh"], ["o ai", "o ai"], ["se fa'amafanafana", "a hearten"], ["i ai?", "therein"], ["Po ifea ou te saili ai", "night where? I will seek"], ["nisi", "some"], ["e fa'amatalaloto ia te oe?", "by faamatalaloto unto you"]]},
  {num:8,words:[["Pe sili ea oe", "whether most you"], ["ia Noamoni,", "he Noamoni"], ["o le", "the"], ["sa nofo", "dwelt"], ["i vaitafe,", "in river"], ["sa siomia foi", "surrounded also"], ["i le vai,", "in the water"], ["o lona malosi", "his strong"], ["o le vai tele lea,", "the water great"], ["sa", "sa"], ["i ai", "therein"], ["lona pa", "his wall"], ["i le vai tele?", "in the water great"]]},
  {num:9,words:[["O Aitiope", "Aitiope"], ["o lona malosi lea,", "his strong"], ["atoa ma Aikupito,", "and Egypt"], ["sa", "sa"], ["le masino foi", "the masino also"], ["ona tagata;", "and man"], ["o Futu", "Futu"], ["ma Lipua o ou fesoasoani", "and Lipua of I help"], ["ia.", "he"]]},
  {num:10,words:[["A", "but"], ["ua tāfea o ia,", "exiled it"], ["ua alu o ia", "went it"], ["fa'atasi ma", "together and"], ["e ua fa'atagataotauaina;", "captivity"], ["o ana tama iti foi", "cave child small also"], ["sa palasi", "had children in"], ["i tuluiga o ala uma;", "in anointing of way all"], ["sa fai foi", "did also"], ["le vili", "the a gimblet"], ["i ona ali'i mamalu,", "in his Lord glory"], ["sa nonoa foi", "tied also"], ["ona ali'i sili uma", "and Lord most all"], ["i maea uamea.", "in rope iron"]]},
  {num:11,words:[["O oe foi", "you also"], ["e te inu", "you drink"], ["ia onā;", "he drunk"], ["e te lafi", "you lafi"], ["lava;", "very"], ["o oe foi", "you also"], ["e te saili", "you seek"], ["se 'olo", "a trench"], ["ona", "and"], ["o le", "the"], ["ua ita ia te oe.", "angry unto you"]]},
  {num:12,words:[["O ou 'olo uma", "I trench all"], ["ua ni mati ia,", "some fig he"], ["o loo", "is/are"], ["i ai", "therein"], ["fua", "fruit"], ["e muai mātua;", "first great"], ["'āfai", "if"], ["e luluina,", "shaken"], ["ona toulu ai lea", "and toulu then"], ["i le gutu", "in the mouth"], ["o le 'ai ai.", "the eat"]]},
  {num:13,words:[["Fa'auta,", "behold"], ["o lou nu'u", "your nation"], ["i totonu ia te oe", "within unto you"], ["ua ni fafine lava,", "some women very"], ["e matuā avanoa faitotoa", "exceedingly an open space door"], ["o lou nu'u", "your nation"], ["i", "in"], ["e o fai oe", "by of do you"], ["ma fili,", "and enemy"], ["e susunuina aʻu", "burned me"], ["fa'amaufaalava", "faamaufaalava"], ["i le afi.", "in the fire"]]},
  {num:14,words:[["Ia e utuina", "he to todraw water"], ["vai,", "water"], ["auā", "for"], ["o le a siosioina oe,", "what surrounded you"], ["ina teu ia ia", "so that store to him"], ["malolosi ou 'olo;", "mighty I trench"], ["alu ia", "go he"], ["i le palapala,", "in the blood"], ["ina soli ia", "so that tread upon he"], ["le omea,", "the mortar"], ["ia teu ia", "he store he"], ["malosi", "strong"], ["le mea", "the thing"], ["e tunu ai", "roast"], ["maaomea.", "maaomea"]]},
  {num:15,words:[["E susunuina oe", "burned you"], ["i le afi", "in the fire"], ["i lea", "in"], ["mea,", "thing"], ["e fasia oe", "slaughtered you"], ["i le pelu,", "by the sword"], ["na te 'aina lava oe", "he edible very you"], ["pei o le sē aleka,", "like the a aleka"], ["ia fa'atoateleina oe", "he make many you"], ["pei o sē aleka,", "like of a aleka"], ["ia fa'atoateleina oe", "he make many you"], ["pei o sē akerise.", "like of a akerise"]]},
  {num:16,words:[["Ua e fa'atoateleina", "you made many"], ["ou tagata fa'atau", "I man buy"], ["e sili", "preferred"], ["i fetu", "in star"], ["o le lagi;", "Heaven"], ["ua salalau sē", "was scattered a"], ["aleka,", "aleka"], ["ona lele ese ai lea.", "and fly away then"]]},
  {num:17,words:[["O ou ali'i sili", "I Lord most"], ["e pei o sē akerise", "like a akerise"], ["ia,", "he"], ["ma ou ali'i e", "and I Lord by"], ["pulea 'au", "was rule troops"], ["e pei o sē akerise aupito tetele", "like a akerise ^ to be great"], ["ia,", "he"], ["o ē nonofo", "whose dwelling"], ["i āi", "in thereof"], ["i le aso maalili,", "in the day maalili"], ["ua alu ae", "went up"], ["le lā,", "the sun"], ["ona sosola ai lea,", "and fled then"], ["e le iloa foi", "shall not know also"], ["le mea lātou te", "the thing they will"], ["i ai.", "therein"]]},
  {num:18,words:[["Le tupu o Asuria e,", "the king of Assyria"], ["o loo momoe ou", "is lie down I"], ["leoleo mamoe,", "shepherd"], ["o taooto ou ali'i sili;", "lie down I Lord most"], ["ua fa'ataapeapeina", "scattered"], ["lou nu'u", "your nation"], ["i mauga,", "in mountain"], ["e leai foi", "there is not also"], ["se", "a"], ["na te fa'apotopotoina", "he gathered together"], ["i lātou .", "them"]]},
  {num:19,words:[["E leai sina feoloolo", "there is not white feoloolo"], ["o lou malaia,", "your disaster"], ["e matuā leaga", "exceedingly evil"], ["lou manua;", "your was animal"], ["o", "o"], ["i lātou uma", "them all"], ["o ē fa'alogologo", "whose listen"], ["i le tala", "in the side"], ["ia te oe,", "unto you"], ["lātou te pati lima", "they will pati hand"], ["ia te oe;", "unto you"], ["auā o ai", "for"], ["se tasi", "a one"], ["ua", "ua"], ["le oo", "the oo"], ["i ona luga", "in his above"], ["lau amio leaga", "your iniquity"], ["e le aunoa?", "shall not without"]]},
];
renderVerseSet(_nah_ch_3_Verses, 'nah-ch3-verses');

})();