(function() {
var nah_ch_1_Verses = [
  {num:1,words:[["O le avega ia Nineva.", "the avega to nineva"], ["O le tusi", "the book"], ["o le faaaliga ia Nauma", "the revelation to nauma"], ["le Elekosi.", "the elekosi"]]},
  {num:2,words:[["O Ieova", "Jehovah"], ["o le Atua fuā ia,", "of God fuā to"], ["o lē taui", "not a reward"], ["ma sui,", "and to dilute"], ["o Ieova o lē taui", "Jehovah not a reward"], ["ma sui", "and to dilute"], ["ma lē matuā toasa;", "and not very wrath"], ["e taui", "to a reward"], ["ma sui Ieova", "and to dilute Jehovah"], ["i e ita ia te", "in to angry unto"], ["ia,", "to"], ["o loo faamoemoe foi o", "to expect also"], ["ia i", "to in"], ["e ua fai o ia", "by make he"], ["ma o latou fili.", "and them to choose"]]},
  {num:3,words:[["O Ieova", "Jehovah"], ["e tele gese lona toasa,", "to great slow his wrath"], ["a e tele lona mana;", "but to great his to get"], ["na te", "na te"], ["le faasaoina lava", "the saved indeed"], ["e ua agasala;", "by sin"], ["o Ieova o loo", "Jehovah"], ["i ai lona ala", "therein his arise"], ["i le asiosio", "in the asiosio"], ["ma le afā,", "and the cyclone"], ["o ao", "day"], ["o le efuefu ia o", "the efuefu to"], ["ona aao.", "and hand (extended)"]]},
  {num:4,words:[["E aoai", "by aoai"], ["e ia", "by him"], ["i le sami,", "in the sea"], ["ma faamateina ai,", "and faamateina"], ["na te faamamateina foi o vaitafe uma.", "faamamateina also river all"], ["E mamae Vasana", "by mamae vasana"], ["ma Karamelu,", "and karamelu"], ["e mamae foi fuga o Lepanona.", "by mamae also flower lepanona"]]},
  {num:5,words:[["E gatete mauga ia te", "by gatete mountain unto"], ["ia,", "to"], ["e liu suāvai mauga iti;", "by liu suāvai mountain iti"], ["e mafuie", "by mafuie"], ["le eleele", "the earth"], ["i ona luma,", "before him"], ["o le lalolagi foi", "the earth also"], ["atoa ma", "and"], ["i latou uma o", "them all"], ["e nonofo ai.", "to dwelling"]]},
  {num:6,words:[["O ai", "o ai"], ["se tu", "a stand"], ["i luma o lona toasa?", "before his wrath"], ["O ai foi", "also"], ["se tu", "a stand"], ["i luga", "in above"], ["pe a tupu lona maemaea?", "whether but grow his maemaea"], ["Ua sasaa atu lona toatamai", "plurzH x)^ saasaa his toatamai"], ["e pei", "to to be broken"], ["o le afi,", "the fire"], ["ua fulisia papa", "fulisia burster"], ["e ia.", "by him"]]},
  {num:7,words:[["O loo agalelei Ieova,", "goodness Jehovah"], ["o le 'olo ia", "the fortress to"], ["i le aso", "in the day"], ["o le puapuaga;", "the pain"], ["o loo silafia", "seen"], ["e ia", "by him"], ["e o faatuatua ia te", "by faith unto"], ["ia.", "to"]]},
  {num:8,words:[["O le tafe", "the to flow"], ["e lofia ai", "by lofia"], ["na te faaumatia ai", "destroy"], ["le mea o", "the thing"], ["i ai", "therein"], ["le aai,", "the eat"], ["e tuliloaina", "by tuliloaina"], ["e le pouliuli", "by the darkness"], ["e ua ita ia te", "by angry unto"], ["ia.", "to"]]},
  {num:9,words:[["Se a ea", "a but to rise (as a diver to the sur-"], ["se mea", "a thing"], ["ua outou mafaufau ai ia Ieova?", "ye all think to Jehovah"], ["E faaumatia lava", "to destroy indeed"], ["e ia;", "by him"], ["e le tupu faalua", "by the grow faalua"], ["mai le puapuaga.", "from the pain"]]},
  {num:10,words:[["E ui lava", "to although indeed"], ["ina filia", "let filia"], ["i latou", "them"], ["e pei o laau talatala,", "to to be broken tree to untie"], ["ma latou matuā onā", "and them very onā"], ["i le inugāuaina,", "in the inugāuaina"], ["a e faaumatia", "but to destroy"], ["i latou pei o tagutugutu", "them to be broken tagutugutu"], ["o saito", "wheat"], ["e matuā magumagu lava.", "to very magumagu indeed"]]},
  {num:11,words:[["Ua sau mai ia te oe", "come unto thee"], ["o ia", "he"], ["o le", "the"], ["ua mafaufau", "think"], ["i mea leaga", "in thing evil"], ["e faia ia Ieova,", "to made to Jehovah"], ["o le faipule amio leaga.", "the a councillor iniquity"]]},
  {num:12,words:[["O loo faapea", "thus"], ["mai Ieova,", "from Jehovah"], ["E ui lava", "to although indeed"], ["ina atoatoa", "let completely"], ["i latou,", "them"], ["ma ua faapea", "and saying"], ["ona toatele,", "and many"], ["a e faapea lava", "but by thus indeed"], ["ona fāsia", "and fāsia"], ["i latou,", "them"], ["ona mavae atu ai lea", "and a parting"], ["o ia.", "he"], ["Na a'u faatigaina oe;", "I faatigaina you"], ["a e ou te", "but to I"], ["le toe faatigaina oe.", "the again faatigaina you"]]},
  {num:13,words:[["Auā ou te gauia nei lana amo", "for I gauia this his amo"], ["o ia te oe,", "he you"], ["ou te motusi foi ou noanoaga.", "I motusi also I bonds"]]},
  {num:14,words:[["Ua fetalai Ieova ia te oe,", "said Jehovah unto thee"], ["E le toe totōina nisi", "by the again totōina some"], ["o lou igoa;", "your name"], ["ou te vavaeeseina", "I vavaeeseina"], ["le tupua", "the idol"], ["ua ta", "a stroke"], ["ma le tupua uamea", "and the idol uamea"], ["i le fale o ou atua;", "in the house I God"], ["ou te fai ai lou tuugamau;", "I make your tuugamau"], ["auā ua leaga lava oe.", "for evil indeed you"]]},
  {num:15,words:[["Faauta ea,", "behold to rise (as a diver to the sur-"], ["o i luga o mauga", "upon mountain"], ["o vae o lē fai", "foot not make"], ["mai le tala lelei,", "from the gospel"], ["o lē logologo", "not logologo"], ["mai i le manuia;", "from in the peace"], ["Iuta e,", "Judas by"], ["ia e fai au tausamiga,", "to to make I tausamiga"], ["ia e avatu mea", "to to give away thing"], ["na e tauto ai;", "to to take an oath"], ["auā e le toe ui atu", "for by the again although"], ["lava ia te oe", "indeed unto thee"], ["le tagata amio leaga;", "the man iniquity"], ["ua matuā fano o ia.", "very perish he"]]},
];
renderVerseSet(nah_ch_1_Verses, 'nah-ch1-verses');

var nah_ch_2_Verses = [
  {num:1,words:[["Ua alu", "go"], ["ae i ou lava luma", "but in I indeed before"], ["le na te faataapeapeina;", "the faataapeapeina"], ["ina leoleo ia le 'olo,", "let police to the fortress"], ["vaavaai i le ala,", "vaavaai in the arise"], ["ia fusi", "to fusi"], ["ae sulugatiti,", "but the place where the"], ["ia matuā faateleina lou malosi.", "to very faateleina your strong"]]},
  {num:2,words:[["Auā e ui lava", "for to although indeed"], ["ina tafia", "let tafia"], ["i latou", "them"], ["e i latou o", "by them"], ["e tafi,", "to to brush"], ["ma latou faataumaoi foi", "and them faataumaoi also"], ["a latou la laau,", "but them la tree"], ["a e toe faafoisia", "but to again faafoisia"], ["e Ieova", "to Jehovah"], ["le mamalu o Iakopo,", "the glory James"], ["e faapea foi", "by thus also"], ["le mamalu o Isaraelu.", "the glory Israel"]]},
  {num:3,words:[["O talita o", "talita"], ["ona tagata totoa", "and man p'ural o( fnt"], ["ua faalanu ulaula ia,", "faalanu ulaula to"], ["o tagata fitafita foi", "man policeman also"], ["ua oofu", "oofu"], ["i latou", "them"], ["i ofu mūmū;", "in garment mūmū"], ["e fepulafi faaafi o uamea", "by fepulafi faaafi uamea"], ["o kariota", "kariota"], ["i le aso", "in the day"], ["e sauniuni ai o ia;", "by sauniuni he"], ["e fuafua foi o latou tao.", "to abscesses in the hands or also them spear"]]},
  {num:4,words:[["E matuā feasofai kariota", "to very feasofai kariota"], ["i ala tele,", "in arise great"], ["e soona fetaufetuliai", "to without form fetaufetuliai"], ["i malae;", "in the"], ["e tino mai pei o sulu,", "to body from to be broken a torch"], ["e tele vavave pei", "to great vavave to be broken"], ["o le uila.", "the uila"]]},
  {num:5,words:[["Ua manatua", "remember"], ["e ia", "by him"], ["ona alii sili,", "and Lord most"], ["ua latou tautevateva", "them tautevateva"], ["i lo latou savali,", "in the them walk"], ["ua latou faatelelise", "them faatelelise"], ["i lona pa,", "in his a wall"], ["ua saunia foi", "prepared also"], ["le talipupuni.", "the talipupuni"]]},
  {num:6,words:[["Ua tatalaina puipui o vaitafe,", "tatalaina a duor river"], ["ua sŏloia foi", "sŏloia also"], ["le maota.", "the the name of a tree"]]},
  {num:7,words:[["Na faatumauina o ia ,", "faatumauina he"], ["a ua faalelavalavaina,", "but faalelavalavaina"], ["ua ta'ita'iina", "ta'ita'iina"], ["ae o ia,", "but he"], ["ua gaegae foi ana auauna fafine", "gaegae also his servant woman"], ["e pei o leo o lupe,", "to to be broken voice dove"], ["latou te taufaitu'i", "them taufaitu'i"], ["i o latou fatafata.", "in them fatafata"]]},
  {num:8,words:[["O Nineva foi", "nineva also"], ["na faapei", "like"], ["o le vailepa ia talu", "the vailepa to since"], ["mai anamua,", "from anamua"], ["a ua latou sosola lava.", "but them fled indeed"], ["Tutū mai ia,", "tutū from to"], ["ina tutū mai;", "let tutū from"], ["a e leai", "but there is not"], ["se tepa", "a to look towards"], ["i tua.", "in behind"]]},
  {num:9,words:[["Ia outou vete ario,", "to ye all vete silver"], ["ina vete ia o auro;", "let vete to gold"], ["e le uma", "by the all"], ["le oloa lelei,", "the goods good"], ["ua faulai mea uma", "faulai all things"], ["e manaomia.", "by manaomia"]]},
  {num:10,words:[["Ua gaogao,", "void"], ["ua faagaogaoina,", "faagaogaoina"], ["ua faatafunaina;", "faatafunaina"], ["ua faavaivai", "faavaivai"], ["le loto,", "the heart"], ["ua gatete tulivae,", "gatete tulivae"], ["ua tiga tele tua uma,", "pain great behind all"], ["o latou mata uma foi", "them eye all also"], ["ua matamatavale.", "matamatavale"]]},
  {num:11,words:[["O ifea ea", "ifea to rise (as a diver to the sur-"], ["le ana o leona,", "the his leona"], ["ma le mea", "and the thing"], ["na aai ai leona taanoa,", "eat leona an animal that is weaned"], ["o le mea", "the thing"], ["na fealuai ai", "fealuai"], ["le leona,", "the leona"], ["le leona avilu,", "the leona stunted"], ["atoa ma le tamai leona,", "and the son leona"], ["e leai foi", "there is not also"], ["se tasi", "a one"], ["na faamatau atu ai?", "faamatau"]]},
  {num:12,words:[["Na saei", "to tear"], ["e le leona ia maoona ai ana fanau,", "by the leona to maoona his born"], ["ua na titina manu foi", "to strangle animal also"], ["mo ana leona fafine,", "for his leona woman"], ["ua na faatumuina", "faatumuina"], ["ona lua", "and two"], ["i mea", "in thing"], ["na maua,", "received"], ["o ona ana foi", "then his also"], ["ua faatumuina ia", "faatumuina to"], ["i mea", "in thing"], ["ua saeia.", "saeia"]]},
  {num:13,words:[["O loo faapea", "thus"], ["mai o Ieova o 'au,", "from Jehovah I"], ["Faauta,", "behold"], ["ou te tetee ia te oe,", "I to refuse unto thee"], ["ou te susunu foi ia liu asu", "I burn also to liu asu"], ["ona kariota,", "and kariota"], ["e faaumatia au leona taanoa", "to destroy I leona an animal that is weaned"], ["i le pelu;", "in the a sword"], ["ou te aveeseina foi", "I aveeseina also"], ["i le nuu au mea", "in the land I thing"], ["na saeia;", "saeia"], ["e le toe lagona foi leo", "by the again to understand also voice"], ["o au sāvali.", "I am sāvali"]]},
];
renderVerseSet(nah_ch_2_Verses, 'nah-ch2-verses');

var nah_ch_3_Verses = [
  {num:1,words:[["Oi talofa", "alas ! oh ! hello"], ["i le aai o", "in the eat"], ["e fasi tagata!", "to kill man"], ["ua tumu lava", "fill indeed"], ["i le pepelo", "in the false"], ["ma le saua;", "and the to have a return of sick-"], ["ua le aveeseina ai lava", "the aveeseina indeed"], ["le mea", "the thing"], ["na saeia.", "saeia"]]},
  {num:2,words:[["O le paō", "the paō"], ["o le sasa,", "the a scourge"], ["o le taalili o mea taavalevale,", "the resounding thing taavalevale"], ["o solofanua", "horse"], ["ua feasofai,", "feasofai"], ["ma kariota", "and kariota"], ["ua osooso.", "osooso"]]},
  {num:3,words:[["Ua i ai", "therein"], ["le oso", "the food for a journey"], ["ae o", "but"], ["e ua tietie", "by tietie"], ["i solofanua,", "in horse"], ["ma le fepulafi", "and the fepulafi"], ["mai o pelu,", "from a sword"], ["o le emoemo", "the emoemo"], ["mai foi o tao;", "from also spear"], ["o le toatele foi o", "the many also"], ["e ua fāsia,", "by fāsia"], ["ma le faupuega o tagata oti;", "and the faupuega man die"], ["e le masino tagata oti,", "by the masino man die"], ["ua latou tautevateva", "them tautevateva"], ["i o latou tagata oti.", "in them man die"]]},
  {num:4,words:[["Ona o le tele", "because of the great"], ["o le talitane", "the talitane"], ["o le fafine talitane", "the woman talitane"], ["o le", "the"], ["ua lalelei,", "lalelei"], ["o le tamaitai taulāitu,", "the woman taulāitu"], ["o le", "the"], ["ua faatau atu nuu", "equally nation"], ["i lona talitane", "in his talitane"], ["atoa ma aiga o ana togafiti faataulāitu.", "and family his heal faataulāitu"]]},
  {num:5,words:[["O loo faapea", "thus"], ["mai Ieova o 'au,", "from Jehovah I"], ["Faauta,", "behold"], ["ou te fai oe mo'u fili,", "I make you many to choose"], ["ou te susue", "I susue"], ["ae foi ou lavalava,", "but also I alternative form of lava-lava"], ["ma lafo", "and cloth used as gratuity for a talking chief"], ["ae i ou mata,", "but in I eye"], ["ou te faaali atu lou tino", "I reveal your body"], ["i atu nuu,", "in nation"], ["e faaali foi lou mā", "to reveal also your First person dual exclusive"], ["i malo.", "in government"]]},
  {num:6,words:[["Ou te lafo mea leaga", "I cloth used as gratuity for a talking chief thing evil"], ["i luga ia te oe,", "in above unto thee"], ["ou te faainosia foi oe,", "I faainosia also you"], ["ma ou faia oe", "and I made you"], ["ma mataaga.", "and mataaga"]]},
  {num:7,words:[["Ona oo ai lea", "and oo"], ["ina sosola ese ia te oe", "let fled away unto thee"], ["o i latou uma o", "them all"], ["e vaai atu ia te oe,", "to to look at unto thee"], ["ma latou faapea ane,", "and them thus"], ["Ua faatafunaina Nineva!", "faatafunaina nineva"], ["o ai", "o ai"], ["se faamafanafana", "a to hearten"], ["i ai? Po ifea ou te saili ai nisi", "therein night ifea I seek some"], ["e faamatalaloto ia te oe?", "by faamatalaloto unto thee"]]},
  {num:8,words:[["Pe sili ea oe ia Noamoni,", "whether most to rise (as a diver to the sur- you to noamoni"], ["o le", "the"], ["sa nofo", "dwell"], ["i vaitafe,", "in river"], ["sa siomia foi", "siomia also"], ["i le vai,", "in the water"], ["o lona malosi", "his strong"], ["o le vai tele lea,", "the water great"], ["sa i ai lona pa", "therein his a wall"], ["i le vai tele?", "in the water great"]]},
  {num:9,words:[["O Aitiope o lona malosi lea,", "aitiope his strong"], ["atoa ma Aikupito,", "and Egypt"], ["sa le masino foi", "the masino also"], ["ona tagata;", "and man"], ["o Futu", "futu"], ["ma Lipua o ou fesoasoani", "and lipua I to help"], ["ia.", "to"]]},
  {num:10,words:[["A ua tāfea o ia,", "but tāfea he"], ["ua alu o ia faatasi", "go he once"], ["ma e", "and by"], ["ua faatagataotauaina;", "faatagataotauaina"], ["o ana tama iti foi", "his child iti also"], ["sa palasi", "to have children in"], ["i tuluiga o ala uma;", "in tuluiga arise all"], ["sa fai foi", "make also"], ["le vili", "the a gimblet"], ["i ona alii mamalu,", "in then Lord glory"], ["sa nonoa foi", "to tie also"], ["ona alii sili uma", "and Lord most all"], ["i maea uamea.", "in maea uamea"]]},
  {num:11,words:[["O oe foi", "you also"], ["e te inu ia onā;", "by drink to onā"], ["e te lafi lava;", "by lafi indeed"], ["o oe foi", "you also"], ["e te saili", "by seek"], ["se 'olo", "a fortress"], ["ona o le", "because of the"], ["ua ita ia te oe.", "angry unto thee"]]},
  {num:12,words:[["O ou 'olo uma", "I fortress all"], ["ua ni mati ia,", "some mati to"], ["o loo", "o loo"], ["i ai fua", "therein fruit"], ["e muai matua;", "to first very"], ["afai e luluina,", "if by luluina"], ["ona toulu ai lea", "and toulu"], ["i le gutu", "in the mouth"], ["o le 'ai ai.", "the eat"]]},
  {num:13,words:[["Faauta,", "behold"], ["o lou nuu", "your nation"], ["i totonu ia te oe", "in inside unto thee"], ["ua ni fafine lava,", "some woman indeed"], ["e matuā avanoa faitotoa o lou nuu", "to very an open space gate your nation"], ["i e o fai oe", "in by make you"], ["ma fili,", "and to choose"], ["e susunuina au faamaufaalava", "by susunuina I faamaufaalava"], ["i le afi.", "in the fire"]]},
  {num:14,words:[["Ia e utuina vai,", "to by utuina water"], ["auā o le a siosioina oe,", "for will siosioina you"], ["ina teu ia ia malolosi ou 'olo;", "let teu to to mighty I fortress"], ["alu ia", "go to"], ["i le palapala,", "in the palapala"], ["ina soli ia le omea,", "let to tread upon to the omea"], ["ia teu ia malosi", "to teu to strong"], ["le mea", "the thing"], ["e tunu ai maaomea.", "by tunu maaomea"]]},
  {num:15,words:[["E susunuina oe", "by susunuina you"], ["i le afi", "in the fire"], ["i lea mea,", "in thing"], ["e fasia oe", "to struck you"], ["i le pelu,", "in the a sword"], ["na te 'aina lava oe pei", "edible indeed you to be broken"], ["o le sē aleka,", "the sē aleka"], ["ia faatoateleina oe pei o sē aleka,", "to faatoateleina you to be broken sē aleka"], ["ia faatoateleina oe pei o sē akerise.", "to faatoateleina you to be broken sē akerise"]]},
  {num:16,words:[["Ua e faatoateleina ou tagata faatau", "by faatoateleina I man equally"], ["e sili", "to most"], ["i fetu", "in star"], ["o le lagi;", "Heaven"], ["ua salalau sē aleka,", "to be scattered sē aleka"], ["ona lele ese ai lea.", "and fly away"]]},
  {num:17,words:[["O ou alii sili", "I Lord most"], ["e pei o sē akerise", "to to be broken sē akerise"], ["ia,", "to"], ["ma ou alii", "and I Lord"], ["e pulea 'au", "by pulea I"], ["e pei o sē akerise aupito tetele", "to to be broken sē akerise ^ to be great"], ["ia,", "to"], ["o e nonofo", "who dwelling"], ["i āi", "in āi"], ["i le aso maalili,", "in the day maalili"], ["ua alu", "go"], ["ae le la,", "but the la"], ["ona sosola ai lea,", "and fled"], ["e le iloa foi", "by the known also"], ["le mea latou te", "the thing them"], ["i ai.", "therein"]]},
  {num:18,words:[["Le tupu o Asuria", "the grow Assyria"], ["e,", "by"], ["o loo momoe ou leoleo mamoe,", "momoe I shepherd"], ["o taooto ou alii sili;", "taooto I Lord most"], ["ua faataapeapeina lou nuu", "faataapeapeina your nation"], ["i mauga,", "in mountain"], ["e leai foi", "there is not also"], ["se na te faapotopotoina", "a faapotopotoina"], ["i latou .", "them"]]},
  {num:19,words:[["E leai sina feoloolo o lou malaia,", "there is not white feoloolo your a calamity"], ["e matuā leaga lou manua;", "to very evil your manua"], ["o i latou uma o", "them all"], ["e faalogologo", "to listen"], ["i le tala ia te oe,", "in the side unto thee"], ["latou te pati lima ia te oe;", "them pati five unto thee"], ["auā o ai", "for"], ["se tasi", "a one"], ["ua le oo", "the oo"], ["i ona luga lau amio leaga", "in then above your iniquity"], ["e le aunoa?", "by the without"]]},
];
renderVerseSet(nah_ch_3_Verses, 'nah-ch3-verses');

})();