(function() {
var nah_ch_1_Verses = [
  {num:1,words:[["O le avega ia Nineva.", "the avega to nineva"], ["O le tusi o le faaaliga ia Nauma le Elekosi.", "the book the revelation to nauma the elekosi"]]},
  {num:2,words:[["O Ieova o le Atua fuā ia,", "Jehovah the God fuā to"], ["o lē taui ma sui,", "not a reward and to dilute"], ["o Ieova o lē taui ma sui ma lē matuā toasa;", "Jehovah not a reward and to dilute and not very wrath"], ["e taui ma sui Ieova i e ita ia te ia,", "to a reward and to dilute Jehovah in to angry unto to"], ["o loo faamoemoe foi o ia i e ua fai o ia ma o latou fili.", "to expect also he in by make he and them to choose"]]},
  {num:3,words:[["O Ieova e tele gese lona toasa,", "Jehovah to great slow his wrath"], ["a e tele lona mana;", "but to great his to get"], ["na te le faasaoina lava e ua agasala;", "the saved indeed by sin"], ["o Ieova o loo i ai lona ala i le asiosio ma le afā,", "Jehovah therein his arise in the asiosio and the cyclone"], ["o ao o le efuefu ia o ona aao.", "day the efuefu to then hand (extended)"]]},
  {num:4,words:[["E aoai e ia i le sami,", "by aoai by him in the sea"], ["ma faamateina ai,", "and faamateina"], ["na te faamamateina foi o vaitafe uma.", "faamamateina also river all"], ["E mamae Vasana ma Karamelu,", "by mamae vasana and karamelu"], ["e mamae foi fuga o Lepanona.", "by mamae also flower lepanona"]]},
  {num:5,words:[["E gatete mauga ia te ia,", "by gatete mountain unto to"], ["e liu suāvai mauga iti;", "by liu suāvai mountain iti"], ["e mafuie le eleele i ona luma,", "by mafuie the earth in then before"], ["o le lalolagi foi atoa ma i latou uma o e nonofo ai.", "the earth also together with and them all to dwelling"]]},
  {num:6,words:[["O ai se tu i luma o lona toasa? O ai foi se tu i luga pe a tupu lona maemaea? Ua sasaa atu lona toatamai e pei o le afi,", "a stand in before his wrath also a stand in above or but grow his maemaea plurzH x)^ saasaa his toatamai to to be broken the fire"], ["ua fulisia papa e ia.", "fulisia burster by him"]]},
  {num:7,words:[["O loo agalelei Ieova,", "goodness Jehovah"], ["o le 'olo ia i le aso o le puapuaga;", "the fortress to in the day the pain"], ["o loo silafia e ia e o faatuatua ia te ia.", "seen by him by faith unto to"]]},
  {num:8,words:[["O le tafe e lofia ai na te faaumatia ai le mea o i ai le aai,", "the to flow by lofia destroy the thing therein the eat"], ["e tuliloaina e le pouliuli e ua ita ia te ia.", "by tuliloaina by the darkness by angry unto to"]]},
  {num:9,words:[["Se a ea se mea ua outou mafaufau ai ia Ieova? E faaumatia lava e ia;", "a but to rise (as a diver to the sur- a thing ye all think to Jehovah to destroy indeed by him"], ["e le tupu faalua mai le puapuaga.", "by the grow faalua from the pain"]]},
  {num:10,words:[["E ui lava ina filia i latou e pei o laau talatala,", "to although indeed let filia them to to be broken tree to untie"], ["ma latou matuā onā i le inugāuaina,", "and them very onā in the inugāuaina"], ["a e faaumatia i latou pei o tagutugutu o saito e matuā magumagu lava.", "but to destroy them to be broken tagutugutu wheat to very magumagu indeed"]]},
  {num:11,words:[["Ua sau mai ia te oe o ia o le ua mafaufau i mea leaga e faia ia Ieova,", "come from unto you he the think in thing evil to made to Jehovah"], ["o le faipule amio leaga.", "the a councillor conduct evil"]]},
  {num:12,words:[["O loo faapea mai Ieova,", "thus from Jehovah"], ["E ui lava ina atoatoa i latou,", "to although indeed let completely them"], ["ma ua faapea ona toatele,", "and thus then many"], ["a e faapea lava ona fāsia i latou,", "but by thus indeed then fāsia them"], ["ona mavae atu ai lea o ia.", "and a parting he"], ["Na a'u faatigaina oe;", "I faatigaina you"], ["a e ou te le toe faatigaina oe.", "but to I the again faatigaina you"]]},
  {num:13,words:[["Auā ou te gauia nei lana amo o ia te oe,", "for I gauia this his amo he you"], ["ou te motusi foi ou noanoaga.", "I motusi also I bonds"]]},
  {num:14,words:[["Ua fetalai Ieova ia te oe,", "said Jehovah unto you"], ["E le toe totōina nisi o lou igoa;", "by the again totōina some your name"], ["ou te vavaeeseina le tupua ua ta ma le tupua uamea i le fale o ou atua;", "I vavaeeseina the idol a stroke and the idol uamea in the house I God"], ["ou te fai ai lou tuugamau;", "I make your tuugamau"], ["auā ua leaga lava oe.", "for evil indeed you"]]},
  {num:15,words:[["Faauta ea,", "behold to rise (as a diver to the sur-"], ["o i luga o mauga o vae o lē fai mai le tala lelei,", "in above mountain foot not make from the side good"], ["o lē logologo mai i le manuia;", "not logologo from in the peace"], ["Iuta e,", "Judas by"], ["ia e fai au tausamiga,", "to to make I tausamiga"], ["ia e avatu mea na e tauto ai;", "to to give away thing to to take an oath"], ["auā e le toe ui atu lava ia te oe le tagata amio leaga;", "for by the again although indeed unto you the man conduct evil"], ["ua matuā fano o ia.", "very perish he"]]},
];
renderVerseSet(nah_ch_1_Verses, 'nah-ch1-verses');

var nah_ch_2_Verses = [
  {num:1,words:[["Ua alu ae i ou lava luma le na te faataapeapeina;", "go but in I indeed before the faataapeapeina"], ["ina leoleo ia le 'olo,", "let police to the fortress"], ["vaavaai i le ala,", "vaavaai in the arise"], ["ia fusi ae sulugatiti,", "to fusi but the place where the"], ["ia matuā faateleina lou malosi.", "to very faateleina your strong"]]},
  {num:2,words:[["Auā e ui lava ina tafia i latou e i latou o e tafi,", "for to although indeed let tafia them by them to to brush"], ["ma latou faataumaoi foi a latou la laau,", "and them faataumaoi also but them la tree"], ["a e toe faafoisia e Ieova le mamalu o Iakopo,", "but to again faafoisia to Jehovah the glory James"], ["e faapea foi le mamalu o Isaraelu.", "by thus also the glory Israel"]]},
  {num:3,words:[["O talita o ona tagata totoa ua faalanu ulaula ia,", "talita then man p'ural o( fnt faalanu ulaula to"], ["o tagata fitafita foi ua oofu i latou i ofu mūmū;", "man policeman also oofu them in garment mūmū"], ["e fepulafi faaafi o uamea o kariota i le aso e sauniuni ai o ia;", "by fepulafi faaafi uamea kariota in the day by sauniuni he"], ["e fuafua foi o latou tao.", "to abscesses in the hands or also them spear"]]},
  {num:4,words:[["E matuā feasofai kariota i ala tele,", "to very feasofai kariota in arise great"], ["e soona fetaufetuliai i malae;", "to without form fetaufetuliai in the"], ["e tino mai pei o sulu,", "to body from to be broken a torch"], ["e tele vavave pei o le uila.", "to great vavave to be broken the uila"]]},
  {num:5,words:[["Ua manatua e ia ona alii sili,", "remember by him then Lord most"], ["ua latou tautevateva i lo latou savali,", "them tautevateva in the them walk"], ["ua latou faatelelise i lona pa,", "them faatelelise in his a wall"], ["ua saunia foi le talipupuni.", "prepared also the talipupuni"]]},
  {num:6,words:[["Ua tatalaina puipui o vaitafe,", "tatalaina a duor river"], ["ua sŏloia foi le maota.", "sŏloia also the the name of a tree"]]},
  {num:7,words:[["Na faatumauina o ia ,", "faatumauina he"], ["a ua faalelavalavaina,", "but faalelavalavaina"], ["ua ta'ita'iina ae o ia,", "ta'ita'iina but he"], ["ua gaegae foi ana auauna fafine e pei o leo o lupe,", "gaegae also his servant woman to to be broken voice dove"], ["latou te taufaitu'i i o latou fatafata.", "them taufaitu'i in them fatafata"]]},
  {num:8,words:[["O Nineva foi na faapei o le vailepa ia talu mai anamua,", "nineva also like the vailepa to since from anamua"], ["a ua latou sosola lava.", "but them fled indeed"], ["Tutū mai ia,", "tutū from to"], ["ina tutū mai;", "let tutū from"], ["a e leai se tepa i tua.", "but to no a to look towards in behind"]]},
  {num:9,words:[["Ia outou vete ario,", "to ye all vete silver"], ["ina vete ia o auro;", "let vete to gold"], ["e le uma le oloa lelei,", "by the all the goods good"], ["ua faulai mea uma e manaomia.", "faulai thing all by manaomia"]]},
  {num:10,words:[["Ua gaogao,", "void"], ["ua faagaogaoina,", "faagaogaoina"], ["ua faatafunaina;", "faatafunaina"], ["ua faavaivai le loto,", "faavaivai the heart"], ["ua gatete tulivae,", "gatete tulivae"], ["ua tiga tele tua uma,", "pain great behind all"], ["o latou mata uma foi ua matamatavale.", "them eye all also matamatavale"]]},
  {num:11,words:[["O ifea ea le ana o leona,", "ifea to rise (as a diver to the sur- the his leona"], ["ma le mea na aai ai leona taanoa,", "and the thing eat leona an animal that is weaned"], ["o le mea na fealuai ai le leona,", "the thing fealuai the leona"], ["le leona avilu,", "the leona stunted"], ["atoa ma le tamai leona,", "and the son leona"], ["e leai foi se tasi na faamatau atu ai?", "there is not also a one faamatau"]]},
  {num:12,words:[["Na saei e le leona ia maoona ai ana fanau,", "to tear by the leona to maoona his born"], ["ua na titina manu foi mo ana leona fafine,", "to strangle animal also for his leona woman"], ["ua na faatumuina ona lua i mea na maua,", "faatumuina then two in thing received"], ["o ona ana foi ua faatumuina ia i mea ua saeia.", "then his also faatumuina to in thing saeia"]]},
  {num:13,words:[["O loo faapea mai o Ieova o 'au,", "thus from Jehovah I"], ["Faauta,", "behold"], ["ou te tetee ia te oe,", "I to refuse unto you"], ["ou te susunu foi ia liu asu ona kariota,", "I burn also to liu asu then kariota"], ["e faaumatia au leona taanoa i le pelu;", "to destroy I leona an animal that is weaned in the a sword"], ["ou te aveeseina foi i le nuu au mea na saeia;", "I aveeseina also in the nation I thing saeia"], ["e le toe lagona foi leo o au sāvali.", "by the again to understand also voice I am sāvali"]]},
];
renderVerseSet(nah_ch_2_Verses, 'nah-ch2-verses');

var nah_ch_3_Verses = [
  {num:1,words:[["Oi talofa i le aai o e fasi tagata! ua tumu lava i le pepelo ma le saua;", "alas ! oh ! hello in the eat to kill man fill indeed in the false and the to have a return of sick-"], ["ua le aveeseina ai lava le mea na saeia.", "the aveeseina indeed the thing saeia"]]},
  {num:2,words:[["O le paō o le sasa,", "the paō the a scourge"], ["o le taalili o mea taavalevale,", "the resounding thing taavalevale"], ["o solofanua ua feasofai,", "horse feasofai"], ["ma kariota ua osooso.", "and kariota osooso"]]},
  {num:3,words:[["Ua i ai le oso ae o e ua tietie i solofanua,", "therein the food for a journey but by tietie in horse"], ["ma le fepulafi mai o pelu,", "and the fepulafi from a sword"], ["o le emoemo mai foi o tao;", "the emoemo from also spear"], ["o le toatele foi o e ua fāsia,", "the many also by fāsia"], ["ma le faupuega o tagata oti;", "and the faupuega man die"], ["e le masino tagata oti,", "by the masino man die"], ["ua latou tautevateva i o latou tagata oti.", "them tautevateva in them man die"]]},
  {num:4,words:[["Ona o le tele o le talitane o le fafine talitane o le ua lalelei,", "because of the great the talitane the woman talitane the lalelei"], ["o le tamaitai taulāitu,", "the woman taulāitu"], ["o le ua faatau atu nuu i lona talitane atoa ma aiga o ana togafiti faataulāitu.", "the equally nation in his talitane together with and family his heal faataulāitu"]]},
  {num:5,words:[["O loo faapea mai Ieova o 'au,", "thus from Jehovah I"], ["Faauta,", "behold"], ["ou te fai oe mo'u fili,", "I make you many to choose"], ["ou te susue ae foi ou lavalava,", "I susue but also I alternative form of lava-lava"], ["ma lafo ae i ou mata,", "and cloth used as gratuity for a talking chief but in I eye"], ["ou te faaali atu lou tino i atu nuu,", "I reveal your body in nation"], ["e faaali foi lou mā i malo.", "to reveal also your First person dual exclusive in government"]]},
  {num:6,words:[["Ou te lafo mea leaga i luga ia te oe,", "I cloth used as gratuity for a talking chief thing evil in above unto you"], ["ou te faainosia foi oe,", "I faainosia also you"], ["ma ou faia oe ma mataaga.", "and I made you and mataaga"]]},
  {num:7,words:[["Ona oo ai lea ina sosola ese ia te oe o i latou uma o e vaai atu ia te oe,", "and oo let fled away unto you them all to to look at unto you"], ["ma latou faapea ane,", "and them thus"], ["Ua faatafunaina Nineva! o ai se faamafanafana i ai? Po ifea ou te saili ai nisi e faamatalaloto ia te oe?", "faatafunaina nineva a to hearten therein night ifea I seek some by faamatalaloto unto you"]]},
  {num:8,words:[["Pe sili ea oe ia Noamoni,", "or most to rise (as a diver to the sur- you to noamoni"], ["o le sa nofo i vaitafe,", "the dwell in river"], ["sa siomia foi i le vai,", "siomia also in the water"], ["o lona malosi o le vai tele lea,", "his strong the water great"], ["sa i ai lona pa i le vai tele?", "therein his a wall in the water great"]]},
  {num:9,words:[["O Aitiope o lona malosi lea,", "aitiope his strong"], ["atoa ma Aikupito,", "and Egypt"], ["sa le masino foi ona tagata;", "the masino also then man"], ["o Futu ma Lipua o ou fesoasoani ia.", "futu and lipua I to help to"]]},
  {num:10,words:[["A ua tāfea o ia,", "but tāfea he"], ["ua alu o ia faatasi ma e ua faatagataotauaina;", "go he once and by faatagataotauaina"], ["o ana tama iti foi sa palasi i tuluiga o ala uma;", "his child iti also to have children in in tuluiga arise all"], ["sa fai foi le vili i ona alii mamalu,", "make also the a gimblet in then Lord glory"], ["sa nonoa foi ona alii sili uma i maea uamea.", "to tie also then Lord most all in maea uamea"]]},
  {num:11,words:[["O oe foi e te inu ia onā;", "you also by drink to onā"], ["e te lafi lava;", "by lafi indeed"], ["o oe foi e te saili se 'olo ona o le ua ita ia te oe.", "you also by seek a fortress then the angry unto you"]]},
  {num:12,words:[["O ou 'olo uma ua ni mati ia,", "I fortress all some mati to"], ["o loo i ai fua e muai matua;", "therein fruit to first very"], ["afai e luluina,", "if by luluina"], ["ona toulu ai lea i le gutu o le 'ai ai.", "and toulu in the mouth the eat"]]},
  {num:13,words:[["Faauta,", "behold"], ["o lou nuu i totonu ia te oe ua ni fafine lava,", "your nation in inside unto you some woman indeed"], ["e matuā avanoa faitotoa o lou nuu i e o fai oe ma fili,", "to very an open space gate your nation in by make you and to choose"], ["e susunuina au faamaufaalava i le afi.", "by susunuina I faamaufaalava in the fire"]]},
  {num:14,words:[["Ia e utuina vai,", "to by utuina water"], ["auā o le a siosioina oe,", "for the but siosioina you"], ["ina teu ia ia malolosi ou 'olo;", "let teu to to mighty I fortress"], ["alu ia i le palapala,", "go to in the palapala"], ["ina soli ia le omea,", "let to tread upon to the omea"], ["ia teu ia malosi le mea e tunu ai maaomea.", "to teu to strong the thing by tunu maaomea"]]},
  {num:15,words:[["E susunuina oe i le afi i lea mea,", "by susunuina you in the fire in thing"], ["e fasia oe i le pelu,", "to struck you in the a sword"], ["na te 'aina lava oe pei o le sē aleka,", "edible indeed you to be broken the sē aleka"], ["ia faatoateleina oe pei o sē aleka,", "to faatoateleina you to be broken sē aleka"], ["ia faatoateleina oe pei o sē akerise.", "to faatoateleina you to be broken sē akerise"]]},
  {num:16,words:[["Ua e faatoateleina ou tagata faatau e sili i fetu o le lagi;", "by faatoateleina I man equally to most in star the heaven"], ["ua salalau sē aleka,", "to be scattered sē aleka"], ["ona lele ese ai lea.", "and fly away"]]},
  {num:17,words:[["O ou alii sili e pei o sē akerise ia,", "I Lord most to to be broken sē akerise to"], ["ma ou alii e pulea 'au e pei o sē akerise aupito tetele ia,", "and I Lord by pulea I to to be broken sē akerise ^ to be great to"], ["o e nonofo i āi i le aso maalili,", "who dwelling in āi in the day maalili"], ["ua alu ae le la,", "go but the la"], ["ona sosola ai lea,", "and fled"], ["e le iloa foi le mea latou te i ai.", "by the known also the thing them therein"]]},
  {num:18,words:[["Le tupu o Asuria e,", "the grow Assyria by"], ["o loo momoe ou leoleo mamoe,", "momoe I police sheep"], ["o taooto ou alii sili;", "taooto I Lord most"], ["ua faataapeapeina lou nuu i mauga,", "faataapeapeina your nation in mountain"], ["e leai foi se na te faapotopotoina i latou .", "there is not also a faapotopotoina them"]]},
  {num:19,words:[["E leai sina feoloolo o lou malaia,", "there is not white feoloolo your a calamity"], ["e matuā leaga lou manua;", "to very evil your manua"], ["o i latou uma o e faalogologo i le tala ia te oe,", "them all to listen in the side unto you"], ["latou te pati lima ia te oe;", "them pati five unto you"], ["auā o ai se tasi ua le oo i ona luga lau amio leaga e le aunoa?", "for a one the oo in then above your conduct evil by the without"]]},
];
renderVerseSet(nah_ch_3_Verses, 'nah-ch3-verses');

})();