(function() {
var _oba_ch_1_Verses = [
  {num:1,words:[["O le faaaliga", "the revelation"], ["ia Opetaia.", "to Obadiah"], ["O loo faapea ona", "saying and"], ["fetalai mai", "said"], ["o le Alii", "the Lord"], ["o Ieova ia", "the LORD to"], ["Etoma,", "Edom"], ["Ua tatou faalogo", "we (incl) hearken"], ["i le tala", "in the side"], ["mai ia Ieova,", "from to the LORD"], ["ua auina atu foi", "sent also"], ["le sāvali", "the sāvali"], ["i nuu ese,", "in nation away"], ["Tulai ia outou,", "arise up to you (all)"], ["ina tatou sii atu", "so that we (incl) lift up"], ["i ai", "therein"], ["le taua.", "the precious"]]},
  {num:2,words:[["Faauta,", "behold"], ["ua ou faia", "I made"], ["oe ia faatauvaa", "you to vain"], ["i nuu,", "in nation"], ["ua matuā inosia", "exceedingly abominable"], ["lava oe.", "indeed you"]]},
  {num:3,words:[["O le faamaualuga", "the exalted"], ["o lou loto", "your heart"], ["ua faaseseina ai", "deceived astray"], ["oe,", "you"], ["o oe", "you"], ["o loo nofo", "dwell"], ["i ana", "in his"], ["o le papa;", "the rock"], ["e maualuga", "to Iiigli"], ["le mea", "the thing"], ["e nofo ai", "to dwell"], ["o ia;", "he"], ["o le faapea", "the thus"], ["i lona loto,", "in his heart"], ["O ai", "O ai"], ["se", "a"], ["na te lafo", "he cloth used as gratuity for a talking chief"], ["ia te au", "unto me"], ["i lalo", "in under"], ["i le eleele?", "the ground"]]},
  {num:4,words:[["E ui lava", "to although indeed"], ["ina maualuga", "so that Iiigli"], ["le mea", "the thing"], ["e te nofo ai", "by dwell"], ["pei o le aeto,", "like the aeto"], ["ma", "and"], ["e tuu", "to put"], ["lou ofaga", "your a nest"], ["i fetu,", "in star"], ["o loo fetalai mai Ieova,", "said the LORD"], ["ou te lafo", "I will cloth used as gratuity for a talking chief"], ["ia te oe", "unto you"], ["i lalo", "in under"], ["i lea", "in"], ["mea.", "thing"]]},
  {num:5,words:[["Ana o atu", "his of"], ["ia te oe", "unto you"], ["o gaoi,", "to steal"], ["ana o atu", "his of"], ["o", "o"], ["e fao mea", "to to seize thing"], ["i le po,", "in the night"], ["(aue!", "alas! oh!"], ["ua faaumatia oe,)", "destroyed you"], ["po", "night"], ["ua latou", "they"], ["le gaoi ea mea", "the to steal indeed?/really? thing"], ["e tusa ia", "to according to to"], ["i latou? Ana", "them his"], ["o atu ia te oe", "unto you"], ["o", "o"], ["e tāu vine,", "to to wring out vine"], ["po", "night"], ["ua latou", "they"], ["le faatotoe ea", "the make phiral of foe indeed?/really?"], ["nai toe fuifui vine?", "from again to dip vine"]]},
  {num:6,words:[["E!", "by"], ["ua suena lava", "suena indeed"], ["Esau;", "Esau"], ["ua sailia ana", "sought his"], ["mea lilo.", "thing secret"]]},
  {num:7,words:[["Ua molia oe", "accused you"], ["i le tuaoi", "in the border"], ["lava", "indeed"], ["e tagata uma", "to man all"], ["na outou fai ai", "you (all) made"], ["mavaega,", "a parting command"], ["ua faa'ole'ole ia te oe,", "treacherous unto you"], ["ua manumalo foi", "overcame also"], ["ia te oe", "unto you"], ["tagata", "man"], ["sa outou nofo", "you (all) dwelt"], ["lelei;", "good"], ["o", "o"], ["e", "by"], ["na aai", "city"], ["i au mea", "in I thing"], ["e 'ai", "to eat"], ["ua latou tuu", "they put"], ["le mailei", "the a trap"], ["i lalo ia te oe.", "in under unto you"]]},
  {num:8,words:[["E leai se mafaufau", "there is no think"], ["ia te ia.", "to him"], ["O loo fetalai mai Ieova,", "said the LORD"], ["Ou te", "I will"], ["le faaumatia ea", "the destroyed indeed?/really?"], ["i lea", "in"], ["aso tagata popoto", "day man round (as the trunk of a"], ["i Etoma,", "in Edom"], ["ma ou faaumatia", "and I destroyed"], ["le mafaufau ai", "the think"], ["le mauga o Esau?", "the mountain of Esau"]]},
  {num:9,words:[["Timanu e,", "Timanu by"], ["e matatau ou tagata totoa,", "to fear I man p'ural o( fnt"], ["ina ia faaumatia tagata uma ai", "so that destroyed man all"], ["le mauga o Esau", "the mountain of Esau"], ["ina", "so that"], ["ua fasiotia.", "slain"]]},
  {num:10,words:[["E matuā faamāina oe", "to exceedingly faamāina you"], ["ona", "and"], ["o lou saua", "your to have a return of sick-"], ["i lou uso", "in your brother"], ["o Iakopo;", "Jacob"], ["e faaumatia foi", "to destroyed also"], ["oe", "you"], ["e faavavau.", "forever/everlasting"]]},
  {num:11,words:[["O le aso", "the day"], ["sa", "sa"], ["e tu ai", "to stand"], ["e faafeagai,", "to make opposite"], ["o le aso", "the day"], ["sa ave ai", "took"], ["faatagataotaua ana 'au", "make a captive his I"], ["e tagata ese,", "to man away"], ["na ulu atu ai", "head"], ["foi tagata ese", "also man away"], ["i ona faitotoa,", "in then door"], ["ma latou fai ai", "and they make"], ["le vili", "the a gimblet"], ["e Ierusalema,", "to Jerusalem"], ["sa", "sa"], ["i ai", "therein"], ["lava oe faapei", "indeed you like"], ["o so latou.", "so they"]]},
  {num:12,words:[["A", "but"], ["ua", "ua"], ["le tatau", "the to wring out"], ["ina", "so that"], ["ua", "ua"], ["e maimoa", "by maimoa"], ["i le aso", "in the day"], ["o lou uso,", "your brother"], ["o le aso", "the day"], ["o lona puapuaga;", "his affliction"], ["ua", "ua"], ["le tatau foi", "the to wring out also"], ["ina", "so that"], ["ua", "ua"], ["e faatuumana", "to to apply an acci-"], ["i le fanauga", "in the children"], ["a Iuta", "of Judas"], ["i le aso", "in the day"], ["na fano ai", "perished"], ["i latou;", "them"], ["ua", "ua"], ["le tatau foi", "the to wring out also"], ["ina", "so that"], ["ua", "ua"], ["e tautala faasiasia", "to speak haughty"], ["i le aso", "in the day"], ["o le puapuaga.", "the affliction"]]},
  {num:13,words:[["Ua", "Ua"], ["le tatau", "the to wring out"], ["ina", "so that"], ["ua", "ua"], ["e ulu atu", "to head"], ["i le faitotoa", "at the door"], ["o lo'u nuu", "my nation"], ["i le aso", "in the day"], ["o lo latou malaia;", "their disaster"], ["ua", "ua"], ["le tatau", "the to wring out"], ["ina", "so that"], ["ua", "ua"], ["e maimoa,", "by maimoa"], ["o oe lava,", "you indeed"], ["i lo latou tiga", "than they grieved"], ["i le aso", "in the day"], ["o lo latou malaia;", "their disaster"], ["ua", "ua"], ["le tatau foi", "the to wring out also"], ["ina", "so that"], ["ua", "ua"], ["e tago", "to reach"], ["i o latou", "in of they"], ["oloa", "goods"], ["i le aso", "in the day"], ["o lo latou malaia.", "their disaster"]]},
  {num:14,words:[["Ua", "Ua"], ["le tatau foi", "the to wring out also"], ["ina", "so that"], ["ua", "ua"], ["e tu", "to stand"], ["i le mafegāala", "in the mafegāala"], ["e fasioti ai", "to killed"], ["ona tagata", "and man"], ["na sao;", "the appointed portion of"], ["ua", "ua"], ["le tatau foi", "the to wring out also"], ["ina", "so that"], ["ua", "ua"], ["e tuuina atu", "shall be given"], ["i nuu ese", "in nation away"], ["ona tagata", "and man"], ["na totoe", "phiral of foe"], ["i le aso", "in the day"], ["o le puapuaga.", "the affliction"]]},
  {num:15,words:[["Auā", "for"], ["e latalata", "to near"], ["le aso o Ieova", "the day the LORD"], ["i nuu uma;", "in nation all"], ["e faia ia te oe", "to made unto you"], ["e pei ona", "as"], ["e faia;", "to made"], ["e toe iu atu", "to again become of"], ["ia te oe", "unto you"], ["mea", "thing"], ["na", "na"], ["e faia.", "to made"]]},
  {num:16,words:[["Auā", "for"], ["e pei ona", "as"], ["outou feinu", "you (all) feinu"], ["i luga", "in above"], ["o lo'u mauga paia,", "my mountain holy"], ["e faapea ona", "saying and"], ["feinu pea lava nuu uma,", "feinu continually indeed nation all"], ["latou te feinu", "they will feinu"], ["lava ia inu tele,", "indeed to drink great"], ["e avea", "to become"], ["i latou", "them"], ["e peiseai", "to as if"], ["ua leai lava", "there was not indeed"], ["i latou.", "them"]]},
  {num:17,words:[["A", "but"], ["e peitai e", "to however by"], ["i ai", "therein"], ["i le mauga", "in the mountain"], ["o Siona", "Zion"], ["e ua sao,", "by the appointed portion of"], ["e paia foi", "to holy also"], ["ia;", "to"], ["o le aiga foi", "the family also"], ["o Iakopo", "Jacob"], ["e fai", "to make"], ["mo", "for"], ["i latou lava", "them indeed"], ["o", "o"], ["a latou lava mea.", "but they indeed thing"]]},
  {num:18,words:[["E fai foi", "to make also"], ["le aiga o Iakopo", "the family of Jacob"], ["ma afi,", "and fire"], ["e fai foi", "to make also"], ["le aiga o Iosefa", "the family of Joseph"], ["ma afi mumū,", "and fire mumū"], ["a", "but"], ["e fai", "to make"], ["le aiga o Esau", "the family of Esau"], ["ma tagutugutu o saito;", "and tagutugutu of wheat"], ["latou te faamu foi", "they will burn incense also"], ["ia te", "unto"], ["i latou,", "them"], ["ma faauma ia te", "and finish unto"], ["i latou;", "them"], ["e leai foi", "there is not also"], ["sē toe", "sē again"], ["i le aiga", "in the family"], ["o Esau;", "Esau"], ["auā", "for"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:19,words:[["O", "O"], ["i latou foi", "them also"], ["o", "o"], ["i le itu", "on the side"], ["i toga", "southward"], ["e fai", "to make"], ["mo", "for"], ["i latou", "them"], ["le mauga o Esau;", "the mountain of Esau"], ["o", "o"], ["i latou foi", "them also"], ["o", "o"], ["i le itu maulalo", "on the side lowly"], ["e fai", "to make"], ["mo", "for"], ["i latou", "them"], ["le nuu o Filisitia;", "the nation of Philistine"], ["e fai foi", "to make also"], ["mo", "for"], ["i latou", "them"], ["le laueleele o Efaraima,", "the ground Ephraim"], ["ma le laueleele", "and the ground"], ["o Samaria;", "Samaria"], ["e fai foi", "to make also"], ["Kiliata", "Gilead"], ["mo Peniamina.", "for Benjamin"]]},
  {num:20,words:[["O le tafeaga foi", "the exiles in wa^ also"], ["o lenei", "now"], ["itu taua", "side precious"], ["a le fanauga", "but the children"], ["a Isaraelu", "of Israel"], ["e ua", "by"], ["i", "in"], ["sa Kananā", "of the clan of Canaanites"], ["e oo", "it shall come to pass"], ["i Sarefata", "in Sarefata"], ["o le tafeaga foi", "the exiles in wa^ also"], ["o Ierusalema o", "Jerusalem of"], ["i Sefarata,", "in Sefarata"], ["e fai", "to make"], ["mo", "for"], ["i latou", "them"], ["o aai o", "city of"], ["i le itu", "on the side"], ["i toga.", "southward"]]},
  {num:21,words:[["E o ae foi", "by go up also"], ["faaola", "save"], ["i le mauga", "in the mountain"], ["o Siona,", "Zion"], ["ina ia faasalaina", "so that punished"], ["le mauga o Esau;", "the mountain of Esau"], ["e fai foi", "to make also"], ["le malo", "the government"], ["mo Ieova.", "for the LORD"]]},
];
renderVerseSet(_oba_ch_1_Verses, 'oba-ch1-verses');

})();