(function() {
var _oba_ch_1_Verses = [
  {num:1,words:[["O le fa'aaliga", "the revelation"], ["ia Opetaia.", "he Obadiah"], ["O loo fa'apea ona", "saying and"], ["fetalai mai", "said"], ["o le Ali'i", "the Lord"], ["o Ieova ia", "the LORD he"], ["Etoma,", "Edom"], ["Ua tātou fa'alogo", "we hearken"], ["i le tala", "in the side"], ["mai ia Ieova,", "from he the LORD"], ["ua auina atu foi", "sent also"], ["le sāvali", "the walk"], ["i nuu ese,", "in nation away"], ["Tulai ia outou,", "arise up he you all"], ["ina tātou sii atu", "so that we lift up"], ["i ai", "therein"], ["le taua.", "the battle"]]},
  {num:2,words:[["Fa'auta,", "behold"], ["ua ou faia oe", "I made you"], ["ia fa'atauvaa i", "he vain in"], ["nuu,", "nation"], ["ua matuā inosia lava oe.", "exceedingly abominable very you"]]},
  {num:3,words:[["O le fa'amaualuga", "the pride"], ["o lou loto", "your heart"], ["ua fa'aseseina ai", "deceived astray"], ["oe,", "you"], ["o oe", "you"], ["o loo nofo", "is dwell"], ["i ana", "in cave"], ["o le papa;", "the rock"], ["e maualuga", "to Iiigli"], ["le mea", "the thing"], ["e nofo ai", "to dwell"], ["o ia;", "he"], ["o le fa'apea", "the so"], ["i lona loto,", "in his heart"], ["O ai", "O ai"], ["se", "a"], ["na te lafo ia te au", "he cloth used as gratuity for a talking chief unto me"], ["i lalo", "in under"], ["i le eleele?", "the ground"]]},
  {num:4,words:[["E ui lava", "to although very"], ["ina maualuga", "so that Iiigli"], ["le mea", "the thing"], ["e te nofo ai", "by dwell"], ["pei o le aeto,", "like the aeto"], ["ma", "and"], ["e tuu", "to put"], ["lou ofaga", "your a nest"], ["i fetu,", "in star"], ["o loo fetalai mai", "is/are said"], ["Ieova,", "the LORD"], ["ou te lafo", "I will cloth used as gratuity for a talking chief"], ["ia te oe", "unto you"], ["i lalo", "in under"], ["i lea", "in"], ["mea.", "thing"]]},
  {num:5,words:[["Ana o atu", "cave went"], ["ia te oe", "unto you"], ["o gaoi,", "to steal"], ["ana o atu", "cave went"], ["o", "o"], ["e fao mea", "to to seize thing"], ["i le po,", "at night"], ["(aue!", "alas! oh!"], ["ua fa'aumatia oe,)", "are destroyed you"], ["po", "night"], ["ua lātou", "they"], ["le gaoi ea mea", "the to steal indeed?/really? thing"], ["e tusa ia", "to according to he"], ["i lātou? Ana", "them cave"], ["o atu ia te oe", "went unto you"], ["o", "o"], ["e tāu vine,", "to fight vine"], ["po", "night"], ["ua lātou", "they"], ["le fa'atotoe ea", "the make phiral of foe indeed?/really?"], ["nai toe fuifui vine?", "from again to dip vine"]]},
  {num:6,words:[["E!", "by"], ["ua suena lava", "suena very"], ["Esau;", "Esau"], ["ua sailia ana", "sought cave"], ["mea lilo.", "thing secret"]]},
  {num:7,words:[["Ua molia oe", "accused you"], ["i le tuaoi", "in the border"], ["lava", "very"], ["e tagata uma", "to man all"], ["na outou fai ai", "you all made"], ["mavaega,", "a parting command"], ["ua fa'a'ole'ole ia te oe,", "treacherous unto you"], ["ua manumalo foi", "victory also"], ["ia te oe", "unto you"], ["tagata", "man"], ["sa outou nofo", "you all dwelt"], ["lelei;", "good"], ["o", "o"], ["e", "by"], ["na aai", "cities"], ["i au mea", "in me thing"], ["e 'ai", "to eat"], ["ua lātou tuu", "they put"], ["le mailei", "the a trap"], ["i lalo ia te oe.", "in under unto you"]]},
  {num:8,words:[["E leai se mafaufau", "there is no think"], ["ia te ia.", "to him"], ["O loo fetalai mai", "is/are said"], ["Ieova,", "the LORD"], ["Ou te", "I will"], ["le fa'aumatia ea", "the destroyed indeed?/really?"], ["i lea aso tagata popoto", "on that day man round (as the trunk of a"], ["i Etoma,", "in Edom"], ["ma ou fa'aumatia", "and I destroyed"], ["le mafaufau ai", "the think"], ["le mauga o Esau?", "the mountain of Esau"]]},
  {num:9,words:[["Timanu e,", "Timanu by"], ["e matatau ou tagata totoa,", "to dismayed I man p'ural o( fnt"], ["ina ia fa'aumatia tagata uma ai", "so that destroyed man all"], ["le mauga o Esau", "the mountain of Esau"], ["ina ua fasiotia.", "when slain"]]},
  {num:10,words:[["E matuā fa'amāina oe", "to exceedingly to put to shame you"], ["ona", "and"], ["o lou saua", "your to have a return of sick-"], ["i lou uso", "in your brother"], ["o Iakopo;", "Jacob"], ["e fa'aumatia foi", "to destroyed also"], ["oe", "you"], ["e fa'avavau.", "forever/everlasting"]]},
  {num:11,words:[["O le aso", "the day"], ["sa e tu ai", "you stood"], ["e fa'afeagai,", "to make opposite"], ["o le aso", "the day"], ["sa ave ai", "took"], ["fa'atagataotaua ana 'au", "make a captive cave troops"], ["e tagata ese,", "to man away"], ["na ulu atu ai", "head"], ["foi tagata ese", "also man away"], ["i ona faitotoa,", "in his door"], ["ma lātou fai ai", "and they make"], ["le vili", "the a gimblet"], ["e Ierusalema,", "by Jerusalem"], ["sa", "sa"], ["i ai", "therein"], ["lava oe fa'apei", "very you like"], ["o so lātou.", "so they"]]},
  {num:12,words:[["A", "but"], ["ua", "ua"], ["le tatau", "the to wring out"], ["ina ua e maimoa", "when by maimoa"], ["i le aso", "in the day"], ["o lou uso,", "your brother"], ["o le aso", "the day"], ["o lona puapuaga;", "his affliction"], ["ua", "ua"], ["le tatau foi", "the to wring out also"], ["ina ua e fa'atuumana", "when to to apply an acci-"], ["i le fanauga", "in the children"], ["a Iuta", "of Judas"], ["i le aso", "in the day"], ["na fano ai", "perished"], ["i lātou;", "them"], ["ua", "ua"], ["le tatau foi", "the to wring out also"], ["ina ua e tautala fa'asiasia", "when to speak haughty"], ["i le aso", "in the day"], ["o le puapuaga.", "the affliction"]]},
  {num:13,words:[["Ua", "Ua"], ["le tatau", "the to wring out"], ["ina ua e ulu atu", "when to head"], ["i le faitotoa", "at the door"], ["o lo'u nuu", "my nation"], ["i le aso", "in the day"], ["o lo lātou malaia;", "their disaster"], ["ua", "ua"], ["le tatau", "the to wring out"], ["ina ua e maimoa,", "when by maimoa"], ["o oe lava,", "you very"], ["i lo lātou tiga", "than they grieved"], ["i le aso", "in the day"], ["o lo lātou malaia;", "their disaster"], ["ua", "ua"], ["le tatau foi", "the to wring out also"], ["ina ua e tago", "when to reach"], ["i o lātou", "in of they"], ["oloa", "goods"], ["i le aso", "in the day"], ["o lo lātou malaia.", "their disaster"]]},
  {num:14,words:[["Ua", "Ua"], ["le tatau foi", "the to wring out also"], ["ina ua e tu", "when to stand"], ["i le mafegāala", "in the mafegāala"], ["e fasioti ai", "to killed"], ["ona tagata", "and man"], ["na sao;", "the appointed portion of"], ["ua", "ua"], ["le tatau foi", "the to wring out also"], ["ina ua e tuuina atu", "when shall be given"], ["i nuu ese", "in nation away"], ["ona tagata", "and man"], ["na totoe", "phiral of foe"], ["i le aso", "in the day"], ["o le puapuaga.", "the affliction"]]},
  {num:15,words:[["Auā", "for"], ["e latalata", "to near"], ["le aso o Ieova", "the day the LORD"], ["i nuu uma;", "in nation all"], ["e faia ia te oe", "to made unto you"], ["e pei ona", "as"], ["e faia;", "to made"], ["e toe iu atu", "to again become of"], ["ia te oe", "unto you"], ["mea", "thing"], ["na e faia.", "you made"]]},
  {num:16,words:[["Auā", "for"], ["e pei ona", "as"], ["outou feinu", "you all feinu"], ["i luga", "in above"], ["o lo'u mauga paia,", "my mountain holy"], ["e fa'apea ona", "saying and"], ["feinu pea lava nuu uma,", "feinu continually very nation all"], ["lātou te feinu", "they will feinu"], ["lava ia inu tele,", "very he drink great"], ["e avea", "to become"], ["i lātou", "them"], ["e peiseai", "to as if"], ["ua leai lava", "there was not very"], ["i lātou.", "them"]]},
  {num:17,words:[["A", "but"], ["e peitai e", "to however by"], ["i ai", "therein"], ["i le mauga", "in the mountain"], ["o Siona", "Zion"], ["e ua sao,", "to the appointed portion of"], ["e paia foi", "to holy also"], ["ia;", "he"], ["o le 'āiga foi", "the family also"], ["o Iakopo", "Jacob"], ["e fai", "to make"], ["mo", "for"], ["i lātou lava", "them very"], ["o", "o"], ["a lātou lava mea.", "their very thing"]]},
  {num:18,words:[["E fai foi", "to make also"], ["le 'āiga o Iakopo", "the family of Jacob"], ["ma afi,", "and fire"], ["e fai foi", "to make also"], ["le 'āiga o Iosefa", "the family of Joseph"], ["ma afi mumū,", "and fire scarlet"], ["a", "but"], ["e fai", "to make"], ["le 'āiga o Esau", "the family of Esau"], ["ma tagutugutu o saito;", "and tagutugutu of wheat"], ["lātou te fa'amu foi", "they will burn incense also"], ["ia te i lātou,", "unto them"], ["ma fa'auma ia te", "and finish unto"], ["i lātou;", "them"], ["e leai foi", "there is not also"], ["sē toe", "a again"], ["i le 'āiga", "in the family"], ["o Esau;", "Esau"], ["auā", "for"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:19,words:[["O", "O"], ["i lātou foi", "them also"], ["o", "o"], ["i le itu", "on the side"], ["i toga", "southward"], ["e fai", "to make"], ["mo", "for"], ["i lātou", "them"], ["le mauga o Esau;", "the mountain of Esau"], ["o", "o"], ["i lātou foi", "them also"], ["o", "o"], ["i le itu maulalo", "on the side lowly"], ["e fai", "to make"], ["mo", "for"], ["i lātou", "them"], ["le nuu o Filisitia;", "the nation of Philistine"], ["e fai foi", "to make also"], ["mo", "for"], ["i lātou", "them"], ["le laueleele o Efaraima,", "the ground Ephraim"], ["ma le laueleele", "and the ground"], ["o Samaria;", "Samaria"], ["e fai foi", "to make also"], ["Kiliata", "Gilead"], ["mo Peniamina.", "for Benjamin"]]},
  {num:20,words:[["O le tafeaga foi", "the exiles in wa^ also"], ["o lenei", "now"], ["itu taua", "army/battle line"], ["a le fanauga", "but the children"], ["a Isaraelu", "of Israel"], ["e ua", "to"], ["i", "in"], ["sa Kananā", "of the clan of Canaanites"], ["e oo", "it shall come to pass"], ["i Sarefata", "in Sarefata"], ["o le tafeaga foi", "the exiles in wa^ also"], ["o Ierusalema o", "Jerusalem of"], ["i Sefarata,", "in Sefarata"], ["e fai", "to make"], ["mo", "for"], ["i lātou", "them"], ["o aai o", "cities of"], ["i le itu", "on the side"], ["i toga.", "southward"]]},
  {num:21,words:[["E o ae foi", "by went up also"], ["fa'aola", "save"], ["i le mauga", "in the mountain"], ["o Siona,", "Zion"], ["ina ia fa'asalaina", "so that punished"], ["le mauga o Esau;", "the mountain of Esau"], ["e fai foi", "to make also"], ["le mālō", "the kingdom"], ["mo Ieova.", "for the LORD"]]},
];
renderVerseSet(_oba_ch_1_Verses, 'oba-ch1-verses');

})();