(function() {
var oba_ch_1_Verses = [
  {num:1,words:[["O le faaaliga ia Opetaia.", "the revelation to opetaia"], ["O loo faapea", "thus"], ["ona fetalai mai", "and said"], ["o le Alii o Ieova", "the Lord Jehovah"], ["ia Etoma,", "to Edom"], ["Ua tatou faalogo", "us hearken"], ["i le tala", "in the side"], ["mai ia Ieova,", "from to Jehovah"], ["ua auina atu foi", "sent also"], ["le sāvali", "the sāvali"], ["i nuu ese,", "in nation away"], ["Tulai ia outou,", "arose up to ye all"], ["ina tatou sii atu", "let us lift up"], ["i ai", "therein"], ["le taua.", "the war"]]},
  {num:2,words:[["Faauta,", "behold"], ["ua ou faia oe ia faatauvaa", "I made you to faatauvaa"], ["i nuu,", "in nation"], ["ua matuā inosia lava oe.", "very abominable indeed you"]]},
  {num:3,words:[["O le faamaualuga o lou loto", "the to be proud your heart"], ["ua faaseseina ai oe,", "faaseseina you"], ["o oe o loo nofo", "you dwell"], ["i ana", "in his"], ["o le papa;", "the burster"], ["e maualuga", "to Iiigli"], ["le mea", "the thing"], ["e nofo ai o ia;", "to dwell he"], ["o le faapea", "the thus"], ["i lona loto,", "in his heart"], ["O ai", "o ai"], ["se na te lafo ia te au", "a cloth used as gratuity for a talking chief unto me"], ["i lalo", "in under"], ["i le eleele?", "in the earth"]]},
  {num:4,words:[["E ui lava", "to although indeed"], ["ina maualuga", "let Iiigli"], ["le mea", "the thing"], ["e te nofo ai pei", "by dwell to be broken"], ["o le aeto,", "the aeto"], ["ma e tuu lou ofaga", "and to put your a nest"], ["i fetu,", "in star"], ["o loo fetalai", "said"], ["mai Ieova,", "from Jehovah"], ["ou te lafo ia te oe", "I cloth used as gratuity for a talking chief unto thee"], ["i lalo", "in under"], ["i lea mea.", "in thing"]]},
  {num:5,words:[["Ana o atu ia te oe", "his unto thee"], ["o gaoi,", "to steal"], ["ana o atu o", "his"], ["e fao mea", "to to seize thing"], ["i le po,", "in the night"], ["(aue!", "alas! oh!"], ["ua faaumatia oe,)", "destroy you"], ["po ua latou", "night them"], ["le gaoi ea mea", "the to steal to rise (as a diver to the sur- thing"], ["e tusa ia", "to according to to"], ["i latou? Ana o atu", "them his"], ["ia te oe o", "unto thee"], ["e tāu vine,", "to to wring out vine"], ["po ua latou", "night them"], ["le faatotoe ea nai toe fuifui vine?", "the faatotoe to rise (as a diver to the sur- from again to dip vine"]]},
  {num:6,words:[["E!", "by"], ["ua suena lava Esau;", "suena indeed Esau"], ["ua sailia ana mea lilo.", "sailia his thing secret"]]},
  {num:7,words:[["Ua molia oe", "molia you"], ["i le tuaoi lava", "in the border indeed"], ["e tagata uma", "to man all"], ["na outou fai ai mavaega,", "ye all make a parting command"], ["ua faa'ole'ole ia te oe,", "faa'ole'ole unto thee"], ["ua manumalo foi ia te oe tagata", "overcome also unto thee man"], ["sa outou nofo lelei;", "ye all dwell good"], ["o e", "who"], ["na aai", "eat"], ["i au mea", "in I thing"], ["e 'ai", "to eat"], ["ua latou tuu", "them put"], ["le mailei", "the a trap"], ["i lalo ia te oe.", "in under unto thee"]]},
  {num:8,words:[["E leai", "there is not"], ["se mafaufau ia te ia.", "a think unto him"], ["O loo fetalai", "said"], ["mai Ieova,", "from Jehovah"], ["Ou te", "I"], ["le faaumatia ea", "the destroy to rise (as a diver to the sur-"], ["i lea aso tagata popoto", "in day man round (as the trunk of a"], ["i Etoma,", "in Edom"], ["ma ou faaumatia", "and I destroy"], ["le mafaufau ai", "the think"], ["le mauga o Esau?", "the mountain Esau"]]},
  {num:9,words:[["Timanu e,", "timanu by"], ["e matatau ou tagata totoa,", "to fear I man p'ural o( fnt"], ["ina ia faaumatia tagata uma ai", "so that destroy man all"], ["le mauga o Esau", "the mountain Esau"], ["ina ua fasiotia.", "let slain"]]},
  {num:10,words:[["E matuā faamāina oe", "to very faamāina you"], ["ona o lou saua", "because of your to have a return of sick-"], ["i lou uso o Iakopo;", "in your a relative of the same generation and gender James"], ["e faaumatia foi oe", "to destroy also you"], ["e faavavau.", "forever/everlasting"]]},
  {num:11,words:[["O le aso", "the day"], ["sa e tu ai", "to stand"], ["e faafeagai,", "by faafeagai"], ["o le aso", "the day"], ["sa ave ai faatagataotaua ana 'au", "take faatagataotaua his I"], ["e tagata ese,", "to man away"], ["na ulu atu ai foi tagata ese", "head also man away"], ["i ona faitotoa,", "in then gate"], ["ma latou fai ai", "and them make"], ["le vili", "the a gimblet"], ["e Ierusalema,", "to Jerusalem"], ["sa i ai lava oe faapei", "therein indeed you like"], ["o so latou.", "so them"]]},
  {num:12,words:[["A ua", "but"], ["le tatau", "the to wring out"], ["ina ua", "let"], ["e maimoa", "by maimoa"], ["i le aso o lou uso,", "in the day your a relative of the same generation and gender"], ["o le aso o lona puapuaga;", "the day his pain"], ["ua le tatau foi", "the to wring out also"], ["ina ua", "let"], ["e faatuumana", "to to apply an acci-"], ["i le fanauga", "in the children"], ["a Iuta", "of Judas"], ["i le aso", "in the day"], ["na fano ai", "perish"], ["i latou;", "them"], ["ua le tatau foi", "the to wring out also"], ["ina ua", "let"], ["e tautala faasiasia", "to to talk haughty"], ["i le aso", "in the day"], ["o le puapuaga.", "the pain"]]},
  {num:13,words:[["Ua le tatau", "the to wring out"], ["ina ua", "let"], ["e ulu atu", "to head"], ["i le faitotoa o lo'u nuu", "in the gate my nation"], ["i le aso", "in the day"], ["o lo latou malaia;", "their a calamity"], ["ua le tatau", "the to wring out"], ["ina ua", "let"], ["e maimoa,", "by maimoa"], ["o oe lava,", "you indeed"], ["i lo latou tiga", "in the them pain"], ["i le aso", "in the day"], ["o lo latou malaia;", "their a calamity"], ["ua le tatau foi", "the to wring out also"], ["ina ua", "let"], ["e tago", "to reach"], ["i o latou oloa", "in them goods"], ["i le aso", "in the day"], ["o lo latou malaia.", "their a calamity"]]},
  {num:14,words:[["Ua le tatau foi", "the to wring out also"], ["ina ua", "let"], ["e tu", "to stand"], ["i le mafegāala", "in the mafegāala"], ["e fasioti ai", "to killed"], ["ona tagata", "and man"], ["na sao;", "the appointed portion of"], ["ua le tatau foi", "the to wring out also"], ["ina ua", "let"], ["e tuuina atu", "shall be given"], ["i nuu ese", "in nation away"], ["ona tagata", "and man"], ["na totoe", "phiral of foe"], ["i le aso", "in the day"], ["o le puapuaga.", "the pain"]]},
  {num:15,words:[["Auā e latalata", "for to near"], ["le aso o Ieova", "the day Jehovah"], ["i nuu uma;", "in nation all"], ["e faia ia te oe", "to made unto thee"], ["e pei", "to to be broken"], ["ona e faia;", "and to made"], ["e toe iu atu ia te oe mea", "to again attain unto thee thing"], ["na e faia.", "to made"]]},
  {num:16,words:[["Auā e pei", "for to to be broken"], ["ona outou feinu", "and ye all feinu"], ["i luga o lo'u mauga paia,", "upon my mountain holy"], ["e faapea", "by thus"], ["ona feinu pea lava nuu uma,", "and feinu continually indeed nation all"], ["latou te feinu lava ia inu tele,", "them feinu indeed to drink great"], ["e avea", "to become"], ["i latou", "them"], ["e peiseai", "to as if"], ["ua leai lava", "there was not indeed"], ["i latou.", "them"]]},
  {num:17,words:[["A e peitai", "but to however"], ["e i ai", "by therein"], ["i le mauga o Siona", "in the mountain Zion"], ["e ua sao,", "by the appointed portion of"], ["e paia foi ia;", "to holy also to"], ["o le aiga foi o Iakopo", "the family also James"], ["e fai", "to make"], ["mo i latou lava o", "for them indeed"], ["a latou lava mea.", "but them indeed thing"]]},
  {num:18,words:[["E fai foi", "to make also"], ["le aiga o Iakopo", "the family James"], ["ma afi,", "and fire"], ["e fai foi", "to make also"], ["le aiga o Iosefa", "the family Joseph"], ["ma afi mumū,", "and fire mumū"], ["a e fai", "but to make"], ["le aiga o Esau", "the family Esau"], ["ma tagutugutu o saito;", "and tagutugutu wheat"], ["latou te faamu foi ia te", "them faamu also unto"], ["i latou,", "them"], ["ma faauma ia te", "and faauma unto"], ["i latou;", "them"], ["e leai foi sē toe", "there is not also sē again"], ["i le aiga o Esau;", "in the family of Esau"], ["auā ua fetalai", "for said"], ["mai ai Ieova.", "from Jehovah"]]},
  {num:19,words:[["O i latou foi o", "them also"], ["i le itu", "on the side"], ["i toga", "in Tonga"], ["e fai", "to make"], ["mo i latou", "for them"], ["le mauga o Esau;", "the mountain Esau"], ["o i latou foi o", "them also"], ["i le itu maulalo", "on the side maulalo"], ["e fai", "to make"], ["mo i latou", "for them"], ["le nuu o Filisitia;", "the nation Philistine"], ["e fai foi", "to make also"], ["mo i latou", "for them"], ["le laueleele o Efaraima,", "the ground Ephraim"], ["ma le laueleele o Samaria;", "and the ground Samaria"], ["e fai foi Kiliata", "to make also kiliata"], ["mo Peniamina.", "for Benjamin"]]},
  {num:20,words:[["O le tafeaga foi o lenei itu taua", "the exiles in wa^ also this itu war"], ["a le fanauga", "but the children"], ["a Isaraelu", "of Israel"], ["e ua", "by"], ["i sa Kananā", "in kananā"], ["e oo", "it shall come to pass"], ["i Sarefata", "in sarefata"], ["o le tafeaga foi o Ierusalema", "the exiles in wa^ also Jerusalem"], ["o i Sefarata,", "in sefarata"], ["e fai", "to make"], ["mo i latou o aai", "for them eat"], ["o i le itu", "on the side"], ["i toga.", "in Tonga"]]},
  {num:21,words:[["E o", "by"], ["ae foi faaola", "but also save"], ["i le mauga o Siona,", "in the mountain Zion"], ["ina ia faasalaina", "so that faasalaina"], ["le mauga o Esau;", "the mountain Esau"], ["e fai foi", "to make also"], ["le malo", "the government"], ["mo Ieova.", "for Jehovah"]]},
];
renderVerseSet(oba_ch_1_Verses, 'oba-ch1-verses');

})();