(function() {
var phm_ch_1_Verses = [
  {num:1,words:[["O a'u o Paulo,", "I am Paul"], ["o le ua noanoatia ona o Keriso Iesu,", "the noanoatia then Christ Jesus"], ["o Timoteo foi lo tatou uso,", "Timothy also our a relative of the same generation and gender"], ["o la ma tusi lenei ia Filemoni o le pele na tatou galulue faatasi;", "la and book this to filemoni the dear us galulue once"]]},
  {num:2,words:[["ma Afia le pele,", "and pass the dear"], ["ma Arekipa o le na tatou matātau faatasi,", "and arekipa the us matātau once"], ["atoa ma le ekalesia i lou fale;", "and the church in your house"]]},
  {num:3,words:[["ia ia te outou le alofa tunoa ma le manuia mai le Atua lo tatou Tamā,", "to unto ye all the love grace and the peace from the God our father"], ["atoa ma le Alii o Iesu Keriso.", "and the Lord Jesus Christ"]]},
  {num:4,words:[["Ou te faafetai atu i lo'u Atua,", "I to tliank in my God"], ["o loo ou ta'uta'ua oe e le aunoa i a'u tatalo,", "I ta'uta'ua you by the without in I pray"]]},
  {num:5,words:[["ina ua ou faalogo i lou alofa ma le faatuatua o ia te oe i le Alii o Iesu,", "let I hearken in your love and the faith he you in the Lord Jesus"], ["atoa ma le au paia uma;", "and the I holy all"]]},
  {num:6,words:[["ina ia galue lava lou mafuta faatasi i le faatuatua,", "so that work indeed your communion once in the faith"], ["ina ia matuā iloa mea lelei uma o ia te outou ia Keriso Iesu.", "so that very known thing good all he ye all to Christ Jesus"]]},
  {num:7,words:[["Auā lo'u uso e,", "for my a relative of the same generation and gender by"], ["ua tele lo matou fiafia ma le mafanafana ona o lou alofa,", "great our competition and the to be warm then your love"], ["ina ua faamafanafanaina le au paia ona o oe.", "let faamafanafanaina the I holy then you"]]},
  {num:8,words:[["O lenei,", "this"], ["e ui lava ina ua ia te au le pule lava mai ia Keriso e poloai atu ai ia te oe i mea e tatau,", "to although indeed let unto I the rule indeed from to Christ to command unto you in thing to to wring out"]]},
  {num:9,words:[["a e ou te aioi atu ona o le alofa,", "but to I aioi then the love"], ["o a'u nei lava o Paulo le toeaina,", "I am this indeed Paul the elder"], ["o le ua noanoatia nei foi ona o Iesu Keriso.", "the noanoatia this also then Jesus Christ"]]},
  {num:10,words:[["Ou te aioi atu ia te oe mo lo'u atalii o Onesemo,", "I aioi unto you for my son onesemo"], ["o le na fanaua e a'u,", "the born to I"], ["a e noanoatia a'u,", "but by noanoatia I"]]},
  {num:11,words:[["sa le aoga o ia ia te oe,", "the useful he unto you"], ["a o lenei e aoga tele ia te oe atoa ma a'u,", "but this to useful great unto you together with and I"]]},
  {num:12,words:[["ou te faafoi atu ia te ia;", "I faafoi unto to"], ["ina e talia mai o ia,", "let to received from he"], ["o lo'u lava tino ia.", "my indeed body to"]]},
  {num:13,words:[["Na ou loto ina ia taofi pea ia te ia ma te nonofo ma a'u,", "I heart let to hold continually unto to and dwelling and I"], ["ina ia fai mou sui,", "so that make many to dilute"], ["na te auauna mai ia te au i o'u noanoataga ona o le tala lelei.", "servant from unto I in I noanoataga then the side good"]]},
  {num:14,words:[["A ou te le fia faia se mea e tasi pe a le to mai sau pule,", "but I the want to do something made a thing by one or but the to plant from come rule"], ["ina ne'i pei o se mea ua faatauanauina lou agalelei mai,", "let now to be broken a thing faatauanauina your goodness from"], ["a ia faia ma le loto.", "but to made and the heart"]]},
  {num:15,words:[["Auā atonu o le mea lea na te'a ese ai o ia i sina itu aso,", "for impers the thing te'a away he in white itu day"], ["ina ia e toe maua o ia e faavavau;", "so that to again received he to a stone connected with"]]},
  {num:16,words:[["e le toe faapei o se pologa,", "by the again like a mouldy"], ["a e sili i le pologa,", "but to most in the mouldy"], ["o le uso pele ia ia te au lava;", "the a relative of the same generation and gender dear to unto I indeed"], ["e le sili ea ona faapea ia te oe i la le tino atoa ma la le Alii?", "by the most to rise (as a diver to the sur- then thus unto you in the body together with and the Lord"]]},
  {num:17,words:[["O lenei afai e te manatu i la ta uo,", "this if by thought in la a stroke uo"], ["ia e talia mai o ia e pei o a'u lava.", "to to received from he to to be broken I am indeed"]]},
  {num:18,words:[["A e afai na ia agaleaga ia te oe,", "but to if to unkind unto you"], ["po ua ia te ia sau mea,", "night unto to come thing"], ["ia e tuu mai lea mea ia te au.", "to to put from thing unto I"]]},
  {num:19,words:[["O a'u o Paulo,", "I am Paul"], ["ua ou tusi atu i lo'u lava lima,", "I book in my indeed five"], ["ou te taui atu lava;", "I a reward indeed"], ["a e ou te le fai atu,", "but to I the make"], ["e tatau ona e tuuina mai oe lava ia te au.", "it is fitting and to given from you indeed unto I"]]},
  {num:20,words:[["E moni,", "verily/truly"], ["lo'u uso e,", "my a relative of the same generation and gender by"], ["se'i e faafiafia mai ia te au i le Alii,", "a flower put into the hair or to to please from unto I in the Lord"], ["ina faamafanafana mai ia i lo'u loto i le Alii.", "let to hearten from to in my heart in the Lord"]]},
  {num:21,words:[["Ua ou tusi atu ia te oe,", "I book unto you"], ["auā ou te faatuatua i lou gauai mai,", "for I faith in your gauai from"], ["ua ou iloa e te faia mea e sili lava i mea ou te fai atu ai.", "I known by made thing to most indeed in thing I make"]]},
  {num:22,words:[["Tasi foi lea mea,", "one also thing"], ["ia e sauni se mea ou te nofo ai;", "to to he who beg^ins the game a thing I dwell"], ["auā ou te faamoemoe e tuuinaatua a'u ia te outou,", "for I to expect by tuuinaatua I unto ye all"], ["ona o a outou tatalo.", "because of but ye all pray"]]},
  {num:23,words:[["O loo alofa atu ia te oe o Epafara,", "love unto you epafara"], ["o loo noanoatia faatasi ma a'u ona o Keriso Iesu.", "noanoatia once and I then Christ Jesus"]]},
  {num:24,words:[["O loo alolofa foi Mareko,", "alolofa also Mark"], ["ma Aritako,", "and aritako"], ["ma Tema,", "and tema"], ["ma Luka,", "and Luke"], ["e ua galulue faatasi ma a'u.", "by galulue once and I"]]},
  {num:25,words:[["Ia i o outou agaga le alofa tunoa o lo tatou Alii o Iesu Keriso.", "to in ye all spirit the love grace our Lord Jesus Christ"], ["Amene.", "amen"]]},
];
renderVerseSet(phm_ch_1_Verses, 'phm-ch1-verses');

})();