(function() {
var _phm_ch_1_Verses = [
  {num:1,words:[["O a'u", "I am"], ["o Paulo,", "Paul"], ["o le", "the"], ["ua noanoatia", "noanoatia"], ["ona o Keriso Iesu,", "because of Christ Jesus"], ["o Timoteo foi", "Timothy also"], ["lo tātou uso,", "our brother"], ["o lā", "sun"], ["ma tusi lenei", "and book this"], ["ia Filemoni", "he Filemoni"], ["o le pele", "the dear"], ["na tātou galulue", "we labour"], ["fa'atasi;", "together"]]},
  {num:2,words:[["ma Afia", "and pass"], ["le pele,", "the dear"], ["ma Arekipa", "and Arekipa"], ["o le", "the"], ["na tātou matātau", "we dismayed"], ["fa'atasi,", "together"], ["atoa ma le ekalesia", "and the church"], ["i lou fale;", "in your house"]]},
  {num:3,words:[["ia ia te outou", "to him you all"], ["le alofa tunoa", "grace"], ["ma le manuia", "and peace"], ["mai le Atua lo tātou Tamā,", "from God our Father"], ["atoa ma le Ali'i", "and the Lord"], ["o Iesu Keriso.", "Jesus Christ"]]},
  {num:4,words:[["Ou te fa'afetai atu", "I will thank"], ["i lo'u Atua,", "in my God"], ["o loo ou ta'uta'ua oe", "is I was to hang up you"], ["e le aunoa", "shall not without"], ["i a'u tatalo,", "in me pray"]]},
  {num:5,words:[["ina ua ou fa'alogo", "when I hearken"], ["i lou alofa", "in your love"], ["ma le fa'atuatua", "and the faith"], ["o ia te oe", "he you"], ["i le Ali'i", "in the Lord"], ["o Iesu,", "Jesus"], ["atoa ma le au paia uma;", "and all the saints"]]},
  {num:6,words:[["ina ia galue", "so that till"], ["lava", "very"], ["lou mafuta fa'atasi", "your communion together"], ["i le fa'atuatua,", "in the faith"], ["ina ia matuā iloa mea lelei uma", "so that exceedingly know thing good all"], ["o ia te outou", "he you all"], ["ia Keriso Iesu.", "he Christ Jesus"]]},
  {num:7,words:[["Auā", "for"], ["lo'u uso e,", "my brother by"], ["ua tele lo mātou", "great our"], ["fiafia", "pleased"], ["ma le mafanafana", "and the to be warm"], ["ona", "and"], ["o lou alofa,", "your love"], ["ina ua fa'amafanafanaina", "when comforted"], ["le au paia", "the saints"], ["ona o oe.", "because of you"]]},
  {num:8,words:[["O lenei,", "now"], ["e ui lava", "to although very"], ["ina ua ia te au", "when unto me"], ["le pule lava", "the rule very"], ["mai ia Keriso", "from he Christ"], ["e poloai atu ai", "to command"], ["ia te oe", "unto you"], ["i mea", "in thing"], ["e tatau,", "it is fitting/ought"]]},
  {num:9,words:[["a", "but"], ["e ou te aioi atu", "to I will cry out"], ["ona", "and"], ["o le alofa,", "the love"], ["o a'u nei", "I am this"], ["lava o Paulo", "very of Paul"], ["le toeaina,", "the elder"], ["o le", "the"], ["ua noanoatia nei foi", "noanoatia this also"], ["ona o Iesu Keriso.", "because of Jesus Christ"]]},
  {num:10,words:[["Ou te aioi atu", "I will cry out"], ["ia te oe", "unto you"], ["mo lo'u atali'i", "for my son"], ["o Onesemo,", "Onesemo"], ["o le", "the"], ["na fanaua", "born"], ["e a'u,", "to me"], ["a", "but"], ["e noanoatia a'u,", "by noanoatia me"]]},
  {num:11,words:[["sa", "sa"], ["le aoga o ia ia te oe,", "the useful he unto you"], ["a o lenei", "but now"], ["e aoga tele", "to useful great"], ["ia te oe", "unto you"], ["atoa ma a'u,", "and me"]]},
  {num:12,words:[["ou te fa'afoi atu", "I will return back"], ["ia te ia;", "to him"], ["ina", "so that"], ["e talia mai", "to received from"], ["o ia,", "he"], ["o lo'u lava tino", "my very body"], ["ia.", "he"]]},
  {num:13,words:[["Na ou loto", "I heart"], ["ina ia taofi pea", "so that hold continually"], ["ia te ia", "to him"], ["ma te nonofo", "and dwelling"], ["ma a'u,", "and me"], ["ina ia fai mou sui,", "so that make many replace"], ["na te auauna mai ia te au", "he servant from me"], ["i o'u noanoataga", "in my bond"], ["ona", "and"], ["o le tala lelei.", "the gospel"]]},
  {num:14,words:[["A ou te", "but I will"], ["le fia faia", "the want to do something made"], ["se mea", "a thing"], ["e tasi", "by one"], ["pe a le to", "even though / although the to plant"], ["mai sau pule,", "from come rule"], ["ina ne'i pei", "so that now like"], ["o se mea", "a thing"], ["ua fa'atauanauina", "made to be urgent"], ["lou agalelei mai,", "your kindness from"], ["a ia faia", "his made"], ["ma le loto.", "and the heart"]]},
  {num:15,words:[["Auā atonu", "for impers"], ["o le mea lea", "therefore"], ["na te'a ese ai", "departed away"], ["o ia", "he"], ["i sina itu aso,", "in white side day"], ["ina ia", "so that"], ["e toe maua", "to again received"], ["o ia", "he"], ["e fa'avavau;", "forever/everlasting"]]},
  {num:16,words:[["e le toe fa'apei", "shall not again like"], ["o se pologa,", "a bondage"], ["a", "but"], ["e sili", "to most"], ["i le pologa,", "in the bondage"], ["o le uso pele", "the brother dear"], ["ia ia te au", "to him me"], ["lava;", "very"], ["e le sili ea", "shall not most indeed?/really?"], ["ona fa'apea ia te oe", "and so unto you"], ["i lā le tino", "according to the flesh"], ["atoa ma lā le Ali'i?", "and the Lord"]]},
  {num:17,words:[["O lenei", "now"], ["afai", "if"], ["e te manatu", "by thought"], ["i lā tā uo,", "in sun struck uo"], ["ia e talia", "he to received"], ["mai o ia", "from he"], ["e pei o a'u", "like me"], ["lava.", "very"]]},
  {num:18,words:[["A", "but"], ["e afai", "to if"], ["na ia agaleaga ia te oe,", "he unkind unto you"], ["po", "night"], ["ua ia te ia", "to him"], ["sau mea,", "come thing"], ["ia e tuu mai", "he to placed"], ["lea mea ia te au.", "thing unto me"]]},
  {num:19,words:[["O a'u", "I am"], ["o Paulo,", "Paul"], ["ua ou tusi atu", "I book"], ["i lo'u lava lima,", "in my very hand"], ["ou te taui atu", "I will a reward"], ["lava;", "very"], ["a", "but"], ["e ou te", "to I will"], ["le fai atu,", "the said to"], ["e tatau ona", "should"], ["e tuuina mai oe", "to given from you"], ["lava ia te au.", "very unto me"]]},
  {num:20,words:[["E moni,", "verily/truly"], ["lo'u uso e,", "my brother by"], ["se'i", "a flower put into the hair or"], ["e fa'afiafia mai ia te au", "to to please from me"], ["i le Ali'i,", "in the Lord"], ["ina fa'amafanafana mai ia", "so that to hearten from he"], ["i lo'u loto", "in my heart"], ["i le Ali'i.", "in the Lord"]]},
  {num:21,words:[["Ua ou tusi atu ia te oe,", "I book unto you"], ["auā ou te fa'atuatua", "for I will faith"], ["i lou gauai", "in your gauai"], ["mai,", "from"], ["ua ou iloa", "I knew"], ["e te faia mea", "by made thing"], ["e sili lava", "to most very"], ["i mea ou te fai atu ai.", "in thing I will said to"]]},
  {num:22,words:[["Tasi foi", "one also"], ["lea mea,", "thing"], ["ia e sauni", "he to he who beg^ins the game"], ["se mea ou te nofo ai;", "a thing I will dwell"], ["auā ou te fa'amoemoe", "for I will hope"], ["e tuuinaatua a'u", "by tuuinaatua me"], ["ia te outou,", "unto you all"], ["ona o", "because of"], ["a outou tatalo.", "your pray"]]},
  {num:23,words:[["O loo alofa atu", "is love"], ["ia te oe", "unto you"], ["o Epafara,", "Epafara"], ["o loo noanoatia fa'atasi ma a'u", "is noanoatia together and me"], ["ona o Keriso Iesu.", "because of Christ Jesus"]]},
  {num:24,words:[["O loo alolofa foi", "is alolofa also"], ["Mareko,", "Mark"], ["ma Aritako,", "and Aritako"], ["ma Tema,", "and Tema"], ["ma Luka,", "and Luke"], ["e ua galulue fa'atasi ma a'u.", "to labour together and me"]]},
  {num:25,words:[["Ia", "he"], ["i o outou agaga", "in of you all spirit"], ["le alofa tunoa", "grace"], ["o lo tātou Ali'i", "our Lord"], ["o Iesu Keriso.", "Jesus Christ"], ["Amene.", "amen"]]},
];
renderVerseSet(_phm_ch_1_Verses, 'phm-ch1-verses');

})();