(function() {
var sng_ch_1_Verses = [
  {num:1,words:[["O le pese silisili a Solomona.", "The song of songs, which is Solomon's."]]},
  {num:2,words:[["Ia sogi mai o ia ia te au i sogi o lona fofoga;", "Let him kiss me with the kisses of his mouth:"], ["auā e sili ona lelei o lou faapelepele mai i le uaina.", "for thy love is better than wine."]]},
  {num:3,words:[["O le nanamu o ou uu lelei ua avea ai lou suafa e pei o le uu ua liligiina;", "Because of the savour of thy good ointments thy name is as ointment poured forth,"], ["o le mea lea ua mananao ai taupou ia te oe.", "therefore do the virgins love thee."]]},
  {num:4,words:[["Ia e tosina atu o a'u,", "Draw me,"], ["matou te taufetuli ma mulimuli atu ia te oe. Ua ta'ita'iina o a'u e le tupu i ona potu;", "we will run after thee:"], ["matou te fiafia ma olioli ia te oe,", "the king hath brought me into his chambers: we will be glad and rejoice in thee,"], ["e tele lo matou manatunatu i lou faapelepele mai a e itiiti i le uaina;", "we will remember thy love more than wine:"], ["ua mananao tagata amiotonu ia te oe.", "the upright love thee."]]},
  {num:5,words:[["Tama fafine a Ierusalema e,", "I am black,"], ["e uliuli a'u,", "but comely,"], ["a e lalelei,", "O ye daughters of Jerusalem,"], ["e pei o fale ie o Kitara,", "as the tents of Kedar,"], ["e pei o ie puipui o Solomona.", "as the curtains of Solomon."]]},
  {num:6,words:[["Aua tou te vaavaai mai ia te au,", "Look not upon me,"], ["ina ua uliuli o a'u;", "because I am black,"], ["auā ua laina a'u. Na ita mai ia te au o fanau a lo'u tinā;", "because the sun hath looked upon me: my mother's children were angry with me;"], ["na latou tofia a'u e fai ma leoleo i tovine;", "they made me the keeper of the vineyards;"], ["a o lo'u lava tovine ou te lei leoleoina.", "but mine own vineyard have I not kept."]]},
  {num:7,words:[["O oe na ua manao i ai lo'u loto,", "Tell me,"], ["ina ta'u mai ia ia te au le mea e te fafaga ai i au mamoe ,", "O thou whom my soul loveth,"], ["o le mea e te ave ai lou lafu e taoto ai i le aoauli;", "where thou feedest, where thou makest thy flock to rest at noon:"], ["auā se a le mea e avea ai a'u e pei o se ua lailoa i fealualuai i lafu o e ua faatasi ma oe?", "for why should I be as one that turneth aside by the flocks of thy companions?"]]},
  {num:8,words:[["Afai e te le iloa,", "If thou know not,"], ["o oe na le sili ona lalelei i fafine,", "O thou fairest among women,"], ["ina alu atu ia oe i tulagavae o le lafu,", "go thy way forth by the footsteps of the flock,"], ["ma fafaga i au tamai 'oti fafine e latalata ane i mea e nonofo ai leoleo mamoe.", "and feed thy kids beside the shepherds' tents."]]},
  {num:9,words:[["La'u uo e,", "I have compared thee, O my love,"], ["ua faatusaina oe i solofanua i kariota o Farao.", "to a company of horses in Pharaoh's chariots."]]},
  {num:10,words:[["Ua matagofie ou alafau i sei;", "Thy cheeks are comely with rows of jewels,"], ["o lou ua foi i asoa.", "thy neck with chains of gold."]]},
  {num:11,words:[["Matou te faia mo oe ni pale auro e ema i ario.", "We will make thee borders of gold with studs of silver."]]},
  {num:12,words:[["Ua puaiina le manogi o lo'u nato ina o afio le tupu i lana tautega.", "While the king sitteth at his table, my spikenard sendeth forth the smell thereof."]]},
  {num:13,words:[["O le ofuofu pulu muro lo'u manamea ia te au;", "A bundle of myrrh is my wellbeloved unto me;"], ["e asoa ia i lo'u ua i le po atoa.", "he shall lie all night betwixt my breasts."]]},
  {num:14,words:[["O le fuifui kofero lo'u manamea ia te au i tovine o Enokati.", "My beloved is unto me as a cluster of camphire in the vineyards of En-gedi."]]},
  {num:15,words:[["Faauta,", "Behold,"], ["la'u uo e,", "thou art fair,"], ["ua e lalelei;", "my love;"], ["faauta,", "behold,"], ["ua lalelei oe,", "thou art fair;"], ["ua ni mata o se lupe ou mata.", "thou hast doves' eyes."]]},
  {num:16,words:[["Faauta,", "Behold,"], ["lo'u manamea e,", "thou art fair,"], ["e lalelei oe,", "my beloved, yea,"], ["e matagofie lava;", "pleasant:"], ["ua uluuluola lo ta moega.", "also our bed is green."]]},
  {num:17,words:[["O utupoto o lo ta fale o arasi ia,", "The beams of our house are cedar,"], ["o lo ta falealuga ua faia i perosi.", "and our rafters of fir."]]},
];
renderVerseSet(sng_ch_1_Verses, 'sng-ch1-verses');

var sng_ch_2_Verses = [
  {num:1,words:[["O a'u o le fuga o le laau i Sarona;", "I am the rose of Sharon,"], ["o le susana i vanu.", "and the lily of the valleys."]]},
  {num:2,words:[["E pei o le susana i totonu o laau talatala,", "As the lily among thorns,"], ["o loo faapea la'u uo i teine.", "so is my love among the daughters."]]},
  {num:3,words:[["E pei o le moli i totonu o laau o le vao,", "As the apple tree among the trees of the wood,"], ["o loo faapea lo'u manamea i taulelea.", "so is my beloved among the sons."], ["Na ou fiafia i lona paolo, ma ou nofo ai;", "I sat down under his shadow with great delight,"], ["na suamalie foi ona fua i lo'u gutu.", "and his fruit was sweet to my taste."]]},
  {num:4,words:[["Na ia aumaia a'u i le fale uaina; o lana fu'a i o'u luga,", "He brought me to the banqueting house,"], ["o le alofa lea.", "and his banner over me was love."]]},
  {num:5,words:[["Ia outou faamalosia a'u i potoi vine;", "Stay me with flagons,"], ["ina fofola mai ia o moli;", "comfort me with apples:"], ["auā o a'u ua ou vaivai i lo'u alofa atu.", "for I am sick of love."]]},
  {num:6,words:[["Ua i lalo o lo'u ulu lona lima tauagavale,", "His left hand is under my head,"], ["ua fusi mai foi ia te au lona lima taumatau.", "and his right hand doth embrace me."]]},
  {num:7,words:[["Tama fafine o Ierusalema e,", "I charge you,"], ["ou te fai atu ia te outou,", "O ye daughters of Jerusalem, by the roes,"], ["ia tauto mai i sevi ma aila o le vao,", "and by the hinds of the field,"], ["tou te le tatatuli pe fafagu i la'u pele,", "that ye stir not up, nor awake my love,"], ["seia faitalia o ia.", "till he please."]]},
  {num:8,words:[["O le leo o lo'u manamea! faauta,", "The voice of my beloved! behold,"], ["o loo sau o ia, o loo osooso i luga o mauga,", "he cometh leaping upon the mountains,"], ["o loo matuā osooso foi i mea maupuepue.", "skipping upon the hills."]]},
  {num:9,words:[["E pei o se sevi,", "My beloved is like a roe or a young hart:"], ["po o se tamai aila lo'u manamea. Faauta,", "behold,"], ["o loo tu mai o ia i tuāpa o lo tatou fale;", "he standeth behind our wall,"], ["o loo silasila mai i faamalama,", "he looketh forth at the windows,"], ["o loo pupula mai lona tino i le mea faamataupega.", "shewing himself through the lattice."]]},
  {num:10,words:[["Na tautala mai lo'u manamea,", "My beloved spake,"], ["ua faapea mai ia te au,", "and said unto me,"], ["Si a'u uo e,", "Rise up,"], ["si o'u lalelei e,", "my love,"], ["ina tulai mai ia oe,", "my fair one,"], ["ina sau ia;", "and come away."]]},
  {num:11,words:[["auā,", "For,"], ["faauta mai ia,", "lo,"], ["ua mavae le tausaga maalili, ua mavae le timuga,", "the winter is past,"], ["ua te'a ia.", "the rain is over and gone;"]]},
  {num:12,words:[["Ua iloa atu fuga i le fanua;", "The flowers appear on the earth;"], ["ua oo mai le tau e teuteu ai vine;", "the time of the singing of birds is come,"], ["ua lagona foi le leo o le manutagi i lo tatou nuu;", "and the voice of the turtle is heard in our land;"]]},
  {num:13,words:[["ua matua fua le mati sa moto;", "The fig tree putteth forth her green figs,"], ["ua puaiina foi le nanamu o vine ua fuga. Si a'u uo e,", "and the vines with the tender grape give a good smell. Arise,"], ["si o'u lalelei e,", "my love,"], ["ina tulai ia oe,", "my fair one,"], ["ina sau ia.", "and come away."]]},
  {num:14,words:[["La'u lupe e,", "O my dove,"], ["ua i ana o papa ma lafitaga o i mato,", "that art in the clefts of the rock,"], ["ina faaali mai ia ou mata ia te au;", "in the secret places of the stairs, let me see thy countenance,"], ["so'u faalogo i lou leo;", "let me hear thy voice;"], ["auā o le leo mălie lou leo,", "for sweet is thy voice,"], ["e lalelei ou mata.", "and thy countenance is comely."]]},
  {num:15,words:[["Ina outou pupue ia mā tatou o alope,", "Take us the foxes,"], ["o alope iti,", "the little foxes,"], ["o e faamāumau i vine;", "that spoil the vines:"], ["auā ua fua o tatou vine.", "for our vines have tender grapes."]]},
  {num:16,words:[["O lo'u manamea,", "My beloved is mine,"], ["o lo'u lava ia , e fai foi a'u mona;", "and I am his:"], ["ua ia fafaga i lona lafu i totonu o susana.", "he feedeth among the lilies."]]},
  {num:17,words:[["Lo'u manamea e,", "Until the day break,"], ["ina foi mai ia seia gafoa le ata,", "and the shadows flee away,"], ["ma mavae le ufiata,", "turn, my beloved,"], ["ia avea oe e faapei o se sevi po o se tamai aila i mauga o Petere.", "and be thou like a roe or a young hart upon the mountains of Bether."]]},
];
renderVerseSet(sng_ch_2_Verses, 'sng-ch2-verses');

var sng_ch_3_Verses = [
  {num:1,words:[["Ua ou i luga o la'u moega i le po,", "By night on my bed I sought him whom my soul loveth:"], ["na ou saili ai i le ua manao i ai lo'u loto. Ua ou saili ia te ia,", "I sought him,"], ["a e lei maua o ia.", "but I found him not."]]},
  {num:2,words:[["Ou te tulai ma fealualuai i le aai,", "I will rise now,"], ["i ala ma malae,", "and go about the city in the streets,"], ["ou te sailiili ai i le ua manao i ai lo'u loto;", "and in the broad ways I will seek him whom my soul loveth:"], ["ua ou sailiili ia te ia,", "I sought him,"], ["a e lei maua.", "but I found him not."]]},
  {num:3,words:[["Na maua a'u e leoleo e feoai i le aai;", "The watchmen that go about the city found me:"], ["ua ou faapea atu i ai ,", "to whom I said,"], ["Ua outou iloa ea le ua manao i ai lo'u loto?", "Saw ye him whom my soul loveth?"]]},
  {num:4,words:[["E lei ata tuanai ia te i latou,", "It was but a little that I passed from them,"], ["ua ou maua loa le ua manao i ai lo'u loto;", "but I found him whom my soul loveth:"], ["na ou taofi ia te ia,", "I held him, and would not let him go,"], ["ou te lei toe tuuina o ia seia ta'ita'iina atu ia te ia i le fale o lo'u tinā,", "until I had brought him into my mother's house,"], ["i le potu o le na fanaua a'u.", "and into the chamber of her that conceived me."]]},
  {num:5,words:[["Tama fafine a Ierusalema e,", "I charge you,"], ["ou te fai atu ia te outou,", "O ye daughters of Jerusalem, by the roes,"], ["ia tauto mai i sevi ma aila o le vao,", "and by the hinds of the field,"], ["tou te le tatatuli pe fafagu i la'u pele,", "that ye stir not up, nor awake my love,"], ["seia faitalia o ia.", "till he please."]]},
  {num:6,words:[["O ai ea lena o loo alu ae nai le vao e faapei o le asu faaniutu,", "Who is this that cometh out of the wilderness like pillars of smoke,"], ["o loo nanamu i le pulu muro, ma le pulu lipano,", "perfumed with myrrh and frankincense,"], ["ma mea manogi uma ua nutililiia a le tagata faatauoa?", "with all powders of the merchant?"]]},
  {num:7,words:[["Faauta mai ia,", "Behold his bed,"], ["o lona moega,", "which is Solomon's;"], ["o le moega o Solomona,", "threescore valiant men are about it,"], ["ua vagavagaia i toa e toaonogafulu nai le au totoa o Isaraelu.", "of the valiant of Israel."]]},
  {num:8,words:[["Ua taitasi uma ma 'u'u i lana pelu,", "They all hold swords,"], ["ua a'oa'oina i le taua;", "being expert in war:"], ["o le tagata ma lana pelu i lona vae ona o le mata'u i le po.", "every man hath his sword upon his thigh because of fear in the night."]]},
  {num:9,words:[["Ua faia e le tupu o Solomona le fata mona i laau mai Lepanona.", "King Solomon made himself a chariot of the wood of Lebanon."]]},
  {num:10,words:[["Ua ia faia ona pou i le ario,", "He made the pillars thereof of silver,"], ["o ona faalava i le auro,", "the bottom thereof of gold,"], ["o lona nofoa i le ie pāuli;", "the covering of it of purple, the midst thereof being paved with love,"], ["ua folasia faamatagofie i totonu i mea alofa mai tama fafine a Ierusalema.", "for the daughters of Jerusalem."]]},
  {num:11,words:[["Tama fafine a Siona e,", "Go forth,"], ["o atu ia,", "O ye daughters of Zion,"], ["ina matamata i le tupu o Solomona ma le pale na faapaleina ai o ia e lona tina i le aso na fai avā ai o ia,", "and behold king Solomon with the crown wherewith his mother crowned him in the day of his espousals,"], ["le aso foi na fiafia ai lona finagalo.", "and in the day of the gladness of his heart."]]},
];
renderVerseSet(sng_ch_3_Verses, 'sng-ch3-verses');

var sng_ch_4_Verses = [
  {num:1,words:[["La'u pele e,", "Behold,"], ["faauta,", "thou art fair, my love;"], ["ua e lalelei;", "behold,"], ["faauta,", "thou art fair;"], ["ua lalelei oe;", "thou hast doves' eyes within thy locks: thy hair is as a flock of goats,"], ["ua ni mata o se lupe ou mata ai totonu o lou ie ufimata. O lou lauulu ua pei o fulufulu o le lafu 'oti ua taooto mai i le mauga o Kiliata.", "that appear from mount Gilead."]]},
  {num:2,words:[["O ou nifo ua pei o le lafu mamoe ua seleina fulufulu ua o ae nai le fulufuluga;", "Thy teeth are like a flock of sheep that are even shorn,"], ["e taitasi o i latou uma ma taiuilua,", "which came up from the washing; whereof every one bear twins,"], ["e leai foi se tasi o i latou e pa.", "and none is barren among them."]]},
  {num:3,words:[["O ou laugutu ua pei o le manoa mūmū,", "Thy lips are like a thread of scarlet,"], ["ua matagofie lou gutu;", "and thy speech is comely:"], ["ua pei o se fasi rimoni ou alafau i totonu o lou ie ufimata.", "thy temples are like a piece of a pomegranate within thy locks."]]},
  {num:4,words:[["O lou ua ua pei o le 'olo o Tavita na faia e tuu ai le auupega;", "Thy neck is like the tower of David builded for an armoury,"], ["ua faatautauina ai o talita e afe,", "whereon there hang a thousand bucklers,"], ["o talita uma o toa.", "all shields of mighty men."]]},
  {num:5,words:[["O ou susu e lua ua pei o tamai sevi e lua, o le ui lua a le sevi,", "Thy two breasts are like two young roes that are twins,"], ["o loo tataa i totonu o susana.", "which feed among the lilies."]]},
  {num:6,words:[["Ou te alu atu i le mauga o i ai le muro,", "Until the day break,"], ["ma le mea maupuepue o i ai le lipano;", "and the shadows flee away,"], ["seia gafoa le ata,", "I will get me to the mountain of myrrh,"], ["ma mavae le ufiata.", "and to the hill of frankincense."]]},
  {num:7,words:[["La'u uo e,", "Thou art all fair,"], ["ua sao lou lalelei,", "my love;"], ["e leai lava se pona ia te oe.", "there is no spot in thee."]]},
  {num:8,words:[["Ina ta tuua ia o Lepanona,", "Come with me from Lebanon,"], ["la'u avā e,", "my spouse,"], ["ina ta tuua Lepanona. Se'i e vaavaai nai le tumutumu o Amana,", "with me from Lebanon: look from the top of Amana,"], ["ma le tumutumu o Senira ma Heremoni,", "from the top of Shenir and Hermon,"], ["ma ana o leona,", "from the lions' dens,"], ["ma mauga o nameri.", "from the mountains of the leopards."]]},
  {num:9,words:[["Ua avea lo'u loto ia te oe,", "Thou hast ravished my heart,"], ["lo'u tuafafine e,", "my sister,"], ["la'u avā e;", "my spouse;"], ["ua avea lo'u loto i le tasi o ou mata,", "thou hast ravished my heart with one of thine eyes,"], ["ma le tasi asoa o i lou ua.", "with one chain of thy neck."]]},
  {num:10,words:[["Lo'u tuafafine e, la'u avā e,", "How fair is thy love,"], ["ua silisili ese lou alofa mai;", "my sister,"], ["e sili ona lelei o lou alofa mai i le uaina; o le nanamu foi o ou suāuu e sili i mea manogi uma.", "my spouse! how much better is thy love than wine! and the smell of thine ointments than all spices!"]]},
  {num:11,words:[["La'u avā e,", "Thy lips,"], ["ua sisina ifo meli i ou laugutu;", "O my spouse,"], ["o i lalo o lou laulaufaiva le meli ma le suāsusu;", "drop as the honeycomb: honey and milk are under thy tongue;"], ["o le nanamu foi o ou ofu ua pei o le nanamu o Lepanona.", "and the smell of thy garments is like the smell of Lebanon."]]},
  {num:12,words:[["O lo'u tuafafine,", "A garden inclosed is my sister,"], ["o la'u avā,", "my spouse;"], ["o le faatoaga ua puipuia o ia; o le vaipuna ua puipui;", "a spring shut up,"], ["o le punāvai ua faamaufaailogaina.", "a fountain sealed."]]},
  {num:13,words:[["O au laau muli o le torimoni ia ,", "Thy plants are an orchard of pomegranates,"], ["ma ona fua e sili ona lelei;", "with pleasant fruits;"], ["o le kofera atoa ma le nato,", "camphire,"], ["o le nato ma le keroko;", "with spikenard,"]]},
  {num:14,words:[["o le kani ma le kinamomi,", "Spikenard and saffron;"], ["atoa ma laau uma o le lipano;", "calamus and cinnamon,"], ["o le muro ma le aloe,", "with all trees of frankincense; myrrh and aloes,"], ["atoa ma mea uma e sili ona manogi;", "with all the chief spices:"]]},
  {num:15,words:[["o le punāvai i faatoaga;", "A fountain of gardens,"], ["o le punāvai ola;", "a well of living waters,"], ["o vaitafe foi mai Lepanona.", "and streams from Lebanon."]]},
  {num:16,words:[["Le matu e,", "Awake,"], ["ina ala mai ia;", "O north wind;"], ["le toga e,", "and come,"], ["ina sau ia;", "thou south;"], ["agi mai i la'u faatoaga,", "blow upon my garden,"], ["ina ia puaiina lona manogi. Ia maliu mai lo'u manamea i lana faatoaga,", "that the spices thereof may flow out. Let my beloved come into his garden,"], ["ma taumafa i ona fua e sili ona lelei.", "and eat his pleasant fruits."]]},
];
renderVerseSet(sng_ch_4_Verses, 'sng-ch4-verses');

var sng_ch_5_Verses = [
  {num:1,words:[["Lo'u tuafafine e,", "I am come into my garden,"], ["la'u avā e,", "my sister,"], ["ua ou sau i la'u faatoaga;", "my spouse:"], ["ua ou tau lo'u muro atoa ma la'u mea manogi;", "I have gathered my myrrh with my spice;"], ["ua ou 'aina la'u meli ua sisina ifo ma la'u meli;", "I have eaten my honeycomb with my honey;"], ["ua ou inu la'u uaina ma la'u suāsusu. A'u uo e,", "I have drunk my wine with my milk: eat,"], ["ina taumamafa ia;", "O friends;"], ["a'u uo pele e,", "drink,"], ["ina feinu ia outou,", "yea,"], ["feinu ia,", "drink abundantly,"], ["ia malilie.", "O beloved."]]},
  {num:2,words:[["Ua ou moe a'u,", "I sleep,"], ["a e ala lo'u loto. O le leo o lo'u manamea! O loo tu'itu'i mai o ia,", "but my heart waketh:"], ["ua faapea mai ,", "it is the voice of my beloved that knocketh,"], ["Lo'u tuafafine e,", "saying,"], ["la'u uo e,", "Open to me, my sister,"], ["la'u lupe e,", "my love,"], ["le ua sao ona lelei,", "my dove,"], ["tatala mai ia le puipui ia te au,", "my undefiled:"], ["auā ua sūsū lo'u ulu i le sau,", "for my head is filled with dew,"], ["o'u lauulu foi i le ma'ulu o le sau i le po.", "and my locks with the drops of the night."]]},
  {num:3,words:[["Ua ou to ese lo'u ofu,", "I have put off my coat;"], ["pe faapefea ona ou toe ofu ai? Ua ou mulumulu i o'u vae,", "how shall I put it on? I have washed my feet;"], ["pe faapefea ona ou toe faaeleelea ai?", "how shall I defile them?"]]},
  {num:4,words:[["Na tuuina mai e lo'u manamea lona lima i le pu o le puipui ,", "My beloved put in his hand by the hole of the door,"], ["ona mutimuti vale lea o lo'u loto ia te ia.", "and my bowels were moved for him."]]},
  {num:5,words:[["Na ou tulai e tatala le puipui i lo'u manamea,", "I rose up to open to my beloved;"], ["na sisina ifo foi le muro ai o'u lima,", "and my hands dropped with myrrh, and my fingers with sweet smelling myrrh,"], ["ma le muro sisina nai o'u tamatamai lima i le 'au o le faamau.", "upon the handles of the lock."]]},
  {num:6,words:[["Ua ou talā le puipui i lo'u manamea,", "I opened to my beloved;"], ["a ua liliu lo'u manamea,", "but my beloved had withdrawn himself,"], ["ua alu ese;", "and was gone:"], ["na segia lo'u mauli ina o tautala mai o ia. Ua ou saili ia te ia,", "my soul failed when he spake: I sought him,"], ["a e lei maua;", "but I could not find him;"], ["na ou valaau atu ia te ia,", "I called him,"], ["a e lei tali mai o ia ia te au.", "but he gave me no answer."]]},
  {num:7,words:[["Na maua a'u e leoleo e na feoai i le aai,", "The watchmen that went about the city found me,"], ["na latou fasi ia te au,", "they smote me, they wounded me;"], ["ua ou manua ia te i latou. Na faoa e leoleo pa lo'u ie e ufita'i lo'u tino.", "the keepers of the walls took away my veil from me."]]},
  {num:8,words:[["Tama fafine a Ierusalema e,", "I charge you,"], ["ou te fai atu ia te outou ia tauto mai,", "O daughters of Jerusalem,"], ["afai tou te iloa lo'u manamea tou te ta'u atu ia te ia,", "if ye find my beloved, that ye tell him,"], ["ua ou vaivai au i lo'u alofa atu.", "that I am sick of love."]]},
  {num:9,words:[["O oe na,", "What is thy beloved more than another beloved,"], ["lē sili ona lalelei i fafine, se a se mea e sili ai lou manamea i se isi manamea? se a se mea e sili ai lou manamea i se isi manamea,", "O thou fairest among women? what is thy beloved more than another beloved,"], ["ina ua e fai mai matou te tauto?", "that thou dost so charge us?"]]},
  {num:10,words:[["O lo'u manamea, e sinasina ma le mūmū,", "My beloved is white and ruddy,"], ["e silisili ese i le mano.", "the chiefest among ten thousand."]]},
  {num:11,words:[["O lona ulu ua pei o le auro ua faamamāina;", "His head is as the most fine gold,"], ["o ona lauulu ua faapuloulou,", "his locks are bushy,"], ["ua uliuli e pei o se oreva.", "and black as a raven."]]},
  {num:12,words:[["O ona mata e pei ni mata o se lupe e latalata ane i vaitafe,", "His eyes are as the eyes of doves by the rivers of waters, washed with milk,"], ["o loo taeele i le suāsusu ma nonofo i le mau.", "and fitly set."]]},
  {num:13,words:[["O ona alafau ua pei o se topasama,", "His cheeks are as a bed of spices,"], ["ma mea maupuepue o i ai laau manogi;", "as sweet flowers:"], ["o ona laugutu o susana ia,", "his lips like lilies,"], ["ua sisina ifo ai le muro sisina.", "dropping sweet smelling myrrh."]]},
  {num:14,words:[["O ona lima ua pei o mama auro ua tuuina i ai tasesa; o lona manava ua pei o nifo o elefane ua faapupulaina,", "His hands are as gold rings set with the beryl:"], ["ma ua ufitia i safaira.", "his belly is as bright ivory overlaid with sapphires."]]},
  {num:15,words:[["O ona vae o pou sesa ia,", "His legs are as pillars of marble,"], ["ua faatuina i luga o lago auro lelei;", "set upon sockets of fine gold:"], ["ua foliga o ia i Lepanona,", "his countenance is as Lebanon,"], ["ua sili ona lelei e pei o arasi.", "excellent as the cedars."]]},
  {num:16,words:[["O lona fofoga ua matuā leo malie. Ua atoatoa ona lelei o ia. Tama fafine a Ierusalema e,", "His mouth is most sweet: yea,"], ["o lo'u manamea lava lea,", "he is altogether lovely. This is my beloved,"], ["o la'u uo foi lea.", "and this is my friend, O daughters of Jerusalem."]]},
];
renderVerseSet(sng_ch_5_Verses, 'sng-ch5-verses');

var sng_ch_6_Verses = [
  {num:1,words:[["O oe na le sili ona lalelei i fafine, po o fea ua alu i ai lou manamea? po o fea ua afe ane i ai lou manamea,", "Whither is thy beloved gone,"], ["ia tatou sailiili ia te ia faatasi ma oe?", "O thou fairest among women? whither is thy beloved turned aside? that we may seek him with thee."]]},
  {num:2,words:[["Ua alu ifo lo'u manamea i lana faatoaga,", "My beloved is gone down into his garden,"], ["i topasama,", "to the beds of spices,"], ["e taumafa i ana faatoaga,", "to feed in the gardens,"], ["ma tau ai susana.", "and to gather lilies."]]},
  {num:3,words:[["O lo'u manamea ua fai a'u mona,", "I am my beloved's,"], ["o ia foi ua fai mo'u;", "and my beloved is mine:"], ["o loo taumafa o ia i totonu o susana.", "he feedeth among the lilies."]]},
  {num:4,words:[["La'u pele e,", "Thou art beautiful,"], ["ua lalelei oe,", "O my love,"], ["e pei o Tiresa;", "as Tirzah,"], ["ua aulelei e pei o Ierusalema;", "comely as Jerusalem,"], ["ua matautia e pei o le 'au ua i ai tagavai.", "terrible as an army with banners."]]},
  {num:5,words:[["Ina liliu ese ia ou fofoga ia te au,", "Turn away thine eyes from me,"], ["auā ua ou fefe ai;", "for they have overcome me:"], ["o lou lauulu ua pei o fulufulu o le lafu 'oti ua taooto mai i Kiliata.", "thy hair is as a flock of goats that appear from Gilead."]]},
  {num:6,words:[["O ou nifo ua pei o le lafu mamoe ua o ae ai le fulufuluga,", "Thy teeth are as a flock of sheep which go up from the washing,"], ["e taitasi o i latou uma ma taiuilua,", "whereof every one beareth twins,"], ["e leai foi se tasi o i latou e pa.", "and there is not one barren among them."]]},
  {num:7,words:[["Ua pei o se fāsi rimoni ou alafau i totonu o lou ie ufimata.", "As a piece of a pomegranate are thy temples within thy locks."]]},
  {num:8,words:[["E toaonogafulu o masiofo;", "There are threescore queens,"], ["e toavalugafulu o palake;", "and fourscore concubines,"], ["o taupou foi e le mafaitaulia.", "and virgins without number."]]},
  {num:9,words:[["O la'u lupe,", "My dove,"], ["o le ua sao ona lelei,", "my undefiled is but one; she is the only one of her mother,"], ["e toatasi o ia,", "she is the choice one of her that bare her. The daughters saw her,"], ["o le toatasi o ia i lona tinā,", "and blessed her;"], ["o le pele a le na fanaua o ia. Na vaavaai mai ia te ia o teine,", "yea, the queens and the concubines,"], ["ona latou faaamuia mai ai lea ia te ia. O masiofo ma palake na latou vivii mai foi ia te ia.", "and they praised her."]]},
  {num:10,words:[["O ai ea lena ua sisila mai e pei o le taeao;", "Who is she that looketh forth as the morning,"], ["e lalelei mai e pei o le masina;", "fair as the moon,"], ["e pupula mai e pei o le la;", "clear as the sun,"], ["e matautia e pei o le 'au ua i ai tagavai?", "and terrible as an army with banners?"]]},
  {num:11,words:[["Na ou alu ifo i lo'u toekosi,", "I went down into the garden of nuts to see the fruits of the valley,"], ["e matamata ai i mea e tutupu i le vanu; e matamata po ua fuga le vine,", "and to see whether the vine flourished,"], ["po ua mātala fuga o rimoni.", "and the pomegranates budded."]]},
  {num:12,words:[["A o lei iloa e a'u ua tuuina ai a'u e lo'u loto i kariota o Aminatipo.", "Or ever I was aware, my soul made me like the chariots of Amminadib."]]},
  {num:13,words:[["Foi mai ia,", "Return,"], ["ina foi mai ia,", "return,"], ["le Sulami e;", "O Shulamite;"], ["ia e foi mai,", "return,"], ["foi mai ia,", "return,"], ["matou te maimoa ai ia te oe. Tou te maimoa i ni a i le Sulami? E peiseai o le siva o 'au e lua.", "that we may look upon thee. What will ye see in the Shulamite? As it were the company of two armies."]]},
];
renderVerseSet(sng_ch_6_Verses, 'sng-ch6-verses');

var sng_ch_7_Verses = [
  {num:1,words:[["Le tausala e,", "How beautiful are thy feet with shoes,"], ["e matagofie naua ou vae i see;", "O prince's daughter! the joints of thy thighs are like jewels,"], ["o le fa'iga o ou suilapalapa ua pei o se asoa ua faia e lima o le tufuga.", "the work of the hands of a cunning workman."]]},
  {num:2,words:[["O lou pute ua pei o se ipu lapotopoto ua i ai le uaina ua suia;", "Thy navel is like a round goblet, which wanteth not liquor:"], ["o lou manava ua pei o le faaputugāsaito ua afei i susana.", "thy belly is like an heap of wheat set about with lilies."]]},
  {num:3,words:[["O ou susu e lua ua pei o tamai sevi e lua, o le ui lua a le sevi.", "Thy two breasts are like two young roes that are twins."]]},
  {num:4,words:[["O lou ua ua pei o se 'olo o nifo o elefane;", "Thy neck is as a tower of ivory;"], ["o ou mata ua pei o vailepa i Hesepona e latalata ane i le faitotoa o Peterepima;", "thine eyes like the fishpools in Heshbon, by the gate of Bath-rabbim:"], ["o lou isu ua pei o le 'olo o Lepanona e feagai ma Tamaseko.", "thy nose is as the tower of Lebanon which looketh toward Damascus."]]},
  {num:5,words:[["O lou ulu i ou luga ua pei o Karamelu,", "Thine head upon thee is like Carmel,"], ["ma lou lauulu ua pei o ie pauli;", "and the hair of thine head like purple;"], ["ua taofia le tupu i ou lauulu.", "the king is held in the galleries."]]},
  {num:6,words:[["Le pele e,", "How fair and how pleasant art thou,"], ["ua matuā lalelei oe, ua matuā matagofie oe,", "O love,"], ["e faafiafia ai.", "for delights!"]]},
  {num:7,words:[["Ua faapea lou maualuga, ua tusa ma le pama;", "This thy stature is like to a palm tree,"], ["o ou susu foi e pei o fuifui vine .", "and thy breasts to clusters of grapes."]]},
  {num:8,words:[["Na ou faapea ifo,", "I said,"], ["Ou te alu ae i le pama,", "I will go up to the palm tree,"], ["ou te tago atu i ona lau;", "I will take hold of the boughs thereof:"], ["ona avea lea o ou susu e pei o fuifui vine,", "now also thy breasts shall be as clusters of the vine,"], ["ma le nanamu o lou isu e pei o moli.", "and the smell of thy nose like apples;"]]},
  {num:9,words:[["O lou fofoga foi e pei e le uaina lelei mā lo'u manamea,", "And the roof of thy mouth like the best wine for my beloved, that goeth down sweetly,"], ["ua tafe malie e faagaganaina ai laugutu o e momoe.", "causing the lips of those that are asleep to speak."]]},
  {num:10,words:[["Ua fai a'u mo lo'u manamea,", "I am my beloved's,"], ["ua uai mai foi lona manao ia te au.", "and his desire is toward me."]]},
  {num:11,words:[["Lo'u manamea e,", "Come,"], ["ina sau ia,", "my beloved,"], ["ina ta o atu ia i le vao;", "let us go forth into the field;"], ["ma momoe i faoa aai.", "let us lodge in the villages."]]},
  {num:12,words:[["Ia ta ala usu atu i tovine,", "Let us get up early to the vineyards;"], ["ma ta matamata ai po ua fuga vine,", "let us see if the vine flourish,"], ["po ua mātala ona fuga,", "whether the tender grape appear,"], ["po ua tupu olaola rimoni;", "and the pomegranates bud forth:"], ["ou te alofa atu ia te oe i lea mea.", "there will I give thee my loves."]]},
  {num:13,words:[["Ua puaiina mai le nanamu o tutaima;", "The mandrakes give a smell,"], ["e latalata ane foi i o tatou faitotoa o fua uma e sili ona lelei;", "and at our gates are all manner of pleasant fruits,"], ["o fua ua faatoa tau atoa ma fua ua loa,", "new and old,"], ["ua ou faaputuina mā oe,", "which I have laid up for thee,"], ["lo'u manamea e.", "O my beloved."]]},
];
renderVerseSet(sng_ch_7_Verses, 'sng-ch7-verses');

var sng_ch_8_Verses = [
  {num:1,words:[["E! ana fai oe mo'u tuagane,", "O that thou wert as my brother,"], ["ana e susu i susu o lo'u tinā,", "that sucked the breasts of my mother! when I should find thee without,"], ["ona ta feasogi ai lea ma oe,", "I would kiss thee;"], ["pe a ou iloa oe i fafo;", "yea,"], ["a e latou te le inosia ai a'u.", "I should not be despised."]]},
  {num:2,words:[["Ona ou ta'ita'i ai lea ia te oe,", "I would lead thee,"], ["ma ou aumaia oe i le fale o lo'u tinā,", "and bring thee into my mother's house,"], ["e te a'oa'o mai ia te au;", "who would instruct me:"], ["ou te avatu ia te oe le uaina manogi ma le sua o la'u rimoni e te inu ai.", "I would cause thee to drink of spiced wine of the juice of my pomegranate."]]},
  {num:3,words:[["Ua i lalo o lo'u ulu lona lima tauagavale,", "His left hand should be under my head,"], ["ua fusi mai foi ia te au lona lima taumatau.", "and his right hand should embrace me."]]},
  {num:4,words:[["Tama fafine a Ierusalema e,", "I charge you,"], ["ou te fai atu ia te outou,", "O daughters of Jerusalem,"], ["ia tauto mai,", "that ye stir not up,"], ["tou te le tatatuli pe fafagu i la'u pele,", "nor awake my love,"], ["seia faitalia lava o ia.", "until he please."]]},
  {num:5,words:[["O ai ea lena,", "Who is this that cometh up from the wilderness,"], ["o loo alu ae mai le vao,", "leaning upon her beloved? I raised thee up under the apple tree:"], ["o loo faalagolago i lona manamea? Na ou fafagu ia te oe i lalo o le moli; na oono ai lou tinā ia te oe i lea mea;", "there thy mother brought thee forth:"], ["na ia oono ai ma fanau mai ai e ia o oe i lea mea.", "there she brought thee forth that bare thee."]]},
  {num:6,words:[["Ia tuuina a'u i lou loto e faapei o se faamaufaailoga,", "Set me as a seal upon thine heart,"], ["e faapei o se faamaufaailoga i lou lima;", "as a seal upon thine arm:"], ["auā ua malosi le alofa e pei o le oti;", "for love is strong as death;"], ["ua faauluulumamau le tuinanau e faapei o le tuugamau;", "jealousy is cruel as the grave:"], ["o lona mumū,", "the coals thereof are coals of fire,"], ["o le mumū lea o le afi mu saesae.", "which hath a most vehement flame."]]},
  {num:7,words:[["E le mafaia i vai e tele ona tineia le alofa,", "Many waters cannot quench love, neither can the floods drown it:"], ["e le mafai ona lofia i vaitafe. A avatu e se tagata le oloa uma o i lona fale ia alofaina o ia e ta'ufaatauvaaina lava.", "if a man would give all the substance of his house for love, it would utterly be contemned."]]},
  {num:8,words:[["Ua ia te i matou le uso itiiti e leai ni ona susu;", "We have a little sister, and she hath no breasts:"], ["se a se mea tatou te faia mo lo matou uso i se aso e au mai ai se tautalatala ia te ia?", "what shall we do for our sister in the day when she shall be spoken for?"]]},
  {num:9,words:[["Afai o se pa o ia,", "If she be a wall,"], ["ona tatou ati ae ai lea i ona luga o se 'olo ario;", "we will build upon her a palace of silver:"], ["a e afai o se puipui o ia,", "and if she be a door,"], ["ona tatou pupuni ai lea i ai i laupapa arasi.", "we will inclose her with boards of cedar."]]},
  {num:10,words:[["O a'u nei o le pa,", "I am a wall,"], ["o o'u susu foi ua pei o 'olo;", "and my breasts like towers:"], ["ona avea ai lea o a'u i ona luma e pei o se ua alofaina.", "then was I in his eyes as one that found favour."]]},
  {num:11,words:[["Na ia Solomona le tovine i Paala-amoni;", "Solomon had a vineyard at Baal-hamon;"], ["na ia tuuina atu le tovine i leoleo;", "he let out the vineyard unto keepers;"], ["e taitoatasi o i latou ma au mai tupe e afe i ona fua.", "every one for the fruit thereof was to bring a thousand pieces of silver."]]},
  {num:12,words:[["O lo'u tovine,", "My vineyard,"], ["o lo'u lava ia,", "which is mine, is before me:"], ["ua i o'u luma. Solomona e,", "thou,"], ["mā oe le afe;", "O Solomon, must have a thousand,"], ["a ia lua selau mā e o leoleo i ona fua.", "and those that keep the fruit thereof two hundred."]]},
  {num:13,words:[["O oe na,", "Thou that dwellest in the gardens,"], ["le o nofo i faatoaga,", "the companions hearken to thy voice:"], ["ua faalogologo e ua faatasi ma oe i lou siufofoga. Ia e faafaalogo mai ai ia te au foi .", "cause me to hear it."]]},
  {num:14,words:[["Lo'u manamea e,", "Make haste,"], ["ina sola ia oe,", "my beloved,"], ["ia pei o le sevi oe po o le tamai aila i luga o mauga o i ai mea manogi.", "and be thou like to a roe or to a young hart upon the mountains of spices."]]},
];
renderVerseSet(sng_ch_8_Verses, 'sng-ch8-verses');

})();