(function() {
var _tit_ch_1_Verses = [
  {num:1,words:[["O a'u", "I am"], ["o Paulo,", "Paul"], ["o le auauna", "the servant"], ["a le Atua,", "of God"], ["ma le aposetolo", "and the apostle"], ["a Iesu Keriso,", "of Jesus Christ"], ["ona", "and"], ["o le faatuatua", "the faith"], ["o", "o"], ["e ua filifilia", "by chosen"], ["e le Atua,", "God"], ["ma le iloa lelei", "and the know good"], ["o le upu moni", "the word true"], ["e iu ai", "to become of"], ["i le amio Atua,", "in the conduct God"]]},
  {num:2,words:[["i le faamoemoe", "in the hope"], ["i le ola", "in the life"], ["e faavavau,", "forever/everlasting"], ["na folafolaina mai", "preached from"], ["talu mai tausaga", "since from year"], ["o le vavau", "the ancient times"], ["e le Atua e le mafai ona", "God by the able then"], ["tala pepelo;", "side false"]]},
  {num:3,words:[["a", "but"], ["ua faalia mai", "made a net from"], ["lana lava afioga", "his indeed word (divine)"], ["i ona po", "in then night"], ["e tatau ai", "it is fitting"], ["i le tala'iga", "in the tala'iga"], ["ua tuuina mai ia te au,", "given from I"], ["e tusa ma le poloaiga", "according to the commandment"], ["a le Atua lo tatou Faaola;", "of God our save"]]},
  {num:4,words:[["o la'u tusi lenei", "this letter"], ["ia Tito", "to Titus"], ["lo'u lava atalii", "my indeed son"], ["i la le faatuatua", "in the faith"], ["ua tuu tele,", "put great"], ["ia ia te oe", "to him you"], ["le alofa tunoa,", "grace"], ["ma le alofa,", "and the love"], ["ma le manuia", "and peace"], ["mai le Atua", "from God"], ["le Tamā,", "the father"], ["atoa ma le Alii", "and the Lord"], ["o Iesu Keriso lo tatou Faaola.", "Jesus Christ our save"]]},
  {num:5,words:[["O le mea lenei", "the thing this"], ["na ou tuu ai", "I put"], ["oe", "you"], ["i Kereta,", "in Kereta"], ["ina ia", "so that"], ["e faatonuina mea", "to commanded thing"], ["ua totoe,", "phiral of foe"], ["ma ia", "and to"], ["e tofia toeaina", "to chosen elder"], ["i lea", "in"], ["aai", "city"], ["ma lea", "and"], ["aai,", "city"], ["faapei", "like"], ["ona ou fai atu ai", "and I said to"], ["ia te oe;", "unto you"]]},
  {num:6,words:[["ai", "ai"], ["se tasi", "a one"], ["e le mata'uleagaina,", "by the mata'uleagaina"], ["o le tane", "the man"], ["a le fafine", "but the woman"], ["e toatasi,", "to one One"], ["o", "o"], ["i ai", "therein"], ["ana fanau", "his born"], ["e faatuatua,", "to faith"], ["e lei ta'ua", "by not us (two, incl)"], ["i latou", "them"], ["ua ulavavale", "ulavavale"], ["pe soli", "whether to tread upon"], ["i tulafono.", "in law"]]},
  {num:7,words:[["Auā", "for"], ["e tatau lava", "it is fitting indeed"], ["i le epikopo", "in the bishop"], ["ona", "and"], ["le mata'uleagaina o ia,", "the mata'uleagaina he"], ["auā o ia", "for he"], ["le auauna", "the servant"], ["e tausi", "to nurse"], ["i mea", "in thing"], ["a le Atua;", "of God"], ["e le finau vale,", "by the contend foolish"], ["e le itagofie,", "by the itagofie"], ["e le inu tele", "by the drink great"], ["i uaina,", "in wine"], ["e le fasi tagata,", "by the kill man"], ["e le manumanu", "by the manumanu"], ["i oloa;", "in goods"]]},
  {num:8,words:[["a o lē alofa", "but of not love"], ["i tagata ese,", "in man away"], ["o lē alofa", "not love"], ["i", "in"], ["e amio lelei,", "to conduct good"], ["o lē faautauta,", "not careful"], ["o lē amiotonu,", "not righteous"], ["o lē amio Atua,", "not conduct God"], ["ma le", "and the"], ["le gaoiā;", "the gaoiā"]]},
  {num:9,words:[["o lē taofi mau", "not hold opinion"], ["i le upu moni,", "in the word true"], ["faapei", "like"], ["ona a'oa'oina o ia,", "and taught he"], ["ina ia mafaia", "so that able"], ["e ia", "by him"], ["ona apoapoai atu", "and exhort"], ["i le mataupu", "in the chapter"], ["e ola ai,", "to life"], ["ma aoai atu", "and chastise"], ["i", "in"], ["e finau mai.", "to contend"]]},
  {num:10,words:[["Auā", "for"], ["e toatele o", "many"], ["e solitulafono", "to transgression"], ["ua tautalatala", "tautalatala"], ["i upu", "in word"], ["le aoga", "the useful"], ["ma faasese atu,", "and to cause to go astray"], ["a", "but"], ["e sili musa", "to most to skip"], ["le au peritome;", "the I circumcision"]]},
  {num:11,words:[["e tatau", "it is fitting/ought"], ["ina punitia o latou", "so that shut of they"], ["gutu;", "mouth"], ["ua latou faaliliu ese", "they to turn round away"], ["i nisi aiga", "in some family"], ["atoa,", "together with"], ["o loo a'oa'o", "is (progressive) excellent"], ["i mea", "in thing"], ["le tatau,", "the to wring out"], ["ina", "so that"], ["ua matapeapea", "matapeapea"], ["i le oloa.", "in the goods"]]},
  {num:12,words:[["Sa faapea mai le", "saying from the"], ["tasi o", "one of"], ["i latou,", "them"], ["o", "o"], ["sa latou lava", "they indeed"], ["perofeta,", "prophet"], ["O tagata Kereta,", "of men Kereta"], ["e sagasaga tala pepelo", "by sagasaga side false"], ["lava", "indeed"], ["i latou,", "them"], ["o manu feai leaga,", "animal wild evil"], ["o", "o"], ["e usuusua'i", "by usuusua'i"], ["ina 'ai.", "so that eat"]]},
  {num:13,words:[["O le molimau moni lava lea.", "the a witness true indeed"], ["O le mea lea", "therefore"], ["ia maamaai", "to maamaai"], ["ona", "and"], ["e aoai atu ai", "to chastise"], ["ia te", "unto"], ["i latou,", "them"], ["ina ia latou", "so that they"], ["faamaoni", "faithful"], ["i le faatuatua;", "in the faith"]]},
  {num:14,words:[["aua ne'i taofi", "for now hold"], ["i tala", "in side"], ["o le vavau faa-Iutaia,", "the ancient times faa-iutaia"], ["ma poloaiga", "and commandment"], ["a tagata o", "but man of"], ["e liliu ese", "to turned away"], ["i le upu moni.", "in the word true"]]},
  {num:15,words:[["Ua mamā mea uma", "clean all things"], ["i", "in"], ["e ua loto mamā,", "by heart clean"], ["a o", "but of"], ["e loto eleelea", "to heart eleelea"], ["ma le", "and the"], ["le faatuatua,", "the faith"], ["e le mamā", "by the clean"], ["ia te", "unto"], ["i latou", "them"], ["se mea", "a thing"], ["e tasi,", "by one"], ["a", "but"], ["ua eleelea o", "eleelea of"], ["latou mafaufau", "they think"], ["atoa ma o latou", "and they"], ["loto fuatia ifo.", "heart weighed down"]]},
  {num:16,words:[["Ua latou ta'u ane", "they told"], ["ua latou iloa", "they knew"], ["le Atua,", "God"], ["a", "but"], ["e faafiti ia te ia", "to denied to him"], ["i", "in"], ["a latou galuega,", "but they work"], ["o inosia", "abominable"], ["i latou", "them"], ["ma faalogogata,", "and faalogogata"], ["latou te", "they will"], ["le faamaoni foi", "the faithful also"], ["i se galuega lelei", "in a work good"], ["e tasi.", "by one"]]},
];
renderVerseSet(_tit_ch_1_Verses, 'tit-ch1-verses');

var _tit_ch_2_Verses = [
  {num:1,words:[["A o oe,", "but of you"], ["ia", "to"], ["e tautala atu", "to speak toward"], ["i mea", "in thing"], ["e tusa ma le mataupu", "according to the chapter"], ["e ola ai;", "to life"]]},
  {num:2,words:[["fai atu", "said to"], ["i toeaina ia", "in elder to"], ["mataala", "mataala"], ["i latou,", "them"], ["ia faatoeaina,", "to sedate"], ["ia faautauta,", "to careful"], ["ia faamaoni", "to faithful"], ["i le faatuatua,", "in the faith"], ["ma le alfoa,", "and the alfoa"], ["ma le onosai.", "and the patience"]]},
  {num:3,words:[["Ia faapena foi", "to likewise also"], ["loomatutua,", "loomatutua"], ["ia amio", "to conduct"], ["i latou", "them"], ["i le amio Atua,", "in the conduct God"], ["aua ne'i faatuaupua,", "for now faatuaupua"], ["aua ne'i faapologaina", "for now to enslave"], ["i latou", "them"], ["i le uaina,", "in the wine"], ["a ia fai ma a'oa'o", "but to to be excellent"], ["i mea lelei,", "in thing good"]]},
  {num:4,words:[["ina ia latou", "so that they"], ["a'oa'o atu", "excellent"], ["i fafine muli latou te alofa atu", "in woman muli they will love"], ["i", "in"], ["a latou tane,", "but they man"], ["ia alofa atu", "to love"], ["i", "in"], ["a latou fanau,", "but they born"], ["ia faautauta", "to careful"], ["i latou,", "them"]]},
  {num:5,words:[["ia le gaoiā,", "to the gaoiā"], ["ia tausi lelei", "to nurse good"], ["i o latou", "in of they"], ["aiga,", "family"], ["ia agalelei,", "to treated well"], ["ia usiusitai atu", "to obeyed"], ["i", "in"], ["a latou lava tane,", "but they indeed man"], ["ina ne'i upuleagaina", "so that now upuleagaina"], ["le afioga", "the word (divine)"], ["a le Atua.", "of God"]]},
  {num:6,words:[["Ia faapea foi", "to thus also"], ["ona", "and"], ["e apoapoai atu", "to exhort"], ["i taulelea,", "in young men"], ["ia faautauta", "to careful"], ["i latou.", "them"]]},
  {num:7,words:[["Ia avea oe", "to become you"], ["a faaa'oa'o o galuega lelei", "but make excellent of work good"], ["i mea uma lava;", "in all things"], ["ia", "to"], ["e a'oa'o", "to excellent"], ["i le mataupu", "in the chapter"], ["ma le faamaoni,", "and the faithful"]]},
  {num:8,words:[["ma le faatoeaina,", "and the sedate"], ["ma le upu", "and the word"], ["e ola ai,", "to life"], ["e le mata'uleagaina,", "by the mata'uleagaina"], ["ina ia faamāina ai", "so that faamāina"], ["o lē tetee", "not to refuse"], ["mai,", "from"], ["ina", "so that"], ["ua", "ua"], ["le maua e", "the received by"], ["ia se mea leaga", "to a thing evil"], ["e talatala ane ai", "to to untie"], ["ia te outou.", "unto you"]]},
  {num:9,words:[["Apoapoai atu", "exhort"], ["i pologa ia", "in mouldy to"], ["usiusitai", "obeyed"], ["i latou", "them"], ["i o latou", "in of they"], ["lava matai,", "indeed chief"], ["ia latou taumafai", "to they to strive"], ["ona faafiafia", "and to please"], ["i ai", "therein"], ["i mea uma lava,", "in all things"], ["aua ne'i faatau upu", "for now buy word"], ["i ai.", "therein"]]},
  {num:10,words:[["Aua ne'i latou", "for now they"], ["gaoi,", "to steal"], ["a ia faaalia", "but to revealed"], ["e", "by"], ["i latou", "them"], ["ua latou faamaoni", "they faithful"], ["aiai,", "aiai"], ["ina ia viia ai", "so that praised"], ["i mea uma lava talu", "in all things since"], ["o", "o"], ["i latou", "them"], ["le mataupu", "the chapter"], ["a le Atua lo tatou Faaola.", "of God our save"]]},
  {num:11,words:[["Auā", "for"], ["o le alofa tunoa", "the grace"], ["o le Atua", "of God"], ["ua au mai ai", "brought"], ["le olataga,", "the salvation"], ["ua faaalia mai", "revealed from"], ["lea", "lea"], ["i tagata uma lava,", "in man all indeed"]]},
  {num:12,words:[["o loo a'oa'o", "is (progressive) excellent"], ["mai ai", "from"], ["ia te", "unto"], ["i tatou,", "in we (incl)"], ["ia tatou tete'a ese", "to we (incl) light colored : as away"], ["ma le faalematau", "and the faalematau"], ["atoa ma tu'inanau faalelalolagi,", "and tu'inanau faalelalolagi"], ["a ia tatou", "but to we (incl)"], ["nonofo", "dwelling"], ["ma le faautauta", "and the careful"], ["ma le amiotonu", "and the righteous"], ["atoa ma le amio Atua", "and the conduct God"], ["i lenei", "in this"], ["olaga;", "lifetime"]]},
  {num:13,words:[["o faatalitali atu", "waited"], ["i le faatuatuaga", "in the something to rely"], ["e manuia ai,", "to peace"], ["o le faaalia lea", "the revealed"], ["o le pupula", "the brightness"], ["o le Atua silisili,", "of God very much"], ["o lo tatou Faaola", "our save"], ["o Iesu Keriso lea;", "Jesus Christ"]]},
  {num:14,words:[["o le", "the"], ["na foaiina mai", "given from"], ["o ia e", "he by"], ["ia", "to"], ["mo", "for"], ["i tatou,", "in we (incl)"], ["e togiola a'i", "to atonement"], ["i tatou ai", "in we (incl)"], ["le solitulafono uma lava,", "the transgression all indeed"], ["ma ia faamamāina", "and to purify"], ["mai e ia", "from by him"], ["e fai mona,", "to make to burst forth (as faiai"], ["o lona lava nuu,", "his indeed nation"], ["e maelega", "by maelega"], ["i galuega lelei.", "in work good"]]},
  {num:15,words:[["Ia", "to"], ["e tautala atu", "to speak toward"], ["i ia mea,", "in to thing"], ["ma apoapoai atu,", "and exhort"], ["ma aoai atu", "and chastise"], ["ma le pule", "and the rule"], ["lava.", "indeed"], ["Aua ne'i inosia oe", "for now abominable you"], ["e se tasi.", "by a one"]]},
];
renderVerseSet(_tit_ch_2_Verses, 'tit-ch2-verses');

var _tit_ch_3_Verses = [
  {num:1,words:[["Ia", "to"], ["e faamanatu atu", "to to remind"], ["ia", "to"], ["i latou ia latou", "them to they"], ["usiusitai", "obeyed"], ["i alii sili", "in Lord most"], ["ma faipule,", "and a councillor"], ["ia gauai", "to gauai"], ["i alii,", "in Lord"], ["ia nofo sauniuni foi", "to dwell prepared also"], ["i latou", "them"], ["i galuega lelei uma lava,", "in work good all indeed"]]},
  {num:2,words:[["aua ne'i upu leaga", "for now word evil"], ["i se tasi,", "in a one"], ["aua ne'i faamisa,", "for now to pick a quarrel"], ["a ia faapalepale,", "but to to bear patiently"], ["ma ia faaali atu", "and to revealed"], ["le agamalu uma", "the meek all"], ["i tagata uma lava.", "in man all indeed"]]},
  {num:3,words:[["Auā o", "for of"], ["i tatou foi,", "in we (incl) also"], ["sa vālea", "vālea"], ["i tatou anamua,", "in we (incl) ancient"], ["ma faalogogata,", "and faalogogata"], ["ma faaseseina,", "and deceived astray"], ["sa auauna", "servant"], ["i tu'inanau", "in tu'inanau"], ["ma mea eseese", "and thing divided"], ["e fiafia ai,", "to competition"], ["sa nonofo", "dwelling"], ["ma le loto leaga", "and the heart evil"], ["ma le mataua,", "and the mataua"], ["sa inosia", "abominable"], ["ma feitagai.", "and look upon one another"]]},
  {num:4,words:[["A", "but"], ["ua faaalia mai le", "revealed from the"], ["agalelei", "treated well"], ["ma le alofa", "and the love"], ["i tagata", "in man"], ["o lo tatou Faaola", "our save"], ["le Atua,", "God"]]},
  {num:5,words:[["ona faaola mai ai lea", "and save from then then"], ["o ia ia", "he to"], ["i tatou,", "in we (incl)"], ["e le", "by the"], ["ona o galuega", "because of work"], ["o", "o"], ["i le amiotonu", "in the righteous"], ["sa tatou faia,", "let us make"], ["a", "but"], ["e tusa ma lona", "according to his"], ["lava alofa", "indeed love"], ["i le faataeleina", "in the make bathe"], ["i le toefuataiina", "in the toefuataiina"], ["ma le faafouina", "and the make new"], ["e le Agaga Paia,", "by the Holy Spirit"]]},
  {num:6,words:[["ua", "ua"], ["na faamaligi tele mai", "faamaligi great from"], ["i luga ia", "in above to"], ["i tatou,", "in we (incl)"], ["ona o Iesu Keriso lo tatou Faaola;", "because of Jesus Christ our save"]]},
  {num:7,words:[["ina ia ta'uamiotonuina", "so that ta'uamiotonuina"], ["i tatou", "in we (incl)"], ["i lona lava alofa tunoa,", "in his indeed grace"], ["ia fai", "to make"], ["i tatou", "in we (incl)"], ["ma suli", "and suli"], ["e tusa ma le faamoemoe", "according to the hope"], ["i le ola", "in the life"], ["e faavavau.", "forever/everlasting"]]},
  {num:8,words:[["O le upu moni lena", "the word true that"], ["ou te loto foi", "I will heart also"], ["ina ia", "so that"], ["e matuā faamalosi atu", "to exceedingly be strong"], ["i ia mea,", "in to thing"], ["ina ia naunau", "so that desire"], ["i latou", "them"], ["o", "o"], ["e ua faatuatua", "by faith"], ["i le Atua", "in the God"], ["ona ia faia galuega lelei;", "and to made work good"], ["e lelei lava", "to good indeed"], ["ia mea", "to thing"], ["ma aoga", "and useful"], ["i tagata.", "in man"]]},
  {num:9,words:[["A ia taumamao", "but to taumamao"], ["ma sailiga valea", "and sailiga foolish"], ["ma tala tupuga,", "and side nation"], ["ma le femisaiga,", "and the femisaiga"], ["ma le fefinauaiga", "and the dispute"], ["i la le tulafono;", "in the law"], ["auā o upu", "for of word"], ["le aoga ia", "the useful to"], ["ma le faatauvaa.", "and the vain"]]},
  {num:10,words:[["O le tagata", "man"], ["na te faatupu", "he made king"], ["le fevaevaeaiga ia", "the fevaevaeaiga to"], ["e 'alo ese", "to Son away"], ["ia te ia", "to him"], ["pe a uma atu", "even though / although all"], ["ia te ia", "to him"], ["le aoaiga", "the discipline"], ["e atu tasi", "by one"], ["pe atu lua;", "whether two"]]},
  {num:11,words:[["auā", "for"], ["ua iloa", "knew"], ["o le tagata faapena", "man likewise"], ["ua liliueseina lava", "liliueseina indeed"], ["o ia,", "he"], ["ma", "and"], ["ua agasala,", "sinned"], ["ua faasalaina o ia", "punished he"], ["e ia.", "by him"]]},
  {num:12,words:[["A ou auina atu", "but I sent"], ["ia te oe", "unto you"], ["o Aretima,", "Aretima"], ["po o Tuiko", "night of Tuiko"], ["ia", "to"], ["e faataalise", "to to make haste"], ["ona sau ia te au", "and come unto me"], ["i Nikopoli;", "in Nikopoli"], ["auā", "for"], ["ua tonu", "right"], ["lo'u manatu ou te nofo ai", "my thought I will dwell"], ["i le tausaga maalili.", "in the year maalili"]]},
  {num:13,words:[["Ia", "to"], ["e matuā fesoasoani", "to exceedingly to help"], ["i le malaga", "in the travelling party"], ["a Sena", "of Sena"], ["le a'oa'o tulafono,", "the excellent law"], ["atoa ma Apolo,", "and Apolo"], ["ina ia le mativa", "so that the want"], ["i laua", "them"], ["i se mea", "in a thing"], ["e tasi.", "by one"]]},
  {num:14,words:[["Ia a'oa'oina foi", "to taught also"], ["o latou uso", "they brother"], ["ia faia e", "to made by"], ["i latou galuega lelei", "them work good"], ["e maua ai", "to received"], ["mea aoga,", "thing useful"], ["ina ne'i", "so that now"], ["le fua mai", "the fruit from"], ["i latou.", "them"]]},
  {num:15,words:[["O", "O"], ["i latou uma lava", "them all indeed"], ["o ia te au", "he I"], ["o loo alolofa atu", "is (progressive) alolofa"], ["i latou ia te oe;", "them unto you"], ["ua ou alofa atu ia", "I loved to"], ["i latou", "them"], ["o", "o"], ["e alolofa mai ia te", "by alolofa from"], ["i matou", "in we (excl)"], ["i le faatuatua.", "in the faith"], ["Ia ia te outou uma lava", "to him all of you"], ["le alofa tunoa.", "grace"], ["Amene.", "amen"]]},
];
renderVerseSet(_tit_ch_3_Verses, 'tit-ch3-verses');

})();