(function() {
var tit_ch_1_Verses = [
  {num:1,words:[["O a'u o Paulo,", "I am Paul"], ["o le auauna", "the servant"], ["a le Atua,", "of God"], ["ma le aposetolo", "and the apostle"], ["a Iesu Keriso,", "of Jesus Christ"], ["ona o le faatuatua o", "because of the faith"], ["e ua filifilia", "by chosen"], ["e le Atua,", "by God"], ["ma le iloa lelei", "and the known good"], ["o le upu moni", "the word true"], ["e iu ai", "to attain"], ["i le amio Atua,", "in the conduct God"]]},
  {num:2,words:[["i le faamoemoe", "in the to expect"], ["i le ola", "in the life"], ["e faavavau,", "forever/everlasting"], ["na folafolaina mai talu", "folafolaina from since"], ["mai tausaga", "from year"], ["o le vavau", "the ancient times"], ["e le Atua", "by God"], ["e le mafai", "by the able"], ["ona tala pepelo;", "and side false"]]},
  {num:3,words:[["a ua faalia", "but faalia"], ["mai lana lava afioga", "from his indeed a word"], ["i ona po", "in then night"], ["e tatau ai", "it is fitting"], ["i le tala'iga", "in the tala'iga"], ["ua tuuina mai ia te au,", "given from I"], ["e tusa", "to according to"], ["ma le poloaiga", "and the commandment"], ["a le Atua lo tatou Faaola;", "of God our save"]]},
  {num:4,words:[["o la'u tusi lenei ia Tito lo'u", "this letter to Titus my"], ["lava atalii", "indeed son"], ["i la le faatuatua", "in the faith"], ["ua tuu tele,", "put great"], ["ia ia te oe", "to unto thee"], ["le alofa tunoa,", "grace"], ["ma le alofa,", "and the love"], ["ma le manuia", "and peace"], ["mai le Atua", "from God"], ["le Tamā,", "the father"], ["atoa ma le Alii o Iesu Keriso lo tatou Faaola.", "and the Lord Jesus Christ our save"]]},
  {num:5,words:[["O le mea lenei", "the thing this"], ["na ou tuu ai oe", "I put you"], ["i Kereta,", "in kereta"], ["ina ia", "so that"], ["e faatonuina mea", "by faatonuina thing"], ["ua totoe,", "phiral of foe"], ["ma ia", "and to"], ["e tofia toeaina", "to chosen elder"], ["i lea aai", "in eat"], ["ma lea aai,", "and eat"], ["faapei ona ou fai atu ai", "like then I said to"], ["ia te oe;", "unto thee"]]},
  {num:6,words:[["ai se tasi", "a one"], ["e le mata'uleagaina,", "by the mata'uleagaina"], ["o le tane", "the man"], ["a le fafine", "but the woman"], ["e toatasi,", "to one One"], ["o i ai ana fanau", "therein his born"], ["e faatuatua,", "to faith"], ["e lei ta'ua", "to whale's teeth war"], ["i latou", "them"], ["ua ulavavale", "ulavavale"], ["pe soli", "whether to tread upon"], ["i tulafono.", "in law"]]},
  {num:7,words:[["Auā e tatau lava", "for it is fitting indeed"], ["i le epikopo", "in the bishop"], ["ona le mata'uleagaina o ia,", "and the mata'uleagaina he"], ["auā o ia le auauna", "for he the servant"], ["e tausi", "to keep"], ["i mea", "in thing"], ["a le Atua;", "of God"], ["e le finau vale,", "by the finau foolish"], ["e le itagofie,", "by the itagofie"], ["e le inu tele", "by the drink great"], ["i uaina,", "in wine"], ["e le fasi tagata,", "by the kill man"], ["e le manumanu", "by the manumanu"], ["i oloa;", "in goods"]]},
  {num:8,words:[["a o lē alofa", "but not love"], ["i tagata ese,", "in man away"], ["o lē alofa", "not love"], ["i e amio lelei,", "in to conduct good"], ["o lē faautauta,", "not to devise"], ["o lē amiotonu,", "not righteous"], ["o lē amio Atua,", "not conduct God"], ["ma le", "and the"], ["le gaoiā;", "the gaoiā"]]},
  {num:9,words:[["o lē taofi mau", "not hold opinion"], ["i le upu moni,", "in the word true"], ["faapei ona a'oa'oina o ia,", "like then taught he"], ["ina ia mafaia", "so that able"], ["e ia", "by him"], ["ona apoapoai atu", "and apoapoai"], ["i le mataupu", "in the chapter"], ["e ola ai,", "to life"], ["ma aoai atu", "and aoai"], ["i e finau", "in by finau"], ["mai.", "from"]]},
  {num:10,words:[["Auā e toatele o", "for to many"], ["e solitulafono", "by solitulafono"], ["ua tautalatala", "tautalatala"], ["i upu", "in word"], ["le aoga", "the useful"], ["ma faasese atu,", "and to cause to go astray"], ["a e sili musa", "but to most to skip"], ["le au peritome;", "the I peritome"]]},
  {num:11,words:[["e tatau", "it is fitting/ought"], ["ina punitia o latou gutu;", "let punitia them mouth"], ["ua latou faaliliu ese", "them to turn round away"], ["i nisi aiga", "in some family"], ["atoa,", "together with"], ["o loo a'oa'o", "excellent"], ["i mea", "in thing"], ["le tatau,", "the to wring out"], ["ina ua matapeapea", "let matapeapea"], ["i le oloa.", "in the goods"]]},
  {num:12,words:[["Sa faapea mai", "saying from"], ["le tasi o", "the one"], ["i latou,", "them"], ["o sa latou lava perofeta,", "them indeed prophet"], ["O tagata Kereta,", "man kereta"], ["e sagasaga tala pepelo lava", "by sagasaga side false indeed"], ["i latou,", "them"], ["o manu feai leaga,", "animal feai evil"], ["o e usuusua'i", "who usuusua'i"], ["ina 'ai.", "let eat"]]},
  {num:13,words:[["O le molimau moni lava lea.", "the a witness true indeed"], ["O le mea lea ia maamaai", "therefore to maamaai"], ["ona e aoai atu ai", "and by aoai"], ["ia te", "unto"], ["i latou,", "them"], ["ina ia latou faamaoni", "so that them faithful"], ["i le faatuatua;", "in the faith"]]},
  {num:14,words:[["aua ne'i taofi", "for now hold"], ["i tala", "in side"], ["o le vavau faa-Iutaia,", "the ancient times faa-iutaia"], ["ma poloaiga", "and commandment"], ["a tagata o", "but man"], ["e liliu ese", "to turned away"], ["i le upu moni.", "in the word true"]]},
  {num:15,words:[["Ua mamā mea uma", "clean all things"], ["i e", "in by"], ["ua loto mamā,", "heart clean"], ["a o", "but"], ["e loto eleelea", "to heart eleelea"], ["ma le", "and the"], ["le faatuatua,", "the faith"], ["e le mamā ia te", "by the clean unto"], ["i latou", "them"], ["se mea", "a thing"], ["e tasi,", "by one"], ["a ua eleelea o latou mafaufau", "but eleelea them think"], ["atoa ma o latou loto fuatia ifo.", "and them heart fuatia"]]},
  {num:16,words:[["Ua latou ta'u ane", "them tell"], ["ua latou iloa", "them known"], ["le Atua,", "God"], ["a e faafiti ia te", "but to to deny unto"], ["ia i", "to in"], ["a latou galuega,", "but them work"], ["o inosia", "abominable"], ["i latou", "them"], ["ma faalogogata,", "and faalogogata"], ["latou te", "them"], ["le faamaoni foi", "the faithful also"], ["i se galuega lelei", "in a work good"], ["e tasi.", "by one"]]},
];
renderVerseSet(tit_ch_1_Verses, 'tit-ch1-verses');

var tit_ch_2_Verses = [
  {num:1,words:[["A o oe,", "but you"], ["ia e tautala atu", "to to to talk"], ["i mea", "in thing"], ["e tusa", "to according to"], ["ma le mataupu", "and the chapter"], ["e ola ai;", "to life"]]},
  {num:2,words:[["fai atu", "said to"], ["i toeaina ia mataala", "in elder to mataala"], ["i latou,", "them"], ["ia faatoeaina,", "to sedate"], ["ia faautauta,", "to to devise"], ["ia faamaoni", "to faithful"], ["i le faatuatua,", "in the faith"], ["ma le alfoa,", "and the alfoa"], ["ma le onosai.", "and the onosai"]]},
  {num:3,words:[["Ia faapena foi loomatutua,", "to faapena also loomatutua"], ["ia amio", "to conduct"], ["i latou", "them"], ["i le amio Atua,", "in the conduct God"], ["aua ne'i faatuaupua,", "for now faatuaupua"], ["aua ne'i faapologaina", "for now faapologaina"], ["i latou", "them"], ["i le uaina,", "in the wine"], ["a ia fai", "but to make"], ["ma a'oa'o", "and excellent"], ["i mea lelei,", "in thing good"]]},
  {num:4,words:[["ina ia latou a'oa'o atu", "so that them excellent"], ["i fafine muli latou te alofa atu", "in woman muli them love"], ["i a latou tane,", "in but them man"], ["ia alofa atu", "to love"], ["i a latou fanau,", "in but them born"], ["ia faautauta", "to to devise"], ["i latou,", "them"]]},
  {num:5,words:[["ia le gaoiā,", "to the gaoiā"], ["ia tausi lelei", "to keep good"], ["i o latou aiga,", "in them family"], ["ia agalelei,", "to goodness"], ["ia usiusitai atu", "to usiusitai"], ["i a latou lava tane,", "in but them indeed man"], ["ina ne'i upuleagaina", "let now upuleagaina"], ["le afioga", "the a word"], ["a le Atua.", "of God"]]},
  {num:6,words:[["Ia faapea foi", "to thus also"], ["ona e apoapoai atu", "and by apoapoai"], ["i taulelea,", "in taulelea"], ["ia faautauta", "to to devise"], ["i latou.", "them"]]},
  {num:7,words:[["Ia avea oe", "to become you"], ["a faaa'oa'o o galuega lelei", "but faaa'oa'o work good"], ["i mea uma lava;", "in all things"], ["ia e a'oa'o", "to to excellent"], ["i le mataupu", "in the chapter"], ["ma le faamaoni,", "and the faithful"]]},
  {num:8,words:[["ma le faatoeaina,", "and the sedate"], ["ma le upu", "and the word"], ["e ola ai,", "to life"], ["e le mata'uleagaina,", "by the mata'uleagaina"], ["ina ia faamāina ai o lē tetee", "so that faamāina not to refuse"], ["mai,", "from"], ["ina ua", "let"], ["le maua", "the received"], ["e ia se mea leaga", "by him a thing evil"], ["e talatala ane ai ia te outou.", "to to untie unto you"]]},
  {num:9,words:[["Apoapoai atu", "apoapoai"], ["i pologa ia usiusitai", "in mouldy to usiusitai"], ["i latou", "them"], ["i o latou lava matai,", "in them indeed chief"], ["ia latou taumafai", "to them to strive"], ["ona faafiafia", "and to please"], ["i ai", "therein"], ["i mea uma lava,", "in all things"], ["aua ne'i faatau upu", "for now equally word"], ["i ai.", "therein"]]},
  {num:10,words:[["Aua ne'i latou gaoi,", "for now them to steal"], ["a ia faaalia", "but to faaalia"], ["e i latou", "by them"], ["ua latou faamaoni aiai,", "them faithful aiai"], ["ina ia viia ai", "so that viia"], ["i mea uma lava talu", "in all things since"], ["o i latou", "them"], ["le mataupu", "the chapter"], ["a le Atua lo tatou Faaola.", "of God our save"]]},
  {num:11,words:[["Auā o le alofa tunoa", "for the grace"], ["o le Atua", "of God"], ["ua au mai ai", "bring"], ["le olataga,", "the a means of deliverance"], ["ua faaalia mai lea", "faaalia from"], ["i tagata uma lava,", "in man all indeed"]]},
  {num:12,words:[["o loo a'oa'o", "excellent"], ["mai ai ia te", "from unto"], ["i tatou,", "in us"], ["ia tatou tete'a ese", "to us light colored : as away"], ["ma le faalematau", "and the faalematau"], ["atoa ma tu'inanau faalelalolagi,", "and tu'inanau faalelalolagi"], ["a ia tatou nonofo", "but to us dwelling"], ["ma le faautauta", "and the to devise"], ["ma le amiotonu", "and the righteous"], ["atoa ma le amio Atua", "and the conduct God"], ["i lenei olaga;", "in this lifetime"]]},
  {num:13,words:[["o faatalitali atu", "faatalitali"], ["i le faatuatuaga", "in the something to rely"], ["e manuia ai,", "to peace"], ["o le faaalia lea", "the faaalia"], ["o le pupula", "the brightness"], ["o le Atua silisili,", "of God very much"], ["o lo tatou Faaola o Iesu Keriso lea;", "our save Jesus Christ"]]},
  {num:14,words:[["o le", "the"], ["na foaiina mai o ia", "given from he"], ["e ia", "by him"], ["mo i tatou,", "for in us"], ["e togiola a'i", "to atonement"], ["i tatou ai", "in us"], ["le solitulafono uma lava,", "the solitulafono all indeed"], ["ma ia faamamāina", "and to faamamāina"], ["mai e ia", "from by him"], ["e fai mona,", "to make to burst forth (as faiai"], ["o lona lava nuu,", "his indeed nation"], ["e maelega", "by maelega"], ["i galuega lelei.", "in work good"]]},
  {num:15,words:[["Ia e tautala atu", "to to to talk"], ["i ia mea,", "in to thing"], ["ma apoapoai atu,", "and apoapoai"], ["ma aoai atu", "and aoai"], ["ma le pule lava.", "and the rule indeed"], ["Aua ne'i inosia oe", "for now abominable you"], ["e se tasi.", "by a one"]]},
];
renderVerseSet(tit_ch_2_Verses, 'tit-ch2-verses');

var tit_ch_3_Verses = [
  {num:1,words:[["Ia e faamanatu atu ia", "to to to remind to"], ["i latou ia latou usiusitai", "them to them usiusitai"], ["i alii sili", "in Lord most"], ["ma faipule,", "and a councillor"], ["ia gauai", "to gauai"], ["i alii,", "in Lord"], ["ia nofo sauniuni foi", "to dwell sauniuni also"], ["i latou", "them"], ["i galuega lelei uma lava,", "in work good all indeed"]]},
  {num:2,words:[["aua ne'i upu leaga", "for now word evil"], ["i se tasi,", "in a one"], ["aua ne'i faamisa,", "for now to pick a quarrel"], ["a ia faapalepale,", "but to to bear patiently"], ["ma ia faaali atu", "and to reveal"], ["le agamalu uma", "the agamalu all"], ["i tagata uma lava.", "in man all indeed"]]},
  {num:3,words:[["Auā o", "for"], ["i tatou foi,", "in us also"], ["sa vālea", "vālea"], ["i tatou anamua,", "in us anamua"], ["ma faalogogata,", "and faalogogata"], ["ma faaseseina,", "and faaseseina"], ["sa auauna", "servant"], ["i tu'inanau", "in tu'inanau"], ["ma mea eseese", "and thing divided"], ["e fiafia ai,", "to competition"], ["sa nonofo", "dwelling"], ["ma le loto leaga", "and the heart evil"], ["ma le mataua,", "and the mataua"], ["sa inosia", "abominable"], ["ma feitagai.", "and feitagai"]]},
  {num:4,words:[["A ua faaalia", "but faaalia"], ["mai le agalelei", "from the goodness"], ["ma le alofa", "and the love"], ["i tagata", "in man"], ["o lo tatou Faaola", "our save"], ["le Atua,", "God"]]},
  {num:5,words:[["ona faaola mai ai lea", "and save from"], ["o ia ia", "he to"], ["i tatou,", "in us"], ["e le", "by the"], ["ona o galuega o", "because of work"], ["i le amiotonu", "in the righteous"], ["sa tatou faia,", "let us make"], ["a e tusa", "but to according to"], ["ma lona lava alofa", "and his indeed love"], ["i le faataeleina", "in the faataeleina"], ["i le toefuataiina", "in the toefuataiina"], ["ma le faafouina", "and the faafouina"], ["e le Agaga Paia,", "by the Holy Spirit"]]},
  {num:6,words:[["ua na faamaligi tele", "faamaligi great"], ["mai i luga ia", "from in above to"], ["i tatou,", "in us"], ["ona o Iesu Keriso lo tatou Faaola;", "because of Jesus Christ our save"]]},
  {num:7,words:[["ina ia ta'uamiotonuina", "so that ta'uamiotonuina"], ["i tatou", "in us"], ["i lona lava alofa tunoa,", "in his indeed grace"], ["ia fai", "to make"], ["i tatou", "in us"], ["ma suli", "and suli"], ["e tusa", "to according to"], ["ma le faamoemoe", "and the to expect"], ["i le ola", "in the life"], ["e faavavau.", "forever/everlasting"]]},
  {num:8,words:[["O le upu moni lena ou te loto", "the word true that I heart"], ["foi ina ia", "also so that"], ["e matuā faamalosi atu", "to very faamalosi"], ["i ia mea,", "in to thing"], ["ina ia naunau", "so that naunau"], ["i latou o", "them"], ["e ua faatuatua", "by faith"], ["i le Atua", "in the God"], ["ona ia faia galuega lelei;", "and to made work good"], ["e lelei lava ia mea", "to good indeed to thing"], ["ma aoga", "and useful"], ["i tagata.", "in man"]]},
  {num:9,words:[["A ia taumamao", "but to taumamao"], ["ma sailiga valea", "and sailiga valea"], ["ma tala tupuga,", "and side descendant"], ["ma le femisaiga,", "and the femisaiga"], ["ma le fefinauaiga", "and the fefinauaiga"], ["i la le tulafono;", "in the law"], ["auā o upu", "for word"], ["le aoga ia", "the useful to"], ["ma le faatauvaa.", "and the faatauvaa"]]},
  {num:10,words:[["O le tagata", "man"], ["na te faatupu", "faatupu"], ["le fevaevaeaiga ia", "the fevaevaeaiga to"], ["e 'alo ese ia te", "to Son away unto"], ["ia pe", "to whether"], ["a uma atu ia te", "but all unto"], ["ia le aoaiga", "to the aoaiga"], ["e atu tasi", "by one"], ["pe atu lua;", "whether two"]]},
  {num:11,words:[["auā ua iloa", "for known"], ["o le tagata faapena", "man faapena"], ["ua liliueseina lava o ia,", "liliueseina indeed he"], ["ma ua agasala,", "and sin"], ["ua faasalaina o ia", "faasalaina he"], ["e ia.", "by him"]]},
  {num:12,words:[["A ou auina atu ia te oe", "but I sent unto thee"], ["o Aretima,", "aretima"], ["po o Tuiko ia", "night tuiko to"], ["e faataalise", "to to make haste"], ["ona sau ia te au", "and come unto me"], ["i Nikopoli;", "in nikopoli"], ["auā ua tonu lo'u manatu ou te nofo ai", "for right my thought I dwell"], ["i le tausaga maalili.", "in the year maalili"]]},
  {num:13,words:[["Ia e matuā fesoasoani", "to to very to help"], ["i le malaga", "in the travelling party"], ["a Sena", "of sena"], ["le a'oa'o tulafono,", "the excellent law"], ["atoa ma Apolo,", "and apolo"], ["ina ia le mativa", "so that the mativa"], ["i laua", "them"], ["i se mea", "in a thing"], ["e tasi.", "by one"]]},
  {num:14,words:[["Ia a'oa'oina foi o latou uso", "to taught also them a relative of the same generation and gender"], ["ia faia", "to made"], ["e i latou galuega lelei", "by them work good"], ["e maua ai mea aoga,", "to received thing useful"], ["ina ne'i", "let now"], ["le fua mai", "the fruit from"], ["i latou.", "them"]]},
  {num:15,words:[["O i latou uma lava", "them all indeed"], ["o ia te au o loo alolofa atu", "he I alolofa"], ["i latou ia te oe;", "them unto thee"], ["ua ou alofa atu ia", "I love to"], ["i latou o", "them"], ["e alolofa mai ia te", "by alolofa from"], ["i matou", "in we"], ["i le faatuatua.", "in the faith"], ["Ia ia te outou uma", "to unto you all"], ["lava le alofa tunoa.", "indeed grace"], ["Amene.", "amen"]]},
];
renderVerseSet(tit_ch_3_Verses, 'tit-ch3-verses');

})();