(function() {
var _tit_ch_1_Verses = [
  {num:1,words:[["O a'u", "I am"], ["o Paulo,", "Paul"], ["o le auauna", "the servant"], ["a le Atua,", "of God"], ["ma le aposetolo", "and the apostle"], ["a Iesu Keriso,", "of Jesus Christ"], ["ona o le faatuatua o e ua filifilia", "because of the faith who chosen"], ["e le Atua,", "God"], ["ma le iloa lelei", "and the know good"], ["o le upu moni", "the word true"], ["e iu ai", "to become of"], ["i le amio Atua,", "in the conduct God"]]},
  {num:2,words:[["i le faamoemoe", "in the hope"], ["i le ola", "in the life"], ["e faavavau,", "forever/everlasting"], ["na folafolaina mai talu", "preached from since"], ["mai tausaga", "from year"], ["o le vavau", "the ancient times"], ["e le Atua e le mafai ona", "God by the able then"], ["tala pepelo;", "side false"]]},
  {num:3,words:[["a ua faalia", "but made a net"], ["mai lana lava afioga", "from his indeed word (divine)"], ["i ona po", "in then night"], ["e tatau ai", "it is fitting"], ["i le tala'iga", "in the tala'iga"], ["ua tuuina mai ia te au,", "given from I"], ["e tusa ma le poloaiga", "according to the commandment"], ["a le Atua lo tatou Faaola;", "of God our save"]]},
  {num:4,words:[["o la'u tusi lenei ia", "this letter to"], ["Tito lo'u lava atalii", "Titus my indeed son"], ["i la le faatuatua", "in the faith"], ["ua tuu tele,", "put great"], ["ia ia te oe", "to him you"], ["le alofa tunoa,", "grace"], ["ma le alofa,", "and the love"], ["ma le manuia", "and peace"], ["mai le Atua le Tamā,", "from God the father"], ["atoa ma le Alii o Iesu Keriso lo tatou Faaola.", "and the Lord Jesus Christ our save"]]},
  {num:5,words:[["O le mea lenei", "the thing this"], ["na ou tuu ai oe", "I put you"], ["i Kereta,", "in Kereta"], ["ina ia", "so that"], ["e faatonuina mea", "to commanded thing"], ["ua totoe,", "phiral of foe"], ["ma ia", "and to"], ["e tofia toeaina", "to chosen elder"], ["i lea aai", "in city"], ["ma lea aai,", "and city"], ["faapei ona ou fai atu ai ia te oe;", "like then I said to unto you"]]},
  {num:6,words:[["ai se tasi", "a one"], ["e le mata'uleagaina,", "by the mata'uleagaina"], ["o le tane", "the man"], ["a le fafine", "but the woman"], ["e toatasi,", "to one One"], ["o i ai ana fanau", "therein his born"], ["e faatuatua,", "to faith"], ["e lei ta'ua", "by not us (two, incl)"], ["i latou", "them"], ["ua ulavavale", "ulavavale"], ["pe soli", "whether to tread upon"], ["i tulafono.", "in law"]]},
  {num:7,words:[["Auā e tatau lava", "for it is fitting indeed"], ["i le epikopo", "in the bishop"], ["ona le mata'uleagaina o ia,", "and the mata'uleagaina he"], ["auā o ia le auauna", "for he the servant"], ["e tausi", "to nurse"], ["i mea", "in thing"], ["a le Atua;", "of God"], ["e le finau vale,", "by the strive foolish"], ["e le itagofie,", "by the itagofie"], ["e le inu tele", "by the drink great"], ["i uaina,", "in wine"], ["e le fasi tagata,", "by the kill man"], ["e le manumanu", "by the manumanu"], ["i oloa;", "in goods"]]},
  {num:8,words:[["a o lē alofa", "but of not love"], ["i tagata ese,", "in man away"], ["o lē alofa", "not love"], ["i e amio lelei,", "in to conduct good"], ["o lē faautauta,", "not careful"], ["o lē amiotonu,", "not righteous"], ["o lē amio Atua,", "not conduct God"], ["ma le", "and the"], ["le gaoiā;", "the gaoiā"]]},
  {num:9,words:[["o lē taofi mau", "not hold opinion"], ["i le upu moni,", "in the word true"], ["faapei ona a'oa'oina o ia,", "like then taught he"], ["ina ia mafaia e ia", "so that able by him"], ["ona apoapoai atu i le mataupu", "and exhort in the chapter"], ["e ola ai,", "to life"], ["ma aoai atu i", "and chastise in"], ["e finau mai.", "to strive from"]]},
  {num:10,words:[["Auā e toatele o e solitulafono", "for many who transgression"], ["ua tautalatala", "tautalatala"], ["i upu", "in word"], ["le aoga", "the useful"], ["ma faasese atu,", "and to cause to go astray"], ["a e sili musa", "but to most to skip"], ["le au peritome;", "the I circumcision"]]},
  {num:11,words:[["e tatau", "it is fitting/ought"], ["ina punitia o latou", "so that shut of they"], ["gutu;", "mouth"], ["ua latou faaliliu ese", "they to turn round away"], ["i nisi aiga", "in some family"], ["atoa,", "together with"], ["o loo a'oa'o", "excellent"], ["i mea", "in thing"], ["le tatau,", "the to wring out"], ["ina ua matapeapea", "so that matapeapea"], ["i le oloa.", "in the goods"]]},
  {num:12,words:[["Sa faapea mai le tasi", "saying from the one"], ["o i latou,", "them"], ["o sa latou lava perofeta,", "they indeed prophet"], ["O tagata Kereta,", "of men Kereta"], ["e sagasaga tala pepelo lava", "by sagasaga side false indeed"], ["i latou,", "them"], ["o manu feai leaga,", "animal wild evil"], ["o e usuusua'i", "who usuusua'i"], ["ina 'ai.", "so that eat"]]},
  {num:13,words:[["O le molimau moni lava lea.", "the a witness true indeed"], ["O le mea lea ia", "therefore to"], ["maamaai ona", "maamaai then"], ["e aoai atu ai ia te i latou,", "to chastise unto them"], ["ina ia latou faamaoni", "so that they faithful"], ["i le faatuatua;", "in the faith"]]},
  {num:14,words:[["aua ne'i taofi", "for now hold"], ["i tala", "in side"], ["o le vavau faa-Iutaia,", "the ancient times faa-iutaia"], ["ma poloaiga", "and commandment"], ["a tagata o e liliu ese", "but man who turned away"], ["i le upu moni.", "in the word true"]]},
  {num:15,words:[["Ua mamā mea uma", "clean all things"], ["i e ua loto mamā,", "in by heart clean"], ["a o e loto eleelea", "but who heart eleelea"], ["ma le", "and the"], ["le faatuatua,", "the faith"], ["e le mamā ia te i latou", "by the clean unto them"], ["se mea e tasi,", "a thing by one"], ["a ua eleelea o latou", "but eleelea of they"], ["mafaufau atoa ma o latou", "think and of they"], ["loto fuatia ifo.", "heart weighed down"]]},
  {num:16,words:[["Ua latou ta'u ane", "they told"], ["ua latou iloa", "they knew"], ["le Atua,", "God"], ["a e faafiti ia te ia i", "but to denied to him in"], ["a latou galuega,", "but they work"], ["o inosia", "abominable"], ["i latou", "them"], ["ma faalogogata,", "and faalogogata"], ["latou te le faamaoni foi i se galuega lelei", "they the faithful also in a work good"], ["e tasi.", "by one"]]},
];
renderVerseSet(_tit_ch_1_Verses, 'tit-ch1-verses');

var _tit_ch_2_Verses = [
  {num:1,words:[["A o oe,", "but of you"], ["ia e tautala atu i mea e tusa ma le mataupu", "to to spoke in thing according to the chapter"], ["e ola ai;", "to life"]]},
  {num:2,words:[["fai atu i toeaina ia", "said to in elder to"], ["mataala i latou,", "mataala them"], ["ia faatoeaina,", "to sedate"], ["ia faautauta,", "to careful"], ["ia faamaoni", "to faithful"], ["i le faatuatua,", "in the faith"], ["ma le alfoa,", "and the alfoa"], ["ma le onosai.", "and the patience"]]},
  {num:3,words:[["Ia faapena foi loomatutua,", "to likewise also loomatutua"], ["ia amio", "to conduct"], ["i latou", "them"], ["i le amio Atua,", "in the conduct God"], ["aua ne'i faatuaupua,", "for now faatuaupua"], ["aua ne'i faapologaina", "for now to enslave"], ["i latou", "them"], ["i le uaina,", "in the wine"], ["a ia fai ma a'oa'o", "but to to be excellent"], ["i mea lelei,", "in thing good"]]},
  {num:4,words:[["ina ia latou a'oa'o atu i fafine muli latou te alofa atu i", "so that they excellent in woman muli they love in"], ["a latou tane,", "but they man"], ["ia alofa atu i", "to love in"], ["a latou fanau,", "but they born"], ["ia faautauta", "to careful"], ["i latou,", "them"]]},
  {num:5,words:[["ia le gaoiā,", "to the gaoiā"], ["ia tausi lelei", "to nurse good"], ["i o latou aiga,", "in their clans"], ["ia agalelei,", "to treated well"], ["ia usiusitai atu i", "to obeyed in"], ["a latou lava tane,", "but they indeed man"], ["ina ne'i upuleagaina", "so that now upuleagaina"], ["le afioga", "the word (divine)"], ["a le Atua.", "of God"]]},
  {num:6,words:[["Ia faapea foi", "to thus also"], ["ona e apoapoai atu i taulelea,", "and to exhort in young men"], ["ia faautauta", "to careful"], ["i latou.", "them"]]},
  {num:7,words:[["Ia avea oe", "to become you"], ["a faaa'oa'o o galuega lelei", "but make excellent of work good"], ["i mea uma lava;", "in all things"], ["ia e a'oa'o", "to to excellent"], ["i le mataupu", "in the chapter"], ["ma le faamaoni,", "and the faithful"]]},
  {num:8,words:[["ma le faatoeaina,", "and the sedate"], ["ma le upu", "and the word"], ["e ola ai,", "to life"], ["e le mata'uleagaina,", "by the mata'uleagaina"], ["ina ia faamāina ai o lē tetee", "so that faamāina of not to refuse"], ["mai,", "from"], ["ina ua", "so that"], ["le maua e ia", "the received by him"], ["se mea leaga", "a thing evil"], ["e talatala ane ai ia te outou.", "to to untie unto you"]]},
  {num:9,words:[["Apoapoai atu i pologa ia", "exhort in mouldy to"], ["usiusitai i latou", "obeyed them"], ["i o latou lava matai,", "in of they indeed chief"], ["ia latou taumafai", "to they to strive"], ["ona faafiafia", "and to please"], ["i ai", "therein"], ["i mea uma lava,", "in all things"], ["aua ne'i faatau upu", "for now buy word"], ["i ai.", "therein"]]},
  {num:10,words:[["Aua ne'i latou gaoi,", "for now they to steal"], ["a ia faaalia e i latou", "but to revealed by them"], ["ua latou faamaoni aiai,", "they faithful aiai"], ["ina ia viia ai", "so that praised"], ["i mea uma lava talu", "in all things since"], ["o i latou", "them"], ["le mataupu", "the chapter"], ["a le Atua lo tatou Faaola.", "of God our save"]]},
  {num:11,words:[["Auā o le alofa tunoa", "for the grace"], ["o le Atua", "of God"], ["ua au mai ai le olataga,", "brought the salvation"], ["ua faaalia mai lea", "revealed from"], ["i tagata uma lava,", "in man all indeed"]]},
  {num:12,words:[["o loo a'oa'o", "excellent"], ["mai ai ia te i tatou,", "from unto us"], ["ia tatou tete'a ese", "to we (incl) light colored : as away"], ["ma le faalematau", "and the faalematau"], ["atoa ma tu'inanau faalelalolagi,", "and tu'inanau faalelalolagi"], ["a ia tatou nonofo", "but to we (incl) dwelling"], ["ma le faautauta", "and the careful"], ["ma le amiotonu", "and the righteous"], ["atoa ma le amio Atua i lenei olaga;", "and the conduct God in this lifetime"]]},
  {num:13,words:[["o faatalitali atu i le faatuatuaga", "waited in the something to rely"], ["e manuia ai,", "to peace"], ["o le faaalia lea o le pupula", "the revealed the brightness"], ["o le Atua silisili,", "of God very much"], ["o lo tatou Faaola o Iesu Keriso lea;", "our save of Jesus Christ"]]},
  {num:14,words:[["o le", "the"], ["na foaiina mai o ia", "given from he"], ["e ia", "by him"], ["mo i tatou,", "for in we (incl)"], ["e togiola a'i", "to atonement"], ["i tatou ai le solitulafono uma lava,", "in we (incl) the transgression all indeed"], ["ma ia faamamāina", "and to make clean"], ["mai e ia", "from by him"], ["e fai mona,", "to make to burst forth (as faiai"], ["o lona lava nuu,", "his indeed nation"], ["e maelega", "by maelega"], ["i galuega lelei.", "in work good"]]},
  {num:15,words:[["Ia e tautala atu i", "to to spoke in"], ["ia mea,", "to thing"], ["ma apoapoai atu,", "and exhort"], ["ma aoai atu", "and chastise"], ["ma le pule lava.", "and the rule indeed"], ["Aua ne'i inosia oe", "for now abominable you"], ["e se tasi.", "by a one"]]},
];
renderVerseSet(_tit_ch_2_Verses, 'tit-ch2-verses');

var _tit_ch_3_Verses = [
  {num:1,words:[["Ia e faamanatu atu ia i latou ia latou", "to to to remind to them to they"], ["usiusitai i alii sili", "obeyed in Lord most"], ["ma faipule,", "and a councillor"], ["ia gauai", "to gauai"], ["i alii,", "in Lord"], ["ia nofo sauniuni foi i latou", "to dwell prepared also them"], ["i galuega lelei uma lava,", "in work good all indeed"]]},
  {num:2,words:[["aua ne'i upu leaga", "for now word evil"], ["i se tasi,", "in a one"], ["aua ne'i faamisa,", "for now to pick a quarrel"], ["a ia faapalepale,", "but to to bear patiently"], ["ma ia faaali atu le agamalu uma", "and to revealed the meek all"], ["i tagata uma lava.", "in man all indeed"]]},
  {num:3,words:[["Auā o", "for of"], ["i tatou foi,", "in we (incl) also"], ["sa vālea", "vālea"], ["i tatou anamua,", "in we (incl) ancient"], ["ma faalogogata,", "and faalogogata"], ["ma faaseseina,", "and deceived astray"], ["sa auauna", "servant"], ["i tu'inanau", "in tu'inanau"], ["ma mea eseese", "and thing divided"], ["e fiafia ai,", "to competition"], ["sa nonofo", "dwelling"], ["ma le loto leaga", "and the heart evil"], ["ma le mataua,", "and the mataua"], ["sa inosia", "abominable"], ["ma feitagai.", "and look upon one another"]]},
  {num:4,words:[["A ua faaalia", "but revealed"], ["mai le agalelei", "from the treated well"], ["ma le alofa", "and the love"], ["i tagata", "in man"], ["o lo tatou Faaola", "our save"], ["le Atua,", "God"]]},
  {num:5,words:[["ona faaola mai ai lea o ia ia i tatou,", "and save from he to in we (incl)"], ["e le", "by the"], ["ona o galuega o", "because of work of"], ["i le amiotonu", "in the righteous"], ["sa tatou faia,", "let us make"], ["a e tusa ma lona", "but according to his"], ["lava alofa", "indeed love"], ["i le faataeleina", "in the make bathe"], ["i le toefuataiina", "in the toefuataiina"], ["ma le faafouina", "and the make new"], ["e le Agaga Paia,", "by the Holy Spirit"]]},
  {num:6,words:[["ua na faamaligi tele", "faamaligi great"], ["mai i luga ia i tatou,", "from in above to in we (incl)"], ["ona o Iesu Keriso lo tatou Faaola;", "because of Jesus Christ our save"]]},
  {num:7,words:[["ina ia ta'uamiotonuina", "so that ta'uamiotonuina"], ["i tatou", "in we (incl)"], ["i lona lava alofa tunoa,", "in his indeed grace"], ["ia fai", "to make"], ["i tatou", "in we (incl)"], ["ma suli", "and suli"], ["e tusa ma le faamoemoe", "according to the hope"], ["i le ola", "in the life"], ["e faavavau.", "forever/everlasting"]]},
  {num:8,words:[["O le upu moni lena ou te loto", "the word true that I heart"], ["foi ina ia", "also so that"], ["e matuā faamalosi atu i", "to exceedingly be strong in"], ["ia mea,", "to thing"], ["ina ia naunau", "so that desire"], ["i latou", "them"], ["o e ua faatuatua", "who faith"], ["i le Atua", "in the God"], ["ona ia faia galuega lelei;", "and to made work good"], ["e lelei lava ia mea", "to good indeed to thing"], ["ma aoga", "and useful"], ["i tagata.", "in man"]]},
  {num:9,words:[["A ia taumamao", "but to taumamao"], ["ma sailiga valea", "and sailiga foolish"], ["ma tala tupuga,", "and side nation"], ["ma le femisaiga,", "and the femisaiga"], ["ma le fefinauaiga", "and the dispute"], ["i la le tulafono;", "in the law"], ["auā o upu", "for of word"], ["le aoga ia ma le faatauvaa.", "the useful to and the vain"]]},
  {num:10,words:[["O le tagata", "man"], ["na te faatupu", "he made king"], ["le fevaevaeaiga ia", "the fevaevaeaiga to"], ["e 'alo ese ia te ia", "to Son away to him"], ["pe a uma atu ia te ia", "whether but all to him"], ["le aoaiga", "the discipline"], ["e atu tasi", "by one"], ["pe atu lua;", "whether two"]]},
  {num:11,words:[["auā ua iloa", "for knew"], ["o le tagata faapena", "man likewise"], ["ua liliueseina lava o ia,", "liliueseina indeed he"], ["ma ua agasala,", "and sinned"], ["ua faasalaina o ia", "punished he"], ["e ia.", "by him"]]},
  {num:12,words:[["A ou auina atu ia te oe", "but I sent unto you"], ["o Aretima,", "Aretima"], ["po o Tuiko ia", "night of Tuiko to"], ["e faataalise", "to to make haste"], ["ona sau ia te au", "and come unto me"], ["i Nikopoli;", "in Nikopoli"], ["auā ua tonu lo'u manatu ou te nofo ai", "for right my thought I dwelt"], ["i le tausaga maalili.", "in the year maalili"]]},
  {num:13,words:[["Ia e matuā fesoasoani", "to to exceedingly to help"], ["i le malaga", "in the travelling party"], ["a Sena", "of Sena"], ["le a'oa'o tulafono,", "the excellent law"], ["atoa ma Apolo,", "and Apolo"], ["ina ia le mativa", "so that the want"], ["i laua", "them"], ["i se mea e tasi.", "in a thing by one"]]},
  {num:14,words:[["Ia a'oa'oina foi o latou", "to taught also of they"], ["uso ia faia e i latou", "brother to made by them"], ["galuega lelei", "work good"], ["e maua ai mea aoga,", "to received thing useful"], ["ina ne'i", "so that now"], ["le fua mai i latou.", "the fruit from them"]]},
  {num:15,words:[["O i latou uma lava o ia te au", "them all indeed he I"], ["o loo alolofa atu i latou ia te oe;", "alolofa them unto you"], ["ua ou alofa atu ia i latou", "I loved to them"], ["o e alolofa", "who alolofa"], ["mai ia te i matou", "from in we (excl)"], ["i le faatuatua.", "in the faith"], ["Ia ia te outou uma lava", "to him all of you"], ["le alofa tunoa.", "grace"], ["Amene.", "amen"]]},
];
renderVerseSet(_tit_ch_3_Verses, 'tit-ch3-verses');

})();