(function() {
var wm_ch_1_Verses = [
  {num:1,words:[["Ma o lenei,", "And now I,"], ["o a'u o Mamona ,", "Mormon,"], ["ona ua toeitiiti ou tuu atu le talafaamaumau ua ou faia i lima o lo'u atalii o Moronae, faauta,", "being about to deliver up the record which I have been making into the hands of my son Moroni,"], ["ua ou molimauina le toe a faaumatiaina atoa o lo'u nuu,", "behold I have witnessed almost all the destruction of my people,"], ["o sa Nifaē.", "the Nephites."]]},
  {num:2,words:[["Ma o le tele o selau o tausaga talu ona mavae le afio mai o Keriso ua ou tuu atu ai nei talafaamaumau i lima o lo'u atalii;", "And it is many hundred years after the coming of Christ that I deliver these records into the hands of my son;"], ["ma ou te manatu o le a molimauina e ia le faafanoga atoa o o'u tagata. Ae talosia ia tuuina mai e le Atua ia faaolatia o ia mai ia te i latou,", "and it supposeth me that he will witness the entire destruction of my people. But may God grant that he may survive them,"], ["ina ia mafai ona ia tusi teisi atu e uiga ia te i latou,", "that he may write somewhat concerning them,"], ["ma teisi atu e uiga ia Keriso,", "and somewhat concerning Christ,"], ["ona atonu e aoga ia te i latou i se aso.", "that perhaps someday it may profit them."]]},
  {num:3,words:[["Ma o lenei,", "And now,"], ["ou te tautala teisi atu e uiga i mea ua ou tusia;", "I speak somewhat concerning that which I have written;"], ["aua ina ua uma ona ou faia o se otootoga mai papatusi a Nifae,", "for after I had made an abridgment from the plates of Nephi,"], ["e oo mai i lalo i le nofoaiga a lenei tupu o Peniamina,", "down to the reign of this king Benjamin,"], ["o lē na tautala atu ai Amaleki,", "of whom Amaleki spake,"], ["sa ou suesueina talafaamaumau na tuu mai i o'u lima,", "I searched among the records which had been delivered into my hands,"], ["ma ou maua ai papatusi nei,", "and I found these plates,"], ["ia ua i ai se tala laitiiti e uiga i perofeta,", "which contained this small account of the prophets,"], ["mai ia Iakopo sei oo mai i lalo i le nofoaiga a lenei tupu o Peniamina ,", "from Jacob down to the reign of this king Benjamin,"], ["ma le tele foi o upu a Nifae.", "and also many of the words of Nephi."]]},
  {num:4,words:[["Ma o mea ua tusia i nei papatusi ua ou fiafia i ai,", "And the things which are upon these plates pleasing me,"], ["ona o valoaga ua i ai e uiga i le afio mai o Keriso; ma le iloa e o'u tamā ua faataunuuina le tele o i latou;", "because of the prophecies of the coming of Christ;"], ["ioe,", "and my fathers knowing that many of them have been fulfilled;"], ["ma ua ou iloa foi o le tele o mea na valoia e uiga ia te i matou e oo mai i lalo i le aso nei,", "yea,"], ["ua uma ona faataunuuina, ma o le tele e i luma atu o le aso nei,", "and I also know that as many things as have been prophesied concerning us down to this day have been fulfilled,"], ["o le a faataunuuina moni lava—", "and as many as go beyond this day must surely come to pass—"]]},
  {num:5,words:[["O le mea lea,", "Wherefore,"], ["ua ou filifilia ai nei mea,", "I chose these things,"], ["e faaiu ai i o latou luga la'u talafaamaumau,", "to finish my record upon them,"], ["le vaega lea o totoe o la'u talafaamaumau o le a ou sii mai papatusi a Nifae;", "which remainder of my record I shall take from the plates of Nephi;"], ["ma e lē mafai ona ou tusia le tasivaeselau o mea o lo'u nuu.", "and I cannot write the hundredth part of the things of my people."]]},
  {num:6,words:[["Ae faauta,", "But behold,"], ["o le a ou ave nei papatusi,", "I shall take these plates,"], ["ua i ai nei valoaga ma faaaliga,", "which contain these prophesyings and revelations,"], ["ma tuufaatasi ma le vaega o totoe o la'u talafaamaumau,", "and put them with the remainder of my record,"], ["ona ua sili ona lelei i latou ia te a'u;", "for they are choice unto me;"], ["ma ua ou iloa o le a sili foi ona lelei i o'u uso.", "and I know they will be choice unto my brethren."]]},
  {num:7,words:[["Ma ua ou faia lenei mea mo se faamoemoega poto,", "And I do this for a wise purpose;"], ["ona ua faapea ona musuia ai o a'u,", "for thus it whispereth me,"], ["e tusa ma galuega a le Agaga o le Alii ua ia te a'u. Ma o lenei,", "according to the workings of the Spirit of the Lord which is in me. And now,"], ["ou te le iloa mea uma;", "I do not know all things;"], ["ae ua silafia e le Alii mea uma e oo mai;", "but the Lord knoweth all things which are to come;"], ["o le mea lea,", "wherefore,"], ["ua galue ai o ia ia te a'u ia ou faia e tusa ai ma lona finagalo.", "he worketh in me to do according to his will."]]},
  {num:8,words:[["Ma o la'u tatalo i le Atua e faatatau i o'u uso,", "And my prayer to God is concerning my brethren,"], ["ia mafai ona latou toe o mai i le malamalama o le Atua,", "that they may once again come to the knowledge of God,"], ["ioe,", "yea,"], ["le togiola a Keriso,", "the redemption of Christ;"], ["ina ia mafai ona toe avea i latou ma tagata moomia .", "that they may once again be a delightsome people."]]},
  {num:9,words:[["Ma o lenei,", "And now I,"], ["o a'u,", "Mormon,"], ["o Mamona, ou te faia faauma la'u talafaamaumau,", "proceed to finish out my record,"], ["lea ou te si'i mai papatusi a Nifae;", "which I take from the plates of Nephi;"], ["ma ua ou faia e tusa ai ma le poto ma le malamalama ua tuu mai e le Atua ia te a'u.", "and I make it according to the knowledge and the understanding which God has given me."]]},
  {num:10,words:[["O le mea lea,", "Wherefore,"], ["sa oo ina ua uma ona tuu atu e Amaleki nei papatusi i lima o le tupu o Peniamina,", "it came to pass that after Amaleki had delivered up these plates into the hands of king Benjamin,"], ["sa ave e ia i latou ma tuufaatasi ma isi papatusi, ia sa i ai talafaamaumau sa tuulima faasolo mai e tupu ,", "he took them and put them with the other plates,"], ["mai lea tupulaga i lea tupulaga,", "which contained records which had been handed down by the kings,"], ["seia oo mai i aso o le tupu o Peniamina.", "from generation to generation until the days of king Benjamin."]]},
  {num:11,words:[["Ma sa tuulima faasolo mai i latou mai le tupu o Peniamina,", "And they were handed down from king Benjamin,"], ["mai lea tupulaga i lea tupulaga seia oo ina pauu mai i latou i o'u lima. Ma o a'u,", "from generation to generation until they have fallen into my hands. And I,"], ["o Mamona,", "Mormon,"], ["ou te tatalo i le Atua ia mafai ona faasaoina i latou mai le taimi nei e oo atu i luma. Ma ua ou mautinoa o le a faasaoina i latou;", "pray to God that they may be preserved from this time henceforth. And I know that they will be preserved;"], ["ona e i ai mea tetele ua tusia i luga o i latou,", "for there are great things written upon them,"], ["o le a faamasino ai o'u tagata ma o latou uso i le aso tele ma le mulimuli,", "out of which my people and their brethren shall be judged at the great and last day,"], ["e tusa ma le afioga a le Atua ua tusia.", "according to the word of God which is written."]]},
  {num:12,words:[["Ma o lenei,", "And now,"], ["e faatatau i lenei tupu o Peniamina—sa i ai ia te ia ni finauga i totonu o lona lava nuu.", "concerning this king Benjamin —he had somewhat of contentions among his own people."]]},
  {num:13,words:[["Ma sa oo ina o ifo i lalo i fafo mai le laueleele o Nifae autau a sa Lamanā,", "And it came to pass also that the armies of the Lamanites came down out of the land of Nephi,"], ["e tau faasaga mai i lona nuu. Ae faauta,", "to battle against his people. But behold,"], ["sa faapotopoto faatasi e le tupu o Peniamina ana autau,", "king Benjamin gathered together his armies,"], ["ma tu o ia e faasaga atu ia te i latou;", "and he did stand against them;"], ["ma sa tau o ia ma le malosi o lona lava lima,", "and he did fight with the strength of his own arm,"], ["i le pelu a Lapana.", "with the sword of Laban."]]},
  {num:14,words:[["Ma sa latou tau faasaga atu i o latou fili ma le malosi o le Alii,", "And in the strength of the Lord they did contend against their enemies,"], ["seia oo ina latou fasia le tele o afe o sa Lamanā. Ma sa oo ina latou tau faasaga atu ia sa Lamanā seia oo ina latou tutuli ese i latou mai laueleele uma o lo latou tofi.", "until they had slain many thousands of the Lamanites. And it came to pass that they did contend against the Lamanites until they had driven them out of all the lands of their inheritance."]]},
  {num:15,words:[["Ma sa oo ina ua mavae atu ona i ai o Keriso pepelo,", "And it came to pass that after there had been false Christs,"], ["ma tapunia o latou gutu,", "and their mouths had been shut,"], ["ma faasalaina i latou e tusa ma a latou solitulafono;", "and they punished according to their crimes;"]]},
  {num:16,words:[["Ma ina ua mavae atu foi ona i ai o perofeta pepelo,", "And after there had been false prophets,"], ["ma faifeau pepelo ma aoao pepelo i totonu o le nuu,", "and false preachers and teachers among the people,"], ["ma uma ona faasalaina o i latou uma nei e tusa ma a latou solitulafono;", "and all these having been punished according to their crimes;"], ["ma ina ua mavae atu finauga e tele ma o ese atu i sa Lamanā le toatele o tagata faatu'i'ese,", "and after there having been much contention and many dissensions away unto the Lamanites,"], ["faauta,", "behold,"], ["sa oo ina toe faatuina e le tupu o Peniamina,", "it came to pass that king Benjamin,"], ["faatasi ma le fesoasoani a perofeta paia o e sa i ai i totonu o lona nuu—", "with the assistance of the holy prophets who were among his people—"]]},
  {num:17,words:[["Aua faauta,", "For behold,"], ["o le tupu o Peniamina,", "king Benjamin was a holy man,"], ["o se tagata paia, ma sa nofotupu o ia i lona nuu i le amiotonu;", "and he did reign over his people in righteousness;"], ["ma sa toatele tagata paia sa i ai i le laueleele,", "and there were many holy men in the land,"], ["ma sa latou fetalai atu le afioga a le Atua ma le mana ma le pule;", "and they did speak the word of God with power and with authority;"], ["ma sa latou faaaoga upu malolosi ona o le ua maaa o tagata—", "and they did use much sharpness because of the stiffnecked– ness of the people—"]]},
  {num:18,words:[["O le mea lea,", "Wherefore,"], ["faatasi ma le fesoasoani a i latou nei,", "with the help of these,"], ["sa oo ina toe faatuina e le tupu o Peniamina,", "king Benjamin,"], ["i le galue ma le malosi atoa o lona tino ma le manatu atoa o lona agaga,", "by laboring with all the might of his body and the faculty of his whole soul,"], ["faapea foi ma perofeta,", "and also the prophets,"], ["le filemu i le laueleele.", "did once more establish peace in the land."]]},
];
renderVerseSet(wm_ch_1_Verses, 'wm-ch1-verses');

})();