(function() {
var zec_ch_1_Verses = [
  {num:1,words:[["O le valuga masina,", "In the eighth month,"], ["o le lua o tausaga o Tariu,", "in the second year of Darius,"], ["na tŭlei mai ai le afioga a Ieova ia Sakaria le perofeta le atalii o Parakaio,", "came the word of the LORD unto Zechariah, the son of Berechiah,"], ["o le atalii ia o Ito,", "the son of Iddo the prophet,"], ["o loo faapea mai,", "saying,"]]},
  {num:2,words:[["Sa matuā toasa Ieova i o outou tamā.", "The LORD hath been sore displeased with your fathers."]]},
  {num:3,words:[["E te fai atu foi ia te i latou,", "Therefore say thou unto them,"], ["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["Ia outou foi mai ia te au,", "Turn ye unto me,"], ["ua fetalai mai ai Ieova o 'au;", "saith the LORD of hosts,"], ["ona ou foi atu lea ia te outou,", "and I will turn unto you,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:4,words:[["Aua tou te faapei o outou tamā,", "Be ye not as your fathers,"], ["o e na valaauina e perofeta anamua,", "unto whom the former prophets have cried,"], ["na faapea,", "saying,"], ["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["Ina foi mai ia i o outou ala leaga,", "Turn ye now from your evil ways,"], ["ma a outou galuega leaga;", "and from your evil doings:"], ["a e lei faalogo mai i latou,", "but they did not hear,"], ["ma lei uai mai o latou taliga ia te au,", "nor hearken unto me,"], ["ua fetalai mai ai Ieova.", "saith the LORD."]]},
  {num:5,words:[["O outou tamā po o fea o i ai i latou? o le au perofeta foi,", "Your fathers, where are they? and the prophets,"], ["e faavavau ea ona ola o i latou?", "do they live for ever?"]]},
  {num:6,words:[["A e peitai o a'u upu ma a'u tulafono,", "But my words and my statutes,"], ["na ou poloai atu ai i a'u auauna le au perofeta,", "which I commanded my servants the prophets,"], ["na le maua atu ai ea o outou tamā? ona latou foi mai ai lea,", "did they not take hold of your fathers? and they returned and said,"], ["ma latou fai mai, E pei ona finagalo o Ieova o 'au,", "Like as the LORD of hosts thought to do unto us,"], ["e fai ia te i matou,", "according to our ways,"], ["e tusa ma o matou ala ma a matou galuega,", "and according to our doings,"], ["ua faapea lava ona faia e ia ia te i matou.", "so hath he dealt with us."]]},
  {num:7,words:[["O le aso e luafulu ma le fa,", "Upon the four and twentieth day of the eleventh month,"], ["o le masina e sefulu ma le tasi,", "which is the month Sebat,"], ["o le masina o Sapata lea,", "in the second year of Darius,"], ["o le tausaga e lua o Tariu,", "came the word of the LORD unto Zechariah,"], ["na tŭlei mai ai le afioga a Ieova ia Sakaria le perofeta le atalii o Parakaio,", "the son of Berechiah,"], ["o le atalii ia o Ito,", "the son of Iddo the prophet,"], ["o loo faapea mai,", "saying,"]]},
  {num:8,words:[["Na ou vaai i le po;", "I saw by night,"], ["faauta foi,", "and behold a man riding upon a red horse,"], ["o le tagata o loo tietie i le solofanua mūmū, o loo tu foi o ia i le ulu atasi,", "and he stood among the myrtle trees that were in the bottom;"], ["i le paolo;", "and behind him were there red horses,"], ["o loo i ona tua foi o solofanua mūmū ma e eefu,", "speckled,"], ["ma e sisina.", "and white."]]},
  {num:9,words:[["Ona ou fai atu lea,", "Then said I,"], ["Le alii e,", "O my lord,"], ["o a ea nei mea? Ua fai mai ia te au le agelu na ma tautala,", "what are these? And the angel that talked with me said unto me,"], ["Ou te faailoa ia te oe le uiga o nei mea.", "I will shew thee what these be."]]},
  {num:10,words:[["Ona tali mai lea o le tagata sa tu i le ulu atasi, ua faapea mai,", "And the man that stood among the myrtle trees answered and said,"], ["O i latou ia ua aauina e Ieova e feoai i le lalolagi.", "These are they whom the LORD hath sent to walk to and fro through the earth."]]},
  {num:11,words:[["Ona tali mai lea o i latou i le agelu a Ieova,", "And they answered the angel of the LORD that stood among the myrtle trees,"], ["sa tu i le ulu atasi,", "and said,"], ["ua faapea mai,", "We have walked to and fro through the earth,"], ["Ua matou feoai lava i le lalolagi;", "and,"], ["faauta foi,", "behold,"], ["o loo nofonofo le lalolagi uma,", "all the earth sitteth still,"], ["ua fifilemu lava.", "and is at rest."]]},
  {num:12,words:[["Ona fai atu lea o le agelu a Ieova, ua faapea atu,", "Then the angel of the LORD answered and said,"], ["Ieova o 'au e,", "O LORD of hosts,"], ["se'i afea ona e le alofa ia Ierusalema,", "how long wilt thou not have mercy on Jerusalem and on the cities of Judah,"], ["ma aai o Iuta, ua e toasa i ai i ia tausaga e fitugafulu?", "against which thou hast had indignation these threescore and ten years?"]]},
  {num:13,words:[["Ua tali mai Ieova i le agelu na ma tautala, i upu lelei ma upu faamafanafana.", "And the LORD answered the angel that talked with me with good words and comfortable words."]]},
  {num:14,words:[["Ua fai mai foi ia te au le agelu na ma tautala,", "So the angel that communed with me said unto me,"], ["Ia e alaga,", "Cry thou,"], ["ia faapea atu,", "saying,"], ["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["Ua ou maelega ona o Ierusalema ma Siona i le maelega tele.", "I am jealous for Jerusalem and for Zion with a great jealousy."]]},
  {num:15,words:[["Ua ou matuā ita lava i nuu ese o e nonofo faafifilemu;", "And I am very sore displeased with the heathen that are at ease:"], ["auā na itiiti lo'u ita, a o i latou,", "for I was but a little displeased,"], ["ua latou faateleina le malaia.", "and they helped forward the affliction."]]},
  {num:16,words:[["O le mea lea,", "Therefore thus saith the LORD;"], ["o loo faapea ona fetalai mai ai o Ieova,", "I am returned to Jerusalem with mercies:"], ["Ua ou foi atu i Ierusalema ma le alofa; e fai ai lo'u fale,", "my house shall be built in it,"], ["ua fetalai mai ai Ieova o 'au;", "saith the LORD of hosts,"], ["e faataotoina foi le fua i luga o Ierusalema.", "and a line shall be stretched forth upon Jerusalem."]]},
  {num:17,words:[["Ia e toe alaga,", "Cry yet,"], ["ia faapea atu,", "saying,"], ["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["E toe oso i tua o'u aai ona o le manuia;", "My cities through prosperity shall yet be spread abroad;"], ["e toe faamafanafana Ieova ia Siona,", "and the LORD shall yet comfort Zion,"], ["na te toe filifili foi ia Ierusalema.", "and shall yet choose Jerusalem."]]},
  {num:18,words:[["Ua ou tepa ae foi i luga,", "Then lifted I up mine eyes,"], ["ua ou vaai, faauta,", "and saw,"], ["o nifo e fa.", "and behold four horns."]]},
  {num:19,words:[["Ona ou fai atu lea i le agelu na ma tautala,", "And I said unto the angel that talked with me,"], ["O a ea ia mea? Ua fai mai o ia ia te au,", "What be these? And he answered me,"], ["O mea ia, o nifo na faataapeapeina ai Iuta,", "These are the horns which have scattered Judah,"], ["ma Isaraelu,", "Israel,"], ["ma Ierusalema.", "and Jerusalem."]]},
  {num:20,words:[["Ua faaali mai foi e Ieova ia te au o tufuga e toafa.", "And the LORD shewed me four carpenters."]]},
  {num:21,words:[["Ona ou fai atu lea,", "Then said I,"], ["Ua o mai i latou na e fai i ni a? Ua tali mai o ia,", "What come these to do? And he spake,"], ["ua faapea mai,", "saying,"], ["O nifo ia na faataapeapeina ai Iuta,", "These are the horns which have scattered Judah,"], ["ua oo ina leai se tasi na ea i luga lona ulu;", "so that no man did lift up his head:"], ["a ua o mai i latou nei e faamatau ia te i latou,", "but these are come to fray them,"], ["e lafo i lalo nifo o nuu ese,", "to cast out the horns of the Gentiles,"], ["e na sii i luga lo latou nifo i le laueleele o Iuta e faataapeapeina ai.", "which lifted up their horn over the land of Judah to scatter it."]]},
];
renderVerseSet(zec_ch_1_Verses, 'zec-ch1-verses');

var zec_ch_2_Verses = [
  {num:1,words:[["Ua ou tepa ae foi i luga,", "I lifted up mine eyes again,"], ["ua ou vaai, faauta,", "and looked,"], ["o le tagata ma le maea e fua a'i i lona lima.", "and behold a man with a measuring line in his hand."]]},
  {num:2,words:[["Ona ou fai atu ai lea,", "Then said I,"], ["Po o fea e te alu i ai? Ua fai mai o ia ia te au,", "Whither goest thou? And he said unto me,"], ["Ou te alu, ou te fuatia Ierusalema,", "To measure Jerusalem,"], ["ia iloa pe faapefea lona lautele,", "to see what is the breadth thereof,"], ["pe faapefea foi lona umi.", "and what is the length thereof."]]},
  {num:3,words:[["Faauta foi,", "And,"], ["ua alu atu le agelu na ma tautala;", "behold, the angel that talked with me went forth,"], ["o le tasi agelu foi ua alu ane e faafetaiai ia te ia.", "and another angel went out to meet him,"]]},
  {num:4,words:[["Ua ia fai ane ia te ia,", "And said unto him,"], ["Momo'e ia,", "Run,"], ["ina fai atu i lena taulealea, ia faapea atu,", "speak to this young man,"], ["E āina Ierusalema e oo i faoa aai,", "saying,"], ["ona o le tele o tagata ma manu e i ai.", "Jerusalem shall be inhabited as towns without walls for the multitude of men and cattle therein:"]]},
  {num:5,words:[["O a'u foi,", "For I,"], ["ua fetalai mai Ieova,", "saith the LORD,"], ["e fai a'u ma pa afi e siosio a'i,", "will be unto her a wall of fire round about,"], ["e fai foi a'u ma pupula i totonu ia te ia.", "and will be the glory in the midst of her."]]},
  {num:6,words:[["Sole e! sole e! sosola mai ia outou,", "Ho,"], ["ai le nuu i le itu i matu,", "ho,"], ["ua fetalai mai ai Ieova;", "come forth, and flee from the land of the north,"], ["auā na ou faataapeape ia te outou,", "saith the LORD:"], ["e pei o matāmatagi e fa,", "for I have spread you abroad as the four winds of the heaven,"], ["ua fetalai mai ai Ieova.", "saith the LORD."]]},
  {num:7,words:[["E! Siona e,", "Deliver thyself,"], ["ia e laveai oe ia te oe,", "O Zion,"], ["o lē nofo faatasi ma le tama fafine a Papelonia.", "that dwellest with the daughter of Babylon."]]},
  {num:8,words:[["Auā o loo faapea ona fetalai mai o Ieova o 'au, E mulimuli ane i le mamalu,", "For thus saith the LORD of hosts;"], ["ua ia auina mai o a'u i nuu ese na vetea a outou mea;", "After the glory hath he sent me unto the nations which spoiled you:"], ["auā o lē pai atu ia te outou, ua pāia e ia le tamatamai mata o lona fofoga.", "for he that toucheth you toucheth the apple of his eye."]]},
  {num:9,words:[["Auā faauta,", "For,"], ["ou te siisii atu lo'u lima i luga ia te i latou;", "behold,"], ["e fai foi i latou ma vete i o latou pologa;", "I will shake mine hand upon them,"], ["ona outou iloa lea,", "and they shall be a spoil to their servants:"], ["ua auina mai a'u e Ieova o 'au.", "and ye shall know that the LORD of hosts hath sent me."]]},
  {num:10,words:[["Le tama fafine a Siona e,", "Sing and rejoice,"], ["ia e alaga,", "O daughter of Zion:"], ["ma ia olioli;", "for,"], ["auā faauta,", "lo,"], ["ou te alu atu,", "I come,"], ["ma ou nofo i totonu ia te oe,", "and I will dwell in the midst of thee,"], ["ua fetalai mai ai Ieova.", "saith the LORD."]]},
  {num:11,words:[["E faaopoopoina atu nuu ese e tele ia Ieova i lea aso;", "And many nations shall be joined to the LORD in that day,"], ["e fai i latou mo'u nuu,", "and shall be my people:"], ["ou te nofo foi i totonu ia te oe;", "and I will dwell in the midst of thee,"], ["ona e iloa ai lea ua auina a'u ia te oe e Ieova o 'au.", "and thou shalt know that the LORD of hosts hath sent me unto thee."]]},
  {num:12,words:[["E maua e Ieova o Iuta, o lona tofi i le laueleele paia;", "And the LORD shall inherit Judah his portion in the holy land,"], ["e toe filifilia foi e ia o Ierusalema.", "and shall choose Jerusalem again."]]},
  {num:13,words:[["Faalologo ia o tagata uma i luma o Ieova;", "Be silent, O all flesh,"], ["auā ua tulai mai o ia nai lona malumalu paia.", "before the LORD: for he is raised up out of his holy habitation."]]},
];
renderVerseSet(zec_ch_2_Verses, 'zec-ch2-verses');

var zec_ch_3_Verses = [
  {num:1,words:[["Ua ia faaali mai foi ia te au o Iosua le faitaulaga sili, o loo tu i luma o le agelu a Ieova;", "And he shewed me Joshua the high priest standing before the angel of the LORD,"], ["o Satani foi, o loo tu o ia i lona itu taumatau e tetee atu ia te ia.", "and Satan standing at his right hand to resist him."]]},
  {num:2,words:[["Ona fetalai atu lea o Ieova ia Satani,", "And the LORD said unto Satan,"], ["Ia aoai atu Ieova ia te oe Satani,", "The LORD rebuke thee,"], ["ia aoai atu ia te oe Ieova,", "O Satan;"], ["o le ua filifili i Ierusalema;", "even the LORD that hath chosen Jerusalem rebuke thee:"], ["e le o le motumotu ea lenei na seia mai le afi?", "is not this a brand plucked out of the fire?"]]},
  {num:3,words:[["Ua ofu Iosua i ofu eleelea;", "Now Joshua was clothed with filthy garments,"], ["ua tu foi o ia i luma o le agelu.", "and stood before the angel."]]},
  {num:4,words:[["Ua ia tali atu,", "And he answered and spake unto those that stood before him,"], ["ma fetalai atu i e na tutū mai i ona luma, o loo faapea,", "saying,"], ["Ave ese ia o ofu eleelea ua ofu ai o ia.", "Take away the filthy garments from him."], ["Ua ia fetalai atu foi ia te ia,", "And unto him he said,"], ["Faauta,", "Behold,"], ["ua ou aveesea au amioletonu i ou luga;", "I have caused thine iniquity to pass from thee,"], ["ou te faaofu foi ia te oe i le ofu matagofie.", "and I will clothe thee with change of raiment."]]},
  {num:5,words:[["Ona ou fai atu lea,", "And I said,"], ["Ia latou faaee le pulou lelei i luga o lona ulu. Ona latou faaee ai lea o le pulou lelei i lona ulu, ma faaofu ia te ia i ofu;", "Let them set a fair mitre upon his head. So they set a fair mitre upon his head,"], ["o loo tu mai foi le agelu a Ieova.", "and clothed him with garments. And the angel of the LORD stood by."]]},
  {num:6,words:[["Ua matuā fai atu le agelu a Ieova ia Iosua,", "And the angel of the LORD protested unto Joshua,"], ["o loo faapea,", "saying,"]]},
  {num:7,words:[["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["Afai e te savali i o'u ala,", "If thou wilt walk in my ways,"], ["afai foi e te tausiusi i a'u sauniga,", "and if thou wilt keep my charge,"], ["ona e faamasino ai lea i lo'u fale,", "then thou shalt also judge my house,"], ["ma e leoleo i o'u lotoā;", "and shalt also keep my courts,"], ["ou te tuu atu foi ia te oe ta'ita'i mai ia te i latou nei o e tutū mai.", "and I will give thee places to walk among these that stand by."]]},
  {num:8,words:[["Ia e faalogo mai Iosua e,", "Hear now,"], ["le faitaulaga sili,", "O Joshua the high priest,"], ["o oe atoa ma e ua ia te oe,", "thou,"], ["o e nonofo i ou luma;", "and thy fellows that sit before thee: for they are men wondered at:"], ["auā e fai ma faailoga nei tagata;", "for,"], ["faauta foi,", "behold,"], ["ou te aumaia la'u auauna o le La laau .", "I will bring forth my servant the BRANCH."]]},
  {num:9,words:[["Auā faauta,", "For behold the stone that I have laid before Joshua;"], ["o le maa na ou tuuina atu i luma o Iosua,", "upon one stone shall be seven eyes:"], ["e i le maa e tasi mata e fitu; faauta,", "behold,"], ["ou te togitogi i ai ona togitogiga,", "I will engrave the graving thereof,"], ["ua fetalai mai ai Ieova o 'au;", "saith the LORD of hosts,"], ["ma ou ave ese le amioletonu a le nuu nei i le aso e tasi.", "and I will remove the iniquity of that land in one day."]]},
  {num:10,words:[["Ua fetalai mai Ieova o 'au,", "In that day, saith the LORD of hosts,"], ["O lea aso tou te taitasi ai ma valaau i lana uo i lalo o le vine ma lalo o le mati.", "shall ye call every man his neighbour under the vine and under the fig tree."]]},
  {num:11,words:[["Ua ou fai atu foi ia te ia,", "I make also unto to"], ["o loo faapea,", "thus"], ["O a ea", "but to rise (as a diver to the sur-"], ["na olive", "olive"], ["e lua", "by two"], ["i le itu taumatau o le lamepa,", "on the side right hand the lamepa"], ["ma lona itu tauagavale?", "and his itu tauagavale"]]},
  {num:12,words:[["Ona ou fai atu faalua lea", "and I make faalua"], ["ia te ia,", "unto him"], ["O loo 1304", "1304"]]},
];
renderVerseSet(zec_ch_3_Verses, 'zec-ch3-verses');

var zec_ch_4_Verses = [
  {num:1,words:[["Ua foi mai le agelu na ma tautala,", "And the angel that talked with me came again,"], ["ua ia fafagu mai ia te au,", "and waked me,"], ["e pei o le tagata ua fagua na moe.", "as a man that is wakened out of his sleep,"]]},
  {num:2,words:[["Ona fai mai lea o ia ia te au,", "And said unto me,"], ["O le a ea ua e vaaia? Ona ou fai atu lea,", "What seest thou? And I said,"], ["Ua ou iloa,", "I have looked,"], ["faauta,", "and behold a candlestick all of gold,"], ["o le lamepa ua auro atoatoa,", "with a bowl upon the top of it,"], ["ma lona tuugāsuāuu i ona luga,", "and his seven lamps thereon,"], ["mona tuugālamepa e fitu i ona luga,", "and seven pipes to the seven lamps,"], ["ma ala e taifitu i tuugālamepa o loo i ona luga;", "which are upon the top thereof:"]]},
  {num:3,words:[["ma olive e lua i ona tafatafa,", "And two olive trees by it,"], ["o le tasi i le itu taumatau o le tuugāsuāuu,", "one upon the right side of the bowl,"], ["ma le tasi i lona itu tauagavale.", "and the other upon the left side thereof."]]},
  {num:4,words:[["Ua ou toe fai atu i le agelu na ma tautala,", "So I answered and spake to the angel that talked with me,"], ["ua faapea atu,", "saying,"], ["Le alii e,", "What are these,"], ["o a ea ia mea?", "my lord?"]]},
  {num:5,words:[["Ona tali mai lea o le agelu na ma tautala,", "Then the angel that talked with me answered and said unto me,"], ["ua faapea mai ia te au,", "Knowest thou not what these be? And I said,"], ["E te le iloa ea po o a mea nei? Ona ou fai atu lea, Le alii e,", "No,"], ["ou te le iloa .", "my lord."]]},
  {num:6,words:[["Ua tali mai o ia,", "Then he answered and spake unto me,"], ["ua fai mai ia te au,", "saying,"], ["o loo faapea mai,", "This is the word of the LORD unto Zerubbabel,"], ["O le afioga lenei a Ieova ia Serupapelu,", "saying,"], ["o loo faapea mai, E le o le fitafita,", "Not by might,"], ["e le o le malosi,", "nor by power,"], ["a o lo'u Agaga,", "but by my spirit,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:7,words:[["O ai ea oe le mauga tele e? e faalaugatasia oe i luma o Serupapelu;", "Who art thou, O great mountain? before Zerubbabel thou shalt become a plain:"], ["na te aumaia foi le maa tulimanu aupitoaluga,", "and he shall bring forth the headstone thereof with shoutings,"], ["o loo alalaga,", "crying,"], ["Le alofa tunoa e! ia ia te ia le alofa tunoa.", "Grace, grace unto it."]]},
  {num:8,words:[["Ua oo mai foi ia te au le afioga a Ieova,", "Moreover the word of the LORD came unto me,"], ["o loo faapea mai,", "saying,"]]},
  {num:9,words:[["O lima o Serupapelu na faavaeina ai le fale nei,", "The hands of Zerubbabel have laid the foundation of this house;"], ["o ona lima foi e faauma a'i; e te iloa ai foi,", "his hands shall also finish it;"], ["ua auina mai a'u ia te outou e Ieova o 'au.", "and thou shalt know that the LORD of hosts hath sent me unto you."]]},
  {num:10,words:[["Auā po o ai ea ua 'ino'ino i le aso o mea iti? Latou te fiafia ina ua latou vaai i le fua faatautau i le lima o Serupapelu;", "For who hath despised the day of small things? for they shall rejoice,"], ["o i latou nei e fitu,", "and shall see the plummet in the hand of Zerubbabel with those seven;"], ["o fofoga o Ieova i latou,", "they are the eyes of the LORD,"], ["o fetaufetuliai i le lalolagi uma.", "which run to and fro through the whole earth."]]},
  {num:11,words:[["Ua ou fai atu foi ia te ia,", "Then answered I,"], ["o loo faapea, O a ea na olive e lua i le itu taumatau o le lamepa,", "and said unto him,"], ["ma lona itu tauagavale?", "What are these two olive trees upon the right side of the candlestick and upon the left side thereof?"]]},
  {num:12,words:[["Ona ou fai atu faalua lea ia te ia,", "And I answered again,"], ["o loo faapea atu, O a ea magāolive e lua,", "and said unto him,"], ["o loo liligi mai ia te i laua lava le uu auro i ala auro e lua?", "What be these two olive branches which through the two golden pipes empty the golden oil out of themselves?"]]},
  {num:13,words:[["Ona fai mai lea o ia ia te au,", "And he answered me and said,"], ["o loo faapea mai,", "Knowest thou not what these be? And I said,"], ["E te le iloa ea po o a ia mea? Ona ou fai atu lea, Le alii e,", "No,"], ["ou te le iloa .", "my lord."]]},
  {num:14,words:[["Ona fai mai lea o ia. O tagata faauuina i laua nei,", "Then said he, These are the two anointed ones,"], ["o loo tutū i luma o le Alii o le lalolagi uma.", "that stand by the Lord of the whole earth."]]},
];
renderVerseSet(zec_ch_4_Verses, 'zec-ch4-verses');

var zec_ch_5_Verses = [
  {num:1,words:[["Ona ou toe tepa ae lea ma ou iloa,", "Then I turned,"], ["faauta,", "and lifted up mine eyes, and looked,"], ["o le tusi taai ua lele.", "and behold a flying roll."]]},
  {num:2,words:[["Ua ia fai mai ia te au,", "And he said unto me,"], ["O le a ea ua e iloa? Ona ou fai atu lea,", "What seest thou? And I answered,"], ["Ua ou iloa le tusi taai ua lele; o lona umi,", "I see a flying roll;"], ["o kupita e luafulu,", "the length thereof is twenty cubits,"], ["o lona lau e sefulu kupita ia.", "and the breadth thereof ten cubits."]]},
  {num:3,words:[["Ua fai mai o ia ia te au, O le faafano lenei o le a alu atu i le fogāeleele uma lava;", "Then said he unto me,"], ["auā e taitasi uma o e gaoi ma tafia o ia ai lenei mea ,", "This is the curse that goeth forth over the face of the whole earth:"], ["e pei o le tusi;", "for every one that stealeth shall be cut off as on this side according to it;"], ["e taitasi uma foi o e tauto ma tafia o ia ai le mea nei, e pei e le tusi .", "and every one that sweareth shall be cut off as on that side according to it."]]},
  {num:4,words:[["Ua fetalai mai Ieova o 'au,", "I will bring it forth,"], ["Ou te aumaia;", "saith the LORD of hosts,"], ["e oo atu lava ia i le fale o le gaoi,", "and it shall enter into the house of the thief,"], ["ma le fale o le ua tauto pepelo i lo'u igoa;", "and into the house of him that sweareth falsely by my name:"], ["e tumau ai i totonu o lona fale,", "and it shall remain in the midst of his house,"], ["ma faaumatia ai ona laau ma ona maa.", "and shall consume it with the timber thereof and the stones thereof."]]},
  {num:5,words:[["Ua alu ane foi le agelu na ma tautala,", "Then the angel that talked with me went forth,"], ["ua fai mai o ia ia te au,", "and said unto me,"], ["Ia e tepa i luga, ma e vaai,", "Lift up now thine eyes,"], ["po o le a lena o loo alu atu.", "and see what is this that goeth forth."]]},
  {num:6,words:[["Ua ou fai atu,", "And I said,"], ["O le a lena? Ua fai mai o ia,", "What is it? And he said,"], ["O le efa lena o loo alu atu; ua fai mai foi o ia,", "This is an ephah that goeth forth. He said moreover,"], ["O lona tino mai lena i le nuu uma.", "This is their resemblance through all the earth."]]},
  {num:7,words:[["Faauta foi,", "And,"], ["o le taleni o pulu ua siitia;", "behold, there was lifted up a talent of lead:"], ["o le fafine foi lenei o loo nofo i totonu o le efa.", "and this is a woman that sitteth in the midst of the ephah."]]},
  {num:8,words:[["Ua ia fai mai foi,", "And he said,"], ["O le amio leaga lenei; ona ia lafotuina lea o ia i totonu o le efa,", "This is wickedness. And he cast it into the midst of the ephah;"], ["ma na lafo le fua pulu i le gutu o le efa .", "and he cast the weight of lead upon the mouth thereof."]]},
  {num:9,words:[["Ua ou tepa foi i luga,", "Then lifted I up mine eyes,"], ["ona ou iloa lea,", "and looked,"], ["faauta,", "and,"], ["o fafine e toalua na o atu;", "behold,"], ["ua i ai foi le matagi i o la apaau;", "there came out two women,"], ["auā sa ia te i laua o apaau,", "and the wind was in their wings;"], ["pei o apaau o le kasita;", "for they had wings like the wings of a stork:"], ["ua la siitia le efa i le va o le lalolagi ma le lagi.", "and they lifted up the ephah between the earth and the heaven."]]},
  {num:10,words:[["Ona ou fai atu lea i le agelu na ma tautala,", "Then said I to the angel that talked with me,"], ["Po o fea la te ave i ai le efa?", "Whither do these bear the ephah?"]]},
  {num:11,words:[["Ona fai mai lea o ia ia te au,", "And he said unto me,"], ["O le a ave ina ia fai se fale mōna i le nuu o Senara;", "To build it an house in the land of Shinar:"], ["e faatu ai,", "and it shall be established,"], ["ma faamau ai i lona lava taele.", "and set there upon her own base."]]},
];
renderVerseSet(zec_ch_5_Verses, 'zec-ch5-verses');

var zec_ch_6_Verses = [
  {num:1,words:[["Ona ou toe tepa ae lea,", "And I turned,"], ["ma ou iloa,", "and lifted up mine eyes,"], ["faauta,", "and looked,"], ["o kariota e fa,", "and,"], ["ua o atu nai le va o mauga e lua;", "behold,"], ["o mauga foi,", "there came four chariots out from between two mountains;"], ["o mauga 'apa memea ia.", "and the mountains were mountains of brass."]]},
  {num:2,words:[["O i le kariota muamua o solofanua mūmū:", "In the first chariot were red horses;"], ["o i le lua o kariota o solofanua uliuli;", "and in the second chariot black horses;"]]},
  {num:3,words:[["o i le tolu o kariota o solofanua sisina;", "And in the third chariot white horses;"], ["o i le fa o kariota o solofanua pulepule e malolosi.", "and in the fourth chariot grisled and bay horses."]]},
  {num:4,words:[["Ona ou fai atu lea,", "Then I answered and said unto the angel that talked with me,"], ["ua faapea atu i le agelu na ma tautala, Le alii e,", "What are these,"], ["o a ea ia mea?", "my lord?"]]},
  {num:5,words:[["Ona tali mai lea o le agelu,", "And the angel answered and said unto me,"], ["ua fai mai ia te au, O i latou ia o agaga e toafa o le lagi,", "These are the four spirits of the heavens,"], ["ua o atu sa tutū i luma o le Alii o le lalolagi uma.", "which go forth from standing before the Lord of all the earth."]]},
  {num:6,words:[["O le ua i ai solofanua uliuli e alu atu ia i le nuu i le itu i matu;", "The black horses which are therein go forth into the north country;"], ["ma ē sisina e mulimuli atu i ai;", "and the white go forth after them;"], ["a o e pulepule e o atu ia i le nuu i le itu i toga.", "and the grisled go forth toward the south country."]]},
  {num:7,words:[["Ua o atu foi ē malolosi,", "And the bay went forth,"], ["ua fia o ina ia feoai i le lalolagi. Ua ia fai atu foi,", "and sought to go that they might walk to and fro through the earth:"], ["O ia,", "and he said, Get you hence,"], ["ina feoai i le lalolagi. Ona feoai lea o i latou i le lalolagi.", "walk to and fro through the earth. So they walked to and fro through the earth."]]},
  {num:8,words:[["Ona ia valaau mai lea ia te au,", "Then cried he upon me,"], ["ma tautala mai ia te au,", "and spake unto me,"], ["o loo faapea mai,", "saying,"], ["Vaai ia i e ua o atu i le nuu i le itu i matu;", "Behold,"], ["ua maona ai lo'u loto i le nuu i le itu i matu.", "these that go toward the north country have quieted my spirit in the north country."]]},
  {num:9,words:[["Ua tŭlei mai foi le afioga a Ieova ia te au,", "And the word of the LORD came unto me,"], ["o loo faapea mai;", "saying,"]]},
  {num:10,words:[["Ave ia nisi o i latou nai le tafeaga o sa Heletaī o sa Toviā,", "Take of them of the captivity,"], ["atoa ma o sa Itaiā;", "even of Heldai, of Tobijah,"], ["o i latou ia na o mai i Papelonia;", "and of Jedaiah,"], ["e te alu lava oe i lea aso,", "which are come from Babylon, and come thou the same day,"], ["e te ulu atu i le fale o Iosia le atalii o Sefanaia;", "and go into the house of Josiah the son of Zephaniah;"]]},
  {num:11,words:[["e te avatu foi ario ma auro,", "Then take silver and gold,"], ["ma ia e fai a'i pale,", "and make crowns, and set them upon the head of Joshua the son of Josedech,"], ["ma faaee ai i le ulu o Iosua le atalii o Iosataka le faitaulaga sili.", "the high priest;"]]},
  {num:12,words:[["E te fai atu foi ia te ia,", "And speak unto him,"], ["ia faapea,", "saying,"], ["Ua faapea ona fetalai mai o Ieova o 'au,", "Thus speaketh the LORD of hosts,"], ["o loo faapea mai, Faauta,", "saying,"], ["o le tagata o le La laau lona igoa;", "Behold the man whose name is The BRANCH;"], ["e tupu ae o ia ai le mea e pogai mai ai;", "and he shall grow up out of his place,"], ["e faia foi e ia le malumalu o Ieova;", "and he shall build the temple of the LORD:"]]},
  {num:13,words:[["o ia lava na te faia le malumalu o Ieova;", "Even he shall build the temple of the LORD;"], ["e ia te ia foi le mamalu,", "and he shall bear the glory,"], ["e tietie foi o ia ma pule i luga o lona nofoālii;", "and shall sit and rule upon his throne;"], ["e fai foi o ia ma faitaulaga i luga o lona nofoālii;", "and he shall be a priest upon his throne:"], ["e i ai foi le pule o le manuia ia te i laua.", "and the counsel of peace shall be between them both."]]},
  {num:14,words:[["E i ai foi ia pale mo Elemi,", "And the crowns shall be to Helem,"], ["ma Tovia,", "and to Tobijah,"], ["ma Itaia,", "and to Jedaiah,"], ["ma Heni le atalii o Sefanaia,", "and to Hen the son of Zephaniah,"], ["e fai ma faamanatuga i le malumalu o Ieova.", "for a memorial in the temple of the LORD."]]},
  {num:15,words:[["O e mamao foi latou te o mai e fai le malumalu o Ieova; ona iloa ai lea e outou,", "And they that are far off shall come and build in the temple of the LORD,"], ["ua auina mai a'u ia te outou e Ieova o 'au;", "and ye shall know that the LORD of hosts hath sent me unto you. And this shall come to pass,"], ["e oo foi lenei , pe afai tou te matuā faalogo i le siufofoga o Ieova lo outou Atua.", "if ye will diligently obey the voice of the LORD your God."]]},
];
renderVerseSet(zec_ch_6_Verses, 'zec-ch6-verses');

var zec_ch_7_Verses = [
  {num:1,words:[["O le tausaga e fa o Tariu le tupu,", "And it came to pass in the fourth year of king Darius,"], ["ua tŭlei mai ai le afioga a Ieova ia Sakaria i le aso e fa, i le iva o masina,", "that the word of the LORD came unto Zechariah in the fourth day of the ninth month,"], ["o Kiselu lea.", "even in Chisleu;"]]},
  {num:2,words:[["Ua auina atu o Peteli o Saresa,", "When they had sent unto the house of God Sherezer and Regem-melech,"], ["ma Rekemeleki,", "and their men,"], ["ma ona tagata e faalaulelei i le finagalo o Ieova;", "to pray before the LORD,"]]},
  {num:3,words:[["o loo fai mai i faitaulaga e ua i ai i le fale e Ieova o 'au,", "And to speak unto the priests which were in the house of the LORD of hosts,"], ["atoa ma perofeta,", "and to the prophets,"], ["o loo faapea mai,", "saying,"], ["Ou te tagi ea i le masina e lima,", "Should I weep in the fifth month,"], ["ma ou nofo ese,", "separating myself,"], ["pei ona ou faia i ia tausaga ua tele?", "as I have done these so many years?"]]},
  {num:4,words:[["Ona oo mai lea o le afioga a Ieova o 'au ia te au,", "Then came the word of the LORD of hosts unto me,"], ["o loo faapea mai,", "saying,"]]},
  {num:5,words:[["Fai atu i tagata uma o le nuu,", "Speak unto all the people of the land,"], ["atoa ma faitaulaga,", "and to the priests, saying,"], ["ia faapea atu,", "When ye fasted and mourned in the fifth and seventh month,"], ["Na outou anapogi ma fetagisi i le lima ma le fitu o masina i ia tausaga e fitugafulu,", "even those seventy years, did ye at all fast unto me,"], ["na outou anapogi ai ea ia te au?", "even to me?"]]},
  {num:6,words:[["na outou aai foi,", "And when ye did eat,"], ["ma outou feinu,", "and when ye did drink,"], ["e le o outou lava ea sa aai,", "did not ye eat for yourselves,"], ["o outou foi sa feinu?", "and drink for yourselves?"]]},
  {num:7,words:[["E le o upu ea ia sa valaau ai Ieova i perofeta anamua,", "Should ye not hear the words which the LORD hath cried by the former prophets,"], ["ina o āina o Ierusalema ma ua manuia,", "when Jerusalem was inhabited and in prosperity,"], ["mōna aai ua vagavagai i ai,", "and the cities thereof round about her,"], ["ma le itu i toga ma le itu maulalo sa āina ia.", "when men inhabited the south and the plain?"]]},
  {num:8,words:[["Ua tŭlei mai foi le afioga a Ieova ia Sakaria,", "And the word of the LORD came unto Zechariah,"], ["o loo faapea,", "saying,"]]},
  {num:9,words:[["Ua faapea ona fetalai mai o Ieova o 'au,", "Thus speaketh the LORD of hosts,"], ["o loo faapea mai,", "saying,"], ["Ia faamasino i le faamasinoga tonu,", "Execute true judgment,"], ["ma ia agalelei ma alofa o le tasi i le tasi;", "and shew mercy and compassions every man to his brother:"]]},
  {num:10,words:[["aua le faasaua i fafine ua oti a latou tane ma e ua mātua-oti,", "And oppress not the widow, nor the fatherless,"], ["o le tagata ese ma le ua mativa;", "the stranger,"], ["aua foi le manatunatu i o outou loto i se mea leaga e fai e le tasi i le tasi.", "nor the poor; and let none of you imagine evil against his brother in your heart."]]},
  {num:11,words:[["A ua latou le mafafai ona uai mai o latou taliga ,", "But they refused to hearken,"], ["ma ua liu tua mai i latou ma le finau vale;", "and pulled away the shoulder, and stopped their ears,"], ["ma o latou taliga ua faatulituli ia ina ia latou le faalogo.", "that they should not hear."]]},
  {num:12,words:[["Ua latou faia foi o latou loto ma samira,", "Yea, they made their hearts as an adamant stone,"], ["ina ia le faalogo i latou i le tulafono ma afioga na auina mai ai e Ieova o 'au e lona Agaga i perofeta anamua;", "lest they should hear the law,"], ["o lea na tele ai le toasa mai ia Ieova o 'au.", "and the words which the LORD of hosts hath sent in his spirit by the former prophets: therefore came a great wrath from the LORD of hosts."]]},
  {num:13,words:[["O lenei,", "Therefore it is come to pass,"], ["e pei ona valaau o ia,", "that as he cried,"], ["a e lei faalogologo mai i latou;", "and they would not hear;"], ["e faapea foi ona valaau o i latou,", "so they cried,"], ["a e ou te lei faalogo i ai,", "and I would not hear,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts:"]]},
  {num:14,words:[["Na a'u faataapeape ia te i latou i nuu uma na latou le iloa;", "But I scattered them with a whirlwind among all the nations whom they knew not. Thus the land was desolate after them,"], ["sa tuufua le nuu i o latou tua, ua le fealuai ai se tasi;", "that no man passed through nor returned:"], ["na faia e i latou le nuu matagofie ma mea tuufua.", "for they laid the pleasant land desolate."]]},
];
renderVerseSet(zec_ch_7_Verses, 'zec-ch7-verses');

var zec_ch_8_Verses = [
  {num:1,words:[["Ua oo mai foi le afioga a Ieova o 'au,", "Again the word of the LORD of hosts came to me,"], ["o loo faapea mai,", "saying,"]]},
  {num:2,words:[["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["Na ou maelega ia Siona ma le maelega tele;", "I was jealous for Zion with great jealousy,"], ["na ou maelega foi ia te ia ma le ita tele.", "and I was jealous for her with great fury."]]},
  {num:3,words:[["O loo faapea ona fetalai mai o Ieova, Ua ou foi atu i Siona,", "Thus saith the LORD;"], ["ou te mau foi i totonu o Ierusalema;", "I am returned unto Zion,"], ["e igoa Ierusalema, O le aai e faamaoni;", "and will dwell in the midst of Jerusalem:"], ["o le mauga foi o Ieova o 'au,", "and Jerusalem shall be called a city of truth;"], ["e igoa lea , O le mauga paia.", "and the mountain of the LORD of hosts the holy mountain."]]},
  {num:4,words:[["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["E toe nonofo toeaina ma loomatutua i malae o Ierusalema;", "There shall yet old men and old women dwell in the streets of Jerusalem,"], ["o le tagata foi ma lona tootoo i lona lima ona o le tele o latou tausaga.", "and every man with his staff in his hand for very age."]]},
  {num:5,words:[["E tutumu foi malae o le aai i tamaiti ma teineiti o loo taaalo i ona malae.", "And the streets of the city shall be full of boys and girls playing in the streets thereof."]]},
  {num:6,words:[["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["E ui lava ina faigata i le manatu o e ua totoe o lenei nuu i ia ona aso,", "If it be marvellous in the eyes of the remnant of this people in these days,"], ["pe faigata ea foi i lo'u manatu? ua fetalai mai ai Ieova o 'au.", "should it also be marvellous in mine eyes? saith the LORD of hosts."]]},
  {num:7,words:[["O loo faapea ona fetalai mai o Ieova o 'au Faauta,", "Thus saith the LORD of hosts;"], ["ou te faaola i lo'u nuu nai le nuu e alu ae ai le la,", "Behold, I will save my people from the east country,"], ["ma le nuu e alu ifo ai.", "and from the west country;"]]},
  {num:8,words:[["Ou te aumaiina i latou,", "And I will bring them,"], ["latou te nonofo ai i totonu o Ierusalema;", "and they shall dwell in the midst of Jerusalem:"], ["e fai foi i latou mo'u nuu,", "and they shall be my people, and I will be their God,"], ["e fai foi a'u mo latou Atua i le faamaoni ma le amiotonu.", "in truth and in righteousness."]]},
  {num:9,words:[["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["Ia malolosi o outou lima o e faalogologo mai i nei ona po i upu nei i fofoga o perofeta,", "Let your hands be strong,"], ["e na i ai i ona aso na faavaeina ai le fale o Ieova o 'au,", "ye that hear in these days these words by the mouth of the prophets,"], ["o le malumalu,", "which were in the day that the foundation of the house of the LORD of hosts was laid,"], ["ina ia faia;", "that the temple might be built."]]},
  {num:10,words:[["auā a o lei oo i ia ona aso sa leai se taui o le tagata,", "For before these days there was no hire for man,"], ["po o se taui o le manu;", "nor any hire for beast;"], ["e leai foi se filemu i le na fealuai, ona o le na ita mai;", "neither was there any peace to him that went out or came in because of the affliction:"], ["na ou faaoso foi i tagata uma ia feteenai i latou.", "for I set all men every one against his neighbour."]]},
  {num:11,words:[["A o nei ona po, ou te le pei o aso anamua i e ua totoe i le nuu nei,", "But now I will not be unto the residue of this people as in the former days,"], ["ua fetalai mai ai Ieova o 'au.", "saith the LORD of hosts."]]},
  {num:12,words:[["Auā e i ai le fua o le toalemu;", "For the seed shall be prosperous;"], ["e fua mai e le vine i ona lava fua,", "the vine shall give her fruit,"], ["e fua mai foi le laueleele i ona lava fua,", "and the ground shall give her increase,"], ["o le lagi foi e totō ifo ai lona sau;", "and the heavens shall give their dew;"], ["ou te avatua foi ia mea uma i e ua totoe o lenei nuu e fai mā latou.", "and I will cause the remnant of this people to possess all these things."]]},
  {num:13,words:[["E pei ona fai outou ma fetuu i nuu ese,", "And it shall come to pass,"], ["o oe le aiga o Iuta,", "that as ye were a curse among the heathen,"], ["ma oe le aiga o Isaraelu,", "O house of Judah,"], ["e faapea ona ou faaola ia te outou,", "and house of Israel; so will I save you,"], ["e fai ai outou ma faamanuia;", "and ye shall be a blessing:"], ["aua le fefefe;", "fear not,"], ["ia malolosi o outou lima.", "but let your hands be strong."]]},
  {num:14,words:[["Auā o loo faapea ona fetalai mai o Ieova o 'au,", "For thus saith the LORD of hosts;"], ["E pei ona ou manatu e faatiga ia te outou,", "As I thought to punish you,"], ["ina ua faaonoono mai o outou tamā ia te au,", "when your fathers provoked me to wrath,"], ["ua fetalai mai ai Ieova o 'au,", "saith the LORD of hosts,"], ["ma ou lei salamo ai;", "and I repented not:"]]},
  {num:15,words:[["e faapea ona ou toe manatu i nei ona aso e agalelei atu ia Ierusalema ma le aiga o Iuta;", "So again have I thought in these days to do well unto Jerusalem and to the house of Judah:"], ["aua tou te matatau.", "fear ye not."]]},
  {num:16,words:[["O mea nei tou te faia,", "These are the things that ye shall do;"], ["Ia outou tautala i upu moni o le tasi i le tasi,", "Speak ye every man the truth to his neighbour;"], ["ma ia faamasino i le faamaoni ma le faamasinoga e lelei ai i o outou faitotoa.", "execute the judgment of truth and peace in your gates:"]]},
  {num:17,words:[["Aua le manatunatu i o outou loto i se mea leaga e fai e le tasi i le tasi;", "And let none of you imagine evil in your hearts against his neighbour;"], ["aua foi le fiafia i le tauto pepelo;", "and love no false oath:"], ["auā o mea uma ia ou te 'ino'ino i ai,", "for all these are things that I hate,"], ["ua fetalai mai ai Ieova.", "saith the LORD."]]},
  {num:18,words:[["Ua oo mai foi le afioga a Ieova o 'au ia te au,", "And the word of the LORD of hosts came unto me,"], ["o loo faapea mai,", "saying,"]]},
  {num:19,words:[["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["O le anapogi i le masina e fa,", "The fast of the fourth month,"], ["ma le anapogi i le masina e lima,", "and the fast of the fifth,"], ["ma le anapogi i le masina e fitu,", "and the fast of the seventh,"], ["ma le anapogi i le masina e sefulu, e fai ma fiafia ia,", "and the fast of the tenth,"], ["ma olioli,", "shall be to the house of Judah joy and gladness,"], ["ma aso o tausamiga lelei i le aiga o Iuta;", "and cheerful feasts;"], ["a ia outou fiafia i le upu moni ma le manuia.", "therefore love the truth and peace."]]},
  {num:20,words:[["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts; It shall yet come to pass,"], ["E toe o mai nuu ma tagata o aai e tele;", "that there shall come people, and the inhabitants of many cities:"]]},
  {num:21,words:[["e o atu tagata o le tasi aai i le tasi aai ,", "And the inhabitants of one city shall go to another,"], ["o loo faapea,", "saying,"], ["O mai ia, ina tatou o e faalaulelei i le finagalo o Ieova,", "Let us go speedily to pray before the LORD,"], ["ma saili ia Ieova o 'au;", "and to seek the LORD of hosts:"], ["ou te alu foi a'u.", "I will go also."]]},
  {num:22,words:[["E o mai foi nuu e tele,", "Yea,"], ["ma nuu malolosi e saili ia Ieova o 'au i Ierusalema,", "many people and strong nations shall come to seek the LORD of hosts in Jerusalem,"], ["e faalaulelei foi i le finagalo o Ieova.", "and to pray before the LORD."]]},
  {num:23,words:[["O loo faapea ona fetalai mai o Ieova o 'au,", "Thus saith the LORD of hosts;"], ["O ia ona aso e tago atu ai tagata e toatinoagafulu ai gagana uma o nuu ese;", "In those days it shall come to pass,"], ["latou te tago atu lava i le pito ofu o le sa Iutā ma faapea atu,", "that ten men shall take hold out of all languages of the nations, even shall take hold of the skirt of him that is a Jew,"], ["Tatou te o ma outou;", "saying,"], ["auā ua matou faalogo,", "We will go with you:"], ["o loo ia te outou le Atua.", "for we have heard that God is with you."]]},
];
renderVerseSet(zec_ch_8_Verses, 'zec-ch8-verses');

var zec_ch_9_Verses = [
  {num:1,words:[["O le avega o le afioga a Ieova i le nuu o Hataraka,", "The burden of the word of the LORD in the land of Hadrach,"], ["a o Tamaseko o lona malologa lea;", "and Damascus shall be the rest thereof:"], ["auā e uai atu ia Ieova o mata o tagata,", "when the eyes of man, as of all the tribes of Israel,"], ["mai itu aiga uma o Isaraelu.", "shall be toward the LORD."]]},
  {num:2,words:[["O Amato foi o loo tuaoi ai;", "And Hamath also shall border thereby; Tyrus,"], ["o Turo ma Saitonu e ui lava ona sili lona poto.", "and Zidon, though it be very wise."]]},
  {num:3,words:[["Ua faia foi e Turo le 'olo mōna,", "And Tyrus did build herself a strong hold,"], ["ma ua faafaupue le ario e pei o le efu,", "and heaped up silver as the dust,"], ["ma le auro e pei o le eleele i fafo.", "and fine gold as the mire of the streets."]]},
  {num:4,words:[["Faauta,", "Behold,"], ["e tulia o ia e le Alii;", "the Lord will cast her out,"], ["na te taia foi lona malosi ia paū i le sami;", "and he will smite her power in the sea;"], ["e faaumatia foi o ia i le afi.", "and she shall be devoured with fire."]]},
  {num:5,words:[["E vaai atu i ai Asekelona,", "Ashkelon shall see it,"], ["ona mata'u ai lea;", "and fear;"], ["o Kasa foi e vaai i ai o ia ,", "Gaza also shall see it,"], ["ona tiga tele ai lea,", "and be very sorrowful,"], ["atoa ma Ekerona;", "and Ekron;"], ["auā ua faamāina lona faatuatuaga,", "for her expectation shall be ashamed;"], ["e fanoia foi le tupu o Kasa,", "and the king shall perish from Gaza,"], ["ma Asekelona e le āina ia.", "and Ashkelon shall not be inhabited."]]},
  {num:6,words:[["E mau le tagata ese i Asetota;", "And a bastard shall dwell in Ashdod,"], ["ou te faaumatia foi le matagofie o Filisitia.", "and I will cut off the pride of the Philistines."]]},
  {num:7,words:[["Ou te aveesea lona toto ai lona gutu,", "And I will take away his blood out of his mouth,"], ["atoa ma ana mea e inosia nai le va o ona nifo;", "and his abominations from between his teeth: but he that remaineth,"], ["e faatoeina foi o ia lava mo lo tatou Atua;", "even he,"], ["e fai o ia e pei se alii ia Iuta,", "shall be for our God, and he shall be as a governor in Judah,"], ["a o Ekerona e pei o le sa Iepusē o ia.", "and Ekron as a Jebusite."]]},
  {num:8,words:[["Ou te to lauapi i lo'u fale e sioma'i ona o le itu taua,", "And I will encamp about mine house because of the army,"], ["i lo latou alu atu ma lo latou foi mai;", "because of him that passeth by,"], ["e le toe alu atu lava lē faasaua ia te i latou;", "and because of him that returneth:"], ["auā o lenei,", "and no oppressor shall pass through them any more:"], ["ua vaavaai o'u lava mata.", "for now have I seen with mine eyes."]]},
  {num:9,words:[["Ia e matuā fiafia o oe le tama fafine a Siona;", "Rejoice greatly,"], ["ia alaga fiafia o oe le tama fafine a Ierusalema;", "O daughter of Zion; shout,"], ["faauta,", "O daughter of Jerusalem:"], ["o le a alu atu lou Tupu ia te oe;", "behold, thy King cometh unto thee:"], ["o ia o le amiotonu ma le faaola;", "he is just,"], ["e agamalu o ia,", "and having salvation;"], ["o loo tietie i le asini,", "lowly, and riding upon an ass,"], ["o le tamai asini foi.", "and upon a colt the foal of an ass."]]},
  {num:10,words:[["Ou te faaumatia le kariota i Efaraima,", "And I will cut off the chariot from Ephraim,"], ["ma le solofanua i Ierusalema,", "and the horse from Jerusalem,"], ["e faaumatia foi le aufana o le taua;", "and the battle bow shall be cut off:"], ["na te tautala foi i le leleiga i nuu ese;", "and he shall speak peace unto the heathen:"], ["o lana pule e pau mai i le sami e oo atu i le sami,", "and his dominion shall be from sea even to sea,"], ["e pau mai i le vaitafe e oo i tuluiga o le lalolagi.", "and from the river even to the ends of the earth."]]},
  {num:11,words:[["O oe foi, ona o le toto o lau feagaiga,", "As for thee also,"], ["ou te tuu atu ai ou tagata ua noanoa e o ese i le lua e le i ai se vai.", "by the blood of thy covenant I have sent forth thy prisoners out of the pit wherein is no water."]]},
  {num:12,words:[["Ina foi mai ia i le 'olo,", "Turn you to the strong hold,"], ["outou ua noanoa ua i ai le faamoemoe; o lenei lava aso ou te ta'utino atu,", "ye prisoners of hope:"], ["ou te toe avatu faalua ia te oe.", "even to day do I declare that I will render double unto thee;"]]},
  {num:13,words:[["Auā ua ou lo'ua Iuta mo a'u;", "When I have bent Judah for me,"], ["ua ou tuu Efaraima i le fu'a o le aufana;", "filled the bow with Ephraim, and raised up thy sons,"], ["ou te faaoso atu foi i ou tagata Siona e,", "O Zion,"], ["e tetee atu i ou tagata Iavana e;", "against thy sons, O Greece,"], ["ou te faia foi oe peiseai se pelu a se toa.", "and made thee as the sword of a mighty man."]]},
  {num:14,words:[["E vaaia Ieova i o latou luga;", "And the LORD shall be seen over them,"], ["e alu atu lana u e pei o le uila;", "and his arrow shall go forth as the lightning:"], ["e ili mai le pu e le Alii o Ieova;", "and the Lord GOD shall blow the trumpet,"], ["e alu atu foi ia i afā o le itu i toga.", "and shall go with whirlwinds of the south."]]},
  {num:15,words:[["O Ieova o 'au,", "The LORD of hosts shall defend them;"], ["o ia na te faamamalu ia te i latou; latou te aai,", "and they shall devour,"], ["ma soli i lalo i maa o le maatā;", "and subdue with sling stones;"], ["latou te feinu,", "and they shall drink,"], ["latou te pisapisaō pei o e inu uaina;", "and make a noise as through wine;"], ["e faatumuina i latou, pei o se ipu,", "and they shall be filled like bowls,"], ["pei o tulimanu o le fata faitaulaga.", "and as the corners of the altar."]]},
  {num:16,words:[["E faaolaina i latou e Ieova lo latou Atua i lena aso;", "And the LORD their God shall save them in that day as the flock of his people:"], ["e pei o le lafu mamoe lona nuu; auā e fai i latou ma maa o le palealii;", "for they shall be as the stones of a crown,"], ["o loo siitia i luga i latou i lona laueleele.", "lifted up as an ensign upon his land."]]},
  {num:17,words:[["Auā ua tele naua lona lelei,", "For how great is his goodness,"], ["e tele naua lona matagofie; e faamalosia taulelea i le saito,", "and how great is his beauty! corn shall make the young men cheerful,"], ["ma taupou e faamalosia ia i le uaina.", "and new wine the maids."]]},
];
renderVerseSet(zec_ch_9_Verses, 'zec-ch9-verses');

var zec_ch_10_Verses = [
  {num:1,words:[["Ole atu ia outou ia Ieova,", "Ask ye of the LORD rain in the time of the latter rain;"], ["ina ia ua i ona po o le uaga mulimuli;", "so the LORD shall make bright clouds,"], ["e faia e Ieova uila, ma foaiina atu timuga tetele ia te i latou,", "and give them showers of rain,"], ["o mutia o le fanua ia te i latou uma.", "to every one grass in the field."]]},
  {num:2,words:[["Auā ua tautala tupua i mea le aoga,", "For the idols have spoken vanity,"], ["ma e fai togafiti faataulāitu ua latou vaaia le pepelo,", "and the diviners have seen a lie, and have told false dreams;"], ["ma latou tala mai miti pepelo,", "they comfort in vain:"], ["ma latou faamafanafana fua;", "therefore they went their way as a flock, they were troubled,"], ["o le mea lea ua o ese ai i latou pei o mamoe sa tigaina ina ua leai se leoleo.", "because there was no shepherd."]]},
  {num:3,words:[["Na tupu lo'u ita i le au leoleo mamoe;", "Mine anger was kindled against the shepherds,"], ["ou te taui atu foi i 'oti poa;", "and I punished the goats:"], ["auā ua asiasi mai Ieova o 'au i lona lafu o le aiga o Iuta;", "for the LORD of hosts hath visited his flock the house of Judah,"], ["e faia foi i latou e ia pei o lana solofanua matagofie i le taua.", "and hath made them as his goodly horse in the battle."]]},
  {num:4,words:[["Mai ia te ia le tulimanu,", "Out of him came forth the corner,"], ["mai ia te ia le fao,", "out of him the nail,"], ["mai ia te ia le aufana o le taua,", "out of him the battle bow,"], ["mai ia te ia foi e o atu ai faipule uma faatasi.", "out of him every oppressor together."]]},
  {num:5,words:[["Latou te pei o toa,", "And they shall be as mighty men,"], ["o loo soli i le palapala i fafo i le taua;", "which tread down their enemies in the mire of the streets in the battle:"], ["latou te tau foi,", "and they shall fight,"], ["auā e ia te i latou Ieova;", "because the LORD is with them,"], ["a e faamāina ē tietie i solofanua.", "and the riders on horses shall be confounded."]]},
  {num:6,words:[["Ou te faamalosia le aiga o Iuta,", "And I will strengthen the house of Judah,"], ["ma le aiga o Iosefa ou te faaolaina lea;", "and I will save the house of Joseph,"], ["ou te faanofomauina foi i latou,", "and I will bring them again to place them;"], ["auā ua ou alofa mutimutivale i ai; e avea i latou,", "for I have mercy upon them:"], ["e peiseai na ou le lafoaiina i latou;", "and they shall be as though I had not cast them off:"], ["auā o a'u o Ieova lo latou Atua,", "for I am the LORD their God,"], ["ou te talia i latou.", "and will hear them."]]},
  {num:7,words:[["E pei o le fitafita sa Efaraimā,", "And they of Ephraim shall be like a mighty man,"], ["e fiafia foi o latou loto,", "and their heart shall rejoice as through wine:"], ["e pei o e inu uaina;", "yea, their children shall see it,"], ["e vaai i ai a latou fanau ma latou fiafia,", "and be glad;"], ["e olioli lava o latou loto ia Ieova.", "their heart shall rejoice in the LORD."]]},
  {num:8,words:[["Ou te mapumapu atu ia te i latou,", "I will hiss for them,"], ["ma ou faapotopotoina i latou;", "and gather them;"], ["auā ua ou faatauina i latou; e faatoateleina foi i latou,", "for I have redeemed them:"], ["e pei ona faatoateleina i latou anamua;", "and they shall increase as they have increased."]]},
  {num:9,words:[["ma ou totōina i latou i nuu;", "And I will sow them among the people:"], ["a e manatua a'u e i latou i mea mamao;", "and they shall remember me in far countries;"], ["latou te ola foi faatasi ma a latou fanau,", "and they shall live with their children,"], ["ma latou toe foi mai.", "and turn again."]]},
  {num:10,words:[["Ou te faafoisia mai i latou nai le nuu o Aikupito,", "I will bring them again also out of the land of Egypt,"], ["ma ou faapotopotoina i latou mai Asuria;", "and gather them out of Assyria;"], ["ou te aumaia i latou i le nuu o Kiliata ma Lepanona,", "and I will bring them into the land of Gilead and Lebanon;"], ["e le maua foi se mea latou te nonofo ai .", "and place shall not be found for them."]]},
  {num:11,words:[["Na te ui ane i le sami ma le puapuaga;", "And he shall pass through the sea with affliction,"], ["na te taia foi peau o le sami;", "and shall smite the waves in the sea,"], ["e faapa'umatuina mea loloto uma i le vaitafe;", "and all the deeps of the river shall dry up:"], ["e faamaulaloina foi le faamaualuga o Asuria;", "and the pride of Assyria shall be brought down,"], ["o le tootoo foi o Aikupito e mavae atu lea.", "and the sceptre of Egypt shall depart away."]]},
  {num:12,words:[["Ou te faamalosia i latou ia Ieova;", "And I will strengthen them in the LORD;"], ["latou te savavali foi i lona suafa,", "and they shall walk up and down in his name,"], ["ua fetalai mai ai Ieova.", "saith the LORD."]]},
];
renderVerseSet(zec_ch_10_Verses, 'zec-ch10-verses');

var zec_ch_11_Verses = [
  {num:1,words:[["Lepanona e,", "Open thy doors,"], ["ina to mai ia ou puipui,", "O Lebanon,"], ["e susunuina ai i le afi ou arasi.", "that the fire may devour thy cedars."]]},
  {num:2,words:[["Ina uio ia le perosi e,", "Howl,"], ["auā ua paū le arasi,", "fir tree;"], ["auā ua fanoia laau sili;", "for the cedar is fallen; because the mighty are spoiled:"], ["uio ia,", "howl,"], ["aluna o Vasana e,", "O ye oaks of Bashan;"], ["auā ua paū le vao na le masaofia.", "for the forest of the vintage is come down."]]},
  {num:3,words:[["O i ai le leo o le uio o leoleo mamoe,", "There is a voice of the howling of the shepherds;"], ["auā ua faaumatia lo latou matagofie;", "for their glory is spoiled:"], ["o i ai le leo o le fetagisi o leona taanoa,", "a voice of the roaring of young lions;"], ["auā ua faaumatia le matagofie o Ioritana.", "for the pride of Jordan is spoiled."]]},
  {num:4,words:[["O loo faapea ona fetalai mai o Ieova lo'u Atua,", "Thus saith the LORD my God;"], ["Ia e leoleo i le lafu mamoe o le a fasia.", "Feed the flock of the slaughter;"]]},
  {num:5,words:[["O e o latou le lafu , latou te fafasi ia te i latou,", "Whose possessors slay them,"], ["a e le nofo sala ai i latou;", "and hold themselves not guilty:"], ["o e faatau foi ia te i latou,", "and they that sell them say,"], ["ua taitasi o i latou ma fai ane, Faafetai ia Ieova,", "Blessed be the LORD;"], ["auā ua faatamaoaigaina a'u; o latou leoleo mamoe foi,", "for I am rich:"], ["latou te le alolofa ia te i latou.", "and their own shepherds pity them not."]]},
  {num:6,words:[["Auā ou te le toe alofa i e nonofo i le nuu na,", "For I will no more pity the inhabitants of the land,"], ["ua fetalai mai ai Ieova;", "saith the LORD:"], ["faauta foi,", "but,"], ["ou te tuuina atu tagata o le tasi i le lima o le tasi,", "lo, I will deliver the men every one into his neighbour's hand,"], ["ma le lima o lona tupu;", "and into the hand of his king:"], ["latou te tu'ipalaina le nuu,", "and they shall smite the land,"], ["a e ou te le laveai ia te i latou ai o latou lima.", "and out of their hand I will not deliver them."]]},
  {num:7,words:[["Ua ou leoleoina le lafu mamoe o le a fasia,", "And I will feed the flock of slaughter,"], ["o le lafu mamoe e matuā malaia; ua ou ave foi ma'u tootoo e lua;", "even you,"], ["ua ou faaigoaina le tasi,", "O poor of the flock. And I took unto me two staves;"], ["o Matagofie;", "the one I called Beauty,"], ["a o le tasi ua ou faaigoaina, o Noataga;", "and the other I called Bands;"], ["ona ou leoleo ai lea i le lafu mamoe.", "and I fed the flock."]]},
  {num:8,words:[["Ua ou faaumatia leoleo mamoe e toatolu i le masina e tasi;", "Three shepherds also I cut off in one month;"], ["ua tiga lo'u loto ia i latou,", "and my soul lothed them,"], ["ua 'ino'ino foi o latou loto ia te au.", "and their soul also abhorred me."]]},
  {num:9,words:[["Ona ou fai atu ai lea,", "Then said I,"], ["Ou te le leoleo ia te outou;", "I will not feed you:"], ["o lē a mate ina mate ia;", "that that dieth, let it die;"], ["o lē a faaumatia,", "and that that is to be cut off,"], ["ia faaumatia lava ia;", "let it be cut off;"], ["a o e ua totoe ia taitasi ma 'ai le tino o le tasi.", "and let the rest eat every one the flesh of another."]]},
  {num:10,words:[["Ona ou tago ai lea i lo'u tootoo,", "And I took my staff,"], ["o Matagofie lea,", "even Beauty,"], ["ma ou gausia;", "and cut it asunder,"], ["ina ia tatala la'u feagaiga na matou osia ma nuu uma;", "that I might break my covenant which I had made with all the people."]]},
  {num:11,words:[["ona tatalaina ai lea i lea aso; ona iloa lelei ai lea e le lafu mamoe malaia,", "And it was broken in that day:"], ["o e ua usiusitai mai ia te au, o le afioga lava lea a Ieova.", "and so the poor of the flock that waited upon me knew that it was the word of the LORD."]]},
  {num:12,words:[["Ona ou fai atu lea ia te i latou,", "And I said unto them,"], ["Afai e lelei ia te outou, aumaia o lo'u taui;", "If ye think good,"], ["a e afai e leai,", "give me my price;"], ["soia; ona latou fua mai ai lea o lo'u taui,", "and if not,"], ["o tupe e fuatolu.", "forbear. So they weighed for my price thirty pieces of silver."]]},
  {num:13,words:[["Ona fetalai mai lea o Ieova ia te au,", "And the LORD said unto me,"], ["Ina lafo atu ia i lē fai ipu omea;", "Cast it unto the potter:"], ["se tau e lelei naua, ua faatusaina ai a'u e i latou! Ona ou tago ai lea i tupe e fuatolu,", "a goodly price that I was prised at of them. And I took the thirty pieces of silver,"], ["ma ou lafoia atu i le fale o Ieova i lē fai ipu omea.", "and cast them to the potter in the house of the LORD."]]},
  {num:14,words:[["Ona ou gausia lea o le tasi o'u tootoo,", "Then I cut asunder mine other staff,"], ["o Noataga lea,", "even Bands,"], ["ina ia ou motusia le tauusoga o Iuta ma Isaraelu.", "that I might break the brotherhood between Judah and Israel."]]},
  {num:15,words:[["Ua fetalai mai foi Ieova ia te au,", "And the LORD said unto me,"], ["Ina e toe ave ia o mea a le leoleo mamoe valea;", "Take unto thee yet the instruments of a foolish shepherd."]]},
  {num:16,words:[["auā faauta,", "For,"], ["o a'u ou te faatuina se leoleo mamoe i le nuu,", "lo,"], ["na te le asiasi i e a fano;", "I will raise up a shepherd in the land,"], ["na te le sailia le ua sē;", "which shall not visit those that be cut off,"], ["na te le fōia le ua gau;", "neither shall seek the young one, nor heal that that is broken,"], ["o le ua tu na te le fagaina;", "nor feed that that standeth still:"], ["a o le tino o le ua peti na te 'aina lava lea,", "but he shall eat the flesh of the fat,"], ["mo latou atigivae na te tafa'ieseina.", "and tear their claws in pieces."]]},
  {num:17,words:[["Oi talofa i le leoleo mamoe le aoga,", "Woe to the idol shepherd that leaveth the flock! the sword shall be upon his arm,"], ["na te tuua le lafu mamoe! e i ai le pelu i lona lima atoa ma lona mata taumatau;", "and upon his right eye:"], ["e matuā gase lava lona lima,", "his arm shall be clean dried up,"], ["ma lona mata taumatau e matuā puaoa lava lea.", "and his right eye shall be utterly darkened."]]},
];
renderVerseSet(zec_ch_11_Verses, 'zec-ch11-verses');

var zec_ch_12_Verses = [
  {num:1,words:[["O le avega o le afioga a Ieova ia Isaraelu;", "The burden of the word of the LORD for Israel,"], ["o loo fetalai mai Ieova le ua faamafolafola le lagi,", "saith the LORD,"], ["ma faavaeina le lalolagi,", "which stretcheth forth the heavens,"], ["na ia faia foi le agaga o le tagata i totonu ia te ia;", "and layeth the foundation of the earth,"], ["faauta,", "and formeth the spirit of man within him."]]},
  {num:2,words:[["o a'u lava ou te faia Ierusalema ma ipu e tautevateva ai nuu uma o vagavagai;", "Behold, I will make Jerusalem a cup of trembling unto all the people round about,"], ["e i ai foi ia Iuta pe a vagaia Ierusalema.", "when they shall be in the siege both against Judah and against Jerusalem."]]},
  {num:3,words:[["O lea aso foi ou te fai ai Ierusalema ma maa mamafa i nuu uma;", "And in that day will I make Jerusalem a burdensome stone for all people:"], ["atoa uma o e sii i ai, e matuā manunua ai i latou;", "all that burden themselves with it shall be cut in pieces,"], ["a e faapotopotoina nuu uma lava o le lalolagi latou te tau.", "though all the people of the earth be gathered together against it."]]},
  {num:4,words:[["Ua fetalai mai Ieova,", "In that day,"], ["O le aso lava lea ou te taia ai solofanua uma i le atuatuvale,", "saith the LORD,"], ["ma e o tietie ai i le faavalemalosi;", "I will smite every horse with astonishment,"], ["a o le aiga o Iuta,", "and his rider with madness:"], ["ou te vaavaai lava i ai;", "and I will open mine eyes upon the house of Judah,"], ["o solofanua uma a nuu ou te taia ia i le tauaso.", "and will smite every horse of the people with blindness."]]},
  {num:5,words:[["O alii o Iuta latou te faapea i o latou loto,", "And the governors of Judah shall say in their heart,"], ["E fai mo'u malosi o e nonofo i Ierusalema ia Ieova o 'au lo latou Atua.", "The inhabitants of Jerusalem shall be my strength in the LORD of hosts their God."]]},
  {num:6,words:[["O le aso lea ou te faia ai o alii o Iuta e pei o le taigaafi i laau,", "In that day will I make the governors of Judah like an hearth of fire among the wood, and like a torch of fire in a sheaf;"], ["e pei o le sulu foi ua mu i le fusi saito;", "and they shall devour all the people round about,"], ["latou te faaumatia nuu uma e siosio mai i le itu taumatau ma le itu tauagavale;", "on the right hand and on the left:"], ["e toe mau foi Ierusalema i lona lava nuu o Ierusalema.", "and Jerusalem shall be inhabited again in her own place, even in Jerusalem."]]},
  {num:7,words:[["E faaolaina foi e Ieova o fale ie o Iuta, e muamua lava,", "The LORD also shall save the tents of Judah first,"], ["ina ia le faasilisili le viiga o le aiga o Tavita, ma le viiga o e nonofo i Ierusalema ia Iuta.", "that the glory of the house of David and the glory of the inhabitants of Jerusalem do not magnify themselves against Judah."]]},
  {num:8,words:[["O lea aso e faamamalu mai ai Ieova i e o nonofo i Ierusalema;", "In that day shall the LORD defend the inhabitants of Jerusalem;"], ["o so latou ua vaivai i lea aso e pei o Tavita ia;", "and he that is feeble among them at that day shall be as David;"], ["o le aiga o Tavita, e pei o le Atua ia,", "and the house of David shall be as God,"], ["e pei o le agelu a Ieova i o latou luma.", "as the angel of the LORD before them."]]},
  {num:9,words:[["O lea aso foi ou te saili ai ia faaumatia nuu uma lava o e o mai e tau ma Ierusalema.", "And it shall come to pass in that day, that I will seek to destroy all the nations that come against Jerusalem."]]},
  {num:10,words:[["Ou te liligi ifo i luga o le aiga o Tavita,", "And I will pour upon the house of David,"], ["ma luga o e nonofo i Ierusalema le agaga o le alofa tunoa ma talosaga,", "and upon the inhabitants of Jerusalem,"], ["latou te vaavaai mai ia te au na latou tu'ia;", "the spirit of grace and of supplications:"], ["latou te tagitu'i foi ia te ia,", "and they shall look upon me whom they have pierced, and they shall mourn for him,"], ["e pei ona tagitu'i i le atalii e toatasi,", "as one mourneth for his only son,"], ["ma latou faanoanoa ia te ia,", "and shall be in bitterness for him,"], ["e pei ona faanoanoa i le ulumatua.", "as one that is in bitterness for his firstborn."]]},
  {num:11,words:[["O lea aso e tele ai le taufaitagitu'i i Ierusalema,", "In that day shall there be a great mourning in Jerusalem,"], ["e pei o le tagitu'i i Atatarimoni i le vanu o Mekito.", "as the mourning of Hadadrimmon in the valley of Megiddon."]]},
  {num:12,words:[["E taufaitagitu'i le nuu e tagi a aiga; o le aiga o sa Tavitā,", "And the land shall mourn,"], ["na o i latou,", "every family apart;"], ["ma a latou avā,", "the family of the house of David apart,"], ["ua na o i latou; o le aiga o sa Natanā,", "and their wives apart;"], ["na o i latou, ma a latou avā,", "the family of the house of Nathan apart,"], ["na o i latou;", "and their wives apart;"]]},
  {num:13,words:[["o le aiga o sa Levī, ua na o i latou,", "The family of the house of Levi apart,"], ["ma a latou avā, na o i latou;", "and their wives apart;"], ["o le aiga o Semi, na o i latou,", "the family of Shimei apart,"], ["ma a latou avā, na o i latou.", "and their wives apart;"]]},
  {num:14,words:[["O aiga uma o e totoe,", "All the families that remain,"], ["o aiga taitasi na o i latou,", "every family apart,"], ["ma a latou avā na o i latou.", "and their wives apart."]]},
];
renderVerseSet(zec_ch_12_Verses, 'zec-ch12-verses');

var zec_ch_13_Verses = [
  {num:1,words:[["O lea aso e i ai le vaipuna ua suena mo le aiga o Tavita ma e o nonofo i Ierusalema, mo le agasala atoa ma mea leaga.", "In that day there shall be a fountain opened to the house of David and to the inhabitants of Jerusalem for sin and for uncleanness."]]},
  {num:2,words:[["Ua fetalai mai Ieova o 'au,", "And it shall come to pass in that day,"], ["O lea aso ou te tineia ai igoa o tupua i le lalolagi,", "saith the LORD of hosts,"], ["e le toe manatua i latou;", "that I will cut off the names of the idols out of the land,"], ["atoa foi ma perofeta ma le agaga leaga,", "and they shall no more be remembered:"], ["ou te faate'aeseina ia i le lalolagi.", "and also I will cause the prophets and the unclean spirit to pass out of the land."]]},
  {num:3,words:[["Afai foi e toe vavalo se tasi,", "And it shall come to pass,"], ["ona fai atu ai lea ia te ia o lona tamā ma lona tinā na fanaua mai ai o ia,", "that when any shall yet prophesy,"], ["E te le ola;", "then his father and his mother that begat him shall say unto him,"], ["auā ua e tala pepelo i le suafa o Ieova;", "Thou shalt not live;"], ["ona tutu'i ai lea ia te ia e lona tamā ma lona tinā na fanaua mai ai o ia,", "for thou speakest lies in the name of the LORD:"], ["pe a vavalo mai ai o ia.", "and his father and his mother that begat him shall thrust him through when he prophesieth."]]},
  {num:4,words:[["O lea aso foi e taitasi le perofeta ma mā ai o ia i lana mea na vaaia,", "And it shall come to pass in that day,"], ["pe a faia lana valoaga;", "that the prophets shall be ashamed every one of his vision, when he hath prophesied;"], ["latou te le oofu foi i se ofu taufulufulu e pepelo ai.", "neither shall they wear a rough garment to deceive:"]]},
  {num:5,words:[["E fai mai foi o ia,", "But he shall say,"], ["Ou te le se perofeta a'u;", "I am no prophet,"], ["o a'u le tagata e galue i fanua; auā na faapologaina a'u,", "I am an husbandman;"], ["talu ina ou taulealea.", "for man taught me to keep cattle from my youth."]]},
  {num:6,words:[["Ona fai mai lea o se tasi ia te ia,", "And one shall say unto him,"], ["O a ea ia manua i ou lima? Ona fai atu lea o ia,", "What are these wounds in thine hands? Then he shall answer,"], ["O mea ia na manua ai a'u i le fale o a'u uo.", "Those with which I was wounded in the house of my friends."]]},
  {num:7,words:[["Ala mai ia,", "Awake,"], ["le pelu e,", "O sword,"], ["i lo'u leoleo mamoe,", "against my shepherd,"], ["ma le tagata ma te faatasi ma a'u,", "and against the man that is my fellow,"], ["ua fetalai mai ai Ieova o 'au;", "saith the LORD of hosts:"], ["ina ta ia o le leoleo mamoe,", "smite the shepherd,"], ["ona faataapeapeina ai lea o le au mamoe;", "and the sheep shall be scattered:"], ["ona faafoi atu lea o lo'u lima i e iti.", "and I will turn mine hand upon the little ones."]]},
  {num:8,words:[["Ua fetalai mai Ieova,", "And it shall come to pass,"], ["E oo ina vavaeeseina i le nuu uma lava ona vaega e lua,", "that in all the land,"], ["e fano lava ia;", "saith the LORD, two parts therein shall be cut off and die;"], ["a e faatotoeina ai lona tolu o vaega .", "but the third shall be left therein."]]},
  {num:9,words:[["Ou te avane lona tolu o vaega i le afi;", "And I will bring the third part through the fire,"], ["ou te faate'aese ai le eleele ia te i latou, e pei ona faate'aeseina ai le eleele o le ario;", "and will refine them as silver is refined,"], ["ou te totofofoina i latou,", "and will try them as gold is tried:"], ["e pei ona tofotofoina o le auro;", "they shall call on my name,"], ["e valaau i latou i lo'u igoa; o a'u foi,", "and I will hear them:"], ["ou te tali atu ai ia te i latou;", "I will say,"], ["ou te fai ane,", "It is my people:"], ["O lo'u nuu lava i latou; a e fai mai i latou,", "and they shall say,"], ["O Ieova o lo'u Atua lava o ia.", "The LORD is my God."]]},
];
renderVerseSet(zec_ch_13_Verses, 'zec-ch13-verses');

var zec_ch_14_Verses = [
  {num:1,words:[["Faauta,", "Behold,"], ["o le a oo mai le aso o Ieova,", "the day of the LORD cometh,"], ["e tufaina ai i totonu ia te oe o lou oa o le a vetea.", "and thy spoil shall be divided in the midst of thee."]]},
  {num:2,words:[["Auā ou te faapotopotoina nuu uma e tau ma Ierusalema;", "For I will gather all nations against Jerusalem to battle;"], ["e aea le aai,", "and the city shall be taken,"], ["e vetea foi fale, ma fetosoina fafine,", "and the houses rifled,"], ["e ta'ita'i faatagataotauaina le tasi vaega o le aai;", "and the women ravished;"], ["a o e totoe o le nuu,", "and half of the city shall go forth into captivity,"], ["e le faate'aeseina i latou i le aai.", "and the residue of the people shall not be cut off from the city."]]},
  {num:3,words:[["Ona afio atu lea o Ieova e tau ma ia nuu,", "Then shall the LORD go forth, and fight against those nations,"], ["pei o le aso na tau ai o ia i le aso o le taua.", "as when he fought in the day of battle."]]},
  {num:4,words:[["E tu ona aao i lea aso i luga o le mauga o Olive,", "And his feet shall stand in that day upon the mount of Olives,"], ["o loo feagai ma Ierusalema i gagae;", "which is before Jerusalem on the east,"], ["e vaeluaina foi le mauga o Olive i totonu i sasae ma sisifo,", "and the mount of Olives shall cleave in the midst thereof toward the east and toward the west,"], ["o le vanu tele lava;", "and there shall be a very great valley;"], ["e te'a atu le tasi itu o le mauga i le itu i matu,", "and half of the mountain shall remove toward the north,"], ["ma le tasi ona itu i le itu i toga.", "and half of it toward the south."]]},
  {num:5,words:[["Ona outou sosola lea i le vanu o i o'u mauga;", "And ye shall flee to the valley of the mountains;"], ["auā e pāia Asela i le vanu o mauga;", "for the valley of the mountains shall reach unto Azal: yea,"], ["tou te sosola foi,", "ye shall flee,"], ["pei ona outou sosola i le mafuie i ona po o Usia le tupu o Iuta;", "like as ye fled from before the earthquake in the days of Uzziah king of Judah: and the LORD my God shall come,"], ["e afio mai lava Ieova lo'u Atua ma le au paia uma faatasi ma oe.", "and all the saints with thee."]]},
  {num:6,words:[["E oo lava i lea aso,", "And it shall come to pass in that day,"], ["e le i ai le malamalama o mea aoga,", "that the light shall not be clear,"], ["a o le pouliuli lava;", "nor dark:"]]},
  {num:7,words:[["a e oo mai le aso,", "But it shall be one day which shall be known to the LORD,"], ["e tasi lava ia,", "not day,"], ["(ua silafia lava e Ieova, ) e le o le ao,", "nor night:"], ["e le o le po;", "but it shall come to pass,"], ["a e a oo i le itu aso afiafi e malamalama ai.", "that at evening time it shall be light."]]},
  {num:8,words:[["O lea aso foi e alu atu ai le vai ola nai Ierusalema o le tasi ona vaega e tafe atu i le sami i sasae,", "And it shall be in that day, that living waters shall go out from Jerusalem;"], ["a o le isi ona vaega e tafe atu i le sami i sisifo;", "half of them toward the former sea,"], ["o le tausaga vevela ma le tausaga maalili e fai ai ia mea .", "and half of them toward the hinder sea: in summer and in winter shall it be."]]},
  {num:9,words:[["E fai foi Ieova ma Tupu i le lalolagi uma lava;", "And the LORD shall be king over all the earth:"], ["o lea aso ua na o Ieova ai lava,", "in that day shall there be one LORD,"], ["ma lona suafa e āu tasi lea.", "and his name one."]]},
  {num:10,words:[["E liua le nuu uma pei o le fanua laugatasi,", "All the land shall be turned as a plain from Geba to Rimmon south of Jerusalem:"], ["e pau mai i Kepa e oo i Rimoni i le itu i toga o Ierusalema; e faaeaina foi o ia,", "and it shall be lifted up,"], ["ma nofo i lona lava nuu,", "and inhabited in her place,"], ["e pau mai i le faitotoa o Peniamina e oo i le mea sa i ai le faitotoa anamua,", "from Benjamin's gate unto the place of the first gate,"], ["e oo i le faitotoa o tulimanu; e pau mai foi i le 'olo o Hananiali,", "unto the corner gate,"], ["e oo i le tuugāuaina a le tupu.", "and from the tower of Hananeel unto the king's winepresses."]]},
  {num:11,words:[["Latou te nonofo ai,", "And men shall dwell in it,"], ["e le toe ai se faafanoga;", "and there shall be no more utter destruction;"], ["e nofo lava Ierusalema ma le filemu.", "but Jerusalem shall be safely inhabited."]]},
  {num:12,words:[["O lenei le mala e taia a'i e Ieova o nuu uma e tau ma Ierusalema;", "And this shall be the plague wherewith the LORD will smite all the people that have fought against Jerusalem;"], ["e lāuvale lava o latou tino,", "Their flesh shall consume away while they stand upon their feet,"], ["a o tutū i o latou vae; e totō o latou mata i mea e tutū ai,", "and their eyes shall consume away in their holes,"], ["ma o latou laulaufaiva e faaumatia ia i o latou gutu.", "and their tongue shall consume away in their mouth."]]},
  {num:13,words:[["O lea aso foi e i ai ia te i latou le atuatuvale tele mai ia Ieova;", "And it shall come to pass in that day,"], ["ona taitasi ai lea ma tago o le tasi i le lima o le tasi;", "that a great tumult from the LORD shall be among them; and they shall lay hold every one on the hand of his neighbour,"], ["e taitasi foi ma sii i luga o latou lima o le tasi i le tasi.", "and his hand shall rise up against the hand of his neighbour."]]},
  {num:14,words:[["O Iuta foi e 'au i laua ma Ierusalema;", "And Judah also shall fight at Jerusalem;"], ["e faaputuina oloa o nuu uma e ua vagavagai,", "and the wealth of all the heathen round about shall be gathered together,"], ["o auro,", "gold, and silver,"], ["ma ario,", "and apparel,"], ["ma ofu e tele lava.", "in great abundance."]]},
  {num:15,words:[["E faapea foi ona i ai le mala i le solofanua,", "And so shall be the plague of the horse,"], ["ma le falata,", "of the mule,"], ["ma le kamela,", "of the camel,"], ["ma le asini,", "and of the ass,"], ["atoa ma manu uma e i ai i ia toagālauapi,", "and of all the beasts that shall be in these tents,"], ["e tusa ma lenei mala.", "as this plague."]]},
  {num:16,words:[["O e totoe uma lava i nuu uma o e o mai e tau ma Ierusalema,", "And it shall come to pass,"], ["latou te o ae lava i lea tausaga ma lea tausaga e ifo i le Tupu,", "that every one that is left of all the nations which came against Jerusalem shall even go up from year to year to worship the King,"], ["o Ieova o 'au;", "the LORD of hosts,"], ["e fai ai foi le tausamiga o fale apitaga.", "and to keep the feast of tabernacles."]]},
  {num:17,words:[["A o le le alu ae ai itu aiga o le lalolagi i Ierusalema e ifo i le Tupu,", "And it shall be,"], ["o Ieova o 'au,", "that whoso will not come up of all the families of the earth unto Jerusalem to worship the King, the LORD of hosts,"], ["ona leai lea o se uaga ia te i latou.", "even upon them shall be no rain."]]},
  {num:18,words:[["A e afai e le alu ae le itu aiga o Aikupito,", "And if the family of Egypt go not up,"], ["ma latou le o mai,", "and come not,"], ["e leai foi se uaga ia te i latou;", "that have no rain; there shall be the plague,"], ["ona i ai lea o le mala e taia a'i e Ieova o nuu o e le o ae e fai le tausamiga o fale apitaga.", "wherewith the LORD will smite the heathen that come not up to keep the feast of tabernacles."]]},
  {num:19,words:[["O le sala lena a Aikupito, ma le sala a nuu uma,", "This shall be the punishment of Egypt,"], ["o e le o ae e fai le tausamiga o fale apitaga.", "and the punishment of all nations that come not up to keep the feast of tabernacles."]]},
  {num:20,words:[["O lea aso e i ai i tagitagi uamea o solofanua,", "In that day shall there be upon the bells of the horses,"], ["E paia ia Ieova ; o ulo foi i le fale o Ieova,", "HOLINESS UNTO THE LORD;"], ["e tutusa ia ma ipu i luma o le fata faitaulaga.", "and the pots in the LORD'S house shall be like the bowls before the altar."]]},
  {num:21,words:[["O ulo uma foi i Ierusalema ma Iuta,", "Yea,"], ["e paia lava ia ia Ieova o 'au;", "every pot in Jerusalem and in Judah shall be holiness unto the LORD of hosts:"], ["o i latou uma o e fasi manu, latou te o mai ma ave nisi ulo ,", "and all they that sacrifice shall come and take of them,"], ["ma tunu ai;", "and seethe therein:"], ["e le toe i ai lava se sa Kananā i le fale o Ieova o 'au i lea aso.", "and in that day there shall be no more the Canaanite in the house of the LORD of hosts."]]},
];
renderVerseSet(zec_ch_14_Verses, 'zec-ch14-verses');

})();