(function() {
var _zec_ch_1_Verses = [
  {num:1,words:[["O le valuga masina,", "the valuga month"], ["o le lua", "the two"], ["o tausaga o Tariu,", "year of Darius"], ["na tŭlei mai ai", "tŭlei from"], ["le afioga", "the word (divine)"], ["a Ieova ia", "of the LORD to"], ["Sakaria", "Zechariah"], ["le perofeta", "the prophet"], ["le atalii o Parakaio,", "the son of Parakaio"], ["o le atalii", "the son"], ["ia", "to"], ["o Ito,", "Ito"], ["o loo faapea mai,", "saying from"]]},
  {num:2,words:[["Sa matuā toasa", "exceedingly wrath"], ["Ieova", "the LORD"], ["i o outou", "in of you (all)"], ["tamā.", "father"]]},
  {num:3,words:[["E te fai atu foi", "by said to also"], ["ia te i latou,", "unto them"], ["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["Ia outou foi mai ia te au,", "to you (all) return unto me"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of me"], ["ona ou foi atu lea", "and I also"], ["ia te outou,", "unto you"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of me"]]},
  {num:4,words:[["Aua tou te faapei", "for second person plural like"], ["o outou tamā,", "you (all) father"], ["o", "o"], ["e", "by"], ["na valaauina", "called"], ["e perofeta anamua,", "to the prophets of old"], ["na faapea,", "thus"], ["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["Ina foi mai ia", "so that return to"], ["i o outou", "in of you (all)"], ["ala leaga,", "way evil"], ["ma", "and"], ["a outou galuega leaga;", "but you (all) work evil"], ["a", "but"], ["e lei faalogo", "by not hearken"], ["mai", "from"], ["i latou,", "them"], ["ma lei uai", "and not desire"], ["mai o latou", "from of they"], ["taliga ia te au,", "ear unto me"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:5,words:[["O outou tamā po", "you (all) father night"], ["o fea o", "where?/which? of"], ["i ai", "therein"], ["i latou?", "them"], ["o le au", "the me"], ["perofeta foi,", "prophet also"], ["e faavavau ea", "forever indeed?/really?"], ["ona ola o", "and life of"], ["i latou?", "them"]]},
  {num:6,words:[["A", "but"], ["e peitai", "to however"], ["o a'u upu", "I am word"], ["ma a'u tulafono,", "and me law"], ["na ou poloai atu ai", "I commanded"], ["i a'u auauna", "in me servant"], ["le au perofeta,", "the me prophet"], ["na", "na"], ["le maua atu ai ea", "the received indeed?/really?"], ["o outou tamā?", "you (all) father"], ["ona latou foi mai ai lea,", "and they return then then"], ["ma latou fai mai,", "and they said"], ["E pei ona", "as"], ["finagalo o Ieova", "a chiefs will or desire the LORD"], ["o 'au,", "me"], ["e fai ia te", "to make unto"], ["i matou,", "in we (excl)"], ["e tusa ma", "according to"], ["o matou ala", "we (excl) way"], ["ma", "and"], ["a matou galuega,", "but we (excl) work"], ["ua faapea lava", "and it was so"], ["ona faia e", "and made by"], ["ia ia te i matou.", "to him in we (excl)"]]},
  {num:7,words:[["O le aso", "the day"], ["e luafulu", "to twenty"], ["ma le fa,", "and four"], ["o le masina", "the month"], ["e sefulu", "by ten"], ["ma le tasi,", "and the one"], ["o le masina", "the month"], ["o Sapata lea,", "Zabdi"], ["o le tausaga", "the year"], ["e lua o Tariu,", "by two of Darius"], ["na tŭlei mai ai", "tŭlei from"], ["le afioga", "the word (divine)"], ["a Ieova ia", "of the LORD to"], ["Sakaria", "Zechariah"], ["le perofeta", "the prophet"], ["le atalii o Parakaio,", "the son of Parakaio"], ["o le atalii", "the son"], ["ia", "to"], ["o Ito,", "Ito"], ["o loo faapea mai,", "saying from"]]},
  {num:8,words:[["Na ou vaai", "I looked"], ["i le po;", "in the night"], ["faauta foi,", "and behold"], ["o le tagata", "man"], ["o loo tietie", "is (progressive) ride"], ["i le solofanua mūmū,", "in the horse mūmū"], ["o loo tu foi", "is (progressive) stand also"], ["o ia", "he"], ["i le ulu atasi,", "in the head atasi"], ["i le paolo;", "in the paolo"], ["o loo", "is/are (progressive)"], ["i ona tua foi", "in then behind also"], ["o solofanua mūmū", "horse mūmū"], ["ma", "and"], ["e eefu,", "by eefu"], ["ma", "and"], ["e sisina.", "by sisina"]]},
  {num:9,words:[["Ona ou fai atu lea,", "and I said to"], ["Le alii e,", "the Lord by"], ["o", "o"], ["a ea nei mea?", "but indeed?/really? this thing"], ["Ua fai mai ia te au", "said unto me"], ["le agelu", "the angel"], ["na", "na"], ["ma tautala,", "and speak"], ["Ou te faailoa", "I will revealed"], ["ia te oe", "unto you"], ["le uiga o nei mea.", "the kind of this thing"]]},
  {num:10,words:[["Ona tali mai lea", "and respond from"], ["o le tagata", "man"], ["sa tu", "stood"], ["i le ulu atasi,", "in the head atasi"], ["ua faapea mai,", "and said"], ["O", "O"], ["i latou ia", "them to"], ["ua aauina", "sent"], ["e Ieova", "the LORD"], ["e feoai", "to walk about"], ["i le lalolagi.", "on the earth"]]},
  {num:11,words:[["Ona tali mai lea", "and respond from"], ["o", "o"], ["i latou", "them"], ["i le agelu", "in the angel"], ["a Ieova,", "of the LORD"], ["sa tu", "stood"], ["i le ulu atasi,", "in the head atasi"], ["ua faapea mai,", "and said"], ["Ua matou feoai lava", "we (excl) walked about indeed"], ["i le lalolagi;", "on the earth"], ["faauta foi,", "and behold"], ["o loo nofonofo", "is (progressive) nofonofo"], ["le lalolagi uma,", "the earth all"], ["ua fifilemu lava.", "fifilemu indeed"]]},
  {num:12,words:[["Ona fai atu lea", "And he said"], ["o le agelu", "the angel"], ["a Ieova,", "of the LORD"], ["ua faapea atu,", "and said"], ["Ieova o 'au e,", "the LORD of me by"], ["se'i afea", "a flower put into the hair or when?"], ["ona", "and"], ["e le alofa", "shall not love"], ["ia Ierusalema,", "to Jerusalem"], ["ma aai o Iuta,", "and city of Judas"], ["ua e toasa", "you wrath"], ["i ai", "therein"], ["i ia tausaga", "in to year"], ["e fitugafulu?", "to seventy"]]},
  {num:13,words:[["Ua tali mai", "responded from"], ["Ieova", "the LORD"], ["i le agelu", "in the angel"], ["na", "na"], ["ma tautala,", "and speak"], ["i upu lelei", "in word good"], ["ma upu faamafanafana.", "and word to hearten"]]},
  {num:14,words:[["Ua fai mai foi", "said also"], ["ia te au", "unto me"], ["le agelu", "the angel"], ["na", "na"], ["ma tautala,", "and speak"], ["Ia e alaga,", "to to cry"], ["ia faapea atu,", "to thus"], ["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["Ua ou maelega", "I maelega"], ["ona o Ierusalema", "because of Jerusalem"], ["ma Siona", "and Zion"], ["i le maelega tele.", "in the maelega great"]]},
  {num:15,words:[["Ua ou matuā", "I exceedingly"], ["ita lava", "angry indeed"], ["i nuu ese", "in nation away"], ["o", "o"], ["e nonofo faafifilemu;", "to dwell faafifilemu"], ["auā", "for"], ["na itiiti", "small"], ["lo'u ita,", "my angry"], ["a o", "but of"], ["i latou,", "them"], ["ua latou faateleina", "they multiplied"], ["le malaia.", "the disaster"]]},
  {num:16,words:[["O le mea lea,", "therefore"], ["o loo faapea ona", "saying and"], ["fetalai mai ai", "said"], ["o Ieova,", "the LORD"], ["Ua ou foi atu", "I also"], ["i Ierusalema", "in Jerusalem"], ["ma le alofa;", "and the love"], ["e fai ai", "to make"], ["lo'u fale,", "my house"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of me"], ["e faataotoina foi", "to lay down also"], ["le fua", "the fruit"], ["i luga o Ierusalema.", "upon Jerusalem"]]},
  {num:17,words:[["Ia e toe", "to to again"], ["alaga,", "cry"], ["ia faapea atu,", "to thus"], ["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["E toe oso", "to again food for a journey"], ["i tua o'u aai", "in behind my city"], ["ona", "and"], ["o le manuia;", "the peace"], ["e toe faamafanafana Ieova", "to again to hearten the LORD"], ["ia Siona,", "to Zion"], ["na te toe", "he again"], ["filifili foi", "choose also"], ["ia Ierusalema.", "to Jerusalem"]]},
  {num:18,words:[["Ua ou tepa ae foi", "I looked up also"], ["i luga,", "in above"], ["ua ou vaai,", "I saw"], ["faauta,", "behold"], ["o nifo", "tooth"], ["e fa.", "by four"]]},
  {num:19,words:[["Ona ou fai atu lea", "and I said to"], ["i le agelu", "in the angel"], ["na", "na"], ["ma tautala,", "and speak"], ["O", "O"], ["a ea ia", "but indeed?/really? to"], ["mea?", "thing"], ["Ua fai mai", "said"], ["o ia ia te au,", "he unto me"], ["O mea ia,", "thing to"], ["o nifo", "tooth"], ["na faataapeapeina ai", "scattered"], ["Iuta,", "Judas"], ["ma Isaraelu,", "and Israel"], ["ma Ierusalema.", "and Jerusalem"]]},
  {num:20,words:[["Ua faaali mai foi", "revealed also"], ["e Ieova ia te au", "the LORD unto me"], ["o tufuga", "master builder"], ["e toafa.", "to four (people)"]]},
  {num:21,words:[["Ona ou fai atu lea,", "and I said to"], ["Ua o mai", "of from"], ["i latou", "them"], ["na e fai", "you made"], ["i ni", "in some"], ["a?", "but"], ["Ua tali mai", "responded from"], ["o ia,", "he"], ["ua faapea mai,", "and said"], ["O nifo ia", "tooth to"], ["na faataapeapeina ai", "scattered"], ["Iuta,", "Judas"], ["ua oo ina", "it came to pass so that"], ["leai se tasi", "no a one"], ["na ea", "indeed?/really?"], ["i luga", "in above"], ["lona ulu;", "his head"], ["a", "but"], ["ua o mai", "of from"], ["i latou nei", "them this"], ["e faamatau ia te", "to make ax unto"], ["i latou,", "them"], ["e lafo", "to cloth used as gratuity for a talking chief"], ["i lalo nifo", "in under tooth"], ["o nuu ese,", "nation away"], ["e", "by"], ["na sii", "lifted up"], ["i luga lo latou nifo", "in above their tooth"], ["i le laueleele", "in the earth"], ["o Iuta", "Judas"], ["e faataapeapeina ai.", "to scattered"]]},
];
renderVerseSet(_zec_ch_1_Verses, 'zec-ch1-verses');

var _zec_ch_2_Verses = [
  {num:1,words:[["Ua ou tepa ae foi", "I looked up also"], ["i luga,", "in above"], ["ua ou vaai,", "I saw"], ["faauta,", "behold"], ["o le tagata", "man"], ["ma le maea", "and the rope"], ["e fua a'i", "to fruit"], ["i lona lima.", "in his five"]]},
  {num:2,words:[["Ona ou fai atu ai lea,", "and I said to then then"], ["Po o fea", "night of where?/which?"], ["e te alu", "by go"], ["i ai?", "therein"], ["Ua fai mai", "said"], ["o ia ia te au,", "he unto me"], ["Ou te alu,", "I will go"], ["ou te fuatia Ierusalema,", "I will weighed Jerusalem"], ["ia iloa", "to know"], ["pe faapefea", "whether how"], ["lona lautele,", "his wide"], ["pe faapefea foi", "whether how also"], ["lona umi.", "his long"]]},
  {num:3,words:[["Faauta foi,", "and behold"], ["ua alu atu", "went away"], ["le agelu", "the angel"], ["na", "na"], ["ma tautala;", "and speak"], ["o le tasi agelu foi", "the one angel also"], ["ua alu ane", "went forth"], ["e faafetaiai ia te ia.", "to meet to him"]]},
  {num:4,words:[["Ua ia fai ane ia te ia,", "to said to him"], ["Momo'e ia,", "lie down to"], ["ina fai atu", "so that said to"], ["i lena", "in that"], ["taulealea,", "young man"], ["ia faapea atu,", "to thus"], ["E āina Ierusalema", "by āina Jerusalem"], ["e oo", "it shall come to pass"], ["i faoa aai,", "in seized captive city"], ["ona", "and"], ["o le tele", "the great"], ["o tagata", "of men"], ["ma manu e", "and animal by"], ["i ai.", "therein"]]},
  {num:5,words:[["O a'u foi,", "I am also"], ["ua fetalai mai", "said"], ["Ieova,", "the LORD"], ["e fai a'u", "to make me"], ["ma pa afi", "and a wall fire"], ["e siosio a'i,", "by siosio"], ["e fai foi", "to make also"], ["a'u", "me"], ["ma pupula", "and brightness"], ["i totonu ia te ia.", "in inside to him"]]},
  {num:6,words:[["Sole e!", "alofi vae by"], ["sole e!", "alofi vae by"], ["sosola mai ia outou,", "fled from to you (all)"], ["ai", "ai"], ["le nuu", "the nation"], ["i le itu", "on the side"], ["i matu,", "northward"], ["ua fetalai mai ai", "said"], ["Ieova;", "the LORD"], ["auā", "for"], ["na ou faataapeape ia te outou,", "I faataapeape unto you"], ["e pei o matāmatagi", "like matāmatagi"], ["e fa,", "by four"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:7,words:[["E!", "by"], ["Siona e,", "Zion by"], ["ia e laveai oe", "to to deliver you"], ["ia te oe,", "unto you"], ["o lē nofo faatasi ma le tama fafine", "not dwell together and the child woman"], ["a Papelonia.", "of Babylon"]]},
  {num:8,words:[["Auā o loo faapea ona", "for saying then"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["E mulimuli ane", "to follow after"], ["i le mamalu,", "in the glory"], ["ua ia auina mai", "to sent from"], ["o a'u", "I am"], ["i nuu ese", "in nation away"], ["na vetea", "vetea"], ["a outou mea;", "but you (all) thing"], ["auā o lē pai atu", "for of not pie"], ["ia te outou,", "unto you"], ["ua pāia e", "pāia by"], ["ia le tamatamai", "to the tamatamai"], ["mata", "eye"], ["o lona fofoga.", "his face"]]},
  {num:9,words:[["Auā faauta,", "for behold"], ["ou te siisii atu", "I will a method of taking fish"], ["lo'u lima", "my five"], ["i luga ia te", "in above unto"], ["i latou;", "them"], ["e fai foi", "to make also"], ["i latou", "them"], ["ma vete", "and plunder"], ["i o latou", "in of they"], ["pologa;", "mouldy"], ["ona outou iloa lea,", "and you (all) know"], ["ua auina mai a'u", "sent from me"], ["e Ieova o 'au.", "the LORD me"]]},
  {num:10,words:[["Le tama fafine", "the child woman"], ["a Siona e,", "of Zion by"], ["ia e alaga,", "to to cry"], ["ma ia olioli;", "and to rejoice"], ["auā faauta,", "for behold"], ["ou te alu atu,", "I will go away"], ["ma ou nofo", "and I dwell"], ["i totonu ia te oe,", "in inside unto you"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:11,words:[["E faaopoopoina atu nuu ese", "to added nation away"], ["e tele ia", "to great to"], ["Ieova", "the LORD"], ["i lea", "in"], ["aso;", "day"], ["e fai", "to make"], ["i latou mo'u nuu,", "them many nation"], ["ou te nofo foi", "I will dwell also"], ["i totonu ia te oe;", "in inside unto you"], ["ona", "and"], ["e iloa ai lea", "to know then then"], ["ua auina a'u", "sent me"], ["ia te oe", "unto you"], ["e Ieova o 'au.", "the LORD me"]]},
  {num:12,words:[["E maua", "to received"], ["e Ieova o Iuta,", "the LORD Judas"], ["o lona tofi", "his lot"], ["i le laueleele paia;", "in the earth holy"], ["e toe filifilia foi", "to again chosen also"], ["e ia", "by him"], ["o Ierusalema.", "Jerusalem"]]},
  {num:13,words:[["Faalologo ia", "to hold one's tongue to"], ["o tagata uma", "of men all"], ["i luma o Ieova;", "before the LORD"], ["auā", "for"], ["ua tulai mai", "arose up from"], ["o ia", "he"], ["nai", "from"], ["lona malumalu paia.", "his temple holy"]]},
];
renderVerseSet(_zec_ch_2_Verses, 'zec-ch2-verses');

var _zec_ch_3_Verses = [
  {num:1,words:[["Ua ia faaali mai foi", "to revealed also"], ["ia te au", "unto me"], ["o Iosua", "Joshua"], ["le faitaulaga sili,", "the priest most"], ["o loo tu", "is (progressive) stand"], ["i luma", "in before"], ["o le agelu", "the angel"], ["a Ieova;", "of the LORD"], ["o Satani foi,", "Satan also"], ["o loo tu", "is (progressive) stand"], ["o ia", "he"], ["i lona itu taumatau", "in his side right hand"], ["e tetee atu", "to to refuse"], ["ia te ia.", "to him"]]},
  {num:2,words:[["Ona fetalai atu lea", "and said to"], ["o Ieova ia", "the LORD to"], ["Satani,", "Satan"], ["Ia aoai atu", "to chastise"], ["Ieova ia te oe", "the LORD unto you"], ["Satani,", "Satan"], ["ia aoai atu ia te oe", "to chastise unto you"], ["Ieova,", "the LORD"], ["o le", "the"], ["ua filifili", "chose"], ["i Ierusalema;", "in Jerusalem"], ["e le", "by the"], ["o le motumotu ea lenei", "the motumotu indeed?/really? this"], ["na seia mai le afi?", "until from the fire"]]},
  {num:3,words:[["Ua ofu Iosua", "garment Joshua"], ["i ofu eleelea;", "in garment eleelea"], ["ua tu foi", "stood also"], ["o ia", "he"], ["i luma", "in before"], ["o le agelu.", "the angel"]]},
  {num:4,words:[["Ua ia tali atu,", "to responded"], ["ma fetalai atu", "and said to"], ["i", "in"], ["e", "by"], ["na tutū mai", "stood up from"], ["i ona luma,", "before him"], ["o loo faapea,", "saying"], ["Ave ese ia", "take away to"], ["o ofu eleelea", "garment eleelea"], ["ua ofu ai", "garment"], ["o ia.", "he"], ["Ua ia fetalai atu foi", "and he also said"], ["ia te ia,", "to him"], ["Faauta,", "behold"], ["ua ou aveesea au", "I removed away me"], ["amioletonu", "wickedness"], ["i ou luga;", "in I above"], ["ou te faaofu foi", "I will make garment also"], ["ia te oe", "unto you"], ["i le ofu matagofie.", "in the garment beautiful"]]},
  {num:5,words:[["Ona ou fai atu lea,", "and I said to"], ["Ia latou faaee", "to they to place upon"], ["le pulou lelei", "the a covering for the head good"], ["i luga", "in above"], ["o lona ulu.", "his head"], ["Ona latou faaee ai lea", "and they to place upon then then"], ["o le pulou lelei", "the a covering for the head good"], ["i lona ulu,", "in his head"], ["ma faaofu ia te ia", "and make garment to him"], ["i ofu;", "in garment"], ["o loo tu mai foi", "is (progressive) stood also"], ["le agelu", "the angel"], ["a Ieova.", "of the LORD"]]},
  {num:6,words:[["Ua matuā fai atu", "exceedingly said to"], ["le agelu", "the angel"], ["a Ieova ia", "of the LORD to"], ["Iosua,", "Joshua"], ["o loo faapea,", "saying"]]},
  {num:7,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["Afai", "if"], ["e te savali", "by walk"], ["i o'u ala,", "in my way"], ["afai foi", "if also"], ["e te tausiusi", "by obey"], ["i a'u sauniga,", "in me preparation"], ["ona", "and"], ["e faamasino ai lea", "to judge then then"], ["i lo'u fale,", "in my house"], ["ma", "and"], ["e leoleo", "to guard"], ["i o'u lotoā;", "in my court"], ["ou te tuu atu foi", "I will placed also"], ["ia te oe", "unto you"], ["ta'ita'i mai ia te", "lead from"], ["i latou nei", "them this"], ["o", "o"], ["e tutū mai.", "to stood up from"]]},
  {num:8,words:[["Ia e faalogo", "to to hearken"], ["mai Iosua e,", "from Joshua by"], ["le faitaulaga sili,", "the priest most"], ["o oe", "you"], ["atoa ma", "and"], ["e ua ia te oe,", "by it is yours"], ["o", "o"], ["e nonofo", "to dwell"], ["i ou luma;", "before thee"], ["auā", "for"], ["e fai ma faailoga nei tagata;", "to be sign this man"], ["faauta foi,", "and behold"], ["ou te aumaia", "I will bring here"], ["la'u auauna", "my servant"], ["o le La laau .", "the La tree"]]},
  {num:9,words:[["Auā faauta,", "for behold"], ["o le maa", "the stone"], ["na ou tuuina atu", "I given / delivered"], ["i luma o Iosua,", "before Joshua"], ["e", "by"], ["i le maa", "in the stone"], ["e tasi mata", "by one eye"], ["e fitu;", "by seven"], ["faauta,", "behold"], ["ou te togitogi", "I will togitogi"], ["i ai", "therein"], ["ona togitogiga,", "and togitogiga"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of me"], ["ma ou ave ese", "and I take away"], ["le amioletonu", "the wickedness"], ["a le nuu nei", "but the nation this"], ["i le aso", "in the day"], ["e tasi.", "by one"]]},
  {num:10,words:[["Ua fetalai mai", "said"], ["Ieova o 'au,", "the LORD of me"], ["O lea", "therefore"], ["aso tou te taitasi ai", "day second person plural each"], ["ma valaau", "and call"], ["i lana uo", "in his uo"], ["i lalo", "in under"], ["o le vine", "the vine"], ["ma lalo", "and under"], ["o le mati.", "the fig"]]},
  {num:11,words:[["Ua ou fai atu foi", "I said to also"], ["ia te ia,", "to him"], ["o loo faapea,", "saying"], ["O", "O"], ["a ea", "but indeed?/really?"], ["na olive", "olive"], ["e lua", "by two"], ["i le itu taumatau", "on the side right hand"], ["o le lamepa,", "the lamp"], ["ma lona itu tauagavale?", "and his side left"]]},
  {num:12,words:[["Ona ou fai atu faalua lea", "and I said to twice"], ["ia te ia,", "to him"], ["O loo 1304", "is (progressive) 1304"]]},
];
renderVerseSet(_zec_ch_3_Verses, 'zec-ch3-verses');

var _zec_ch_4_Verses = [
  {num:1,words:[["Ua foi mai le", "returned the"], ["agelu", "angel"], ["na", "na"], ["ma tautala,", "and speak"], ["ua ia fafagu mai ia te au,", "to fafagu from me"], ["e pei o le tagata", "like the man"], ["ua fagua", "fagua"], ["na moe.", "slept"]]},
  {num:2,words:[["Ona fai mai lea", "And he said"], ["o ia ia te au,", "he unto me"], ["O le a ea", "what indeed?/really?"], ["ua e vaaia?", "you seen"], ["Ona ou fai atu lea,", "and I said to"], ["Ua ou iloa,", "I knew"], ["faauta,", "behold"], ["o le lamepa", "the lamp"], ["ua auro atoatoa,", "gold completely"], ["ma lona tuugāsuāuu", "and his tuugāsuāuu"], ["i ona luga,", "in then above"], ["mona tuugālamepa", "to burst forth (as faiai tuugālamepa"], ["e fitu", "by seven"], ["i ona luga,", "in then above"], ["ma ala", "and way"], ["e taifitu", "by taifitu"], ["i tuugālamepa o loo", "in tuugālamepa is (progressive)"], ["i ona luga;", "in then above"]]},
  {num:3,words:[["ma olive", "and olive"], ["e lua", "by two"], ["i ona tafatafa,", "in then to cut in many places"], ["o le tasi", "the one"], ["i le itu taumatau", "on the side right hand"], ["o le tuugāsuāuu,", "the tuugāsuāuu"], ["ma le tasi", "and the one"], ["i lona itu tauagavale.", "in his side left"]]},
  {num:4,words:[["Ua ou toe", "I again"], ["fai atu", "said to"], ["i le agelu", "in the angel"], ["na", "na"], ["ma tautala,", "and speak"], ["ua faapea atu,", "and said"], ["Le alii e,", "the Lord by"], ["o", "o"], ["a ea ia", "but indeed?/really? to"], ["mea?", "thing"]]},
  {num:5,words:[["Ona tali mai lea", "and respond from"], ["o le agelu", "the angel"], ["na", "na"], ["ma tautala,", "and speak"], ["ua faapea mai ia te au,", "and said unto me"], ["E te", "by"], ["le iloa ea po", "the know indeed?/really? night"], ["o", "o"], ["a mea nei?", "but thing this"], ["Ona ou fai atu lea,", "and I said to"], ["Le alii e,", "the Lord by"], ["ou te", "I will"], ["le iloa .", "the know"]]},
  {num:6,words:[["Ua tali mai", "responded from"], ["o ia,", "he"], ["ua fai mai ia te au,", "said unto me"], ["o loo faapea mai,", "saying from"], ["O le afioga lenei", "the word (divine) this"], ["a Ieova ia", "of the LORD to"], ["Serupapelu,", "Serupapelu"], ["o loo faapea mai,", "saying from"], ["E le", "by the"], ["o le fitafita,", "the policeman"], ["e le", "by the"], ["o le malosi,", "the strong"], ["a", "but"], ["o lo'u Agaga,", "my spirit"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of me"]]},
  {num:7,words:[["O ai ea oe", "who you"], ["le mauga tele", "the mountain great"], ["e?", "by"], ["e faalaugatasia oe", "by faalaugatasia you"], ["i luma o Serupapelu;", "before Serupapelu"], ["na te aumaia foi", "he brought here also"], ["le maa tulimanu aupitoaluga,", "the stone the corner (as of a aupitoaluga"], ["o loo alalaga,", "is (progressive) cry out"], ["Le alofa tunoa e!", "grace by"], ["ia ia te ia", "to him to"], ["le alofa tunoa.", "grace"]]},
  {num:8,words:[["Ua oo mai foi", "it came to pass from also"], ["ia te au", "unto me"], ["le afioga", "the word (divine)"], ["a Ieova,", "of the LORD"], ["o loo faapea mai,", "saying from"]]},
  {num:9,words:[["O lima o Serupapelu", "five of Serupapelu"], ["na faavaeina ai", "foundation"], ["le fale nei,", "the house this"], ["o", "o"], ["ona lima foi", "and five also"], ["e faauma a'i;", "to finish"], ["e te iloa ai", "by know"], ["foi,", "also"], ["ua auina mai a'u", "sent from me"], ["ia te outou", "unto you"], ["e Ieova o 'au.", "the LORD me"]]},
  {num:10,words:[["Auā po o ai ea", "for who? indeed?/really?"], ["ua 'ino'ino", "hated"], ["i le aso", "in the day"], ["o mea iti? Latou te fiafia", "thing small they will competition"], ["ina", "so that"], ["ua latou vaai", "they looked"], ["i le fua faatautau", "in the fruit make to hang up"], ["i le lima", "in the five"], ["o Serupapelu;", "Serupapelu"], ["o", "o"], ["i latou nei", "them this"], ["e fitu,", "by seven"], ["o fofoga o Ieova", "face the LORD"], ["i latou,", "them"], ["o fetaufetuliai", "contend with one another"], ["i le lalolagi uma.", "on the earth all"]]},
  {num:11,words:[["Ua ou fai atu foi", "I said to also"], ["ia te ia,", "to him"], ["o loo faapea,", "saying"], ["O", "O"], ["a ea", "but indeed?/really?"], ["na olive", "olive"], ["e lua", "by two"], ["i le itu taumatau", "on the side right hand"], ["o le lamepa,", "the lamp"], ["ma lona itu tauagavale?", "and his side left"]]},
  {num:12,words:[["Ona ou fai atu faalua lea", "and I said to twice"], ["ia te ia,", "to him"], ["o loo faapea atu,", "saying"], ["O", "O"], ["a ea magāolive", "but indeed?/really? magāolive"], ["e lua,", "by two"], ["o loo liligi", "is (progressive) to pour"], ["mai ia te", "from"], ["i laua lava", "them indeed"], ["le uu auro", "the oil gold"], ["i ala auro", "in way gold"], ["e lua?", "by two"]]},
  {num:13,words:[["Ona fai mai lea", "And he said"], ["o ia ia te au,", "he unto me"], ["o loo faapea mai,", "saying from"], ["E te", "by"], ["le iloa ea po", "the know indeed?/really? night"], ["o", "o"], ["a ia mea?", "but to thing"], ["Ona ou fai atu lea,", "and I said to"], ["Le alii e,", "the Lord by"], ["ou te", "I will"], ["le iloa .", "the know"]]},
  {num:14,words:[["Ona fai mai lea", "And he said"], ["o ia.", "he"], ["O tagata faauuina", "of men anointed"], ["i laua nei,", "them this"], ["o loo tutū", "is (progressive) stood up"], ["i luma", "in before"], ["o le Alii", "the Lord"], ["o le lalolagi uma.", "the earth all"]]},
];
renderVerseSet(_zec_ch_4_Verses, 'zec-ch4-verses');

var _zec_ch_5_Verses = [
  {num:1,words:[["Ona ou toe tepa ae lea", "and I again looked up"], ["ma ou iloa,", "and I know"], ["faauta,", "behold"], ["o le tusi taai", "the book taai"], ["ua lele.", "flew"]]},
  {num:2,words:[["Ua ia fai mai ia te au,", "he said unto me"], ["O le a ea", "what indeed?/really?"], ["ua e iloa?", "you knew"], ["Ona ou fai atu lea,", "and I said to"], ["Ua ou iloa", "I knew"], ["le tusi taai", "the book taai"], ["ua lele;", "flew"], ["o lona umi,", "his long"], ["o kupita", "cubit"], ["e luafulu,", "to twenty"], ["o lona", "his/her"], ["lau", "your"], ["e sefulu kupita", "by ten cubit"], ["ia.", "to"]]},
  {num:3,words:[["Ua fai mai", "said"], ["o ia ia te au,", "he unto me"], ["O le faafano lenei", "the to curse this"], ["o le a alu atu", "what go away"], ["i le fogāeleele uma lava;", "the face of all the earth indeed"], ["auā", "for"], ["e taitasi uma", "by each all"], ["o", "o"], ["e gaoi", "to to steal"], ["ma tafia o ia", "and tafia he"], ["ai lenei", "this"], ["mea ,", "thing"], ["e pei o le tusi;", "like the book"], ["e taitasi uma foi", "by each all also"], ["o", "o"], ["e tauto", "to to take an oath"], ["ma tafia o ia", "and tafia he"], ["ai", "ai"], ["le mea nei,", "the thing this"], ["e pei", "like"], ["e le tusi .", "shall not book"]]},
  {num:4,words:[["Ua fetalai mai", "said"], ["Ieova o 'au,", "the LORD of me"], ["Ou te aumaia;", "I will bring here"], ["e oo atu", "it shall come to pass"], ["lava ia", "indeed to"], ["i le fale", "in the house"], ["o le gaoi,", "the to steal"], ["ma le fale", "and the house"], ["o le", "the"], ["ua tauto pepelo", "to take an oath false"], ["i lo'u igoa;", "in my name"], ["e tumau ai", "to be firm"], ["i totonu", "in inside"], ["o lona fale,", "his house"], ["ma faaumatia ai", "and destroyed"], ["ona laau", "and tree"], ["ma", "and"], ["ona maa.", "and stone"]]},
  {num:5,words:[["Ua alu ane foi", "went forth also"], ["le agelu", "the angel"], ["na", "na"], ["ma tautala,", "and speak"], ["ua fai mai", "said"], ["o ia ia te au,", "he unto me"], ["Ia e tepa i luga,", "to to to look towards in above"], ["ma", "and"], ["e vaai,", "to look"], ["po", "night"], ["o le a lena", "what that"], ["o loo alu atu.", "is/are (progressive) go away"]]},
  {num:6,words:[["Ua ou fai atu,", "I said to"], ["O le a lena?", "what that"], ["Ua fai mai", "said"], ["o ia,", "he"], ["O le efa lena", "the ephah that"], ["o loo alu atu;", "is/are (progressive) go away"], ["ua fai mai foi", "said also"], ["o ia,", "he"], ["O lona tino", "his body"], ["mai lena", "from that"], ["i le nuu uma.", "in the land all"]]},
  {num:7,words:[["Faauta foi,", "and behold"], ["o le taleni", "the talent"], ["o pulu", "latex or milky sap secreted from any plant in general e.g. breadfruit"], ["ua siitia;", "lifted up"], ["o le fafine foi", "the woman also"], ["lenei o loo nofo", "this is (progressive) dwell"], ["i totonu", "in inside"], ["o le efa.", "the ephah"]]},
  {num:8,words:[["Ua ia fai mai foi,", "he said also"], ["O le amio leaga lenei;", "the iniquity this"], ["ona ia lafotuina lea", "and to lafotuina"], ["o ia", "he"], ["i totonu", "in inside"], ["o le efa,", "the ephah"], ["ma", "and"], ["na lafo", "cloth used as gratuity for a talking chief"], ["le fua pulu", "the fruit latex or milky sap secreted from any plant in general e.g. breadfruit"], ["i le gutu", "in the mouth"], ["o le efa .", "the ephah"]]},
  {num:9,words:[["Ua ou tepa foi", "I to look towards also"], ["i luga,", "in above"], ["ona ou iloa lea,", "and I know"], ["faauta,", "behold"], ["o fafine", "woman"], ["e toalua", "to two (people)"], ["na o atu;", "of"], ["ua", "ua"], ["i ai", "therein"], ["foi", "also"], ["le matagi", "the wind"], ["i", "in"], ["o la apaau;", "la a wing"], ["auā", "for"], ["sa ia te", "unto"], ["i laua", "them"], ["o apaau,", "a wing"], ["pei o apaau", "like of a wing"], ["o le kasita;", "the kasita"], ["ua la siitia", "la lifted up"], ["le efa", "the ephah"], ["i le va", "in the expanse"], ["o le lalolagi", "the earth"], ["ma le lagi.", "and the heaven"]]},
  {num:10,words:[["Ona ou fai atu lea", "and I said to"], ["i le agelu", "in the angel"], ["na", "na"], ["ma tautala,", "and speak"], ["Po o fea la te ave", "night of where?/which? la take"], ["i ai", "therein"], ["le efa?", "the ephah"]]},
  {num:11,words:[["Ona fai mai lea", "And he said"], ["o ia ia te au,", "he unto me"], ["O le a ave", "what take"], ["ina ia fai", "so that make"], ["se fale mōna", "a house mōna"], ["i le nuu", "in the land"], ["o Senara;", "Senara"], ["e faatu ai,", "to pitch"], ["ma faamau ai", "and establish"], ["i lona lava taele.", "in his indeed bathe"]]},
];
renderVerseSet(_zec_ch_5_Verses, 'zec-ch5-verses');

var _zec_ch_6_Verses = [
  {num:1,words:[["Ona ou toe tepa ae lea,", "and I again looked up"], ["ma ou iloa,", "and I know"], ["faauta,", "behold"], ["o kariota", "chariot"], ["e fa,", "by four"], ["ua o atu nai", "of from"], ["le va o mauga", "the expanse of mountain"], ["e lua;", "by two"], ["o mauga foi,", "mountain also"], ["o mauga 'apa memea", "mountain can scarlet"], ["ia.", "to"]]},
  {num:2,words:[["O", "O"], ["i le kariota muamua", "in the chariot first the beginning"], ["o solofanua mūmū:", "horse mūmū"], ["o", "o"], ["i le lua", "in the two"], ["o kariota o solofanua uliuli;", "chariot of horse uliuli"]]},
  {num:3,words:[["o", "o"], ["i le tolu", "in the three"], ["o kariota o solofanua sisina;", "chariot of horse sisina"], ["o", "o"], ["i le fa", "in the four"], ["o kariota o solofanua pulepule", "chariot of horse small sheltfish"], ["e malolosi.", "to mighty"]]},
  {num:4,words:[["Ona ou fai atu lea,", "and I said to"], ["ua faapea atu", "and said"], ["i le agelu", "in the angel"], ["na", "na"], ["ma tautala,", "and speak"], ["Le alii e,", "the Lord by"], ["o", "o"], ["a ea ia", "but indeed?/really? to"], ["mea?", "thing"]]},
  {num:5,words:[["Ona tali mai lea", "and respond from"], ["o le agelu,", "the angel"], ["ua fai mai ia te au,", "said unto me"], ["O", "O"], ["i latou ia", "them to"], ["o agaga", "spirit"], ["e toafa", "to four (people)"], ["o le lagi,", "Heaven"], ["ua o atu", "of"], ["sa tutū", "stood up"], ["i luma", "in before"], ["o le Alii", "the Lord"], ["o le lalolagi uma.", "the earth all"]]},
  {num:6,words:[["O le", "the"], ["ua", "ua"], ["i ai", "therein"], ["solofanua uliuli", "horse uliuli"], ["e alu atu", "to go away"], ["ia", "to"], ["i le nuu", "in the land"], ["i le itu", "on the side"], ["i matu;", "northward"], ["ma ē sisina", "and who sisina"], ["e mulimuli atu", "to follow after"], ["i ai;", "therein"], ["a o", "but of"], ["e pulepule", "to small sheltfish"], ["e o atu", "by of"], ["ia", "to"], ["i le nuu", "in the land"], ["i le itu", "on the side"], ["i toga.", "southward"]]},
  {num:7,words:[["Ua o atu foi", "of also"], ["ē malolosi,", "who mighty"], ["ua fia o", "wanted to do something of"], ["ina ia feoai", "so that walk about"], ["i le lalolagi.", "on the earth"], ["Ua ia fai atu foi,", "he said to also"], ["O ia,", "he"], ["ina feoai", "so that walk about"], ["i le lalolagi.", "on the earth"], ["Ona feoai lea", "and walk about"], ["o", "o"], ["i latou", "them"], ["i le lalolagi.", "on the earth"]]},
  {num:8,words:[["Ona ia valaau", "and to call"], ["mai lea", "from"], ["ia te au,", "unto me"], ["ma tautala mai ia te au,", "and speak from me"], ["o loo faapea mai,", "saying from"], ["Vaai ia", "look to"], ["i", "in"], ["e ua o atu", "by of"], ["i le nuu", "in the land"], ["i le itu", "on the side"], ["i matu;", "northward"], ["ua maona ai", "to subside"], ["lo'u loto", "my heart"], ["i le nuu", "in the land"], ["i le itu", "on the side"], ["i matu.", "northward"]]},
  {num:9,words:[["Ua tŭlei mai foi", "tŭlei from also"], ["le afioga", "the word (divine)"], ["a Ieova ia te au,", "of the LORD unto me"], ["o loo faapea mai;", "saying from"]]},
  {num:10,words:[["Ave ia nisi", "take to some"], ["o", "o"], ["i latou", "them"], ["nai", "from"], ["le tafeaga o", "the exiles in wa^ of"], ["sa Heletaī o", "of the clan of Heletaī of"], ["sa Toviā,", "of the clan of Toviā"], ["atoa ma o", "and"], ["sa Itaiā;", "of the clan of Itaiā"], ["o", "o"], ["i latou ia", "them to"], ["na o mai", "of from"], ["i Papelonia;", "in Babylon"], ["e te alu", "by go"], ["lava oe", "indeed you"], ["i lea", "in"], ["aso,", "day"], ["e te ulu atu", "by head"], ["i le fale", "in the house"], ["o Iosia", "Josiah"], ["le atalii o Sefanaia;", "the son of Zephaniah"]]},
  {num:11,words:[["e te avatu foi", "by give away also"], ["ario", "silver"], ["ma auro,", "and gold"], ["ma ia", "and to"], ["e fai a'i pale,", "to make to row"], ["ma faaee ai", "and to place upon"], ["i le ulu", "in the head"], ["o Iosua", "Joshua"], ["le atalii o Iosataka", "the son of Iosataka"], ["le faitaulaga sili.", "the priest most"]]},
  {num:12,words:[["E te fai atu foi", "by said to also"], ["ia te ia,", "to him"], ["ia faapea,", "to thus"], ["Ua faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["o loo faapea mai,", "saying from"], ["Faauta,", "behold"], ["o le tagata", "man"], ["o le La laau", "the La tree"], ["lona igoa;", "his name"], ["e tupu ae", "to king up"], ["o ia ai", "he"], ["le mea", "the thing"], ["e pogai mai ai;", "to cause from"], ["e faia foi", "to made also"], ["e ia le malumalu", "by him the temple"], ["o Ieova;", "the LORD"]]},
  {num:13,words:[["o ia lava", "he indeed"], ["na te faia", "he made"], ["le malumalu o Ieova;", "the temple the LORD"], ["e ia te ia", "by him to"], ["foi", "also"], ["le mamalu,", "the glory"], ["e tietie foi", "to ride also"], ["o ia", "he"], ["ma pule", "and rule"], ["i luga", "in above"], ["o lona nofoālii;", "his throne"], ["e fai foi", "to make also"], ["o ia", "he"], ["ma faitaulaga", "and priest"], ["i luga", "in above"], ["o lona nofoālii;", "his throne"], ["e", "by"], ["i ai", "therein"], ["foi", "also"], ["le pule", "the rule"], ["o le manuia", "the peace"], ["ia te i laua.", "unto them"]]},
  {num:14,words:[["E", "by"], ["i ai", "therein"], ["foi ia pale", "also to to row"], ["mo Elemi,", "for Elemi"], ["ma Tovia,", "and Tovia"], ["ma Itaia,", "and Itaia"], ["ma Heni", "and Heni"], ["le atalii o Sefanaia,", "the son of Zephaniah"], ["e fai ma faamanatuga", "to be faamanatuga"], ["i le malumalu", "in the temple"], ["o Ieova.", "the LORD"]]},
  {num:15,words:[["O", "O"], ["e mamao foi", "to far also"], ["latou te o", "they will"], ["mai", "from"], ["e fai", "to make"], ["le malumalu o Ieova;", "the temple the LORD"], ["ona iloa ai lea", "and know then then"], ["e outou,", "by you (all)"], ["ua auina mai a'u", "sent from me"], ["ia te outou", "unto you"], ["e Ieova o 'au;", "the LORD me"], ["e oo foi", "it shall come to pass also"], ["lenei ,", "this"], ["pe afai tou te matuā faalogo", "whether if second person plural exceedingly hearken"], ["i le siufofoga", "in the voice"], ["o Ieova lo outou Atua.", "the LORD your God"]]},
];
renderVerseSet(_zec_ch_6_Verses, 'zec-ch6-verses');

var _zec_ch_7_Verses = [
  {num:1,words:[["O le tausaga", "the year"], ["e fa o Tariu", "by four of Darius"], ["le tupu,", "the king"], ["ua tŭlei mai ai", "tŭlei from"], ["le afioga", "the word (divine)"], ["a Ieova ia", "of the LORD to"], ["Sakaria", "Zechariah"], ["i le aso", "in the day"], ["e fa,", "by four"], ["i le iva", "in the nine"], ["o masina,", "month"], ["o Kiselu lea.", "Kiselu"]]},
  {num:2,words:[["Ua auina atu", "sent"], ["o Peteli o Saresa,", "Bethel of Saresa"], ["ma Rekemeleki,", "and Rekemeleki"], ["ma", "and"], ["ona tagata", "and man"], ["e faalaulelei", "to make even"], ["i le finagalo", "in the a chiefs will or desire"], ["o Ieova;", "the LORD"]]},
  {num:3,words:[["o loo fai mai", "is/are (progressive) said/told"], ["i faitaulaga", "in priest"], ["e ua", "by"], ["i ai", "therein"], ["i le fale", "in the house"], ["e Ieova o 'au,", "the LORD me"], ["atoa ma perofeta,", "and prophet"], ["o loo faapea mai,", "saying from"], ["Ou te tagi ea", "I will cry indeed?/really?"], ["i le masina", "in the month"], ["e lima,", "by five"], ["ma ou nofo ese,", "and I dwell away"], ["pei ona", "like then"], ["ou faia", "I made"], ["i ia tausaga", "in to year"], ["ua tele?", "great"]]},
  {num:4,words:[["Ona oo mai lea", "and came"], ["o le afioga", "the word (divine)"], ["a Ieova o 'au", "of the LORD of me"], ["ia te au,", "unto me"], ["o loo faapea mai,", "saying from"]]},
  {num:5,words:[["Fai atu", "said to"], ["i tagata uma", "in man all"], ["o le nuu,", "the nation"], ["atoa ma faitaulaga,", "and priest"], ["ia faapea atu,", "to thus"], ["Na outou anapogi", "you (all) to fast"], ["ma fetagisi", "and wept"], ["i le lima", "in the five"], ["ma le fitu", "and seven"], ["o masina", "month"], ["i ia tausaga", "in to year"], ["e fitugafulu,", "to seventy"], ["na outou anapogi ai ea ia te au?", "you (all) to fast indeed?/really? unto me"]]},
  {num:6,words:[["na outou aai foi,", "you (all) city also"], ["ma outou feinu,", "with you feinu"], ["e le o outou", "by the of you (all)"], ["lava ea", "indeed indeed?/really?"], ["sa aai,", "city"], ["o outou foi", "you (all) also"], ["sa feinu?", "feinu"]]},
  {num:7,words:[["E le o upu ea", "by the of word indeed?/really?"], ["ia", "to"], ["sa valaau ai", "called"], ["Ieova", "the LORD"], ["i perofeta anamua,", "in the prophets of old"], ["ina o āina", "so that of āina"], ["o Ierusalema", "Jerusalem"], ["ma", "and"], ["ua manuia,", "peace"], ["mōna aai", "mōna city"], ["ua vagavagai", "to surround"], ["i ai,", "therein"], ["ma le itu", "and the side"], ["i toga", "southward"], ["ma le itu maulalo", "and the side lowly"], ["sa āina ia.", "āina to"]]},
  {num:8,words:[["Ua tŭlei mai foi", "tŭlei from also"], ["le afioga", "the word (divine)"], ["a Ieova ia", "of the LORD to"], ["Sakaria,", "Zechariah"], ["o loo faapea,", "saying"]]},
  {num:9,words:[["Ua faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["o loo faapea mai,", "saying from"], ["Ia faamasino i le", "to judge in the"], ["faamasinoga tonu,", "judgment right"], ["ma ia agalelei", "and to treated well"], ["ma alofa", "and love"], ["o le tasi", "the one"], ["i le tasi;", "in the one"]]},
  {num:10,words:[["aua", "for"], ["le faasaua", "the cruel"], ["i fafine", "in woman"], ["ua oti", "died"], ["a latou tane", "but they man"], ["ma", "and"], ["e ua mātua-oti,", "by mātua-oti"], ["o le tagata ese", "man away"], ["ma le", "and the"], ["ua mativa;", "wanted"], ["aua foi", "for also"], ["le manatunatu", "the meditate"], ["i o outou", "in of you (all)"], ["loto", "heart"], ["i se mea leaga", "in a thing evil"], ["e fai", "to make"], ["e le tasi", "shall not one"], ["i le tasi.", "in the one"]]},
  {num:11,words:[["A", "but"], ["ua latou", "they"], ["le mafafai", "the able"], ["ona uai mai", "and desire from"], ["o latou taliga ,", "they ear"], ["ma", "and"], ["ua liu tua mai", "liu behind from"], ["i latou", "them"], ["ma le finau vale;", "and the contend foolish"], ["ma o latou", "and of they"], ["taliga", "ear"], ["ua faatulituli ia", "faatulituli to"], ["ina ia latou", "so that they"], ["le faalogo.", "the hearken"]]},
  {num:12,words:[["Ua latou faia foi", "they did also"], ["o latou loto", "they heart"], ["ma samira,", "and samira"], ["ina ia le faalogo", "so that the hearken"], ["i latou", "them"], ["i le tulafono", "in the law"], ["ma afioga", "and word (divine)"], ["na auina mai ai", "sent from"], ["e Ieova o 'au", "the LORD me"], ["e lona Agaga", "by his spirit"], ["i perofeta anamua;", "in the prophets of old"], ["o lea", "therefore"], ["na tele ai", "great"], ["le toasa mai ia", "the wrath from to"], ["Ieova o 'au.", "the LORD of me"]]},
  {num:13,words:[["O lenei,", "now"], ["e pei ona", "as"], ["valaau o ia,", "call he"], ["a", "but"], ["e lei faalogologo", "by not listen"], ["mai", "from"], ["i latou;", "them"], ["e faapea foi", "saying also"], ["ona valaau o", "and call of"], ["i latou,", "them"], ["a", "but"], ["e ou te lei faalogo", "to I will not hearken"], ["i ai,", "therein"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of me"]]},
  {num:14,words:[["Na a'u faataapeape ia te", "me faataapeape unto"], ["i latou", "them"], ["i nuu uma", "in nation all"], ["na latou", "they"], ["le iloa;", "the know"], ["sa tuufua", "tuufua"], ["le nuu", "the nation"], ["i o latou", "in of they"], ["tua,", "behind"], ["ua", "ua"], ["le fealuai ai", "the walk about"], ["se tasi;", "a one"], ["na faia e", "made you"], ["i latou", "them"], ["le nuu matagofie", "the nation beautiful"], ["ma mea tuufua.", "and thing tuufua"]]},
];
renderVerseSet(_zec_ch_7_Verses, 'zec-ch7-verses');

var _zec_ch_8_Verses = [
  {num:1,words:[["Ua oo mai foi", "it came to pass from also"], ["le afioga", "the word (divine)"], ["a Ieova o 'au,", "of the LORD of me"], ["o loo faapea mai,", "saying from"]]},
  {num:2,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["Na ou maelega ia", "I maelega to"], ["Siona", "Zion"], ["ma le maelega tele;", "and the maelega great"], ["na ou maelega foi", "I maelega also"], ["ia te ia", "to him"], ["ma le ita tele.", "and the angry great"]]},
  {num:3,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova,", "said the LORD"], ["Ua ou foi atu", "I also"], ["i Siona,", "in Zion"], ["ou te mau foi", "I will opinion also"], ["i totonu o Ierusalema;", "in the midst of Jerusalem"], ["e igoa Ierusalema,", "to name Jerusalem"], ["O le aai", "the city"], ["e faamaoni;", "to faithful"], ["o le mauga foi", "the mountain also"], ["o Ieova o 'au,", "the LORD me"], ["e igoa lea", "to name"], [",", ","], ["O le mauga paia.", "the mountain holy"]]},
  {num:4,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["E toe nonofo toeaina", "to again dwelling elder"], ["ma loomatutua", "and loomatutua"], ["i malae o Ierusalema;", "in the of Jerusalem"], ["o le tagata foi", "man also"], ["ma lona tootoo", "and his staff"], ["i lona lima", "in his five"], ["ona", "and"], ["o le tele", "the great"], ["o latou tausaga.", "they year"]]},
  {num:5,words:[["E tutumu foi", "by tutumu also"], ["malae", "the"], ["o le aai", "the city"], ["i tamaiti", "in tamaiti"], ["ma teineiti o loo taaalo", "and teineiti is (progressive) taaalo"], ["i ona malae.", "in then the"]]},
  {num:6,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["E ui lava", "to although indeed"], ["ina faigata", "so that difficult"], ["i le manatu", "in the thought"], ["o", "o"], ["e ua totoe", "by phiral of foe"], ["o lenei", "now"], ["nuu", "nation"], ["i ia", "in to"], ["ona aso,", "and day"], ["pe faigata ea foi", "whether difficult indeed?/really? also"], ["i lo'u manatu?", "in my thought"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of me"]]},
  {num:7,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au", "me"], ["Faauta,", "behold"], ["ou te faaola", "I will save"], ["i lo'u nuu", "in my nation"], ["nai", "from"], ["le nuu", "the nation"], ["e alu ae ai", "to go up"], ["le la,", "the la"], ["ma le nuu", "and the nation"], ["e alu ifo ai.", "to go down"]]},
  {num:8,words:[["Ou te aumaiina", "I will bring"], ["i latou,", "them"], ["latou te nonofo ai", "they will dwelling"], ["i totonu o Ierusalema;", "in the midst of Jerusalem"], ["e fai foi", "to make also"], ["i latou mo'u nuu,", "them many nation"], ["e fai foi", "to make also"], ["a'u", "me"], ["mo latou Atua", "for they God"], ["i le faamaoni", "in the faithful"], ["ma le amiotonu.", "and the righteous"]]},
  {num:9,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["Ia malolosi o outou", "to mighty of you (all)"], ["lima o", "five of"], ["e faalogologo mai", "to listen from"], ["i nei", "in this"], ["ona po", "and night"], ["i upu nei", "in word this"], ["i fofoga o perofeta,", "in face of prophet"], ["e", "by"], ["na", "na"], ["i ai", "therein"], ["i ona aso", "in then day"], ["na faavaeina ai", "foundation"], ["le fale o Ieova", "the house the LORD"], ["o 'au,", "me"], ["o le malumalu,", "the temple"], ["ina ia faia;", "so that made"]]},
  {num:10,words:[["auā", "for"], ["a o lei oo", "but of not oo"], ["i ia", "in to"], ["ona aso", "and day"], ["sa leai se", "no a"], ["taui", "a reward"], ["o le tagata,", "man"], ["po", "night"], ["o se taui", "a a reward"], ["o le manu;", "the animal"], ["e leai foi", "there is not also"], ["se filemu", "a peace"], ["i le", "in the"], ["na fealuai,", "walked about"], ["ona", "and"], ["o le", "the"], ["na ita mai;", "angry from"], ["na ou faaoso foi", "I food for a journey also"], ["i tagata uma", "in man all"], ["ia feteenai i latou.", "to feteenai them"]]},
  {num:11,words:[["A o nei", "but of this"], ["ona po,", "and night"], ["ou te", "I will"], ["le pei o aso anamua", "the like of day ancient"], ["i", "in"], ["e ua totoe", "by phiral of foe"], ["i le nuu nei,", "in the land this"], ["ua fetalai mai ai", "said"], ["Ieova o 'au.", "the LORD of me"]]},
  {num:12,words:[["Auā e", "for by"], ["i ai", "therein"], ["le fua", "the fruit"], ["o le toalemu;", "the toalemu"], ["e fua mai", "yielding fruit"], ["e le vine", "shall not vine"], ["i ona lava fua,", "in then indeed fruit"], ["e fua mai foi", "yielding fruit also"], ["le laueleele", "the ground"], ["i ona lava fua,", "in then indeed fruit"], ["o le lagi foi", "Heaven also"], ["e totō ifo ai", "by totō down"], ["lona sau;", "his come"], ["ou te avatua foi", "I will given away also"], ["ia mea uma i", "to all things in"], ["e ua totoe", "by phiral of foe"], ["o lenei", "now"], ["nuu", "nation"], ["e fai mā latou.", "to make First person dual exclusive they"]]},
  {num:13,words:[["E pei ona fai outou", "as make you (all)"], ["ma fetuu", "and cursed"], ["i nuu ese,", "in nation away"], ["o oe", "you"], ["le aiga o Iuta,", "the family of Judas"], ["ma oe", "and you"], ["le aiga o Isaraelu,", "the family of Israel"], ["e faapea ona", "saying and"], ["ou faaola ia te outou,", "I save unto you"], ["e fai ai", "to make"], ["outou", "you (all)"], ["ma faamanuia;", "and blessed"], ["aua", "for"], ["le fefefe;", "the afraid"], ["ia malolosi o outou", "to mighty of you (all)"], ["lima.", "five"]]},
  {num:14,words:[["Auā o loo faapea ona", "for saying then"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["E pei ona", "as"], ["ou manatu", "I thought"], ["e faatiga ia te outou,", "to afflict unto you"], ["ina", "so that"], ["ua faaonoono mai", "vex from"], ["o outou tamā", "you (all) father"], ["ia te au,", "unto me"], ["ua fetalai mai ai", "said"], ["Ieova o 'au,", "the LORD of me"], ["ma ou lei salamo ai;", "and I not repent"]]},
  {num:15,words:[["e faapea ona", "saying and"], ["ou toe manatu", "I again thought"], ["i nei", "in this"], ["ona aso", "and day"], ["e agalelei atu", "to treated well"], ["ia Ierusalema", "to Jerusalem"], ["ma le aiga", "and the family"], ["o Iuta;", "Judas"], ["aua tou te matatau.", "for second person plural fear"]]},
  {num:16,words:[["O mea nei tou te faia,", "thing this second person plural made"], ["Ia outou tautala i", "to you (all) speak in"], ["upu moni", "word true"], ["o le tasi", "the one"], ["i le tasi,", "in the one"], ["ma ia faamasino", "and to judge"], ["i le faamaoni", "in the faithful"], ["ma le faamasinoga", "and the judgment"], ["e lelei ai", "to good"], ["i o outou", "in of you (all)"], ["faitotoa.", "door"]]},
  {num:17,words:[["Aua", "for"], ["le manatunatu", "the meditate"], ["i o outou", "in of you (all)"], ["loto", "heart"], ["i se mea leaga", "in a thing evil"], ["e fai", "to make"], ["e le tasi", "shall not one"], ["i le tasi;", "in the one"], ["aua foi", "for also"], ["le fiafia", "the competition"], ["i le tauto pepelo;", "in the to take an oath false"], ["auā o mea uma", "for everything"], ["ia ou te", "to I will"], ["'ino'ino", "hate"], ["i ai,", "therein"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:18,words:[["Ua oo mai foi", "it came to pass from also"], ["le afioga", "the word (divine)"], ["a Ieova o 'au", "of the LORD of me"], ["ia te au,", "unto me"], ["o loo faapea mai,", "saying from"]]},
  {num:19,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["O le anapogi", "the to fast"], ["i le masina", "in the month"], ["e fa,", "by four"], ["ma le anapogi", "and the to fast"], ["i le masina", "in the month"], ["e lima,", "by five"], ["ma le anapogi", "and the to fast"], ["i le masina", "in the month"], ["e fitu,", "by seven"], ["ma le anapogi", "and the to fast"], ["i le masina", "in the month"], ["e sefulu,", "by ten"], ["e fai ma fiafia", "to be competition"], ["ia,", "to"], ["ma olioli,", "and rejoice"], ["ma aso o tausamiga lelei", "and for days feast good"], ["i le aiga", "in the family"], ["o Iuta;", "Judas"], ["a ia outou", "but to you (all)"], ["fiafia", "competition"], ["i le upu moni", "in the word true"], ["ma le manuia.", "and peace"]]},
  {num:20,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["E toe o", "to again of"], ["mai nuu", "from nation"], ["ma tagata o aai", "and people city"], ["e tele;", "to great"]]},
  {num:21,words:[["e o atu tagata", "by of man"], ["o le tasi aai", "the one city"], ["i le tasi aai ,", "in the one city"], ["o loo faapea,", "saying"], ["O mai ia,", "from to"], ["ina tatou", "so that we (incl)"], ["o", "o"], ["e faalaulelei", "to make even"], ["i le finagalo", "in the a chiefs will or desire"], ["o Ieova,", "the LORD"], ["ma saili ia", "and seek to"], ["Ieova o 'au;", "the LORD of me"], ["ou te alu foi", "I will go also"], ["a'u.", "me"]]},
  {num:22,words:[["E o mai foi", "by of from also"], ["nuu e tele,", "nation to great"], ["ma nuu malolosi", "and nation mighty"], ["e saili ia", "to seek to"], ["Ieova o 'au", "the LORD of me"], ["i Ierusalema,", "in Jerusalem"], ["e faalaulelei foi", "to make even also"], ["i le finagalo", "in the a chiefs will or desire"], ["o Ieova.", "the LORD"]]},
  {num:23,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["o 'au,", "me"], ["O ia", "he"], ["ona aso", "and day"], ["e tago atu ai", "to reached out"], ["tagata", "man"], ["e toatinoagafulu ai", "to ten (people)"], ["gagana uma o nuu ese;", "language all of nation away"], ["latou te tago atu", "they will reached out"], ["lava", "indeed"], ["i le pito ofu", "in the edge garment"], ["o le", "the"], ["sa Iutā", "of the clan of Iutā"], ["ma faapea atu,", "and thus"], ["Tatou te o", "we will"], ["ma outou;", "with you"], ["auā", "for"], ["ua matou faalogo,", "we (excl) hearken"], ["o loo ia te outou", "is/are (progressive) unto you"], ["le Atua.", "God"]]},
];
renderVerseSet(_zec_ch_8_Verses, 'zec-ch8-verses');

var _zec_ch_9_Verses = [
  {num:1,words:[["O le avega", "the burden"], ["o le afioga", "the word (divine)"], ["a Ieova", "of the LORD"], ["i le nuu", "in the land"], ["o Hataraka,", "Hataraka"], ["a o Tamaseko", "but of Damascus"], ["o lona malologa lea;", "his a resting place"], ["auā", "for"], ["e uai atu", "to desire"], ["ia Ieova o", "to the LORD of"], ["mata o tagata,", "eye of men"], ["mai itu aiga uma", "from side family all"], ["o Isaraelu.", "Israel"]]},
  {num:2,words:[["O Amato foi", "Amato also"], ["o loo tuaoi ai;", "is (progressive) border"], ["o Turo", "Tyre"], ["ma Saitonu", "and Sidon"], ["e ui lava", "to although indeed"], ["ona sili", "and most"], ["lona poto.", "his wise"]]},
  {num:3,words:[["Ua faia foi", "made also"], ["e Turo", "to Tyre"], ["le 'olo mōna,", "the fortress mōna"], ["ma", "and"], ["ua faafaupue", "faafaupue"], ["le ario", "the silver"], ["e pei o le efu,", "like the dust"], ["ma le auro", "and the gold"], ["e pei o le eleele", "like the earth"], ["i fafo.", "in outside"]]},
  {num:4,words:[["Faauta,", "behold"], ["e tulia o ia", "to driven away he"], ["e le Alii;", "shall not Lord"], ["na te taia foi", "he struck also"], ["lona malosi ia", "his strong to"], ["paū", "paū"], ["i le sami;", "in the sea"], ["e faaumatia foi", "to destroyed also"], ["o ia", "he"], ["i le afi.", "in the fire"]]},
  {num:5,words:[["E vaai atu", "to looked toward"], ["i ai", "therein"], ["Asekelona,", "Asekelona"], ["ona mata'u ai lea;", "and ax then then"], ["o Kasa foi", "Kasa also"], ["e vaai", "to look"], ["i ai", "therein"], ["o ia ,", "he"], ["ona tiga tele ai lea,", "and grieved great then then"], ["atoa ma Ekerona;", "and Ekron"], ["auā", "for"], ["ua faamāina", "faamāina"], ["lona faatuatuaga,", "his something to rely"], ["e fanoia foi", "by fanoia also"], ["le tupu o Kasa,", "the king of Kasa"], ["ma Asekelona", "and Asekelona"], ["e le āina", "by the āina"], ["ia.", "to"]]},
  {num:6,words:[["E mau", "to opinion"], ["le tagata ese", "the man away"], ["i Asetota;", "in Asetota"], ["ou te faaumatia foi", "I will destroyed also"], ["le matagofie o Filisitia.", "the beautiful of Philistine"]]},
  {num:7,words:[["Ou te aveesea", "I will removed away"], ["lona toto ai", "his blood"], ["lona gutu,", "his mouth"], ["atoa ma ana mea", "and his thing"], ["e inosia", "to abominable"], ["nai", "from"], ["le va", "the expanse"], ["o", "o"], ["ona nifo;", "and tooth"], ["e faatoeina foi", "to make again also"], ["o ia lava", "he indeed"], ["mo lo tatou Atua;", "for our God"], ["e fai o ia", "to make he"], ["e pei", "like"], ["se alii ia", "a Lord to"], ["Iuta,", "Judas"], ["a o Ekerona", "but of Ekron"], ["e pei o le", "like the"], ["sa Iepusē o ia.", "of the clan of Jebusites he"]]},
  {num:8,words:[["Ou te to lauapi", "I will to plant a war lod|^ing houfe"], ["i lo'u fale", "in my house"], ["e sioma'i", "by sioma'i"], ["ona", "and"], ["o le itu taua,", "the side precious"], ["i lo latou alu atu", "than they go away"], ["ma lo latou foi mai;", "and the they return"], ["e le toe alu atu", "shall not again go away"], ["lava lē faasaua", "indeed not cruel"], ["ia te i latou;", "unto them"], ["auā o lenei,", "for now"], ["ua vaavaai o'u lava", "watched my indeed"], ["mata.", "eye"]]},
  {num:9,words:[["Ia e matuā", "to to exceedingly"], ["fiafia o oe", "competition of you"], ["le tama fafine", "the child woman"], ["a Siona;", "of Zion"], ["ia alaga fiafia", "to cry competition"], ["o oe", "you"], ["le tama fafine", "the child woman"], ["a Ierusalema;", "of Jerusalem"], ["faauta,", "behold"], ["o le a alu atu", "what go away"], ["lou Tupu ia te oe;", "your king unto you"], ["o ia", "he"], ["o le amiotonu", "the righteous"], ["ma le faaola;", "and the save"], ["e agamalu o ia,", "to meek he"], ["o loo tietie", "is (progressive) ride"], ["i le asini,", "in the donkey"], ["o le tamai asini foi.", "the son donkey also"]]},
  {num:10,words:[["Ou te faaumatia", "I will destroyed"], ["le kariota", "the chariot"], ["i Efaraima,", "in Ephraim"], ["ma le solofanua", "and the horse"], ["i Ierusalema,", "in Jerusalem"], ["e faaumatia foi", "to destroyed also"], ["le aufana", "the bow"], ["o le taua;", "the precious"], ["na te tautala foi", "he spoke also"], ["i le leleiga", "in the leleiga"], ["i nuu ese;", "in nation away"], ["o lana pule", "his rule"], ["e pau mai", "to fall from"], ["i le sami", "in the sea"], ["e oo atu", "it shall come to pass"], ["i le sami,", "in the sea"], ["e pau mai", "to fall from"], ["i le vaitafe", "in the river"], ["e oo", "it shall come to pass"], ["i tuluiga", "in anointing"], ["o le lalolagi.", "the earth"]]},
  {num:11,words:[["O oe foi,", "you also"], ["ona", "and"], ["o le toto", "the blood"], ["o lau feagaiga,", "your covenant"], ["ou te tuu atu ai", "I will placed"], ["ou tagata", "I man"], ["ua noanoa", "caliu"], ["e o ese", "by of away"], ["i le lua", "in the two"], ["e le", "by the"], ["i ai", "therein"], ["se vai.", "a water"]]},
  {num:12,words:[["Ina foi mai ia", "so that return to"], ["i le 'olo,", "in the fortress"], ["outou", "you (all)"], ["ua noanoa", "caliu"], ["ua", "ua"], ["i ai", "therein"], ["le faamoemoe;", "the hope"], ["o lenei", "now"], ["lava aso ou te ta'utino atu,", "indeed day I will testify"], ["ou te toe avatu faalua", "I will again give away twice"], ["ia te oe.", "unto you"]]},
  {num:13,words:[["Auā", "for"], ["ua ou lo'ua", "I troublesome"], ["Iuta", "Judas"], ["mo a'u;", "for me"], ["ua ou tuu", "I put"], ["Efaraima", "Ephraim"], ["i le fu'a", "in the fruit"], ["o le aufana;", "the bow"], ["ou te faaoso atu foi", "I will food for a journey also"], ["i ou tagata Siona e,", "in I man Zion by"], ["e tetee atu", "to to refuse"], ["i ou tagata Iavana e;", "in I man Iavana by"], ["ou te faia foi", "I will make also"], ["oe peiseai", "you as if"], ["se pelu", "a sword"], ["a se toa.", "but a heroic"]]},
  {num:14,words:[["E vaaia Ieova", "to seen the LORD"], ["i o latou", "in of they"], ["luga;", "above"], ["e alu atu", "to go away"], ["lana u", "his u"], ["e pei o le uila;", "like the uila"], ["e ili mai le pu", "by ili from the the tail"], ["e le Alii", "shall not Lord"], ["o Ieova;", "the LORD"], ["e alu atu foi", "to go away also"], ["ia", "to"], ["i afā", "in cyclone"], ["o le itu", "the side"], ["i toga.", "southward"]]},
  {num:15,words:[["O Ieova o 'au,", "the LORD me"], ["o ia", "he"], ["na te faamamalu ia te", "he to protect unto"], ["i latou;", "them"], ["latou te aai,", "they will city"], ["ma soli", "and to tread upon"], ["i lalo", "in under"], ["i maa", "in stone"], ["o le maatā;", "the maatā"], ["latou te feinu,", "they will feinu"], ["latou te pisapisaō pei", "they will pisapisaō like"], ["o", "o"], ["e inu uaina;", "to drink wine"], ["e faatumuina", "to filled"], ["i latou,", "them"], ["pei o se ipu,", "like a cup"], ["pei o tulimanu", "like of the corner (as of a"], ["o le fata faitaulaga.", "the altar"]]},
  {num:16,words:[["E faaolaina", "to saved alive"], ["i latou", "them"], ["e Ieova lo latou Atua", "the LORD their God"], ["i lena", "in that"], ["aso;", "day"], ["e pei o le lafu mamoe", "like the herd sheep"], ["lona nuu;", "his nation"], ["auā", "for"], ["e fai", "to make"], ["i latou", "them"], ["ma maa", "and stone"], ["o le palealii;", "the palealii"], ["o loo siitia", "is (progressive) lifted up"], ["i luga", "in above"], ["i latou", "them"], ["i lona laueleele.", "in his ground"]]},
  {num:17,words:[["Auā", "for"], ["ua tele naua", "great exceedingly"], ["lona lelei,", "his good"], ["e tele naua", "to great exceedingly"], ["lona matagofie;", "his beautiful"], ["e faamalosia taulelea", "to strengthened young men"], ["i le saito,", "in the wheat"], ["ma taupou", "and virgin"], ["e faamalosia ia", "to strengthened to"], ["i le uaina.", "in the wine"]]},
];
renderVerseSet(_zec_ch_9_Verses, 'zec-ch9-verses');

var _zec_ch_10_Verses = [
  {num:1,words:[["Ole atu ia outou", "entreat to you (all)"], ["ia Ieova,", "to the LORD"], ["ina ia", "so that"], ["ua", "ua"], ["i ona po", "in then night"], ["o le uaga mulimuli;", "the heavy rain follow after"], ["e faia", "to made"], ["e Ieova uila,", "the LORD uila"], ["ma foaiina atu timuga tetele", "and given timuga great"], ["ia te i latou,", "unto them"], ["o mutia", "the general name for grass"], ["o le fanua", "the land"], ["ia te i latou", "unto them"], ["uma.", "all"]]},
  {num:2,words:[["Auā", "for"], ["ua tautala tupua", "spoke pillar"], ["i mea", "in thing"], ["le aoga,", "the useful"], ["ma", "and"], ["e fai togafiti faataulāitu", "to make heal faataulāitu"], ["ua latou vaaia", "they seen"], ["le pepelo,", "the false"], ["ma latou tala", "and they side"], ["mai miti pepelo,", "from dream false"], ["ma latou faamafanafana fua;", "and they to hearten fruit"], ["o le mea lea", "therefore"], ["ua o ese ai", "of away"], ["i latou pei", "them like"], ["o mamoe", "sheep"], ["sa tigaina", "afflicted"], ["ina", "so that"], ["ua leai se", "there was no"], ["leoleo.", "guard"]]},
  {num:3,words:[["Na tupu", "king"], ["lo'u ita", "my angry"], ["i le au", "in the me"], ["leoleo mamoe;", "shepherd"], ["ou te taui atu foi", "I will a reward also"], ["i 'oti poa;", "in cut captive"], ["auā", "for"], ["ua asiasi mai", "visited (here)"], ["Ieova o 'au", "the LORD of me"], ["i lona lafu", "in his herd"], ["o le aiga", "the family"], ["o Iuta;", "Judas"], ["e faia foi", "to made also"], ["i latou e", "them by"], ["ia pei o", "to like of"], ["lana solofanua matagofie", "his horse beautiful"], ["i le taua.", "in the precious"]]},
  {num:4,words:[["Mai ia te ia", "from him"], ["le tulimanu,", "the the corner (as of a"], ["mai ia te ia", "from him"], ["le fao,", "the to seize"], ["mai ia te ia", "from him"], ["le aufana", "the bow"], ["o le taua,", "the precious"], ["mai ia te ia", "from him"], ["foi", "also"], ["e o atu ai", "by of"], ["faipule uma faatasi.", "a councillor all together"]]},
  {num:5,words:[["Latou te pei", "they will like"], ["o toa,", "heroic"], ["o loo soli", "is (progressive) to tread upon"], ["i le palapala", "in the palapala"], ["i fafo", "in outside"], ["i le taua;", "in the precious"], ["latou te tau foi,", "they will season also"], ["auā e ia te", "for by him"], ["i latou Ieova;", "them the LORD"], ["a", "but"], ["e faamāina ē tietie", "by faamāina who ride"], ["i solofanua.", "in horse"]]},
  {num:6,words:[["Ou te faamalosia", "I will strengthened"], ["le aiga o Iuta,", "the family of Judas"], ["ma le aiga", "and the family"], ["o Iosefa ou te faaolaina lea;", "Joseph I will saved alive"], ["ou te faanofomauina foi", "I will faanofomauina also"], ["i latou,", "them"], ["auā", "for"], ["ua ou alofa mutimutivale", "I mercy"], ["i ai;", "therein"], ["e avea", "to become"], ["i latou,", "them"], ["e peiseai", "to as if"], ["na ou", "I"], ["le lafoaiina", "the forsaken"], ["i latou;", "them"], ["auā", "for"], ["o a'u", "I am"], ["o Ieova lo latou Atua,", "the LORD their God"], ["ou te talia", "I will received"], ["i latou.", "them"]]},
  {num:7,words:[["E pei o le fitafita", "like the policeman"], ["sa Efaraimā,", "of the clan of Efaraimā"], ["e fiafia foi", "to competition also"], ["o latou loto,", "they heart"], ["e pei o", "like"], ["e inu uaina;", "to drink wine"], ["e vaai", "to look"], ["i ai", "therein"], ["a latou fanau", "but they born"], ["ma latou fiafia,", "and they competition"], ["e olioli lava", "to rejoice indeed"], ["o latou loto", "they heart"], ["ia Ieova.", "to the LORD"]]},
  {num:8,words:[["Ou te mapumapu atu", "I will mapumapu"], ["ia te i latou,", "unto them"], ["ma ou faapotopotoina", "and I gathered together"], ["i latou;", "them"], ["auā", "for"], ["ua ou faatauina", "I bought"], ["i latou;", "them"], ["e faatoateleina foi", "to make many also"], ["i latou,", "them"], ["e pei ona", "as"], ["faatoateleina", "make many"], ["i latou anamua;", "them ancient"]]},
  {num:9,words:[["ma ou totōina", "and I planted"], ["i latou", "them"], ["i nuu;", "in nation"], ["a", "but"], ["e manatua a'u", "to remember me"], ["e", "by"], ["i latou", "them"], ["i mea mamao;", "in thing far"], ["latou te ola foi", "they will life also"], ["faatasi ma", "together and"], ["a latou fanau,", "but they born"], ["ma latou toe foi mai.", "and they returned"]]},
  {num:10,words:[["Ou te faafoisia", "I will restored"], ["mai", "from"], ["i latou", "them"], ["nai", "from"], ["le nuu o Aikupito,", "the nation of Egypt"], ["ma ou faapotopotoina", "and I gathered together"], ["i latou mai Asuria;", "them from Assyria"], ["ou te aumaia", "I will bring here"], ["i latou", "them"], ["i le nuu", "in the land"], ["o Kiliata", "Gilead"], ["ma Lepanona,", "and Lebanon"], ["e le maua foi", "shall not received also"], ["se mea latou te nonofo ai", "a thing they will dwelling"], [".", "."]]},
  {num:11,words:[["Na te ui ane", "he although"], ["i le sami", "in the sea"], ["ma le puapuaga;", "and the affliction"], ["na te taia foi", "he struck also"], ["peau", "a wave"], ["o le sami;", "Sea"], ["e faapa'umatuina mea loloto uma", "by faapa'umatuina thing deep all"], ["i le vaitafe;", "in the river"], ["e faamaulaloina foi", "to to be humble also"], ["le faamaualuga o Asuria;", "the exalted of Assyria"], ["o le tootoo foi", "the staff also"], ["o Aikupito", "Egypt"], ["e mavae atu lea.", "to passed"]]},
  {num:12,words:[["Ou te faamalosia", "I will strengthened"], ["i latou ia", "them to"], ["Ieova;", "the LORD"], ["latou te savavali foi", "they will walked also"], ["i lona suafa,", "in his name"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
];
renderVerseSet(_zec_ch_10_Verses, 'zec-ch10-verses');

var _zec_ch_11_Verses = [
  {num:1,words:[["Lepanona e,", "Lebanon by"], ["ina to mai ia", "so that to plant from to"], ["ou puipui,", "I a duor"], ["e susunuina ai", "to burned"], ["i le afi ou arasi.", "in the fire I cedar"]]},
  {num:2,words:[["Ina uio ia", "so that uio to"], ["le perosi e,", "the perosi by"], ["auā", "for"], ["ua paū", "paū"], ["le arasi,", "the cedar"], ["auā", "for"], ["ua fanoia laau", "fanoia tree"], ["sili;", "most"], ["uio ia,", "uio to"], ["aluna o Vasana e,", "aluna of Bashan by"], ["auā", "for"], ["ua paū", "paū"], ["le vao", "the vegetation"], ["na", "na"], ["le masaofia.", "the masaofia"]]},
  {num:3,words:[["O", "O"], ["i ai", "therein"], ["le leo", "the voice"], ["o le uio", "the uio"], ["o leoleo mamoe,", "shepherd"], ["auā", "for"], ["ua faaumatia lo latou", "are destroyed their"], ["matagofie;", "beautiful"], ["o", "o"], ["i ai", "therein"], ["le leo", "the voice"], ["o le fetagisi", "the wept"], ["o leona taanoa,", "lion an animal that is weaned"], ["auā", "for"], ["ua faaumatia", "are destroyed"], ["le matagofie o Ioritana.", "the beautiful of Jordan"]]},
  {num:4,words:[["O loo faapea ona", "saying and"], ["fetalai mai o Ieova", "said the LORD"], ["lo'u Atua,", "my God"], ["Ia e leoleo i le", "to to guard in the"], ["lafu mamoe", "herd sheep"], ["o le a fasia.", "what slaughtered"]]},
  {num:5,words:[["O", "O"], ["e o latou", "by of they"], ["le lafu ,", "the herd"], ["latou te fafasi", "they will slaughter"], ["ia te i latou,", "unto them"], ["a", "but"], ["e le nofo sala ai", "shall not dwell a fine"], ["i latou;", "them"], ["o", "o"], ["e faatau foi", "to buy also"], ["ia te i latou,", "unto them"], ["ua taitasi o", "each of"], ["i latou", "them"], ["ma fai ane,", "and said"], ["Faafetai ia Ieova,", "thank to the LORD"], ["auā", "for"], ["ua faatamaoaigaina a'u;", "made economy me"], ["o latou leoleo mamoe foi,", "they shepherd also"], ["latou te", "they will"], ["le alolofa ia te", "the alolofa unto"], ["i latou.", "them"]]},
  {num:6,words:[["Auā ou te", "for I will"], ["le toe alofa", "the again love"], ["i", "in"], ["e nonofo", "to dwell"], ["i le nuu", "in the land"], ["na,", "na,"], ["ua fetalai mai ai", "said"], ["Ieova;", "the LORD"], ["faauta foi,", "and behold"], ["ou te tuuina atu tagata", "I will give man"], ["o le tasi", "the one"], ["i le lima", "in the five"], ["o le tasi,", "the one"], ["ma le lima", "and five"], ["o lona tupu;", "his king"], ["latou te tu'ipalaina", "they will tu'ipalaina"], ["le nuu,", "the nation"], ["a", "but"], ["e ou te", "to I will"], ["le laveai ia te", "the deliver unto"], ["i latou ai", "them"], ["o latou lima.", "they five"]]},
  {num:7,words:[["Ua ou leoleoina", "I guarded"], ["le lafu mamoe", "the herd sheep"], ["o le a fasia,", "what slaughtered"], ["o le lafu mamoe", "the herd sheep"], ["e matuā malaia;", "to exceedingly disaster"], ["ua ou ave foi", "I took also"], ["ma'u tootoo", "opinion staff"], ["e lua;", "by two"], ["ua ou faaigoaina", "I named"], ["le tasi,", "the one"], ["o Matagofie;", "beautiful"], ["a", "but"], ["o le tasi", "the one"], ["ua ou faaigoaina,", "I named"], ["o Noataga;", "a tie"], ["ona ou leoleo ai lea", "and I guard then then"], ["i le lafu mamoe.", "in the herd sheep"]]},
  {num:8,words:[["Ua ou faaumatia", "I destroyed"], ["leoleo mamoe", "shepherd"], ["e toatolu", "to three (people)"], ["i le masina", "in the month"], ["e tasi;", "by one"], ["ua tiga", "grieved"], ["lo'u loto ia", "my heart to"], ["i latou,", "them"], ["ua 'ino'ino foi", "hated also"], ["o latou loto", "they heart"], ["ia te au.", "unto me"]]},
  {num:9,words:[["Ona ou fai atu ai lea,", "and I said to then then"], ["Ou te", "I will"], ["le leoleo ia te outou;", "the guard unto you"], ["o lē", "not"], ["a mate", "but mate"], ["ina mate ia;", "so that mate to"], ["o lē", "not"], ["a faaumatia,", "but destroyed"], ["ia faaumatia lava ia;", "to destroyed indeed to"], ["a o", "but of"], ["e ua totoe", "by phiral of foe"], ["ia taitasi", "to each"], ["ma 'ai", "and eat"], ["le tino", "the body"], ["o le tasi.", "the one"]]},
  {num:10,words:[["Ona ou tago ai lea", "and I reach then then"], ["i lo'u tootoo,", "in my staff"], ["o Matagofie lea,", "beautiful"], ["ma ou gausia;", "and I gausia"], ["ina ia tatala", "so that open"], ["la'u feagaiga", "my covenant"], ["na matou osia", "we (excl) hewn"], ["ma nuu uma;", "and nation all"]]},
  {num:11,words:[["ona tatalaina ai lea", "and opened then then"], ["i lea", "in"], ["aso;", "day"], ["ona iloa lelei ai lea", "and know good then then"], ["e le lafu mamoe malaia,", "shall not herd sheep disaster"], ["o", "o"], ["e ua usiusitai", "by obeyed"], ["mai ia te au,", "from me"], ["o le afioga", "the word (divine)"], ["lava lea", "indeed"], ["a Ieova.", "of the LORD"]]},
  {num:12,words:[["Ona ou fai atu lea", "and I said to"], ["ia te i latou,", "unto them"], ["Afai", "if"], ["e lelei ia te outou,", "to good unto you"], ["aumaia", "bring here"], ["o lo'u taui;", "my a reward"], ["a", "but"], ["e afai", "to if"], ["e leai,", "there is not"], ["soia;", "stop"], ["ona latou fua mai ai lea", "and they fruit from then then"], ["o lo'u taui,", "my a reward"], ["o tupe", "St. Thomas bean"], ["e fuatolu.", "by fuatolu"]]},
  {num:13,words:[["Ona fetalai mai lea", "and said"], ["o Ieova ia te au,", "the LORD unto me"], ["Ina lafo atu", "so that cloth used as gratuity for a talking chief"], ["ia", "to"], ["i lē fai ipu omea;", "in not make cup mortar"], ["se tau", "a season"], ["e lelei naua,", "to good exceedingly"], ["ua faatusaina ai", "compared"], ["a'u e", "me by"], ["i latou!", "them"], ["Ona ou tago ai lea", "and I reach then then"], ["i tupe", "in St. Thomas bean"], ["e fuatolu,", "by fuatolu"], ["ma ou lafoia atu", "and I lafoia"], ["i le fale", "in the house"], ["o Ieova", "the LORD"], ["i lē fai ipu omea.", "in not make cup mortar"]]},
  {num:14,words:[["Ona ou gausia lea", "and I gausia"], ["o le tasi o'u tootoo,", "the one my staff"], ["o Noataga lea,", "a tie"], ["ina ia ou motusia", "so that I to come in small and"], ["le tauusoga o Iuta", "the tauusoga of Judas"], ["ma Isaraelu.", "and Israel"]]},
  {num:15,words:[["Ua fetalai mai foi", "said also"], ["Ieova ia te au,", "the LORD unto me"], ["Ina", "so that"], ["e toe ave", "to again take"], ["ia", "to"], ["o mea", "thing"], ["a le leoleo mamoe valea;", "but the shepherd foolish"]]},
  {num:16,words:[["auā faauta,", "for behold"], ["o a'u ou te faatuina", "I am I will built"], ["se leoleo mamoe", "a shepherd"], ["i le nuu,", "in the land"], ["na te", "he"], ["le asiasi", "the visit"], ["i", "in"], ["e", "by"], ["a fano;", "but perish"], ["na te", "he"], ["le sailia", "the sought"], ["le", "the"], ["ua sē;", "sē"], ["na te", "he"], ["le fōia", "the fōia"], ["le", "the"], ["ua gau;", "to break"], ["o le", "the"], ["ua tu", "stood"], ["na te", "he"], ["le fagaina;", "the a bay"], ["a", "but"], ["o le tino", "the body"], ["o le", "the"], ["ua peti", "fat"], ["na te 'aina lava", "he edible indeed"], ["lea,", "lea,"], ["mo latou atigivae", "for they atigivae"], ["na te tafa'ieseina.", "he tafa'ieseina"]]},
  {num:17,words:[["Oi talofa", "wo"], ["i le leoleo mamoe", "in the shepherd"], ["le aoga,", "the useful"], ["na te tuua", "he left"], ["le lafu mamoe!", "the herd sheep"], ["e", "by"], ["i ai", "therein"], ["le pelu", "the sword"], ["i lona lima", "in his five"], ["atoa ma lona mata taumatau;", "and his eye right hand"], ["e matuā gase", "to exceedingly gase"], ["lava", "indeed"], ["lona lima,", "his five"], ["ma lona mata taumatau", "and his eye right hand"], ["e matuā puaoa", "to exceedingly misty"], ["lava lea.", "indeed"]]},
];
renderVerseSet(_zec_ch_11_Verses, 'zec-ch11-verses');

var _zec_ch_12_Verses = [
  {num:1,words:[["O le avega", "the burden"], ["o le afioga", "the word (divine)"], ["a Ieova ia", "of the LORD to"], ["Isaraelu;", "Israel"], ["o loo fetalai mai", "is/are (progressive) said"], ["Ieova", "the LORD"], ["le", "the"], ["ua faamafolafola", "to spread out"], ["le lagi,", "the heaven"], ["ma faavaeina", "and foundation"], ["le lalolagi,", "the earth"], ["na ia faia foi", "he made also"], ["le agaga", "the spirit"], ["o le tagata", "man"], ["i totonu ia te ia;", "in inside to him"], ["faauta,", "behold"]]},
  {num:2,words:[["o a'u lava ou te faia Ierusalema", "I am indeed I will make Jerusalem"], ["ma ipu", "and cup"], ["e tautevateva ai", "by tautevateva"], ["nuu uma o vagavagai;", "nation all of to surround"], ["e", "by"], ["i ai", "therein"], ["foi ia Iuta", "also to Judas"], ["pe a vagaia Ierusalema.", "even though / although vagaia Jerusalem"]]},
  {num:3,words:[["O lea", "therefore"], ["aso foi", "day also"], ["ou te fai ai", "I will make"], ["Ierusalema", "Jerusalem"], ["ma maa mamafa", "and stone heavy"], ["i nuu uma;", "in nation all"], ["atoa uma o", "together with all of"], ["e sii", "to lift up"], ["i ai,", "therein"], ["e matuā manunua ai", "to exceedingly manunua"], ["i latou;", "them"], ["a", "but"], ["e faapotopotoina nuu uma lava", "to gathered together nation all indeed"], ["o le lalolagi latou te tau.", "the earth they will season"]]},
  {num:4,words:[["Ua fetalai mai", "said"], ["Ieova,", "the LORD"], ["O le aso", "the day"], ["lava lea", "indeed"], ["ou te taia ai", "I will struck"], ["solofanua uma", "horse all"], ["i le atuatuvale,", "in the to be greatly dis-"], ["ma", "and"], ["e o tietie ai", "by of ride"], ["i le faavalemalosi;", "in the faavalemalosi"], ["a", "but"], ["o le aiga", "the family"], ["o Iuta,", "Judas"], ["ou te vaavaai", "I will watch"], ["lava", "indeed"], ["i ai;", "therein"], ["o solofanua uma", "horse all"], ["a nuu ou te taia", "but nation I will struck"], ["ia", "to"], ["i le tauaso.", "in the a blind man"]]},
  {num:5,words:[["O alii o Iuta latou te faapea", "Lord of Judas they will thus"], ["i o latou", "in of they"], ["loto,", "heart"], ["E fai mo'u malosi", "to make many strong"], ["o", "o"], ["e nonofo", "to dwell"], ["i Ierusalema ia", "in Jerusalem to"], ["Ieova o 'au lo latou Atua.", "the LORD of me their God"]]},
  {num:6,words:[["O le aso lea", "the day"], ["ou te faia ai", "I will make"], ["o alii o Iuta", "Lord of Judas"], ["e pei o le taigaafi", "like the taigaafi"], ["i laau,", "in tree"], ["e pei o le sulu foi", "like the graft also"], ["ua mu", "mu"], ["i le fusi saito;", "in the bind wheat"], ["latou te faaumatia nuu uma", "they will destroyed nation all"], ["e siosio mai", "by siosio from"], ["i le itu taumatau", "on the side right hand"], ["ma le itu tauagavale;", "and the side left"], ["e toe mau foi", "to again opinion also"], ["Ierusalema", "Jerusalem"], ["i lona lava nuu", "in his indeed nation"], ["o Ierusalema.", "Jerusalem"]]},
  {num:7,words:[["E faaolaina foi", "to saved alive also"], ["e Ieova o fale ie", "the LORD house faamaise"], ["o Iuta,", "Judas"], ["e muamua lava,", "to first the beginning indeed"], ["ina ia le faasilisili", "so that the make very much"], ["le viiga", "the praise"], ["o le aiga", "the family"], ["o Tavita,", "David"], ["ma le viiga", "and the praise"], ["o", "o"], ["e nonofo", "to dwell"], ["i Ierusalema ia", "in Jerusalem to"], ["Iuta.", "Judas"]]},
  {num:8,words:[["O lea", "therefore"], ["aso", "day"], ["e faamamalu mai ai", "to to protect from"], ["Ieova", "the LORD"], ["i", "in"], ["e o nonofo", "by of dwelling"], ["i Ierusalema;", "in Jerusalem"], ["o so latou", "so they"], ["ua vaivai", "weak"], ["i lea", "in"], ["aso", "day"], ["e pei o Tavita", "like David"], ["ia;", "to"], ["o le aiga", "the family"], ["o Tavita,", "David"], ["e pei o le Atua", "like the God"], ["ia,", "to"], ["e pei o le agelu", "like the angel"], ["a Ieova", "of the LORD"], ["i o latou", "in of they"], ["luma.", "before"]]},
  {num:9,words:[["O lea", "therefore"], ["aso foi", "day also"], ["ou te saili ai", "I will seek"], ["ia faaumatia nuu", "to destroyed nation"], ["uma lava o", "all indeed of"], ["e o mai", "by of from"], ["e tau", "to season"], ["ma Ierusalema.", "and Jerusalem"]]},
  {num:10,words:[["Ou te liligi ifo", "I will to pour down"], ["i luga", "in above"], ["o le aiga", "the family"], ["o Tavita,", "David"], ["ma luga o", "and above of"], ["e nonofo", "to dwell"], ["i Ierusalema", "in Jerusalem"], ["le agaga", "the spirit"], ["o le alofa tunoa", "the grace"], ["ma talosaga,", "and talosaga"], ["latou te vaavaai", "they will watch"], ["mai ia te au", "from me"], ["na latou tu'ia;", "they tu'ia"], ["latou te tagitu'i foi", "they will tagitu'i also"], ["ia te ia,", "to him"], ["e pei ona", "as"], ["tagitu'i", "tagitu'i"], ["i le atalii", "in the son"], ["e toatasi,", "to one One"], ["ma latou faanoanoa", "and they mourn"], ["ia te ia,", "to him"], ["e pei ona", "as"], ["faanoanoa", "mourn"], ["i le ulumatua.", "in the the first-born"]]},
  {num:11,words:[["O lea", "therefore"], ["aso e tele ai", "day to great"], ["le taufaitagitu'i", "the taufaitagitu'i"], ["i Ierusalema,", "in Jerusalem"], ["e pei o le tagitu'i", "like the tagitu'i"], ["i Atatarimoni", "in Atatarimoni"], ["i le vanu", "in the valley"], ["o Mekito.", "Mekito"]]},
  {num:12,words:[["E taufaitagitu'i", "by taufaitagitu'i"], ["le nuu", "the nation"], ["e tagi", "to cry"], ["a aiga;", "but family"], ["o le aiga", "the family"], ["o", "o"], ["sa Tavitā,", "of the clan of Tavitā"], ["na o", "of"], ["i latou,", "them"], ["ma", "and"], ["a latou avā,", "but they wife"], ["ua", "ua"], ["na o", "of"], ["i latou;", "them"], ["o le aiga", "the family"], ["o", "o"], ["sa Natanā,", "of the clan of Natanā"], ["na o", "of"], ["i latou,", "them"], ["ma", "and"], ["a latou avā,", "but they wife"], ["na o", "of"], ["i latou;", "them"]]},
  {num:13,words:[["o le aiga", "the family"], ["o", "o"], ["sa Levī,", "of the clan of Levi"], ["ua", "ua"], ["na o", "of"], ["i latou,", "them"], ["ma", "and"], ["a latou avā,", "but they wife"], ["na o", "of"], ["i latou;", "them"], ["o le aiga", "the family"], ["o Semi,", "Shimei"], ["na o", "of"], ["i latou,", "them"], ["ma", "and"], ["a latou avā,", "but they wife"], ["na o", "of"], ["i latou.", "them"]]},
  {num:14,words:[["O aiga uma", "family all"], ["o", "o"], ["e totoe,", "to phiral of foe"], ["o aiga taitasi", "family each"], ["na o", "of"], ["i latou,", "them"], ["ma", "and"], ["a latou avā", "but they wife"], ["na o", "of"], ["i latou.", "them"]]},
];
renderVerseSet(_zec_ch_12_Verses, 'zec-ch12-verses');

var _zec_ch_13_Verses = [
  {num:1,words:[["O lea", "therefore"], ["aso e", "day by"], ["i ai", "therein"], ["le vaipuna", "the a fountain"], ["ua suena", "suena"], ["mo le aiga", "for the family"], ["o Tavita", "David"], ["ma", "and"], ["e o nonofo", "by of dwelling"], ["i Ierusalema,", "in Jerusalem"], ["mo le agasala", "for sin"], ["atoa ma mea leaga.", "and thing evil"]]},
  {num:2,words:[["Ua fetalai mai", "said"], ["Ieova o 'au,", "the LORD of me"], ["O lea", "therefore"], ["aso ou te tineia ai", "day I will tineia"], ["igoa o tupua", "name of pillar"], ["i le lalolagi,", "on the earth"], ["e le toe manatua", "shall not again remember"], ["i latou;", "them"], ["atoa foi", "together with also"], ["ma perofeta", "and prophet"], ["ma le agaga leaga,", "and the spirit evil"], ["ou te faate'aeseina", "I will faate'aeseina"], ["ia", "to"], ["i le lalolagi.", "on the earth"]]},
  {num:3,words:[["Afai foi", "if also"], ["e toe vavalo", "to again prophesy"], ["se tasi,", "a one"], ["ona fai atu ai lea", "and said to then then"], ["ia te ia", "to him"], ["o lona tamā", "his father"], ["ma lona tinā", "and his mother"], ["na fanaua mai ai", "born from"], ["o ia,", "he"], ["E te", "by"], ["le ola;", "the life"], ["auā", "for"], ["ua e tala", "you side"], ["pepelo", "false"], ["i le suafa", "in the name"], ["o Ieova;", "the LORD"], ["ona tutu'i ai lea", "and to seize with the claws (ns then then"], ["ia te ia", "to him"], ["e lona tamā", "by his father"], ["ma lona tinā", "and his mother"], ["na fanaua mai ai", "born from"], ["o ia,", "he"], ["pe a vavalo", "even though / although prophesy"], ["mai ai", "from"], ["o ia.", "he"]]},
  {num:4,words:[["O lea", "therefore"], ["aso foi", "day also"], ["e taitasi", "by each"], ["le perofeta", "the prophet"], ["ma mā ai", "and First person dual exclusive"], ["o ia", "he"], ["i lana mea", "in his thing"], ["na vaaia,", "seen"], ["pe a faia", "even though / although made"], ["lana valoaga;", "his a prediction"], ["latou te", "they will"], ["le oofu foi", "the oofu also"], ["i se ofu taufulufulu", "in a garment taufulufulu"], ["e pepelo ai.", "to false"]]},
  {num:5,words:[["E fai mai foi", "to said also"], ["o ia,", "he"], ["Ou te", "I will"], ["le", "the"], ["se perofeta a'u;", "a prophet me"], ["o a'u", "I am"], ["le tagata", "the man"], ["e galue", "to till"], ["i fanua;", "in land"], ["auā", "for"], ["na faapologaina a'u,", "to enslave me"], ["talu", "since"], ["ina ou taulealea.", "so that I young man"]]},
  {num:6,words:[["Ona fai mai lea", "And he said"], ["o se tasi", "a one"], ["ia te ia,", "to him"], ["O", "O"], ["a ea ia", "but indeed?/really? to"], ["manua", "manua"], ["i ou lima?", "in I five"], ["Ona fai atu lea", "And he said"], ["o ia,", "he"], ["O mea ia", "thing to"], ["na manua ai", "manua"], ["a'u", "me"], ["i le fale", "in the house"], ["o a'u uo.", "I am uo"]]},
  {num:7,words:[["Ala mai ia,", "way from to"], ["le pelu e,", "the sword by"], ["i lo'u leoleo mamoe,", "in my shepherd"], ["ma le tagata", "and the man"], ["ma te faatasi ma a'u,", "and together and me"], ["ua fetalai mai ai", "said"], ["Ieova o 'au;", "the LORD of me"], ["ina ta ia", "so that a stroke to"], ["o le leoleo mamoe,", "the shepherd"], ["ona faataapeapeina ai lea", "and scattered then then"], ["o le au", "the me"], ["mamoe;", "sheep"], ["ona faafoi atu lea", "and return back"], ["o lo'u lima", "my five"], ["i", "in"], ["e iti.", "to small"]]},
  {num:8,words:[["Ua fetalai mai", "said"], ["Ieova,", "the LORD"], ["E oo ina vavaeeseina", "it shall come to pass so that cut off"], ["i le nuu uma lava", "in the land all indeed"], ["ona vaega", "and portion"], ["e lua,", "by two"], ["e fano lava", "to perish indeed"], ["ia;", "to"], ["a", "but"], ["e faatotoeina ai", "to make phiral of foe"], ["lona tolu o vaega .", "his three of portion"]]},
  {num:9,words:[["Ou te avane", "I will gave"], ["lona tolu o vaega", "his three of portion"], ["i le afi;", "in the fire"], ["ou te faate'aese ai", "I will faate'aese"], ["le eleele ia te", "the earth unto"], ["i latou,", "them"], ["e pei ona", "as"], ["faate'aeseina ai", "faate'aeseina"], ["le eleele", "the earth"], ["o le ario;", "the silver"], ["ou te totofofoina", "I will totofofoina"], ["i latou,", "them"], ["e pei ona", "as"], ["tofotofoina", "tested"], ["o le auro;", "the gold"], ["e valaau", "to call"], ["i latou", "them"], ["i lo'u igoa;", "in my name"], ["o a'u foi,", "I am also"], ["ou te tali atu ai", "I will respond"], ["ia te i latou;", "unto them"], ["ou te fai ane,", "I will said/spoke"], ["O lo'u nuu", "my nation"], ["lava", "indeed"], ["i latou;", "them"], ["a", "but"], ["e fai mai", "to said"], ["i latou,", "them"], ["O Ieova", "the LORD"], ["o lo'u Atua", "my God"], ["lava o ia.", "indeed he"]]},
];
renderVerseSet(_zec_ch_13_Verses, 'zec-ch13-verses');

var _zec_ch_14_Verses = [
  {num:1,words:[["Faauta,", "behold"], ["o le a oo mai le aso", "what came the day"], ["o Ieova,", "the LORD"], ["e tufaina ai", "to to divide"], ["i totonu ia te oe", "in inside unto you"], ["o lou oa", "your a couple"], ["o le a vetea.", "what vetea"]]},
  {num:2,words:[["Auā ou te faapotopotoina nuu uma", "for I will gathered together nation all"], ["e tau", "to season"], ["ma Ierusalema;", "and Jerusalem"], ["e aea", "by aea"], ["le aai,", "the city"], ["e vetea foi", "by vetea also"], ["fale,", "house"], ["ma fetosoina fafine,", "and fetosoina woman"], ["e ta'ita'i faatagataotauaina", "to lead captivity"], ["le tasi vaega", "the one portion"], ["o le aai;", "the city"], ["a o", "but of"], ["e totoe", "to phiral of foe"], ["o le nuu,", "the nation"], ["e le faate'aeseina", "by the faate'aeseina"], ["i latou", "them"], ["i le aai.", "in the city"]]},
  {num:3,words:[["Ona afio atu lea", "and dwell (respectful)"], ["o Ieova", "the LORD"], ["e tau", "to season"], ["ma ia nuu,", "and to nation"], ["pei o le aso", "like the day"], ["na tau ai", "season"], ["o ia", "he"], ["i le aso", "in the day"], ["o le taua.", "the precious"]]},
  {num:4,words:[["E tu", "to stand"], ["ona aao", "and hand (extended)"], ["i lea", "in"], ["aso", "day"], ["i luga", "in above"], ["o le mauga", "the mountain"], ["o Olive,", "olive"], ["o loo feagai", "is (progressive) opposite"], ["ma Ierusalema", "and Jerusalem"], ["i gagae;", "in gagae"], ["e vaeluaina foi", "by vaeluaina also"], ["le mauga o Olive", "the mountain of olive"], ["i totonu", "in inside"], ["i sasae", "eastward"], ["ma sisifo,", "and westward"], ["o le vanu tele", "the valley great"], ["lava;", "indeed"], ["e te'a atu", "to depart"], ["le tasi itu", "the one side"], ["o le mauga", "the mountain"], ["i le itu", "on the side"], ["i matu,", "northward"], ["ma le tasi", "and the one"], ["ona itu", "and side"], ["i le itu", "on the side"], ["i toga.", "southward"]]},
  {num:5,words:[["Ona outou sosola lea", "and you (all) fled"], ["i le vanu", "in the valley"], ["o", "o"], ["i o'u mauga;", "in my mountain"], ["auā", "for"], ["e pāia Asela", "by pāia Asela"], ["i le vanu", "in the valley"], ["o mauga;", "mountain"], ["tou te sosola foi,", "second person plural fled also"], ["pei ona", "like then"], ["outou sosola", "you (all) fled"], ["i le mafuie", "in the mafuie"], ["i ona po", "in then night"], ["o Usia", "Usia"], ["le tupu o Iuta;", "the king of Judas"], ["e afio mai", "to dwell (respectful) from"], ["lava Ieova", "indeed the LORD"], ["lo'u Atua", "my God"], ["ma le au paia uma faatasi ma oe.", "and the saints all with you"]]},
  {num:6,words:[["E oo lava", "it shall come to pass indeed"], ["i lea", "in"], ["aso,", "day"], ["e le", "by the"], ["i ai", "therein"], ["le malamalama o mea aoga,", "the light thing useful"], ["a", "but"], ["o le pouliuli", "the darkness"], ["lava;", "indeed"]]},
  {num:7,words:[["a", "but"], ["e oo mai le aso,", "it shall come to pass from the day"], ["e tasi lava", "by one indeed"], ["ia,", "to"], ["(ua silafia lava", "knew indeed"], ["e Ieova,)", "the LORD"], ["e le", "by the"], ["o le ao,", "Day"], ["e le", "by the"], ["o le po;", "Night"], ["a", "but"], ["e", "by"], ["a oo", "but oo"], ["i le itu aso afiafi", "on the side day evening"], ["e malamalama ai.", "to light"]]},
  {num:8,words:[["O lea", "therefore"], ["aso foi", "day also"], ["e alu atu ai", "to go away"], ["le vai ola", "the water life"], ["nai Ierusalema", "from Jerusalem"], ["o le tasi", "the one"], ["ona vaega", "and portion"], ["e tafe atu", "to to flow"], ["i le sami", "in the sea"], ["i sasae,", "eastward"], ["a", "but"], ["o le isi", "the other"], ["ona vaega", "and portion"], ["e tafe atu", "to to flow"], ["i le sami", "in the sea"], ["i sisifo;", "westward"], ["o le tausaga vevela", "the year to be hot"], ["ma le tausaga maalili", "and the year maalili"], ["e fai ai", "to make"], ["ia mea .", "to thing"]]},
  {num:9,words:[["E fai foi", "to make also"], ["Ieova", "the LORD"], ["ma Tupu", "and king"], ["i le lalolagi uma lava;", "on the earth all indeed"], ["o lea", "therefore"], ["aso", "day"], ["ua", "ua"], ["na o Ieova ai", "the LORD"], ["lava,", "indeed"], ["ma lona suafa", "and his name"], ["e āu tasi lea.", "by āu one"]]},
  {num:10,words:[["E liua", "to turned into"], ["le nuu uma pei", "the nation all like"], ["o le fanua laugatasi,", "the land plain"], ["e pau mai", "to fall from"], ["i Kepa", "in Kepa"], ["e oo", "it shall come to pass"], ["i Rimoni", "in Rimmon"], ["i le itu", "on the side"], ["i toga o Ierusalema;", "southward Jerusalem"], ["e faaeaina foi", "by faaeaina also"], ["o ia,", "he"], ["ma nofo", "and dwell"], ["i lona lava nuu,", "in his indeed nation"], ["e pau mai", "to fall from"], ["i le faitotoa", "at the door"], ["o Peniamina", "Benjamin"], ["e oo", "it shall come to pass"], ["i le mea", "in the thing"], ["sa", "sa"], ["i ai", "therein"], ["le faitotoa anamua,", "the door ancient"], ["e oo", "it shall come to pass"], ["i le faitotoa", "at the door"], ["o tulimanu;", "the corner (as of a"], ["e pau mai foi", "to fall from also"], ["i le 'olo", "in the fortress"], ["o Hananiali,", "Hananiali"], ["e oo", "it shall come to pass"], ["i le tuugāuaina", "in the tuugāuaina"], ["a le tupu.", "but the king"]]},
  {num:11,words:[["Latou te nonofo ai,", "they will dwelling"], ["e le toe ai", "shall not again"], ["se faafanoga;", "a destruction"], ["e nofo lava Ierusalema", "to dwell indeed Jerusalem"], ["ma le filemu.", "and the peace"]]},
  {num:12,words:[["O lenei", "now"], ["le mala", "the calamity"], ["e taia a'i", "to struck"], ["e Ieova o nuu uma", "the LORD nation all"], ["e tau", "to season"], ["ma Ierusalema;", "and Jerusalem"], ["e lāuvale lava", "by lāuvale indeed"], ["o latou tino,", "they body"], ["a o tutū", "but of stood up"], ["i o latou", "in of they"], ["vae;", "foot"], ["e totō o latou", "by totō of they"], ["mata", "eye"], ["i mea", "in thing"], ["e tutū ai,", "to stood up"], ["ma o latou", "and of they"], ["laulaufaiva", "tongue"], ["e faaumatia ia", "to destroyed to"], ["i o latou", "in of they"], ["gutu.", "mouth"]]},
  {num:13,words:[["O lea", "therefore"], ["aso foi", "day also"], ["e", "by"], ["i ai", "therein"], ["ia te i latou", "unto them"], ["le atuatuvale tele", "the to be greatly dis- great"], ["mai ia Ieova;", "from to the LORD"], ["ona taitasi ai lea", "and each then then"], ["ma tago", "and reach"], ["o le tasi", "the one"], ["i le lima", "in the five"], ["o le tasi;", "the one"], ["e taitasi foi", "by each also"], ["ma sii", "and lift up"], ["i luga o latou", "upon they"], ["lima", "five"], ["o le tasi", "the one"], ["i le tasi.", "in the one"]]},
  {num:14,words:[["O Iuta foi", "Judas also"], ["e 'au", "to me"], ["i laua", "them"], ["ma Ierusalema;", "and Jerusalem"], ["e faaputuina oloa", "to to gather together goods"], ["o nuu uma", "nation all"], ["e ua vagavagai,", "by to surround"], ["o auro,", "gold"], ["ma ario,", "and silver"], ["ma ofu e tele", "and garment to great"], ["lava.", "indeed"]]},
  {num:15,words:[["E faapea foi", "saying also"], ["ona", "and"], ["i ai", "therein"], ["le mala", "the calamity"], ["i le solofanua,", "in the horse"], ["ma le falata,", "and the falata"], ["ma le kamela,", "and the camel"], ["ma le asini,", "and the donkey"], ["atoa ma manu uma", "and animal all"], ["e", "by"], ["i ai", "therein"], ["i ia toagālauapi,", "in to toagālauapi"], ["e tusa ma lenei", "according to this"], ["mala.", "calamity"]]},
  {num:16,words:[["O", "O"], ["e totoe uma lava", "to phiral of foe all indeed"], ["i nuu uma", "in nation all"], ["o", "o"], ["e o mai", "by of from"], ["e tau", "to season"], ["ma Ierusalema,", "and Jerusalem"], ["latou te o ae", "they will go up"], ["lava", "indeed"], ["i lea", "in"], ["tausaga", "year"], ["ma lea", "and"], ["tausaga", "year"], ["e ifo", "by down"], ["i le Tupu,", "in the king"], ["o Ieova o 'au;", "the LORD me"], ["e fai ai", "to make"], ["foi", "also"], ["le tausamiga o fale apitaga.", "the feast of house a tempoiary"]]},
  {num:17,words:[["A", "but"], ["o le", "the"], ["le alu ae ai", "the go up"], ["itu aiga", "side family"], ["o le lalolagi", "the earth"], ["i Ierusalema", "in Jerusalem"], ["e ifo", "by down"], ["i le Tupu,", "in the king"], ["o Ieova o 'au,", "the LORD me"], ["ona leai lea", "and no"], ["o se uaga", "a heavy rain"], ["ia te i latou.", "unto them"]]},
  {num:18,words:[["A", "but"], ["e afai", "to if"], ["e le alu ae", "shall not go up"], ["le itu aiga", "the side family"], ["o Aikupito,", "Egypt"], ["ma latou", "and they"], ["le o mai,", "the of from"], ["e leai foi", "there is not also"], ["se uaga ia te", "a heavy rain unto"], ["i latou;", "them"], ["ona", "and"], ["i ai lea", "therein"], ["o le mala", "the calamity"], ["e taia a'i", "to struck"], ["e Ieova o nuu", "the LORD nation"], ["o", "o"], ["e le o ae", "by the go up"], ["e fai", "to make"], ["le tausamiga o fale apitaga.", "the feast of house a tempoiary"]]},
  {num:19,words:[["O le sala lena", "the a fine that"], ["a Aikupito,", "of Egypt"], ["ma le sala", "and the a fine"], ["a nuu uma,", "but nation all"], ["o", "o"], ["e le o ae", "by the go up"], ["e fai", "to make"], ["le tausamiga o fale apitaga.", "the feast of house a tempoiary"]]},
  {num:20,words:[["O lea", "therefore"], ["aso e", "day by"], ["i ai", "therein"], ["i tagitagi uamea", "in tagitagi iron"], ["o solofanua,", "horse"], ["E paia ia", "to holy to"], ["Ieova ;", "the LORD"], ["o ulo foi", "ulo also"], ["i le fale", "in the house"], ["o Ieova,", "the LORD"], ["e tutusa ia", "to equal to"], ["ma ipu", "and cup"], ["i luma", "in before"], ["o le fata faitaulaga.", "the altar"]]},
  {num:21,words:[["O ulo uma foi", "ulo all also"], ["i Ierusalema", "in Jerusalem"], ["ma Iuta,", "and Judas"], ["e paia lava", "to holy indeed"], ["ia ia Ieova", "to him the LORD"], ["o 'au;", "me"], ["o", "o"], ["i latou uma", "them all"], ["o", "o"], ["e fasi manu,", "to kill animal"], ["latou te o", "they will"], ["mai", "from"], ["ma ave nisi ulo ,", "and take some ulo"], ["ma tunu ai;", "and roast"], ["e le toe", "shall not again"], ["i ai", "therein"], ["lava", "indeed"], ["se", "a"], ["sa Kananā", "of the clan of Canaanites"], ["i le fale", "in the house"], ["o Ieova o 'au", "the LORD me"], ["i lea", "in"], ["aso.", "day"]]},
];
renderVerseSet(_zec_ch_14_Verses, 'zec-ch14-verses');

})();