(function() {
var _zec_ch_1_Verses = [
  {num:1,words:[["O le valuga masina,", "the valuga month"], ["o le lua o tausaga", "the two of year"], ["o Tariu,", "Darius"], ["na tŭlei mai ai le afioga", "tŭlei from the word (divine)"], ["a Ieova ia Sakaria", "of the LORD to Zechariah"], ["le perofeta", "the prophet"], ["le atalii o Parakaio,", "the son of Parakaio"], ["o le atalii ia o Ito,", "the son to of Ito"], ["o loo faapea mai,", "saying from"]]},
  {num:2,words:[["Sa matuā toasa Ieova", "exceedingly wrath the LORD"], ["i o outou tamā.", "in of you (all) father"]]},
  {num:3,words:[["E te fai atu foi ia te i latou,", "by said to also unto them"], ["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["Ia outou foi mai ia te au,", "to you (all) return unto me"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["ona ou foi atu lea", "and I also"], ["ia te outou,", "unto you"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:4,words:[["Aua tou te faapei o outou", "for second person plural like of you (all)"], ["tamā,", "father"], ["o e", "who"], ["na valaauina", "called"], ["e perofeta anamua,", "to the prophets of old"], ["na faapea,", "thus"], ["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["Ina foi mai ia i o outou", "so that return to in of you (all)"], ["ala leaga,", "way evil"], ["ma a outou galuega leaga;", "and but you (all) work evil"], ["a e lei faalogo", "but by not hearken"], ["mai i latou,", "from them"], ["ma lei uai", "and not desire"], ["mai o latou taliga ia te au,", "from of they ear unto me"], ["ua fetalai mai ai Ieova.", "said the LORD"]]},
  {num:5,words:[["O outou tamā po o fea", "you (all) father night of where?/which?"], ["o i ai", "therein"], ["i latou?", "them"], ["o le au perofeta foi,", "the I prophet also"], ["e faavavau ea", "forever to rise (as a diver to the sur-"], ["ona ola o", "and life of"], ["i latou?", "them"]]},
  {num:6,words:[["A e peitai", "but"], ["o a'u upu", "I am word"], ["ma a'u tulafono,", "and I law"], ["na ou poloai atu ai", "I commanded"], ["i a'u auauna", "in I servant"], ["le au perofeta,", "the I prophet"], ["na le maua atu ai ea", "not received to rise (as a diver to the sur-"], ["o outou tamā?", "you (all) father"], ["ona latou foi mai ai lea,", "and they return"], ["ma latou fai mai,", "and they said"], ["E pei ona", "as"], ["finagalo o Ieova o 'au,", "a chiefs will or desire the LORD of I"], ["e fai ia te i matou,", "to make unto in we (excl)"], ["e tusa ma o matou", "according to we (excl)"], ["ala ma a matou", "way and but we (excl)"], ["galuega,", "work"], ["ua faapea lava ona faia e ia ia te i matou.", "and it was so and made by him unto in we (excl)"]]},
  {num:7,words:[["O le aso e luafulu", "the day to twenty"], ["ma le fa,", "and four"], ["o le masina", "the month"], ["e sefulu", "by ten"], ["ma le tasi,", "and the one"], ["o le masina o Sapata lea,", "the month of Zabdi"], ["o le tausaga", "the year"], ["e lua o Tariu,", "by two of Darius"], ["na tŭlei mai ai le afioga", "tŭlei from the word (divine)"], ["a Ieova ia Sakaria", "of the LORD to Zechariah"], ["le perofeta", "the prophet"], ["le atalii o Parakaio,", "the son of Parakaio"], ["o le atalii ia o Ito,", "the son to of Ito"], ["o loo faapea mai,", "saying from"]]},
  {num:8,words:[["Na ou vaai", "I looked"], ["i le po;", "in the night"], ["faauta foi,", "and behold"], ["o le tagata o loo tietie", "man ride"], ["i le solofanua mūmū,", "in the horse mūmū"], ["o loo tu foi o ia i le ulu atasi,", "stand also he in the head atasi"], ["i le paolo;", "in the paolo"], ["o loo", "o loo"], ["i ona tua foi o solofanua mūmū", "in then behind also of horse mūmū"], ["ma e eefu,", "and by eefu"], ["ma e sisina.", "and by sisina"]]},
  {num:9,words:[["Ona ou fai atu lea,", "and I said to"], ["Le alii e,", "the Lord by"], ["o a ea nei mea?", "but to rise (as a diver to the sur- this thing"], ["Ua fai mai ia te au", "said unto me"], ["le agelu", "the angel"], ["na ma tautala,", "and spoke"], ["Ou te faailoa ia te oe", "I revealed unto you"], ["le uiga o nei mea.", "the kind of this thing"]]},
  {num:10,words:[["Ona tali mai lea o le tagata", "and respond from man"], ["sa tu", "stood"], ["i le ulu atasi,", "in the head atasi"], ["ua faapea mai,", "and said"], ["O i latou ia", "them to"], ["ua aauina", "sent"], ["e Ieova e feoai", "the LORD to walk about"], ["i le lalolagi.", "on the earth"]]},
  {num:11,words:[["Ona tali mai lea o", "and respond from of"], ["i latou", "them"], ["i le agelu", "in the angel"], ["a Ieova,", "of the LORD"], ["sa tu", "stood"], ["i le ulu atasi,", "in the head atasi"], ["ua faapea mai,", "and said"], ["Ua matou feoai lava", "we (excl) walked about indeed"], ["i le lalolagi;", "on the earth"], ["faauta foi,", "and behold"], ["o loo nofonofo", "nofonofo"], ["le lalolagi uma,", "the earth all"], ["ua fifilemu lava.", "fifilemu indeed"]]},
  {num:12,words:[["Ona fai atu lea o le agelu", "And he said the angel"], ["a Ieova,", "of the LORD"], ["ua faapea atu,", "and said"], ["Ieova o 'au", "the LORD of I"], ["e,", "by"], ["se'i afea", "a flower put into the hair or when ?"], ["ona e le alofa ia", "and by the love to"], ["Ierusalema,", "Jerusalem"], ["ma aai o Iuta,", "and city of Judas"], ["ua e toasa", "to wrath"], ["i ai", "therein"], ["i ia tausaga", "in to year"], ["e fitugafulu?", "to seventy"]]},
  {num:13,words:[["Ua tali mai Ieova", "responded from the LORD"], ["i le agelu", "in the angel"], ["na ma tautala,", "and spoke"], ["i upu lelei ma upu faamafanafana.", "in word good and word to hearten"]]},
  {num:14,words:[["Ua fai mai foi ia te au", "said also unto me"], ["le agelu", "the angel"], ["na ma tautala,", "and spoke"], ["Ia e alaga,", "to to cry"], ["ia faapea atu,", "to thus"], ["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["Ua ou maelega", "I maelega"], ["ona o Ierusalema", "because of Jerusalem"], ["ma Siona", "and Zion"], ["i le maelega tele.", "in the maelega great"]]},
  {num:15,words:[["Ua ou matuā ita lava", "I exceedingly angry indeed"], ["i nuu ese o e nonofo faafifilemu;", "in nation away who dwelling faafifilemu"], ["auā na itiiti lo'u ita,", "for small my angry"], ["a o", "but of"], ["i latou,", "them"], ["ua latou faateleina", "they multiplied"], ["le malaia.", "the disaster"]]},
  {num:16,words:[["O le mea lea,", "therefore"], ["o loo faapea ona fetalai mai ai o Ieova,", "saying and said the LORD"], ["Ua ou foi atu i Ierusalema", "I also in Jerusalem"], ["ma le alofa;", "and the love"], ["e fai ai lo'u fale,", "to make my house"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["e faataotoina foi le fua", "to lay down also the fruit"], ["i luga o Ierusalema.", "upon Jerusalem"]]},
  {num:17,words:[["Ia e toe alaga,", "to to again cry"], ["ia faapea atu,", "to thus"], ["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["E toe oso", "to again food for a journey"], ["i tua o'u aai", "in behind my city"], ["ona o le manuia;", "because of the peace"], ["e toe faamafanafana Ieova ia", "to again to hearten the LORD to"], ["Siona,", "Zion"], ["na te toe filifili foi ia", "he again chose also to"], ["Ierusalema.", "Jerusalem"]]},
  {num:18,words:[["Ua ou tepa ae foi i luga,", "I looked up also in above"], ["ua ou vaai,", "I saw"], ["faauta,", "behold"], ["o nifo", "tooth"], ["e fa.", "by four"]]},
  {num:19,words:[["Ona ou fai atu lea", "and I said to"], ["i le agelu", "in the angel"], ["na ma tautala,", "and spoke"], ["O a ea ia mea?", "but to rise (as a diver to the sur- to thing"], ["Ua fai mai o ia ia te au,", "said he unto me"], ["O mea ia,", "thing to"], ["o nifo", "tooth"], ["na faataapeapeina ai Iuta,", "scattered Judas"], ["ma Isaraelu,", "and Israel"], ["ma Ierusalema.", "and Jerusalem"]]},
  {num:20,words:[["Ua faaali mai foi e Ieova ia te au", "revealed also the LORD unto me"], ["o tufuga", "master builder"], ["e toafa.", "to four (people)"]]},
  {num:21,words:[["Ona ou fai atu lea,", "and I said to"], ["Ua o mai i latou", "of from them"], ["na e fai", "to made"], ["i ni", "in some"], ["a? Ua tali mai o ia,", "of responded from he"], ["ua faapea mai,", "and said"], ["O nifo ia", "tooth to"], ["na faataapeapeina ai Iuta,", "scattered Judas"], ["ua oo ina leai se tasi", "it came to pass so that no a one"], ["na ea", "to rise (as a diver to the sur-"], ["i luga lona ulu;", "in above his head"], ["a ua o mai i latou", "but of from them"], ["nei e faamatau ia te i latou,", "this to make ax unto them"], ["e lafo", "to cloth used as gratuity for a talking chief"], ["i lalo nifo o nuu ese,", "in under tooth of nation away"], ["e na sii", "by lifted up"], ["i luga lo latou nifo", "in above their tooth"], ["i le laueleele o Iuta", "in the earth Judas"], ["e faataapeapeina ai.", "to scattered"]]},
];
renderVerseSet(_zec_ch_1_Verses, 'zec-ch1-verses');

var _zec_ch_2_Verses = [
  {num:1,words:[["Ua ou tepa ae foi i luga,", "I looked up also in above"], ["ua ou vaai,", "I saw"], ["faauta,", "behold"], ["o le tagata", "man"], ["ma le maea", "and the rope"], ["e fua a'i", "to fruit"], ["i lona lima.", "in his five"]]},
  {num:2,words:[["Ona ou fai atu ai lea,", "and I said to"], ["Po o fea", "night of where?/which?"], ["e te alu", "by go"], ["i ai?", "therein"], ["Ua fai mai o ia ia te au,", "said he unto me"], ["Ou te alu,", "I go"], ["ou te fuatia Ierusalema,", "I weighed Jerusalem"], ["ia iloa", "to know"], ["pe faapefea lona lautele,", "whether how his wide"], ["pe faapefea foi lona umi.", "whether how also his long"]]},
  {num:3,words:[["Faauta foi,", "and behold"], ["ua alu atu le agelu", "went away the angel"], ["na ma tautala;", "and spoke"], ["o le tasi agelu foi", "the one angel also"], ["ua alu ane", "went forth"], ["e faafetaiai ia te ia.", "to meet to him"]]},
  {num:4,words:[["Ua ia fai ane ia te ia,", "to made to him"], ["Momo'e ia,", "lie down to"], ["ina fai atu i lena taulealea,", "so that said to in that young man"], ["ia faapea atu,", "to thus"], ["E āina Ierusalema", "by āina Jerusalem"], ["e oo i faoa aai,", "unto seized captive city"], ["ona o le tele o tagata", "because of the great of men"], ["ma manu e i ai.", "and animal by therein"]]},
  {num:5,words:[["O a'u foi,", "I am also"], ["ua fetalai mai Ieova,", "said the LORD"], ["e fai a'u", "to make I"], ["ma pa afi", "and a wall fire"], ["e siosio a'i,", "by siosio"], ["e fai foi a'u", "to make also I"], ["ma pupula", "and brightness"], ["i totonu ia te ia.", "in inside to him"]]},
  {num:6,words:[["Sole e!", "alofi vae by"], ["sole e!", "alofi vae by"], ["sosola mai ia outou,", "fled from to you (all)"], ["ai le nuu", "the nation"], ["i le itu i matu,", "on the north side"], ["ua fetalai mai ai Ieova;", "said the LORD"], ["auā na ou faataapeape ia te outou,", "for I faataapeape unto you"], ["e pei o matāmatagi", "to like of matāmatagi"], ["e fa,", "by four"], ["ua fetalai mai ai Ieova.", "said the LORD"]]},
  {num:7,words:[["E! Siona e,", "to Zion by"], ["ia e laveai oe", "to to deliver you"], ["ia te oe,", "unto you"], ["o lē nofo faatasi ma le tama fafine", "not dwell together and the child woman"], ["a Papelonia.", "of Babylon"]]},
  {num:8,words:[["Auā o loo faapea ona fetalai mai o Ieova", "for saying then said the LORD"], ["o 'au,", "I"], ["E mulimuli ane", "to follow after"], ["i le mamalu,", "in the glory"], ["ua ia auina", "to sent"], ["mai o a'u", "from I am"], ["i nuu ese", "in nation away"], ["na vetea", "vetea"], ["a outou mea;", "but you (all) thing"], ["auā o lē pai atu ia te outou,", "for of not pie unto you"], ["ua pāia e ia", "pāia by him"], ["le tamatamai mata", "the tamatamai eye"], ["o lona fofoga.", "his face"]]},
  {num:9,words:[["Auā faauta,", "for behold"], ["ou te siisii atu lo'u lima", "I a method of taking fish my five"], ["i luga ia te i latou;", "in above unto them"], ["e fai foi i latou", "to make also them"], ["ma vete", "and plunder"], ["i o latou pologa;", "in of they mouldy"], ["ona outou iloa lea,", "and you (all) know"], ["ua auina mai a'u", "sent from I"], ["e Ieova o 'au.", "the LORD I"]]},
  {num:10,words:[["Le tama fafine", "the child woman"], ["a Siona", "of Zion"], ["e,", "by"], ["ia e alaga,", "to to cry"], ["ma ia olioli;", "and to rejoice"], ["auā faauta,", "for behold"], ["ou te alu atu,", "I go away"], ["ma ou nofo", "and I dwell"], ["i totonu ia te oe,", "in inside unto you"], ["ua fetalai mai ai Ieova.", "said the LORD"]]},
  {num:11,words:[["E faaopoopoina atu nuu ese", "to added nation away"], ["e tele ia Ieova", "to great to the LORD"], ["i lea aso;", "in day"], ["e fai", "to make"], ["i latou mo'u nuu,", "them many nation"], ["ou te nofo foi i totonu", "I dwell also in inside"], ["ia te oe;", "unto you"], ["ona e iloa ai lea", "and to know"], ["ua auina a'u ia te oe", "sent I unto you"], ["e Ieova o 'au.", "the LORD I"]]},
  {num:12,words:[["E maua", "to received"], ["e Ieova o Iuta,", "the LORD Judas"], ["o lona tofi", "his appoint"], ["i le laueleele paia;", "in the earth holy"], ["e toe filifilia foi e ia o Ierusalema.", "to again chosen also by him of Jerusalem"]]},
  {num:13,words:[["Faalologo ia o tagata uma", "to hold one's tongue to of men all"], ["i luma o Ieova;", "before the LORD"], ["auā ua tulai", "for arose up"], ["mai o ia", "from he"], ["nai lona malumalu paia.", "from his temple holy"]]},
];
renderVerseSet(_zec_ch_2_Verses, 'zec-ch2-verses');

var _zec_ch_3_Verses = [
  {num:1,words:[["Ua ia faaali mai foi ia te au", "to revealed also unto me"], ["o Iosua", "Joshua"], ["le faitaulaga sili,", "the priest most"], ["o loo tu", "stand"], ["i luma o le agelu", "before the angel"], ["a Ieova;", "of the LORD"], ["o Satani foi,", "Satan also"], ["o loo tu o ia i lona itu taumatau", "stand he in his side right hand"], ["e tetee atu ia te ia.", "to to refuse to him"]]},
  {num:2,words:[["Ona fetalai atu lea o Ieova ia", "and said to the LORD to"], ["Satani,", "Satan"], ["Ia aoai atu Ieova ia te oe", "to chastise the LORD unto you"], ["Satani,", "Satan"], ["ia aoai atu ia te oe", "to chastise unto you"], ["Ieova,", "the LORD"], ["o le ua filifili", "the chose"], ["i Ierusalema;", "in Jerusalem"], ["e le", "by the"], ["o le motumotu ea lenei", "the motumotu to rise (as a diver to the sur- this"], ["na seia mai le afi?", "until from the fire"]]},
  {num:3,words:[["Ua ofu Iosua", "garment Joshua"], ["i ofu eleelea;", "in garment eleelea"], ["ua tu foi o ia i luma o le agelu.", "stood also he before the angel"]]},
  {num:4,words:[["Ua ia tali atu,", "to responded"], ["ma fetalai atu i", "and said to in"], ["e na tutū", "by stood up"], ["mai i ona luma,", "from before him"], ["o loo faapea,", "saying"], ["Ave ese ia o ofu eleelea", "take away to of garment eleelea"], ["ua ofu ai o ia.", "garment he"], ["Ua ia fetalai atu foi ia te ia,", "and he also said to him"], ["Faauta,", "behold"], ["ua ou aveesea au", "I removed away I"], ["amioletonu i ou luga;", "wickedness in I above"], ["ou te faaofu foi ia te oe", "I make garment also unto you"], ["i le ofu matagofie.", "in the garment beautiful"]]},
  {num:5,words:[["Ona ou fai atu lea,", "and I said to"], ["Ia latou faaee", "to they to place upon"], ["le pulou lelei", "the a covering for the head good"], ["i luga o lona ulu.", "upon his head"], ["Ona latou faaee ai lea o le pulou lelei", "and they to place upon the a covering for the head good"], ["i lona ulu,", "in his head"], ["ma faaofu ia te ia i ofu;", "and make garment to him in garment"], ["o loo tu mai foi le agelu", "stood also the angel"], ["a Ieova.", "of the LORD"]]},
  {num:6,words:[["Ua matuā fai atu le agelu", "exceedingly said to the angel"], ["a Ieova ia Iosua,", "of the LORD to Joshua"], ["o loo faapea,", "saying"]]},
  {num:7,words:[["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["Afai e te savali", "if by walk"], ["i o'u ala,", "in my way"], ["afai foi e te tausiusi", "if also by obey"], ["i a'u sauniga,", "in I preparation"], ["ona e faamasino ai lea", "and to judge"], ["i lo'u fale,", "in my house"], ["ma e leoleo", "and to guard"], ["i o'u lotoā;", "in my court"], ["ou te tuu atu foi ia te oe", "I placed also unto you"], ["ta'ita'i mai ia te i latou", "lead from them"], ["nei o e tutū", "this who stood up"], ["mai.", "from"]]},
  {num:8,words:[["Ia e faalogo", "to to hearken"], ["mai Iosua", "from Joshua"], ["e,", "by"], ["le faitaulaga sili,", "the priest most"], ["o oe", "you"], ["atoa ma", "and"], ["e ua ia te oe,", "by unto you"], ["o e nonofo", "who dwelling"], ["i ou luma;", "before thee"], ["auā e fai ma faailoga nei tagata;", "for to be sign this man"], ["faauta foi,", "and behold"], ["ou te aumaia la'u auauna", "I bring here my servant"], ["o le La laau .", "the La tree"]]},
  {num:9,words:[["Auā faauta,", "for behold"], ["o le maa", "the stone"], ["na ou tuuina atu i luma o Iosua,", "I given before Joshua"], ["e i le maa", "by in the stone"], ["e tasi mata", "by one eye"], ["e fitu;", "by seven"], ["faauta,", "behold"], ["ou te togitogi", "I togitogi"], ["i ai", "therein"], ["ona togitogiga,", "and togitogiga"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["ma ou ave ese", "and I take away"], ["le amioletonu", "the wickedness"], ["a le nuu nei", "but the nation this"], ["i le aso e tasi.", "in the day by one"]]},
  {num:10,words:[["Ua fetalai mai Ieova o 'au,", "said the LORD of I"], ["O lea aso tou te taitasi ai", "therefore day second person plural each"], ["ma valaau", "and call"], ["i lana uo", "in his uo"], ["i lalo o le vine", "under the vine"], ["ma lalo o le mati.", "and under the fig"]]},
  {num:11,words:[["Ua ou fai atu foi ia te ia,", "I said to also to him"], ["o loo faapea,", "saying"], ["O a ea", "but to rise (as a diver to the sur-"], ["na olive", "olive"], ["e lua", "by two"], ["i le itu taumatau", "on the side right hand"], ["o le lamepa,", "the lamp"], ["ma lona itu tauagavale?", "and his side left"]]},
  {num:12,words:[["Ona ou fai atu faalua lea", "and I said to twice"], ["ia te ia,", "to him"], ["O loo 1304", "1304"]]},
];
renderVerseSet(_zec_ch_3_Verses, 'zec-ch3-verses');

var _zec_ch_4_Verses = [
  {num:1,words:[["Ua foi mai le agelu", "returned the angel"], ["na ma tautala,", "and spoke"], ["ua ia fafagu", "to fafagu"], ["mai ia te au,", "from I"], ["e pei o le tagata", "like the man"], ["ua fagua", "fagua"], ["na moe.", "slept"]]},
  {num:2,words:[["Ona fai mai lea o ia ia te au,", "And he said he unto me"], ["O le a ea", "what to rise (as a diver to the sur-"], ["ua e vaaia?", "to seen"], ["Ona ou fai atu lea,", "and I said to"], ["Ua ou iloa,", "I knew"], ["faauta,", "behold"], ["o le lamepa", "the lamp"], ["ua auro atoatoa,", "gold completely"], ["ma lona tuugāsuāuu", "and his tuugāsuāuu"], ["i ona luga,", "in then above"], ["mona tuugālamepa", "to burst forth (as faiai tuugālamepa"], ["e fitu", "by seven"], ["i ona luga,", "in then above"], ["ma ala", "and way"], ["e taifitu", "by taifitu"], ["i tuugālamepa o loo", "in tuugālamepa of"], ["i ona luga;", "in then above"]]},
  {num:3,words:[["ma olive", "and olive"], ["e lua", "by two"], ["i ona tafatafa,", "in then to cut in many places"], ["o le tasi", "the one"], ["i le itu taumatau", "on the side right hand"], ["o le tuugāsuāuu,", "the tuugāsuāuu"], ["ma le tasi", "and the one"], ["i lona itu tauagavale.", "in his side left"]]},
  {num:4,words:[["Ua ou toe fai atu i le agelu", "I again said to in the angel"], ["na ma tautala,", "and spoke"], ["ua faapea atu,", "and said"], ["Le alii e,", "the Lord by"], ["o a ea ia mea?", "but to rise (as a diver to the sur- to thing"]]},
  {num:5,words:[["Ona tali mai lea o le agelu", "and respond from the angel"], ["na ma tautala,", "and spoke"], ["ua faapea mai ia te au,", "and said unto me"], ["E te le iloa ea po", "by the know to rise (as a diver to the sur- night"], ["o a mea nei?", "but thing this"], ["Ona ou fai atu lea,", "and I said to"], ["Le alii e,", "the Lord by"], ["ou te le iloa .", "I the know"]]},
  {num:6,words:[["Ua tali mai o ia,", "responded from he"], ["ua fai mai ia te au,", "said unto me"], ["o loo faapea mai,", "saying from"], ["O le afioga lenei", "the word (divine) this"], ["a Ieova ia Serupapelu,", "of the LORD to Serupapelu"], ["o loo faapea mai,", "saying from"], ["E le", "by the"], ["o le fitafita,", "the policeman"], ["e le", "by the"], ["o le malosi,", "the strong"], ["a o lo'u Agaga,", "but my spirit"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:7,words:[["O ai ea oe", "who you"], ["le mauga tele", "the mountain great"], ["e? e faalaugatasia oe", "by by faalaugatasia you"], ["i luma o Serupapelu;", "before Serupapelu"], ["na te aumaia foi le maa tulimanu aupitoaluga,", "he brought here also the stone the corner (as of a aupitoaluga"], ["o loo alalaga,", "cry out"], ["Le alofa tunoa e!", "grace by"], ["ia ia te ia", "to him to"], ["le alofa tunoa.", "grace"]]},
  {num:8,words:[["Ua oo mai foi ia te au", "it came to pass from also unto me"], ["le afioga", "the word (divine)"], ["a Ieova,", "of the LORD"], ["o loo faapea mai,", "saying from"]]},
  {num:9,words:[["O lima o Serupapelu", "five of Serupapelu"], ["na faavaeina ai le fale nei,", "foundation the house this"], ["o ona lima foi e faauma a'i;", "then five also to finish"], ["e te iloa ai foi,", "by know also"], ["ua auina mai a'u", "sent from I"], ["ia te outou", "unto you"], ["e Ieova o 'au.", "the LORD I"]]},
  {num:10,words:[["Auā po o ai ea", "for night who"], ["ua 'ino'ino", "hated"], ["i le aso o mea iti? Latou te fiafia", "in the day of thing small they competition"], ["ina ua latou vaai", "so that they looked"], ["i le fua faatautau", "in the fruit make to hang up"], ["i le lima o Serupapelu;", "in the five of Serupapelu"], ["o i latou nei", "them this"], ["e fitu,", "by seven"], ["o fofoga o Ieova", "face the LORD"], ["i latou,", "them"], ["o fetaufetuliai", "contend with one another"], ["i le lalolagi uma.", "on the earth all"]]},
  {num:11,words:[["Ua ou fai atu foi ia te ia,", "I said to also to him"], ["o loo faapea,", "saying"], ["O a ea", "but to rise (as a diver to the sur-"], ["na olive", "olive"], ["e lua", "by two"], ["i le itu taumatau", "on the side right hand"], ["o le lamepa,", "the lamp"], ["ma lona itu tauagavale?", "and his side left"]]},
  {num:12,words:[["Ona ou fai atu faalua lea", "and I said to twice"], ["ia te ia,", "to him"], ["o loo faapea atu,", "saying"], ["O a ea magāolive", "but to rise (as a diver to the sur- magāolive"], ["e lua,", "by two"], ["o loo liligi", "to pour"], ["mai ia te i laua", "from them"], ["lava le uu auro", "indeed the oil gold"], ["i ala auro", "in way gold"], ["e lua?", "by two"]]},
  {num:13,words:[["Ona fai mai lea o ia ia te au,", "And he said he unto me"], ["o loo faapea mai,", "saying from"], ["E te le iloa ea po", "by the know to rise (as a diver to the sur- night"], ["o a ia mea?", "but to thing"], ["Ona ou fai atu lea,", "and I said to"], ["Le alii e,", "the Lord by"], ["ou te le iloa .", "I the know"]]},
  {num:14,words:[["Ona fai mai lea o ia.", "And he said he"], ["O tagata faauuina", "of men anointed"], ["i laua nei,", "them this"], ["o loo tutū", "stood up"], ["i luma o le Alii o le lalolagi uma.", "before the Lord the earth all"]]},
];
renderVerseSet(_zec_ch_4_Verses, 'zec-ch4-verses');

var _zec_ch_5_Verses = [
  {num:1,words:[["Ona ou toe tepa ae lea", "and I again looked up"], ["ma ou iloa,", "and I know"], ["faauta,", "behold"], ["o le tusi taai", "the book taai"], ["ua lele.", "flew"]]},
  {num:2,words:[["Ua ia fai mai ia te au,", "he said unto me"], ["O le a ea", "what to rise (as a diver to the sur-"], ["ua e iloa?", "to knew"], ["Ona ou fai atu lea,", "and I said to"], ["Ua ou iloa", "I knew"], ["le tusi taai", "the book taai"], ["ua lele;", "flew"], ["o lona umi,", "his long"], ["o kupita", "cubit"], ["e luafulu,", "to twenty"], ["o lona lau", "his your"], ["e sefulu kupita ia.", "by ten cubit to"]]},
  {num:3,words:[["Ua fai mai o ia ia te au,", "said he unto me"], ["O le faafano lenei", "the to curse this"], ["o le a alu atu i le fogāeleele uma lava;", "what go away the face of all the earth indeed"], ["auā e taitasi uma o e gaoi", "for by each all who to steal"], ["ma tafia o ia", "and tafia he"], ["ai lenei mea ,", "this thing"], ["e pei o le tusi;", "like the book"], ["e taitasi uma foi o e tauto", "by each all also who to take an oath"], ["ma tafia o ia", "and tafia he"], ["ai le mea nei,", "the thing this"], ["e pei", "to like"], ["e le tusi .", "by the book"]]},
  {num:4,words:[["Ua fetalai mai Ieova o 'au,", "said the LORD of I"], ["Ou te aumaia;", "I bring here"], ["e oo atu lava ia i le fale", "it shall come to pass indeed to in the house"], ["o le gaoi,", "the to steal"], ["ma le fale", "and the house"], ["o le ua tauto pepelo", "the to take an oath false"], ["i lo'u igoa;", "in my name"], ["e tumau ai", "to be firm"], ["i totonu o lona fale,", "in the midst of his house"], ["ma faaumatia ai", "and destroyed"], ["ona laau", "and tree"], ["ma ona maa.", "and then stone"]]},
  {num:5,words:[["Ua alu ane foi le agelu", "went forth also the angel"], ["na ma tautala,", "and spoke"], ["ua fai mai o ia ia te au,", "said he unto me"], ["Ia e tepa", "to to to look towards"], ["i luga,", "in above"], ["ma e vaai,", "and to look"], ["po o le a lena", "night will that"], ["o loo alu atu.", "go away"]]},
  {num:6,words:[["Ua ou fai atu,", "I said to"], ["O le a lena?", "what that"], ["Ua fai mai o ia,", "said he"], ["O le efa lena o loo alu atu;", "the ephah that of go away"], ["ua fai mai foi o ia,", "said also he"], ["O lona tino", "his body"], ["mai lena", "from that"], ["i le nuu uma.", "in the land all"]]},
  {num:7,words:[["Faauta foi,", "and behold"], ["o le taleni o pulu", "the talent of latex or milky sap secreted from any plant in general e.g. breadfruit"], ["ua siitia;", "lifted up"], ["o le fafine foi lenei", "the woman also this"], ["o loo nofo", "dwell"], ["i totonu o le efa.", "in the midst of the ephah"]]},
  {num:8,words:[["Ua ia fai mai foi,", "he said also"], ["O le amio leaga lenei;", "the iniquity this"], ["ona ia lafotuina lea o ia i totonu o le efa,", "and to lafotuina he in the midst of the ephah"], ["ma na lafo", "and cloth used as gratuity for a talking chief"], ["le fua pulu", "the fruit latex or milky sap secreted from any plant in general e.g. breadfruit"], ["i le gutu", "in the mouth"], ["o le efa .", "the ephah"]]},
  {num:9,words:[["Ua ou tepa foi i luga,", "I to look towards also in above"], ["ona ou iloa lea,", "and I know"], ["faauta,", "behold"], ["o fafine", "woman"], ["e toalua", "to two (people)"], ["na o atu;", "of"], ["ua i ai foi le matagi", "therein also the wound"], ["i o la apaau;", "in la a wing"], ["auā sa ia te i laua", "for unto them"], ["o apaau,", "a wing"], ["pei o apaau", "like of a wing"], ["o le kasita;", "the kasita"], ["ua la siitia", "la lifted up"], ["le efa", "the ephah"], ["i le va o le lalolagi ma le lagi.", "in the midst of the earth and the heaven"]]},
  {num:10,words:[["Ona ou fai atu lea", "and I said to"], ["i le agelu", "in the angel"], ["na ma tautala,", "and spoke"], ["Po o fea la te ave", "night of where?/which? la take"], ["i ai le efa?", "therein the ephah"]]},
  {num:11,words:[["Ona fai mai lea o ia ia te au,", "And he said he unto me"], ["O le a ave", "what take"], ["ina ia fai", "so that make"], ["se fale mōna", "a house mōna"], ["i le nuu o Senara;", "in the land Senara"], ["e faatu ai,", "to pitch"], ["ma faamau ai", "and establish"], ["i lona lava taele.", "in his indeed taele"]]},
];
renderVerseSet(_zec_ch_5_Verses, 'zec-ch5-verses');

var _zec_ch_6_Verses = [
  {num:1,words:[["Ona ou toe tepa ae lea,", "and I again looked up"], ["ma ou iloa,", "and I know"], ["faauta,", "behold"], ["o kariota", "chariot"], ["e fa,", "by four"], ["ua o atu", "of"], ["nai le va o mauga", "from the space of mountain"], ["e lua;", "by two"], ["o mauga foi,", "mountain also"], ["o mauga 'apa memea ia.", "mountain can scarlet to"]]},
  {num:2,words:[["O i le kariota muamua", "in the chariot first"], ["o solofanua mūmū:", "horse mūmū"], ["o i le lua o kariota", "in the two of chariot"], ["o solofanua uliuli;", "horse uliuli"]]},
  {num:3,words:[["o i le tolu o kariota", "in the three of chariot"], ["o solofanua sisina;", "horse sisina"], ["o i le fa o kariota", "in the four of chariot"], ["o solofanua pulepule", "horse small sheltfish"], ["e malolosi.", "to mighty"]]},
  {num:4,words:[["Ona ou fai atu lea,", "and I said to"], ["ua faapea atu i le agelu", "and said in the angel"], ["na ma tautala,", "and spoke"], ["Le alii e,", "the Lord by"], ["o a ea ia mea?", "but to rise (as a diver to the sur- to thing"]]},
  {num:5,words:[["Ona tali mai lea o le agelu,", "and respond from the angel"], ["ua fai mai ia te au,", "said unto me"], ["O i latou ia o agaga e toafa", "them to of spirit to four (people)"], ["o le lagi,", "Heaven"], ["ua o atu", "of"], ["sa tutū", "stood up"], ["i luma o le Alii o le lalolagi uma.", "before the Lord the earth all"]]},
  {num:6,words:[["O le ua", "the"], ["i ai solofanua uliuli", "therein horse uliuli"], ["e alu atu ia i le nuu", "to go away to in the land"], ["i le itu i matu;", "on the north side"], ["ma ē sisina", "and who sisina"], ["e mulimuli atu i ai;", "to follow after therein"], ["a o e pulepule", "but who small sheltfish"], ["e o atu ia i le nuu", "by of to in the land"], ["i le itu i toga.", "on the south side"]]},
  {num:7,words:[["Ua o atu foi ē malolosi,", "of also who mighty"], ["ua fia o", "wanted to do something of"], ["ina ia feoai", "so that walk about"], ["i le lalolagi.", "on the earth"], ["Ua ia fai atu foi,", "he said to also"], ["O ia,", "he"], ["ina feoai", "so that walk about"], ["i le lalolagi.", "on the earth"], ["Ona feoai lea o", "and walk about of"], ["i latou", "them"], ["i le lalolagi.", "on the earth"]]},
  {num:8,words:[["Ona ia valaau", "and to call"], ["mai lea ia te au,", "from unto me"], ["ma tautala mai ia te au,", "and spoke from I"], ["o loo faapea mai,", "saying from"], ["Vaai ia i", "look to in"], ["e ua o atu i le nuu", "by of in the land"], ["i le itu i matu;", "on the north side"], ["ua maona ai lo'u loto", "to subside my heart"], ["i le nuu", "in the land"], ["i le itu i matu.", "on the north side"]]},
  {num:9,words:[["Ua tŭlei mai foi le afioga", "tŭlei from also the word (divine)"], ["a Ieova ia te au,", "of the LORD unto me"], ["o loo faapea mai;", "saying from"]]},
  {num:10,words:[["Ave ia nisi o", "take to some of"], ["i latou", "them"], ["nai le tafeaga o", "from the exiles in wa^ of"], ["sa Heletaī o", "of the clan of Heletaī of"], ["sa Toviā,", "of the clan of Toviā"], ["atoa ma o", "and"], ["sa Itaiā;", "of the clan of Itaiā"], ["o i latou ia", "them to"], ["na o mai i Papelonia;", "of from in Babylon"], ["e te alu lava oe", "by go indeed you"], ["i lea aso,", "in day"], ["e te ulu atu i le fale", "by head in the house"], ["o Iosia", "Josiah"], ["le atalii o Sefanaia;", "the son of Zephaniah"]]},
  {num:11,words:[["e te avatu foi ario", "by give away also silver"], ["ma auro,", "and gold"], ["ma ia", "and to"], ["e fai a'i pale,", "to make to row"], ["ma faaee ai", "and to place upon"], ["i le ulu o Iosua", "in the head of Joshua"], ["le atalii o Iosataka", "the son of Iosataka"], ["le faitaulaga sili.", "the priest most"]]},
  {num:12,words:[["E te fai atu foi ia te ia,", "by said to also to him"], ["ia faapea,", "to thus"], ["Ua faapea ona fetalai mai o Ieova", "saying and said the LORD"], ["o 'au,", "I"], ["o loo faapea mai,", "saying from"], ["Faauta,", "behold"], ["o le tagata", "man"], ["o le La laau lona igoa;", "the La tree his name"], ["e tupu", "to king"], ["ae o ia ai le mea e pogai", "but he the thing to cause"], ["mai ai;", "from"], ["e faia foi e ia", "to made also by him"], ["le malumalu o Ieova;", "the temple the LORD"]]},
  {num:13,words:[["o ia lava", "he indeed"], ["na te faia le malumalu", "he made the temple"], ["o Ieova;", "the LORD"], ["e ia te ia", "by him to"], ["foi le mamalu,", "also the glory"], ["e tietie foi o ia ma pule i luga o lona nofoālii;", "to ride also he and rule upon his throne"], ["e fai foi o ia ma faitaulaga", "to make also he and priest"], ["i luga o lona nofoālii;", "upon his throne"], ["e i ai foi le pule", "by therein also the rule"], ["o le manuia ia te i laua.", "the peace unto them"]]},
  {num:14,words:[["E i ai foi ia", "by therein also to"], ["pale mo Elemi,", "to row for Elemi"], ["ma Tovia,", "and Tovia"], ["ma Itaia,", "and Itaia"], ["ma Heni", "and Heni"], ["le atalii o Sefanaia,", "the son of Zephaniah"], ["e fai ma faamanatuga", "to be faamanatuga"], ["i le malumalu o Ieova.", "in the temple the LORD"]]},
  {num:15,words:[["O e mamao foi latou te", "who to be far ofl\" also they"], ["o mai e fai", "from to make"], ["le malumalu o Ieova;", "the temple the LORD"], ["ona iloa ai lea e outou,", "and know by you (all)"], ["ua auina mai a'u", "sent from I"], ["ia te outou", "unto you"], ["e Ieova o 'au;", "the LORD I"], ["e oo foi lenei ,", "it shall come to pass also this"], ["pe afai tou te matuā faalogo", "whether if second person plural exceedingly hearken"], ["i le siufofoga o Ieova lo outou Atua.", "in the voice the LORD your God"]]},
];
renderVerseSet(_zec_ch_6_Verses, 'zec-ch6-verses');

var _zec_ch_7_Verses = [
  {num:1,words:[["O le tausaga", "the year"], ["e fa o Tariu", "by four of Darius"], ["le tupu,", "the king"], ["ua tŭlei mai ai le afioga", "tŭlei from the word (divine)"], ["a Ieova ia Sakaria", "of the LORD to Zechariah"], ["i le aso e fa,", "in the day by four"], ["i le iva o masina,", "in the nine of month"], ["o Kiselu lea.", "Kiselu"]]},
  {num:2,words:[["Ua auina atu o Peteli", "sent of Bethel"], ["o Saresa,", "Saresa"], ["ma Rekemeleki,", "and Rekemeleki"], ["ma ona tagata", "and then man"], ["e faalaulelei", "to make even"], ["i le finagalo o Ieova;", "in the a chiefs will or desire the LORD"]]},
  {num:3,words:[["o loo fai mai i faitaulaga", "said in priest"], ["e ua", "by"], ["i ai", "therein"], ["i le fale", "in the house"], ["e Ieova o 'au,", "the LORD I"], ["atoa ma perofeta,", "and prophet"], ["o loo faapea mai,", "saying from"], ["Ou te tagi ea", "I cry to rise (as a diver to the sur-"], ["i le masina", "in the month"], ["e lima,", "by five"], ["ma ou nofo ese,", "and I dwell away"], ["pei ona", "like then"], ["ou faia", "I made"], ["i ia tausaga", "in to year"], ["ua tele?", "great"]]},
  {num:4,words:[["Ona oo mai lea o le afioga", "and came the word (divine)"], ["a Ieova o 'au ia te au,", "of the LORD of I unto me"], ["o loo faapea mai,", "saying from"]]},
  {num:5,words:[["Fai atu i tagata uma", "said to in man all"], ["o le nuu,", "the nation"], ["atoa ma faitaulaga,", "and priest"], ["ia faapea atu,", "to thus"], ["Na outou anapogi", "you (all) to fast"], ["ma fetagisi", "and wept"], ["i le lima", "in the five"], ["ma le fitu o masina", "and seven month"], ["i ia tausaga", "in to year"], ["e fitugafulu,", "to seventy"], ["na outou anapogi ai ea", "you (all) to fast to rise (as a diver to the sur-"], ["ia te au?", "unto me"]]},
  {num:6,words:[["na outou aai foi,", "you (all) city also"], ["ma outou feinu,", "with you feinu"], ["e le o outou", "by the of you (all)"], ["lava ea", "indeed to rise (as a diver to the sur-"], ["sa aai,", "city"], ["o outou foi", "you (all) also"], ["sa feinu?", "feinu"]]},
  {num:7,words:[["E le o upu ea", "by the of word to rise (as a diver to the sur-"], ["ia sa valaau ai Ieova", "to called the LORD"], ["i perofeta anamua,", "in the prophets of old"], ["ina o āina o Ierusalema", "so that of āina of Jerusalem"], ["ma ua manuia,", "and peace"], ["mōna aai", "mōna city"], ["ua vagavagai", "to surround"], ["i ai,", "therein"], ["ma le itu i toga", "and the side southward"], ["ma le itu maulalo", "and the side lowly"], ["sa āina ia.", "āina to"]]},
  {num:8,words:[["Ua tŭlei mai foi le afioga", "tŭlei from also the word (divine)"], ["a Ieova ia Sakaria,", "of the LORD to Zechariah"], ["o loo faapea,", "saying"]]},
  {num:9,words:[["Ua faapea ona fetalai mai o Ieova", "saying and said the LORD"], ["o 'au,", "I"], ["o loo faapea mai,", "saying from"], ["Ia faamasino", "to judge"], ["i le faamasinoga tonu,", "in the judgment right"], ["ma ia agalelei", "and to treated well"], ["ma alofa", "and love"], ["o le tasi", "the one"], ["i le tasi;", "in the one"]]},
  {num:10,words:[["aua le faasaua", "do not cruel"], ["i fafine", "in woman"], ["ua oti", "died"], ["a latou tane ma", "but they man and"], ["e ua mātua-oti,", "by mātua-oti"], ["o le tagata ese", "man away"], ["ma le ua mativa;", "and the wanted"], ["aua foi le manatunatu", "for also the meditate"], ["i o outou loto", "in of you (all) heart"], ["i se mea leaga", "in a thing evil"], ["e fai", "to make"], ["e le tasi", "by the one"], ["i le tasi.", "in the one"]]},
  {num:11,words:[["A ua latou", "but they"], ["le mafafai", "the able"], ["ona uai mai o latou", "and desire from of they"], ["taliga ,", "ear"], ["ma ua liu tua", "and liu behind"], ["mai i latou", "from them"], ["ma le finau vale;", "and the strive foolish"], ["ma o latou taliga", "and of they ear"], ["ua faatulituli ia", "faatulituli to"], ["ina ia latou", "so that they"], ["le faalogo.", "the hearken"]]},
  {num:12,words:[["Ua latou faia foi o latou", "they did also of they"], ["loto ma samira,", "heart and samira"], ["ina ia le faalogo", "so that the hearken"], ["i latou", "them"], ["i le tulafono", "in the law"], ["ma afioga", "and word (divine)"], ["na auina mai ai e Ieova", "sent from the LORD"], ["o 'au", "I"], ["e lona Agaga", "by his spirit"], ["i perofeta anamua;", "in the prophets of old"], ["o lea", "therefore"], ["na tele ai le toasa", "great the wrath"], ["mai ia Ieova o 'au.", "from to the LORD of I"]]},
  {num:13,words:[["O lenei,", "now"], ["e pei ona valaau o ia,", "as call he"], ["a e lei faalogologo", "but by not listen"], ["mai i latou;", "from them"], ["e faapea foi", "saying also"], ["ona valaau o", "and call of"], ["i latou,", "them"], ["a e ou te lei faalogo", "but to I not hearken"], ["i ai,", "therein"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:14,words:[["Na a'u faataapeape ia te i latou", "I faataapeape unto them"], ["i nuu uma", "in nation all"], ["na latou", "they"], ["le iloa;", "the know"], ["sa tuufua", "tuufua"], ["le nuu", "the nation"], ["i o latou tua,", "in of they behind"], ["ua le fealuai ai", "not walk about"], ["se tasi;", "a one"], ["na faia e i latou", "made by them"], ["le nuu matagofie", "the nation beautiful"], ["ma mea tuufua.", "and thing tuufua"]]},
];
renderVerseSet(_zec_ch_7_Verses, 'zec-ch7-verses');

var _zec_ch_8_Verses = [
  {num:1,words:[["Ua oo mai foi le afioga", "it came to pass from also the word (divine)"], ["a Ieova o 'au,", "of the LORD of I"], ["o loo faapea mai,", "saying from"]]},
  {num:2,words:[["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["Na ou maelega ia", "I maelega to"], ["Siona ma le maelega tele;", "Zion and the maelega great"], ["na ou maelega foi ia te ia ma le ita tele.", "I maelega also to him and the angry great"]]},
  {num:3,words:[["O loo faapea ona fetalai mai o Ieova,", "thus saith the LORD"], ["Ua ou foi atu i Siona,", "I also in Zion"], ["ou te mau foi i totonu o Ierusalema;", "I opinion also in the midst of Jerusalem"], ["e igoa Ierusalema,", "to name Jerusalem"], ["O le aai", "the city"], ["e faamaoni;", "to faithful"], ["o le mauga foi o Ieova", "the mountain also the LORD"], ["o 'au,", "I"], ["e igoa lea ,", "to name"], ["O le mauga paia.", "the mountain holy"]]},
  {num:4,words:[["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["E toe nonofo toeaina", "to again dwelling elder"], ["ma loomatutua", "and loomatutua"], ["i malae o Ierusalema;", "in the of Jerusalem"], ["o le tagata foi ma lona tootoo", "man also and his staff"], ["i lona lima", "in his five"], ["ona o le tele o latou", "because of the great of they"], ["tausaga.", "year"]]},
  {num:5,words:[["E tutumu foi malae", "by tutumu also the"], ["o le aai", "the city"], ["i tamaiti", "in tamaiti"], ["ma teineiti o loo taaalo", "and teineiti of taaalo"], ["i ona malae.", "in then the"]]},
  {num:6,words:[["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["E ui lava", "to although indeed"], ["ina faigata", "so that difficult"], ["i le manatu o e ua totoe", "in the thought who phiral of foe"], ["o lenei nuu", "now nation"], ["i ia", "in to"], ["ona aso,", "and day"], ["pe faigata ea foi i lo'u manatu?", "whether difficult to rise (as a diver to the sur- also in my thought"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:7,words:[["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au", "I"], ["Faauta,", "behold"], ["ou te faaola", "I save"], ["i lo'u nuu", "in my nation"], ["nai le nuu", "from the nation"], ["e alu ae ai le la,", "to go up the la"], ["ma le nuu", "and the nation"], ["e alu ifo ai.", "to go down"]]},
  {num:8,words:[["Ou te aumaiina", "I bring"], ["i latou,", "them"], ["latou te nonofo ai", "they dwelling"], ["i totonu o Ierusalema;", "in the midst of Jerusalem"], ["e fai foi i latou", "to make also them"], ["mo'u nuu,", "many nation"], ["e fai foi a'u", "to make also I"], ["mo latou Atua i le faamaoni", "for they God in the faithful"], ["ma le amiotonu.", "and the righteous"]]},
  {num:9,words:[["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["Ia malolosi o outou", "to mighty of you (all)"], ["lima o e faalogologo", "five who listen"], ["mai i nei", "from in this"], ["ona po", "and night"], ["i upu nei", "in word this"], ["i fofoga o perofeta,", "in face of prophet"], ["e na", "by"], ["i ai", "therein"], ["i ona aso", "in then day"], ["na faavaeina ai le fale", "foundation the house"], ["o Ieova o 'au,", "the LORD I"], ["o le malumalu,", "the temple"], ["ina ia faia;", "so that made"]]},
  {num:10,words:[["auā a o lei oo i", "for but of not oo in"], ["ia ona aso", "to then day"], ["sa leai se taui", "no a a reward"], ["o le tagata,", "man"], ["po o se taui", "night a a reward"], ["o le manu;", "the animal"], ["e leai foi", "there is not also"], ["se filemu", "a peace"], ["i le", "in the"], ["na fealuai,", "walked about"], ["ona o le", "because of the"], ["na ita mai;", "angry from"], ["na ou faaoso foi i tagata uma", "I food for a journey also in man all"], ["ia feteenai", "to feteenai"], ["i latou.", "them"]]},
  {num:11,words:[["A o nei", "but of this"], ["ona po,", "and night"], ["ou te le pei o aso anamua", "I the like of day ancient"], ["i e ua totoe", "in by phiral of foe"], ["i le nuu nei,", "in the land this"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au.", "I"]]},
  {num:12,words:[["Auā e i ai le fua", "for by therein the fruit"], ["o le toalemu;", "the toalemu"], ["e fua mai e le vine", "yielding fruit by the vine"], ["i ona lava fua,", "in then indeed fruit"], ["e fua mai foi le laueleele", "yielding fruit also the ground"], ["i ona lava fua,", "in then indeed fruit"], ["o le lagi foi e totō ifo ai lona sau;", "Heaven also by totō down his come"], ["ou te avatua foi ia mea uma", "I given away also to all things"], ["i e ua totoe o lenei nuu", "in by phiral of foe now nation"], ["e fai mā latou.", "to make First person dual exclusive they"]]},
  {num:13,words:[["E pei ona fai outou", "as make you (all)"], ["ma fetuu", "and cursed"], ["i nuu ese,", "in nation away"], ["o oe", "you"], ["le aiga o Iuta,", "the family of Judas"], ["ma oe", "and you"], ["le aiga o Isaraelu,", "the family of Israel"], ["e faapea ona", "saying and"], ["ou faaola ia te outou,", "I save unto you"], ["e fai ai outou", "to make you (all)"], ["ma faamanuia;", "and blessed"], ["aua le fefefe;", "do not afraid"], ["ia malolosi o outou", "to mighty of you (all)"], ["lima.", "five"]]},
  {num:14,words:[["Auā o loo faapea ona fetalai mai o Ieova", "for saying then said the LORD"], ["o 'au,", "I"], ["E pei ona", "as"], ["ou manatu", "I thought"], ["e faatiga ia te outou,", "to afflict unto you"], ["ina ua faaonoono", "so that vex"], ["mai o outou tamā ia te au,", "from of you (all) father unto me"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au,", "I"], ["ma ou lei salamo ai;", "and I not repent"]]},
  {num:15,words:[["e faapea ona", "saying and"], ["ou toe manatu", "I again thought"], ["i nei", "in this"], ["ona aso e agalelei atu ia", "and day to treated well to"], ["Ierusalema ma le aiga o Iuta;", "Jerusalem and the family of Judas"], ["aua tou te matatau.", "for second person plural fear"]]},
  {num:16,words:[["O mea nei tou te faia,", "thing this second person plural made"], ["Ia outou tautala", "to you (all) spoke"], ["i upu moni", "in word true"], ["o le tasi", "the one"], ["i le tasi,", "in the one"], ["ma ia faamasino", "and to judge"], ["i le faamaoni", "in the faithful"], ["ma le faamasinoga", "and the judgment"], ["e lelei ai", "to good"], ["i o outou faitotoa.", "in of you (all) door"]]},
  {num:17,words:[["Aua le manatunatu", "do not meditate"], ["i o outou loto", "in of you (all) heart"], ["i se mea leaga", "in a thing evil"], ["e fai", "to make"], ["e le tasi", "by the one"], ["i le tasi;", "in the one"], ["aua foi le fiafia", "for also the competition"], ["i le tauto pepelo;", "in the to take an oath false"], ["auā o mea uma ia", "for everything to"], ["ou te 'ino'ino", "I hate"], ["i ai,", "therein"], ["ua fetalai mai ai Ieova.", "said the LORD"]]},
  {num:18,words:[["Ua oo mai foi le afioga", "it came to pass from also the word (divine)"], ["a Ieova o 'au ia te au,", "of the LORD of I unto me"], ["o loo faapea mai,", "saying from"]]},
  {num:19,words:[["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["O le anapogi", "the to fast"], ["i le masina", "in the month"], ["e fa,", "by four"], ["ma le anapogi", "and the to fast"], ["i le masina", "in the month"], ["e lima,", "by five"], ["ma le anapogi", "and the to fast"], ["i le masina", "in the month"], ["e fitu,", "by seven"], ["ma le anapogi", "and the to fast"], ["i le masina", "in the month"], ["e sefulu,", "by ten"], ["e fai ma fiafia ia,", "to be competition to"], ["ma olioli,", "and rejoice"], ["ma aso o tausamiga lelei", "and for days feast good"], ["i le aiga o Iuta;", "in the family of Judas"], ["a ia outou fiafia", "but to you (all) competition"], ["i le upu moni", "in the word true"], ["ma le manuia.", "and peace"]]},
  {num:20,words:[["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["E toe o mai nuu", "to again of from nation"], ["ma tagata o aai e tele;", "and people city to great"]]},
  {num:21,words:[["e o atu tagata", "by of man"], ["o le tasi aai", "the one city"], ["i le tasi aai ,", "in the one city"], ["o loo faapea,", "saying"], ["O mai ia,", "from to"], ["ina tatou", "so that we (incl)"], ["o e faalaulelei", "who make even"], ["i le finagalo o Ieova,", "in the a chiefs will or desire the LORD"], ["ma saili ia Ieova o 'au;", "and seek to the LORD of I"], ["ou te alu foi a'u.", "I go also I"]]},
  {num:22,words:[["E o mai foi nuu", "by of from also nation"], ["e tele,", "to great"], ["ma nuu malolosi", "and nation mighty"], ["e saili ia Ieova o 'au", "to seek to the LORD of I"], ["i Ierusalema,", "in Jerusalem"], ["e faalaulelei foi i le finagalo", "to make even also in the a chiefs will or desire"], ["o Ieova.", "the LORD"]]},
  {num:23,words:[["O loo faapea ona fetalai mai o Ieova", "thus saith the LORD"], ["o 'au,", "I"], ["O ia", "he"], ["ona aso e tago atu ai tagata", "and day to reached out man"], ["e toatinoagafulu ai gagana uma", "to ten (people) language all"], ["o nuu ese;", "nation away"], ["latou te tago atu lava", "they reached out indeed"], ["i le pito ofu", "in the edge garment"], ["o le", "the"], ["sa Iutā", "of the clan of Iutā"], ["ma faapea atu,", "and thus"], ["Tatou te o", "we (incl) of"], ["ma outou;", "with you"], ["auā ua matou faalogo,", "for we (excl) hearken"], ["o loo ia te outou", "unto you"], ["le Atua.", "God"]]},
];
renderVerseSet(_zec_ch_8_Verses, 'zec-ch8-verses');

var _zec_ch_9_Verses = [
  {num:1,words:[["O le avega", "the burden"], ["o le afioga", "the word (divine)"], ["a Ieova", "of the LORD"], ["i le nuu o Hataraka,", "in the land Hataraka"], ["a o Tamaseko", "but of Damascus"], ["o lona malologa lea;", "his a resting place"], ["auā e uai atu ia", "for to desire to"], ["Ieova o mata o tagata,", "the LORD of eye of men"], ["mai itu aiga uma o Isaraelu.", "from side family all of Israel"]]},
  {num:2,words:[["O Amato foi o loo tuaoi ai;", "Amato also of border"], ["o Turo", "Tyre"], ["ma Saitonu", "and Sidon"], ["e ui lava ona", "to although indeed then"], ["sili lona poto.", "most his wise"]]},
  {num:3,words:[["Ua faia foi e Turo", "made also to Tyre"], ["le 'olo mōna,", "the fortress mōna"], ["ma ua faafaupue", "and faafaupue"], ["le ario", "the silver"], ["e pei o le efu,", "like the dust"], ["ma le auro", "and the gold"], ["e pei o le eleele", "like the earth"], ["i fafo.", "in outside"]]},
  {num:4,words:[["Faauta,", "behold"], ["e tulia o ia", "to driven away he"], ["e le Alii;", "by the Lord"], ["na te taia foi lona malosi", "he struck also his strong"], ["ia paū", "to paū"], ["i le sami;", "in the sea"], ["e faaumatia foi o ia i le afi.", "to destroyed also he in the fire"]]},
  {num:5,words:[["E vaai atu i ai Asekelona,", "to looked toward therein Asekelona"], ["ona mata'u ai lea;", "and ax"], ["o Kasa foi e vaai", "Kasa also to look"], ["i ai o ia", "therein he"], [",", ","], ["ona tiga tele ai lea,", "and grieved great"], ["atoa ma Ekerona;", "and Ekron"], ["auā ua faamāina lona faatuatuaga,", "for faamāina his something to rely"], ["e fanoia foi le tupu", "by fanoia also the king"], ["o Kasa,", "Kasa"], ["ma Asekelona", "and Asekelona"], ["e le āina ia.", "by the āina to"]]},
  {num:6,words:[["E mau", "to opinion"], ["le tagata ese", "the man away"], ["i Asetota;", "in Asetota"], ["ou te faaumatia foi le matagofie", "I destroyed also the beautiful"], ["o Filisitia.", "Philistine"]]},
  {num:7,words:[["Ou te aveesea lona toto ai lona gutu,", "I removed away his blood his mouth"], ["atoa ma ana mea e inosia", "and his thing to abominable"], ["nai le va o ona nifo;", "from the space of then tooth"], ["e faatoeina foi o ia lava", "to make again also he indeed"], ["mo lo tatou Atua;", "for our God"], ["e fai o ia", "to make he"], ["e pei", "to like"], ["se alii ia Iuta,", "a Lord to Judas"], ["a o Ekerona", "but of Ekron"], ["e pei o le", "like the"], ["sa Iepusē o ia.", "of the clan of Jebusites he"]]},
  {num:8,words:[["Ou te to lauapi", "I to plant a war lod|^ing houfe"], ["i lo'u fale", "in my house"], ["e sioma'i", "by sioma'i"], ["ona o le itu taua,", "because of the side precious"], ["i lo latou alu atu", "in the they go away"], ["ma lo latou foi mai;", "and the they return"], ["e le toe alu atu", "by the again go away"], ["lava lē faasaua ia te i latou;", "indeed not cruel unto them"], ["auā o lenei,", "for now"], ["ua vaavaai o'u lava mata.", "watched my indeed eye"]]},
  {num:9,words:[["Ia e matuā fiafia o oe", "to to exceedingly competition of you"], ["le tama fafine", "the child woman"], ["a Siona;", "of Zion"], ["ia alaga fiafia o oe", "to cry competition of you"], ["le tama fafine", "the child woman"], ["a Ierusalema;", "of Jerusalem"], ["faauta,", "behold"], ["o le a alu atu lou Tupu", "what go away your king"], ["ia te oe;", "unto you"], ["o ia o le amiotonu", "he the righteous"], ["ma le faaola;", "and the save"], ["e agamalu o ia,", "to meek he"], ["o loo tietie", "ride"], ["i le asini,", "in the donkey"], ["o le tamai asini foi.", "the son donkey also"]]},
  {num:10,words:[["Ou te faaumatia", "I destroyed"], ["le kariota", "the chariot"], ["i Efaraima,", "in Ephraim"], ["ma le solofanua", "and the horse"], ["i Ierusalema,", "in Jerusalem"], ["e faaumatia foi le aufana", "to destroyed also the bow"], ["o le taua;", "the precious"], ["na te tautala foi i le leleiga", "he spoke also in the leleiga"], ["i nuu ese;", "in nation away"], ["o lana pule", "his rule"], ["e pau mai i le sami", "to fall from in the sea"], ["e oo atu i le sami,", "it shall come to pass in the sea"], ["e pau mai i le vaitafe", "to fall from in the river"], ["e oo i tuluiga", "unto anointing"], ["o le lalolagi.", "the earth"]]},
  {num:11,words:[["O oe foi,", "you also"], ["ona o le toto o lau feagaiga,", "because of the blood of your covenant"], ["ou te tuu atu ai ou tagata", "I placed I man"], ["ua noanoa", "caliu"], ["e o ese", "by of away"], ["i le lua", "in the two"], ["e le", "by the"], ["i ai", "therein"], ["se vai.", "a water"]]},
  {num:12,words:[["Ina foi mai ia i le 'olo,", "so that return to in the fortress"], ["outou ua noanoa", "you (all) caliu"], ["ua i ai le faamoemoe;", "therein the hoped"], ["o lenei lava aso ou te ta'utino atu,", "now indeed day I to hang near the body"], ["ou te toe avatu faalua", "I again give away twice"], ["ia te oe.", "unto you"]]},
  {num:13,words:[["Auā ua ou lo'ua Iuta", "for I troublesome Judas"], ["mo a'u;", "for I"], ["ua ou tuu Efaraima", "I put Ephraim"], ["i le fu'a", "in the fruit"], ["o le aufana;", "the bow"], ["ou te faaoso atu foi i ou tagata Siona", "I food for a journey also in I man Zion"], ["e,", "by"], ["e tetee atu i ou tagata Iavana", "to to refuse in I man Iavana"], ["e;", "by"], ["ou te faia foi oe", "I will make also you"], ["peiseai se pelu", "as if a a sword"], ["a se toa.", "but a heroic"]]},
  {num:14,words:[["E vaaia Ieova", "to seen the LORD"], ["i o latou luga;", "in of they above"], ["e alu atu lana u", "to go away his u"], ["e pei o le uila;", "like the uila"], ["e ili mai le pu", "by ili from the the tail"], ["e le Alii o Ieova;", "by the Lord the LORD"], ["e alu atu foi ia i afā", "to go away also to in cyclone"], ["o le itu i toga.", "the side southward"]]},
  {num:15,words:[["O Ieova o 'au,", "the LORD I"], ["o ia", "he"], ["na te faamamalu ia te i latou;", "he to protect unto them"], ["latou te aai,", "they city"], ["ma soli", "and to tread upon"], ["i lalo", "in under"], ["i maa", "in stone"], ["o le maatā;", "the maatā"], ["latou te feinu,", "they feinu"], ["latou te pisapisaō pei o e inu uaina;", "they pisapisaō like who drink wine"], ["e faatumuina", "to filled"], ["i latou,", "them"], ["pei o se ipu,", "like a cup"], ["pei o tulimanu", "like of the corner (as of a"], ["o le fata faitaulaga.", "the altar"]]},
  {num:16,words:[["E faaolaina", "to saved alive"], ["i latou", "them"], ["e Ieova lo latou Atua i lena aso;", "the LORD their God in that day"], ["e pei o le lafu mamoe lona nuu;", "like the herd sheep his nation"], ["auā e fai", "for to make"], ["i latou", "them"], ["ma maa", "and stone"], ["o le palealii;", "the palealii"], ["o loo siitia", "lifted up"], ["i luga", "in above"], ["i latou", "them"], ["i lona laueleele.", "in his ground"]]},
  {num:17,words:[["Auā ua tele naua lona lelei,", "for great exceedingly his good"], ["e tele naua lona matagofie;", "to great exceedingly his beautiful"], ["e faamalosia taulelea", "to strengthened young men"], ["i le saito,", "in the wheat"], ["ma taupou", "and virgin"], ["e faamalosia ia i le uaina.", "to strengthened to in the wine"]]},
];
renderVerseSet(_zec_ch_9_Verses, 'zec-ch9-verses');

var _zec_ch_10_Verses = [
  {num:1,words:[["Ole atu ia outou", "entreat to you (all)"], ["ia Ieova,", "to the LORD"], ["ina ia", "so that"], ["ua i ona po", "in then night"], ["o le uaga mulimuli;", "the heavy rain follow after"], ["e faia e Ieova uila,", "to made the LORD uila"], ["ma foaiina atu timuga tetele", "and given timuga great"], ["ia te i latou,", "unto them"], ["o mutia", "the general name for grass"], ["o le fanua ia te i latou", "the land unto them"], ["uma.", "all"]]},
  {num:2,words:[["Auā ua tautala tupua", "for spoke pillar"], ["i mea", "in thing"], ["le aoga,", "the useful"], ["ma e fai togafiti faataulāitu", "and to make heal faataulāitu"], ["ua latou vaaia", "they seen"], ["le pepelo,", "the false"], ["ma latou tala", "and they side"], ["mai miti pepelo,", "from dream false"], ["ma latou faamafanafana fua;", "and they to hearten fruit"], ["o le mea lea", "therefore"], ["ua o ese ai", "of away"], ["i latou pei o mamoe", "them like of sheep"], ["sa tigaina", "afflicted"], ["ina ua leai se leoleo.", "so that there was no guard"]]},
  {num:3,words:[["Na tupu lo'u ita", "king my angry"], ["i le au leoleo mamoe;", "in the I shepherd"], ["ou te taui atu foi i 'oti poa;", "I a reward also in cut captive"], ["auā ua asiasi mai Ieova", "for visited (here) the LORD"], ["o 'au", "I"], ["i lona lafu", "in his herd"], ["o le aiga o Iuta;", "the family of Judas"], ["e faia foi i latou", "to made also them"], ["e ia pei o lana solofanua matagofie", "by him like of his horse beautiful"], ["i le taua.", "in the precious"]]},
  {num:4,words:[["Mai ia te ia", "from him"], ["le tulimanu,", "the the corner (as of a"], ["mai ia te ia", "from him"], ["le fao,", "the to seize"], ["mai ia te ia", "from him"], ["le aufana", "the bow"], ["o le taua,", "the precious"], ["mai ia te ia", "from him"], ["foi e o atu ai faipule uma faatasi.", "also by of a councillor all together"]]},
  {num:5,words:[["Latou te pei o toa,", "they like of heroic"], ["o loo soli", "to tread upon"], ["i le palapala", "in the palapala"], ["i fafo", "in outside"], ["i le taua;", "in the precious"], ["latou te tau foi,", "they season also"], ["auā e ia te i latou", "for by him them"], ["Ieova;", "the LORD"], ["a e faamāina ē tietie", "but by faamāina who ride"], ["i solofanua.", "in horse"]]},
  {num:6,words:[["Ou te faamalosia", "I strengthened"], ["le aiga o Iuta,", "the family of Judas"], ["ma le aiga o Iosefa ou te faaolaina lea;", "and the family of Joseph I saved alive"], ["ou te faanofomauina foi i latou,", "I faanofomauina also them"], ["auā ua ou alofa mutimutivale", "for I mercy"], ["i ai;", "therein"], ["e avea", "to become"], ["i latou,", "them"], ["e peiseai", "to as if"], ["na ou", "I"], ["le lafoaiina", "the forsaken"], ["i latou;", "them"], ["auā o a'u", "for I am"], ["o Ieova lo latou Atua,", "the LORD their God"], ["ou te talia", "I received"], ["i latou.", "them"]]},
  {num:7,words:[["E pei o le fitafita", "like the policeman"], ["sa Efaraimā,", "of the clan of Efaraimā"], ["e fiafia foi o latou", "to competition also of they"], ["loto,", "heart"], ["e pei o e inu uaina;", "to like who drink wine"], ["e vaai", "to look"], ["i ai", "therein"], ["a latou fanau", "but they born"], ["ma latou fiafia,", "and they competition"], ["e olioli lava o latou", "to rejoice indeed of they"], ["loto ia Ieova.", "heart to the LORD"]]},
  {num:8,words:[["Ou te mapumapu atu ia te i latou,", "I mapumapu unto them"], ["ma ou faapotopotoina", "and I gathered together"], ["i latou;", "them"], ["auā ua ou faatauina", "for I bought"], ["i latou;", "them"], ["e faatoateleina foi i latou,", "to make many also them"], ["e pei ona", "as"], ["faatoateleina i latou anamua;", "make many them ancient"]]},
  {num:9,words:[["ma ou totōina", "and I totōina"], ["i latou", "them"], ["i nuu;", "in nation"], ["a e manatua a'u", "but to remember I"], ["e i latou", "by them"], ["i mea mamao;", "in thing to be far ofl\""], ["latou te ola foi faatasi ma a latou", "they life also together and but they"], ["fanau,", "born"], ["ma latou toe foi mai.", "and they returned"]]},
  {num:10,words:[["Ou te faafoisia", "I restored"], ["mai i latou", "from them"], ["nai le nuu o Aikupito,", "from the nation of Egypt"], ["ma ou faapotopotoina", "and I gathered together"], ["i latou mai Asuria;", "them from Assyria"], ["ou te aumaia", "I bring here"], ["i latou", "them"], ["i le nuu o Kiliata", "in the land Gilead"], ["ma Lepanona,", "and Lebanon"], ["e le maua foi", "by the received also"], ["se mea latou te nonofo ai .", "a thing they dwelling"]]},
  {num:11,words:[["Na te ui ane", "he although"], ["i le sami", "in the sea"], ["ma le puapuaga;", "and the affliction"], ["na te taia foi peau", "he struck also a wave"], ["o le sami;", "Sea"], ["e faapa'umatuina mea loloto uma", "by faapa'umatuina thing deep all"], ["i le vaitafe;", "in the river"], ["e faamaulaloina foi le faamaualuga", "to to be humble also the exalted"], ["o Asuria;", "Assyria"], ["o le tootoo foi o Aikupito", "the staff also of Egypt"], ["e mavae atu lea.", "to passed"]]},
  {num:12,words:[["Ou te faamalosia", "I strengthened"], ["i latou ia Ieova;", "them to the LORD"], ["latou te savavali foi i lona suafa,", "they walked also in his name"], ["ua fetalai mai ai Ieova.", "said the LORD"]]},
];
renderVerseSet(_zec_ch_10_Verses, 'zec-ch10-verses');

var _zec_ch_11_Verses = [
  {num:1,words:[["Lepanona e,", "Lebanon by"], ["ina to mai ia", "so that to plant from to"], ["ou puipui,", "I a duor"], ["e susunuina ai", "to burned"], ["i le afi ou arasi.", "in the fire I cedar"]]},
  {num:2,words:[["Ina uio ia le perosi", "so that uio to the perosi"], ["e,", "by"], ["auā ua paū", "for paū"], ["le arasi,", "the cedar"], ["auā ua fanoia laau sili;", "for fanoia tree most"], ["uio ia,", "uio to"], ["aluna o Vasana", "aluna of Bashan"], ["e,", "by"], ["auā ua paū", "for paū"], ["le vao", "the vegetation"], ["na le masaofia.", "the masaofia"]]},
  {num:3,words:[["O i ai le leo", "therein the voice"], ["o le uio o leoleo mamoe,", "the uio of shepherd"], ["auā ua faaumatia lo latou matagofie;", "for destroyed their beautiful"], ["o i ai le leo", "therein the voice"], ["o le fetagisi o leona taanoa,", "the wept of lion an animal that is weaned"], ["auā ua faaumatia", "for destroyed"], ["le matagofie o Ioritana.", "the beautiful of Jordan"]]},
  {num:4,words:[["O loo faapea ona fetalai mai o Ieova lo'u Atua,", "thus saith the LORD my God"], ["Ia e leoleo", "to to guard"], ["i le lafu mamoe o le a fasia.", "in the herd sheep will struck"]]},
  {num:5,words:[["O e o latou", "who they"], ["le lafu ,", "the herd"], ["latou te fafasi ia te i latou,", "they fafasi unto them"], ["a e le nofo sala ai", "but by the dwell a fine"], ["i latou;", "them"], ["o e faatau foi ia te i latou,", "who buy also unto them"], ["ua taitasi o", "each of"], ["i latou", "them"], ["ma fai ane,", "and make"], ["Faafetai ia Ieova,", "thank to the LORD"], ["auā ua faatamaoaigaina a'u;", "for made economy I"], ["o latou leoleo mamoe foi,", "they shepherd also"], ["latou te le alolofa ia te i latou.", "they the alolofa unto them"]]},
  {num:6,words:[["Auā ou te le toe alofa", "for I the again love"], ["i e nonofo", "in to dwell"], ["i le nuu", "in the land"], ["na,", "na,"], ["ua fetalai mai ai Ieova;", "said the LORD"], ["faauta foi,", "and behold"], ["ou te tuuina atu tagata", "I will give man"], ["o le tasi", "the one"], ["i le lima", "in the five"], ["o le tasi,", "the one"], ["ma le lima", "and five"], ["o lona tupu;", "his king"], ["latou te tu'ipalaina", "they tu'ipalaina"], ["le nuu,", "the nation"], ["a e ou te le laveai", "but to I the deliver"], ["ia te i latou", "unto them"], ["ai o latou lima.", "of they five"]]},
  {num:7,words:[["Ua ou leoleoina", "I guarded"], ["le lafu mamoe o le a fasia,", "the herd sheep will struck"], ["o le lafu mamoe", "the herd sheep"], ["e matuā malaia;", "to exceedingly disaster"], ["ua ou ave foi ma'u tootoo", "I took also opinion staff"], ["e lua;", "by two"], ["ua ou faaigoaina", "I named"], ["le tasi,", "the one"], ["o Matagofie;", "beautiful"], ["a o le tasi", "but the one"], ["ua ou faaigoaina,", "I named"], ["o Noataga;", "a tie"], ["ona ou leoleo ai lea", "and I guard"], ["i le lafu mamoe.", "in the herd sheep"]]},
  {num:8,words:[["Ua ou faaumatia leoleo mamoe", "I destroyed shepherd"], ["e toatolu", "to three (people)"], ["i le masina", "in the month"], ["e tasi;", "by one"], ["ua tiga lo'u loto ia i latou,", "grieved my heart to them"], ["ua 'ino'ino foi o latou", "hated also of they"], ["loto ia te au.", "heart unto me"]]},
  {num:9,words:[["Ona ou fai atu ai lea,", "and I said to"], ["Ou te le leoleo ia te outou;", "I the guard unto you"], ["o lē", "not"], ["a mate", "but mate"], ["ina mate ia;", "so that mate to"], ["o lē", "not"], ["a faaumatia,", "but destroyed"], ["ia faaumatia lava ia;", "to destroyed indeed to"], ["a o e ua totoe", "but who phiral of foe"], ["ia taitasi ma 'ai", "to each and eat"], ["le tino", "the body"], ["o le tasi.", "the one"]]},
  {num:10,words:[["Ona ou tago ai lea", "and I reach"], ["i lo'u tootoo,", "in my staff"], ["o Matagofie lea,", "beautiful"], ["ma ou gausia;", "and I gausia"], ["ina ia tatala la'u feagaiga", "so that open my covenant"], ["na matou osia", "we (excl) hewn"], ["ma nuu uma;", "and nation all"]]},
  {num:11,words:[["ona tatalaina ai lea", "and opened"], ["i lea aso;", "in day"], ["ona iloa lelei ai lea e le lafu mamoe malaia,", "and know good by the herd sheep disaster"], ["o e ua usiusitai", "who obeyed"], ["mai ia te au,", "from I"], ["o le afioga lava lea", "the word (divine) indeed"], ["a Ieova.", "of the LORD"]]},
  {num:12,words:[["Ona ou fai atu lea", "and I said to"], ["ia te i latou,", "unto them"], ["Afai e lelei ia te outou,", "if to good unto you"], ["aumaia o lo'u taui;", "bring here my a reward"], ["a e afai", "but to if"], ["e leai,", "there is not"], ["soia;", "stop"], ["ona latou fua mai ai lea o lo'u taui,", "and they fruit from my a reward"], ["o tupe", "St. Thomas bean"], ["e fuatolu.", "by fuatolu"]]},
  {num:13,words:[["Ona fetalai mai lea o Ieova ia te au,", "and said the LORD unto me"], ["Ina lafo atu ia i lē fai ipu omea;", "so that cloth used as gratuity for a talking chief to in not make cup mortar"], ["se tau", "a season"], ["e lelei naua,", "to good exceedingly"], ["ua faatusaina ai a'u", "compared I"], ["e i latou!", "by them"], ["Ona ou tago ai lea", "and I reach"], ["i tupe", "in St. Thomas bean"], ["e fuatolu,", "by fuatolu"], ["ma ou lafoia atu i le fale", "and I lafoia in the house"], ["o Ieova", "the LORD"], ["i lē fai ipu omea.", "in not make cup mortar"]]},
  {num:14,words:[["Ona ou gausia lea o le tasi o'u tootoo,", "and I gausia the one my staff"], ["o Noataga lea,", "a tie"], ["ina ia ou motusia", "so that I to come in small and"], ["le tauusoga o Iuta", "the tauusoga of Judas"], ["ma Isaraelu.", "and Israel"]]},
  {num:15,words:[["Ua fetalai mai foi Ieova ia te au,", "said also the LORD unto me"], ["Ina e toe ave ia o mea", "so that to again take to of thing"], ["a le leoleo mamoe valea;", "but the shepherd foolish"]]},
  {num:16,words:[["auā faauta,", "for behold"], ["o a'u ou te faatuina", "I am I built"], ["se leoleo mamoe", "a shepherd"], ["i le nuu,", "in the land"], ["na te le asiasi", "he the spy out"], ["i e", "in by"], ["a fano;", "but perish"], ["na te le sailia", "he the sought"], ["le ua sē;", "the sē"], ["na te le fōia", "he the fōia"], ["le ua gau;", "the to break"], ["o le ua tu", "the stood"], ["na te le fagaina;", "he the a bay"], ["a o le tino", "but the body"], ["o le ua peti", "the fat"], ["na te 'aina lava lea,", "he edible indeed"], ["mo latou atigivae", "for they atigivae"], ["na te tafa'ieseina.", "he tafa'ieseina"]]},
  {num:17,words:[["Oi talofa", "wo"], ["i le leoleo mamoe", "in the shepherd"], ["le aoga,", "the useful"], ["na te tuua", "he left"], ["le lafu mamoe!", "the herd sheep"], ["e i ai le pelu", "by therein the a sword"], ["i lona lima", "in his five"], ["atoa ma lona mata taumatau;", "and his eye right hand"], ["e matuā gase lava lona lima,", "to exceedingly gase indeed his five"], ["ma lona mata taumatau", "and his eye right hand"], ["e matuā puaoa lava lea.", "to exceedingly misty indeed"]]},
];
renderVerseSet(_zec_ch_11_Verses, 'zec-ch11-verses');

var _zec_ch_12_Verses = [
  {num:1,words:[["O le avega", "the burden"], ["o le afioga", "the word (divine)"], ["a Ieova ia Isaraelu;", "of the LORD to Israel"], ["o loo fetalai mai Ieova le ua faamafolafola", "said the LORD the to spread out"], ["le lagi,", "the heaven"], ["ma faavaeina", "and foundation"], ["le lalolagi,", "the earth"], ["na ia faia foi le agaga o le tagata", "he made also the spirit man"], ["i totonu ia te ia;", "in inside to him"], ["faauta,", "behold"]]},
  {num:2,words:[["o a'u lava ou te faia Ierusalema", "I am indeed I will make Jerusalem"], ["ma ipu", "and cup"], ["e tautevateva ai nuu uma", "by tautevateva nation all"], ["o vagavagai;", "to surround"], ["e i ai foi ia", "by therein also to"], ["Iuta pe a vagaia Ierusalema.", "Judas whether but vagaia Jerusalem"]]},
  {num:3,words:[["O lea aso foi ou te fai ai Ierusalema", "therefore day also I make Jerusalem"], ["ma maa mamafa", "and stone heavy"], ["i nuu uma;", "in nation all"], ["atoa uma o e sii", "together with all who lift up"], ["i ai,", "therein"], ["e matuā manunua ai", "to exceedingly manunua"], ["i latou;", "them"], ["a e faapotopotoina nuu uma lava o le lalolagi latou te tau.", "but to gathered together nation all indeed the earth they season"]]},
  {num:4,words:[["Ua fetalai mai Ieova,", "said the LORD"], ["O le aso lava lea ou te taia ai solofanua uma", "the day indeed I struck horse all"], ["i le atuatuvale,", "in the to be greatly dis-"], ["ma e o tietie ai", "and by of ride"], ["i le faavalemalosi;", "in the faavalemalosi"], ["a o le aiga o Iuta,", "but the family of Judas"], ["ou te vaavaai lava", "I watch indeed"], ["i ai;", "therein"], ["o solofanua uma", "horse all"], ["a nuu ou te taia", "but nation I struck"], ["ia i le tauaso.", "to in the a blind man"]]},
  {num:5,words:[["O alii o Iuta latou te faapea", "Lord of Judas they thus"], ["i o latou loto,", "in of they heart"], ["E fai mo'u malosi o e nonofo", "to make many strong who dwelling"], ["i Ierusalema ia Ieova o 'au lo latou Atua.", "in Jerusalem to the LORD of I their God"]]},
  {num:6,words:[["O le aso lea ou te faia ai o alii o Iuta", "the day I will make of Lord of Judas"], ["e pei o le taigaafi", "like the taigaafi"], ["i laau,", "in tree"], ["e pei o le sulu", "like the graft"], ["foi ua mu", "also mu"], ["i le fusi saito;", "in the bind wheat"], ["latou te faaumatia nuu uma", "they destroyed nation all"], ["e siosio mai i le itu taumatau", "by siosio from on the side right hand"], ["ma le itu tauagavale;", "and the side left"], ["e toe mau foi Ierusalema", "to again opinion also Jerusalem"], ["i lona lava nuu o Ierusalema.", "in his indeed nation of Jerusalem"]]},
  {num:7,words:[["E faaolaina foi e Ieova", "to saved alive also the LORD"], ["o fale ie o Iuta,", "house faamaise of Judas"], ["e muamua lava,", "to first indeed"], ["ina ia le faasilisili", "so that the make very much"], ["le viiga", "the praise"], ["o le aiga o Tavita,", "the family of David"], ["ma le viiga o e nonofo", "and the praise who dwelling"], ["i Ierusalema ia Iuta.", "in Jerusalem to Judas"]]},
  {num:8,words:[["O lea aso e faamamalu", "therefore day to to protect"], ["mai ai Ieova", "from the LORD"], ["i e o nonofo", "in by of dwelling"], ["i Ierusalema;", "in Jerusalem"], ["o so latou", "so they"], ["ua vaivai", "weak"], ["i lea aso e pei o Tavita", "in day to like of David"], ["ia;", "to"], ["o le aiga o Tavita,", "the family of David"], ["e pei o le Atua", "like the God"], ["ia,", "to"], ["e pei o le agelu", "like the angel"], ["a Ieova", "of the LORD"], ["i o latou luma.", "before them"]]},
  {num:9,words:[["O lea aso foi ou te saili ai ia", "therefore day also I seek to"], ["faaumatia nuu uma lava o e", "destroyed nation all indeed who"], ["o mai e tau", "from to season"], ["ma Ierusalema.", "and Jerusalem"]]},
  {num:10,words:[["Ou te liligi ifo", "I to pour down"], ["i luga o le aiga o Tavita,", "upon the family of David"], ["ma luga o e nonofo", "and above who dwelling"], ["i Ierusalema", "in Jerusalem"], ["le agaga o le alofa tunoa ma talosaga,", "the spirit the grace and talosaga"], ["latou te vaavaai", "they watch"], ["mai ia te au", "from I"], ["na latou tu'ia;", "they tu'ia"], ["latou te tagitu'i foi ia te ia,", "they tagitu'i also to him"], ["e pei ona", "as"], ["tagitu'i i le atalii", "tagitu'i in the son"], ["e toatasi,", "to one One"], ["ma latou faanoanoa ia te ia,", "and they mourn to him"], ["e pei ona", "as"], ["faanoanoa i le ulumatua.", "mourn in the the first-born"]]},
  {num:11,words:[["O lea aso e tele ai le taufaitagitu'i", "therefore day to great the taufaitagitu'i"], ["i Ierusalema,", "in Jerusalem"], ["e pei o le tagitu'i", "like the tagitu'i"], ["i Atatarimoni", "in Atatarimoni"], ["i le vanu o Mekito.", "in the valley of Mekito"]]},
  {num:12,words:[["E taufaitagitu'i", "by taufaitagitu'i"], ["le nuu", "the nation"], ["e tagi", "to cry"], ["a aiga;", "but family"], ["o le aiga o", "the family of"], ["sa Tavitā,", "of the clan of Tavitā"], ["na o", "of"], ["i latou,", "them"], ["ma a latou avā,", "and but they wife"], ["ua na o", "of"], ["i latou;", "them"], ["o le aiga o", "the family of"], ["sa Natanā,", "of the clan of Natanā"], ["na o", "of"], ["i latou,", "them"], ["ma a latou avā,", "and but they wife"], ["na o", "of"], ["i latou;", "them"]]},
  {num:13,words:[["o le aiga o", "the family of"], ["sa Levī,", "of the clan of Levi"], ["ua na o", "of"], ["i latou,", "them"], ["ma a latou avā,", "and but they wife"], ["na o", "of"], ["i latou;", "them"], ["o le aiga o Semi,", "the family of Shimei"], ["na o", "of"], ["i latou,", "them"], ["ma a latou avā,", "and but they wife"], ["na o", "of"], ["i latou.", "them"]]},
  {num:14,words:[["O aiga uma o e totoe,", "family all who phiral of foe"], ["o aiga taitasi", "family each"], ["na o", "of"], ["i latou,", "them"], ["ma a latou avā", "and but they wife"], ["na o", "of"], ["i latou.", "them"]]},
];
renderVerseSet(_zec_ch_12_Verses, 'zec-ch12-verses');

var _zec_ch_13_Verses = [
  {num:1,words:[["O lea aso e i ai le vaipuna", "therefore day by therein the a fountain"], ["ua suena", "suena"], ["mo le aiga o Tavita", "for the family of David"], ["ma e o nonofo", "and by of dwelling"], ["i Ierusalema,", "in Jerusalem"], ["mo le agasala", "for sin"], ["atoa ma mea leaga.", "and thing evil"]]},
  {num:2,words:[["Ua fetalai mai Ieova o 'au,", "said the LORD of I"], ["O lea aso ou te tineia ai igoa", "therefore day I tineia name"], ["o tupua", "pillar"], ["i le lalolagi,", "on the earth"], ["e le toe manatua", "by the again remember"], ["i latou;", "them"], ["atoa foi ma perofeta", "together with also and prophet"], ["ma le agaga leaga,", "and the spirit evil"], ["ou te faate'aeseina ia i le lalolagi.", "I faate'aeseina to on the earth"]]},
  {num:3,words:[["Afai foi e toe vavalo", "if also to again prophesy"], ["se tasi,", "a one"], ["ona fai atu ai lea", "and said to"], ["ia te ia o lona tamā", "to him his father"], ["ma lona tinā", "and his mother"], ["na fanaua mai ai o ia,", "born from he"], ["E te le ola;", "by the life"], ["auā ua", "for"], ["e tala pepelo", "to side false"], ["i le suafa o Ieova;", "in the name the LORD"], ["ona tutu'i ai lea ia te ia", "and to seize with the claws (ns to him"], ["e lona tamā", "by his father"], ["ma lona tinā", "and his mother"], ["na fanaua mai ai o ia,", "born from he"], ["pe a vavalo", "whether but prophesy"], ["mai ai o ia.", "from he"]]},
  {num:4,words:[["O lea aso foi e taitasi", "therefore day also by each"], ["le perofeta", "the prophet"], ["ma mā ai o ia i lana mea", "and First person dual exclusive he in his thing"], ["na vaaia,", "seen"], ["pe a faia lana valoaga;", "whether but made his a prediction"], ["latou te le oofu foi i se ofu taufulufulu", "they the oofu also in a garment taufulufulu"], ["e pepelo ai.", "to false"]]},
  {num:5,words:[["E fai mai foi o ia,", "to said also he"], ["Ou te le", "I the"], ["se perofeta a'u;", "a prophet I"], ["o a'u", "I am"], ["le tagata", "the man"], ["e galue", "to till"], ["i fanua;", "in land"], ["auā na faapologaina a'u,", "for to enslave I"], ["talu ina ou taulealea.", "since so that I young man"]]},
  {num:6,words:[["Ona fai mai lea o se tasi", "And he said a one"], ["ia te ia,", "to him"], ["O a ea ia", "but to rise (as a diver to the sur- to"], ["manua i ou lima?", "manua in I five"], ["Ona fai atu lea o ia,", "And he said he"], ["O mea ia", "thing to"], ["na manua ai a'u", "manua I"], ["i le fale", "in the house"], ["o a'u uo.", "I am uo"]]},
  {num:7,words:[["Ala mai ia,", "way from to"], ["le pelu e,", "the a sword by"], ["i lo'u leoleo mamoe,", "in my shepherd"], ["ma le tagata", "and the man"], ["ma te faatasi ma a'u,", "and together and I"], ["ua fetalai mai ai Ieova", "said the LORD"], ["o 'au;", "I"], ["ina ta ia o le leoleo mamoe,", "so that a stroke to the shepherd"], ["ona faataapeapeina ai lea o le au", "and scattered the I"], ["mamoe;", "sheep"], ["ona faafoi atu lea o lo'u lima", "and return back my five"], ["i e iti.", "in to small"]]},
  {num:8,words:[["Ua fetalai mai Ieova,", "said the LORD"], ["E oo ina vavaeeseina", "it shall come to pass so that separated apart"], ["i le nuu uma lava ona", "in the land all indeed then"], ["vaega e lua,", "portion by two"], ["e fano lava ia;", "to perish indeed to"], ["a e faatotoeina ai lona tolu", "but to make phiral of foe his three"], ["o vaega .", "portion"]]},
  {num:9,words:[["Ou te avane lona tolu", "I gave his three"], ["o vaega", "portion"], ["i le afi;", "in the fire"], ["ou te faate'aese ai le eleele", "I faate'aese the earth"], ["ia te i latou,", "unto them"], ["e pei ona", "as"], ["faate'aeseina ai le eleele", "faate'aeseina the earth"], ["o le ario;", "the silver"], ["ou te totofofoina", "I totofofoina"], ["i latou,", "them"], ["e pei ona", "as"], ["tofotofoina o le auro;", "to try the gold"], ["e valaau", "to call"], ["i latou", "them"], ["i lo'u igoa;", "in my name"], ["o a'u foi,", "I am also"], ["ou te tali atu ai ia te i latou;", "I respond unto them"], ["ou te fai ane,", "I make"], ["O lo'u nuu lava", "my nation indeed"], ["i latou;", "them"], ["a e fai mai i latou,", "but to said them"], ["O Ieova", "the LORD"], ["o lo'u Atua lava o ia.", "my God indeed he"]]},
];
renderVerseSet(_zec_ch_13_Verses, 'zec-ch13-verses');

var _zec_ch_14_Verses = [
  {num:1,words:[["Faauta,", "behold"], ["o le a oo mai le aso", "what came the day"], ["o Ieova,", "the LORD"], ["e tufaina ai", "to to divide"], ["i totonu ia te oe", "in inside unto you"], ["o lou oa", "your a couple"], ["o le a vetea.", "what vetea"]]},
  {num:2,words:[["Auā ou te faapotopotoina nuu uma", "for I gathered together nation all"], ["e tau", "to season"], ["ma Ierusalema;", "and Jerusalem"], ["e aea", "by aea"], ["le aai,", "the city"], ["e vetea foi fale,", "by vetea also house"], ["ma fetosoina fafine,", "and fetosoina woman"], ["e ta'ita'i faatagataotauaina", "to lead captivity"], ["le tasi vaega", "the one portion"], ["o le aai;", "the city"], ["a o e totoe", "but who phiral of foe"], ["o le nuu,", "the nation"], ["e le faate'aeseina", "by the faate'aeseina"], ["i latou", "them"], ["i le aai.", "in the city"]]},
  {num:3,words:[["Ona afio atu lea o Ieova e tau", "and dwell (respectful) the LORD to season"], ["ma ia nuu,", "and to nation"], ["pei o le aso", "like the day"], ["na tau ai o ia i le aso", "season he in the day"], ["o le taua.", "the precious"]]},
  {num:4,words:[["E tu", "to stand"], ["ona aao", "and hand (extended)"], ["i lea aso", "in day"], ["i luga o le mauga", "upon the mountain"], ["o Olive,", "olive"], ["o loo feagai", "opposite"], ["ma Ierusalema", "and Jerusalem"], ["i gagae;", "in gagae"], ["e vaeluaina foi le mauga", "by vaeluaina also the mountain"], ["o Olive", "olive"], ["i totonu", "in inside"], ["i sasae", "eastward"], ["ma sisifo,", "and westward"], ["o le vanu tele lava;", "the valley great indeed"], ["e te'a atu le tasi itu", "to depart the one side"], ["o le mauga", "the mountain"], ["i le itu i matu,", "on the north side"], ["ma le tasi", "and the one"], ["ona itu i le itu i toga.", "and side on the side southward"]]},
  {num:5,words:[["Ona outou sosola lea", "and you (all) fled"], ["i le vanu o", "in the valley of"], ["i o'u mauga;", "in my mountain"], ["auā e pāia Asela", "for by pāia Asela"], ["i le vanu o mauga;", "in the valley of mountain"], ["tou te sosola foi,", "second person plural fled also"], ["pei ona", "like then"], ["outou sosola", "you (all) fled"], ["i le mafuie", "in the mafuie"], ["i ona po o Usia", "in then night of Usia"], ["le tupu o Iuta;", "the king of Judas"], ["e afio mai lava Ieova lo'u Atua", "to dwell (respectful) from indeed the LORD my God"], ["ma le au paia uma faatasi ma oe.", "and the saints all with you"]]},
  {num:6,words:[["E oo lava", "it shall come to pass indeed"], ["i lea aso,", "in day"], ["e le", "by the"], ["i ai le malamalama o mea aoga,", "therein the light of thing useful"], ["a o le pouliuli lava;", "but the darkness indeed"]]},
  {num:7,words:[["a e oo mai le aso,", "but it shall come to pass from the day"], ["e tasi lava ia,", "by one indeed to"], ["(ua silafia lava", "known indeed"], ["e Ieova,)", "the LORD"], ["e le", "by the"], ["o le ao,", "Day"], ["e le", "by the"], ["o le po;", "Night"], ["a e", "but by"], ["a oo i le itu aso afiafi", "but oo on the side day evening"], ["e malamalama ai.", "to light"]]},
  {num:8,words:[["O lea aso foi e alu atu ai le vai ola", "therefore day also to go away the water life"], ["nai Ierusalema", "from Jerusalem"], ["o le tasi", "the one"], ["ona vaega", "and portion"], ["e tafe atu i le sami", "to to flow in the sea"], ["i sasae,", "eastward"], ["a o le isi", "but the other"], ["ona vaega", "and portion"], ["e tafe atu i le sami", "to to flow in the sea"], ["i sisifo;", "westward"], ["o le tausaga vevela", "the year to be hot"], ["ma le tausaga maalili", "and the year maalili"], ["e fai ai ia mea .", "to make to thing"]]},
  {num:9,words:[["E fai foi Ieova", "to make also the LORD"], ["ma Tupu", "and king"], ["i le lalolagi uma lava;", "on the earth all indeed"], ["o lea aso", "therefore day"], ["ua na o Ieova ai lava,", "the LORD indeed"], ["ma lona suafa", "and his name"], ["e āu tasi lea.", "by āu one"]]},
  {num:10,words:[["E liua", "to turned into"], ["le nuu uma pei o le fanua laugatasi,", "the nation all like the land plain"], ["e pau mai i Kepa", "to fall from in Kepa"], ["e oo i Rimoni", "unto Rimmon"], ["i le itu i toga", "on the south side"], ["o Ierusalema;", "Jerusalem"], ["e faaeaina foi o ia,", "by faaeaina also he"], ["ma nofo", "and dwell"], ["i lona lava nuu,", "in his indeed nation"], ["e pau mai i le faitotoa o Peniamina", "to fall from at the door of Benjamin"], ["e oo i le mea", "unto the thing"], ["sa i ai le faitotoa anamua,", "therein the door ancient"], ["e oo i le faitotoa o tulimanu;", "unto the door of the corner (as of a"], ["e pau mai foi i le 'olo", "to fall from also in the fortress"], ["o Hananiali,", "Hananiali"], ["e oo i le tuugāuaina", "unto the tuugāuaina"], ["a le tupu.", "but the king"]]},
  {num:11,words:[["Latou te nonofo ai,", "they dwelling"], ["e le toe ai", "by the again"], ["se faafanoga;", "a destruction"], ["e nofo lava Ierusalema", "to dwell indeed Jerusalem"], ["ma le filemu.", "and the peace"]]},
  {num:12,words:[["O lenei", "now"], ["le mala", "the calamity"], ["e taia a'i", "to struck"], ["e Ieova o nuu uma", "the LORD nation all"], ["e tau", "to season"], ["ma Ierusalema;", "and Jerusalem"], ["e lāuvale lava o latou", "by lāuvale indeed of they"], ["tino,", "body"], ["a o tutū", "but of stood up"], ["i o latou vae;", "in of they foot"], ["e totō o latou", "by totō of they"], ["mata i mea e tutū ai,", "eye in thing to stood up"], ["ma o latou laulaufaiva", "and of they tongue"], ["e faaumatia ia i o latou", "to destroyed to in of they"], ["gutu.", "mouth"]]},
  {num:13,words:[["O lea aso foi e i ai ia te i latou", "therefore day also by therein unto them"], ["le atuatuvale tele", "the to be greatly dis- great"], ["mai ia Ieova;", "from to the LORD"], ["ona taitasi ai lea", "and each"], ["ma tago", "and reach"], ["o le tasi", "the one"], ["i le lima", "in the five"], ["o le tasi;", "the one"], ["e taitasi foi ma sii", "by each also and lift up"], ["i luga o latou", "upon they"], ["lima o le tasi", "five the one"], ["i le tasi.", "in the one"]]},
  {num:14,words:[["O Iuta foi e 'au", "Judas also to I"], ["i laua", "them"], ["ma Ierusalema;", "and Jerusalem"], ["e faaputuina oloa o nuu uma", "to to gather together goods of nation all"], ["e ua vagavagai,", "by to surround"], ["o auro,", "gold"], ["ma ario,", "and silver"], ["ma ofu e tele lava.", "and garment to great indeed"]]},
  {num:15,words:[["E faapea foi", "saying also"], ["ona i ai le mala", "and therein the calamity"], ["i le solofanua,", "in the horse"], ["ma le falata,", "and the falata"], ["ma le kamela,", "and the camel"], ["ma le asini,", "and the donkey"], ["atoa ma manu uma", "and animal all"], ["e i ai", "by therein"], ["i ia toagālauapi,", "in to toagālauapi"], ["e tusa ma lenei mala.", "according to this calamity"]]},
  {num:16,words:[["O e totoe uma lava", "who phiral of foe all indeed"], ["i nuu uma o e", "in nation all who"], ["o mai e tau", "from to season"], ["ma Ierusalema,", "and Jerusalem"], ["latou te o", "they of"], ["ae lava", "but indeed"], ["i lea tausaga", "in year"], ["ma lea tausaga", "and year"], ["e ifo", "by down"], ["i le Tupu,", "in the king"], ["o Ieova o 'au;", "the LORD I"], ["e fai ai foi le tausamiga", "to make also the feast"], ["o fale apitaga.", "house a tempoiary"]]},
  {num:17,words:[["A o le", "but the"], ["le alu ae ai itu aiga o le lalolagi i Ierusalema", "the go up side family the earth in Jerusalem"], ["e ifo", "by down"], ["i le Tupu,", "in the king"], ["o Ieova o 'au,", "the LORD I"], ["ona leai lea o se uaga", "and no a heavy rain"], ["ia te i latou.", "unto them"]]},
  {num:18,words:[["A e afai", "but to if"], ["e le alu ae", "by the go up"], ["le itu aiga o Aikupito,", "the side family of Egypt"], ["ma latou", "and they"], ["le o mai,", "the of from"], ["e leai foi", "there is not also"], ["se uaga ia te i latou;", "a heavy rain unto them"], ["ona i ai lea o le mala", "and therein the calamity"], ["e taia a'i", "to struck"], ["e Ieova o nuu o e le", "the LORD nation who the"], ["o ae", "up"], ["e fai", "to make"], ["le tausamiga o fale apitaga.", "the feast of house a tempoiary"]]},
  {num:19,words:[["O le sala lena", "the a fine that"], ["a Aikupito,", "of Egypt"], ["ma le sala", "and the a fine"], ["a nuu uma,", "but nation all"], ["o e le o", "who the of"], ["ae e fai", "but to make"], ["le tausamiga o fale apitaga.", "the feast of house a tempoiary"]]},
  {num:20,words:[["O lea aso e i ai", "therefore day by therein"], ["i tagitagi uamea o solofanua,", "in tagitagi iron of horse"], ["E paia ia Ieova ;", "to holy to the LORD"], ["o ulo foi i le fale", "ulo also in the house"], ["o Ieova,", "the LORD"], ["e tutusa ia ma ipu", "to equal to and cup"], ["i luma o le fata faitaulaga.", "before the altar"]]},
  {num:21,words:[["O ulo uma foi i Ierusalema", "ulo all also in Jerusalem"], ["ma Iuta,", "and Judas"], ["e paia lava ia ia", "to holy indeed to him"], ["Ieova o 'au;", "the LORD of I"], ["o i latou uma o e fasi manu,", "them all who kill animal"], ["latou te o mai", "they of from"], ["ma ave nisi ulo ,", "and take some ulo"], ["ma tunu ai;", "and roast"], ["e le toe", "by the again"], ["i ai lava", "therein indeed"], ["se sa Kananā", "a of the clan of Canaanites"], ["i le fale o Ieova", "in the house the LORD"], ["o 'au", "I"], ["i lea aso.", "in day"]]},
];
renderVerseSet(_zec_ch_14_Verses, 'zec-ch14-verses');

})();