(function() {
var _zep_ch_1_Verses = [
  {num:1,words:[["O le afioga", "the word"], ["a Ieova", "of the LORD"], ["na oo mai ia", "came he"], ["Sefanaia", "Zephaniah"], ["le atali'i o Kusi,", "the son of Kusi"], ["o le atali'i lea", "the son"], ["o Ketalia,", "Ketalia"], ["o le atali'i lea", "the son"], ["o Amaria,", "Amaria"], ["o le atali'i lea", "the son"], ["o Esekia,", "Hezekiah"], ["i ona po", "in his nights"], ["o Iosia", "Josiah"], ["le atali'i o Amone", "the son of Amone"], ["le tupu o Iuta.", "the king of Judas"]]},
  {num:2,words:[["Ua fetalai mai", "said"], ["Ieova,", "the LORD"], ["Ou te matuā fa'aumatia mea uma", "I will exceedingly destroyed all things"], ["i le fogaeleele.", "in the face of the earth"]]},
  {num:3,words:[["Ou te fa'aumatia tagata", "I will destroyed man"], ["ma manu vaefa,", "and cattle"], ["ou te fa'aumatia manu felelei", "I will destroyed birds of the air"], ["atoa ma i'a", "and fish"], ["o le sami,", "Sea"], ["o mea foi", "thing also"], ["e tausuai ai", "to stumble"], ["atoa ma tagata amio leaga,", "and man iniquity"], ["ou te fa'aumatia foi", "I will destroyed also"], ["tagata", "man"], ["i le fogaeleele,", "in the face of the earth"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:4,words:[["Ou te fa'aloaloa atu foi", "I will stretch out also"], ["lo'u lima", "my hand"], ["i luga o Iuta,", "upon Judas"], ["ma luga o", "and above of"], ["i lātou uma", "them all"], ["o", "o"], ["e nonofo", "to dwell"], ["i Ierusalema,", "in Jerusalem"], ["ou te fa'aumatia foi", "I will destroyed also"], ["i lenei", "in this"], ["mea o toe mea", "thing of again thing"], ["a Paala,", "of a small fly-fishhook"], ["o le igoa foi", "the name also"], ["o faitaulaga", "priest"], ["i tupua fa'atasi ma ositaulaga;", "in pillar together and high priest"]]},
  {num:5,words:[["o", "o"], ["i lātou foi", "them also"], ["o", "o"], ["e ifo", "by down"], ["i 'au", "in troops"], ["o le lagi", "Heaven"], ["i luga o fale;", "upon house"], ["o", "o"], ["i lātou foi", "them also"], ["o", "o"], ["e ifo", "by down"], ["ma tauto ia", "and to take an oath he"], ["Ieova,", "the LORD"], ["a", "but"], ["e tauto foi", "to to take an oath also"], ["ia Moloka;", "he Molech"]]},
  {num:6,words:[["o", "o"], ["i lātou foi", "them also"], ["o", "o"], ["e liliu ese", "to turn away"], ["ia Ieova,", "he the LORD"], ["ma", "and"], ["e o loo saili", "by is seek"], ["ia Ieova,", "he the LORD"], ["pe fesili ia te ia.", "whether asked to him"]]},
  {num:7,words:[["Ina fa'alologo ia", "so that to hold one's tongue he"], ["i luma", "in before"], ["o le Ali'i", "the Lord"], ["o Ieova,", "the LORD"], ["auā", "for"], ["ua latalata", "near"], ["le aso o Ieova;", "the day the LORD"], ["auā", "for"], ["ua sauni", "he who beg^ins the game"], ["e Ieova", "the LORD"], ["le taulaga,", "the offering"], ["ua fa'apaiaina e", "consecrated you"], ["ia e", "he by"], ["na ia tala'iina.", "he preached"]]},
  {num:8,words:[["O le aso", "the day"], ["o le taulaga", "the offering"], ["a Ieova ou te taui atu ai", "of the LORD I will a reward"], ["i ali'i sili", "in Lord most"], ["ma alo", "and Son"], ["o le tupu,", "the king"], ["atoa foi", "together with also"], ["ma", "and"], ["i lātou uma", "them all"], ["o", "o"], ["e oofu", "by oofu"], ["i ofu o nuu ese.", "in garment of nation away"]]},
  {num:9,words:[["O lea", "therefore"], ["lava aso ou te taui atu ai", "very day I will a reward"], ["i lātou uma lava", "them all very"], ["o", "o"], ["e feosofi", "to rushed upon"], ["i le faitotoa,", "at the door"], ["ma fa'atumu", "and make fill"], ["le fale o lātou", "the house of they"], ["ali'i", "Lord"], ["i le saua", "in the to have a return of sick-"], ["ma le pepelo.", "and the false"]]},
  {num:10,words:[["O loo fetalai mai", "is/are said"], ["Ieova,", "the LORD"], ["O lea aso", "therefore day"], ["e", "by"], ["i ai", "therein"], ["le leo", "the voice"], ["o le alaga", "the cry"], ["i le faitotoa", "at the door"], ["o i'a,", "fish"], ["ma le uio", "and the uio"], ["i le lua", "in the two"], ["o aai ,", "cities"], ["ma le taalili", "and the resounding"], ["o le lepetia", "the overthrown"], ["o mea e tele", "great things"], ["i mauga.", "in mountain"]]},
  {num:11,words:[["Ina uio ia outou", "so that uio he you all"], ["o", "o"], ["e mau", "to opinion"], ["i Metesa,", "in Metesa"], ["auā", "for"], ["ua fa'aumatia", "are destroyed"], ["le nuu uma", "all the nation"], ["o Kanana;", "Canaan"], ["ua fasiotia", "slain"], ["i lātou uma", "them all"], ["o", "o"], ["e ave avega", "to take burden"], ["o ario.", "silver"]]},
  {num:12,words:[["Ona po foi", "and night also"], ["ia ou te", "he I will"], ["suesue ai", "examine"], ["Ierusalema", "Jerusalem"], ["i sulu,", "in graft"], ["ona ou taui atu lea", "and I a reward"], ["i tagata o", "in man of"], ["e ua to'a", "to champion"], ["i luga o 'alu", "upon go"], ["o", "o"], ["a lātou uaina,", "their wine"], ["o loo fa'apea", "saying"], ["i o lātou", "in of they"], ["loto,", "heart"], ["E le faia", "shall not made"], ["e Ieova", "the LORD"], ["se mea lelei,", "a thing good"], ["na te", "he"], ["le faia foi", "the made also"], ["se mea leaga.", "a thing evil"]]},
  {num:13,words:[["E avea foi", "to become also"], ["o lātou oloa", "they goods"], ["ma vete,", "and plunder"], ["o lātou fale foi", "they house also"], ["e avea ia", "to become he"], ["ma mea gaogao;", "and thing void"], ["lātou te faia fale,", "they will made house"], ["a e lātou te", "but by they will"], ["le mau ai;", "the opinion"], ["lātou te faia tovine foi,", "they will made vineyard also"], ["a e lātou te", "but by they will"], ["le feinu ai", "the feinu"], ["uaina.", "wine"]]},
  {num:14,words:[["O loo latalata", "is near"], ["mai le aso tele", "from the day great"], ["o Ieova,", "the LORD"], ["e lata mai", "to near from"], ["lava,", "very"], ["o loo matuā televave", "is exceedingly televave"], ["mai lava,", "from very"], ["o le taalili", "the resounding"], ["o le aso", "the day"], ["o Ieova;", "the LORD"], ["e matuā tagiaue ai", "to exceedingly to wail"], ["le toa.", "the champion"]]},
  {num:15,words:[["E fai lea aso", "to make day"], ["ma aso", "and for days"], ["o le toasa,", "the wrath"], ["o le aso", "the day"], ["o le puapuaga", "the affliction"], ["ma le tiga,", "and the grieved"], ["o le aso", "the day"], ["o le fa'atafunaina", "the destroyed"], ["ma le fa'agaogaoina,", "and the make void"], ["o le aso", "the day"], ["o le pouliuli", "the darkness"], ["ma le pogisa,", "and the darkness"], ["o le aso", "the day"], ["o ao", "day"], ["ma le fa'amalumalu,", "and the to overshadow"]]},
  {num:16,words:[["o le aso", "the day"], ["o le pu", "the the tail"], ["ma le pāpā", "and the rock"], ["o alaga", "cry"], ["i le taua,", "in the battle"], ["e sii", "to lift up"], ["i aai nofo 'olo", "in cities dwell trench"], ["atoa ma 'olo maualuluga.", "and trench most high"]]},
  {num:17,words:[["Ou te fa'atiga foi", "I will afflict also"], ["i tagata,", "in man"], ["lātou te savavali ai", "they will walked"], ["pei o tagata tauaso,", "like of men a blind man"], ["auā", "for"], ["ua lātou agasala atu ia", "they sinned he"], ["Ieova;", "the LORD"], ["e fa'amaligiina o lātou", "by faamaligiina of they"], ["toto pei o le efuefu,", "blood like the dust"], ["e fai o lātou", "to make of they"], ["tino foi", "body also"], ["pei o otaota.", "like of full of rubbish"]]},
  {num:18,words:[["E le mafai lava", "shall not able very"], ["i o lātou", "in of they"], ["ario", "silver"], ["ma o lātou", "and of they"], ["auro", "gold"], ["ona laveai ia te", "and delivered unto"], ["i lātou", "them"], ["i le aso", "in the day"], ["o le toasa", "the wrath"], ["o Ieova;", "the LORD"], ["a", "but"], ["e fa'aumatia", "to destroyed"], ["le nuu uma", "all the nation"], ["i le afi", "in the fire"], ["o lona fuā;", "his fruit"], ["auā", "for"], ["e matuā fa'afuasei", "to exceedingly faafuasei"], ["ona fa'aumatia e", "and destroyed by"], ["ia", "he"], ["o", "o"], ["i lātou uma", "them all"], ["o", "o"], ["e nonofo", "to dwell"], ["i le nuu.", "in the land"]]},
  {num:19,words:[["O le ATUA", "of God"], ["le Ali'i,", "the Lord"], ["o lo'u malosi", "my strong"], ["ia,", "he"], ["na te faia", "he made"], ["o'u vae", "my foot"], ["e pei o vae", "like foot"], ["o aila,", "aila"], ["o ia foi", "he also"], ["ou te sāvali ai", "I will walk"], ["i afu mea maualuluga.", "in herb thing most high"], ["Ma le usu pese", "and the to lead the singing a song"], ["i nekina.", "in nekina"], ["O LE TUSI", "the book"], ["A LE PEROFETA", "of the prophesied"], ["O SEFANAIA", "Zephaniah"], ["O le aoaiga", "the discipline"], ["ia Iuta", "he Judas"], ["ona o", "because of"], ["a lātou agasala", "their sin"], ["O le afioga", "the word"], ["a le Ali'i", "but the Lord"], ["na 00 mai ia", "00 from he"], ["Sefanaia", "Zephaniah"], ["le atali'i o Kusi,", "the son of Kusi"], ["o le atali'i lea", "the son"], ["o Ketalia,", "Ketalia"], ["o le atali'i lea", "the son"], ["o Amaria,", "Amaria"], ["o le atali'i lea", "the son"], ["o Esekia,", "Hezekiah"], ["i ona po", "in his nights"], ["o Iosia", "Josiah"], ["le atali'i o Amone", "the son of Amone"], ["le tupu o Iuta.", "the king of Judas"]]},
];
renderVerseSet(_zep_ch_1_Verses, 'zep-ch1-verses');

var _zep_ch_2_Verses = [
  {num:1,words:[["Ia outou fa'apotopoto outou,", "he you all gather you all"], ["ina fa'apotopotoina ia outou,", "so that gathered together he you all"], ["le nuu", "the nation"], ["e le manaomia;", "shall not desired"]]},
  {num:2,words:[["manū o lei fānau mai le pule;", "animal of not born the rule"], ["o loo mavae atu", "is passed"], ["le aso pei", "the day like"], ["o aputi o saito;", "aputi of wheat"], ["manū o lei oo mai le toasa tele", "animal of not came the wrath great"], ["o Ieova ia te outou;", "the LORD unto you all"], ["manū o lei oo mai ia te outou", "animal of not came unto you all"], ["le aso", "the day"], ["o le toasa", "the wrath"], ["o Ieova.", "the LORD"]]},
  {num:3,words:[["Ia outou saili ia", "he you all seek he"], ["Ieova,", "the LORD"], ["outou uma", "you all all"], ["ua agamalu", "meek"], ["i le nuu,", "in the land"], ["o", "o"], ["e ua faia", "to made"], ["lana fa'amasinoga;", "his judgment"], ["ia outou saili", "he you all seek"], ["le amiotonu,", "the righteous"], ["ia outou saili", "he you all seek"], ["le agamalu,", "the meek"], ["atonu", "impers"], ["e lilo ai", "to secret"], ["outou", "you all"], ["i le aso", "in the day"], ["o le toasa", "the wrath"], ["o Ieova.", "the LORD"]]},
  {num:4,words:[["Auā", "for"], ["e tuulafoaiina Kasa,", "by tuulafoaiina Kasa"], ["e avea foi", "to become also"], ["Asekelona", "Asekelona"], ["ma mea gaogao;", "and thing void"], ["o Asetota lātou te tulia", "Asetota they will driven away"], ["o ia", "he"], ["i le tutonu", "in the tutonu"], ["o le lā,", "the sun"], ["e liaiina foi", "by liaiina also"], ["Ekerona.", "Ekron"]]},
  {num:5,words:[["Oi talofa", "wo"], ["i", "in"], ["e nonofo", "to dwell"], ["i nuu tumatafaga,", "in nation mariUBM"], ["o le nuu", "the nation"], ["o Kereti!", "Kereti"], ["o loo fa'asaga", "is face"], ["ia te outou", "unto you all"], ["le afioga", "the word"], ["a Ieova;", "of the LORD"], ["Kanana e,", "Canaan by"], ["le nuu o Filisitia,", "the nation of Philistine"], ["ou te fa'aumatia oe,", "I will destroyed you"], ["e iu", "to become of"], ["ina leai se nofo ai.", "so that no a dwell"]]},
  {num:6,words:[["E avea foi", "to become also"], ["nuu tu matafaga", "nation stand shore"], ["ma lotoā", "and court"], ["a manu,", "but animal"], ["ma vaieli o", "and well of"], ["e leoleo manu,", "to guard animal"], ["ma lotoā mamoe.", "and court sheep"]]},
  {num:7,words:[["E avea foi", "to become also"], ["le nuu", "the nation"], ["mo", "for"], ["e o totoe", "by of phiral of foe"], ["o le 'āiga", "the family"], ["o Iuta,", "Judas"], ["lātou te aai ai;", "they will cities"], ["o le afiafi lātou te taooto ai", "the evening they will lie down"], ["i fale o Asekelona;", "in house of Asekelona"], ["auā", "for"], ["e asiasi Ieova lo lātou Atua", "to visit the LORD their God"], ["ia te i lātou", "unto them"], ["ma fa'afoisia mai lā lātou tafeaga.", "and restored from their exiles in wa^"]]},
  {num:8,words:[["Ua ou fa'alogo atu", "I hearken"], ["i le faifai", "in the defy"], ["mai", "from"], ["a Moapi,", "of Moab"], ["ma le fa'aleaga", "and the to abuse"], ["mai", "from"], ["a le fanauga", "but the children"], ["a Amoni,", "of Ammon"], ["ua lātou faifai mai ai", "they defy from"], ["i lo'u nuu,", "in my nation"], ["ma lātou fa'amaualuluga", "and they exaltation"], ["mai ai", "from"], ["i lo lātou tuaoi.", "than they border"]]},
  {num:9,words:[["O le mea lea,", "therefore"], ["o loo fa'apea mai ai", "saying from"], ["Ieova o 'au", "the LORD of troops"], ["le Atua o Isaraelu,", "God Israel"], ["Ou te ola a'u,", "I will life me"], ["e avea lava Moapi pei", "to become very Moab like"], ["o Sotoma,", "Sodom"], ["o le fanauga", "the children"], ["a Amoni foi", "of Ammon also"], ["pei o Komoro,", "like of Gomorrah"], ["o le mea", "the thing"], ["e", "by"], ["i ai", "therein"], ["le vao ogoogo,", "the vegetation to scorch"], ["ma lua o masima,", "and two of salt"], ["o le mea gaogao foi", "the thing void also"], ["e fa'avavau;", "forever/everlasting"], ["o", "o"], ["e o totoe", "by of phiral of foe"], ["o lo'u nuu lātou te vetea", "my nation they will plundered"], ["i lātou,", "them"], ["o", "o"], ["e totoe foi", "to phiral of foe also"], ["o o'u tagata lātou te fai", "my man they will make"], ["i lātou", "them"], ["mo", "for"], ["i lātou lava.", "them very"]]},
  {num:10,words:[["E oo lea", "it shall come to pass"], ["mea ia te", "thing unto"], ["i lātou", "them"], ["ona", "and"], ["o lo lātou fa'amaualuluga,", "their exaltation"], ["auā", "for"], ["na lātou faifai", "they defy"], ["ma fa'amaualuga", "and pride"], ["i le nuu", "in the land"], ["o Ieova o 'au.", "the LORD troops"]]},
  {num:11,words:[["E matautia Ieova", "to fearful the LORD"], ["e", "by"], ["i lātou;", "them"], ["au?", "me"], ["na te fa'aumatia", "he destroyed"], ["atua uma", "God all"], ["o le lalolagi;", "the earth"], ["e ifo tagata", "by down man"], ["ia te ia", "to him"], ["taitasi", "each"], ["i le mea", "in the thing"], ["e nofo ai,", "to dwell"], ["o nuu tumatafaga uma", "nation mariUBM all"], ["o nuu ese.", "nation away"]]},
  {num:12,words:[["Outou Aitiope foi", "you all Aitiope also"], ["e fasiotia outou", "to slain you all"], ["i la'u pelu.", "in my sword"]]},
  {num:13,words:[["Na te fa'aloaloa atu foi", "he stretched out also"], ["lona aao", "his hand"], ["i le itu", "on the side"], ["i matu,", "northward"], ["ma fa'aumatia Asuria;", "and destroyed Assyria"], ["e fai foi", "to make also"], ["e ia", "by him"], ["o Nineva", "Nineveh"], ["ma mea gaogao,", "and thing void"], ["o le nuu naumati pei", "the nation dry like"], ["o le vao.", "the vegetation"]]},
  {num:14,words:[["E taooto foi", "to lie down also"], ["i ai", "therein"], ["lafu o manu vaefa uma", "flock of beasts all"], ["o nuu ese;", "nation away"], ["o le kati", "the kati"], ["ma le kifota lā te momoe", "and the kifota sun lie down"], ["i tumutumu", "in top"], ["o", "o"], ["ona pou;", "and pillar"], ["e tagi", "to cry"], ["le leo o manu", "the voice of animal"], ["i fa'amalama,", "in heathen customs (as"], ["e gaogao faitotoa;", "to void door"], ["auā", "for"], ["e aliali mea", "to to appear thing"], ["ua fai", "made"], ["i arasi.", "in cedar"]]},
  {num:15,words:[["O le aai mitamita lena", "the cities to boast that"], ["sa nofo fa'atalanoa,", "dwelt faatalanoa"], ["o le", "the"], ["sa fa'apea ifo", "saying down"], ["i lona loto,", "in his heart"], ["O a'u lava,", "I am very"], ["e leai se tasi,", "there is no one"], ["na", "na"], ["o a'u;", "I am"], ["oi!", "alas ! oh !"], ["ua fa'apea ona fai ma mea", "saying and to be thing"], ["gaogao;", "void"], ["o le mea", "the thing"], ["e taooto ai", "to lie down"], ["manu feai;", "wild beasts"], ["e taitasi", "by each"], ["ma uisa o", "and uisa of"], ["e ui ane ai,", "to although"], ["e tusi atu ai", "to book"], ["o lātou lima.", "they hand"]]},
];
renderVerseSet(_zep_ch_2_Verses, 'zep-ch2-verses');

var _zep_ch_3_Verses = [
  {num:1,words:[["Oi talofa", "wo"], ["i le aai fouvale", "in the cities to rebel"], ["ma le leaga,", "and the evil"], ["o le aai saua!", "the cities to have a return of sick-"]]},
  {num:2,words:[["Na ia le", "he the"], ["fa'alogo", "hearken"], ["i le leo;", "in the voice"], ["na ia le", "he the"], ["talia", "received"], ["le aoaiga;", "the discipline"], ["na ia le", "he the"], ["fa'atuatua ia Ieova,", "faith he the LORD"], ["na ia le", "he the"], ["fa'alatalata atu", "drew near"], ["i lona Atua.", "in his God"]]},
  {num:3,words:[["O", "O"], ["ona ali'i sili", "and Lord most"], ["i totonu ia te ia", "in inside to him"], ["o leona fetagisi", "lion wept"], ["i lātou;", "them"], ["o", "o"], ["ona fa'amasino o luko", "and judge of wolf"], ["o le afiafi", "the evening"], ["i lātou;", "them"], ["ua lātou", "they"], ["le paagugu ni ivi", "the to scranch as bones some bone"], ["i le taeao.", "in the morning"]]},
  {num:4,words:[["O ana perofeta", "cave prophesied"], ["o tagata mitamita vale", "of men to boast foolish"], ["i lātou", "them"], ["ma le fa'a'ole'ole;", "and the treacherous"], ["o ana ositaulaga", "cave high priest"], ["ua lātou soli", "they to tread upon"], ["le malumalu,", "the temple"], ["ua lātou soli", "they to tread upon"], ["le tulafono.", "the law"]]},
  {num:5,words:[["O Ieova", "the LORD"], ["le amiotonu o loo", "the righteous is"], ["i totonu ia te ia;", "in inside to him"], ["e le faia", "shall not made"], ["e ia se amioletonu;", "by him a wickedness"], ["o lea", "therefore"], ["taeao", "morning"], ["ma lea", "and"], ["taeao", "morning"], ["na te fa'amalamalama mai ai", "he gave light from"], ["lana fa'amasinoga,", "his judgment"], ["e le aunoa", "shall not without"], ["lava;", "very"], ["a", "but"], ["o le tagata amioletonu", "man wickedness"], ["na te", "he"], ["le iloa mā.", "the know and"]]},
  {num:6,words:[["Ua ou fa'aumatia", "I destroyed"], ["nuu ese;", "nation away"], ["ua fa'atafunaina o", "destroyed of"], ["lātou 'olo;", "they trench"], ["ua ou fa'agaogaoina", "I made void"], ["o lātou malae,", "they the"], ["ua leai se", "there was no"], ["ui ai;", "although"], ["ua fa'aumatia", "are destroyed"], ["a lātou aai,", "their cities"], ["ua", "ua"], ["le", "the"], ["i ai", "therein"], ["se tagata,", "a man"], ["ua leai foi", "there was not also"], ["se mau ai.", "a opinion"]]},
  {num:7,words:[["Na ou fai atu,", "I said to"], ["Tau ina", "yet / nevertheless"], ["e mata'u mai ia te au,", "to afraid from me"], ["ia e talia", "he to received"], ["le aoaiga,", "the discipline"], ["ona", "and"], ["le fa'aumatia ai lea", "the destroyed then"], ["o le mea", "the thing"], ["e mau ai", "to opinion"], ["o ia,", "he"], ["e le oo foi", "by the oo also"], ["se mea", "a thing"], ["e tasi", "by one"], ["ua ou fa'asalaina atu ai", "I punished"], ["ia te ia;", "to him"], ["a", "but"], ["ua lātou ala", "they way"], ["tulai,", "arise up"], ["ua lātou fai ia", "they made he"], ["leaga", "evil"], ["a lātou mea uma", "their all things"], ["ua fai.", "made"]]},
  {num:8,words:[["O lenei,", "now"], ["ia outou fa'atalitali ia te au,", "he you all waited unto me"], ["o loo fetalai mai ai", "is said"], ["Ieova,", "the LORD"], ["ia oo i le aso", "he oo in the day"], ["ou te tulai atu ai", "I will arise up"], ["i le vete;", "in the plunder"], ["auā", "for"], ["ua tonu ia te au", "right unto me"], ["e fa'apotopotoina nuu ese,", "to gathered together nation away"], ["e aofia lava mālō;", "by aofia very kingdom"], ["ina ia sasaa atu", "so that plurzH x)^ saasaa"], ["i luga ia", "in above he"], ["i lātou", "them"], ["lo'u ita,", "my angry"], ["o lo'u ita tele uma lava;", "my angry great all very"], ["auā", "for"], ["e fa'aumatia", "to destroyed"], ["le lalolagi uma", "all the earth"], ["i le afi", "in the fire"], ["o lo'u fuā.", "my fruit"]]},
  {num:9,words:[["Auā", "for"], ["o", "o"], ["ona po ia", "and night he"], ["ou te liliu atu ai", "I will turn"], ["i nuu", "in nation"], ["o le gagana lelei,", "the language good"], ["ina ia lātou", "so that they"], ["valaau uma lava", "cried out all very"], ["i le suafa", "in the name"], ["o Ieova,", "the LORD"], ["ma auauna ia te ia", "and servant to him"], ["ma le loto gatasi.", "and the heart gatasi"]]},
  {num:10,words:[["O", "O"], ["i tala atu", "in side"], ["o vaitafe o Aitiope", "river of Aitiope"], ["e au mai ai", "to bring"], ["le taulaga ia te au", "the offering unto me"], ["e o'u tagata", "to my man"], ["o ole mai,", "entreat from"], ["o le afafine", "the daughter"], ["lava", "very"], ["o o'u tagata", "my man"], ["ua fa'asalalauina.", "to scatter"]]},
  {num:11,words:[["O lea aso", "therefore day"], ["e te", "by"], ["le mā ai", "the and"], ["ona o sau amioga", "because of come conduct"], ["e tasi", "by one"], ["ua e fouvale ai", "you to rebel"], ["ia te au;", "unto me"], ["auā", "for"], ["o", "o"], ["ona po ia", "and night he"], ["ou te aveeseina ai", "I will carried away"], ["i totonu ia te oe", "in inside unto you"], ["o", "o"], ["i lātou", "them"], ["o ia te oe", "he you"], ["o", "o"], ["e mitamita fa'amaualuga;", "to to boast pride"], ["ona", "and"], ["e le toe fa'amaualuga ai lea", "shall not again pride then"], ["i lo'u mauga paia.", "in my mountain holy"]]},
  {num:12,words:[["Ou te fa'atotoe", "I will make phiral of foe"], ["i totonu ia te oe", "in inside unto you"], ["o le nuu agamalu", "the nation meek"], ["ma le mativa,", "and the want"], ["lātou te fa'atuatua foi", "they will faith also"], ["i le suafa", "in the name"], ["o Ieova.", "the LORD"]]},
  {num:13,words:[["O", "O"], ["e totoe o Isaraelu lātou te", "to phiral of foe of Israel they will"], ["le faia amioletonu,", "the made wickedness"], ["lātou te", "they will"], ["le tala pepelo foi;", "the side false also"], ["e le iloa foi", "shall not know also"], ["i o lātou", "in of they"], ["gutu", "mouth"], ["le laulaufaiva fa'a'ole'ole;", "the tongue treacherous"], ["a e lātou te aai,", "but by they will cities"], ["ma taooto,", "and lie down"], ["e leai foi", "there is not also"], ["se fa'amatau mai.", "a make ax from"]]},
  {num:14,words:[["Le tama fafine", "the child women"], ["a Siona e,", "of Zion by"], ["ia e pese.", "he to a song"], ["Isaraelu e,", "Israel by"], ["ia e alaga;", "he to cry"], ["le tama fafine", "the child women"], ["a Ierusalema e,", "of Jerusalem by"], ["ia e fiafia,", "he to pleased"], ["ma olioli lava", "and joy very"], ["ma le loto atoa.", "and the heart together with"]]},
  {num:15,words:[["Ua fa'aolaina", "saved alive"], ["e Ieova au", "the LORD me"], ["sala,", "a fine"], ["ua", "ua"], ["na aveeseina", "carried away"], ["le", "the"], ["na fai oe", "made you"], ["ma", "and"], ["ona fili;", "and to choose"], ["o le Tupu", "the king"], ["o Isaraelu,", "Israel"], ["o Ieova,", "the LORD"], ["o loo", "is/are"], ["i ai", "therein"], ["o ia", "he"], ["i totonu ia te oe,", "in inside unto you"], ["e te", "by"], ["le toe iloa ai", "the again know"], ["se malaia.", "a disaster"]]},
  {num:16,words:[["O lea aso", "therefore day"], ["o le a fa'apea atu ai", "what so"], ["i Ierusalema,", "in Jerusalem"], ["Aua", "for"], ["e te fefe;", "by afraid"], ["Siona e,", "Zion by"], ["aua ne'i vaivai ou lima.", "for now weak I hand"]]},
  {num:17,words:[["O Ieova", "the LORD"], ["lou Atua", "your God"], ["i totonu ia te oe", "in inside unto you"], ["o l? malosi", "l strong"], ["ia;", "he"], ["na te fa'aolaina;", "he saved alive"], ["e olioli o ia ia te oe", "to joy he unto you"], ["ma le fiafia;", "and the pleased"], ["o lona alofa", "his love"], ["e le fetalai ai", "shall not said"], ["o ia;", "he"], ["e olioli lava", "to joy very"], ["o ia ia te oe", "he unto you"], ["ma le ofo fiafia.", "and the greeted pleased"]]},
  {num:18,words:[["Ou te fa'apotopotoina", "I will gathered together"], ["i lātou", "them"], ["ua fa'anoanoa", "mourned"], ["ona o tausamiga,", "because of feast"], ["(o ou tagata", "I man"], ["i lātou,)", "them"], ["ua mafatia", "the distribution of pro-"], ["i le luma", "in the before"], ["ona o ia.", "because of he"]]},
  {num:19,words:[["Fa'auta,", "behold"], ["o", "o"], ["ona po ia", "and night he"], ["ou te fa'atiga ai", "I will afflict"], ["ia te i lātou", "unto them"], ["uma o", "all of"], ["e fa'asaua ia te oe;", "to cruel unto you"], ["ou te fa'aolaina foi", "I will saved alive also"], ["le", "the"], ["ua setusetu,", "'"], ["ou te fa'apotopotoina foi", "I will gathered together also"], ["le", "the"], ["ua tulia,", "driven away"], ["ou te avatu foi", "I will give away also"], ["ia te i lātou", "unto them"], ["le viiga", "the praise"], ["ma le igoa", "and the name"], ["i nuu uma lava", "in nation all very"], ["sa fa'amāina ai", "to put to shame"], ["i lātou.", "them"]]},
  {num:20,words:[["O", "O"], ["ona po ia", "and night he"], ["ou te au mai ai", "I will bring"], ["outou,", "you all"], ["o", "o"], ["ona po foi", "and night also"], ["lava ou te fa'apotopotoina ai", "very I will gathered together"], ["outou;", "you all"], ["ou te avatu ai", "I will give away"], ["lava ia te outou", "very unto you all"], ["le igoa", "the name"], ["ma le viiga", "and the praise"], ["i nuu uma", "in nation all"], ["o le lalolagi,", "the earth"], ["pe a ou fa'afoisia lā outou tafeaga,", "even though I restored your exiles in wa^"], ["o outou", "you all"], ["o vaai", "look"], ["i ai,", "therein"], ["o loo fetalai mai ai", "is said"], ["Ieova.", "the LORD"]]},
];
renderVerseSet(_zep_ch_3_Verses, 'zep-ch3-verses');

})();