(function() {
var _zep_ch_1_Verses = [
  {num:1,words:[["O le afioga", "the word (divine)"], ["a Ieova", "of the LORD"], ["na oo mai ia", "came to"], ["Sefanaia", "Zephaniah"], ["le atalii o Kusi,", "the son of Kusi"], ["o le atalii lea", "the son"], ["o Ketalia,", "Ketalia"], ["o le atalii lea", "the son"], ["o Amaria,", "Amaria"], ["o le atalii lea", "the son"], ["o Esekia,", "Hezekiah"], ["i ona po", "in then night"], ["o Iosia", "Josiah"], ["le atalii o Amone", "the son of Amone"], ["le tupu o Iuta.", "the king of Judas"]]},
  {num:2,words:[["Ua fetalai mai", "said"], ["Ieova,", "the LORD"], ["Ou te matuā faaumatia mea uma", "I will exceedingly destroyed all things"], ["i le fogaeleele.", "in the face of the earth"]]},
  {num:3,words:[["Ou te faaumatia tagata", "I will destroyed man"], ["ma manu vaefa,", "and cattle"], ["ou te faaumatia manu felelei", "I will destroyed fowl"], ["atoa ma i'a", "and fish"], ["o le sami,", "Sea"], ["o mea foi", "thing also"], ["e tausuai ai", "to to stumble forward"], ["atoa ma tagata amio leaga,", "and man iniquity"], ["ou te faaumatia foi", "I will destroyed also"], ["tagata", "man"], ["i le fogaeleele,", "in the face of the earth"], ["ua fetalai mai ai", "said"], ["Ieova.", "the LORD"]]},
  {num:4,words:[["Ou te faaloaloa atu foi", "I will stretch out also"], ["lo'u lima", "my five"], ["i luga o Iuta,", "upon Judas"], ["ma luga o", "and above of"], ["i latou uma", "them all"], ["o", "o"], ["e nonofo", "to dwell"], ["i Ierusalema,", "in Jerusalem"], ["ou te faaumatia foi", "I will destroyed also"], ["i lenei", "in this"], ["mea o toe mea", "thing of again thing"], ["a Paala,", "of a small fly-fishhook"], ["o le igoa foi", "the name also"], ["o faitaulaga", "priest"], ["i tupua faatasi ma ositaulaga;", "in pillar together and high priest"]]},
  {num:5,words:[["o", "o"], ["i latou foi", "them also"], ["o", "o"], ["e ifo", "by down"], ["i 'au", "in me"], ["o le lagi", "Heaven"], ["i luga o fale;", "upon house"], ["o", "o"], ["i latou foi", "them also"], ["o", "o"], ["e ifo", "by down"], ["ma tauto ia", "and to take an oath to"], ["Ieova,", "the LORD"], ["a", "but"], ["e tauto foi", "to to take an oath also"], ["ia Moloka;", "to Molech"]]},
  {num:6,words:[["o", "o"], ["i latou foi", "them also"], ["o", "o"], ["e liliu ese", "to turned away"], ["ia Ieova,", "to the LORD"], ["ma", "and"], ["e o loo saili", "by is (progressive) seek"], ["ia Ieova,", "to the LORD"], ["pe fesili ia te ia.", "whether ask to him"]]},
  {num:7,words:[["Ina faalologo ia", "so that to hold one's tongue to"], ["i luma", "in before"], ["o le Alii", "the Lord"], ["o Ieova,", "the LORD"], ["auā", "for"], ["ua latalata", "near"], ["le aso o Ieova;", "the day the LORD"], ["auā", "for"], ["ua sauni", "he who beg^ins the game"], ["e Ieova", "the LORD"], ["le taulaga,", "the offering"], ["ua faapaiaina e", "consecrated you"], ["ia e", "to by"], ["na ia tala'iina.", "to preached"]]},
  {num:8,words:[["O le aso", "the day"], ["o le taulaga", "the offering"], ["a Ieova ou te taui atu ai", "of the LORD I will a reward"], ["i alii sili", "in Lord most"], ["ma alo", "and Son"], ["o le tupu,", "the king"], ["atoa foi", "together with also"], ["ma", "and"], ["i latou uma", "them all"], ["o", "o"], ["e oofu", "by oofu"], ["i ofu o nuu ese.", "in garment of nation away"]]},
  {num:9,words:[["O lea", "therefore"], ["lava aso ou te taui atu ai", "indeed day I will a reward"], ["i latou uma lava", "them all indeed"], ["o", "o"], ["e feosofi", "by feosofi"], ["i le faitotoa,", "at the door"], ["ma faatumu", "and make fill"], ["le fale o latou", "the house of they"], ["alii", "Lord"], ["i le saua", "in the to have a return of sick-"], ["ma le pepelo.", "and the false"]]},
  {num:10,words:[["O loo fetalai mai", "is/are (progressive) said"], ["Ieova,", "the LORD"], ["O lea", "therefore"], ["aso e", "day by"], ["i ai", "therein"], ["le leo", "the voice"], ["o le alaga", "the cry"], ["i le faitotoa", "at the door"], ["o i'a,", "fish"], ["ma le uio", "and the uio"], ["i le lua", "in the two"], ["o aai ,", "city"], ["ma le taalili", "and the resounding"], ["o le lepetia", "the overthrown"], ["o mea e tele", "great things"], ["i mauga.", "in mountain"]]},
  {num:11,words:[["Ina uio ia outou", "so that uio to you (all)"], ["o", "o"], ["e mau", "to opinion"], ["i Metesa,", "in Metesa"], ["auā", "for"], ["ua faaumatia", "are destroyed"], ["le nuu uma", "the nation all"], ["o Kanana;", "Canaan"], ["ua fasiotia", "slain"], ["i latou uma", "them all"], ["o", "o"], ["e ave avega", "to take burden"], ["o ario.", "silver"]]},
  {num:12,words:[["Ona po foi", "and night also"], ["ia ou te", "to I will"], ["suesue ai", "examine"], ["Ierusalema", "Jerusalem"], ["i sulu,", "in graft"], ["ona ou taui atu lea", "and I a reward"], ["i tagata o", "in man of"], ["e ua to'a", "by heroic"], ["i luga o 'alu", "upon go"], ["o", "o"], ["a latou uaina,", "but they wine"], ["o loo faapea", "saying"], ["i o latou", "in of they"], ["loto,", "heart"], ["E le faia", "shall not made"], ["e Ieova", "the LORD"], ["se mea lelei,", "a thing good"], ["na te", "he"], ["le faia foi", "the made also"], ["se mea leaga.", "a thing evil"]]},
  {num:13,words:[["E avea foi", "to become also"], ["o latou oloa", "they goods"], ["ma vete,", "and plunder"], ["o latou fale foi", "they house also"], ["e avea ia", "to become to"], ["ma mea gaogao;", "and thing void"], ["latou te faia fale,", "they will made house"], ["a e latou te", "but by they will"], ["le mau ai;", "the opinion"], ["latou te faia tovine foi,", "they will made vineyard also"], ["a e latou te", "but by they will"], ["le feinu ai", "the feinu"], ["uaina.", "wine"]]},
  {num:14,words:[["O loo latalata", "is (progressive) near"], ["mai le aso tele", "from the day great"], ["o Ieova,", "the LORD"], ["e lata mai", "to near from"], ["lava,", "indeed"], ["o loo matuā televave", "is (progressive) exceedingly televave"], ["mai lava,", "from indeed"], ["o le taalili", "the resounding"], ["o le aso", "the day"], ["o Ieova;", "the LORD"], ["e matuā tagiaue ai", "to exceedingly to wail"], ["le toa.", "the heroic"]]},
  {num:15,words:[["E fai lea", "to make"], ["aso", "day"], ["ma aso", "and for days"], ["o le toasa,", "the wrath"], ["o le aso", "the day"], ["o le puapuaga", "the affliction"], ["ma le tiga,", "and the grieved"], ["o le aso", "the day"], ["o le faatafunaina", "the destroyed"], ["ma le faagaogaoina,", "and the make void"], ["o le aso", "the day"], ["o le pouliuli", "the darkness"], ["ma le pogisa,", "and the darkness"], ["o le aso", "the day"], ["o ao", "day"], ["ma le faamalumalu,", "and the to overshadow"]]},
  {num:16,words:[["o le aso", "the day"], ["o le pu", "the the tail"], ["ma le pāpā", "and the pāpā"], ["o alaga", "cry"], ["i le taua,", "in the precious"], ["e sii", "to lift up"], ["i aai nofo 'olo", "in city dwell fortress"], ["atoa ma 'olo maualuluga.", "and fortress most high"]]},
  {num:17,words:[["Ou te faatiga foi", "I will afflict also"], ["i tagata,", "in man"], ["latou te savavali ai", "they will walked"], ["pei o tagata tauaso,", "like of men a blind man"], ["auā", "for"], ["ua latou agasala atu ia", "they sinned to"], ["Ieova;", "the LORD"], ["e faamaligiina o latou", "by faamaligiina of they"], ["toto pei o le efuefu,", "blood like the dust"], ["e fai o latou", "to make of they"], ["tino foi", "body also"], ["pei o otaota.", "like of full of rubbish"]]},
  {num:18,words:[["E le mafai", "shall not able"], ["lava", "indeed"], ["i o latou", "in of they"], ["ario", "silver"], ["ma o latou", "and of they"], ["auro", "gold"], ["ona laveai ia te", "and deliver unto"], ["i latou", "them"], ["i le aso", "in the day"], ["o le toasa", "the wrath"], ["o Ieova;", "the LORD"], ["a", "but"], ["e faaumatia", "to destroyed"], ["le nuu uma", "the nation all"], ["i le afi", "in the fire"], ["o lona fuā;", "his fuā"], ["auā", "for"], ["e matuā faafuasei", "to exceedingly faafuasei"], ["ona faaumatia e", "and destroyed by"], ["ia", "to"], ["o", "o"], ["i latou uma", "them all"], ["o", "o"], ["e nonofo", "to dwell"], ["i le nuu.", "in the land"]]},
  {num:19,words:[["O le ATUA", "of God"], ["le ALII,", "the Lord"], ["o lo'u malosi", "my strong"], ["ia,", "to"], ["na te faia", "he made"], ["o'u vae", "my foot"], ["e pei o vae", "like foot"], ["o aila,", "aila"], ["o ia foi", "he also"], ["ou te savali ai", "I will walk"], ["i afu mea maualuluga.", "in herb thing most high"], ["Ma le usu pese", "and the to lead the singing a song"], ["i nekina.", "in nekina"], ["O LE TUSI", "the book"], ["A LE PEROFETA", "of the prophet"], ["O SEFANAIA", "Zephaniah"], ["O le aoaiga", "the discipline"], ["ia Iuta", "to Judas"], ["ona o", "because of"], ["a latou agasala", "but they sin"], ["O le afioga", "the word (divine)"], ["a le ALII", "but the Lord"], ["na 00 mai ia", "00 from to"], ["Sefanaia", "Zephaniah"], ["le atalii o Kusi,", "the son of Kusi"], ["o le atalii lea", "the son"], ["o Ketalia,", "Ketalia"], ["o le atalii lea", "the son"], ["o Amaria,", "Amaria"], ["o le atalii lea", "the son"], ["o Esekia,", "Hezekiah"], ["i ona po", "in then night"], ["o Iosia", "Josiah"], ["le atalii o Amone", "the son of Amone"], ["le tupu o Iuta.", "the king of Judas"]]},
];
renderVerseSet(_zep_ch_1_Verses, 'zep-ch1-verses');

var _zep_ch_2_Verses = [
  {num:1,words:[["Ia outou faapotopoto outou,", "to you (all) gather you (all)"], ["ina faapotopotoina ia outou,", "so that gathered together to you (all)"], ["le nuu", "the nation"], ["e le manaomia;", "shall not desired"]]},
  {num:2,words:[["manū o lei fanau mai le pule;", "manū of not born the rule"], ["o loo mavae atu", "is (progressive) passed"], ["le aso pei", "the day like"], ["o aputi o saito;", "aputi of wheat"], ["manū o lei oo mai le toasa tele", "manū of not came the wrath great"], ["o Ieova ia te outou;", "the LORD unto you"], ["manū o lei oo mai ia te outou", "manū of not came unto you"], ["le aso", "the day"], ["o le toasa", "the wrath"], ["o Ieova.", "the LORD"]]},
  {num:3,words:[["Ia outou saili ia", "to you (all) seek to"], ["Ieova,", "the LORD"], ["outou uma", "you (all) all"], ["ua agamalu", "meek"], ["i le nuu,", "in the land"], ["o", "o"], ["e ua faia", "by made"], ["lana faamasinoga;", "his judgment"], ["ia outou saili", "to you (all) seek"], ["le amiotonu,", "the righteous"], ["ia outou saili", "to you (all) seek"], ["le agamalu,", "the meek"], ["atonu", "impers"], ["e lilo ai", "to secret"], ["outou", "you (all)"], ["i le aso", "in the day"], ["o le toasa", "the wrath"], ["o Ieova.", "the LORD"]]},
  {num:4,words:[["Auā", "for"], ["e tuulafoaiina Kasa,", "by tuulafoaiina Kasa"], ["e avea foi", "to become also"], ["Asekelona", "Asekelona"], ["ma mea gaogao;", "and thing void"], ["o Asetota latou te tulia", "Asetota they will driven away"], ["o ia", "he"], ["i le tutonu", "in the tutonu"], ["o le la,", "the la"], ["e liaiina foi", "by liaiina also"], ["Ekerona.", "Ekron"]]},
  {num:5,words:[["Oi talofa", "wo"], ["i", "in"], ["e nonofo", "to dwell"], ["i nuu tumatafaga,", "in nation mariUBM"], ["o le nuu", "the nation"], ["o Kereti!", "Kereti"], ["o loo faasaga", "is (progressive) toward"], ["ia te outou", "unto you"], ["le afioga", "the word (divine)"], ["a Ieova;", "of the LORD"], ["Kanana e,", "Canaan by"], ["le nuu o Filisitia,", "the nation of Philistine"], ["ou te faaumatia oe,", "I will destroyed you"], ["e iu", "to become of"], ["ina leai se nofo ai.", "so that no a dwell"]]},
  {num:6,words:[["E avea foi", "to become also"], ["nuu tu matafaga", "nation stand shore"], ["ma lotoā", "and court"], ["a manu,", "but animal"], ["ma vaieli o", "and well of"], ["e leoleo manu,", "to guard animal"], ["ma lotoā mamoe.", "and court sheep"]]},
  {num:7,words:[["E avea foi", "to become also"], ["le nuu", "the nation"], ["mo", "for"], ["e o totoe", "by of phiral of foe"], ["o le aiga", "the family"], ["o Iuta,", "Judas"], ["latou te aai ai;", "they will city"], ["o le afiafi latou te taooto ai", "the evening they will lie down"], ["i fale o Asekelona;", "in house of Asekelona"], ["auā", "for"], ["e asiasi Ieova lo latou Atua", "to visit the LORD their God"], ["ia te i latou", "unto them"], ["ma faafoisia mai la latou tafeaga.", "and restored from their exiles in wa^"]]},
  {num:8,words:[["Ua ou faalogo atu", "I hearken"], ["i le faifai", "in the say repeatedly say"], ["mai", "from"], ["a Moapi,", "of Moab"], ["ma le faaleaga", "and the to abuse"], ["mai", "from"], ["a le fanauga", "but the children"], ["a Amoni,", "of Ammon"], ["ua latou faifai mai ai", "they said repeatedly say from"], ["i lo'u nuu,", "in my nation"], ["ma latou faamaualuluga", "and they make most high"], ["mai ai", "from"], ["i lo latou tuaoi.", "than they border"]]},
  {num:9,words:[["O le mea lea,", "therefore"], ["o loo faapea mai ai", "saying from"], ["Ieova o 'au", "the LORD of me"], ["le Atua o Isaraelu,", "God Israel"], ["Ou te ola a'u,", "I will life me"], ["e avea lava Moapi pei", "to become indeed Moab like"], ["o Sotoma,", "Sodom"], ["o le fanauga", "the children"], ["a Amoni foi", "of Ammon also"], ["pei o Komoro,", "like of Gomorrah"], ["o le mea", "the thing"], ["e", "by"], ["i ai", "therein"], ["le vao ogoogo,", "the vegetation ogoogo"], ["ma lua o masima,", "and two of salt"], ["o le mea gaogao foi", "the thing void also"], ["e faavavau;", "forever/everlasting"], ["o", "o"], ["e o totoe", "by of phiral of foe"], ["o lo'u nuu latou te vetea", "my nation they will vetea"], ["i latou,", "them"], ["o", "o"], ["e totoe foi", "to phiral of foe also"], ["o o'u tagata latou te fai", "my man they will make"], ["i latou", "them"], ["mo", "for"], ["i latou lava.", "them indeed"]]},
  {num:10,words:[["E oo lea", "it shall come to pass"], ["mea ia te", "thing unto"], ["i latou", "them"], ["ona", "and"], ["o lo latou faamaualuluga,", "their make most high"], ["auā", "for"], ["na latou faifai", "they said repeatedly say"], ["ma faamaualuga", "and exalted"], ["i le nuu", "in the land"], ["o Ieova o 'au.", "the LORD me"]]},
  {num:11,words:[["E matautia Ieova", "to fearful the LORD"], ["e", "by"], ["i latou;", "them"], ["au?", "me"], ["na te faaumatia", "he destroyed"], ["atua uma", "God all"], ["o le lalolagi;", "the earth"], ["e ifo tagata", "by down man"], ["ia te ia", "to him"], ["taitasi", "each"], ["i le mea", "in the thing"], ["e nofo ai,", "to dwell"], ["o nuu tumatafaga uma", "nation mariUBM all"], ["o nuu ese.", "nation away"]]},
  {num:12,words:[["Outou Aitiope foi", "you (all) Aitiope also"], ["e fasiotia outou", "to slain you (all)"], ["i la'u pelu.", "in my sword"]]},
  {num:13,words:[["Na te faaloaloa atu foi", "he stretched out also"], ["lona aao", "his hand (extended)"], ["i le itu", "on the side"], ["i matu,", "northward"], ["ma faaumatia Asuria;", "and destroyed Assyria"], ["e fai foi", "to make also"], ["e ia", "by him"], ["o Nineva", "Nineveh"], ["ma mea gaogao,", "and thing void"], ["o le nuu naumati pei", "the nation dry like"], ["o le vao.", "the vegetation"]]},
  {num:14,words:[["E taooto foi", "to lie down also"], ["i ai", "therein"], ["lafu o manu vaefa uma", "herd of beasts all"], ["o nuu ese;", "nation away"], ["o le kati", "the kati"], ["ma le kifota la te momoe", "and the kifota la lie down"], ["i tumutumu", "in top"], ["o", "o"], ["ona pou;", "and pillar"], ["e tagi", "to cry"], ["le leo o manu", "the voice of animal"], ["i faamalama,", "in heathen customs (as"], ["e gaogao faitotoa;", "to void door"], ["auā", "for"], ["e aliali mea", "to to appear thing"], ["ua fai", "made"], ["i arasi.", "in cedar"]]},
  {num:15,words:[["O le aai mitamita lena", "the city to boast that"], ["sa nofo faatalanoa,", "dwelt faatalanoa"], ["o le", "the"], ["sa faapea ifo", "saying down"], ["i lona loto,", "in his heart"], ["O a'u lava,", "I am indeed"], ["e leai se tasi,", "there is no one"], ["na", "na"], ["o a'u;", "I am"], ["oi!", "alas ! oh !"], ["ua faapea ona fai ma mea", "saying and to be thing"], ["gaogao;", "void"], ["o le mea", "the thing"], ["e taooto ai", "to lie down"], ["manu feai;", "animal wild"], ["e taitasi", "by each"], ["ma uisa o", "and uisa of"], ["e ui ane ai,", "to although"], ["e tusi atu ai", "to book"], ["o latou lima.", "they five"]]},
];
renderVerseSet(_zep_ch_2_Verses, 'zep-ch2-verses');

var _zep_ch_3_Verses = [
  {num:1,words:[["Oi talofa", "wo"], ["i le aai fouvale", "in the city to rebel"], ["ma le leaga,", "and the evil"], ["o le aai saua!", "the city to have a return of sick-"]]},
  {num:2,words:[["Na ia le", "to the"], ["faalogo", "hearken"], ["i le leo;", "in the voice"], ["na ia le", "to the"], ["talia", "received"], ["le aoaiga;", "the discipline"], ["na ia le", "to the"], ["faatuatua ia Ieova,", "faith to the LORD"], ["na ia le", "to the"], ["faalatalata atu", "draw near"], ["i lona Atua.", "in his God"]]},
  {num:3,words:[["O", "O"], ["ona alii sili", "and Lord most"], ["i totonu ia te ia", "in inside to him"], ["o leona fetagisi", "lion wept"], ["i latou;", "them"], ["o", "o"], ["ona faamasino o luko", "and judge of wolf"], ["o le afiafi", "the evening"], ["i latou;", "them"], ["ua latou", "they"], ["le paagugu ni ivi", "the to scranch as bones some bone"], ["i le taeao.", "in the morning"]]},
  {num:4,words:[["O ana perofeta", "his prophet"], ["o tagata mitamita vale", "of men to boast foolish"], ["i latou", "them"], ["ma le faa'ole'ole;", "and the treacherous"], ["o ana ositaulaga", "his high priest"], ["ua latou soli", "they to tread upon"], ["le malumalu,", "the temple"], ["ua latou soli", "they to tread upon"], ["le tulafono.", "the law"]]},
  {num:5,words:[["O Ieova", "the LORD"], ["le amiotonu o loo", "the righteous is (progressive)"], ["i totonu ia te ia;", "in inside to him"], ["e le faia", "shall not made"], ["e ia se amioletonu;", "by him a wickedness"], ["o lea", "therefore"], ["taeao", "morning"], ["ma lea", "and"], ["taeao", "morning"], ["na te faamalamalama mai ai", "he gave light from"], ["lana faamasinoga,", "his judgment"], ["e le aunoa", "shall not without"], ["lava;", "indeed"], ["a", "but"], ["o le tagata amioletonu", "man wickedness"], ["na te", "he"], ["le iloa mā.", "the know First person dual exclusive"]]},
  {num:6,words:[["Ua ou faaumatia", "I destroyed"], ["nuu ese;", "nation away"], ["ua faatafunaina o", "destroyed of"], ["latou 'olo;", "they fortress"], ["ua ou faagaogaoina", "I made void"], ["o latou malae,", "they the"], ["ua leai se", "there was no"], ["ui ai;", "although"], ["ua faaumatia", "are destroyed"], ["a latou aai,", "but they city"], ["ua", "ua"], ["le", "the"], ["i ai", "therein"], ["se tagata,", "a man"], ["ua leai foi", "there was not also"], ["se mau ai.", "a opinion"]]},
  {num:7,words:[["Na ou fai atu,", "I said to"], ["Tau ina", "yet / nevertheless"], ["e mata'u mai ia te au,", "to ax from me"], ["ia e talia", "to to received"], ["le aoaiga,", "the discipline"], ["ona", "and"], ["le faaumatia ai lea", "the destroyed then then"], ["o le mea", "the thing"], ["e mau ai", "to opinion"], ["o ia,", "he"], ["e le oo foi", "by the oo also"], ["se mea", "a thing"], ["e tasi", "by one"], ["ua ou faasalaina atu ai", "I punished"], ["ia te ia;", "to him"], ["a", "but"], ["ua latou ala", "they way"], ["tulai,", "arise up"], ["ua latou fai ia", "they made to"], ["leaga", "evil"], ["a latou mea uma", "but they all things"], ["ua fai.", "made"]]},
  {num:8,words:[["O lenei,", "now"], ["ia outou faatalitali ia te au,", "to you (all) waited unto me"], ["o loo fetalai mai ai", "is (progressive) said"], ["Ieova,", "the LORD"], ["ia oo i le aso", "to oo in the day"], ["ou te tulai atu ai", "I will arise up"], ["i le vete;", "in the plunder"], ["auā", "for"], ["ua tonu ia te au", "right unto me"], ["e faapotopotoina nuu ese,", "to gathered together nation away"], ["e aofia lava malo;", "by aofia indeed government"], ["ina ia sasaa atu", "so that plurzH x)^ saasaa"], ["i luga ia", "in above to"], ["i latou", "them"], ["lo'u ita,", "my angry"], ["o lo'u ita tele uma lava;", "my angry great all indeed"], ["auā", "for"], ["e faaumatia", "to destroyed"], ["le lalolagi uma", "the earth all"], ["i le afi", "in the fire"], ["o lo'u fuā.", "my fuā"]]},
  {num:9,words:[["Auā", "for"], ["o", "o"], ["ona po ia", "and night to"], ["ou te liliu atu ai", "I will turned"], ["i nuu", "in nation"], ["o le gagana lelei,", "the language good"], ["ina ia latou", "so that they"], ["valaau uma lava", "call all indeed"], ["i le suafa", "in the name"], ["o Ieova,", "the LORD"], ["ma auauna ia te ia", "and servant to him"], ["ma le loto gatasi.", "and the heart gatasi"]]},
  {num:10,words:[["O", "O"], ["i tala atu", "in side"], ["o vaitafe o Aitiope", "river of Aitiope"], ["e au mai ai", "to bring"], ["le taulaga ia te au", "the offering unto me"], ["e o'u tagata", "to my man"], ["o ole mai,", "entreat from"], ["o le afafine", "the daughter"], ["lava", "indeed"], ["o o'u tagata", "my man"], ["ua faasalalauina.", "to scatter"]]},
  {num:11,words:[["O lea", "therefore"], ["aso", "day"], ["e te", "by"], ["le mā ai", "the First person dual exclusive"], ["ona o sau amioga", "because of come amioga"], ["e tasi", "by one"], ["ua e fouvale ai", "you to rebel"], ["ia te au;", "unto me"], ["auā", "for"], ["o", "o"], ["ona po ia", "and night to"], ["ou te aveeseina ai", "I will carried away"], ["i totonu ia te oe", "in inside unto you"], ["o", "o"], ["i latou", "them"], ["o ia te oe", "he you"], ["o", "o"], ["e mitamita faamaualuga;", "to to boast exalted"], ["ona", "and"], ["e le toe faamaualuga ai lea", "shall not again exalted then then"], ["i lo'u mauga paia.", "in my mountain holy"]]},
  {num:12,words:[["Ou te faatotoe", "I will make phiral of foe"], ["i totonu ia te oe", "in inside unto you"], ["o le nuu agamalu", "the nation meek"], ["ma le mativa,", "and the want"], ["latou te faatuatua foi", "they will faith also"], ["i le suafa", "in the name"], ["o Ieova.", "the LORD"]]},
  {num:13,words:[["O", "O"], ["e totoe o Isaraelu latou te", "to phiral of foe of Israel they will"], ["le faia amioletonu,", "the made wickedness"], ["latou te", "they will"], ["le tala pepelo foi;", "the side false also"], ["e le iloa foi", "shall not know also"], ["i o latou", "in of they"], ["gutu", "mouth"], ["le laulaufaiva faa'ole'ole;", "the tongue treacherous"], ["a e latou te aai,", "but by they will city"], ["ma taooto,", "and lie down"], ["e leai foi", "there is not also"], ["se faamatau mai.", "a make ax from"]]},
  {num:14,words:[["Le tama fafine", "the child woman"], ["a Siona e,", "of Zion by"], ["ia e pese.", "to to a song"], ["Isaraelu e,", "Israel by"], ["ia e alaga;", "to to cry"], ["le tama fafine", "the child woman"], ["a Ierusalema e,", "of Jerusalem by"], ["ia e fiafia,", "to to competition"], ["ma olioli lava", "and rejoice indeed"], ["ma le loto atoa.", "and the heart together with"]]},
  {num:15,words:[["Ua faaolaina", "saved alive"], ["e Ieova au", "the LORD me"], ["sala,", "a fine"], ["ua", "ua"], ["na aveeseina", "carried away"], ["le", "the"], ["na fai oe", "made you"], ["ma", "and"], ["ona fili;", "and to choose"], ["o le Tupu", "the king"], ["o Isaraelu,", "Israel"], ["o Ieova,", "the LORD"], ["o loo", "is/are (progressive)"], ["i ai", "therein"], ["o ia", "he"], ["i totonu ia te oe,", "in inside unto you"], ["e te", "by"], ["le toe iloa ai", "the again know"], ["se malaia.", "a disaster"]]},
  {num:16,words:[["O lea", "therefore"], ["aso", "day"], ["o le a faapea atu ai", "what thus"], ["i Ierusalema,", "in Jerusalem"], ["Aua", "for"], ["e te fefe;", "by get scared"], ["Siona e,", "Zion by"], ["aua ne'i vaivai ou lima.", "for now weak I five"]]},
  {num:17,words:[["O Ieova", "the LORD"], ["lou Atua", "your God"], ["i totonu ia te oe", "in inside unto you"], ["o l? malosi", "l strong"], ["ia;", "to"], ["na te faaolaina;", "he saved alive"], ["e olioli o ia ia te oe", "to rejoice he unto you"], ["ma le fiafia;", "and the competition"], ["o lona alofa", "his love"], ["e le fetalai ai", "shall not said"], ["o ia;", "he"], ["e olioli lava", "to rejoice indeed"], ["o ia ia te oe", "he unto you"], ["ma le ofo fiafia.", "and the n competition"]]},
  {num:18,words:[["Ou te faapotopotoina", "I will gathered together"], ["i latou", "them"], ["ua faanoanoa", "mourned"], ["ona o tausamiga,", "because of feast"], ["(o ou tagata", "I man"], ["i latou,)", "them"], ["ua mafatia", "the distribution of pro-"], ["i le luma", "in the before"], ["ona o ia.", "because of to"]]},
  {num:19,words:[["Faauta,", "behold"], ["o", "o"], ["ona po ia", "and night to"], ["ou te faatiga ai", "I will afflict"], ["ia te i latou", "unto them"], ["uma o", "all of"], ["e faasaua ia te oe;", "to cruel unto you"], ["ou te faaolaina foi", "I will saved alive also"], ["le", "the"], ["ua setusetu,", "setusetu"], ["ou te faapotopotoina foi", "I will gathered together also"], ["le", "the"], ["ua tulia,", "driven away"], ["ou te avatu foi", "I will give away also"], ["ia te i latou", "unto them"], ["le viiga", "the praise"], ["ma le igoa", "and the name"], ["i nuu uma lava", "in nation all indeed"], ["sa faamāina ai", "faamāina"], ["i latou.", "them"]]},
  {num:20,words:[["O", "O"], ["ona po ia", "and night to"], ["ou te au mai ai", "I will bring"], ["outou,", "you (all)"], ["o", "o"], ["ona po foi", "and night also"], ["lava ou te faapotopotoina ai", "indeed I will gathered together"], ["outou;", "you (all)"], ["ou te avatu ai", "I will give away"], ["lava ia te outou", "indeed unto you"], ["le igoa", "the name"], ["ma le viiga", "and the praise"], ["i nuu uma", "in nation all"], ["o le lalolagi,", "the earth"], ["pe a ou faafoisia la outou tafeaga,", "even though I restored your exiles in wa^"], ["o outou", "you (all)"], ["o vaai", "look"], ["i ai,", "therein"], ["o loo fetalai mai ai", "is (progressive) said"], ["Ieova.", "the LORD"]]},
];
renderVerseSet(_zep_ch_3_Verses, 'zep-ch3-verses');

})();