(function() {
var _zep_ch_1_Verses = [
  {num:1,words:[["O le afioga", "the a word"], ["a Ieova", "of the LORD"], ["na oo mai ia", "came to"], ["Sefanaia le atalii o Kusi,", "Zephaniah the son of Kusi"], ["o le atalii lea o Ketalia,", "the son of Ketalia"], ["o le atalii lea o Amaria,", "the son of Amaria"], ["o le atalii lea o Esekia,", "the son of Hezekiah"], ["i ona po o Iosia", "in then night of Josiah"], ["le atalii o Amone", "the son of Amone"], ["le tupu o Iuta.", "the king of Judas"]]},
  {num:2,words:[["Ua fetalai mai Ieova,", "said the LORD"], ["Ou te matuā faaumatia mea uma", "I exceedingly destroyed all things"], ["i le fogaeleele.", "in the face of the earth"]]},
  {num:3,words:[["Ou te faaumatia tagata", "I destroyed man"], ["ma manu vaefa,", "and cattle"], ["ou te faaumatia manu felelei", "I destroyed fowl"], ["atoa ma i'a", "and fish"], ["o le sami,", "Sea"], ["o mea foi", "thing also"], ["e tausuai ai", "to to stumble forward"], ["atoa ma tagata amio leaga,", "and man iniquity"], ["ou te faaumatia foi tagata", "I destroyed also man"], ["i le fogaeleele,", "in the face of the earth"], ["ua fetalai mai ai Ieova.", "said the LORD"]]},
  {num:4,words:[["Ou te faaloaloa atu foi lo'u lima", "I to stretch out also my five"], ["i luga o Iuta,", "upon Judas"], ["ma luga o", "and above of"], ["i latou uma o", "them all of"], ["e nonofo", "to dwell"], ["i Ierusalema,", "in Jerusalem"], ["ou te faaumatia foi", "I destroyed also"], ["i lenei mea o toe mea", "in this thing of again thing"], ["a Paala,", "of a small fly-fishhook"], ["o le igoa foi o faitaulaga", "the name also of priest"], ["i tupua faatasi", "in pillar once"], ["ma ositaulaga;", "and high priest"]]},
  {num:5,words:[["o i latou foi o", "them also of"], ["e ifo", "by down"], ["i 'au", "in I"], ["o le lagi", "Heaven"], ["i luga o fale;", "upon house"], ["o i latou foi o", "them also of"], ["e ifo", "by down"], ["ma tauto ia Ieova,", "and to take an oath to the LORD"], ["a e tauto foi ia", "but to to take an oath also to"], ["Moloka;", "Molech"]]},
  {num:6,words:[["o i latou foi o", "them also of"], ["e liliu ese ia", "to turned away to"], ["Ieova,", "the LORD"], ["ma e o loo saili", "and by of seek"], ["ia Ieova,", "to the LORD"], ["pe fesili ia te ia.", "whether to question to him"]]},
  {num:7,words:[["Ina faalologo ia", "let to hold one's tongue to"], ["i luma", "in before"], ["o le Alii o Ieova,", "the Lord the LORD"], ["auā ua latalata", "for near"], ["le aso o Ieova;", "the day the LORD"], ["auā ua sauni", "for he who beg^ins the game"], ["e Ieova", "the LORD"], ["le taulaga,", "the offering"], ["ua faapaiaina e ia", "consecrated by him"], ["e na ia tala'iina.", "by to preached"]]},
  {num:8,words:[["O le aso", "the day"], ["o le taulaga", "the offering"], ["a Ieova ou te taui atu ai", "of the LORD I a reward"], ["i alii sili", "in Lord most"], ["ma alo", "and Son"], ["o le tupu,", "the king"], ["atoa foi", "together with also"], ["ma i latou uma o", "and them all of"], ["e oofu", "by oofu"], ["i ofu o nuu ese.", "in garment of nation away"]]},
  {num:9,words:[["O lea lava aso ou te taui atu ai", "therefore indeed day I a reward"], ["i latou uma lava o", "them all indeed of"], ["e feosofi", "by feosofi"], ["i le faitotoa,", "at the door"], ["ma faatumu", "and faatumu"], ["le fale o latou", "the house of they"], ["alii i le saua", "Lord in the to have a return of sick-"], ["ma le pepelo.", "and the false"]]},
  {num:10,words:[["O loo fetalai", "said"], ["mai Ieova,", "from the LORD"], ["O lea aso e", "therefore day by"], ["i ai", "therein"], ["le leo", "the voice"], ["o le alaga", "the cry"], ["i le faitotoa o i'a,", "at the door fish"], ["ma le uio", "and the uio"], ["i le lua o aai ,", "in the two of city"], ["ma le taalili", "and the resounding"], ["o le lepetia o mea", "the overthrown of thing"], ["e tele", "to great"], ["i mauga.", "in mountain"]]},
  {num:11,words:[["Ina uio ia outou", "let uio to you (all)"], ["o e mau", "who opinion"], ["i Metesa,", "in Metesa"], ["auā ua faaumatia", "for destroyed"], ["le nuu uma o Kanana;", "the nation all of Canaan"], ["ua fasiotia", "slain"], ["i latou uma o", "them all of"], ["e ave avega o ario.", "to take burden of silver"]]},
  {num:12,words:[["Ona po foi ia", "and night also to"], ["ou te suesue ai Ierusalema", "I examine Jerusalem"], ["i sulu,", "in a torch"], ["ona ou taui atu lea", "and I a reward"], ["i tagata o", "in man of"], ["e ua to'a", "by heroic"], ["i luga o 'alu o", "upon go of"], ["a latou uaina,", "but they wine"], ["o loo faapea", "saying"], ["i o latou loto,", "in of they heart"], ["E le faia", "by the made"], ["e Ieova", "the LORD"], ["se mea lelei,", "a thing good"], ["na te", "he"], ["le faia foi", "the made also"], ["se mea leaga.", "a thing evil"]]},
  {num:13,words:[["E avea foi o latou", "to become also of they"], ["oloa ma vete,", "goods and plunder"], ["o latou fale foi", "they house also"], ["e avea ia", "to become to"], ["ma mea gaogao;", "and thing void"], ["latou te faia fale,", "they made house"], ["a e latou te", "but by they"], ["le mau ai;", "the opinion"], ["latou te faia tovine foi,", "they made vineyard also"], ["a e latou te", "but by they"], ["le feinu ai uaina.", "the feinu wine"]]},
  {num:14,words:[["O loo latalata", "near"], ["mai le aso tele o Ieova,", "from the day great the LORD"], ["e lata mai lava,", "to near from indeed"], ["o loo matuā televave", "exceedingly televave"], ["mai lava,", "from indeed"], ["o le taalili", "the resounding"], ["o le aso o Ieova;", "the day the LORD"], ["e matuā tagiaue ai", "to exceedingly to wail"], ["le toa.", "the heroic"]]},
  {num:15,words:[["E fai lea aso", "to make day"], ["ma aso", "and for days"], ["o le toasa,", "the wrath"], ["o le aso", "the day"], ["o le puapuaga", "the affliction"], ["ma le tiga,", "and the grieved"], ["o le aso", "the day"], ["o le faatafunaina", "the destroyed"], ["ma le faagaogaoina,", "and the faagaogaoina"], ["o le aso", "the day"], ["o le pouliuli", "the darkness"], ["ma le pogisa,", "and the darkness"], ["o le aso o ao", "the day day"], ["ma le faamalumalu,", "and the to overshadow"]]},
  {num:16,words:[["o le aso", "the day"], ["o le pu", "the the tail"], ["ma le pāpā o alaga", "and the pāpā of cry"], ["i le taua,", "in the precious"], ["e sii", "to lift up"], ["i aai nofo 'olo", "in city dwell fortress"], ["atoa ma 'olo maualuluga.", "and fortress most high"]]},
  {num:17,words:[["Ou te faatiga foi", "I a also"], ["i tagata,", "in man"], ["latou te savavali ai pei", "they walked like"], ["o tagata tauaso,", "of men a blind man"], ["auā ua latou agasala atu", "for they sin"], ["ia Ieova;", "to the LORD"], ["e faamaligiina o latou", "by faamaligiina of they"], ["toto pei o le efuefu,", "blood like the dust"], ["e fai o latou", "to make of they"], ["tino foi pei o otaota.", "body also like of full of rubbish"]]},
  {num:18,words:[["E le mafai lava", "by the able indeed"], ["i o latou ario", "in of they silver"], ["ma o latou auro", "and of they gold"], ["ona laveai ia te", "and deliver unto"], ["i latou", "them"], ["i le aso", "in the day"], ["o le toasa o Ieova;", "the wrath the LORD"], ["a e faaumatia", "but to destroyed"], ["le nuu uma", "the nation all"], ["i le afi", "in the fire"], ["o lona fuā;", "his fuā"], ["auā e matuā faafuasei", "for to exceedingly faafuasei"], ["ona faaumatia e ia", "and destroyed by him"], ["o i latou uma o", "them all of"], ["e nonofo", "to dwell"], ["i le nuu.", "in the land"]]},
  {num:19,words:[["O le ATUA", "of God"], ["le ALII,", "the Lord"], ["o lo'u malosi ia,", "my strong to"], ["na te faia o'u vae", "he made my foot"], ["e pei o vae o aila,", "to like of foot of aila"], ["o ia foi ou te savali ai", "he also I walk"], ["i afu mea maualuluga.", "in herb thing most high"], ["Ma le usu pese", "and the to lead the singing a song"], ["i nekina.", "in nekina"], ["O LE TUSI", "the book"], ["A LE PEROFETA O SEFANAIA", "of the prophet of Zephaniah"], ["O le aoaiga ia", "the discipline to"], ["Iuta ona o", "Judas because of"], ["a latou agasala", "but they sin"], ["O le afioga", "the a word"], ["a le ALII", "but the Lord"], ["na 00 mai ia", "00 from to"], ["Sefanaia le atalii o Kusi,", "Zephaniah the son of Kusi"], ["o le atalii lea o Ketalia,", "the son of Ketalia"], ["o le atalii lea o Amaria,", "the son of Amaria"], ["o le atalii lea o Esekia,", "the son of Hezekiah"], ["i ona po o Iosia", "in then night of Josiah"], ["le atalii o Amone", "the son of Amone"], ["le tupu o Iuta.", "the king of Judas"]]},
];
renderVerseSet(_zep_ch_1_Verses, 'zep-ch1-verses');

var _zep_ch_2_Verses = [
  {num:1,words:[["Ia outou faapotopoto outou,", "to you (all) gather you (all)"], ["ina faapotopotoina ia outou,", "let gathered together to you (all)"], ["le nuu", "the nation"], ["e le manaomia;", "by the desired"]]},
  {num:2,words:[["manū o lei fanau", "manū of not born"], ["mai le pule;", "from the rule"], ["o loo mavae atu", "a parting"], ["le aso pei o aputi", "the day like of aputi"], ["o saito;", "wheat"], ["manū o lei oo", "manū of not oo"], ["mai le toasa tele o Ieova", "from the wrath great the LORD"], ["ia te outou;", "unto you"], ["manū o lei oo", "manū of not oo"], ["mai ia te outou", "from you (all)"], ["le aso", "the day"], ["o le toasa o Ieova.", "the wrath the LORD"]]},
  {num:3,words:[["Ia outou saili ia", "to you (all) seek to"], ["Ieova,", "the LORD"], ["outou uma", "you (all) all"], ["ua agamalu", "meek"], ["i le nuu,", "in the land"], ["o e", "who"], ["ua faia lana faamasinoga;", "made his judgment"], ["ia outou saili", "to you (all) seek"], ["le amiotonu,", "the righteous"], ["ia outou saili", "to you (all) seek"], ["le agamalu,", "the meek"], ["atonu e lilo ai outou", "impers to secret you (all)"], ["i le aso", "in the day"], ["o le toasa o Ieova.", "the wrath the LORD"]]},
  {num:4,words:[["Auā e tuulafoaiina Kasa,", "for by tuulafoaiina Kasa"], ["e avea foi Asekelona", "to become also Asekelona"], ["ma mea gaogao;", "and thing void"], ["o Asetota latou te tulia", "Asetota they driven away"], ["o ia", "he"], ["i le tutonu", "in the tutonu"], ["o le la,", "the la"], ["e liaiina foi Ekerona.", "by liaiina also Ekron"]]},
  {num:5,words:[["Oi talofa", "wo"], ["i e nonofo", "in to dwell"], ["i nuu tumatafaga,", "in nation mariUBM"], ["o le nuu o Kereti!", "the nation of Kereti"], ["o loo faasaga ia te outou", "toward unto you"], ["le afioga", "the a word"], ["a Ieova;", "of the LORD"], ["Kanana e,", "Canaan by"], ["le nuu o Filisitia,", "the nation of Philistine"], ["ou te faaumatia oe,", "I destroyed you"], ["e iu", "to attain"], ["ina leai", "let no"], ["se nofo ai.", "a dwell"]]},
  {num:6,words:[["E avea foi nuu tu matafaga", "to become also nation stand shore"], ["ma lotoā", "and court"], ["a manu,", "but animal"], ["ma vaieli o", "and well of"], ["e leoleo manu,", "to guard animal"], ["ma lotoā mamoe.", "and court sheep"]]},
  {num:7,words:[["E avea foi", "to become also"], ["le nuu", "the nation"], ["mo e o totoe", "for by of phiral of foe"], ["o le aiga o Iuta,", "the family of Judas"], ["latou te aai ai;", "they city"], ["o le afiafi latou", "the evening they"], ["te taooto ai", "lie down"], ["i fale o Asekelona;", "in house of Asekelona"], ["auā e asiasi Ieova lo latou Atua", "for to spy out the LORD their God"], ["ia te", "unto"], ["i latou", "them"], ["ma faafoisia mai la latou tafeaga.", "and restored from their exiles in wa^"]]},
  {num:8,words:[["Ua ou faalogo atu", "I hearken"], ["i le faifai", "in the to become"], ["mai a Moapi,", "from of Moab"], ["ma le faaleaga", "and the to abuse"], ["mai a le fanauga", "from but the children"], ["a Amoni,", "of Ammon"], ["ua latou faifai", "they to become"], ["mai ai", "from"], ["i lo'u nuu,", "in my nation"], ["ma latou faamaualuluga", "and they faamaualuluga"], ["mai ai", "from"], ["i lo latou tuaoi.", "in the they border"]]},
  {num:9,words:[["O le mea lea,", "therefore"], ["o loo faapea", "saying"], ["mai ai Ieova o 'au", "from the LORD of I"], ["le Atua o Isaraelu,", "God Israel"], ["Ou te ola a'u,", "I life I"], ["e avea lava Moapi pei", "to become indeed Moab like"], ["o Sotoma,", "Sodom"], ["o le fanauga", "the children"], ["a Amoni foi pei o Komoro,", "of Ammon also like of Gomorrah"], ["o le mea e", "the thing by"], ["i ai", "therein"], ["le vao ogoogo,", "the vegetation ogoogo"], ["ma lua o masima,", "and two of salt"], ["o le mea gaogao foi", "the thing void also"], ["e faavavau;", "forever/everlasting"], ["o e o totoe", "who phiral of foe"], ["o lo'u nuu latou", "my nation they"], ["te vetea", "vetea"], ["i latou,", "them"], ["o e totoe foi", "who phiral of foe also"], ["o o'u tagata latou", "my man they"], ["te fai", "make"], ["i latou", "them"], ["mo i latou lava.", "for them indeed"]]},
  {num:10,words:[["E oo lea mea ia te", "it shall come to pass thing unto"], ["i latou", "them"], ["ona o lo latou faamaualuluga,", "because of their faamaualuluga"], ["auā na latou faifai", "for they to become"], ["ma faamaualuga", "and to be proud"], ["i le nuu o Ieova", "in the land the LORD"], ["o 'au.", "I"]]},
  {num:11,words:[["E matautia Ieova e", "to fearful the LORD by"], ["i latou;", "them"], ["au? na te faaumatia atua uma", "I he destroyed God all"], ["o le lalolagi;", "the earth"], ["e ifo tagata ia te ia", "by down man to him"], ["taitasi i le mea", "each in the thing"], ["e nofo ai,", "to dwell"], ["o nuu tumatafaga uma o nuu ese.", "nation mariUBM all of nation away"]]},
  {num:12,words:[["Outou Aitiope foi", "you (all) Aitiope also"], ["e fasiotia outou", "to slain you (all)"], ["i la'u pelu.", "in my a sword"]]},
  {num:13,words:[["Na te faaloaloa atu foi lona aao", "he to stretch out also his hand (extended)"], ["i le itu", "on the side"], ["i matu,", "northward"], ["ma faaumatia Asuria;", "and destroyed Assyria"], ["e fai foi e ia", "to make also by him"], ["o Nineva", "Nineveh"], ["ma mea gaogao,", "and thing void"], ["o le nuu naumati pei", "the nation dry like"], ["o le vao.", "the vegetation"]]},
  {num:14,words:[["E taooto foi", "to lie down also"], ["i ai lafu o manu vaefa uma", "therein herd of beast all"], ["o nuu ese;", "nation away"], ["o le kati", "the kati"], ["ma le kifota la te momoe", "and the kifota la lie down"], ["i tumutumu", "in top"], ["o ona pou;", "then pillar"], ["e tagi", "to cry"], ["le leo o manu", "the voice of animal"], ["i faamalama,", "in heathen customs (as"], ["e gaogao faitotoa;", "to void door"], ["auā e aliali mea", "for to to appear thing"], ["ua fai", "make"], ["i arasi.", "in cedar"]]},
  {num:15,words:[["O le aai mitamita lena", "the city to boast that"], ["sa nofo faatalanoa,", "dwell faatalanoa"], ["o le", "the"], ["sa faapea ifo", "saying down"], ["i lona loto,", "in his heart"], ["O a'u lava,", "I am indeed"], ["e leai", "there is not"], ["se tasi,", "a one"], ["na o a'u;", "I am"], ["oi!", "alas ! oh !"], ["ua faapea ona", "saying and"], ["fai ma mea gaogao;", "to be thing void"], ["o le mea", "the thing"], ["e taooto ai manu feai;", "to lie down animal wild"], ["e taitasi", "by each"], ["ma uisa o", "and uisa of"], ["e ui ane ai,", "to although"], ["e tusi atu ai o latou", "to book of they"], ["lima.", "five"]]},
];
renderVerseSet(_zep_ch_2_Verses, 'zep-ch2-verses');

var _zep_ch_3_Verses = [
  {num:1,words:[["Oi talofa", "wo"], ["i le aai fouvale", "in the city to rebel"], ["ma le leaga,", "and the evil"], ["o le aai saua!", "the city to have a return of sick-"]]},
  {num:2,words:[["Na ia le faalogo", "to the hearken"], ["i le leo;", "in the voice"], ["na ia le talia", "to the received"], ["le aoaiga;", "the discipline"], ["na ia le faatuatua ia", "to the faith to"], ["Ieova,", "the LORD"], ["na ia le faalatalata atu", "to the draw near"], ["i lona Atua.", "in his God"]]},
  {num:3,words:[["O ona alii sili", "then Lord most"], ["i totonu ia te ia", "in inside to him"], ["o leona fetagisi", "lion wept"], ["i latou;", "them"], ["o ona faamasino o luko", "then a judge of wolf"], ["o le afiafi", "the evening"], ["i latou;", "them"], ["ua latou", "they"], ["le paagugu ni ivi", "the to scranch as bones some bone"], ["i le taeao.", "in the morning"]]},
  {num:4,words:[["O ana perofeta o tagata mitamita vale", "his prophet of men to boast foolish"], ["i latou", "them"], ["ma le faa'ole'ole;", "and the deceit"], ["o ana ositaulaga", "his high priest"], ["ua latou soli", "they to tread upon"], ["le malumalu,", "the temple"], ["ua latou soli", "they to tread upon"], ["le tulafono.", "the law"]]},
  {num:5,words:[["O Ieova", "the LORD"], ["le amiotonu o loo", "the righteous of"], ["i totonu ia te ia;", "in inside to him"], ["e le faia e ia", "by the made by him"], ["se amioletonu;", "a wickedness"], ["o lea taeao", "therefore morning"], ["ma lea taeao", "and morning"], ["na te faamalamalama", "he give light"], ["mai ai lana faamasinoga,", "from his judgment"], ["e le aunoa lava;", "by the without indeed"], ["a o le tagata amioletonu", "but man wickedness"], ["na te", "he"], ["le iloa mā.", "the known First person dual exclusive"]]},
  {num:6,words:[["Ua ou faaumatia nuu ese;", "I destroyed nation away"], ["ua faatafunaina o latou", "destroyed of they"], ["'olo;", "fortress"], ["ua ou faagaogaoina o latou", "I faagaogaoina of they"], ["malae,", "the"], ["ua leai", "there was not"], ["se ui ai;", "a although"], ["ua faaumatia", "destroyed"], ["a latou aai,", "but they city"], ["ua le", "not"], ["i ai", "therein"], ["se tagata,", "a man"], ["ua leai foi", "there was not also"], ["se mau ai.", "a opinion"]]},
  {num:7,words:[["Na ou fai atu,", "I said to"], ["Tau ina", "season let"], ["e mata'u mai ia te au,", "to ax from I"], ["ia e talia", "to to received"], ["le aoaiga,", "the discipline"], ["ona le faaumatia ai lea", "and the destroyed"], ["o le mea", "the thing"], ["e mau ai o ia,", "to opinion he"], ["e le oo foi", "by the oo also"], ["se mea", "a thing"], ["e tasi", "by one"], ["ua ou faasalaina atu ai", "I punished"], ["ia te ia;", "to him"], ["a ua latou ala tulai,", "but they way arose up"], ["ua latou fai ia", "they make to"], ["leaga a latou mea uma", "evil but they all things"], ["ua fai.", "make"]]},
  {num:8,words:[["O lenei,", "this"], ["ia outou faatalitali ia te au,", "to you (all) waited unto me"], ["o loo fetalai", "said"], ["mai ai Ieova,", "from the LORD"], ["ia oo", "to oo"], ["i le aso ou te tulai atu ai", "in the day I arose up"], ["i le vete;", "in the plunder"], ["auā ua tonu ia te au", "for right unto me"], ["e faapotopotoina nuu ese,", "to gathered together nation away"], ["e aofia lava malo;", "by aofia indeed government"], ["ina ia sasaa atu", "so that plurzH x)^ saasaa"], ["i luga ia", "in above to"], ["i latou lo'u ita,", "them my angry"], ["o lo'u ita tele uma", "my angry great all"], ["lava;", "indeed"], ["auā e faaumatia", "for to destroyed"], ["le lalolagi uma", "the earth all"], ["i le afi", "in the fire"], ["o lo'u fuā.", "my fuā"]]},
  {num:9,words:[["Auā o", "for of"], ["ona po ia ou te liliu atu ai", "and night to I turned"], ["i nuu", "in nation"], ["o le gagana lelei,", "the language good"], ["ina ia latou valaau uma", "so that they call all"], ["lava i le suafa o Ieova,", "indeed in the name the LORD"], ["ma auauna ia te ia", "and servant to him"], ["ma le loto gatasi.", "and the heart gatasi"]]},
  {num:10,words:[["O i tala atu o vaitafe", "in side of river"], ["o Aitiope e au", "Aitiope to I"], ["mai ai", "from"], ["le taulaga ia te au", "the offering unto me"], ["e o'u tagata o ole", "to my man of entreat"], ["mai,", "from"], ["o le afafine lava", "the daughter indeed"], ["o o'u tagata", "my man"], ["ua faasalalauina.", "faasalalauina"]]},
  {num:11,words:[["O lea aso", "therefore day"], ["e te", "by"], ["le mā ai", "the First person dual exclusive"], ["ona o sau amioga", "because of come amioga"], ["e tasi", "by one"], ["ua e fouvale ai ia te au;", "to to rebel unto me"], ["auā o", "for of"], ["ona po ia ou te aveeseina ai", "and night to I carried away"], ["i totonu ia te oe", "in inside unto you"], ["o i latou", "them"], ["o ia te oe", "he you"], ["o e mitamita faamaualuga;", "who to boast to be proud"], ["ona e le toe faamaualuga ai lea", "and by the again to be proud"], ["i lo'u mauga paia.", "in my mountain holy"]]},
  {num:12,words:[["Ou te faatotoe", "I faatotoe"], ["i totonu ia te oe", "in inside unto you"], ["o le nuu agamalu", "the nation meek"], ["ma le mativa,", "and the want"], ["latou te faatuatua foi", "they faith also"], ["i le suafa o Ieova.", "in the name the LORD"]]},
  {num:13,words:[["O e totoe o Isaraelu latou", "who phiral of foe of Israel they"], ["te le faia amioletonu,", "the made wickedness"], ["latou te", "they"], ["le tala pepelo foi;", "the side false also"], ["e le iloa foi", "by the known also"], ["i o latou gutu", "in of they mouth"], ["le laulaufaiva faa'ole'ole;", "the tongue deceit"], ["a e latou te aai,", "but by they city"], ["ma taooto,", "and lie down"], ["e leai foi", "there is not also"], ["se faamatau mai.", "a faamatau from"]]},
  {num:14,words:[["Le tama fafine", "the child woman"], ["a Siona", "of Zion"], ["e,", "by"], ["ia e pese.", "to to a song"], ["Isaraelu e,", "Israel by"], ["ia e alaga;", "to to cry"], ["le tama fafine", "the child woman"], ["a Ierusalema", "of Jerusalem"], ["e,", "by"], ["ia e fiafia,", "to to competition"], ["ma olioli lava", "and rejoice indeed"], ["ma le loto atoa.", "and the heart together with"]]},
  {num:15,words:[["Ua faaolaina", "saved alive"], ["e Ieova au sala,", "the LORD I a fine"], ["ua na aveeseina", "carried away"], ["le na fai oe", "the make you"], ["ma ona fili;", "and then to choose"], ["o le Tupu o Isaraelu,", "the king of Israel"], ["o Ieova,", "the LORD"], ["o loo", "o loo"], ["i ai o ia", "therein he"], ["i totonu ia te oe,", "in inside unto you"], ["e te", "by"], ["le toe iloa ai", "the again known"], ["se malaia.", "a disaster"]]},
  {num:16,words:[["O lea aso", "therefore day"], ["o le a faapea atu ai", "what thus"], ["i Ierusalema,", "in Jerusalem"], ["Aua e te fefe;", "for by get scared"], ["Siona e,", "Zion by"], ["aua ne'i vaivai ou lima.", "for now weak I five"]]},
  {num:17,words:[["O Ieova lou Atua", "the LORD your God"], ["i totonu ia te oe", "in inside unto you"], ["o l? malosi ia;", "l strong to"], ["na te faaolaina;", "he saved alive"], ["e olioli o ia", "to rejoice he"], ["ia te oe", "unto you"], ["ma le fiafia;", "and the competition"], ["o lona alofa", "his love"], ["e le fetalai ai o ia;", "by the said he"], ["e olioli lava o ia", "to rejoice indeed he"], ["ia te oe", "unto you"], ["ma le ofo fiafia.", "and the n competition"]]},
  {num:18,words:[["Ou te faapotopotoina", "I gathered together"], ["i latou", "them"], ["ua faanoanoa", "to mourn"], ["ona o tausamiga,", "because of feast"], ["(o ou tagata", "I man"], ["i latou,)", "them"], ["ua mafatia", "the distribution of pro-"], ["i le luma", "in the before"], ["ona o ia.", "because of to"]]},
  {num:19,words:[["Faauta,", "behold"], ["o ona po ia", "then night to"], ["ou te faatiga ai ia te", "I a unto"], ["i latou uma o", "them all of"], ["e faasaua ia te oe;", "to to be oppressive unto you"], ["ou te faaolaina foi", "I saved alive also"], ["le ua setusetu,", "the setusetu"], ["ou te faapotopotoina foi", "I gathered together also"], ["le ua tulia,", "the driven away"], ["ou te avatu foi ia te", "I give away also unto"], ["i latou", "them"], ["le viiga", "the praise"], ["ma le igoa", "and the name"], ["i nuu uma lava", "in nation all indeed"], ["sa faamāina ai", "faamāina"], ["i latou.", "them"]]},
  {num:20,words:[["O ona po ia", "then night to"], ["ou te au", "I I"], ["mai ai outou,", "from you (all)"], ["o ona po foi lava ou te faapotopotoina ai outou;", "then night also indeed I gathered together you (all)"], ["ou te avatu ai lava", "I give away indeed"], ["ia te outou", "unto you"], ["le igoa", "the name"], ["ma le viiga", "and the praise"], ["i nuu uma", "in nation all"], ["o le lalolagi,", "the earth"], ["pe a ou faafoisia la outou tafeaga,", "whether but I restored your exiles in wa^"], ["o outou", "you (all)"], ["o vaai", "to look at"], ["i ai,", "therein"], ["o loo fetalai", "said"], ["mai ai Ieova.", "from the LORD"]]},
];
renderVerseSet(_zep_ch_3_Verses, 'zep-ch3-verses');

})();